### PR TITLE
Revert "Scope parameter in Oauth 2.0 token exchange"

### PR DESCRIPTION
**Pull request by jonasvoelcker**
This reverts commit ba8c22eaf01290b0f850c297c11206d63f7179d2.

It will solve issue #29614

### CODE REVIEW

**Comment by mposolda** [comment]
@jonasvoelcker Thanks for the PR, but I don't think that just reverting the previously done work is the way to go. We may need to keep supporting `scope` parameter in token-exchange as it is supposed to be supported there.

@cgeorgilakis Since you are the author of the original commit for #21578, could you check what should be the behaviour here according to the token-exchange specification and whether the bug is even valid?

**Comment by jonasvoelcker** [comment]
Hi @mposolda,

I've made some checks and answered within the issue: https://github.com/keycloak/keycloak/issues/29614

**Comment by cgeorgilakis** [comment]
I have commented in [issue](https://github.com/keycloak/keycloak/issues/29614).
I believe we firstly need to clear business there.

**Review by stianst — CHANGES_REQUESTED** [review]
Reverting the changes is not the way to go, as there has to be some control over what scopes are permitted. How it behaves currently is a better of two evils, as it does at least provide some level of control on what scopes are permitted in an exchange.

For a proper solution we essentially need a mechanism to not only say which clients can exchange to a given client, but also what scopes are permitted.

See my comment here for more details:
https://github.com/keycloak/keycloak/issues/29614#issuecomment-2367320348

For now I will close this PR, but as part of making token exchange supported we need to address this problem properly.

**Pull request closed without merging**
