### PR TITLE
KEYCLOAK-11991 Simplify conditions in module core

### PR DESCRIPTION
**Pull request by Captain1653**
I have found some conditions which (I suppose) can be simplified.

P.S. Should I have issue for this PR?

### CODE REVIEW

**Comment by Captain1653** [comment]
I have one failed test on TESTS=server-group4:
RefreshTokenTest.tokenRefreshRequest_ClientES512_RealmRS256:1013->conductTokenRefreshRequest:1057->refreshToken:1110 » Runtime . 
Can you help me with this exception?:
Caused by: org.keycloak.common.VerificationException: Token not set 

Was it my mistake or I don't know something?

**Comment by stianst** [comment]
Hi thanks for your PR. However, it looks like you're not actually trying to resolve any real issues, rather just refactoring code. Although I agree that your changes is a nicer way to write it what is already there is perfectible valid. As such I would rather not include this as there is always a chance it introduces a regression.

**Review by stianst — CHANGES_REQUESTED** [review]
I'm not in favour of merging this as there are chances of it introducing regressions. Unless there are some actual issues being resolved here.

**Comment by Captain1653** [comment]
@stianst Thanks . I understood your reasons. You are completely right. I'll close this PR, but, honestly. It's little strage to see failed test after this refactoring.

**Comment by Captain1653** [comment]
@stianst I'm sorry. It was my fault. Now build is "green"

**Comment by stianst** [comment]
We had some stability issues in RefreshTokenTest. It should be fixed now.

**Comment by stianst** [comment]
Closing this as I think it's a bit to heavy on the refactoring, so could introduce a regression and the current code is okay.

**Pull request closed without merging**
