### PR TITLE
Deleted authentication sessions should not be re-surrected with an update

### LINKED ISSUE #31829: Deleted authentication sessions should not be re-surrected with an update
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

The issue #31699 changed the behavior that a a replace operation could supersede a previous delete operation for an authentication session. 

This issue will revert back to the original behavior.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

A previously removed authentication session should not be resurrected by a a later replace.

### Actual behavior

A replace overwrites a previous delete or tombstone.

### How to Reproduce?

The test case `AppInitiatedActionResetPasswordTest#resetPassword` can be used to show the behavior. 

A call to `removeAuthenticationSessionByTabId` will remove the root authentication session. Later, an `authSession.removeAuthNote()` will try to trigger an update, which should not overwrite the update.

### Anything else?

I'll create a PR to revert to the original behavior.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #31829

### CODE REVIEW

**Comment by ahus1** [comment]
@mhajas - please give this PR a review when you have the time. Thanks!

**Review by mhajas — DISMISSED** [review]
@ahus1 Thank you for the PR. Can we introduce a test for this scenario to make sure we have something that fails when this happens again?

**Comment by ahus1** [comment]
@mhajas - I've ammended an existing test case, please review. Thanks!

**Comment by ahus1** [comment]
This might be the performance regression we've seen in KCB in issue https://github.com/keycloak/keycloak-benchmark/issues/901

**Review by pruivo — APPROVED** [review]
I had to spend some time with the debugger to understand the problem. It LGTM :+1:

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
