### PR TITLE
Fixes using wrong db when using import or export command

### LINKED ISSUE #11767: Inconsistent configuration settings for `start` and `import` commands
### Describe the bug

When starting a pre-augmented Keycloak instance configuration is picked up differently in between the `start` and the `import` command.

Reproducer:

- Build a container `test-custom-keycloak` from a `Dockerfile` as follows ( `docker build . -t test-custom-keycloak` ):
```Dockerfile
FROM quay.io/keycloak/keycloak:18.0.0
RUN /opt/keycloak/bin/kc.sh build --db=postgres --health-enabled=true
```
- the `start` commands:
```bash
docker run --rm -e KC_DB=postgres -e KC_DB_URL_HOST=foo test-custom-keycloak start --hostname-strict=false
```
and
```bash
docker run --rm -e KC_DB_URL_HOST=foo test-custom-keycloak start --hostname-strict=false
```
returns the expected result:
```
java.net.UnknownHostException: foo
```
- instead the `import` command:
```bash
docker run --rm -e KC_DB=postgres -e KC_DB_URL_HOST=foo test-custom-keycloak import --dir=/tmp
```
returns the expected result:
```
java.net.UnknownHostException: foo
```
but the command:
```bash
docker run --rm -e KC_DB_URL_HOST=foo test-custom-keycloak import --dir=/tmp
```
fails with:
```
Connection to localhost:5432 refused.
```
meaning that the option `KC_DB_URL_HOST` has been ignored.

The expected result is that the last command fails to try to resolve `foo` as the rest.

### Version

18.0.0

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### LINKED ISSUE #11902: Keycloak.X 18.0.0 - export/import in container does not work as expected
### Describe the bug

Docker image is created as:
```
ARG KEYCLOAK_VERSION="18.0.0"
FROM quay.io/keycloak/keycloak:${KEYCLOAK_VERSION} as builder

ENV KC_CACHE_STACK=kubernetes
ENV KC_DB=mysql
ENV KC_HTTP_RELATIVE_PATH=/auth
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

RUN /opt/keycloak/bin/kc.sh build --db=mysql --transaction-xa-enabled=false

# Runtime image
ARG KEYCLOAK_VERSION="18.0.0"
FROM quay.io/keycloak/keycloak:${KEYCLOAK_VERSION} as runtime
COPY --from=builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
WORKDIR /opt/keycloak
```

If I run this image, and set environment variables:
```
JAVA_OPTS_APPEND="-Djgroups.dns.query=..."
KC_HOSTNAME_STRICT=false
KC_HOSTNAME_STRICT_HTTPS=false
KC_HTTP_PORT=8080
KC_HTTP_ENABLED=true
KC_DB_URL_DATABASE=keycloak_test
KC_DB_URL_HOST=xxx
KC_DB_USERNAME=xxx
KC_DB_USERNAME=xxx
```
and run:
```
./bin/kc.sh start
```
then the server starts fine, and connects to mysql database that I've configured.

If I run:
```
./bin/kc.sh export --dir ./export
```
then the server does not start and exception is thrown:
```
Appending additional Java properties to JAVA_OPTS: -Djgroups.dns.query=localhost
2022-05-09 08:15:32,097 WARN  [io.agroal.pool] (main) Datasource '<default>': Driver does not support the provided URL: jdbc:h2:file:/opt/keycloak/bin/..//data/h2/keycloakdb;;AUTO_SERVER=TRUE
2022-05-09 08:15:32,263 WARN  [io.quarkus.runtime.configuration.ConfigRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.datasource.jdbc.driver is set to 'com.mysql.cj.jdbc.Driver' but it is build time fixed to 'org.h2.Driver'. Did you change the property quarkus.datasource.jdbc.driver after building the application?
 - quarkus.http.root-path is set to '/auth' but it is build time fixed to '/'. Did you change the property quarkus.http.root-path after building the application?
2022-05-09 08:15:32,555 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
2022-05-09 08:15:32,694 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Driver does not support the provided URL: jdbc:h2:file:/opt/keycloak/bin/..//data/h2/keycloakdb;;AUTO_SERVER=TRUE
2022-05-09 08:15:32,696 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: Driver does not support the provided URL: jdbc:h2:file:/opt/keycloak/bin/..//data/h2/keycloakdb;;AUTO_SERVER=TRUE
        at io.agroal.pool.ConnectionFactory.connectionSetup(ConnectionFactory.java:226)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:210)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

2022-05-09 08:15:33,292 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Driver does not support the provided URL: jdbc:h2:file:/opt/keycloak/bin/..//data/h2/keycloakdb;;AUTO_SERVER=TRUE
2022-05-09 08:15:33,395 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-05-09 08:15:33,422 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-05-09 08:15:33,433 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-05-09 08:15:33,579 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final
2022-05-09 08:15:33,684 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2022-05-09 08:15:33,684 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2022-05-09 08:15:33,780 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2022-05-09 08:15:33,780 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
2022-05-09 08:15:33,781 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2022-05-09 08:15:33,781 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
2022-05-09 08:15:35,799 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) c5cf5e52c0c1-35457: no members discovered after 2006 ms: creating cluster as coordinator
2022-05-09 08:15:35,810 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [c5cf5e52c0c1-35457|0] (1) [c5cf5e52c0c1-35457]
2022-05-09 08:15:35,816 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `c5cf5e52c0c1-35457`, physical addresses are `[10.0.2.100:44606]`
2022-05-09 08:15:36,413 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2022-05-09 08:15:36,531 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2022-05-09 08:15:36,532 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
2022-05-09 08:15:36,532 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Driver does not support the provided URL: jdbc:h2:file:/opt/keycloak/bin/..//data/h2/keycloakdb;;AUTO_SERVER=TRUE
2022-05-09 08:15:36,533 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

As a workaround, if I pass --auto-build to the export command:
```
./bin/kc.sh export --dir ./export --auto-build
```
then the server starts, performs the export successfully, but the script exits with error code, and message of unsupported flag --auto-build:
```
Appending additional Java properties to JAVA_OPTS: -Djgroups.dns.query=localhost
Changes detected in configuration. Updating the server image.
2022-05-09 08:16:30,160 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
2022-05-09 08:16:30,727 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-05-09 08:16:30,759 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-05-09 08:16:30,774 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-05-09 08:16:30,931 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final
2022-05-09 08:16:31,028 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2022-05-09 08:16:33,131 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) c5cf5e52c0c1-61054: no members discovered after 2003 ms: creating cluster as coordinator
2022-05-09 08:16:33,140 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [c5cf5e52c0c1-61054|0] (1) [c5cf5e52c0c1-61054]
2022-05-09 08:16:33,144 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `c5cf5e52c0c1-61054`, physical addresses are `[10.0.2.100:7800]`
2022-05-09 08:16:33,567 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: c5cf5e52c0c1-61054, Site name: null
2022-05-09 08:16:33,841 INFO  [org.keycloak.exportimport.dir.DirExportProvider] (main) Exporting into directory /opt/keycloak/./export
2022-05-09 08:16:50,203 INFO  [org.keycloak.services] (main) KC-SERVICES0033: Full model export requested
2022-05-09 08:16:59,924 INFO  [org.keycloak.exportimport.dir.DirExportProvider] (main) Realm 'master' - data exported
2022-05-09 08:17:01,536 INFO  [org.keycloak.exportimport.dir.DirExportProvider] (main) Users 0-0 exported
2022-05-09 08:17:01,701 INFO  [org.keycloak.services] (main) KC-SERVICES0035: Export finished successfully
2022-05-09 08:17:02,380 INFO  [io.quarkus] (main) Keycloak 18.0.0 on JVM (powered by Quarkus 2.7.5.Final) started in 34.612s. Listening on: http://0.0.0.0:8080
2022-05-09 08:17:02,381 INFO  [io.quarkus] (main) Profile import_export activated.
2022-05-09 08:17:02,381 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]
2022-05-09 08:17:02,428 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2022-05-09 08:17:02,484 INFO  [io.quarkus] (main) Keycloak stopped in 0.100s
Unknown option: '--auto-build'
Try 'kc.sh export --help' for more information on the available options.
```

The same issue is present for `import` as well.

### Version

18.0.0

### Expected behavior

The export should work the same as start. It seems that the properties with which the quarkus distribution is built (mysql database) are not respected in export/import and export/import process still sees default h2 database configuration.

### Actual behavior

The export/import fails

### How to Reproduce?

Follow the steps from bug description

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DGuhr**
Closes #11902
Closes #11767

### CODE REVIEW

**Review by andreaTP — DISMISSED** [review]
LGTM

**Review by andreaTP — APPROVED** [review]

**Review by pedroigor — COMMENTED** [review]
@DGuhr I think it is a fair assumption that import/export should always run in runtime mode. You probably have a pre-configured server if you are running import/export.

I'll run your PR and do some local tests too.

The only thing I'm not sure is the test. Why we can't have the test similar to how we are running the database tests?

**Comment by pedroigor** [comment]
@DGuhr After looking at this one in more detail, I noticed that the issue is somewhere else. Please, see https://github.com/keycloak/keycloak/issues/12156.

I also tried to simplify the tests a bit so that we don't need to introduce a new dependency but just leverage the existing code to run database tests. The export/import tests should also run for all the databases we are testing too (instead of running only `postgres`).

Please, let me know if my [changes](https://github.com/keycloak/keycloak/pull/12157) makes sense for you and if you want to incorporate them into this PR. Otherwise, I can also send a new PR.

**Comment by abstractj** [comment]
@pedroigor please correct me if I'm wrong, but it seems that the changes proposed here were superseded by https://github.com/keycloak/keycloak/pull/12157. Is that correct? If yes, I believe it's safe to close this PR.

**Comment by abstractj** [comment]
@DGuhr closing it based on @pedroigor's comments.

**Pull request closed without merging**
