### PR TITLE
Added support to indicate desired locale on login options

### PR DESCRIPTION
**Pull request by ramirost**
Added support through options to indicate the desired locale on login calls

### CODE REVIEW

**Comment by stianst** [comment]
Thanks, for the PR. A few things to sort out before we can merge:
* Need associated JIRA issue
* It should use ui_locales query parameter, not kc_locale

**Comment by stianst** [comment]
Saw the JIRA issue now, so that's sorted.

**Comment by ramirost** [comment]
I changed the query parameter name.

Drawing your attention... Which is the right procedure to add a new language to the official release of keycloak, just a JIRA issue and a pull request with the new language files? I would like to have it translated to Spanish, and I can contribute with the translations.

**Comment by ramirost** [comment]
Sorry I forgout to update the documentation, I just added the parameter in the third commit

**Comment by ramirost** [comment]
ok, Stian, I'll do it when I have the first version of the files, because we need it for us, and we plan to update also the translation.

**Pull request merged**
