### PR TITLE
Add Foresight status badge to README

### PR DESCRIPTION
**Pull request by rwxdash**

### CODE REVIEW

**Comment by stianst** [comment]
Nice. Looking at it at the moment it's not 100% clear what the badge is showing.

image

A few questions:
* Is this considering only non-PR runs? 
* Is the test number based on the total number of unique tests that has been run? 
* A bit curious why it looks good, as at the moment our testsuite is quite broken. 
* What is the number 115?

Would also be ideal if the link is to a page on our public Foresight URL, which shows the relevant information with more details.

**Comment by stianst** [comment]
Looking at https://docs.runforesight.com/how-to/badges I think maybe the 'Successful Tests Badge' might be better, would need it to exclude PR runs though, so latest test results from either push or schedule events.

**Comment by serkan-ozal** [comment]
Hi @stianst,

Answers are inline:
> Is this considering only non-PR runs?

Yes, test results are only collected from `main` branch in `KeyCloak CI` workflow.

> Is the test number based on the total number of unique tests that has been run?

Results don't reflect unique test counts but sum of all executed tests from all jobs. So if the same test is executed multiple times at different jobs, since they are different test executions, it is counted multiple times.

> A bit curious why it looks good, as at the moment our testsuite is quite broken.

We made a fix on our side, so it should be OK now.

> What is the number 115?

Count of ignored/skipped tests.

**Comment by serkan-ozal** [comment]
Hi @stianst, 
How we should process on this PR?

**Comment by stianst** [comment]
Closing since sadly Thundra is no more:
image

**Pull request closed without merging**
