### PR TITLE
[KEYCLOAK-12463] Missing consents on Applications Endpoint

### PR DESCRIPTION
**Pull request by douglaspalmer**

### CODE REVIEW

**Review by abstractj — CHANGES_REQUESTED** [review]
@douglaspalmer I manually checked it and it works as before, thanks for the fix.

We need to update the commit message. I created a new Jira https://issues.redhat.com/browse/KEYCLOAK-12463 because it's a bug and KEYCLOAK-5628 was already merged and resolved.

To prevent regressions in the future and if technically possible we need to create tests to check if the endpoint will return the consents when granted on apps.

**Comment by abstractj** [comment]
@douglaspalmer quoting @vmuzikar on the alternatives for testing this:

> 1. use a test app deployment as we do in adapter tests and login to this app – but this solution could be overly complicated
> 2. set consentRequired for the account console client – it's a bit nasty workaround but it should work (I usually test consents this way :D)
> 2. create a client for non-existing app and directly add consents to the user (you'd probably need to directly access Models from the tests, but it should be possible with runOnServer) – you don't need to test the consents as such (with the login screen etc.), you just want to test if the consents are correctly displayed in the console

**Comment by vmuzikar** [comment]
@douglaspalmer When I was discussing this with @abstractj , I thought he's speaking about the UI tests. Because this is a REST API test, option 2 is not really usable. IMHO the best way would be to use option 3. You should be able to sort of mock the consent by calling [UserProvider.addConsent](https://github.com/keycloak/keycloak/blob/118b413152c0e2a234ae55db5dd6f0cdded621b4/server-spi/src/main/java/org/keycloak/models/UserProvider.java#L48) using testing client like e.g. [here](https://github.com/keycloak/keycloak/blob/118b413152c0e2a234ae55db5dd6f0cdded621b4/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserConsentModelTest.java#L54-L56).

**Comment by abstractj** [comment]
> @douglaspalmer When I was discussing this with @abstractj , I thought he's speaking about the UI tests. Because this is a REST API test, option 2 is not really usable. IMHO the best way would be to use option 3. You should be able to sort of mock the consent by calling [UserProvider.addConsent](https://github.com/keycloak/keycloak/blob/118b413152c0e2a234ae55db5dd6f0cdded621b4/server-spi/src/main/java/org/keycloak/models/UserProvider.java#L48) using testing client like e.g. [here](https://github.com/keycloak/keycloak/blob/118b413152c0e2a234ae55db5dd6f0cdded621b4/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserConsentModelTest.java#L54-L56).

@vmuzikar apologies about the confusion!

**Review by abstractj — APPROVED** [review]

**Comment by abstractj** [comment]
@vmuzikar I did run the tests provided by Doug and also checked it manually. They look good and we can always iterate if we manage to find more scenarios.

Thanks for your help on this.

**Pull request merged**
