### PR TITLE
Clean up language names in messages_<lang>.properties

### LINKED ISSUE #19442: Translations files contain duplicate information (name of other languages)
### Description

I've noticed that some of the translation files contain a list of languages in the original language name. 

For example `locale_fi=Suomi` is added to several messages_<lang>.properties files. 

It should not be necessary to have this duplicate information in the translation files when Keycloak can pick it up from the default/fallback `messages_en.properties` file

### Discussion

_No response_

### Motivation

_No response_

### Details

We could remove those extraneous translations from all translation files making Keycloak messages files easier to keep up to date.

### PR DESCRIPTION
**Pull request by badrange**
Fixes #19442 for login theme.

### CODE REVIEW

**Comment by stianst** [comment]
@ahus1 could you take a look at this one?

**Review by ahus1 — APPROVED** [review]
Thank you for this cleanup. I rebased the change and resolved some conflicts. Once the CI completes this is ready to be merged.

**Comment by ahus1** [comment]
Hi @badrange - once this PR has been merged, I'd be happy to review additional pull requests to clean up other languages and themes. Please mention me on the pull requests and I'll have a look. Thanks!

**Comment by ahus1** [comment]
@badrange - would it make sense to move the language names to a separate file to avoid the confusion that they should not be translated?

**Comment by badrange** [comment]
Hi @ahus1 Thanks for merging this!

Yes it definitely makes sense for me to have these in a separate file.

**Comment by ahus1** [comment]
@badrange - if you want to give it a try to refactor this, I'm happy to discuss or review that.

**Pull request merged**
