### PR TITLE
KEYCLOAK-13281 changed to export one instance

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Review by stianst — CHANGES_REQUESTED** [review]
Is this actually causing any real issues? The current admin console is going to be replaced with a new version this year, so I really don't understand why we are making this refactoring now?

**Comment by edewit** [comment]
@stianst this is a small refactor on the new console

**Comment by stianst** [comment]
Ok, so reason why I'm commenting is that it was opened as a bug, and the compoment was set to admin console

**Comment by edewit** [comment]
@stianst ooops, sorry about that

**Comment by ssilvert** [comment]
@edewit As we discussed, this will be incorporated into the snowpack changes.  I'll leave it on hold for now though.

**Comment by stianst** [comment]
@ssilvert if this PR is abandoned and will be replaced by Snowpack please close this

**Comment by edewit** [comment]
superseded by #6994

**Pull request closed without merging**
