### PR TITLE
only render the `multi-input` when no input type

### LINKED ISSUE #24318: User attribute array data gets stored as comma-separated value if no specific input type annotation present
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When a user attribute value contains multiple values and no annotation is set to render it as multi-value field, it is rendered as text field with comma-separated string. Editing this string causes the comma separated string value to be stored.
The original array of values is replaced with a single value.

screen-record

### Version

22.0.5

### Expected behavior

The attribute with multipe-values should not get lost.

### Actual behavior

A comma separated string is stored.

### How to Reproduce?

1) Store multiple values in an attribute of a user, e.g. by 

 - configuring input type 'multiselect'
 - update a user and add two values
 - remove input type annotation

2) Update the user. The input is rendered as simple text field.

image

3) Add an entry as if you would believe it should be done (",newentry") and save the user

### Anything else?

This bug may cause accidental data corruption by Admins.

Thought that this bug was already reported and fixed in #20837. 
Maybe it was re-introduced with #23911?

### PR DESCRIPTION
**Pull request by edewit**
fixes: #24318

### CODE REVIEW

**Comment by jonkoops** [comment]
@edewit I suspect that #24359 fixes this issue as well.

**Review by ssilvert — APPROVED** [review]
LGTM

**Review by ssilvert — CHANGES_REQUESTED** [review]
@edewit I approved this before seeing @jonkoops comment about the other PR.

Please determine if the two are logically equivalent.

**Comment by jonkoops** [comment]
Got confirmation that the other PR fixes the same issue https://github.com/keycloak/keycloak/pull/24359#issuecomment-1785132258. @edewit should we close this PR, and perhaps you can do a review of the other PR?

**Comment by jonkoops** [comment]
Discussed this with the team and we're closing this PR in favor of #24359.

**Pull request closed without merging**
