### PR TITLE
fix rewriting history 

### LINKED ISSUE #19543: Browser history gets corrupted when using keycloak-js adapter
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/javascript

### Describe the bug

Login/Logout/Register methods of adapter clears current address from the history of tab. This should not happens, since clicking "Back" button should bring the user back where he came from, instead in navigates to second last address.

More deeply explained here: https://keycloak.discourse.group/t/back-button-issue-in-browser-from-cloak-page/5020

### Version

20

### Expected behavior

Clicking browser "Back" button on the Login or Register page brings user to the page he navigated from to get to the Login/Register Page.

### Actual behavior

Clicking browser "Back" button on the Login or Register page brings user to the second last page(the one that was before the page that allowed him to navigate to keycloak Login page.

### How to Reproduce?

1. Create a keycloak server(or use existing one).
2. Create a client for standard web application.
3. Create a simple web application, install keycloak-js. Add a button to call `keycloak.login()`.
4. Open new tab, nabigate to your web application local server(or deployed server URL, doesn't matter).
5. Click the login button in your web app.
6. Wait for keycloak login page to open.
7. Click the browser "Back" button.
   image
8. Notice where it brings you.

### Anything else?

The fix and more explanation is in this PR: #19525

### PR DESCRIPTION
**Pull request by MetaMmodern**
This issue was noticed in 2021 on [Keycloak forum](https://keycloak.discourse.group/t/back-button-issue-in-browser-from-cloak-page/5020) and now it's experienced by our team using keycloak-js adapter. Clearing browser history is an unexpected behaviour, this change should fix it.

This PR is a copy of #12959. I tried to fix conflicts and instead github undone my commit so that PR closed automatically. This PR has additional fix for `register` function as well. Idk if you should do the same for `logout`, think it through.

Closes #19543

### CODE REVIEW

**Comment by MetaMmodern** [comment]
@jonkoops assign yourself here pls

**Comment by jonkoops** [comment]
I am wondering if we want to make this change from a security perspective. Ideally no information such as tokens is exposed through the browser history. Re-writing the browser history ensures that this kind of information remains hidden, to the extend that is possible.

What kind of issues does re-writing cause for your application @MetaMmodern? Do you have an example of others experiencing similar issues (as you mentioned the forums).

Also, could you create an issue to go with this PR? Thanks.

**Comment by MetaMmodern** [comment]
> 

Hi, yes I can tell you an example, but not exactly provide it because we "fixed" it in our app.

Take a simple example, we have a web application that uses keycloak as auth server and users login through keycloak.
1. User opens new tab.
2. User types in website URL, hits enter.
3. User clicks "Login in" on the website.
4. User is navigated to keycloak login page.
5. User changes his mind and clicks "Go back" button in browser.
6. User ends up on an empty tab(or his browser "home" tab with shortcuts, bookmarks, etc)

In order to fix that we had to write like this:

```js
const loginUrl = keycloak.createLoginUrl();
window.assign(loginUrl);
```

But this shouldn't be the case, it's additional code in every project that uses keycloak-js library.

Security is not a good anchor point in this question, because it affects UX and provides an unexpected behaviour(user expects to go back to the website, not to go back to his browser home screen).

Hope I made it clear, you can easily create an example for this if you need and you should be able to reproduce what I described.

**Comment by MetaMmodern** [comment]
@jonkoops here is that forum: https://keycloak.discourse.group/t/back-button-issue-in-browser-from-cloak-page/5020

**Comment by jonkoops** [comment]
I see, so this attempts to solve an edge case where the user cancels the login flow. Thanks for clarifying that, I can indeed reproduce it.

Let me take a look at what the options are here and test your fix so I can give a proper review.

**Review by jonkoops — APPROVED** [review]
I think this is a valid fix. Let's run the tests and see if everything keeps working.

**Comment by jonkoops** [comment]
Nice looks like everything works as expected, thanks for the contribution @MetaMmodern!

**Comment by MetaMmodern** [comment]
> Nice looks like everything works as expected, thanks for the contribution @MetaMmodern!

Awesome, thanks

**Pull request merged**
