### PR TITLE
KEYCLOAK-17502 Galleon based server build

### PR DESCRIPTION
**Pull request by pskopek**
New Galleon based build/distribution.
The new distribution is located at the original location distribution/server-dist/.
The original (old/legacy) is located at distribution/server-legacy-dist/.
To activate legacy distribution use -Dlegacy-dist.

https://issues.redhat.com/browse/KEYCLOAK-17502

### CODE REVIEW

**Comment by ASzc** [comment]
I'm seeing similar differences in the de-noised diff for the server configs, as was in the pre-PR source:

standalone
```diff
--- /tmp/ckmt/standalone_server-legacy-dist.xml	2021-06-16 14:09:49.012524831 -0600
+++ /tmp/ckmt/standalone_server-dist.xml	2021-06-16 14:09:49.223524673 -0600
@@ -522,6 +522,7 @@
                     <permission class-name="org.wildfly.extension.batch.jberet.deployment.BatchPermission" module="org.wildfly.extension.batch.jberet" target-name="*"/>
                     <permission class-name="org.wildfly.transaction.client.RemoteTransactionPermission" module="org.wildfly.transaction.client"/>
                     <permission class-name="org.jboss.ejb.client.RemoteEJBPermission" module="org.jboss.ejb-client"/>
+                    <permission class-name="org.jboss.ejb.client.RemoteEJBPermission" module="org.jboss.ejb-client"/>
                 </permission-set>
                 <permission-set name="login-permission">
                     <permission class-name="org.wildfly.security.auth.permission.LoginPermission"/>
```

standalone-ha
```diff
--- /tmp/ckmt/standalone-ha_server-legacy-dist.xml	2021-06-16 14:09:49.089524773 -0600
+++ /tmp/ckmt/standalone-ha_server-dist.xml	2021-06-16 14:09:49.290524623 -0600
@@ -137,7 +137,7 @@
                 <stateless>
                     <bean-instance-pool-ref pool-name="slsb-strict-max-pool"/>
                 </stateless>
-                <stateful cache-ref="distributable" default-access-timeout="5000" passivation-disabled-cache-ref="simple"/>
+                <stateful cache-ref="simple" default-access-timeout="5000" passivation-disabled-cache-ref="simple"/>
                 <singleton default-access-timeout="5000"/>
             </session-bean>
             <pools>
@@ -574,6 +574,7 @@
                     <permission class-name="org.wildfly.extension.batch.jberet.deployment.BatchPermission" module="org.wildfly.extension.batch.jberet" target-name="*"/>
                     <permission class-name="org.wildfly.transaction.client.RemoteTransactionPermission" module="org.wildfly.transaction.client"/>
                     <permission class-name="org.jboss.ejb.client.RemoteEJBPermission" module="org.jboss.ejb-client"/>
+                    <permission class-name="org.jboss.ejb.client.RemoteEJBPermission" module="org.jboss.ejb-client"/>
                 </permission-set>
                 <permission-set name="login-permission">
                     <permission class-name="org.wildfly.security.auth.permission.LoginPermission"/>

```

Domain attached
[domain.diff.txt](https://github.com/keycloak/keycloak/files/6665601/domain.diff.txt)

The duplicate `RemoteEJBPermission` in Standalone and Standalone-HA probably won't hurt, but I'm not 100% certain if it will be ignored as I think it will.

In HA only, ejb3 subsystem `cache-ref` changed from `distributable` to `simple`, this does seem to reflect a change in the default value upstream [here](https://github.com/wildfly/wildfly/blob/a9e061675ea9b3ebebfc9eb01d809f4a092ded55/ejb3/src/main/resources/subsystem-templates/ejb3.xml#L52), but I think it's still worth thinking about if we need the old default value or not? I don't know.

In Domain, there are a lot of changes:

1. For infinispan:12.0 subsystem's hibernate, `pending-puts` is a new timeout added, and at 60000 it's less than the other defined timeouts of 100000, which might be concerning, however all the values appear to be their defaults from upstream [here](https://github.com/wildfly/wildfly/blob/master/clustering/infinispan/extension/src/main/resources/subsystem-templates/infinispan.xml#L34), so we're probably ok.
2. All of the CONSOLE log handlers have been removed for all subsystems. So, the log will only be recorded as a file. I'm not able to trace the origin of this change, it doesn't appear to be upstream or any commit made to Keycloak.
3. A JDBC connection URL changes. This appears to originate in commit 452bcd8b
4. A new interface `unsecure` is defined, but it doesn't seem to be used anywhere in the rest of the config, unlike `public`, which is.
5. There are a bunch of host-excludes added at the end

I also ran one of my older tools to compare the whole distribution before and after, and it's somewhat noisy, but I don't think I see any critical problems there. I have attached it here 
[dist-diff.txt](https://github.com/keycloak/keycloak/files/6665797/dist-diff.txt)

**Review by martin-kanis — CHANGES_REQUESTED** [review]
standalone-ha mode (`./standalone.sh --server-config=standalone-ha.xml`):
There is an error in the server log after log in attempt to the admin console:
```
08:49:45,518 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-4) Uncaught server error: java.lang.NoClassDefFoundError: org/jboss/logging/Logger
	at org.keycloak.keycloak-core@14.0.0-SNAPSHOT//org.keycloak.representations.idm.RealmRepresentation.<clinit>(RealmRepresentation.java:42)
	at org.keycloak.keycloak-server-spi-private@14.0.0-SNAPSHOT//org.keycloak.models.utils.ModelToRepresentation.toRepresentation(ModelToRepresentation.java:300)
	at org.keycloak.keycloak-services@14.0.0-SNAPSHOT//org.keycloak.services.resources.admin.RealmsAdminResource.toRealmRep(RealmsAdminResource.java:105)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at org.keycloak.keycloak-server-spi-private@14.0.0-SNAPSHOT//org.keycloak.utils.StreamsUtil.throwIfEmpty(StreamsUtil.java:51)
	at org.keycloak.keycloak-services@14.0.0-SNAPSHOT//org.keycloak.services.resources.admin.RealmsAdminResource.getRealms(RealmsAdminResource.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:546)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:435)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:396)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:398)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:150)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:104)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:245)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:61)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.keycloak.keycloak-wildfly-extensions@14.0.0-SNAPSHOT//org.keycloak.provider.wildfly.WildFlyRequestFilter.lambda$doFilter$0(WildFlyRequestFilter.java:41)
	at org.keycloak.keycloak-services@14.0.0-SNAPSHOT//org.keycloak.services.filters.AbstractRequestFilter.filter(AbstractRequestFilter.java:43)
	at org.keycloak.keycloak-wildfly-extensions@14.0.0-SNAPSHOT//org.keycloak.provider.wildfly.WildFlyRequestFilter.doFilter(WildFlyRequestFilter.java:39)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
	at io.undertow.core@2.2.5.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
	at io.undertow.core@2.2.5.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at org.jboss.xnio@3.8.4.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: org.jboss.logging.Logger from [Module "org.keycloak.keycloak-core" version 14.0.0-SNAPSHOT from local module loader @531f4093 (finder: local module finder @62ef27a8 (roots: /home/mkanis/workspace/keycloak/distribution/server-dist/target/keycloak-14.0.0-SNAPSHOT/modules,/home/mkanis/workspace/keycloak/distribution/server-dist/target/keycloak-14.0.0-SNAPSHOT/modules/system/layers/keycloak,/home/mkanis/workspace/keycloak/distribution/server-dist/target/keycloak-14.0.0-SNAPSHOT/modules/system/layers/base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	... 90 more

08:49:45,526 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-4) Uncaught server error: java.lang.NoClassDefFoundError: Could not initialize class org.keycloak.representations.idm.RealmRepresentation
	at org.keycloak.keycloak-server-spi-private@14.0.0-SNAPSHOT//org.keycloak.models.utils.ModelToRepresentation.toRepresentation(ModelToRepresentation.java:300)
	at org.keycloak.keycloak-services@14.0.0-SNAPSHOT//org.keycloak.services.resources.admin.RealmsAdminResource.toRealmRep(RealmsAdminResource.java:105)

08:49:45,531 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-4) Uncaught server error: java.lang.NoClassDefFoundError: Could not initialize class org.keycloak.representations.idm.RealmRepresentation
	at org.keycloak.keycloak-server-spi-private@14.0.0-SNAPSHOT//org.keycloak.models.utils.ModelToRepresentation.toRepresentation(ModelToRepresentation.java:300)
	at org.keycloak.keycloak-services@14.0.0-SNAPSHOT//org.keycloak.services.resources.admin.RealmsAdminResource.toRealmRep(RealmsAdminResource.java:105)
```
domain mode (`./domain.sh --host-config=host-master.xml`) doesn't start up properly (only 80 of 81 services are started)

Regarding GHA failure `Failed to resolve artifact xalan:xalan:jar:2.7.1.jbossorg-4`: This is reproducible locally if you delete the artifact in your local repo and run `mvn clean install -nsu -e -DskipTests -Pquarkus,distribution`. The artifact is deployed at `https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/` which is probably not defined somewhere in a pom.xml.

**Comment by martin-kanis** [comment]
One more thing. The legacy packaging also produce tar.gz archive which is needed on the Keycloak website.

**Comment by ASzc** [comment]
Checked latest commit, config seem similar

**Comment by martin-kanis** [comment]
Thanks Peter for addressing my comments. Few more things with the latest changes:

- missing /appclient/* in galleon dist
- missing /bin/appclient.* in galleon dist
- missing WARNINGS at the beginning of /bin/migrate-standalone-ha.cli and /bin/migrate-standalone.cli files in galleon dist
- missing /docs/examples/map-storage-concurrenthashmap.cli file in galleon dist

**Comment by pskopek** [comment]
Thanks for catching that Martin:

> * missing /appclient/* in galleon dist
>
This directory shouldn't exist in keycloak distribution (it is not present in older versions too)

> * missing /bin/appclient.* in galleon dist
>
The same as above, it was included by mistake

> * missing WARNINGS at the beginning of /bin/migrate-standalone-ha.cli and /bin/migrate-standalone.cli files in galleon dist
>
Fixed

> * missing /docs/examples/map-storage-concurrenthashmap.cli file in galleon dist
>
Fixed

**Comment by pskopek** [comment]
Thanks @ASzc  for the diff of configs.
I kept defaults as generated by Galleon packs from Wildfly, changes are only for Keycloak specific needs.
The `unsecure` interface has been removed.
I kept default logging subsystem settings, so no server logs in console for domain mode.
JDBC URL kept intentionally. 
It was impossible to get rid of host-excludes, but it shouldn't hurt and it is also WildFly default.

**Review by martin-kanis — APPROVED** [review]
Looks good! Thanks Peter.

**Pull request merged**
