### PR TITLE
Make sure federationLink always map to the storage provider associated with federated users

### LINKED ISSUE #31670: Make sure the storage provider ID is always available from `UserModel.getFederationLink`
### Description

When federating users from external storage they can be imported to Keycloak and be assigned with a UUID or use a specific format to their IDs when they are not imported to Keycloak and just fetched (e.g: read-only) from an external storage.

Today we have an `origin` field in the `UserRepresentation` that is set with the storage provider ID as well as the `federationLink` field that maps to the same information, the storage provider the user is linked to. This causes some confusion when handling `UserModel` instances because we now need to look at both the ID and the `federationLink` field to identify the storage provider associated with the user.

This proposal is to have the `federationLink` as the single source of truth when resolving the storage provider id associated with an user and remove boilerplate code that handles both forms of federated users.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #31670

### CODE REVIEW

**Comment by mposolda** [comment]
I think this is good change. But few additional points:

- Do we need some small note for this in the "Upgrading guide" ? As `user.getFederationLink()` will now behave slightly differently for the federated users.

- Do we need method `user.isLocal()` you introduced in the other PR? I suppose probably not?

**Comment by pedroigor** [comment]
> I think this is good change. But few additional points:
> 
> * Do we need some small note for this in the "Upgrading guide" ? As `user.getFederationLink()` will now behave slightly differently for the federated users.

Yeah, I think so. Just wanted to show what I had in mind and if it makes sense to refactor the code. I did not do I deep review of other places it might be others we want to refactor.

> * Do we need method `user.isLocal()` you introduced in the other PR? I suppose probably not?

Once we merge that one, I'll check.. But here I'm basically removing in some places the boilerplate code when using `StorageId`. But it might be useful to make things more readable...

**Comment by mposolda** [comment]
> > * Do we need method `user.isLocal()` you introduced in the other PR? I suppose probably not?
> 
> Once we merge that one, I'll check.. But here I'm basically removing in some places the boilerplate code when using `StorageId`. But it might be useful to make things more readable...

@pedroigor So that other PR https://github.com/keycloak/keycloak/pull/31631 was already merged. Considering that, it can be good to either simplify `UserModel.isLocal()` in this PR (as it possibly needs to check just for federationLink now and does not need to check for `StorageId` anymore?) or `UserModel.isLocal()` can be removed. Whatever you prefer.

**Review by edewit — DISMISSED** [review]

**Comment by pedroigor** [comment]
@mposolda I changed `UserModel.isLocal` to `UserModel.isFederated`. If we don't have this method we will end up with null checks to check whether the user is linked with an external user provider or not. For readability, checking `UserModel.isFederated` is better than `UserModel.getFederationLink() != null`.

**Review by mposolda — DISMISSED** [review]

**Review by ahus1 — APPROVED** [review]
Approving based on @mposolda's review

**Comment by ahus1** [comment]
@edewit - can you please re-approve, as @pedroigor needed to rebase the PR due to conflicts? Thanks!

**Review by edewit — APPROVED** [review]

**Pull request merged**
