### PR TITLE
KEYCLOAK-16066 Unable to build Keycloak distribution on Windows due t…

### PR DESCRIPTION
**Pull request by Pepo48**
…o io.quarkus.builder.BuildException failure

* added null check in the KeycloakProcessor.configureHibernate class

Signed-off-by: Peter Zaoral <pzaoral@redhat.com>

@mposolda (Cc: @stianst @pedroigor @iankko ) PTAL once you get a chance. Thanks!

### CODE REVIEW

**Review by mposolda — DISMISSED** [review]
@Pepo48 Thanks!

**Review by pedroigor — CHANGES_REQUESTED** [review]
@Pepo48 Could you please check if the following changes work https://github.com/pedroigor/keycloak/commit/4f9736aee6ff50e16b3ef608170ecf7e83538cf1.

I would rather prefer to make sure the dialect is always set.

**Comment by pedroigor** [comment]
Not sure though why it behaves like that on Windows. I'll check. I guess the execution of build steps changes on Windows, what may show a risk that we assumed when using some internal APIs from ORM extension.

That said, making sure we "guess" the dialect should be better than relying on not setting it.

**Comment by mposolda** [comment]
@pedroigor Just a note that from what I remember the "dialect" should be automatically auto-guessed by Hibernate based on the DB used. So question is if we need to explicitly "guess" it in our code or rather rely on Hibernate, which is likely internally doing the same?
See the docs:
https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#database-dialect
https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#portability-dialectresolver

Or is this different in case of the Quarkus integration, when it should be always preferred to "guess" the dialect in build time to avoid it being "auto-gessed" later at runtime?

**Comment by pedroigor** [comment]
The dialect will never be guessed at runtime.

Also, when using a persistence unit it is expected that you define a dialect. That was the behavior we had before but I can re-check now. So, that is the reason we force it to the persistence unit. I've added more details to the JIRA.

**Comment by pedroigor** [comment]
If you want we can just merge this one as is too. And do the change later to not block other critical tasks.

**Comment by mposolda** [comment]
@pedroigor Thanks.

@Pepo48 Do you please have a chance to try the solution from the referenced branch by @pedroigor and see if it helps with the build on Windows? Thanks!

**Comment by Pepo48** [comment]
> @Pepo48 Could you please check if the following changes work [pedroigor@4f9736a](https://github.com/pedroigor/keycloak/commit/4f9736aee6ff50e16b3ef608170ecf7e83538cf1).

Now it throws NoSuchElementException:
```[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.9.0.Final:build (default) on project keycloak-quarkus-server-app: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureHibernate threw an exception: java.util.NoSuchElementException: No value present
[ERROR]         at java.util.Optional.get(Optional.java:135)
[ERROR]         at org.keycloak.quarkus.deployment.KeycloakProcessor.configureHibernate(KeycloakProcessor.java:99)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR]         at java.lang.Thread.run(Thread.java:748)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] -> [Help 1]```

![obrázok](https://user-images.githubusercontent.com/12138171/97590382-d3c19980-19fe-11eb-9f32-a15492a8f4a4.png)

**Comment by pedroigor** [comment]
@Pepo48 I'm going to run on Windows to see what we can do. Please, let me know if we have time for that or if you want to merge this workaround to unblock you.

I'm also suspecting that this fix will only fix the build issue but it could potentially break configuring data sources other than H2 (the default).

**Comment by pedroigor** [comment]
@Pepo48 Here it is https://github.com/pedroigor/keycloak/commit/5b6ab342f9c264651df99366a3e8ec29fe0f47da. 

This one should solve the problem because we don't rely on any dependency. Could you check it out?

I'm preparing my windows box to test it. Hope I check this out before you do.

**Comment by pedroigor** [comment]
@Pepo48 And here we go again. See https://github.com/pedroigor/keycloak/tree/KEYCLOAK-14255-dialect-windows.

I've run successfully on Windows. We were looking wrongly at the classpath for the configuration properties files.

**Comment by Pepo48** [comment]
@pedroigor it looks good to me now:
obrázok
Approving :). Thanks!

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
