### PR TITLE
Arabic translation, following KEYCLOAK-9373

### PR DESCRIPTION
**Pull request by wowi42**
Arabic translation for login, account, and email themes, based on the work of @Mhmd-Ali

Continuity of #5962

### CODE REVIEW

**Comment by wowi42** [comment]
Found one more issue: emails for reset password are not working in Arabic, it seems that the encoding is off

```
Ù‚Ø§Ù… Ø£Ø­Ø¯ Ù…Ø§ Ø¨ØªØ·Ù„Ø¨ ØªØºÙŠÙŠØ± Ù…Ø¹Ù„ÙˆÙ…Ø§Øª Ø§Ù„Ø¯Ø®ÙˆÙ„ Ù„Ø­Ø³Ø§Ø¨Ùƒ Ù ÙŠ TDSchool . Ø¥Ø°Ø§ ÙƒÙ†Øª Ø£Ù†Øª Ù‚Ù…Øª Ø¨Ø°Ù„ÙƒØŒ Ù‚Ù… Ø¨Ø§Ù„Ø¶ØºØ· Ø¹Ù„Ù‰ Ø§Ù„Ø±Ø§Ø¨Ø· Ø£Ø¯Ù†Ø§Ù‡ ï»¹Ø¹Ø§Ø¯Ø© ØªØ¹ÙŠÙŠÙ†Ù‡Ø§.
```

I will try to fix it

**Comment by celghandour** [comment]
Hello , can you tell me how can i test this feature ?

**Comment by ahus1** [comment]
Thanks for contributing to this project with this pull request!

When creating PRs, this project asks in its [contributing guidelines](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md) to:

* squash all commits in this pull request to a single commit

Also, this PR needs a rebase as there have been some conflicts with other ongoing changes.

Looking at the implementation, I see that you have escaped all Arabic characters. Within Keycloak, this is not necessary once you add a `# encoding: UTF-8` as the first line of the file. You can find an example in the `messages_fi.properties` files. As this makes the translation readable in a regular editor, I ask you to add this line and then un-escape all characters. 

Finally, when this is all complete, you'll need to find someone from the community to review the translation. This was also a note in the previous pull request. 

Please update your PR to align with this. Thanks!

**Comment by ahus1** [comment]
There has been no feedback on this PR from the community. Closing it.

**Comment by sltanhs** [comment]
حسبي الله ونعم الوكيل منك يا ابو بشار المنحرف الغدار الخاين المخادع الكذاب ليش عادك تحلف من كذب وهذا ماهو

**Pull request closed without merging**
