### PR TITLE
[KEYCLOAK-6298] SAML adapter script should support offline installation of adapter

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Good catch, thanks!
It should include the elytron variant too.

**Comment by abstractj** [comment]
@hmlnarik updated!

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Apologies I didn't realize earlier - Offline mode was introduced with WF so these scripts should not be included in as7/eap6

**Comment by abstractj** [comment]
@hmlnarik oh boy, I missed this, sorry. Updated now.

**Review by hmlnarik — DISMISSED** [review]
Looks good to me, thanks!

**Comment by abstractj** [comment]
@hmlnarik I just did a rebase, otherwise due to protected branches we won't be able to merge. Certainly tomorrow another rebase will be required :)

**Review by hmlnarik — APPROVED** [review]
@abstractj Go for it :)

**Pull request merged**
