### PR TITLE
KEYCLOAK-19039 Sync UPDATE_PASSWORD required action to only to MSAD w…

### PR DESCRIPTION
**Pull request by mposolda**
…ith WRITABLE edit mode. Add tests for MSAD mapper

### CODE REVIEW

**Comment by mposolda** [comment]
@pskopek Do you please have a chance to review this?

**Comment by mposolda** [comment]
LDAP tests in pipeline: https://keycloak-jenkins.com/job/universal-test-pipeline-server/701/

**Comment by mposolda** [comment]
Adding also @pdrozd for the review of this.

This PR in fact addresses also https://issues.redhat.com/browse/KEYCLOAK-4294 as we did not have any coverage of MSAD mapper. All new MSAD tests passed in the mentioned pipeline run from above.

**Review by pskopek — APPROVED** [review]
It looks good to me!

**Comment by mposolda** [comment]
@pskopek Thanks!

**Pull request merged**
