### PR TITLE
Make the option buildTime to match the quarkus configuration

### LINKED ISSUE #26168: KC_DB_DRIVER is not propagated properly
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

Currently, when running nigthly 
KC_DB_DRIVER does propagate properly. This makes it impossible to override the driver 

### Version

nightly

### Expected behavior

KC_DB_DRIVER can be set during build and properly propagated

### Actual behavior

KC_DB_DRIVER is ignored

### How to Reproduce?

Configure KC_DB_DRIVER to custom value and change the url to require plugin.
Example AWS jdbc driver for Postgres:
`
--db-url=jdbc:aws-wrapper:postgresql://
--db-driver=software.amazon.jdbc.Driver
`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rh-iatanaso**
Closes #26168

### CODE REVIEW

**Review by shawkins — DISMISSED** [review]
LGTM - once the help is updated, thanks @rh-iatanaso

**Review by vmuzikar — DISMISSED** [review]
@rh-iatanaso Thanks, a wonder that we didn't hit this sooner. :)

**Comment by shawkins** [comment]
@vmuzikar @rh-iatanaso this is the quick and dirty class that I leave in my workspace to help with the help files https://gist.github.com/shawkins/f5f907f27bfad8b317678976a04d2814 - after the test fails, just run that to copy things over. It's not fully correct for windows as there's a chance that that command name length will throw off the indentation - but it's close enough, and I don't think we bother checking the windows stuff anyway. 

It might be work a few extra minutes to check something like this in along with the maven command that would run it (or I'm sure it could be done in just a few lines of bash).

The OptionValidationTest failures are due to the way we are building up the list of possible options - it seems to be ordered by run time, then build time. That should be due to the order in which command options are added to pico-cli. Should we can consider alpha sorting here instead?

**Comment by vmuzikar** [comment]
> @vmuzikar @rh-iatanaso this is the quick and dirty class that I leave in my workspace to help with the help files https://gist.github.com/shawkins/f5f907f27bfad8b317678976a04d2814 - after the test fails, just run that to copy things over. It's not fully correct for windows as there's a chance that that command name length will throw off the indentation - but it's close enough, and I don't think we bother checking the windows stuff anyway.

Thanks, that looks really useful! With regards to windows, since the help content differs from linux to some extent, we should also test it. Looks like an oversight that it's not included in the sanity checks.
 
> It might be work a few extra minutes to check something like this in along with the maven command that would run it (or I'm sure it could be done in just a few lines of bash).

I'd do it with mvn to be platform independent.

> The OptionValidationTest failures are due to the way we are building up the list of possible options - it seems to be ordered by run time, then build time. That should be due to the order in which command options are added to pico-cli. Should we can consider alpha sorting here instead?

Not sure what you mean?

**Comment by shawkins** [comment]
> Not sure what you mean?

I'm talking about the reordering that is happening here - https://github.com/keycloak/keycloak/pull/26171/files#diff-fe890af5e7a93bf15668f178fc4ee80a0158732621d42abdc1339094c2f60ea8R76

We could instead consider alpha sorting the options.

**Comment by rh-iatanaso** [comment]
@shawkins the PR should be good now I hope, I did not sort the options but rather updated the test.

**Comment by shawkins** [comment]
> @shawkins the PR should be good now I hope, I did not sort the options but rather updated the test.

That's perfectly fine. It'll be a follow-on proposal if @vmuzikar is in favor of it.

**Review by shawkins — APPROVED** [review]
LGTM, thanks for updating those test results @rh-iatanaso

**Review by vmuzikar — APPROVED** [review]
@rh-iatanaso Thanks, LGTM!

@shawkins I see, thanks for clarifying.

**Pull request merged**
