### PR TITLE
Avoid using user property mapper when resolving root user attributes

### LINKED ISSUE #20613: Avoid using user property mapper when resolving root user attributes
### Description

The `UserPropertyMapper` [1] relies on reflection to resolve the root user attributes (e.g.: username, first|last name, email, etc).

The same mapping can be achieved for these attributes if using the `UserAttributeMapper`, which does not rely on reflection and resolves the root attributed from the attributes associated with an user.

Looks like the spread usage of the `UserPropertyMapper` is due to a legacy behavior where the root attributes were not available from the user attributes hence the need for reflection to obtain them from their corresponding getter methods in the `UserModel`.

Given that the root attributes are most of the time mapped into tokens, not using the `UserPropertyMapper` should improve the runtime when authenticating and mapping claims to tokens.

[1] https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/mappers/UserPropertyMapper.java 

### Discussion

_No response_

### Motivation

Improve the server runtime.

### Details

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #20613

* Removes the `UserAttributeMapper` from the build-in mappers
* Adds the `UserPropertyMapper` as a replacement to the aforementioned mapper, only for root user attributes like username, first|last names, and email

### CODE REVIEW

**Comment by pedroigor** [comment]
@mposolda It should not impact existing deployments and realms, right?

**Review by mposolda — APPROVED** [review]
@pedroigor Yes, I see your change is backwards compatible just fine, so approving and merging.

**Comment by twobiers** [comment]
@mposolda @pedroigor We just ran into a problem with that change. We're using a custom UserStorageProvider which did not map the root Properties `firstName`, `lastName` and `email` as an attribute. When creating a new realm with the provider these properties are not mapped into the ID Token, which was a breaking change for us.

Are you aware of this kind of problem? In my opinion it should be worth mentioning it in the Upgrade Guide.

**Comment by wallner** [comment]
> @mposolda @pedroigor We just ran into a problem with that change. We're using a custom UserStorageProvider which did not map the root Properties `firstName`, `lastName` and `email` as an attribute. When creating a new realm with the provider these properties are not mapped into the ID Token, since by default the UserAttributeMapper is now used, which was a breaking change for us.
> 
> Are you aware of this kind of problem? In my opinion it should be worth mentioning it in the Upgrade Guide.

We got hit by that too. Mentioning it in the Upgrade Guide would have saved us a lot of trouble. :shrug:

**Pull request merged**
