### PR TITLE
Fix code scanning alert #2506: Implicit narrowing conversion in compound assignment

### PR DESCRIPTION
**Pull request by abstractj**
Fixes [https://github.com/keycloak/keycloak/security/code-scanning/2506](https://github.com/keycloak/keycloak/security/code-scanning/2506)

_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

### CODE REVIEW

**Comment by abstractj** [comment]
@keycloak/maintainers this is an experiment with the new feature provided by GitHub.

**Review by stianst — CHANGES_REQUESTED** [review]
This change makes no sense to me.

It's changing the param type of _offsets to a long, to then cast it back to an int when it's used. How does that make any sense?

Doesn't even compile I would think, unless the method is not used anywhere?

**Comment by jonkoops** [comment]
Copilot is hallucinating hard here

**Comment by abstractj** [comment]
Closing it as the suggestion was not useful.

**Pull request closed without merging**
