### PR TITLE
Avoid short-lived connections for ApacheDS to avoid errors

### LINKED ISSUE #11171: Model tests for LDAP fail with a message "Could not unbind DN" and "ignoring the message MessageType UNBIND_REQUEST"
### Describe the bug

The model tests are unstable on GitHub action while they seem to complete locally. 

There seems to be a problem that entities (users) are sometimes not deleted as expected, and then a later test fails when the user or role still exists. 

### Version

18.0.0-SNAPSHOT

### Expected behavior

Deletion in LDAP/ApacheDS should succeed

### Actual behavior

Deletion in LDAP/ApacheDS sometimes fails

### How to Reproduce?

Difficult to reproduce due to environment/timing issues.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
after messages around ignoring the message MessageType UNBIND_REQUEST"

The comment in LdapRequestHandler.java in ApacheDS notes just before discarding an unbind: "in some cases the session is becoming null though the client is sending the UnbindRequest before closing".

Closes #11171

### CODE REVIEW

**Comment by ahus1** [comment]
I did a local test by adding a breakpoint in the problematic ApacheDS class LdapRequestHandler. Before the change the message was triggered several times even locally, although the tests were green (as not unbinding in LDAP would only cause a problem in the next test). 

After the change enabling connection pooling and setting pref=max, the problematic code was no longer triggered. Therefore I assume this is now solved. A previous workaround is now also removed.

**Review by sguilhen — COMMENTED** [review]
I like that this fix removes the workaround in the `UserModelTest`, so it gets a +1 from me. However, shouldn't you also change the https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/resources/META-INF/keycloak-server.json as well? AFAIK the one in `testsuite/utils` is used when we run the `KeycloakServer`, whereas the one I've linked is used when we run the base testsuite via mvn.

**Comment by ahus1** [comment]
Hi @sguilhen - I had a look and the keycloak-server.json doesn't configure LDAP. Looking at the tests it is configured later at runtime. I changed some more files that take care of this runtime configuration: 

* [TestLDAPResource.java](https://github.com/keycloak/keycloak/pull/11172/files#diff-f6cc0a1ff0b37ad2ffab7a5f9966e8b696d655ae7f54922895ab774cf0d6d248)
* [LDAPRule.java](https://github.com/keycloak/keycloak/pull/11172/files#diff-09e166fb7a6606020653b8237217458765c1ddd2b67b0f6f3cb8381ed484e39d)
* [LDAPTestConfiguration.java](https://github.com/keycloak/keycloak/pull/11172/files#diff-279261b7eddbf33f4f383b47ecdf16341b0852f7e04b028ed265c2f42264d5a1)

Please have a look. At the time you're about this they have hopefully completed.

**Comment by ahus1** [comment]
Raised an upstream issue: https://issues.apache.org/jira/browse/DIRSERVER-2369

**Review by hmlnarik — APPROVED** [review]
Thanks for the PR

**Pull request merged**
