### PR TITLE
KEYCLOAK-16076 added new warining when cookies are disabled -with new branch-

### PR DESCRIPTION
**Pull request by DaSmoo**

### CODE REVIEW

**Comment by DaSmoo** [comment]
Hello @thomasdarimont  and @abstractj ,

could you take a look at the PR, as i said in the old PR #7595, i had issues with the squash and i created this new PR (sorry for that).

Greetings David

**Comment by DaSmoo** [comment]
Hey @abstractj,

did you had any time to take a look at the changes?

greetings David

**Comment by mposolda** [comment]
I am sorry for late feedback on this.

I wonder if this change could mean that under some circumstances there might be a "false alarm" ? Like the user seeing the message about disabled cookies even if he doesn't really have disabled cookies.

For example when you have the flow like this:
- Start the login session. Username/password screen is shown
- Fill the incorrect username/password (just to enforce changing URL to pointing to LoginActionsService endpoint)
- Restart the browser
- Wouldn't it be the error page about disabled cookies displayed now even if user doesn't really have cookies disabled?

**Review by mposolda — CHANGES_REQUESTED** [review]
Switching to "Request changes" until the comment above is addressed.

**Comment by DaSmoo** [comment]
Hey, @mposolda, unfortunately i left the Bosch company at the end of February. @sschu will take over the communication and changes for this PR. 

About your Question:
As far as i remember the changes i did could only effect the login flow when the third party cookies are disabled in the browser. As long as the the thrid party cookies are not disabled, the error message should be the old one. 

Greetings David

**Comment by leischt** [comment]
Hey @mposolda,
I changed the error message to make it more clear what happens. Now the main error is the missing cookie and the disabled browser cookies is mentioned as possible solution to solve this issue by the user himself. 
I also merged master into the PR branch to resolve the conflicting file.

**Comment by nmiddendorff** [comment]
Thank you for picking this PR up, @leischt. We are looking forward to taking advantage of this feature as well.

**Comment by stianst** [comment]
Wonder if it would be better to use some JavaScript to detect if cookies are enabled?

**Comment by leischt** [comment]
> 
> 
> Wonder if it would be better to use some JavaScript to detect if cookies are enabled?

This was my first thought too.
But as the login ui is build with server-side rendered templates, it seems easier to display a proper error page, if the check is done on server side also.
A additional advantage of the server side check: it is included all themes automatically without any changes, as the default error template is used.

**Comment by mposolda** [comment]
Thanks all for the changes. I am accepting this as it is better behaviour than what we have today.

**Pull request merged**
