### PR TITLE
KEYCLOAK-8708: Provide aggregation of group attributes for mappers

### PR DESCRIPTION
**Pull request by rmartinc**

### CODE REVIEW

**Comment by mposolda** [comment]
@rmartinc Looks quite good! Thanks! Just one small thing: WDYT about  changing the signature of the method KeycloakModelUtils to return Set rather than List? Right now, there is creation to Set, which is then unecessary converted to List.

**Comment by rmartinc** [comment]
Maybe it's better to return just a Collection<String>, this way we can return the list or the set. But it's needed to change another SAML method that expects a List: [AttributeStatementHelper.java](https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/protocol/saml/mappers/AttributeStatementHelper.java#L55). From List to Collection too. Better?

**Comment by rmartinc** [comment]
The set part was done to remove duplicates (maybe I'm overthinking).

**Comment by mposolda** [comment]
Collection is fine and avoiding duplicates is good. Changing the signature of the method in AttributeStatementHelper is also fine. What I was just looking is, that "resolveAttribute" is currently internally using Set and then needs to convert it to List. So just thinking about avoid creating one unecessary collection, that's the only reason I asked about changing to Set (or Collection). Thanks!

**Comment by rmartinc** [comment]
Yes, yes, I understood that you wanted to avoid the double creation of the list/set. It's done. Remember that I only added the new labels in "admin-messages_en.properties" (don't know how you manage the translations to other languages).

**Review by mposolda — DISMISSED** [review]
@rmartinc Great! Approving and hopefully we will merge once tests are passing. Localization is fine. English is the only "mandatory" language, for which the messages need to be filled when adding some new messages. For the other languages, the english message is shown for the stuff, which is not translated. This is not ideal, however it is the only possibility. 

The translations are handled by community and the contributor/maintainer of each language is supposed to send PR and update all new/updated/removed messages "in bulk" from time to time (however we can't obviously force anyone from community to do it, so it is not something to rely on).

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@rmartinc It seems that OIDCProtocolMappersTest.testGroupAttributeUserOneGroupMultivalueNoAggregate is failing with MySQL 5.7. Do you have a chance to try to test on MySQL and ensure that OIDCProtocolMappersTest is passing? 

Here are some instructions on how to run the test on MySQL: https://github.com/keycloak/keycloak/blob/master/misc/DatabaseTesting.md . I think that you will be able to run the MySQL test (once you have MySQL docker image running) with something like:
````
mvn clean install -Pdistribution -DskipTests=true
cd testsuite/integration-arquillian
mvn clean install -Dkeycloak.connectionsJpa.url=jdbc:mysql://`docker inspect --format '{{ .NetworkSettings.IPAddress }}' mysql`/keycloak -Dkeycloak.connectionsJpa.driver=com.mysql.jdbc.Driver -Dkeycloak.connectionsJpa.user=keycloak -Dkeycloak.connectionsJpa.password=keycloak -Dtest=OIDCProtocolMappersTest
`````

**Comment by rmartinc** [comment]
Right, it seems that if there are two attributes in the database the order is not guaranteed. So you can get the first or the second value in two of the tests. It didn't happen in H2 . I have changed those tests to check it like that:

```diff
--- a/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OIDCProtocolMappersTest.java
+++ b/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OIDCProtocolMappersTest.java
@@ -768,7 +768,8 @@ public class OIDCProtocolMappersTest extends AbstractKeycloakTest {
             assertNotNull(idToken.getOtherClaims());
             assertNotNull(idToken.getOtherClaims().get("group-value"));
             assertTrue(idToken.getOtherClaims().get("group-value") instanceof String);
-            assertEquals("user-value1", idToken.getOtherClaims().get("group-value"));
+            assertTrue("user-value1".equals(idToken.getOtherClaims().get("group-value")) ||
+                    "user-value2".equals(idToken.getOtherClaims().get("group-value")));
         } finally {
             // revert
             user.getAttributes().remove("group-value");
@@ -808,8 +809,8 @@ public class OIDCProtocolMappersTest extends AbstractKeycloakTest {
             assertNotNull(idToken.getOtherClaims().get("group-value"));
             assertTrue(idToken.getOtherClaims().get("group-value") instanceof List);
             assertEquals(2, ((List) idToken.getOtherClaims().get("group-value")).size());
-            assertEquals("user-value1", ((List) idToken.getOtherClaims().get("group-value")).get(0));
-            assertEquals("user-value2", ((List) idToken.getOtherClaims().get("group-value")).get(1));
+            assertTrue(((List) idToken.getOtherClaims().get("group-value")).contains("user-value1"));
+            assertTrue(((List) idToken.getOtherClaims().get("group-value")).contains("user-value2"));
         } finally {
             // revert
             user.getAttributes().remove("group-value");
```

Let's see now.

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Review by mposolda — APPROVED** [review]
@rmartinc Thanks!

**Comment by diogomonte** [comment]
Is this issue in production?

**Comment by diogomonte** [comment]
Is this issue deployed to production?

**Pull request merged**
