### PR TITLE
Added warning when map storage contains multi-valued attributes

### LINKED ISSUE #9714: Adpaters for Map Storage swallow multi-valued attribute while Keycloak Core doesn't support them
### Description

The adapters in the Map storage for Client, Realm and ClientScope translate the internal Map representation to the Keycloak model. If the internal representation contains a multi-valued attribute, it passes on only the first entry. Other items will be dropped.

This behavior could hide a problem in the implementation or inconsistencies in the data that could lead to problems in a production environment.

The goal is to log a low priority warning.

### Discussion

https://github.com/keycloak/keycloak/discussions/9636

### Motivation

Throwing an exception instead of logging a warning was rejected as this would lead to for example a client not being readable.

As a multi-valued attribute could be written for example by a future version of Keycloak during a zero-downtime upgrade or after a rollback from version that wrote such information to the store, throwing an exception (and thereby preventing a zero-downtime upgrade or rollback) was considered not acceptable.

### Details

./.

### PR DESCRIPTION
**Pull request by ahus1**
and Keycloak model doesn't support them.

Closes #9714

### CODE REVIEW

**Comment by ahus1** [comment]
Did a manual test with the JPA Map Storage:
* inserting an additional client attribute in the database for a client
* when listing the clients, the warning shows Keycloak's console
* when updating the client, the additional rows are removed and only a single row persists.

This matches the expectations we had when discussing this issue last week.

> 08:54:08,309 WARN  XNIO-1 task-5 [org.keycloak.models.map.client.MapClientAdapter] Client 'account-console' realm 'master' has attribute 'pkce.code.challenge.method' with 2 values, retrieving only the first

**Review by vramik — APPROVED** [review]
Thank you @ahus1, tested locally. LGTM.

**Review by mhajas — APPROVED** [review]
LGTM @ahus1, thanks

**Review by hmlnarik — APPROVED** [review]
Approving per @vramik and @mhajas 's reviews

**Pull request merged**
