### PR TITLE
KEYCLOAK-6448 - implement instagram social broker

### PR DESCRIPTION
**Pull request by hguerrero**

### CODE REVIEW

**Comment by stianst** [comment]
@vmuzikar another social provider. How do you feel about adding tests for it?

**Comment by stianst** [comment]
@hguerrero thanks. For pass it looks OK, but haven't tried it out. We'll also need to update documentation and add tests to SocialLoginTest.

**Comment by stianst** [comment]
Can you also squash to a single commit please and include KEYCLOAK-6448 in the commit message?

**Comment by vmuzikar** [comment]
Hi @hguerrero! Here's Václav from the QE. Thanks again for the contribution.
Could you please try to add a test for this as well? It should be pretty straightforward, very similar to other social provider tests we already have so you can take inspiration there. You can add it to the [SocialLoginTest](https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java) and create another [social login page class](https://github.com/keycloak/keycloak/tree/master/testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/social) which will be used by the test - that should do it. Further details on the social login tests can be found in the [HOW-TO-RUN](https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md#social-login) guide.
Please let me know if you run into any issues with the test.
Thank you.

**Comment by stianst** [comment]
@hguerrero are you able to provide updates to the test and docs as well?

**Comment by hguerrero** [comment]
let me work on that during weekend after FY end.

**Comment by vmuzikar** [comment]
Hello @hguerrero!
I just wanted to ask if you got any chance to look into squashing the commits. Other than that it looks good to me (incl. the test) - after squashing it we're ready to merge this.

Could you please also look into updating the docs for this Identity Provider? See https://github.com/keycloak/keycloak-documentation/tree/master/server_admin/topics/identity-broker

Please let me know in case you need any help with it.

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
Thanks @hguerrero :)

**Pull request merged**
