### PR TITLE
[KEYCLOAK-14346] Base URL for applications is broken

### PR DESCRIPTION
**Pull request by douglaspalmer**

### CODE REVIEW

**Comment by douglaspalmer** [comment]
Would it be better to remove rootUrl and baseUrl and just pass the effectiveUrl around?

**Review by ssilvert — COMMENTED** [review]
LGTM

**Review by ssilvert — APPROVED** [review]

**Comment by edewit** [comment]
this PR broke the UI tests

**Comment by abstractj** [comment]
@edewit please talk with @ssilvert and in the future we can coordinate a better way to make sure that things like this won't happen again.

**Pull request merged**
