### PR TITLE
Fixes KEYCLOAK-7689 Authenticator - Mobile Setup HTML

### PR DESCRIPTION
**Pull request by junezhang**
This PR is aim to provide the HTML for Mobile Authenticator Set up.
JIRA task: https://issues.jboss.org/browse/KEYCLOAK-7689

The desktop screenshot:
screen shot 2018-06-29 at 5 38 55 pm

The responsive screenshot:
screen shot 2018-06-29 at 5 38 00 pm

@ssilvert hello, Stan, in this page, I used an image, the url is `${resourceUrl}/app/assets/img/QRCode.png`, I don't know why the image is not displayed. please have a review.

### CODE REVIEW

**Comment by ssilvert** [comment]
You need to make the resourceUrl variable available to the HTML template.  This should be done in mobile-authenticator-setup-page.component.ts.  See applications-page.component.ts for an example.  You will need to add two lines of code and then rebuild.

declare const resourceUrl: string;

private resourceUrl: string = resourceUrl;

**Comment by ssilvert** [comment]
I'll let you go ahead and make that change and then I'll do the review.

**Comment by ssilvert** [comment]
Of course, this image will eventually be replaced with the real QR code, but it will be helpful to see it with the dummy code for now.

**Comment by junezhang** [comment]
@ssilvert Hello, Stan, thanks for the code review.
For easily review, adding two more pages for SMS Code Setup and Backup Code Setup in this PR.

SMS Code Setup - Desktop version
screen shot 2018-07-02 at 2 46 36 pm

SMS Code Setup - Responsive version
screen shot 2018-07-02 at 2 46 50 pm

Backup Code Setup - Desktop version
screen shot 2018-07-02 at 3 14 49 pm

Backup Code Setup - Responsive version
screen shot 2018-07-02 at 3 14 58 pm

**Review by ssilvert — APPROVED** [review]

**Pull request merged**
