### PR TITLE
Allow duplicated keys in advanced claim mappers

### LINKED ISSUE #22638: SAML AdvancedAttributeToRoleMapper does not allow predicate evaluation on same Array Attribute
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

saml

### Describe the bug

d3850847-10cc-464b-81a5-688daa2a5805
```
<saml:Attribute xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="groupMembership" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
	<saml:AttributeValue xsi:type="xs:string">cn=captain,ou=...,ou=...,o=...</saml:AttributeValue>
	<saml:AttributeValue xsi:type="xs:string">cn=america,ou=...,ou=...,o=...</saml:AttributeValue>
```

Configuration above leads to an "duplicate key groupMembership..." error in Keycloak's log and no mapping at all.

### Version

22.0.1

### Expected behavior

I expect following behaviour (for the example above):

_if I am a group member of "america" and a group member of "captain" give  me the role "manager_us"_

### Actual behavior

Predicates (equals or regex) on different keys evaluate with AND.
Predicates on same key evaluate not at all.

### How to Reproduce?

Define predicates on same key.

### Anything else?

I consider this a bug because of the inconsistent behavior and the inability to express a common use-case.

Fix should be easy when I look into the source code.

### PR DESCRIPTION
**Pull request by rmartinc**
Closes https://github.com/keycloak/keycloak/issues/22638

Modifying the `getConfigMap` to return a `MultivaluedHashMap` instead of a simple `Map<string,String>`. The only concern is that I'm modifying the API. If you want me to maintain the old method (creating a new one) just let me know. But I decided to change it because the old one is incorrect and can throw an exception as the related issue shows. Mappers that use the method have been updated and tests modified to include two conditions with the same claim.

### CODE REVIEW

**Review by pedroigor — COMMENTED** [review]
For me, better would be if we keep the same method contract and just populate properly the list of values for a same key.

**Comment by rmartinc** [comment]
@pedroigor But the problem is that the current contract is `Map<Stting,String>`. So it cannot contain several config values for the same key/claim. I have to change it to `MultivaluedHashMap` which is `Map<String,List<String>>`. I thought about maintaining the method and adding a new one, I can even avoid the exception, but it will contain only one value. If you prefer I can create a new method that return the `MultivaluedHashMap`.

**Comment by pedroigor** [comment]
Sorry, please ignore what I said. Breaking it looks like the best approach. Otherwise, that method will be confusing and not aligned with the configuration schema.

Perhaps return a Map<String, List<Strng>> rather than the multivalued type. Also wondering if we shouldn't return an immutable instance too.

**Comment by rmartinc** [comment]
> Perhaps return a Map<String, List> rather than the multivalued type. Also wondering if we shouldn't return an immutable instance too.

Done! Changed to `Map<String,List<String>` and returning immutable versions. I rebased too. Let's see the tests as I see github quite unstable these days.

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
