### PR TITLE
task: update kube / minikube versions

### PR DESCRIPTION
**Pull request by shawkins**
relates to: #27080

### CODE REVIEW

**Review by mabartos — COMMENTED** [review]
We could use Kubernetes v1.28.x (OCP 4.15) when upgrading it now, right? 

But LGTM anyway

**Comment by shawkins** [comment]
> We could use Kubernetes v1.28.x (OCP 4.15) when upgrading it now, right?

We support both the latest and the previous. I opted to leave this at the previous.

**Review by vmuzikar — APPROVED** [review]
LGTM

**Review by mabartos — APPROVED** [review]
@shawkins Works for me. LGTM

**Pull request merged**
