### PR TITLE
KEYCLOAK-1372 - do not perform email verification if email is provided by trusted Identity provider

### PR DESCRIPTION
**Pull request by velias**

### CODE REVIEW

**Comment by stianst** [comment]
Would be nice to have tests that checks email is sent when provider email is not trusted, and not sent when provider email is trusted. Could you add that?

**Comment by velias** [comment]
Tests are improved now. `SAMLKeyCloakServerBrokerBasicTest` tests case when email trust is enabled. All other broker related tests assert behaviour when email trust is disabled.

**Comment by velias** [comment]
To be clear, my code from this PR only sets `User.emailVerified` attribute to `true` if necessary. Email sending itself is performed based on this attribute by completely unrelated code somewhere in login flow code.

**Comment by velias** [comment]
Finally I decided to add other tests which will test whole flow, not only assert `User.emailVerified` attribute. So wait with merge of this PR please.

**Comment by velias** [comment]
Full tests with testing of complete flow are done now. You can merge PR if travis build will be OK.

**Comment by stianst** [comment]
Awesome - thanks

**Pull request merged**
