### PR TITLE
KEYCLOAK-3641 - Only remove email verify key from session once we know the key from the session is valid

### PR DESCRIPTION
**Pull request by ksteffe**

### CODE REVIEW

**Comment by stianst** [comment]
Thanks for the PR. Can you please add a test for this?

**Comment by mposolda** [comment]
Doesn't this open vulnerability to brute-force attack? It seems that now attacker will have possibility to send gazillion mails and guess the "key". Previously the unsuccessful attempt removed the key from clientSession, so brute-force wasn't easily possible.

**Comment by stianst** [comment]
I see the theoretical brute force (although would be close to impossible to guess, take a look at how client session codes are created). Besides, is it not just the same error message shown before/after the PR?

**Comment by ksteffe** [comment]
Hello,

I'd love to add a test here (it was tricky enough to figure out how to reproduce this bug in the first place) but was wondering if you could point me to some existing tests that test email verification.  I see a lot of Selenium tests of the service layer in general, and this code would be a lot easier to unit test if it were factored out of LoginActionsService (though I thought that would make for a separate PR).

In order to do a Selenium test I would need the test to be able to access the email that gets sent, and then click on the link from the email.  It seems like there has to be an easier way to do this.  Can you point me in the right direction?

**Comment by mposolda** [comment]
I wonder if client session note should track all the keys (in case the email was re-send). This will improve usability (even better than your PR), but at the same time keep the same security and won't allow even theoretical brute force.

Example scenario:
- Account created. Email1 send and clientSession note with "key1" 
- User doesn't yet receive email1 (eg. slow mailserver), so clicks on "re-send email" to send email2. Now clientSession won't just replace the previous key, but add new one to it divided with some delimiter - something like "key1###key2" 
- Mailserver awakes and both emails are received. Now regardless if user clicks on link in email1 or email2, both will just work as clientSession note keeps track of both keys.
- In case that attacker tries with some bad link, clientSession note will be just removed (same behaviour as now), so brute force won't be possible.

Another option to track all keys is, that instead of delimiter, we will support list in clientSession note. But that means much more refactoring including model.

@stianst @ksteffe What do you guys think? Is it something to consider or is it rather corner case, which doesn't worth more complexity with tracking all keys?

**Comment by mposolda** [comment]
@ksteffe For testing of mails, we use GreenMail. For example take a look at UserTest.sendVerifyEmail in testsuite/integration-arquillian module.

**Comment by ksteffe** [comment]
@mposolda I like your suggestion of appending keys with a delimiter and don't think it's too much of a corner case.  To me, the added usability benefit of having all emails work and protection against a theoretical brute-force is a win-win.

While I think that having a list in clientSession note is more natural for this type of note, it may be more trouble than it is worth for other types of notes.  For existing notes it seems convenient to be able to assume that if you have a key, you have a single value, and you don't have to pull out the first one from the list or check for emptiness.  If there truly are other note types that could benefit from a list though, maybe it is worth it.

If @stianst is on board as well, would you rather that I drop this PR and create a new PR?  Or just keep working from the same PR?

P.S. Thanks for the tip on where to find a similar test.

**Comment by stianst** [comment]
I'm on board with what Marek proposed with one addition. We should have a maximum size of the list (say 10?). If someone tries to send more they'd get an error when trying to send the mail.

If we don't have a limit then someone could do a DOS attack and/or fill up with a large amount of keys to take a guess. Then do it again to take another guess. So they can do batch guesses until they get it right.

**Comment by mposolda** [comment]
We have one more issue now in latest master, because it's also "code" which is changing . Latest behaviour expects that each code can be verified just once. Also unsuccessful code validation for particular clientSession will cause later validation with correct code to fail, as the ACTION_SIGNATURE is now removed from clientSession even before it's validated - https://github.com/keycloak/keycloak/blob/master/server-spi/src/main/java/org/keycloak/services/managers/ClientSessionCode.java#L265 

In other words, even with your PR (not removing "key" during unsuccessful validation), the issue will be still here, because codes in email1 and email2 will be different. So when user clicks on email1, it will remove ACTION_SIGNATURE clientSession note. Then click on email2 will fail because ACTION_SIGNATURE note was removed in the meantime.


@stianst I don't know what we can achieve to improve. Maybe we don't need to remove the ACTION_SIGNATURE during each unsuccessful attempt, but have allowed number of code verification failures (eg. 3 by default)? 

That will help at least with the scenario. which @ksteffe described in the JIRA https://issues.jboss.org/browse/KEYCLOAK-3641 . In other words, when 2 mails were sent, then click on email1 won't remove the ACTION_SIGNATURE and hence user will be still able to click on email2 and successfully verify email. But I don't know how to support the scenario, which I originally wanted to support without further complexity (click on any of email1 or email2 will successfully verify email).

**Comment by ksteffe** [comment]
I haven't yet updated the PR with the feedback given so far (I was out in vacation).  Does it still make sense to do this given the ACTION_SIGNATURE behavior in master?  Or should I consider a different approach?

**Comment by stianst** [comment]
@mposolda isn't actually the correct behavior what we have now? only the latest email can be used and all other emails will no longer be valid?

**Comment by mposolda** [comment]
@stianst yeah, I can't see how tu support all the emails now.

But again, it seems that now this PR won't even fix the scenario described in https://issues.jboss.org/browse/KEYCLOAK-3641 . Because due to ACTION_SIGNATURE change, we don't have just "key", but also "code" to care about. 

Now what will happen is:
1) Account is created. Email-1 was sent
2) User clicks on re-send email. Email-2 is sent. Note that it has different "code" than email-1 now.
3) User clicks on link in email-1. The code verification will fail (expected). But it will call this line and remove ACTION_SIGNATURE note https://github.com/keycloak/keycloak/blob/master/server-spi/src/main/java/org/keycloak/services/managers/ClientSessionCode.java#L265 . 
4) User clicks on link in email-2. ACTION_SIGNATURE note is not available, hence verification will fail again -> FAIL
Expected behaviour: Link from email2 should still be valid

Possible solution: Remove ACTION_SIGNATURE note from clientSession after successful code validation. In other words, request with invalid code won't remove the note. Are you seeing any issue with it? I can't come with anything despite brute-force guessing code, but that's very unlikely...

**Comment by stianst** [comment]
Closing this as I've sent another PR for it:
https://github.com/keycloak/keycloak/pull/3433

Basically what I did is to first check the key. If the key is invalid complain. If it's valid remove it and then check the code. Someone can bruteforce the key all they like. All they'd manage to accomplish is to get one attempt at guessing the code. So the key is now not really a security thing, rather it's a way to make sure previous emails won't clear the code from the session.

**Pull request closed without merging**
