### PR TITLE
Add back <?INTERFACES?> to avoid a NPE in wildfly-server-provisioning-maven-plug

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by stianst** [comment]
Closing this PR as there's a lot of stuff in the same PR. We're also not upgrading to WildFly 10 until Final is released.

Only commit here that looks applicable now is https://github.com/ppalaga/keycloak/commit/fb3c6159f87e08f5318a3cf61074e598c22c6eff

However, it's not causing any issues here, so what's the actual problem?

**Comment by ppalaga** [comment]
> However, it's not causing any issues here, so what's the actual problem?
I see an NPE with provisoining plugin 1.1.1.Final

**Comment by ppalaga** [comment]
* I see an NPE with provisoining plugin 1.1.0.Final

**Comment by ppalaga** [comment]
2507af1 should make sense too.

**Comment by ppalaga** [comment]
> Closing this PR as there's a lot of stuff in the same PR.

Where do I find the desired granularity of PRs documented?

**Comment by stianst** [comment]
For upgrading dependency versions and especially to upgrade the version of the underlying container we won't accept PRs from anyone outside of the core team. Once WF 10 Final is ready we'll upgrade to it. We've already started a branch where we're testing with WF 10.0.0.CR4 (wildfly-10 branch). If you want to try Keycloak server on WF-10 then you can try that. Releases of Keycloak server are only supported on one single version of WF though.

For granularity of issues see:
https://github.com/keycloak/keycloak/blob/master/misc/HackingOnKeycloak.md

We also appreciate a heads up about things on the mailing list and there should an accompanying JIRA.

**Pull request closed without merging**
