### PR TITLE
[KEYCLOAK-8172] - Evaluation not considering scopes inherited from parent resources

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by mhajas — APPROVED** [review]

**Comment by stianst** [comment]
What about tests?

**Comment by mhajas** [comment]
@stianst Tests are already there, but for some reason, they didn't catch this. I will add another PR with a fix, but there are lots of other changes (making photoz work on undertow, removing angular app and using JavascriptExecutor instead) so it will be separate PR.

**Comment by mhajas** [comment]
@stianst I need this merged to test my changes properly

**Comment by stianst** [comment]
OK, I'll approve, but I'm not fully happy about it ;)

**Review by stianst — APPROVED** [review]

**Comment by pedroigor** [comment]
@stianst we are actually fixing code after failures found by Michal's work to improve testsuite. We are covering this particular change already.

**Pull request merged**
