### PR TITLE
[KEYCLOAK-17113] - Clean up and expand use of TokenResponseMapper

### PR DESCRIPTION
**Pull request by lmsurpre**
1. UserAttributeMapper now extends OIDCAccessTokenResponseMapper
2. admin-messages_en.properties now contains enlish labels for
`includeInAccessTokenResponse.label` and
`includeInAccessTokenResponse.tooltip`
3. Minor javadoc cleanup in AbstractOIDCProtocolMapper

Signed-off-by: Lee Surprenant <lmsurpre@us.ibm.com>

### CODE REVIEW

**Comment by mposolda** [comment]
@lmsurpre Thanks for the PR and sorry for late response. I see the change is good, but will be nice to add automated tests for this functionality. Also probably rebase to latest "main" might be needed.

**Review by mposolda — CHANGES_REQUESTED** [review]
@lmsurpre MArking as "Request changes" due the missing test

**Comment by mposolda** [comment]
I am closing for now. Feel free to re-open once you are able to address the concern with the automated test.

**Comment by lmsurpre** [comment]
Thanks @mposolda ...I meant to get back to this one after your last comment but it slipped off my radar.  Will reopen if/when I get to it.

**Comment by burningSchadow42** [comment]
I would like to reopen this.
SMART on FHIR requires the token response to contain the patient ID.

**Pull request closed without merging**
