### PR TITLE
[KEYCLOAK-13586] Fix typos related to QueryParamterTokenRequestAuthenticator

### PR DESCRIPTION
**Pull request by intricate**
See [KEYCLOAK-13586](https://issues.redhat.com/browse/KEYCLOAK-13586) for details.

### CODE REVIEW

**Comment by stianst** [comment]
Problem is that renaming the class is a breaking change, so not just as simple as going ahead and rename it.

**Comment by stianst** [comment]
Simplest is probalby just to leave it as is :/

**Comment by mposolda** [comment]
@stianst This stuff is in "adapter-core" library and IMO it is the class, which is supposed to be used internally by the adapters. It is not supposed to be consumed directly by the customer's applications IMO. If someone is using directly some internal Keycloak classes, then it could break for them, but not sure if it is the scenario, which we should care about?

So my vote is to include this in Keycloak 10.

@intricate Noticed that there is some trace message "try query paramter auth" in RequestAuthenticator, which will be nice to fix too when you're at it :)

**Comment by intricate** [comment]
@stianst @mposolda: Thanks for the feedback! 

> Noticed that there is some trace message "try query paramter auth" in RequestAuthenticator, which will be nice to fix too when you're at it :)

I can push another commit for that as well later today.

**Review by mposolda — APPROVED** [review]
@intricate Thanks for the updates

**Pull request merged**
