### PR TITLE
KEYCLOAK-12768: Certain characters in names cause bad URIs.  Disallow.

### PR DESCRIPTION
**Pull request by ssilvert**

### CODE REVIEW

**Comment by alexandershiltcev-gelato** [comment]
Hi guys, this change brakes our roles management. We do use : symbol to name roles like "urn:order:resources:order:ro" and now we can't create additional roles.

**Comment by abstractj** [comment]
@alexandershiltcev-gelato as far as I recall this change wasn't merged into master, the issue was closed, instead of merged. If there are any bugs, please report it on the mailing list or file a new Jira with all the details.

**Comment by alexandershiltcev-gelato** [comment]
It was merged and released in 9.0.2. That is how I found this PR. I wouldn't say it is a bug, it is a braking change which makes no sense to me....

**Comment by vmuzikar** [comment]
@abstractj https://github.com/keycloak/keycloak/pull/6842

**Comment by ssilvert** [comment]
@alexandershiltcev-gelato The problem is that a role name can end up in a URL and break the admin console.  Unfortunately, escaping wasn't an option.  So we decided to disallow special characters specified in https://tools.ietf.org/html/rfc3986#section-2.2.

It's definitely not the best solution.  We shouldn't be creating URLs out of those names in the first place, but the fix for that would be even more disruptive.

You could try just changing app.js and remove the colon in line 2394.  I'm not sure if it is disallowed on the back end.

Or you can switch to a different delimiter for your role names.

On the bright side, we are going to rewrite the admin console and I will make sure that it does not have this limitation.

**Comment by Josh-Airmap** [comment]
Do we know in which case a role name ends up in a URL?  In all cases I can find, our existing roles with non-URL safe characters are referenced by their UUID, rather than the string name (and function properly).  I've been navigating around the admin console (including flagged features like permissions) and failing to find anywhere this breaks (no 400's or 500's).  

This is a fairly disruptive regression for us, as we had automation across a significant amount of microservices to parse and generate roles in this format.  Going forward, we would either need to create some kind of role name map to support the legacy format in tokens (via a client-scope script mapper), or change all our microservices parsing code.  The largest pain point is that this wasn't noted in the 9.0.2 release notes (which don't exist).  At minimum, this caveat should be included in release notes as a potentially significant change for all future implementations to be aware of.

**Comment by alexandershiltcev-gelato** [comment]
@ssilvert Thank you for detailed answer. Unfortunately as I see backend validation was also updated in 9.0.2. I can create roles containing chars like * or : via API in 9.0.0, but not in 9.0.2 as KeyCloak throws 400 error.

**Comment by ssilvert** [comment]
OK.  I'll take another look at this.  It may be that this shouldn't have applied to roles.

**Comment by krnbr** [comment]
@ssilvert , yes should not have been applied to roles, or at least support roles of format as below:-

**arn:aws:iam::123456:role/test,arn:aws:iam::123456:saml-provider/test**

which is like need help with colon, comma, and forward slash

any tentative timeline for the resolution?

**Comment by krnbr** [comment]
> OK. I'll take another look at this. It may be that this shouldn't have applied to roles.

@ssilvert , yes should not have been applied to roles, or at least support roles of format as below:-

arn:aws:iam::123456:role/test,arn:aws:iam::123456:saml-provider/test

which is like need help with colon, comma, and forward slash

any tentative timeline for the resolution?

**Comment by krnbr** [comment]
I think that it's related to the PR here?

https://github.com/keycloak/keycloak/pull/7071

when can we expect the release for this?

any timeline? @ssilvert ?

**Comment by krnbr** [comment]
if a release 10.0.3 be done for this?

**Pull request closed without merging**
