### PR TITLE
https://issues.jboss.org/browse/KEYCLOAK-1727

### PR DESCRIPTION
**Pull request by gerbermichi**
LDAP with Kerberos, login with different user

added skip_auth_mechanisms query parameter to skip one to many not
required authenticators.

### CODE REVIEW

**Comment by mposolda** [comment]
The approach in the PR looks good to me. If others agree, I am fine with merging it.

I think it will be good to also add the test and some docs for it - maybe paragraph into Authentication SPI chapter and some small note into Kerberos chapter as well with the link to the Authentication SPI chapter with details.

Btv. did you try to test the scenarios, when you have authentication flow with more alternative mechanisms and all the mechanisms are skipped by the parameter? IMO it should display some error like "Don't know how to authenticate user" or something like that.

**Comment by stianst** [comment]
I assume this is to bypass the Kerberos authenticator? If so I don't like this approach as it just delegates the problem to the application itself. Then what about SSO? If you bake the logic of when to login with Kerberos into one specific application the behavior will be different depending on what application you login to. Or you have to add the same logic to all applications. Nasty! With a centralized SSO server applications should not have to deal with authentication semantics.

**Comment by gerbermichi** [comment]
The goal is to bypass the kerberos authenticator after a logout. So you can login with a different user (i.e. Admin). How can you achive this goal? Maybe its possible to extand the LogoutEndpoint?

**Comment by stianst** [comment]
One simple solution would be to use a session cookie as a marker for logged-out from Kerberos (and any other authenticators that automatically login users). That would then prevent a user from being automatically re-logged in using Kerberos. My main point is that this should be solved at the Keycloak side, not by just adding some work around so it can be solved no the application side.

**Comment by mposolda** [comment]
I am not confident about the cookie. The problem is that cookie works automatically. So after logout, people will be automatically redirected to login screen instead of being logged with Kerberos. This might be confusing (Hey, what's this username/password screen about? Why I am not logged? etc)

The only way to enforce Kerberos login again will be to remove the cookie or restart the browser (assuming it's session cookie. Doing persistent cookie will be even worse...). Maybe we can make it configurable and not add cookie by default? 

But still the parameter looks better solution to me. AFAIK this is just solution for admins to bypass kerberos login once time. Admins just need to know that they need to add parameter skip_auth_mechanims=kerberos . They can even add it manually (then there is no change needed on application side) or application can provide link.

**Comment by gerbermichi** [comment]
I implemented a version with a logout cookie:
https://github.com/gerbermichi/keycloak/commit/f804d9e13573cb666cf6d2eff1407978c9e5e854

But I still prefer the version with the query parameter, because it's a lot more reusable for other authenticators.

**Comment by stianst** [comment]
We should bring this conversation back to the mailing list

**Pull request closed without merging**
