### PR TITLE
KEYCLOAK-13806 - form valiation if isRegistrationEmailAsUsername is true

### PR DESCRIPTION
**Pull request by railsonsm**
when finding the realm field isRegistrationEmailAsUsername ,the username field is hidden but validation continues to be done. As e-mail becomes username, email predicts to be mandatory

### CODE REVIEW

**Comment by hmlnarik** [comment]
Thank you for your PR. Before looking into the code, please file a JIRA and reference it in the commit and pull request. Check https://github.com/keycloak/keycloak/blob/master/CONTRIBUTING.md#contributing-to-keycloak for more details

**Comment by stianst** [comment]
@railsonsm could you add a better description to the issue, including steps-to-reproduce and expected/observed behaviour?

**Comment by railsonsm** [comment]
@stianst yes I can!

When the attribute USERNAME_AS_EMAIL is true in the realm, in the form of adding user the username fields will be hidden. The problem is that when submitting the form, the validation happens and keeps informing to verify the fields that are required, but the username field is hidden, so the user will never know why the error is being thrown. This correction makes the username field no longer mandatory when USERNAME_AS_EMAIL is true and e-mail becomes mandatory.

**Comment by stianst** [comment]
How do you reproduce this issue? What are the observed behaviour and the expected behaviour?

**Comment by pedroigor** [comment]
@railsonsm this PR can help with tests https://github.com/keycloak/keycloak/pull/6955.

**Pull request closed without merging**
