### PR TITLE
Add FAPI 2.0 security profile as default profile of client policies

### LINKED ISSUE #21181: Add FAPI 2.0 security profile as default profile of client policies
### Description

Like FAPI 1.0 baseline, FAPI 1.0 advanced, and FAPI-CIBA, FAPI 2.0 security profile is added as default profile of client policies after keycloak supports FAPI 2.0 secuirty profile.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by tnorimat**
closes #21181

### CODE REVIEW

**Comment by tnorimat** [comment]
@mposolda This PR is the final one to complete FAPI 2.0 support epic https://github.com/keycloak/keycloak/issues/20708 . Could you review the PR?

**Review by mposolda — DISMISSED** [review]
@tnorimat Thanks! I hope to merge if tests are ok

**Comment by mposolda** [comment]
@tnorimat I would like to merge this, but there are some conflicts according to github. Could you please rebase to resolve conflicts?

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
@tnorimat Thanks!

**Comment by tnorimat** [comment]
@mposolda Thank you. Could you work on the release note https://github.com/keycloak/keycloak/issues/21945 ?
Please feel free to ask me if you need some help to write the release note.

**Pull request merged**
