### PR TITLE
Workarounds to make Listeners and non-autocommit work on Quarkus

### LINKED ISSUE #13200: Fails to update a client with JPA Map store
### Describe the bug

When updating a client in the keycloak-benchmark project using `manage_gatling_client.sh`:

```
kcadm.sh update clients/$CID -r $REALM_NAME  -s "secret=***" -s serviceAccountsEnabled=true  -s publicClient=false -s 'redirectUris=["http://localhost:8081"]'
```

this fails with the following exception: 

> {"log":"{\"timestamp\":\"2022-07-19T06:46:40.211Z\",\"sequence\":5149,\"loggerClassName\":\"org.jboss.logging.DelegatingBasicLogger\",\"loggerName\":\"org.hibernate.engine.jdbc.spi.SqlExceptionHelper\",\"level\":\"ERROR\",\"message\":\"ERROR: duplicate key value violates unique constraint \\\"kc_client_attribute_fk_root_name_value_key\\\"\\n  Detail: Key (fk_root, name, value)=(8faabb01-f8a1-4c6a-96be-7808806bfe4c, client.secret.creation.time, 1658213199) already exists.\",\"threadName\":\"executor-thread-15\",\"threadId\":42,\"mdc\":{},\"ndc\":\"\",\"hostName\":\"keycloak-578dc9f8bc-hvdmj\",\"processName\":\"QuarkusEntryPoint\",\"processId\":1}\n","stream":"stdout","time":"2022-07-19T06:46:40.211893445Z"}

### Version

999-SNAPSHOT

### Expected behavior

The operation should succeed like it succeeds for the legacy store

### Actual behavior

_No response_

### How to Reproduce?

By running the script `manage_gatling_client.sh` above.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #13200

### CODE REVIEW

**Comment by ahus1** [comment]
Hi @vramik - this implements the workarounds we discussed earlier today, and I reviewed them with Pedro and we didn't find a simpler solution for that yet. 

The legacy implementation uses a XA datasource, and that switches the connection to non-autocommit, but I don't think we want an XA datasource here. 

I'll revisit it tomorrow and have another look where to add documentation; feel free to add review comments that make this simpler to understand for our future selfs and other people. 

Thanks!

**Comment by ahus1** [comment]
Testsuite was green once, which showed that the solution didn't break old things. 

Two follow-up issues created and added as comments in the code in those places that were added: 
* QuarkusJpaMapStorageProviderFactory: #13222 
* EventListenerIntegrator: #13219

**Review by vramik — APPROVED** [review]
Thank you @ahus1! LGTM

**Review by hmlnarik — APPROVED** [review]
Approving per @vramik 's approval

**Pull request merged**
