### PR TITLE
Add iat to JWT passed to CIBA HttpAuthenticationChannel

### LINKED ISSUE #21283: Add `iat` claim to JWT that is passed to CIBA HttpAuthenticationChannel
### Description

Add `iat` claim to JWT that is passed to CIBA HttpAuthenticationChannel, as `iat` is a mandatory claim in some frameworks (e.g. `quarkus-oidc`).

Related quarkusio/quarkus#34365

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by Eng-Fouad**
Fixes #21283

### CODE REVIEW

**Comment by sberyozkin** [comment]
@Eng-Fouad I think you should create an enhancement request in the Keycloak project and have this PR addressing that Keycloak enhancement issue.

@pedroigor Hey Pedro, does this PR look all right to you ? Having `iat` in JWT would never cause any side-effects :-), we can relax it a bit on the Quarkus side if it would be the only option, but I'm hoping Keycloak can get `iat` added for the tokens issued to the CIBA grant requests

**Comment by mposolda** [comment]
@tnorimat Does this PR looks ok to you? Could you please review?

**Comment by tnorimat** [comment]
@mposolda Yes, I will review the PR.

**Review by tnorimat — APPROVED** [review]
LGTM.
I think it is not needed to write additional tests.
If adding the test, `TestingOIDCEndpointsApplicationResource.requestAuthenticationChannel` might be the best place.

**Comment by mposolda** [comment]
@tnorimat Thanks! I was wondering about test as well, but agree that it is not that useful for such minor change.

**Review by mposolda — APPROVED** [review]

**Pull request merged**
