### PR TITLE
Admin UI: Credentials Reset dialog should only show activated required actions

### LINKED ISSUE #19046: Admin UI: Credentials Reset dialog should only show activated required actions
### Description

At the moment when opening the `Credentials Reset` dialog for a user all Required Actions are shown:
image
E.g. Terms and Conditions is deactivated for that realm:
image

It would make sense to limit this list to the Required Actions that are actually enabled for the Realm.

The Backend API to get the required actions already returns whether a required action is enabled or not, so the list must only be filtered on the Frontend.

image

### Discussion

_No response_

### Motivation

This would clean up the UI. 

### Details

_No response_

### PR DESCRIPTION
**Pull request by antikalk**
Fixes https://github.com/keycloak/keycloak/issues/19046

### CODE REVIEW

**Review by edewit — DISMISSED** [review]

**Comment by antikalk** [comment]
@edewit Thanks for approving the changes! I just saw that on the details screen of a user there is another dropdown to select required user actions that is currently unfiltered: 
image

It would make sense to apply the same filter here. Will you add that or shall I? :)

**Comment by edewit** [comment]
I can do it @antikalk, let's move this to a separate component.

**Comment by antikalk** [comment]
> I can do it @antikalk, let's move this to a separate component. I'll update this PR

That makes sense, thank you

**Review by jonkoops — DISMISSED** [review]

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
Thanks for your contribution @antikalk!

**Pull request merged**
