### PR TITLE
fix: PEM files distributed as part of SAML adapter configs for mod_au…

### LINKED ISSUE #34276: PEM files distributed as part of SAML adapter configs are missing -----BEGIN and -----END blocks
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

When you use the SAML apapter config downloads to download a client config, you are given a certificate and private key that are "bare", just a base64 blob starting with MII...but most clients that recognize pem files (including mod_auth_mellon) do not recognize these without their "container" lines.

### Version

25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

pem files that are valid according to https://www.rfc-editor.org/rfc/rfc7468

### Actual behavior

Bare pem files such as the following, with no -----BEGIN CERTIFICATE----/-----END CERTIFICATE  and -----BEGIN PRIVATE KEY----/-----END PRIVATE KEY----- blocks.  Tools such as mod_auth_mellon seem to reject these.  Keycloak's own docs for mod_auth_mellon seem to say that these are usable when downloaded from keycloak.

```
MIICuTCCAaECBgGSu5MBETANBgkqhkiG9w0BAQsFADAgMR4wHAYDVQQDDBVodHRwczovL2Nsb2FrLmlzYy5vcmcwHhcNMjQxMDIzMjI0ODQ2WhcNMzQxMDIzMjI1MDI2WjAgMR4wHAYDVQQDDBVodHRwczovL2Nsb2FrLmlzYy5vcmcwggEiM....etc....contents not important just missing headers
```

### How to Reproduce?

Follow directions here: https://www.keycloak.org/securing-apps/mod-auth-mellon to download the adapter configs, and try to use them.

### Anything else?

On FreeBSD 14.1 AMD64 with apache24-2.4.62 and with ap24-mod_auth_mellon-0.19.1.

### PR DESCRIPTION
**Pull request by JanDolling**
…th_mellon export

Closes #34276

Co-authored-by: ccudennec-otto
Co-authored-by: radwa-otto
Co-authored-by: IngoStrauch2020

### CODE REVIEW

**Comment by mposolda** [comment]
@JanDolling Thanks for the PR! Is it possible to remove mockito from the PR? Please add the automated test(s) instead to the class `InstallationTest`, which is in the arquillian integration testsuite.

**Comment by IngoStrauch2020** [comment]
@mposolda We have a hard time implementing a new test in `InstallationTest`.

It should be quite similar to e.g. `testSamlAdapterXml()`, but `String modAuthMellonZip = samlClient.getInstallationProvider("mod-auth-mellon");` is a String that's actually a ZIP file which is always reported as corrupt when we try to read the contents.
Writing the string to file also results in a corrupt ZIP.

**Comment by ccudennec-otto** [comment]
> @mposolda We have a hard time implementing a new test in InstallationTest.

We solved this by changing the return type of the `ClientResource` as we get different return types from the server. Our assumption that is not breaking as the class is only used internally by Keycloak integration tests.

**Comment by ccudennec-otto** [comment]
@mposolda : Can you check the PR again if this meets your expectations? Any comments are very welcome. 🙂

**Review by mposolda — DISMISSED** [review]
@JanDolling Cool, Thanks! I hope to merge if tests are OK

**Comment by ccudennec-otto** [comment]
@mposolda : Found the issue and fixed it. Hope builds are green now. 🙂

**Review by mposolda — APPROVED** [review]
@JanDolling Thanks!
@ccudennec-otto Thanks

**Pull request merged**
