### PR TITLE
[KEYCLOAK-11534] Add filter by name to applications endpoint

### PR DESCRIPTION
**Pull request by douglaspalmer**
Blocked by #6566

### CODE REVIEW

**Comment by abstractj** [comment]
@douglaspalmer adding the Hold label until we merge https://github.com/keycloak/keycloak/pull/6382

**Review by vmuzikar — DISMISSED** [review]
Even though filtering is usually better done on the DB side, I understand it would be unnecessarily complicated given that the clients are fetched from multiple resources.

Travis failures seem to be unrelated to this change (cross DC).

LGTM, thanks @douglaspalmer!

**Comment by vmuzikar** [comment]
One last thing. KEYCLOAK-11534 specifies it'll be possible to filter apps based on type. This will be done as a follow-up task, right?

**Comment by douglaspalmer** [comment]
> One last thing. KEYCLOAK-11534 specifies it'll be possible to filter apps based on type. This will be done as a follow-up task, right?

Clients don't have a Type field. What would type be defined as?

**Comment by vmuzikar** [comment]
@douglaspalmer You're correct, there's no type field. But if I understand it correctly, type is actually a mix of fields (in-use, internal, third-party, offline access). But I'm not sure, we'd need more clarification on this. @stianst?

**Review by vmuzikar — DISMISSED** [review]

**Comment by abstractj** [comment]
@vmuzikar @douglaspalmer added the label '_Discuss_' because this requires more discussion on the dev mailing list, plus filtering is not part of our priorities for 7.4. So merge and review it is a best effort if we have the time for it.

**Comment by abstractj** [comment]
@ssilvert when the filtering on applications UI is being planned? Asking because maybe it's time to review the changes in this PR.

**Comment by ssilvert** [comment]
@abstractj There is no particular time frame.  It's easy to implement the UI side once the server side is done.

Also, I really don't have a feel for the relative importance of this feature.  Maybe it's a nice to have at this point?

**Comment by abstractj** [comment]
> @abstractj There is no particular time frame. It's easy to implement the UI side once the server side is done.
> 
> Also, I really don't have a feel for the relative importance of this feature. Maybe it's a nice to have at this point?

@ssilvert it was implemented long time ago based on the wireframes we had, not sure if it's still true. Should filtering be part of the scope for further releases? What was the agreement with UXD team? Whether or not we should incorporate this is up to you, we can close this issue if no longer valid.

**Comment by ssilvert** [comment]
@abstractj I'm fine with it going in.  Is there any more discussion needed?

@douglaspalmer To me, it looks like the tests doesn't check filtering properly.  From what I can tell, it only checks if it found the application it was looking for but it doesn't check if any apps were returned that did not match the name.  But I don't know what the full list looks like.  Maybe just a check that size=1 would be sufficient to test that it didn't return too many results.

**Comment by abstractj** [comment]
Hi @douglaspalmer, we need to iterate over this PR and decide what to do next. Could you please check the latest comments?

**Comment by douglaspalmer** [comment]
> @abstractj I'm fine with it going in. Is there any more discussion needed?
> 
> @douglaspalmer To me, it looks like the tests doesn't check filtering properly. From what I can tell, it only checks if it found the application it was looking for but it doesn't check if any apps were returned that did not match the name. But I don't know what the full list looks like. Maybe just a check that size=1 would be sufficient to test that it didn't return too many results.

If the list contained more apps then containsInAnyOrder("in-use-client") would fail.

**Review by ssilvert — DISMISSED** [review]
I think this can be merged.

**Review by abstractj — APPROVED** [review]

**Review by abstractj — COMMENTED** [review]
@douglaspalmer because it's been a while, this PR needs a rebase I guess. Travis is reporting the following error:

```
[ERROR] /home/travis/build/keycloak/keycloak/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java:[670,9] method assertClientRep in class org.keycloak.testsuite.account.AccountRestServiceTest cannot be applied to given types;
[ERROR]   required: org.keycloak.representations.account.ClientRepresentation,java.lang.String,java.lang.String,boolean,boolean,boolean,java.lang.String,java.lang.String
[ERROR]   found: org.keycloak.representations.account.ClientRepresentation,java.lang.String,<nulltype>,boolean,boolean,boolean,java.lang.String
[ERROR]   reason: actual and formal argument lists differ in length
```

**Review by abstractj — CHANGES_REQUESTED** [review]
Please, see my last comments.

**Review by abstractj — APPROVED** [review]

**Pull request merged**
