### PR TITLE
KEYCLOAK-1925: SAML adapter multitenant support

### PR DESCRIPTION
**Pull request by rmartinc**
Hi,

I've been implementing the KEYCLOAK-1925 when I had some time. It's a little change in the code but it's bigger in the test part (using multi-tenant changes a bit all test infrastructure, besides tests have been changing a lot in the last days and that part have been crazy). I decided to include the tests in the general SAMLServletAdapterTest.

I have commented about this to @hmlnarik and @vramik and they commented me to send the PR (thanks guys). So here it is.

Regards.

### CODE REVIEW

**Comment by rmartinc** [comment]
@vramik Ok, I'll take a look to the documentation, I suppose the idea is adding a new chapter as the OIDC one you point but in the SAML java adapters (adding a 3.1.x chapter). Give some time to do this.

**Comment by rmartinc** [comment]
Hi @vramik 

I have sent the PR for the documentation in:
https://github.com/keycloak/keycloak-documentation/pull/414

Check it and let me know if you need some change (not very good in documentation :-/ ).

**Review by vramik — APPROVED** [review]
@rmartinc thanks for the documentation PR. 

This PR LGTM

@mposolda would you like to review it as well? Or do you prefer to wait for @hmlnarik?

**Comment by mposolda** [comment]
@vramik Rather wait for @hmlnarik as it's not blocker. Added him as reviewer

**Review by mhajas — APPROVED** [review]

**Comment by rmartinc** [comment]
Hi,

What about this? I don't want to rebase it again... :-)

**Review by hmlnarik — APPROVED** [review]

**Comment by hmlnarik** [comment]
@rmartinc I just happen to catch up with the PRs and other work after my return from PTO. Thanks for this PR, there's one minor documentation fix (squashing the commits) and it's ready to get in.

**Pull request merged**
