### PR TITLE
Update messages_nl.properties

### PR DESCRIPTION
**Pull request by jevanlingen**
Updated it to latest keys.

### CODE REVIEW

**Comment by kkplein** [comment]
Hi. I reviewed this, and noticed something: "delegationFailedHeader=Login gefaalt" should be "delegationFailedHeader=Login gefaald". But in fact this dutch is not so nice. Nicer would be "delegationFailedHeader=Login mislukt"
(dit past ook beter bij "delegationCompleteHeader=Login gelukt")

**Comment by jevanlingen** [comment]
@kkplein: Somehow you reviewed my first commit. I did already change that in my second commit :smile: (check the commit history).

**Comment by kkplein** [comment]
Ah I see now. Yes, the second translation has some other nice improvements as well. I'll see if I can 'Add my review'.

**Review by kkplein — APPROVED** [review]
Looking good.

**Comment by stianst** [comment]
@keycloak-ci-bot test

**Comment by stianst** [comment]
Please squash to a single commit

**Pull request merged**
