### PR TITLE
Use Quarkus Platform BOM

### LINKED ISSUE #9075: Remove any unnecessary dependency from distribution
### Description

Not only to reduce the distribution size but also to reduce the vulnerability surface, we should review the dependencies included in the distribution and keep only those strictly necessary to runtime and re-augmentation.

As the server is a mutable jar, these additional dependencies are a trade-off as part of continuous testing support from Quarkus. However, in theory, these dependencies won't actually be loaded in the runtime application.

### Discussion

_No response_

### Motivation

Not only to reduce the distribution size but also to reduce the vulnerability surface, we should review the dependencies included in the distribution and keep only those strictly necessary to runtime and re-augmentation.

### Details

Looks like the best approach should be to exclude these dependencies through Maven (instead of using Quarkus properties such as `quarkus.class-loading.removed-artifacts`).

The proposal is to have a specific profile in the root pom that explicitly excludes the unwanted dependencies. The trade-off here is that we need to make sure the distribution is built using this profile.

### LINKED ISSUE #15870: Cleanup unused WildFly dependencies.
### Description

After the Quarkus based distribution became the new default, we should check, which WildFly dependencies remained unused and we should do a proper cleanup.

### LINKED ISSUE #20570: Use Quarkus Platform BOMs
### Description

To further align with Quarkus, we should be using the Platform BOMs. In particular:
* [`io.quarkus.platform:quarkus-bom`](https://github.com/quarkusio/quarkus-platform/blob/main/generated-platform-project/quarkus/bom/pom.xml)
* [`io.quarkus.platform:quarkus-operator-sdk-bom`](https://github.com/quarkusio/quarkus-platform/blob/main/generated-platform-project/quarkus-operator-sdk/bom/pom.xml). This in particular is important as we won't be no longer specifying an Operator SDK version but rather using the version that comes with a certain Quarkus version.

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes #20570
Closes #15870
Closes #9075

Supersedes https://github.com/keycloak/keycloak/pull/21078
Changes from the original PR:
* Rebased to resolve conflicts
* Quarkus 3.2.0.Final is used instead of 3.2.0.CR1
* I sneaked in more of the dependencies clean-up (to resolve #9075). This could be split into a separate PR if desired.

Umbrella for post-22 follow-up issues: #21356

~~**This is currently blocked as we're waiting for the release of [Quarkus Platform BOM for 3.2.0.Final](https://central.sonatype.com/artifact/io.quarkus.platform/quarkus-bom/3.2.0.Final)**~~

### CODE REVIEW

**Comment by vmuzikar** [comment]
In order to merge this, we need reviews from @keycloak/store and @keycloak/core.

@miquelsi Could you please confirm the QE pipelines are happy with this change?

@ASzc Could you please confirm it's ok for prod?

@abstractj Can you please double check the dependencies upgrades/downgrades are ok from CVEs perspective?

@pedroigor With regards to #9075, I currently went the simple path and excluded the Quarkus dev services on mvn level (without using profiles). Are you aware of any use cases we need the dev services for during development currently?

**Review by sguilhen — APPROVED** [review]
Thsanks @vmuzikar ! I'm ok with the much needed cleanup being in this PR - don't think we need a separate one just for that.

From store perspective, it should be ok!

**Review by ASzc — APPROVED** [review]
I see `com.fasterxml.jackson.core:jackson-core` and `com.fasterxml.jackson.core:jackson-annotations` are being removed? There are some product build parameters related to those two, specifically forcing version `2.13.4.redhat-00002`, I can't remember why. If they're being removed then easy enough to drop these related build parameters too.

I also see there are some new exclusions for deployment dependencies. That's good, in theory should help clean up non-RHBQ jars in our zip.

Otherwise seems ok. Ideally with the volume of pom changes a trial product build would be performed before merging this PR, but we don't have automation for that yet. If you're interested in doing it manually I can guide you, otherwise I'll fix any errors that crop up in the nightly build after this is merged

**Review by abstractj — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]
Reviewed the changes, thank you for this cleanup. I see that the distribution is now down to 168 MB instead of 188 MB, which is great.

I did a short local test, and it looks fine to me. Thanks!

**Review by ahus1 — APPROVED** [review]
Reviewed the changes, thank you for this cleanup. I see that the distribution is now down to 168M instead of 188 MB, which is great.

I did a short local test, and it looks fine to me. Thanks!

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
