### PR TITLE
KEYCLOAK-16464 Allow to map enabled and emailVerified user model attribute to LDAP attributes

### PR DESCRIPTION
**Pull request by thomasdarimont**
What would be the suitable place to add a test for this?

### CODE REVIEW

**Comment by mposolda** [comment]
@thomasdarimont Thanks! The good place for the test may be the package "org.keycloak.testsuite.federation.ldap" .

I am not sure if the "emailVerified" is standardized LDAP attribute or if it is required to do some custom change to the LDAP schema to have it supported? Ideal is, if the test works at least with the ApacheDS server, which is used in the testsuite by default...

**Comment by mposolda** [comment]
@thomasdarimont Another thing: Will it be possibility to add support also for the "enabled" attribute as that one is also boolean property and hence similar case like "emailVerified" ?

**Comment by thomasdarimont** [comment]
@mposolda sure I can give it a try! Thanks for the hint!

**Comment by thomasdarimont** [comment]
@mposolda I just added the support for mapping the `enabled` user attribute to an LDAP attribute as well.

There seems to be no standard LDAP attribute to express a verified email address or an enabled user.
So it seems that this has to be mapped to custom LDAP attributes. However most customers who want full control over 
their LDAP user mapping can also add custom attributes.

Some LDAP implementations like MS AD provide a proprietary way of maintaining the user enabled state.
https://docs.microsoft.com/en-us/windows/win32/adschema/a-msds-useraccountdisabled
http://www.selfadsi.de/ads-attributes/user-userAccountControl.htm

**Comment by mposolda** [comment]
> @mposolda I just added the support for mapping the `enabled` user attribute to an LDAP attribute as well.

Thanks!

> 
> There seems to be no standard LDAP attribute to express a verified email address or an enabled user.
> So it seems that this has to be mapped to custom LDAP attributes. However most customers who want full control over
> their LDAP user mapping can also add custom attributes.

I suppose we can hopefully have an automated test with something like:

- Limit the test to make sure it runs only on the ApacheDS embedded LDAP server. This can be done by adding new class and configure LDAPRule for example like in LDAPLegacyImportTest

- Then check if there is any attribute in ApacheDS, which can be used to map to that. I am using ApacheDirectoryStudio tool and when browsing the "SChema Browser" with this tool, I see that there are for example some attributes like "ads-enabled", which seems that it is available for the class "extensibleObject"

- If the previous option is not great solution, I hope it is possible to use at least some attribute available by default on the default "organizationalPerson" class. For example "description" or "title", and map the attributes to that.

Sorry, but we try to have Keycloak tested as much as possible. Adding each feature, which is not tested, is just a pain in the long run, as it adds bigger probability of the bug/regression in the future and hence it is not ideal for the maintenance perspective...

> 
> Some LDAP implementations like MS AD provide a proprietary way of maintaining the user enabled state.
> https://docs.microsoft.com/en-us/windows/win32/adschema/a-msds-useraccountdisabled
> http://www.selfadsi.de/ads-attributes/user-userAccountControl.htm

Yes, this is something, which we already support (See MSADUserAccountControlStorageMapper).

**Comment by thomasdarimont** [comment]
@mposolda thanks for the useful hints!

I just added the missing test.

For the sake of testing the mapping I just used unused attributes that supported the "true" and "false" values, for this
I bound the `emailVerfied` user property to the `l` LDAP attribute (Location), and the `enabled` user property to the `o` LDAP attribute (organizationName).

**Review by mposolda — APPROVED** [review]
@thomasdarimont Thanks!

**Pull request merged**
