### PR TITLE
Update password-policies.adoc

### LINKED ISSUE #21652: Password regex policy should specify which regex should be used
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

docs

### Describe the bug

There are multiple regex types, and the docs should provide a pointer to the docs.

> Please add that perl regular expressions are required, I wasted 2 and a half hours looking for the right answer, the official documentation should be the source of truth

### Version

nightly

### Expected behavior

Link to the regex docs in Keycloak docs

### Actual behavior

No specific regex syntax named, and no link to docs.

### How to Reproduce?

see docs.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by davidbister**
Closes #21652

Please add that perl regular expressions are required, I wasted 2 and a half hours looking for the right answer, the official documentation should be the source of truth

### CODE REVIEW

**Comment by ahus1** [comment]
Thanks for raising this gap in the documentation. Actually, it is not a Perl regular expression, but a Java variant. See https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html for the documentation. 

Please give that a try. If this works for you, please update the PR, and possibly link to this description.

**Review by andymunro — APPROVED** [review]

**Review by ahus1 — CHANGES_REQUESTED** [review]
(I previously added it as a comment, now adding it as a review comment)

Thanks for raising this gap in the documentation. Actually, it is not a Perl regular expression, but a Java variant. See https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html for the documentation.

Please give that a try. If this works for you, please update the PR, and possibly link to this description.

**Review by ahus1 — COMMENTED** [review]
I've update the docs with the contents from my previous comment.

**Comment by ahus1** [comment]
@keycloak/core-maintainers - could someone from the core team please review this documentation change? Thanks!

**Review by pedroigor — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]

**Comment by ahus1** [comment]
@jonkoops or someone else from the UI team - could you please approve this documentation change from the UI team's perspective? Thanks!

**Review by jonkoops — APPROVED** [review]
LGTM

**Pull request merged**
