### PR TITLE
Enable JPA store for ActionTokenStoreSpi in model tests

### LINKED ISSUE #12902: Run model tests with `ActionTokenStoreSpi` set to JPA provider
This PR didn't enable JPA store for `ActionTokenStoreSpi` it should be changed here: https://github.com/keycloak/keycloak/pull/12339/files#diff-c360bd20f7df79632bef4e7606cec033d07c8a81b07393da61d65d41ac2c3be1R100

### PR DESCRIPTION
**Pull request by sguilhen**
Closes #12902

### CODE REVIEW

**Review by ahus1 — DISMISSED** [review]
LGTM, let's keep the fingers crossed that the build is green.

**Comment by abstractj** [comment]
@sguilhen @ahus1 could you please solve the conflicts?

**Comment by sguilhen** [comment]
@abstractj rebased, need to wait for CI again.

**Review by ahus1 — APPROVED** [review]

**Comment by abstractj** [comment]
No problem, I will check after they pass, so we can merge.

**Pull request merged**
