### PR TITLE
[KEYCLOAK-8768] - Policy evaluation tool failing when client is used and identity.getId is called

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Review by sguilhen — APPROVED** [review]

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Comment by stianst** [comment]
@keycloak-ci-bot test

**Review by stianst — APPROVED** [review]

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Pull request merged**
