### PR TITLE
Add new version of Welcome theme based on PatternFly 5

### LINKED ISSUE #21343: Upgrade welcome theme to PatternFly 5
The welcome theme will have to be upgraded to the latest version of PatternFly. This will take more effort than the other themes, as the welcome theme is still stuck on PatternFly 3.

### PR DESCRIPTION
**Pull request by jonkoops**
Adds a new version of the Welcome theme based on the recently released PatternFly 5. This is meant to be an early version with a basic design that matches the functionality of the original theme, avoiding breaking changes to the Java code that might impact folks extending it.

An improved version will follow later based on a new design.

Closes #21343

### CODE REVIEW

**Review by edewit — DISMISSED** [review]
so the design that kun made will be added later?

**Comment by edewit** [comment]
image

**Comment by jonkoops** [comment]
> so the design that kun made will be added later?

Yeah, that's correct. This PR just implements something bare-bones and similar to the existing welcome theme. Then once we have a solid design we can start making things look a bit better, plus some other tasks.

**Review by ssilvert — CHANGES_REQUESTED** [review]
You already have a link to the admin console before the initial admin user is created.  This should be hidden until the user is created.

**Review by agagancarczyk — APPROVED** [review]
LGTM

**Review by edewit — APPROVED** [review]

**Review by ssilvert — APPROVED** [review]

**Pull request merged**
