### PR TITLE
Bump jboss.marshalling to 2.1.1.Final

### LINKED ISSUE #15607: JDK 17 InaccessibleObjectException with infinispan
### Area

infinispan

### Describe the bug

Using JDK 17 with a Keycloak Cluster (read: infinispan) results in InaccessibleObjectException upon execution of certain kcadm commands, such as adding a new IdentityStorageProvider.

### Version

20.0.1

### Expected behavior

Executing kcadm commands should not fail due to InaccessibleObjectException.

### Actual behavior

Executing an kcadm add ldap storage provider command results in the following stack trace:

```
2022-11-21 22:24:53,211 ERROR [org.infinispan.CLUSTER] (jgroups-12,keycloak1-26964) ISPN000474: Error processing request 150@keycloak2-62845: java.lang.ExceptionInInitializerError
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1268)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1064)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1381)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:298)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:231)
        at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41)
        at org.infinispan.jboss.marshalling.commons.AbstractJBossMarshaller.objectFromObjectStream(AbstractJBossMarshaller.java:137)
        at org.infinispan.jboss.marshalling.commons.AbstractJBossMarshaller.objectFromByteBuffer(AbstractJBossMarshaller.java:115)
        at org.infinispan.commons.marshall.AbstractMarshaller.objectFromByteBuffer(AbstractMarshaller.java:82)
        at org.infinispan.marshall.core.impl.DelegatingUserMarshaller.objectFromByteBuffer(DelegatingUserMarshaller.java:63)
        at org.infinispan.marshall.protostream.impl.MarshallableUserObject$Marshaller.read(MarshallableUserObject.java:139)
        at org.infinispan.marshall.protostream.impl.MarshallableUserObject$Marshaller.read(MarshallableUserObject.java:100)
        at org.infinispan.protostream.impl.ProtobufTagMarshallerDelegate.unmarshall(ProtobufTagMarshallerDelegate.java:32)
        at org.infinispan.protostream.WrappedMessage.readMessage(WrappedMessage.java:539)
        at org.infinispan.protostream.WrappedMessage.read(WrappedMessage.java:351)
        at org.infinispan.protostream.ProtobufUtil.fromWrappedByteArray(ProtobufUtil.java:129)
        at org.infinispan.marshall.protostream.impl.AbstractInternalProtoStreamMarshaller.objectFromByteBuffer(AbstractInternalProtoStreamMarshaller.java:97)
        at org.infinispan.marshall.protostream.impl.AbstractInternalProtoStreamMarshaller.objectFromByteBuffer(AbstractInternalProtoStreamMarshaller.java:92)
        at org.infinispan.marshall.core.GlobalMarshaller.readUnknown(GlobalMarshaller.java:905)
        at org.infinispan.marshall.core.GlobalMarshaller.readUnknown(GlobalMarshaller.java:890)
        at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:714)
        at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
        at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
        at org.keycloak.cluster.infinispan.WrapperClusterEvent$ExternalizerImpl.readObjectVersion1(WrapperClusterEvent.java:145)
        at org.keycloak.cluster.infinispan.WrapperClusterEvent$ExternalizerImpl.readObject(WrapperClusterEvent.java:130)
        at org.keycloak.cluster.infinispan.WrapperClusterEvent$ExternalizerImpl.readObject(WrapperClusterEvent.java:109)
        at org.infinispan.marshall.core.GlobalMarshaller.readAnnotated(GlobalMarshaller.java:735)
        at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:712)
        at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
        at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
        at org.infinispan.commands.write.PutKeyValueCommand.readFrom(PutKeyValueCommand.java:96)
        at org.infinispan.marshall.exts.ReplicableCommandExternalizer.readCommandParameters(ReplicableCommandExternalizer.java:117)
        at org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:106)
        at org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:68)
        at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
        at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
        at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
        at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
        at org.infinispan.commands.remote.SingleRpcCommand.readFrom(SingleRpcCommand.java:56)
        at org.infinispan.marshall.exts.ReplicableCommandExternalizer.readCommandParameters(ReplicableCommandExternalizer.java:117)
        at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.readObject(CacheRpcCommandExternalizer.java:170)
        at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.readObject(CacheRpcCommandExternalizer.java:88)
        at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
        at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
        at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
        at org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
        at org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1455)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1395)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:146)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1586)
        at org.jgroups.JChannel.up(JChannel.java:780)
        at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:913)
        at org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:363)
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:355)
        at org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
        at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
        at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:392)
        at org.jgroups.protocols.pbcast.NAKACK2.deliver(NAKACK2.java:926)
        at org.jgroups.protocols.pbcast.NAKACK2.handleMessage(NAKACK2.java:818)
        at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:602)
        at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
        at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
        at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
        at org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
        at org.jgroups.protocols.Discovery.up(Discovery.java:300)
        at org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
        at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.util.AbstractMap() accessible: module java.base does not "opens java.util" to unnamed module @396a51ab
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
        at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
        at org.jboss.marshalling.reflect.JDKSpecific$SerMethods.<init>(JDKSpecific.java:147)
        at org.jboss.marshalling.reflect.SerializableClass.<init>(SerializableClass.java:84)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:62)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:59)
        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
        at java.base/java.lang.ClassValue.get(ClassValue.java:116)
        at org.jboss.marshalling.reflect.SerializableClassRegistry.lookup(SerializableClassRegistry.java:83)
        at org.jboss.marshalling.reflect.SerializableClass.<init>(SerializableClass.java:76)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:62)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:59)
        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
        at java.base/java.lang.ClassValue.get(ClassValue.java:116)
        at org.jboss.marshalling.reflect.SerializableClassRegistry.lookup(SerializableClassRegistry.java:83)
        at org.jboss.marshalling.river.ClassDescriptors.getSerializableClassDescriptor(ClassDescriptors.java:152)
        at org.jboss.marshalling.river.ClassDescriptors.getSerializableClassDescriptor(ClassDescriptors.java:146)
        at org.jboss.marshalling.river.ClassDescriptors.<clinit>(ClassDescriptors.java:101)
        ... 72 more
```

### How to Reproduce?

I have created a Docker Compose reproducer [GitHub project](https://github.com/slominskir/keycloak_cluster):

1. Grab project
```
git clone -b jdk17_cluster https://github.com/slominskir/keycloak_cluster
cd keycloak_cluster
```

2. Launch Compose
```
docker compose up
```

Watch the log output.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by slominskir**
Closes #15607

### CODE REVIEW

**Review by mposolda — COMMENTED** [review]
Not sure if we can just update this as KEycloak has also dependency on infinispan `14.0.2.Final` and that version has dependency on jboss-marshalling `2.0.12.Final`.

@hmlnarik Can you please check or delegate to someone from storage team?

**Comment by hmlnarik** [comment]
@martin-kanis @mhajas Could you please check if upgrading the jboss-marshalling works correctly with Infinispan upgrade?

**Review by martin-kanis — APPROVED** [review]
I tried on my machine (java 11) both old and new store via model tests and also cluster tests. All good, so approving the PR.

**Comment by abstractj** [comment]
@hmlnarik @martin-kanis my apologies for the confusion here. I performed another round with security, scanners now manually and could not find any outstanding CVEs.

@hmlnarik thanks for bringing this to my attention. For now, I'm removing the relevant labels.

**Review by martin-kanis — CHANGES_REQUESTED** [review]
Actually `<jboss.marshalling.version>` isn't correct maven property. `jboss-marshalling-osgi` artifact is transitively coming from Infinispan and we don't specify the version. See part of the dependency tree.
+- org.infinispan:infinispan-jboss-marshalling:jar:14.0.2.Final:compile
        \- org.jboss.marshalling:jboss-marshalling-osgi:jar:2.0.12.Final:compile

In order the override the version, we would need to specifiy the GAV in our poms. But I would argue this bug should be filed on Infinispan side.

**Comment by martin-kanis** [comment]
Closing for now. Explained in the linked issue.

**Pull request closed without merging**
