### PR TITLE
[KEYCLOAK-16928] Typo in the Authenticator Flow

### PR DESCRIPTION
**Pull request by abstractj**
@mposolda that's a simple fix, it's just a minor typo. But worth to consider that this will be a breaking changes for clients referring to this.

### CODE REVIEW

**Review by sguilhen — APPROVED** [review]

**Review by mposolda — CHANGES_REQUESTED** [review]
@abstractj It seems that this can be a breaking change for the migration. We have the contract that realm JSON files exported in previous versions must be possible to import into the new version.

In this PR, you are renaming the fields in the JSON files for the migration tests (EG. migration-realm-9.0.3.json). This is exactly something, which shouldn't be done IMO because the JSON files exported in 9.0.3 will have the field like "autheticatorFlow" and they likely will fail to be imported to the newest Keycloak with this change.

It will be ideal if JSON import still works without any changes needed in the files like "migration-realm-*.json" or any other JSON files. Looks that it may be needed to have some "Deprecated" fields in the representation objects and make sure that JSON import is able to deal with this and import the stuff from the deprecated fields. We are doing something similar on couple of places. For example see deprecated fields on the RealmRepresentation class.

**Comment by abstractj** [comment]
Thanks, @mposolda. I completely agree with you and what you said makes sense to me. Before move forward, let me try to summarize:

1. Migrations must be updated to make sure that these breaking changes, won't break the realm import from one Keycloak server to another.
2. These fields with the typo must be deprecated and a new field without the typo introduced

I will look into `RealmRepresentation`, but despite the changes required and all the breaking changes. Are you ok with the idea of refactoring and fixing this typo?

**Comment by mposolda** [comment]
@abstractj Yes, I think your summary is fine.

Another perspective how to look at this: I think we are fine if this PR doesn't need to change anything in any of the files migration-realm-*.json and tests still work even if nothing is changed in those files.

**Review by slaskawi — APPROVED** [review]

**Review by vramik — CHANGES_REQUESTED** [review]
@abstractj thanks for the PR, @mposolda is right, imo we should introduce migration step when importing older realm.json to ensure all `"autheticatorFlow"` from the json will end up in `authenticatorFlow`.

**Comment by mposolda** [comment]
@abstractj Any update or should this PR be closed and we just live with the typo?

I understand typo is not ideal, but on the other hand, it is not "real" bug. However fixing typo can introduce "real" bugs for the migrations etc. unless they are not addressed in this PR.

**Comment by slaskawi** [comment]
@abstractj rebase please?

**Comment by mposolda** [comment]
@abstractj I am closing this as it is low priority and there is most likely potential migration issue. Feel free to re-open whenever you have some additional concerns for this and potential migration issues are addressed.

**Pull request closed without merging**
