### PR TITLE
KEYCLOAK-16534 -> New quickstarts scripts folder.

### PR DESCRIPTION
**Pull request by lhanusov**
@vmuzikar @pdrozd

### CODE REVIEW

**Comment by vmuzikar** [comment]
Needs to be merged with https://github.com/keycloak/keycloak-quickstarts/pull/251

**Review by vmuzikar — DISMISSED** [review]

**Review by abstractj — APPROVED** [review]

**Review by abstractj — COMMENTED** [review]
@lhanusov @vmuzikar I noticed some failures after merging the PR on the Quickstarts repository:

```
/home/runner/work/_temp/6b3acd40-033b-4a1d-a154-4b22d2a51e1c.sh: line 1: scripts/build-quickstarts.sh: No such file or directory
Error: Process completed with exit code 127.
```

**Comment by vmuzikar** [comment]
@abstractj Could you please re-run the GH Actions? It seems that it failed because keycloak/keycloak-quickstarts#251 was not merged yet.

**Comment by abstractj** [comment]
@vmuzikar I done after the merge, but let's try again.

**Comment by abstractj** [comment]
@vmuzikar @lhanusov tests are still failing here https://github.com/keycloak/keycloak/pull/8212/checks?check_run_id=3010055456

**Review by abstractj — CHANGES_REQUESTED** [review]
Please review the comments above.

**Comment by lhanusov** [comment]
@vmuzikar @abstractj I found that the checkout branch was master not "latest". I pushed the changes to Github recently.

**Comment by lhanusov** [comment]
related PRs: https://github.com/keycloak/keycloak-quickstarts/pull/253, https://github.com/keycloak/keycloak-quickstarts/pull/254

**Review by abstractj — APPROVED** [review]

**Comment by abstractj** [comment]
Thank you @lhanusov

**Pull request merged**
