### PR TITLE
Execute Aurora DB cleanup in a separate workflow to prevent timeout o…

### LINKED ISSUE #803: Pending VPC after Aurora test
### Describe the bug

There is a left-over VPC vpc-0e19cb27c5d005238 named Aurora Cluster gh-action-217987b in eu-east-1 which is left-over

### Version

main

### Expected behavior

There shouldn't be a left-over VPC after the run

### Actual behavior

There is one left-over

### How to Reproduce?

Unclear, needs to be investigated

### Anything else?

https://github.com/keycloak/keycloak-benchmark/actions/runs/8992235578/job/24704996505

### PR DESCRIPTION
**Pull request by ryanemerson**
Fixes keycloak/keycloak-benchmark#803

I've also removed calls to delete Aurora from the `persistent-sessions-tests` job as this job doesn't create any Aurora resources.

### CODE REVIEW

**Comment by ahus1** [comment]
@ryanemerson - could you please add a link to a test you can in your personal repository?

**Comment by ahus1** [comment]
Rebased as agreed with the UI team to make the admin test succeed.

**Comment by ryanemerson** [comment]
Here's the latest run from my fork after your rebase: https://github.com/ryanemerson/keycloak/actions/runs/9170679505

**Comment by ahus1** [comment]
I found https://github.com/ryanemerson/keycloak/actions/runs/9160170631 in your repository from a previous run, looks good to me. Thanks!

**Review by ahus1 — APPROVED** [review]

**Comment by ryanemerson** [comment]
Good point! https://github.com/keycloak/keycloak/pull/29938

**Pull request merged**
