### PR TITLE
Return location for execution/flow creation

### PR DESCRIPTION
**Pull request by josh-cain**
This pull request does 3 things:

- Returns flow location header on creation
- Returns execution location header on creation
- Adds method whereby executions can be retrieved by ID

### CODE REVIEW

**Comment by cainj13** [comment]
What on earth is happening with these tests?  I've got a failure on testPostEncryptedLoginLogout where it cannot validate the token.  Wonder if I'm missing some Travis environment configs...

**Comment by mposolda** [comment]
@cainj13 It's just unstable test. Not your fault. I've rerun the test and hopefully next time will be successful :)

**Comment by mposolda** [comment]
Any chance you can update also admin client? Interface org.keycloak.admin.client.resource.AuthenticationManagementResource and method "addExecution" there and add "Response" as returning type?  

My vote is to keep method name to "addExecution" . Agree that "addExecutionToFlow" is better name, however it doesn't worth to break backwards compatibility IMO and will be good to keep the name of the method on admin-client and REST endpoint consistent.

**Comment by cainj13** [comment]
I originally left the name as "addExecution".  However, since there was a duplicate method name, I couldn't use the uriBuilder tools to derive the @Path that was defined for that particular method (thereby allowing me to get a relative url path for the Auth configuration endpoint).

If you wanted to use a more static definition for the created Location url, I could change the name back.  Otherwise we're going to have to use a more static definition of the created URL that could break if the @Path were to ever change.  Very low likelihood, but a tradeoff.

Let me know which you prefer - more hard-coded-y @Path, or a signature change.  And I'll get the admin client updated as well.

**Comment by mposolda** [comment]
@cainj13 ah I see. Ok, renaming both "addExecutionToFlow" should be fine.

**Comment by cainj13** [comment]
Updated admin client.

**Comment by mposolda** [comment]
@cainj13 tests passed and PR looks good. Thanks. Could you please also create JIRA?

**Comment by cainj13** [comment]
@mposolda done.  [KEYCLOAK-6710](https://issues.jboss.org/browse/KEYCLOAK-6710)

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
@cainj13 Thanks

**Pull request merged**
