### PR TITLE
update keycloak-admin-client resteasy version to 4

### LINKED ISSUE #14208: Upgrade Resteasy v4 keycloak-admin-client
### Description

* `keycloak-admin-client` still uses resteasy version 3
* Would be nice to have the same resteasy version in the whole project
* See #10916 as well.

### PR DESCRIPTION
**Pull request by benjamin37**
Fixes  #14208

### CODE REVIEW

**Review by sschu — APPROVED** [review]

**Comment by sschu** [comment]
@mposolda Changes look good to me. Operator test seems to be unstable and in the base testsuite run, there was a connectivity issue with `repo.maven.apache.org`. Maybe rerun that part?

**Comment by mposolda** [comment]
@sschu Looks good to me as long as testa are ok.

@pedroigor Do you see any issue with this update?

**Review by pedroigor — APPROVED** [review]
TBH, I don't. But I'm trying to remember why I did not update this module when doing https://github.com/keycloak/keycloak/pull/10917.

Looks like I missed it.

@benjamin37 Would you please send a PR to keycloak-documentation to mention this change in the upgrade guide?

**Comment by benjamin37** [comment]
@pedroigor Created a PR for the keycloak-documentation. Not entirely sure what to mention there exactly though.

https://github.com/keycloak/keycloak-documentation/pull/1679

**Comment by pedroigor** [comment]
@benjamin37 Thanks.

**Pull request merged**
