### PR TITLE
Fix https://issues.jboss.org/browse/KEYCLOAK-3471

### PR DESCRIPTION
**Pull request by ebondu**

### CODE REVIEW

**Comment by ebondu** [comment]
There is a missing class for this PR (KeycloakAuthenticationFailureHandler) that has been added in https://github.com/keycloak/keycloak/pull/3741. Should be OK if https://github.com/keycloak/keycloak/pull/3741 is accepted first.

**Comment by trecloux** [comment]
I'm also facing the issue described in KEYCLOAK-3471.
How can I help progress on this topic ?

**Comment by stianst** [comment]
@sebastienblanc will review this PR and we'll merge if it's all good. @trecloux if you can try it out and see if this PR fixes your issue as well that'd be great.

**Comment by trecloux** [comment]
@sebastienblanc Do you need any help ?

**Comment by sebastienblanc** [comment]
@ebondu @trecloux I'm about to test the PR , could you tell me first how to reproduce the issue ?

**Comment by sebastienblanc** [comment]
@ebondu could you also rebase your branch ?

**Comment by ebondu** [comment]
On my side, the bug appends when I am using the authentication filter (KeycloakAuthenticationProcessingFilter) inside a spring web app.

**Comment by sebastienblanc** [comment]
@ebondu do you have maybe a sample app ? I have a simple spring app that uses the filter but not sure how to reproduce exactly your issue. 
Anyway, https://github.com/keycloak/keycloak/pull/3741 must be merged first , correct ?

**Comment by ebondu** [comment]
Yes, #3741 must be merged first (missing class).

**Comment by trecloux** [comment]
@sebastienblanc : Here is a sample app 
https://github.com/trecloux/spring-keycloak-classcastexception
You need to configure keycloack url, realm and client id in the application.yaml configuration file.

**Comment by sebastienblanc** [comment]
@trecloux Thanks that will be really helpful to fully understand the bug and the fix !

**Comment by rafterhuang** [comment]
Hello,

Same issue looks in 3.1.0 FINAL, when can we expect this being fixed?

Thanks,
Rong

**Comment by stianst** [comment]
@sebastienblanc any updates on reviewing this?

**Comment by sebastienblanc** [comment]
@stianst https://github.com/keycloak/keycloak/pull/3741 must be cleaned up and merged first, no news from @ebondu yet, let me see if I can sometihng about it.

**Comment by sebastienblanc** [comment]
So I rebased this PR here https://github.com/sebastienblanc/keycloak/tree/KEYCLOAK-3471 and tried the sample app from @trecloux but I'm still seeing a class cast exception https://gist.github.com/sebastienblanc/08b2689f78dbb40e7fb727955862bf41 , maybe @trecloux you have an idea ?

**Comment by ebondu** [comment]
I just reviewed the PR and it should be ok. Are we sure the modification has been taken in account in the sample app ?

**Comment by ebondu** [comment]
I just tried the sample app and it seems the error is gone. Here are the steps I followed to test the app : 
- I checked out the branch https://github.com/sebastienblanc/keycloak/tree/KEYCLOAK-3471
- I installed all KC libs the in my maven repo as 3.2.0.CR1-SNAPSHOT (mvn install)
- I updated the sample project pom to get dependencies pointing to 3.2.0.CR1-SNAPSHOT
- I change the code to be able to compile the app (KeycloakSpringBootConfiguration -> KeycloakAutoConfiguration)
- I started the spring-boot app.

I can see the login page and then I get a 401 (instead of the 500)

**Comment by sebastienblanc** [comment]
Okay, I retried and now I'm always getting a 401 , I got never redirected to the login page, looks like the same issue as @scranen is seeing here https://github.com/keycloak/keycloak/pull/4167#issuecomment-306431191 , this is a serious regression right now, any idea what is happening ?

**Comment by sebastienblanc** [comment]
BTW I rebased again https://github.com/sebastienblanc/keycloak/tree/KEYCLOAK-3471

**Comment by ebondu** [comment]
The redirection to the login page make sense for a web application but not for a REST API so I guess the expected behavior will depends on the scenario. The default behavior should not have changed since the addition of the spring error handler (401 was the default code returned without the error handler?). To allow a redirection to the login page I think the simplest way is to define and register your own error handler that will not send the 401 code but a 302 ?

**Comment by sebastienblanc** [comment]
if it's configured as `bearer-only` then 401 otherwise it's a redirect, in the sample app (and an other app I tested) it's not a bearer-only app and I should have a redirect and not a 401, that should be the default behavior and I should not have to register my own error handler.

**Comment by scranen** [comment]
The redirect is an OAuth redirect; the construction of this URL is something that should probably remain encapsulated in `OAuthRequestAuthenticator`. I think what's unclear here is the expected behaviour of the `challenge`. IMO, if the `challenge` returns `true`, meaning that the response was changed in a way that the `challenge` deemed appropriate, then the request is dealt with and we should not throw an `AuthenticationException` (this is not an exception flow). If I don't want the redirect to be sent, then I should be using an `Authenticator` that is configured not to send redirects.

**Comment by ebondu** [comment]
This discussion should be done in https://github.com/keycloak/keycloak/pull/4167 ?

**Comment by ebondu** [comment]
@trecloux if we have no cast exception can we say https://issues.jboss.org/browse/KEYCLOAK-3471 is solved by this PR ?

**Comment by sebastienblanc** [comment]
@ebondu let continue the discussion on https://github.com/keycloak/keycloak/pull/4167

**Comment by trecloux** [comment]
@sebastienblanc I'm still facing this ClassCastException with V3.2.0
```
java.lang.ClassCastException: org.keycloak.adapters.springsecurity.account.SimpleKeycloakAccount cannot be cast to org.keycloak.KeycloakSecurityContext
	at org.keycloak.adapters.springsecurity.facade.SimpleHttpFacade.getSecurityContext(SimpleHttpFacade.java:60) ~[keycloak-spring-security-adapter-3.2.0.Final.jar:3.2.0.Final]
	
```
Can I submit a pull request scoped to this issue ?

**Comment by trecloux** [comment]
Just in case, the fix is ready : https://github.com/trecloux/keycloak/commit/114e5cc47d1ff16102729213baec1fb3ae4bea71 :-)

**Comment by sebastienblanc** [comment]
Sure submit the PR and update the jira ticket please, thx!

Envoyé de mon iPhone

**Comment by trecloux** [comment]
Should it be against master or 3.2.x ?

**Comment by sebastienblanc** [comment]
No idea if we will do a 3.2.3 , if you don't bother can you open 2 PRs ,
one against master and another against 3.2.x ?

**Comment by trecloux** [comment]
Just created #4343 and #4344

**Comment by stianst** [comment]
What's going on with this PR? There's https://github.com/keycloak/keycloak/pull/4343 that is already merged, does that fix KEYCLOAK-3471 or are there still issues here?

**Comment by sebastienblanc** [comment]
@stianst yes you can close this PR

**Pull request closed without merging**
