### PR TITLE
Fix: Added LDSigningServiceProvider entry for LD-Credentials/VCDM

### LINKED ISSUE #25943: Issue Verifiable Credentials in the VCDM format
### Description

Keycloak should support the creation of Verifiable credentials in the [W3C Verfiable Credentials Data Format(VCDM)](https://www.w3.org/TR/vc-data-model/). The format encodes Verifiable Credentials in the [JSON-LD Format](https://json-ld.org/). An example would be: 

```json
{
    "type" : [ "VerifiableCredential" ],
    "@context" : [ "https://www.w3.org/2018/credentials/v1", "https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#", "https://w3id.org/security/suites/jws-2020/v1" ],
    "id" : "urn:uuid:a4c51032-1aab-46ba-8f51-68210a60cc27",
    "issuer" : "did:web:animalgoods.gaia-x.fiware.dev:did",
    "issuanceDate" : "2023-04-26T09:17:52Z",
    "issued" : "2023-04-26T09:17:52Z",
    "validFrom" : "2023-04-26T09:17:52Z",
    "expirationDate" : "2023-04-28T21:17:52Z",
    "credentialSubject" : {
        "id" : "did:web:animalgoods.gaia-x.fiware.dev:did",
        "type" : "gx:LegalParticipant",
        "gx:legalName" : "Animal Goods Org.",
        "gx:legalRegistrationNumber" : {
        "gx:vatID" : "MYVATID"
        },
        "gx:headquarterAddress" : {
        "gx:countrySubdivisionCode" : "BE-BRU"
        },
        "gx:legalAddress" : {
        "gx:countrySubdivisionCode" : "BE-BRU"
        },
        "gx-terms-and-conditions:gaiaxTermsAndConditions" : "70c1d713215f95191a11d38fe2341faed27d19e083917bc8732ca4fea4976700"
    },
    "proof" : {
        "type" : "JsonWebSignature2020",
        "creator" : "did:web:animalgoods.gaia-x.fiware.dev:did",
        "created" : "2023-04-26T09:17:52Z",
        "verificationMethod" : "did:web:animalgoods.gaia-x.fiware.dev:did#e1b0c827edd5446ebb830d9a8b9b748c",
        "jws" : "eyJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdLCJhbGciOiJQUzI1NiJ9..SGj9KmaiowH2NOVJtWDN9tnAN4MivHJ2QdijCbTv-7V3ZXXtXrLI7qNkOMyxX9LwJv83S6USWFNoqWiluB8CiGYkfFe1FexqWBbodIIqxCM0xO7k2y78Zy_aMTjWkcFuKeGtELL6VeBnQglQauAOMOX60_-TRxNp96K8bJ-8O7EfJQhJnDVq5Dx6XE6oG4_vQyeDPafxb1_JmtjqG0aZ5b8ZRjPYkCYzpeomV4hAtOCT8xN7W6d7vAw07IeVZ_mcvk4OmS6hKND2x3g_gLfroTf43kx0sI-HeD6x4F3wCb_yFvxzolXZ4yI-f-JHalTwFuLJUKlrhNPsjse1eqRGCQ"
    }
}
```

### Discussion

https://github.com/keycloak/keycloak/discussions?discussions_q=is%3Aopen+label%3Aarea%2Foid4vc

### Motivation

The format is currently mentioned or mandated by various relevant projects:
* [EBSI](https://ec.europa.eu/digital-building-blocks/wikis/pages/viewpage.action?pageId=555222155)
* [Gaia-X](https://gaia-x.eu/wp-content/uploads/2022/06/SSI_White_Paper_Design_Final_EN.pdf)
* [DOME-Reference Architecture](https://docs.google.com/document/d/1tzZ_TstAqcBKKyySnSgKAu3ntlPYjtBg/edit#heading=h.30j0zll)
* [i4Trust](https://i4trust.github.io/building-blocks/docs/i4Trust-BuildingBlocks_v4.0.pdf)
* [DSBA Technical Convergence](https://data-spaces-business-alliance.eu/wp-content/uploads/dlm_uploads/Data-Spaces-Business-Alliance-Technical-Convergence-V2.pdf)

### Details

_No response_

### LINKED ISSUE #29885: Unable to create an  LD-Credentials/VCDM provider for OID4VC
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oid4vc

### Describe the bug

Error when importing a JSON-LD Credentials provider within an OID4VC Realm.

### Version

not yet released

### Regression

- [ ] The issue is a regression

### Expected behavior

Successful import of the Verifiable Credentials Signing Service.

### Actual behavior

```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.IllegalArgumentException: No such provider 'ldp_vc'
	at org.keycloak.models.utils.ComponentUtil.getComponentFactory(ComponentUtil.java:87)
	at org.keycloak.models.utils.ComponentUtil.getComponentFactory(ComponentUtil.java:57)
```

### How to Reproduce?

Issue can be replicated by attempting to  to import a VerifiableCredentialSigningService with `"providerId": "ldp_vc"`
Corresponding to LD-Credentials.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by BaptisteMcDonald**
Added a small missing entry for  LDSigningServiceProvider
Closes #29885

### CODE REVIEW

**Review by ahus1 — CHANGES_REQUESTED** [review]
The issue referenced in this PR is already closed. It would be good to have a new issue here. 

I also see that the commit is missing a sign-off. 

@wistefan - as you created the original PR, do agree with the change and could you review it?

**Review by wistefan — APPROVED** [review]
@ahus1 LGTM , I already planned to do that fix myself:) Thanks @BaptisteMcd

**Comment by BaptisteMcd** [comment]
Thank you !

**Comment by ahus1** [comment]
@BaptisteMcd - so the minimum fix for this PR is to get the sign-off right, and a new (bug) issue would be appreciated.

From the CONTRIBUTING.md: 

### Developer's Certificate of Origin

Any contributions to Keycloak must only contain code that can legally be contributed to Keycloak, and which the Keycloak
project can distribute under its license.

Prior to contributing to Keycloak please read the [Developer's Certificate of Origin](https://developercertificate.org/)
and sign-off all commits with the `--signoff` option provided by `git commit`. For example:

```
git commit --signoff --message "This is the commit message"
```

**Comment by mposolda** [comment]
@BaptisteMcd To the points mentioned by @ahus1, I can add that for tracking purposes it can be also useful if the issue has label `area/oid4vci` on it (you can achieve this by select corresponding "area" when creating the issue). Also can be useful to add it to the epic https://github.com/keycloak/keycloak/issues/25936 (It is possibe you may not be able to do that, but I can possibly do it once issue is created).

**Comment by BaptisteMcd** [comment]
I created an issue (#29885) and added my signoff.
Shall you add the epic @mposolda ?

**Comment by ahus1** [comment]
I've added it to the epic

**Review by ahus1 — APPROVED** [review]

**Comment by BaptisteMcd** [comment]
Thanks!

**Pull request merged**
