### PR TITLE
Replace occurrences of getParameterTypes().length and getParameters()…

### LINKED ISSUE #10333: getParameterCount() can be used instead of getParameterTypes().length and getParameters().length
### Description

Replace occurrences of `getParameterTypes().length` and `getParameters().length` with `getParameterCount()`.

```
Targets
    Occurrences of 'getParameterTypes().length' in Project
Found Occurrences in Project  (9 usages found)
    Production  (8 usages found)
        Unclassified  (8 usages found)
            keycloak-common  (2 usages found)
                org.keycloak.common.util.reflections  (2 usages found)
                    Types.java  (2 usages found)
                        isCompatible(Method, Method)  (2 usages found)
                            166 if (method.getParameterCount() != intfMethod.getParameterTypes().length) return false;
                            168 for (int i = 0; i < method.getParameterTypes().length; i++)
            keycloak-ldap-federation  (1 usage found)
                org.keycloak.storage.ldap  (1 usage found)
                    LDAPUtils.java  (1 usage found)
                        getUserModelProperties()  (1 usage found)
                            326 && m.getParameterTypes().length > 0) {
            keycloak-oidc-client-adapter-pom  (1 usage found)
                adapters/oidc/as7-eap6/as7-adapter-spi/src/main/java/org/keycloak/adapters/jbossweb  (1 usage found)
                    JBossWebPrincipalFactory.java  (1 usage found)
                        findJBossGenericPrincipalConstructor()  (1 usage found)
                            166 if (c.getParameterTypes().length == 9 &&
            keycloak-server-spi-private  (4 usages found)
                org.keycloak.models.utils.reflection  (4 usages found)
                    MethodPropertyImpl.java  (4 usages found)
                        MethodPropertyImpl(Method)  (2 usages found)
                            52 } else if (method.getParameterTypes().length > 0) {
                            62 } else if (method.getParameterTypes().length != 1) {
                        getSetterMethod(Class<?>, String)  (1 usage found)
                            154 if (methodName.startsWith(SETTER_METHOD_PREFIX) && method.getParameterTypes().length == 1) {
                        getGetterMethod(Class<?>, String)  (1 usage found)
                            166 if (method.getParameterTypes().length == 0) {
    Test  (1 usage found)
        Unclassified  (1 usage found)
            integration-arquillian-tests-base  (1 usage found)
                org.keycloak.testsuite.migration.cluster  (1 usage found)
                    MultiVersionClusterTest.java  (1 usage found)
                        createCacheAndGetFromServer(ContainerInfo)  (1 usage found)
                            279 .anyMatch(c -> c.getParameterTypes().length == 0 )) {

Targets
    Occurrences of 'getParameters().length' in Project
Found Occurrences in Project  (1 usage found)
    Test  (1 usage found)
        Unclassified  (1 usage found)
            integration-arquillian-tests-base  (1 usage found)
                org.keycloak.testsuite.admin  (1 usage found)
                    PermissionsTest.java  (1 usage found)
                        assertGettersEmpty(Object, String...)  (1 usage found)
                            1976 if (m.getParameters().length == 0 && m.getName().startsWith("get") && !ignoreList.contains(m.getName())) {

```

### Discussion

_No response_

### Motivation

`getParameterTypes().length` and `getParameters().length` are inefficient because they create an array clone, while `getParameterCount()` directly returns the length.

### Details

_No response_

### PR DESCRIPTION
**Pull request by clara0**
….length with getParameterCount()

Closes #10333

### CODE REVIEW

**Comment by ahus1** [comment]
The changes look good. I'll ask a maintainer to approve the workflow runs. When they're green, I'll approve the PR.

**Comment by ahus1** [comment]
@abstractj - could you please approve the workflow runs on this PR? Thanks!

**Review by ahus1 — DISMISSED** [review]
The changes look good to me, and the CI/CD is good. The Operator build failed, and looking at the log this is unrelated.

**Comment by ahus1** [comment]
Hi @mposolda - as I labeled this PR as "area/core", I ping you for this issue. Please feel free to comment. 

At the same time: @hmlnarik - would you be ready to merge this, or do you want to wait for Marek to have a look? Thanks!

**Comment by abstractj** [comment]
@clara0 would you mind rebasing your changes against `main`? That's only to make sure that all the checks will pass.

**Comment by clara0** [comment]
@abstractj Ok, I've rebased the changes now.

**Comment by ahus1** [comment]
@abstractj - could you please re-approve the workflows, as they won't run automatically for first-time contributors to this repository? Thanks!

**Review by ahus1 — APPROVED** [review]

**Review by hmlnarik — APPROVED** [review]

**Comment by ahus1** [comment]
@clara0 - To add on that, this is totally our fault that our docs and pom.xml don't match, and that our build doesn't check API compatibility. I opened another issue for that #10842.

**Comment by clara0** [comment]
@ahus ok, thank you for taking care of this!

**Pull request merged**
