### PR TITLE
Add Migration Tests to CI workflow

### PR DESCRIPTION
**Pull request by lhanusov**

### CODE REVIEW

**Comment by lhanusov** [comment]
@miquelsi @mposolda @mhajas ready for review

**Review by miquelsi — APPROVED** [review]

**Comment by mabartos** [comment]
@lhanusov Just out of curiosity; why does the execution of migration tests with Oracle take 24m when for the other DBs it takes ~5m?

**Comment by miquelsi** [comment]
> @lhanusov Just out of curiosity; why does the execution of migration tests with Oracle take 24m when for the other DBs it takes ~5m?

It's using an Oracle 19c enterprise edition image, which takes quite longer to start up (around 15 minutes).

**Review by mposolda — APPROVED** [review]
@lhanusov Thanks!

**Review by mposolda — APPROVED** [review]

**Pull request merged**
