### PR TITLE
Ensure the SAML Galleon feature pack generates an appropriate licenses file

### LINKED ISSUE #22623: The SAML adapter galleon feature pack should generate an appropriate licenses file
### Description

When provisioning a WildFly server using the SAML adapter Galleon feature pack, an appropriate licenses file should be generated (e.g., `keycloak-saml-adapter-galleon-pack-licenses.xml`).

### PR DESCRIPTION
**Pull request by fjuma**
Closes https://github.com/keycloak/keycloak/issues/22623

### CODE REVIEW

**Review by jfdenise — CHANGES_REQUESTED** [review]

**Comment by jfdenise** [comment]
@fjuma , I opened a PR against your branch with my findings: https://github.com/fjuma/keycloak/pull/1

**Review by jfdenise — APPROVED** [review]

**Comment by fjuma** [comment]
Thanks very much @jfdenise! I've merged your changes.

@pedroigor / @pskopek When you get a chance, please review this one, thanks!

**Review by pedroigor — APPROVED** [review]
LGTM.

Failures are unrelated. Rebased the PR and re-running tests.

**Comment by pskopek** [comment]
@fjuma I have cherry-picked your commits to my PR #22824 as it need to go in together.
Can you review it an close this PR, please?

**Comment by fjuma** [comment]
I've reviewed https://github.com/keycloak/keycloak/pull/22824 so am closing this PR now. Thanks!

**Pull request closed without merging**
