### PR TITLE
Fix URL endpoint for Docker registry v2 authentication

### LINKED ISSUE #29132: Documentation cites wrong endpoint for Docker Registry v2 Authentication
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

Chapter [_Keycloak Docker Registry v2 Authentication Server URI Endpoints_](https://www.keycloak.org/docs/latest/server_admin/index.html#keycloak-docker-registry-v2-authentication-server-uri-endpoints) in the current _Server Administration Guide_ cites the endpoint

```
http(s)://authserver.host/realms/{realm-name}/protocol/docker-v2
```

However, empirical evidence from testing with Keycloak 24.0.3, other points in the documentation, and the Keycloak [source code](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/docker/installation/DockerRegistryConfigFileInstallationProvider.java#L46-L46) suggest it should refer to

```
http(s)://authserver.host/realms/{realm-name}/protocol/docker-v2/auth

```

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

`docker login` (and `podman login`) should succeed for a Docker/OCI registry that uses the cited endpoint for its OAuth2 authentication.

### Actual behavior

`docker login` (and `podman login`) fails.

### How to Reproduce?

Configure a [`registry:2`](https://hub.docker.com/_/registry) container image with the endpoint as its `REGISTRY_AUTH_TOKEN_REALM` and check whether `docker login` (or `podman login`) work.

### Anything else?

Please let me know if you want me to prepare a PR.

### PR DESCRIPTION
**Pull request by christian-2**
Closes #29132

### CODE REVIEW

**Review by rmartinc — APPROVED** [review]
Thanks or sending the PR @christian-2! LGTM!

**Review by rmartinc — CHANGES_REQUESTED** [review]
Just one comment, can you please modify the commit with the `--signoff` option? we need this to pass the DCO tests.

```
git commit --signoff --amend
```

And just re-push force the PR.

Thanks!

**Comment by christian-2** [comment]
@rmartinc Done. (I had previously just copy-pasted the sign-off text into the commit message.)

**Review by ahus1 — APPROVED** [review]
Approving as @rmartinc's review comments have been addressed. Thanks!

**Pull request merged**
