### PR TITLE
KEYCLOAK-18848 KEYCLOAK-18850 Enable CIBA and PAR by default

### PR DESCRIPTION
**Pull request by mposolda**

### CODE REVIEW

**Comment by mposolda** [comment]
@pedroigor @tnorimat Do you please have a chance to review this PR?

I've used single PR for both things to avoid conflicts, which would likely happen if those are sent as separate PRs due the Profile and ProfileTest classes. And we know that we need both PAR and CIBA as default features.

**Comment by tnorimat** [comment]
@mposolda I see. I'll review this PR.

**Review by tnorimat — CHANGES_REQUESTED** [review]
LGTM. I have one comment.
It might be better to purge the following. WDYT?
https://github.com/keycloak/keycloak/blob/f154b0b20993aac9d5b4d30f255236aa0e3e788a/services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientAuthenticator.java#L281

**Comment by mposolda** [comment]
> LGTM. I have one comment.
> It might be better to purge the following. WDYT?
> 
> https://github.com/keycloak/keycloak/blob/f154b0b20993aac9d5b4d30f255236aa0e3e788a/services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientAuthenticator.java#L281

Maybe yes, since we have the same for PAR and features are enabled by default. I changed it as you suggested.

**Review by tnorimat — APPROVED** [review]
LGTM

**Review by pedroigor — APPROVED** [review]

**Comment by mposolda** [comment]
@pedroigor @tnorimat Thanks!

**Pull request merged**
