### PR TITLE
Prevent concurrent session cleanup on different instances in the cluster

### LINKED ISSUE #22198: User session expire task shouldn't run concurrently in a cluster
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

The `ClearExpiredUserSessions` will run eventually `JpaUserSesionPersisterProvider#removeExpired()` which touches the database. 

It shouldn't do this concurrently in a cluster as it will purge the same data from the database, and will likely cause locking (and maybe even deadlocks) in the database

### Version

main

### Expected behavior

The task should run - like other tasks - cluster aware.

### Actual behavior

The task runs concurrently on different nodes

### How to Reproduce?

- 

### Anything else?

I'll prepare a pull request.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #22198

### CODE REVIEW

**Comment by ahus1** [comment]
The unreported flaky was reported previously in #22243, so it is unrelated to this change. I ran it locally multiple times without being able to reproduce it.

**Comment by mhajas** [comment]
Thank you @ahus1, nice catch. This seems like the correct thing to do.

I tried to track why `ScheduledTaskRunner` was used, and it seems it was changed from `ClusterAwareScheduledTaskRunner` to `ScheduledTaskRunner` here: https://github.com/keycloak/keycloak/pull/3511/files#diff-c5ac0bf69a5ce4796ee527c633a6422baa9281e1e74dbcd086029ee73391f779

The PR is quite big and I didn't go through it properly, however, I don't see any reason for this change. It seems irrelevant to the issue the PR is fixing, so I am leaning towards merging this.

Any thoughts @ahus1 @mposolda?

**Comment by ahus1** [comment]
@mhajas - thank you for tracking this down.

I have been looking at the current code, and all activities in `ClearExpiredUserSessions` don't do anything on the Infinispan parts as they rely only the expiry via Infinispan (they are no-ops).

The only activities happening there are `UserSessionPersisterProvider`, which eventually end up in `JpaUserSessionPersisterProvider`. 

So given these implementations, it is IMHO safe to proceed, as there is no need to execute it in parallel on all nodes (and it would actually be harmful for the JPA implementation, as stated in the related ticket).

**Comment by mposolda** [comment]
@ahus1 @mhajas It's long ago and I don't recall exactly, but AFAIR when this commit was done https://github.com/keycloak/keycloak/pull/3511/files#diff-cd5a52710a689873698d76128144c7f52bf6baffe2a4855f6f3b59c1e3f92ef0, we did not relied on infinispan expiration, but we had our own expiration task and triggered expiration manually. And I think that with distributable session caches, every node was responsible to cleanup just the sessions owned by him (the session entities where particular node was primary owner). This was later changed to rely on infinispan expiration (AFAIR it probably happened during initial cross-dc work somewhen in 2017).

**Comment by mhajas** [comment]
Thanks for the response @mposolda!

**Review by mhajas — APPROVED** [review]
Based on the discussion I am merging this now. Thanks @ahus1

**Pull request merged**
