### PR TITLE
21360 updated bouncycastle to jdk15to18 1.75

### PR DESCRIPTION
**Pull request by sschu**
Implements #21360 (potentially/partly)

I am not sure anymore if this is the way to go or somehow align with Quarkus as mentioned in #21360.

### CODE REVIEW

**Comment by ahus1** [comment]
Not sure if this is related: There is an effort to move to the Quarkus BOM https://github.com/keycloak/keycloak/pull/21426

**Comment by vmuzikar** [comment]
@ahus1 #21360 is a follow-up from #21426.

We should probably align bouncycastle versions with the Quarkus BOM. WDYT @pedroigor @mposolda?

**Comment by pedroigor** [comment]
Sorry, I thought I have commented about this somewhere ...

I think we should just use `*-jdk18on` because we don't need to support JVMs earlier than 1.8. And we are using JDK17 which supports multi-release JARs. 

@vmuzikar Looking at Quarkus, it seems we can align the artifacts/versions.

**Comment by sschu** [comment]
@pedroigor Fine for me. I will go ahead and close this one. Please note that @stianst wanted to have the bouncy castle update in KC22. Will the quarkus BOM alignment be done for KC22?

**Comment by pedroigor** [comment]
I think so, looks like @vmuzikar is looking at this.

**Comment by vmuzikar** [comment]
PR for alignment with Quarkus BOM https://github.com/keycloak/keycloak/pull/21543

**Pull request closed without merging**
