### PR TITLE
Use short UUID for ldap components

### LINKED ISSUE #32143: UserId too long to add Security Key WebauthN
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication/webauthn

### Describe the bug

Same issue as https://github.com/keycloak/keycloak/issues/24645. I could not reopen the other 

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Ability to add security keys for federated users. Note that it may be needed to simulate this with LDAP provider with import disabled (To make sure that userId is in longer format like `f:<ldap provider UUID>:<ldap UUID>` or might be simulated with custom userStorage provider.

### Actual behavior

Error: Security key registration result is invalid. TypeError: User handle exceeds 64 bytes.

### How to Reproduce?

 Add `User federation` ldap should work well if the `username` is set to `userPrincipalName`. 

### Anything else?

I don't think that WebAuthn will change their standards which leaves it to Keycloak to adjust. Here is the link to the specification https://www.w3.org/TR/webauthn-2/#sctn-createCredential. It fails on point 5.

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #32143

This PR just adds a new `generateShortId` method in `KeycloakModelUtils` that generates an UUID but encoded in base64 URL without padding (22 ascii chars). The ldap component adds this ID at creation time in the `validateConfiguration`method. I also managed the idea about adding a method in the component interface like `useShortId` (true/false) than can be overriden, but finally I thought this is simpler and any factory can use the short form if needed at validation time. With this, all the new ldap components will use a short ID that left 40 chars for external IDs when not importing into the internal DB.

### CODE REVIEW

**Comment by mposolda** [comment]
@rmartinc LGTM, Thanks!

One disadvantage is, that it does not fix existing deployments as they have already LDAP component created and users established their IDs. But hopefully ok for now. We can see if we need some follow-up...

Does it worth also to be documented? As it can affect also users having their own userStorage provider implementations? Perhaps some some small info box in the WebAuthn docs and also in the UserStorage chapter in the development guide that people using combination of WebAuthn together with custom userStorage should take this into consideration?

**Comment by rmartinc** [comment]
> One disadvantage is, that it does not fix existing deployments as they have already LDAP component created and users established their IDs. But hopefully ok for now. We can see if we need some follow-up...

Yes, but in general I don't think we can do much for existing ldap providers. The ID is already set and any FEDERATION user row is already linked using the long ID (credentials, roles,...). So we cannot change the IDs already assigned.

> Does it worth also to be documented? As it can affect also users having their own userStorage provider implementations? Perhaps some some small info box in the WebAuthn docs and also in the UserStorage chapter in the development guide that people using combination of WebAuthn together with custom userStorage should take this into consideration?

I have added a note in the webauthn and a new paragraph in the developer guide about the storage-id. Take a look to see what you think about it.

**Review by mposolda — APPROVED** [review]
@rmartinc Approving as it is an improvement. We will see if we need to do something as a follow-up.

@andymunro Can you please review documentation part of this PR?

@keycloak/core-iam Are you please able to review this PR as well since it is related to LDAP and userStorage providers?

**Review by sguilhen — APPROVED** [review]
@rmartinc @mposolda LGTM!

**Pull request merged**
