### PR TITLE
Add ability to enable OID4VCI Verifiable Credentials per realm (#34524)

### LINKED ISSUE #34524: Add ability to enable support for Verifiable Credentials per Realm
### Description

Add a boolean switch for Verifiable Credentials to the realm settings to allow users to enable OpenID 4 VCI Verifiable Credentials support per realm.

### Discussion

_No response_

### Motivation

Currently the support for OpenID 4 VCI Verifiable Credentials can only be enabled for the whole server which ten affects all realms.

However, if the Keycloak server hosts multiple realms and users don't want to have the OpenID 4 VCI Verifiable Credentials support for some realms it's currently not possible.

Also the account ui always shows the "Verifiable Credentials" menu item in the navigation, even if it is not used.

image

### Details

_No response_

### PR DESCRIPTION
**Pull request by thomasdarimont**
- Added new realm property verifiableCredentialsEnabled
- Updated RealmRepresentation (added Boolean verifiableCredentialsEnabled)
- Added boolean switch to Realm settings page to control Verifiable Credentials enablement
- Add guard Oid4VCI page: we now only show the Verifiable Credentials page in the navigation if the if feature is enabled and "Verifiable Credentials" realm setting is enabled.
- When the "Verifiable Credentials" realm setting is off, the OID4VCI link is removed from realm settings page

image

Fixes #34524

### CODE REVIEW

**Comment by mposolda** [comment]
@thomasdarimont Thanks! I think that the failing tests are regression of this PR. Looks there might be some issue with account console in case that feature is `oid4vc` is disabled?

**Comment by thomasdarimont** [comment]
Thanks for the review. I take a look at the failed tests.

**Comment by thomasdarimont** [comment]
@mposolda tests are passing now :)

**Review by tnorimat — COMMENTED** [review]
@thomasdarimont  Hello, it seems that the PR only support a switch to enable/disable oid4vci but it does not include logic for enabling/disabling oid4vci feature. Is it right? If so, the logic would be support by other PR in the future?

**Comment by thomasdarimont** [comment]
The oidc4vci "feature" needs to be enabled for the whole server via the --features=oid4vc-vci  flag.
This PR adds another layer on top of that that allows admins to control the availability of the oid4vc-vci support per realm.

**Comment by tnorimat** [comment]
@thomasdarimont Thank you for the clarification.

**Review by tnorimat — APPROVED** [review]
LGTM

**Review by mposolda — APPROVED** [review]
@thomasdarimont @tnorimat Thanks for fixing the tests for the additional review!

This requires also review from our UI team. I hope we can merge afterwards.

**Review by edewit — APPROVED** [review]

**Comment by mposolda** [comment]
@edewit Thanks for the review!

**Comment by Captain-P-Goldfish** [comment]
I am not sure if we should call it `Verifiable Credentials`. If we look at the FUNKEN challenge it becomes clear that not all issued credentials are `Verifiable Credentials` after https://www.w3.org/TR/vc-data-model-2.0/ but can also be simple JSON structures or even other specific JSON structure types. Therefore, I think it would be better to name it `OpenId4VCI`?

**Comment by thomasdarimont** [comment]
@Captain-P-Goldfish thanks for your remark! I used the term "Verifiable Credentials" as this term was used for in the "Account Console". Do you suggest to rename the realm setting from `verifiableCredentialsEnabled` to `oid4VciEnabled` in the code and the admin-console, but keep the "Verifiable Credentials" label in the account console?

**Comment by Captain-P-Goldfish** [comment]
> @Captain-P-Goldfish thanks for your remark! I used the term `Verifiable Credentials` as this term was used for in the "Account Console". Do you suggest to rename the realm setting from `Enable Verifiable Credentials` to `Enable OID4VCI` and `verifiableCredentialsEnabled` to `oid4VciEnabled` in the code and the admin-console, but keep the `Verifiable Credentials` label in the account console?

Yes, this was exactly my intention.

**Comment by thomasdarimont** [comment]
I created this PR to revise the names: https://github.com/keycloak/keycloak/pull/35498

**Comment by thomasdarimont** [comment]
I also created this feature request for a generic way to toggle features on realm level: https://github.com/keycloak/keycloak/issues/35500

**Pull request merged**
