### PR TITLE
KEYCLOAK-2486: Update SimpleHTTP to use Apache HTTP Client

### PR DESCRIPTION
**Pull request by daklassen**
Update SimpleHTTP to use Apache HTTP client under the covers.

### CODE REVIEW

**Comment by stianst** [comment]
We have SPI to retrieve properly configured HttpClient, that should be used rather than a separate provider.

**Comment by daklassen** [comment]
Is this the correct way to retrieve the HttpClient?
`HttpClient httpClient = session.getProvider(HttpClientProvider.class).getHttpClient();`

How do I setup the truststore if I need you use preconfigured HttpClient? (see method "setupTruststoreIfApplicable")

**Comment by thomasdarimont** [comment]
Isn't the `TrustStore` already configured in the [DefaultHttpClientFactory](https://github.com/keycloak/keycloak/blob/a743600b344763ce2e7f70a625f590a8425fc5f3/services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java#L131)?

**Comment by stianst** [comment]
When the HttpClient is retrieved from the HttpClientProvider it will be configured with the truststore set in the truststore provider. There's docs around this in the server installation guide I think.

**Comment by daklassen** [comment]
Thanks for your help. Will open a new and clean one-commit-PR.

**Pull request closed without merging**
