### PR TITLE
KEYCLOAK-14902 Replace SAML SP metadata export with link to descriptor

### PR DESCRIPTION
**Pull request by lscorcia**
Currently, the SAML remote Identity Provider configuration has an "Export" tab to export the local endpoint Service Provider metadata.

While it's working, this UI has a few of problems:

*    This is incoherent with the export of the local Identity Provider metadata, which shows just a link to the descriptor;
*    After the recent SP metadata refactoring, the current metadata display is not that easy to read;
*    The tab display is hardcoded to appear only for the "saml" provider into the kc-tabs-identity-provider component, so any custom saml-derived providers cannot provide the metadata export function:
https://github.com/keycloak/keycloak/blob/feef5b4db2add4d583630674afe778b9fdc551e0/themes/src/main/resources/theme/base/admin/resources/templates/kc-tabs-identity-provider.html#L14
*    It's not easy for administrators to discover the direct link to the descriptor, say to share it via mail to a 3rd party.

My suggestion is to remove the Export tab altogether and replace it with a simple link to the /descriptor endpoint, like Keycloak already does with the IdP metadata.

### CODE REVIEW

**Comment by pedroigor** [comment]
@lscorcia I like your proposal and it makes sense for me. Have a link instead of that ugly text area with the metadata looks better.

But I did not understand what you have said around `This is incoherent with the export of the local Identity Provider metadata, which shows just a link to the descriptor`. If you could elaborate more, I appreciate it.

I would also suggest you send an e-mail to `keycloak-dev` mailing list (if not already) giving some update about this change. It has some impact due to changes in UI and UX.

**Review by pedroigor — COMMENTED** [review]
@lscorcia I like your proposal and it makes sense for me. Have a link instead of that ugly text area with the metadata looks better.

But I did not understand what you have said around `This is incoherent with the export of the local Identity Provider metadata, which shows just a link to the descriptor`. If you could elaborate more, I appreciate it.

I would also suggest you send an e-mail to `keycloak-dev` mailing list (if not already) giving some update about this change. It has some impact due to changes in UI and UX.

**Comment by pedroigor** [comment]
@hmlnarik What do you think about these changes?

**Comment by lscorcia** [comment]
What I meant is that the current SP metadata UI is different from the one already used to access the local SAML Identity Provider metadata in the Realm Settings which is a simple link (see also the screenshots attached at https://issues.redhat.com/browse/KEYCLOAK-14902) .

I have somewhat talked about this in the dev ml at https://groups.google.com/g/keycloak-dev/c/u7IiuSqpzOg , but I hadn't envisioned this solution at that time. I will try to write a followup with the description of this pull request.

Thanks for your help!

**Comment by vmuzikar** [comment]
I've triggered the Admin Console UI tests here: https://keycloak-jenkins.com/job/universal-test-pipeline-server/2010/

**Comment by pedroigor** [comment]
@vmuzikar Thanks, would that mean adding some test for this too?

**Comment by lscorcia** [comment]
@vmuzikar I suppose that's an internal domain, I can't access it. Are there any failures? Can you paste the output on a pastebin?

**Comment by vmuzikar** [comment]
> @vmuzikar Thanks, would that mean adding some test for this too?

Ideally, yes. On the other hand, this PR doesn't add any new functionality, right? Just changing slightly changing UI. Apparently, we had no test for this particular part of UI (no test is broken), so maybe it's not that much important to add it now.

> @vmuzikar I suppose that's an internal domain, I can't access it. Are there any failures? Can you paste the output on a pastebin?

All tests passed. Only IE failed but that's unrelated to this.

**Comment by lscorcia** [comment]
Yep, it's just an UI change. It's probably going to need a small documentation update at paragraph https://www.keycloak.org/docs/latest/server_admin/index.html#_identity_broker_saml_sp_descriptor too.

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
