### PR TITLE
[KEYCLOAK-4964] Implement a named query for role fetching by ID to in…

### PR DESCRIPTION
**Pull request by johnament**
…clude the composite roles.

### CODE REVIEW

**Comment by johnament** [comment]
The test seems to fail on this:

```
Caused by: java.io.FileNotFoundException: target/dependency/keystore/keycloak.truststore (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.keycloak.truststore.FileTruststoreProviderFactory.loadStore(FileTruststoreProviderFactory.java:95)
	at org.keycloak.truststore.FileTruststoreProviderFactory.init(FileTruststoreProviderFactory.java:74)
	... 84 more
```

And I have no idea what to do.

**Comment by johnament** [comment]
Ok, after looking at it a bit more I understand the N+1 query issue, its actually closer to 2N+1 in this case.  Maybe @patriot1burke can give some insight here.

When you fetch roles, you're fetching the IDs and looking to see if they're in the cache.  If they're not in the cache, you're doing a second query to pull back the entire object.

I'm almost wondering if it makes more sense to rely on internal hibernate caching instead of this backed infinispan call.

**Comment by stianst** [comment]
Maybe what we actually need is two things: 

1. When realm is first loaded load all roles for the realm into the cache. This would be a single get all roles for realm query in one go.
2. When a role is removed from cache load just the removed role, not composites. Composites should in this case be in the cache already so no need to fetch.

**Comment by johnament** [comment]
@stianst  maybe.  Basically, the idea is to avoid the many queries that executed, even if they take 100ms each its Y x 100 causing the slowness in the operation.

The caching done here is very disjointed.  Please don't take offense to that.  The entire persistence layer seems to treat caching as its own thing, rather than relying on the built in functions from hibernate which will probably provide you the same if not better performance overall.

The whole probably would be easier to grok if there was a single place where roles are loaded, instead of 5-6 places, using different logic.  The delegate pattern makes it harder to follow since it looks like a recursive call stack.

Are composite roles also direct members of the realm?  If so, I would remove the JPA level foreign key and manually build the hierarchy in memory.

**Comment by stianst** [comment]
Closing as outdated. Please send a new PR if still relevant.

**Pull request closed without merging**
