### PR TITLE
Upgrade agroal

### LINKED ISSUE #17161: Acquisition timeout while waiting for new connection
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

Originally reported as part of #16448.

Tracker of Agroal issue: https://issues.redhat.com/browse/AG-201

Occassionally, the following exception can be seen upon obtaining new connection in Keycloak:

```
2023-01-13 07:20:55,243 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: Acquisition timeout while waiting for new connection
	at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:320)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:248)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
	at io.quarkus.hibernate.orm.runtime.customized.QuarkusConnectionProvider.getConnection(QuarkusConnectionProvider.java:23)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:107)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.boot.internal.SessionFactoryOptionsBuilder.<init>(SessionFactoryOptionsBuilder.java:272)
	at io.quarkus.hibernate.orm.runtime.recording.PrevalidatedQuarkusMetadata.buildSessionFactoryOptionsBuilder(PrevalidatedQuarkusMetadata.java:68)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:72)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:72)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:165)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:66)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:296)
	... 23 more
```

This is caused by Agroal issue AG-201.

### Version

20, main

### Expected behavior

no exception

### Actual behavior

exception

### How to Reproduce?

See #16448 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes #17161

Upgrading just 21.0 branch for now. Main will soon be on Quarkus 3 where this is [fixed](https://github.com/quarkusio/quarkus/blob/d1c9c141037822675ea7b000a951a01783f4d904/bom/application/pom.xml#L107) already. Let me know if you want me to temporarily override the agroal version in main too.

Didn't override agroal in guides and operator where it's a transitive dependency.

### CODE REVIEW

**Review by vramik — APPROVED** [review]
LGTM

**Review by mhajas — APPROVED** [review]
Approving per @vramik 's approval

**Review by stianst — APPROVED** [review]

**Comment by notTrinity** [comment]
Will this be in a 20.0.5+ patch? There are certain changes we won't pickup in 21.0.0 for awhile.

**Comment by prashankjauhari** [comment]
> Closes #17161
> 
> Upgrading just 21.0 branch for now. Main will soon be on Quarkus 3 where this is [fixed](https://github.com/quarkusio/quarkus/blob/d1c9c141037822675ea7b000a951a01783f4d904/bom/application/pom.xml#L107) already. Let me know if you want me to temporarily override the agroal version in main too.
> 
> Didn't override agroal in guides and operator where it's a transitive dependency.

is it resolved in main? I downloaded from keycloak latest from keycloak site. But I am getting this error. around 40 connection are created then I get this error. Minimum pool size is 100 for my case.

**Pull request merged**
