### PR TITLE
Add CopyToClipboardButton to UserID

### LINKED ISSUE #33496: Add CopyToClipboardButton to UserID in Admin UI
### Description

In the Admin UI we should add a CopyToClipBordButton next to the user id like this:

image

### Discussion

_No response_

### Motivation

Everytime I needed to copy a user id, I wondered why there was no button to copy it.

### Details

Will be fixed by https://github.com/keycloak/keycloak/pull/33491

### PR DESCRIPTION
**Pull request by TimKochDev**
Closes #33496

This pull requests adds a CopyToClipboard button in the Admin UI for the id field in the user details tab. Everytime I needed to copy a user id, I wondered why there was no button to copy it. 

I have to admit: This is my first commit in this code base. I did NOT take a lot of time to understand the full Admin UI. Instead, I copied from `js/apps/admin-ui/src/clients/credentials/ClientSecret.tsx`. It works flawlessly but if I violated a coding guideline or misinterpreted a component prop, please tell me.

Fixes https://github.com/keycloak/keycloak/issues/33496

### CODE REVIEW

**Comment by jonkoops** [comment]
> I've read the contributing guideline and came to the conclusion that this commit is small enough to not need a dedicated issue. Please tell me if you think I am wrong!

Please log an issue anyways, as we use this to build the changelog for releases.

**Comment by jonkoops** [comment]
I understand your confusion, we should move the `CopyToClipboardButton` component to `src/components` instead, as it is a reusable component that is not specifically tied to any specific functionality. @TimKochDev could you do this cleanup here?

**Comment by TimKochDev** [comment]
I am not quite sure what is going on:

@ahus1 You re-committed and force-pushed my commit again in order to restart the flaky test pipeline, right? Or did that commit anything else?

---



> I understand your confusion, we should move the `CopyToClipboardButton` component to `src/components` instead, as it is a reusable component that is not specifically tied to any specific functionality. @TimKochDev could you do this cleanup here?

@jonkoops I never said I was confused :)
But yes, I will try my best and will update this pull request as soon as possible

**Comment by TimKochDev** [comment]
As requested, I moved the `CopyToClipboardButton` to `src/components`. Looking forward to your feedback.

**Review by jonkoops — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
