### PR TITLE
Ignore unrecognized JSON fields for OIDC dynamic client registration

### LINKED ISSUE #14946: Unrecognized JSON field causes DCR to fail
### Describe the bug

According to RFC 7591 OAuth 2.0 Dynamic Client Registration Protocol, Section 2:

> The authorization server MUST ignore any client metadata sent by the client that it does not understand

If such an unrecognized field is included into an otherwise legitimate DCR request, the latter would fail. Moreover, it would expose class names and other internal details.

### Version

19.0.3

### Expected behavior

Successful client registration

### Actual behavior

```json
{
    "error": "Unrecognized field \"foo\" (class org.keycloak.representations.oidc.OIDCClientRepresentation), not marked as ignorable (54 known properties: \"tos_uri\", \"redirect_uris\", \"client_id\", \"request_object_signing_alg\", \"grant_types\", \"client_id_issued_at\", \"backchannel_client_notification_endpoint\", \"client_secret_expires_at\", \"backchannel_logout_uri\", \"userinfo_signed_response_alg\", \"id_token_encrypted_response_enc\", \"jwks_uri\", \"client_secret\", \"default_max_age\", \"require_auth_time\", \"request_object_encryption_alg\", \"software_id\", \"token_endpoint_auth_method\", \"require_pushed_authorization_requests\", \"request_uris\", \"frontchannel_logout_session_required\", \"backchannel_logout_session_required\", \"registration_client_uri\", \"userinfo_encrypted_response_alg\", \"software_version\", \"tls_client_auth_subject_dn\", \"backchannel_token_delivery_mode\", \"application_type\", \"backchannel_authentication_request_signing_alg\", \"sector_identifier_uri\", \"contacts\", \"scope\", \"logo_uri\", \"frontchannel_logout_uri\", \"policy_uri\", \"id_token_encrypted_response_alg\", \"subject_type\", \"request_object_encryption_enc\", \"token_endpoint_auth_signing_alg\" [truncated]])\n at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 1, column: 29] (through reference chain: org.keycloak.representations.oidc.OIDCClientRepresentation[\"foo\"])"
}
```

### How to Reproduce?

1. Set up client registration policies to allow DCR
2. Make a request:
```
POST /realms/{{KEYCLOAK_REALM}}/clients-registrations/openid-connect

{
    "client_name": "Test",
    "foo": "bar"
}
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dteleguin**
Closes: #14946

### CODE REVIEW

**Review by mposolda — CHANGES_REQUESTED** [review]
@dteleguin The change looks good, but there is failing test, which requires some work.
```
Error: OR] Failures: 
Error: OR]   ClientRegistrationTest.registerClientWithWrongCharacters:635 
-- Expected: is <400>
--      but: was <403>
```

**Comment by dteleguin** [comment]
A `403 Forbidden` is returned by the Trusted Hosts client registration policy, which kicks in because the request containing an unknown property is now considered valid.

As we are going to ignore any unrecognized properties and not return any property-specific error, would it be OK just to remove this test case? WDYT @mposolda @mabartos ?

**Comment by mposolda** [comment]
@dteleguin I think the test itself can be possibly kept, but it can be changed in a way that unrecognized fields are ignored (not shown anywhere to the user and not shown in the client-registration response of newly registered client).

**Comment by mabartos** [comment]
@dteleguin Thanks for the PR! I agree with @mposolda, as it'd be good to keep there the test case as it verifies it's not possible to execute an XSS attack. AFAIK it's the only place where such a situation is tested for the DCR endpoint. We should be sure the unrecognized fields are really ignored for DCR in terms of the possible XSS.

**Comment by mposolda** [comment]
@dteleguin Closing due not feedback to previous comment and we might need to squash the queue of existing "inactive" PRs. But it would be welcome if you re-open with the changes mentioned in the previous comments. Thanks!

**Comment by remcojansen** [comment]
I noticed this PR and the [closed discussion here](https://github.com/keycloak/keycloak/issues/14946). The way I read RFC 7591 on DCR the authorization server must indeed ignore unknown properties. Instead of creating a new issue for it, I figured it might be preferred to re-open the existing issue?

I have created a [new PR](https://github.com/keycloak/keycloak/pull/43603) similar to the earlier proposed PR, but with the aim to address the concerns in this thread regarding test coverage.

@mposolda I am testing that the unknown properties are not returned to the client, but you also mentioned "not shown anywhere to the user". Did you think of any place in particular? Do you think the tests I added are sufficient?

**Pull request closed without merging**
