### PR TITLE
Upgrade to Quarkus 3.8

### LINKED ISSUE #26859: Upgrade to Quarkus 3.8
### Description

As Quarkus 3.8 is the next LTS release we should upgrade to it prior to releasing Keycloak 24.

[Quarkus Release Planning](https://github.com/quarkusio/quarkus/wiki/Release-Planning)

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### LINKED ISSUE #27204: SQL injection in pgjdbc
### Description

pgjdbc, the PostgreSQL JDBC Driver, allows attacker to inject SQL if using PreferQueryMode=SIMPLE. Note this is not the default. In the default mode there is no vulnerability. A placeholder for a numeric value must be immediately preceded by a minus. There must be a second placeholder for a string value after the first placeholder; both must be on the same line. By constructing a matching string payload, the attacker can inject SQL to alter the query,bypassing the protections that parameterized queries bring against SQL Injection attacks. Versions before 42.7.2, 42.6.1, 42.5.5, 42.4.4, 42.3.9, and 42.2.8 are affected.

Reference: https://github.com/advisories/GHSA-xfg6-62px-cxc2

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes #26859
Closes #27204

### CODE REVIEW

**Review by ahus1 — APPROVED** [review]
Approving. Leaving it up to you to merge it, or get additional reviews from the CND team.

**Review by mabartos — APPROVED** [review]
@vmuzikar LGTM

**Comment by orgads** [comment]
Thanks! What about backports?

**Comment by vmuzikar** [comment]
@orgads Due to breaking changes, we're backporting only Quarkus micro upgrades. This is for Keycloak 24 which will be released soon.

**Pull request merged**
