### PR TITLE
KEYCLOAK-1776 / JettySessionTokenStore sets content type on restoring form values

### PR DESCRIPTION
**Pull request by ahus1**
JettySessionTokenStore will call saveRequest() to preserve data submitted by a form. The subsequent call to restoreRequest() will restore the form parameters, but not the content type. 

see: [KEYCLOAK-1776](https://issues.jboss.org/browse/KEYCLOAK-1776)

### CODE REVIEW

**Comment by stianst** [comment]
This only works if content-type is "application/x-www-form-urlencoded", it should use the content-type from the original request.

**Comment by ahus1** [comment]
@stianst //
Hello Stian,

saveRequest() will only save the submitted content when the content-type of the request "application/x-www-form-urlencoded" and store it inside CACHED_FORM_PARAMETERS.

Therefore (as far as I can see) it is symetric to set the content-type to "application/x-www-form-urlencoded" in restoreRequest() when CACHED_FORM_PARAMETERS are found in the session. 

Do you agree? Are you missing additional logic that I should add? 

Thanks!

**Comment by patriot1burke** [comment]
I wrote all this stuff....I have vague memories that saveRequest() is different per version of Jetty (or was that Tomcat?)  You need to add an test to each Jetty test that is in the testsuite before I can accept this PR.

**Comment by ahus1** [comment]
Hello Bill,

I found that there is already testSavedPostRequest in Jetty9Test and Jetty8Test. It calls to InputPage and InputServlet. I extended InputServlet so that it will only return the result when the correct content type is received (like my Dropwizard/Jersey situation). 

The affected tests for Jetty 9.2 can be run from the command line like this:

`mvn test -Dtest=Jetty9Test -pl testsuite/jetty/jetty92 -am -DfailIfNoTests=false`

Please let me know if you are missing anything.

Best regards,
Alexander.

**Pull request merged**
