### PR TITLE
[KEYCLOAK-12063] ExtendingThemeTest.systemPropertiesSubstitutionInThe…

### PR DESCRIPTION
**Pull request by douglaspalmer**
…meProperties failing

### CODE REVIEW

**Review by stianst — COMMENTED** [review]
getProperties is used quite frequently and this means it will be generated everytime it's called. So this is not a good change.

There's an open issue with theme caches not being cleared on hot-deploy. I can fix this issue as part of fixing that by introducing a method to clear the cache. See https://issues.redhat.com/browse/KEYCLOAK-8044

**Review by stianst — CHANGES_REQUESTED** [review]
See previous comment

**Comment by stianst** [comment]
Here's PR to introduce ability to clear theme caches on hot-deployment:
https://github.com/keycloak/keycloak/pull/6804

The ExtendingThemeTest now triggers clearing of the caches after setting the system property, which should fix the broken test in the pipeline.

**Comment by douglaspalmer** [comment]
Closing because @stianst has a better fix.

**Pull request closed without merging**
