### PR TITLE
KEYCLOAK-8150 Improve loading user list

### PR DESCRIPTION
**Pull request by hmlnarik**

### CODE REVIEW

**Review by ssilvert — APPROVED** [review]

**Comment by ibauersachs** [comment]
This looks more like a workaround than actually solving the issue...

**Comment by hmlnarik** [comment]
@ibauersachs There are several issues that contribute to this, some of them not particularly easy to fix.
Just wondering whether limiting returned data to what is actually used/needed instead of returning the dataset that is mostly discarded by the consumer the moment the data arrive is indeed a workaround?

**Comment by ibauersachs** [comment]
@hmlnarik Well, limiting data to what is required by the consumer is generally a good idea, and it's a valid fix for the case of the slow admin UI. However, it's not a fix for the general API, which continues to be slow, as has been pointed out on the mailing list.

**Comment by hmlnarik** [comment]
... and has just the same been replied with the direction of the other necessary fixes at the same mailing list. We're open to any reasonable contribution with the fix, feel free to submit a PR.

**Pull request merged**
