### PR TITLE
External Infinispan as cache - Part 2

### LINKED ISSUE #28648: External Infinispan as cache - Part 2
### Description

See Part 1: https://github.com/keycloak/keycloak/issues/28140

### Discussion

_No response_

### Motivation

See Part 1: https://github.com/keycloak/keycloak/issues/28140

### Details

Part 2 of the series `External Infinispan as cache`

This part includes a new implementation for the providers:
* StickySessionEncoderProviderFactory
* LoadBalancerCheckProviderFactory
* SingleUseObjectProviderFactory

And adds a new remote-only cache `actionTokens`.

### PR DESCRIPTION
**Pull request by pruivo**
Includes a new implementation for the providers:

* StickySessionEncoderProviderFactory
* LoadBalancerCheckProviderFactory
* SingleUseObjectProviderFactory

Closes #28648

### CODE REVIEW

**Review by ahus1 — APPROVED** [review]
Thank you for these changes. I reviewed the changes and tested it locally, it looks good.

**Comment by ahus1** [comment]
Before the next iteration on this branch, I assume we should first merge the other pending PRs for main, and then rebase this PR?

**Comment by pruivo** [comment]
wow that was fast @ahus1 :+1: :partying_face: 

Yes, we can rebase during the F2F (except if you want to have the pain of fixing the conflicts yourself)

**Comment by ahus1** [comment]
Yes, I don't plan to resolve the conflicts myself.

My pragmatic suggestion for a rebase: Once the PRs in main are merged, you rebase the branch and push it to your local repo and let me know the branch name. I then double-check it and then push it over to the main repo's branch.

**Pull request merged**
