### PR TITLE
KEYCLOAK-14496 Use KeycloakAdapter interface for 'adapter' option

### PR DESCRIPTION
**Pull request by jonkoops**
Also improves documentation by adding more details and an explicit example on how to use the interface.

### CODE REVIEW

**Comment by jonkoops** [comment]
This will also have to be documented properly in the documentation so that users can find this option. I'll make a PR for this as soon as I have some time available.

**Review by ssilvert — CHANGES_REQUESTED** [review]
I think what you did here looks good, but we should not piggyback on the https://issues.redhat.com/browse/KEYCLOAK-13956 JIRA.

I'm closing that JIRA as a duplicate.  Please create a new JIRA for this work and change the description of this PR.

**Comment by jonkoops** [comment]
@ssilvert I've updated the issue number.

**Review by ssilvert — DISMISSED** [review]
LGTM

**Review by mhajas — DISMISSED** [review]
Thanks @jonkoops, this looks good to me. Addition of this to the documentation would be really appreciated.

**Comment by jonkoops** [comment]
@mhajas I'll see if I can make some time tonight to add a documentation PR, I'll link it here.

**Review by ssilvert — APPROVED** [review]

**Comment by jonkoops** [comment]
I've opened up a PR for the documentation here https://github.com/keycloak/keycloak-documentation/pull/961

**Pull request merged**
