### PR TITLE
NPE fix for missing/null attributes

### PR DESCRIPTION
**Pull request by LorenzoLuconi**
Small fix for NPE when there are mapped attributes optional for some users (using federated storage).

### CODE REVIEW

**Comment by stianst** [comment]
Thanks for your PR. Can you please create a JIRA bug report and also would be good to see a test added.

**Comment by abstractj** [comment]
@LorenzoLuconi any feedback on this?

**Comment by lippling** [comment]
I have the same issue right now. I "fixed" it for now:
```java
return new AbstractUserAdapterFederatedStorage ... {
...
...
    @Override
    public List<String> getAttribute(final String name)
    {
        // Fix for broken method in super class
        return Optional.ofNullable(super.getAttribute(name)).orElse(new ArrayList<>());
    }
}
```

**Comment by stianst** [comment]
Closing due to lack of tests and JIRA

**Pull request closed without merging**
