### PR TITLE
Prevent ProviderFactories being loaded twice

### PR DESCRIPTION
**Pull request by mstruk**

### CODE REVIEW

**Comment by stianst** [comment]
This seems unnecessary. I can't see how the same factory would be loaded twice in the first place. What scenario is this actually solving?

**Comment by mstruk** [comment]
Without this patch if I put a breakpoint in this code, or in my ProviderFactory impl class I see that the class is loaded by two different classloaders. One is the one looking for providers in modules using module classloader, the other is the one looking for providers at standalone/configuration/providers directory which contains as it's parent a classpath of jars that picks up the same jars that are already exposed as modules. Thus, the same jars are in effect exposed via two classloaders and provider factories in them are consequently loaded twice. 

Maybe a more proper fix would be to use ModuleClassLoader for standalone/configuration/providers dir as well, and properly configure dependencies on it. That would ensure all provider factory classes found twice would be of the same classloader, and thus only one static init would occur.

**Comment by mstruk** [comment]
Actually what I wrote is wrong (need coffee :)

What happens is there are two instances of the same ProviderFactory class instanciated because they are found through different classloaders. Consequently both instances enter the factoryClasses map, and both are used when initializing providers, and thus we end up with double the necessary providers.

**Comment by stianst** [comment]
In that case you've wrongly deployed the same provider twice. In your PR you end up just suppressing that so the user wouldn't know from which classloader the provider is actually loaded. Actually as you're comparing by class and the class is different as it's different classloaders I don't see how it's even going to work.

In either case what we could do is if someone does wrongly register a provider multiple times with different class-loaders we should throw a runtime exception. We should take this one step further and base the check on the id of the provider (ProviderFactory.getId) as that will also catch the case if someone uses an existing id for the provider.

**Comment by stianst** [comment]
Oh and please create a JIRA issue so we can track changes like this ;)

**Comment by mstruk** [comment]
No, I think you're talking about my initial erroneous-from-memory summary of the issue. 
It's actually two instances of the same class / same classloader where there should only be one.
And it's not just my provider factory represented by two instances of the same class. They all are.

[Here's the JIRA](https://issues.jboss.org/browse/KEYCLOAK-2264) with another description of the issue.

**Comment by stianst** [comment]
Ok - in that case the check is not necessary. Instead we should fix it properly. What you are doing here is a hack IMO.

**Comment by stianst** [comment]
I think a decent solution would be to use a URLClassLoader without the parent to search for factories. Then use another URLClassLoader to load them. That way we won't load anything from the parent classloader

**Comment by mstruk** [comment]
Often times quick and short solution do the trick :) In this case I just added a little 'defensive coding' that fixed the issue. But I agree that the original sin is in the classloader part.

I can look at a more appropriate fix you suggest but only after I finish some other tasks on my platter first.

**Pull request merged**
