### PR TITLE
Disable caching for map storage in the interactive Testsuite

### LINKED ISSUE #11748: Disable caches for Map Storage in testsuite.KeycloakServer
### Describe the bug

While #11213 disabled the caching for the integration tests, this should also be disabled for interactive testing. 

This change will align the configuration and also the configuration properties.

### Version

999-SNAPSHOT

### PR DESCRIPTION
**Pull request by ahus1**
Also aligns the properties with the integration test suite to avoid confusion.

Closes #11748

### CODE REVIEW

**Comment by ahus1** [comment]
When running with the command 

```
mvn -pl testsuite/utils -Pkeycloak-server,map-storage exec:java | grep "SPI" | grep -i cache
``` 

it will log

```
16:50:37,441 DEBUG org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.services.DefaultKeycloakSessionFactory] SPI authorizationCache provider default disabled
16:50:37,699 DEBUG org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.services.DefaultKeycloakSessionFactory] SPI realmCache provider default disabled
16:50:37,776 DEBUG org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.services.DefaultKeycloakSessionFactory] SPI userCache provider default disabled
```

Thereby showing that the three caches are disabled.

**Review by vramik — APPROVED** [review]

**Review by hmlnarik — APPROVED** [review]
Approving per @vramik 's approval

**Comment by ahus1** [comment]
@kami619 - you'll now be able to run the tests with a disabled cache for JPA Map storage. Beware, it will still be slow until two more changes are in (#11768, #11765), so don't put too much effort into retesting.

**Comment by kami619** [comment]
@ahus1 thanks for the heads up :)

**Pull request merged**
