### PR TITLE
Improve procedure for handling open transactions

### PR DESCRIPTION
**Pull request by k-tamura**
This operation should not be necessary in the Quarkus version.

### CODE REVIEW

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for looking into this. 

This would still be necessary if a deployment has XA transactions enabled. But the path is wrong, as it is set for Quarkus to a different value: https://github.com/keycloak/keycloak/blob/c4fdf1cee7d646bbde18f571d721c933e2c209d5/quarkus/runtime/src/main/resources/application.properties#L38

See https://github.com/keycloak/keycloak/blob/9db144336766076966ddb2055b4179f5008d4836/docs/guides/server/db.adoc?plain=1#L270-L283 for the current state of XA transactions in KC25.

Note that XA transactions have been enabled by default in the Quarkus versions up until KC24 (including), and have been disabled by default in KC25 (see #27308).

**Comment by k-tamura** [comment]
@ahus1 
Could you check [my new commit](https://github.com/keycloak/keycloak/pull/29748/files)?

**Comment by ahus1** [comment]
@k-tamura - thank you, the updated docs match Keycloak's behavior. 

To be able to merge this PR, I ask you to squash those commits, and add a Sign-off to the commit. See the file `CONTRIBUTING.md` in this repository on how to do this. The sign-off shows that you comply with the contribution guidelines to this repository.

**Comment by k-tamura** [comment]
@ahus1
Thank you. I squashed, could you check again?

**Review by ahus1 — APPROVED** [review]
Thank you for this fix and making the docs accurate!

**Comment by ahus1** [comment]
Thank you - your changes will be part of the next major release of Keycloak (26.0.0)

**Pull request merged**
