### PR TITLE
KEYCLOAK-12852 remove internal query params after redirect

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Review by stianst — CHANGES_REQUESTED** [review]
Removing OIDC query parameters should be taken care of by keycloak.js not the application itself. Not sure what is going on here, but setting an AIA should be handled by keycloak.js and it should have methods to check if it's a success or error. 

Further, keycloak.js handles the OAuth/OIDC callback, then should remove any OIDC/OAuth query params from the URL.

**Comment by edewit** [comment]
@stianst right found that, the responseMode had to be changed to `query` for that logic to work

**Comment by ssilvert** [comment]
> @stianst right found that, the responseMode had to be changed to `query` for that logic to work

@stianst Are you OK with this solution?  According to the doc, it says, "responseMode - Set the OpenID Connect response mode send to {project_name} server at login request. Valid values are query or fragment. Default value is fragment, which means that after successful authentication will {project_name} redirect to JavaScript application with OpenID Connect parameters added in URL fragment. **This is generally safer and recommended over query.**"

I don't know what "safer" means here.

**Comment by stianst** [comment]
For client-side fragment is safer. The fragment bit of the url is not sent to the server, which could then potentially be leaked in server logs etc. and when it's the client-side that parses the callback param they don't need to be sent server-side. With PKCE it is less of an issue though as the code is useless without the code-verifier which only the client has.

Just checked admin console. It uses fragment and the OAuth/OIDC query parameters are removed from the callback there. So the actual issue here may be in the new account console. It should not manually remove the parameters as done in this PR though.

**Comment by vmuzikar** [comment]
> Just checked admin console. It uses fragment and the OAuth/OIDC query parameters are removed from the callback there. So the actual issue here may be in the new account console. It should not manually remove the parameters as done in this PR though.

@stianst You mean the query params in Admin Console are somehow removed from the URL "manually", not automatically by keycloak.js? 

Maybe this affects only AIAs. The query params are correctly removed after logging in to the Account Console, but not after using an AIA.

@edewit Btw, `responseMode: 'query'` didn't completely fixed this. I can still see `kc_action_status` query param after using an AIA. This also confirm the tests in this PR which are correctly failing.

**Comment by edewit** [comment]
@stianst I'm no longer doing it manually, I've changed it so that it's done
by `keycloak.js`. But as I understand it, admin console shouldn't be using
the query, but the fragment instead? Now the fragment is already used by
react to do the routing will that not interfere with each other?

@vmuzikar @ssilvert  mentioned in the meeting that this `kc_action_status`
was used by the client to "know" what the user did and I guess it's right
that it's still there, so we should update the test?

**Comment by stianst** [comment]
@vmuzikar params are removed by keycloak.js in admin console, even with it using fragment as response_mode

If this is only an issue with AIAs then its probably down to how keycloak.js handles AIA responses. We probably need to update keycloak.js to remove kc_action_status, then add a callback onActionUpdate, which is called when callback includes kc_action_status and would include if its a success or failure (and include failure message). So that the app can do something like:

```
kc.onActionUpdate(function(status) {
 if (status='success') {
   notification('OTP registered successfully')
  } else if (status = 'cancelled') {
    // Ignore
  } else {
   notification('Failed to register OTP');
  }
}
```

**Comment by vmuzikar** [comment]
@edewit IMHO `kc_action_status` should definitely be removed from the URL at some point. We should keep the URL clean.

**Comment by stianst** [comment]
@edewit admin console uses fragment, and also angular uses fragment for its routes. The way it works is that keycloak.js remembers the fragment the user requested, then on the callback it reads the fragment, and replaces it with the initial fragment from before.

**Comment by stianst** [comment]
kc_action_status must be removed, not should. It's a callback parameter and not an application parameter. We need to introduce a callback handler as I suggested for apps that need to know the status of the kc_action.

**Comment by ssilvert** [comment]
> @vmuzikar params are removed by keycloak.js in admin console, even with it using fragment as response_mode
> 
> If this is only an issue with AIAs then its probably down to how keycloak.js handles AIA responses. We probably need to update keycloak.js to remove kc_action_status, then add a callback onActionUpdate, which is called when callback includes kc_action_status and would include if its a success or failure (and include failure message). So that the app can do something like:
> 
> ```
> kc.onActionUpdate(function(status) {
>  if (status='success') {
>    notification('OTP registered successfully')
>   } else if (status = 'cancelled') {
>     // Ignore
>   } else {
>    notification('Failed to register OTP');
>   }
> }
> ```

I wouldn't ignore 'cancelled'.  That can be useful to the client.

**Comment by stianst** [comment]
@ssilvert that was just an example of an app using it - for sure it should fire success/cancel/error events then the app can do with it what it wants

**Comment by abstractj** [comment]
@edewit whenever you get the chance, could you please follow up on the comments done in this PR? I'm afraid that if we take too long to respond, this will get completely outdated and the time that people invested to review it can be lost.

**Comment by edewit** [comment]
@abstractj that is fine, but I have no clue what to do with these comments

**Comment by abstractj** [comment]
@edewit if I understood correctly, @stianst stated that `kc_action_status` should not be removed, so I believe we can see this discussion as "resolved".

@stianst could you please summarize what's missing from your standpoint? I see some back and forth on this PR.

**Comment by stianst** [comment]
No OIDC params should be presented after keycloak.js has completed processing the callback. Rather an application should be able to register an event listener when an action has been completed. 

So the app would not parse query params, but rather do something like:
```
kc.onActionUpdate(function(status) {
 if (status='success') {
   notification('OTP registered successfully')
  } else if (status = 'cancelled') {
    // Ignore
  } else {
   notification('Failed to register OTP');
  }
}
```

**Comment by stianst** [comment]
Changing responseMode is not a fix to this issue - from my POV it's only a partial work-around if that.

**Review by stianst — CHANGES_REQUESTED** [review]
See previous comments - this approach is not correct

**Comment by stianst** [comment]
Cant' even see how this PR affects AIA at all, as it looks like account console is for some reason not even using keycloak.js when triggering an AIA:

https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/keycloak-preview/account/resources/app/util/AIACommand.ts#L30

**Comment by stianst** [comment]
So here's the mystery solved:

The new account console uses keycloak.js for authentication. By default this uses response_mode=fragment. In a regular login from the account console it works just fine.

Now when you do an AIA it is not using keycloak.js, but instead some hard-coded login URL in AIACommand which is completely wrong for several reasons. It uses the wrong client, it doesn't use PKCE, and finally it doesn't parse the callback.

So here's what happens when you do an AIA:

1. Auth request is done from AIACommand, with response_mode empty (query) and wrong client
2. AIA is complete and user is redirected back to account
3. Neither keycloak.js nor AIACommand will handle the callback, and the query parameters from the callback are left in the URL
4. Account console won't be authenticated anymore as tokens are lost from keycloak.js in step 1. If it used keycloak.js to trigger the AIA keycloak.js would have handled the callback and retrieved new tokens
5. Account console redirects to login again using keycloak.js (response_mode=fragment, but URL already contains the query params from 3)
6. Done

So every time you do a AIA you end up with double redirects to Keycloak

**Comment by stianst** [comment]
So here's how we should do it:
https://github.com/keycloak/keycloak/pull/6929

I don't know how to update the account console though to use keycloak.js login function instead of AIACommand stuff.

**Pull request closed without merging**
