### PR TITLE
only add realm access to the current realm

### LINKED ISSUE #21553: WhoAmI endpoint
> honestly don't know why it's adding roles for all realms, as the admin console is only displaying one realm at a time. So perhaps this can be relatively easily resolved by the whoAmI endpoint returning only roles the admin has for the currently selected realm

### PR DESCRIPTION
**Pull request by edewit**
fixes: #21553

### CODE REVIEW

**Review by jonkoops — DISMISSED** [review]

**Review by jonkoops — DISMISSED** [review]

**Comment by stianst** [comment]
Couple failing tests here:

AdminConsolePermissionsCalculatedTest:

I reckon we can just remove the line checking for permissions for the master realm:
https://github.com/keycloak/keycloak/blob/67b20dfd9b7c63f96bbd81a6ce8562f663fde56c/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminConsolePermissionsCalculatedTest.java#L76

AdminSignatureAlgorithmTest:

A bit weird this test as I don't get why it is doing the who-ami as it seems completely irrelevant. I reckon we can just delete the lines:

https://github.com/keycloak/keycloak/blob/67b20dfd9b7c63f96bbd81a6ce8562f663fde56c/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminSignatureAlgorithmTest.java#L61-L65

**Review by stianst — COMMENTED** [review]
LGTM just need to get the two broken tests to pass

**Review by ahus1 — APPROVED** [review]
Reviewed the code changes and tested it manually. 
Thank you for this change - this is a big step forward to support a lot of realms in the UI!

**Review by agagancarczyk — APPROVED** [review]
LGTM!

**Pull request merged**
