### PR TITLE
changed to use adminUrl instead

### LINKED ISSUE #19070: authBaseUrl error on different hostname-admin-url, hostname-url
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

On keycloak 21.0.1, we have hostname-admin-url, hostname-url configured with different values e.g 
--hostname-admin-url=admin.example.com
--hostname-url=auth.example.com
The above urls are configured as virtualhosts on reverse proxy
When I create a new realm, the default value ${authBaseUrl} is configured for all the clients.
The value of ${authBaseUrl} is always the value of hostname-admin-url, not hostname-url

### Version

21.0.1

### Expected behavior

The value of ${authBaseUrl} is the hostname-url

### Actual behavior

The value of ${authBaseUrl} is the hostname-admin-url

### How to Reproduce?

1. Start keycloak 21.0.1 with different hostname-admin-url, hostname-url
2. Use the hostname-admin-url to login and configure a new realm
3. Check on any client that ${authBaseUrl} is configured as Root URL
4. Confirm that ${authBaseUrl} is resolved to hostname-admin-url

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #19070
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

### CODE REVIEW

**Review by vmuzikar — COMMENTED** [review]
@edewit Thank you for the fix!

I noticed the `${authAdminUrl}` var is not expanded, the base URL is missing there. Is that expected?

Screenshot 2024-06-14 at 17 08 07

**Comment by edewit** [comment]
@vmuzikar the way I understood it from the issue is that it would replace `${authAdminUrl}` with the value for the base + adminUrl from the client, but for `security-admin-console` the adminUrl is empty so it just shows the rootUrl. But I might have misunderstood

**Comment by vmuzikar** [comment]
@edewit My understanding was that `authBaseUrl ` is replaced by [frontend URL](https://github.com/keycloak/keycloak/blob/c7361ccf6e3079dffd72e191e839822b3309c446/services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java#L343) and `authAdminUrl` is replaced by [admin URL](https://github.com/keycloak/keycloak/blob/c7361ccf6e3079dffd72e191e839822b3309c446/services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java#L331).

@mposolda @pedroigor Is that correct?

**Comment by edewit** [comment]
@vmuzikar like this?

**Review by vmuzikar — APPROVED** [review]
@edewit Thanks for the update. Based on manual testing, LGTM. (Did not review the UI code though.)

**Review by agagancarczyk — APPROVED** [review]

**Pull request merged**
