### PR TITLE
Add missing properties to keycloak-server.json for map storage

### LINKED ISSUE #10058: Keycloak configuration in testsuite doesn't provide properties for supported map storages
### Description

The configuration doesn't provide properties like `keycloak.authSession.map.storage.provider`  that are present for example in integration-arquillian. 

### Discussion

_No response_

### Motivation

Adding these properties would allow users to try out the new Map storage providers with less local configuration. A guide can then refer just to the properties that need to be set.

### Details

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #10058

### CODE REVIEW

**Comment by ahus1** [comment]
I added the properties I needed to enable all map storages for concurrent hash map and LDAP locally, and it allowed me to restart  Keycloak without JPA and re-login to the UI, therefore speeding up my local development. 

By adding it to this file with properties, I allows me to add properties to the run configuration instead of using locally edited configuration files.

The keycloak-server.json in the Arquillian integration test served as a template. Please comment if there is something missing and should be added. Thanks!

**Review by mhajas — APPROVED** [review]
Thanks @ahus1, LGTM

**Comment by mhajas** [comment]
btw. there is a maven profile that enables map storage as default for each area: https://github.com/keycloak/keycloak/blob/main/testsuite/utils/pom.xml#L280

> I added the properties I needed to enable all map storages for concurrent hash map
If I understand it correctly, this PR should not be necessary for enabling CHM for all map storages, it should be enough to just enable the `map-storage` profile. Am I missing something?

**Comment by ahus1** [comment]
Hi @mhajas - thanks for commenting on this. I now see that I can configure this to have some or all to use one map storage provider, for example the concurrenthashmap provider. 

Still, for my local tests I wanted to use the concurrenthashmap for some of the stores, and the new LDAP for the roles. With this PR, a configuration like this is possible (like it is also possible in the other keycloak-server.json in integration-arquillian). 

This configuration uses LDAP for roles, and concurrent hash map (the default) for all others:

```
-Dkeycloak.profile.feature.map_storage=enabled
-Dkeycloak.role.map.storage.provider=ldap-map-storage
-Dkeycloak.realm.provider=map
-Dkeycloak.client.provider=map
-Dkeycloak.clientScope.provider=map
-Dkeycloak.group.provider=map
-Dkeycloak.role.provider=map
-Dkeycloak.user.provider=map
-Dkeycloak.deploymentState.provider=map
-Dkeycloak.authSession.provider=map
-Dkeycloak.userSession.provider=map
-Dkeycloak.loginFailure.provider=map
-Dkeycloak.authorization.provider=map
```

**Comment by mhajas** [comment]
I see. I didn't want to say that this PR is wrong or not necessary. It is necessary when we want to set a different provider for authorization services or user sessions, etc. I just wanted to point out the maven profile we have for enabling map storage for each area so you don't need to set all these properties one by one.

It should be enough to use this:
```
mvn compile exec:java -Dexec.mainClass=org.keycloak.testsuite.KeycloakServer -Pmap-storage -Dkeycloak.role.map.storage.provider=ldap-map-storage

**Comment by ahus1** [comment]
In this run, CacheExpirationTest was unstable during startup. After refactoring of #9869 there should be more information on this. This test failure is unrelated to this change.

**Review by martin-kanis — APPROVED** [review]

**Review by vramik — APPROVED** [review]

**Review by hmlnarik — APPROVED** [review]
Approving per team approval

**Pull request merged**
