### PR TITLE
migration overwrites custom browser flow of imported realm (KEYCLOAK-1884)

### PR DESCRIPTION
**Pull request by gerbermichi**
https://issues.jboss.org/browse/KEYCLOAK-1884
added null check in migration

### CODE REVIEW

**Comment by stianst** [comment]
Not sure this is the correct approach. I think importRealms and migrateModel should be swapped around. Could you try changing:

    importRealms(context);
    migrateModel();

To:

    migrateModel();
    importRealms(context);

And see if that works for you?

**Comment by mposolda** [comment]
Then it needs to be swapped before calling of:

new ExportImportManager().checkExportImport

to also handle importing through import mechanism. But that will have other consequences though... Looks that null checks is the safest approach though.

**Comment by gerbermichi** [comment]
That is true, it works fine with the following order:

migrateModel();
new ExportImportManager().checkExportImport(this.sessionFactory, context.getContextPath());
importRealms(context);

should I create a PR with that?

**Comment by stianst** [comment]
Yes, please

**Comment by mposolda** [comment]
I think the order change won't work with the realms imported from previous version - for example realm file exported from version 1.2 doesn't have anything related to authenticationFlows in it. So it won't have filled authenticationFlows as migrateModel() will be called before import, so it will result in error. 

Same applies for hand-written JSON realm files (like our demo files) imported through import mechanism.

My vote is to keep the null checks as it is done in this PR.

**Comment by stianst** [comment]
Importing from json files shouldn't and can't rely on the migrate model for several reasons:
* Migrate model is only executed if importing to a new server - what about if you are importing one realm into an existing server where the migrate model has already executed. In this case the model in the database will be updated already and migrateModel won't run anything
* Realms imported through admin console also needs to be updated. This can't rely on migrateModel, but instead RepresentationToModel is used to translate the json files. We'll have more of this soon as we want to have partial imports of other things like clients, users, etc..

**Comment by mposolda** [comment]
Yes, I agree. The issue is that we have 3 mechanisms for import. 
1) admin console
2) Startup with -Dkeycloak.import
3) Startup with the system properties like -Dkeycloak.migration.provider=singleFile

The (1) and (2) are using RealmManager, which already checks if all the required builtins are available. I just have some doubts about (3) . I will need to doublecheck this though...

Maybe it's good time to simplify things and merge mechanisms (2) and (3) to avoid having 2 different mechanisms to import realm at startup. Maybe we can also remove some export/import providers. AFAIK 99% of people is using "singleFile" . The directory provider makes sense just for the environments with the big number of users, so looks we should still keep it. Not sure about zip provider, can't remember anyone ever using it. Should we remove it?

**Comment by stianst** [comment]
+1 Merging 2 and 3
+1 To remove zip provider

With regards to migrating JSON this should be done prior to importing into database, so shouldn't rely on db migration and migration manager.

**Pull request closed without merging**
