### PR TITLE
Instead of the test blocking for an unknown reason, specify a timeout

### LINKED ISSUE #29528: Failure: SessionTimeoutsTest
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

[Store Model Tests](https://github.com/keycloak/keycloak/actions/runs/9047369196)
[Store Model Tests](https://github.com/keycloak/keycloak/actions/runs/9034344676/attempts/1)

Run 1: SessionTimeoutsTest.testOnlineUserClientIdleTimeoutSmallerThanSessionNoRefresh:380->testUserClientIdleTimeoutSmallerThanSession:304->KeycloakModelTest.withRealm:593->KeycloakModelTest.inComittedTransaction:567->KeycloakModelTest.inComittedTransaction:571->KeycloakModelTest.lambda$inComittedTransaction$13:583->KeycloakModelTest.lambda$inComittedTransaction$12:567->KeycloakModelTest.lambda$withRealm$14:596->lambda$testUserClientIdleTimeoutSmallerThanSession$14:309 

Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project keycloak-model-test: There was a timeout in the fork -> [Help 1]

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

Pass

### Actual behavior

Fail

### How to Reproduce?

Run Store Model Test

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #29528

### CODE REVIEW

**Review by mabartos — APPROVED** [review]
I've encountered issues in model tests as the whole job was timed out due to certain waiting. It totally makes sense to me to specify the timeout for these two methods.

**Review by rmartinc — APPROVED** [review]
Thanks @ahus1! LGTM, at least we'll see if the tests pass at the 2nd attempt.

**Comment by ahus1** [comment]
Keeping my fingers crossed that it will reveal more information if it times out. I suspect it might be caused by the recent upgrade to Infinispan 15 and that some shutdown / async processing isn't working as we expect. Let's see once we have some reports.

cc: @pruivo

**Comment by pruivo** [comment]
@ahus1 The test is failing for my external Infinispan feature. I fixed by forcing Infinispan to remove the expired entries
```java
    private void processExpiration(boolean offline) {
        var hotRodServer = getParameters(HotRodServerRule.class).findFirst();
        if (hotRodServer.isEmpty()) {
            return;
        }
        // force expired entries to be removed from memory
        var cacheName = offline ? InfinispanConnectionProvider.OFFLINE_CLIENT_SESSION_CACHE_NAME : InfinispanConnectionProvider.CLIENT_SESSION_CACHE_NAME;
        hotRodServer.get().getHotRodCacheManager().getCache(cacheName).getAdvancedCache().getExpirationManager().processExpiration();
        hotRodServer.get().getHotRodCacheManager2().getCache(cacheName).getAdvancedCache().getExpirationManager().processExpiration();
    }
```

I'm also using `eventually()` (copied from ISPN source code) instead of test timeout. My code is here:
https://github.com/pruivo/keycloak/blob/8c79b577bdb56616bb9f58be25c98b92abfb8ba3/testsuite/model/src/test/java/org/keycloak/testsuite/model/session/SessionTimeoutsTest.java#L396-L416

**Pull request merged**
