### PR TITLE
Add mapping UserSessionNoteMapper into UserInfo claims

### LINKED ISSUE #15251: Add mapping UserSessionNoteMapper into UserInfo claims
### Description

We found that UserSessionNoteMapper does not support mapping to UserInfo. It would be nice to have an ability to map user session notes into UserInfo claims

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by RuslanTM**
Add mapping UserSessionNoteMapper into UserInfo claims

Closes #15251

### CODE REVIEW

**Comment by dteleguin** [comment]
@mposolda @tnorimat could you please take a look? it's a minimal PR but it adds some real value. Thanks!

**Comment by tnorimat** [comment]
@RuslanTM Hello. 
It seems that this PR does not include arquillian integration tests. Could you add them?

**Comment by dteleguin** [comment]
Hello @tnorimat, we looked into that and it seems like we don't have any integration tests for UserSessionNoteMapper currently (hence no tests within this PR). Should we introduce them?

**Comment by tnorimat** [comment]
@RuslanTM @dteleguin For example, the method `processClaimsRequestParamSupported` of `OIDCAdvancedRequestParamsTest` tests the mapper `ClaimsParameterTokenMapper` for UserInfo.

**Comment by mposolda** [comment]
Another hint for the tests: AbstractKerberosSingleRealmTest.credentialDelegationTest() uses UserSessionNote mapper under the covers. Maybe it helps to just add userInfo request into that test to make sure that claim is returned in userInfo?

**Comment by mposolda** [comment]
Another duplicated PR for the same thing: https://github.com/keycloak/keycloak/pull/15370 . I am keeping this PR open for now. When test is added, we can merge that one PR, which will first add a test :-)

**Pull request closed without merging**
