### PR TITLE
[WIP] Arabic for Keycloak

### PR DESCRIPTION
**Pull request by wowi42**
Trying again to have arabic inside the main keycloak repo

### CODE REVIEW

**Comment by wowi42** [comment]
@Eng-Fouad If you want to help :-)

**Comment by Eng-Fouad** [comment]
I actually started the translation but didn't finish it yet.

https://github.com/Eng-Fouad/keycloak/tree/ar-locale

**Comment by Eng-Fouad** [comment]
@wowi42 I've completed

- 100% of `base/email/messages/messages_ar.properties`
- 100% of `keycloak/v2/account/messages/messages_ar.properties`
- 90% of `base/account/messages/messages_ar.properties` 

The remaining are:

- `base/login/messages/messages_ar.properties`
- `base/admin/messages/messages_ar.properties`
- `base/admin/messages/admin-messages_ar.properties`.

I will start working on `base/login/messages/messages_ar.properties`, while you can start working on `base/admin/messages/messages_ar.properties` and `base/admin/messages/admin-messages_ar.properties` if you don't mind. Later on, we can merge our work together.

**Comment by Mouhand-Kaddo** [comment]
@Eng-Fouad I have completed the `base/admin/messages/messages_ar.properties` file but when I went to do the `base/admin/messages/admin-messages_ar.properties` file I couldn't find the English version of this file, if you could point me in the right direction I would appreciate it.

**Comment by Eng-Fouad** [comment]
> @Eng-Fouad I have completed the `base/admin/messages/messages_ar.properties` file but when I went to do the `base/admin/messages/admin-messages_ar.properties` file I couldn't find the English version of this file, if you could point me in the right direction I would appreciate it.

They just removed it in a [recent change](https://github.com/keycloak/keycloak/pull/16905/files). Please add your translation of `admin/messages/messages_ar.properties` in this branch: https://github.com/Eng-Fouad/keycloak/tree/ar-locale (add it as PR)

I am almost done with `login/messages/messages_ar.properties`.

**Review by Eng-Fouad — COMMENTED** [review]
`themes/src/main/resources-community/theme/base/login/messages/messages_ar.properties` is wrong, and it does not match `themes/src/main/resources/theme/base/login/messages/messages_en.properties`

**Comment by Mouhand-Kaddo** [comment]
@Eng-Fouad, I suggest we collaborate and merge our efforts into a single branch. Would it be possible for you to push your changes to this branch, or alternatively, could you grant me access so I can make the necessary changes on your branch?

**Comment by Mouhand-Kaddo** [comment]
@Eng-Fouad when you are done with the messages could you merge your branch into this one so that we merge it into main

**Comment by Eng-Fouad** [comment]
> @Eng-Fouad when you are done with the messages could you merge your branch into this one so that we merge it into main

I’ve completed the entire translations and opened another PR: https://github.com/keycloak/keycloak/pull/17090

**Pull request closed without merging**
