### PR TITLE
KEYCLOAK-12065 UserSessionInitializerTest is failing - NullPointerException

### PR DESCRIPTION
**Pull request by mabartos**
JIRA: [KEYCLOAK-12065](https://issues.redhat.com/browse/KEYCLOAK-12065)

### CODE REVIEW

**Comment by stianst** [comment]
The problem here is really that the test creates user sessions outside of a request context, so this is more a workaround than a real fix. Creating user sessions results in invoking code that is not intended to work outside of a request context.

What is a bit weird is that since it's not running in a new thread, it should strictly be using the context from the request to the test resource, so client connectino should in theory be there.

Not sure how trivial it is to update the test though.

**Comment by mposolda** [comment]
I see the test uses KeycloakModelUtils.runJobInTransaction . This starts new KeycloakSession and new transaction. It uses same thread as the caller thread, but different KeycloakSession and hence different KeycloakContext where the clientConnection is not injected. IMO it would be fine to refactor the tests to "inject" clientConnection to the new session - simply inherit it from the new session.

Conceptually, it is a bit strange to me that InfinispanProvider needs to call "DeviceActivityManager.attachDevice(adapter, session);" . IMO the model provider implementations should take care just about the CRUD of the model objects. So it may be better if the DeviceRepresentation is instead added as the argument to the UserSessionProvider.createUserSession. However that would be non-trivial changes and not something to handle in this PR.

So for this PR, I vote to just update the test and inject clientConnection to the proper places.

**Review by mposolda — CHANGES_REQUESTED** [review]
See above

**Comment by mabartos** [comment]
@stianst @mposolda Thanks for clarification. I'll fix this. :)

**Review by mposolda — APPROVED** [review]
@mabartos Thanks!

**Pull request merged**
