### PR TITLE
fix: allows the keycloak session to be accessed in prematching filters

### LINKED ISSUE #27446: keycloaksession access with PreMatching request filters
keycloaksession creation happens here: https://github.com/keycloak/keycloak/blob/77c4cee4d0ea84b17f9ef46fa70638fa16a46c87/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/CreateSessionHandler.java#L42

Which is controlled by https://github.com/keycloak/keycloak/blob/77c4cee4d0ea84b17f9ef46fa70638fa16a46c87/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/KeycloakHandlerChainCustomizer.java#L62

When a request filter is annotated with PreMatching, what we see is that it the filter will get invoked before the CreateSessionHandler runs.

The user indicates that in prior releases of Keycloak, using just the resteasy classic stack, that a PreMatching filter still had access to the session. 

In the prior releases the keycloaksession creation was handled by QuarkusRequestFilter https://github.com/keycloak/keycloak/commit/217a09ce46bac48b7492a881e2ca5fbeef9dfd6d#diff-80ef3a628be94a94774a6f6e71af1c5d29cfb9dedf6c1e88c39ceb5664662239L134 which was installed via https://github.com/keycloak/keycloak/commit/217a09ce46bac48b7492a881e2ca5fbeef9dfd6d#diff-6ebe7f8db3e4dea9dbefd50eed883b8aac997e6c01127e283631e92e9d022835L614 - which at first glance does appear like it would have priority to run before anything else.

_Originally posted by @shawkins in https://github.com/keycloak/keycloak/pull/27368#discussion_r1508939704_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #27446

cc @pedroigor @geoand @vmuzikar This is a good news / bad news kind of fix. The good news is that the KeycloakSession can be accessible in PreMatching filters. The bad news is that prematching is not covered by the handler customizer and needs to be covered by a new filter - but prematching also runs in a different thread than the method invoke handler, so we have to delay starting the transaction until BEFORE_METHOD_INVOKE. So we'd likely still need to document that if the user wants to do anything transactional that they need to use a filter that runs later. Alternatively we'd have to add logic to suspend / capture the transaction started by the filter that creates the session, then pick that up and resume it for use by the invoke logic.

Or is there a way to ensure the thread that is used by the prematching filter is the same as the one used for invoking?

### CODE REVIEW

**Comment by vmuzikar** [comment]
> Or is there a way to ensure the thread that is used by the prematching filter is the same as the one used for invoking?

I might be completely wrong but the way I understand it the request filters (what prematching is) should run on the same thread, at least based on [docs](https://quarkus.io/guides/resteasy-reactive#request-or-response-filters). Why it is not happening I have no clue.

Possibly adding `@Blocking` might do the trick as that should make the filter run on the worker thread – same as the resource method?

**Comment by shawkins** [comment]
@geoand any thoughts about what thread should be used for a PreMatching request filter vs. the handler before method invoke and PreMatching response filter?

**Comment by vmuzikar** [comment]
@shawkins I wonder if we should use the [Quarkus specific annotations](https://javadoc.io/doc/io.quarkus.resteasy.reactive/resteasy-reactive/latest/org/jboss/resteasy/reactive/server/ServerRequestFilter.html) instead for filters on our end.

**Comment by shawkins** [comment]
> I wonder if we should use the [Quarkus specific annotations](https://javadoc.io/doc/io.quarkus.resteasy.reactive/resteasy-reactive/latest/org/jboss/resteasy/reactive/server/ServerRequestFilter.html) instead for filters on our end.

I can certainly try that as well.

**Comment by shawkins** [comment]
That doesn't work either.

Underneath the covers the quarkus logic just generates a "standard" filter when you use that annotation. There's an advanced annotation that deals with kotlin suspension that deals with swapping the TCCL: https://github.com/quarkusio/quarkus/blob/04358cbe340364be73e79c7ada9e904422733d5f/extensions/resteasy-reactive/rest-kotlin/runtime/src/main/kotlin/org/jboss/resteasy/reactive/server/runtime/kotlin/AbstractSuspendedRequestFilter.kt - not sure if something like that could be applicable here.

**Comment by vmuzikar** [comment]
@shawkins Starting to seem like a Quarkus bug, TBH. As I mentioned, according to the docs the filter should run on the same thread. But I might have misunderstood it.

**Comment by geoand** [comment]
I don't remember the exact rules, I'll have to check tomorrow

**Comment by geoand** [comment]
I looked at what we do and because pre-matching filters are the first thing handlers that ever executed, they are always run on the event loop. 
We could theoretically change this, but unless there is a very good reason to do so, I am against it as it could have unintended consequences.

**Comment by vmuzikar** [comment]
@geoand Thank you for looking into this! Would it make sense to update the [Quarkus docs](https://quarkus.io/guides/resteasy-reactive#request-or-response-filters) then with the information that pre-matching filter always run on event-loop? Currently it implies that all request filters run on the same thread as the resource method. We can create an issue for it.

@shawkins I think we can just update Keycloak docs to mention transaction is started after pre-matching.

**Comment by geoand** [comment]
> @geoand Thank you for looking into this! Would it make sense to update the [Quarkus docs](https://quarkus.io/guides/resteasy-reactive#request-or-response-filters) then with the information that pre-matching filter always run on event-loop? Currently it implies that all request filters run on the same thread as the resource method. We can create an issue for it.

Clarifying the documentation always makes sense :)

**Comment by geoand** [comment]
#39354 updates the docs

**Comment by shawkins** [comment]
@vmuzikar updated the keycloak extension docs

**Comment by shawkins** [comment]
@vmuzikar @pedroigor @geoand took another pass with this pr to clear up some of the how the routing context and session closure is done. From what I can see the CloseSessionFilter is not necessary if we just register a completionCallback to do the close.

**Review by geoand — COMMENTED** [review]
Seems reasonable (albeit my knowledge of Keycloak is limited)

**Comment by shawkins** [comment]
Took one more pass to make the test failure work and to try to further refine the context handling. This elevates the threadlocal handling out of the ResteasyVertxProvider and into the Resteasy logic. Here are the remaining issues:

- The ResteasyContext appears to contain values by default, which are not present in the RoutingContext. This was captured as #27863 - I'm not sure what beyond the Providers could still have some assumption of availability.  For example if you run the services test without the ResteasyTestProvider, you will see errors because some context objects are not there.
- I'd like for things to look more like context propogation. We could take things further to remove the general usage of Resteasy.pushContext. Instead values would be stored directly on the KeycloakSession (KeycloakContext getContextObject and add putContextObject). That would make it so the only thing that needs special handling is the KeycloakSession itself. If the request context is active, then we'll pick the KeycloakSession up via the provider. If the request context is not active (for example during a KeycloakSessionTask run), the surrounding logic should handle treating the KeycloakSession as threadlocal if that is still needed - at least the SamlService calls Resteasy.pushContext(KeycloakSession.class, session); - although the changes in this pr to KeycloakModelUtils make that unnecessary.

**Comment by shawkins** [comment]
Moving back to draft - after talking about this with @pedroigor and the new direction where arbitrary jax-rs components are unsupported we'll focus instead on the light refactoring around the keycloakcontext instead with #28152

**Review by pedroigor — COMMENTED** [review]
@shawkins As discussed, I don't think we want to introduce so deep changes to enable a unsupported usage. I'm not sure the use case for having a filter in KC running so early and not when the request scope is available.

Also, this filter runs in the event loop and we don't want sessions managed at this point, I would say.

It is still possible to intercept requests by other means.

**Comment by shawkins** [comment]
> I'm not sure the use case for having a filter in KC running so early and not when the request scope is available.

My understanding was the request scope was avaialable.

> Also, this filter runs in the event loop and we don't want sessions managed at this point, I would say.

Ok, if there's no objections / additional thoughts from @vmuzikar then we can close the issue and this pr.

**Comment by vmuzikar** [comment]
> Ok, if there's no objections / additional thoughts from @vmuzikar then we can close the issue and this pr.

Works for me.

**Pull request closed without merging**
