### PR TITLE
Instead of returning instances with different semantics, throw an exception.

### LINKED ISSUE #12556: Throw exception in deprecated `KeycloakSession` methods
Throw an exception in all storage-related methods in `KeycloakSession` deprecated in #11933 rather than returning their generic counterparty

In other words, implement Option 2 from the _post by @mhajas in https://github.com/keycloak/keycloak/pull/11933#discussion_r899148011_.

Update the documentation accordingly, especially the Upgrading guide.

### PR DESCRIPTION
**Pull request by ahus1**
This exception points the caller to the migration guide of Keycloak 19.

Closes #12556

### CODE REVIEW

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Thank you for the changes! Apart from `*LocalStorage()` and `*StorageManager()` methods, please add deprecation note and exception to `userCache`, `userCredentialManager()`, and `userFederatedStorage()` methods as well.

**Comment by hmlnarik** [comment]
> AFAIK those three methods don't fall into the category "returning a generic counterparty", so I am surprised those should also throw an exception. Can you please describe a scenario when calling the current implementation would be a problem for the caller?

I see, this was not well stated :). Apologies for confusion
- `userCache()` needs the deprecation note in javadoc
- `userFederatedStorage()` will be tackled in a follow-up task and will throw an exception
- `userCredentialManager()` can remain as is

**Comment by ahus1** [comment]
@hmlnarik - deprecation note changed, ready for review. Will create a separate docs PR tomorrow.

**Review by hmlnarik — APPROVED** [review]

**Comment by ahus1** [comment]
PR for the docs is now available: https://github.com/keycloak/keycloak-documentation/pull/1598

**Pull request merged**
