### PR TITLE
KEYCLOAK-7774 KEYCLOAK-8438 Errors when SSO authenticating to same cl…

### PR DESCRIPTION
**Pull request by mposolda**
…ient multiple times concurrently in more browser tabs

### CODE REVIEW

**Comment by mposolda** [comment]
@hmlnarik @stianst Added some more info to the keycloak-dev thread "Issue with concurrent SSO login to same client in more browser tabs"

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Review by hmlnarik — APPROVED** [review]
Looks good to me, thank you!

**Pull request merged**
