### PR TITLE
KEYCLOAK-11967 Violation of UNIQUE KEY constraint SIBLING_NAMES

### PR DESCRIPTION
**Pull request by martin-kanis**

### CODE REVIEW

**Comment by martin-kanis** [comment]
I noticed some failed tests on postgres, I'll investigate this further. 
https://keycloak-jenkins.com/view/pipelines/job/universal-test-pipeline-server/1033/

**Comment by martin-kanis** [comment]
@hmlnarik @mposolda 
In the first run I noticed something suspicious. org.keycloak.models.ModelDuplicateException which I saw during development. I wasn't able to reproduce it locally with upstream postgres DB. Here is the link https://keycloak-jenkins.com/view/pipelines/job/universal-test-pipeline-server/1033 .
So I decided to give it another runs. https://keycloak-jenkins.com/view/pipelines/job/universal-test-pipeline-server/1037/ and https://keycloak-jenkins.com/view/pipelines/job/universal-test-pipeline-server/1042/ and I didn't see it again or anything else what could be a regression of this PR.
WDYT?

**Comment by hmlnarik** [comment]
IMO, these failures seem to be rather manifestation of https://issues.jboss.org/browse/KEYCLOAK-11866. The PR looks sane to me

**Review by mposolda — APPROVED** [review]
@martin-kanis Thanks!

**Pull request merged**
