### PR TITLE
Log some details if error happens in CIBA authentication request

### LINKED ISSUE #14650: ciba authentication policy not found in keycloak 19
### Describe the bug

according to the documentation, the ciba policy is still active and still a feature in the lastest keycloak version, but the problem is while im making a post request to http://localhost:8080/realms/XXXXX/protocol/openid-connect/ext/ciba/auth
with all the url-encoded params satisfied and verified, im getting a 503 service unavailable status code;
and the following response is what im getting:
**{
    "error": "server_error",
    "error_description": "Failed to send authentication request"
}**

### Version

19.0.1

### Expected behavior

it should return a authentication request id in the response body

### Actual behavior

**{
    "error": "server_error",
    "error_description": "Failed to send authentication request"
}**

### How to Reproduce?

just use the latest version of keycloak and try to use ciba authentication.

### Anything else?

in addition, the ciba policy is mentioned in the lastest documentation of keycloak and is referenced by :
realm settings-----> policies----> ciba policy
but this is false and it is not found there, thank you

### PR DESCRIPTION
**Pull request by mposolda**
Closes #14650

### CODE REVIEW

**Comment by mposolda** [comment]
@tnorimat Could you please review? There was an user reporting the issue, but it's not clear what the issue is for him due the fact that we don't log any details. So this is just 1-liner to add some logging.

See the underlying issue for the details: https://github.com/keycloak/keycloak/issues/14650#issuecomment-1441595556

**Comment by tnorimat** [comment]
@mposolda  Yes, I will review the PR soon.

**Review by pedroigor — APPROVED** [review]

**Review by tnorimat — APPROVED** [review]

**Comment by tnorimat** [comment]
CIBA Policy tab in a new admin console was implemented in https://github.com/keycloak/keycloak-ui/pull/4300

**Comment by mposolda** [comment]
@tnorimat @pedroigor Thanks

**Pull request merged**
