### PR TITLE
Refactor remote cache feature code

### PR DESCRIPTION
**Pull request by pruivo**
* Added missing copyright messages
* RemoteInfinispanAuthenticationSessionProvider should remove sessions during commit

I'm unsure if I should move the ` implements EnvironmentDependentProviderFactory` to the implementation. Currently, I added it to the `ProviderFactory` interfaces. Please advise, although my preference is to have it on the `ProviderFactory` interface to make it clearer that the provider depends on features/configuration.

### CODE REVIEW

**Comment by ahus1** [comment]
Looks good to me looking at the code changes. I re-ran the build as one of the tests in the store model tests failed. I trigger the whole CI as the artifacts have expired.

**Comment by pruivo** [comment]
It would be nice to have the feature branch rebased before merging this PR @ahus1 
I have my branch up to date here [1], need to wait for the test suite results :+1: 

[1] https://github.com/pruivo/keycloak/tree/feature/remote-cache-rebased

**Comment by ahus1** [comment]
@pruivo - please ping me when those tests are green, at the moment it seems they are not (might be flaky?)
https://github.com/pruivo/keycloak/actions?query=branch%3Afeature%2Fremote-cache-rebased

**Comment by pruivo** [comment]
@ahus1 there is a single failure in the Javascript CI test suite. I don't think the test suite in cause uses this feature or it is related to this issue :shrug:

**Comment by ahus1** [comment]
> there is a single failure in the Javascript CI test suite. I don't think the test suite in cause uses this feature or it is related to this issue 🤷

Ok, I pushed the rebased branch to the main repository. To merge the feature branch, all tests need to pass eventually, so this might be just postponing. 

Looking at the conflicts, you now might need to rebase this PR.

**Comment by pruivo** [comment]
rebased :+1:

**Comment by ahus1** [comment]
Thanks. Any idea why `testOnlineUserClientIdleTimeoutSmallerThanSessionNoRefresh` has been failing in https://github.com/keycloak/keycloak/actions/runs/9396813002/job/25879433575?pr=29638? 

I applied a change to so some additional cleanup, still it seems it might not be sufficient: f6f3b385c52db6165b5442edd0f9281e3598f2a6

I'd be happy if you could help out here, even if this PR is most likely not causing this.

**Comment by ahus1** [comment]
I was first scared when I read you'd remove the timeouts, now I see that you moved them to the condition. Thank you for that. The tests are green now, I assume we'll see more results when they fail for the next time.

**Review by ahus1 — APPROVED** [review]

**Pull request merged**
