### PR TITLE
[KEYCLOAK-7394] Change Content-Type to x-www-form-urlencoded for Real…

### PR DESCRIPTION
**Pull request by grgrzybek**
…mAdminResource#testLDAPConnection

### Check list

- [x] Pull-request manually verified/tested by @abstractj

- [x] Write integration tests for the current change

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by abstractj** [comment]
@grgrzybek first thanks so much for spending time on this. I manually tested your changes and they look good. Although, we need to make sure that this issue won't come back. For that, I would like to ask you to write integration for the admin console.

You can take a look at how to run them here: https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md#ui-tests. After that, take a look at this https://github.com/keycloak/keycloak/blob/cf056b346469b1010893b1220bfd8140242ce779/testsuite/integration-arquillian/tests/other/console/src/test/java/org/keycloak/testsuite/console/federation/LdapUserFederationTest.java.

**Comment by grgrzybek** [comment]
@abstractj Thanks for pointing me to tests - I'll have a look and try to provide test for my change

**Comment by grgrzybek** [comment]
@abstractj I tried to create such test, but:

1. there's already `org.keycloak.testsuite.console.federation.LdapUserFederationTest#testConnection()
2. I had to fix `testsuite/integration-arquillian/tests/other/console/src/main/java/org/keycloak/testsuite/console/page/roles/RoleDetailsForm.java` and `testsuite/integration-arquillian/tests/other/console/src/test/java/org/keycloak/testsuite/console/clients/ClientMappersOIDCTest.java` because they were not compiling
3. I had problems running this test because of:
```
unknown error: failed to change window state to maximized, current state is normal
  (Session info: chrome=67.0.3396.87)
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.16.15-300.fc28.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
```
4. I don't have that much time to investigate Selenium problems right now (even if I wanted to)...

I think `org.keycloak.testsuite.console.federation.LdapUserFederationTest#testConnection()` is exactly what's related to my change and it should work - after fixing selenium (?) issues.

**Comment by stianst** [comment]
@abstractj can you either write the test otherwise I think you should just manually review and merge. We can create a JIRA to create the test later. We need this fix in.

**Comment by abstractj** [comment]
PR rebased and superseded by https://github.com/keycloak/keycloak/pull/5511

**Pull request closed without merging**
