### PR TITLE
KEYCLOAK-13978 onTokenExpired + onAuthRefreshError

### PR DESCRIPTION
**Pull request by edewit**
implemented handlers and use context for "services"

### CODE REVIEW

**Comment by edewit** [comment]
UI tests build: https://keycloak-jenkins.com/job/keycloak-account2-matrix/910/

**Comment by ssilvert** [comment]
> UI tests build: https://keycloak-jenkins.com/job/keycloak-account2-matrix/910/

@edewit I checked on this and there are several failed tests.

**Comment by edewit** [comment]
@ssilvert let's wait for #7067 to be merged and then I'll have a look

**Comment by edewit** [comment]
UI build: https://keycloak-jenkins.com/job/keycloak-account2-matrix/917/

**Comment by ssilvert** [comment]
Kicked off new UI build #923

**Review by ssilvert — APPROVED** [review]

**Pull request merged**
