### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Keycloak/Admin UI](https://hosted.weblate.org/projects/keycloak/admin-ui/).

It also includes following components:

* [Keycloak/Theme base/email](https://hosted.weblate.org/projects/keycloak/theme-baseemail/)

* [Keycloak/Theme base/admin](https://hosted.weblate.org/projects/keycloak/theme-baseadmin/)

* [Keycloak/Theme base/account](https://hosted.weblate.org/projects/keycloak/theme-baseaccount/)

* [Keycloak/Account UI](https://hosted.weblate.org/projects/keycloak/account-ui/)

* [Keycloak/Theme base/login](https://hosted.weblate.org/projects/keycloak/theme-baselogin/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by ahus1** [comment]
@DimitriDR / @gilbert-fernandes - can you please review this French translation changes? Thanks!

**Review by ssilvert — DISMISSED** [review]

**Comment by ssilvert** [comment]
@ahus1 This doesn't follow our procedure of having an issue associated with it.  Have we decided to make an exception for Weblate?

**Comment by ahus1** [comment]
@ssilvert - I know we discussed this, and I agree to have issues when we add new languages. For small updates, I don't see the added value, especially as we currently don't backport those changes. 

An an issue would then usually be "update language X" which a bunch of changes to several labels across Keycloak.

So with those PRs coming from Weblate, I'd choose not to have issues.

**Comment by ahus1** [comment]
Gentle reminder: @DimitriDR / @gilbert-fernandes - can you please review this French translation changes? Thanks!

**Review by DimitriDR — APPROVED** [review]

**Review by DimitriDR — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]

**Comment by ahus1** [comment]
Thank you for the review, @DimitriDR!

**Pull request merged**
