### PR TITLE
Code certain features as upstream only

### LINKED ISSUE #23581: Code certain topics as upstream only
### Description

These topics should only appear in upstream

- 'Fine grain admin permissions
- New map storage 
- Token exchange

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andymunro**
Closes #23581

@ssilvert @pskopek  Now that certain features are marked as Development Preview, we need to remove all documentation about them except in the release notes.  Can you verify this change?

### CODE REVIEW

**Review by ssilvert — APPROVED** [review]
LGTM

**Comment by andymunro** [comment]
Thanks, @ssilvert

**Review by miquelsi — APPROVED** [review]

**Comment by andymunro** [comment]
Thanks, @miquelsi.  Can you merge this one, @ssilvert

**Comment by andymunro** [comment]
Thanks, @ssilvert

**Pull request merged**
