### PR TITLE
KEYCLOAK-7166 Made broker logout optional when doing browser logout, …

### PR DESCRIPTION
**Pull request by torbjornsk**
…through extending the endpoint with an additional query param.

Suggestion for how this could be solved. Tried to align with the way this is done for backchannel logout. For simplicity I added the behaviour to the existing logout endpoint, if the added query param is an issue it could be solved with a new logout REST-endpoint.

### CODE REVIEW

**Comment by stianst** [comment]
I'm not convinced about the approach with a query parameter. Should this not rather be configured on the identity brokering? I believe you can already do that today by simply not adding a logout endpoint to the IdP.

**Comment by torbjornsk** [comment]
Hi,

The thing is that the remote logout is useful when the logout is initiated
locally (by Keycloak or one of its client apps.) So there are two cases
that needs to be satisfied in order to achieve single logout:

- logout initiated by Keycloak: should redirect to logout of remote idp, to
achieve single logout.
- logout initiated by the remote idp: should have the possibility to
redirect to a logout endpoint of keycloak, without keycloak redirecting
back to the logout endpoint of the remote idp (which will result in either
a redirect loop, or a break in the redirect chain for logging out). Then,
logout from the remote idp will also log out of keycloak (slo).

I'm not all that sure of the query parameter solution myself, a separate
endpoint would probably be better. Went for the least amount on changes in
my pr, it was mostly to demonstrate the intent of the change. A separate
endpoint would probably lead to a simpler configuration on the remote idp
as well.

-Torbjørn

**Comment by torbjornsk** [comment]
So I need a solution that would provide single logout between keycloak and the remote idp, regardless of which of the two initiated the logout.

**Comment by torbjornsk** [comment]
That would be an elegant solution to the problem, but I'm not sure if implementing it this way would have any adverse effects for other use cases. But in my case, if the base of the "post_logout_redirect_uri" corresponds to the base of the various urls in the remote OIDC IDP configuration, it would work. I'm not totally sure what the actual callback url is, and how much of it will be equal to the configuration URLs.

I'll contact the remote idp tomorrow and ask them what value they are passing, and perhaps also whether they use some kind of standard or if they came up with the solution themselves.

**Comment by stianst** [comment]
I like what @mposolda is proposing.

**Comment by torbjornsk** [comment]
I'm still awaiting response from my remote idp, but if it is so that they use their regular logout uri as a post logout redirect in all cases, I think it would be an elegant solution. Then if the post logout redirect uri is equal to (or possibly starts with) the logout url defined in the remote idp config, there won't be a remote logout. I don't think just looking at the base of the url would work though, since there might be use cases where you would want the user to end up at the remote idp post-logout after initiating a local logout.

I'll keep you updated when I get an answer from my remote idp.

**Comment by torbjornsk** [comment]
They finally got back to me, turns out they have implemented the "frontchannel" spec, here: http://openid.net/specs/openid-connect-frontchannel-1_0.html

So it seems to me that a separate endpoint is required to solve this, as they are not using redirect as a mechanism (and have no way to add a post logout redirect url). They are using iframe from what they told me, but I'm not sure how it works on their end. It seems they need an endpoint for a get-request with optional parameters "iss" and "sid", which performs a downstream logout of all Keycloak clients, while not initiating any logout to the remote idp.

From what I could tell from the example they provided me, the value of the "iss" parameter is the same as the "issuer" in the OIDC configuration.

So, something like:

- A new endpoint for frontchannel logout for a realm
- Accepts get-request
- Accepts at least "iss" as a query param (and possibly also "sid", but don't know if that will be useful)
- Logs out the user from the Keycloak realm (and thus all Keycloak clients)
- Does not initiate logout from any remote idp where the issuer equals the value of the "iss" parameter

That would at least fulfill my current needs, not sure if the spec specifies any other stuff that needs to be implemented..

**Comment by stianst** [comment]
We've been holding off on implementing OpenID Connect Front-Channel as the specification has been untouched since January 2017.

I don't have any issue with accepting a contribution for OpenID Connect Front-Channel though if you want to do that. It would have to be a new endpoint as you say. It should be a complete implementation of the specification though.

However, I'm not sure that actually solves your problem as it would still in effect logout the IdP as well.

I think your current PR could be accepted if it's modified to use a query param "initiating_idp" or something that would be the id of the external provider. That way we know which IdP to exclude. There can be multiple IdPs linked to a single session in some cases.

**Comment by torbjornsk** [comment]
From what I could tell, there is only one identity provider connected to a session. This line:

String brokerId = userSession.getNote(Details.IDENTITY_PROVIDER);
in AuthenticationManager.java:483 (and the following code flow) seems to indicate that this is single-value. 

I could change my implementation to accept a query param "initiating_idp" with the alias of the idp in question as a value, but the way the code looks now this would be equivalent to my current solution.

**Comment by torbjornsk** [comment]
Hi

I have pushed changes as discussed above.

**Comment by mposolda** [comment]
- This PR is mixed with the different PR for KEYCLOAK-4538, which was already merged into KEycloak master. Could you please remove all the parts related to KEYCLOAK-4538 from this PR, rebase it on latest master and ensure it's squashed to single commit?

- Could you remove "import javax.ws.rs.*;" from LogoutEndpoint and keep the import of individual classes?

- We will also need some test for this. The brokering tests are here: https://github.com/keycloak/keycloak/tree/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker . Will be good to test that without the parameter, there is SSO-logout including broker. With the parameter used, the broker won't be logged-out.

- It will be good to document this. Probably add separate section under our Identity Brokering documentation: https://www.keycloak.org/docs/latest/server_admin/index.html#_identity_broker  about this custom logout endpoint and an example how to use it. Separate PR to docs need to be sent: https://github.com/keycloak/keycloak-documentation/

**Comment by torbjornsk** [comment]
I'll see what I can do. When it comes to the PR being "mixed", all I did was merge from origin/master, since some time had passed since I started my PR. Removing stuff from git that has already been pushed is nasty business, so maybe I should just create a new branch and PR?

**Comment by mposolda** [comment]
@torbjornsk You can create separate "temporary" branch and once it's properly rebased with latest master, you can replace the branch "KEYCLOAK-7166_make_broker_logout_optional_when_browser_logout" with this branch, so that PR is kept.

But if you feel, it's better to start new branch and new PR, feel free to do it. It will be far better option than accidentally replace your work :)

You can use cherry-pick to cherry-pick single commit (or 2 commits) from this branch on top of the master.

I generally like "rebase" and "cherry-pick" much more than "merge" due the clean history.

**Comment by torbjornsk** [comment]
Hi, finally got around to doing the requested changes, but the whole git mess got to difficult so I created a new branch and PR: https://github.com/keycloak/keycloak/pull/5347

Don't even know how git got messed up, all I did was merge/rebase from origin/master, but meh...

**Pull request closed without merging**
