### PR TITLE
Fixing compile time warnings

### LINKED ISSUE #17499: Avoid warnings when compiling HotRodServerRule
### Description

When looking at the build logs, I found the following strange compile time warnings in the log. All are related to the class HotRodServerRule

```
unknown enum constant org.infinispan.jmx.annotations.DataType.TRAIT
...
/home/runner/work/keycloak/keycloak/testsuite/model/src/main/java/org/keycloak/testsuite/model/HotRodServerRule.java:[102,43] enabled(boolean) in org.infinispan.configuration.cache.BackupConfigurationBuilder has been deprecated
```

### PR DESCRIPTION
**Pull request by ahus1**
Avoiding calling deprecated methods, and adding compile time dependencies for annotations.

Closes #17499

### CODE REVIEW

**Comment by ahus1** [comment]
@martin-kanis - when looking at the compile time logs, I found some strange compile time warnings around `HotRodServerRule` and I found that adding a compile time dependency prevents those warnings. 

I'm asking you as you've been involved in that class most of the time for a review. If you think you don't have time, please let me know and I'll ask within the team.

**Review by martin-kanis — APPROVED** [review]
Thank @ahus1 for this improvement!

**Comment by ahus1** [comment]
@hmlnarik - this is ready to be merged. Thanks!

**Review by hmlnarik — APPROVED** [review]
Approving per @martin-kanis's approval

**Pull request merged**
