### PR TITLE
KEYCLOAK-4375 Improve CLI tools test coverage and performance

### PR DESCRIPTION
**Pull request by mstruk**

### CODE REVIEW

**Comment by stianst** [comment]
@mposolda will sort out the performance issues as we're aiming to make all tests import realm per test class and not per-method.

SSL bits we need to discuss with QE

**Comment by stianst** [comment]
DON'T MERGE FOR NOW

**Comment by stianst** [comment]
@mstruk not sure what we should do about this? It looks like it's doing 3 things in one PR. Adding test coverage (this we can add), improving test performance (is this not resolved by Marek's recent changes to only import testrealm per test class), dealing with SSL test issues (this needs to be addressed separately and discussed with QE beforehand)

**Comment by stianst** [comment]
@mstruk I'm closing this. Please send separate PRs for the individual things if you want.

**Comment by mstruk** [comment]
Ok. So separate things I see here are two basically:

- performance
  (should be addressable with per-class realm import that @mposolda did - that then gets rid of test aggregation), 

- capability to run tests that require SSL
  (currently these are skipped as part of the testsuite tests, and the only way to run them is to set some system properties. That part we should communicate with the QE team how they want to run these tests, and if current way to skip by default, and activate via system properties is appropriate or it should be changed)

**Pull request closed without merging**
