### PR TITLE
Fixes SAML tests in testsuite

### LINKED ISSUE #16711: SAML tests in quarkus3 branch failing due to missing SAAJ factory
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

testsuite

### Describe the bug

SAML tests (e.g. `ArtifactBindingTest` fail on quarkus 3 branch due to missing SAAJ meta-factory:

```
Caused by: jakarta.xml.soap.SOAPException: Unable to create message factory for SOAP: Unable to create SAAJ meta-factory: Provider com.sun.xml.messaging.saaj.soap.SAAJMetaFactoryImpl not found
	at jakarta.xml.soap.MessageFactory.newInstance(MessageFactory.java:96)
	at org.keycloak.protocol.saml.profile.util.Soap$SoapMessageBuilder.<init>(Soap.java:120)
	... 142 more
```

### Version

quarkus3 branch

### Expected behavior

SAML tests should pass in the quarkus 3 branch

### Actual behavior

Tests such as `ArtifactBindingTest` fail on quarkus 3 branch

### How to Reproduce?

Run the mentioned tests using the quarkus 3 branch

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sguilhen**
- adds dependency to saaj-impl in saml core public
- updates test apps' web.xml files to use jakarta namespaces
- small cleanup in main pom
- changes order of e-mail servers in testsuite pom to enforce usage of greenmail (changes order in Undertow's classpath)

Closes #16711

### CODE REVIEW

**Review by ahus1 — APPROVED** [review]
Thank you @sguilhen - looks good to me! Thanks for migrating some more test to Jakarta!

**Comment by ahus1** [comment]
@sguilhen - on another note: Having to worry about the order of dependencies seems to be a bit fragile. Can you elaborate on the cause? Do both of them add the same classes to the class path? Could this also be solved by excluding dependencies?

**Comment by sguilhen** [comment]
@ahus1 I'd need to re-run one of the email tests to refresh my memory on the exact problem, but IIRC if subethamail ends up first in the classpath there was a jakarta/javax conflict. I'll try to run one of the tests again and I can add more detail later.

**Comment by mabartos** [comment]
@sguilhen JFYI I'm not able to successfully execute tests where the email is used. I'm trying to figure it out even with the GreenMail maintainers for JakartaEE support. It can also be related to this.

**Pull request merged**
