### PR TITLE
KEYCLOAK-8082 use level instead of gallery

### PR DESCRIPTION
**Pull request by edewit**
image

### CODE REVIEW

**Comment by edewit** [comment]
image
with just 3 boxes on a big screen

**Comment by edewit** [comment]
4 boxes on an iPad:
image

**Comment by edewit** [comment]
phone layout:
image

**Review by vmuzikar — COMMENTED** [review]
Thanks for the update!

To be completely honest, I have to admit that I don't like much the redesign. Not sure what exactly is wrong there, but I think it looks to me somehow... inconsistent and perhaps even a little bit chaotic. Every box has different shape, at some window sizes even different alignments (one box is on the left, other on the right).

Maybe we could take some inspiration from [Google](https://myaccount.google.com/) or [Microsoft](https://account.microsoft.com/). They use pretty much similar design but it somehow looks better.

But perhaps it's just me, I won't block merging this – I'm no UX expert after all.

**Comment by edewit** [comment]
Remember that we are not allowed to create our own css to make this look
good. This is the best I can do given the constraints. I wouldn't even
suggest this if this hadn't been the case.

**Comment by vmuzikar** [comment]
@edewit Yes, I know. Perhaps we should reach out to the PatternFly team and request some enhancement? I can imagine we're the first project using PF4 that needs some page like that.

**Comment by edewit** [comment]
I'm sure we are the only once that have such a strict rule:
https://developers.redhat.com/launch/
https://code.quarkus.io/

Where also built with patternfly react, but as you can see don't look like
standard patternfly. This is because the patternfly components were used as
building blocks to base the site upon, instead of taking them as they are.
I think a lot of users of patternfly work that way.

**Comment by ssilvert** [comment]
I agree with @vmuzikar that this doesn't look right.

If it requires custom CSS to do a card layout that looks good on different devices then that is definitely a PatternFly issue and needs to be fixed by them.  Or we just need to ask them what is the "PatternFly" way to do it.

I don't think those other apps are handing their PatternFly code to their customers and expecting them to generate new themes.  But our customers do need to do that.

Our strategy right now is to use PatternFly's CSS variables to allow customers to theme the application.  Our customers should be able to change one of PatternFly's CSS variables and trust that it will take effect throughout the app.

As I understand it, custom CSS could circumvent PatternFly's theme system.  So if we do include custom CSS it would need to be limited to tweaking PatternFly's CSS variables.

Lastly, I'll state that this is only my personal understanding of how we should be using PatternFly.  I'm not a CSS expert and I'm not even a good CSS amateur.  So I could be totally wrong.  But before we go off on our own we should at least consult with the PatternFly team.

**Pull request closed without merging**
