### PR TITLE
Update Social Identity Providers documentation

### PR DESCRIPTION
**Pull request by tondrusk**
Backporting to KC 22

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]
LGTM, ready to be merged once the KC22 branch is no longer locked.

**Comment by ahus1** [comment]
@tondrusk / @jonkoops - this PR can't be merged while checks are green. 

The Operator checks seems to be red due to a temporary mirror problem where it can't download the right packages for the image: 

> "[MIRROR] tzdata-2023c-1.el9.noarch.rpm: Interrupted by header callback: Inconsistent server data, reported file Content-Length: 864432, repository metadata states file length: 864888 (please report to repository maintainer)"

The admin UI tests also fail, and they failed more than once. Can one of you please have a look why this is the case?

**Comment by jonkoops** [comment]
@ahus1 the tests broke at some point, but the fix was never backported to 22. I've created #25072 to fix this.

**Comment by jonkoops** [comment]
Merged the fix for the Cypress tests and did a rebase, if all goes well the Cypress tests should not longer fail.

**Comment by ahus1** [comment]
@jonkoops - unfortunately the Admin UI tests still failed with either errors or timeouts. Could you please have another look?

**Comment by ahus1** [comment]
@jonkoops - I ran it again. No more timeouts this time, just one failing test.

**Pull request merged**
