### PR TITLE
KEYCLOAK-1306 - Better Admin API error handling

### PR DESCRIPTION
**Pull request by panga**

### CODE REVIEW

**Comment by stianst** [comment]
I can't merge this for several reasons:
* No associated JIRA
* This change hasn't been discussed on mailing-list - so I don't even know what you're trying to achieve with this
* Changes to a lot of files, for example every line in ClientAttributeCertificateResource is marked as changed
* We have our own provider framework in Keycloak so registering a MessageProvider with ResteasyProviderFactory is not the correct way to do things. Also, we haven't externalized log messages
or anything in the admin console, so this is a bit pointeless atm

**Comment by stianst** [comment]
Forget about the no associated JIRA - it's in the title. I blame Monday 7am ;)

**Comment by stianst** [comment]
Ok found thread about it on mailing list as well

**Comment by stianst** [comment]
Closing this PR for the following reasons:
* We don't want MessageProvider currently as we don't have internationalization support and it's not using our spi/provider framework.
* KeycloakExceptionMapper is not needed as we have ErrorResponseException which extends WebApplicationException to return a response with error message

**Comment by panga** [comment]
I understand your point.

The initial problem here was ModelException handling, as it's a unchecked exception and server was returning 500.

To fix that I implemented sort of I18N in admin because of message key and parameters returned in ModelException. It's a start point for messages and logging I18N.

No problem if you replace MessageProvider with KC spi or just rename to something else ;)

I know there're other issues opened about admin console internationalization, for me it's extremely necessary.

Another issue was that deprecated Resteasy Exceptions being used (NotFound, BadRequest), so I replaced with JAX-RS 2 ones that extend WebApplicationException.

I just changed the imports, I don't know the reason git marked all lines as changed, but I think it was because EOL characters (I'm linux user).

I agree that KeycloakException mapper could be replaced with just a ModelExceptionMapper because now all exceptions extends WebApplicationException.

What do you think?

**Comment by panga** [comment]
I understand your point.

The initial problem here was ModelException handling, as it's a unchecked
exception and server was returning 500.

To fix that I implemented sort of I18N in admin because of message key and
parameters returned in ModelException. It's a start point for messages and
logging I18N.

No problem if you replace MessageProvider with KC spi or just rename to
something else ;)

I know there're other issues opened about admin console
internationalization, for me it's extremely necessary.

Another issue was that deprecated Resteasy Exceptions being used (NotFound,
BadRequest), so I replaced with JAX-RS 2 ones that extend
WebApplicationException.

I just changed the imports, I don't know the reason git marked all lines as
changed, but I think it was because EOL characters (I'm linux user).

I agree that KeycloakException mapper could be replaced with just a
ModelExceptionMapper because now all exceptions extends
WebApplicationException.

What do you think?

**Comment by stianst** [comment]
If admin console internationalization is extremely necessary for you then we'd love a contribution for it. If you're up for this let's discuss how to proceed with it. It's not a high priority for us at the moment, so it will be a while until we could do it ourselves.

For KEYCLOAK-1306 are you only fixing missing messages on reset password? If so that'd be best done for now by just catching the exception there and returning an ErrorResponse. Admin endpoints shouldn't be using messages from login themes though.

Not sure ModelExceptionMapper/KeycloakExceptionMapper isn't the best approach. Internal exceptions aren't going to be convertible to user friendly error messages for admin console (or rest api) and it's probably best dealt with by catching exceptions in the methods themselves, like what we've done elsewhere.

**Comment by panga** [comment]
Certainly If needed I'll contribute to admin internationalization.
But for now I want start by fixing some logging messages, for example reset
password.
I wouldn't look at server.log every time a business exception occurs. This
simply doesn't scale!

We can catch the exception in the reset password method, but some problems
need be addressed:
- ModelException is an unchecked exception, it can be throw from anywhere.
So the problem will happen again.
- What message I would return? We're dealing with alot of PasswordPolicy
combinations and parameters.
- User messages are already been specified in base account and base login
themes, I'll need to create a third copy of the same message.
https://github.com/keycloak/keycloak/blob/8224f3ba4882a5e5ce257064374d7e074ba7d300/forms/common-themes/src/main/resources/theme/base/account/messages/messages_en.properties
https://github.com/keycloak/keycloak/blob/8224f3ba4882a5e5ce257064374d7e074ba7d300/forms/common-themes/src/main/resources/theme/base/login/messages/messages_en.properties

In that PR, I could replace my custom provider with KC provider SPI and
also create some admin theme messages. What do you think?

**Comment by stianst** [comment]
OK, let's start doing things properly then.

* Add ModelExceptionMapper
* Add MessageProvider SPI (Keycloak provider framework) - and add ThemeProvider implementation - don't add any localization stuff to it yet though. There's no way for api users or admin console users to select the locale.
* For now add messages_en.properties to base admin theme - we're considering fixing this by having a single place for all messages in the future (KEYCLOAK-1219)

**Comment by panga** [comment]
Ok, I've created a new PR based on your analysis.

https://github.com/keycloak/keycloak/pull/1261

**Pull request closed without merging**
