### PR TITLE
Switch testsuite to test with keycloak v2 login theme

### LINKED ISSUE #29009: Switch login theme to keycloak.v2: Stabilize testsuite after the switch

### PR DESCRIPTION
**Pull request by hmlnarik**
⚠️ **EDIT: Since the functional changes have been merged in #31402, this PR has changed to testsuite-only changes.** ⚠️

The fixes (mostly selectors) needed for tests.

In the future, to switch the default login theme to `keycloak.v2`, do the following:

- Update `ThemeSelectorProvider`: Uncomment [the relevant lines](https://github.com/keycloak/keycloak/blob/dc9de96f7b82b9ca97532cf985a2fe8f9e11e7fe/server-spi/src/main/java/org/keycloak/theme/ThemeSelectorProvider.java#L55-L57)
- Update `testsuite/integration-arquillian/tests/pom.xml`: Revert [the change](https://github.com/keycloak/keycloak/pull/30319/files#diff-c9f832b79f928bca025186fce32297ceda5fd8c28ffa4b071018d40fee7c6acbR213) in `<login.theme.default>` property
- Update `ThemeSelectorTest` per [comment](https://github.com/keycloak/keycloak/pull/30319/files#diff-32d5b1bd89cfeaf5ff3e429041d60d080c2055c2bc05d2131a35564e00a2585bR15-R18)
- Update `UncaughtErrorPageTest` per [comment](https://github.com/keycloak/keycloak/pull/30319/files#diff-a5e183948d759a2d0bd8c2ca24ab3a1c88df295b169e096a1a0917967a4a52a1R226-R227)

With the [prior removal of alpine.js](https://github.com/keycloak/keycloak/pull/31402), htmlunit is used again, and the workflow run times are similar to those with original `keycloak` login theme

Fixes: #29009

### CODE REVIEW

**Review by edewit — DISMISSED** [review]

**Review by mposolda — DISMISSED** [review]
@hmlnarik Thanks, I am approving! I have these notes:

- Minor concern: In general, I prefer selectors in tests to use element ID rather than `css` classes as `css` can change more often. But we already used selectors of css before this PR as well, so not a blocker for me. Just a note :-)

- My bigger concern is the fact that tests seem to run slower with chrome than previously with `htmlunit` . When looking briefly at some other PRs like for instance https://github.com/keycloak/keycloak/pull/30508 or https://github.com/keycloak/keycloak/pull/30495, it looks that the difference for `Base IT *` groups is 10-15 additional minutes per group - like for instance `Base IT (5)` group had before around 25 minutes, and with this PR, it has 40 minutes. Some other groups may have smaller difference.

IMO this is fine as we just need to be able to test with real browsers, however would prefer if this difference is reviewed also by other team leads.

**Comment by hmlnarik** [comment]
> @hmlnarik Thanks, I am approving! I have these notes:
> 
> * Minor concern: In general, I prefer selectors in tests to use element ID rather than `css` classes as `css` can change more often. But we already used selectors of css before this PR as well, so not a blocker for me. Just a note :-)

I am with you here. This PR aims for the minimal changes, so the changes are mostly in the selector (`css` vs `class`). Some of the changes are there due to dual testing of both `base` and `keycloak.v2` themes where the both use e.g. field names (`name` field) but have different element IDs. 

> * My bigger concern is the fact that tests seem to run slower with chrome than previously with `htmlunit` . When looking briefly at some other PRs like for instance [Adjust JpaEventQuery.toDate so that events fro… #30508](https://github.com/keycloak/keycloak/pull/30508) or [Add UPDATE event to the client-roles condition #30495](https://github.com/keycloak/keycloak/pull/30495), it looks that the difference for `Base IT *` groups is 10-15 additional minutes per group - like for instance `Base IT (5)` group had before around 25 minutes, and with this PR, it has 40 minutes. Some other groups may have smaller difference.
>   IMO this is fine as we just need to be able to test with real browsers, however would prefer if this difference is reviewed also by other team leads.

As you write, this is a direct consequence of testing with a real browser. The good news is that none of the timeouts specified in the workflows has been extended. Also good news is that this exercise revealed a few (multitab) tests which only work in an artificial htmlunit setup. That said, there are potential improvements possible like splitting the base testsuite into more than 6 groups which could be done after this PR like you suggested offline, should it be desirable. However, I similarly hold the same position that we need to be abled to test with real browsers, and thus would prefer keeping the proposed way of testing with a real browser to catch real issues.

**Comment by pedroigor** [comment]
Are we removing the current theme in Keycloak 26?

**Comment by hmlnarik** [comment]
> Are we removing the current theme in Keycloak 26?

There is no removal of the _current theme_ (`keycloak`) scheduled. The current theme will be available for extended period of time to allow for migration. At the same time the `keycloak` theme is based on pf3 which is not maintained anymore and we have to move to pf5-based theme moving forward.

**Comment by hmlnarik** [comment]
Rebased and resolved conflicts in `.github/workflows/ci.yml`.

**Review by edewit — DISMISSED** [review]

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@hmlnarik Thank you for the PR, nice work!

While I do appreciate the benefits of running with a real browser, the increased running time is a serious concern. I compared the test runs [in this PR](https://github.com/keycloak/keycloak/actions/runs/9610115469) with [today's nightly](https://github.com/keycloak/keycloak/actions/runs/9606128791). Some of the jobs are slower by just a couple of minutes but some much more than that (one takes 40 minutes longer). In summary it seems we need ~180 minutes longer of runners capacity. That of course does not mean each CI run will take 180 minutes longer – the jobs run in parallel – but it means we will block available runners longer which will make other CI runs wait longer. This might be especially problematic in private repos where we have limited time budget.

I believe this should be discussed in a wider team, the increase is quite significant and I'm not sure it's worth it.

I wonder how this aligns also with the effort around the testsuite refactoring.

**Comment by stianst** [comment]
> @hmlnarik Thank you for the PR, nice work!
> 
> While I do appreciate the benefits of running with a real browser, the increased running time is a serious concern. I compared the test runs [in this PR](https://github.com/keycloak/keycloak/actions/runs/9610115469) with [today's nightly](https://github.com/keycloak/keycloak/actions/runs/9606128791/job/26495249978). Some of the jobs are slower by just a couple of minutes but some much more than that (one takes 40 minutes longer). In summary it seems we need ~180 minutes longer of runners capacity. That of course does not mean each CI run will take 180 minutes longer – the jobs run in parallel – but it means we will block available runners longer which will make other CI runs wait longer. This might be especially problematic in private repos where we have limited time budget.
> 
> I believe this should be discussed in a wider team, the increase is quite significant and I'm not sure it's worth it.
> 
> I wonder how this aligns also with the effort around the testsuite refactoring.

That amount of additional time for testing is not possible, and would be a blocker for this for sure.

**Review by stianst — CHANGES_REQUESTED** [review]
Assuming @vmuzikar findings of additional required minutes to run the jobs is correct that is not acceptable; we're already at a limit of the number of parallel jobs and execution time in GitHub Actions, and need to find ways of using less runners/time per-PR not more.

**Comment by stianst** [comment]
Adding @miquelsi and @lhanusov as we've already done some effort in benchmarking execution times with Chrome to see if switching to that as the default would be feasible, but due to the increase execution time we decided to not pursue it.

**Comment by hmlnarik** [comment]
@stianst @vmuzikar The issue with the workflow run time has been addressed. Can you please revisit your review?

**Review by edewit — DISMISSED** [review]

**Comment by hmlnarik** [comment]
This PR is being split into #31402 and the testsuite and GHA changes which will be present here.

**Review by ssilvert — APPROVED** [review]
We need to merge this to make progress on Login V2.  It changes most of the tests to use Login V2.  It only affects how tests are run.

We plan to follow up with a PR that will fully test both Login V1 and Login V2 in the nightly build.

Meanwhile, Login V1 is still tested with FIPS tests and Docker tests, which provides us a nice sanity check on Login V1.

**Review by vmuzikar — COMMENTED** [review]
The changes as such LGTM, nice work @hmlnarik with resolving the issue with htmlunit!

My only concern is that we'll be now testing with a different theme that we ship as the default. I understand it's only temporary which is ok. But I wonder if we'll be able to make v2 the default before the next major release, i.e. Keycloak 26, so that we'd test the default.

**Comment by ssilvert** [comment]
> The changes as such LGTM, nice work @hmlnarik with resolving the issue with htmlunit!
> 
> My only concern is that we'll be now testing with a different theme that we ship as the default. I understand it's only temporary which is ok. But I wonder if we'll be able to make v2 the default before the next major release, i.e. Keycloak 26, so that we'd test the default.

@vmuzikar Regardless of which login theme is the default, we need to keep both around for awhile.  Login V2 needs to be fully vetted in the community before we make it the default for new realms.  However, V1 is pretty stable and should require less regression testing.   So we want to start testing against V2 as soon as possible because that's where the new development is happening.

For performance reasons, we don't want to run the tests against both versions each time a PR is submitted.  But we do plan to run both in the nightly build.

**Comment by vmuzikar** [comment]
@ssilvert Ok, makes sense. Thanks for clarifying.

**Review by vmuzikar — APPROVED** [review]

**Review by miquelsi — APPROVED** [review]

**Review by mposolda — APPROVED** [review]

**Pull request merged**
