### PR TITLE
KEYCLOAK-19348 SAML/ OIDC IdP AutoUpdate

### PR DESCRIPTION
**Pull request by cgeorgilakis**
Related PR to keycloak-documentation : keycloak/keycloak-documentation#1251
Based on discussion in [KEYCLOAK-10680](https://issues.redhat.com/browse/KEYCLOAK-10680) about autoUpdate SAML/OIDC Identity Provider.

### CODE REVIEW

**Review by hmlnarik — COMMENTED** [review]
Thank you for the PR.

Please regard this as a preliminary review (not checking UI and no in-depth code review). Could you please check inline questions / comments.

**Comment by cgeorgilakis** [comment]
[OIDC specification](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig) states that OIDC metadata URL must be equal to issuer + '/.well-known/openid-configuration. So, for autoUpdated OIDC IdP metadata URL is taken from mandatory field issuer. I have committed the change.
Could you continue the review?

**Comment by stianst** [comment]
From a quick glance at this it seems that the background task will update the configuration in the DB? We should not do that, but rather instead only have the config URL stored in the DB. This is especially important in the future when we have support for static configuration where the identity provider is configured in a read-only YAML file.

**Review by stianst — CHANGES_REQUESTED** [review]
I'd like to avoid having the stored configuration updated, and only keep the configuration URL in the DB.

**Comment by cgeorgilakis** [comment]
> I'd like to avoid having the stored configuration updated, and only keep the configuration URL in the DB.

Although I understand the need for static configuration support in future, we have concerns about only saving URL in database and dynamically read configuration. Take into account that Identity Provider configuration - meaning communicating with IdP URL- is needed during many parts of User login via Identity Provider. Things become more difficult for SAML due to needed XML parsing, many fields are taken from SAML IdP metadata, SP Descriptor URL as configuration in SAML Identity Provider. We could achieve better performance if we achieve a new caching mechanism for Identity Provider configuration - f.e for 1 hour. However, in this part we want your idea and help.

Maybe this discussion is more appropriate to be done in github discussions.

**Comment by stianst** [comment]
> > I'd like to avoid having the stored configuration updated, and only keep the configuration URL in the DB.
> 
> Although I understand the need for static configuration support in future, we have concerns about only saving URL in database and dynamically read configuration. Take into account that Identity Provider configuration - meaning communicating with IdP URL- is needed during many parts of User login via Identity Provider. Things become more difficult for SAML due to needed XML parsing, many fields are taken from SAML IdP metadata, SP Descriptor URL as configuration in SAML Identity Provider. We could achieve better performance if we achieve a new caching mechanism for Identity Provider configuration - f.e for 1 hour. However, in this part we want your idea and help.
> 
> Maybe this discussion is more appropriate to be done in github discussions.

+1 Yeah, a GH Discussion on this would be great. To make it clear I'm certainly not advocating that it is parsed on every request, etc. rather that there is a local cache, or a cluster-wide cache that is updated, rather than updating the persisted/DB config.

**Comment by cgeorgilakis** [comment]
github discussion : https://github.com/keycloak/keycloak/discussions/8697

**Comment by cgeorgilakis** [comment]
I have updated PR message based on the github issue( instead of old jira issue) and I have rebased it also.

Could you @stianst @hmlnarik continue reviewing this useful PR?
Although I do not know your plans for static IdP configuration, we need to autoretrieve Identity Provider changes instead of doing it by hand. As you can see from [discussion](https://github.com/keycloak/keycloak/discussions/8697) also other Keycloak users are intersting in this feature.

**Comment by cgeorgilakis** [comment]
I have made changes related to realm delete, realm partial/ full import. 
I have also replace System.currentTimeMillis with Instant.now().toEpochMilli().
From javadoc : 

> Returns the current time in milliseconds. Note that while the unit of time of the return value is a millisecond, the granularity of the value depends on the underlying operating system and may be larger. For example, many operating systems measure time in units of tens of milliseconds.

**Comment by djbulsink** [comment]
@stianst could you please continue the review of this PR? For us this functionality would be really useful because it would save us a lot of maintenance while having dozens of idp federations.   

Thanks,

**Comment by ammmze** [comment]
I am also interested in this functionality. We are planning to use keycloak to provide SSO integrations with a bunch of schools and having to maintain info for hundreds to a couple thousand idp's is not going to be fun.

**Comment by cgeorgilakis** [comment]
@djbulsink @ammmze I propose to continue discussion in [this github discussion](https://github.com/keycloak/keycloak/discussions/8697).

I do not understand why future Keycloak team goal for static IdP configuration blocks reviewing this. IdP configuration could be changed, it is not static. We want autoupdate to be done automatically.

**Review by stianst — COMMENTED** [review]
This should be reviewed by @pedroigor and/or @mposolda

**Comment by MartinNowak** [comment]
Would it make sense to start with a simpler approach and only update the SAML validating certificates from the metadata? Should mostly reassemble the JWKS URL support for [OpenID Connect](https://www.keycloak.org/docs/latest/server_admin/#_identity_broker_oidc).

**Comment by nicolabeghin** [comment]
Any update on this? Thanks!

**Comment by nicolabeghin** [comment]
> Would it make sense to start with a simpler approach and only update the SAML validating certificates from the metadata? Should mostly reassemble the JWKS URL support for [OpenID Connect](https://www.keycloak.org/docs/latest/server_admin/#_identity_broker_oidc).

for everyone stumbling on this: SAML certificates refresh has been merged with https://github.com/keycloak/keycloak/pull/24881 and will be released (AFAIK) with Keycloak 24.x - thanks @rmartinc !!

**Comment by cgeorgilakis** [comment]
> > Would it make sense to start with a simpler approach and only update the SAML validating certificates from the metadata? Should mostly reassemble the JWKS URL support for [OpenID Connect](https://www.keycloak.org/docs/latest/server_admin/#_identity_broker_oidc).
> 
> for everyone stumbling on this: SAML certificates refresh has been merged with #24881 and will be released (AFAIK) with Keycloak 24.x - thanks @rmartinc !!

SAML certificates is not the only (SAML or OIDC) Identity Provider attribute that may change and Keycloak should autoupdate the value in order to keep compliant with Identity Provider. Otherwise, you must find and make changes with ui.
This is problematic especially with large amount of Identity Providers.

**Review by pedroigor — COMMENTED** [review]
@sguilhen @cgeorgilakis It has been a long discussion. I would like to understand the motivation to schedule a task for each broker rather than a single one that updates all brokers.

I can see some reasoning behind this decision like fetching metadata taking some time to happen and impacting others brokers from updating or avoid having a long running task to update all brokers in a realm. But still, IMO a single task should be better if you make it right.

Wdyt?

**Comment by cgeorgilakis** [comment]
> @sguilhen @cgeorgilakis It has been a long discussion. I would like to understand the motivation to schedule a task for each broker rather than a single one that updates all brokers.
> 
> I can see some reasoning behind this decision like fetching metadata taking some time to happen and impacting others brokers from updating or avoid having a long running task to update all brokers in a realm. But still, IMO a single task should be better if you make it right.
> 
> Wdyt?

@pedroigor I agree with your proposal for having one update task. We could configure the delay in realm level.
My only concern is the possible long execution time. Think updating thousand of IdPs.
A possible solution could be asychronously update each autoUpdated IdP in this task. Do you agree?

**Comment by cgeorgilakis** [comment]
> > My only concern is the possible long execution time. Think updating thousand of IdPs.
> > A possible solution could be asychronously update each autoUpdated IdP in this task. Do you agree?
> 
> Makes sense to me.

Ok, I will try to provide a new PR based on this implementation and Keycloak changes as soon as possible.
I close this PR.

**Pull request closed without merging**
