### PR TITLE
Avoid table locks on CockroachDB by disabling optimistic locking

### LINKED ISSUE #13213: JPA Map Storage with CRDB: BackchannelLogoutTest failures
### Describe the bug

**org.keycloak.testsuite.oauth.BackchannelLogoutTest** presents failures/errors with `CockroachDB`:

```
[ERROR]   BackchannelLogoutTest.postBackchannelLogoutNestedBrokering:451 
Expected: response status code matches is <200>
     but: was <HttpResponseProxy{HTTP/1.1 504 Gateway Time-out [X-XSS-Protection: 1; mode=block, X-Frame-Options: SAMEORIGIN, Referrer-Policy: no-referrer, Date: Wed, 13 Jul 2022 18:30:31 GMT, Connection: keep-alive, Strict-Transport-Security: max-age=31536000; includeSubDomains, X-Content-Type-Options: nosniff, Content-Type: application/json, Content-Length: 0] [Content-Type: application/json,Content-Length: 0,Chunked: false]}> with entity 
[ERROR]   BackchannelLogoutTest.postBackchannelLogoutNestedBrokeringDoNotRevokeOfflineSessions:564 
Expected: response status code matches is <200>
     but: was <HttpResponseProxy{HTTP/1.1 504 Gateway Time-out [X-XSS-Protection: 1; mode=block, X-Frame-Options: SAMEORIGIN, Referrer-Policy: no-referrer, Date: Wed, 13 Jul 2022 18:30:31 GMT, Connection: keep-alive, Strict-Transport-Security: max-age=31536000; includeSubDomains, X-Content-Type-Options: nosniff, Content-Type: application/json, Content-Length: 0] [Content-Type: application/json,Content-Length: 0,Chunked: false]}> with entity 
[ERROR]   BackchannelLogoutTest.postBackchannelLogoutNestedBrokeringRevokeOfflineSessions:524 
Expected: response status code matches is <200>
     but: was <HttpResponseProxy{HTTP/1.1 504 Gateway Time-out [X-XSS-Protection: 1; mode=block, X-Frame-Options: SAMEORIGIN, Referrer-Policy: no-referrer, Date: Wed, 13 Jul 2022 18:30:31 GMT, Connection: keep-alive, Strict-Transport-Security: max-age=31536000; includeSubDomains, X-Content-Type-Options: nosniff, Content-Type: application/json, Content-Length: 0] [Content-Type: application/json,Content-Length: 0,Chunked: false]}> with entity
 ```
- Required JPA stores to reproduce the failure: **authenticationSessions** and **clients**

Logs for these tests show the following error on transaction commit:

 ```
Caused by: org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): "sql txn" meta={id=b62f10b4 key=/Table/1641/1/"\x82\x8c\xe8ÐrB0\x9e\xd2U\xaf\xa6\x1f)\xf5"/0 pri=0.01206459 epo=0 ts=1657800854.963471353,1 min=1657800854.787508613,0 seq=12} lock=true stat=PENDING rts=1657800854.787508613,0 wto=false gul=1657800855.287508613,0
```

### Version

main

### Expected behavior

Tests should run without failures or errors

### Actual behavior

_No response_

### How to Reproduce?

1- Setup CockroachDB according to the instructions in https://github.com/keycloak/keycloak/discussions/9596
2- Run the test using the map-storage-jpa profile:

```
cd testsuite/integration-arquillian

mvn clean install -Pmap-storage,map-storage-jpa -Dpageload.timeout=90000 \
-Dkeycloak.map.storage.connectionsJpa.url=jdbc:postgresql://localhost:26257/keycloak \
-Dtest=BackchannelLogoutTest
```

### Anything else?

_No response_

### LINKED ISSUE #14991: Deactivate optimistic locking when running JPA Map store on a DB with isolation level serializable
### Description

This is a spike to work around a problem on CockroachDB where using optimistic locking (which adds the `version` column to each delete statement) creates a lock that affects the table and not only the single row. 

 

### Discussion

_No response_

### Motivation

Avoid deadlocks on CockroachDB

### Details

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #14991 
Closes #13213

Undertow and the  Quarkus setup recognize a DB with serializable isolation level automatically. To analyze the SQL statements for the auth sessions, use the following CLI:

NOTE: after this change, updates are still using the version column for updates for PostgreSQL and CockroachDB: 

> update kc_auth_root_session set metadata=?, version=? where id=? and version=?

This changes only the deletes, see the following:

For PostgreSQL:

```
bin/kc.sh start-dev --storage=jpa --db-password=pass --db-username=keycloak --db-url=jdbc:postgresql://localhost:5432/keycloak --log-level=org.hibernate.SQL:debug | grep kc_auth_root
``` 

This generates: 

> delete from kc_auth_root_session where id=? and version=?

When running with CockroachDB:

``` 
bin/kc.sh start-dev --storage=jpa --db-password=pass --db-username=keycloak --db-url=jdbc:postgresql://localhost:26257/keycloak --log-level=org.hibernate.SQL:debug | grep kc_auth_root
```

This generates: 

> delete from kc_auth_root_session where id = ?

### CODE REVIEW

**Comment by ahus1** [comment]
@sguilhen - as discussed earlier this week, this is the PR with changes to disable optimistic locking when running on CockroachDB. 

While it detects the isolation level automatically on Untertow, a build time parameter is necessary for Quarkus. 

Have tested it with SQL logging locally, will need to do some more polishing later this week; probably not all changes are necessary for the final PR.  

cc: @vramik, @hmlnarik

**Review by sguilhen — COMMENTED** [review]
@ahus1 Thanks for working on this. I like the direction this is going, would just ask @pedroigor for his input on the quarkus side of things.

**Comment by pedroigor** [comment]
LGTM

**Comment by ahus1** [comment]
After reviewing the first approach to disable the version column in hibernate with the team and seeing the complexity, the following approach was implemented: 

* Do a native delete for the root authentication session when in isolation level serializable instead to avoid lots of configurations in lots of places. Thanks to @sguilhen for the suggestion. This seems to be the simpler solution
* All native and custom SQL needs should be stored in separate file `queries-*.properties` as this is a best-practice learned from the old store. The SQL goes into "default", and will be selected by the code whenever the DB connection is using a serializable isolation level.

**Comment by ahus1** [comment]
@sguilhen - this is now ready to review: 

* The issue comment at the top is updated to reflect the latest behavior tested locally
* It uses a delete without the version column (although it it still using it for any update - see top note).
* It passes the test described in #13213

**Review by sguilhen — APPROVED** [review]
Thanks @ahus1! It does look good to me, so approving.

I would just wait for @hmlnarik 's review before looking to merge this one.

**Review by sguilhen — APPROVED** [review]

**Review by hmlnarik — APPROVED** [review]
Approving per @sguilhen 's approval

**Pull request merged**
