### PR TITLE
[KEYCLOAK-13579] - Ignore exceptions when shutting down loopback server

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by stianst — COMMENTED** [review]
This looks like it would more just mask any potential issues while stopping the server?

**Comment by pedroigor** [comment]
@stianst Yeah, just in case. The server lifetime is really short and as long as the JVM is terminated we should be fine. Since we stop the server within a handler, it might happen that the server is already shutting down.

**Comment by stianst** [comment]
I see there could be valid reason why it would fail to run stop, but this would also mask if it doesn't manage to stop at all, which could then lead to longer running desktop app from hanging on to ports for example

**Comment by pedroigor** [comment]
See, this issue is related to security managers complaining about permissions when shutting down the server. I agree with you that it might happen to not stop the server.

But instead of having to change JVM policies to include permissions, I found it easier for users to just ignore and let them to take care of the status of the embedded server.

You know better than me how this used, but my assumption is that this component is executed on its own JVM and dies when the JVM terminates.

**Comment by stianst** [comment]
JVM that is running the app may be long lived, while this loopback server should be short lived. If it fails to close the server then it would keep being open and listening while it shouldn't until the app is closed. 

Not sure if there are reasons stop would fail though, nor really sure what the user would do about it. So I'm okay with this.

**Review by stianst — APPROVED** [review]

**Pull request merged**
