### PR TITLE
Allow verbose flag(s) to be accepted regardless of their CLI position

### LINKED ISSUE #13250: --verbose option doesn't work in Quarkus distribution
### Describe the bug

When there is an error during Keycloak startup there is the following error message:
```
ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (Quarkus Main Thread) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```
However, if I add `--verbose` parameter (for example: `./kc.sh start-dev --verbose`) it fails with:
```
Unknown option: '--verbose'
```

### Version

main

### Expected behavior

`--verbose` parameter works or Keycloak doesn't suggest using it.

### Actual behavior

Keycloak suggests using `--verbose` parameter but it doesn't work.

### How to Reproduce?

`./kc.sh start-dev --verbose`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by iankko**
Closes #13250

@pedroigor @keycloak/cloud-native PTAL once got a chance

Thanks,
Jan

### CODE REVIEW

**Comment by iankko** [comment]
This one needs updates to the text files comparing the output of the HelpCommand* output for the HelpCommandDistTest, since verbose flag is now listed in all screens. Moving back to draft.

**Comment by pedroigor** [comment]
@iankko The reason `verbose` is available only from the root command (`kc.sh`) itself is to allow using it with any other subcommand (e.g: `build`, `start`, etc).

The initial idea was to separate "cross-cutting" options such as `verbose` or `debug` from those related to subcommand options and reduce/improving a bit the help message for the subcommand.

Not sure how far this is aligned with CLI best practices though.

**Review by mabartos — APPROVED** [review]
@pedroigor @iankko

IMO, it makes perfect sense to specify the scope of the option to be global in our CLI; to be able to specify it regardless of its position. It'll bring us more benefits than drawbacks and improve our CLI UX.

AFAIK, the common scenario, in this case, is that user's trying to start the server, an error occurs, and CLI informs the user that for more details, provide the `--verbose` flag. The natural thing user will do is providing the flag at the end of the CLI. However, when the user does that with the latest upstream, another error message occurs: `Unknown option: '--verbose'`. That's not what we want.

IMO, the issue and PR are valid and should be accepted. 

@pedroigor Could you please little bit more elaborate on your concerns about this?

**Comment by pedroigor** [comment]
@mabartos The reasons are pretty much in my last comment.

I see the point but I'm not fully convinced it is the best. For instance, why debug does not work the same? Why `config-file` is not the same too?

For me, making them only available from the root command makes it more explicit that they are global (as you called them). And reduces a bit the verbosity of the help message.

Not sure if this gives the best UX though, for me it works fine.

**Comment by stianst** [comment]
@pedroigor @mabartos @vmuzikar I don't feel to strongly about this one, but would probably just close this PR and leave it as is. Wdyt?

**Comment by stianst** [comment]
Closing as this is resolved by https://github.com/keycloak/keycloak/pull/25590

**Pull request closed without merging**
