### PR TITLE
[KEYCLOAK-405] - Feature that doesn't allow old password to be reused

### PR DESCRIPTION
**Pull request by girirajsharma**
This PR doesn't allows resetting of N(3) old passwords.

### CODE REVIEW

**Comment by patriot1burke** [comment]
You can't implement it this way.  Your "oldPasswords" field will fill up pretty quick.  Instead you should add a "effectiveDate" to CredentialEntity and add a new CredentialEntity whenever a new password is issued.

**Comment by girirajsharma** [comment]
@patriot1burke "oldPasswords" field of CredentialEntity is a comma separated string containing only at most the last three passwords set (including the current one). So, it won't fill up. Current password is as well also stored in "value" field of CredentialEntity. I suppose a field like "effectiveDate" or "effectiveFromDate" will be better to be used for a similar issue https://issues.jboss.org/browse/KEYCLOAK-402.

**Comment by stianst** [comment]
This should be implemented as a password policy and the number of maximum old passwords should be configurable. Looks like it's now hard coded to always prevent the last 3 passwords. By default this should not be enabled.

The version in the database migration should be set to 1.2.0.RC1, not 1.2.0.Final. 

Also, I agree what Bill is proposing is cleaner.

**Comment by girirajsharma** [comment]
I am on the way doing the required changes and will issue a PR then.

**Pull request closed without merging**
