### PR TITLE
Modify OpenAPI spec POST /admin/realms

### LINKED ISSUE #25565: OpenAPI: POST for /admin/realms response is 201
POST for /admin/realms response is 201 (OpenAPI spec said 200)

### PR DESCRIPTION
**Pull request by y-tabata**
Closes https://github.com/keycloak/keycloak/issues/25565

### CODE REVIEW

**Review by ahus1 — APPROVED** [review]
Thank you for this PR - like the previous one, in a future PR please also add the other responses using `@APIResponses`.

**Comment by y-tabata** [comment]
@ahus1 Thank you for reviewing. This time I prioritized correcting the problem, I'd like to continue to contribute improvements to developer experience including adding error responses to OpenAPI.

**Comment by ahus1** [comment]
@y-tabata - please rebase this PR as the lastest main branch contains a fix for the failing WebAuthn test.

**Comment by y-tabata** [comment]
@ahus1 I rebased it.

**Review by ahus1 — APPROVED** [review]

**Pull request merged**
