### PR TITLE
KEYCLOAK-15976 Latvian language adjustments 

### PR DESCRIPTION
**Pull request by OskarsPakers**
Some adjustments for Latvian language translations related to #7507.
Converted messages_en.properties to utf8 to make it easier to compare files.

### CODE REVIEW

**Comment by ahus1** [comment]
Thanks for contributing this. I see that you converted the properties to UTF-8. This works only with JDK 9+, and the current Keycloak code base assumes JDK 8 (see docs/building.md). Therefore I ask you to revert the conversion. 

The [contributing guidelines of the repository](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md) also ask for a single commit. Therefore, please squash all change to a single commit. 

As with the previous PR, please ask some (for example on the Keycloak users list, or just someone familiar with the language to review the translations and approve them. 

For future pull requests, I ask you to open a bug issue first, and then create a pull request that references the bug issue as described in the contributing guidelines. Thanks!

**Comment by OskarsPakers** [comment]
@ahus1 Some files in main branch already contains utf8 properties files. See:
https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources-community/theme/base/login/messages/messages_pl.properties 
https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources-community/theme/base/login/messages/messages_nl.properties 

What`s the best way to squash commits in the Pull request? Isn`t it possible to squash them on merge?
I can find somebody who knows Latvian to approve this change, but I am not in the mailing list.

**Comment by ahus1** [comment]
Hi @OskarsPakers - thanks for pointing out the previous UTF-8 discussion; I wasn't aware of the "magic" at the beginning of the file that enables parsing them correctly.

Please keep the UTF-8 characters for `messages_lv.properties`, but revert all changes for `messages_en.properties` as they don't relate to the original subject of this PR. Converting the EN properties would be a separate issue and a separate commit. 

It would be possible to squash-on-merge, but this project prefers to squash the commits earlier. This avoids re-writing the squash commit message. 

To squash commits in a PR, first squash the commits locally, then force-push the changes to the remote branch.

**Comment by OskarsPakers** [comment]
I created a new pull request https://github.com/keycloak/keycloak/pull/10797 as I have remove my fork since. Please review that one instead.

**Pull request closed without merging**
