### PR TITLE
fix for issue "Attributes missing in OrganizationRepresentation when using Admin REST API in Keycloak 26"

### LINKED ISSUE #34590: Attributes missing in OrganizationRepresentation when using Admin REST API in Keycloak 26
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

After upgrading from Keycloak 25.0.6 to Keycloak 26.0.5 the attributes for the OrganizationRepresentation are missing when using the Admin REST API.

### Version

26.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

OrganizationRepresentation in Keycloak 26 should contain attributes when using Admin REST API.

### Actual behavior

When using Keycloak 25 the Admin REST API the OrganizationRepresentation when calling the endpoint `/admin/realms/{realm}/organizations` looks like the following example: 

```
[
    {
        "id": "dca0ec5a-3440-476d-b41e-91730e8b2da9",
        "name": "test-01",
        "enabled": true,
        "description": "test-01",
        "attributes": {
            "custom-attribute": [
                "My Test Organization"
            ]
        },
        "domains": [
            {
                "name": "test-01.org",
                "verified": false
            }
        ]
    }
]
```

After an upgrade to any Keycloak 26.0.X version the response for the same request looks like this:
```
[
    {
        "id": "dca0ec5a-3440-476d-b41e-91730e8b2da9",
        "name": "test-01",
        "alias": "test-01",
        "enabled": true,
        "description": "test-01",
        "domains": [
            {
                "name": "test-01.org",
                "verified": false
            }
        ]
    }
]
```

### How to Reproduce?

- Running Keycloak in version 25.0.6
- Creating an organization with some attributes in the Admin UI
- Upgrading to Keycloak 26.0.5
- Calling `/admin/realms/{realm}/organizations` endpoint

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by himanshi1099**
closes #34590

### CODE REVIEW

**Comment by jonkoops** [comment]
Hi @himanshi1099, please give your PR and commit a descriptive name of what it does and do not reference the issue in the title.

**Review by pedroigor — COMMENTED** [review]
Wouldn't be an option to get the representation by querying the organization by ID? AFAIK, the reason why we removed attributes from the representation is because we wanted to reduce the response payload for searches.

**Comment by dennis-schaefer** [comment]
Hello @pedroigor, yes, that could be an option. I just wondered, why I could not receive the attributes for the same request I did in version 25. And I could not find that change in any changelog either.

**Comment by pedroigor** [comment]
@dennis-schaefer Perhaps we can add a `briefRepresentation` parameter, similar to what we have in other places. If you set it to `true` then you get the attributes. By default, it would behave as it stands today.

Does it work for you?

**Comment by dennis-schaefer** [comment]
@pedroigor that sounds great!

**Comment by himanshi1099** [comment]
@pedroigor Shall I go ahead adding briefRepresentation parameter and raise PR again?

**Comment by himanshi1099** [comment]
@pedroigor Changes are done as per your suggestion can you please check

**Comment by pedroigor** [comment]
@himanshi1099 Thanks! I'll update a test to the PR.

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
