### PR TITLE
KEYCLOAK-4392 Copy component id from representation to model

### PR DESCRIPTION
**Pull request by anderius**

### CODE REVIEW

**Comment by anderius** [comment]
I have tested this locally, and I am now able to set the ID. If there is any test I should update, please give me a pointer to where that might be.

When scripting the configuration of Keycloak, this small change will be very much appreciated!

**Comment by stianst** [comment]
Please add tests to org.keycloak.testsuite.admin.ComponentsTest

**Comment by anderius** [comment]
I have now created some tests.

Should I create a PR against 2.5.x as well? Hoping to get this into RHSSO 7.1.GA.

**Comment by anderius** [comment]
@stianst I got an error message from Travis: 

> The job exceeded the maximum time limit for jobs, and has been terminated.

Is this something I can fix, or can you trigger a re-test?

**Comment by stianst** [comment]
@anderius I think I saw a customer ticket for this - are you using RH-SSO?

@pdrozd are you OK with including this in 2.5.4?

**Comment by anderius** [comment]
@stianst: Case #01788291 is me, yes. We are right now testing with Keycloak 2.5.1, but the plan is to change to RHSSO 7.1 when it becomes GA.  We tested the beta, but we wanted to use the new user storage SPI, which was not (yet) included.

**Comment by stianst** [comment]
@anderius I'll get this included in 2.5.4 / RHSSO 7.1 as well for you

**Pull request merged**
