### PR TITLE
KEYCLOAK-4322 : adding a helper class

### PR DESCRIPTION
**Pull request by sebastienblanc**
@abstractj can you take a look ?

### CODE REVIEW

**Comment by abstractj** [comment]
@sebastienblanc some questions.

1. What's the point of having https://github.com/sebastienblanc/keycloak/blob/2ddaa7f41a034532eaa4df0c57db5cc84bbae3a6/misc/keycloak-test-helper/src/main/resources/quickstart-realm.json ? I don't see any reference to this file at the sources.

2. Do we have tests for this helper?

**Comment by sebastienblanc** [comment]
1. Tests that uses this library can use it , like here https://github.com/sebastienblanc/keycloak-quickstarts/blob/quickstart-testing/service-jee-jaxrs/src/test/java/org/keycloak/quickstart/jaxrs/ArquillianTest.java#L48 , I know it's duplicated with the realm we have at the root of the quickstarts repo but it needs to be available in the classpath when doing `getResourceAsStream` , it's not optimal but not critical, we can fix this later. 
2. No, not yet

**Comment by abstractj** [comment]
@sebastienblanc -1 on it. IMO tests that need to reference it, should explicitly reference the file into their own projects. 

Reasons:

1. They have no control and idea over the content of the json file. They know that they're importing something for their tests, with no clue about what it is.
2. This module will never use this file.
3. Every time you get a new requirement for the quickstarts, you will need to change it and release keycloak modules to get the changes or run mvn install.

**Comment by sebastienblanc** [comment]
You're right, I will remove it and add it to the quickstart tests

**Comment by patriot1burke** [comment]
Any concerns left, can I merge?

**Comment by abstractj** [comment]
@patriot1burke I believe @sebastienblanc will do some updates to this PR

**Comment by sebastienblanc** [comment]
@abstractj realm json has been removed !

**Comment by abstractj** [comment]
@patriot1burke I believe we're good to go now

**Pull request merged**
