### PR TITLE
KEYCLOAK-19539 FAPI 2.0 Baseline : Reject Implicit Grant

### PR DESCRIPTION
**Pull request by tnorimat**
This PR is for [KEYCLOAK-18456 FAPI 2 Support](https://issues.redhat.com/browse/KEYCLOAK-18456), also is the part of [FAPI-SIG](https://github.com/keycloak/kc-sig-fapi) activity.

This PR is needed to satisfy requirements by [FAPI 2.0 Baseline](https://bitbucket.org/openid/fapi/src/master/FAPI_2_0_Baseline_Profile.md).
[KEYCLOAK-19539 FAPI 2.0 Baseline : Reject Implicit Grant](https://issues.redhat.com/browse/KEYCLOAK-19539) describes it more.

### CODE REVIEW

**Review by pedroigor — DISMISSED** [review]
LGTM.

@mposolda Wdyt?

**Comment by mposolda** [comment]
@tnorimat Thanks and sorry for the late review...

Would you mind also updating documentation and add few lines about new executor https://www.keycloak.org/docs/latest/server_admin/index.html#_client_policies ? You probably know that documentation is now part of the main repository (Directory `docs`)

**Comment by tnorimat** [comment]
@mposolda I added the documentation of this executor.

**Review by mposolda — APPROVED** [review]
@tnorimat Thanks!

**Pull request merged**
