### PR TITLE
Removal of retry blocks introduced for CRDB

### LINKED ISSUE #24095: Map Store Removal: Delete retry blocks introduced for CockroachDB
### Description

With the Map Store being removed, we have to delete the retry logic that was added to a few endpoints to handle concurrency when using CockroachDB.

### PR DESCRIPTION
**Pull request by vramik**
Closes #24095

### CODE REVIEW

**Comment by vramik** [comment]
@sguilhen Could you take a look once you got a chance? Thank you

**Review by ahus1 — COMMENTED** [review]
Hi @vramik - thank you for identifying the code occurrences that need changes. When digging into the code history in Git, I found that two classes could be simplified further: The transaction wrapper we added for component changes wasn't there before the map store, so I removed it. I also removed the locking code, which we were supporting only for the map store so far. 

Please let me know what you think about this change. Let's hope the tests will be green.

**Comment by vramik** [comment]
Thank you @ahus1! Your changes lgtm. 

As discussed on a call, I was planning to update `TokenEndpoint` withing next PR when `Profile.Feature.MAP_STORAGE` will be removed: https://github.com/vramik/keycloak/commit/ec6098707ddcae352af665ce0db320c77f2d5335#diff-6e6a77363b94c36b9ec82d765274264ab137e93190dc0e0da3dfb8b3ee449e91L181-L197 but from my POV it can stay here and I'll update next PR.

Changes in `ComponentResource` simplify the code, thanks for that. There is a issue for removal `LockObjectsForModification`: https://github.com/keycloak/keycloak/issues/24793

**Review by sguilhen — APPROVED** [review]
Thanks @vramik and @ahus1 LGTM!

**Review by ahus1 — APPROVED** [review]
Approving as of @sguilhen's review. Thank you for this change!

**Pull request merged**
