### PR TITLE
Fix OpenshiftClientStorageTest.testCodeGrantFlowWithServiceAccountUsingOAuthRedirectReference (#15741)

### LINKED ISSUE #15565: Flaky test: OpenshiftClientStorageTest.testCodeGrantFlowWithServiceAccountUsingOAuthRedirectReference
### Area

testsuite

### Describe the bug

```
OpenshiftClientStorageTest.testCodeGrantFlowWithServiceAccountUsingOAuthRedirectReference:176->testCodeGrantFlow:221->testCodeGrantFlow:240->lambda$testCodeGrantFlowWithServiceAccountUsingOAuthRedirectReference$0:176->assertSuccessfulResponseWithoutConsent:244->assertSuccessfulResponseWithoutConsent:255->assertSuccessfulRedirect:271
```

### Version

main

### Expected behavior

Test pass always

### Actual behavior

Test fails randomly, with 3 failures last 7 days on GitHub Actions

### How to Reproduce?

```
============================================================================================================================================
Finding details for OpenshiftClientStorageTest.testCodeGrantFlowWithServiceAccountUsingOAuthRedirectReference
============================================================================================================================================
https://github.com/keycloak/keycloak/actions/runs/3494331231

Base testsuite (quarkus, group3)	Run base tests	2022-11-18T06:06:05.5404958Z -- [ERROR]   OpenshiftClientStorageTest.testCodeGrantFlowWithServiceAccountUsingOAuthRedirectReference:176->testCodeGrantFlow:221->testCodeGrantFlow:240->lambda$testCodeGrantFlowWithServiceAccountUsingOAuthRedirectReference$0:176->assertSuccessfulResponseWithoutConsent:244->assertSuccessfulResponseWithoutConsent:255->assertSuccessfulRedirect:271
--------------------------------------------------------------------------------------------------------------------------------------------
https://github.com/keycloak/keycloak/actions/runs/3476545118

Base testsuite (quarkus, group3)	Run base tests	2022-11-16T06:06:27.8369156Z -- [ERROR]   OpenshiftClientStorageTest.testCodeGrantFlowWithServiceAccountUsingOAuthRedirectReference:176->testCodeGrantFlow:221->testCodeGrantFlow:240->lambda$testCodeGrantFlowWithServiceAccountUsingOAuthRedirectReference$0:176->assertSuccessfulResponseWithoutConsent:244->assertSuccessfulResponseWithoutConsent:255->assertSuccessfulRedirect:271
--------------------------------------------------------------------------------------------------------------------------------------------
https://github.com/keycloak/keycloak/actions/runs/3449634399

Base testsuite (quarkus, group3)	Run base tests	2022-11-12T06:05:55.3393893Z -- [ERROR]   OpenshiftClientStorageTest.testCodeGrantFlowWithServiceAccountUsingOAuthRedirectReference:176->testCodeGrantFlow:221->testCodeGrantFlow:240->lambda$testCodeGrantFlowWithServiceAccountUsingOAuthRedirectReference$0:176->assertSuccessfulResponseWithoutConsent:244->assertSuccessfulResponseWithoutConsent:255->assertSuccessfulRedirect:271
--------------------------------------------------------------------------------------------------------------------------------------------

```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #15565

This is a backport of #15741

### CODE REVIEW

**Comment by ahus1** [comment]
Model tests failed due to DBLock test with is still unter investigation in main and disabled there, see #15487 

Quarkus tests failed due to problems loading PhantomJS, which is currently being handled in the new build process approach, see #15861

Therefore this should now be ready to be reviewed and merged.

**Comment by ahus1** [comment]
Hi @stianst - I backedported your change to main to the release branch to stabilize it as it turning some of my other backport PRs with red builds. 

Please approve. Thanks!

**Review by mhajas — APPROVED** [review]
Thanks @ahus1

**Pull request merged**
