### PR TITLE
KEYCLOAK-8681: Support OTP secrets containing non-ISO-8859-1 characters

### PR DESCRIPTION
**Pull request by ChrisBrandhorst**
We need support for the [Feitian C-200 OTP hardware token](https://www.ftsafe.com/Products/OTP/Single_Button_OTP). This token is supplied together with a text file containing the secrets of these tokens with their serials. We have a custom required action which allows the user to enter the serial of their device, after which we lookup the secret and add it to the user credentials.

These secrets are given as a hex string with values from `00` through `FF`, for example:
`41414141414141414141414141414141414141c6`

This hex string is placed into the database as "normal text" and when Keycloak loads this value, it is represented as a Java String (UTF-16):
`AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\u00c6`

The final character in this example gives problems, because `HmacOTP#generateOTP` calls `getBytes()` on this key, which explodes this final character into **two** bytes, making sure the calculations go wrong. Of course, any character which needs to be represented as a unicode point will be a problem.

This PR fixes this issue by forcing the encoding during this operation, and also removes some superfluous lines.

### CODE REVIEW

**Comment by stianst** [comment]
I wonder if this could break OTP setup for existing users after an upgrade

**Comment by ChrisBrandhorst** [comment]
I don't think it will be a problem, since Keycloak only generates secrets using characters for which the `getBytes` does not give different results (all charcodes are < 128).

I can of course check whether this is the case on my own development environment: set a new secret using the old code, then apply the codechange and check if the user can still login. But I can imagine you'd want something more watertight than a comment on Github :)

I've been thinking about extending `LoginTotpTest` to check the old and new behaviour against each other, but everything I can think of will result in quite some code duplication. Now I think about it again, we can also enable switching the behaviour at runtime (something like `HmacOTP#setGetBytesCharset`), which can be used in the test (but nowhere else). What do you think?

**Comment by hmlnarik** [comment]
@ChrisBrandhorst Thanks for the PR. I have similar concerns as @stianst. If a secret (potentially not generated by Keycloak) contains non-ISO-8859-1 characters and has been scuccessfully used already, then this change would break it.

The proper way to fix this would require changing storage of the key in the CredentialStore. Likely we can use Base64 or similar encoding to store it in a text field. Such a change has to be backwards compatible and must be able to distinguish a secret stored in earlier keycloak version and one that's being used one. Then `generateOTP` with `String` key would be deprecated in favor of a newly introduced `generateOTP` method that takes `byte[]` as input; and the related code would be changed to obtain the key in `byte[]` form and prefer the new version whenever possible.

Last, but important point - please create a JIRA first and refer it both in the commit message and the PR title.

**Comment by thomasdarimont** [comment]
@ChrisBrandhorst nice one! I also had to deal with C200 OTP Generators a while ago:
https://issues.jboss.org/browse/KEYCLOAK-1893

Is there any chance you could share your custom required action for C200 token setup?

**Comment by ChrisBrandhorst** [comment]
JIRA issue created: https://issues.jboss.org/browse/KEYCLOAK-8681

@thomasdarimont Sorry, we do not have the required action yet because of this issue :)

@hmlnarik Thanks for the comment. At first I didn't think this could cause issues, but it indeed **is** possible that secrets are not generated by Keycloak (as is in our usecase).

Looking at the code, i see {{CredentialModel}} has a {{config}}. Would you say adding an entry to this {{config}} by the {{OTPCredentialProvider}} be a proper way to distinguish between the old and new way?

**Comment by hmlnarik** [comment]
@ChrisBrandhorst Thank you for the contribution. Sadly, current priorities and bandwidth does not allow us to work on this PR at this moment. Therefore this PR is currently marked on hold. We will be happy to continue the work after 4.x is wrapped up.
Thank you for understanding.

**Comment by ChrisBrandhorst** [comment]
@hmlnarik Now that 4.x is out, we would be happy to rework this PR to something acceptable. To do that, we need an answer to our latest question. Can this be provided?

**Comment by hmlnarik** [comment]
@ChrisBrandhorst I am sorry for late reply, was unable to get to PR reviews earlier.

> Looking at the code, i see CredentialModel has a `config`. Would you say adding an entry to this `config` by the `OTPCredentialProvider` be a proper way to distinguish between the old and new way?

Generally yes; specifically it depends on what you would like to use `config` for. Is the intention that the `value` still would be used for the base64-encoded secret but some `config` flag would mark it as base64? That should work, however the max length of the encoded secret would be 255 characters due to storage limitations. It should possible to store the secret in the credential attribute (i.e. `config`) instead where the limitation is 4000 characters, then `value` should be ignored if such an attribute would be set.

**Comment by ChrisBrandhorst** [comment]
@hmlnarik No problem.

To store the actual secret in the `config` sounds a bit iffy to me.
I'd say the storage limitation of 255 characters would suffice, this would mean we have room for 190 decoded characters. I have not yet seen a hardware token with a secret that long.

We'll start work on a new PR.

**Comment by stianst** [comment]
@ChrisBrandhorst we've changed the issue to a bug, as after revisiting it we agree that it is indeed a bug and not an enhancement request. Are you able to address the comments from @hmlnarik ?

**Comment by ChrisBrandhorst** [comment]
@stianst Sorry for the delay I haven't had much time to work on this. The comments are enough to move forward.

**Comment by ChrisBrandhorst** [comment]
@hmlnarik @stianst I would like to revisit Hynek's statement about the possibility of having existing non-ISO-8859-1 characters in the db prior to making this change.

Is it not true dat if such a secret is present in the database it can never have been correctly validated by the vanilla Keycloak implementation in the first place, or any extension that uses the same code?
Thus (I infer), for such a secret to be present also requires custom validation code in some extension, which will not be affected by this change.
So, any change in this code should not affect the validation of such a secret?

**Comment by hmlnarik** [comment]
> Is it not true dat if such a secret is present in the database it can never have been correctly validated by the vanilla Keycloak implementation in the first place, or any extension that uses the same code?

That is not generally true. The vanilla implementation might or might not actually work, depending on the settings of the locale both in Java (see [getBytes](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#getBytes())) and database.

**Comment by ChrisBrandhorst** [comment]
Ah, thanks for that pointer. All clear now.

**Comment by ChrisBrandhorst** [comment]
Rewrite done based on all input. Unsure if any more tests should be extended for this, please advise.

**Comment by stianst** [comment]
Looking at the PR the amount of changes worries me and I'm concerned this could introduce regressions. I also question whether or not the built-in credential which was developed to support software OTP authenticators should be extended/modified to support hardware devices.

I would actually rather have expected a custom authenticator, action and credential type to support hardware tokens. In the end I assume the saved credential will either work for software OTP, or it will work for a specific hardware OTP, not be able to be used both places. Hence it should probably be a different credential type so it can be bound to the correct authenticator/action.

We are currently working on making it easier to add support for custom authenticators as part of the webauthn work. See https://github.com/keycloak/keycloak-community/blob/master/design/multi-factor-admin-and-step-up.md and https://github.com/keycloak/keycloak-community/blob/master/design/web-authn-two-factor.md. The aim here is to allow multiple two factor types to exist withing a realm and allow users to select which to use.

**Review by stianst — COMMENTED** [review]
See comment. I'm sorry to bring this so late, but I'm uncertain that this should be accepted.

**Pull request closed without merging**
