### PR TITLE
Update codeql-analysis.yml

### PR DESCRIPTION
**Pull request by stianst**

### CODE REVIEW

**Review by abstractj — COMMENTED** [review]
I believe we can close this PR considering that https://github.com/keycloak/keycloak/commit/38d817b7b98aba192a4fe5cbaa73188da2f59fde was merged.

**Comment by stianst** [comment]
@abstractj this was mainly to update the action, was hoping it would magically fix the error we're getting:

    Error: {"msg":"SARIF content is too large"}

**Comment by stianst** [comment]
Closing since it didn't actually seem to fix the issue

**Comment by abstractj** [comment]
@stianst created https://github.com/keycloak/keycloak/issues/10203

**Pull request closed without merging**
