### PR TITLE
Keep same name on update for LDAP attributes

### LINKED ISSUE #23888: LDAP attribute name is case sensitive for update only
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

If the attribute name in LDAP (openldap is used) has a case error when defining a mapping in a user federation the result is that when editing the attributes of a user new attributes can be CREATED from that mapping but CANNOT BE EDITED. 

### Version

22.0.4

### Expected behavior

The behavior should be consistent. If case matching is required in the LDAP attribute name it should no longer work when creating the attribute. Conversely, if case is not required, updating an existing value for that attribute should work. 

### Actual behavior

The attributes of a user new attributes can be CREATED from that mapping but CANNOT BE EDITED. 

### How to Reproduce?

Modify any existing and functional mapping by introducing some case difference. You will then be able to create values for this attribute but you will not be able to modify or delete them.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes https://github.com/keycloak/keycloak/issues/23888

If an attribute is modified using a different case it can be duplicated in the attributes map and the old value can remain. This PR adds the original attribute name (exact case) to the `lowerCasedAttributes` map to also know the initial case used in the name and maintain it during the update. Test added.

I also managed the idea to just maintain one `attributes` map but the key was a private object which is a `IgnoreCaseString` (equals, hash, compare,... methods would ignore the case). But the `getAttributes` would return an unmodifiable map. I decided to follow current idea but if you prefer this second approach just let me know.

Test added.

### CODE REVIEW

**Comment by rmartinc** [comment]
@mposolda Please re-run the failed CI run (the node.exe again).

**Comment by rmartinc** [comment]
@keycloak/store Please review this one when you have time. Thanks in advance!

**Review by sguilhen — APPROVED** [review]
Thanks @rmartinc . I think the current approach is fine. I've also tested locally and it works, so this gets a +1 from me!

**Review by ahus1 — APPROVED** [review]
Approving as of @sguilhen's review

**Pull request merged**
