### PR TITLE
enable dot in attribute when user profile enabled

### PR DESCRIPTION
**Pull request by sschu**
fixes: #24918

### CODE REVIEW

**Comment by sschu** [comment]
@jonkoops I tried to do the backport without knowing Typescript. I just pray it works. ;)

**Comment by jonkoops** [comment]
Thanks @sschu, much appreciated. The failure is unrelated, it's been fixed in `main`, but looks like it needs a backport to v23, so I created #25432.

**Comment by jonkoops** [comment]
We're still in release freeze, I think we'll get a release today or tomorrow if all goes well, so that will hopefully resolve this.

**Comment by ahus1** [comment]
Depending PR has been merged, reran the builds. Someone from @keycloak/ui-maintainers would need to approve.

**Comment by sschu** [comment]
The test failure checks if there is an error message when testing an LDAP connection. I would not expect this to be related.

**Comment by sschu** [comment]
@jonkoops Do you think this can be merged now to have this backported to KC23?

**Review by edewit — APPROVED** [review]

**Comment by ahus1** [comment]
@sschu - as it has been a while, I can't any more re-trigger the builds on GitHub. And as the PR disabled the option to push changes to the branch, I can't rebase the PR. 

Please rebase the PR to trigger new builds. Once that's in, it can again be approved.

**Pull request merged**
