### PR TITLE
KEYCLOAK-19877 Update additional Arquillian dependencies

### PR DESCRIPTION
**Pull request by mabartos**
JIRA: [KEYCLOAK-19877](https://issues.redhat.com/browse/KEYCLOAK-19877)

@Aboullos @pdrozd Could you please take a look at it? Thanks

### CODE REVIEW

**Comment by Aboullos** [comment]
LGTM, just the Model test are failing, could they be re-launched?

**Comment by mabartos** [comment]
@miquelsi @pdrozd It resolved the issue with the Windows machines in pipeline. See https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/816/

**Review by miquelsi — APPROVED** [review]
LGTM. Thanks Martin, specially for the fixes in Arquillian framework :-)

**Review by Aboullos — APPROVED** [review]
LGTM!

**Review by pedroigor — APPROVED** [review]
Approving based on previous reviews.

**Pull request merged**
