### PR TITLE
Add a common pitfalls section to the cordova example

### PR DESCRIPTION
**Pull request by konstin**
Spare others from the hours of debugging it took to write these two line. See https://issues.jboss.org/browse/KEYCLOAK-4536 for some details.

### CODE REVIEW

**Comment by stianst** [comment]
Github seems to think that the README you've attached is a binary file and I can't view the diff.

**Comment by konstin** [comment]
I tried to set markdown files to be treated as text, but apparently github ignores that. This shouldn't be to hard to review anyway. I've only added one paragraph, so reviewing should be as easy viewing the file and looking at the last paragraph.

**Comment by stianst** [comment]
I don't think it should be strictly needed to add to gitattributes, we've had many PRs for md files in the past without any issues, so not sure what's going on. Maybe it works if you add it, but it should be text, not diff.

**Comment by stianst** [comment]
There's some issues with encoding in the file which is why it's not detected as text. I'm closing this PR as I've sent a separate PR with a properly encoded file.

**Comment by stianst** [comment]
https://github.com/keycloak/keycloak/pull/3916

**Pull request closed without merging**
