### PR TITLE
[KEYCLOAK-12865] Stabilize distribution profile

### PR DESCRIPTION
**Pull request by iankko**
[KEYCLOAK-12865] Stabilize distribution profile
    
    Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

### CODE REVIEW

**Comment by iankko** [comment]
@rmartinc @hmlnarik @mposolda PTAL once got a chance

Thanks! Jan

**Review by rmartinc — APPROVED** [review]
Looks good to me. I have run the affected test and it works OK.

**Comment by rmartinc** [comment]
@iankko The error is just because of time, and it was almost finished. So I think it is OK. Have a nice weekend!

**Review by mposolda — APPROVED** [review]
@iankko @rmartinc Thanks for looking at this and fixing it!

**Pull request merged**
