### PR TITLE
Use property parameter instead of duplicating content

### PR DESCRIPTION
**Pull request by niekdonk**
Use the provided pnpm.args.install property instead of duplicating the contents

Closes #34447

### CODE REVIEW

**Comment by jonkoops** [comment]
@niekdonk could you file a quick issue for this and link it to this PR? We require all PRs have an issue attached for bookkeeping (e.g. for the changelog).

**Comment by niekdonk** [comment]
[Link issue](https://github.com/keycloak/keycloak/pull/34446)

**Comment by jonkoops** [comment]
@niekdonk see [Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue), specifically using a keyword in the PR description.

**Comment by niekdonk** [comment]
Resolves #34447

**Comment by jonkoops** [comment]
@niekdonk you'll have to add this keyword to the PR description by editing it, posting a new comment will not link it.

**Comment by jonkoops** [comment]
@niekdonk you've edited the PR title, the keyword should be in the description. I went ahead and edited it for you so it is linked to the PR now.

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
LGTM, this should be merged automatically once the CI passes.

**Comment by jonkoops** [comment]
@niekdonk please do not rebase the PR, it re-triggers CI and generates additional notifictions for us. It is not required for your branch to be up-to-date with `main` for it to get merged.

**Review by ahus1 — APPROVED** [review]

**Pull request merged**
