### PR TITLE
KEYCLOAK-3807: Calling 'setHandler' is forbidden

### PR DESCRIPTION
**Pull request by bdalenoord**
Use 'insertHandler' as suggested in the 'setHandler's log warning.

### CODE REVIEW

**Comment by stianst** [comment]
@sebastienblanc can you take a look at this please?

**Comment by sebastienblanc** [comment]
@bdalenoord Did you check that this fix doesn't introduce any regression ? In other worlds, does that affects older version of Jetty ?

**Comment by bdalenoord** [comment]
@sebastienblanc I hadn't, but I have now tested the fix with the following versions:

- 9.3.11.v20160721
- 9.2.19.v20160908
- 9.1.6.v20160112
- 8.1.22.v20160922

All 9.x.x releases seem to work perfectly using my fix, but the 8.1-version is not compiling as the `insertHandler`-method wasn't present in that version. There is however a `setSecurityHandler`-method which works for all 9.x.x releases, so I'll push an update to the PR with that change.

I can not test the 8.1-release though, as the next error I'm seeing is a nullpointer on the `webAppContext`. My change didn't touch that line though, and I'm not sure what might cause it. It seems to've been broken for a longer time though, should that be fixed under this PR or is a new bug report more appropriate?

**Comment by sebastienblanc** [comment]
@bdalenoord I don't think this problem has been reported yet for the 8.1-release, so feel free to create a new ticket (and indeed a different PR if you know how to fix it ;) )

**Comment by bdalenoord** [comment]
I've filed a new issue for 8.1: https://issues.jboss.org/browse/KEYCLOAK-3818
I've currently got no idea on how that crash could be fixed, might look into it later.

**Comment by sebastienblanc** [comment]
@bdalenoord Hey Bas , I'm trying to run your sample app ( https://github.com/bdalenoord/keycloak-spring-boot-issue) to reproduce the issue but I can not even run the server. I don't know that much Jetty and Kotlin ;) , here is my stacktrace https://gist.github.com/sebastienblanc/d77c5b3fc2aba5a7aebb11bc6dfc9d85 , do you have any idea why the jetty server doesn't start ?

**Comment by bdalenoord** [comment]
@sebastienblanc You're running the branch I created to showcase the problem (master), which it does so beautifully :) . I've implemented the fix on another branch called `fix`, if you check that one out, rebuild it and run the application it should start:

````
git checkout fix
mvn clean package
java -jar target/api-0.0.1-SNAPSHOT.war
````

(I must note that the way of implementing the fix on that branch was a little dirty, I monkeypatched it by copying the classes from the original keycloak-spring-boot-adapter to the project and modifying them so I didn't have to run through the entire maven cycle every time I changed it. It does not change the outcome of my final implementation though, so it should not be a problem)

**Comment by sebastienblanc** [comment]
@bdalenoord Ah right ! I thought it was crashing later while the server was running, but indeed the `fix` branch works.
And to double check I also tested your master branched with as local dependency your PR, also works ;) . Bedankt ! 

@stianst looks good to go

**Pull request merged**
