### PR TITLE
KEYCLOAK-4765 - Add ability to disable Query Parameter parsing.

### PR DESCRIPTION
**Pull request by johnament**
This allows a consumer to override whether or not query parameter parsing will occur per request.

### CODE REVIEW

**Comment by stianst** [comment]
We don't want to use mockito so please change the tests to be proper functional tests instead. We have the adapter testsuite that allows this. If you need I can see if someone from our QE can give you some pointers on how to do that.

**Comment by stianst** [comment]
The config property also needs to be exposed in standalone.xml. Take a look at https://github.com/keycloak/keycloak/commit/886528dab8d91ef53524f73ff4a291f1cf0a479d as an example on how to do that.

**Comment by johnament** [comment]
I see your change is only for wf8-subsystem.  Is that accurate? Or do I need to change a different one? Or all three?

I can add the functional tests.

**Comment by sebastienblanc** [comment]
@johnament If you take a close look you will see it's also added for the `wildfly` subsystem and not only wf8.

**Comment by johnament** [comment]
@sebastienblanc take a look, let me know.

**Comment by sebastienblanc** [comment]
Looks good to me
@stianst Could you merge this ?

**Comment by johnament** [comment]
ping... just wondering, this blocks up from taking new releases.

**Comment by stianst** [comment]
I'm afraid this won't be included until 3.2.0 release.

**Comment by stianst** [comment]
PR and tests looks good, but the docs will also need to be updated
https://keycloak.gitbooks.io/documentation/content/securing_apps/topics/oidc/java/java-adapter-config.html

**Comment by johnament** [comment]
What is the expected release date of 3.2?

**Comment by stianst** [comment]
You can find that in JIRA

**Comment by johnament** [comment]
@stianst so to resolve this PR.. what else is needed?  Docs are in a separate repo, do you want me to raise both PRs at the same time?

**Comment by stianst** [comment]
Yes, please send a PR to the docs and add a link to the PR here. Once that's ready I'll merge both.

**Comment by johnament** [comment]
Documentation PR: https://github.com/keycloak/keycloak-documentation/pull/135

**Pull request merged**
