### PR TITLE
fix: admin cli client should set the content when performing a merge

### LINKED ISSUE #29878: Updating a client protocol mappers through Admi CLI (kcadm) resets the client service account roles
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

I tried to update the protocol mappers of a client using the Admin CLI like this : 

`kcadm update clients/<client_id> -f client-protocol-mappers.json`

With the json file containing the id of the client and the updated protocol mappers. Here is a simple example : 
```
{
  "id" : "1c8c3cb0-4496-4ef3-bf14-93a40c67dc6f",
  "protocolMappers" : [ {
    "id" : "25c9005f-4348-4a13-8c39-4dd5bb3cb30d",
    "name" : "given name",
    "protocol" : "openid-connect",
    "protocolMapper" : "oidc-usermodel-property-mapper",
    "consentRequired" : false,
    "config" : {
      "userinfo.token.claim" : "true",
      "user.attribute" : "firstName",
      "id.token.claim" : "false",
      "access.token.claim" : "true",
      "claim.name" : "given_name",
      "jsonType.label" : "String"
    }
  }, {
    "id" : "d3a75456-fc69-432f-9a80-5825703ff84b",
    "name" : "family name",
    "protocol" : "openid-connect",
    "protocolMapper" : "oidc-usermodel-property-mapper",
    "consentRequired" : false,
    "config" : {
      "userinfo.token.claim" : "true",
      "user.attribute" : "lastName",
      "id.token.claim" : "false",
      "access.token.claim" : "true",
      "claim.name" : "family_name",
      "jsonType.label" : "String"
    }
  } ]
}
```

Everything works fine and the protocol mappers are correctly updated for my client.
All other client configuration values still have correctly the same values as before the Admin CLI command was executed (Client name, description, redirect URIs, theme, keys, credentials, etc...), except the configuration of the service account roles which got reset to the default values.

Before : 
image

After updating the protocol mappers : 
image

As you can see no more roles (except the default 'default-roles-<realm>' role) are associated to the service account.

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Only the protocol mappers of the client should be updated

### Actual behavior

Protocol mappers of the client are correctly updated but the service account roles are reset

### How to Reproduce?

Create a client in the management console.
Associate roles to the service account of the client (through the 'Service account roles' tab)
Execute kcadm update clients/<client_id> -f client-protocol-mappers.json
Refresh the page showing the roles associated to the service account of the client -> Roles are no more associated.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #29878

### CODE REVIEW

**Comment by mabartos** [comment]
@shawkins Even though this solves the issue with the `null` content, it does not solve the issue around resetting the client service account roles, right? IMHO, it's not an intentional behavior.

**Comment by shawkins** [comment]
> @shawkins Even though this solves the issue with the null content, it does not solve the issue around resetting the client service account roles, right? IMHO, it's not an intentional behavior.

Resetting the service accounts is seemingly expected behavior when a merge is not used - cc @pedroigor 

The fix here allows for merge to be used, which then preserve everything else.

**Comment by mabartos** [comment]
> Resetting the service accounts is seemingly expected behavior when a merge is not used

@shawkins Ahh, ok. Is it well documented somewhere? It might probably be done better, or it could even display some warnings? It seems a little bit unintuitive to me. WDYT?

**Comment by shawkins** [comment]
> @shawkins Ahh, ok. Is it well documented somewhere? 

I doubt it. It's very similar to a behavioral change that happened with basic user attributes - just setting the email for example will clear other fields #28220 because that more closely aligns with the PUT verb behavior.

> It might probably be done better, or it could even display some warnings? It seems a little bit unintuitive to me. WDYT?

There's another issue to better document the rest api, you can add a subtask or a comment there. Or were you thinking of some other place?

**Review by mabartos — COMMENTED** [review]
After a private discussion, this PR should be ready to go as it solves the bug with the usage of the merge option. The bigger issue might be caused by changes on the REST API level. 

@shawkins LGTM. However, I think these changes should not close the parent issue (https://github.com/keycloak/keycloak/issues/29878) as these are kinda separated, correct? Is it possible to create a brief issue about the "merge" bug?

**Comment by shawkins** [comment]
> @shawkins LGTM. However, I think these changes should not close the parent issue (https://github.com/keycloak/keycloak/issues/29878) as these are kinda separated, correct? Is it possible to create a brief issue about the "merge" bug?

I'll confirm if there has been a behavioral change wrt to this operation - if not, then I don't think another issue is needed. We have been, and probably still are, inconsistent with our rest api and don't have it fully documented. I've added and epic #30921 and an specific issue for this nuance #30922

**Review by mabartos — APPROVED** [review]
@shawkins Agree. Approving now as these are valid changes. 

If you potentially spot the behavioral change, please address these issues appropriately.

**Review by vmuzikar — APPROVED** [review]
Approving based on @mabartos' review.

**Comment by shawkins** [comment]
@mabartos @vmuzikar tested the same scenario on KC 22 - it had the same behavior then as well. Without the merge the service account roles are cleared. So there's no regression here.

**Pull request merged**
