### PR TITLE
KEYCLOAK-4703 Use phantomJS in adapter tests

### PR DESCRIPTION
**Pull request by mhajas**

### CODE REVIEW

**Comment by stianst** [comment]
Can't we fix the test instead? HtmlUnit is significantly faster and there is a problem with the adapter tests taking to long to execute.

**Comment by stianst** [comment]
I would actually prefer if the JS tests was re-written to just invoke JS directly rather than having a "sample app" to drive the behaviour. The current approach makes it hard to test different scenarios.

Take a look at:
https://github.com/stianst/keycloak/blob/ACCOUNT-REST/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountCorsTest.java#L112

This is an example on how JS can be used directly from the Java tests without having to build out an example app at all.

**Comment by mhajas** [comment]
I like this approach I saw this is possible when investigating this issue with htmlUnit , but I can't imagine it completely without example app. We need at least somehow import keycloak.js and it should be added in html, shouldn't it? Or am I missing something?

Another problem I see is angular. In case we would use this, it would mean no testing of combination of keycloak + angular. Would it be correct? 

Anyway, rewriting the tests to use this approach will take me some time, until then we should use phantomjs as default browser for adapters.

**Comment by stianst** [comment]
Yes, you're right we'd need at least a bootstrapping app. It would just need to load keycloak.js with a script element.

It should be possible to fix the tests as they are though with htmlunit. There's no reason afaik that as simple onclick shouldn't work with htmlunit. Maybe you need to fetch the element differently or click on it differently or something. Try Googling htmlunit + onclick?

**Comment by mhajas** [comment]
I googled quite a lot, but I was not successful, I talked also with mposolda, he gave me some advice, but I was unsuccessful again. I found a lot of users which are experiencing a problem with clicking in htmlUnit. 

I don't have any experiences with htmlUnit, so I created an issue for solving this later and created a PR for temporarily use of phantomjs until htmlUnit will not work.

**Comment by stianst** [comment]
Is this problem solved with the PR you did to keycloak.js? Or is there still issues with htmlunit?

**Comment by mhajas** [comment]
Issue with htmlunit is still present. I am just using phantomjs or firefox to run adapter tests since I am not able to fix this issue.

**Comment by stianst** [comment]
We can merge this until we find a solution, but we do need to put some effort into getting the adapter tests working with htmlunit, so please leave KEYCLOAK-4703 open. There is a big issue with the adapter tests with regards to execution time which is preventing us from being able to use these on Travis. Switching back to PhantomJS only makes matters worse.

**Pull request merged**
