### PR TITLE
Removes the bundle generator from the runtime

### LINKED ISSUE #22573: Remove bundle generator dependency from the Operator dist
### Description

The `io.quarkiverse.operatorsdk:quarkus-operator-sdk-bundle-generator` should be build time only.

**This depends on https://github.com/quarkiverse/quarkus-operator-sdk/pull/690.** I.e. we need QOSDK >=6.3.0.

Follows up on #22496

### PR DESCRIPTION
**Pull request by shawkins**
Closes #22573

### CODE REVIEW

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks @shawkins 

@ASzc Can you please confirm this approach of moving the unproductized dep to build time is ok for you?

**Comment by shawkins** [comment]
> Can you please confirm this approach of moving the unproductized dep to build time is ok for you?

At the provided scope, we'll fail to build with the error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.1:single (assemble-bundle) on project keycloak-operator: Failed to create assembly: Error creating assembly archive olm: archive cannot be empty
```

So if a filtered optional dependency does not work, then we'll need some additional upstream changes.

**Comment by vmuzikar** [comment]
> So if a filtered optional dependency does not work, then we'll need some additional upstream changes.

Can't we scope it to `provided`?

**Comment by ASzc** [comment]
LGTM, `optional` doesn't seem to cause any issues with prod, and I confirm that it removes the bundle generator jar from the zip

**Pull request merged**
