### PR TITLE
Document behaviour of GET GroupResources

### LINKED ISSUE #27694: auth/admin/realms/{realm-name}/groups?briefRepresentation=false returns empty subgroups.
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Hi Team,

We have been migrating to KC 23.5 and observed that the /groups functionality doesn't return subgroups anymore and the field is empty. 
Can you suggest an alternative way/fix to handle the same? 

### Version

23.5

### Regression

- [ ] The issue is a regression

### Expected behavior

The groups should be returned with subgroups populated.

### Actual behavior

Subgroup field is empty

### How to Reproduce?

https://{keycloak-host}:port/auth/admin/realms/{realm-name}/groups?briefRepresentation=false

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by RichieB2B**
Closes #27694

The behaviour of `GET /admin/realms/{realm}/groups` still causes confusion, see #27694

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you for your contribution. I see you added the documentation to two methods. Actually only one of the methods has this query parameter, and only that method should receive updated docs. 

The way to document query parameters is shown in: 

https://github.com/keycloak/keycloak/blob/b5d0154bb1db76cf9e461acb55ec048f84cf44e8/services/src/main/java/org/keycloak/services/resources/admin/ClientRoleMappingsResource.java#L127

You add a `@Parameter(description =...` to each parameter, and than it is generated in the API documentation. 

Please rework your PR. Please also sign-off your commit as outlined in the `CONTRIBUTING.md` file. Thanks!

@keycloak/core-iam - anyone of you wants to take over reviewing this PR?

**Comment by RichieB2B** [comment]
@ahus1 It is not the `q` and `search` parameter that needs additional documentation but the default case when these parameters are not used. Documenting this at the parameter level feels counter productive.

**Review by ahus1 — APPROVED** [review]
Thank you for the PR that updates the docs to match the current behavior. I don't think this behavior is really consistent. Still as the only one who picked is you to update the docs, let's update the docs. 
In the future, maybe someone will create another PR to also deliver the subGroups

**Comment by RichieB2B** [comment]
@ahus1 I believe 481acac41f209dcf0655635f34cea6c2dd1cc952 contains wrong information.  Please drop this line as the statement is simply not true:
```
If these parameters are empty, the top-level groups are returned without `subGroups` being filled.
```
Added an empty `search` paramter does populate the `subGroups`.

**Comment by ahus1** [comment]
Ok, my mistake. As it has now been merged: Can you please create a follow-up PR with a fix?

**Comment by RichieB2B** [comment]
Your mistake proves #27694 is an actual bug that should be fixed. The current behaviour is counter intuitive and confuses even long time Keycloak developers. Please fix the bug instead of the documentation.

**Comment by ahus1** [comment]
So do you suggest to revert to the original docs?

**Comment by RichieB2B** [comment]
The current behavious is clearly a bug but at least now it is documented. See #36022

**Pull request merged**
