### PR TITLE
Issue #14933: jwks endpoint for X/Y coordinates in EC keypair can return less bytes than expected

### LINKED ISSUE #14933: jwks endpoint for X/Y coordinates in EC keypair can return less bytes than expected
### Describe the bug

The [RFC-7518](https://www.rfc-editor.org/rfc/rfc7518#section-6.2.1.2) specifies that X and Y fields for a EC key MUST be the full size of the curve coordinate specified in the "crv" parameter.

>   The "x" (x coordinate) parameter contains the x coordinate for the
>   Elliptic Curve point.  It is represented as the base64url encoding of
>   the octet string representation of the coordinate, as defined in
>   [Section 2.3.5](https://www.rfc-editor.org/rfc/rfc7518#section-2.3.5) of [SEC1](https://www.rfc-editor.org/rfc/rfc7518#ref-SEC1) [SEC1].  The length of this octet string MUST
>   be the full size of a coordinate for the curve specified in the "crv"
>   parameter.  For example, if the value of "crv" is "P-521", the octet
>   string must be 66 octets long.

In current implementation the big integer is always written removing the sign bit using [toIntegerBytes](https://github.com/keycloak/keycloak/blob/19.0.3/core/src/main/java/org/keycloak/jose/jwk/JWKUtil.java#L29). So it can happen that the resulting bytes are less than expected. Example test:

```java
    @Test
    void test() throws NoSuchAlgorithmException, InvalidKeySpecException {
        byte[] bytes = Base64.getDecoder().decode("MIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQA17IdNXGUWR9trV1RjjtU4yQiHG1LvpVGyuqQ8t8t2ei3ao/dEu+h2RVPUlD2JuqQfbEIb0jeS5pXgJlO/HSLBYoATBvn23AmBEF7LmLR8uNTW+nJcwm1Tg2sVKvQ7i202Y5TkhvsmwwKx9U/+K6HgB22m7FqhtLxFR8InSmMnnK/0sU="); //EC publickey whose y coordinate byte array start with 0
        X509EncodedKeySpec keyspec = new X509EncodedKeySpec(bytes);
        KeyFactory keyFactory = KeyFactory.getInstance("EC");
        ECPublicKey publicKey = (ECPublicKey) keyFactory.generatePublic(keyspec);
        BigInteger bigInteger = publicKey.getW().getAffineY();
        byte[] yBytes = toIntegerBytes(bigInteger);
        assertThat(yBytes).hasSize(66); // should be 66, but 65
    }
```

### Version

19.0.3

### Expected behavior

The X and Y coordinates in the JWKS should be always 66 bytes when using P-521.

### Actual behavior

Sometime it can be 65 (if the first byte starts by 0).

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #14933 

The `toIntegerBytes` has a new variant method that receives the expected bits of the array. Previous implementation calls this one passing the big integer bit-length as the expected bits. A simple test `JWKUtilTest` added to check different big integers and `JWKTest.java` modified to check the X/Y fields are of the expected size.

### CODE REVIEW

**Comment by rmartinc** [comment]
@larsw I think that your fix is not complete, the previous PR solves the problem of having 1 byte more (the sign byte if the size is aligned to 8), but it didn't fix the issue of having less bytes than the specified by the algorithm (66 octets in P-521). For example P-521 can generate a number of 518b which is 65B, and the current implementation of `toInteger` returns the 65B instead of the 66B specified in the [RFC-7518](https://www.rfc-editor.org/rfc/rfc7518#section-6.2.1.2). This can also happen in P-256 and P-384 but it's much less probable.

@stianst Any option to assign a reviewer, it's not a big change.

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
@rmartinc Thanks for this change and sorry for late review ;) Updated your branch to latest main. I hope to merge if all the tests are OK

**Comment by rmartinc** [comment]
:smile: Thanks!

**Comment by Emyrk** [comment]
When can this get into a release?

This is currently breaking when validating the keyset with https://github.com/go-jose/go-jose

**Comment by mposolda** [comment]
Will be in Keycloak 21.1.0. Probably is going to be released next week.

**Pull request merged**
