### PR TITLE
Update Catalan translation

### PR DESCRIPTION
**Pull request by jmallach**

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you for this translation. Please ask a native speaker (colleague, friend or someone on the Keycloak mailing list) to review this translation and to add their approval in this issue. 

Once it is reviewed and approved, this can then be merged.

**Comment by jmallach** [comment]
I just committed the result of an out-of-github review by @ecron. Artur can ack that he's happy with the result here.

**Comment by Ecron** [comment]
Hi there, Artur here. I took some time to review @jmallach’s translation, and after a few corrections, I’m confident with the final result 👍🏼.

**Comment by jmallach** [comment]
I assume the new flaky test has nothing to do with my changes, but please tell me if that's not correct and I need to make any changes/corrections.

**Review by jonkoops — APPROVED** [review]
LGTM, @ssilvert can I get your approval on this one?

**Comment by jonkoops** [comment]
> I assume the new flaky test has nothing to do with my changes, but please tell me if that's not correct and I need to make any changes/corrections.

Yeah, no worries, just the ghost in the machine.

**Comment by jonkoops** [comment]
I've set this to merge automatically, so once it has @ssilvert's approval it will go through. Thanks for your contributions!

**Review by ahus1 — APPROVED** [review]

**Pull request merged**
