### PR TITLE
[WIP] [DNM] [KEYCLOAK-12344] Bump the version of Keycloak examples to '9.0.0-SNAPSHOT' too

### PR DESCRIPTION
**Pull request by iankko**
Currently, an attempt to use some of the exapmles (e.g. `examples/ldap`) ends up with:
```
$ mvn -Pldap exec:ldap
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.keycloak:keycloak-examples-parent:[unknown-version]: Could not find artifact org.keycloak:keycloak-parent:pom:8.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ org.keycloak:keycloak-examples-parent:[unknown-version], /home/iankko/KEYCLOAK-12242/keycloak/examples/pom.xml, line 20, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.keycloak.example.demo:keycloak-examples-ldap:[unknown-version] (/home/iankko/KEYCLOAK-12242/keycloak/examples/ldap/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.keycloak:keycloak-examples-parent:[unknown-version]: Could not find artifact org.keycloak:keycloak-parent:pom:8.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ org.keycloak:keycloak-examples-parent:[unknown-version], /home/iankko/KEYCLOAK-12242/keycloak/examples/pom.xml, line 20, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

With this change, they work again:
```
$ mvn -Pldap exec:java
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------< org.keycloak.example.demo:keycloak-examples-ldap >----------
[INFO] Building LDAP Demo Application 9.0.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ keycloak-examples-ldap ---
...
16:19:45,080 INFO  [org.keycloak.util.ldap.LDAPEmbeddedServer] LDAP Server started
```

Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

### CODE REVIEW

**Comment by iankko** [comment]
@mposolda @abstractj @stianst @hmlnarik PTAL once got a chance

Thanks!
Jan

**Review by abstractj — COMMENTED** [review]
@iankko thanks for these changes. Maybe we should update our set-version script to update the examples?

@stianst wdyt?

**Comment by stianst** [comment]
It's strange that set-version script doesn't already update this stuff, as it does for quarkus, distribution, etc.. Not sure why that is.

To be honest I would actually consider just cleaning up the examples asap. We can delete what isn't needed anymore as it's replaced by QuickStarts, and perhaps just move the rest to QuickStarts without adding tests, but somehow mark them as not tested?

**Comment by stianst** [comment]
What's weird is that examples is included in the pom in the same way as testsuite, but set-version works for testsuite, not for examples.

**Comment by stianst** [comment]
By the way manually updating this won't fix it for the release as that uses the set-version.sh script. So we need to figure out why that suddenly stopped working for the examples - or just move all the examples to quickstarts.

**Comment by stianst** [comment]
./set-version.sh script was working until 5 or so it seems, then it suddenly stopped working

**Comment by stianst** [comment]
@iankko Hello!?

**Comment by iankko** [comment]
@stianst 

> By the way manually updating this won't fix it for the release as that uses the set-version.sh script. So we need to figure out why that suddenly stopped working for the examples - or just move all the examples to quickstarts.

Will look into redoing this by updating `set-version.sh` script, as you suggested above.

**Comment by stianst** [comment]
Closing this as it's not a priority right now and updating poms directly won't have any affect on what is released. We need the set-version script to work properly to fix the released example.zip.

**Pull request closed without merging**
