### PR TITLE
Use `--verbose` by default in Operator deployments

### LINKED ISSUE #21802: Allow "--verbose" option when running Keycloak via the Operator
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

Keycloak might fail with an exception. It then prints the following text:

> For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.

AFAIK there is no way to pass that option via the Operator. Due to the lack of that option, I don't see the stack trace in the log.

### Version

main

### Expected behavior

I wonder if "--verbose" it should be the default when starting Keycloak via the Operator. Which leads to the question why not enabling it by default from the CLI.

### Actual behavior

Missing information to debug an issue.

### How to Reproduce?

Inject any exception that prevents Keycloak from starting. 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes #21802

### CODE REVIEW

**Review by ahus1 — COMMENTED** [review]
This solves my need for the deployment. 

There are also the import jobs, maybe those could be change as well to add the flag to both build and import.

https://github.com/keycloak/keycloak/blob/6a92669139e42f72179d30f0ad0eede19a965322/operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJob.java#L146-L150

**Review by ahus1 — DISMISSED** [review]

**Review by ahus1 — DISMISSED** [review]

**Review by shawkins — APPROVED** [review]
LGTM

**Review by mabartos — APPROVED** [review]

**Comment by ahus1** [comment]
@vmuzikar - there are test failures in `KeycloakDeploymentTest` as they don't expect the new CLI parameter.

**Review by ahus1 — APPROVED** [review]

**Comment by vmuzikar** [comment]
> @vmuzikar - there are test failures in `KeycloakDeploymentTest` as they don't expect the new CLI parameter.

Thanks, I was a bit quick and missed that test even though I was checking manually for potentially broken tests by this change. 🙈

**Pull request merged**
