### PR TITLE
Fix breadcrumbs.

### PR DESCRIPTION
**Pull request by ssilvert**

### CODE REVIEW

**Comment by stianst** [comment]
JIRA is missing + 'credentials' should be 'Credentials'

**Comment by ssilvert** [comment]
I thought we didn't do JIRA for trivial fixes?  Are we going to do JIRA for every change now?  (Personally, I think we should)

**Comment by stianst** [comment]
I'd like JIRAs for everything (except for docs and tests).

**Comment by ssilvert** [comment]
KEYCLOAK-1853

**Pull request merged**
