### PR TITLE
Fix duplicate group memberships when mapping LDAP groups in READ_ONLY mode

### LINKED ISSUE #23966: Group members are displayed incorrectly when using LDAP in READ_ONLY mode
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

When user federation via LDAP is configured and the group mapper is set to READ_ONLY mode, group members are sometimes duplicated in the admin UI. More specifically, the same group members are listed multiple times on different pages in the admin UI. This does not appear to be a UI bug though as the API calls actually return the same users for different pages.

Making a request to the admin API `/admin/realms/{realm}/groups/{id}/members` manually shows the same behaviour when requesting group members page by page (using the `first` and `max` parameters). Requesting group members with `max` set to a higher value than the group has members returns all members correctly without duplicates.

### Version

22.0.1

### Expected behavior

The admin API returns group members correctly without any duplicates.

### Actual behavior

The admin API endpoint `/admin/realms/{realm}/groups/{id}/members` returns the same users multiple times on different pages when using pagination.

### How to Reproduce?

- Setup LDAP user federation with the group mapper set to READ_ONLY mode.
- Create a LDAP group with more than 100 members (the default page size in the admin UI).
- Query the group members in Keycloak.

### Anything else?

The actual pagination happens in https://github.com/keycloak/keycloak/blob/22.0.1/federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/MembershipType.java#L87. Multiple sequential requests will not keep some kind of cursor for pagination, so all group members are queried with every request. The order of the returned users is not defined anywhere and as a `Set<LDAPDn>` is used for the query results, the iteration order is not necessarily defined. A fix would be to sort the returned users before getting a sublist as proposed in #23784.

### PR DESCRIPTION
**Pull request by 999eagle**
Without this, the order for returned LDAP group members is undefined and the admin API endpoint `/admin/realms/{realm}/groups/{id}/members` will return the same users on multiple pages. The admin UI will also display the same users on multiple pages.

Fixes: #23966

### CODE REVIEW

**Comment by 999eagle** [comment]
Drafted this PR due to the ongoing discussion in #23966 as this PR doesn't seem to fully fix this issue.

**Comment by 999eagle** [comment]
This is ready for review now. I've tested this for DNs now.

**Comment by sguilhen** [comment]
@999eagle Thanks for putting some time to work into this. I was following the discussion in the associated issue, and it seems to me that @rmartinc has produced a more complete fix. Would you mind if we close this PR in favor of a PR from Ricardo?

**Comment by 999eagle** [comment]
If we have a more complete PR for the same issue, sure just go ahead and close mine over @rmartinc's.

**Comment by ahus1** [comment]
Closing as suggested by @sguilhen and agreed by @999eagle. This PR can be reopened later if there should be the need.

**Pull request closed without merging**
