### PR TITLE
KEYCLOAK-7274 Hardcoded config in offline adapter installation scripts

### PR DESCRIPTION
**Pull request by vramik**

### CODE REVIEW

**Comment by vramik** [comment]
https://github.com/keycloak/keycloak-documentation/pull/373

**Comment by stianst** [comment]
I like the ability to specify the config file, but it seems that the user first has to edit ./bin/jboss-cli.xml to enable resolve-parameter-values. I don't like that. Can that param somehow be specified from the CLI or is there some other approach that doesn't require changing WF "config" first?

**Comment by vramik** [comment]
@stianst actually I've just re-tested it and it seems to work without editing jboss-cli.xml in WF11. But yesterday it didn't work and I had to edit the file.

**Comment by stianst** [comment]
@vramik worked like a charm without editing jboss-cli.xml. I suggest on minor change and use `${server.config:standalone.xml}` that way for standalone.xml you don't need to specify it, but you can specify it if you use a different config.

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
@vramik The JavascriptAdapterTest is failing, but I don't think that has anything to do with this PR?

**Comment by vramik** [comment]
@stianst no it has not

**Pull request merged**
