### PR TITLE
Add a span per rest resource, thereby showing subresources

### LINKED ISSUE #35419: OTEL: Enhance traces with spans for each RestEASY resource
### Description

This is a feature of the OTEL agent instrumentation, and we should add it as well.

### Discussion

_No response_

### Motivation

Locate the source of activity in a simpler way within Keycloak

### Details

I'll create a PR

### PR DESCRIPTION
**Pull request by ahus1**
Closes #35419

Example output: 

image

### CODE REVIEW

**Comment by ahus1** [comment]
@mabartos - please review when you have the time. Thanks!

**Comment by mabartos** [comment]
@ahus1 Nice work!

Would not be better to mimic format as Quarkus/Vert.x do for traces?

As it might be better to have span names like: "<HTTP-Method> <path>" for sub-resources (if present). Additionally add the `code.function`, and `code.namespace` attributes. We could also add some of the "http.*" attributes.

Wondering if we can leverage the functionality Quarkus/Vert.x do for these traces, but didn't check it more.

Or at least show the simple name of the class without the full package name.

image

**Comment by ahus1** [comment]
The up-most span will contain all that information. Still for the subresources, this information isn't available after some debugging: When ending the span, the HTTP request hasn't been fully processed, so you wouldn't know the path. Also the subresources don't have a `@Method`, only a `@Path`.

I adopted the suggestion to use the simple name, see my second commit for that. The full class name is still available in the extra attribute.

**Review by mabartos — APPROVED** [review]
@ahus1 Thanks for the PR! Very valuable! Changes LGTM.

Note: Agree to use the "raw" OTel instrumentation in the customizer instead of the Tracing SPI - we don't need to take care of KeycloakSession initialization order in other customizer, etc.

**Pull request merged**
