### PR TITLE
Restores deleted /delegated endpoint need by kc installed (#9401)

### PR DESCRIPTION
**Pull request by bekwam**
This restores the /delegated endpoint.  /delegated is needed for the latest (18.0.2) KeycloakInstalled Java adapter to complete the login operation and to display a message to the end user indicating a successful login.  Without the endpoint, a successful KeycloakInstalled login shows "Page not found" and does not cleanup cookies.

### CODE REVIEW

**Review by devSummer76 — APPROVED** [review]

**Review by stianst — CHANGES_REQUESTED** [review]
We need to fix KeycloakInstalled instead. The '/delegated' endpoint was a broken concept that should never have been introduced. It also has a CSRF issue as it's an open endpoint anyone can link to that will invalidate a users session.

The proper fix here is to remove getRedirectUrl:

https://github.com/keycloak/keycloak/blob/ac6ee544555115a8810b9be2bb9b7e815f770412/adapters/oidc/installed/src/main/java/org/keycloak/adapters/installed/KeycloakInstalled.java#L473

Instead of redirecting it should show a message that the browser tab can be closed like it did previously, by updating this method:

https://github.com/keycloak/keycloak/blob/ac6ee544555115a8810b9be2bb9b7e815f770412/adapters/oidc/installed/src/main/java/org/keycloak/adapters/installed/KeycloakInstalled.java#L453

To something like how it used to work prior to `kcinit` was introduced:

https://github.com/keycloak/keycloak/blob/6b8ec0bb8297184f052b6bcf8666230686a21066/adapters/oidc/installed/src/main/java/org/keycloak/adapters/installed/KeycloakInstalled.java#L122-L128

If this PR can be updated to what I've listed above we can include this in 19.0.2.

**Comment by bekwam** [comment]
Thanks for looking into this.  To confirm, you're looking for the client-side app server to return a page without contacting the remote Keycloak server?

The current implementation of the call to Keycloak "/delegated" also expires the KEYCLOAK_IDENTITY and KEYCLOAK_REMEMBER_ME cookies and this would be skipped if we don't hit the server with the GET.  Is this important?

-Carl

**Comment by stianst** [comment]
> Thanks for looking into this. To confirm, you're looking for the client-side app server to return a page without contacting the remote Keycloak server?

Yes, that's how authorization code flow should work for native clients.

> 
> The current implementation of the call to Keycloak "/delegated" also expires the KEYCLOAK_IDENTITY and KEYCLOAK_REMEMBER_ME cookies and this would be skipped if we don't hit the server with the GET. Is this important?
> 
> -Carl

Actually, the way that it used to work was a bug as it should never have cleared the identity cookies. A native application should delegate to the system browser when doing authorization code flow, which allows it to leverage SSO, but with the old behaviour and using the '/delegated' endpoint it actually resulted in the SSO session being destroyed.

**Comment by bekwam** [comment]
Would it be possible to continue the server-side call for non-destructive, presentation purposes?  I'd like to pick up the branding and theming so that the Login Successful HTML isn't different.  This would keep the server-side GET, but remove the cookie operations.

And I'd keep the ?error so that Login Failure would be styled consistently.

```java
    @GET
    @Path("delegated")
    public Response kcinitBrowserLoginComplete(@QueryParam("error") boolean error) {
        // cookie-handling code removed
        if (error) {
            LoginFormsProvider forms = session.getProvider(LoginFormsProvider.class);
            return forms
                    .setAttribute("messageHeader", forms.getMessage(Messages.DELEGATION_FAILED_HEADER))
                    .setAttribute(Constants.SKIP_LINK, true).setError(Messages.DELEGATION_FAILED).createInfoPage();

        } else {
            LoginFormsProvider forms = session.getProvider(LoginFormsProvider.class);
            return forms
                    .setAttribute("messageHeader", forms.getMessage(Messages.DELEGATION_COMPLETE_HEADER))
                    .setAttribute(Constants.SKIP_LINK, true)
                    .setSuccess(Messages.DELEGATION_COMPLETE).createInfoPage();
        }
    }
```

**Comment by stianst** [comment]
> Would it be possible to continue the server-side call for non-destructive, presentation purposes? I'd like to pick up the branding and theming so that the Login Successful HTML isn't different. This would keep the server-side GET, but remove the cookie operations.
> 
> And I'd keep the ?error so that Login Failure would be styled consistently.
> 
> ```java
>     @GET
>     @Path("delegated")
>     public Response kcinitBrowserLoginComplete(@QueryParam("error") boolean error) {
>         // cookie-handling code removed
>         if (error) {
>             LoginFormsProvider forms = session.getProvider(LoginFormsProvider.class);
>             return forms
>                     .setAttribute("messageHeader", forms.getMessage(Messages.DELEGATION_FAILED_HEADER))
>                     .setAttribute(Constants.SKIP_LINK, true).setError(Messages.DELEGATION_FAILED).createInfoPage();
> 
>         } else {
>             LoginFormsProvider forms = session.getProvider(LoginFormsProvider.class);
>             return forms
>                     .setAttribute("messageHeader", forms.getMessage(Messages.DELEGATION_COMPLETE_HEADER))
>                     .setAttribute(Constants.SKIP_LINK, true)
>                     .setSuccess(Messages.DELEGATION_COMPLETE).createInfoPage();
>         }
>     }
> ```

I do appreciate that it may be nice to have, but it's not something I'm super thrilled about to be honest, as it's a non-standard approach. In a standard authz code flow you wouldn't redirect back to the IdP after the flow is completed. 

Since it's a relatively simple page it wouldn't be all that hard to make it styled the same. Perhaps instead we could come up with a simple way to let folks customize/theme the response page generated by KeycloakInstall?

**Comment by bekwam** [comment]
Will do.  The use case I'm writing about is for a customer I have who uses branded realms for different tenants.  I'm anticipating confusion if there's a plain <html><body><h1>Success!</h1></body></html> page.  I'll see if there's some way to get the Freemarker themes to present purely client-side.

**Comment by stianst** [comment]
One thought that may help is we could support custom pages for these, but could also allow redirecting to another URL, and here's a potential solution for you as you could implement a custom realmresourceprovider that generates the page using themes on the Keycloak server side

**Comment by bekwam** [comment]
What do you think about a Keycloak RESTful call that returns text/html?  The client-side app server relays this back to the user.  The KeycloakInstalled method would skip the redirect as in your first reply and directly return the contents of this GET.

If it's a custom realm provider, would that mean that KeycloakInstalled wouldn't work out of the box?

**Comment by stianst** [comment]
KeycloakInstalled would work just fine out of the box with what I'm suggesting. You would just make it configurable to link to a different URL and for that you could deploy a custom endpoint on KC for a page that is styled as you want.

**Comment by adame11** [comment]
Hi. I wasn't clear that this Pull Request was ever going to be approved as-is, without doing it the way @stianst suggested - in other words that the fix be made in the `KeycloakInstalled.java`  (no longer redirect to the server)? So I've submitted  https://github.com/keycloak/keycloak/pull/15180 which I addresses these concerns. Instead of redirecting back to the server, show a simple: "Authentication successful. You may close your browser" or "You are logged out. You may close your browser." I did not try to address adding customizable formatting (or wording).

**Comment by adame11** [comment]
For what it's worth, I've added support in [PR#15180](https://github.com/keycloak/keycloak/pull/15180) for customized html and customized text for login and logout when using the Keycloak installed adapter. You can either set plain text or HTML. For HTML, it works by setting a Path to an optional static single HTML page to serve. Can only serve single page HTML (css and images are not served separately because webserver shuts down immediately after serving the single page).

**Comment by stianst** [comment]
Closing in favour of https://github.com/keycloak/keycloak/pull/15180

**Pull request closed without merging**
