### PR TITLE
Prevent "kc.{bat,sh} show-config" from triggering a build

### LINKED ISSUE #23070: Calling "kc.sh show-config" triggers a build
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

Calling `kc.sh show-config` triggers a build, for example in my custom Docker image of Keycloak:
```
#14 [builder 9/9] RUN ./bin/kc.sh show-config
#14 0.938 Changes detected in configuration. Updating the server image.
#14 0.957 Current Mode: production
#14 0.957 Current Configuration:
#14 0.959 	kc.cache =  ispn (PersistedConfigSource)
#14 0.959 	kc.config.build-and-exit =  true (SysPropConfigSource)
#14 0.959 	kc.db =  postgres (PersistedConfigSource)
#14 0.959 	kc.health-enabled =  true (PersistedConfigSource)
#14 0.959 	kc.http-enabled =  false (PropertiesConfigSource[source=jar:file:///opt/bitnami/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-21.1.2.jar!/META-INF/keycloak.conf])
#14 0.959 	kc.http-relative-path =  / (PersistedConfigSource)
#14 0.959 	kc.log-console-output =  default (PropertiesConfigSource[source=jar:file:///opt/bitnami/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-21.1.2.jar!/META-INF/keycloak.conf])
#14 0.960 	kc.log-file =  ${kc.home.dir:default}${file.separator}data${file.separator}log${file.separator}keycloak.log (PropertiesConfigSource[source=jar:file:///opt/bitnami/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-21.1.2.jar!/META-INF/keycloak.conf])
#14 0.960 	kc.metrics-enabled =  true (PersistedConfigSource)
#14 0.960 	kc.provider.file.keycloak-metrics-spi-3.0.0.jar.last-modified =  1690220150000 (PersistedConfigSource)
#14 0.960 	kc.provider.file.quarkus-logging-sentry-1.2.2.jar.last-modified =  169409[93](https://gitlab.ripe.net/swe/ripe-keycloak/-/jobs/1159792#L93)80400 (PersistedConfigSource)
#14 0.960 	kc.provider.file.quarkus-logging-sentry-deployment-1.2.2.jar.last-modified =  16[94](https://gitlab.ripe.net/swe/ripe-keycloak/-/jobs/1159792#L94)099380521 (PersistedConfigSource)
#14 0.[96](https://gitlab.ripe.net/swe/ripe-keycloak/-/jobs/1159792#L96)0 	kc.provider.file.sentry-6.29.0.jar.last-modified =  1694099379679 (PersistedConfigSource)
#14 0.960 	kc.provider.file.sentry-jul-6.29.0.jar.last-modified =  169409937[98](https://gitlab.ripe.net/swe/ripe-keycloak/-/jobs/1159792#L98)18 (PersistedConfigSource)
#14 0.961 	kc.spi-map-storage-concurrenthashmap-dir =  ${kc.home.dir:default}${file.separator}data${file.separator}chm (PropertiesConfigSource[source=jar:file:///opt/bitnami/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-21.1.2.jar!/META-INF/keycloak.conf])
#14 0.961 	kc.spi-map-storage-concurrenthashmap-key-type-authz-resource-servers =  string (PropertiesConfigSource[source=jar:file:///opt/bitnami/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-21.1.2.jar!/META-INF/keycloak.conf])
#14 0.961 	kc.spi-map-storage-concurrenthashmap-key-type-realms =  string (PropertiesConfigSource[source=jar:file:///opt/bitnami/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-21.1.2.jar!/META-INF/keycloak.conf])
#14 0.961 	kc.spi-map-storage-concurrenthashmap-key-type-single-use-objects =  string (PropertiesConfigSource[source=jar:file:///opt/bitnami/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-21.1.2.jar!/META-INF/keycloak.conf])
#14 0.961 	kc.version =  21.1.2 (SysPropConfigSource)
#14 0.963 Next time you run the server, just run:
#14 0.963 
#14 0.963 	kc.sh start --optimized 
#14 0.963 
#14 1.634 Current Mode: production
#14 1.634 Current Configuration:
#14 1.635 	kc.cache =  ispn (PersistedConfigSource)
#14 1.635 	kc.config.built =  true (SysPropConfigSource)
#14 1.635 	kc.db =  postgres (PersistedConfigSource)
#14 1.635 	kc.health-enabled =  true (PersistedConfigSource)
#14 1.636 	kc.http-enabled =  false (PropertiesConfigSource[source=jar:file:///opt/bitnami/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-21.1.2.jar!/META-INF/keycloak.conf])
#14 1.636 	kc.http-relative-path =  / (PersistedConfigSource)
#14 1.636 	kc.log-console-output =  default (PropertiesConfigSource[source=jar:file:///opt/bitnami/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-21.1.2.jar!/META-INF/keycloak.conf])
#14 1.636 	kc.log-file =  ${kc.home.dir:default}${file.separator}data${file.separator}log${file.separator}keycloak.log (PropertiesConfigSource[source=jar:file:///opt/bitnami/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-21.1.2.jar!/META-INF/keycloak.conf])
#14 1.636 	kc.metrics-enabled =  true (PersistedConfigSource)
#14 1.636 	kc.provider.file.keycloak-metrics-spi-3.0.0.jar.last-modified =  1690220150000 (PersistedConfigSource)
#14 1.636 	kc.provider.file.quarkus-logging-sentry-1.2.2.jar.last-modified =  16940[99](https://gitlab.ripe.net/swe/ripe-keycloak/-/jobs/1159792#L99)380400 (PersistedConfigSource)
#14 1.637 	kc.provider.file.quarkus-logging-sentry-deployment-1.2.2.jar.last-modified =  1694099380521 (PersistedConfigSource)
#14 1.637 	kc.provider.file.sentry-6.29.0.jar.last-modified =  1694099379679 (PersistedConfigSource)
#14 1.637 	kc.provider.file.sentry-jul-6.29.0.jar.last-modified =  1694099379818 (PersistedConfigSource)
#14 1.637 	kc.spi-map-storage-concurrenthashmap-dir =  ${kc.home.dir:default}${file.separator}data${file.separator}chm (PropertiesConfigSource[source=jar:file:///opt/bitnami/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-21.1.2.jar!/META-INF/keycloak.conf])
#14 1.637 	kc.spi-map-storage-concurrenthashmap-key-type-authz-resource-servers =  string (PropertiesConfigSource[source=jar:file:///opt/bitnami/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-21.1.2.jar!/META-INF/keycloak.conf])
#14 1.637 	kc.spi-map-storage-concurrenthashmap-key-type-realms =  string (PropertiesConfigSource[source=jar:file:///opt/bitnami/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-21.1.2.jar!/META-INF/keycloak.conf])
#14 1.637 	kc.spi-map-storage-concurrenthashmap-key-type-single-use-objects =  string (PropertiesConfigSource[source=jar:file:///opt/bitnami/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-21.1.2.jar!/META-INF/keycloak.conf])
#14 1.637 	kc.version =  21.1.2 (SysPropConfigSource)
#14 DONE 1.8s
```

### Version

22

### Expected behavior

The current configuration should only be displayed, nothing more.

### Actual behavior

Before the configuration is displayed, a *build* operation is carried out first, due to:
https://github.com/keycloak/keycloak/blob/bc31fde4c0de1fbc8c0ceadd104424bd77563f30/quarkus/dist/src/main/content/bin/kc.sh#L129

### How to Reproduce?

Simply run `kc.sh show-config`.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dalbani**
Closes https://github.com/keycloak/keycloak/issues/23070.

### CODE REVIEW

**Review by mabartos — COMMENTED** [review]
@dalbani Thanks for the PR. I don't see a problem with this, and everything should be working as expected. 

@dalbani Could you please also update the `kc.bat` for Windows?

**Comment by dalbani** [comment]
@mabartos
I have updated my code to support `kc.bat`.

**Comment by mabartos** [comment]
@pedroigor Was there any reason to execute the build phase for the `show-config` command in the past?

**Comment by dalbani** [comment]
Not applicable anymore, as the issue doesn't affect Keycloak 22.

**Pull request closed without merging**
