### PR TITLE
Upgrade liquibase to version 4.25.1

### LINKED ISSUE #26570: Upgrade liquibase to 4.25.1
### Description

Relates to #26535 - quarkus 3.7 has moved ahead to liquibase 4.25.1, which at the very least requires a code change to CustomLockService. However even after that change there were test failures, so this needs evaluated by the @keycloak/store team.

### PR DESCRIPTION
**Pull request by sguilhen**
Closes #26570

### CODE REVIEW

**Review by ahus1 — DISMISSED** [review]
The code changes look good to me. Thank you for preparing them!

**Comment by ahus1** [comment]
I saw a strange exception in the run [here](https://github.com/keycloak/keycloak/actions/runs/7785250011/job/21227883463), which seems at first sight somehow related to the Oracle driver. It might be a flaky thing, still I pointed me to the fact that some dependencies are no longer aligned with Quarkus upstream and I pushed another commit. Let's see if the next build is greener.

**Comment by shawkins** [comment]
@ahus1 some additional version alignments are coming with #26788

**Review by shawkins — APPROVED** [review]
LGTM

**Review by ahus1 — APPROVED** [review]
Approving as of  @shawkins's review and after my review of @sguilhen's changed. Thanks!

**Pull request merged**
