### PR TITLE
Invalid redirect uri when identity provider alias has spaces

### LINKED ISSUE #22836: Invalid redirect uri when identity provider alias has spaces
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

identity-brokering

### Describe the bug

When creating a new identity provider for a realm, if the identity provider alias has spaces, the error below is trowed and it is not possible to login into the application:

Identity provider:
image

Error on the **server.log**:
```
2023-08-30 15:30:57,828 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-22) Uncaught server error: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "redirectUri" is null
	at org.keycloak.protocol.oidc.utils.RedirectUtils.verifyRedirectUri(RedirectUtils.java:146)

```

image

If i create the same identity provider without spaces, it works as expected:
image

### Version

22.0.1

### Expected behavior

Creating identity provider with space in the alias.

### Actual behavior

Creating a new identity provider for the realm with a space in the alias, leads to error on the application.

### How to Reproduce?

- Create a new keycloak realm(e.g. Example)
- Create a confidential client that will be used for broker identity provider
- Create a new keycloak realm(e. g. Application)
- Add a new identity provider changing the alias to something with spaces(e.g "Another Login")
- Point the identity provider configuration to the Example realm created on the first step
- Try to login on an application that is on Application realm

### Anything else?

Here is the two realms used for the test:

[application1-realm.json.txt](https://github.com/keycloak/keycloak/files/12479192/application1-realm.json.txt)
[broker-realm.json.txt](https://github.com/keycloak/keycloak/files/12479193/broker-realm.json.txt)

### PR DESCRIPTION
**Pull request by pedro-hos**
closes #22836

### CODE REVIEW

**Review by douglaspalmer — CHANGES_REQUESTED** [review]
Nitpicking but can you please rename validateWithSpace to validateNoSpace? Otherwise I think this PR is fine.

**Comment by pedro-hos** [comment]
> Nitpicking but can you please rename validateWithSpace to validateNoSpace? Otherwise I think this PR is fine.

Hi Douglas, I've just updated the commit with the suggested change.

**Review by douglaspalmer — APPROVED** [review]

**Comment by mposolda** [comment]
@pedro-hos Thanks! Is it possible to also add the automated test for this?

**Comment by mposolda** [comment]
@pedro-hos Any luck with the test?

**Comment by pedro-hos** [comment]
Hey @mposolda I am working on it today, I'd send the PR until Sunday.

**Comment by pedro-hos** [comment]
@mposolda tests were done!

**Review by mposolda — APPROVED** [review]
@pedro-hos @douglaspalmer Thanks for the PR and review. I hope to merge if tests are OK

**Pull request merged**
