### PR TITLE
[KEYCLOAK-9920] Create a saml-adapter-feature-pack

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by sberyozkin** [comment]
@hmlnarik Does this PR look OK to you ? We'd like to get a better picture about the keycloak-saml fraction prospects on the Thorntail side. The other question is, if this PR is accepted, can it make it into the KC 5.x tree ? thanks

**Review by hmlnarik — CHANGES_REQUESTED** [review]
@sberyozkin Thank you for your PR and apologies for the review taking this long. Would you still be interested in merging the PR?

Overall the PR looks good, thank you. There are few comments inline, and the PR needs rebasing (this should be straightforward since there was only a version change in the meantime). Once done that and the commits would be squashed into a single one, the PR would be ready for merging.

**Comment by stianst** [comment]
Closing due to lack of activity. Feel free to re-open

**Comment by sberyozkin** [comment]
Hi @stianst, @hminarik, sorry, I've not got any comment notifications, I'll get back to it asap and reopen once I'm ready, thanks

**Pull request closed without merging**
