### PR TITLE
Fix issue with access tokens claims not being imported using OIDC IDP Attribute Mappers

### LINKED ISSUE #9004: Access Token claims not imported using OpenID Connect v1.0 Identity Provider Attribute Importer Mappers
### Describe the bug

Hi there !

We have configured an external OIDC Identity Provider (type: `OpenID Connect v1.0`), and are trying to map claims present in the IDP Access Token to Keycloak User Attributes, using an Attribute Importer Mapper.

But Keycloak seems unable to find the claims in the Access Token, with the following DEBUG messages reported:

```
DEBUG [org.keycloak.broker.oidc.mappers.AbstractJsonUserAttributeMapper] (default task-6) Going to process JsonNode path role-coh-irn71429 on data null
DEBUG [org.keycloak.broker.oidc.mappers.AbstractJsonUserAttributeMapper] (default task-6) Going to process JsonNode path iat on data null
```

### Version

10.0.1, but also reproducible with 15.0.2

### Expected behavior

The tooltip message on the Mapper type states:

```
Import declared claim if it exists in ID, access token or the claim set 
returned by the user profile endpoint into the specified user property or attribute.
```

Using the documentation provided [here](https://www.keycloak.org/docs/latest/server_admin/#retrieving-external-idp-tokens), I managed to retrieve the external IDP Token, and can confirm it contains the expected claim. 
So I would actually expect Keycloak to resolve the claims present in the Access Token.

### Actual behavior

The user created in Keycloak at first login does not contain the attribute expected.

### How to Reproduce?

- Configure Keycloak by adding an Identity Provider of type `OpenID Connect v1.0` : https://www.keycloak.org/docs/latest/server_admin/#_identity_broker_oidc
- Configure the external IDP to include a claim in the Access Token only
- In Keycloak, add an Attribute Importer mapper in the identity provider configured. This Attribute Importer should map the claim present in the Access Token
- Try to login using this new Identity Broker. Authentication should pass, but in Keycloak, the user attributes will not contain the mapped claim.

By the way, to make things clearer, I added two test cases in the [following branch in my fork](https://github.com/rm3l/keycloak/tree/claims_not_imported_using_oidc_idp_attribute_mappers_test). 

You can run these tests with the command below:
```shell
mvn -f testsuite/integration-arquillian/pom.xml clean install \
  -Dtest=KcOidcAccessTokenOnlyClaimsUserAttributeMapperTest,OidcAccessTokenOnlyClaimsUserAttributeMapperTest
```

`KcOidcAccessTokenOnlyClaimsUserAttributeMapperTest`, which passes, registers a `keycloak-oidc` Identity Provider.
But as reported here, `OidcAccessTokenOnlyClaimsUserAttributeMapperTest` does not pass because it registers an `oidc` IDP.

### Anything else?

Few months ago, I opened a discussion [here](https://github.com/keycloak/keycloak/discussions/8462) about that issue,but got no response so far. After some discussions, I am finally about to contribute a PR for this issue.

While the reproduction steps are a bit different, @galzetta reported a similar issue (#8961) with similar debug logs. I could not add a test case for this other issue, so I am not sure the linked PR will fix that issue.

### PR DESCRIPTION
**Pull request by rmartinc**
Closes https://github.com/keycloak/keycloak/issues/9004
Supersedes https://github.com/keycloak/keycloak/pull/9005 

Adding an option to the OIDC providers to mark the access token sent by the IDP is a JWT. If that property is set the access token is validated and assigned to the VALIDATED_ACCESS_TOKEN context data (as the keycloak provider does now). The attribute mappers also use the context data to import attributes.

@rm3l sent an initial PR in #9005 with tests and everything long time ago, he commented that he can't do the requested changes right now, so I'm just adding the property over his changes. OIDC does not ensure that the access token is a JWT, only the IDToken, so it can be an opaque token and the new behavior is restricted when the option is set by the configurators (false by default). The keycloak provider is updated to use the new option.

If you think we need the new property explained in the [doc](https://www.keycloak.org/docs/latest/server_admin/#_identity_broker_oidc), just let me now.

### CODE REVIEW

**Review by jonkoops — DISMISSED** [review]
Changes to the Admin Console look good, can't vouch for the rest.

**Comment by pedroigor** [comment]
If the option being added is not related to keeping backward compatibility when mappers are resolving claims from both AT and ID Token, we could avoid it by always taking claims from a JWT AT and reviewing how they are resolved when both AT and ID as available from the context.

**Comment by rmartinc** [comment]
Yes, we can try to always parse the Access Token but don't fail in case it's not a JWT. As @pedroigor commented, it is a slight change in behavior (AT is tried before ID token) but we avoid adding new config options. We'll decide something the next week.

**Comment by pedroigor** [comment]
@rmartinc As the protocol is OIDC, I would also change the order to first try to resolve from the ID Token and then from the AT.

**Comment by rmartinc** [comment]
There is always a little change in behavior no matter the order we choose. If first ID then AT, the change is in the keycloak provider; if AT then ID, it's in the OIDC provider. But it's very, very similar, so I think it's acceptable. I also think that trying ID token first is better because it's JWT by spec. I'll try to modify the PR.

**Comment by rmartinc** [comment]
The idea about always trying to parse can be something like this [branch](https://github.com/rmartinc/keycloak/tree/issue-9004-2).

**Review by mposolda — DISMISSED** [review]
@rmartinc Thanks! I hope to merge if tests are OK (there was test failure in UI test in previous run, but not 100% sure if it is related to the PR).

**Comment by mposolda** [comment]
@jonkoops I am not sure if the test failure in group `Keycloak JavaScript CI / Admin UI E2E (3, chrome) (pull_request)` in the test `identity_providers_oidc_test.spec.ts` is the regression of this PR or if it is known issue. Could you please confirm if this is known issue and this PR can be merged as is, or if it is something, which needs to be investigated before merging this?

**Comment by jonkoops** [comment]
@mposolda I've been seeing this failure recently, I think it's a regression that has been fixed that is unrelated to the changes here. I'll do a quick rebase to see if it will pass now.

**Comment by rmartinc** [comment]
@jonkoops If you need me to fully rebase the PR just let me know. :smile:

**Comment by jonkoops** [comment]
@rmartinc looks like the failures might be related to the changes made in this PR. Likely something has changed that fails the tests, or something is broken. I'll give it another rebase just to be sure.

**Review by jonkoops — APPROVED** [review]
LGTM!

**Review by mposolda — APPROVED** [review]
@rmartinc @jonkoops Thanks for the fixes and review. Good that this can be finally merged!

**Comment by rmartinc** [comment]
@HappyMoai This means the access token is not signed or the verification is failing for whatever reason. When you activate the option the access token is validated as a JWT (signed), if not activated, it's just not parsed/validated and then it doesn't fail.

**Comment by rmartinc** [comment]
@HappyMoai I don't think you need to change that, you have to check what do you have in the response (retrieve the access token from it) and try to guess why the signature is failing. And please do not mess this PR, use the http://groups.google.com/group/keycloak-user list or file a new issue if you think this is a code bug.

**Comment by Frank-LR** [comment]
Hi @rmartinc 

I've got the same issue on keycloak version **17.0.1** with Okta/PKCE:
"_Advanced Claim to Role_" finds claims in the "id_token" but not in the "access_token"

Which keycloak-version do I have to install, to fix this problem?

**Comment by rmartinc** [comment]
@Frank-LR issue https://github.com/keycloak/keycloak/issues/9004 is marked for keycloak 23 so it's still not available. It will be in the next major release. For the moment it's just in the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly).

**Pull request merged**
