### PR TITLE
KEYCLOAK-14851: make AIA max auth age configurable per AIA

### PR DESCRIPTION
**Pull request by zak905**

### CODE REVIEW

**Comment by abstractj** [comment]
@ssilvert it seems that tests and docs are missing. But feel free to remove the labels if I'm wrong.

**Comment by ssilvert** [comment]
This is a neutral change so IMO it doesn't need a specific test.  The test to make sure this didn't break anything is to run the testsuite for the new account console.  I've kicked off build number 971 for that.

**Review by ssilvert — APPROVED** [review]
Test run looks good.  Approved.

**Comment by zak905** [comment]
Awesome, thanks. now we can move on with KEYCLOAK-953

**Pull request merged**
