### PR TITLE
16189 removed lots of unnecessary quotes and allowed passing quoted a…

### LINKED ISSUE #16189: Keycloak Quarkus Distro is not able to process the log format
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Linking one issue related mulitple log handler [https://github.com/keycloak/keycloak/issues/16188](https://github.com/keycloak/keycloak/issues/16188)

In the same line i could start keycloak with single handler only but we can not pass format 

I'm trying to start Keycloak with log format as the document suggests and it's failing in windows but the same works in mac

**C:\Users\Administrator\Downloads\keycloak-20.0.2\keycloak-20.0.2\bin>kc.bat start-dev --log=file --log-file=../data/kc.log --log-file-format="'%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n'"**

"JAVA_OPTS already set in environment; overriding default settings with values: -Dprogram.name=kc.bat -Dprogram.name=kc.bat -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8"
%s%e%n' was unexpected at this time.

image

Doc reference:
image

### Version

20.0.1

### Expected behavior

It's failing in windows machine if we provide the log format

### Actual behavior

It should log the information in the provided format

### How to Reproduce?

Execute the following command:

kc.bat start-dev --log=file --log-file=../data/kc.log --log-file-format="'%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n'"

### Anything else?

_No response_

### LINKED ISSUE #16319: Keycloak have space in path , or keystore , truststore , or till js-provider if space it's failed
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I'm running Keycloak in both mac and windows os and it's failing every where if 

**--https-key-store-file**      /Users/ajay/keycloak cert/keystore.ks
**--https-trust-store-file**.   /Users/ajay/keycloak cert/truststore.ks
And path till js-provider have space.

For ex:

Here is the path of Keycloak 

**/Users/ajaykumarjaiswal/driveE/keycloak spacepath/bin**

And i have placed one provider as js-policy.jar

image

Here is the error i'm getting 

`(base) ajaykumarjaiswal@C02Z45LWLVDR bin % ./kc.sh start-dev   
Updating the configuration and installing your custom providers, if any. Please wait.
The DelayedHandler was closed before any children handlers were configured. Messages will be written to stderr.
2023-01-09 18:06:33,649 DEBUG [org.jboss.logging] (main) Logging Provider: org.jboss.logging.JBossLogManagerProvider

2023-01-09 18:06:33,718 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement@2792b416 to QuarkusClassLoader Augmentation Class Loader: PROD

2023-01-09 18:06:33,719 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement@4735d6e5 to QuarkusClassLoader Augmentation Class Loader: PROD

...

2023-01-09 18:06:35,907 DEBUG [io.netty.util.internal.PlatformDependent0] (build-3) direct buffer constructor: unavailable: java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$5.run(PlatformDependent0.java:288)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:282)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:333)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:88)
	at io.netty.util.AsciiString.<init>(AsciiString.java:223)
	at io.netty.util.AsciiString.<init>(AsciiString.java:210)
	at io.netty.util.AsciiString.cached(AsciiString.java:1401)
	at io.netty.util.AsciiString.<clinit>(AsciiString.java:48)
	at io.netty.handler.codec.http.HttpMethod.<init>(HttpMethod.java:132)
	at io.netty.handler.codec.http.HttpMethod.<clinit>(HttpMethod.java:36)
	at io.vertx.core.http.HttpMethod.<clinit>(HttpMethod.java:192)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.<clinit>(VertxHttpRecorder.java:1511)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.quarkus.deployment.proxy.ProxyFactory.newInstance(ProxyFactory.java:274)
	at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy(BytecodeRecorderImpl.java:378)
	at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFromClass$57(ExtensionLoader.java:663)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:905)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

2023-01-09 18:06:35,907 DEBUG [io.netty.util.internal.PlatformDependent0] (build-3) java.nio.Bits.unaligned: available, true

2023-01-09 18:06:35,908 DEBUG [io.netty.util.internal.PlatformDependent0] (build-3) jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable: java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$7 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @16053510
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at io.netty.util.internal.PlatformDependent0$7.run(PlatformDependent0.java:410)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:401)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:333)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:88)
	at io.netty.util.AsciiString.<init>(AsciiString.java:223)
	at io.netty.util.AsciiString.<init>(AsciiString.java:210)
	at io.netty.util.AsciiString.cached(AsciiString.java:1401)
	at io.netty.util.AsciiString.<clinit>(AsciiString.java:48)
	at io.netty.handler.codec.http.HttpMethod.<init>(HttpMethod.java:132)
	at io.netty.handler.codec.http.HttpMethod.<clinit>(HttpMethod.java:36)
	at io.vertx.core.http.HttpMethod.<clinit>(HttpMethod.java:192)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.<clinit>(VertxHttpRecorder.java:1511)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.quarkus.deployment.proxy.ProxyFactory.newInstance(ProxyFactory.java:274)
	at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy(BytecodeRecorderImpl.java:378)
	at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFromClass$57(ExtensionLoader.java:663)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:905)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

ERROR: Failed to run 'build' command.
ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureKeycloakSessionFactory threw an exception: java.lang.RuntimeException: Failed to discover script providers
	at org.keycloak.quarkus.deployment.KeycloakProcessor.loadDeployedScriptProviders(KeycloakProcessor.java:698)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.loadFactories(KeycloakProcessor.java:637)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.configureKeycloakSessionFactory(KeycloakProcessor.java:340)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.NoSuchFileException: /Users/ajaykumarjaiswal/driveE/keycloak%20spacepath/lib/../providers/js-policy.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1259)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:350)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:321)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:260)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.loadDeployedScriptProviders(KeycloakProcessor.java:679)
	... 13 more

ERROR: Build failure: Build failed due to errors
	[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureKeycloakSessionFactory threw an exception: java.lang.RuntimeException: Failed to discover script providers
	at org.keycloak.quarkus.deployment.KeycloakProcessor.loadDeployedScriptProviders(KeycloakProcessor.java:698)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.loadFactories(KeycloakProcessor.java:637)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.configureKeycloakSessionFactory(KeycloakProcessor.java:340)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.NoSuchFileException: /Users/ajaykumarjaiswal/driveE/keycloak%20spacepath/lib/../providers/js-policy.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1259)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:350)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:321)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:260)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.loadDeployedScriptProviders(KeycloakProcessor.java:679)
	... 13 more

ERROR: Failed to discover script providers
ERROR: /Users/ajaykumarjaiswal/driveE/keycloak%20spacepath/lib/../providers/js-policy.jar
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
`

### Version

20.0.1

### Expected behavior

It should handle path in all environment

### Actual behavior

it's failing

### How to Reproduce?

keep spaces in the path of truststore , keystore , or till provider folder and add one javascript provider  then it will fail.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sschu**
…rgument values

Closes #16189 

Also fixes #16319 for `kc.bat`.

### CODE REVIEW

**Comment by sschu** [comment]
Hmm, everything green. Strange. Probably because there are no Windows test runners? @DGuhr Do you know if there are any windows test runners to test running Keycloak with `kc.bat`, especially the tests I changed?

**Comment by pedroigor** [comment]
@sschu We are not running tests in Windows. Some people in the team are working to enable it.

Looks like your changes are enough to bring more consistency between shell and bat scripts. The code you are removing from tests is an example.

If you are happy with these changes I can run some tests here and see if we can include them.

**Comment by pedroigor** [comment]
@sschu Your changes look OK and the failures I'm facing when running tests are expected:

* `HelpCommandDistTest`
* `LoggingDistTest`

Your changes are also fixing https://github.com/keycloak/keycloak/issues/16189. It should be possible to start using:

```
 ./kc.bat start-dev --log='"console,file"' --log-file-format='"%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t123) %s%e%n"'
```

The format is a bit different than what is described in docs.

I need some more time to fix the test failures on Windows and include an additional test to the issue you are fixing.

**Comment by sschu** [comment]
@pedroigor You can even leave out the outer single quotes. But you probably mean #16188 ? This can already by circumvented by adding double quotes as I commented in that issue.

**Comment by pedroigor** [comment]
@sschu So the changes here are basically improvements to code? I mean, we can close https://github.com/keycloak/keycloak/issues/16189 and https://github.com/keycloak/keycloak/issues/16188?

**Comment by sschu** [comment]
This one here closes #16189 completely and #16319 for `kc.bat`. To close #16319 for `kc.sh` there is #16339. 
#16188 already works if you quote the log handlers correctly, I updated the documentation for that: #16298.

**Comment by mabartos** [comment]
Any progress here?

@Pepo48 Could you please check it? Thanks

**Comment by Pepo48** [comment]
@mabartos I can check this one on my local machine tomorrow. Regardless, we can run this even in our internal pipelines just to be completely sure, right?

Anyway, from my point of view the changes LGTM.

**Review by pedroigor — DISMISSED** [review]

**Review by pedroigor — APPROVED** [review]

**Comment by Eng-Fouad** [comment]
See #19803

**Pull request merged**
