### PR TITLE
Drop old table USERNAME_LOGIN_FAILURE used before by UserSessionProvider

### LINKED ISSUE #34380: Remove remaining table USERNAME_LOGIN_FAILURE from the jpa UserSessionProvider times
### Description

In issue #32582 there was a cleanup of the tables used for the jpa UserSessionProvider that was deleted very long ago (1.5.0). But there is still one table that remains: USERNAME_LOGIN_FAILURE.

This table can also be deleted as it's not used. So it would be good if we add it for removal in the next mayor release.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #34380

Just deleting USERNAME_LOGIN_FAILURE table that is not used since version 1.5.0 (see deleted class `UsernameLoginFailureEntity.java` in commit 7665b9f81eda1614ee17eb349fb5d699471ae1cd). There were some other drops executed by issue #32582 but the table USERNAME_LOGIN_FAILURE was not included and the table still there.

### CODE REVIEW

**Review by pedroigor — COMMENTED** [review]
There is a reference to this table here [`org.keycloak.helpers.DropAllServlet`](https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/helpers/DropAllServlet.java#L163).

Wondering if we even need that class in our test suite....

**Comment by rmartinc** [comment]
Yep, you are right, but the previous deleted tables are also there. Let me try if I can remove those methods.

**Comment by rmartinc** [comment]
I have deleted the class `DropAllServlet` and the annotation `RestartContainer` that uses it. This annotation is not used in any test and we are using the features class to restart the server when another configuration is needed. I think that tests are OK. If you prefer to just modify `RestartContainer` to avoid any database initialization we can do that too.

**Review by mposolda — APPROVED** [review]
@rmartinc Thanks! Looks ok to me as long as tests are fine and QE team is fine with changing this due the updates in tests (I don't expect any issues here, but adding @miquelsi as a reviewer just in case).

**Review by miquelsi — APPROVED** [review]

**Pull request merged**
