### PR TITLE
Update URL for FreeOTP

### PR DESCRIPTION
**Pull request by gmarziou**
It was poniting to obsolete location: https://fedorahosted.org/freeotp/

Now pointing to: https://freeotp.github.io/

### CODE REVIEW

**Comment by stianst** [comment]
Added JIRA (https://issues.jboss.org/browse/KEYCLOAK-4558)

@patriot1burke can you please make sure there are JIRAs? We need visibility of what's being changed.

**Comment by gmarziou** [comment]
Sorry I did not know I had to open a JIRA issue for minor change like this.
Maybe it could be clarified in https://github.com/keycloak/keycloak/blob/master/misc/HackingOnKeycloak.md#discuss-changes

**Comment by stianst** [comment]
No problem, but it does state:

"A JIRA associated with your PR (include the JIRA issue number in commit
comment)"

**Comment by gmarziou** [comment]
Sorry, how could I miss it! Anyway, I created a JIRA for my other pull request.

**Pull request merged**
