### PR TITLE
[KEYCLOAK-2538] - groups pagination and group search

### PR DESCRIPTION
**Pull request by levyndot**
As it's done on users and to response to an opened issue [https://issues.jboss.org/browse/KEYCLOAK-2538](https://issues.jboss.org/browse/KEYCLOAK-2538), this pull request contains group request with pagination and groups search by name and pagined. This can help to improve also group page Keycloak UI as it's done on users page.

### CODE REVIEW

**Comment by stianst** [comment]
Can you add tests and also update the UI to support the pagination?

**Comment by guitaro** [comment]
For tests, yes I can, sorry for this mistake.
For UI, I will pick up the same pagination as it's done on users page. Is that right for you?

**Comment by stianst** [comment]
That should do the trick. Although user page is using a table, while this is using a tree view so it would have to be a bit different. We don't have an example of how to do pagination with the tree view though.

**Comment by guitaro** [comment]
Hi,
As you asked since some days (months... sorry for this delay), I've added JUnits and improve UI to support pagination for groups.
I'm waiting for your feedbacks :) Thanks.

**Comment by stianst** [comment]
We don't accept unit tests using mocks. Please add tests to existing functional tests:
https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java

**Comment by guitaro** [comment]
Here's an update. Hope tests are what you expecte

**Comment by guitaro** [comment]
Sorry for close/open action on PR. Clicking mistake...

**Review by patriot1burke — COMMENTED** [review]
Please do not reformat files.  It is really hard to figure out what is just a line indentation and what is an actual change.

**Comment by guitaro** [comment]
Oh I'm sorry for that... My IDE doesn't hightlight that thinks... I'll change immediatly my settings. Thanks for all.

**Comment by patriot1burke** [comment]
@guitaro 

This is incomplete.  Default groups panel needs pagination. Also adding/removing groups to a user need pagination as well.   I reopened the issue.

I also had to fix a number of issues. I should have reviewed the original PR a little more closely.  The page queries caching code did not hook up with invalidations.  Had to add that otherwise it just broke everything.

**Comment by guitaro** [comment]
@patriot1burke Sorry to hear that... My tests perimeter should was larger than i've done.
As this PR was closed, I suppose that I have to created a new one isn't it ?

Can we separate backend and admin-client API changes and front changes into 2 distinct PullRequest ? By this way, we can provide step by step pagination, firstly in admin-client and then by UI ?

**Pull request merged**
