### PR TITLE
Fix *-Capability OSGI manifest to provide Claim…   …InformationPointProviderFactory via service loader

### LINKED ISSUE #9287: Use PolicyEnforcer within OSGI doesn't work
### Describe the bug

AbstractPolicyEnforcer will fail to load ClaimInformationPointProviderFactory within an OSGI environment.
The reason is the service loader is unable to find ClaimInformationPointProviderFactory.

### Version

15.0.2

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

Use the keycloak-adapter in an OSGI env. And use a keycloak.json with the attribute `"policy-enforcer": {}` set. This forces the adapter to use ClaimInformationPointProviderFactory. If you call now a secured endpoint, this will fail.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ChristianLutz**
Closes #9287

### CODE REVIEW

**Comment by pedroigor** [comment]
Running pipeline: 451.

**Review by pedroigor — DISMISSED** [review]
@mposolda Do you have any objection to this change?

I'm running the pipeline again but it seems to not break anything. Build: 460.

**Comment by ChristianLutz** [comment]
@pedroigor @stianst Any chance to get this merged?

**Comment by pedroigor** [comment]
@ChristianLutz Sorry for the time ... Running again 900.

**Review by mposolda — APPROVED** [review]
@pedroigor I don't see any issues with adding the changes. Not 100% sure if there is any side-effect, but since pipeline is OK, I guess we are fine? So approving this.

**Pull request merged**
