### PR TITLE
Include frame-ancestors for CSP 2

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Review by mvanhulsentop — COMMENTED** [review]
Maybe 'self' would be a better value then 'none'? At least in previous versions Keycloak used to use iframes. Also, it corresponds with the 'SAMEORIGIN' policy mentioned in the X-Frame-Options.

**Comment by abstractj** [comment]
@mvanhulsentop fair enough, makes sense.

**Comment by stianst** [comment]
There's two things missing:
* Update to migration guide
* Migration task

**Comment by abstractj** [comment]
@stianst just thinking about it. Should we worry about migrations? No new field was created, this pretty much only change the value that goes on CSP policies.

**Comment by stianst** [comment]
@abstractj if you don't do anything under migration existing realms is not going to get the new value. Take a look at MigrateTo3_1_0 it's pretty easi to add migration for this. Just check if the value is the same as the previous default and modify it to the new default if it is.

**Review by stianst — CHANGES_REQUESTED** [review]
Needs migration to update existing realms

**Comment by stianst** [comment]
Need to add migration to MigrationModelManager and also add a test to MigrationTest

**Comment by abstractj** [comment]
@stianst would you mind to give another look?

**Review by stianst — APPROVED** [review]

**Pull request merged**
