### PR TITLE
KEYCLOAK-681 - HTML emails

### PR DESCRIPTION
**Pull request by cfsnyder**
Changed content-type of emails so that we can include html in the email templates.

### CODE REVIEW

**Comment by stianst** [comment]
We need to support multi-part emails, not just text or html

**Comment by cfsnyder** [comment]
Ok, I understand. I wouldn't mind hacking on this to add support for multi-part emails as well since the html part will be very useful for me. It looks like the ticket is currently unassigned, so I assume you're open to contribution here? Anything else I should know about the vision for this feature before I attempt?

**Comment by stianst** [comment]
That'd be great. Other than it supporting multi-part I can't think of anything else. I've assigned the issue to myself so I can track it.

**Comment by panga** [comment]
Example:

```java
Multipart multipart = new MimeMultipart("alternative");

MimeBodyPart htmlPart = new MimeBodyPart();
htmlPart.setContent(htmlContent, "text/html");
multipart.addBodyPart(htmlPart);
message.setContent(multipart);
```

**Comment by stianst** [comment]
@panga that's very helpful, thanks

@cfsnyder where are you with this? It would make most sense if we had separate FreeMarker templates for plain-text and html?

**Comment by cfsnyder** [comment]
Thanks @panga .

@stianst  - I haven't thought of any better way to do this than to have separate templates for plain-text and html, so that is the direction that I was going to take. Unless anyone has a better idea.

**Pull request closed without merging**
