### PR TITLE
Fix to check correctly that the service account scope is assigned

### LINKED ISSUE #34875: Clients invalidated on each client credential grant
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

After the change in #34664 a client is invalidated on each call as `client.getClientScopes(true).containsKey(serviceAccountScope.getId())` is always false as the `id` is a UUID and the keys are the scope names.

https://github.com/keycloak/keycloak/blob/226daa41c72a7c2f0831dcaec6890eeed67afb30/services/src/main/java/org/keycloak/protocol/oidc/grants/ClientCredentialsGrantType.java#L86

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

If a default scope is already set, don't call enable service account

### Actual behavior

KC runs enable service account, thereby invalidating the Keycloak cache

### How to Reproduce?

Debugging

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #34875

The on the fly check to see if the service_account scope was assigned to the client was not OK (the key is the name and not the id! Sorry!). The scope is also change from default to none, so it's assigned only via service accounts enabled attribute. I think it's better this way.

### CODE REVIEW

**Comment by rmartinc** [comment]
2nd try adding the sa user for the failed test.

**Review by mposolda — APPROVED** [review]
@rmartinc Thanks!

**Comment by mhajas** [comment]
I compared the flamegraphs of this branch and current main with the commit that caused this issue reverted and it looks comparable. It seems the client are no longer invalidated that often.

Main with the commit reverted:
image

Main with the commits from this PR:
image

I didn't go through the code changes so I will leave it to @ahus1 to do the final review.

**Review by ahus1 — APPROVED** [review]
I tested this locally and I didn't see invalidations. This should resolve the performance regressions. Thanks you for this fix!

**Comment by ahus1** [comment]
@rmartinc - should the two commits be squashed when merging?

**Comment by rmartinc** [comment]
> @rmartinc - should the two commits be squashed when merging?

Yes, I think that it's part of the same fix. I just did in a second commit because maybe we wanted to revert the last part.

**Pull request merged**
