### PR TITLE
KEYCLOAK-8504 Ensure the authenticationFlowBindingOverrides client co…

### PR DESCRIPTION
**Pull request by sguilhen**
…nfiguration references a valid authentication flow id when a realm is imported

### CODE REVIEW

**Review by mposolda — DISMISSED** [review]
@sguilhen Approving. Thanks! It is a bit strange that for "authenticationFlowBindingOverrides", we reference the flows by ID when in all other places (RealmRepresentation, IdentityProviderRepresentation) we reference them by alias. But it's not the fault of this PR and changing may likely break some other things (EG ExportImport from JSONs created in previous versions). Keeping it this way as in this PR is probably the best we can do...

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by sguilhen** [comment]
@mposolda I agree 100% that it is a bit strange that this is the only reference by ID and just as you said I didn't want to make further changes to prevent breaking other things and ruining compatibility with previously exported JSON files.
As a side note, only one test currently failing on Travis but it works fine locally.

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@sguilhen Sorry, conflicting file (maybe due your other PR). Is it possible to update?

**Comment by sguilhen** [comment]
@mposolda sure, working on it. Should send a new commit very soon

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Pull request merged**
