### PR TITLE
[KEYCLOAK-17263] - Add exact searching by e-mail, first name and last…

### PR DESCRIPTION
**Pull request by SergiusAC**
Add exact searching by e-mail, first name and last name in Admin REST API Client.

### CODE REVIEW

**Comment by SergiusAC** [comment]
@mposolda @pedroigor could you please review this PR even though there are some failures unrelated to my code?

**Review by pedroigor — COMMENTED** [review]
@SergiusAC Not related. But why add another method if you already have one with more params than this one?

**Comment by SergiusAC** [comment]
> 
> 
> @SergiusAC Not related. But why add another method if you already have one with more params than this one?

If I change the existing method, it will impact on the existing code base using this method, so I decided to introduce new one with 'exact' params.
Do you suggest me to just add the 'exact' param in the existing method?

**Comment by pedroigor** [comment]
> Do you suggest me to just add the 'exact' param in the existing method?

I meant using any of these existing methods https://github.com/keycloak/keycloak/blob/de8d2eafa3321d325dc92d762d05df500ac6f79f/integration/admin-client/src/main/java/org/keycloak/admin/client/resource/UsersResource.java#L76.

Aren't they enough even if providing more parameters than what you need?

**Comment by SergiusAC** [comment]
@pedroigor Ok, I got you. But changing any of those methods will cause changes in code of some other projects if they want to update version of keycloak admin client. This is the reason I introduce the new method.

**Comment by pedroigor** [comment]
@SergiusAC Sorry, you are right.

Would you mind rebasing? LGTM.

**Comment by pedroigor** [comment]
@SergiusAC Could you rebase? Once you do that, I would like to merge this one. Thanks.

**Comment by SergiusAC** [comment]
@pedroigor I will create new PR, this one became unacceptable due to my fault :(

**Comment by SergiusAC** [comment]
@pedroigor Please, see this PR #8059.

**Pull request closed without merging**
