### PR TITLE
authz client token fix

### PR DESCRIPTION
**Pull request by csckcac**
Please check https://github.com/keycloak/keycloak/commit/d04b330c960c723b3721cf386e05c84b75e0e3ce

### CODE REVIEW

**Comment by csckcac** [comment]
@pedroigor, i cannot rebase it to master, since master is already using TokenCallable instead of Supplier<String>. Is it possible to create a 3.4.3-Final branch so that i can re-create PR against that branch?

**Comment by pedroigor** [comment]
@csckcac, sorry for the late response. Back from parental leave :)

The problem is that we don't apply patches to older releases thus we don't keep branches to apply these patches.

I guess latest version of Keycloak and upstream/master are already fixed with the issue you are trying to solve, right ?

**Comment by pedroigor** [comment]
@csckcac, can we close this one?

**Comment by pedroigor** [comment]
@csckcac, I'm closing this one. Feel free to re-open in case you think it is still relevant.

**Pull request closed without merging**
