### PR TITLE
KEYCLOAK-13721 Allow to configure the port of the callbackserver in the keycloak client

### PR DESCRIPTION
**Pull request by mvdlaan**
We are using the keycloak client in a Java desktop application. The default behaviour is that a callback server is created on a random available port. In our production environment this approach does not work, because it will perform some kind of port scan to find an available port. Therefore a configurable port does not perform a port scan and it will run the login procedure correctly in our production environment. The configurable port should be an optional configuration.

### CODE REVIEW

**Comment by stianst** [comment]
Can you elaborate a bit more on why this is an issue?

**Comment by mvdlaan** [comment]
We are using the key cloak client in a desktop application in production. On the systems/network where it is used, it is not allowed to do port scanning. Therefore the authentication using keycloak does not work. We have copied some keycloak code to our own code base and created this patch which a configurable port and then it does work correctly in our production environment.  But for maintainability reasons we think is is a much better idea to have a configurable port in the keycloak library itself.

**Review by stianst — CHANGES_REQUESTED** [review]
Port/configuration should not be passed into login/logout methods like this. Rather, it should be part of configuration passed in through keycloak.json. By default it should scan for a port like now, but allow fixing the port in keycloak.json config file if needed.

**Comment by stianst** [comment]
Closing due to lack of progress/feedback

**Pull request closed without merging**
