### PR TITLE
remove empty password check

### PR DESCRIPTION
**Pull request by gerbermichi**
https://issues.jboss.org/browse/KEYCLOAK-2123

### CODE REVIEW

**Comment by mposolda** [comment]
Michael, any chance you can do the same for direct access grants authentication too? It's class ValidatePassword. Will be cool, so that the behaviour is consistent among browser login and direct grant. WDYT?

**Comment by gerbermichi** [comment]
done

**Comment by mposolda** [comment]
Seems that it's failing on AccessTokenTest.testGrantAccessToken with NullPointerException. I guess we shouldn't pass null password to Pbkdf2PasswordEncoder, but return false instead from CredentialValidation.validateHashedCredential .

Would you mind to fix it? Or do you rather want me to cherry pick your commits and continue? I think that this is last issue, once you fix it I bet travis will be happy :)

**Comment by gerbermichi** [comment]
I fixed the null pointer according to your proposal. Thanks a lot.

**Comment by mposolda** [comment]
Thanks!

**Pull request merged**
