### PR TITLE
KEYCLOAK-9999 fix client import

### PR DESCRIPTION
**Pull request by benjamin37**
This PR fixes https://issues.jboss.org/browse/KEYCLOAK-9999?_sscc=t

### CODE REVIEW

**Comment by benjamin37** [comment]
Tests are currently failing due to travis is failing downloading dependencies 

`[ERROR] Failed to execute goal com.samaxes.maven:minify-maven-plugin:1.7.6:minify (min-js) on project keycloak-js-adapter: Execution min-js of goal com.samaxes.maven:minify-maven-plugin:1.7.6:minify failed: Plugin com.samaxes.maven:minify-maven-plugin:1.7.6 or one of its dependencies could not be resolved: The following artifacts could not be resolved: rhino:js:jar:1.7R2, com.google.javascript:closure-compiler:jar:v20161024: Could not transfer artifact rhino:js:jar:1.7R2 from/to google-maven-central (https://maven-central.storage-download.googleapis.com/repos/central/data/): GET request of: rhino/js/1.7R2/js-1.7R2.jar from google-maven-central failed: Connection reset -> [Help 1]`

**Comment by abstractj** [comment]
@benjamin37 thanks for submiting this. Please, rebase against master and also add integration tests for it.

**Comment by benjamin37** [comment]
Added a test, it also work in travis server-group1. The failing jobs of travis seem to have nothing to do with my changes. Some dependencies that can not be resolved.

**Review by mposolda — APPROVED** [review]
@benjamin37 Thanks for the PR and sorry for longer review.

**Pull request merged**
