### PR TITLE
Add missing scope to dependencies

### PR DESCRIPTION
**Pull request by lkubik**
I've added scope to the dependencies which had no scope but their scope was changed by the dependency management section. Try to avoid this in future please.

### CODE REVIEW

**Comment by stianst** [comment]
Why should we not add scope in the dependency management section?

**Comment by lkubik** [comment]
Scope in the dependency management section is correct but missing scope in the artifacts that are affected by the management is IMHO and colleague opinion a bad practice.

**Comment by lkubik** [comment]
Try to do mvn help:effective-pom on any poms that I changed. Scope of these artifacts will be changed by the dependency management section... This is at least not transparent in the first moment when you look in some of these changed pom files.

**Comment by stianst** [comment]
I'm not quite following - so you're saying instead of declaring a "test" dependency as such in the dependency management we have to declare it as test everywhere it's used?

**Comment by lkubik** [comment]
Yep, that's what I'm saying. But apparently I was wrong. I discussed that one more time with colleague and I misunderstood that. It would be a bad practice if this change would be done by an external BOM file. Apparently it's OK if it's changed by a project parent. I'm sorry, my bad. Closing this PR.

**Pull request closed without merging**
