### PR TITLE
KEYCLOAK-16075: require user interaction (button press) for WebAuthn on Safari

### PR DESCRIPTION
**Pull request by gtudan**
Safari will fail to use TouchID/FaceID if it is not triggered by an explicit user interaction.
This stops the automatic webauthn prompt through `onload` and shows a button instead.

### CODE REVIEW

**Comment by mposolda** [comment]
@gtudan Thanks for the PR! I wonder that for the non-safari browsers, the button might be hidden entirely?

@vmuzikar Do you have a chance to review this please? As I recall you have macbook? Especially is the algorithm for detect "safari" ok to you?

**Review by vmuzikar — COMMENTED** [review]
@gtudan Thank you for your contribution!

@mposolda On the other hand, I wonder whether we should make the change for all browsers, not just Safari. AFAIK the requirement of _user gesture_ is some privacy effort from Apple and there's a good chance others will copy it over time. Also, all other IdP servers where I encountered WebAuthn (GitHub, MojeID, Google, ...) use this approach with a button.

**Comment by archoversight** [comment]
> @gtudan Thank you for your contribution!
> 
> @mposolda On the other hand, I wonder whether we should make the change for all browsers, not just Safari. AFAIK the requirement of _user gesture_ is some privacy effort from Apple and there's a good chance others will copy it over time. Also, all other IdP servers where I encountered WebAuthn (GitHub, MojeID, Google, ...) use this approach with a button.

There's a tracking issue that was re-opened by my comment here: https://github.com/w3c/webauthn/issues/1293

**Comment by archoversight** [comment]
> @gtudan Thanks for the PR! I wonder that for the non-safari browsers, the button might be hidden entirely?

If the user accidentally clicks out of the WebAuthN form on Chrome/Edge they will now have to refresh the whole page, if the button stays they can simply attempt to click the button to try again. Hiding the button leads to worse UX.

**Comment by gtudan** [comment]
I was thinking about hiding the button for other browsers as well. Would be no problem, just let me know. 

Although I prefer the onload-way (one click less) I'm pretty sure other browser vendors will adopt the mandatory user gesture. It's a shame we don't have a way of detecting this before trying. The browser-detection surely isn't the best way of doing this.

**Comment by vmuzikar** [comment]
> So maybe a more robust solution would be to always use the button method (maybe with a little help text about what's going on and the "use another method"-link)?

+1

**Comment by gtudan** [comment]
I've updated the PR: now the button will always show with an option to return to the 2FA selection screen (similar to the OTP form).

Webauth-login

**Comment by gtudan** [comment]
I've added another fix for the registration page. It has the same issue when registration is requested through a required action.

**Comment by gtudan** [comment]
@vmuzikar Do you have any more feedback? Anything else that's missing?

**Review by vmuzikar — APPROVED** [review]
I tested it with Safari Tech Preview (where I was able to reproduce the issue) and it looks good to me. Thank you!

My only concern is if this change breaks some tests (for sure it does), but AFAIK the tests are currently broken in any case and hence they're not executed until we figure it out. @mposolda WDYT?

I'm approving as I'm pretty sure we can't do much about the tests right now.

**Review by mposolda — APPROVED** [review]
@vmuzikar @gtudan @archoversight Thanks everyone for the feedback and your work on this. Agree that always show the button is better approach for the UX and merging this PR. Thanks!

**Comment by fifofonix** [comment]
This is great but to make it even more similar to the GitHub experience, where a single key stroke will allow you to light up your U2F for validation, the base webauthn-authenticate.ftl template should be enhanced to achieve `autofocus` on the 'Sign In With Security Key' button...without this customization in Keycloak 14 you need to tab twice to this button and then strike enter/space.

**Pull request merged**
