### PR TITLE
[KEYCLOAK-2538] - groups pagination and group search

### PR DESCRIPTION
**Pull request by levyndot**
Group pagination responding to [JIRA KEYCLOAK-2538](https://issues.jboss.org/browse/KEYCLOAK-2538). Including fixes detected after #4209 validation ([JIRA KEYCLOAK-5701](https://issues.jboss.org/browse/KEYCLOAK-5701)).

Wainting for backup from @patriot1burke  and/or @stianst.

Thanks :)

### CODE REVIEW

**Comment by guitaro** [comment]
The pages number ton each lists is not updated when a search is done. I'm fixing it right now.

**Comment by guitaro** [comment]
It's ok for pages number update.

**Comment by guitaro** [comment]
Up

**Comment by guitaro** [comment]
Did you think that this PR can be released before February ?
Just to know what kind of answer we have to prepare to our clients on when they can use an official distribution with group pagination. Thanks :)

**Comment by stianst** [comment]
Due to feature freeze for Keycloak 3.x we're not able to accept this contribution at the moment. We would also really need some tests added here for the admin console as the previous PR for this was quite broken if I remember correctly. If the PR is updated and tests added we should be able to review and include it for the first Keycloak 4.x release which should be some time in February.

**Comment by guitaro** [comment]
Thanks @stianst for this answer.

**Comment by guitaro** [comment]
Hi,

I'm coming for news. Can we have any state on test progress for this feature ? Thanks.

**Comment by guitaro** [comment]
@patriot1burke, @stianst, any news please about this feature ? Thanks

**Comment by stianst** [comment]
@mposolda can you take a look at this please?

**Comment by mposolda** [comment]
@guitaro Thanks for the PR and sorry it took so long to review :( Overally it looks very good. I have few points:

- Will be good to squash the commits to contain just 1 commit in the PR instead of 14 commits and ensure it is rebases/cherry-picked on top of latest master. We strongly prefer rebase/cherry-pick instead of merging due the cleaner git history. I see there are conflicts in files GroupsResource and UsersResource, but not sure, if you rather don't want to remove any changes from those files entirely (as I see that your PR changes just imports).

- Is it possible that you add some automated tests to the admin console UI tests and re-check that your changes didn't break existing tests? See: https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md#admin-console-ui-tests

**Review by mposolda — CHANGES_REQUESTED** [review]
@guitaro Thanks for the PR and sorry it took so long to review :( Overally it looks very good. I have few points:

- Will be good to squash the commits to contain just 1 commit in the PR instead of 14 commits and ensure it is rebases/cherry-picked on top of latest master. We strongly prefer rebase/cherry-pick instead of merging due the cleaner git history. I see there are conflicts in files GroupsResource and UsersResource, but not sure, if you rather don't want to remove any changes from those files entirely (as I see that your PR changes just imports).

- Is it possible that you add some automated tests to the admin console UI tests and re-check that your changes didn't break existing tests? See: https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md#admin-console-ui-tests

**Comment by mposolda** [comment]
Closing as we had other PR with this functionality, which added also server-side support.

**Comment by mposolda** [comment]
@guitaro Thanks for your PR anyway. You can check if current master (Keycloak 4.7.0.Final) suits your needs.

**Pull request closed without merging**
