### PR TITLE
angular2-product-app: simplify KeycloakHttp

### PR DESCRIPTION
**Pull request by tsabirgaliev**
Implement Angular 2 example from scratch using latest and greatest Anglular 2.4.x and `angular-cli`

### CODE REVIEW

**Comment by ssilvert** [comment]
Sorry it has taken so long to look at this.  I tried your code and it's not fetching the data when you click "Reload".  I get a 401 "Unauthorized" error in the console when it tries to get http://localhost:8080/database/products.

**Comment by tsabirgaliev** [comment]
@ssilvert can you please provide some guidance on how to test this code? Can't figure out how to build the demo apps

**Comment by ssilvert** [comment]
How did you test your code before you submitted the PR?

**Comment by tsabirgaliev** [comment]
Ok, I managed to build the app and now see that the example relies on outdated version of angular. So now there are 2 paths I can go:

1. upgrade dependencies and stay with system.js (less impact on code, but harder to maintain)
2. replace the build tools with more modern angular-cli approach (more impact, easier to maintain)

What should I do?

**Comment by ssilvert** [comment]
I think #2 would be best.  You are thinking WebPack?

**Comment by ssilvert** [comment]
Oh, you said use angular-cli.  So that means definitely moving to WebPack.  That would be great.

**Comment by tsabirgaliev** [comment]
I hoped for that option as well :)

Ok, let me come back with more patches then

**Comment by tsabirgaliev** [comment]
@ssilvert please, review :)

**Comment by ssilvert** [comment]
Looks good now.  Works like a charm.

Did see a couple of things in /frontend that need to be touched up before we merge:
1. Change license in package.json to Apache 2.0
2. Update README.md to include detail on how to run with ng serve.  Have you tried enabling CORS?

**Comment by tsabirgaliev** [comment]
@ssilvert Done!

**Comment by ssilvert** [comment]
Great.  Thanks for the contribution!

**Pull request merged**
