### PR TITLE
[KEYCLOAK-2038] Bug-Fix: Password grant flow

### PR DESCRIPTION
**Pull request by pwolf23**
Allows password grant flow with required user consent, if user consent has been given.

### CODE REVIEW

**Comment by mposolda** [comment]
Thanks for the PR! Looks good, just few things:

- The formatting seems to be a bit broken. We are using 4 chars indent, the full ide template is for example here https://github.com/liveoak-io/liveoak/tree/master/support/ide-configs . It will be cool that in the "commits" tab, it cab be seen just changes of lines you really changed. This usually proves that you didn't change formatting of other parts of method or class.

- Would you mind to add the test? We have automated test for direct grant flow in class ResourceOwnerPasswordCredentialsGrantTest . Will be cool if you can add 1 or 2 new tests for both negative (ensure login is rejected if consent not granted) and positive (ensure login is ok if consent was already granted).

Thanks!

**Comment by pwolf23** [comment]
Hi,

Thanks for pulling! I will look into writing some tests later, but before
that... After I made the pull request I was thinking if user consent is
relevant in the password grant flow at all. Think about: The application is
in possession of the user credentials anyway and from a security
perspective the client app can give all user consent it wants to it self as
well.

I'm not totally sure how to think about that. What is your opinion on that?

Paul

**Comment by stianst** [comment]
With that in mind does it even make sense to permit password grant flow for a client that requires consent?

**Comment by pwolf23** [comment]
Or is the consent implicitly given with the user giving his credentials to
an app?

**Comment by stianst** [comment]
I agree with that, but I don't see the point in enabling consent for a client if you're going to be using password grant.

**Comment by mposolda** [comment]
Sorry to bring this now, but I am bit curious about your use-case. Since your client requires consent, you want to use this client in classic browser application (OAuth2 Authorization Code Grant). But since you're also interested in direct grant, you're using same client in non-browser context too. Isn't it better if you use 2 separate clients instead? (One for browser application and another one for direct grant)?

**Comment by stianst** [comment]
My current thinking now is that we should just throw an error if client requires consent

**Comment by pwolf23** [comment]
The problem I see with that is that the person/process creating the client
entity in Keycloak can be someone totally different from the developer of
the app. Imagine Alice is running an api for a web application (like gmail)
and wants developers to write apps (ie Keycloak clients) to access user
data of that web app in one way or another. Now Alice would _always_ and
for _all_ such Keycloak clients have user consent to be mandatory, right?
Now Bob wants to write an application. He registers, a client is generated
via developer portal app (with mandatory consent) and he gets his client id
and secret. Now he might just wants to use the password grant for
prototyping or he might wants to run the app on his server as a service
without ui. This wouldn't be possible however if you deny that flow for
apps with mandatory user consent.

Am I missing something? Is there any scenario, where Alice would not
require user consent for her api?

**Comment by stianst** [comment]
Assuming Bob and Alice do not work for the same organization and Bob is then writing a "3rd party app", then yes I would say you want to require user consent.

However, in those cases I would say that you actually want to explicitly disable the password grant as you don't want 3rd party apps to be implemented in such a way that they can collect your users passwords.

For running the app on his servers as a service Bob should have a service account for his app and not use a regular user account.

**Comment by pwolf23** [comment]
I am not sure Alice really would like to disable the password grant flow.
Disabling the flow would disable Bob's use case while at the same time it
wouldn't offer any advantage in security, since 3rd party clients could ask
the user for their password anyways and then have them sent to the IdP
directly. The user is responsible for taking care not to enter his
credentials into a third party app in any scenario.

You suggest to use a service account, but how would that be established in
this scenario? Should Alice (manually?) Create it just for Bob? How do you
make sure that Bob's service account just has access to Bob's data?

I think supporting the password grant is a valid use case (in addition to
the client credential grant you mention) and should be supported even with
a mandatory user consent (especially if it has been given) in order to be
oauth2 compliant.

Assuming Bob and Alice do not work for the same organization and Bob is
then writing a "3rd party app", then yes I would say you want to require
user consent.

However, in those cases I would say that you actually want to explicitly
disable the password grant as you don't want 3rd party apps to be
implemented in such a way that they can collect your users passwords.

For running the app on his servers as a service Bob should have a service
account for his app and not use a regular user account.

—
Reply to this email directly or view it on GitHub
<https://github.com/keycloak/keycloak/pull/1792#issuecomment-155001692>.

**Comment by stianst** [comment]
We've discussed this a bit and we've come to the conclusion that if a user provides a client a password that implies the user is giving the application consent. So for direct access grants there should be no difference if an client requires consent or not.

Would you like to prepare a PR for that? I would appreciate if you could make sure the formatting follows our formatting (especially spaces instead of tabs) so we can more easily see what changes you've made. Also, I would appreciate if you could add a test to ResourceOwnerPasswordCredentialsGrantTest in testsuite/integration.

**Comment by patriot1burke** [comment]
Stian, I guessed I missed this conversation...I disagree that direct grants mean the user has provided consent.

**Comment by stianst** [comment]
@patriot1burke here's my argumentation:

* If an app has access to username and password the app can emulate a browser and use the standard web flow endpoints in either case. So giving the application the password is the same as giving the application full control over your account.
* Requiring consent is not going to work as it requires the user to use the web flow with the same application before using the direct grant flow.
* Requiring consent is something baked into OAuth to prevent third party applications from automatically getting access to a users account without the users knowledge. This is only applicable to the web flows and primarily if the user is already logged-in to their account. There's just no need for consent for non-web based flows

Convinced or do you still disagree?

**Comment by pwolf23** [comment]
Hi Stian, I will be doing what you asked me for once Bill has expressed his
consent (pun intended ;))

**Comment by patriot1burke** [comment]
we save consent don't we?  User grants consent via browser, then direct grant is allowed since consent has been persisted and done in the past.  Build trust before you allow direct grants.  Just seems like you're adding a security hole...Especially since you remvoed the ability to turn of direct grants.

**Comment by stianst** [comment]
We do save consent, but that requires the user to login to the specific client first using the web flow. If the client is able to use the web flow it should use it always, not just as an initial setup stage.

As I stated there's just no need for a consent screen as the consent screen is only required to prevent a third party application from automatically login a user if the user is logged-in to SSO. With a standard web flow it's also possible to reduce the permissions granted to the client as the client doesn't have access to the users credentials.

With direct grant the user is required to enter username+password so there's no way for the client to automatically login the user.

There's no additional security hole with direct grant. Anyone with direct access to users username and password can just go ahead and emulate the browser in either case to retrieve a token. Web based flow is just HTTP requests, which can easily be created by any application to simulate the web browser.

Direct grant is not recommended as it leaks passwords to applications, which effectively gives applications full access to user accounts (doesn't matter if direct grant is enabled or not, if it requires consent or not).

We should have an option on each client to enable/disable direct grant. It should be disabled by default. However, that's only to increase awareness and make people use the proper web based flow. The only way to increase security beyond that is to educate users on where to enter their username and password, and also enable two factor authentication.

**Comment by patriot1burke** [comment]
Maybe you misunderstood me?  I'm saying the user has to grant consent through regular browser login flow before direct grants can be used.  Maybe thats too weird...

**Comment by stianst** [comment]
Nopes, I didn't misunderstand. I'm described why it won't work (client doesn't use web flow for a reason and consent is given through the web flow for a specific client). Also, described why it's not necessary and why it doesn't add any additional security.

**Comment by pwolf23** [comment]
In addition to Stian's points:

Password grant flow will not work in v1.6.1 even when consent has been
given! That is why I call this a bug and made the pull request in the first
place.

**Comment by patriot1burke** [comment]
I thought about this some more.

Consent means you don't fully trust the client and the user must consent to grant this semi-trusted application access to their stuff.  If the client does not require consent, then direct grants work just fine.  If the client does require consent or hasn't provided consent, then direct grants should just not be allowed to work.  I just don't agree that clients requiring consent should just automatically be allowed to invoke direct grants.

**Comment by patriot1burke** [comment]
If direct grants aren't checking that consent has already been given (I don't remember if we store that information), then that's a bug that needs to be fixed.   But, client requiring consent should not be allowed to invoke direct grants.  Sorry.

**Comment by patriot1burke** [comment]
HOnestly, it doesn't make sense that a client would both require consent and be allowed to invoke direct grants.  What's the point of requiring consent in the first place?

**Comment by stianst** [comment]
The reason why consent is required in the web flow is that the user can already be logged-in. In this case the user would automatically be logged-in to a third party application without giving any form of consent.

However, if the third party application uses direct grant and not the web flow the application has to request the username and password from the user. If the user provides the third-party application the username and password the user is explicitly giving the application full access to the users account. This is equivalent of the user giving consent and trusting the third-party application.

If we require consent for third-party applications it is the equivalent of not allowing third-party applications from using direct grant. If a third party is able to use the web flow (to obtain consent) it should use that in the first place. If it's not able to use the web flow, it can't obtain consent to subsequently be able to use direct grant.

End of the day though, it doesn't matter. As I've mentioned if a third party application has access to the users credentials the third-party application can emulate a browser to log the user in to Keycloak directly and can just submit the consent form on its own without any interaction from the user. A third-party application with access to the users credentials will also be able to do all sorts of other things like login to other applications, login to the account management console etc..

**Comment by patriot1burke** [comment]
Consent would be required even if the user is *NOT* logged in.  The user is granting permission to the app.  The consent is also logged and remembered and displayed to the user.  Its like a legal agreement.  Think of consent as a type of terms and conditions page.  Allowing direct grants to bypass this process is akin to allowing a user access to content where they didn't agree to the terms and conditions.

Again, it makes zero sense that consent would be required for browser logins, but not direct grant.

**Comment by pwolf23** [comment]
I agree with Stian here... The user can grant consent by giving his
password or by telling an identity provider to let a client access his data
without giving his password.

Now Bill, you wonder why a client would needs consent in the first place...
It's quite simple in my eyes. There is a user, an identity provider
(coupled to a service like facebook) and a client (e.g. a Facebook app).
Facebook has no clue about the trust relationship between a specific user
and a specific client (which can be indeed very high). That is why Facebook
would protect their users by being restrictive to other apps by requiring
consent (because they assume a worst case security scenario). In case the
trust between client and user is high however (implicated by the user
giving his password out), there is no reason for Facebook to prevent the
password grant flow.

Think about: in general... In all cases where user consent isn't needed,
oauth2 is absolutely unnecessary in the first place. Still they decided to
have a password grant flow in the standard as an exception of high trust in
an otherwise not trustworthy environment.

Having a password grant flow despite requiring consent isn't a problem in
the oauth2 standard. Being able to disable mandatory consent is a problem
(in terms of oauth2 use cases)

**Comment by patriot1burke** [comment]
Again, I equate consent to terms and conditions.  A direct grant request has no idea if the user agreed to provide consent or not.  Consent is not only a browser security measure but also a log that the user has agreed to a specific form of interaction.

**Comment by pwolf23** [comment]
I see your point, but then I would say that Stians argument still holds
true: You can never assume that a user has agreed to anything at all, since
you know that third parties are in possession of his password! In that case
the current implementation would make sense actually.

But I think it is valid to assume that a service provider doesn't care at
all OR he interprets it that way, that a user grants consent at the same
tame he registers at the identity provider. Would you exclude such use
cases?

To summarize I think there are 3 (relevant) scenarios:

A) User consent is necessary and therefore the password grant flow is not
permitted in any way (that is the current behaviour)

B) User consent is necessary and password grant flow is only permitted if
consent has been given in advance (this is the behaviour of my pull
request... however it seems kind of inconsequent to me now)

C) User consent is necessary, but implicitly given when a user uses
password grant flow and therefore the existence of previously given user
consent via another flow is irrelevant in the password grant flow (what
Stian is arguing and I agree and I think this is in the spirit of the
oauth2 spec)

A suggestion: If password grant flow can be turned on and off completely (a
new switch has to be introduced?), then you can have behaviour A when the
flow is off and you can have behaviour C when the password grant flow is
turned on. Makes sense?

**Comment by stianst** [comment]
We are going to introduce switches to enable/disable each flow independently.

**Comment by stianst** [comment]
It makes no sense to require consent for direct grant though. By the way even disable direct grant has no effect either. An application with the users username and password is perfectly able to do whatever they want. Take a look at:
https://github.com/keycloak/keycloak/blob/master/testsuite/integration/src/test/java/org/keycloak/testsuite/oauth/OAuthGrantTest.java
Imagine OAuthGrantTest is the third-party app. No user interaction required to click the consent button. It's also fully capable of obtaining a token all without direct grant, just using the standard authorization code flow.

**Comment by stianst** [comment]
I can't stress this enough - a user giving the username + password to an application is the same as consenting to give the application full access to the users account.

**Comment by stianst** [comment]
The log argument doesn't hold up either as there's a log entry about the application using direct grant as well.

**Comment by patriot1burke** [comment]
Stian, I disagree.  Consent is THE EXACT SAME THING as a terms and conditions page.  Would we allow a user to log in without clicking accept to Terms and Conditions?  No, we wouldn't.  What about any other required action?  Consent is just another required action.  

This idea that if somebody has the credentials of a user is irrelevant and an extremely DUMB argument.  Somebody that has credentials can pretty much do whatever they want period...

**Comment by patriot1burke** [comment]
The original thought to direct grant was that if there were any require actions pending, the direct grant would automatically fail.  Consent is just another required action.

**Comment by stianst** [comment]
I don't see how possession of user credentials is an irrelevant and DUMB argument. It's actually a very good argument as it allows anyone to obtain a token without user consent in either case. As I mentioned it's no problem whatsoever to use the standard authorization code grant in place of the direct grant flow as long as you have the username and credentials. IMO that fact alone renders this whole discussion pointless!

**Comment by stianst** [comment]
I'm still convinced that direct grant should not require consent. However, the only option remaining if we can't do that is to disallow direct grant for clients that require consent.

**Comment by stianst** [comment]
@pwolf23 Sorry it's taken so long, but we've finally managed to come to a conclusion on this one. The outcome is that we've decided it doesn't make sense to require consent for a client that uses direct grant. So we are going to disallow direct grant if consent is enabled. In 1.7 we're introducing some additional switches that allows enabling/disabling different flows for an individual client, which then allows disabling authorization code flow.

**Comment by pwolf23** [comment]
I am sad to hear that you came to this conclusion. Stian, I unterstand that
everyone able to perform the password grant flow is equally able to perform
the authorization flow regardless of whether consent is required or not.
This is absolutely correct... However: Why do you think then the password
grant flow exists in the first place?

I think the route you took with this issue makes Keycloak not fully
implement the  oauth2 spec, which is a shame. Especially since the solution
is so near: if you enable the admin to switch of each flow seperately for
any client, why do you deny switching on password grant when consent is
required? Why don't you let the admin decide what is good for them.

Bill, I understand your reasoning why password grant and mandatory user
consent should not be enabled at the same time. I am afraid however that
you don't understand that your reasoning is just one of many. A company
using Keycloak might handle terms of conditions in a different way, but
still needs user consent; consent not in the meaning of terms and
conditions but more in the sense of authorizing an application which is not
needed for password grant, but all other flows. The initial use case I
outlined still can't be solved and Alice would be left with not using
Keycloak.

While your reasoning, Bill, might be sound, please don't be ignorant to
other reasonings and use cases of (potential) Keycloak users, which might
be different but no less sound.

I think the fix as it currently stands doesn't solve the initial problem. I
hope you reconsider and enable the password grant switch (which can still
be turned off by the administrator) regardless of the user consent settings.

**Comment by stianst** [comment]
I don't see the issue? For an application that needs to use direct grant, disable the authorization code and consent. For an application that wants to use consent the web flow is required in either case as otherwise there's no way for a user to review and consent. It doesn't make any sense to have one application that uses direct grant if it can use the web flow, so there's no point in being able to do both from the same application. Please elaborate exactly on how your use-case is not possible.

I don't believe this makes us incompatible with the oauth2 spec. Please elaborate exactly (and refer to the spec if possible) how it makes us incompatible with the spec.

Obviously if you can give us a use-case that is not possible and/or can refer to how we are incompatible with the spec we will reconsider.

**Comment by pwolf23** [comment]
So let's have a look at the specification. The specification doesn't use
the terms "user", "consent" and "direct grant". So let's find the
equivalent terms:

The entity most likely to be the end-user is called "resource owner":
"An entity capable of granting access to a protected resource. When the
resource owner is a person, it is referred to as an end-user." (1.1.)

There is no concept of consent. Instead there is only an "authorization
grant":
"An authorization grant is a credential representing the resource owner's
authorization (to access its protected resources) used by the client to
obtain an access token.  This specification defines four grant types --
authorization code, implicit, resource owner password credentials, and
client credentials --..." (1.3.)

What you call direct grant (and I password grant) is described in 1.3.3. as
"resource owner password credentials":
"The resource owner password credentials (i.e., username and password) can
be used directly as an authorization grant to obtain an access token."

So we talked about "consent" and "direct grant". In oauth2 lingo it is _the
same thing_. Let me make that clear:
1. "An authorization grant is a credential representing the resource
owner's authorization (to access its protected resources)" -> An
authorization grant _is_ the consent!
2. "The resource owner password credentials (i.e., username and password)
can be used directly as an authorization grant" -> The username and
password are the same thing as consent!

Strictly speaking: If Keycloak won't allow the "direct grant" while "user
consent" is mandatory, this is per oauth2 oxymoronic, since it is the same
thing!
Further strictly speaking: If you have the authorization code flow or
implicit flow and you don't ask for user consent (because Keycloak has it
disabled) this is not oauth2 anymore ("Before directing the resource owner
back to the client with the authorization code, the authorization server
authenticates the resource owner and obtains authorization." - The last
part "...and obtains authorization" is the important thing here).

So I hope this is obvious to you?

Regarding my use case... I repeat what I said before:
--------------
Imagine Alice is running an api for a web application (like gmail) and
wants developers to write apps (ie Keycloak clients) to access user data of
that web app in one way or another. Now Alice would _always_ and for _all_
such Keycloak clients have user consent to be mandatory, right? Now Bob
wants to write an application. He registers, a client is generated via
developer portal app (with mandatory consent) and he gets his client id and
secret. Now he might just wants to use the password grant for prototyping
or he might wants to run the app on his server as a service without ui.
This wouldn't be possible however if you deny that flow for apps with
mandatory user consent.
--------------
Per oauth2 spec you would be able to have a safe authorization code and
implicit flow, as the authorization server "obtains authorization [from the
resource owner]", while at the same time having the resource owner password
credentials grant flow as an option. In the oauth spec authorization code
flow and resource owner password credentials grant flow for a single client
can be used at the same time and are not exclusive!

In Keycloak it is not possible! That is why I say that Keycloak (in the
current state) is not oauth2 conformant and the solution to the issue
doesn't change a thing! I already proposed a solution, which (to me) seems
trivial to be implemented and would satisfy the the oauth2 spec (in this
specific regard).

2015-11-25 9:18 GMT+01:00 Stian Thorgersen <notifications@github.com>:

**Comment by stianst** [comment]
I still disagree that we are not conforming to the specification. What we call consent is the option of requiring a user to manually review what permissions are given. Exactly how consent is given is outside of the spec. When the consent button is off we assume that the admin has given the application consent on behalf of the user as the admin deems the client trusted.

Obviously with the resource owner credentials grant this is not possible, and not necessary either as the user has already given the application full access to his account, so there's no need for the consent screen.

There's also nothing in the spec that mandates what flows are required and if it's possible to mix multiple flows for a single client. It even goes further and suggests that an IdP should be careful about allowing resource owner credential grant and implicit flow at all.

In Keycloak your use-case is perfectly possible. Assuming you have a portal that allow's Bob to create his own client you let him choose which flow he wants. If he wants the authorization flow, you enable consent and the authorization flow grant. If he wants the direct grant flow you disable authorization flow and enable resource owner cred flow.

End of the day I don't see it as a big issue to allow resource owner credential grant even with the consent option enabled. As I agree with you that the fact that the application has the resource owners credentials implies the user has given (intentionally or unintentionally) full access to the app. It also doesn't matter as if the application has the credentials the application could just use the authorization code flow and simply submit the consent page itself. I will discuss it again with the others in the team next week.

**Pull request closed without merging**
