### PR TITLE
Fix missing migration when reading TERMS_AND_CONDITIONS required action

### LINKED ISSUE #17277: Can't accept terms and conditions after upgrade from 20.0.3 to 21.0.0
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

We have enabled Terms and Conditions and Email verificiation as required default actions when a new user is registered.

We updated to keycloak 21 today and new users can't accept the terms and conditions any more.
When Accept is clicked it just reloads the page, and the action isn't removed from the list of required user actions for the user.

### Version

21.0.0

### Expected behavior

When accept is clicked on the terms and conditions page the next required action is triggered, or the user is logged in and redirected to the application

### Actual behavior

Terms and conditions page is refreshed when clicking accept.

### How to Reproduce?

Enable terms and conditions as required default action in the realm authentication settings.

Create a new user. Click on accept on the terms and conditions page

### Anything else?

Some logs around the issue:
```
DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-16) `hibernate.connection.provider_disables_autocommit` was enabled.  This setting should only be enabled when you are certain that the Connections given to Hibernate by the ConnectionProvider have auto-commit disabled.  Enabling this setting when the Connections do not have auto-commit disabled will lead to Hibernate executing SQL operations outside of any JDBC/SQL transaction.
DEBUG [org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl] (executor-thread-16) Hibernate RegisteredSynchronization successfully registered with JTA platform
DEBUG [org.keycloak.services.resources.SessionCodeChecks] (executor-thread-16) Will use client 'web-md-app' in back-to-application link
DEBUG [org.keycloak.services.util.CookieHelper] (executor-thread-16) Could not find any cookies with name {0}, trying {1}
DEBUG [org.keycloak.services.util.CookieHelper] (executor-thread-16) AUTH_SESSION_ID_LEGACY cookie found in the request header
DEBUG [org.keycloak.services.util.CookieHelper] (executor-thread-16) AUTH_SESSION_ID_LEGACY cookie found in the cookie field
DEBUG [org.keycloak.services.managers.AuthenticationSessionManager] (executor-thread-16) Found AUTH_SESSION_ID cookie with value 4bc3b110-fdc9-43e7-8678-9237b771faeb
DEBUG [org.keycloak.services.resources.SessionCodeChecks] (executor-thread-16) required action doesn't match current required action
DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-16) JtaTransactionWrapper  commit
DEBUG [org.hibernate.engine.transaction.internal.TransactionImpl] (executor-thread-16) On TransactionImpl creation, JpaCompliance#isJpaTransactionComplianceEnabled == false
DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-16) Initiating JDBC connection release from beforeTransactionCompletion
DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-16) Initiating JDBC connection release from afterTransaction
DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-16) JtaTransactionWrapper end
DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-16) new JtaTransactionWrapper
DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-16) was existing? false
DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-16) `hibernate.connection.provider_disables_autocommit` was enabled.  This setting should only be enabled when you are certain that the Connections given to Hibernate by the ConnectionProvider have auto-commit disabled.  Enabling this setting when the Connections do not have auto-commit disabled will lead to Hibernate executing SQL operations outside of any JDBC/SQL transaction.
DEBUG [org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl] (executor-thread-16) Hibernate RegisteredSynchronization successfully registered with JTA platform
DEBUG [org.keycloak.services.resources.SessionCodeChecks] (executor-thread-16) Will use client 'web-md-app' in back-to-application link
DEBUG [org.keycloak.services.util.CookieHelper] (executor-thread-16) Could not find any cookies with name {0}, trying {1}
DEBUG [org.keycloak.services.util.CookieHelper] (executor-thread-16) AUTH_SESSION_ID_LEGACY cookie found in the request header
DEBUG [org.keycloak.services.util.CookieHelper] (executor-thread-16) AUTH_SESSION_ID_LEGACY cookie found in the cookie field
DEBUG [org.keycloak.services.managers.AuthenticationSessionManager] (executor-thread-16) Found AUTH_SESSION_ID cookie with value 4bc3b110-fdc9-43e7-8678-9237b771faeb
DEBUG [org.keycloak.services.managers.AuthenticationManager] (executor-thread-16) processAccessCode: go to oauth page?: false
```

especially the line `DEBUG [org.keycloak.services.resources.SessionCodeChecks] (executor-thread-16) required action doesn't match current required action` seems strange.

It seems even worse, I can't remove the terms and conditions action using the admin console. If I remove the action from required actions of the user and save, it seems like it has been removed, but if I refresh the page, the action reappears again.

### PR DESCRIPTION
**Pull request by mhajas**
Closes #17277

### CODE REVIEW

**Review by sguilhen — APPROVED** [review]
LGTM @mhajas . Thanks!

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Please ensure the migration on the logical level is only developed at that level.

**Comment by hmlnarik** [comment]
Given this is a blocker, I suggest fixing this via JPA changelog in the legacy store and ignoring map storage for now

**Comment by mhajas** [comment]
Thanks @hmlnarik, I will prepare another PR then.

**Pull request closed without merging**
