### PR TITLE
KEYCLOAK-16392 Client Policy - Condition : NPE without any initial configuration

### PR DESCRIPTION
**Pull request by tnorimat**
This PR is for [KEYCLOAK-13933 Client Policies](https://issues.redhat.com/browse/KEYCLOAK-13933), also is the part of the project [Client Policy Official Support](https://github.com/keycloak/kc-sig-fapi/projects) of [FAPI-SIG](https://github.com/keycloak/kc-sig-fapi) activity.

Potentially NPE may happen on existing conditions when no initial configuration is set to these conditions.

### CODE REVIEW

**Comment by tnorimat** [comment]
@mposolda This PR is not directly about Client Policy Official Support I mentioned in [page 16 of FAPI-SIG 6th Meeting Agenda](https://github.com/keycloak/kc-sig-fapi/blob/master/FAPI-SIG/meetings/6th/presentations/FAPI-SIG_6th_MTG_agenda%20.pdf) but relates to them. Could you or your team also review this PR?

**Review by mposolda — CHANGES_REQUESTED** [review]
@tnorimat Thanks for the PR. Will it makes sense to add the test for this?

**Comment by tnorimat** [comment]
@mposolda I've added tests and rebased.

**Review by mposolda — APPROVED** [review]
@tnorimat Cool, Thanks!

**Pull request merged**
