### PR TITLE
KEYCLOAK-12624 ECDSA KeyFactory not available

### PR DESCRIPTION
**Pull request by mstruk**
Fix EC KeyFactory provider loading issue.

### CODE REVIEW

**Comment by stianst** [comment]
@mstruk Hi, long time since I've heard from you :)

Looks like a correct change, but what's a bit strange is that I can't reproduce it. We have a few tests, including JWKTest.publicEs256 which passes fine here on OpenJDK 8.

**Comment by stianst** [comment]
Is there any chance this is being used when BouncyCastle isn't available? Seems OpenJDK only has EC, while BouncyCastle has EC and ECDSA.

**Comment by mstruk** [comment]
@stianst Hey, it's been a while yes :)

That's a good point about BouncyCastle. We package only `bcprov-jdk15on-1.60.jar` - trying to keep third party dependencies to the minimum.

It sounds like adding `bcpkix-jdk15on-1.60.jar` might fix the issue?

**Comment by stianst** [comment]
Yes, I think it would. To be honest I couldn't figure out conclusively if there would be any difference switching from ECDSA to EC, so safest would be if you try include that dependency and see if it's working after that.

**Comment by stianst** [comment]
Also, not sure where and how you are using this, but the BouncyCastle provider needs to be configured.

**Comment by mstruk** [comment]
The context is non-web resource server (Kafka Broker) accepting signed JWT tokens for authentication - performing token validation using Keycloak-core as a helper library.

You can see the code [here](https://github.com/strimzi/strimzi-kafka-oauth/blob/master/oauth-common/src/main/java/io/strimzi/kafka/oauth/validator/JWTSignatureValidator.java).

The issue first showed up when [a user encountered difficulties](https://github.com/strimzi/strimzi-kafka-operator/issues/2327) when using their authorization server  (not Keycloak) configured with EC.

**Comment by mstruk** [comment]
@stianst By configuring provider you probably mean adding this:
```
static {
  Security.addProvider(new BouncyCastleProvider());
}
```
Or is there maybe more?

**Comment by stianst** [comment]
@mstruk that should probably do the trick as long as that is executed first

**Comment by stianst** [comment]
@mstruk I'm going to close this (and the bug report) for now. If you continue having issues feel free to drop me an email.

**Comment by mstruk** [comment]
I understand the reservation about changing a piece deep in the code with possible unintended consequences in many places.
Let me just share my conclusions based on additional exploration while trying to work around this issue.

When only Sun EC provider is available, without BouncyCastle provider, then with the proposed patch everything works nicely for my use-case.

If BouncyCastle provider is installed in first position, then with the proposed patch the code will find BouncyCastle provided factories for both "EC" and "ECDSA" when they are loaded. 

If BouncyCastle provider is installed in last position, then with the proposed patch the code will find Sun EC provided factories when "EC" is requested, and BouncyCastle provided factories when "ECDSA" is requested. Even then, everything still works for me even though two different implementations have to inter-operate.

The conclusion would be that since properly installing BouncyCastle results in both "EC" and "ECDSA" be covered by BouncyCastle, then only consistently using "EC" in all the places in the code where providers are specified should make no difference. But there would be a clear benefit to this in that it would make BouncyCastle optional as a provider. Default Sun EC provider seems to fulfil the role just fine for signature validation. 

The security providers can always be configured from outside the code as well, so one can for example edit `$JAVA_HOME/jre/lib/security/java.security` and exactly place BouncyCastleProvider to the position they want, so no need even to perform:

    Security.addProvider(new BouncyCastleProvider());

or:

    Security.insertProviderAt(new BouncyCastleProvider(), 1);

Thus, currently without the fix JWKParser has a hard dependency on BouncyCastle which IMHO is unnecessary.

**Pull request closed without merging**
