### PR TITLE
KEYCLOAK-14574: Upgrade angularjs to 1.8.0

### PR DESCRIPTION
**Pull request by ssilvert**
Need to merge #7222 before this one.

### CODE REVIEW

**Comment by ssilvert** [comment]
UI tests passed.

**Review by hmlnarik — DISMISSED** [review]

**Comment by hmlnarik** [comment]
Approval based on the UI tests passing.

**Comment by abstractj** [comment]
@ssilvert merged #7222 before this one. But it seems that we need a rebase now.

**Comment by abstractj** [comment]
@ssilvert I believe we need to update `package-lock.json` too. I can explain to you why in some minutes.

**Comment by ssilvert** [comment]
> @ssilvert I believe we need to update `package-lock.json` too. I can explain to you why in some minutes.

Makes sense.  I'll take care of it.

**Comment by ssilvert** [comment]
@abstractj Not sure why we were not committing package-lock.json, but I have now rebased and included that file.

Kicking off the UI tests again.  Build number 180.

**Comment by abstractj** [comment]
I will wait for GH actions to run, but that's not a deal breaker to merge.

**Review by abstractj — APPROVED** [review]

**Pull request merged**
