### PR TITLE
always preserve URL fragment in redirectUri

### PR DESCRIPTION
**Pull request by mwcz**
When redirectUri is called currently, keycloak.js will only preserve the URL fragment (aka 'hash' aka 'anchor') if no URL was passed in.  For example:
1. navigate to https://mysite.com/#foo
2. run `keycloak.login()`
3. log in

Keycloak will return you to https://mysite.com/?redirect_fragment=foo#state=...&code=...
Then keycloak.js will restore `redirect_fragment`, and you're back at https://mysite.com/#foo, perfect.

However, if a redirectUri is passed in, any fragments will be lost.  For example:
1. navigate to https://mysite.com/
2. run `keycloak.login({ redirectUri: 'https://mysite.com/#foo' })`
3. log in

Keycloak will return you to https://mysite.com/#state=...&code=... and then https://mysite.com.

This patch runs the fragment preservation code no matter where the redirectUri came from.

I'm happy to start a JIRA or a mailing list discussion on request.

### CODE REVIEW

**Comment by stianst** [comment]
Can you create a JIRA please? I'd also like to see a test added to https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/example/AbstractJSConsoleExampleAdapterTest.java

**Comment by stianst** [comment]
Until a JIRA and a test is added I can't merge this

**Comment by mwcz** [comment]
Sorry for the slow response.  I'll see about getting that test added and create a JIRA once the test is ready.

**Comment by stianst** [comment]
Closing the PR. Please send a new PR once it's ready.

**Comment by mwcz** [comment]
I tried to add a test but I couldn't get keycloak running.  All of the mvn comands failed for me, so I need to collaborate with someone who's more familiar with Java development.  @cainj13, interested?

**Comment by cainj13** [comment]
sure thing.  Just gotta carve out some time @mwcz

**Comment by stianst** [comment]
@mwcz let me know when you have time to look at this again. I gave it a quick spin and it seemed to break  things for me. Perhaps that was caused by my attempt at merge conflict not sure.

**Comment by mwcz** [comment]
Will do, it will be after Summit but I'll let you know!

**Comment by mwcz** [comment]
Hey @stianst, I'm going to take a look at this in the next 2-3 weeks.  Just FYI :)

**Comment by stianst** [comment]
@mwcz great, thanks. @mhajas is the guy to talk to about how to add tests as he's our JavaScript testing guru :)

**Comment by mwcz** [comment]
@mhajas Hi!  What's the latest on mergin JS adapter changes?  I see it passed the test suite.  My PR doesn't have any tests in it though.  I can add some if you point me towards how to test JS adapter changes.  Thanks!

**Comment by mwcz** [comment]
@stianst I'm hoping to get this done in my team's current sprint, is there some doc I can look at to find whatever might be missing from this PR?

**Comment by mhajas** [comment]
@mwcz Hi. Unfortunately, PR can't be merged without tests. All JavascriptTests are in JavascriptAdapterTest.java. I think it should be enough, to login option (redirectUri), similar to [here](https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/javascript/JavascriptAdapterTest.java#L133) and then check whether url which you were redirected to contains fragment uri. If you won't be able to make it work, just let me know, seems like an easy test I can do it for you.

**Comment by mwcz** [comment]
Thanks @mhajas!  I made an attempt, but Java dev environment issues got me (as usual).  I can't get Keycloak to build, similar problem I had in 2016 when I first created the PR.  I haven't worked on a Java project in about 10 years so I am way out of touch with how to fix this.  Any advice?

I'm sure it would be much faster for you to write the tests, but I don't want to put any more work on your plate.

Versions:
```
Apache Maven 3.5.2 (Red Hat 3.5.2-5)
Maven home: /usr/share/maven
Java version: 10.0.1, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-10-openjdk-10.0.1.10-4.fc28.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.16.16-300.fc28.x86_64", arch: "amd64", family: "unix"
```

Error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project keycloak-saml-core: Compilation failure: Compilation failure: 
[ERROR] ./keycloak/saml-core/src/main/java/org/keycloak/saml/processing/core/util/XMLSignatureUtil.java:[757,42] incompatible types: java.util.List<java.lang.Object> cannot be converted to java.util.List<? extends javax.xml.crypto.XMLStructure>
[ERROR] ./keycloak/saml-core/src/main/java/org/keycloak/saml/processing/api/util/KeyInfoTools.java:[51,70] incompatible types: java.util.List<javax.xml.crypto.XMLStructure> cannot be converted to java.lang.Iterable<java.lang.Object>
[ERROR] ./keycloak/saml-core/src/main/java/org/keycloak/saml/processing/api/util/KeyInfoTools.java:[55,70] incompatible types: java.util.List<javax.xml.crypto.XMLStructure> cannot be converted to java.lang.Iterable<java.lang.Object>
[ERROR] ./keycloak/saml-core/src/main/java/org/keycloak/saml/processing/api/util/KeyInfoTools.java:[60,58] incompatible types: java.util.List<capture#1 of ?> cannot be converted to java.lang.Iterable<java.lang.Object>
```

**Comment by mhajas** [comment]
I see, no problem. I will look at it, hopefully, I will manage to do it this week. 

In case you are interested in how to run tests, try:

From root directory:
````
mvn clean install -Pdistribution -DskipTests
````

Then change directory to: testsuite/integration-arquillian and run:
````
mvn clean install -Dtest=JavascriptAdapterTest
````

This should run all javascript tests we have. If you want to tests with firefox add:

````
-Djs.browser=firefox
````

**Comment by mwcz** [comment]
@mhajas I am happy to continue working on this if someone can give me assistance getting past the build errors.

**Comment by mposolda** [comment]
@mwcz Not 100% sure, but maybe your Java is too new?  Would you mind try to downgrade to Java 8? Mine is:

$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

$ mvn -version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /home/mposolda/software/apache-maven-3.3.3
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-128-generic", arch: "amd64", family: "unix"

**Comment by mhajas** [comment]
Thanks @mposolda I didn't realize this.

@mwcz I tried to do a test for this, but I have a problem. I tried two scenarios:

### 1st:
1. navigate to testApp/index.html#fragmentPart
2. Login using js adapter
3. Successfully authenticated, but I am not redirected to 
````
testApp/index.html#fragmentPart
```` 
but to: 
````
testApp/index.html?redirect_fragment=fragmentPart
````

### 2nd
1. navigate to testApp/index.html
2. Login using js adapter (with testApp/index.html#fragmentPart as redirectUri for login function)
3. Again Successfully authenticated but again with fragment as query param, not as fragment

Is this correct? I would expect this fragmentPart is in fragment not in query param.

**Comment by mwcz** [comment]
@mposolda Nice!  I downgraded to 1.8.0_172 and it works.  I couldn't easily downgrade maven (still on 3.5.2) but that didn't seem to matter.  Builds and tests work now.  Thanks.

@mhajas That's definitely not the right behavior.  I'll take a look.

**Comment by mhajas** [comment]
@mwcz You are right, thanks. I tried my tests in master and it is working, so I created issue and new PR with tests https://github.com/keycloak/keycloak/pull/5360

**Pull request closed without merging**
