### PR TITLE
Use feature versions for admin3, account3, and login2

### LINKED ISSUE #33405: Use feature versions for admin3, account3, and login2
### Description

We recently added support for versioning of features. For example the hostname:v2 feature:

https://github.com/keycloak/keycloak/blob/main/common/src/main/java/org/keycloak/common/Profile.java#L109

Ideally we would use the same for Admin, Account, and Login, to make consistent, as well as having the ability to introduce new features in the future.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by edewit**
- **Use feature versions for admin, account, and login**
- **WIP**

fixes: #33405

### CODE REVIEW

**Review by stianst — APPROVED** [review]

**Review by mabartos — APPROVED** [review]
LGTM

**Comment by shawkins** [comment]
@mabartos @stianst @vmuzikar doesn't this need at least an upgrade note because if anyone was using the existing feature keys in the features option, they will no longer work. I believe that concern is why we didn't make a similar change initially when introducing versioned features.

**Comment by mabartos** [comment]
@shawkins Yes, the upgrade note would be perfect. Will you take care of it?

**Comment by shawkins** [comment]
@mabartos sure, I can do that. Just want to get a few more eyes on this as a breaking change to make sure that's what we want to do - if anyone wants to add logic to continue using the deprecated old names we can do that instead.

**Comment by mabartos** [comment]
@shawkins I'd rather unify the versioning of features in the major release with the appropriate upgrading guide. Like, why do some features behave like this and the other one differently? 

It makes sense to me to do it now. WDYT?

**Comment by shawkins** [comment]
> It makes sense to me to do it now. WDYT?

It just comes down to the tolerance of making a potentially breaking change. As long as that is the concensus, then we'll proceed.

**Pull request merged**
