### PR TITLE
Action expired error occurs when accessing regular registration page …

### LINKED ISSUE #33064: Action expired error occurs when accessing regular registration page with Organizations enabled
When the feature is enabled and regular registration page is accessed there is `Action expired` error while it is expected to succeed.

### PR DESCRIPTION
**Pull request by vramik**
…with Organizations enabled

Closes #33064

### CODE REVIEW

**Review by sguilhen — APPROVED** [review]

**Review by jonkoops — APPROVED** [review]

**Comment by ahus1** [comment]
@jonkoops - can you please have a look at https://github.com/keycloak/keycloak/actions/runs/10924714425/job/30330678806?pr=33065 -- I restarted it once, and I a second re-run is running now. Not sure if that one will complete. Thank!

**Comment by jonkoops** [comment]
calling @keycloak/ui

**Comment by sguilhen** [comment]
@jonkoops  @ahus1 Problem here is that with orgs enabled, the default browser flow has now a different structure in new realms created. I could not find a way to make the test work with the new flow, so for this test I've tried switching to master realm before checking the browser flow structure. The flows are not changed in master, only in new realms - looks promising, see https://github.com/keycloak/keycloak/pull/33073

**Comment by sguilhen** [comment]
Can't make the other PR get a green CI - I'm facing operator failures all the time in pretty much every PR I open. That one is not an option yet unless someone can re-run the failing tests

**Comment by sguilhen** [comment]
Closing in favor of https://github.com/keycloak/keycloak/pull/33086

**Pull request closed without merging**
