### PR TITLE
Adds init param to automatically logout on failed token refresh.

### PR DESCRIPTION
**Pull request by RyanLefebvre**
This PR addresses this issue: https://github.com/keycloak/keycloak/issues/14568

### CODE REVIEW

**Comment by RyanLefebvre** [comment]
@stianst @mposolda  Could I get a review please?

**Comment by mposolda** [comment]
@RyanLefebvre Can you please try with latest Keycloak server and keycloak adapter build from the latest Keycloak main? Or eventually from latest Keycloak nightly build? I think this issue was resolved in Keycloak main in the meantime - however possibly not yet available in any released version.

**Comment by RyanLefebvre** [comment]
@mposolda We tried with the latest version and still saw the issue. I checked the commit history and source code for the keycloak repo and did not see anything indicating that this would have been fixed. I believe the bug is still there.

**Comment by mposolda** [comment]
@RyanLefebvre The method `createLogoutUrl` on the keycloak.js adapter is changed to include `id_token_hint` just when ID token is present to the adapter. Also there is `client_id` parameter included, which can be consumed by latest Keycloak. In case that Keycloak server receives logout request just with `client_id` and `post_logout_redirect_uri` parameters and there is no session in the browser, Keycloak will automatically "finish" logout as "successful" and redirect back to client.

Are you sure you test with the latest version of keycloak.js with these changes included and with the latest version of Keycloak server?

**Comment by mposolda** [comment]
@RyanLefebvre Sorry to ask again, but do you please have opportunity to doublecheck with latest Keycloak 21 server and latest Keycloak 21 adapter? The Keycloak 21 was released just today. Thanks!

**Comment by mposolda** [comment]
Closing due not feedback to previous comment. Please re-open if you think that this is still valid, but then please reply to previous comment and eventually update PR accordingly.

**Comment by vladimirsvicevicsrb** [comment]
The behavior is the same in the latest 23.0.3 version...

**Pull request closed without merging**
