### PR TITLE
[Admin Console v2] Policy creation at Permissions screen

### LINKED ISSUE #21908: [Admin Console v2] Policy creation at Permissions screen missing
### Description

In #20884 we added the navigation feature but not the creation of a new policy in the permission screen.
Within this issue this will be implemented.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andreas-blaettlinger**
Closes #21908

### CODE REVIEW

**Comment by andreas-blaettlinger** [comment]
@jonkoops As discussed in #20884 we added the policy creation on the permission screen in this separate PR.

**Review by jonkoops — APPROVED** [review]
Thanks @andreas-blaettlinger, this looks good to me :+1:

**Comment by andreas-blaettlinger** [comment]
@jonkoops Are we waiting for something here? 🙂

**Comment by jonkoops** [comment]
Nope, I expected some more of the team to weigh in, but let's merge this now.

**Comment by jonkoops** [comment]
Thanks again @andreas-blaettlinger!

**Pull request merged**
