### PR TITLE
Update reverseproxy.adoc

### PR DESCRIPTION
**Pull request by tslol**
Fixed Spelling Error

### CODE REVIEW

**Comment by ahus1** [comment]
Thanks for contributing this PR. When creating PRs, this project asks in its contributing guidelines to: 

* create a GitHub issue first
* reference the GitHub issue in the commit message of the pull request with a message as the following: 
```
A brief descriptive summary

Optionally, more details around how it was implemented

Closes #1234
```
* update the description of this PR to include `Closes #xxx`.
  This will help collaboration on GitHub in two ways:
  * it populates the right hand column on both the issue and the PR with a reference to the issue you're about to fix 
  * it will close the issue once the PR has been merge automatically.

All of this allows us to track all changes in the GitHub commit log to the issue on GitHub. 

Please update your PR to align with this. Thanks!

**Comment by ahus1** [comment]
@andymunro - I see that you've been working on the original file recently. 

Please comment here from the perspective of the documentation team if you'd be OK with this change. Thanks!

**Review by andymunro — APPROVED** [review]
Thanks @ahus1. Definitely need to make this correction.

**Comment by stianst** [comment]
Merging without GH issue as it's only a minor spelling fix

**Pull request merged**
