### PR TITLE
[KEYCLOAK-5175] Importing certificate to saml client takes too long

### PR DESCRIPTION
**Pull request by abstractj**
This change it's related with Angular.js upgrade to 1.6.6, It looks like `success` was removed and no longer supported. See this line of code https://github.com/keycloak/keycloak/pull/4780/files#diff-4ef7eace98655aa6aed01f40f9f2379fL437.

@ssilvert besides the changes at the console. I would like you help checking if the tests are not broken on Windows due to the changes [here]( https://github.com/abstractj/keycloak/blob/db3b6830aed7f9164977959f53084080cd92af01/testsuite/integration-arquillian/tests/other/console/src/main/java/org/keycloak/testsuite/console/page/clients/credentials/SAMLClientCredentialsForm.java#L43-L61).

## Instructions to run

```
mvn clean install -Pdistribution -DskipTests && 
cd testsuite/integration-arquillian/tests/other/console && 
mvn clean test -Pconsole-ui-tests -Dtest=ClientSAMLKeysTest -Dbrowser=chrome
```

### CODE REVIEW

**Comment by ssilvert** [comment]
Sorry I missed the notification on this one.  I'll start working on it today.

**Comment by ssilvert** [comment]
BTW, when I did the angularjs upgrade I tried to find all the instances of "success" and fix them.  Not sure how that one got missed, but I apologize.

**Comment by ssilvert** [comment]
What makes you concerned that the tests won't run on Windows?  Are there specific tests I need to concentrate on or do you need me to run everything I can?

**Comment by abstractj** [comment]
@stianst I was chatting with @ssilvert  about this PR, the Angular.js changes are ok. But for some reason tests are passing for me, but not working for @ssilvert locally and it seems unrelated to Windows. 

We need a 3rd environment to run these tests and make sure that everything is ok.

**Comment by stianst** [comment]
Tests works just fine for me

**Pull request merged**
