### PR TITLE
fix label error for persistent-user-sessions feature flag in document…

### LINKED ISSUE #30368: Documentation : fix label typo of persistent-user-sessions feature flag
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

New feature flag `persistent-user-sessions` is missing the trailing `s` in documentation and upgrading guide for Keycloak 25

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Documentation is correct

### Actual behavior

Documentation is not correct

### How to Reproduce?

Start a server with `--features=persistent-user-session` and get this error : 

`persistent-user-session is an unrecognized feature, it should be one of [account-api, account3, admin-api, admin-fine-grained-authz, admin2, authorization, ciba, client-policies, client-secret-rotation, client-types, declarative-ui, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, js-adapter, kerberos, login2, multi-site, oid4vc-vci, organization, par, passkeys, persistent-user-sessions, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn]`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by daviddelannoy**
Closes #30368

### CODE REVIEW

**Comment by daviddelannoy** [comment]
Hi @ahus1 
I think that a `s` is missing in the documentation for the new feature `persistent-user-sessions`

**Review by ahus1 — APPROVED** [review]
Thank you for fixing this, it slipped everyone else's review!

Could you please create the same PR also against the release branch for 25? Thanks!

**Comment by daviddelannoy** [comment]
> Thank you for fixing this, it slipped everyone else's review!
> 
> Could you please create the same PR also against the release branch for 25? Thanks!

no worries, with the starting check in the feature flag list it's easy to get the good value :) 
I am creating the PR against the release branch yes

**Comment by daviddelannoy** [comment]
@ahus1 

I think that I committed too quickly ^^

I could have fixed another typo I guess, please confirm that this sentence here, I'll submit a small PR later : https://github.com/keycloak/keycloak/blob/main/docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc?plain=1#L145 

should be 

The data will be stored in the tables `offline_user_session` and `offline_client_session` with `offline_flag` set to `false`.

**Pull request merged**
