### PR TITLE
KEYCLOAK-18685 Style in product login screen is broken

### PR DESCRIPTION
**Pull request by mabartos**
JIRA: [KEYCLOAK-18685](https://issues.redhat.com/browse/KEYCLOAK-18685)

@Pepo48 @vmuzikar @ssilvert Could you please take a look at it? Thanks.

### CODE REVIEW

**Review by vmuzikar — COMMENTED** [review]
@mabartos Thanks for the fix! Just by a brief look changes LGTM, but please bear in mind I didn't test them as I'm unable to build RH-SSO dist (as we discussed privately). This should be thoroughly tested using the browser dev tools to check if there are really no 404s, and/or if all the added files are really required.

**Comment by ssilvert** [comment]
> @mabartos Thanks for the fix! Just by a brief look changes LGTM, but please bear in mind I didn't test them as I'm unable to build RH-SSO dist (as we discussed privately). This should be thoroughly tested using the browser dev tools to check if there are really no 404s, and/or if all the added files are really required.

Agree with @vmuzikar.  Changes look fine.  You just need to verify with testing.

**Comment by ssilvert** [comment]
@miquelsi Are you able to verify this PR works as it should?

**Comment by mabartos** [comment]
You can test it with my other branch [1], where are included necessary changes, from `keycloak-prod` repository, to properly build product distribution. These changes will be added to the upstream soon. The commit from this PR is cherry-picked on top of the `rhsso75` branch. 

[1] https://github.com/mabartos/keycloak/tree/rhsso75

**Comment by Pepo48** [comment]
After I changed the eap version in the parent pom, the problem with WildFly Galleon Plugin dependency got resolved and I was able to build the distribution. The proposed changes also look good in Internet Explorer:
obrázok

Thanks for the fix and the effort, @mabartos!

**Comment by nehachopra27** [comment]
@mabartos : I am getting correct screen after following the steps in https://docs.google.com/document/d/1slIvYZG6M2Z7LWmxDoCJpHAQUvk7Ul5R3Ov36-bpc10/edit

Screenshot 2021-07-23 at 10 55 06

**Comment by nehachopra27** [comment]
@mabartos : I am getting correct screen after following the steps.

Screenshot 2021-07-23 at 10 55 06

Thanks!

**Comment by ssilvert** [comment]
This seems like something that definitely needs to be in Keycloak 15 and I think we should consider merging now.

Enough people have verified the fix and it's pretty low risk for regression.  Plus, if we merge this it will be formally tested for regressions by QE, right?

@vmuzikar @stianst Do you agree?

**Comment by mabartos** [comment]
@ssilvert Yes, it should be included in Keycloak 15. It'll be properly tested after building the product version. We are not able to execute pipeline tests with this change right now, so we have to test it manually. However, as you've mentioned, enough people have verified this solution fixes the bug.

**Comment by ssilvert** [comment]
@stianst Needs to approve before we can merge.

**Review by pdrozd — APPROVED** [review]

**Review by stianst — APPROVED** [review]

**Pull request merged**
