### PR TITLE
make Carrier-Grade NAT (CGNAT) also allowed

### PR DESCRIPTION
**Pull request by gruppferi**
it is not real PR to merge, if no complain I can make proper PR for it.
this should be basically solve the issues:
[#25881](https://github.com/keycloak/keycloak/discussions/15400)
[#15400](https://github.com/keycloak/keycloak/issues/25881)

### CODE REVIEW

**Comment by pteroctopus** [comment]
We need this to :-)

**Comment by korenlev** [comment]
would resolve https://github.com/keycloak/keycloak/discussions/15400 too

**Comment by pedroigor** [comment]
@gruppferi My only concern is that the range might not be a private address space for some deployments, as per RFC1918 and the implementation of `java.net.Inet4Address#isSiteLocalAddress`.

Based on RFC6598:

```
Shared Address Space is distinct from [RFC 1918](https://datatracker.ietf.org/doc/html/rfc1918) private address space
   because it is intended for use on Service Provider networks.
   However, it may be used in a manner similar to [RFC 1918](https://datatracker.ietf.org/doc/html/rfc1918) private
   address space on routing equipment that is able to do address
   translation across router interfaces when the addresses are identical
   on two different interfaces.  Details are provided in the text of
   this document.
```
It seems to be safe to assume that address space as private but at they same time they are something else :) Perhaps having some option to enable this address space when checking for private address is safer?

**Review by stianst — CHANGES_REQUESTED** [review]
I disagree with this change. SSL should be required in all production cases, and for testing cases you can always set the SSL requirement to none. In addition cookies will require a secure context in the future, which means only localhost or host.localhost would be supported without SSL (see https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts).

**Pull request closed without merging**
