### PR TITLE
KEYCLOAK-9713 Warning in the log during export/import on current master

### PR DESCRIPTION
**Pull request by mposolda**

### CODE REVIEW

**Comment by stianst** [comment]
Would be better to parse it properly than rely on catching an exception

**Comment by mposolda** [comment]
@stianst ok, I wasn't sure if "5.0.0-SNAPSHOT" was a mistake/temporary version, but now I know it is new versioning scheme. Improved parsing a bit rather than relying on catching exception.

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Review by stianst — APPROVED** [review]

**Pull request merged**
