### PR TITLE
[KEYCLOAK-18007] - Configure resolved paths with the method config from configuration

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by sguilhen — DISMISSED** [review]

**Comment by pedroigor** [comment]
@stianst @sguilhen Added test. Sorry, Stefan, I've now included it as you also suggested.

**Review by sguilhen — APPROVED** [review]
Thanks for adding the tests @pedroigor . LGTM

**Comment by stianst** [comment]
This should also be documented, as otherwise no-one will know about it.

I'd like to also know if a wildcard should match only children, or all descendents.

So, basically does "/api/*" match "/api/2" only, or also "/api/2/3" as well. Test-cases should be extended to include this as well.

**Comment by pedroigor** [comment]
> This should also be documented, as otherwise no-one will know about it.
> 
> I'd like to also know if a wildcard should match only children, or all descendents.
> 
> So, basically does "/api/*" match "/api/2" only, or also "/api/2/3" as well. Test-cases should be extended to include this as well.

It matches both. We already have tests covering the scenarios you described and a lot of others. The issue here is not really related to path matching but considering the config set to the path config after resolving the corresponding resource from Keycloak. See https://github.com/keycloak/keycloak/blob/40efbb0f9c4bb5cc756f9dfc67a81b5536291d2a/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/example/authorization/AbstractServletPolicyEnforcerTest.java#L49.

Documentation-wise, the behavior is now aligned with docs. See https://www.keycloak.org/docs/latest/authorization_services/#_enforcer_filter.

**Review by stianst — APPROVED** [review]

**Pull request merged**
