### PR TITLE
redirectUri problem fix.

### LINKED ISSUE #17600: Keycloak js adapter login method problem
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/javascript

### Describe the bug

For `keycloak.init({onLoad: 'login-required'})`, it will replaceState with callback newUrl.
For `keycloack.login()`, it won't.
https://github.com/keycloak/keycloak/blob/main/js/libs/keycloak-js/src/keycloak.js#L246-L250

### Version

20.0.3

### Expected behavior

`keycloak.login()` should replaceState with callback url as well.
The redirect login should be success.

### Actual behavior

`keycloak.login()` won't replaceState with callback url as well.
The redirect login is failed without refresh.

### How to Reproduce?

Call `keycloak.init({onLoad: 'login-required'})` and `keycloack.login()` to see the difference.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SetoKaiba**
Closes #17600

### CODE REVIEW

**Comment by jonkoops** [comment]
@SetoKaiba I am not able to reproduce the issue you mentioned in my [test project](https://github.com/jonkoops/kjs-playground). I [removed](https://github.com/jonkoops/kjs-playground/commit/90171d0eaf1effe71a9c33f57b0612a793c8c8d3) all of the options for the `init()` step and called `.login()` manually and the parameters seem to be removed as expected.

Could you provide me with the minimal steps to reproduce this? Feel free to fork my project and see if you can reproduce the issue there.

**Comment by SetoKaiba** [comment]
> @SetoKaiba I am not able to reproduce the issue you mentioned in my [test project](https://github.com/jonkoops/kjs-playground). I [removed](https://github.com/jonkoops/kjs-playground/commit/90171d0eaf1effe71a9c33f57b0612a793c8c8d3) all of the options for the `init()` step and called `.login()` manually and the parameters seem to be removed as expected.
> 
> Could you provide me with the minimal steps to reproduce this? Feel free to fork my project and see if you can reproduce the issue there.

Here's the step.
1. init({onLoad: 'check-sso'}. I need this option to check the authentication status.
2. Call login.
3. Login within the page.
4. Check the address bar.

**Comment by jonkoops** [comment]
@SetoKaiba I've [updated my commit](https://github.com/jonkoops/kjs-playground/commit/07739c4879732a0f8665f21034d5d8c37452c8b8) to match what you have provided. When I log in the paramaters stay in the URL for a second and are then removed. So this seems to work as expected.

Are you able to reproduce this with my provided example?

**Comment by SetoKaiba** [comment]
Let me have a try with your project to see what's the problem.

**Comment by SetoKaiba** [comment]
@jonkoops I try your project. But I'm on windows and I can't run it.
I try to reproduce it of my own project and have video recording. But it seems that I can't reproduce it. Previously, when I use check-sso and it fails, my address bar will follow the `#error=login-required&state=xxxx`. But it doesn't now. I don't know why. If no `#error=login-required&state=xxxx` after the check-sso. The bug won't be reproduced.

**Comment by jonkoops** [comment]
Thanks for checking this @SetoKaiba. I am considering this as unreproducible at this time, so I'll go ahead and close this PR and the associated issue. If someone does manage to reproduce this issue feel free to let us know.

**Comment by jonkoops** [comment]
If the extension is the cause then I would recommend disabling it.

**Comment by jonkoops** [comment]
I am sorry, but I think that it doesn't make sense to merge fixes for things that are getting broken by a browser extension. I'd recommend logging an issue for the browser extension instead. Alternatively you can disable CORS entirely for Chrome by passing the [--disable-web-security](https://alfilatov.com/posts/run-chrome-without-cors/) flag during testing.

**Pull request closed without merging**
