### PR TITLE
Remove support for IE

### LINKED ISSUE #11268: Remove support for IE
### Description

As we don't support Internet Explorer anymore, we can remove the related changes to that. It's mainly related to the `login.css` file, where the browser doesn't support variables in the CSS files and it was needed to hardcoded values there for IE.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
Closes #11268

I'll execute the pipeline tests.

Also after these changes, the alert is slightly changed.

Old alert:
brokenAlerts

New alert:
verificationNem

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]
Always a fan of removing anything related to Internet Explorer.

**Comment by jonkoops** [comment]
Is this decision made only for certain parts of the application or are we officially dropping support for Internet Explorer everywhere (login, other uis, adapters, etc)?

**Review by edewit — APPROVED** [review]
:+1:

**Comment by Pepo48** [comment]
> Is this decision made only for certain parts of the application or are we officially dropping support for Internet Explorer everywhere (login, other UIs, adapters, etc)?

@jonkoops afaik we completely dropped support for IE/old Edge with the 7.5.0 (which translates to Keycloak 15 if I'm not mistaken). This is a clean-up of leftovers 😊 .

**Comment by jonkoops** [comment]
Great! I've been meaning to clean up some code, but browser support was always an issue. Only problem is that we still use PhantomJS for a lot of the tests which is a horrible system that breaks whenever you try to introduce something new.

**Comment by mabartos** [comment]
I think the execution of the pipeline tests is not necessary as there's no change in some "logic", only changes in CSS files. I verified the possibly affected screens and everything seems fine.

Is it necessary to mention this in the release notes? It'd be good to have it included already in the KC 18.

**Review by ssilvert — APPROVED** [review]
LGTM

**Review by Pepo48 — APPROVED** [review]
I forgot to submit my review 😊  LGTM, thanks @mabartos!

**Comment by stianst** [comment]
Removing IE support is most likely fine at this point, but would be better to wait until after Keycloak 18 is released as it seems IE is still supported until June 15, 2022.

**Pull request merged**
