### PR TITLE
KEYCLOAK-9053 KEYCLOAK-9818 Increase column size for federated foreig…

### PR DESCRIPTION
**Pull request by vramik**
…n keys

### CODE REVIEW

**Comment by hmlnarik** [comment]
@vramik Has the pipeline been run on this PR?

**Comment by vramik** [comment]
@hmlnarik yes, but there is a lot of failures and it's hard to distinguish what failures are related to the PR:

- https://keycloak-jenkins.com/job/universal-test-pipeline-server/1218/
- https://keycloak-jenkins.com/view/vramik/job/universal-test-pipeline-adapters/1011/

**Comment by vramik** [comment]
@hmlnarik it should be ready for review. 

https://keycloak-jenkins.com/job/test-keycloak-jpa/146/

**Review by hmlnarik — APPROVED** [review]
Thanks @vramik !

**Pull request merged**
