### PR TITLE
KEYCLOAK-1906 : Customized LDAP filter

### PR DESCRIPTION
**Pull request by mkdgit**
This functionality gives a possibility to query LDAP with user provided filter in User Federation Mappers -> Role Mappings mapper type.

### CODE REVIEW

**Comment by stianst** [comment]
Have you written to the Keycloak dev mailing list about this? Also is there an associated JIRA issue?

**Comment by mkdgit** [comment]
No, I have not. Should I ? This is a functionality that I need and it is worth to share. This is not related to any issue.

**Comment by stianst** [comment]
We need a JIRA so we can track what features/bugs/etc are added, so we definitively need that. It's also generally a good idea to write to the Keycloak dev mailing list as well, but you don't need to this time around.

**Comment by mkdgit** [comment]
Ok, what should I do next? Should I create some feature in JIRA? Can I get a link ?

**Comment by stianst** [comment]
https://issues.jboss.org/browse/KEYCLOAK

**Comment by mkdgit** [comment]
Ok, issue created. https://issues.jboss.org/browse/KEYCLOAK-1906

**Pull request merged**
