### PR TITLE
KEYCLOAK-7855 Cannot reset Client Consent Screen Text

### PR DESCRIPTION
**Pull request by mposolda**

### CODE REVIEW

**Review by stianst — DISMISSED** [review]

**Comment by mposolda** [comment]
Will be probably better to wait with merging this after https://github.com/keycloak/keycloak/pull/5602 is merged and cherry-pick on top of it. I am not 100% sure if there won't be test conflicts...

**Comment by mposolda** [comment]
@stianst @vmuzikar Done the rebase on top of https://github.com/keycloak/keycloak/pull/5602 . Everything should be fine and tests passing.

**Comment by stianst** [comment]
@keycloak-ci-bot test

**Review by vmuzikar — APPROVED** [review]
LGTM. Thanks!

**Review by stianst — APPROVED** [review]

**Pull request merged**
