### PR TITLE
[KEYCLOAK-3169] - UMA 2.0

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by tiny-dancer** [comment]
@pedroigor really looking forward to this one! is there anywhere to track an associated release?

**Comment by pedroigor** [comment]
Yeah, @tiny-dancer. Please, check https://issues.jboss.org/browse/KEYCLOAK-3169.

We don't have yet a decision about the release that we are going to push all these changes. The main discussions are around usability and backward compatibility.

Right now, the changes in this PR are providing:

* UMA 2.0 Grant Type
* Enable users to manage their resources, grant/deny/revoke access, via Account Service
* Enable/Disable Permission Tickets on a per-resource basis
* Additions to Permission REST API in order to allow managing permission tickets. So users could create their own UIs to manage users permission requests. 

There are much more to be done though:

* Review Entitlement API and make it an extension of UMA Grant Type instead of a separated endpoint
* Allow resource servers to push claims via permission tickets and allow policies to make decisions based on contextual data provided by resource servers
* Finish additions to Permission REST API

Any feedback is welcome about what we have so far.

**Comment by tiny-dancer** [comment]
@pedroigor thanks for the response, we're just starting to look into keycloak + uma. it's a great project and hope to contribute back/provide feedback in due time.

**Comment by ror6ax** [comment]
Hi guys, any chance this work can be shared with some more people? @tiny-dancer @pedroigor  From what I can see in Jira, there's quite a lot of components to it. If someone can provide a bit more technically detailed write-up, I'd be interested to help.

**Comment by Trojan295** [comment]
I tried to make a build from this branch. Tests are failing, but this is caused by a different issue  (PR for it was merged #4460). I will try to play with it and check compliance with UMA 2.0 specs.

**Comment by ror6ax** [comment]
Hi @stianst ,will this be in 4.0.0 Final or later?

**Comment by stianst** [comment]
It can be included whenever @pedroigor is happy with it

**Comment by tristola** [comment]
Any updates on if or when this will be merged?

**Comment by m-wcislo** [comment]
Same here, any rough estimates available?

**Comment by blazejkw** [comment]
Hello guys,

is there any chance that it will be merged into 4.x ? 

Regards,

**Comment by pedroigor** [comment]
Hello All, it will be included in 4.x. We are probably going to split this PR in two:

* Deprecation of both Entitlement and Authorization API, UMA Grant Type, Permission Ticket Management and other internals
* Account Service changes

Our next spring is planned to end on February 9th. We should have the first part in until there.

**Comment by m-wcislo** [comment]
Hi,
I was playing a bit with your branch @pedroigor and found out that it is possible to access all registered resources in account service by simply adding resource id to the /account/resource/{resource id} path no matter if you own/share this resource which seems like a bug. We can assume that guessing resource id is hard, but in the scenario when the resource was shared and then revoked, user could possibly share the resource on its own or back to itself (after revoke).

**Comment by pedroigor** [comment]
@m-wcislo, that is certainly something we need to avoid. Did not notice that in this initial implementation. Will fix that.

What are your thoughts on the overall solution and changes to Account Service ? There are other things we can do there, for sure, but as an initial version I would like to start with something around you tested. 

Other things we might do are:

* Users should be able to specify expiration constraints to their permissions. E.g.: I want this granted permission to be automatically revoked at some time.

*  Users should be able to check the when a resource was last accessed

* Users should receive notifications (e.g.: via e-mail) about permission requests or when a resource is granted by resource owner. This will also probably include support for customizing the e-mail, etc.

Any more thing you think we should consider ?

**Comment by m-wcislo** [comment]
Hi,
I'm not that experienced with Keycloak code, so it's hard to give any meaningful opinion about the programming part. Solution itself is great and would save me from policy/permission cha-cha (grant-revoke-grant) to mimic UMA2.0 :) .

As for functional part first thing that comes to my mind are audit capabilities on resource usage by other users (Events) would be great, but I assume it is not considered in those first steps. Also small thing - it would be nice to stay on the resource-detail page after completing share or revoke, which is what is there in other parts of Keycloak as far as I noticed. It would be useful if user wants to share (revoke) with more users at once.

Also, I bumbed into another issue: when you revoke share for one user it is revoked for all shares withing same resource.

Currently I'm testing UMA2.0 grant flow, I'm able to get permissions but only when policy/permission is there explicitly for the other user not when shared by owner. From  [https://issues.jboss.org/browse/KEYCLOAK-3169](https://issues.jboss.org/browse/KEYCLOAK-3169) looks like policy/permission part was not considered yet? Or do I need to create some special policy to make it work only based on grant?

**Comment by pedroigor** [comment]
@m-wcislo , thanks again for the feedback.

I'll take a look at the issues you mentioned: resource-detail UI and revocation. 

Regarding your last question, I think I have considered that in the initial design. If not working it should be an issue.

I just rebased this PR and I'll start now running the tests I wrote to see if things are at least working as before. Then I'm going to start looking the issues you mentioned.

Like I said, I would like to send separated PRs instead of a big one like this. Will see how we'll handle that during the next days. I may be closing this PR at any time.

**Comment by pedroigor** [comment]
@stianst @sguilhen this one is ready for review and merge.

**Review by sguilhen — APPROVED** [review]
Huge changelog but it looks good to me!

**Comment by stianst** [comment]
QuickStarts:
https://github.com/keycloak/keycloak-quickstarts/pull/98

Documentation:
https://github.com/keycloak/keycloak-documentation/pull/325

**Comment by chicco785** [comment]
hi all,
any update on this feature? thx :)

**Comment by mhajas** [comment]
@pedroigor Hi, I checked tests and I found out, that test is failing AbstractPhotozExampleAdapterTest#testClientRoleRepresentingUserConsent:391. Seems like it is caused by wrongly adding scope parameter to url. The test is relying [1] on having the scope query parameter as last in url and simply add "%20photoz-restful-api/manage-albums" at the end. While at the moment the last parameter is nonce. This means the scope parameter is not added. 

[1] https://github.com/pedroigor/keycloak/blob/88b68958618cef7bbbb45728957dbd5b0da211ec/testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/adapter/page/PhotozClientAuthzTestApp.java#L151

**Comment by mhajas** [comment]
The other failing test is AbstractServletAuthzFunctionalAdapterTest#testAccessPublicResource which is failing because after redirecting to public resource user is redirected to login page.

**Comment by pedroigor** [comment]
@mhajas, ```AbstractPhotozExampleAdapterTest#testClientRoleRepresentingUserConsent``` is fixed.

Regarding the second one, do we have any other test in testsuite that is using a web.xml with a public security-contraint (no roles) ?

**Comment by pedroigor** [comment]
@mhajas, failing tests should be OK now.

**Review by mhajas — APPROVED** [review]
@pedroigor Tests are OK now, thanks.

**Comment by ror6ax** [comment]
Patiently chewing popcorn while waiting for this to get merged ;)
Alt Text

**Review by stianst — DISMISSED** [review]
Approving without review

**Comment by pedroigor** [comment]
@stianst, I'm about to merge this PR but I noticed that crossdc tests are being run after rebasing my branch.

Any other PR in the queue is skipping crossdc tests, wondering why mine is triggering them ....

**Comment by pedroigor** [comment]
@stianst, think I figured out why. Because of the diff (see ```.travis-run-tests.sh```) crossdc is being triggered due to changes in infinispan related classes.

**Comment by stianst** [comment]
Looks like the test is plain broken and that it doesn't have anything to do with this PR

**Comment by mposolda** [comment]
Just checked that the test is broken because of this commit from different PR: https://github.com/keycloak/keycloak/commit/d70e4740fcde822588891266f7f8723702313e80 . I've created JIRA for that: https://issues.jboss.org/browse/KEYCLOAK-6772

It's unrelated to this PR. My vote is to merge this.

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
OK, I'm going to use the squash and merge option to get it in as one commit

**Comment by ror6ax** [comment]
Hi guys. When is your next release scheduled?

**Pull request merged**
