### PR TITLE
Add Chinese translation for email verification page

### PR DESCRIPTION
**Pull request by megamorf**
These translations were provided by our customer and are approved for publishing.

This change includes the following constants:

```
expiredActionMessage=Action expired. Please continue with login now.
expiredActionTokenNoSessionMessage=Action expired.
expiredActionTokenSessionExistsMessage=Action expired. Please start again.
resetPasswordMessage=You need to change your password.
confirmExecutionOfActions=Perform the following action(s)
requiredAction.terms_and_conditions=Terms and Conditions
requiredAction.UPDATE_PASSWORD=Update Password
requiredAction.UPDATE_PROFILE=Update Profile
requiredAction.VERIFY_EMAIL=Verify Email
proceedWithAction=Click here to proceed
```
The most important change is that during email verification process a localized Chinese screen is shown to the user instead of using the English fallback:

image

There still is a noticeable disparity between the core English and community translations, e.g. CN (red) vs EN (green):

```diff
diff --git a/cn.keys b/en.keys
index a0e4a28..a682a76 100644
--- a/cn.keys
+++ b/en.keys
@@ -5,6 +5,7 @@ doSubmit
 doYes
 doNo
 doContinue
+doIgnore
 doAccept
 doDecline
 doForgotPassword
@@ -14,8 +15,7 @@ kerberosNotConfigured
 kerberosNotConfiguredTitle
 bypassKerberosDetail
 kerberosNotSetUp
-registerWithTitle
-registerWithTitleHtml
+registerTitle
 loginTitle
 loginTitleHtml
 impersonateTitle
@@ -34,9 +34,14 @@ emailForgotTitle
 updatePasswordTitle
 codeSuccessTitle
 codeErrorTitle
+displayUnsupported
+browserRequired
+browserContinue
+browserContinuePrompt
+browserContinueAnswer
 termsTitle
-termsTitleHtml
 termsText
+termsPlainText
 recaptchaFailed
 recaptchaNotConfigured
 consentDenied
@@ -63,10 +68,29 @@ postal_code
 country
 emailVerified
 gssDelegationCredential
+profileScopeConsentText
+emailScopeConsentText
+addressScopeConsentText
+phoneScopeConsentText
+offlineAccessScopeConsentText
+samlRoleListScopeConsentText
+rolesScopeConsentText
+loginTotpIntro
 loginTotpStep1
 loginTotpStep2
 loginTotpStep3
+loginTotpManualStep2
+loginTotpManualStep3
+loginTotpUnableToScan
+loginTotpScanBarcode
 loginTotpOneTime
+loginTotpType
+loginTotpAlgorithm
+loginTotpDigits
+loginTotpInterval
+loginTotpCounter
+loginTotp.totp
+loginTotp.hotp
 oauthGrantRequest
 inResource
 emailVerifyInstruction1
@@ -76,9 +100,14 @@ emailLinkIdpTitle
 emailLinkIdp1
 emailLinkIdp2
 emailLinkIdp3
+emailLinkIdp4
+emailLinkIdp5
 backToLogin
 emailInstruction
 copyCodeInstruction
+pageExpiredTitle
+pageExpiredMsg1
+pageExpiredMsg2
 personalInfo
 role_admin
 role_realm-admin
@@ -98,6 +127,7 @@ role_manage-clients
 role_manage-events
 role_view-profile
 role_manage-account
+role_manage-account-links
 role_read-token
 role_offline-access
 client_account
@@ -110,6 +140,9 @@ invalidEmailMessage
 accountDisabledMessage
 accountTemporarilyDisabledMessage
 expiredCodeMessage
+expiredActionMessage
+expiredActionTokenNoSessionMessage
+expiredActionTokenSessionExistsMessage
 missingFirstNameMessage
 missingLastNameMessage
 missingEmailMessage
@@ -118,6 +151,7 @@ missingPasswordMessage
 missingTotpMessage
 notMatchPasswordMessage
 invalidPasswordExistingMessage
+invalidPasswordBlacklistedMessage
 invalidPasswordConfirmMessage
 invalidTotpMessage
 usernameExistsMessage
@@ -131,12 +165,17 @@ confirmLinkIdpContinue
 configureTotpMessage
 updateProfileMessage
 updatePasswordMessage
+resetPasswordMessage
 verifyEmailMessage
 linkIdpMessage
 emailSentMessage
 emailSendErrorMessage
 accountUpdatedMessage
 accountPasswordUpdatedMessage
+delegationCompleteHeader
+delegationCompleteMessage
+delegationFailedHeader
+delegationFailedMessage
 noAccessMessage
 invalidPasswordMinLengthMessage
 invalidPasswordMinDigitsMessage
@@ -146,6 +185,7 @@ invalidPasswordMinSpecialCharsMessage
 invalidPasswordNotUsernameMessage
 invalidPasswordRegexPatternMessage
 invalidPasswordHistoryMessage
+invalidPasswordGenericMessage
 failedToProcessResponseMessage
 httpsRequiredMessage
 realmNotEnabledMessage
@@ -183,6 +223,10 @@ realmSupportsNoCredentialsMessage
 identityProviderNotUniqueMessage
 emailVerifiedMessage
 staleEmailVerificationLink
+identityProviderAlreadyLinkedMessage
+confirmAccountLinking
+confirmEmailAddressVerification
+confirmExecutionOfActions
 locale_ca
 locale_de
 locale_en
@@ -192,15 +236,41 @@ locale_it
 locale_ja
 locale_nl
 locale_no
+locale_pl
 locale_pt_BR
 locale_pt-BR
 locale_ru
 locale_lt
 locale_zh-CN
+locale_sk
+locale_sv
 backToApplication
 missingParameterMessage
 clientNotFoundMessage
 clientDisabledMessage
 invalidParameterMessage
 alreadyLoggedIn
+differentUserAuthenticated
+brokerLinkingSessionExpired
+proceedWithAction
+requiredAction.CONFIGURE_TOTP
+requiredAction.terms_and_conditions
+requiredAction.UPDATE_PASSWORD
+requiredAction.UPDATE_PROFILE
+requiredAction.VERIFY_EMAIL
 p3pPolicy
+doX509Login
+clientCertificate
+noCertificate
+pageNotFound
+internalServerError
+console-username
+console-password
+console-otp
+console-new-password
+console-confirm-password
+console-update-password
+console-verify-email
+console-email-code
+console-accept-terms
+console-accept
```

The diff was created with:

```bash
egrep -v "^\s*($|#)" messages_en.properties | awk -F'=' '{print $1}' > en.keys
egrep -v "^\s*($|#)" messages_zh_CN.properties | awk -F'=' '{print $1}' > cn.keys
git diff --no-index cn.keys en.keys >> cn-to-en.diff
```

### CODE REVIEW

**Comment by megamorf** [comment]
@stianst What does the Hold label stand for?

**Comment by megamorf** [comment]
@stianst when will this be merged?

**Comment by stianst** [comment]
Please ask on Keycloak dev and user mailing lists if anyone can review this. We require someone from the community to review translations prior to merging.

**Comment by stianst** [comment]
Closing due to lack of review by the community. Please ask for a volunteer to review on the dev and user mailing lists, resolve the merge conflict and re-open the PR after that.

**Pull request closed without merging**
