### PR TITLE
Stabilize the quarkus-next build stage

### LINKED ISSUE #27683: Quarkus-next build failure: Could not find artifact io.quarkus:quarkus-extension-maven-plugin
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

In order to stabilize the quarkus-next branch nightly builds, we need to prevent a failure during the CI workflow build stage. It happens because of the io.quarkus:quarkus-extension-maven-plugin:jar:999-SNAPSHOT artifact is not being found [1].

Based on a local analysis, adding the Quarkus Sonatype Snapshots repository as a plugin repository could solve the problem.

[1] https://github.com/keycloak/keycloak/actions/runs/8180607544/job/22390615429

### Version

upstream/main

### Regression

- [ ] The issue is a regression

### Expected behavior

Quarkus-next nigthly workflow build success.

### Actual behavior

https://github.com/keycloak/keycloak/actions/runs/8180607544/job/22390615429

### How to Reproduce?

Run the current quarkus-next branch.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Pepo48**
* edited prepare-quarkus-next.sh in order to add the Quarkus nightly snapshot repository as a plugin repository to avoid multiple "artifacts are not being found" failures

Closes #27683

### CODE REVIEW

**Comment by vmuzikar** [comment]
@Pepo48 Thanks for the PR! Do you have a link to a test run with these changes?

**Comment by Pepo48** [comment]
@vmuzikar here you go:
* [CI](https://github.com/Pepo48/keycloak/actions/runs/8205682896)
* [Operator CI](https://github.com/Pepo48/keycloak/actions/runs/8205682772)

The initial aim of this PR was to stabilize the build phase, yet there seem to be (possibly related) issues, which caused the Operator CI tests to fail. I can either try to fix it as a part of this PR or I can do a follow-up.

**Review by vmuzikar — APPROVED** [review]

**Review by vmuzikar — CHANGES_REQUESTED** [review]
After discussing further offline with @Pepo48 we agreed on fixing the Operator build as part of this PR.

**Review by vmuzikar — APPROVED** [review]
@Pepo48 Thank you, I like the clean up. LGTM.

**Pull request merged**
