### PR TITLE
KEYCLOAK-5434: Dbl-refresh on FF causes error if use hash routing

### PR DESCRIPTION
**Pull request by ssilvert**

### CODE REVIEW

**Comment by ssilvert** [comment]
This is not ready to merge.  I want to make sure we run this through whatever tests are available with as many browsers as possible.

**Comment by stianst** [comment]
pushState adds additional elements to the history which is why it used replaceState, so not sure this is the correct fix.

**Comment by ssilvert** [comment]
> pushState adds additional elements to the history which is why it used replaceState, so not sure this is the correct fix.

I want to be sure as well.  This is why I've been very hesitant to make the change without some really thorough testing.  I've played around with it quite a bit and haven't been able to detect any problems.

Is there some specific scenario that you suspect might not work with pushState?

**Comment by ssilvert** [comment]
This was resolved by KEYCLOAK-9050.

**Pull request closed without merging**
