### PR TITLE
Tweak the default memory request and limit in the Operator

### LINKED ISSUE #27169: Tweak the default memory request and limit in the Operator
### Description

This is a follow-up from https://github.com/keycloak/keycloak/pull/26661.

Based on the test results, we estimated that Keycloak needs ~300 MiB non-heap memory. This seems to be long term more or less stable regardless of other factors. Based on discussion with @ahus1 we estimated that for a smaller production ready deployments 1.4 GiB heap memory should be sufficient. From that, the following was calculated:
* Limit: 2 GiB
* Request: 1.7 GiB = 70% of limit (as specified by the JVM args) for heap + 300 MiB for non-heap memory

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes #27169

CC @mabartos

### CODE REVIEW

**Comment by ahus1** [comment]
@vmuzikar - please update the docs which are referencing the default values. 

Those are to my knowledge:  `advanced-configuration.adoc`, `changes-24_0_0.adoc`, `24_0_0.adoc`.

**Review by shawkins — APPROVED** [review]
LGTM

**Comment by ahus1** [comment]
@vmuzikar - consider it resolved, I see that the change was now force-pushed. Thanks!

**Comment by vmuzikar** [comment]
@ahus1 Can I ask you for your green tick so we can merge after @mabartos' approval? :)

**Review by ahus1 — APPROVED** [review]

**Review by mabartos — APPROVED** [review]
If the KCB inferred these values for some reasonable production-ready env for Keycloak, I'm ok with this. As we provide the ability to easily change these values to meet the users' requirements, I don't see a problem here.  

@vmuzikar @ahus1 Thanks for the further analysis and discussion!

**Pull request merged**
