### PR TITLE
KEYCLOAK-17284 Evaluate ID-Token and UserInfo-Endpoint

### PR DESCRIPTION
**Pull request by danielFesenmeyer**
KEYCLOAK-17284 Evaluate ID-Token and UserInfo-Endpoint:

- add additional REST endpoints for evaluation:
  - for ID Token: GET /realm/clients/id/evaluate-scopes/generate-example-id-token
  - for UserInfo-Endpoint: GET /realm/clients/id/evaluate-scopes/generate-example-userinfo
- extend UI: add additional tabs "Generated ID Token" and "Generated User Info" to the client scopes evaluation screen

Related documentation PR: https://github.com/keycloak/keycloak-documentation/pull/1140

### CODE REVIEW

**Comment by mposolda** [comment]
@danielFesenmeyer Your PR looks good to me. Thanks for your work! I am just running the admin console tests in our internal pipeline to make sure there is not regression in the admin console (Default GH action tests don't run admin console tests).

**Comment by mposolda** [comment]
@danielFesenmeyer Do you please have a chance to rebase this on top of latest master?

I see there are some admin console tests failing, and I am not 100% sure if it is a regression of your PR or not. The test errors are like this:
```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientClientScopesTest.testEvaluateClientScopes:158 Expected: [uma_authorization], was: [default-roles-test, uma_authorization]: array lengths differed, expected.length=1 actual.length=2
[ERROR]   DefaultRolesTest.defaultRoleAssignedToNewUser:60
[ERROR] Errors: 
[ERROR]   DisableAuthorizationSettingsTest.testDisableAuthorization:40->AbstractConsoleTest.assertAlertSuccess:134 » ElementClickIntercepted
[INFO] 
[ERROR] Tests run: 183, Failures: 2, Errors: 1, Skipped: 5
```

For example the `DefaultRolesTest` can be a regression of your PR, as it seems to not fail in latest master (but not really 100% sure it is regression). Maybe rebase will help.

If you have a chance to try admin console tests on your laptop, there are some hints in testsuite/integration-arquillian/HOW-TO-RUN.md on how to run them with FF or Chrome browser.

**Comment by danielFesenmeyer** [comment]
@mposolda Thanks for the hints, I will rebase and check the tests.

**Comment by danielFesenmeyer** [comment]
Hi Marek,

after rebase, the DefaultRolesTest no longer fails.

The following tests are still failing - this was my local test result:
```
[ERROR] Failures: 
[ERROR]   ClientClientScopesTest.testSetupClientScopes:101 Expected: [email, role_list], was: [email]: array lengths differed, expected.length=2 actual.length=1; arrays first differed at element [1]; expected:<role_list> but was:<end of array>
[ERROR] Errors: 
[ERROR]   DisableAuthorizationSettingsTest.testDisableAuthorization:44 » ElementClickIntercepted
[INFO] 
[ERROR] Tests run: 185, Failures: 1, Errors: 1, Skipped: 5
```

I checked those tests and I'm pretty sure that those failures are not related to this PR.

**Review by mposolda — APPROVED** [review]
@danielFesenmeyer Thanks for the rebase! Same tests are failing in our CI, so this is not a regression. Thanks!

**Pull request merged**
