### PR TITLE
Fix compilation errors with Eclipse Java compiler

### LINKED ISSUE #13145: Keycloak fails to compile with Eclipse Compiler
### Describe the bug

I'm using JDT / Eclipse Java Compier to compile Keycloak in vscode. Compiling fails in main branch.

### Version

main

### Expected behavior

_No response_

### Actual behavior

Following errors happen:

**Error 1**: `Cannot refer to 'this' nor 'super' while explicitly invoking a constructor`

https://github.com/keycloak/keycloak/blob/30b41d02b4595677772e80699a12e0359cb89fca/services/src/main/java/org/keycloak/protocol/oidc/OIDCClientSecretConfigWrapper.java#L223

**Error 2**: `The method myMethod(Map<String,String>) in the type App is not applicable for the arguments (Map<Object,Object>)`

https://github.com/keycloak/keycloak/blob/30b41d02b4595677772e80699a12e0359cb89fca/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/events/AuthenticationSessionAuthNoteUpdateEvent.java#L121-L125

**Error 3**: `Type mismatch: cannot convert from Map<Object,Object> to HashMap<String,String>`

https://github.com/keycloak/keycloak/blob/30b41d02b4595677772e80699a12e0359cb89fca/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/SessionEntityWrapper.java#L194

### How to Reproduce?

Open Keycloak in vscode. 
Likely the same errors also happen on Eclipse.

### Anything else?

The syntax is likely correct and Eclipse compiler is wrong. Following issues are submitted on these errors:

* Inner classes using lambdas in super calls difference between javac https://bugs.eclipse.org/bugs/show_bug.cgi?id=564263
* ECJ error due to type inference problem with generic method https://github.com/eclipse-jdt/eclipse.jdt.core/issues/224

It would still be nice to apply workarounds to Keycloak since it would be far more difficult to fix the compiler.

### PR DESCRIPTION
**Pull request by tsaarni**
This change allows compiling Keycloak with Eclipse JDT Java compiler by working around (likely) compiler bugs described in the linked issue.

Fixes #13145

### CODE REVIEW

**Comment by pedroigor** [comment]
@tsaarni Thanks for your time on this. 

The problem doing this is that we now need too consider building using JDT compiler when making changes to the code base. The risk of breaking again is still here and potentially high.

@stianst I'm not sure if we want to include this one?

**Comment by tsaarni** [comment]
So far this was the only place compilation did not work for me. Alternative way to think about this could be that users of vscode and eclipse will find and fix the problems, but nobody still guarantees that new changes would work with JDT out of the box.

I can only wish vscode used JDK instead of using eclipse compiler.... :/

**Comment by pedroigor** [comment]
@tsaarni Yeah ... I'm closing this one for now. Thanks for your interest on making it work on VSCode. Perhaps you can send another PR, if you want, to our contributor guidelines about this limitation. See https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md.

**Comment by hmlnarik** [comment]
@pedroigor I was in the midst of reviewing this PR  while it was closed. The changes are correct, and fix JDK compiler warnings as well, not only fix perhaps more strict Eclipse compiler.
I am in favor of including these changes. Any objections?

**Comment by pedroigor** [comment]
I think the reasons are outlined in my comments. I'm not hard on it but we just can't make any guarantee it won't break again.

**Review by hmlnarik — APPROVED** [review]
@tsaarni Thank you for the PR!

**Pull request merged**
