### PR TITLE
KEYCLOAK-18128 Keycloak cannot fetch group claims from openshift

### PR DESCRIPTION
**Pull request by vmuzikar**

### CODE REVIEW

**Comment by vmuzikar** [comment]
@Pepo48 Could you please review, mainly from the test perspective?

**Comment by iam-veeramalla** [comment]
Hi @vmuzikar , I will be happy to test this, Do u have a build for this ?

**Comment by iam-veeramalla** [comment]
Hi @vmuzikar , I tested this changes and they work for me. 

I have configured our application([Argo CD](https://argo-cd.readthedocs.io/en/stable/)) to use Keycloak as an Identity Broker and OpenShift-V4 as Identity Provider. 

I was able to fetch the OCP groups information related to user and use them in our application to configure some RBAC policies. 

Attaching the screenshots for reference.
keycloak_user_attributes
ocp_groups_keycloak

**Comment by Pepo48** [comment]
> @Pepo48 Could you please review, mainly from the test perspective?

@vmuzikar of course, I will take a look at it today.

@iam-veeramalla thanks for the additional info regarding the testing.

**Review by pedroigor — APPROVED** [review]

**Comment by Pepo48** [comment]
@iam-veeramalla jfyi regarding the progress - I manually tested the PR's functionality yesterday, I still have some issues with running the tests though. I discussed it with @vmuzikar earlier today it seems that the problem is related to my environment, but I still need to investigate it a little bit more. Hopefully I will be able to approve the PR from QE perspective on Monday.

**Comment by vmuzikar** [comment]
jFTR, I created an [internal JIRA](https://issues.redhat.com/browse/KEYCLOAK-19296) to track required changes in our OCP test cluster.

**Comment by iam-veeramalla** [comment]
> jFTR, I created an [internal JIRA](https://issues.redhat.com/browse/KEYCLOAK-19296) to track required changes in our OCP test cluster.

@vmuzikar So this will be merged after making the changes to the test cluster and verifying it there ?

**Comment by vmuzikar** [comment]
@iam-veeramalla This will be merged once @Pepo48 has approved. :) The automated testing in our cluster is a follow-up.

**Comment by Pepo48** [comment]
@iam-veeramalla there were just issues mainly with my environment - at first with the certificates in the local truststore did not reflect the certs at OCP side correctly and then there were a slight misconfiguration with regards to OCP OAuth client.

After a discussion with @vmuzikar I was able to resolve everything and I successfully ran the tests. Therefore I'm approving these changes - the PR can be safely merged from the QE PoV. Thanks Vašek!

**Pull request merged**
