### PR TITLE
KEYCLOAK-9346 Add new KeycloakPromise to support native promises

### PR DESCRIPTION
**Pull request by jonkoops**
This PR introduces a new type of promise called `KeycloakPromise` that replaces our existing promise implementations. It's a special class that extends native promises and implements the `.success()` and `.error()` methods that our users are familiar with to provide backwards compatibility.

The changes made in this PR should allow us to migrate fully to native promises without breaking backwards compatibility with existing code out in the wild. This also means that the previous `promiseType` strategy of supporting native promises and it's migration strategy is no longer needed and has been removed.

Notable changes:
- `promiseType` has been removed as it is obsolete with the introduction of `KeycloakPromise`
- `.error()` and `.success()` methods have been deprecated, a deprecation warning will be logged to the user when they are used.
- A Promise polyfill has been included by default when using the static version of the script. When built with tools such as WebPack the user needs include their own polyfill.
- In case there are no Promises available a hard error will be thrown instructing the user to include a Polyfill.
- All methods have been refactored internally to use standard promise methods

I've manually tested this PR on the latest version of Chrome, Firefox and Internet Explorer. Both using a simple static server use-case and one with WebPack as a build system.

### CODE REVIEW

**Comment by jonkoops** [comment]
As for the failing tests, I would really appreciate it it someone could help me out fixing them.

**Comment by stianst** [comment]
@mhajas would you be able to give @jonkoops some guidance with the failing tests?

**Comment by jonkoops** [comment]
Thanks @stianst. Yeah, I am unable to run the tests locally. Some help would be appreciated.

**Comment by stianst** [comment]
@jonkoops I'm sorry, but I didn't find time to look into this before we got to the feature freeze for 9.0.0. As it's a bit risky I would like to postpone this to after 9 is released. Hope that's okay with you.

**Comment by jonkoops** [comment]
@stianst No problem, I wasn't expecting to get this in before version 9.0.0. It would be nice if we could ship this with version 10.0.0, if capacity is available of course.

**Review by stianst — DISMISSED** [review]

**Comment by stianst** [comment]
There's been a few bugs reported against keycloak.js where it doesn't work if native promises are enabled. Makes me think that we should just get this stuff included. I tried it out and seems to work fine.

**Review by mhajas — CHANGES_REQUESTED** [review]
Thank you for the fix @jonkoops, it looks awesome, finally we will get rid of these legacy promises. I was able to fix the tests and also I added one new for testing success and error methods. Could you please incorporate? https://github.com/mhajas/keycloak/commit/5ce0139e3b81f315795a59e7173b629df94059c1

**Comment by jonkoops** [comment]
@mhajas I've cherry-picked your commit into mine and rebased the PR with master.

**Comment by jonkoops** [comment]
Tests have passed :tada: Thanks for the help @mhajas!

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
Added a docs update for this:
https://github.com/keycloak/keycloak-documentation/pull/863

**Review by mhajas — APPROVED** [review]
Thank you @jonkoops, LGTM!

**Pull request merged**
