### PR TITLE
Get admin console title from theme.properties

### LINKED ISSUE #19733: Page title hard-coded in new admin console.
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

The page title, "Keycloak Administration UI" is hard-coded in index.ftl/index.html.

At the very least, we should allow the user to change this in theme.properties.  Ideally, it should be localized.

### Version

main

### Expected behavior

Not hard-coded

### Actual behavior

hard-coded

### How to Reproduce?

There is no good way to change the title of the page.  The only way currently is to replace index.ftl.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ssilvert**
Fixes #19733

Now, you can change the title of the admin console by creating a new theme that only includes a simple themes.properties that looks like this:
```
parent=keycloak.v2
title=My Cool Title
```
Just put the themes.properties file in themes/mytheme/admin

### CODE REVIEW

**Comment by jonkoops** [comment]
I wonder if we should be using theme properties to accomplish this. The title of the Admin Console is likely something that one might want to localize.

For example, in the old Account Console a localized message is used [in the template](https://github.com/keycloak/keycloak/blob/18.0.0/themes/src/main/resources/theme/base/account/template.ftl#L9).

**Comment by ssilvert** [comment]
> I wonder if we should be using theme properties to accomplish this. The title of the Admin Console is likely something that one might want to localize.
> 
> For example, in the old Account Console a localized message is used [in the template](https://github.com/keycloak/keycloak/blob/18.0.0/themes/src/main/resources/theme/base/account/template.ftl#L9).

Yeah, I mentioned that in the issue.  I'll create a new issue for it.  What I need to do on the back end is to expose the `msg` method to the admin console.  Then, if the value of `properties.title` is a message key, it will display the localized value instead of the hard-coded value of `properties.title`.

**Comment by jonkoops** [comment]
> What I need to do on the back end is to expose the msg method to the admin console.

Would this not be a good place to start? I'd rather have a conventional key for this title than to be able to configure it here in the properties. I feel like merging this in now would only complicate the feature itself.

**Comment by ssilvert** [comment]
> > What I need to do on the back end is to expose the msg method to the admin console.
> 
> Would this not be a good place to start? I'd rather have a conventional key for this title than to be able to configure it here in the properties. I feel like merging this in now would only complicate the feature itself.

It wouldn't change this PR at all.  We still need to be able to specify the title in theme.properties.  Localization will happen later.  That's a different issue and it's low priority.

**Comment by jonkoops** [comment]
> We still need to be able to specify the title in theme.properties.

Why? We can use a conventionally named key like `adminTitle` (same as the Account Console does now). Then users can customize the name by changing the locale.

**Review by jonkoops — APPROVED** [review]
As discussed in the team meeting we can use the property if present and fall back to a localized message if it is not defined.

**Comment by jonkoops** [comment]
@agagancarczyk just FYI we will have to create some docs for this.

**Pull request merged**
