### PR TITLE
Prevent Arbitrary code execution via crafted environment variables

### PR DESCRIPTION
**Pull request by abstractj**
- Avoid the usage of eval
- Suppress error messages without suppressing the error code

### CODE REVIEW

**Review by SecKatie — DISMISSED** [review]
LGTM. Eval is generally an anti-pattern

**Review by DGuhr — CHANGES_REQUESTED** [review]
@abstractj Seems this leads to the command not being invoked correctly anymore from looking at the tests. Can you please check?

**Comment by pedroigor** [comment]
IIRC, Wildfly also uses `eval` in `standalone.sh` and that is the reason why we are also using it.

Looks like the changes break the script and fails to start the server. I'm kinda lacking an alternative here :)

**Comment by DGuhr** [comment]
@pedroigor jump to pure java instead of scripts? (fun for now, but only half. we should really go down that path)

But yeh, i tried it out locally and the server starts but nothing gets logged anymore. the newest changes are also not doing the trick, at least not locally here and also not in the CI -> https://github.com/keycloak/keycloak/runs/6453217301?check_suite_focus=true#step:8:4177

Option 1: Really go down the pure java path. (+1 from my side)
Option 2: sanitize eval. see e.g. https://unix.stackexchange.com/questions/296825/how-to-deal-with-insecurity-of-eval-evaluating-external-input-in-a-script | https://stackoverflow.com/questions/17529220/why-should-eval-be-avoided-in-bash-and-what-should-i-use-instead | https://medium.com/dot-debug/the-perils-of-bash-eval-cc5f9e309cae 
Option 3: leave as is (not recommended)

**Comment by pedroigor** [comment]
TBH, I would just leave it as-is for now. We should probably reach out Wildfly team to understand why they are using it as I wouldn't be surprised at all if they had this discussion before.

Not sure if we can do #1 now but yes we should consider it in the future after a lot of discussions :)

**Comment by DGuhr** [comment]
@abstractj when we can improve this, we should imo improve it, so sure, go for it :) 

Just to clarify: When I tried your PR branch locally, not only the errors were not showing (e.g. running ./kc.sh start-dev) but I got no console output at all, but the server started. That's also reflected in the test results, see e.g. https://github.com/keycloak/keycloak/runs/6425900016?check_suite_focus=true#step:8:5753 this run.

But +1 to low impact.

**Pull request closed without merging**
