### PR TITLE
Update social login tests

### PR DESCRIPTION
**Pull request by tondrusk**
Backporting to KC 22

### CODE REVIEW

**Review by miquelsi — APPROVED** [review]

**Comment by ahus1** [comment]
MSSQL tests fail due to #24848 which should be merged first. Not sure if a retry will fix it (probably not, re-running it anyway)

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for this PR. I see that several of the commits don't contain issue number, possibly because they have been cherry-picked from the respective PRs before they have been merged. Looking at the commits in the main branch, I see that those contain the issue numbers (probably by using squashed commits via GitHub). 

To be able to track the commits in this branch to the issues later, I ask you to update this PR to use the commits cherry-picked from the main branch as they contain all information that is necessary to track the changes to their issues.

**Review by ahus1 — APPROVED** [review]
Thank you for these changes, I can now see where each commits belongs to. I'm also happy to see the commit IDs, which is nice and helps when browsing the changes. 

Approving as of @miquelsi's earlier review, as the last force-push didn't contain code changes.

**Comment by ahus1** [comment]
Ready to be merged, but should probably wait after 22.0.6 has been released?

**Pull request merged**
