### PR TITLE
[KEYCLOAK-5071] If refresh token failed, drop token in security context

### PR DESCRIPTION
**Pull request by wvdhaute**

### CODE REVIEW

**Comment by mposolda** [comment]
@wvdhaute It looks there is a test failure in CookieTokenStoreAdapterTest.testTokenInCookieRefresh . Seems it's related to your PR. Could you verify please?

**Comment by mposolda** [comment]
@wvdhaute Sorry for late response. I was on PTO, but finally back now.

In your PR I can see that you changed line 159 in CookieTokenStoreAdapterTest and it looks to me that user is still logged now even if he should be logged-out. IMO the change in behaviour like this can't be accepted. Please investigate why this is the case, maybe some other changes need to be done to preserve the old behaviour.

**Comment by mposolda** [comment]
@wvdhaute Also please squash commits into one commit. We prefer to have ideally 1 commit per PR. Thanks.

**Comment by mposolda** [comment]
@wvdhaute Thanks and sorry for late response.

Unfortunately the same change like in UndertowCookieTokenStore.java will likely need to be added to all our other adapters, which support CookieStore. EAP, Tomcat, Jetty and possibly more. We have some howto how to run adapter tests - they are not part of the default built, which is why this PR is passing, but I bet they will fail after this change. Howto is here: https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md

The thing is that RefreshableKeycloakSecurityContext is the adapter-core class used in all the other adapters and every change in behaviour like this needs to touch all the other adapters.

**Comment by mposolda** [comment]
BTV. RefreshableKeycloakSecurityContext wasn't mean to be class used in the end user's applications. Maybe it's easier if you just used your own fork (or subclass) of it instead of touch the core class?

**Comment by wvdhaute** [comment]
@mposolda no problem, holiday period, same goes for me :)

Ok, I will try to find some time later on as I cannot run these tests easily on my work machine, port issues.

**Comment by stianst** [comment]
@mposolda can you review this again? It looks like @wvdhaute has done what was requested

**Comment by mposolda** [comment]
@wvdhaute Were you able to run adapter tests with Wildfly, EAP, JBoss7 and Tomcat?

**Comment by wvdhaute** [comment]
@mposolda sorry did not find time yet to run these and sort of forgot about it also to be honest. Also hard to run them on the company machine as we have a port issue. Hopefully I'll find some time this weekend. I'll bump it on my list :)

**Comment by mposolda** [comment]
Closing this PR for now due the:

- It's not complete and there is some work pending for a long time. Especially there is slight risk that the change will break some adapter impls.
- It adds some improvements to RefreshableKeycloakSecurityContext class, but this class was originally meant to be used internally by our adapters, not as an util class for handling adapter flows manually from the client applications. 

Feel free to reopen if you really think that this require fixing and if you have complete PR and all the adapter tests passing (including EAP6, AS7, Wildfly, EAP7, Spring, all Tomcat and all Jetty versions). However if you really want the customizations, it's maybe better and easier to rather create your own class (or subclass of RefreshableKeycloakSecurityContext) and do it by yourself in your own way.

**Pull request closed without merging**
