### PR TITLE
Remove leftover code in login-passkeys-conditional-authenticate.ftl

### LINKED ISSUE #32755: Leftover code in login-passkeys-conditional-authenticate.ftl
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

Hello,  

It works by coincidence, but there is some leftover code from a refactor of the `login-passkeys-conditional-authenticate.ftl` page.
A `<div />` block was likely copied and modified, but the old one wasn’t removed.

Here:  

```ftl
<div id="kc-form-passkey-button" class="${properties.kcFormButtonsClass!}" style="display:none">
    <input id="authenticateWebAuthnButton" type="button" onclick="doAuthenticate([], "${rpId}", "${challenge}", ${isUserIdentified}, ${createTimeout}, "${userVerification}", "${msg("passkey-unsupported-browser-text")?no_esc}")" autofocus="autofocus"
        value="${kcSanitize(msg("passkey-doAuthenticate"))}"
        class="${properties.kcButtonClass!} ${properties.kcButtonPrimaryClass!} ${properties.kcButtonBlockClass!} ${properties.kcButtonLargeClass!}"/>
</div>
<div id="kc-form-passkey-button" class="${properties.kcFormButtonsClass!}" style="display:none">
    <input id="authenticateWebAuthnButton" type="button" autofocus="autofocus"
        value="${kcSanitize(msg("passkey-doAuthenticate"))}"
        class="${properties.kcButtonClass!} ${properties.kcButtonPrimaryClass!} ${properties.kcButtonBlockClass!} ${properties.kcButtonLargeClass!}"/>
</div>
```

We can see the two block have an identical `<input id="authenticateWebAuthnButton"` and are essentially the same. It's just that in the refactor the click event callback is assigned imperatively in the script while in the old version it there was a declarative onclick attribute.  

The issue is not visible because the blocks are `display:none`

Fixed in #32727  

Best,

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

N.A

### Actual behavior

N.A

### How to Reproduce?

N.A

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by garronej**
Hello,  
I'm pretty sure that the block that this PR removes have been left here by mistake.  

Fixes #32755

### CODE REVIEW

**Comment by ahus1** [comment]
@garronej - Please create GitHub bug issue describing the behavior you see and what indicates to you that this block has been removed. Then mention this new issue as `Closes #xxxx` in the description of this issue above. This helps us to understand the intention of this change. 

@tnorimat - pinging you here as you have added these changes in the conditional UI changes in b4e7d9b1aa09da44ba673dcaf6658a2d71e11cdf so you might be able to review it. Thanks!

**Comment by tnorimat** [comment]
@ahus1 Yes, I will reivew the PR.

**Review by tnorimat — APPROVED** [review]
I confirmed that it worked well on my local environment.

**Comment by tnorimat** [comment]
@ahus1 @ssilvert  Hello, This feature of conditional UI cannot be tested by integration test automatically, so I tested the PR by myself on my computing environment.

**Review by ahus1 — APPROVED** [review]
Approving as of @tnorimat's review. It will need also someone from the UI team to review this given our code ownership rules.

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
Thanks for this fix @garronej. Since this issue affects v25 could I ask you to backport this work to the `release/25.0` branch? If it affects more versions let us know and we can backport this fix there as well.

**Pull request merged**
