### PR TITLE
Revisit unique constraints in jpa user store

### LINKED ISSUE #14797: Revisit unique constraints in jpa user store
https://github.com/keycloak/keycloak/pull/14748#discussion_r988239010

### PR DESCRIPTION
**Pull request by vramik**
Closes #14797

### CODE REVIEW

**Review by ahus1 — APPROVED** [review]
I reviewed and tested that this change aligns with the original comment/idea that was proposed. Still I'm a bit sad that for two things that are quite similar (constraint on email and user name), we have two so very different concepts, and both are incomplete. See next comment.

**Comment by ahus1** [comment]
Look at this PR, this calls for another issue/PR IMHO: 

* When changing the email constraint in the realm UI. it shows the following hint  "It is recommended to manually update email constraints of existing users in the database after switching off support for duplicate email addresses. This can only be done by someone with direct database access, is not well documented, storage dependent and error-prone.

* The new constraint to the user name will only work when the use types in the same name as on registration; if they change the capitalization, the constraint will not trigger. Looking at that behavior from the outside in a realm with non-case-sensitive user names, this behavior would look erratic. 

Looking at the two solutions, I'd prefer the variant with the email constraint plus a new background job that updates the users as described in the help text. This would lead to a constraint that would catch all duplicates.

**Comment by ahus1** [comment]
BTW: The failing model tests are unrelated, they failed in `legacy-jpa-federation+infinispan` which is not affected by this PR. 

>  ConcurrentAuthzTest.testStaleCacheConcurrent:153 » ModelDuplicate org.keycloak.models.ModelDuplicateException: javax.persistence.PersistenceException: org.hibernate.excepti
on.ConstraintViolationException: could not execute statement

> org.keycloak.testsuite.model.authz.ConcurrentAuthzTest.testPermissionRemoved
> Run 1: ConcurrentAuthzTest>KeycloakModelTest.createEnvironment:504->createEnvironment:62 » ModelDuplicate javax.persistence.PersistenceException: org.hibernate.exception.Co
nstraintViolationException: could not execute statement
> Run 2: ConcurrentAuthzTest>KeycloakModelTest.cleanEnvironment:513->cleanEnvironment:82 » NullPointer Null keys are not supported

**Comment by vramik** [comment]
> Look at this PR, this calls for another issue/PR IMHO:

I agree it would to be good to create another issue or discussion for that. Would you like to create it?

> * The new constraint to the user name will only work when the use types in the same name as on registration; if they change the capitalization, the constraint will not trigger. Looking at that behavior from the outside in a realm with non-case-sensitive user names, this behavior would look erratic.

I'm not sure I follow here. Could you please explain the scenario when the constraint would be problematic?

**Comment by ahus1** [comment]
> Could you please explain the scenario when the constraint would be problematic?

The constraint is IMHO problematic as it will catch only some scenarios: 

* Setup a realm with capitalization disabled
* Create a user `ALEX` -> succeeds
* Create another user `ALEX` -> prevented by the constraint, and also the check in the Java code
* Create a user `alex` -> not prevented by the constraint, but the check in the Java code

I therefore argue that it is not as simple as it should/could be for maintenance and usage. I'll created the following issue: #14911

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
