### PR TITLE
Remove legacy cookies entirely

### LINKED ISSUE #16181: Deprecate legacy cookie behaviour behind profile
### Description

Since implementing [KEYCLOAK-12125](https://issues.redhat.com/browse/KEYCLOAK-12125), Keycloak adds two cookies with the same value but different `SameSite` settings when the `SameSite=None` is set to none. 

The was due to old browsers not support `SameSite=None`, see https://www.chromium.org/updates/same-site/incompatible-clients/ for details and how to detect them.

Since then, browsers supporting this are wide-spread: https://caniuse.com/?search=SameSite%3DNone (92+%). 

Adding these extra cookies adds to the HTTP headers sent in a response and request, and a default setup with NGINX which limits responses with 4k headers needs to be tweaked to make it work. 

Therefore, I suggest to remove the `*_LEGACY` cookies. Additionally, we should unify our cookie behaviour so that:
- All cookies are `Secure` by default.
- All cookies are `SameSite=Strict`, unless explicitly specified otherwise.

### Motivation

* Simplify Keycloak's code structure, and support ever-green browers.
* Simplify setup of Keycloak behind a loadbalancer

### LINKED ISSUE #16770: Remove legacy cookies
`_LEGACY` cookies was introduced in Keycloak as a work-around to SameSite enforcement in browsers. As time has past SameSite for cookies is widely supported and this work-around is no longer required.

One caveat to the above is that the `_LEGACY` cookies also served another purpose, which is they where available in an insecure context, while the regular cookies are not. This results in login not working as expected when accessing a Keycloak deployment not through `localhost`, but through `http` rather than `https`. This is of course not recommended at all in production, but frequently used during development or testing. An alternative to the above is conditionally set the `secure` flag on cookies only when access over a secure context, as well as changing `SameSite=None` cookies to `SameSite=Lax` as user-agents will not send cookies with `SameSite=none` if they do not have the `secure` flag set.

### PR DESCRIPTION
**Pull request by jonkoops**
Closes #16770

### CODE REVIEW

**Review by mabartos — APPROVED** [review]
@jonkoops Thanks! I don't see any issues with removing the legacy Keycloak Session cookie. 

@mposolda @stianst @pedroigor Could you please take a look at it?

**Review by pedroigor — COMMENTED** [review]
Does it make sense to include a switch to enable legacy cookies for backward compatibility and evaluation of the impact on the existing deployments?

We can use a hidden option in our config or just use a system property. I think how we set this is not so relevant as we want to effectively remove those cookies.

The idea is to at least give a chance to people to plan the upgrade if they need to support old browsers.

**Comment by ahus1** [comment]
+1 for making it switchable. Instead of using a hidden config option, could we add it to the `Profile.Feature` enum that it is deprecated (those are disabled by default AFAIK)? This would help with documenting it. I'm always about hidden features in security related software.

**Comment by jonkoops** [comment]
I see no issue with putting this behind a flag, and I agree with @ahus1 that the default should be disabled. Let me see what I can do.

**Comment by jonkoops** [comment]
Closing this PR as we decided to put this behind a profile first. I'll get back to this once that lands.

**Pull request closed without merging**
