### PR TITLE
Convert all properties files to UTF-8

### LINKED ISSUE #20848: Convert all properties files to UTF-8
### Description

A lot of our property files are not using UTF-8, which makes some of the translations hard to read. Under the issue the following should happen:

1. All `.properties` files should start with `# encoding: utf-8`
2. All encoded texts should be written in their plain UTF-8 representation.

### PR DESCRIPTION
**Pull request by Eng-Fouad**
Resolves #20848

### CODE REVIEW

**Comment by ahus1** [comment]
Pinging @jonkoops as you assigned yourself to the parent issue

**Review by jonkoops — APPROVED** [review]
Tested this locally, and it seems that the localization still works as expected. LGTM!

**Comment by jonkoops** [comment]
@ahus1 could you give this one maintainer approval and merge it in?

**Review by ahus1 — APPROVED** [review]
Approving as of @jonkoops's review. Thank you!

**Pull request merged**
