### PR TITLE
Improve third-party storage access detection and cookie fallback

### PR DESCRIPTION
**Pull request by jonkoops**
Backports #19835

### CODE REVIEW

**Review by edewit — APPROVED** [review]

**Comment by jonkoops** [comment]
Looks like the tests are failing because some of the Chrome, this is because of a misssing backport. See #20598.

**Comment by jonkoops** [comment]
@ssilvert could you merge this one in? I need some maintainer approval to do so.

**Comment by tschlechtweg** [comment]
@jonkoops have the tests been run on this change, currently we have issues with that change from version 21.1.2 to 22.0.1 in Firefox 114.0.1. We use React as our Frontend Stack, and we have configured keycloak to accept some local redirect URLs set in the `host`-file of our dev systems (e.g. service.product.local). This way we can start the UI and use our real backend services for communication. Normally this worked without a problem, but after upgrading to >=21.1.2 we saw that Firefox has a strange issue.

In Firefox warnings about the `KEYCLOAK_3P_COOKIE` are displayed saying Cookies without `SameSite`-attribute will be set to `SameSite=Lax` some time in the future, fine. Also, warnings about partitioned storage and cookie access for all 3 of the touched htmls sites, fine. But after a short amount of time (~3s) the site refreshes and this happens in a loop. Also, our frontend display, before the refresh, for a short amount that the user does not have the correct rights to access some of the functionality (this should never happen, as pages then would not be displayed).

Using any version lower or equal to than ``

**Comment by jonkoops** [comment]
Please open a new issue if this can be reproduced in the [nightly version])(https://github.com/keycloak/keycloak/releases/tag/nightly) of Keycloak.

**Pull request merged**
