### PR TITLE
KEYCLOAK-16323 Speedup GHA

### PR DESCRIPTION
**Pull request by hmlnarik**

### CODE REVIEW

**Comment by pedroigor** [comment]
@hmlnarik Good idea around using matrix.

Do you think we can also add the running platform to the matrix too? Quarkus should also run on Windows due to some differences in how the configuration works.

**Comment by hmlnarik** [comment]
@pedroigor Thank you. I'd say let's keep this PR small and add the Quarkus / Windows build as a follow-up?

**Comment by pedroigor** [comment]
ok

**Review by pedroigor — COMMENTED** [review]
Can we have better names for the test groups so that one can easily infer the tests being run on each of them?

**Comment by pedroigor** [comment]
@hmlnarik Btw, how much you think we got better in terms of execution time ?

**Comment by hmlnarik** [comment]
> Can we have better names for the test groups so that one can easily infer the tests being run on each of them?

There is no logical grouping, all the tests are run, and they are distributed by their average time. So there is no better naming.

> @hmlnarik Btw, how much you think we got better in terms of execution time ?

appx. an hour better

**Comment by pedroigor** [comment]
> There is no logical grouping, all the tests are run, and they are distributed by their average time. So there is no better naming.

Could you elaborate more on how this distribution was done? It seems you are basically using regex to filter tests, no?

**Comment by hmlnarik** [comment]
The regexes are based on the test execution time and rough alphabetical separation to keep the regex simple.

**Comment by pedroigor** [comment]
@hmlnarik Sorry but I still don't understand this distribution and what it would mean from now on. How we are supposed to put a test in one of these groups based on the average time if you are using regex to filter them?

What would happen if I add some tests that take time to run, which group it would/should run?

**Comment by hmlnarik** [comment]
> @hmlnarik Sorry but I still don't understand this distribution and what it would mean from now on. How we are supposed to put a test in one of these groups based on the average time if you are using regex to filter them?
> 
> What would happen if I add some tests that take time to run, which group it would/should run?

It does not mean anything. You can add any test anywhere.

If some group starts being too non-evenly distributed, then the groups can be rebalanced. However that would have to be many tests

**Comment by pedroigor** [comment]
@hmlnarik I would like to see more meaningful names, that helps a lot. At least for me.

Btw, as per the execution time, I did a simple calculation:

* Here quarkus group1,group2 and group3 takes 81
* My latest build [here](https://github.com/keycloak/keycloak/pull/7607) running basic tests + adapters (which I think are "distributed" across your groups) takes 89

Should we expect more ?

**Comment by hmlnarik** [comment]
@pedroigor The #7607 took 2h 2m 5s to run per https://github.com/keycloak/keycloak/actions/runs/365938372
This PR took 48m 52s per https://github.com/keycloak/keycloak/actions/runs/363108136
What else should I add?

**Review by pedroigor — APPROVED** [review]
Nothing to add. The improvement is clear due to more parallelism.

I'm approving even though not 100% sure about the distribution approach.

Nice work.

**Pull request merged**
