### PR TITLE
[KEYCLOAK-8646] - Error deleting policies when admin events are enabled

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by sguilhen — APPROVED** [review]
LGTM

**Comment by mposolda** [comment]
@pedroigor I wonder if we can just update the existing GenericPolicyManagementTest and enable admin events in it rather then creating separate subclass? AFAIK separate subclass will mean that tests will need to be defacto executed twice (adds some more time to the overall testsuite execution time). Or do you prefer to keep it separate to test with both admin events enabled and disabled?

**Comment by pedroigor** [comment]
@mposolda, the reason behind the new test class is to make sure all operations run fine with and without admin events enabled.

**Review by mposolda — APPROVED** [review]
@pedroigor Ok, so you want to test with both enabled and disabled admin events. I am approving then. Thanks for clarifying.

**Pull request merged**
