### PR TITLE
KEYCLOAK-13205 Apply locale resolution strategy to admin console.

### PR DESCRIPTION
**Pull request by devopsix**
* Add new “locale” attribute to “whoami” response.
* Query “whoami” before loading messages.
* Use “whoami” locale instead of ID token locale for loading messages.

### CODE REVIEW

**Comment by abstractj** [comment]
@ssilvert please change the labels if you need. It seems to me that the impact is not medium or high. But it's your call to decide.

**Comment by ssilvert** [comment]
Running admin console UI tests build #166

**Review by ssilvert — APPROVED** [review]
UI test successful on FireFox and Chrome.  Approve.

**Comment by cdmikechen** [comment]
@ssilvert @abstractj  @devopsix  I'm using keycloak 11.0.2 and found a problem...
I use `zh-CN` locale. When keycloack use `http://localhost:8080/auth/admin/master/console/whoami` to get locale, keycloack return `locale: "zh_CN"`.
But when using `http://localhost:8080/auth/admin/master/console/messages.json?lang=zh_CN` to get data, I found it will return English datas. Meanwhile, if I use `http://10.3.101.210:8080/auth/admin/master/console/messages.json?lang=zh-CN`, I will get chineses datas.

**Comment by devopsix** [comment]
[`AdminConsole.WhoAmI.locale`](https://github.com/keycloak/keycloak/blob/08dca9e89f27ddb92166ee14e40989550ad8cf84/services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java#L103) is modelled as a `java.util.Locale` which is probably serialized using its [`toString()` method](https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#toString--) when the response is being built. Unfortunately, `Locale.toString()` does not return a well-formed IETF BCP 47 language tag but this non-standard “underscored” representation.

In contrast, [`AdminRoot.getMesages(KeycloakSession, RealmModel, String)`](https://github.com/keycloak/keycloak/blob/08dca9e89f27ddb92166ee14e40989550ad8cf84/services/src/main/java/org/keycloak/services/resources/admin/AdminRoot.java#L251) uses [`Locale.forLanguageTag(String)`](https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#forLanguageTag-java.lang.String-) for reading the value of the `lang` parameter.

Using proper language tags should definitely be preferred over the “underscored” representation.

@cdmikechen IMO its worth opening an issue in JIRA for that.

@ssilvert I would be willing to contribute a patch. (I would suggest `@JsonIgnore`ing the `AdminConsole.WhoAmI.locale` field and adding a `@JsonProperty` annotated accessor that does the conversion.)

**Comment by cdmikechen** [comment]
@devopsix Glad to see your response. I've opened an issue in JIRA https://issues.redhat.com/browse/KEYCLOAK-15459 , and I've put some request and response data pictures.

**Comment by devopsix** [comment]
Re. “zh-CN” locale see pull request #7397.

**Comment by argentinaluiz** [comment]
I created a Docker image to momentarily solve the translation problem of the Keycloak admin for some locales like pt-BR, zh-CN and etc.

https://hub.docker.com/r/codeeducation/keycloak

**Comment by ccckblaze** [comment]
when will this released?

**Pull request merged**
