### PR TITLE
KEYCLOAK-1924 SAML adapter full subsystem EAP/Wildfly

### PR DESCRIPTION
**Pull request by mstruk**

### CODE REVIEW

**Comment by stianst** [comment]
Is this ready to be merged or do you want Bill to review it first?

**Comment by mstruk** [comment]
From my POV it's ready to merge, so it's more a question for @patriot1burke. 
It would be good for Bill to review in any case.

**Comment by patriot1burke** [comment]
Looks good, only thing I orry about is:
<subsystem xmlns="urn:jboss:domain:keycloak-saml:1.1"/>

It was 1.6 previously.  If you're ok answering all the "My saml adapter doesn't work anymore", then merge it :)

**Comment by patriot1burke** [comment]
urn:jboss:domain:keycloak-saml:1.1 from 1.6

**Comment by mstruk** [comment]
I'm OK with answering all the "doesn't work anymore" questions :)

**Pull request closed without merging**
