### PR TITLE
KEYCLOAK-5883 Build testsuite within product profile

### PR DESCRIPTION
**Pull request by martin-kanis**

### CODE REVIEW

**Comment by stianst** [comment]
I think we've had testsuite disabled in Brew/PNC the whole time right? Does this introduce any issues when building in PNC?

**Comment by martin-kanis** [comment]
Yes, we had testsuite disabled while building in Brew.  It should be OK in PNC, I test it locally with pnc repository but without alignment.

**Comment by stianst** [comment]
Will it not cause a lot of headaches with the alignment? I suspect that's one of the reasons it was disabled in the past.

I don't have any issues with this change, just want to make sure it doesn't cause big problems building ER2.

**Comment by martin-kanis** [comment]
I tried to built it locally with alignment but I failed. Stage PNC is about to be upgraded. If we'll hit a blocker because of this change I can easily revert the change in the Gerrit.

**Comment by stianst** [comment]
Looking at https://github.com/keycloak/keycloak/blob/master/pom.xml#L1597 it should already be enabled as long as -DskipTestsuite isn't set.

**Comment by martin-kanis** [comment]
We build with -DskipTests which I guess causes the testsuite is not being built.

**Pull request closed without merging**
