### PR TITLE
Added support for Nexus 3 repositories

### LINKED ISSUE #34136: Add support for Nexus 3 repositories
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

Currently Keycloak supports only uploading artifacts to Nexus (version 2) repositories. Soon we might want to support Nexus 3 version, which needs a different plugin.

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by miquelsi**
Closes #34136

### CODE REVIEW

**Review by pedroigor — COMMENTED** [review]
Don't we want a specific profile to enable Nexus 3?

**Comment by miquelsi** [comment]
@pedroigor it is enabled when we specify `nxrm3:staging-deploy`

**Review by stianst — CHANGES_REQUESTED** [review]
Not sure this will work like this, as the staging plugins automatically register themselves. `nexus-staging-maven-plugin` for example we don't specify directly when releasing Keycloak, we just do a `mvn deploy`, and behind the scenes it somehow gets wired-in.

Does `nexus-staging-maven-plugin` not work for Nexus 3?

**Comment by miquelsi** [comment]
Wrapped Nexus 3 support in a specific profile

@stianst @pedroigor

**Review by stianst — APPROVED** [review]

**Pull request merged**
