### PR TITLE
KEYCLOAK-5802 fix install-adapters.sh script for wildfly10 and below

### PR DESCRIPTION
**Pull request by vramik**

### CODE REVIEW

**Comment by pedroigor** [comment]
@vramik, can you give more details about why we need to remove elytron subsystem when ```app.server.elytron.adapter.supported``` is set to false ?

**Comment by vramik** [comment]
@pedroigor I don't really know, I was fixing just the script and the `else` was already there.

@mhajas authored this as part of [KEYCLOAK-5568](https://issues.jboss.org/browse/KEYCLOAK-5568), Michal can you answer the question?

**Comment by mhajas** [comment]
@pedroigor We have discussed this on Hipchat. Basically, it is there so that we were able to distinguish between elytron-enabled and elytron-disabled in tests and based on this decide whether run tests which are dependent on elytron.

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@stianst ready for merge.

**Pull request merged**
