### PR TITLE
Add docs for transient-users how to prevent profile-review

### PR DESCRIPTION
**Pull request by Captain-P-Goldfish**
#relatesTo https://github.com/keycloak/keycloak/discussions/26637

### CODE REVIEW

**Review by hmlnarik — COMMENTED** [review]
Thanks, the changes look good. Could you please add the commit signature (for the DCO check)?

**Comment by Captain-P-Goldfish** [comment]
done.

**Comment by ahus1** [comment]
@Captain-P-Goldfish - thank you for resolving the conflicts. The checks are still read as the commit message misses the Sign-off line as outlined in CONTRIBUTING.md

Please update your commit with a signoff.

**Comment by Captain-P-Goldfish** [comment]
sorry forget the option. Updated the commit with the `--signoff` option

**Review by ahus1 — APPROVED** [review]

**Comment by ahus1** [comment]
Thank you for taking the time to contribute this documentation enhancement!

**Pull request merged**
