### PR TITLE
Remove the BC dependency from keycloak-operator

### LINKED ISSUE #13115: Remove BouncyCastle dependency from operator

### PR DESCRIPTION
**Pull request by david-rh**
Remove the BC dependency from keycloak-operator, resolves #13115

### CODE REVIEW

**Review by mposolda — APPROVED** [review]
@david-rh Thanks for this PR!

**Comment by andreaTP** [comment]
Hi all, I'm sorry for being late to this party but removing the Bouncycastle dependencies from the operator makes it unusable on [K3s](https://k3s.io/) ( [reported here](https://github.com/fabric8io/kubernetes-client/issues/4063) and in multiple other issues ) and possibly on other kubernetes distributions (e.g. [Rancher](https://rancher.com/) is based on K3s).

Currently, there is no documented option on how to provide those libraries on the classpath if required, I see a couple of alternatives:
- revert this change
- document how to provide the needed libraries on the classpath testing the operator on K3s and Rancher

cc. @abstractj @DGuhr @vmuzikar

**Comment by mposolda** [comment]
@andreaTP Ok, Thanks for pointing this and sorry for the issues. For now, I've reverted the changes in this commit https://github.com/keycloak/keycloak/pull/13953 . Anyone has a time to review please?

I will create follow-up issue for better long term strategy how to remove bouncycastle dependency from operator and will discuss with you guys later if needed to remove. It may be needed for the FIPS 140-2 compliance (but not yet sure, to be investigated...)

**Comment by david-rh** [comment]
Hi All,

I think there is a misunderstanding of the PR I submitted. We are
decoupling Bouncy Castles from the code and moving those dependencies into
keycloak-crypto. The keycloak-operator package originally did not have an
explicit dependency on BC, but pulled it in as part of its dependency on
keycloak-common. I added an explicit dependency on BC when we decoupled BC
from common and created an issue to revisit this at a later date. In the
operator project itself, there is only one line that directly depended on
BC and that was using BC's Base64 instead of java.util.Base64.

Now, the issue referenced is talking about the elliptical curve algorithms.
The implementation of those algorithms were moved to the keycloak-crypto.
Right now, the project chooses which crypto module to include at build time
(Marek, correct me if I am wrong). So, we just need to make sure that the
operator includes the appropriate crypto module as it's being packaged.
Marek, is that not being done already?

David Anderson
Associate Principal AppDev Solution Architect
Mobile: 469-328-0761 <(469)%20328-0761>
Email: ***@***.***
Red Hat Certified Professional: 150-068-187
Learn OpenShift-> https://learn.openshift.com/
<https://openshift.katacoda.com/>

**Comment by mposolda** [comment]
@david-rh Actually the operator doesn't have dependency on `keycloak-crypto-default` module. Which is currently the only module of Keycloak server, which uses bouncycastle. So I assume that operator needs to use bouncycastle for something completely different than what is used by Keycloak itself? For example even if Keycloak server itself wouldn't use bouncycastle dependencies for anything, the operator would still need to use bouncycastle dependencies. Or am I wrong here? I am just guessing as I am not very familiar with the operator. @andreaTP @vmuzikar Anyone of you clarify this please?

**Comment by andreaTP** [comment]
@mposolda the operator is an heavy user of the fabric8 Kubernetes Client and the optional dependency on BouncyCastle is explained here:
https://github.com/fabric8io/kubernetes-client/blob/da35d31d3323572d631aaeb553204bec8b926d0b/doc/FAQ.md#what-is-bouncy-castle-optional-dependency-and-when-is-it-required

If the library is not provided it will throw this exception in some circumstances:
https://github.com/fabric8io/kubernetes-client/blob/cedf1614d0fc82b0d67bbb72d6b5e36da9f94e1b/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/internal/CertUtils.java#L164

I think that you can even decide to remove the dependency from the standard operator distribution, but, in that case, you'd better add documentation on how to provide it in the classpath of the final Docker image.

**Comment by david-rh** [comment]
Just to be clear, the dependency in the pom.xml for operator did not exist
prior to the work I've been doing. It inherited that dependency through
keycloak common. I added it as a temporary fix while working on decoupling
common from a direct dependency on bc. If you are relying on the adapter,
the bc library should still be included as part of the adapter.

David

**Comment by mposolda** [comment]
@andreaTP Thanks for explain

@david-rh Yes, so before BC dependency was added as a side-effect of adding keycloak-common. Now it needs to be added explicitly due it was removed from keycloak-common and due the reasons mentioned by @andreaTP . Right now, I am not sure if we need to have also operator to be FIPS compliant. If yes, we may later need to somehow document how to remove BC dependency and possibly replace it with BCFIPS (assuming the fabric8 stuff works with BCFIPS, which can be another possible challenge...)

**Comment by david-rh** [comment]
Short answer, yes the operator will also need to support FIPS. I would also
include the adapters in that list.

David Anderson
Associate Principal AppDev Solution Architect
Mobile: 469-328-0761 <(469)%20328-0761>
Email: ***@***.***
Red Hat Certified Professional: 150-068-187
Learn OpenShift-> https://learn.openshift.com/
<https://openshift.katacoda.com/>

**Pull request merged**
