### PR TITLE
Role mappers must return a single value when they are not multivalued

### LINKED ISSUE #20218: Role mappers must return a single value when they are not multivalued
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Both built-in realm and client role mappers are not properly handling the `multivalued` attribute. Instead, `string`-typed claims are always set using a stringified JSON array.

It is also not behaving similarly to other mappers that also allow configuring single/multi-valued claims.

### Version

21.1.1

### Expected behavior

When setting the `multivalued` to `false`, the claim value should be a single string. If based on a list, only the first element is considered.

### Actual behavior

When setting the `multivalued` to `false`, the claim is still represented as an array when the values come from a list.

### How to Reproduce?

* Change either the role or client role mappers to use single-valued claims (`multivalued==false`)
* Issue an access token for a user with multiple roles and note that a stringified JSON array is set to the claim

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #20218

### CODE REVIEW

**Comment by pedroigor** [comment]
@mposolda @thomasdarimont Would you mind reviewing it?

FYI, I'm working on more improvements on both realm and client role mappers in order to make it more clear whether are dealing with a realm or client role mapping. Today, their code is mixed and a bit confusing to follow.

**Comment by mposolda** [comment]
@pedroigor LGTM, Thanks.

One question: Does it worth to be documented in the migration guide too? If I understand correctly, before the string claim returned might be something like `"roles": "[role1, role2]"` and it is possible that someone relies on this format to be returned (even if it is a bit strange format...). Leaving to you. If you think it is not needed, I can approve as it is, but would slightly prefer to document that.

**Comment by pedroigor** [comment]
@mposolda Makes sense, adding to release notes.

**Review by pedroigor — COMMENTED** [review]
@mposolda Added the documentation.

I was also wondering if we want to make sure values are following at least the natural order of their corresponding type so that we don't pick random values when the mapper is single-valued. Perhaps a follow-up.

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
> @mposolda Added the documentation.
> 
> I was also wondering if we want to make sure values are following at least the natural order of their corresponding type so that we don't pick random values when the mapper is single-valued. Perhaps a follow-up.

+1 for the follow-up if needed.

**Pull request merged**
