### PR TITLE
Use a typeahead select control where there are 10 or more options

### PR DESCRIPTION
**Pull request by john-gom**
Resolves Issue https://github.com/keycloak/keycloak/issues/17776

Previously implemented in PR #27726 but split into smaller parts as per review comments

### CODE REVIEW

**Comment by jonkoops** [comment]
I am asking someone else from the UI team to take a look at this, as I currently have other tasks to take care of.

**Comment by john-gom** [comment]
> @john-gom I tried this out and it doesn't appear to work correctly.
> 
> 1. I created a few clients so that I have more than 10.
> 2. Then I go to client details for the `realm-management` client.
> 3. Go to Authorization tab
> 4. Typeahead always gives message, `No results found`

Hi @ssilvert. TBH, I was mainly focussed on user profile attributes rather than more general capabilities in the admin UI, but I will investigate. I am aware that the typeahead only does a "starts with" rather than "contains" match, so not sure if that is part of the problem...

**Comment by ssilvert** [comment]
> > @john-gom I tried this out and it doesn't appear to work correctly.
> > 
> > 1. I created a few clients so that I have more than 10.
> > 2. Then I go to client details for the `realm-management` client.
> > 3. Go to Authorization tab
> > 4. Typeahead always gives message, `No results found`
> 
> Hi @ssilvert. TBH, I was mainly focussed on user profile attributes rather than more general capabilities in the admin UI, but I will investigate. I am aware that the typeahead only does a "starts with" rather than "contains" match, so not sure if that is part of the problem...

Hmm.  Looks like this typeahead problem on the Authorization tab exists in the current code.  I'm not sure why typeahead would have been enabled already.

**Comment by ssilvert** [comment]
@john-gom I think the dropdown on the Authorization tab is not using your new code.

**Review by ssilvert — APPROVED** [review]
I see this working on account console.  And the code looks fine.  Approved.

**Pull request merged**
