### PR TITLE
Made adapters compatible with KC23 "iss" parameter change

### LINKED ISSUE #23794: Made adapters compatible with KC23 "iss" parameter change
Part of the changes for #20621 will need to be backported.The purpose of this backport is to allow the adapters to recognize the "iss" parameter so clients can better prepare for the official change in KC23.

_Issue created from #23583_

### PR DESCRIPTION
**Pull request by vickeybrown**
Closes #23794

### CODE REVIEW

**Comment by pedroigor** [comment]
Could you please add a link to the issue/PR we are backporting from upstream?

I'm also not following these changes because the change you are referring to is actually adding the `iss` parameter to authorization responses. The opposite you are proposing here.

What we actually need to implement is https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-23#section-4.4.2.1.

I'm also not sure about changes in Java adapters as they are deprecated and they should work fine with the latest Keycloak releases. For this particular case, there is a compatibility mode setting at the client settings that allows you to remove this parameter from responses if you have issues with it.

**Comment by vickeybrown** [comment]
Hi @pedroigor, I'll update the description with the Issue and a better description of what I'm trying to do. I'm only wanting to backport the ability for the adapters to handle receiving the "iss" parameter to allow for an easier transition to this change in KC23.

**Comment by jsorah** [comment]
@pedroigor - To add more background here - we're looking to make the KC22 adapters "forward compatible" with the change coming in KC23, we're not looking to backport entire functionality of RFC 9027 to KC22.

This is to solve some logistical issues with making a shift from prior Keycloak versions to something that will work with KC23 without significant problems. If one were to use even the KC22 versions of KeycloakJS or the Java based Keycloak adapters (which I do understand they're deprecated) with nightly / KC23, those clients will not function correctly. The adapter code for KC22 and prior appends the 'iss' param back to the redirect URI used in the code to token exchange, hence it will not match the original value supplied during the initial auth request.  The KeycloakJS change is a little more nuance and only breaks in some instances, but still has an impact.

So that means every Keycloak administrator must ensure their clients are either 
1) using the KC23 version of adapters or something else before they upgrade 
2) have the compatibility flag enabled for impacted clients

This is certainly no small chore in a largely integrated system with hundreds of OIDC clients. 

I think additionally, we are uniquely building against nightly, so we don't actually have a new, compatible version of the adapters to point folks to for now, until KC23 is released, and that places time constraints on us. 

Backporting this "forward compatible" change would eliminate the time constraint we have and could ease transition for folks from KC22 -> KC23 as they could plan to make any necessary updates sooner, prior to KC23 being released.

**Review by pedroigor — COMMENTED** [review]
Sure, I understand that. But the changes you are referring to are actually a server-side thing whereas Keycloak will actually include the `iss` in responses. Not the opposite.

At least in Java Adapters, the changes you are introducing are basically about the parameters the client is sending to the server. What I'm a bit confused.

**Comment by jsorah** [comment]
> Sure, I understand that. But the changes you are referring to are actually a server-side thing whereas Keycloak will actually include the `iss` in responses. Not the opposite.
> 
> At least in Java Adapters, the changes you are introducing are basically about the parameters the client is sending to the server. What I'm a bit confused.

Yeah I think its a little weird because the adapters seem to rely on the authorization server to tell it what redirect URI was used based on the auth response, instead of maintaining that state itself. It then uses that same redirect URI from the auth server to use in code to token. This is where the trouble is with the new `iss` param and why it is added to those methods to strip that query param from the redirect URI.

So its a little something like

1. Initial auth request to http://authserver -> use redirect URI http://someclient/somepath
2. Auth response -> redirect URI -> http://someclient/somepath?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz&iss=http://authserver
3. Adapters remove extraneous OAuth params from redirect URI sent back from authz server
4. Adapters use modified redirect URI in code to token exchange

**Review by mposolda — APPROVED** [review]
Thanks for the PR. Looks good to me and agree that "forward compatibility" of adapters with server changes in Keycloak 23 is beneficial.

@pedroigor Do you have more comments to this or can we merge?

**Review by pedroigor — APPROVED** [review]
I see now. Sorry for the noise.

**Comment by pedroigor** [comment]
@ssilvert Could you please review the changes to JS adapter?

**Comment by ssilvert** [comment]
LGTM, but @jonkoops knows the adapter better than I.  I'll let him weigh in.

**Review by jonkoops — APPROVED** [review]
Changes to the client look fine to me.

**Pull request merged**
