### PR TITLE
Add js validation for Login form

### LINKED ISSUE #19065: No validations on UI side for the user credentials in the login form
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

There is no validation on the UI side for the user credentials in the login form. User can provide an empty password and username and the request gets to the backend. In this way the user might end up locking himself..For e.g you have your browser open, you've provided only username and by accident click the login button without password.. This might result in locking the user

### Version

20.0.5

### Expected behavior

There is validation on the UI for the user's credentials, request should not make it to the backend with empty values

### Actual behavior

No validation on the UI, the user can press the submit button with providing no credentials at all

### How to Reproduce?

1. Click on the "Login" button
2. Submit the form without any credentials

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vplemyannik**
Check password is not empty when submitting login form

Closes #19065

### CODE REVIEW

**Comment by pedroigor** [comment]
@vplemyannik Closing for now as per last comments.

**Comment by vplemyannik** [comment]
Ok, thank for reply

**Comment by vplemyannik** [comment]
@pedroigor maybe it makes sense to close the issue also? because i have decided to take this issue because of label 'help wanted'

**Comment by pedroigor** [comment]
@vplemyannik Thanks for looking at the issue. It might happen that even though the issue is marked as `help-wanted` it deserves a bit more discussion/clarification.

**Pull request closed without merging**
