### PR TITLE
KEYCLOAK-19364 : Add some vi_VN translations

### PR DESCRIPTION
**Pull request by olivierboudet**
KEYCLOAK-19364 : Add translations for locale `vi`. Only login and email messages are in this PR.

### CODE REVIEW

**Comment by stianst** [comment]
I would suggest changing to utf-8 encoding as it makes it easier to maintain and review the translations. This can be done with:

https://github.com/keycloak/keycloak/blob/64717f650b11cbc06bb498bbc4d6d107c9aed180/themes/src/main/resources-community/theme/base/admin/messages/messages_ja.properties#L1-L3

**Comment by stianst** [comment]
We also need to find someone that is able to review the translation. Can you ask for volunteers on the developer mailing list (https://groups.google.com/forum/#!forum/keycloak-dev)?

**Comment by stianst** [comment]
Closing due to lack of response

**Comment by olivierboudet** [comment]
Hello @stianst, I have sent a message on the keycloak-dev list on 1st october : https://groups.google.com/u/2/g/keycloak-dev/c/_MmFVBnF6eo/m/klc6Pt_NAwAJ
Is this PR rejected by lack of reviewer ?

**Comment by stianst** [comment]
Re-opened. Didn't notice that you'd pushed the changes for encoding (GH doesn't give any notifications when changes to the code are pushed, just new comments, etc.). Thanks for sending the mail to ml. Could you ask one more time, and if we don't get any help, I can try to review with help from Google translate. Or, perhaps you know any other native speakers that could review it?

**Comment by olivierboudet** [comment]
OK thank you, I initially used "GH reactions" to not spam you with not very useful notifications :)  
I have just sent a new message on the list. And sorry, the translation has been done by the only vitenamese speaker I know :smile:

**Comment by olivierboudet** [comment]
Hello @stianst apparently there is no Vietnamese speaker on the ML :)

**Comment by stianst** [comment]
That might suggest that there isn't anyone else interested in the Vietnamese translation. You could add the translations to a separate git repo and list it on the extensions page perhaps? That's probably the way we will go with all translations in the future as we plan to provide a better extension mechanism with a better way to discover and install them.

**Comment by olivierboudet** [comment]
Ok thanks, so I close this PR.

**Comment by nguyendtan2030** [comment]
Hello everyone, may I ask, do we still have plans to add Vietnamese?

**Comment by jonkoops** [comment]
@nguyendtan2030 we would welcome contributions to add new languages if you are willing to step up as a maintainer feel free to open a PR.

**Pull request closed without merging**
