### PR TITLE
Adding different strategies to avoid conflicts when updating sessions in Infinispan

### LINKED ISSUE #28388: Handle concurrent writes to sessions more gracefullly
### Description

When updating refresh tokens for multiple clients, the updates to the user session can fail due to too many concurrent requests.

Keycloak should behave more gracefully if concurrent requests happen.

This should avoid the warnings: 

```
Failed to replace entity 'xxx' in cache 'sessions'
``` 

### Discussion

https://github.com/keycloak/keycloak/issues/14040#issuecomment-2031428316

### Motivation

Be better prepared for concurrent refreshes and not well-behaving clients.

### Details

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
This applies three strategies: 

* Avoid unnecessary updates to the sessions during refreshes of tokens
* Avoid conflicts when writing to the session store by checking for concurrent requests within the JVM
* Add a back-off period when replacing cache entries fails

Closes #28388

### CODE REVIEW

**Comment by ahus1** [comment]
@pedroigor @mposolda - to overcome situations where the message `Failed to replace entity 'xxx' in cache 'sessions'` appears, I added three distinct commits with different focus. 

I'd like to hear your feedback on those when you have the time if you think that some or all of the commits should be included in Keycloak.

cc: @mhajas

**Review by douglaspalmer — APPROVED** [review]
LGTM

**Review by mhajas — APPROVED** [review]
Thanks @ahus1, I like these changes. It should make embedded caches replaces more stable. 

I pushed one commit to replace `synchronized` blocks with `ReentrantLock` to be more Virtual threads ready.

The backoff mechanism is not the nicest, it would be great to have some unified approach as we have in the [Retry](https://github.com/keycloak/keycloak/blob/main/common/src/main/java/org/keycloak/common/util/Retry.java) class, however, these methods there are not suitable for this usecase as we want to repeat only if replaced is `false` and not on all `RuntimeException`s. Also, making the method cluttered with yet another lambda would be overkill. So in my opinion we can have this as is.

I think adding the backoff is very important here and I think it can speed up things a lot so I would not remove it from this PR.

Let me know what you think about the commit I added and then we can merge.

**Comment by ahus1** [comment]
@mhajas - thank you for the change towards a reentrant lock, I like it.

**Pull request merged**
