### PR TITLE
The escape() function is deprecated.

### PR DESCRIPTION
**Pull request by Abhishek-Govula**
The escape() function is deprecated which is being used in the decodeToken method. Replaced it to use decodeUriComponent

### CODE REVIEW

**Review by jonkoops — CHANGES_REQUESTED** [review]
Build is failing.

**Comment by jonkoops** [comment]
I was thinking perhaps we can replace this code with [`jwt-decode`](https://github.com/auth0/jwt-decode).

**Comment by Abhishek-Govula** [comment]
@jonkoops - The piece of code to replace the taken from jwt-decode lib directly. Since this is something which is not going to change frequently, I opted to take the piece of code instead of importing the full lib

Also fixed the build failing issue

**Comment by jonkoops** [comment]
Closing this PR to lack of response from the author. If anyone feels like taking this on, feel free to let me know.

**Comment by Abhishek-Govula** [comment]
@jonkoops apologies I missed your reply. I will raise a new PR with latest changes and use ```jwt-decode``` as dependency.

**Comment by jonkoops** [comment]
No problem @Abhishek-Govula, thanks for that!

**Pull request closed without merging**
