### PR TITLE
KEYCLOAK-9836 Deprecate keycloak-servlet-oauth-clien

### PR DESCRIPTION
**Pull request by mposolda**

### CODE REVIEW

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by abstractj** [comment]
@mposolda I found some places where we still refer to keycloak-servlet-oauth-client, see the output below:

```
pom.xml
960:                <artifactId>keycloak-servlet-oauth-client</artifactId>

adapters/oidc/pom.xml
44:        <module>servlet-oauth-client</module>

adapters/oidc/servlet-oauth-client/pom.xml
29:    <artifactId>keycloak-servlet-oauth-client</artifactId>

distribution/adapters/wf8-adapter/wf8-modules/build.xml
72:        <module-def name="org.keycloak.keycloak-servlet-oauth-client">
73:            <maven-resource group="org.keycloak" artifact="keycloak-servlet-oauth-client"/>

distribution/adapters/wf8-adapter/wf8-modules/pom.xml
75:            <artifactId>keycloak-servlet-oauth-client</artifactId>

distribution/adapters/wf8-adapter/wf8-modules/src/main/resources/modules/org/keycloak/keycloak-servlet-oauth-client/main/module.xml
20:<module xmlns="urn:jboss:module:1.1" name="org.keycloak.keycloak-servlet-oauth-client">

distribution/adapters/wf8-adapter/wf8-adapter-zip/assembly.xml
41:                <include>org/keycloak/keycloak-servlet-oauth-client/**</include>

distribution/adapters/as7-eap6-adapter/as7-modules/build.xml
90:        <module-def name="org.keycloak.keycloak-servlet-oauth-client">
91:            <maven-resource group="org.keycloak" artifact="keycloak-servlet-oauth-client"/>

distribution/adapters/as7-eap6-adapter/as7-modules/pom.xml
139:            <artifactId>keycloak-servlet-oauth-client</artifactId>

distribution/adapters/as7-eap6-adapter/as7-modules/src/main/resources/modules/org/keycloak/keycloak-servlet-oauth-client/main/module.xml
20:<module xmlns="urn:jboss:module:1.1" name="org.keycloak.keycloak-servlet-oauth-client">

distribution/feature-packs/adapter-feature-pack/pom.xml
106:            <artifactId>keycloak-servlet-oauth-client</artifactId>

distribution/feature-packs/adapter-feature-pack/src/main/resources/modules/system/add-ons/keycloak/org/keycloak/keycloak-servlet-oauth-client/main/module.xml
20:<module xmlns="urn:jboss:module:1.3" name="org.keycloak.keycloak-servlet-oauth-client">
22:        <artifact name="${org.keycloak:keycloak-servlet-oauth-client}"/>

```

**Review by abstractj — CHANGES_REQUESTED** [review]
Please, see my comments in this PR.

**Comment by mposolda** [comment]
@abstractj The PR doesn't remove the servlet-oauth-client entirely, it just deprecates it for now. So it just removes the examples related to servlet-oauth-client from the keycloak-examples distribution, so people are not "guided" to use this in their app. And the java classes itself are deprecated due the backwards compatibility. Hopefully complete remove can be done in few more releases...

**Review by abstractj — APPROVED** [review]
@mposolda sorry, my bad.

**Comment by mposolda** [comment]
@abstractj Thanks!

**Pull request merged**
