### PR TITLE
KEYCLOAK-18308 Evaluate composite roles for hardcoded LDAP roles/groups

### LINKED ISSUE #11771: HardcodedLDAPRoleStorageMapper and HardcodedLDAPGroupStorageMapper ignore composite roles when checking whether user has role (was KEYCLOAK-18308)
### Describe the bug

We have configured a composite realm role `composite` which contains a client role `client-role`. We assign the `composite` to all LDAP users via the `HardcodedLDAPRoleStorageMapper`.

We have a custom authenticator which checks user roles via `UserModel.hasRole(role)`. 

### Version

16.0.0

### Expected behavior

We would expect `UserModel.hasRole(role)` to return `true` instead of `false`. It should respect the composition of roles even if the role is hardcoded.

### Actual behavior

`UserModel.hasRole(role)` always returns `false` when the given `role` is `client-role`.
However, we can see the `composite role` as well as the `client-role` in the role mappings tab beeing shown as effective.

### How to Reproduce?

- Create a client-role `client-role`
- Create a composite realm role `composite`
  - mark as composite
  - add the client role `client-role`
- Add a LDAP user federation
- Add `HardcodedLDAPRoleStorageMapper` to the user federation
  - Map realm role `composite` to all users
- Configure an authentication flow with `ConditionalRoleAuthenticator`
  - check for the client role `client-role`

Condition is never met, though all LDAP users have the client role assigned via the composite realm role.

### Anything else?

Similar behaviour can be observed with `HardcodedLDAPGroupStorageMapper`.

This clones [KEYCLOAK-18308](https://issues.redhat.com/browse/KEYCLOAK-18308)

### PR DESCRIPTION
**Pull request by sventorben**
I think this should fix KEYCLOAK-18308.
Happy for any advice on how to test this.

Closes #11771

### CODE REVIEW

**Comment by sventorben** [comment]
@mposolda may I ask you for some feedback on this, please?

**Comment by mposolda** [comment]
@sventorben Thanks and sorry for late review. The change itself looks good to me. The only missing part is the test. I suggest to add the scenario similar to the one you described in the JIRA. For configuration of custom authentication flow, I suggest to add some minimal flow with role condition (See for example BrowserFlowTest for the inspiration for how to easily create the custom authentication flow)

**Review by mposolda — CHANGES_REQUESTED** [review]
Marking as "Request changes" due the missing tests

**Comment by sventorben** [comment]
@mposolda Could you also point me to an example test for the LDAD side of the issue? I guess I would need to set up the federation somehow. 
And is there anything I should keep in mind regarding Quarkus? Any special testing strategies? I would prefer not to put any further legacy tests if there is such a thing.

**Comment by sventorben** [comment]
Hey @mposolda,
I added a test case for the role mapper. I did not follow your advice to take the `BrowserFlowTest` as an example. While I was looking for examples to setup LDAP, I have seen that there are already some tests for ldap mappers in place. I took them as an example and wrote the new test in a similiar way.

If that testing approach is ok for you, I can add a similar test for the group mapper. However, I would like to get your feedback first, before proceeding in a (possibly) wrong direction here.

**Comment by sventorben** [comment]
@mposolda I have added the missing test case.

Hint: Maybe the newly introduced map storage may have a similiar issue. For example. `MapGroupAdapter.hasRole(RoleModel)` simply calls `MapGroupAdapter.hasDirectRole(RoleModel)`.

**Comment by mposolda** [comment]
@sventorben Hmm... I am not sure if what you mentioned is the reason of failed test in the "undertow-map, group3" :-) But anyway, looks that this one needs to be fixed before we move forward with this PR.

**Review by mposolda — APPROVED** [review]
@sventorben Thanks!

**Pull request merged**
