### PR TITLE
[KEYCLOAK-14755] Update dependencies for package-lock.json file - Removal of unused file

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Comment by ssilvert** [comment]
@abstractj Don't we need to change a .gitignore?  It was my understanding that this is what cause package-lock.json to not be committed.  

I think we can just add this to /keycloak/themes/src/main/resources/theme/keycloak-preview/account/src/.gitignore

`!package-lock.json`

**Comment by ssilvert** [comment]
Oh, but actually that might not be the real problem.  Somewhere else there must be a .gitignore that includes package-lock.json.

**Comment by abstractj** [comment]
> Oh, but actually that might not be the real problem. Somewhere else there must be a .gitignore that includes package-lock.json.

@ssilvert  these are all the references to `package-lock.json`:

```
themes/pom.xml
91:                    <exclude>**/package-lock.json</exclude>

themes/UPDATING-NODE-MODULES.md
15:The node dependencies will be downloaded at build time, based on the content of `package-lock.json`. To update `package-lock.json`:
19:    git add package-lock.json
22:You should verify the new set of packages don't break anything before commiting the new `package-lock.json`. Do not commit the `node_modules` directory for the new account console.
```

Do you think we should add it to `.gitignore` ? Why?

**Comment by ssilvert** [comment]
> > Oh, but actually that might not be the real problem. Somewhere else there must be a .gitignore that includes package-lock.json.
> 
> @ssilvert these are all the references to `package-lock.json`:
> 
> ```
> themes/pom.xml
> 91:                    <exclude>**/package-lock.json</exclude>
> 
> themes/UPDATING-NODE-MODULES.md
> 15:The node dependencies will be downloaded at build time, based on the content of `package-lock.json`. To update `package-lock.json`:
> 19:    git add package-lock.json
> 22:You should verify the new set of packages don't break anything before commiting the new `package-lock.json`. Do not commit the `node_modules` directory for the new account console.
> ```
> 
> Do you think we should add it to `.gitignore` ? Why?

I just tried something.  I guess we don't need to do anything.  I thought that package-lock.json might not be tracked by git because of a .gitignore.  But it seems to be tracked OK.

**Review by ssilvert — APPROVED** [review]

**Comment by ssilvert** [comment]
Though I do have another question now.  Concerning the package-lock.json that is in keycloak-preview, how did that get changed without changing package.json?

**Comment by abstractj** [comment]
> Though I do have another question now. Concerning the package-lock.json that is in keycloak-preview, how did that get changed without changing package.json?

@ssilvert remove `packge-lock.json` and run `npm i`. Or run `npm i --package-lock-only`. Are you ok with these changes or would like another round of review?

**Comment by abstractj** [comment]
@ssilvert can we merge this?

**Pull request merged**
