### PR TITLE
Adding missing time offset resets for AuthenticationSessionTest and UserSessionPersisterProviderTest

### LINKED ISSUE #12530: unstable test SingleUseObjectModelTest.testActionTokens
### Describe the bug

This test seems to randomly fail. 

While the test is simple, it uses a time-offset. It might be that the initial time offset is not 0, but a different value.

### Version

999-SNAPSHOT

### Expected behavior

_No response_

### Actual behavior

Test should pass.

### How to Reproduce?

Unable to reproduce locally, it seems to fail randomly.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
also adding try/finally in other places where it was missing.

Closes #12530

### CODE REVIEW

**Review by hmlnarik — DISMISSED** [review]
These changes are an improvement, thank you!

**Comment by hmlnarik** [comment]
I don't think the model test failures are related, but would like to double check

**Comment by hmlnarik** [comment]
Thinking about it a bit more:

Could you add `Time.setOffset(0)` in the `@After` method?
https://github.com/keycloak/keycloak/blob/39cff0750cb82e0e11872373c0c91138640d715a/testsuite/model/src/test/java/org/keycloak/testsuite/model/KeycloakModelTest.java#L565-L571

**Comment by ahus1** [comment]
@hmlnarik - this is now ready for review. The earlier PR overwrite the wrong method, as there are two createEnvironment method, one with an one without parameter. 

This PR attempts to make the API safer to make the one that shouldn't be overwritten final.

**Review by hmlnarik — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
