### PR TITLE
KEYCLOAK-15595: update keycloak js for KEYCLOAK-15595

### PR DESCRIPTION
**Pull request by sanket-bhalerao**
while working on cordova+angular+ios the keycloak logout is not working. as the user clicks logout the user can again see the app instead of the inappbrowser page for login.
with clearcache=yes in the inappbrowser open the issue appears no more.

### CODE REVIEW

**Review by mhajas — DISMISSED** [review]
I tested this on Android and it seems it didn't break anything. Let's wait for ios review, but from my point of view, this looks good.

**Comment by sanket-bhalerao** [comment]
@mhajas any luck?

**Comment by abstractj** [comment]
@mhajas who is supposed to review the iOS part?

**Comment by mhajas** [comment]
@abstractj. I asked @vmuzikar yesterday and he told me he will try to have a look this week.

**Review by vmuzikar — DISMISSED** [review]
@sanket-bhalerao Thank you for your contribution and sorry for the late reply.

I can confirm this PR correctly fixes the issue. Tested it both on iOS simulator and a real iOS device. BTW, the issue was now reproducible even on the simulator (not just the real device like before).

**Comment by mhajas** [comment]
Thank you very much @vmuzikar! @abstractj Could you please run github actions workflow and then possibly merge?

**Comment by sanket-bhalerao** [comment]
@abstractj @mhajas @vmuzikar any luck?

**Comment by sanket-bhalerao** [comment]
@abstractj @mhajas @vmuzikar any luck?

**Comment by hmlnarik** [comment]
GH has not allowed running the checks, thus closing and reopening.

**Comment by abstractj** [comment]
@mhajas @hmlnarik tests were retriggered by it seems we have some failing tests.

**Comment by mhajas** [comment]
@abstractj I don't think this PR is causing any failures in Github actions as the code that is changed is not tested. Should we rebase to make the tests pass?

**Comment by abstractj** [comment]
@mhajas we have 2 options:

1. Ask @sanket-bhalerao to kindly rebase his PR
2. Take over this PR and open a new one

It is not possible for me to only rebase.

**Comment by sanket-bhalerao** [comment]
@abstractj @mhajas i have used fetch and merge option in the repository today. it included around 219 commits to my fork.
is this what you mean by rebase ?
image

**Comment by mhajas** [comment]
@sanket-bhalerao Thank you for updating the branch. Unfortunately, the fetch and merge functionality on Github doesn't work as we would like. We prefer having PRs with only one commit so this merge commit shouldn't be there. Could you please squash your commits together so that there is only one?

**Comment by sanket-bhalerao** [comment]
@mhajas i am not able to squash the commits, please let me know if i should create a new pull request ?

**Comment by mhajas** [comment]
You should be able to do it locally, just run 
```
git reset --soft HEAD~2 &&
git commit
```

then you need to do force push `git push -f`

**Comment by sanket-bhalerao** [comment]
@mhajas let me try..

**Comment by sanket-bhalerao** [comment]
@mhajas i think something is wrong with it now..
i followed the same 2 commands mentioned.. now its showing 1475 file modified..

**Comment by mhajas** [comment]
Ahhh, I am really sorry. That is my fault, it wasn't the best idea to do it. I can open a PR for you or if you want to send it yourself you can close this one and send a new PR based on the latest master. It is also possible to force push it to this branch but should be easier to send a new PR.

**Comment by sanket-bhalerao** [comment]
let me open a new PR..

**Comment by sanket-bhalerao** [comment]
@mhajas opened a new pull requst https://github.com/keycloak/keycloak/pull/8335.

**Pull request closed without merging**
