### PR TITLE
KEYCLOAK-15846 Upgrade locale dropdown to PF4

### PR DESCRIPTION
**Pull request by mabartos**
JIRA : [KEYCLOAK-15846](https://issues.redhat.com/browse/KEYCLOAK-15846)

### CODE REVIEW

**Comment by hmlnarik** [comment]
@mabartos Have you run UI tests on Jenkins?

**Review by ssilvert — APPROVED** [review]
LGTM

**Comment by Pepo48** [comment]
@mabartos @ssilvert @hmlnarik Hi guys, I was just finishing the review when I realized that this was already merged.

Anyway, I have couple of comments regarding this PR:
* design-wise it looks good for Firefox or Google Chrome but in it is broken (at least for me) in Internet Explorer 11, see:
image
I see that some IE compatibility tweaks were added but for some reason the dropdown background is not applied.
 
* not directly related to the design but some strings for certain languages are not translated:  
image
image
Should I create a separate JIRA for this? Let me know, thanks!

**Comment by ssilvert** [comment]
@Pepo48 Yes, create JIRAs.  The one about IE11 should be assigned to @mabartos.  

I suspect the ones about missing translations are unrelated to this PR.  But please create JIRAs for those as well.

**Pull request merged**
