### PR TITLE
KEYCLOAK-1135 add Realm name in email messages

### PR DESCRIPTION
**Pull request by jean-merelis**

### CODE REVIEW

**Comment by jean-merelis** [comment]
I did not change the file encode.

**Comment by stianst** [comment]
There are some changes to messages_de.properties which looks like changes to encoding to me. Is it caused by the way you're editing the files?

**Comment by jean-merelis** [comment]
I edited file in a the IDE. So, it added the encoded characters. Sorry.
But perhaps encode should be UTF-8. See the strange characters in this file:

https://github.com/keycloak/keycloak/blob/master/forms/common-themes/src/main/resources/theme/base/login/messages/messages_de.properties

**Comment by stianst** [comment]
ISO-8859-1 is fine as long as special characters are replaced, but messags_de.properties doesn't seem to be encoded correctly, nor does it seem to be correct in your PR or in messages_pt-BR.

I've configured IntelliJ to use ISO-8859-1 and to convert native-to-ascii. It then changes for example ü to \u00FC, which according to http://en.wikipedia.org/wiki/ISO/IEC_8859-1 is correct.

In messages_de.properties native characters are not converted and in messages_pt-BR they are converted, but the code uses lower case (for example \u00fc, which isn't correct going from the above).

Do you both agree with this? If so I can sort out the correct encoding after merging this PR.

**Comment by stianst** [comment]
Another thing to check is if the generated HTML contains UTF-8 as it should and not ISO-8859-1. Or maybe the simpler and better solution is to just go with UTF-8 everywhere!?!

**Comment by jean-merelis** [comment]
I think the best solution is to just go with UTF-8 everywhere

**Comment by gerbermichi** [comment]
So we better change everything to UTF8 :-) that would make everything easier.

**Comment by stianst** [comment]
There's actually not a trivial way to load properties using UTF-8, and also we have other properties files with ISO-8859-1 and I don't want to convert those as well. So we're sticking with the default (ISO-8859-1).

**Comment by jean-merelis** [comment]
If you want to, I can convert the properties files to UTF-8

**Comment by stianst** [comment]
Let's just stick with ISO-8859-1 as that's the default for Java properties files

**Pull request merged**
