### PR TITLE
Update LDAPOperationManager.java

### LINKED ISSUE #9560: LDAP connection timeout is treated as login failure and brute force locking the user
### Describe the bug

Hi Team,

Recently we are facing an issue with Brute Force and LDAP integration. 

We have set QuickLoginMilliSec in Brute force settings page to 1ms and we run some health check scripts on the keycloak pods which makes some rest calls. As LDAP is integrated, the users get authenticated with LDAP calls and when there is a connection timeout in LDAP, that is treated as Login Error, and eventually when there are 2 LDAP connection timeouts in 1ms, the user is getting temporarily locked. The scripts after retrying for few secs, they are aborting its execution.

As we understand those very LDAP connections are timed out, keycloak should be able to handle it gracefully by not treating ConnectionTimout exception as a LoginError and lock the user.

In LDAPOperationManager.java, Exception handling should have been more robust. For this we are planning to make some changes like throwing a RuntimeException in 

authenticate() method. Would you be accepting the change to resolve our issue till the time exception handling has been made robust. Thoughts please!!

 

Code Snippet:

/**

     * <p>

     * Performs a simple authentication using the given DN and password to bind to the authentication context.

     * </p>

     *

     * @param dn

     * @param password

     * @throws AuthenticationException if authentication is not successful

     *

     */

    public void authenticate(String dn, String password) throws AuthenticationException  {

 

        if (password == null || password.isEmpty())

{             *throw* *new* AuthenticationException("Empty password used");         }
 

        LdapContext authCtx = null;

        StartTlsResponse tlsResponse = null;

 

        try {

 

            Hashtable<Object, Object> env = LDAPContextManager.getNonAuthConnectionProperties(config);

 

            // Never use connection pool to prevent password caching

            env.put("com.sun.jndi.ldap.connect.pool", "false");

 

            if(!this.config.isStartTls())

{                 env.put(Context.*_SECURITY_AUTHENTICATION_*, "simple");                 env.put(Context.*_SECURITY_PRINCIPAL_*, dn);                 env.put(Context.*_SECURITY_CREDENTIALS_*, password);             }
 

            authCtx = new InitialLdapContext(env, null);

            if (config.isStartTls()) {

                SSLSocketFactory sslSocketFactory = null;

                String useTruststoreSpi = config.getUseTruststoreSpi();

                if (useTruststoreSpi != null && useTruststoreSpi.equals(LDAPConstants.USE_TRUSTSTORE_ALWAYS))

{                     TruststoreProvider provider = session.getProvider(TruststoreProvider.*class*);                     sslSocketFactory = provider.getSSLSocketFactory();                 }
 

                tlsResponse = LDAPContextManager.startTLS(authCtx, "simple", dn, password.toCharArray(), sslSocketFactory);

 

                // Exception should be already thrown by LDAPContextManager.startTLS if "startTLS" could not be established, but rather do some additional check

                if (tlsResponse == null)

{                     *throw* *new* AuthenticationException("Null TLS Response returned from the authentication");                 }
            }

        } catch (AuthenticationException ae) {

            if (logger.isDebugEnabled())

{                 *_logger_*.debugf(ae, "Authentication failed for DN [%s]", dn);             }
 

            throw ae;

        } catch(RuntimeException re) {

        if (logger.isDebugEnabled())

{         *_logger_*.debugf(re, "Connection timeOut exception for DN [%s]", dn);         }
        throw re;

        }

        catch (Exception e)

{             *_logger_*.errorf(e, "Unexpected exception when validating password of DN [%s]", dn);             *throw* *new* AuthenticationException("Unexpected exception when validating password of user");         }
        finally {

            if (tlsResponse != null) {

                try

{                     tlsResponse.close();                 }
catch (IOException e)

{                     e.printStackTrace();                 }

            }

 

            if (authCtx != null) {

                try {                     authCtx.close();                 } catch (NamingException e) {                     e.printStackTrace();                 }
            }

        }

    }

### Version

11.0

### Expected behavior

Exception handling in case of LDAP Connection TimeOuts should be robust.

### Actual behavior

_No response_

### How to Reproduce?

Enable Brute Force in Keycloak
Integrate LDAP and create some users.
Introduce some network delay or mock no response from LDAP.
Make some concurrent requests with the same user.
Observe the user locked and temporarily disabled in keycoak.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pravsjv**
Github JIRA number  for a detailed description of the issue :
https://github.com/keycloak/keycloak/issues/9560

### CODE REVIEW

**Comment by mposolda** [comment]
@pravsjv Your code seem fail to compile. Can you please use `debug` method with correct arguments?

**Review by mposolda — CHANGES_REQUESTED** [review]
@pravsjv Your code seem fail to compile. Can you please use debug method with correct arguments?

**Comment by pravsjv** [comment]
> @pravsjv Your code seem fail to compile. Can you please use debug method with correct arguments?

corrected debug method to debugf. Now the build should run. Thanks!!

**Review by mposolda — APPROVED** [review]
@pravsjv Thanks!

**Comment by bohmber** [comment]
@mposolda I think the fix is not correct.

```
XX-YY-ZZZZ 10:08:13,264 ERROR [org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager](default task-5) Unexpected exception when validating password of DN [XYZ]: javax.naming.CommunicationException: ZZZ:YYY [Root exception is java.net.ConnectException: Connection refused (Connection refused)]
XX-YY-ZZZZ 17:32:25,927 ERROR [org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager](default task-30) Unexpected exception when validating password of DN [XYZ]: javax.naming.CommunicationException: ZZZ:YYY [Root exception is java.net.UnknownHostException: ZZZ:YYY]
```

A `javax.naming.CommunicationException` is thrown by ldap lib. The fix might be valid in the startTLS case but in our case the fix is not handling the `CommunicationException` correctly


A 
```
} catch (CommunicationException ce) {
    throw new RuntimeException(ce);

```
might be needed:

**Pull request merged**
