### PR TITLE
KEYCLOAK-5098 - adapter for spring boot 2

### PR DESCRIPTION
**Pull request by ryandawsonuk**
Spring boot 2.0.0 is in M2 at the time of writing but this is tested and working with Jetty and Undertow.

It's not working as expected with Tomcat (the embedded 8.5.4). Currently the Tomcat redirect uris hit the keycloak server encoded and hence get rejected by RedirectUtils.verifyRedirectUri. This appears to be a boot2 issue as we're just applying the same configuration in the same way and there haven't been any relevant updates in the boot documentation on this - compare https://docs.spring.io/spring-boot/docs/1.5.4.RELEASE/reference/htmlsingle/#boot-features-customizing-embedded-containers with https://docs.spring.io/spring-boot/docs/2.0.0.M2/reference/htmlsingle/#boot-features-customizing-embedded-containers.

The adapter is just a copy of the existing boot 1 adapter but adjusted for the changes in boot 2 (see details in https://issues.jboss.org/browse/KEYCLOAK-5098). A starter has also been added.

### CODE REVIEW

**Comment by stianst** [comment]
Does Spring 2 really need a new adapter? Would be much better if the old one can just support Spring 2 as well if that's possible.

**Comment by ryandawsonuk** [comment]
The boot classes used in the KeyCloakAutoConfiguration class have all changed but I think it's possible (though I haven't tried it). I think you could have two versions of that class (or methods within it) with the one used determined by a ConditionalOnExpression condition on ${spring-boot.version} (or pick a class that is specific to 2 and do a @ConditionalOnClass). The boot 1 and 2 classes would need to be imported and this could be used to switch between which is used. I thought it would be cleaner to have separate adapters and noticed that there are already separate adapters for different versions of application servers so thought it better to follow the same approach.

**Comment by sebastienblanc** [comment]
Let me ask the Spring Boot / Pivotal team what is the best approach.

**Comment by Salaboy** [comment]
@sebastienblanc 👍 

@stianst Not sure if having just 1 adapter make sense. Spring Boot 1 and 2 will carry a completely different set of dependencies and trying to just have one module to deal with those will require a complicated configuration. I think that is similar to tomcat 7 and 8, they require to have two different adapter modules.

**Comment by sebastienblanc** [comment]
So I discussed with Stéphane from the Spring Boot Team and he agreed that we should have a separate adapter and we will have to decide at which version of Keycloak we will make it the default one (probably around between Spring Boot 2 will be final and the KC release coming after this). 
But until then, and since 90% of the code is similar I would like to propose the following : We should create a library `spring-boot-adapter-core` containing all the duplicate code and the 2 adapters will depend on this. This will make the maintenance easier.

**Comment by Salaboy** [comment]
+1

**Comment by ryandawsonuk** [comment]
Makes sense to me. I'm happy to create a spring-boot-adapter-core library.

**Comment by sebastienblanc** [comment]
Hum looks like went wrong with these commits , was it a failed attempt to rebase ;) ?

**Comment by ryandawsonuk** [comment]
Yep

**Comment by ryandawsonuk** [comment]
I think I might create a new PR for the changes

**Comment by ryandawsonuk** [comment]
Replaced with https://github.com/keycloak/keycloak/pull/4325

**Pull request closed without merging**
