### PR TITLE
Limit paths for running the operator CI

### PR DESCRIPTION
**Pull request by andreaTP**
This is the implementation of the path whitelist discussed in #9927 for the operator CI.

The operator CI will run only if something gets modified under those specific paths.

cc. @hmlnarik @vmuzikar

### CODE REVIEW

**Review by vmuzikar — CHANGES_REQUESTED** [review]
I'm not comfortable with this solution. Can we be sure only this paths affect Operator (combined with Quarkus dist etc.)? The operator tests are not taking that much time now, at least for now. So I'd avoid limiting it just yet.

**Comment by andreaTP** [comment]
The current CI is taking about 5/6 minutes, and, you are right, this list of included paths needs to be maintained over time.

**Review by stianst — CHANGES_REQUESTED** [review]
Operator tests should at the very least also be executed if the Quarkus distribution, or container changes.

With its execution test being so low at the moment. This is also probably not the first place to optimise.

Let's discuss this through:
https://github.com/keycloak/keycloak/discussions/9947

**Comment by andreaTP** [comment]
> This is also probably not the first place to optimise.

I opened this mostly to show how this might look like, I agree this is not the biggest pain-point.

> Operator tests should at the very least also be executed if the Quarkus distribution, or container changes.

I like this one! Now we can build the Keycloak docker image locally(to this repo) and check everything all together. ( cc. @vmuzikar )

**Pull request closed without merging**
