### PR TITLE
KEYCLOAK-7997 Implement Client Registration Metadata based on Mutual TLS

### PR DESCRIPTION
**Pull request by tnorimat**
This PR is for https://issues.redhat.com/browse/KEYCLOAK-7997 .

### CODE REVIEW

**Review by slaskawi — COMMENTED** [review]
The code itself looks good to me.

I'm just thinking, perhaps we should add some more tests. The `
2.1.1.  PKI Authentication Method Metadata Value` spec ([link](https://tools.ietf.org/html/draft-ietf-oauth-mtls-07#section-2.1.1)) says:

> The values are used (...) authentication methods in authorization server metadata, such as OpenID Connect Discovery (...) OAuth 2.0 (...) Authorization Server Metadata (...), and in the OAuth 2.0 Dynamic Client Registration Protocol

Personally, I would love to see at least one more test that also checks if proper parameters are exposed in our well-known endpoint. @stianst WDYT?

**Comment by tnorimat** [comment]
@slaskawi As for the server metadata for PKI Authentication Method, I've already implemented and been merged (https://github.com/keycloak/keycloak/pull/6351). This PR has implemented the test for checking whether our well-known endpoint returns "tls_client_auth".

As for the client metadata "token_endpoint_auth_method" mentioned in OAuth 2.0 Dynamic Registration (https://tools.ietf.org/html/rfc7591#section-2), I've added the test checking whether the method "tls_client_auth" defined in IANA Registry of OAuth Token Endpoint Authentication methods (https://www.iana.org/assignments/oauth-parameters/oauth-parameters.xhtml#token-endpoint-auth-method) can be set by Dynamic Registration.

**Review by slaskawi — APPROVED** [review]
@tnorimat Ok, thanks for clarification! LGTM!

**Review by mposolda — APPROVED** [review]
@tnorimat @slaskawi Thanks for the PR and sorry for the late review

**Pull request merged**
