### PR TITLE
don't close the dropdown when clicking next or previous

### PR DESCRIPTION
**Pull request by edewit**
related: #33616
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

### CODE REVIEW

**Review by jonkoops — DISMISSED** [review]
Needs an issue linked

**Comment by edewit** [comment]
@jonkoops it has

**Review by agagancarczyk — APPROVED** [review]
LGTM!

**Comment by jonkoops** [comment]
It does not
image

**Comment by edewit** [comment]
@jonkoops it references an issue, but it doesn't close it... as it is not reproducible

**Pull request merged**
