### PR TITLE
KEYCLOAK-19731: Make password field autofocus on login form, fixes #10027

### LINKED ISSUE #10027: Focus on the password field when using separate pages for username and password
### Describe the bug

Hi,

We have configured the login flow on our keycloak instance in all realms to use Webauthn.
The flow we use for this looks as so:

image

When users go to login, after entering their username, and clicking the login button, they are taken to the password form.

On the password form, the page loads up without the password field in focus. Users have to click on it in order to enter their password.

We have a feature request from a user asking to make it automatically focus on the password field on this form.

### Version

16.1.1

### Expected behavior

The password field will be automatically selected

### Actual behavior

The password field must be clicked on in order to put focus on it so that the user can enter their password

### How to Reproduce?

Configure a flow as per the screenshot above (optionally without the webauthn authentication -- the important part is the username and password fields being on separate forms), and then login to the realm where the flow is configured.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by d2a-raudenaerde**
As user I would like to be able to directly type my password in a flow where I have a username form, followed by a password form. fixes #10027

### CODE REVIEW

**Review by MPParsley — COMMENTED** [review]
I really like this feature but note that there's an accessibility implication when you send users to a part of a page without context.

See https://medium.com/@gavyn/til-autofocus-inputs-are-an-accessibility-problem-32ced60c3109

**Review by mabartos — DISMISSED** [review]

**Comment by ahus1** [comment]
With the listed resources about accessibility I close this issue. @ssilvert - as you're the one involved with UIs, please feel free to intervene and override. 

If there is additional evidence from accessibility resources, please provide them here to re-open the issue.

**Comment by ssilvert** [comment]
@ahus1 I think this was the right decision.

**Comment by mabartos** [comment]
Opened again, because I think it's a relevant issue, which could be solved. See the comment ^^ above.

@ssilvert Could you please check this PR once again? Thank you.

**Comment by mabartos** [comment]
@d2a-raudenaerde Could you please create a GH issue for this and link the issue number to the commit description? Or you can link this PR with issue #10027. Thank you.

**Comment by ahus1** [comment]
@mabartos - thank you for this additional input and re-opening it. Thinking about this from a "context" angle might make it work.

**Comment by d2a-raudenaerde** [comment]
See also: #10027

**Comment by mabartos** [comment]
@d2a-raudenaerde Please update the commit message, not the PR title. Sth like this: `git commit -m "Make password field autofocus" -m "Closes #10027"`. Thank you

**Comment by ssilvert** [comment]
> Opened again, because I think it's a relevant issue, which could be solved. See the comment ^^ above.
> 
> @ssilvert Could you please check this PR once again? Thank you.

I don't have any particular expertise in the area of screen readers.  If you guys conclude that it's really not an issue then I'm fine with it.

Also, the UI team is not yet in charge of the login theme, so it's really not my call.

**Comment by mabartos** [comment]
I can confirm that everything's working as expected from my POV. I tried to test it with _axe DevTools - Web Accessibility Testing_ tool and _Screen reader_ extension provided by Chrome itself.

@d2a-raudenaerde Could you please update the commit message?

**Comment by mabartos** [comment]
@d2a-raudenaerde Please, squash these commits and provide a correct commit message with a commit description mentioned above. 

Hint: You can amend the commit
```
git commit --amend
```
and then edit the commit message as follows:
```
Make password field autofocus on login form

Closes #10027
```

**Review by ahus1 — DISMISSED** [review]
Ready to be merged as long as it is being squashed on merge.

**Comment by ahus1** [comment]
@d2a-raudenaerde - thanks for updating the commit as @mabartos asked you to. One step that didn't work out: the changes then need to be force-pushed to the branch of the pull request. Without that, this PR still lists 5 commits, when it should show only one (see screen shot below).
 
image

**Comment by ahus1** [comment]
@d2a-raudenaerde - force-push, well done! I'll re-open the PR!

**Review by ahus1 — APPROVED** [review]

**Review by mabartos — APPROVED** [review]

**Pull request merged**
