### PR TITLE
Remove session related caches from external Infinispan in HA guide

### LINKED ISSUE #32131: Remove session related caches from external Infinispan in HA guide
It is also necessary to add removal of sessions to the migration guide for users that are using previous version of MULTI_SITE

### PR DESCRIPTION
**Pull request by pruivo**
Closes #32131

### CODE REVIEW

**Comment by ahus1** [comment]
@pruivo - thank you for the changes, they look good to me. 

I saw that you added additional information with background information and configuration alternatives. I wrapped this into a block so people know it is an optional/advanced setup. I also added some sentences with items from our previous discussions that I thought would be worth adding here. 

Side note: If we describe these options in the docs as alternative, they are all fully supported. Just saying :-)

Please review my changes, and then it should be good to be merge. Thanks again!

**Comment by pruivo** [comment]
@ahus1 I've removed the async stuff. I feel I'm shooting myself in the foot if we keep them :rofl:
I added a sentence about the strategy; let me know what you think, I can squash and re-push the commits.

**Review by ahus1 — APPROVED** [review]
Thank you for the changes, and reconsidering what we want to support. I'm approving the changes and squash the changes on merge (no need to squash them in the PR).

**Comment by tormodatt** [comment]
Thank you for the quick and detailed response!

I have a use-case for sessions in external infinispan with HA:

We were planning to do a multi-site setup, but where each Keycloak instance has their own DB. The users are stored externally in a seperate DB both Keycloak instances have access to.

The use case for this is to be able to run Terraform on the passive instance, and verify that before making it active. With many realms Terraform apply might fail or make Keycloak unresponsive with certain changes. When sessions were stored in the external infinspan the idea was that we could switch the traffic over without users getting logged out, and even a gradual switch given sticky sessions.

This would also enable us to upgrade major version on the passive instance (from kc 26 with Infinispan Protostream).

**Comment by ahus1** [comment]
The setup you share is non-standard and not supported. I don't know how you store the users in the external database. Maybe you can use the same database where you store the users to also store the sessions. 

In the meantime, @pruivo, please create an epic where we track the changes related to "cacheless" set, which IMHO should include at least #32270, https://github.com/keycloak/keycloak-benchmark/pull/971 and (as usual) doing performance tests and writing docs.

**Comment by ahus1** [comment]
> make Keycloak unresponsive with certain changes

Can you please elaborate on this part? Sounds like a Keycloak bug - or is is related to different entities being changed in independent transactions, and due to that having a time when the configuration is inconsistent?

**Comment by pruivo** [comment]
@tormodatt I'm not sure if I understood your architecture. So, you have 3 database instances? 1 shared (users) and 2 privates (one for each Keycloak cluster). How do you keep the "private" databases in sync? Because the passive cannot take over with an empty database. 

As @ahus1 mentioned, the feature is very new and requires the latest Infinispan release. I can guide you through the configuration if you want to try it in a *STAGE* environment. I *DO NOT* recommend it in production until we do more testing (although, I have 100% confidence in my coding skill and it is 100% bugfree :rofl:. Just kidding).

**Comment by pruivo** [comment]
> In the meantime, @pruivo, please create an epic where we track the changes related to "cacheless" set,

@ahus1 Epic created: https://github.com/keycloak/keycloak/issues/33658
ps. `cacheless`!?

**Comment by tormodatt** [comment]
> The setup you share is non-standard and not supported

I know, I was hoping that it would be become a supported case in kc 26, but I understand you went a different path 😄 

> Can you please elaborate on this part?

We have a complex setup, if we run with default concurrency Terraform DDoS'es Keycloak. It can be somewhat mitigated with setting parallelism to 1, and some other customizations but it is still not perfect. To give you an idea, from a clean DB it takes about 1 hour to complete. We usually apply only small changes, but some changes will create a lot of calls in our setup. I'd be much more comfortable to run some of them on a passive instance.

Yes, we have 3 databases. 1 (private) for each Keycloak instance, and the third is for a custom User Storage Provider. Is there a concept like that for sessions too?

As for syncing the keycloak databases, we use Terraform for the config (realms, clients etc) that we apply on both instances. The users we don't need to sync as those are only stored one place. The remaining part is the sessions, which we planned to have synced in the external Infinispan.

The "clusterless"(?) thing sounds very interessting. That will store user sessions in external Infinispan only? I'd be happy to test it out @pruivo

**Comment by ahus1** [comment]
> Yes, we have 3 databases. 1 (private) for each Keycloak instance, and the third is for a custom User Storage Provider. Is there a concept like that for sessions too?

There is the `UserSessionPersisterProvider` that you can override with your own implementation. The default is the `JpaUserSessionPersisterProvider`. It is a private API, and you might need to track changes to the JPA implementation to stay up-to-date with what it provides. Not sure if someone has tried that one before, and there might be challenges ahead. An alternative might be to use a DB link between the local and the share database for the relevant tables, but that comes with its own caveats.

**Comment by pruivo** [comment]
> The "clusterless"(?) thing sounds very interessting. That will store user sessions in external Infinispan only? I'd be happy to test it out @pruivo

@tormodatt Yes, that's right. Could you open a discussion and ping me? I'm assuming that you're not using Openshift, so I'm going to need a description of your architecture (clusters, networks). Most configuration is hardcoded and some architectures may not be possible. 

If I may, I'm not a fan of the private database instances for each cluster. It adds complexity, probably costs too and it is complex to maintain. Using a single database simplifies your operations too.

**Comment by tormodatt** [comment]
thanks @ahus1 , I'll look into `UserSessionPersisterProvider` too

**Pull request merged**
