### PR TITLE
KEYCLOAK-4640: LDAP memberships are being replaced instead of being added or deleted

### PR DESCRIPTION
**Pull request by rmartinc**
Tentative fix for KEYCLOAK-4640 (also includes some changes for covering range attribute retrieval: KEYCLOAK-8525). I suppose we are going to need some cycles for this, but we have to start with something.

### CODE REVIEW

**Comment by mposolda** [comment]
@rmartinc The PR looks good to me, but I think that we will rather need to re-test with our LDAP servers matrix to doublecheck that backwards compatibility is not broken. Adding @pdrozd as reviewer.

**Review by mposolda — DISMISSED** [review]

**Comment by mposolda** [comment]
@rmartinc Could you please rebase this PR?

**Review by mposolda — DISMISSED** [review]

**Comment by rmartinc** [comment]
Rebased! It was a clean too.

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by pdrozd** [comment]
There are some failures with Active Directory - probably not related to this PR, but have to investigate more.

**Comment by pdrozd** [comment]
@rmartinc I'm not able to run the newly added tests without failures with AD. Do you know which property should I change to set the max range to 10?

**Comment by rmartinc** [comment]
@pdrozd I think that the minimum range in AD is 30. You have to change it following [this MS note ](https://support.microsoft.com/en-us/help/315071/how-to-view-and-set-ldap-policy-in-active-directory-by-using-ntdsutil), the Modifying policy settings section and configure the `MaxValRange` limit. I suppose that `test08` fails but `test09` is OK. If you want I can modify the tests to work with 30 instead of 10 as the limit value in the simulated range retrieval in internal apache-ds (to make both situations, apache-ds and AD, the same).

**Comment by pdrozd** [comment]
@rmartinc Thanks, I was changing MaxValRange attribute - the strange thing is that I was able to update it to 10, but if the minimum is 30, may be it didn't work correctly. I will test it with 30, thanks a lot!

**Comment by rmartinc** [comment]
@pdrozd OK, you have to change the members to test [here](https://github.com/keycloak/keycloak/blob/656c46dff2bfc880a41da6aadf8aab79fb813c66/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java#L699). Set it to more than 30, I used 25 (10+10+5) to test more than two pages, for example you can set it to 61 (30+30+1).

**Comment by pdrozd** [comment]
Thanks @rmartinc It works correctly with 61 users. Can you change the PR to create 61 users as you suggested?

**Comment by rmartinc** [comment]
Ok @pdrozd, I have changed to have a simulated page size of 30 and the test now uses 61 members (it worked locally). This change:

```patch
diff --git a/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java b/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
index 253b159881..e52eb368f9 100755
--- a/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
+++ b/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
@@ -696,7 +696,7 @@ public class LDAPGroupMapperTest extends AbstractLDAPTest {
     @Test
     public void test08_ldapOnlyGroupMappingsRanged() {
         testingClient.server().run(session -> {
-            int membersToTest = 25; // the paged search is defined to 10 => 3 searches
+            int membersToTest = 61; // try to do 3 pages (30+30+1)
             LDAPTestContext ctx = LDAPTestContext.init(session);
             RealmModel appRealm = ctx.getRealm();
 
diff --git a/util/embedded-ldap/src/main/java/org/keycloak/util/ldap/InMemoryDirectoryServiceFactory.java b/util/embedded-ldap/src/main/java/org/keycloak/util/ldap/InMemoryDirectoryServiceFactory.java
index 3147c091e8..2b324694ca 100644
--- a/util/embedded-ldap/src/main/java/org/keycloak/util/ldap/InMemoryDirectoryServiceFactory.java
+++ b/util/embedded-ldap/src/main/java/org/keycloak/util/ldap/InMemoryDirectoryServiceFactory.java
@@ -57,7 +57,7 @@ import org.apache.directory.server.core.normalization.NormalizationInterceptor;
 class InMemoryDirectoryServiceFactory implements DirectoryServiceFactory {
 
     private static final Logger log = Logger.getLogger(InMemoryDirectoryServiceFactory.class);
-    private static final int PAGE_SIZE = 10;
+    private static final int PAGE_SIZE = 30;
 
     private final DirectoryService directoryService;
     private final PartitionFactory partitionFactory;
```

**Comment by pdrozd** [comment]
@keycloak-ci-bot test

**Review by pdrozd — APPROVED** [review]

**Review by mposolda — APPROVED** [review]

**Comment by hmlnarik** [comment]
@keycloak-ci-bot test

**Pull request merged**
