### PR TITLE
KEYCLOAK-8155 

### PR DESCRIPTION
**Pull request by snicoll**
Use Spring Boot autoconfigure-processor to optimize auto-configurations

### CODE REVIEW

**Comment by stianst** [comment]
I'm not that familiar with Spring Boot myself, but seems like rather than adding this as an optional dependency to our POMs, its something that should be added to your own application if you want the capabilities provided by spring-boot-autoconfigure-processor?

**Comment by snicoll** [comment]
@stianst No. Have you looked at the issue's description on Jira?

**Comment by stianst** [comment]
@snicoll I did, but only a quick glance. So seems fine by me, but @sebastienblanc will have to review this as well.

**Review by sebastienblanc — APPROVED** [review]
This is good to go, @snicoll I assume, looking at your jira, that we also need it here https://github.com/keycloak/keycloak/blob/master/adapters/oidc/spring-boot/pom.xml , correct ?

**Comment by snicoll** [comment]
Thanks for the feedback. You are correct, I missed that module. Basically, any module that provides an auto-configuration should be included.

**Pull request merged**
