### PR TITLE
Translate the front channel logout screens into Japanese (#13296)

### LINKED ISSUE #13296: The front channel logout screens are not translated into Japanese
### Describe the bug

The logout consent and logout completion screens at front channel logout are not translated into Japanese.
file_3H87aI6zG
file_sT_GH6bfI

### Version

18.0.2

### Expected behavior

Displayed in Japanese.

### Actual behavior

Displayed in English.

### How to Reproduce?

non-response

### Anything else?

non-response

### PR DESCRIPTION
**Pull request by okuura**
Fixes #13296

### CODE REVIEW

**Comment by okuura** [comment]
@wadahiro 
Could you please review this PR?

**Review by wadahiro — APPROVED** [review]
LGTM

**Review by tnorimat — APPROVED** [review]
LGTM.

**Review by hmlnarik — APPROVED** [review]
Approving per @tnorimat 's approval. Thank you for the PR!

**Pull request merged**
