### PR TITLE
KEYCLOAK-5896: Parameter "ui_locales" not redirected to login page in java adapters

### PR DESCRIPTION
**Pull request by rmartinc**

### CODE REVIEW

**Comment by mposolda** [comment]
@rmartinc Looks good, but needs also the automated test as we discussed in the email.

**Comment by rmartinc** [comment]
@mposolda One question... I'm not sure if I just need to check that the parameter is in the login URL or even check that the login page comes in the required language.

I have done both but I need to change the `demorealm.json` to add the internationalization configuration to the domain:

    "internationalizationEnabled": true,
    "supportedLocales": [ "en", "de" ],
    "defaultLocale": "en",

My test is something like the following:

        // test login with ui_locales to de+en
        String portalUri = securePortal.getUriBuilder().build().toString();
        String appUri = securePortal.getUriBuilder().queryParam(OAuth2Constants.UI_LOCALES_PARAM, "de en").build().toString();
        URLUtils.navigateToUri(appUri, true);
        assertCurrentUrlStartsWithLoginUrlOf(testRealmPage);
        // chek the ui_locales param is there
        Map<String, String> parameters = getQueryFromUrl(driver.getCurrentUrl());;
        assertNotNull(parameters.get(OAuth2Constants.UI_LOCALES_PARAM));
        assertEquals("de en", parameters.get(OAuth2Constants.UI_LOCALES_PARAM));
        // check that the page is in german
        String pageSource = driver.getPageSource();
        assertTrue(pageSource.contains("Passwort"));
        testRealmLoginPage.form().login("bburke@redhat.com", "password");
        // check no ui_locales in the final url adapter url
        assertCurrentUrlEquals(portalUri);
        pageSource = driver.getPageSource();
        assertTrue(pageSource.contains("Bill Burke") && pageSource.contains("Stian Thorgersen"));

Everything is working (the rest of tests I mean).  What do you think?

**Comment by mposolda** [comment]
@rmartinc The test for checking that loginPage is in required language is good. Like you have. Cool!

Adding the locale to demorealm.json works. There is also a (maybe better) way to enable locale programmaticaly through the admin client and then revert it back. For example something like used here: https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/AbstractDemoServletsAdapterTest.java#L314-L317 . However as long as any existing tests are not broken, then edit of demorealm.json should be fine.

**Comment by rmartinc** [comment]
Added the test. Finally I decided to just modify the test (not the realm definition). Thanks for all the info.

**Pull request merged**
