### PR TITLE
Add missing equals in reverseproxy.adoc

### PR DESCRIPTION
**Pull request by LelouBil**
I added the required equals in the first command line examples.

### CODE REVIEW

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@LelouBil Hello, thank you for the contribution!

It is possible to use as the key-value separator either `=` or a space. Are you observing any issues when space is used?

Also each PR needs to be linked to an Issue. Could you please create one? See our [contribution guidelines](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md).

**Comment by LelouBil** [comment]
I was having issues using the "command" argument in docker compose but it just occurred to me this might be because it does argument splitting manually, and I had one argument with "--proxy-headers forwarded" where I assume keycloak wants 2 different argument without spaces.

So I can just close this then ?

**Comment by ahus1** [comment]
> So I can just close this then ?

Yes, I'd think so.

**Comment by vmuzikar** [comment]
> So I can just close this then ?

Yeah, let's close it. Thank you.

**Pull request closed without merging**
