### PR TITLE
KEYCLOAK-3660: Cancel button doesn't work on execution's config page

### PR DESCRIPTION
**Pull request by ssilvert**

### CODE REVIEW

**Comment by stianst** [comment]
This will make it inconsistent with other forms. All other forms have save and cancel. Cancel will reset the form if editing a current entity or go back to the list if creating a new entity. That may not be the ideal and that can be discussed in the future, but for now don't introduce additional buttons on some forms which will then make them inconsistent.

**Comment by ssilvert** [comment]
The other problem is that in several places the button labeled "Cancel" is really a "Reset".  In those places it makes more sense because there is no previous page to go back to.  But IMO, they should be labeled "Reset".

But if we do nothing here then we still haven't solved the problem where the only way to get back to the previous screen is to use the breadcrumbs.  This particular page seems to be unique in that you need both a "Reset" and a "Cancel and navigate back".

**Comment by ssilvert** [comment]
Stian, do you want this to be fixed?  If so, what do you want it to do?

Also see https://issues.jboss.org/browse/RHSSO-336

**Comment by ssilvert** [comment]
Stian, do you want this to be fixed?  If so, what do you want it to do?

Also see https://issues.jboss.org/browse/RHSSO-336

**Comment by stianst** [comment]
Actually let's just reject it. I agree it's not nice that the only way back is via breadcrumbs, but that's the case pretty much everywhere.

**Pull request closed without merging**
