### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Keycloak/Admin UI](https://hosted.weblate.org/projects/keycloak/admin-ui/).

It also includes following components:

* [Keycloak/Theme base/account](https://hosted.weblate.org/projects/keycloak/theme-baseaccount/)

* [Keycloak/Theme base/admin](https://hosted.weblate.org/projects/keycloak/theme-baseadmin/)

* [Keycloak/Theme base/login](https://hosted.weblate.org/projects/keycloak/theme-baselogin/)

* [Keycloak/Theme base/email](https://hosted.weblate.org/projects/keycloak/theme-baseemail/)

* [Keycloak/Account UI](https://hosted.weblate.org/projects/keycloak/account-ui/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by jonkoops — DISMISSED** [review]

**Review by jonkoops — DISMISSED** [review]

**Review by ahus1 — DISMISSED** [review]

**Comment by ahus1** [comment]
@jonkoops @thomasdarimont @robson90 - I see that the tests fail, I need to look into this next week if some tests depend on translations.

I also see that the German language now has a translation of all other languages. AFAIK the English language has entries for each language in the language's own writing, which would indicate not to translate those entries. If we choose to not translate them, we should better move those strings to a different file. Still this is open for discussion: in an admin UI it would make sense to translate the languages if they are presented to an admin to select them. If they are presented to a user in the login page, it would be good not to translate them as a user might not recognize their language in the current UI's language. (I am currently unable to look at the UIs, so I might be wrong here, will do that next week). 

Happy to hear your thoughts. While the build breaks and with the question I raised about the language names, I ask you to slow down the translation a bit and wait for this PR to be merged. I assume we will resolve this next week.

**Comment by jonkoops** [comment]
> I also see that the German language now has a translation of all other languages. AFAIK the English language has entries for each language in the language's own writing, which would indicate not to translate those entries. If we choose to not translate them, we should better move those strings to a different file.

Agreed, those strings should not be translated. But perhaps they don't need to be in a property file either. Perhaps we could just use [`Locale.getDisplayName();`](https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#getDisplayName--) to get the language name on the Java-side? For example:

```java
Locale locale = new Locale("nl");
System.out.println(locale.getDisplayName()); // "Dutch"
```

@ahus1 WDYT?

**Comment by thomasdarimont** [comment]
Thanks for looking into this!

My 2 cents:
While working on the german translations I also noticed that the locale names could be pulled form the JDK, that's in fact what I used
to create the translations in the first place... but I hesitated to question the implementation as it were "just a few strings..." ;-)

However, I'm in favor of using JDK built-in functionality. It seems that the languages are currently translated via messagebundle in 
the UI since the server only returns the list of supportedLocales in the realm response.

If we want to leverage the translations built-in the JDK we could add a new `supportedLocales` endpoint to the 
[RealmLocalizationResource](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/RealmLocalizationResource.java) to expose a `LocaleRepresentation`.

Additionally there is also [LocaleBean](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/theme/beans/LocaleBean.java#L40) which is used by the language selection in Freemarker based pages.

**Comment by jonkoops** [comment]
> If we want to leverage the translations built-in the JDK we could add a new supportedLocales endpoint to the
[RealmLocalizationResource](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/RealmLocalizationResource.java) to expose a `LocaleRepresentation`.

There should be no need to create a new REST API endpoint for this, there are [equivalent APIs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames) on the browser-side we can use to localize this. Taking my previous example translated to JS:

```js
const regionNames = new Intl.DisplayNames(['en'], { type: 'language' });
console.log(regionNames.of('nl')); // "Dutch"
```

**Comment by ahus1** [comment]
Thank you for the feedback. I'll prepare a PR to automatically blend in the Java translations of locales at the backend. This would allow us to leverage the translation override if anyone would want that. And the results shown would be consistent, independent of the user's browser settings. Please follow #29124 for the progress.

**Comment by ahus1** [comment]
Repeating my sentence which might got lost: 

> While the build breaks and with the question I raised about the language names, I ask you to slow down the translation a bit and wait for this PR to be merged. I assume we will resolve this next week.

**Comment by ahus1** [comment]
I've looked at the failing tests, and they stem from the translated locales. I've reverted the translation in Weblate, and marked the keys to be read-only. I also enabled a setting which squashes the commits by author. I hope this build will be green, and then it can be merged.

**Comment by thomasdarimont** [comment]
Hi @ahus1 I didn't touch weblate today, so something else is probably triggering a rebuild / push or something.

**Review by ahus1 — APPROVED** [review]

**Comment by ahus1** [comment]
@thomasdarimont - Weblate is buffering changes, so they might show up deferred only. With the latest squash-commit changes (maybe even before?) it will rebase this PR once there is a change in the parent repo. Let's see how often this happens, and how annoying this is to get the PR merged.

**Comment by ahus1** [comment]
@jonkoops - please review for the UI team. Thanks!

**Review by jonkoops — APPROVED** [review]

**Pull request merged**
