### PR TITLE
Script Protocol Mapping Logger

### PR DESCRIPTION
**Pull request by gambol99**
- adding the logger to the script protocol mapper for debug purposes

### CODE REVIEW

**Comment by abstractj** [comment]
@gambol99 could you please link the Jira adding a description for it?

**Comment by gambol99** [comment]
hi @abstractj ... sorry for delay .. I've created https://issues.jboss.org/browse/KEYCLOAK-7893

**Comment by gambol99** [comment]
hi @abstractj ... this one cool now? :-)

**Comment by gambol99** [comment]
Hi @abstractj ... admittedly i'm no longer using it :-) .. but was attempting to grab the client roles and inject them as the "groups" claim in the access token .. At the time is wasn't, I did find the reason after much googling but would have been useful to have access to see inside while I was playing with and give the script authenticator https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/authentication/authenticators/browser/ScriptBasedAuthenticator.java#L164 had it injected, I figured it wouldn't be a biggie :-) ..

**Comment by abstractj** [comment]
@gambol99 let's do this way. I'm closing it for now and but in the future if we see a real need for this we can revisit and reopen that Jira.

**Pull request closed without merging**
