### PR TITLE
Service Accounts Client must create the Client ID mapper with Token C…

### LINKED ISSUE #16329: Service Accounts Client must create the Client ID mapper with Token Claim Name as client_id
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

[Enabling service account](https://www.keycloak.org/docs/latest/server_admin/#_service_accounts) create three default mappers.
One of them is 'Client ID' mapper. This mapper has default 'Token Claim Name' field equal to clientId.
Default 'Token Claim Name' field must be **client_id** in order to be compliant with OAuth2 specifications.
OAuth2 specifications related to **client_id** claim:

- [JSON Web Token (JWT) Profile for OAuth 2.0 Access Tokens ](https://datatracker.ietf.org/doc/html/rfc9068#section-2.2)
- [OAuth 2.0 Token Introspection](https://www.rfc-editor.org/rfc/rfc7662#section-2.2)
- [OAuth 2.0 Token Exchange](https://datatracker.ietf.org/doc/html/rfc8693#section-4.3)

### Version

20.0.2

### Expected behavior

 'Client ID' mapper with default 'Token Claim Name' field equal to client_id.

### Actual behavior

 'Client ID' mapper with default 'Token Claim Name' field equal to clientId.

### How to Reproduce?

[Enable service account](https://www.keycloak.org/docs/latest/server_admin/#_service_accounts) in a Client

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cgeorgilakis**
…laim Name as client_id

closes #16329

### CODE REVIEW

**Comment by sschu** [comment]
This change might break things for people that rely on `clientId` in the session note and also in the token. Not sure how to progress here. Maybe first add `client_id` as an additional session note and token claim and deprecate the old one to give people time to adapt?

**Comment by cgeorgilakis** [comment]
> This change might break things for people that rely on `clientId` in the session note and also in the token. Not sure how to progress here. Maybe first add `client_id` as an additional session note and token claim and deprecate the old one to give people time to adapt?

Default client_id mapper is created only during new Service Account Client created. So, changes does not break anything.
If someone want to use different Token Claim name than the default, he can change mapper as we do now in order to be compliant with OAuth2 specifications mentioned in github issue. It is importat default Keycloak behaviour to be compliant with OAuth2 specifications.

**Comment by mposolda** [comment]
@sschu @cgeorgilakis One note here: Isn't it sufficient if we just add the new claim for `client_id` here? I think it shouldn't break existing deployments as those already have the claim with `clientId` created - note it is created just at the time when the "Service account" client is created (or when "service account" switch is enabled for the client). So existing apps should work pretty fine? Just the new applications will be affected by this though.

However I think that adding userSession note should be done for both `client_id` and `clientId` as this can affect existing deployments.

So what I suggest is:
- Change it for the mapper like done in this PR
- Add this to the documentation to the migration guide (As some deployments can be still affected for some corner cases - for example when they always re-create their Keycloak instance by some scripts etc)
- Add the new userSession note in addition to the existing one in TokenEndpoint. So something like:
```
userSession.setNote(ServiceAccountConstants.CLIENT_ID, client.getClientId());
userSession.setNote("clientId", client.getClientId()); // This is for backwards compatibility
```

WDYT?

**Comment by cgeorgilakis** [comment]
> @sschu @cgeorgilakis One note here: Isn't it sufficient if we just add the new claim for `client_id` here? I think it shouldn't break existing deployments as those already have the claim with `clientId` created - note it is created just at the time when the "Service account" client is created (or when "service account" switch is enabled for the client). So existing apps should work pretty fine? Just the new applications will be affected by this though.
> 
> However I think that adding userSession note should be done for both `client_id` and `clientId` as this can affect existing deployments.
> 
> So what I suggest is:
> 
> * Change it for the mapper like done in this PR
> * Add this to the documentation to the migration guide (As some deployments can be still affected for some corner cases - for example when they always re-create their Keycloak instance by some scripts etc)
> * Add the new userSession note in addition to the existing one in TokenEndpoint. So something like:
> 
> ```
> userSession.setNote(ServiceAccountConstants.CLIENT_ID, client.getClientId());
> userSession.setNote("clientId", client.getClientId()); // This is for backwards compatibility
> ```
> 
> WDYT?

As you mentioned, 'it is created just at the time when the "Service account" client is created (or when "service account" switch is enabled for the client)'. That's why and for not creating two mappers, my PR is as you see. I agree with your proposal change.

I could make changes soon together with needed PR in keycloak-documentation.

**Comment by sschu** [comment]
@mposolda @cgeorgilakis I agree, this should work.

**Comment by cgeorgilakis** [comment]
Documentation PR : https://github.com/keycloak/keycloak-documentation/pull/1800

**Comment by cgeorgilakis** [comment]
@mposolda I have also make code changes requested

**Comment by cgeorgilakis** [comment]
Documentation changes has been added to the PR

**Review by mposolda — DISMISSED** [review]
@cgeorgilakis @sschu Thanks for the confirm and for updating this PR! I am approving.

Now we just need to have tests passing... I will try to re-run them.

**Comment by mposolda** [comment]
@cgeorgilakis Can you please rebase this PR to latest Keycloak main? Hope that helps to have test happy (there was recently some refactoring in latest Keycloak main related to adding new admin console and docs to main codebase and maybe this is related to build failures in your PR).

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
@cgeorgilakis Thanks!

**Comment by rad-pat** [comment]
This change went into 21.1.1, yet the documentation for the change is for 22.0 so it's pretty hard to track down!! Suggest inclusion of the documentation ASAP.

**Comment by cgeorgilakis** [comment]
> This change went into 21.1.1, yet the documentation for the change is for 22.0 so it's pretty hard to track down!! Suggest inclusion of the documentation ASAP.

You are right. This PR was intended for 22. @mposolda is it easy to change only the 21.1.0 documentation?

@rad-pat the changes are described [here](https://www.keycloak.org/2023/04/keycloak-2110-released).

**Pull request merged**
