### PR TITLE
KEYCLOAK-15697 SAML Identity Broker - Make the SP Entity ID user configurable

### PR DESCRIPTION
**Pull request by lscorcia**
Currently the SAML Identity Broker feature does not offer the option to customize the Entity ID that identifies the Service Provider and always uses a value computed as follows:

`<authUrl>/realms/<realmName>`

The SAML Entity ID is intended to be just an URI and there is no reason why this has to be a working URL.

While this hardcoded behavior is fine for many scenarios, in my case the Entity ID is actually assigned from the SAML federation management (i.e. the remote IdP). This pull request makes the Entity ID value user configurable.

The changes are very simple as all the plumbing is already in place. For backwards compatibility, the proposed code takes care of generating the default value for existing SAML providers according to the above mentioned pattern.

### CODE REVIEW

**Review by mhajas — APPROVED** [review]
This looks pretty good @lscorcia, thank you for the PR. Great work!

**Review by sguilhen — APPROVED** [review]
Nice work indeed, @lscorcia - approving this!

**Review by hmlnarik — APPROVED** [review]
Approving based on reviews by @mhajas and @sguilhen

**Comment by hmlnarik** [comment]
@lscorcia Thank you for the contribution!

**Pull request merged**
