### PR TITLE
KEYCLOAK-3490: Added Keycloak admin client that use CXF instead RESTeasy as JAX-RS implementation.

### PR DESCRIPTION
**Pull request by luigidemasi**

### CODE REVIEW

**Comment by stianst** [comment]
We can't accept this PR at least not in it's current state.

There's a large amount of duplicated code, but also introducing a new module doubles the effort to maintain the client. Every-time we add to the admin endpoints we'd need to add to to both modules. There's also lack of testing and documentation.

If you can rather add an option to the existing admin-client module to make it use CXF with as much shared code as possible we'd be happy to accept the PR. We'd also require updates to the documentation (https://keycloak.gitbooks.io/server-developer-guide/content/topics/admin-rest-api.html) as well as testing (not duplicating tests, but rather making tests run with two RestEasy and CXF).

**Comment by luigidemasi** [comment]
Introduce a new module is required to avoid name clashes and cast exceptions and the duplicate code is a consequence of some RESTeasy specific classes and annotations (eg. @NoCache, MultipartFormDataOutput, etc..) in the admin client.
Maybe I can externalize the common resources in a third module and let the specific implementation in the *-admin-client modules?

**Comment by stianst** [comment]
I'm sorry, but the only way I'll accept a PR is if we can find a way to have a single module and absolutely minimal amount of additional code for the CXF bits.

The @NoCache annotations can be removed as they are not required on the client side. There may be an equivalent to MultipartFormDataOutput in JAX-RS API as well as other things.

**Comment by luigidemasi** [comment]
Is not possible to mix RESTeasy and CXF dependency in a single module because it will lead to cast exception at runtime (already tried in my current project with Jboss Fuse and CXF).
Feel free to close the PR, I'll continue to maintain it as a side project in my repository.

**Comment by stianst** [comment]
Would it not work at runtime by including one or the other?

**Comment by luigidemasi** [comment]
I can try but the problem is that JAX-RS 2.0 spec doesn't define a standard way to create a proxy object neither standard way to deal with multipart form.
Now, for obtaining the proxy, I can implement a strategy pattern but to invoke a service with multipart parameters I need to have two separate implementation of the resource interface, so at least some code is duplicated.
Even worse you are forcing users to include a dependency (RESTeasy or CXF) that will never use.
In my opinion the best option is to externalize the resources package in a third module and create two different modules for RESTeasy and CXF.

**Comment by luigidemasi** [comment]
@stianst I tried and the multipart issue is blocking. As I said yesterday JAX-RS 2 spec doesn't define a standard way to deal with multipart form, the only way to implement it in a portable fashion is to use plain http client (apache or standard java) but I think it's an overkill. Feel free to close the PR.

**Comment by stianst** [comment]
You've convinced me that we'd need to have multiple modules. I'm not quite sure if that's something we want to do though. I know a few people have had issues with using the admin clients because of it's strong dependency on RestEasy, but CXF may just fix some cases as there are still other JAX-RS implementations out there. It seems it's rather difficult to use the admin client when you have another JAX-RS on the classpath. Dropping down to plain http client would alleviate that, but would be much more work to maintain.

I'll leave the PR open for now as I'd like to discuss it a bit with other team members. Then I'll get back to you.

**Comment by luigidemasi** [comment]
Stian, any news about this PR?

**Comment by stianst** [comment]
Afraid I've not had time to discuss this with others. I'll do my best to make a final call on this next week.

**Comment by stianst** [comment]
Sorry this has taken so long, but we've finally come to a conclusion. We've decided that rather than having multiple versions of the admin client RestEasy client should be changed to make it agnostic of the underlying JAX-RS implementation so it can be used with CXF or any other JAX-RS implementation. See https://issues.jboss.org/browse/KEYCLOAK-3607 for more details.

Thanks for your PR, but I'm afraid I'm going to have to reject it.

**Pull request closed without merging**
