### PR TITLE
KEYCLOAK-5774 New SessionAttributeMapper

### PR DESCRIPTION
**Pull request by ckEriksen**
Mapper between a received claim and the user session notes.

### CODE REVIEW

**Comment by stianst** [comment]
@ckEriksen thanks for your PR. We are currently in feature freeze for Keycloak 3.x and will not be able to review/merge this work until we open the doors for Keycloak 4.x development.

**Comment by stianst** [comment]
@mposolda @hmlnarik what do you guys think about this? I'm not convinced we should add support to add things to the session like this. To be accepted the PR would also have to be updated with proper testing as there's nothing to check that the mapper actually works.

**Comment by mposolda** [comment]
I think the scenario described in the JIRA KEYCLOAK-5774 makes sense and so this PR likely too. But I am not sure if the usecase can't be addressed using the new TokenExchange service and it's not the better place to address this. If not, my vote is to merge this PR (assuming the test will be added).

**Comment by stianst** [comment]
This is just a workaround for https://issues.jboss.org/browse/KEYCLOAK-5774 not a proper solution. Having acr values in tokens is something we should do properly. Keycloak should have its own concept of acr values, with the ability to map acr values from external IdPs. One IdP may be trusted and the acr value map directly, but another may be less trusted in which case the acr value would be downgraded.

I'm not sure having a generic mapper to map claims from the external token into user session is something that will have many real use-cases.

@mposolda I don't understand how token exchange would fill the requirement to have the acr value in the token can you elaborate?

**Comment by mposolda** [comment]
@stianst I didn't consider any concrete claim like "acr" .  

I assume the general usecase is, that you are able to map any random claim "foo" from Facebook token to the claim "foo" in the Keycloak accessToken. Is it correct?

If I see correctly, this PR address the usecase. You will need to configure 2 mappers:
- The newly implemented IDP mapper implementation, which will allow to map some claim from external IDP token to userSession note.
- Then userSessionNote Protocol mapper (which we already have implemented) to map this claim from userSession note to the Keycloak tokens. 

So was wondering if TokenExchange can't be directly used to address the usecase instead of using those 2 mappers. AFAIK TokenExchange has some support for exchange 3rd party broker tokens for Keycloak tokens with corresponding claims, but maybe I am wrong?

**Comment by stianst** [comment]
Token exchange would be different use-case in that case the app has the external IdP token and wants to exchange the token for an internal one.

I think the general use-case you're listing makes sense. At the moment the only way to do that would be to map to user attributes, but not everything fits there.

So after considering it again I don't see any problem in adding this and can see the value of it. However, we do need some proper tests to make sure the mapper actually works. At the moment there's only tests that checks if it's registered.

**Comment by mposolda** [comment]
@stianst ok, Thanks for clarifying the token exchange. +1 to this PR (after tests are added).

**Comment by torsteis** [comment]
Thanks for the feedback. We will be taking over this PR from @ckEriksen, and plan to add tests as soon as possible

**Comment by stianst** [comment]
Closing due to lack of tests

**Pull request closed without merging**
