### PR TITLE
[Fixes #26651] Do not verify nonce in access and refresh tokens (only…

### LINKED ISSUE #26651: [keycloak.js] useNonce parameter is all-or-nothing
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

adapter/javascript

### Describe the bug

With f44cda262124ec76737386717f53a84dd956b84a for #4978 `useNonce` parameter was added.

I'm checking keycloak.js with [Spring Authorization Server](https://docs.spring.io/spring-authorization-server) and almost everything works. But...

my authorization request is:
```
http://localhost:9000/oauth2/authorize?
    client_id=hawtio-public&
    redirect_uri=http://localhost:3000/hawtio/&
    state=ac99f440-7953-4f1a-8536-1854d1a4d3be&
    response_mode=query&
    response_type=code&
    scope=openid&
    nonce=dd31a03c-d7e0-4771-959c-a3c39792bb84&
    code_challenge=OcXihqVsiGg1KXkfs2wGjRhhdoVypMrTXJ78XsIT8WA&
    code_challenge_method=S256
```
It is successful with this redirect:
```
Location: http://localhost:3000/hawtio/?
    code=vNVS6qV-sUefkPqM1dPm1aq7v1_JyJ4-U1eUug0E94e6m6Uze8TQuz7SL73N5I0Y7Glk71--CFmEhTg3rrKUVnN58OL8w0L1pQr_KHI0vkx194r2mwy_M190aAsFQkkV&
    state=ac99f440-7953-4f1a-8536-1854d1a4d3be
```
Then token endpoint is POSTed with:
```
code=vNVS6qV-sUefkPqM1dPm1aq7v1_JyJ4-U1eUug0E94e6m6Uze8TQuz7SL73N5I0Y7Glk71--CFmEhTg3rrKUVnN58OL8w0L1pQr_KHI0vkx194r2mwy_M190aAsFQkkV&
grant_type=authorization_code&
client_id=hawtio-public&
redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fhawtio%2F&
code_verifier=iPekAWjAJ9OMBzRAJi9PHvFyFSsoixIXsED8rAGufFSqtRFdwQaGEEZWsHdUCEXv2Gzo01go1eBkWBPgxeAmH4rOEJHorizd
```
However the response contains (item [1] of JTWs is base64 decoded):
```
{
"access_token":"
    eyJraWQiOiI3MThmYjYwOS00MGQ4LTRiMjYtYmUyZC1mY2I3NGM3OTU1YzgiLCJhbGciOiJSUzI1NiJ9
    {
      "sub": "user1",
      "aud": "hawtio-public",
      "nbf": 1706709324,
      "scope": [
        "openid"
      ],
      "iss": "http://localhost:9000",
      "exp": 1706709624,
      "iat": 1706709324,
      "jti": "079aab32-9799-4e73-ae76-3b9d61c51992"
    }
    H1b8lWu18VZEOM-oyNdjImFg_0ELEXEfjxavFrdR-6Rurz4MDKnyRTLXg2Oemhfpbm4xIGPfi8rwOJn7Kc-VT8BqD5U_AOslRyje9Hf6k7TnTOId32D-Nn_YoWU2EUWQAZSyDGdXotHLiAsIedB27e5CWx25BambZ-mil4TieYoXjiVrOOSITMi6fkdECyat8cdOZiiXc4FzCNygGcsz1jHCOlUDN39W5Y1r_wRUhK2O1UnfxcAAI6zRsc2z_ocu4vRiBXf979LfY6e5JSe31JnWBOrp9m4udMnmgUEf838-RG0-D_obAvC5zyX6WGy3BpnHzyIl9lhmHVh3Q0eSEw",
"scope":"openid",
"id_token":"
    eyJraWQiOiI3MThmYjYwOS00MGQ4LTRiMjYtYmUyZC1mY2I3NGM3OTU1YzgiLCJhbGciOiJSUzI1NiJ9
    {
      "sub": "user1",
      "aud": "hawtio-public",
      "azp": "hawtio-public",
      "auth_time": 1706708739,
      "iss": "http://localhost:9000",
      "exp": 1706711124,
      "iat": 1706709324,
      "nonce": "dd31a03c-d7e0-4771-959c-a3c39792bb84",
      "jti": "34984761-de7c-414a-9506-e7c6dfdea88e",
      "sid": "IhCpYEA4R0V_LPS3OYyIuplpxhYK12wNl-R4NgLuXQo"
    }
    fNTowFiRgZqNpUh6ut5HlUAxRvALEptkW1cxuwNpdrXutWpV1hxs8mVzwsVzWljp-Z6blq0ba_X-aoC3KnoibQr8Dr3HnFDP7rQtNURxInZjJwbxJmJWGwDy8zwEVbYSMpPtDvThf0ffWP9IrsJgqD1kQBxKx6eXgxe19uhFJHuhdmM1ZH6We0U-BVUn-kYmKN27e_V3077OPW3tgNqRz7F6Ftc8-j2HtYB7JZANkDWGZc3HRNgbDRHpSflRsdeO77t1rYBsPZRku7y1zkpoTYLRGTP-hknSatn9I2ulWkZB5738aXAX6pYTeI1PR-Yk5K9R7tqKcJOap880aeHQ8w",
"token_type":"Bearer",
"expires_in":299
}
```
So:

* `id_token` contains the nonce (according to https://openid.net/specs/openid-connect-core-1_0.html#IDToken)
* `access_token` doesn't contain the nonce (OAuth 2 doesn't define the content of tokens and RFC 7519 (JWT) doesn't mention nonce as well)

Can the nonce be mandatory only for id_token, but not for access_token and refresh_token?

### Version

23.0.5

### Expected behavior

`nonce` claim not available in `access_token` and not required.

### Actual behavior

`nonce` claim not available in `access_token` but required by keycloak.js.

### How to Reproduce?

Use keycloak.js with Spring Authorization Server

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by grgrzybek**
Closes #26651

### CODE REVIEW

**Comment by stianst** [comment]
Could you update commit message to link to GitHub Issue like this:

```
<Summary>

Closes: #26651
```

**Comment by grgrzybek** [comment]
> Could you update commit message to link to GitHub Issue like this:
> 
> ```
> <Summary>
> 
> Closes: #26651
> ```

Hmm, I named it:
```
[Fixes #26651] Do not verify nonce in access and refresh tokens (only id tokens)
```
it has changed to
```
[Fixes https://github.com/keycloak/keycloak/issues/26651] Do not verify nonce in access and refresh tokens (only id tokens)```

**Comment by grgrzybek** [comment]
Got it - I forced pushed the PR to my fork with better (hopefully) commit

**Review by stianst — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]

**Review by jonkoops — APPROVED** [review]
Yeah this look good to me, let's get this merged.

**Pull request merged**
