### PR TITLE
Ensure safe initialization of the embedded caches

### LINKED ISSUE #24085: Test OfflineSessionPersistenceTest.testPersistenceClientSessionsMultipleNodes failed
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

infinispan

### Describe the bug

When analyzing a model test run which blocked, there was the following exception. 

Possible cause: The configuration is bound to a thread. If Infinispan tries to read the configuration from a JGroups thread, there is no configuration, and the warning occurs as shown below.

```
10:19:27,749 WARN  [org.infinispan.CLUSTER] (jgroups-8,node-26) ISPN000071: Caught exception when handling command org.infinispan.manager.impl.ReplicableManagerFunctionCommand@6eda0df4
java.lang.RuntimeException: No org.keycloak.cluster.ManagedCacheManagerProvider found. If running in embedded mode set the [embedded] property to this provider.
	at org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory.lazyInit(DefaultInfinispanConnectionProviderFactory.java:148)
	at org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory.create(DefaultInfinispanConnectionProviderFactory.java:83)
	at org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory.create(DefaultInfinispanConnectionProviderFactory.java:67)
	at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:177)
	at org.keycloak.models.cache.infinispan.InfinispanCacheRealmProviderFactory.lazyInit(InfinispanCacheRealmProviderFactory.java:55)
	at org.keycloak.models.cache.infinispan.InfinispanCacheRealmProviderFactory.create(InfinispanCacheRealmProviderFactory.java:47)
	at org.keycloak.models.cache.infinispan.InfinispanCacheRealmProviderFactory.create(InfinispanCacheRealmProviderFactory.java:37)
	at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:177)
	at org.keycloak.storage.datastore.LegacyDatastoreProvider.getRealmProvider(LegacyDatastoreProvider.java:154)
	at org.keycloak.storage.datastore.LegacyDatastoreProvider.realms(LegacyDatastoreProvider.java:224)
	at org.keycloak.services.DefaultKeycloakSession.realms(DefaultKeycloakSession.java:274)
	at org.keycloak.models.jpa.session.JpaUserSessionPersisterProvider.toAdapter(JpaUserSessionPersisterProvider.java:491)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.keycloak.utils.ClosingStream.collect(ClosingStream.java:182)
	at org.keycloak.models.jpa.session.JpaUserSessionPersisterProvider.loadUserSessionsWithClientSessions(JpaUserSessionPersisterProvider.java:423)
	at org.keycloak.models.jpa.session.JpaUserSessionPersisterProvider.loadUserSessionsStream(JpaUserSessionPersisterProvider.java:382)
	at org.keycloak.models.sessions.infinispan.initializer.OfflinePersistentUserSessionLoader.loadSessions(OfflinePersistentUserSessionLoader.java:101)
	at org.keycloak.models.sessions.infinispan.initializer.OfflinePersistentUserSessionLoader.loadSessions(OfflinePersistentUserSessionLoader.java:37)
	at org.keycloak.models.sessions.infinispan.initializer.SessionInitializerWorker$1.run(SessionInitializerWorker.java:71)
	at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:261)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:383)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:260)
	at org.keycloak.models.sessions.infinispan.initializer.SessionInitializerWorker.apply(SessionInitializerWorker.java:67)
	at org.keycloak.models.sessions.infinispan.initializer.SessionInitializerWorker.apply(SessionInitializerWorker.java:34)
	at org.infinispan.manager.impl.ReplicableManagerFunctionCommand.invokeAsync(ReplicableManagerFunctionCommand.java:45)
	at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler$ReplicableCommandRunner.run(GlobalInboundInvocationHandler.java:256)
	at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler.handleReplicableCommand(GlobalInboundInvocationHandler.java:175)
	at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler.handleFromCluster(GlobalInboundInvocationHandler.java:114)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1548)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1476)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1681)
	at org.jgroups.JChannel.up(JChannel.java:733)
	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:936)
	at org.jgroups.protocols.FRAG2.up(FRAG2.java:139)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:253)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:261)
	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:845)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:226)
	at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1083)
	at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:822)
	at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:804)
	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:453)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:680)
	at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
	at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:180)
	at org.jgroups.protocols.FD_SOCK2.up(FD_SOCK2.java:188)
	at org.jgroups.protocols.MERGE3.up(MERGE3.java:274)
	at org.jgroups.protocols.Discovery.up(Discovery.java:294)
	at org.jgroups.stack.Protocol.up(Protocol.java:340)
	at org.jgroups.protocols.TP.passMessageUp(TP.java:1184)
	at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:107)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Version

main

### Expected behavior

Exception should not be thrown, 

### Actual behavior

Exception thrown, possible cause of Infinispan locking up later in the test

### How to Reproduce?

Seen in logs of this run: https://github.com/keycloak/keycloak/actions/runs/6551101782/job/17792066640

[logs.txt.gz](https://github.com/keycloak/keycloak/files/13030059/logs.txt.gz)

### Anything else?

I'll prepare a pull request.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #24085

### CODE REVIEW

**Review by martin-kanis — CHANGES_REQUESTED** [review]
Thanks for the PR. However, it seems it doesn't fix the problem. See https://github.com/martin-kanis/keycloak/actions/runs/6717616121

1. There is quite a lot failed stages (didn't investigate the reasons more)
2. There is still few `java.lang.RuntimeException: No org.keycloak.cluster.ManagedCacheManagerProvider found. If running in embedded mode set the [embedded] property to this provider.` errors in some log files i.e `0_Store Model Tests (11).txt`
3. It doesn't have an effect on https://github.com/keycloak/keycloak/pull/23779 -- there are few `NullPointerException: Cannot invoke "org.keycloak.models.UserSessionModel.getStarted()" because "userSession" is null`

**Comment by martin-kanis** [comment]
@ahus1 Thanks for the changes. The `java.lang.RuntimeException: No org.keycloak.cluster.ManagedCacheManagerProvider found. If running in embedded mode set the [embedded] property to this provider.` error is away. Now we have the following error in 3 log files (0_Store Model Tests (7).txt, 0_Store Model Tests (16).txt, 0_Store Model Tests (28).txt)
```
ISPN000136: Error executing command PutMapCommand on Cache 'offlineClientSessions', writing keys [f815e1f8-af70-41f8-b303-27bd35c28e99, b61c1ef5-632a-440d-90d8-40c80f52f2ef, f659082c-61d3-440c-83ca-0d5eb488ef91, b4b4d8d2-2fb1-4072-ab27-a533de4e01b8, 234b4e7c-1a43-4acc-9137-170e4511e058, a5112574-20ae-4b88-b5cc-22434e9265f7, 3a07f5a6-360f-4e70-929e-409c2a2d0b3b, 9567600d-4cc9-4461-9b31-f35ea1abd84c...<12 other elements>]
2023-11-01T20:57:53.6057611Z org.infinispan.util.concurrent.TimeoutException: ISPN000427: Timeout after 15 seconds waiting for acks ([node-22(site-id=site-2), node-24(site-id=site-2)]). Id=100420
```

I think, I saw this several times before. Probably it's not cased by your changes. Still, we have 3 occurrences out of 35. Do you want to investigate it now or file a separate issue?

Full stacktrace :
```
ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (timeout-thread-node-24-p124-t1) ISPN000136: Error executing command PutMapCommand on Cache 'offlineClientSessions', writing keys [f815e1f8-af70-41f8-b303-27bd35c28e99, b61c1ef5-632a-440d-90d8-40c80f52f2ef, f659082c-61d3-440c-83ca-0d5eb488ef91, b4b4d8d2-2fb1-4072-ab27-a533de4e01b8, 234b4e7c-1a43-4acc-9137-170e4511e058, a5112574-20ae-4b88-b5cc-22434e9265f7, 3a07f5a6-360f-4e70-929e-409c2a2d0b3b, 9567600d-4cc9-4461-9b31-f35ea1abd84c...<12 other elements>]
org.infinispan.util.concurrent.TimeoutException: ISPN000427: Timeout after 15 seconds waiting for acks ([node-22(site-id=site-2), node-24(site-id=site-2)]). Id=100420
	at org.infinispan.util.concurrent.CommandAckCollector.createTimeoutException(CommandAckCollector.java:228)
	at org.infinispan.util.concurrent.CommandAckCollector$BaseCollector.call(CommandAckCollector.java:281)
	at org.infinispan.util.concurrent.CommandAckCollector$BaseCollector.call(CommandAckCollector.java:261)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (timeout-thread-node-22-p134-t1) ISPN000136: Error executing command PutMapCommand on Cache 'offlineClientSessions', writing keys [cf176276-ff1c-4326-8c65-a7ec374c945e, f8c99fb0-e0a1-405d-bd42-cb57da735c63, c65fa9d8-32f2-4001-8e76-936f5450cc3f, f758597b-2e49-4586-ab3f-67ca64d5ae8e, 5b2aa161-b516-4d76-80c3-88fdf01b0a0d, 62fabd0c-4e88-492d-aa2f-4510d4a2ad4d, 3693f555-70df-4e06-8751-518e17a5d36f, f559e6da-0e6f-4915-aeab-e9511cab9de3...<25 other elements>]
org.infinispan.util.concurrent.TimeoutException: ISPN000427: Timeout after 15 seconds waiting for acks ([node-22(site-id=site-2)]). Id=100422
	at org.infinispan.util.concurrent.CommandAckCollector.createTimeoutException(CommandAckCollector.java:228)
	at org.infinispan.util.concurrent.CommandAckCollector$BaseCollector.call(CommandAckCollector.java:281)
	at org.infinispan.util.concurrent.CommandAckCollector$BaseCollector.call(CommandAckCollector.java:261)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (timeout-thread-node-24-p124-t1) ISPN000136: Error executing command PutMapCommand on Cache 'offlineClientSessions', writing keys [92ba8484-020a-4928-99ab-6e249b10e4c3, 063a139b-9fff-4032-96df-6019d3c54d2e, 76530a5e-1fde-465f-a17d-d7fac887e7cd, 3e6dfcb2-1f91-44c0-9c52-d757e96a48e3, c38e2b15-09be-4464-9283-b3d447e1ea75, 28d76f85-c7e6-4431-a9b4-067140f8657b, 714cb7cc-5270-46d8-b1d7-323ab2eef56f, 94f06f30-e8ee-45c8-bcf9-f4489afcebae...<37 other elements>]
org.infinispan.util.concurrent.TimeoutException: ISPN000427: Timeout after 15 seconds waiting for acks ([node-22(site-id=site-2)]). Id=100421
 	at org.infinispan.util.concurrent.CommandAckCollector.createTimeoutException(CommandAckCollector.java:228)
 	at org.infinispan.util.concurrent.CommandAckCollector$BaseCollector.call(CommandAckCollector.java:281)
 	at org.infinispan.util.concurrent.CommandAckCollector$BaseCollector.call(CommandAckCollector.java:261)
 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 	at java.base/java.lang.Thread.run(Thread.java:840)
WARN  [org.infinispan.CLUSTER] (jgroups-11,node-22(site-id=site-2)) ISPN000071: Caught exception when handling command org.infinispan.manager.impl.ReplicableManagerFunctionCommand@28ea04e1
org.infinispan.util.concurrent.TimeoutException: ISPN000427: Timeout after 15 seconds waiting for acks ([node-22(site-id=site-2)]). Id=100422
 	at org.infinispan.interceptors.impl.AsyncInterceptorChainImpl.invoke(AsyncInterceptorChainImpl.java:258)
 	at org.infinispan.cache.impl.InvocationHelper.doInvoke(InvocationHelper.java:323)
 	at org.infinispan.cache.impl.InvocationHelper.invoke(InvocationHelper.java:111)
 	at org.infinispan.cache.impl.InvocationHelper.invoke(InvocationHelper.java:93)
 	at org.infinispan.cache.impl.CacheImpl.putAll(CacheImpl.java:1361)
 	at org.infinispan.cache.impl.DecoratedCache.putAll(DecoratedCache.java:562)
 	at org.infinispan.cache.impl.DecoratedCache.putAll(DecoratedCache.java:567)
 	at org.infinispan.cache.impl.EncoderCache.putAll(EncoderCache.java:792)
 	at org.keycloak.models.sessions.infinispan.remotestore.RemoteCacheSessionsLoader.loadSessions(RemoteCacheSessionsLoader.java:144)
 	at org.keycloak.models.sessions.infinispan.remotestore.RemoteCacheSessionsLoader.loadSessions(RemoteCacheSessionsLoader.java:47)
 	at org.keycloak.models.sessions.infinispan.initializer.SessionInitializerWorker$1.run(SessionInitializerWorker.java:71)
 	at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:262)
 	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:384)
 	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:261)
 	at org.keycloak.models.sessions.infinispan.initializer.SessionInitializerWorker.apply(SessionInitializerWorker.java:67)
 	at org.keycloak.models.sessions.infinispan.initializer.SessionInitializerWorker.apply(SessionInitializerWorker.java:34)
 	at org.infinispan.manager.impl.ReplicableManagerFunctionCommand.invokeAsync(ReplicableManagerFunctionCommand.java:45)
 	at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler$ReplicableCommandRunner.run(GlobalInboundInvocationHandler.java:256)
 	at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler.handleReplicableCommand(GlobalInboundInvocationHandler.java:175)
 	at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler.handleFromCluster(GlobalInboundInvocationHandler.java:114)
 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1548)
 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1476)
 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.lambda$up$1(JGroupsTransport.java:1695)
 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1687)
 	at org.jgroups.JChannel.up(JChannel.java:749)
 	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:939)
 	at org.jgroups.protocols.FRAG2.up(FRAG2.java:161)
 	at org.jgroups.protocols.FlowControl.up(FlowControl.java:319)
 	at org.jgroups.protocols.FlowControl.up(FlowControl.java:319)
 	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:859)
 	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:246)
 	at org.jgroups.protocols.UNICAST3.deliverBatch(UNICAST3.java:1108)
 	at org.jgroups.protocols.UNICAST3.handleBatchReceived(UNICAST3.java:882)
 	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:549)
 	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:722)
 	at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:146)
 	at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:193)
 	at org.jgroups.protocols.FD_SOCK2.up(FD_SOCK2.java:202)
 	at org.jgroups.protocols.MERGE3.up(MERGE3.java:288)
 	at org.jgroups.protocols.Discovery.up(Discovery.java:314)
 	at org.jgroups.protocols.RED.up(RED.java:119)
 	at org.jgroups.protocols.TP.passBatchUp(TP.java:1210)
 	at org.jgroups.util.SubmitToThreadPool$BatchHandler.passBatchUp(SubmitToThreadPool.java:161)
 	at org.jgroups.util.SubmitToThreadPool$BatchHandler.run(SubmitToThreadPool.java:157)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.infinispan.util.concurrent.TimeoutException: ISPN000427: Timeout after 15 seconds waiting for acks ([node-22(site-id=site-2)]). Id=100422
 	at org.infinispan.util.concurrent.CommandAckCollector.createTimeoutException(CommandAckCollector.java:228)
 	at org.infinispan.util.concurrent.CommandAckCollector$BaseCollector.call(CommandAckCollector.java:281)
 	at org.infinispan.util.concurrent.CommandAckCollector$BaseCollector.call(CommandAckCollector.java:261)
 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
 	... 3 more
 	Suppressed: org.infinispan.commons.util.logging.TraceException
 		at org.infinispan.interceptors.impl.SimpleAsyncInvocationStage.get(SimpleAsyncInvocationStage.java:39)
 		at org.infinispan.interceptors.impl.AsyncInterceptorChainImpl.invoke(AsyncInterceptorChainImpl.java:249)
 		at org.infinispan.cache.impl.InvocationHelper.doInvoke(InvocationHelper.java:323)
 		at org.infinispan.cache.impl.InvocationHelper.invoke(InvocationHelper.java:111)
 		at org.infinispan.cache.impl.InvocationHelper.invoke(InvocationHelper.java:93)
 		at org.infinispan.cache.impl.CacheImpl.putAll(CacheImpl.java:1361)
 		at org.infinispan.cache.impl.DecoratedCache.putAll(DecoratedCache.java:562)
 		at org.infinispan.cache.impl.DecoratedCache.putAll(DecoratedCache.java:567)
 		at org.infinispan.cache.impl.EncoderCache.putAll(EncoderCache.java:792)
 		at org.keycloak.models.sessions.infinispan.remotestore.RemoteCacheSessionsLoader.loadSessions(RemoteCacheSessionsLoader.java:144)
 		at org.keycloak.models.sessions.infinispan.remotestore.RemoteCacheSessionsLoader.loadSessions(RemoteCacheSessionsLoader.java:47)
 		at org.keycloak.models.sessions.infinispan.initializer.SessionInitializerWorker$1.run(SessionInitializerWorker.java:71)
 		at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:262)
 		at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:384)
 		at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:261)
 		at org.keycloak.models.sessions.infinispan.initializer.SessionInitializerWorker.apply(SessionInitializerWorker.java:67)
 		at org.keycloak.models.sessions.infinispan.initializer.SessionInitializerWorker.apply(SessionInitializerWorker.java:34)
 		at org.infinispan.manager.impl.ReplicableManagerFunctionCommand.invokeAsync(ReplicableManagerFunctionCommand.java:45)
 		at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler$ReplicableCommandRunner.run(GlobalInboundInvocationHandler.java:256)
 		at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler.handleReplicableCommand(GlobalInboundInvocationHandler.java:175)
 		at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler.handleFromCluster(GlobalInboundInvocationHandler.java:114)
 		at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1548)
 		at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1476)
 		at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.lambda$up$1(JGroupsTransport.java:1695)
 		at java.base/java.lang.Iterable.forEach(Iterable.java:75)
 		at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1687)
 		at org.jgroups.JChannel.up(JChannel.java:749)
 		at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:939)
 		at org.jgroups.protocols.FRAG2.up(FRAG2.java:161)
 		at org.jgroups.protocols.FlowControl.up(FlowControl.java:319)
 		at org.jgroups.protocols.FlowControl.up(FlowControl.java:319)
 		at org.jgroups.protocols.pbcast.GMS.up(GMS.java:859)
 		at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:246)
 		at org.jgroups.protocols.UNICAST3.deliverBatch(UNICAST3.java:1108)
 		at org.jgroups.protocols.UNICAST3.handleBatchReceived(UNICAST3.java:882)
 		at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:549)
 		at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:722)
 		at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:146)
 		at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:193)
 		at org.jgroups.protocols.FD_SOCK2.up(FD_SOCK2.java:202)
 		at org.jgroups.protocols.MERGE3.up(MERGE3.java:288)
 		at org.jgroups.protocols.Discovery.up(Discovery.java:314)
 		at org.jgroups.protocols.RED.up(RED.java:119)
 		at org.jgroups.protocols.TP.passBatchUp(TP.java:1210)
 		at org.jgroups.util.SubmitToThreadPool$BatchHandler.passBatchUp(SubmitToThreadPool.java:161)
 		at org.jgroups.util.SubmitToThreadPool$BatchHandler.run(SubmitToThreadPool.java:157)
 		... 3 more
ERROR [org.keycloak.models.sessions.infinispan.initializer.InfinispanCacheInitializer] (pool-40-thread-3) Interruped exception when computed future. Errors: 1
 java.lang.InterruptedException
 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
 	at org.keycloak.models.sessions.infinispan.initializer.InfinispanCacheInitializer.startLoadingImpl(InfinispanCacheInitializer.java:183)
 	at org.keycloak.models.sessions.infinispan.initializer.InfinispanCacheInitializer.startLoading(InfinispanCacheInitializer.java:113)
 	at org.keycloak.models.sessions.infinispan.initializer.CacheInitializer.loadSessions(CacheInitializer.java:66)
 	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory$6.run(InfinispanUserSessionProviderFactory.java:343)
 	at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:262)
 	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:384)
 	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:261)
 	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory.loadSessionsFromRemoteCache(InfinispanUserSessionProviderFactory.java:329)
 	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory.loadSessionsFromRemoteCaches(InfinispanUserSessionProviderFactory.java:321)
 	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory.access$800(InfinispanUserSessionProviderFactory.java:72)
 	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory$1.lambda$onEvent$0(InfinispanUserSessionProviderFactory.java:129)
 	at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:262)
 	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:384)
 	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:261)
 	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithTimeout(KeycloakModelUtils.java:475)
 	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory$1.onEvent(InfinispanUserSessionProviderFactory.java:123)
 	at org.keycloak.services.DefaultKeycloakSessionFactory.publish(DefaultKeycloakSessionFactory.java:91)
 	at org.keycloak.testsuite.model.KeycloakModelTest.createKeycloakSessionFactory(KeycloakModelTest.java:349)
 	at org.keycloak.testsuite.model.KeycloakModelTest.inIndependentFactory(KeycloakModelTest.java:496)
 	at org.keycloak.testsuite.model.KeycloakModelTest.lambda$inIndependentFactories$6(KeycloakModelTest.java:401)
 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 	at java.base/java.lang.Thread.run(Thread.java:840)
DEBUG [org.keycloak.testsuite.model.KeycloakModelParameters] (pool-40-thread-4) Closing KeycloakSessionFactory 25 (from pool-40-thread-4 thread)
ERROR [org.keycloak.models.sessions.infinispan.initializer.CacheInitializer] (pool-40-thread-1) Interrupted
 java.lang.InterruptedException: sleep interrupted
 	at java.base/java.lang.Thread.sleep(Native Method)
 	at java.base/java.lang.Thread.sleep(Thread.java:344)
 	at java.base/java.util.concurrent.TimeUnit.sleep(TimeUnit.java:446)
 	at org.keycloak.models.sessions.infinispan.initializer.CacheInitializer.loadSessions(CacheInitializer.java:41)
 	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory$6.run(InfinispanUserSessionProviderFactory.java:343)
 	at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:262)
 	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:384)
 	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:261)
 	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory.loadSessionsFromRemoteCache(InfinispanUserSessionProviderFactory.java:329)
 	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory.loadSessionsFromRemoteCaches(InfinispanUserSessionProviderFactory.java:321)
 	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory.access$800(InfinispanUserSessionProviderFactory.java:72)
 	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory$1.lambda$onEvent$0(InfinispanUserSessionProviderFactory.java:129)
 	at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:262)
 	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:384)
 	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:261)
 	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithTimeout(KeycloakModelUtils.java:475)
 	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory$1.onEvent(InfinispanUserSessionProviderFactory.java:123)
 	at org.keycloak.services.DefaultKeycloakSessionFactory.publish(DefaultKeycloakSessionFactory.java:91)
 	at org.keycloak.testsuite.model.KeycloakModelTest.createKeycloakSessionFactory(KeycloakModelTest.java:349)
 	at org.keycloak.testsuite.model.KeycloakModelTest.inIndependentFactory(KeycloakModelTest.java:496)
 	at org.keycloak.testsuite.model.KeycloakModelTest.lambda$inIndependentFactories$6(KeycloakModelTest.java:401)
 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by ahus1** [comment]
@martin-kanis - I did another review, and another run. This one failed only two times.  https://github.com/ahus1/keycloak/actions/runs/6733624344/job/18303482814

The two remaining failures show the error you also mentioned above. I created a new issue, and I already have an idea why this is failing and how it can be fixed. See #24508

This PR is now squashed and cleaned up, and show be hopefully good enough to be merged.

**Review by martin-kanis — APPROVED** [review]
Thanks for the effort @ahus1! This looks good.

**Review by mhajas — APPROVED** [review]
Thank you @ahus1!

**Pull request merged**
