### PR TITLE
KEYCLOAK-12045 Improve UX for the Credentials tab in Admin Console

### PR DESCRIPTION
**Pull request by vmuzikar**

### CODE REVIEW

**Comment by mposolda** [comment]
Thanks! LGTM, when just looking at the sources. I did not tried it myself. Will try to check with someone in the team for trying it and review further. @vmuzikar I assume you checked the admin console tests if they are not broken? :)

**Comment by vmuzikar** [comment]
@mposolda Thanks for the review! Yes, the tests are currently running: https://keycloak-jenkins.com/job/keycloak-ui-matrix_nightly/146/ ;)

**Comment by vmuzikar** [comment]
One of the tests on IE failed but that's unrelated to this change.

**Review by ssilvert — COMMENTED** [review]
Looks fine from the code.  I'll wait to hear from @mposolda and his team before giving approval.

**Comment by abstractj** [comment]
@mposolda adding you as reviewer, but feel free to delegate to someone else if you don't have the time.

**Review by Pepo48 — APPROVED** [review]
@vmuzikar LGTM, good job! Thanks!

@mposolda @ssilvert jfyi.

**Review by mposolda — APPROVED** [review]
@Pepo48 Thanks! I am approving too based on your review.

**Comment by ssilvert** [comment]
Holding for Keycloak 11

**Review by ssilvert — APPROVED** [review]

**Pull request merged**
