### PR TITLE
Wrong Italian Message into HTML Email

### PR DESCRIPTION
**Pull request by maramazza**
Into the Italian HTML Message Email there is a problem with the link.

### CODE REVIEW

**Review by ahus1 — APPROVED** [review]
Changes look good, thank you for the contribution!

**Comment by ahus1** [comment]
Hi @hmlnarik - this PR looks good, I'd be happy if you could merge it. Thanks!

**Review by ahus1 — CHANGES_REQUESTED** [review]
For translations want them to be reviewed by someone familiar with the language. Unfortunately I don't know Italian.
Therefore, please ask someone else who you know (or ask on the user's mailing list) to confirm in this PR with a comment or a GitHub review that this a correct Italian translation. Thanks!

**Comment by maramazza** [comment]
[ahus1](https://github.com/ahus1) sorry if i made some mistake... I hope that now is ok

**Comment by fcps3** [comment]
> For translations want them to be reviewed by someone familiar with the language. Unfortunately I don't know Italian. Therefore, please ask someone else who you know (or ask on the user's mailing list) to confirm in this PR with a comment or a GitHub review that this a correct Italian translation. Thanks!

I'm italian, translation is perfect

**Pull request merged**
