### PR TITLE
KEYCLOAK-14145 OIDC support for Client "offline" session lifespan

### PR DESCRIPTION
**Pull request by y-tabata**
JIRA: https://issues.redhat.com/browse/KEYCLOAK-14145

# Spec
## GUI
- Add **Client Offline Session Idle** and **Client Offline Session Max** to the Tokens tab of the Realm Settings.
  - They are displayed only when the **Offline Session Max Limited** is ON.
  - The default value is 0.
- Add **Client Offline Session Idle** and **Client Offline Session Max** to the Advanced Settings of each client's Settings tab of the Clients.
  - If the **Offline Session Max Limited** is OFF, they are ignored.
  - The default value is null.

## exp claim of the offline token
- If using the offline token and the **Offline Session Max Limited** is ON, set the shorter one between the expiry calculated by the **Offline Session Idle** and that of the **Offline Session Max** and that of the **Offline Client Session Idle** and that of the **Offline Client Session Max**.
- The **Client Offline Session Idle** and the **Client Offline Session Max** can be overwritten by each client.

## exp claim of the access token
- If using the offline token and the **Offline Session Max Limited** is ON, set the shorter one between the expiry calculated by the **Access Token Lifespan** and that of the **Offline Session Max** and that of the **Client Offline Session Max**.
- The **Client Offline Session Max** can be overwritten by each client.

### CODE REVIEW

**Comment by y-tabata** [comment]
Docs PR: keycloak/keycloak-documentation#941

**Review by mposolda — CHANGES_REQUESTED** [review]
@y-tabata Thanks for the PR! I am not sure if this was discussed on keycloak-dev before this PR was sent. I can't recall discussion related to Client offline session lifespans?

To me, it seems the issue that we have 2 new timeouts introduced for the realm and 2 new timeouts introduced for the client. So 4 new timeout options. We already have quite a lot of timeouts...

I hope it will be possible to have just 2 new timeouts on the client and not add anything new on the realm. I think that by default, client offline session timeout can be inherited from the offline user session timeouts. Just in case that they are overriden for particular client, then the timeouts set at the client level will take precedence.

**Comment by y-tabata** [comment]
@mposolda 
> I am not sure if this was discussed on keycloak-dev before this PR was sent. I can't recall discussion related to Client offline session lifespans?

We had a little discussion in [1] and in my understanding, this client session lifespan for the offline token is one of the important reasons which Stian decided ok to contribute to [2]. If needed, I will start to open the discussion again.

[1] https://groups.google.com/forum/#!topic/keycloak-dev/T4k3sMzYmuA
[2] https://github.com/keycloak/keycloak/pull/7012

> To me, it seems the issue that we have 2 new timeouts introduced for the realm and 2 new timeouts introduced for the client. So 4 new timeout options. We already have quite a lot of timeouts...

I know. However, I believe we need to reduce the difference between the settings of the refresh token and the settings of the offline token.
Regarding the refresh token, according to [3], there are already 4 timeout options for the refresh token (2 timeouts for the realm, and 2 timeouts for the client). For me, if we add only 2 new options for the client, it makes users some confusing because of the difference of the settings between the refresh token and the offline token. How do you think?

[3] https://github.com/keycloak/keycloak/pull/6581

**Comment by mposolda** [comment]
@y-tabata Sorry for late answer. More inline...

> @mposolda
> 
> > I am not sure if this was discussed on keycloak-dev before this PR was sent. I can't recall discussion related to Client offline session lifespans?
> 
> We had a little discussion in [1] and in my understanding, this client session lifespan for the offline token is one of the important reasons which Stian decided ok to contribute to [2]. If needed, I will start to open the discussion again.
> 
> [1] https://groups.google.com/forum/#!topic/keycloak-dev/T4k3sMzYmuA
> [2] #7012

I went again through that discussion [1] and I don't see anything in that discussion about introducing 4 new timeout options just because of offline client session timeout. Could you please start new discussion on keycloak-dev about this?

> 
> > To me, it seems the issue that we have 2 new timeouts introduced for the realm and 2 new timeouts introduced for the client. So 4 new timeout options. We already have quite a lot of timeouts...
> 
> I know. However, I believe we need to reduce the difference between the settings of the refresh token and the settings of the offline token.
> Regarding the refresh token, according to [3], there are already 4 timeout options for the refresh token (2 timeouts for the realm, and 2 timeouts for the client). For me, if we add only 2 new options for the client, it makes users some confusing because of the difference of the settings between the refresh token and the offline token. How do you think?
> 
> [3] #6581

I see. And I wonder if we can rather remove the "Client Session Idle" and "Client Session Max" options from the realm instead of introducing options also for offline token. And allow them to be overriden just at the client level?

Honestly, I am a bit scared when I look at the "Realm -> Tokens" tab :-) I think the original idea of Keycloak is to address most of the use-cases and still be relatively easy to use. So big amount of timeout options doesn't help with that target IMO.

**Comment by y-tabata** [comment]
@mposolda 
According to [1], could you start to review this PR?

[1] https://groups.google.com/forum/#!topic/keycloak-dev/BLvrhibZ87Y

**Review by mposolda — APPROVED** [review]
@y-tabata Sure. I am sorry for the delay. Thanks for starting the discussion on keycloak-dev and Thanks again for your contribution!

**Pull request merged**
