### PR TITLE
update javax.json (1.1.6) to jakarta.json (2.0.1)

### LINKED ISSUE #11544: update javax.json (1.1.6) to jakarta.json (2.0.1)
### Description

update javax.json (1.1.6) to jakarta.json (2.0.1)

This package appears to only be in used in
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java

### Discussion

_No response_

### Motivation

I'm running into more and more projects that are using the newer library.

### Details

_No response_

### PR DESCRIPTION
**Pull request by ebremer**
update javax.json (1.1.6) to jakarta.json (2.0.1)
Closes #11544

### CODE REVIEW

**Comment by ahus1** [comment]
Thanks for contributing to this project with this pull request!

When creating PRs, this project asks in its [contributing guidelines](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md) to:

* create a GitHub issue first
* reference the GitHub issue in the commit message of the pull request with a message as the following:
  ```
  A brief descriptive summary

  Optionally, more details around how it was implemented

  Closes #1234
  ```
* update the description of this PR to include `Closes #1234`.

This will help collaboration on GitHub in two ways:

1. It populates the right-hand column on both the issue and the PR with a reference to the issue you're about to fix.
2. It will close the issue once the PR has been merged automatically.

All of this allows us to track all changes in the Git commit log to the issue on GitHub.

In addition to that, the issue will reveal more about the problem you're planning to solve by updating this library.

Thanks!

**Review by stianst — CHANGES_REQUESTED** [review]
Rather than updating this we should switch this single place that is using it to FasterXML to be consistent with the rest of the project. Also worth noting that the version in the parent pom is not the version that goes into either the WF or the Quarkus dist.

**Comment by ebremer** [comment]
@stianst I added a new pull request which does this.  If this one works for you, we can close the other PR.

**Comment by ebremer** [comment]
closing in lieu of #11554

**Pull request closed without merging**
