### PR TITLE
[KEYCLOAK-7523] better context path detection in PathBasedKeycloakCon…

### PR DESCRIPTION
**Pull request by grgrzybek**
…figResolver

### CODE REVIEW

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Since Keycloak does not use mocking libraries for testing (see recent discussion on keycloak-dev), can you test it without mocks?

**Comment by grgrzybek** [comment]
doesn't it? I saw it's used in `org.keycloak.adapters.springboot.client.KeycloakSecurityContextClientRequestInterceptorTest`...

I read http://lists.jboss.org/pipermail/keycloak-dev/2018-May/010875.html and I kind of agree - or rather I don't want to change the rules established in Keycloak project.
In Fuse we used a lot of mocking - mostly to test error scenarios. These can't simply be tested with arquillian and real server.

I just found mocking OSGi infra (bundle contexts, service registry) and servlet interaction (HttpServletRequest) to be very useful it you just test some simple logic - I really don't need running server for that.

**Comment by grgrzybek** [comment]
I updated the PR - no more mockito

**Comment by hmlnarik** [comment]
@grgrzybek Thank you. @vramik Could you please check app-server-fuse63 with this PR?

**Comment by vramik** [comment]
@hmlnarik the PR passed app-server-fuse63 tests

**Review by hmlnarik — APPROVED** [review]
@grgrzybek Thanks for the contribution!

**Pull request merged**
