### PR TITLE
Credential validation shouldn't invalidate the user in the cache

### LINKED ISSUE #14309: Credential validation not taking into account if the user is already cached
### Describe the bug

The changes introduced here https://github.com/keycloak/keycloak/pull/11933, in particular to https://github.com/keycloak/keycloak/blob/main/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserAdapter.java#L292, are forcing a database round-trip even though the user was previously cached.

### Version

19.0.1

### Expected behavior

During authentication, user data should be returned from the cache and do not force an invalidation when obtaining a credential manager.

### Actual behavior

_No response_

### How to Reproduce?

Try to authenticate and check if on the second attempt the user is marked for invalidation and unnecessary round-trips to the database happen.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Instead create a new instance of LegacyUserCredentialManager to ensure all calls are routed via the CacheAdaper and its SubjectCredentialManagerCacheAdapter.

Closes #14309

### CODE REVIEW

**Comment by ahus1** [comment]
@hmlnarik - this change prevents the users to be invalidated from the cache on login. 

I found that the `UserCacheSession.cacheUser()` is the best place debug when a user instance is cached. 

I tested that the invalidation is called on a regular login when the number of hash iterations has been changed and therefore `PasswordCredentialProvider.isValid()` updates the credentials.

As a side effect validating the password will now use the cached credentials and no longer hit the database (as before the legacy refactoring). 

This kind of big assumption is that `UserAdapter` creates a new instance of LegacyUserCredentialManager(), while a legacy store implementation could decide to now return such an instance, or a modified instance. 

I'd like to get your feedback on this. This has been marked as a candidate for backporting it to 19.x. Thanks!

**Review by hmlnarik — DISMISSED** [review]

**Comment by ahus1** [comment]
@hmlnarik agreed that this approach would be valid, will continue to work on the PR to make the tests pass.

**Review by sguilhen — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
