### PR TITLE
Ensure organization id is preserved on export/import

### LINKED ISSUE #33207: [Organizations] Preserve org id in exported realms
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When exporting a realm with orgs, the organization ids are not exported, and are re-generated when imported back. This prevents the ids from being mapped into access tokens, for example.

See discussion https://github.com/keycloak/keycloak/discussions/32364 for more details on why this is problematic

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Organization ids should be preserved on export/import so that any tokens referencing the org by id would still be valid

### Actual behavior

The ids are regenerated once the realm with the orgs is re-imported.

### How to Reproduce?

Export a realm with organizations, then re-import it. Check that the org ids have changed.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sguilhen**
- Also fixes issues with description, enabled, and custom attributes missing when re-importing the orgs.

Closes #33207

### CODE REVIEW

**Review by vramik — COMMENTED** [review]
Changes LGTM, thank you @sguilhen! It might be worth to also add a testcase, wdyt?

**Review by vramik — APPROVED** [review]
Test will be added as a follow-up. Thanks

**Comment by sguilhen** [comment]
@vramik sorry for the confusion, I ended up updating the tests in this PR

**Review by vramik — APPROVED** [review]

**Review by vramik — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]
Approving based on @vramik's review

**Pull request merged**
