### PR TITLE
KEYCLOAK-17938 Not possible to create client in the admin console when client policy with "secure-redirecturi-enforce-executor" condition is used

### PR DESCRIPTION
**Pull request by tnorimat**
This PR is for [KEYCLOAK-13933 Client Policies](https://issues.redhat.com/browse/KEYCLOAK-13933), also is the part of the project [Client Policy Official Support](https://github.com/keycloak/kc-sig-fapi/projects) of [FAPI-SIG](https://github.com/keycloak/kc-sig-fapi) activity.

[KEYCLOAK-17938](https://issues.redhat.com/browse/KEYCLOAK-17938) describes it in detail.

### CODE REVIEW

**Comment by tnorimat** [comment]
@mposolda This PR treats the one of the follow-up tasks you've created. Could you review it?

**Review by mposolda — CHANGES_REQUESTED** [review]
@tnorimat Thanks a lot for the PR!

Regarding this executor, is it possible to also add another small improvement I suggested in the JIRA to make it a bit more secure?

For more details, the FAPI specification talks only about redirect_uri, but IMO it will be nice to make sure that other URLs of the client are secured as well (especially in relation to "https" protocol). So I was thinking that we can possibly introduce new switch like "Enforce all client URIs secure" . IMO it can be true by default. In case it is true, then all other client URIs can be checked during client registration + client update request to be secured and NOT start with "http" . Especially the URLs like: rootUrl, adminUrl, baseUrl, web origin, jwks URL, backchannel logout URL. WDYT? Does it makes sense to you to add something like this?

**Comment by tnorimat** [comment]
@mposolda I see, I'll check the JIRA ticket's comment.

**Comment by tnorimat** [comment]
@mposolda I've refined codes as you've suggested. Could you check them?

**Review by mposolda — APPROVED** [review]
@tnorimat Thanks for the update!

**Review by mposolda — CHANGES_REQUESTED** [review]
@tnorimat But it looks this PR will require rebase

**Comment by tnorimat** [comment]
@mposolda I've rebased in on the latest master. Could you check it?

**Review by mposolda — APPROVED** [review]
@tnorimat Thanks!

**Pull request merged**
