### PR TITLE
Specific hostname to bind to for H2 in dev mode

### LINKED ISSUE #26042: Issue when start-dev in 23.0.1
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

After downloading version 23, carrying out a simple test reveals the errors as detailed in the [discussion](https://github.com/keycloak/keycloak/discussions/25312#discussioncomment-8044871) 

### Version

23

### Expected behavior

Keycloak started in development mode with H2 database

### Actual behavior

An exception related to the database occurs and the service does not start

### How to Reproduce?

The problem was identified on some machines with Windows 11 and MacOS 14. 

- Just download the zip version, unzip it
- access the bin folder
- run `kc.sh start-dev`

### Anything else?

The problem is occurring in an environment with the configuration below:

```shell
$ java --version
openjdk 17.0.9 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode)
```

```
$system_profiler SPSoftwareDataType SPHardwareDataType
Software:

    System Software Overview:

      System Version: macOS 14.2.1 (23C71)
      Kernel Version: Darwin 23.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: ##########
      User Name: ####################
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 19 days, 19 hours, 36 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro16,1
      Processor Name: 6-Core Intel Core i7
      Processor Speed: 2,6 GHz
      Number of Processors: 1
      Total Number of Cores: 6
      L2 Cache (per Core): 256 KB
      L3 Cache: 12 MB
      Hyper-Threading Technology: Enabled
      Memory: 32 GB
      System Firmware Version: 2020.61.1.0.0 (iBridge: 21.16.2057.0.0,0)
      OS Loader Version: 580~1053
      Serial Number (system): C02FD4MSMD6R
      Hardware UUID: D22635E5-ECFC-55A6-A990-1E7DD9777227
      Provisioning UDID: D22635E5-ECFC-55A6-A990-1E7DD9777227
      Activation Lock Status: Disabled

```

### PR DESCRIPTION
**Pull request by ahus1**
Avoids problems if the hostname can't be resolved by InetAddress.getLocalHost()

I assume the AUTO_MODE set up here is still useful if multiple instances of Keycloak running from the same folder make sense. If it doesn't make sense, let me know.

Closes #26042

### CODE REVIEW

**Comment by ahus1** [comment]
@pedroigor / @Pepo48 / @vmuzikar - I'd like to get your feedback on this, and if AUTO_SERVER mode is useful for Keycloak (either when developing, or in tests). If not, we could simplify the setup. 

See the H2 for more docs on this: https://www.h2database.com/html/features.html#auto_mixed_mode

**Comment by vmuzikar** [comment]
@ahus1 Thank you for the PR.

I'm not aware of any reason to keep `AUTO_SERVER=TRUE`, AFAIK it doesn't work for dev-mem in any case, no real reason to keep it for dev-file from my perspective.

Without it, we don't need to set `h2.bindAddress`?

**Comment by ahus1** [comment]
> Without it [AUTO_SERVER], we don't need to set `h2.bindAddress`?

Yes, this is my understanding. Do we use in the test suite a setup with `dev-file` where we start for example cluster of two nodes, and those access the same database? 

Also asking @pedroigor, @sguilhen and @vramik. Thanks!

**Review by vmuzikar — DISMISSED** [review]

**Comment by ahus1** [comment]
@vmuzikar - with the removal of AUTO_SERVER, it is now no longer possible to run the cluster tests with H2, and instead you'll need to use a real database. 

WDYT? If you think running it with H2 makes things simpler, I'll need to dig deeper into this to figure out how to pass the DB URL options to Quarkus (the CLI allows it, but IMHO the build isn't equipped for that).

**Comment by vmuzikar** [comment]
@ahus1 IMHO that's something for the Core Teams to decide. It is true that is is a bit inconvenient to use a real DB. On the other hand, we should not be including stuff in the dist that is required for tests only...

**Review by pedroigor — COMMENTED** [review]
@ahus1 I would only keep `AUTO_SERVER=true` because it is useful during dev when running multiple instances. I think because of cluster tests and local dev we have this set.

I remember a long time ago solving problems with that setting, probably when enabling cluster tests to quarkus. But you are solving it differently (and better) now.

But if @mposolda thinks otherwise, I don't mind removing it.

**Comment by ahus1** [comment]
@vmuzikar - there haven't been objections by @mposolda, so I assume this can now be merged. I assume this should be backported to KC25. Should it also be backported to KC24? I'd assume yes, please advise if you think differently.

**Review by vmuzikar — APPROVED** [review]
@ahus1 LGTM, thank you.

@miquelsi Do we run cluster tests internally as well? If so, they'll need to be adjusted in the same manner as in this PR.

**Comment by miquelsi** [comment]
> @ahus1 LGTM, thank you.
> 
> @miquelsi Do we run cluster tests internally as well? If so, they'll need to be adjusted in the same manner as in this PR.

No, we don't run cluster tests internally.

**Pull request merged**
