### PR TITLE
KEYCLOAK-8490: Direct grants returns invalid credentials when user ha…

### PR DESCRIPTION
**Pull request by rmartinc**
…s pending actions

### CODE REVIEW

**Comment by stianst** [comment]
Thanks for your PR. This is a valid bug and we want to get the fix in. At first glance the PR looks great, I especially like the thorough testing you've done. Need a bit more time to review it properly before we can merge. Will try to get it reviewed soon, hopefully in time for 4.6 assuming it's good to go.

**Review by abstractj — CHANGES_REQUESTED** [review]
@rmartinc the code and the functionality looks good. It just needs a rebase against master.

@stianst overall, good to go.

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
@abstractj looks clean to merge for me. Not sure what you mean about "rebase against master"?

**Review by abstractj — APPROVED** [review]

**Comment by stianst** [comment]
@rmartinc thanks

**Comment by jbadilla** [comment]
guys: without using the Keycloak Login and Reset Password screens, how can I from this error correctly deduce whether the required user action causing this to fail is "UPDATE_PASSWORD"

I need to implement my own components and handle this error to redirect a user to an update password page.

**Comment by abstractj** [comment]
@jbadilla thanks for reaching out, but I'd appreciate if you send your question to the keycloak user mailing list. We have so many repositories, that's impossible to keep track of discussions happening on closed PRs.

**Pull request merged**
