### PR TITLE
Edit use of Keycloak in Server Admin Guide

### LINKED ISSUE #27955: Address term Keycloak in Server Administration Guide
### Description

Make this term work for downstream.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andymunro**
Closes #27955

@tondrusk @ahus1 Please review

### CODE REVIEW

**Review by ahus1 — APPROVED** [review]
Thank you for this review!

**Comment by tondrusk** [comment]
@andymunro @ahus1 outta curiosity, is there a difference between {project_name}, {project_**N**ame}, and {**P**roject_**N**ame} or are the variables case insensitive?

**Comment by ahus1** [comment]
@tondrusk - they are case insensitive, with the all-lower-case variant preferred.

**Comment by andymunro** [comment]
Yes, I always use all lower case. However, my editor was recently using initial capitals.

**Pull request merged**
