### PR TITLE
Update to Quarkus 3.2.9 (#24842)

### LINKED ISSUE #24160: HTTP/2 - Last parameter of POST form data contains 0x00 byte in some configurations.
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

This is a different manifestation of a previous issue with HTTP/2 handling and empty dataframes - https://github.com/keycloak/keycloak/issues/13315

When an HTTP/2 capable client sends POST data to a Keycloak instance running the current nightly codebase and also ends the HTTP/2 stream with an empty dataframe, the last parameter in the POST data will have a `0x00` byte appended to it. 

This current issue will show up in odd ways - such as Keycloak responding that `grant_type=client_credentials` is an invalid grant type when used at the OIDC Token endpoint, or that PKCE values are invalid.

This is ultimately a problem that should be handled by the resteasy-reactive implementation, but logging this bug for tracking purposes within Keycloak itself.

### Version

main / nightly

### Expected behavior

No `0x00` byte is appending to any form parameters.

### Actual behavior

`0x00` byte is appended to last form parameter, breaking various flows and making the deployment unusable.

### How to Reproduce?

Background:
Our deployment makes use of Openshift, and that uses HAProxy configured to reencrypt and send data to the backend (Keycloak) using http/2 - the HAProxy implementation uses an empty dataframe to close the stream.

Actually reproducing it:
Configure Keycloak with HTTPS and an appropriate TLS certificate.
Use the reproducer code from https://github.com/keycloak/keycloak/issues/13315#issuecomment-1238125070
Debug the code in Keycloak and notice that the last form parameter contains an additional `0x00`

Alternatively, without using Keycloak, it can be reproduced using a generic quarkus app + some of the constructs Keycloak uses

See - https://github.com/jsorah/reproducer/tree/null_bytes_appended_to_form_data

### Anything else?

Disabling HTTP/2 will prevent this issue from occurring.

### LINKED ISSUE #24841: Update to Quarkus 3.2.9
### Description

https://github.com/quarkusio/quarkus/releases/tag/3.2.9.Final

### LINKED ISSUE #24984: Operator is missing CRDs metadata in CSV
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

Compare [22.0.5](https://github.com/k8s-operatorhub/community-operators/blob/main/operators/keycloak-operator/22.0.5/manifests/keycloak-operator.clusterserviceversion.yaml#L48-L59) and [23.0.0](https://github.com/k8s-operatorhub/community-operators/blob/main/operators/keycloak-operator/23.0.0/manifests/keycloak-operator.clusterserviceversion.yaml#L48-L55).
Screenshot 2023-11-23 at 18 25 38

### Version

23.0.0

### Expected behavior

Missing name and desc for CRDs.

### Actual behavior

Metadata present like:
```yaml
spec:
  customresourcedefinitions:
    owned:
      - kind: KeycloakRealmImport
        description: Represents a Keycloak Realm Import
        displayName: KeycloakRealmImport
        name: keycloakrealmimports.k8s.keycloak.org
        version: v2alpha1
      - kind: Keycloak
        description: Represents a Keycloak Instance
        displayName: Keycloak
        name: keycloaks.k8s.keycloak.org
        version: v2alpha1
```

### How to Reproduce?

https://operatorhub.io/operator/keycloak-operator

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes #24841
Closes #24160 

Backports #24842

Conflicts:
  pom.xml

### CODE REVIEW

**Review by mabartos — APPROVED** [review]

**Review by abstractj — APPROVED** [review]
Approving it, given that the migration test failures are not related to the proposed changes here.

**Comment by ahus1** [comment]
As discussed in the chat, this is on hold until the Quarkus 3.2.9 is available as RHBK GA

**Comment by vmuzikar** [comment]
@ASzc Can you please approve once this is ready to be merged, i.e. when RHBQ 3.2.9 is available?

**Comment by vmuzikar** [comment]
This is impacted by https://github.com/keycloak/keycloak/issues/24983
Transferring back to draft before it's resolved.

**Comment by vmuzikar** [comment]
Also impacted by https://github.com/keycloak/keycloak/issues/24984

**Review by mabartos — APPROVED** [review]
@vmuzikar LGTM

**Pull request merged**
