### PR TITLE
Encoded special chars in utf-8 and improved some translations

### PR DESCRIPTION
**Pull request by jaime-pineiro-imatia**

### CODE REVIEW

**Review by jonkoops — CHANGES_REQUESTED** [review]
Rather than encoding the special characters, let's add a header to set the encoding to UTF-8 (see #20848). This also means that previously encoded special chars should be decoded.

**Comment by jaime-pineiro-imatia** [comment]
I've changed encoded chars and added header, but i think it will not work until #20848 is fixed, right?

**Comment by jonkoops** [comment]
> I've changed encoded chars and added header, but i think it will not work until https://github.com/keycloak/keycloak/issues/20848 is fixed, right?

This should work as expected, are you seeing a different result when running Keycloak with these changes? #20848 is intended to convert the rest of the properties over, so you can consider this as a part of delivering that.

**Comment by jaime-pineiro-imatia** [comment]
I'm testing with latest [bitnami's image](https://hub.docker.com/r/bitnami/keycloak) (version 21.1.2) and special chars are not displayed properly 
image

**Comment by jaime-pineiro-imatia** [comment]
In docker-compose.yml like this:
```
keycloak:
    image: docker.io/bitnami/keycloak:latest
    environment:
      KEYCLOAK_DATABASE_HOST: *KEYCLOAK_DATABASE_HOST
      KEYCLOAK_DATABASE_NAME: *KEYCLOAK_DATABASE_NAME
      KEYCLOAK_DATABASE_USER: *KEYCLOAK_DATABASE_USERNAME
      KEYCLOAK_DATABASE_PASSWORD: *KEYCLOAK_DATABASE_PASSWORD
      KEYCLOAK_ADMIN_USER: *KEYCLOAK_USERNAME
      KEYCLOAK_ADMIN_PASSWORD: *KEYCLOAK_PASSWORD
      KEYCLOAK_EXTRA_ARGS_PREPENDED: "--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true"
      KEYCLOAK_EXTRA_ARGS: "--import-realm"
    container_name: XXX-keycloak
    ports:
      - "8082:8080"
    volumes:
      - ./keycloak/import:/opt/bitnami/keycloak/data/import
      - ./keycloak/themes:/opt/bitnami/keycloak/themes
```

**Comment by jonkoops** [comment]
Hi @jaime-pineiro-imatia, sorry for the late update. We've recently landed some changes to properly support UTF-8 (see #21714 and #21755), so this PR will no longer be needed. Thanks again for your efforts!

**Pull request closed without merging**
