### PR TITLE
Remove `P3P` header from authentication flow

### LINKED ISSUE #23348: Remove `P3P` header from authentication flow
Historically we needed the `P3P` header to be set as Microsoft Internet Explorer was the only major browser to support the [P3P policy](https://en.wikipedia.org/wiki/P3P). This protocol was never implemented by any other browser and has been obsolete for quite some time.

Under this issue any code related to setting this header will have to be removed.

### PR DESCRIPTION
**Pull request by jonkoops**
Closes #23348

### CODE REVIEW

**Review by pedroigor — COMMENTED** [review]
@jonkoops LGTM. But it also deserves a reference in the release notes, don't you think?

**Comment by pedroigor** [comment]
Something like that mentions that P3P is obsolete in Windows 10 (Microsoft Edge and all modes of Internet Explorer 11 for Windows 10).

**Comment by jonkoops** [comment]
> But it also deserves a reference in the release notes, don't you think?

I could write something for it, but considering that if you currently try to use Internet Explorer with Keycloak everything already breaks, so it would have no practical impact for end users to land this change. Also, Internet Explorer was the only browser that ever implemented this specification.

So I think adding this to the release notes is not needed.

**Review by pedroigor — APPROVED** [review]

**Comment by ahus1** [comment]
I know I'm too late as this issue has already been merged: The reason for the P3P header is usually that it was the only way on IE11 to support cross-domain cookies. I'm adding it here as I didn't see it mentioned in the PR or the parent issue. 

See for example this page https://my.f5.com/manage/s/article/K40326169

> The P3P header is required for Internet Explorer 11 browser to support Cross-Domain cookies

Once you remove it, cross-domain cookies will no longer work with IE11. 

Do we somewhere list supported browser?

**Comment by pedroigor** [comment]
I agree with the idea behind this PR so we shouldn't support browsers no longer supported by their vendors.

**Comment by jonkoops** [comment]
>The reason for the P3P header is usually that it was the only way on IE11 to support cross-domain cookies.

Yeah, but we haven't supported IE11 for quite some time now, so it doesn't really matter if we break compatibility.

> Do we somewhere list supported browser?

Currently we do not have a central resource for the supported browsers, but it's on our radar (see #22266).

**Pull request merged**
