### PR TITLE
Enable WebAuthn tests for Firefox

### LINKED ISSUE #22075: Enable WebAuthn tests for Firefox
### Description

Once the https://github.com/keycloak/keycloak/issues/22074 is resolved, we can enable WebAuthn tests executed in our GHA CI again. 

These tests are disabled in https://github.com/keycloak/keycloak/pull/22071.

### PR DESCRIPTION
**Pull request by mabartos**
Closes #22075

### CODE REVIEW

**Review by jonkoops — COMMENTED** [review]
Would be good to document for each instance why Firefox is ignored for future reference.

**Review by jonkoops — APPROVED** [review]
LGTM

**Review by miquelsi — APPROVED** [review]

**Comment by miquelsi** [comment]
Thanks @mabartos!

**Review by vmuzikar — APPROVED** [review]
Approving based on the reviews from @miquelsi and @jonkoops.

**Pull request merged**
