### PR TITLE
[KEYCLOAK-4474] swagger integration to document all apis and models

### PR DESCRIPTION
**Pull request by amirtoole**
The following urls document all apis and their request/response:
/auth/swagger.json and /auth/swagger.yaml

How to generate a client library and which languages/frameworks are supported can be found here:
https://github.com/swagger-api/swagger-codegen

If documentation or other information is needed, let me know.

### CODE REVIEW

**Comment by Azuka** [comment]
Awesome work, @hellofornow. @stianst, would you mind looking / recommending someone to review?

**Comment by stianst** [comment]
Thanks for this. I will review this most likely next week and get back to you.

**Comment by wan-gan** [comment]
I suggest to change the annotation @Api in the files services/src/main/java/org/keycloak/services/resources/admin/*.java to use the name of the class

Details can be found in my pull request of a forked repository
https://github.com/caseware/keycloak/pull/2

**Comment by Azuka** [comment]
@hellofornow, @wan-gan, does either of you have a swagger json I can start using to generate a go client? I'm having issues building locally to run (probably because I don't know my way around Maven).

**Comment by hellofornow** [comment]
[keycloak-3.4.3.Final.yaml.txt](https://github.com/keycloak/keycloak/files/2055429/keycloak-3.4.3.Final.yaml.txt)
I've attached a yaml file -- had to add `.txt` extension to be github compatible

**Comment by Azuka** [comment]
Hi @hellofornow, would you happen to have an updated swagger? Thanks.

**Comment by hellofornow** [comment]
@Azuka attached latest version
[swagger.yaml.txt](https://github.com/keycloak/keycloak/files/2143512/swagger.yaml.txt)

**Comment by Azuka** [comment]
Thanks. I went ahead and started writing a go client since some of the generation doesn't quite work as well for go.

**Comment by illes** [comment]
for Swagger definitions and Swagger UI of a more recent version, see #5506

**Comment by illes** [comment]
Adding [`swagger-maven-plugin`](https://github.com/kongchen/swagger-maven-plugin), we could get rid of `swagger-doclet` entirely, the drop in-replacement for in `services/pom.xml`:

```xml
<plugin>
    <groupId>com.github.kongchen</groupId>
    <artifactId>swagger-maven-plugin</artifactId>
    <version>3.1.8-SNAPSHOT</version>
    <configuration>
        <apiSources>
            <apiSource>
                <info>
                    <title>${product.name.full} Admin REST API</title>
                    <description>This is a REST API reference for the ${product.name.full} Admin</description>
                    <version>1</version>
                </info>
                <!--<descriptionFile>${project.basedir}/target/docs/swagger/apiinfo.json</descriptionFile>-->
                <schemes>
                    <scheme>http</scheme>
                </schemes>
                <host>localhost:8080</host>
                <basePath>/auth</basePath>
                <locations>
                    <!-- 
                    Sub-resources are also annotated with @Api/@Path, hence to make the swagger parser 
                    exclude them as top-level resources, we have to specify entry point classes instead of packages.
                    https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X#swagger-core-annotations
                    -->
                    <location>org.keycloak.services.resources.admin.AdminRoot</location>
                    <location>org.keycloak.protocol.oidc.OIDCLoginProtocolService</location>
                </locations>
                <springmvc>false</springmvc>
                <swaggerDirectory>${project.basedir}/target/apidocs-rest/swagger/</swaggerDirectory>
                <swaggerFileName>service</swaggerFileName>
            </apiSource>
        </apiSources>
    </configuration>
    <executions>
        <execution>
            <phase>compile</phase>
            <goals>
                <goal>generate</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

Unfortunately, to get sub-resources not matching return type right (e.g. in `AdminRoot.getRealmsAdmin()` is declared to return `Object`), one still has to add `@ApiOperation(response=...)` annotations and [patch the plugin](https://github.com/kongchen/swagger-maven-plugin/pull/661) (hence version `3.1.8-SNAPSHOT`).

**Comment by abstractj** [comment]
@hellofornow could you please rebase and squash your commits in a single one? It helps for code review.

**Comment by hellofornow** [comment]
@abstractj merged latest master and squashed

**Comment by abstractj** [comment]
@hellofornow thanks so much for spending time submitting this patch. We're going to revisit this change in the future looking for a definitive solution to fix the docs. For now I'm putting this on hold.

**Comment by melissapalmer** [comment]
I'd really like to use the swagger spec for client code generation against Keyclaok API 
- is there a reason why this PR hasn't been included into main branch? 
- could that be considered again? 

@stianst / @abstractj  would you mind looking at this PR again / recommending someone to review?
@hellofornow wonder if you could make sure the PR is mergable again 

Thank You in advance. 
Melissa

**Comment by abstractj** [comment]
@melissapalmer Hi Melissa, sorry for not getting back to you earlier. This PR needs to be revisited and updated @douglaspalmer has been looking into https://issues.jboss.org/browse/KEYCLOAK-9655 which will probably incorporate changes from this PR.

**Comment by brnbs** [comment]
@abstractj @douglaspalmer thanks for the update, is there an ETA on finishing this feature? Would be very useful for me as well.

**Comment by stianst** [comment]
Thanks for the PR. We are currently investigating how we can best provide good quality documentation (and Swagger files) for REST APIs. Keeping this open as we may take some inspiration from it, but we will start addressing proper docs in Account REST API and visit Admin REST API afterwards.

**Comment by stianst** [comment]
Suggestions to change how we generate the API docs should be brought up on the dev ML prior to working on a PR.

**Comment by Hronom** [comment]
@stianst and it dead after N years?

> We are starting this by introducing a new Account API, which we hope will serve as a reference API.

This was not done as I see and Account API becomes undocumented at all

**Pull request closed without merging**
