### PR TITLE
KEYCLOAK-18603 Remove duplicated statement

### PR DESCRIPTION
**Pull request by ValentinH**
This is super minor but saw this while reading this file.

### CODE REVIEW

**Comment by hmlnarik** [comment]
Thank you spotting this! Could you please introduce a JIRA and refer it in the commit message?

**Comment by ValentinH** [comment]
I created the ticket and updated the PR title. Is this enough?

**Comment by hmlnarik** [comment]
> I created the ticket and updated the PR title. Is this enough?

Thank you! If you could also change the commit message (`git commit --amend`), that would be all.

**Comment by ValentinH** [comment]
> > I created the ticket and updated the PR title. Is this enough?
> 
> Thank you! If you could also change the commit message (`git commit --amend`), that would be all.

done

**Comment by hmlnarik** [comment]
> > > I created the ticket and updated the PR title. Is this enough?
> > 
> > 
> > Thank you! If you could also change the commit message (`git commit --amend`), that would be all.
> 
> done

Thank you!

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
