### PR TITLE
KEYCLOAK-10071 check isNaN for minValidity

### PR DESCRIPTION
**Pull request by serl**

### CODE REVIEW

**Comment by serl** [comment]
Let me know if there are tests to update/add

**Comment by stianst** [comment]
It would be better to throw an error in this case rather than a info log statement. The info log statement can easily be missed.

**Comment by serl** [comment]
I see your point, actually it is exactly what I was about to do, then I thought that:
- throwing there is equivalent to say that the token is not valid, so it could lead to misinterpretation. (For example, in our code we'll logout the user, sending it back to login page. Maybe we're not the only ones)
- the parameter is optional, isn't an exception too much? (Given that we can fix that with the default value)

Still, I agree that console.info isn't enough, I would change it to warn at least.

Let me know what you think about this.

**Comment by ssilvert** [comment]
When this happens, does it not mean that there is a bug in the application code?  In that case your application needs to be fixed.  Why fall back to some default value when you really need to be notified about a bug?

**Comment by stianst** [comment]
I agree with Stan here, it's a bug in app code, so changing to a default
value is just potentially making a bug in the app hard to find.

**Comment by serl** [comment]
Yep, you're totally right, I edited the commit.

I didn't really run the code. Is there somewhere a test project? Otherwise, I could try something on Monday. Let me know.

**Review by ssilvert — APPROVED** [review]
I'm fine with this change.  Thanks.

**Pull request merged**
