### PR TITLE
KEYCLOAK-2962

### PR DESCRIPTION
**Pull request by santoszv**
Adressing KEYCLOAK-2962 using a new property in "KeycloakDeployment" class.

### CODE REVIEW

**Comment by stianst** [comment]
There's already a solution to completely disable login which is using a bearer-type application type. This is just the same thing isn't it?

**Comment by stianst** [comment]
For a proper solution I'd rather have a way to define what requests to redirect. It could have an include content-types and/or exclude content-types.

For example:

    {
        enable-login-redirect: [ "text/html" ]
    }

And complement that with:

    {
        disable-login-redirect: [ "application/json" ]
    }

That would allow users to control either by including only those they want to redirect. Or to exclude only those they don't want to redirect. This should give enough flexiblity for all scenarios.

**Comment by santoszv** [comment]
Calling KeycloakDeployment.setBearerOnly(true) is working well for AJAX requests, there is not any problem there, general speaking.

I have a set of URLs with a special requirement, responses with 403 status if the user is not authenticated. Initially, i was returning "null" from a config resolver, to force a 403 status, although, the messages in log about an unconfigured deployment were not welcomed.

This approach also works in other cases like "AJAX", because the deployment is resolved per request, any place where is necesary a 403 status response can be handled by disabling redirection. Setting "bearer-only" works well, unless you need a 403 status response.

**Comment by stianst** [comment]
I'm not following. If it's not authenticated a 401 is returned for a bearer-only service. Returning 403 should only be done if the user is authenticated, but doesn't have the correct permissions. That's what the adapters already do. So I really don't see what you are trying to achieve here.

**Pull request closed without merging**
