### PR TITLE
[KEYCLOAK-8289] - Remove authorization services from product preview profile

### PR DESCRIPTION
**Pull request by pedroigor**
…

### CODE REVIEW

**Review by stianst — APPROVED** [review]

**Review by stianst — DISMISSED** [review]
Fine grained authz should still remain preview

**Review by vramik — CHANGES_REQUESTED** [review]
Hey @pedroigor, do not forget to search for usages of ProfileAssume.assumePreviewDisabled() and ProfileAssume.assumeCommunity() in the testsuite and check if some of the usages affect Authz services. (e.g. like AuthorizationDisabledInPreviewTest)

**Comment by pedroigor** [comment]
@vramik, tks for the heads up. Related changes should be here now.

**Review by stianst — COMMENTED** [review]
Looks good to me, but wait for Vlasta to review properly before merging.

**Review by vramik — APPROVED** [review]
LGTM, thanks @pedroigor

**Review by stianst — APPROVED** [review]

**Pull request merged**
