### PR TITLE
Dependency alignment with WF-parent BOM

### PR DESCRIPTION
**Pull request by lkubik**
Hi,
I used a Wildfly-parent as a BOM for dependency alignment with Wildfly versions. This changes could save productization some time. Take it as a proposal and tell me what can and what cannot be done. I did it in a half-automatic way so there are also changes in not productized modules. I can remove them but I would prefer to have as many versions as possible managed by a single BOM.

### CODE REVIEW

**Comment by lkubik** [comment]
Weird, it passed on local. Any ideas why this failed? Is there any way to retest it or view full log?

**Comment by stianst** [comment]
I want to hold off on merging this until after 1.4 is released

**Comment by lkubik** [comment]
Do not merge this PR yet. This won't be 100% compatible with EAP 6.x

**Comment by stianst** [comment]
Closing it for now - then we can discuss what we need to do when I get back

**Pull request closed without merging**
