### PR TITLE
Incorrect Url on Keycloak Health - Liveness and Readiness, no Startup Probes

### LINKED ISSUE #17388: Incorrect Url on Keycloak Health - Liveness and Readiness, no Startup Probes
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

operator

### Describe the bug

I have set the Crds for a deployment, and enabled Health using the Additional Options. 
```
    - name: health-enabled
      value: "true"
    - name: metrics-enabled
      value: "true"
```

The pod starts ok, but ends up in a continuous restart loop as the readiness probe is never satisfied

Looking at the deployed probes, I see an error in the url `http://:8080//health/live` mnnote the `//` before health path

image

### Version

21.0.0

### Expected behavior

Health Probes should work, we should see a startup probe

### Actual behavior

Health Probes sdo not work, we do not see a startup probe

### How to Reproduce?

As described above in the CRD

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
Fixes #17388

### CODE REVIEW

**Comment by mabartos** [comment]
I was able to reproduce the issue and after these changes, the problem disappeared. The fix looks straightforward and probably does not need any test case. Manually confirmed the solution works.

@shawkins @Pepo48 Are you ok with that?

**Comment by shawkins** [comment]
> @shawkins @Pepo48 Are you ok with that?

Seems good.  In the furutre it wouldn't be too hard to adapt the unit.PodTemplateTest to test the StatefulSet, not just the PodTemplate, without introducing more integration tests.

**Comment by mabartos** [comment]
@shawkins Thanks for your comment. I've added a small test case and also the possibility to specify additional Keycloak spec. Can be extended/refactored once there's a need for particular functionality.

**Comment by shawkins** [comment]
LGTM

**Comment by Pepo48** [comment]
LGTM as well, thanks @mabartos.

**Review by abstractj — APPROVED** [review]

**Pull request merged**
