### PR TITLE
Add translation to portuguese

### LINKED ISSUE #11194: Translation of administration button "View all groups" is missing
### Describe the bug

When I use locale pt_BR the button "View all groups" is not translated to portuguese, looking at the admin-messages_pt_BR.properties the button identifier is missing, so it needs to create a new line in this file like this:

`view-all-groups=Exibir todos os grupos
`

### Version

17.0.1

### Expected behavior

When the administration opens the groups menu:
http://<keycloak-base-url>/auth/admin/master/console/#/realms/master/groups using locate pt_BR, he must see the button "View all groups" with the translated text: "Exibir todos os grupos".

### Actual behavior

When the administration opens the groups menu:
http://<keycloak-base-url>/auth/admin/master/console/#/realms/master/groups using locate pt_BR, he actually see the button "View all groups" in english.

### How to Reproduce?

Administrator user has to open the groups menu:
http://<keycloak-base-url>/auth/admin/master/console/#/realms/master/groups using locate pt_BR and check the view all groups button.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by lexcao**
For
- `view-all-groups`
- `view-all-roles`

Fixes https://github.com/keycloak/keycloak/issues/11194

### CODE REVIEW

**Review by sguilhen — APPROVED** [review]
These are indeed missing in the `pt_BR` version of the admin-messages file.

**Comment by trixpan** [comment]
@lexcao @sguilhen I know we use "role" in some of the other messages but may I suggest we adopt "função" across the board.

RBAC is generaly translated in PT-BR as "(Controle de Acesso|Segurança) Baseada em Função"



 e.g.

https://www.gov.br/governodigital/pt-br/seguranca-e-protecao-de-dados/guias/guia_framework_seguranca.pdf (Pag 23, Controle 6.8)

also:

https://docs.microsoft.com/pt-br/dotnet/standard/security/role-based-security
https://www.ibm.com/docs/pt-br/integration-bus/10.0?topic=overview-role-based-security

**Comment by trixpan** [comment]
@sguilhen sure. If we get this PR merged I will be happy to open another one moving from "role" to "função"

**Comment by sguilhen** [comment]
@lexcao Awesome, thank you!

@abstractj this is good to go, could you trigger the workflow, please?

**Pull request merged**
