### PR TITLE
KEYCLOAK-14767 OpenShift Review Endpoint audience fix

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.redhat.com/browse/KEYCLOAK-14767

### CODE REVIEW

**Review by stianst — CHANGES_REQUESTED** [review]
We need to check audiences against aud in the token

**Comment by slaskawi** [comment]
@stianst Updated. The current behavior is the following:
- If the audience is passed in - we validate it
- If not, we skip it

**Comment by vmuzikar** [comment]
If I understand it correctly, audience check is mandatory in newer OCP versions, right? In other words, the audience check is optional just to keep it backward compatible with older OCP versions, correct?

IMHO we should harden this a bit. Currently, all it takes to pass the aud check is to omit it in the review request. Couldn't we rather make it a switch in Admin Console that would define whether KC should check aud or not?

Also, I think we should extend the tests a bit. Make sure aud is really checked in the review requests (and not checked when it's not present).

Thank you @slaskawi.

**Comment by slaskawi** [comment]
> If I understand it correctly, audience check is mandatory in newer OCP versions, right? In other words, the audience check is optional just to keep it backward compatible with older OCP versions, correct?

@vmuzikar That is correct.

> IMHO we should harden this a bit. Currently, all it takes to pass the aud check is to omit it in the review request. Couldn't we rather make it a switch in Admin Console that would define whether KC should check aud or not?

@vmuzikar I don't like this approach as it requires the user to know exactly what K8s version is he running on and what version uses audience and what not. I would leave it as is. @stianst, @abstractj  - any thoughts on this?

> Also, I think we should extend the tests a bit. Make sure aud is really checked in the review requests (and not checked when it's not present).

@vmuzikar Granted.

**Comment by slaskawi** [comment]
@vmuzikar I've been thinking about this for a while and I came to the conclusion, that you're right - the audience checks shouldn't be option. It needs to be mandatory.

We haven't really announced OpenShift 3 integration anywhere (in the docs or blogs). Therefore, I think it's safe to implement this non-backwards compatible change and focus only on OpenShift 4.

@stianst @vmuzikar I implemented another approach with a mandatory audience check here: https://github.com/keycloak/keycloak/pull/7334

Closing this one.

**Pull request closed without merging**
