### PR TITLE
External Infinispan as cache - Part 4

### LINKED ISSUE #28755: External Infinispan as cache - Part 4 / user + client sessions online + offline
### Description

See Part 1: https://github.com/keycloak/keycloak/issues/28140

### Discussion

_No response_

### Motivation

See Part 1: https://github.com/keycloak/keycloak/issues/28140

### Details

Final part!
Creates a new provider implementation of `UserSessionProvider` and remote-only caches for the latest 4 caches.

### PR DESCRIPTION
**Pull request by pruivo**
UserSessionProvider implementation to make use of Infinispan remote cache.

Closes #28755

- [x] Cleanup code
- [x] Javadoc
- [x] Revisit disabled tests

### CODE REVIEW

**Review by ahus1 — APPROVED** [review]
With all tests passing and after a review of the code, this is IMHO good to be merged.

**Comment by ahus1** [comment]
@mhajas - this can IMHO be merged unless you want to do another review. Thanks!

**Review by mhajas — APPROVED** [review]
Thank you @pruivo, I think this can be merged.

There is just one thing I would like to point out. At this stage, we have a unique opportunity to do some schema changes or adjustments. Whatever we release in 26 the migration can be difficult. Therefore I think we should rethink some design patterns. Here are some ideas we followed back in the times of Map store but I am sure there are more that came to your mind when working on this PR.

1. The code is cluttered by the online and offline flags everywhere and I don't think it has any benefits to have 4 caches instead of 2, maybe even 1. If we have queries in the future offline flag can be stored the same way as any other field.
2. Expiration - currently we store lastSessionRefresh/timestamp, we can change this to store expiration instead. The advantage would be we can use the field in queries. On the other hand, May not be worth it since we can rely on the lifespan in Infinispan.
3. We could make things more consistent if we use HotRod transactions, then we can use XA. The problem here is that if I am not mistaken AWS JDBC wrapper does not support XA so we can't use it in multi-site at the moment.

**Comment by pruivo** [comment]
I agree this is the time to change things. I have some ideas to improve the entity stored in Infinspan. I need to open a GH discussion for these:

* Remove offline caches, I think we agreed at some point :+1: 
* Remove `AuthenticatedClientSessionStore` (trying to reduce conflicts when creating client sessions)
. Remote Infinispan only would use `publishEntriesByQuery`
. Embedded Infinispan would use groups, grouped by user session id: `getGroup()` 
. Embedded Infinispan + Persistent Session I'm not sure, to be honest :) 

About the expiration, I'm not that familiar with the KC code to comment on that. But if we can remove fields, I'm up for it :+1: 

I wouldn't recommend Hot Rod transactions. Never tested with cross-site, has a huge perf impact and it is buggy at the moment :rofl:

**Comment by pruivo** [comment]
just sharing the link: https://github.com/keycloak/keycloak/discussions/30532

**Pull request merged**
