### PR TITLE
KEYCLOAK-4163 Improve support for e-mail addresses

### PR DESCRIPTION
**Pull request by thomasdarimont**
Added support for user friendly email addresses as well as dedicated
reply-to addresses for emails being sent by Keycloak.

Both can be customized via the email settings per realm in
the admin-console.
User friendly email addresses use the format `"Friendly Name"<email@example.org>` 
and provide way to add a meaningfull name to an e-mail address.

### CODE REVIEW

**Comment by stianst** [comment]
We need some tests ;)

**Comment by stianst** [comment]
@abstractj can you review this please?

**Comment by abstractj** [comment]
@stianst of course!

**Comment by abstractj** [comment]
@thomasdarimont aside from what Stian already mentioned. I tested your PR and maybe doc updates would be nice. Some considerations about this change:

- From display name & From

I tried your branch with the following configuration:

screenshot from 2017-03-07 10-12-04

When I use 'Forgot Password' or even the the registration, I get an e-mail like this:

screenshot from 2017-03-07 10-15-17

In theory I believe, the expected e-mail would be _"Keycloak Store...<x@x.com>."_. Am I wrong?

- Envelope From

I tried to mimic e-mail bounce with Gmail and Mailinator, but I believe that the reason why this is not working is due to what [RFC5321](https://tools.ietf.org/html/rfc5321) states:

> A message-originating SMTP system SHOULD NOT send a message that
   already contains a Return-path header field.  SMTP servers performing
   a relay function MUST NOT inspect the message data, and especially
   not to the extent needed to determine if Return-path header fields
   are present.  SMTP servers making final delivery MAY remove Return-
   path header fields before adding their own.

The only place which I see some usage for this field, is for scenarios where you have control over the SMTP server. Is this kind of scenario that you had in mind?

**Comment by thomasdarimont** [comment]
Thanks for the review @abstractj!

> Envelope From
Yes the main usecase for this is to be able to detect returned emails
in environments where one has control over the mailserver.
If you use a corporate smtp (postfix / ms exchange) to sent out emails
within the internal network or to customers.

> From display name & From
Yes, indeed - when I merged my PRs i accidentally dropped the `from` address config... :-(
Just rebased and fixed this (as well as a broken translation)

After the fix one can see the correct display name for from.
(See attached images + mail headers from thunderbird at the end)

keycloak-4163 -mail-aliases-setup
keycloak-4163 -mail-aliases-ux-thunderbird


Mail Headers (thunderbird)

```
Return-Path: <sso+bounces@tdlabs.local>
Delivered-To: <tom@tdlabs.local>
Received: from mail.tdlabs.local
	by mail.tdlabs.local (Dovecot) with LMTP id fB99AGaBwFjsAwAAurbLDQ
	for <tom@tdlabs.local>; Wed, 08 Mar 2017 22:10:46 +0000
Received: from localhost (localhost [127.0.0.1])
	by mail.tdlabs.local (Postfix) with ESMTP id F3D391BA5DFA
	for <tom@tdlabs.local>; Wed,  8 Mar 2017 22:10:45 +0000 (UTC)
Received: from mail.tdlabs.local ([127.0.0.1])
	by localhost (mail.tdlabs.local [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id 67yuUuPejYLi for <tom@tdlabs.local>;
	Wed,  8 Mar 2017 22:10:45 +0000 (UTC)
Received: from euler (unknown [172.19.0.1])
	by mail.tdlabs.local (Postfix) with ESMTP id E48211BA5DF4
	for <tom@tdlabs.local>; Wed,  8 Mar 2017 22:10:45 +0000 (UTC)
Date: Wed, 8 Mar 2017 23:10:45 +0100 (GMT+01:00)
From: tdlabs SSO <sso@tdlabs.local>
Reply-To: no-reply <no-reply@tdlabs.local>
To: tom@tdlabs.local
Message-ID: <1821365399.13.1489011045891.JavaMail.tom@euler>
Subject: Update Your Account
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_12_331045891.1489011045877"
```

**Comment by abstractj** [comment]
@thomasdarimont thank you Thomas

@stianst I tested the latest changes from @thomasdarimont and looks ready to go. The only thing that I would do before merge is to squash all the commits in a single one, because they only make sense together. But this is pretty much my personal taste about git.

**Comment by thomasdarimont** [comment]
Thanks for review!

I can squash the commits later if you like.

Cheers,
Thomas

**Comment by thomasdarimont** [comment]
Just rebased and squashed the PR.

**Comment by thomasdarimont** [comment]
PR for docs update is here:
https://github.com/keycloak/keycloak-documentation/issues/42

How can I build the documentation?
Would be helpful to have the build script in the keycloak-documentation repository.

**Comment by abstractj** [comment]
@thomasdarimont there's a build script inside each folder https://github.com/keycloak/keycloak-documentation/blob/master/server_admin/build.sh. But I believe this is something we have to improve to make more clear.

**Comment by stianst** [comment]
build.sh only builds the "product" version of the documentation. You need
gitbook tools to build the community docs.

**Comment by stianst** [comment]
@thomasdarimont thanks

**Pull request merged**
