### PR TITLE
Refactor the packages structure of the operator

### LINKED ISSUE #10738: Polish the operator code
* Rename packages.
* Rename test classes.

### PR DESCRIPTION
**Pull request by andreaTP**
This is the `main` package refactoring.
Partially resolves #10738

### CODE REVIEW

**Review by pedroigor — APPROVED** [review]

**Review by abstractj — APPROVED** [review]
Great stuff. Will merge after @vmuzikar's review.

**Review by vmuzikar — COMMENTED** [review]
@andreaTP Thanks, changes LGTM.

I was wondering if we could sneak in also the test changes in order to fully cover everything in https://github.com/keycloak/keycloak/issues/10738. Created a PR for it in your fork: https://github.com/andreaTP/keycloak/pull/6. Feel free to use it, otherwise I will create a separate follow-up PR to Keycloak repository. Either way works for me.

**Comment by vmuzikar** [comment]
Actually, just realized that #10738 won't be fully resolved even with my PR for tests. We're missing the config renaming. But let's do that as a follow-up.

**Review by vmuzikar — APPROVED** [review]
Feel free to merge this. https://github.com/andreaTP/keycloak/pull/6 will require a bit more work and I'll create a separate PR to `keycloak/keycloak` for it.

**Pull request merged**
