### PR TITLE
KEYCLOAK-5779 Czech and Slovak translation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by stianst** [comment]
Doesn't look like all files have "# encoding: utf-8" and there's also still some property files that are not using utf-8 encoding.

**Comment by Joe32** [comment]
Fixed, mvn clean install with distribution profile worked, I also changed messages_en to utf-8  (https://github.com/keycloak/keycloak/pull/4921/files#diff-212b66440fb033927a3a24caf41983c9, https://github.com/keycloak/keycloak/pull/4921/files#diff-b5d1ca446863b2174e6d69b58e2b3b2f)

**Comment by hmlnarik** [comment]
Furthermore, please split the PR into two (separate one for Czech and Slovak) so that they can be reviewed accordingly. There are now two separate issues for these: https://issues.jboss.org/browse/KEYCLOAK-6304 and https://issues.jboss.org/browse/KEYCLOAK-6305, respectively.

**Review by hmlnarik — CHANGES_REQUESTED** [review]
see comment above

**Comment by Joe32** [comment]
Created new PRs: https://github.com/keycloak/keycloak/pull/4925 https://github.com/keycloak/keycloak/pull/4926

**Pull request closed without merging**
