### PR TITLE
Test WebAuthn with multiple browsers

### LINKED ISSUE #10062: Test WebAuthn with multiple browsers
At this moment, the WebAuthn is tested only on Chrome browser and it'd be good to test it even on other frequently used browsers such as Firefox, Safari, and so on.

### PR DESCRIPTION
**Pull request by mabartos**
Closes #10062 

I'll link PR to the pipeline and link to pipeline tests lately.

This PR can be merged after #10214 

@miquelsi Could you please take a look at it? Thanks

### CODE REVIEW

**Comment by mabartos** [comment]
Needed to rebase due to failures in GH actions.

**Review by miquelsi — DISMISSED** [review]
LGTM, thanks Martin!

**Comment by mabartos** [comment]
@miquelsi Rebased again due to cancellation of the Keycloak Operator CI action.

**Review by miquelsi — DISMISSED** [review]

**Comment by mabartos** [comment]
@miquelsi Sorry Miquel, but you'll have to approve it again... But this time, it should be the last change, I swear! xD As the #10406 is already merged, the Operator build stage might be successful now.

**Review by miquelsi — APPROVED** [review]

**Review by pdrozd — APPROVED** [review]

**Pull request merged**
