### PR TITLE
[KEYCLOAK-10634] - Permission not removing reference to resource when setting the resource type

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by abstractj — COMMENTED** [review]
@pedroigor would make sense to add tests to https://github.com/keycloak/keycloak/blob/a2b13715ed21d692967f2aa717602a4cef50ecb7/testsuite/integration-arquillian/tests/other/console/src/test/java/org/keycloak/testsuite/console/authorization/DefaultAuthorizationSettingsTest.java to make sure that the issue does not happen again?

**Comment by mhajas** [comment]
@pedroigor I tried this manually and your fix works. However, as Bruno pointed out we should add also some tests.

**Comment by pedroigor** [comment]
@abstractj @mhajas Test added.

**Review by mhajas — APPROVED** [review]

**Comment by abstractj** [comment]
@mhajas @pedroigor I'm running:

```
mvn -Dtest=ResourcePermissionManagementTest -f testsuite/integration-arquillian/tests/other/console/pom.xml clean test -Pconsole-ui-tests -Dbrowser=firefox
```

But I'm getting a test failure:

```
Results :

Failed tests:
  ResourcePermissionManagementTest.testUpdateResourceType:196
```

Are all the tests passing for you guys?

**Comment by mhajas** [comment]
@abstractj  I run `mvn clean install -Dtest=ResourcePermissionManagementTest -Dbrowser=chrome` and it passed for me

**Comment by mhajas** [comment]
@abstractj I was accidentally testing the old commit without the test, now testing correct commit.

**Review by abstractj — APPROVED** [review]
It turns out that was my fault. I did a full clean up and all the tests are passing now.

**Comment by mhajas** [comment]
@abstractj @pedroigor The test is working for me on both chrome and firefox. I think this is ready to merge.

**Pull request merged**
