### PR TITLE
KEYCLOAK-1910 Fixes ftl rendering

### PR DESCRIPTION
**Pull request by srose**
At least it fixes the rendering. I am confused about two different origins for bean initialization.

### CODE REVIEW

**Comment by stianst** [comment]
This looks like a work around rather than the proper solution

**Comment by stianst** [comment]
Just checked the code and this is not the correct fix. Basically this just enforces the password field on registration form, but this should be made pluggable.

Not actually 100% sure what the correct fix is

**Comment by srose** [comment]
Sorry, this was just meant as a workaround and to get KEYCLOAK-1904 working for my setup.

I'd like to get to the correct solution, but right now i don't see it.

The other origin of page initalization is the configurable action/flow thing. Can you provide help on this?

**Comment by stianst** [comment]
I'm not 100% sure, but I'll take a look and commit a fix

**Pull request closed without merging**
