### PR TITLE
KEYCLOAK-4072

### PR DESCRIPTION
**Pull request by patriot1burke**

### CODE REVIEW

**Comment by hmlnarik** [comment]
Bill, could you please postpone merging this issue till Monday? There is an issue with keys that has impact on performance and I'd like to discuss this beforehand. I'll be sending an e-mail in few hours to kc-dev.

**Comment by patriot1burke** [comment]
I I did not see any foreign key set up for the OFFLINE_USER_SESSION.USER_ID.  The OFFLINE_USER_SESSION.USER_ID needs to be pointable to a non-keycloak-stored user.  In other words, it may point to a User Storage Provider.  So, there can't be any DB referential integrity validation.

**Comment by patriot1burke** [comment]
The OFFLINE_USER_SESSION.USER_ID can't be validated because it points to an externally stored user.

**Comment by hmlnarik** [comment]
That's correct, sorry for reading USER_ID as FK to USER_ENTITY table. Still it contains a component ID which is a keycloak UUID according to [documentation](https://github.com/keycloak/server_development_guide/blob/6b82f0868c0d7a148a084a30e0d8fda192f01502/topics/user-storage/model-interfaces.adoc) - hence I think it should be split into two fields (component_id, custom_key) where component_id is constrained by a foreign key. I've just managed to send an e-mail to keycloak-dev with explanation on what performance implications this type of key has.

**Comment by patriot1burke** [comment]
I don't see a reason I can't commit this right now because your proposed solution pretty much requires a big change to our datamodel and the User Storage SPI.

**Comment by stianst** [comment]
IMO this can be merged as is - improvements (if any, but I can't see what we can do) can be done later (in 3.x)

**Comment by hmlnarik** [comment]
I agree yet I think it would be safer for future data model adjustments to explicitly warn if the key format is incorrect. I've added a PR #3666 to check this.

**Comment by stianst** [comment]
Merged manually to resolve conflicts:
https://github.com/keycloak/keycloak/commit/8b5aafc4b4faed1779e2e5a68dd60a62fbbf190e

**Pull request closed without merging**
