### PR TITLE
Fix Operator tests on OpenShift

### LINKED ISSUE #22140: KeycloakIngressTest failing in OCP
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

The tests below in KeycloakIngressTest are failing when running them in an OCP cluster.

### Version

latest

### Expected behavior

The test passes successfully

### Actual behavior

```
2023-07-31 16:42:11  [ERROR]   KeycloakIngressTest.testIngressOnHTTP:85 » ConditionTimeout Assertion condition defined as a org.keycloak.operator.testsuite.utils.K8sUtils 
2023-07-31 16:42:11  expected: true
2023-07-31 16:42:11   but was: false within 5 minutes.
2023-07-31 16:42:11  [ERROR]   KeycloakIngressTest.testIngressOnHTTPS:108->testIngressURLs:114 » ConditionTimeout Assertion condition defined as a org.keycloak.operator.testsuite.integration.KeycloakIngressTest null within 6 minutes.
```

### How to Reproduce?

`mvn install -Poperator -pl :keycloak-operator -am -Dquarkus.kubernetes.image-pull-policy=Always -Doperator.keycloak.image=quay.io/keycloak/keycloak:nightly -Dquarkus.container-image.image=quay.io/keycloak/keycloak-operator:nightly -Dquarkus.jib.jvm-arguments=-Djava.util.logging.manager=org.jboss.logmanager.LogManager -Doperator.keycloak.image-pull-policy=Always -Dtest.operator.deployment=remote`

### Anything else?

Full execution log: https://keycloak-jenkins/view/OpenShift/job/rhbk-operator-test-pipeline/27/execution/node/40/log/?consoleFull

### LINKED ISSUE #22142: PodTemplateTest.testPodTemplateIncorrectNamespace error in OCP
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

This test is throwing an error when running in an OCP cluster.

### Version

latest

### Expected behavior

The test passes successfully

### Actual behavior

```
2023-07-31 16:42:11  [ERROR]   PodTemplateTest.testPodTemplateIncorrectNamespace:130 » ConditionTimeout Assertion condition defined as a org.keycloak.operator.testsuite.integration.PodTemplateTest 
2023-07-31 16:42:11  expected: false
2023-07-31 16:42:11   but was: true within 3 minutes.
```

### How to Reproduce?

`mvn install -Poperator -pl :keycloak-operator -am -Dquarkus.kubernetes.image-pull-policy=Always -Doperator.keycloak.image=quay.io/keycloak/keycloak:nightly -Dquarkus.container-image.image=quay.io/keycloak/keycloak-operator:nightly -Dquarkus.jib.jvm-arguments=-Djava.util.logging.manager=org.jboss.logmanager.LogManager -Doperator.keycloak.image-pull-policy=Always -Dtest.operator.deployment=remote`

### Anything else?

Full execution log: https://keycloak-jenkins/view/OpenShift/job/rhbk-operator-test-pipeline/27/execution/node/40/log/?consoleFull

### LINKED ISSUE #22143: WatchedSecretsTest.testSecretChangesArePropagated error in OCP
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

This test is throwing an error when running in an OCP cluster.

### Version

latest

### Expected behavior

The test passes successfully

### Actual behavior

`2023-07-31 16:42:11  [ERROR]   WatchedSecretsTest.testSecretChangesArePropagated:113 » ConditionTimeout Condition with org.keycloak.operator.testsuite.integration.WatchedSecretsTest was not fulfilled within 1 minutes.`

### How to Reproduce?

`mvn install -Poperator -pl :keycloak-operator -am -Dquarkus.kubernetes.image-pull-policy=Always -Doperator.keycloak.image=quay.io/keycloak/keycloak:nightly -Dquarkus.container-image.image=quay.io/keycloak/keycloak-operator:nightly -Dquarkus.jib.jvm-arguments=-Djava.util.logging.manager=org.jboss.logmanager.LogManager -Doperator.keycloak.image-pull-policy=Always -Dtest.operator.deployment=remote`

### Anything else?

Full execution log: https://keycloak-jenkins/view/OpenShift/job/rhbk-operator-test-pipeline/27/execution/node/40/log/?consoleFull

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes https://github.com/keycloak/keycloak/issues/22140
Closes https://github.com/keycloak/keycloak/issues/22142
Closes https://github.com/keycloak/keycloak/issues/22143

### CODE REVIEW

**Comment by vmuzikar** [comment]
Successful QE pipeline run: https://keycloak-pipeline.com/view/OpenShift/job/rhbk-operator-test-pipeline/30/console

**Review by miquelsi — APPROVED** [review]
Thanks @vmuzikar!

**Review by shawkins — APPROVED** [review]
LGTM

**Comment by vmuzikar** [comment]
Test failures are unrelated, Operator CI passed.

**Review by ahus1 — APPROVED** [review]

**Pull request merged**
