### PR TITLE
Enable HTTP metrics for Keycloak by default

### LINKED ISSUE #27924: Enable http metrics once Quarkus 3.8.3 is available
### Description

With fixed http metrics support for sub-resources available in Quarkus 3.8.3, this can now be re-enabled

See 
* https://github.com/quarkusio/quarkus/issues/31497
* https://github.com/keycloak/keycloak/issues/27925
* https://github.com/keycloak/keycloak/issues/17281

### Motivation

This offers better monitoring of the Keycloak instance

### PR DESCRIPTION
**Pull request by ahus1**
Closes #27924

### CODE REVIEW

**Comment by ahus1** [comment]
@sschu - they will show the patterns as defined in the REST resource. See below for an example, so no explosion expected.

Note that redirects and not founds will be grouped without the URI until https://github.com/quarkusio/quarkus/pull/39583 is resolved.

```
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/resources/{version}/{themeType}/{themeName}/{path:.*}"} 84.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/resources/{version}/{themeType}/{themeName}/{path:.*}"} 0.748752785
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/admin/realms/{realm}/default-default-client-scopes"} 2.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/admin/realms/{realm}/default-default-client-scopes"} 0.014428475
http_server_requests_seconds_count{method="POST",outcome="SUCCESS",status="200",uri="/realms/{realm}/protocol/{protocol}/token"} 1.0
http_server_requests_seconds_sum{method="POST",outcome="SUCCESS",status="200",uri="/realms/{realm}/protocol/{protocol}/token"} 0.100825205
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/realms/{realm}/protocol/{protocol}/3p-cookies/step2.html"} 3.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/realms/{realm}/protocol/{protocol}/3p-cookies/step2.html"} 0.006380506
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/admin/{realm}/console/whoami"} 1.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/admin/{realm}/console/whoami"} 0.016965703
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/admin/realms/{realm}/{extension}/realms/names"} 1.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/admin/realms/{realm}/{extension}/realms/names"} 0.019349262
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/admin/realms/{realm}/roles"} 1.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/admin/realms/{realm}/roles"} 0.014090926
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/realms/{realm}/protocol/{protocol}/auth"} 1.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/realms/{realm}/protocol/{protocol}/auth"} 0.014670861
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/admin/{realm}/console"} 3.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/admin/{realm}/console"} 0.013646932
```

**Comment by sschu** [comment]
I could imagine having these metrics by realm might be interesting in some cases. But maybe this can be added later. For a start it is better to have a safe default.

**Review by mabartos — APPROVED** [review]
@ahus1 Thanks! LGTM.

Everything works as expected, and we should be fine around the NOT_FOUND records as they could be the most suitable tool to log pollution type of attack. Even after merging your PR to Quarkus.

**Review by vmuzikar — APPROVED** [review]
@ahus1 Thank you for the PR!

Approving based on @mabartos' review.

**Pull request merged**
