### PR TITLE
KEYCLOAK-10852 Inconsistency when using 'forgot password' after chang…

### PR DESCRIPTION
**Pull request by mposolda**
…ing email directly in LDAP

### CODE REVIEW

**Comment by iankko** [comment]
@mposolda Thank you for the change, Marek! But could you hopefully add two more tests in the following form:? (please see below for the motivation why)

1. Test:
- First reset user's email address directly via LDAP,
- Then quickly request to send three emails by three times clicking the `Forgot password` link. The three cases would be: a) using user's username b) using old user's email c) using new user's email
- And verify there are three new email messages received at the new user's email address

2. Test (analogous to the first one, but changing the order of the b) and c) steps):
- First reset user's email address directly via LDAP,
- Then quickly request to send three emails by three times clicking the `Forgot password` link. The three cases would be: a) using user's username b) using *new* user's email c) using *old* user's email
- And verify there are three new email messages received at the new user's email address

I might be wrong, but still seeing some inconsistency between these two cases (there are three emails received at the new email address in the case the new / updated email address was provided as the last one in the `Forgot Password` link. But only two emails received, when first the user's username, and then the new email address of the user is provided within the `Forgot password` form).

I would rather be proven wrong (that the behavior above is OK), than to have the issue unfixed.

IIRC in 8.0.1's case the behaviour was even after resetting the email in LDAP, clicking `Forgot password` with username, then clicking `Forgot password` with new email, the email was still delivered to the old address.

Thanks, Jan

**Review by iankko — CHANGES_REQUESTED** [review]
Would be great to have two more tests yet (still seeing an inconsistency in the behaviour, see previous comment)

**Comment by mposolda** [comment]
@iankko I guess you meant that when you go through the scenarios you mentioned, then there are 3 emails received. However there should be only two emails received (In other words, the email should not be sent at all when old email was used). Is it what you meant?

**Comment by mposolda** [comment]
@iankko Updated PR per your suggestion and added the tests you mentioned.

**Comment by iankko** [comment]
@mposolda 
> @iankko Updated PR per your suggestion and added the tests you mentioned.

Thanks, Marek! Retested the latest version and it LGTM (the behaviour is now consistent, and emails are sent to the updated email address)

**Review by iankko — APPROVED** [review]

**Comment by iankko** [comment]
@mposolda One small nitpick for this one yet though - there's a success message printed out each time. Regardless if the email was: 1) properly sent (to the new email address) 2) not sent (if the old email address was specified in `Forgot password` form).

Should we change the behaviour to error instead if the old email address was used in the `Forgot password`? (since right now success message might indicate the user will receive email that never arrives) WDYT?

**Comment by mposolda** [comment]
@iankko Regarding this, it is the requested behaviour. Keycloak always displayed "success" message even if you use unexistent email address like "nonexistent@something.com" . This is to prevent enumeration of email addresses.

**Comment by iankko** [comment]
@mposolda 
> @iankko Regarding this, it is the requested behaviour. Keycloak always displayed "success" message even if you use unexistent email address like "[nonexistent@something.com](mailto:nonexistent@something.com)" . This is to prevent enumeration of email addresses.

Ah, right, good catch, thanks for clarification (definitely makes sense, forgot about it).

**Review by pdrozd — APPROVED** [review]

**Review by stianst — APPROVED** [review]

**Pull request merged**
