### PR TITLE
KEYCLOAK-10316 Given a user with a password, updating it with a password hashed credential representation leads to the presence of 2 passwords

### PR DESCRIPTION
**Pull request by reda-alaoui**

### CODE REVIEW

**Comment by reda-alaoui** [comment]
Hello?

**Comment by stianst** [comment]
I'm pretty sure using disableCredentialType is not the right solution here, but I haven't had time to look into this properly.

@mposolda can you take a look or assign someone from your team to look at this?

**Comment by reda-alaoui** [comment]
Hello?

**Comment by reda-alaoui** [comment]
Hello?

**Comment by reda-alaoui** [comment]
Ping :)

**Comment by mposolda** [comment]
@reda-alaoui Sorry for late response. But IMO this is not a bug and shouldn't be fixed like that. I think we should just document that userResource.update REST endpoint is not meant for updating password, but for updating user profile data (attributes etc).

There is separate REST endpoint for updating user passwords. This endpoint is used by admin console when you update password of some user. And you can see that it is different endpoint than  userResource.update. I suggest to take a look at admin console, figure what endpoint is called and use that endpoint for updating passwords.

We plan to refactor admin REST API in the near future and provide proper guidelines for REST development. That should hopefully help to avoid similar issues.

IMO if we really want to fix/improve the current endpoint, we may just add javadoc/documentation to the REST endpoint userResource.update and highlight that this endpoint is not meant for updating user credentials (and other user data like role/group memberships etc), but just for updating the basic properties of user, attributes of user, requiredActions etc. Feel free to open other PR for document that.

**Pull request closed without merging**
