### PR TITLE
[KEYCLOAK-17602] Email account verification link is wrongly encoded

### PR DESCRIPTION
**Pull request by douglaspalmer**
There doesn't seem to be a way to prevent the sanitizer from sanitizing the URLs. So this PR fixes the URLs after sanitizing.

### CODE REVIEW

**Comment by douglaspalmer** [comment]
@mposolda @stianst @mhajas Do any of you have time to review this?

**Review by ssilvert — APPROVED** [review]
LGTM

**Comment by conet** [comment]
We upgraded to 14.0.0 with a template that contains 2 `hrefs` with the same URL (inline link and button) and the templating started to fail:
```
Caused by: java.lang.IndexOutOfBoundsException: No group 2
	at java.base/java.util.regex.Matcher.group(Matcher.java:647)
	at org.keycloak.keycloak-services@14.0.0//org.keycloak.theme.KeycloakSanitizerMethod.fixURLs(KeycloakSanitizerMethod.java:56)
	at org.keycloak.keycloak-services@14.0.0//org.keycloak.theme.KeycloakSanitizerMethod.exec(KeycloakSanitizerMethod.java:47)
	at org.freemarker@2.3.31//freemarker.core.MethodCall._eval(MethodCall.java:62)
	at org.freemarker@2.3.31//freemarker.core.Expression.eval(Expression.java:101)
	at org.freemarker@2.3.31//freemarker.core.BuiltInsForOutputFormatRelated$AbstractConverterBI.calculateResult(BuiltInsForOutputFormatRelated.java:50)
	at org.freemarker@2.3.31//freemarker.core.MarkupOutputFormatBoundBuiltIn._eval(MarkupOutputFormatBoundBuiltIn.java:40)
	at org.freemarker@2.3.31//freemarker.core.Expression.eval(Expression.java:101)
	at org.freemarker@2.3.31//freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
	at org.freemarker@2.3.31//freemarker.core.DollarVariable.accept(DollarVariable.java:63)
	at org.freemarker@2.3.31//freemarker.core.Environment.visit(Environment.java:347)
	at org.freemarker@2.3.31//freemarker.core.Environment.visit(Environment.java:353)
	at org.freemarker@2.3.31//freemarker.core.Environment.process(Environment.java:326)
	at org.freemarker@2.3.31//freemarker.template.Template.process(Template.java:383)
	at org.keycloak.keycloak-services@14.0.0//org.keycloak.theme.FreeMarkerUtil.processTemplate(FreeMarkerUtil.java:68)
```
probably because `.replace` replaces all occurrences thus the second group extraction fails.

**Comment by conet** [comment]
If this MR is not the proper place for such requests please point me to the proper place but I'm certain that this changed introduced the bug that we are seeing.

**Pull request merged**
