### PR TITLE
Upgrade to Infinispan 15.0.7.Final

### LINKED ISSUE #31963: Upgrade to Infinispan 15.0.7.Final
### Description

Infinispan 15.0.7.Final fixes a number of bugs affecting Keycloak users.

### PR DESCRIPTION
**Pull request by ryanemerson**
Closes #31963

### CODE REVIEW

**Comment by pruivo** [comment]
@ryanemerson search and update `quay.io/infinispan/server:15.0.5.Final` (if the image is available)

**Review by ahus1 — APPROVED** [review]
Thank you for this PR!

**Comment by ahus1** [comment]
@ryanemerson - please also backport for KC25 so those issues are fixed there as well, and we get feedback for this patch release from the community.

**Comment by ryanemerson** [comment]
https://github.com/keycloak/keycloak/pull/31973

**Pull request merged**
