### PR TITLE
[KEYCLOAK-8444] - Error when producing KeycloakSpringBootConfigResolver from spring security configuration

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by sebastienblanc — APPROVED** [review]
Awesone @pedroigor  !

**Comment by durimkryeziu** [comment]
I'm sorry for asking here, maybe it's not the correct place to ask, but when will you release these changes?

**Comment by pedroigor** [comment]
@durimkryeziu, 2 weeks from now.

**Comment by BladeWise** [comment]
Is this PR part of the 7.0.0 release? I am experiencing the exact same issue using
Spring Boot 2.1.6.RELEASE
and
keycloak-spring-boot-starter 7.0.0

**Comment by wspurgin** [comment]
@BladeWise yes its an issue with 7.0.0 caused by #6075 and #6097 
https://issues.jboss.org/browse/KEYCLOAK-11282

**Pull request merged**
