### PR TITLE
KEYCLOAK-12834 Fix Account Console build is missing some dependencies

### PR DESCRIPTION
**Pull request by vmuzikar**

### CODE REVIEW

**Review by ssilvert — APPROVED** [review]
This PR looks good.

Of course, it underscores the weakness of how we are building this thing.  Every time we add something to the new account console, we have to change this pom.

**Review by abstractj — APPROVED** [review]

**Comment by vmuzikar** [comment]
@ssilvert Yes, I'd like to investigate it after the tech preview – we need something more robust / automated.

**Comment by ssilvert** [comment]
@vmuzikar @abstractj  I'm going to be looking into a new tool called "snowpack".  The idea is that you can replace each large javascript library with a single file that includes only what you need.  It looks like this will solve our problems with building and our performance problems.  It kind of does what webpack does but it does it piecemeal.  This is the compromise I've been looking for.  Just hoping it works.

**Comment by vmuzikar** [comment]
@ssilvert @abstractj Created a generic JIRA for this: https://issues.redhat.com/browse/KEYCLOAK-12847

**Pull request merged**
