### PR TITLE
KEYCLOAK-7844: Space in the realm name causes infinite browser redirects

### PR DESCRIPTION
**Pull request by gkgeorgiev**
URL decoding the Realm name, which is derived from the ticket issuer.
This is required for a realm name, which has non URL compliant symbols,
such as white spaces.

### CODE REVIEW

**Comment by abstractj** [comment]
@gkgeorgiev thanks for taking your time and submitting this patch. I would really appreciate if you add integration tests for this, in this way we make sure that won't happen again.

Thanks in advance.

**Comment by gkgeorgiev** [comment]
@abstractj I apologize, but right now I'm short of time and I just modified an existing unit test which covers this scenario. Integration test will take much longer to me.

**Comment by gkgeorgiev** [comment]
@abstractj Could you restart the build, it seems to be failing because of some infra problem?

**Comment by stianst** [comment]
Thanks for the PR, but I'm going to close this PR for a couple reasons:

* You shouldn't really have a space in the realm name as it generates messy URLs. Rather give it a short and url friendly name and use the display name
* Realm name is used many places in the URLs and I very much doubt this case is the only place that has an issue
* You've stated that you don't have time to do a proper PR with the needed level of testing

**Comment by gkgeorgiev** [comment]
"shouldn't really have a space"  is kind of a lame excuse since you have a free text field,  which allows it.  
With the rest i have nothing to add,  if you define it as improper PR,  so shall it be done. 
 Thx for the feedback 
Thx

**Comment by stianst** [comment]
It shouldn't have. We will add validation to prevent it at some point, but we need to setup a proper validation framework first as we don't want to simply hardcode a lot of messy validation code.

If you want to go to the trouble of properly testing if everything works properly with a space in there I don't have any issue with accepting a PR that allows space in the realm name though. I think just preventing it in the first place with validation is a better and much simpler approach.

**Comment by gkgeorgiev** [comment]
@joranb , I know ... I also had the same experience and I had to debug Keycloak to figure it out.

**Pull request closed without merging**
