### PR TITLE
Fix default helpText as per new defaults for password hashing algorithm

### LINKED ISSUE #28697: Password policy hashing iterations incorrect helpText
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

As per new changes introduced in password hashing algorithm which also changed default number of iterations as per OWASP recommendations, the changes are not reflected in admin UI password policy tab helpText.

image

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Defaults should reflect the new iterations.

### Actual behavior

Still showing the older default iterations.

### How to Reproduce?

1. Login to admin UI console
2. Browse to `authentication` tab
3. Click on `Policies` and switch to `password policies`
4. Select `Hashing iterations` from policy dropdown
5. Click on tooltip for help

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by souravs17031999**
closes https://github.com/keycloak/keycloak/issues/28697

image

### CODE REVIEW

**Review by edewit — APPROVED** [review]

**Comment by souravs17031999** [comment]
thanks @edewit for the review, I was thinking of one more idea if we can provide dropdowns for available algorithms and then dynamically update the text accordingly , what do you think ?

**Comment by ssilvert** [comment]
> thanks @edewit for the review, I was thinking of one more idea if we can provide dropdowns for available algorithms and then dynamically update the text accordingly , what do you think ?

@souravs17031999 I don't know if we can determine all the available algorithms?  Can we do it?

**Comment by souravs17031999** [comment]
> > thanks @edewit for the review, I was thinking of one more idea if we can provide dropdowns for available algorithms and then dynamically update the text accordingly , what do you think ?
> 
> @souravs17031999 I don't know if we can determine all the available algorithms? Can we do it?

I will try this out today

**Comment by souravs17031999** [comment]
@ssilvert we are getting some of the data (provider ID's) but not all of the data, so it will require some more changes not directly related to this PR.
I will first merge this one and open another PR containing changes for dropdowns.

**Comment by souravs17031999** [comment]
@edewit how do I merge the PR, it keeps saying branch is out of date and once I rebase it, then it says `6 workflows awaiting approval`, please help ?

**Comment by ssilvert** [comment]
> @edewit how do I merge the PR, it keeps saying branch is out of date and once I rebase it, then it says `6 workflows awaiting approval`, please help ?

@souravs17031999 Someone from the Keycloak team has to approve the CI run.  I just kicked it off.  Assuming the tests pass, we can merge.

**Comment by souravs17031999** [comment]
@ssilvert thanks, I can see tests passed. Still I don't see the option to merge, maybe you can merge :)

**Pull request merged**
