### PR TITLE
Update Cors.java

### PR DESCRIPTION
**Pull request by jasonlkx**
Start error when the log level is configured as debug.

### CODE REVIEW

**Comment by thomasdarimont** [comment]
Wouldn't it make sense to use something like "<not configured>" instead of an empty string in the debug message?

**Comment by stianst** [comment]
+1 would be better to explicitly show allowedOrigins is null/empty

By the  way what happens now? Doesn't it output "null"? Or does it throw an exception?

**Comment by stianst** [comment]
Can you create a jira and include steps to reproduce?

**Comment by stianst** [comment]
Closing due to lack of Jira and details how to reproduce.so we can't verify if this should be accepted or not.

**Pull request closed without merging**
