### PR TITLE
Avoid deprecated API usage in testsuite/integration-arquillian/tests/base

### LINKED ISSUE #24995: Avoid deprecated API usage in testsuite/integration-arquillian/tests/base
### Description

-    Removed unused imports
-    Avoided deprecated junit/hamcrest API
-    Avoid usage of JDK API scheduled for removal

This should reduce the number of compiler warnings in the logs quite a bit.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by thomasdarimont**
- Removed unused imports
- Avoided deprecated junit/hamcrest API
- Avoid usage of JDK API scheduled for removal

This should reduce the number of compiler warnings in the logs quite a bit.

closes #24995

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Comment by mposolda** [comment]
@thomasdarimont This would be great! Marking PR as "ready for review". Is it ok to you?

There is just failing test (`LDAPProvidersIntegrationTest`). I hope this one would be easier to fix than the tricky test failures you had in your recent PRs ;-)

**Comment by thomasdarimont** [comment]
Thanks for having a look, this was indeed an oversight. Should be fixed now.

**Comment by mposolda** [comment]
@thomasdarimont Thanks! It's a shame this PR missed the Keycloak 23 release, but still, it is always great to improve things this way!

**Review by mposolda — APPROVED** [review]

**Pull request merged**
