### PR TITLE
Udate webauthn4j license files

### PR DESCRIPTION
**Pull request by pskopek**
This is follow up pull request to: https://github.com/keycloak/keycloak/pull/6853 
Should be merged after it.

JIRA: https://issues.redhat.com/browse/KEYCLOAK-12696

### CODE REVIEW

**Review by mposolda — DISMISSED** [review]

**Comment by pskopek** [comment]
I have just rebased the PR.

**Review by mposolda — DISMISSED** [review]
@pskopek Thanks

**Review by martin-kanis — CHANGES_REQUESTED** [review]
Thanks Peter. Can you use productized version in distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/licenses.xml or it's not built yet?

**Comment by pskopek** [comment]
Thanks @martin-kanis for spotting this. Fixed, take a look, please.

**Comment by martin-kanis** [comment]
@pskopek Looks good. Thanks!

**Review by martin-kanis — APPROVED** [review]

**Comment by mposolda** [comment]
@pskopek @martin-kanis Thanks for the review and fixing!

**Review by mposolda — APPROVED** [review]

**Pull request merged**
