### PR TITLE
KEYCLOAK-2533: Test values of events in LoginEventsTest

### PR DESCRIPTION
**Pull request by ssilvert**
This PR also includes some new tests for admin client that test endpoints for managing Keycloak clients.  I figured that it didn't hurt to go ahead and get those merged even though there will be more tests to come.

### CODE REVIEW

**Comment by stianst** [comment]
This is just testing if the values are non-null. We should really test that the values are actually correct.

**Comment by ssilvert** [comment]
I am indeed testing the values where I know for sure what those values will be.  For instance, I don't know what id will be generated so I just assertNotNull for resource path.

For a few, it's a toss-up.  I could probably figure out what IP address will be returned, but it seems that would make the test rather brittle because that is something that could change with underlying changes in the test suite.  So again, I chose to play it safe and just assertNotNull.

**Comment by stianst** [comment]
IP address you can now, user id you can find out, client id you know. So what is it exactly that can't be checked?

As it stands the values could be en empty string, swapped around, etc.. and the tests wouldn't catch it. I don't really see how that's sufficient testing.

**Comment by ssilvert** [comment]
Sure, I can spend more time and write more code to try to figure some of these things out.  But I was told to get through this quickly.   If you saw what a mess we have with the ClientResource API's I'm working on now, you would not want me to spend more time on events.

**Comment by ssilvert** [comment]
BTW, I certainly don't claim that this is in any way "sufficient".  I'm also not doing bounds tests, invalid value tests, etc.  I'm just trying to meet the broad goal that we have some semblance of API coverage in the near future.

**Comment by stianst** [comment]
What mess with ClientResource? Can you write me a mail about that?

I don't see any point in arguing this any further so just going to merge it. However, there's little point in adding tests just to add some coverage unless you actually test something.

**Pull request merged**
