### PR TITLE
KEYCLOAK-2009 Remove unnecessary dependencies and scopes

### PR DESCRIPTION
**Pull request by k-tamura**
Please refer to [KEYCLOAK-2009](https://issues.jboss.org/browse/KEYCLOAK-2009).

The following line in `pom.xml` of Keycloak admin client should be removed because dependent libraries are not provided if the line exists:

```xml
<scope>provided</scope>
```

Keycloak admin client should work without container such as WildFly and needs to get dependent libraries.

If my PR is merged, applications which use Keycloak admin client can work with only `keycloak-admin-client` dependency:

```xml
<dependency>
    <groupId>org.keycloak</groupId>
    <artifactId>keycloak-admin-client</artifactId>
    <version>${keycloak.admin.version}</version>
</dependency>
```

In addition, four dependencies can be safely removed because the dependencies are included in the three remaining dependencies.

mvn dependency tree after my changes are applied:
```
D:\build\keycloak\integration\admin-client> mvn dependency:tree
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Keycloak Admin REST Client 7.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ keycloak-admin-client ---
[INFO] org.keycloak:keycloak-admin-client:jar:7.0.0-SNAPSHOT
[INFO] +- org.keycloak:keycloak-core:jar:7.0.0-SNAPSHOT:compile
[INFO] |  +- org.keycloak:keycloak-common:jar:7.0.0-SNAPSHOT:compile
[INFO] |  +- org.bouncycastle:bcprov-jdk15on:jar:1.60:compile
[INFO] |  +- org.bouncycastle:bcpkix-jdk15on:jar:1.60:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.8:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.8:compile
[INFO] +- org.jboss.resteasy:resteasy-multipart-provider:jar:3.6.3.Final:compile
[INFO] |  +- org.jboss.resteasy:resteasy-jaxrs:jar:3.6.3.Final:compile
[INFO] |  |  +- org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:1.0.2.Final:compile
[INFO] |  |  +- org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:1.0.1.Final:compile
[INFO] |  |  +- org.reactivestreams:reactive-streams:jar:1.0.2:compile
[INFO] |  |  +- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] |  |  +- org.jboss.spec.javax.annotation:jboss-annotations-api_1.3_spec:jar:1.0.1.Final:compile
[INFO] |  |  +- javax.activation:activation:jar:1.1.1:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.4:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.5:compile
[INFO] |  |  |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  |  +- commons-io:commons-io:jar:2.5:compile
[INFO] |  |  \- net.jcip:jcip-annotations:jar:1.0:compile
[INFO] |  +- org.jboss.resteasy:resteasy-client:jar:3.6.3.Final:compile
[INFO] |  +- org.jboss.resteasy:resteasy-jaxb-provider:jar:3.6.3.Final:compile
[INFO] |  |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.1:compile
[INFO] |  |     +- org.glassfish.jaxb:txw2:jar:2.3.1:compile
[INFO] |  |     +- com.sun.istack:istack-commons-runtime:jar:3.0.7:compile
[INFO] |  |     +- org.jvnet.staxex:stax-ex:jar:1.8:compile
[INFO] |  |     +- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.15:compile
[INFO] |  |     \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] |  +- com.sun.mail:javax.mail:jar:1.6.2:compile
[INFO] |  +- org.apache.james:apache-mime4j:jar:0.6:compile
[INFO] |  \- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
[INFO] \- org.jboss.resteasy:resteasy-jackson2-provider:jar:3.6.3.Final:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.8:compile
[INFO]    +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.9.8:compile
[INFO]    |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.9.8:compile
[INFO]    |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.8:compile
[INFO]    \- com.github.fge:json-patch:jar:1.9:compile
[INFO]       \- com.github.fge:jackson-coreutils:jar:1.6:compile
[INFO]          +- com.github.fge:msg-simple:jar:1.1:compile
[INFO]          |  \- com.github.fge:btf:jar:1.2:compile
[INFO]          \- com.google.guava:guava:jar:25.0-jre:compile
[INFO]             +- org.checkerframework:checker-compat-qual:jar:2.0.0:compile
[INFO]             +- com.google.errorprone:error_prone_annotations:jar:2.1.3:compile
[INFO]             +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO]             \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.404 s
[INFO] Finished at: 2019-08-08T16:44:14+09:00
[INFO] Final Memory: 27M/434M
[INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by abstractj** [comment]
@k-tamura could you please rebase against the latest changes from master? Travis seems to be stable again.

**Comment by k-tamura** [comment]
> 
> 
> @k-tamura could you please rebase against the latest changes from master? Travis seems to be stable again.

Okay. I have done.

**Review by abstractj — APPROVED** [review]
@martin-kanis @mposolda the changes here look reasonable to me. I tested it locally and seems like nothing was broken. What do you think?

**Review by martin-kanis — APPROVED** [review]
LGTM. Tested locally with a simple standalone app. The app can be compiled/started only with org.keycloak:keycloak-admin-client dependency.

**Review by hmlnarik — APPROVED** [review]
Looks sane to me, thank you, @k-tamura !

**Comment by k-tamura** [comment]
@abstractj @martin-kanis @hmlnarik 

Thank you for your reviewing. Should I rebase again?

**Pull request merged**
