### PR TITLE
KEYCLOAK-8493: Added danish translation from abandoned PR-5567

### PR DESCRIPTION
**Pull request by pmorch**
This is based on:

	Author: Thomas Sørensen <tvs@flexdanmark.dk>
	Date:   Thu Sep 13 14:24:43 2018 +0200

	Added danish translation. by FuKe · Pull Request #5567
	https://github.com/keycloak/keycloak/pull/5567

However, I:

* Fixed up a couple of theme.properties merge conflicts compared to
  current master
* Fixed some spelling mistakes and added missing entries
* Introduced Danish to list of locales in messages_en.properties
* Squashed it all into a single commit as pr.
  https://github.com/keycloak/keycloak/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by ssilvert — DISMISSED** [review]

**Comment by ssilvert** [comment]
Hi @pmorch.  Please fix conflicts and then I can merge.  Thanks.

**Comment by pmorch** [comment]
Great, thanks! I've used the github tools to fix the merge conflicts. (Hungarian has been introduced as a new translation on master since I created the PR), and they've created a second commit in this PR.

But this project prefers a single, squashed commit, right? Should I create a single squashed commit and create a new PR? The only way I know how to do that would be:

```
cd my_keycloak
git checkout danish_translation_single_commit
git pull master
git rebase -i master
git push --force
```

Is that the way to do it? Or should I simple create another PR referencing this one, while we close this one (messy)? Let me know what you'd like me to do and I'll do that. I'm currently painting the house and may not get back to this on the same day, but will within "a couple of days".

**Comment by ssilvert** [comment]
@pmorch Either way is fine.  Just let me know if you do create a new PR and reference it from here.  I'll be out until Monday so I probably won't get to it until then.

**Comment by ssilvert** [comment]
@pmorch I'm back now.  If you want to squash those commits I can approve and merge.

The way I squash the last two commits is like this:
```
git reset --soft HEAD~2
git commit
git push --force origin mybranch
```

**Comment by pmorch** [comment]
Hi there, @ssilvert : It was a little more complicated than just merging two commits.

The reason I needed to introduce the second commit was that a Hungarian translation made it into master between my PR and the time you saw it, causing merge conflicts. So a merge with master was required.

Instead I rebased the original PR to the current master and fixed the merge conflicts manually again, so there now again is only one commit against current master. All should be well now, I hope.

**Review by ssilvert — APPROVED** [review]
Looks good.  Thanks!

**Pull request merged**
