### PR TITLE
[Windows] Stabilizing flaky Quarkus unit tests

### LINKED ISSUE #35405: [Keycloak CI] - Quarkus UT (windows-latest) - Keycloak Quarkus Server Deployment
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

> Error:  Errors: 
> Error:    KeycloakMetricsConfigurationTest � Runtime java.lang.RuntimeException: Failed to start quarkus
> Error:    KeycloakNegativeHealthCheckTest � Runtime java.lang.RuntimeException: Failed to start quarkus
> Error:    KeycloakPathConfigurationTest � Runtime java.lang.RuntimeException: Failed to start quarkus
> Error:    KeycloakReadyHealthCheckTest � Runtime java.lang.RuntimeException: Failed to start quarkus
> [INFO] 
> Error:  Tests run: 4, Failures: 0, Errors: 4, Skipped: 0
> 

`Caused by: java.lang.IllegalStateException: fv-az653-80-49239: failed to find an available port in ports [57800, 57801, 57802, 57803]`

https://github.com/keycloak/keycloak/actions/runs/12049067476/job/33595264630

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Pepo48**
Closes: #35405

### CODE REVIEW

**Review by vmuzikar — COMMENTED** [review]
There seems to be a compilation error.

**Comment by Pepo48** [comment]
@vmuzikar I decided to utilize `@BeforeEach` annotation instead - we've already used it for setting the port up, it should also do the trick for the property. Alternatively, we can create here a custom junit extension annotation in a similar fashion like we do for the integration tests, but it's probably unnecessary. Please, check again. Thanks.

**Review by shawkins — COMMENTED** [review]
Could this be done in a before all, with a after all that removes the setting?

**Comment by Pepo48** [comment]
@shawkins sure, it can be done that way. We just need to leave the port setting annotated with @BeforeEach.

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks.

**Review by shawkins — APPROVED** [review]
LGTM

**Comment by vmuzikar** [comment]
@Pepo48 Do you want to take it out of draft?

**Pull request merged**
