### PR TITLE
KEYCLOAK-9988 Unstable UserSessionPersisterOfflineTest.testExpired - …

### PR DESCRIPTION
**Pull request by mposolda**
…more fix

### CODE REVIEW

**Comment by mposolda** [comment]
@vramik Could you please run DB matrix for this PR?

**Comment by mposolda** [comment]
@vramik Maybe I managed to run DB matrix :) See mail for more details.

**Review by hmlnarik — DISMISSED** [review]

**Review by vramik — CHANGES_REQUESTED** [review]
@mposolda I'm affraid the issue is still present see e.g.: https://keycloak-jenkins.com/job/test-keycloak-jpa/102/DB=mariadb101,jdk=local_openjdk8,label_exp=rhel7_large/testReport/org.keycloak.testsuite.model/UserSessionProviderOfflineTest/testExpired/

**Comment by mposolda** [comment]
@vramik @hmlnarik Issue not present anymore with the latest build from today https://keycloak-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/test-keycloak-jpa/105/ (Used different branch for the JPA build, but it's in fact the same stuff used in this PR)

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
