### PR TITLE
[KEYCLOAK-9102] Re-Auth for Same Client Session Can Have Stale RelayState Info

### PR DESCRIPTION
**Pull request by josh-cain**
See description on [Jira](https://issues.jboss.org/browse/KEYCLOAK-9102).

### CODE REVIEW

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Thanks for your contribution! Please see inline for detailed review. Overall, the changes are SAML specific and should be only implemented in SAML classes. Also please add a test to org.keycloak.testsuite.saml package.

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Comment by hmlnarik** [comment]
@cainj13 Could you please have a look and address the comments?

**Comment by cainj13** [comment]
@hmlnarik - hey, I've got this set to allow edits from contributors, but I'm not able to get to this any time in the near future.

**Comment by hmlnarik** [comment]
Hi @joshuacain, thanks for the reply. Unfortunately there's not time to rework the PR in our team so I'm closing it now. Still, if you find some time, feel free to reopen and update the PR.
The JIRA is valid and I'm leaving it open.

**Pull request closed without merging**
