### PR TITLE
KEYCLOAK-12876 re-introduce some changes to preserve UserStorage SPI …

### PR DESCRIPTION
**Pull request by mposolda**
…backwards compatibility

### CODE REVIEW

**Comment by mposolda** [comment]
@stianst @abstractj Do someone of you have a chance to review? The PR re-introduce some changes in UserStorage SPI to preserve backwards compatibility with the versions older than Keycloak 8.0.0. Keycloak 8.0.0 introduced some backwards incompatible changes in the Authentication SPI PR and this PR fixes it.

It is related to the quickstarts PR: https://github.com/keycloak/keycloak-quickstarts/pull/166

**Review by slaskawi — DISMISSED** [review]

**Comment by slaskawi** [comment]
@mposolda LGTM

**Comment by mposolda** [comment]
@slaskawi @stianst @abstractj @vmuzikar Anyone of you has a chance to review this please? Thanks

**Review by stianst — APPROVED** [review]

**Review by iankko — COMMENTED** [review]
@mposolda Thank you for the change, Marek!

Wondering how much (into the past) is this change intended to be backward compatible?

In other words, I can see the `getValue()` method got added e.g. for the [CredentialModel](https://github.com/keycloak/keycloak/pull/6795/files#diff-63f0f74afad3ca2088937956fe782110) implementation. But I would expect e.g. the [user-storage-simple](https://github.com/keycloak/keycloak-quickstarts/tree/latest/user-storage-simple) quickstart to work properly with this change already.

But it doesn't seem to be the case yet:
```
$ git clone -b KEYCLOAK-12876-user-storage-backwards-compat git@github.com:mposolda/keycloak.git
```

```
cd keycloak/
```

```
$ mvn clean install -Pdistribution -DskipTests
```

Once rebuild, unzip & run the updated server (in `standalone` mode):
```
$ cp keycloak/distribution/server-dist/target/keycloak-9.0.1-SNAPSHOT.zip distribution/
```

```
$ ./standalone.sh
```

Then try to run the `user-storage-simple` quickstart:
```
[iankko@localhost user-storage-simple]$ mvn clean install wildfly:deploy
...
ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /tmp/github/keycloak-quickstarts/user-storage-simple/src/main/java/org/keycloak/quickstart/writeable/PropertyFileUserStorageProvider.java:[257,36] cannot find symbol
  symbol:   method getValue()
  location: variable cred of type org.keycloak.models.UserCredentialModel
[ERROR] /tmp/github/keycloak-quickstarts/user-storage-simple/src/main/java/org/keycloak/quickstart/writeable/PropertyFileUserStorageProvider.java:[268,60] cannot find symbol
  symbol:   method getValue()
  location: variable cred of type org.keycloak.models.UserCredentialModel
[ERROR] /tmp/github/keycloak-quickstarts/user-storage-simple/src/main/java/org/keycloak/quickstart/readonly/PropertyFileUserStorageProvider.java:[120,36] cannot find symbol
  symbol:   method getValue()
  location: variable cred of type org.keycloak.models.UserCredentialModel
[INFO] 3 errors 
...
```
Is this expectation (that the `user-storage-simple` quickstart) should work properly with the change already wrong?

Or should same / similar `getValue()` / `setValue()` methods be added to the `org.keycloak.models.UserCredentialModel` too?

**Comment by mposolda** [comment]
@stianst Thanks for the review and merge!

@iankko Hmmm.... Actually if you look at the changed files in this PR, you can see that methods getValue / setValue were re-added to class UserCredentialModel in this PR. So this compilation error is exactly something, which shouldn't happen anymore...

I've just tried to compile user-storage-simple and user-storage-jpa modules from the "master" branch of latest "keycloak/keycloak-quickstarts" and indeed I can see that compilation with "mvn clean install" is successful now.

I am not sure exactly what step is missing for you, so that you saw the compilation error. Could you doublecheck if you are really on the "master" branch of the quickstarts? When I look at this URL through the web https://github.com/keycloak/keycloak-quickstarts , I can see that default branch is "latest" . This branch has dependency on Keycloak 9.0.0 and that's maybe why you still see compilation error. Could it be the case?

**Comment by iankko** [comment]
> @iankko Hmmm.... Actually if you look at the changed files in this PR, you can see that methods getValue / setValue were re-added to class UserCredentialModel in this PR. So this compilation error is exactly something, which shouldn't happen anymore...
> 
> I've just tried to compile user-storage-simple and user-storage-jpa modules from the "master" branch of latest "keycloak/keycloak-quickstarts" and indeed I can see that compilation with "mvn clean install" is successful now.
> 
> I am not sure exactly what step is missing for you, so that you saw the compilation error. Could you doublecheck if you are really on the "master" branch of the quickstarts? When I look at this URL through the web https://github.com/keycloak/keycloak-quickstarts , I can see that default branch is "latest" . This branch has dependency on Keycloak 9.0.0 and that's maybe why you still see compilation error. Could it be the case?

@mposolda 

Right, that was it, used `latest` branch of quickstarts instead of the `master` one: :( 
```
$ git status
On branch latest
Your branch is up to date with 'origin/latest'.
```

With `master` one it works:
```
15:16:44,079 INFO  [org.keycloak.subsystem.server.extension.KeycloakProviderDeploymentProcessor] (MSC service thread 1-6) Deploying Keycloak provider: user-storage-properties-example.jar
15:16:44,145 INFO  [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0010: Deployed "user-storage-properties-example.jar" (runtime-name : "user-storage-properties-example.jar")
```

Sorry for turmoil

**Comment by mposolda** [comment]
@iankko Cool! Glad we figured it. Thanks for the confirm!

**Pull request merged**
