### PR TITLE
Fix erroneous return of parent group when querying for groups via attribute keycloak/keycloak#16535

### LINKED ISSUE #16535: Group Attribute Search Erroneously returns when searching for nested group
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

When given a group structure such as 

- group1 (attr: <test, test> )
- group2
-- group2_a (attr: <group2_test, group2_test>) 
-- group2_b

Querying for the attribute `(test, test)` of `group1` will correctly return `group1`

Querying for the attribute `(group2_test, group2_test)` will *incorrectly* return `group2` as well as both sub groups. 

### Version

confirmed on main branch

### Expected behavior

Querying for a sub group should only return that sub group

However, a test was added that checks that the problematic behavior actually does occur. I believe this was added erroneously (by me) and not caught. 

[`GroupSearchTest:](https://github.com/agandhew/keycloak/blob/73d01403bc594c693c6d39af7804fa6307be49ec/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupSearchTest.java#L128-L147)

### Actual behavior

Querying for a sub group by attribute should only return that sub group as it's the only one relevant to the search

### How to Reproduce?

GET <keycloak url>/auth/admin/realms/redhat-external/groups?q=<attribute name>:<attribute value>&first=0&max=20

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by alice-wondered**
resolves keycloak#16535

### CODE REVIEW

**Comment by stianst** [comment]
> testPersistenceClientSessionsMultipleNodes

Reported https://github.com/keycloak/keycloak/issues/16564

**Comment by pedroigor** [comment]
@Redhat-Alice Would make sense to leverage the `briefRepresentation` parameter to indicate that the response should not include the group hierarchy?

The changes herein proposed should work fine but they add a bit more complexity to the endpoint (another parameter). I see the `briefRepresentation` as a parameter that indicates whether you want more details about groups, including hierarchy.

When `briefRepresentation` is set to `false` we assume the caller does not want to return hierarchy (in addition to other data such as roles, attributes, etc), hence returning the groups separately.

I'm not sure about the impact on the admin console though. @ssilvert Do you know if not returning the group hierarchy by default (as it stands today) will break the admin console?

**Comment by hmlnarik** [comment]
@Redhat-Alice I like the PR as is, looks as a good addition to me. Could you please rebase?

**Comment by Redhat-Alice** [comment]
Rebased on latest upstream main branch!

**Review by hmlnarik — APPROVED** [review]
LGTM. I am approving as is.

@Redhat-Alice could you please respond to @pedroigor 's question [above](https://github.com/keycloak/keycloak/pull/16540#issuecomment-1558036190)? My take is that it is sensible to have special option here, [elaborated in here](https://github.com/keycloak/keycloak/issues/20445#issuecomment-1569651752).

@pedroigor @mposolda Since this is touching the admin endpoint, would you like to review too?

**Comment by ssilvert** [comment]
> I'm not sure about the impact on the admin console though. @ssilvert Do you know if not returning the group hierarchy by default (as it stands today) will break the admin console?

@pedroigor @hmlnarik I'm not sure about this either.  Trying to find out.  One problem is that the admin console tests don't run for this PR because there are no changes to the UI code.

**Comment by Redhat-Alice** [comment]
> @Redhat-Alice could you please respond to @pedroigor 's question [above](https://github.com/keycloak/keycloak/pull/16540#issuecomment-1558036190)? My take is that it is sensible to have special option here, [elaborated in here](https://github.com/keycloak/keycloak/issues/20445#issuecomment-1569651752).

I also agree. It's possible to want to retrieve from this endpoint: groups that match the query with no hierarchy data (functioning as a list of groups that exist and match the query, irrespective of where they fall in the hierarchy) and groups that match the query with hierarchy data (serving the purpose of populating a UI with contextual information after a search, for instance) 

Additionally, either of these two possibilities could call for returning the brief representation of all matched records or not. If the goal is to get exactly one matched group with no hierarchal information it may make sense to retrieve all information for that record whereas if the goal is to get the entire hierarchy for a matched group then we would want the ability to cut the returned information down to avoid a bloated response size. 

I do think that maybe this could be done with a more intuitive approach using separate endpoints for these goals (getting a specific group you're searching for vs populating hierarchy data) but as I understand there are some concerns over changing things in this way, so having two configuration properties with default values does feel like a more solid middle ground!

**Pull request merged**
