### PR TITLE
[fixes #9133] - Allow setting JDBC driver and transaction type

### LINKED ISSUE #9133: Configuration of custom JDBC driver is broken (leads to Azure SQL cannot be used as database)
Configuration of custom JDBC driver is broken (leads to Azure SQL cannot be used as database)

In previous versions of keycloak.x it was possible to configure the JDBC driver by settings the environment variable _KC_DB_DRIVER_ .
This is e.g. required to run keycloak.x in Azure using Azure SQL (see also [disussion on dev mailing list](https://groups.google.com/g/keycloak-dev/c/ZGuX0CFWqwo/m/uEHToZDSBwAJ)).

With keycloak.x 15.1.0 this does no longer work - the database driver is now set based on the db settings to a hard coded driver class. 
In case of mssql this uses a driver that uses XA transactions which are not supported by Azure SQL.
When trying to set the jdbc driver via configuration, keycloak uses the H2 database driver always.

I added a unit test to show the behaviour to [ConfigurationTest.java](https://github.com/bosch-io/keycloak/blob/bug/keycloak.x-setting-jdbc-driver/quarkus/runtime/src/test/java/org/keycloak/provider/quarkus/ConfigurationTest.java#L257).

Has this been changed intentionally or is this a bug?

_Originally posted by @ioemat in https://github.com/keycloak/keycloak/discussions/8654#discussioncomment-1799232_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #9133

### CODE REVIEW

**Review by DGuhr — DISMISSED** [review]

**Comment by ioemat** [comment]
I can confirm that this is fixes #9133 in our environment

**Comment by skug67** [comment]
I'm not sure if this is related (there's a pretty decent chance it's not) but since the update to 15.1.0 I have been unable to get keycloak.x to connect to my mariadb database.  It errors out with "Access denied" from the db server and a reference to character encoding (both my normal bash environment and the db server use UTF8).

`2021-12-20 15:49:55,933 ERROR [org.key.qua.run.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
2021-12-20 15:49:55,933 ERROR [org.key.qua.run.cli.ExecutionExceptionHandler] (main) ERROR: Could not connect to address=(host=localhost)(port=3306)(type=master) : (conn=93528) Access denied for user 'keycloak'@'127.0.0.1' (using password: YES)
2021-12-20 15:49:55,934 ERROR [org.key.qua.run.cli.ExecutionExceptionHandler] (main) ERROR: Could not connect to address=(host=localhost)(port=3306)(type=master) : (conn=93528) Access denied for user 'keycloak'@'127.0.0.1' (using password: YES)
Current charset is UTF-8. If password has been set using other charset, consider using option 'passwordCharacterEncoding'
2021-12-20 15:49:55,937 ERROR [org.key.qua.run.cli.ExecutionExceptionHandler] (main) ERROR: (conn=93528) Access denied for user 'keycloak'@'127.0.0.1' (using password: YES)
Current charset is UTF-8. If password has been set using other charset, consider using option 'passwordCharacterEncoding'
2021-12-20 15:49:55,937 ERROR [org.key.qua.run.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.`

**Comment by pedroigor** [comment]
@ioemat I've changed the properties to `kc.db.tx-type` and `kc.db.driver` to follow the same format we are using in other properties

**Review by DGuhr — APPROVED** [review]

**Review by abstractj — APPROVED** [review]

**Comment by pedroigor** [comment]
thanks @abstractj

**Pull request merged**
