### PR TITLE
OpenSSF Best Practices Badge Program

### LINKED ISSUE #13574: OpenSSF Best Practices Badge Program
### Discussed in https://github.com/keycloak/keycloak/discussions/13276

<div type='discussions-op-text'>

<sup>Originally posted by **marcwrobel** July 22, 2022</sup>
The [Open Source Security Foundation (OpenSSF) Best Practices badge](https://bestpractices.coreinfrastructure.org/) is a way for Free/Libre and Open Source Software (FLOSS) projects to show that they follow security best practices. Many popular projects (such as Linux, GitLab, Prometheus, OpenSSL...) already joined this program and I think it would send a positive message to the users if Keycloak could join it too.

Is the Keycloak team aware this program exists ? Is it something you could consider ?</div>

### PR DESCRIPTION
**Pull request by abstractj**
Resolves #13574

### CODE REVIEW

**Comment by vmuzikar** [comment]
@abstractj Thanks for the PR. If I understand correctly, our registration in OpenSSF Best Practices is maintained manually (basically we need to keep some form up-to-date). What will be the process for that? Who will be responsible for that?

**Review by pedroigor — APPROVED** [review]

**Comment by abstractj** [comment]
@vmuzikar yes it is maintained manually, and it is considered a good practice that from time to time maintainers reevaluate their projects.

@stianst all the Keycloak maintainers should have access to change https://bestpractices.coreinfrastructure.org/projects/6818. I don't mind waiting if you would like, or we can review and iterate over it.

**Review by vmuzikar — APPROVED** [review]
@abstractj Thank you for clarifying. If I understand correctly, in order to "maintain" the badge, all maintainers should be able to edit [the form](https://bestpractices.coreinfrastructure.org/projects/6818)? Makes sense to me (although it doesn't seem to work for me :)). In any case, LGTM.

**Comment by abstractj** [comment]
@vmuzikar in theory, that's what they say when I submitted the form (this is new for me). But I will check how to grant access to you.

**Comment by stianst** [comment]
Didn't want this single badge so added a few here https://github.com/keycloak/keycloak/pull/27921

**Pull request closed without merging**
