### PR TITLE
Check if OSGI metadata can be removed entirely

### LINKED ISSUE #29104: Check if OSGI metadata can be removed entirely
This issue is about checking if we can/should remove OSGI metadata or if we rather keep them.

The OSGI metadata were originally added to the `pom.xml` of some adapter modules and their dependencies for the purpose of Fuse adapters. Currently just few modules in the Keycloak codebase like `keycloak-common` or `keycloak-core` has those metadata as they were used by Fuse adapters. Keycloak server modules (like `keycloak-services` etc) don't have them as they never needed them. 

Now we don't support Fuse adapter anymore, so in theory, we don't need OSGI metadata anymore. On the other hand, keeping OSGI metadata is probably not huge deal and not big maintenance cost. They can be still used by community for some purpose (by people, who include `keycloak-common` and `keycloak-core` in their dependencies and use them in some OSGI-friendly environment). In the past, there was even request from the community to add those metadata even to server libraries.

We may first need to open discussion in the community whether to remove OSGI metadata or not. If there is not much people, we can maybe first deprecate them in the release notes of Keycloak X (where X is probably bigger than 25) with the announcement of them being removed and then we can remove them in Keycloak X+1.

### PR DESCRIPTION
**Pull request by douglaspalmer**
Closes #29104

### CODE REVIEW

**Review by mposolda — DISMISSED** [review]
@douglaspalmer Thanks!

**Review by jonkoops — DISMISSED** [review]
LGTM, but perhaps this warrants a note in the changelog?

**Comment by douglaspalmer** [comment]
> LGTM, but perhaps this warrants a note in the changelog?

I just added a release note, thanks.

**Review by jonkoops — APPROVED** [review]

**Review by mposolda — APPROVED** [review]
@jonkoops @douglaspalmer Thanks!

**Pull request merged**
