### PR TITLE
KEYCLOAK-10153 When a LDAP managed user changes its own password, allow Keycloak to propagate the update using the LDAP user DN instead of the LDAP admin DN

### PR DESCRIPTION
**Pull request by reda-alaoui**

### CODE REVIEW

**Comment by reda-alaoui** [comment]
Conflict solved

**Comment by reda-alaoui** [comment]
Oups :)

**Comment by reda-alaoui** [comment]
Build should be green now.

**Comment by reda-alaoui** [comment]
Hello?

**Review by mposolda — CHANGES_REQUESTED** [review]
Thanks for the contribution and sorry for longer review. I am not sure whether to accept the PR and introduce new configuration switch. IMO there are few issues with the approach like:

1) It is specific just for one specific use-case of password updates. It won't work with other operations where LDAP update will be needed (Updating user profile, user registration, changing of password by administrator from the admin console).

2) I think it won't work in new account console. We plan to do some refactoring and change the credential screen of new acount console. Among other things, the existing password won't be available in same screen where user provides his own password like it is in the old account console (the current AccountForm console).

For the reason 2, I would surely wait with this PR until we have new account console ready and make sure that it works with the new credentials in new account console. Otherwise, things will stop work when we do the current account console the default one and we will have the test failure to fix. I think we may need to add existing password as a note to the authenticationSession during flow and then somehow make this available in the user session. This should be somehow done on demand (introduce the option on the PasswordAuthenticator or require to subclass the authenticator, but that's TBD). Hence I am adding the label "On Hold" to this PR.

For the reason 1, I wouldn't introduce the 1st level option to LDAP provider. I would rather add the LDAP mapper, but not even sure whether to introduce LDAP mapper directly to keycloak codebase or have that as a community extension. Every mapper and configuration option adds some complexity and TBH this use-case seem to me like supporting one corner-case scenario. IMO the typical LDAP deployment, which don't want to bind to LDAP with admin credentials, should rather use the "read-only" or "unsynced" edit mode.

BTV. in new keycloak version, we introduced the vault capability, which allows to hide the LDAP bindCredential to be directly available in Keycloak DB. Not sure if that helps to re-consider whether use admin credentials.

**Comment by mposolda** [comment]
Closing the PR as there are lots of conflicts and there is no additional feedback from the reporter.

**Pull request closed without merging**
