### PR TITLE
KEYCLOAK-12744: rh-sso-preview theme for product build

### PR DESCRIPTION
**Pull request by ssilvert**
This PR fixes issues from https://github.com/keycloak/keycloak/pull/6691

### CODE REVIEW

**Review by abstractj — COMMENTED** [review]
@ssilvert maybe I'm doing something wrong, but when I click on "Signing in Page" it loads forever and I get: https://i.imgur.com/bQ1LnU6.png. Not sure if that's related.

## Steps to reproduce
1.  mvn clean install -Pnpm-update -Pdistribution -DskipTests=true -Dproduct
2. cp distribution/server-dist/target/rh-sso-7.4.zip ~/tmp && cd ~/tmp && unzip rh-sso-7.4.zip && cd rh-sso-7.4
3. export JBOSS_HOME=`pwd`; export WILDFLY_HOME=`pwd`
4. Login into the admin console and set the `account` theme to `rh-sso-preview`
5. Go to `Manage account` and click in `Signing In`

Please let me know how you've been testing it and I can give it a try.

**Comment by vmuzikar** [comment]
@ssilvert I'm afraid the issue @abstractj described is present in upstream too. Something must have changed after Alex's PR was merged.

Luckily, the fix should be as simple as adding
```xml
<include>**/node_modules/@patternfly/react-icons/dist/umd/icons/plus-circle-icon.js</include>
```
to the [POM](https://github.com/keycloak/keycloak/blob/1a53110bb61be27a5cca5af267cfc2d1dd36df6b/themes/pom.xml#L354).

**Review by vmuzikar — CHANGES_REQUESTED** [review]
Found one more thing to productize:https://github.com/keycloak/keycloak/blob/1331f917485552e93ec42a502ece7f60a7152a9d/themes/src/main/resources/theme/keycloak-preview/account/index.ftl#L4
https://github.com/keycloak/keycloak/blob/f1ddd5016fb8e9c96ba929ef028e5ee4e0637b3f/themes/src/main/resources/theme/base/account/messages/messages_en.properties#L18

It's already done [in the rh-sso theme](https://github.com/keycloak/keycloak/blob/90c4de27e5970f784396cd2a36868126412eb900/themes/src/main/resources-product/theme/rh-sso/account/messages/messages_en.properties#L2-L1) but I'm not sure if we can use it in the preview theme.

**Comment by vmuzikar** [comment]
> ```
> ```
> <include>**/node_modules/@patternfly/react-icons/dist/umd/icons/plus-circle-icon.js</include>
> ```
> ```

@ssilvert @abstractj Fixed that in https://github.com/keycloak/keycloak/pull/6706

**Comment by ssilvert** [comment]
> Found one more thing to productize:
> 
> https://github.com/keycloak/keycloak/blob/1331f917485552e93ec42a502ece7f60a7152a9d/themes/src/main/resources/theme/keycloak-preview/account/index.ftl#L4
> 
> 
> https://github.com/keycloak/keycloak/blob/f1ddd5016fb8e9c96ba929ef028e5ee4e0637b3f/themes/src/main/resources/theme/base/account/messages/messages_en.properties#L18
> 
> It's already done [in the rh-sso theme](https://github.com/keycloak/keycloak/blob/90c4de27e5970f784396cd2a36868126412eb900/themes/src/main/resources-product/theme/rh-sso/account/messages/messages_en.properties#L2-L1) but I'm not sure if we can use it in the preview theme.

Good catch.  I'll fix it a little later today.

**Comment by ssilvert** [comment]
> Found one more thing to productize:
> 
> https://github.com/keycloak/keycloak/blob/1331f917485552e93ec42a502ece7f60a7152a9d/themes/src/main/resources/theme/keycloak-preview/account/index.ftl#L4
> 
> 
> https://github.com/keycloak/keycloak/blob/f1ddd5016fb8e9c96ba929ef028e5ee4e0637b3f/themes/src/main/resources/theme/base/account/messages/messages_en.properties#L18
> 
> It's already done [in the rh-sso theme](https://github.com/keycloak/keycloak/blob/90c4de27e5970f784396cd2a36868126412eb900/themes/src/main/resources-product/theme/rh-sso/account/messages/messages_en.properties#L2-L1) but I'm not sure if we can use it in the preview theme.

Fixed.

**Comment by abstractj** [comment]
@ssilvert I did a rebase against the changes from master and we should be good to go.

**Review by abstractj — APPROVED** [review]

**Review by vmuzikar — APPROVED** [review]
@abstractj Yes, after rebase to current master everything works as expected.

LGTM, thanks @edewit @ssilvert!
Just please be careful when merging this. This PR currently contains a merge commit which we try to avoid in repo. Therefore we should squash it before merging (you can use the [`Co-authored-by:`](https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors) commit message trailer).

**Pull request merged**
