### PR TITLE
KEYCLOAK-9091 Fix for claims with dots from userInfo

### PR DESCRIPTION
**Pull request by helaar**
Rewritten getJsonValue using OIDCAttributeMapperHelper.splitClaimPath and removed recursion.

### CODE REVIEW

**Review by mposolda — COMMENTED** [review]
The PR looks good to me, but formatting is a bit broken. Could you please setup your editor to avoid changes in the lines, which you didn't touch? Also could you setup it to use spaces instead of tabs and make sure 4 spaces for nested blocks are used? EG. like this:
```
if (something) {
    doSomething();
}
```

**Review by mposolda — CHANGES_REQUESTED** [review]
The PR looks good to me, but formatting is a bit broken. Could you please setup your editor to avoid changes in the lines, which you didn't touch? Also could you setup it to use spaces instead of tabs and make sure 4 spaces for nested blocks are used? EG. like this:
````
if (something) {
    doSomething();
}
````

**Comment by helaar** [comment]
Fomatting was actually set to 4 spaces, but original content of AbstractJsonUserAttributeMapperTest seems a bit fishy in the `getJsonValue_nestedSimpleValues` test so I have some issues reverting this changes into a clean one-commit PR. 

I could drop this PR and create a new one if that is more convinient?

**Comment by helaar** [comment]
Sorry for beeing impatient, but are you waiting for me to do anyting more, please tell me. I'm a bit eager to get this PR into the 8.0.0 release in October

**Review by mposolda — APPROVED** [review]
@helaar Thanks for the change and sorry for late review

**Pull request merged**
