### PR TITLE
improve german email translation

### LINKED ISSUE #15948: Improve german email messages
### Description

In german email messages of the base theme expirations are always shown in minutes.

In order to make the shown number a bit more readable the next greater time-unit shall be shown instead of minutes hardcoded.

### PR DESCRIPTION
**Pull request by klausbetz**
Closes #15948

### CODE REVIEW

**Review by sguilhen — COMMENTED** [review]
@ahus1 Would you be able to review this one?

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for updating the German translation to match the latest English texts.

Some small changes are necessary to merge this, please find my comments below. 

Please ensure that all changes are squashed to one commit. Please also rebase this PR with the latest changes in the main branch, as there were some recent changes around the GitHub actions which are required to be able to merge this PR.

**Comment by klausbetz** [comment]
@ahus1 Thx for your comments. Should be resolved.

**Review by ahus1 — APPROVED** [review]
Thank for updating the German translation, looks good to me!

**Comment by ahus1** [comment]
Hi @klausbetz - I see you pushed new changes. I'll now wait for the build to complete and then re-review your changes. 

If you could leave a not what you've changed, this would be great.

**Comment by klausbetz** [comment]
@ahus1 I just rebased the branch.

**Review by ahus1 — APPROVED** [review]
Thank you for updating the translation!

**Pull request merged**
