### PR TITLE
KEYCLOAK-14132 DefaultSecurityHeadersProvider should support 307 as r…

### PR DESCRIPTION
**Pull request by martin-kanis**
…edirect code

### CODE REVIEW

**Comment by stianst** [comment]
Keycloak doesn't use 307 or 308 codes, so I don't think this is needed.

**Comment by stianst** [comment]
Rejecting this as there is no explanation why this is needed

**Comment by PhilippStein** [comment]
@stianst I agree that 307 and 308 should be added. I wrote a keycloak extension which is using 307 for temprary redirect. The extention was working fine with Keycloak 8.0.2, but now with 10.0.2 I'm getting the exception `"ERROR [org.keycloak.headers.DefaultSecurityHeadersProvider] (default task-14) MediaType not set on path /auth/realms/entity/protocol/openid-connect/auth, with response status 307"`.
I changed my extension now to use 302 for the redirect, so this is working, but 307 would be more accurate.

**Comment by PhilippStein** [comment]
Maybe this is related and the facebook provider is also using 307?
https://keycloak.discourse.group/t/failure-when-logging-in-out-from-keycloak-using-fb-provider/3217/2

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
Approving this as I don't see any harm. The Facebook provider shouldn't do a 307 though, so not sure what's going on there.

**Comment by ullgren** [comment]
Not sure if this is it but seems that Undertow is using 307 as TEMPORARY_REDIRECT 
(https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/util/StatusCodes.java#L52) perhaps this is related.

Since we are also having issues with this in a custom IDP provider (without explicitly using 307 our self). Any chance this will be backported to 10.0.x ?

**Pull request merged**
