### PR TITLE
Keycloak.js: Add support for passing acr_values in auth requests

### LINKED ISSUE #9383: Support to customize acr_values query parameter in keycloak.js
### Description

Allow to customize the acr_values query parameter to let clients control the level of authentication they require.

### Discussion

_No response_

### Motivation

Given the newly added support for Step-Up Authentication  #7897, it makes sense to add support for configuring the required level of authentication in client libraries.

Currently it is hard to use the Step-Up Authentication support from clients since there is no explicit support for configuring acr_values for auth requests.

To play with the new feature we currently need to monkey patch the Keycloak object and augment the createLoginUrl function:
```javascript
...
let originalCreateLoginUrl = keycloak.createLoginUrl;

keycloak.createLoginUrl = function(options) {
    let url = originalCreateLoginUrl(options);
    url += "&acr_values=0";
    return url;
};
...
```

### Details

The keycloak.js adapter should allow to configure `acr_values` as query parameter for login and registration urls.

```javascript

let keycloak = new Keycloak({
    url: keycloakUrl,
    realm: realm,
    clientId: clientId
});

let initConfig = {
    onLoad: 'login-required', // redirects to login if not login
    // onLoad: 'check-sso', // shows login button of not logged in
    checkLoginIframe: true,
    checkLoginIframeInterval: 1,
    pkceMethod: 'S256',
    scope: scope,
    acrValues: "0"  // new parameter
};

...

keycloak.init(initConfig).success(onLoginSuccess);
```

The `acr_value` should be configurable via  `initOptions` and `loginOptions` for login and register urls.

### PR DESCRIPTION
**Pull request by thomasdarimont**
Fixes #9383

Signed-off-by: Thomas Darimont <thomas.darimont@googlemail.com>

### CODE REVIEW

**Review by jonkoops — DISMISSED** [review]

**Comment by jonkoops** [comment]
I see no issue in getting this in, @thomasdarimont would you be interested in rebasing this PR to get it into a mergable state?

**Comment by thomasdarimont** [comment]
@jonkoops I just updated the PR based on current main.

**Comment by jonkoops** [comment]
Seeing some failures on CI

**Comment by mposolda** [comment]
@jonkoops @thomasdarimont BTV. Just a note that there is already parameter `acr` supported for the `login` method. It will send the configured acr in the `claims` parameter to the Keycloak server. This has somehow more flexible than `acr_values` as it allows both "essential" and "non essential" acr (where the `acr_values` allows only non-essential). However it is a JSON and hence a little bit complicated to use. So I am fine with including `acr_values` as well. Just wanted to point it in case it is sufficient for your purposes. See docs for the details: https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter

**Comment by thomasdarimont** [comment]
@mposolda Thanks for the mention. Yes the `acr` parameter is more versatile, but the acr_values parameter is also standard and used by many projects in the context of step-up authentication, see: https://developer.okta.com/docs/guides/step-up-authentication/main/#predefined-parameter-values

I'll add a short note to the documentation of the javascript adapter parameters.

**Comment by thomasdarimont** [comment]
Added documentation of `acr_values` for init and login options.

**Review by jonkoops — DISMISSED** [review]
LGTM

**Comment by jonkoops** [comment]
@stianst @mposolda this looks fine to me, can I ask one of you to merge this in?

**Review by mposolda — DISMISSED** [review]
@thomasdarimont @jonkoops Looks good, Thanks! Hopefully it is auto-merged once tests are ok

**Comment by jonkoops** [comment]
Looks like some of the tests are still failing, @thomasdarimont could you take a look?

**Comment by thomasdarimont** [comment]
@jonkoops it seems as the failures were caused by some network hickups:
````
...
2023-07-26T11:39:12.2374113Z [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (default) on project keycloak-js-adapter-jar: Could not download Node.js from: https://nodejs.org/dist/v18.16.0/win-x64/node.exe: Got error code 500 from the server. -> [Help 1]
...````

I'll rebase the code and trigger a re-run.

**Comment by thomasdarimont** [comment]
Okay, now I see test failures:
``` 
2023-08-01T22:23:59.2941402Z -- [ERROR] org.keycloak.testsuite.javascript.JavascriptAdapterTest.testAcrValuesInLoginOptionsShouldBeConsideredByLoginUrl  Time elapsed: 4.9 s  <<< FAILURE!
2023-08-01T22:23:59.2942333Z -- java.lang.AssertionError
2023-08-01T22:23:59.2942709Z -- 	at org.junit.Assert.fail(Assert.java:87)
```
I'm taking a look...

**Comment by thomasdarimont** [comment]
Should be fixed now, I had a typo in the JavaScriptAdapterTest... (the config option is `acrValues` and not `acr_values`)

**Comment by thomasdarimont** [comment]
Last remaining error was the external link checker in the documentation build:
```
Error:  checkExternalLinks{String}[3]  Time elapsed: 138.076 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
Broken links (1):
		- https://nodejs.org/ (invalid redirect to /en/)
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:135)
	at org.keycloak.documentation.test.ExternalLinksTest.checkExternalLinks(ExternalLinksTest.java:26)
```
Currently https://nodejs.org seems to send the relative path ``/en/` in the `location` header of the response. Added `/en/` to the `ignored-link-redirects` file.

**Comment by thomasdarimont** [comment]
It seems that now the base-ui tests seem to fail with the same error message. I think there is something wrong with the testsetup. @jonkoops do you have an idea?

````Error: OR] org.keycloak.testsuite.ui.account2.PersonalInfoTest.navigationTest  Time elapsed: 0.206 s  <<< ERROR!
-- org.jboss.arquillian.graphene.enricher.exception.PageObjectInitializationException: 
-- Can not instantiate Page Object 
-- class org.keycloak.testsuite.ui.account2.page.PersonalInfoPage
--  declared in: 
-- org.keycloak.testsuite.ui.account2.PersonalInfoTest
````

**Comment by jonkoops** [comment]
@thomasdarimont I am not to familiar with these tests, but I think it might be related to #22251. Since a fix just landed, perhaps a rebase will fix the issue?

**Comment by thomasdarimont** [comment]
@jonkoops thanks for the hint! I give it another try :)

**Comment by jonkoops** [comment]
@thomasdarimont have you gotten any time to work on this? We're in the process of pruning some PRs, so I'd like to get this merged or closed. Let me know!

**Comment by jonkoops** [comment]
Closing this PR to prune our backlog. I'll re-open it if there is renewed interest in landing this.

**Comment by thomasdarimont** [comment]
I wanted to take another look at this.

**Comment by thomasdarimont** [comment]
I wanted to take another look at this.

**Comment by thomasdarimont** [comment]
I'll send a new PR for this.

**Pull request closed without merging**
