### PR TITLE
Move over caching related interfaces to the legacy module

### LINKED ISSUE #12531: Move org.keycloak.models.cache to model-legacy module
## Description

server-spi module contains `org.keycloak.models.cache` package which contains interfaces related to internals of legacy store. Therefore this package has to be moved to model-legacy module.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #12531

### CODE REVIEW

**Comment by ahus1** [comment]
2 Classes moved, one to go.

Question to @hmlnarik - how to handle CachedObject that CacheableStorageProviderModel depends on.

**Comment by ahus1** [comment]
Answered by @hmlnarik: `CachedObject` and everything that depends on it should be moved.

**Comment by ahus1** [comment]
Moved over a first set of classes around ClientStorageProviderModel in commit 3e324dfa0ae2a586c1017efc826c1b62d059eaab. Found that ClientStorageProviderResource wasn't used anywhere, which is strange. 

@hmlnarik - please have a look and comment on the changes if I moved too much or too few classes. Other classes (GroupStorageProviderModel, RoleStorageProviderModel, UserStorageProviderModel, ClientScopeStorageProviderModel) will follow.

**Comment by hmlnarik** [comment]
I like the way the changes are being made, thank you @ahus1 !

**Comment by ahus1** [comment]
@hmlnarik - this is now ready for a (final) review. 

Noteworthy changes: 
* When moving over the OpenShiftStorageProvider, I also moved over the OpenShift Client dependency to the legacy-services module. It included some transitive dependencies, including commons-lang. I had to remove some unused imports and update one test case to use plain Java.
* I chose not to mention this in the release notes as this is an internal change that shouldn't be visible; in Wildfly, those interfaces haven't been exported.
* The introduction of the interface LegacyRealmModel is something I liked better than the original refactoring to have a UserStorageUtil, still I kept the old code as is to avoid changing those places again for the sake of time. Due to this, the migration guide describes different ways on how to migrate the different methods.

The PR for the documentation is available here: https://github.com/keycloak/keycloak-documentation/pull/1590

I kept the moves of the different providers as separate commits. Each commit references the original issue (in contrast to the big legacy PR), so I'd assume it is OK to merge all those commits to have better traceability.

**Review by hmlnarik — APPROVED** [review]
Thank you for the PR!

**Pull request merged**
