### PR TITLE
[KEYCLOAK-14504] Correct behaviour of setReuiredActions to obey current Authflow

### PR DESCRIPTION
**Pull request by strima**
The previous codeblock (commit 39f40bc0054bd5a63d23b80c879a2bdc804faeb0 )iterated over ALL Authenticator Configs in the current realm (realm.getAuthenticatorConfigs())
This is not what we want since it is absolutely possible that other Authenticator Configs exist which have
possible other settings to the for us in the current auth flow relevant ones
e.g. the most simple scenario:
    * you have realm: TESTREALM
    * you have 2 Clients: CLIENTA and CLIENTB
    * you have defined 2 auth flows: FLOWA and FLOWB
    * in both flows you have configured a ConditionalOTPForm with following settings
        - FLOWA: defaultOtpOutcome=skip
        - FLOWB: defaultOtpOutcome=force
    * FLOWA is assigned to CLIENTA and FLOWB to CLIENTB
    * if you iterated over ALL configs in one concrete auth session as before then you will not get the desired behaviour
hence we try now to find the matching config based on the current auth flow

### CODE REVIEW

**Comment by abstractj** [comment]
@strima thanks for submitting this. Could you please check our contributing guidelines? See: https://github.com/keycloak/keycloak/blob/master/CONTRIBUTING.md

**Comment by strima** [comment]
JIRA: https://issues.redhat.com/browse/KEYCLOAK-14504
MAILINGLIST: https://groups.google.com/forum/#!topic/keycloak-dev/wkHr6Wf4GHs

**Comment by strima** [comment]
i'm not perfectly happy with this, since imho it would be way better to extend the interface definition for setREquiredActions by adding the context or even better the configModel , but since that would have meant to touch way more code i decided for the current implemented way in the patch
 
 
i didn't write tests for that scenario yet since i first wanted to talk about the proposed changes if they are the right direction

**Comment by mposolda** [comment]
@strima As pointed in the keycloak-dev, i strongly vote to address this properly instead of the workaround. Do you please have a chance to re-work this PR in that manner? Thanks!

**Comment by strima** [comment]
> @strima As pointed in the keycloak-dev, i strongly vote to address this properly instead of the workaround. Do you please have a chance to re-work this PR in that manner? Thanks!

sure - that's one of the reasons why i wanted to talk about that before starting the final part of establishing the tests

regarding organizational: shall i close this PR and create a new one as soon as i have refactoring done or can/should we keep this one and "just" add commits to it ?

**Comment by strima** [comment]
and what is the preferred way of discussing this ? here or in mailing list ?

**Comment by mposolda** [comment]
@strima Thanks! Whatever is easier for you.

Since the current commit is not useful anymore, it can be discarded entirely and replace with the other commit. Hence new PR might be good. On the other hand, you can use same PR for tracking purposes. So whatever you prefer :)

**Pull request closed without merging**
