### PR TITLE
consistent spelling of WebAuthn in user-facing material

### LINKED ISSUE #19216: Typo "Webauthn" (no capital "A")
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

When looking in the UI for "Authentication" -> "Required Actions", the "WebAuthn" is misspelled.

image

### Version

nightly

### Expected behavior

It should be "WebAuthn"

### Actual behavior

It shows "Webauthn"

### How to Reproduce?

Open the admin UI and choose "Authentication" -> "Required Actions".

### Anything else?

Search the codebase for the following (including quotes): 

```
"Webauthn Register"
"Webauthn Register Passwordless"
=Webauthn Register
```

Matches found in `messages_en.properties`, `DefaultRequiredActions.java`, `WebAuthnRegisterFactory.java`, `WebAuthnPasswordlessRegisterFactory.java`.

There are also occurrences in `webauthn.adoc` and `flows.adoc`. Fix text for `webAuthnPolicyPasswordlessFormHelp` in `authentication-help.json`. 

There is a table `required_action_provider` which contains the name of the providers which might needs to be updated. 
Don't know why the name is there, when it can be read from the factory?

### PR DESCRIPTION
**Pull request by christian-2**
* fixes #19216
* I did not touch any JavaScript or Vue identifiers with that lower-case "a"
* I ran tests as described in #20494 (specifically [here](https://github.com/keycloak/keycloak/issues/20494#issuecomment-1628169830)), and results were as follows:

```
INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Keycloak Quarkus Parent 999.0.0-SNAPSHOT:
[INFO] 
[INFO] Keycloak Quarkus Parent ............................ SUCCESS [  1.533 s]
[INFO] Keycloak Configuration API ......................... SUCCESS [  2.766 s]
[INFO] Keycloak Quarkus Server Extension .................. SUCCESS [ 17.738 s]
[INFO] Keycloak Quarkus Server Deployment ................. SUCCESS [ 52.722 s]
[INFO] Keycloak Quarkus Server App ........................ SUCCESS [  9.474 s]
[INFO] Keycloak Quarkus Server Distribution ............... SUCCESS [ 27.531 s]
[INFO] Keycloak Quarkus Test Parent ....................... SUCCESS [  0.014 s]
[INFO] Keycloak Quarkus Server JUnit 5 Internal Test Framework SUCCESS [  1.045 s]
[INFO] Keycloak Quarkus Server Integration tests .......... SUCCESS [44:45 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

**Review by ahus1 — COMMENTED** [review]
@christian-2 - thank you for these changes, they look all good to me. 

One more think that could be added here to complete the issue is to update the names in the table `required_action_provider`. This would require adding a Liquibase changeset. 

If you choose not to touch Liquibase for any reason, IMHO this PR could be merged (speaking for a storage team's perspective here, and as long as the core and UI teams agree) as long as the parent issue is kept open to track missing the Liquibase update in a future PR.

When you consider changing the PR, please ensure that there is only a single commit, and the commit comment includes "Closes: #xxxx" as described in `CONTRIBUTING.md`.

**Comment by christian-2** [comment]
@ahus1 Thanks for your quick review and suggestion re Liquibase. I can look into that too.

**Comment by ahus1** [comment]
Thank you @christian-2. I'm switching the PR to draft while you are looking into this. Please let me know if you have questions. You can switch it to non-draft once you see it is ready for another review.

**Comment by christian-2** [comment]
@ahus1 FYI I have prepared two Liquibase changelogs and a test (see below), but I cannot try this because of sustained issues with building from source and running all tests. There are apparently several reports about such issues (e.g. #21716).

```
model/map-jpa/src/main/resources/META-INF/jpa-required-actions-changelog.xml
model/map-jpa/src/main/resources/META-INF/required-actions/jpa-required-actions-changelog-1.xml
testsuite/model/src/test/java/org/keycloak/testsuite/model/requiredAction/WebAuthnTest.java
```

**Comment by ahus1** [comment]
@christian-2 - I've commented on that ticket. This is unfortunate, still I see that our main build completes successfully, see https://github.com/keycloak/keycloak/actions/runs/5583512724. 

The files you mentioned are for the new map storage, and I didn't see them committed to the PR yet, so I am not able to review them. There are also changelogs for the legacy JPA store which are located here: `model/jpa/src/main/resources/META-INF` which are the ones I had in mind. While the map store is in preview today, it might be OK to skip that migration. As the legacy store is the one that is maintained, it needs to have a migration.

**Comment by christian-2** [comment]
@ahus1 my guess at this point is that the Keycloak main build succeeds (as one would expect) because it presumably runs on RHEL, whereas some contributors are apparently facing issues on Debian (as in my case) and Windows.

I have not pushed those three files yet (only listed their names) for I would prefer to run local tests (including my new `requiredAction/WebAuthnTest`) first. This is the first time I am employing Liquibase, so it seems advisable to me.

Your hint towards `model/map-jpa/src/main/resources/META-INF` is well taken: I took `jpa-users-changelog.xml` and `users/jpa-users-changelog-1.xml` as inspiration.

**Comment by ahus1** [comment]
@christian-2 - while we're in the process getting your local build and tests to work in the other issue, there are some alternatives:

* Merge the PR as is, and keep the original issue open to submit a second PR with the Liquibase changes later
* You push your changes to a new branch your personal GitHub repository, and enable GitHub actions on the repository. While the cypress UI tests will not run in your repository as they are missing an API key, they other test should come up pretty green
* You an also push your changes to the PR, and the CI on this repo will show you if your tests succeeded or failed. While this PR is in draft mode, feel free to push more commits, and only later squash them before marking this PR "ready for review".

Again, thank you for the effort you're putting into this!

**Comment by christian-2** [comment]
@ahus1 I'd really like to get the build and tests working on my side as a prerequisite because (a) one would expect this to work judging from the documentation, and if it does not after sustained attempts this does eventually raise some doubts, (2) there are also other things that I'd like to contribute (e.g. ability to download adaptor configs for Apache `mod_shib`, i.e. `shibboleth2.xml`, etc., in a way similar to Mod Auth Mellon) and such efforts would clearly require a fully functioning local development environment.

**Comment by ahus1** [comment]
Closing this PR, as the discussion stalled.

**Pull request closed without merging**
