### PR TITLE
Remove ALL_OPTIONS from codebase as it is unused

### LINKED ISSUE #13850: HOSTNAME_ADMIN option is missing from HostnameOptions ALL_OPTIONS array
### Describe the bug

According to the code in [HostnameOptions class](https://github.com/keycloak/keycloak/blob/e3ece8244fff0206b029b9539257fdf2626b6c13/quarkus/config-api/src/main/java/org/keycloak/config/HostnameOptions.java) , the HOSTNAME_ADMIN option is defined but not added to the ALL_OPTIONS array.

As a consequence it may not be accessible to the configuration properties mappers .

Is this by purpose ?

### Version

main

### Expected behavior

HOSTNAME_ADMIN should have its entry in the HostnameOptions ALL_OPTIONS array

### Actual behavior

_No response_

### How to Reproduce?

N/A (it's just from source code analysis)

### Anything else?

_No response_

### LINKED ISSUE #13947: Remove `ALL_OPTIONS` from option category types
### Description

We don't need this https://github.com/keycloak/keycloak/blob/e3ece8244fff0206b029b9539257fdf2626b6c13/quarkus/config-api/src/main/java/org/keycloak/config/HostnameOptions.java#L47.

The same applies to other option category types.

It should be a follow-up of https://github.com/keycloak/keycloak/pull/13848.

### Discussion

https://github.com/keycloak/keycloak/issues/13850

### Motivation

Remove unnecessary code.

### Details

_No response_

### PR DESCRIPTION
**Pull request by DGuhr**
Closes #13850
Closes #13947

### CODE REVIEW

**Review by pedroigor — COMMENTED** [review]
As you mentioned before, we don't really use it for anything and it just adds unnecessary code and complicates things.

Based on the recent changes we did here https://github.com/keycloak/keycloak/pull/13848, we should remove this code pattern from the code.

If you are not able to change in this PR, I would close this one and create a follow-up issue.

**Comment by DGuhr** [comment]
will change it to remove them.

**Comment by DGuhr** [comment]
@pedroigor changed. Pls give it another review :)

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
Thanks.

**Pull request merged**
