### PR TITLE
Properly handle space in the directory name

### LINKED ISSUE #11343: kc.sh Does Not Allow Spaces in Filenames
### Describe the bug

When I run kc.sh from Ubuntu 20.04 and Java 11.0.12, I get the following error

```
carl@wdp:/media/carl/Extra Drive 1/opt/keycloak/keycloak-17.0.1$ ./bin/kc.sh
Error: Could not find or load main class Drive
Caused by: java.lang.ClassNotFoundException: Drive
carl@wdp:/media/carl/Extra Drive 1/opt/keycloak/keycloak-17.0.1$ 
```
This is being run from a folder containing a path segment with spaces.  In this case "Extra Drive 1".

### Version

17.0.1

### Expected behavior

I expected the server to start normally from a path with spaces.

### Actual behavior

The server fails to start

### How to Reproduce?

1. Create a folder on Ubuntu with spaces
2. Download and decompress Keycloak 17 in the folder from Step 1
3. Change into the Keycloak folder from Step 2
4. Run ./bin/kc.sh

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #11343

### CODE REVIEW

**Comment by DGuhr** [comment]
LGTM. For the quarkus tests failure i created #11460 to fix them - they are unrelated, were introduced by accidentally merging #11260

**Review by DGuhr — APPROVED** [review]

**Review by DGuhr — APPROVED** [review]
@pedroigor uhm, now there is a merge commit. Approved nevertheless, not that I care too much when it happens occasionally. 

For the future: Guess you used the UI to incorporate the changes of the other PR to fix CI. 

On the UI, there's also merge with rebase possible, see e.g. https://github.blog/2016-09-26-rebase-and-merge-pull-requests/

This can also be set up at repository level, so disallow merge commits in general, thus defaulting to rebase/squash. see screenshot from my Fork:
Screenshot 2022-04-19 at 13 02 00

cc @stianst maybe you want to change it for the main repo :)

**Comment by pedroigor** [comment]
@DGuhr It should be possible to squash commits before merging. Does it work for you?

**Comment by DGuhr** [comment]
@pedroigor sure, that was just a FYI - PR is approved :)

**Review by stianst — APPROVED** [review]

**Pull request merged**
