### PR TITLE
suppress confirmation screen for logout in oidc with new flag

### LINKED ISSUE #13469: Make compatibility mode for oidc logout endpoint fully compatible to previous keyloak versions
### Description

As of now the OIDC logout endpoint supports a legacy mode (`legacy-logout-redirect-uri`) where `redirect_uri` can be used instead of `post_logout_redirect_uri` also the `client_id` and `id_token_hint` get optional if the legacy mode is active.

Still there has been a breaking change with the introduction of the new logout endpoint behaviour with kc18. The new Keycloak logout confirmation page, which is if id_token_hint is not provided correctly or is missing.

### Motivation

As the logout endpoint is part of the client flow its hard to change a lot of clients very fast. We are facing the issue that some clients based there behaviour on the logout as it has been so far. The logout prompt in some cases confuses the users in others leads to problems in the way the system is integrated.

### Details

Therefore we would like to also disable the new confirmation page with the `legacy-logout-redirect-uri` flag (#13470)

The downside would be that this is indeed incompatible to the behaviour right now. Alternatively one could consider a new flag just for the confirmation page which is a new feature on its own. (#13471)

### PR DESCRIPTION
**Pull request by bs-matil**
One way to fix #13469

The documentation PR is https://github.com/keycloak/keycloak-documentation/pull/1658

### CODE REVIEW

**Comment by mposolda** [comment]
@bs-matil Thanks for this change. +1 for this approach.

Is it possible to also send PR to the keycloak/keycloak-documentation repository and introduce file "Migrating to 19.0.2" and add some note about this new switch? The previous switch was already documented https://www.keycloak.org/docs/latest/upgrading/#openid-connect-logout

**Comment by bs-matil** [comment]
@mposolda I filed the PR for the docs https://github.com/keycloak/keycloak-documentation/pull/1652

**Review by mposolda — DISMISSED** [review]

**Comment by mposolda** [comment]
@bs-matil I would like to merge this, but unfortunately there are some conflicts. Could you please rebase to latest Keycloak main and update this PR with the rebased version?

**Review by mposolda — DISMISSED** [review]
@sschu Thanks for the update!

I am approving. I hope to merge once the tests are ok

**Review by mposolda — APPROVED** [review]

**Pull request merged**
