### PR TITLE
KEYCLOAK-16862 Avoid NPE on realm update with trace enabled

### PR DESCRIPTION
**Pull request by micedre**
…eating event

### CODE REVIEW

**Comment by micedre** [comment]
oops, this has more impact than I thought, I'll look into it.

**Comment by micedre** [comment]
I am not sure about the best way to correct this. The problem is in `DefaultKeycloakContext#getUri` : when the event is treated (by the JbossLoggingEventListeningProvider  for instance), if the map `uriInfo` is empty, there is no context to retrieve UriInfo (the event being treated once the http request is finished). 
This is not really a problem if frontendUrl is defined, there will be a NPE in `JbossLoggingEventListeningProvider` (because of the toString), but, if it is not defined, we get an NPE before that.

A way to fix this is to call context.getUri before  on the session when the http request is not finished, so that the uriInfo map is populated, but this is not really pretty.

Do you see another way, without too much impact ?

**Review by mposolda — APPROVED** [review]
@micedre Thanks

**Comment by finventario** [comment]
> I am not sure about the best way to correct this. The problem is in `DefaultKeycloakContext#getUri` : when the event is treated (by the JbossLoggingEventListeningProvider for instance), if the map `uriInfo` is empty, there is no context to retrieve UriInfo (the event being treated once the http request is finished).
> This is not really a problem if frontendUrl is defined, there will be a NPE in `JbossLoggingEventListeningProvider` (because of the toString), but, if it is not defined, we get an NPE before that.

This also seems to be the case when trying to log login error events. (keycloakX)
Did anyone experience this as well?

**Pull request merged**
