### PR TITLE
KEYCLOAK-10802 add support of SAMLv2 ForceAuthn

### PR DESCRIPTION
**Pull request by Spechey**
Add support of SAML 2 request ForceAuthn attribute and update test to not use this to re authn test

### CODE REVIEW

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Thanks @Spechey for the PR, looks well fit into the code. Please see inline and also incorporate changes from https://github.com/Spechey/keycloak/pull/1. When the commits would be squashed, I believe this PR would be good to go.

**Comment by Spechey** [comment]
this is my first PR (and i'm not a developer), i hope i did the right thing.

**Comment by hmlnarik** [comment]
Thank you, almost. The only thing that remains now is to squash the 4 commits into a single one.

In case you are not familiar with how to do that:
1. `git rebase -i HEAD~4` (see [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) for the details what it does)
2. within the rebase, use `pick` or `p` for  first commit and `fixup` or `f` for the all the other
3. finally you force push this branch to your github repository: `git push -f`

See https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history for more details.

Hope that helps.

**Comment by Spechey** [comment]
Thanks to your help

**Comment by hmlnarik** [comment]
@Spechey Thanks for the changes now. Would you mind addressing also the other two review comments (https://github.com/keycloak/keycloak/pull/6289/files#r327499083 and https://github.com/keycloak/keycloak/pull/6289/files#r327521452)?

**Review by hmlnarik — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
