### PR TITLE
Angular 2: Added an extension to the Http class to automatically retrieve Keycloak tokens

### PR DESCRIPTION
**Pull request by jsight**

### CODE REVIEW

**Comment by ssilvert** [comment]
Hi Jessee.  Thanks for the PR.  I haven't looked at this in detail yet, but I assume this is mostly (all?) refactoring?  Please open a KEYCLOAK jira to explain your changes and then link this PR to it.  Also, inside the new pom you created I saw some versions in the dependency section.  We need to get those out so that it relies on a dependencyManagement.  Otherwise, we won't find the versions when we update.

**Comment by jsight** [comment]
The POM change is there by mistake. Maybe the .gitignore should be setup to ignore that file?

JIRA: https://issues.jboss.org/browse/KEYCLOAK-3610

**Comment by ssilvert** [comment]
I tried to build and run this.  I got some warnings when I did npm install about peer requirements.  I think that specifically, the rxjs problem is causing your code to not compile with tsc.

C:\GitHub\keycloak\examples\demo-template\angular2-product-app\src\main\webapp>npm install

> angular2-product-app@1.0.0 postinstall C:\GitHub\keycloak\examples\demo-template\angular2-product-app\src\main\webapp
> typings install

typings WARN deprecated 9/28/2016: "registry:dt/node#6.0.0+20160909174046" is deprecated (updated, replaced or removed)
typings WARN deprecated 9/14/2016: "registry:dt/core-js#0.0.0+20160725163759" is deprecated (updated, replaced or removed)

+-- core-js (global)
+-- jasmine (global)
`-- node (global)

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN angular2@2.0.0-beta.3 requires a peer of es6-promise@^3.0.2 but none was installed.
npm WARN angular2@2.0.0-beta.3 requires a peer of reflect-metadata@0.1.2 but none was installed.
npm WARN angular2@2.0.0-beta.3 requires a peer of rxjs@5.0.0-beta.0 but none was installed.
npm WARN angular2@2.0.0-beta.3 requires a peer of zone.js@0.5.11 but none was installed.
npm WARN angular2-product-app@1.0.0 No description
npm WARN angular2-product-app@1.0.0 No repository field.

C:\GitHub\keycloak\examples\demo-template\angular2-product-app\src\main\webapp>npm run tsc

> angular2-product-app@1.0.0 tsc C:\GitHub\keycloak\examples\demo-template\angular2-product-app\src\main\webapp
> tsc

app/keycloak.http.ts(27,61): error TS2339: Property 'fromPromise' does not exist on type 'typeof Observable'.
app/keycloak.http.ts(48,14): error TS2339: Property 'merge' does not exist on type 'typeof Observable'.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "tsc"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-product-app@1.0.0 tsc: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular2-product-app@1.0.0 tsc script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-product-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-product-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-product-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\GitHub\keycloak\examples\demo-template\angular2-product-app\src\main\webapp\npm-debug.log

**Comment by jsight** [comment]
@ssilvert At least one of those problems is because I was importing a version of Rxjs that doesn't have the fromPromise operator.

I'm not sure how you are getting messages related to "angular2@2.0.0-beta.3". Perhaps you aren't working from the latest master?

**Comment by ssilvert** [comment]
My build problems are gone now, but the demo isn't showing the products.

Please fix the conflict and verify that the demo is still working.  Thanks.

**Comment by jsight** [comment]
Ok, fixed. :)

**Comment by ssilvert** [comment]
It's still not loading the products for me.  I log in as bburke@redhat.com.  I see the word "Products", but there is no list of products.  I click the "Reload" button and nothing happens.  This app used to show some products.  Is it working for you?

**Comment by jsight** [comment]
Yes

**Comment by ssilvert** [comment]
In the console, I get:

"EXCEPTION: Response with status: 401 Unauthorized for URL: http://localhost:8080/database/products"

**Pull request merged**
