### PR TITLE
Remove testing groups in CI to limit concurrent jobs

### LINKED ISSUE #9927: Improve CI setup
### Description

Yesterday we observed enormous delays and queuing of GH Action pipelines.

The underlying issue was probably network hiccups, still, it took more than 6 hours to recover (timing out most of the queued jobs).

The current setup is optimized for CI speed but is clogging the available concurrent runners.
in the "testing phase", after the build of the distribution, we count 7 independent jobs + 12 matrix jobs, given that the available runners on a Free plan are 20 ( [ref](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits) ) it means that this project CI is (on average) serving 1/2 PRs concurrently, queuing all the rest of the jobs.

I think that an acceptable compromise is to slow the CI down by removing one axis from the matrix build but allowing more PR CIs to progress concurrently.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andreaTP**
We are currently completely flooding the GH Action runners, this PR should reduce the number of concurrent jobs and, eventually, leave more bandwidth to effectively run the checks for all of the PRs.

cc. @hmlnarik since looks like this matrix was introduced by you.

### CODE REVIEW

**Comment by andreaTP** [comment]
The current Queue has 13 Workflows waiting (some since more than 6 hours) and only 4 in-progress.
This change removes 8 workflows from each run (from 12 down to 4).

**Comment by hmlnarik** [comment]
Please introduce GH issue and provide analysis of expected savings before filing a PR.

According to the previous successful builds, preparation before running each test group takes 2-3 minutes, most of the time is spent in the tests. It seems that this PR expects saving of 8x 2-3 minutes of total running time at the cost of getting the results in longer total time, correct? For example, in the case of wildfly from [this run](https://github.com/keycloak/keycloak/runs/5017567536?check_suite_focus=true), the results would be available in appx 2 + 43 + 46 + 41 = 132 rather than max(2+43, 2+46, 2+41) = 48 minutes - is this calculation correct?

Side note: The Build phase should terminate in not half an hour without and ~ 15 minutes with a cached maven repository. In this PR, it is already over 90 minutes and counting, and there are builds in the queue with build phase running [for over 5 hours](https://github.com/keycloak/keycloak/actions/runs/1778576218). Today does not seem to be a representative day for GitHub Actions performance.

**Comment by andreaTP** [comment]
> In this PR, it is already over 90 minutes and counting

That's exactly the problem, the job got queued for a crazy amount of time(e.g. hours) and the same is happening to most PRs.
Tomorrow I'll follow up with the formalities.
If this is just a symptom of GH Actions problems I'm happy to close this one!
I'll be happy to explore alternatives!

Thanks for the review and insights @hmlnarik !

**Comment by hmlnarik** [comment]
> That's exactly the problem, the job got queued for a crazy amount of time(e.g. hours) and the same is happening to most PRs. 

The job is not _queued_ but _running_ for over 90 minutes. Feel free to check the console to validate

**Comment by andreaTP** [comment]
> The job is not queued but running for over 140 minutes. Feel free to check the console to validate

Confirm, it was a network hiccup.

> Please introduce GH issue and provide analysis of expected savings before filing a PR.

This PR resolves #9927 that, I believe, is still valid.
No issues in closing both issue and PR if the current behaviour is acceptable.

**Review by hmlnarik — CHANGES_REQUESTED** [review]
I don't believe this PR really helps to mitigate the problem, the gain is too low for the cost. Let's take step back and discuss the right approach on the original issue #9927.

**Comment by andreaTP** [comment]
@hmlnarik let's discuss on the issue, I move back this PR to draft but I let the CI run to(hopefully) have numbers to compare.

**Review by stianst — CHANGES_REQUESTED** [review]
I don't see how this helps at all. Sure, it may mean we have more PRs running in parallel, but that doesn't mean the waiting time for completion will be shorter. What I think the result of merging this will be:

* No real difference when there's loads of contention
* Longer total running time when there isn't contention

**Comment by andreaTP** [comment]
This PR was opened aiming to try this approach out, evaluate the results and iterate, since we are not confident experimenting in this direction I close it. 👍

**Pull request closed without merging**
