### PR TITLE
Improve message for failing partial import of realm

### LINKED ISSUE #28017: Un-friendly error message for Fail Import option in keycloak GUI
### Description

Need improvement in error message in the attached screen.

Step1:
Go to Realm settings -> click Action -> choose Partial export -> change Include groups and roles, Include clients to On -> click Export button -> realm json file is generated -> OK

Screen Shot 2024-03-18 at 12 24 07 PM

Step 2. 
Go to Realm settings -> click Action -> choose Partial import -> click Browse button -> choose realm json file is generated in the step 1 -> Choose all the resources you want to import

Step3: 
If pick ‘If a resource already exists, specify what should be done’ field = “Fail import” value -> click Import button

 Actual : Display error message as below: ‘ Import failed: HTTP 500 Internal Server Error’
 
Screen Shot 2024-03-18 at 12 24 52 PM

### Discussion

_No response_

### Motivation

Better excpetion/alert message gives us more clarity of what the issue instead of a generic message.

### Details

_No response_

### PR DESCRIPTION
**Pull request by keshavprashantdeshpande**
Closes #28017

### CODE REVIEW

**Comment by keshavprashantdeshpande** [comment]
The problem was the exception which was thrown was from other class but the one which is caught was from other class.
To be more specific services/ErrorResponseException was thrown but partialimport/ErrorResponseException was caught.

My idea is we can remove the partialimport/ErrorResponseException as we do not use it explicitly other than this place. Let me know what you guys think.

**Review by ahus1 — COMMENTED** [review]
Thank you for this change! Removing the exception is the right thing to do. 
By using the other exception, this is now a RuntimeException and you wouldn't need to declare it on each method body. 

I also found that `return error.getResponse();` in `RealmAdminResource` was problematic as instead of throwing the exception, it returned a response directly. This leads to a situation where all changes are committed instead of rolled back. 

To catch any other exception, we should instead rely on the `KeycloakErrorHandler` and its standardized handling. So I was able to simplify this even more. 

Let me know if this look good to you, and then we can proceed with merging this. Thanks!

**Comment by keshavprashantdeshpande** [comment]
@ahus1 Thanks you for the changes and information! We can proceed with the merge!

**Comment by ahus1** [comment]
This is how an error message looks now: 

image

**Comment by ahus1** [comment]
@mhajas - as I've contributed to this change, can you please review my changes before we merge this? Thanks!

**Review by mhajas — APPROVED** [review]
Thank you for the contribution @keshavprashantdeshpande and @ahus1! LGTM

**Pull request merged**
