### PR TITLE
Add scope parameter to admin-client TokenManager.

### LINKED ISSUE #11032: Possibility to add scope to admin-client TokenManager
### Description

**Describe the feature**

When using the admin-client with TokenManager it is not possible to set the scope for the token request. See https://github.com/keycloak/keycloak/discussions/10759.

Version
999-SNAPSHOT

Expected behavior

It would be good to allow the scope to be set for the token manager, so that the admin-client can request a scoped token, rather then only the default scopes for that client.

### Discussion

https://github.com/keycloak/keycloak/discussions/10759

### Motivation

When the scope can be added to the token manager request for access token the user of the admin-client can create different instances for the same keycloak client with different scopes to it.

This would make the access token smaller.

### Details

The token of an admin-client is to large, when using the "roles"-mapper.

### PR DESCRIPTION
**Pull request by mteubner**
Add scope parameter to admin-client TokenManager.

Closes https://github.com/keycloak/keycloak/discussions/10759

Closes #11032

### CODE REVIEW

**Comment by mteubner** [comment]
@pedroigor Hi, could you have a look if this is something that would make sense, and if so give me a comment on that. I merged it against your new changes.

**Review by pedroigor — COMMENTED** [review]
Thanks.

Could you please provide a test here https://github.com/keycloak/keycloak/blob/d27635fb1b2cf6c411902357cd6fbad7498d102b/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminClientTest.java?

Perhaps you can look at the access token returned by the server and see if the claims/scope are there as expected.

**Comment by mteubner** [comment]
@pedroigor Do you think the test is sufficient?

**Comment by pedroigor** [comment]
@mteubner Thanks, it is.

**Comment by mteubner** [comment]
Sorry that I pulled you in on that Request, but I saw you changed something on the client as the last person. ;)

What would be the next step to promote this featrue?

**Review by pedroigor — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@mteubner I think I merged too fast ... I missed the issue and the commit properly updated referencing the issue :)

**Comment by mteubner** [comment]
The issue in the pipeline is not exclusive to this branch it also happends in most of the other pull-requests currently. So, I don't think it is due to the changes of this branch.

What do you mean be properly update the referencing? Shall I do something here?

**Comment by pedroigor** [comment]
Yes, it is not related. 

I meant I should have asked you to create an issue and update the commit message (and squash to a single one). But now is late :) Sorry.

**Comment by pedroigor** [comment]
@mteubner Please ... Then I'll update to include the project/milestone.

**Comment by mteubner** [comment]
I created an enhancement task https://github.com/keycloak/keycloak/issues/11032

**Pull request merged**
