### PR TITLE
Don't show client policies tab when feature is disabled

### LINKED ISSUE #19510: Client Policy tab causes 501 if the client policy feature is disabled
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

If the client policy feature is disabled, clicking on "Client policies" tab in "Realm settings" in the admin UI, a 501 is triggered and causes the error "Feature not enabled".

### Version

20.0.5

### Expected behavior

The tab shouldn't be there

### Actual behavior

The tab is there

### How to Reproduce?

Disable client policies feature. Go to the admin UI and click on client policies

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bplotnick-humane**
It triggers a 501 when clicked if the feature is disabled. This gates the tab behind the feature check.

Closes https://github.com/keycloak/keycloak/issues/19510

### CODE REVIEW

**Comment by ssilvert** [comment]
@bplotnick-humane This needs an issue associated with it.

**Comment by bplotnick-humane** [comment]
> @bplotnick-humane This needs an issue associated with it.

done

**Review by jonkoops — DISMISSED** [review]

**Comment by jonkoops** [comment]
Thanks for creating a fix for this @bplotnick-humane. I'll let the tests run, if they pass the PR should merge automatically.

**Review by jonkoops — APPROVED** [review]

**Review by jonkoops — CHANGES_REQUESTED** [review]
Looks like this change breaks some existing tests on CI, can you take a look @bplotnick-humane?

**Comment by ssilvert** [comment]
@bplotnick-humane I think this code doesn't work?  Since `client-policies` is enabled by default, it is not included in the array for enabledFeatures.

I created another PR for this: https://github.com/keycloak/keycloak/pull/19558

**Pull request closed without merging**
