### PR TITLE
KEYCLOAK-5191 Prevent exception in KeycloakAuthenticationFailureHandler

### PR DESCRIPTION
**Pull request by scranen**
Maybe the second commit is overly defensive?

### CODE REVIEW

**Comment by sebastienblanc** [comment]
Is there any testcase that could be added or updated to test this ?

**Comment by scranen** [comment]
I wondered the same thing, but couldn't find anything yet. Maybe I missed something? If there is no test, then I think we should create a unit test based on `AbstractJUnitSpringContextTests` that spins up a `MockMvc` with the default settings and tests a couple of scenarios. I could work on that, but not sure how long that'll take me. Perhaps it should be a separate ticket, too, since it would test a lot more than just this fix.

**Comment by scranen** [comment]
Can we merge this as-is?

**Comment by sebastienblanc** [comment]
@scranen Do you thing your PR will also resolve https://issues.jboss.org/browse/KEYCLOAK-5195 ?

**Comment by scranen** [comment]
I don't think so. The exception described in that ticket is not treated as an authentication failure, so it wouldn't pass through the code that's modified in this PR.

**Comment by sebastienblanc** [comment]
@stianst this can be merged

**Pull request merged**
