### PR TITLE
KEYCLOAK-20343 Add message bundle to export/import

### LINKED ISSUE #20343: message bundles are not  included in the realm export
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

import-export

### Describe the bug

When exporting and importing an realm, the created message bundles are not take one to the new realm.

### Version

21.1.1

### Expected behavior

That the message bundles are also an part of the export/import.

### Actual behavior

After the import the bundles are missing.

### How to Reproduce?

1. create an realm
2. add message bundles
3. export the realm
4. On an second instance import the json file from the export.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Todor13**
Closes #20343

Add message bundle to export/import.

Add test check in ExportImportUtil.assertDataImportedInRealm which is called during testDirFullExportImport, testDirRealmExportImport and testSingleFileRealmWithoutBuiltinsImport.

### CODE REVIEW

**Review by pedroigor — APPROVED** [review]

**Review by vramik — CHANGES_REQUESTED** [review]
Changes LGTM, there are 2 checks repeatedly canceled, it needs to be investigated whether it's caused by this PR.

**Comment by ahus1** [comment]
I'm triggering a rebase to trigger another build.

**Comment by ahus1** [comment]
Hm, the GitHub UI doesn't allow me to rebase it. I have to think of something different then.

**Comment by ahus1** [comment]
@vramik - looking at the last three logs that timed out, they stalled at "ZeroDowntimeTest", so I assume it is a reproducible pattern here. Can you investigate this, or would you need another pair of eyes on this?

**Comment by ahus1** [comment]
@Todor13  - looking at the last three logs that timed out, they stalled at "ZeroDowntimeTest", so I assume it is a reproducible pattern here. Can you investigate this, or would you need another pair of eyes on this?

// cc: @vramik

**Comment by Todor13** [comment]
> @Todor13 - looking at the last three logs that timed out, they stalled at "ZeroDowntimeTest", so I assume it is a reproducible pattern here. Can you investigate this, or would you need another pair of eyes on this?
> 
> // cc: @vramik

@ahus1 I am on it, however another pair of eyes would be appreciated.

**Comment by vramik** [comment]
I was investigating the cause of the issue. The problem is the [test](https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/HOW-TO-RUN.md#zero-downtime-tests) is written in a way that it imports data to legacy container: https://github.com/keycloak/keycloak/blob/82b1f2bb5a3f6135146215b08012598b56dbfb69/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/zerodowntime/ZeroDowntimeTest.java#L126-L138

Legacy container then deserializes `InputStream` to `RealmRepresentation` using `JsonSerialization` class: https://github.com/keycloak/keycloak/blob/82b1f2bb5a3f6135146215b08012598b56dbfb69/model/map/src/main/java/org/keycloak/models/map/datastore/MapExportImportManager.java#L495

and as the PR adds a new field `"localizationTexts"` to `RealmRepresentation` it fails with 

```java
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "localizationTexts" (class org.keycloak.representations.idm.RealmRepresentation), not marked as ignorable (136 known properties: "userFederationMappers", "rememberMe", "duplicateEmailsAllowed", "adminEventsDetailsEnabled", "users", "clientOfflineSessionMaxLifespan", "webAuthnPolicyRequireResidentKey", "webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister", "components", "otpPolicyType", "accessCodeLifespanUserAction", "id", "webAuthnPolicyAttestationConveyancePreference", "enabledEventTypes", "applications", "webAuthnPolicyPasswordlessSignatureAlgorithms", "eventsListeners", "ssoSessionMaxLifespanRememberMe", "defaultDefaultClientScopes", "webAuthnPolicyPasswordlessCreateTimeout", "clientOfflineSessionIdleTimeout", "notBefore", "publicKey", "smtpServer", "clientPolicies", "resetPasswordAllowed", "webAuthnPolicyAvoidSameAuthenticatorRegister", "accessTokenLifespanForImplicitFlow", "webAuthnPolicyPasswordlessUserVerificationRequirement", "clientScopes", "internationalizationEnabled", "defaultRole", "accessTokenLifespan", "passwordCredentialGrantAllowed", "federatedUsers", "applicationScopeMappings" [truncated]])
 at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 1, column: 2363] (through reference chain: org.keycloak.representations.idm.RealmRepresentation["localizationTexts"])
```

One option would be to add `mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);` to https://github.com/keycloak/keycloak/blob/82b1f2bb5a3f6135146215b08012598b56dbfb69/core/src/main/java/org/keycloak/util/JsonSerialization.java#L44-L45
so the unrecognized field would be ignored.

@ahus1 @pedroigor wdyt?

**Comment by pedroigor** [comment]
@vramik For me, disabling that flag is not a good thing and is not really what is causing the issue.

Looks like that test should also take into account the representation schema for a specific version?

**Comment by vramik** [comment]
Thanks @pedroigor. 

I'm not sure tbh. The test should verify that two versions of keycloak (say `n` and `n+1`) are able to co-exist in the cluster at the same time with capability to downgrade to lower version if needed. If an export from version `n+1` would be done, the file would contain the `"localizationTexts"` field, then after downgrade it wouldn't be possible to import such a file. The same applies when using `adminClient`.

Could you please elaborate on why it wouldn't be good to disable the flag?

Regarding representation schema: it relates to https://github.com/keycloak/keycloak/issues/13626 which should solve these types of issues.

**Comment by vramik** [comment]
To unblock this, we've decided to disable the failing test: https://github.com/keycloak/keycloak/issues/21823 and adjust the mechanism when importing using map store. Once https://github.com/keycloak/keycloak/issues/21823 is resolved, then rebase to main should unblock this PR

**Review by ahus1 — APPROVED** [review]
Approving as of @vramik's review. The handling for zero-downtime upgrades will be handled in a separate PR.

**Review by vramik — APPROVED** [review]
Approving, leaving up to a maintainer to decide whether we need to have passed GHA (that'd require a rebase) or not.

@Todor13 thank you for the contribution!

**Comment by Todor13** [comment]
I am happy to see the re-try mechanism as it makes the export/import between versions flexible.

@ahus1 I tried the rebase GitHub web API and it worked on my side.

@vramik I am happy to contribute. Looking forward to doing it again!

**Pull request merged**
