### PR TITLE
KEYCLOAK-4591, add support for a wget --no-check-certificate behavior

### PR DESCRIPTION
**Pull request by starksm64**

### CODE REVIEW

**Comment by stianst** [comment]
We already have ways to disable the truststore and hostname verification in the adapter. With disable-trust-manager and allow-any-hostname (see https://keycloak.gitbooks.io/securing-client-applications-guide/content/topics/oidc/java/java-adapter-config.html) for more details. The authorization client should probably rather obtain the correctly configured HttpClient from the adapter instead of creating its own. This can be done with KeycloakDeployment.getClient.

@pedroigor can you comment on this please?

**Comment by starksm64** [comment]
This is not in the client adaptor, but a direct use of the keycloak-authz-client library to obtain a bearer token from the keycloak server. The org.keycloak.authorization.client.Configuration object that parses the keycloak.json in that library certainly does not have disable-trust-manager and allow-any-hostname fields in it, but I can use those instead to support this behavior.

**Comment by stianst** [comment]
Would be better if the authz client had a way to set the http client and when used from within a client adapter it would just get the correctly configured client from the deployment. We have a bunch of other options in keycloak.json for the http client as well.

**Comment by stianst** [comment]
@pedroigor Does the client use the httpclient from the KeycloakDeployment when it's used from within one of our adapters? If so I think we can just close this. If it's used outside our adapters then the http client should be configured and injected separately.

**Comment by stianst** [comment]
Update from Pedro. It uses HttpClient from KeycloakDeployment, which allows configuring through keycloak.json. If used outside Keycloak adapter you can pass your own HttpClient.

Closing this PR.

**Pull request closed without merging**
