### PR TITLE
Extract LocaleSelectorSPI to allow custom overrides of locale selection

### PR DESCRIPTION
**Pull request by knutz3n**

### CODE REVIEW

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
@knutz3n Thanks! Looks good to me. 

Waiting a bit before merge in case that @stianst or @ssilvert has an additional feedback.

**Comment by mposolda** [comment]
@knutz3n one more thing, we may need a documentation for this.

**Comment by knutz3n** [comment]
@mposolda I tried to find relevant documentation, but I couldn't find any section related to specific SPIs or Locale selection. Do you have a hint on where you think I should document this SPI?

**Comment by mposolda** [comment]
@knutz3n There is something here in the admin guide: https://www.keycloak.org/docs/4.3/server_admin/#internationalization and also here in the development guide: https://www.keycloak.org/docs/4.3/server_development/#internationalization . It seems this LocaleSelector suits better to the Server Developer guide, so the existing section could be probably somehow updated?

**Comment by mposolda** [comment]
@knutz3n How is it looking with the docs? We have some pending bugs regarding to localization and we're waiting until this can be merged (no avoid conflicts etc).

**Comment by knutz3n** [comment]
@mposolda Sorry the late reply. I have created a suggestion: https://github.com/keycloak/keycloak-documentation/pull/469/.
Ended up creating a separate section for the Locale Selector to align it with the Theme Selector section. Any input on the suggested documentation is very welcome.

**Comment by mposolda** [comment]
@knutz3n Thanks!

**Pull request merged**
