### PR TITLE
KEYCLOAK-7055: Avoid setting realm not before policy on logout all

### PR DESCRIPTION
**Pull request by knutz3n**

### CODE REVIEW

**Comment by stianst** [comment]
Logout all is intended to logout everything including offline sessions. Otherwise there is no way for an admin to logout also offline sessions.

Looks like it doesn't clear the sessions on the server side though, which it really should do.

With regards to being able to only logout non-offline sessions that is probably something we should add. We could probably add another button for logout only non-offline sessions.

@mposolda can you comment on this please?

**Comment by stianst** [comment]
Another improvement that could be made here is that instead of calling logout on all clients we could just push the update not before to all clients. That would be much more efficient if there are many clients.

For only logging-out non-offline maybe we should add a separate not-before on the realm for offline sessions?

**Comment by mposolda** [comment]
I will try to start discussion on keycloak-dev regarding this. Just a quick comment, that this PR probably can't be simply merged as is due the fact that there is no other way how to logout offline sessions. Currently notBefore ensure that there is at least some (indirect) way to "invalidate" offline sessions (even if they are not properly cleared on Keycloak server side).

**Comment by knutz3n** [comment]
@mposolda Thanks for the clarification. I guess this issue should rather be closed and a new bug should be created regarding missing invalidation of the offline sessions. Please also add a confirmation dialog in the admin GUI for this. It is easy to push the button by mistake and invalidation of offline sessions could make a huge impact which is hard to reverse the effect of.
I will follow the discussion on the keycloak-dev list.

**Comment by mposolda** [comment]
I've started a thread on keycloak-dev for this. See http://lists.jboss.org/pipermail/keycloak-dev/2018-June/date.html and the thread "Improve "Logout all" for the realm?" (It's not yet in the archive when I am writing this, but hopefully should appear soon)

**Comment by mposolda** [comment]
I am closing PR as it can't be used anyway as is. We can continue discussion on keycloak-dev mailing list: http://lists.jboss.org/pipermail/keycloak-dev/2018-June/010907.html

**Pull request closed without merging**
