### PR TITLE
Add missing space

### LINKED ISSUE #30417: Keycloak 25 db guide shows unevaluated "ifeval
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

Fix the website on https://www.keycloak.org/server/db showing some asciidoc related ifeval text

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The evals should be evaluated

### Actual behavior

It is not evaluated due to missing line breaks.

### How to Reproduce?

Look at the docs.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by wimdeblauwe**
Fix the website on https://www.keycloak.org/server/db showing some asciidoc related `ifeval` text

Closes #30417

### CODE REVIEW

**Comment by mhajas** [comment]
@wimdeblauwe Thank you for the fix! Could you please signoff your commit? https://github.com/keycloak/keycloak/pull/30394/checks?check_run_id=26165830605

**Comment by ahus1** [comment]
@wimdeblauwe did you try to render it locally? As ifeval is a block preprocessor element it needs to be on the start of a new line, so we might be missing a newline instead?

**Review by stianst — DISMISSED** [review]

**Comment by wimdeblauwe** [comment]
I did not render it locally. I have never build Keycloak or the documentation. I just saw the wrong text on the website and thought I might be able to create my smallest PR ever :) Would be good if somebody could validate that it really fixes the problem.

**Comment by vmuzikar** [comment]
I did build it locally and can confirm the problem still persists, as hinted by @ahus1.

**Comment by ahus1** [comment]
I've pushed another commit, and also linked this to an issue so we can better backport it to KC25. 

See below a screenshot of the newly rendered text.

image

**Comment by ahus1** [comment]
@vmuzikar - please review when you have the time. Thanks!

**Review by vmuzikar — APPROVED** [review]
@ahus1 @wimdeblauwe LGTM, thank you.

**Pull request merged**
