### PR TITLE
Marking nested classes in brokering endpoints as static

### LINKED ISSUE #15443: Marking nested classes in brokering endpoints as static
Resteasy Reactive requires that JAX-RS resources defined as nested classes are marked as `static`.

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #15443

### CODE REVIEW

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
LGTM Curious why RestEasy Reactive requires this, do you know?

**Review by mabartos — APPROVED** [review]
@pedroigor Thanks!

**Comment by stianst** [comment]
@pedroigor this will also have an impact on folks creating custom identity providers (and other things?), so we should include some stuff around it in migration/realease notes.

**Comment by pedroigor** [comment]
@stianst Because it fails to properly scan/discover JAX-RS resources if they are non-static nested classes (inner classes). We get a build error.

**Pull request merged**
