### PR TITLE
Validate name of client scope

### PR DESCRIPTION
**Pull request by lexcao**
https://github.com/keycloak/keycloak/issues/12553

### CODE REVIEW

**Comment by lexcao** [comment]
Hi @mposolda 
Could you please help with this?

**Comment by mposolda** [comment]
@lexcao Thanks for the PR! Could you please rebase this PR to latest main branch and add the automated test? I think ClientScopeTest might be good candidate.

**Comment by lexcao** [comment]
@mposolda  Thanks for your suggestion. 
Tests are added.

**Review by mposolda — APPROVED** [review]
@lexcao Thanks!

**Pull request merged**
