### PR TITLE
[KEYCLOAK-9772] Permissions are duplicated

### PR DESCRIPTION
**Pull request by nicholas-fwang**
- when resource server is current user

[KEYCLOAK-9772](https://issues.jboss.org/browse/KEYCLOAK-9772)

### CODE REVIEW

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Review by pedroigor — APPROVED** [review]
Thanks @fisache. Let's wait now CI status.

**Comment by fisache** [comment]
@pedroigor Thanks for review.
Can I know why jenkins ci failed?

**Comment by pedroigor** [comment]
It is an internal resource. But it is not related with your changes. I'll start a new build.

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Pull request merged**
