### PR TITLE
doc: add keycloak cr truststores

### LINKED ISSUE #27892: Truststore handling for the Operator is not documented
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

KC24 introduced adding truststores via the CR, and this is documented in the release notes. 

It seems that this is missing in the regular Keycloak docs, so people won't be able to find it. 

Also the documentation of the CR as shown in OpenShift is very minimal, and doesn't show what to put into that "object" ("Details" is missing).

image

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Documentation on https://www.keycloak.org/operator/advanced-configuration on how to use truststores. 

### Actual behavior

Documentation exists only in the release notes.

### How to Reproduce?

Search for "truststores:" in all `*.adoc` files in the project

### Anything else?

This would be a candidate for a KC24 backport. 

cc: @vmuzikar, @shawkins

### PR DESCRIPTION
**Pull request by shawkins**
closes: #27892

After #28013 we can remove the duplicate name from the example.

We can of course consider these prs for backport as well.

### CODE REVIEW

**Review by mabartos — COMMENTED** [review]
@shawkins LGTM and I think it's sufficient (would be good to double-check with @vmuzikar and @Pepo48 ). But as you've mentioned, I'd wait for the https://github.com/keycloak/keycloak/pull/28013 and remove the name from docs.

**Comment by shawkins** [comment]
> I'd wait for the https://github.com/keycloak/keycloak/pull/28013 and remove the name from docs.

Updated based upon that.

**Review by mabartos — DISMISSED** [review]
@shawkins Thanks, LGTM. @vmuzikar @Pepo48 Are you ok with it?

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@shawkins Thanks for the PR!

I'd be probably good to add some note that we trust default K8s CA.

**Comment by shawkins** [comment]
> I'd be probably good to add some note that we trust default K8s CA.

Ok, added a blurb about that.

**Review by Pepo48 — APPROVED** [review]
LGTM, thanks @shawkins.

**Review by abstractj — APPROVED** [review]

**Review by mabartos — APPROVED** [review]

**Review by vmuzikar — APPROVED** [review]

**Comment by vmuzikar** [comment]
@shawkins Can you please create a backport?

**Comment by shawkins** [comment]
@vmuzikar https://github.com/keycloak/keycloak/pull/28168

**Pull request merged**
