### PR TITLE
Add empty Georgian translation for Weblate

### PR DESCRIPTION
**Pull request by NorwayFun**
Initial 'adding empty files for themes' commit.

### CODE REVIEW

**Comment by jonkoops** [comment]
Thanks for starting a PR to add translations. I think you should hold off until the translation is ready or your PR will be out here quite a while, feel free to open up a PR once you have the translations ready. We also require another native speaker to review any contributions, so keep that in mind thanks!

**Comment by jonkoops** [comment]
Re-opening as per https://github.com/keycloak/keycloak/discussions/9270#discussioncomment-9444549, wasn't aware of the previous discussion around this apologies.

**Comment by jonkoops** [comment]
@NorwayFun could you [sign off](https://github.com/keycloak/keycloak/pull/29559/checks?check_run_id=24995731800) on your commit?

**Review by ahus1 — CHANGES_REQUESTED** [review]
I see that this is adding the language to `theme.properties`, which would make the translation show up in Keycloak already, although it is incomplete. 

I'd rather revert those changes, and instead only keep the `messages_ka.properties` files which are required for Weblate to do the job. 

In addition to this, please create GitHub issue first as outlined in the `CONTRIBUTING.md` and reference this in the commit. This allows us to track the conversation around this. Thanks!

**Comment by NorwayFun** [comment]
> @NorwayFun - I updated this PR to remove the `theme.properties` as agreed in the discussion.
> 
> The new `messages_ka.properties` are now only present in the `resources-community`, I removed them from the `resources` folder.
> 
> To clarify: Which themes do you plan to translate - all of Keycloak? Only some themes? This PR now contains 3 themes out of the total 6 themes.
> 
> image

Ineresting..  cloned whole repo and searched for .properties files in themes dir and made _ka files for every file.
Is there anything else? Lets make it for everything, I'll translate at least minimal amount of strings in every file so build will not fail.

**Review by ahus1 — APPROVED** [review]

**Review by jonkoops — APPROVED** [review]
Looking good

**Comment by ahus1** [comment]
@NorwayFun - as this PR is now merged, Georgian now appeared as a language in Weblate. 

For translations in Keycloak, it is common practice that a second native speaker reviews translations. This helps to ensure the quality of the translation, and we have a similar practice for code changes. 

For incremental translations in Weblate, this would usually be the maintainer of a language. As this is the initial translation, and you are the maintainer of that language, I ask you to find yourself a second person who is a native speaker. 

That person would then either review the translations in Weblate, or review the translated files in the Keycloak repository the moment before we add the Georgian language code to the `theme.properties` files - this is up for the two of you to decide. 

Please let me know if you think this can work, if you see obstacles and if you would like someone to help you with that. Thanks!

**Comment by NorwayFun** [comment]
> @NorwayFun - as this PR is now merged, Georgian now appeared as a language in Weblate.
> 
> For translations in Keycloak, it is common practice that a second native speaker reviews translations. This helps to ensure the quality of the translation, and we have a similar practice for code changes.
> 
> For incremental translations in Weblate, this would usually be the maintainer of a language. As this is the initial translation, and you are the maintainer of that language, I ask you to find yourself a second person who is a native speaker.
> 
> That person would then either review the translations in Weblate, or review the translated files in the Keycloak repository the moment before we add the Georgian language code to the `theme.properties` files - this is up for the two of you to decide.
> 
> Please let me know if you think this can work, if you see obstacles and if you would like someone to help you with that. Thanks!

Hi!
მადლობა! Thank you!
Me and my friend are in the middle of translating LibreOffice now. After finishing it (And man it's taking a lot) I'll try to convince her to do proofreading for me. Most likely we'll reach for you to assign her as proofreader.

**Comment by ahus1** [comment]
Great, let's proceed as you describe. There is also the Keycloak user mailing list, and you might find a volunteer there to help with a review.

**Comment by NorwayFun** [comment]
@ahus1 I think support can already be added. There is only bigger one left to be translated, but if sync process from weblate is automated, it makes no sense to wait until I'll finish it (3k strings with 160k chars are no joke :) )

About volunteers/contributors, good luck finding even one :)

Anything else is needed to be done from my side, other than continuing translation, please?

**Comment by ahus1** [comment]
I see that all components except for the Admin UI are now translated one the next PR #30044 is merged - see the image below.

So I'd say we're good to add the Georgian language to all themes except for the Admin UI. When doing this, all these translations need to be reviewed by a second native speaker. Do you have a friend or partner who can do this? You could also consider looking for other Georgian users on the Keycloak Users mailing list. When creating that PR, you should also update the `translation.md` file and add the Georgian language to the list of languages managed in Weblate.

image

**Pull request merged**
