### PR TITLE
KEYCLOAK-9611 Add support to the testsuite for migration from 4.8.3

### PR DESCRIPTION
**Pull request by vramik**

### CODE REVIEW

**Comment by hmlnarik** [comment]
@keycloak-ci-bot test

**Comment by vramik** [comment]
@keycloak-ci-bot test

**Comment by vramik** [comment]
@keycloak-ci-bot test

**Comment by vramik** [comment]
@keycloak-ci-bot test

**Comment by vramik** [comment]
@keycloak-ci-bot test

**Review by pdrozd — APPROVED** [review]

**Pull request merged**
