### PR TITLE
Adding Brazilian Portuguese, Greek and Persian labels for login/messages/messages_en.properties

### LINKED ISSUE #28201: Locale label missing on login page for Brazilian Portuguese, Greek and Persian
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

translations

### Describe the bug

In `themes/src/main/resources/theme/base/login/messages/messages_en.properties` the messages for el, fa and pt-BR do not show up.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The language picker shows the name of the language.
(Like in the admin panel)

### Actual behavior

The language picker shows the language code.
grafik

### How to Reproduce?

1. Create new realm
2. Enable internationalization
3. Select Greek, Brazilian Portuguese and Persion

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sulthan309**
Adding Brazilian Portuguese, Greek and Persian labels for login/messages/messages_en.properties.

closes #28201 

Screenshot after the changes:

image

### CODE REVIEW

**Review by ssilvert — APPROVED** [review]
LGTM

**Comment by ahus1** [comment]
@ssilvert / @sulthan309 - There is a PR https://github.com/keycloak/keycloak/pull/29125 which removes the need to add those entries in the first place. This PR should be merged within the next days, and then this change would be obsolete.

So I suggest to put this PR on hold for now, and close it once the other PR is merged and provides the functionality you are looking for.

**Comment by ahus1** [comment]
The PR #29125 has been merged, and the changes will be available in KC25. 

The changes of this PR would still be valid for KC24, so I changed this PR to now be a change against KC24.
One thing I see missing here is the "Sign-off" line for the commit as outlined in the `CONTRIBUTOR.md` file. 

Please add it, and then this PR is ready to be merged.

**Comment by jonkoops** [comment]
We require that PRs that update localizations are reviewed by another native speaker. Since it is hard to keep track of each locale in a review, I'd recommend you split your PR up into separate ones per locale.

**Pull request closed without merging**
