### PR TITLE
Client Policies fixes and default FAPI profile (KEYCLOAK-18280 Issues with boolean properties of executors, enable client policies by default)

### PR DESCRIPTION
**Pull request by mposolda**

### CODE REVIEW

**Comment by mposolda** [comment]
@vmuzikar @tnorimat Do you please have a chance to review this?

**Review by tnorimat — DISMISSED** [review]
LGTM.

**Review by vmuzikar — COMMENTED** [review]
I ran into this issue when writing UI tests. :)

Looks good to me, but I wonder whether we should add the same fix for conditions as well. I know conditions currently don't use any boolean properties but it may change and more over admins can add custom conditions.

**Comment by mposolda** [comment]
@vmuzikar Thanks, I will do for conditions as well.

**Comment by mposolda** [comment]
@vmuzikar Thanks for the review. Since you already reviewed the other 2 PRs, which I've sent, I've added the commits from those 2 PRs https://github.com/keycloak/keycloak/pull/8101 , https://github.com/keycloak/keycloak/pull/8091  into this one and I will close the other ones.

The reason is, that pull requests are partially dependent on each other. And there is big chance, that when the 3 pull requests would be merged independently one-by-one, each of them might pass, but together they will very likely break Keycloak master. Also consider that we do not have much time...

**Comment by vmuzikar** [comment]
@mposolda Makes sense. So maybe we should also include #8107 as it strongly depends on these changes as well.

**Review by vmuzikar — COMMENTED** [review]
@mposolda Forgot to reply to the changes around global profile being present in the JSON view. I wouldn't personally do it as it kinda implies it's something editable whereas it's not. But since we don't have time to make changes anymore, let's leave it.

**Review by vmuzikar — APPROVED** [review]
LGTM (if the tests pass), thanks!

**Comment by mposolda** [comment]
@vmuzikar Thanks!

**Pull request merged**
