### PR TITLE
KEYCLOAK-9598 Apache Tomcat adapter

### PR DESCRIPTION
**Pull request by vramik**

### CODE REVIEW

**Comment by stianst** [comment]
If there are no changes why don't we just mark 8 with both 8 and 9 rather than add yet another noackage and zip?

**Comment by vramik** [comment]
In my opinion it's a bit strange when you install something called tomca8-adapter to tomcat9 application server, another way how to solve this would be to remove the specific version from the package and have just tomcat-adapter and tomcat7-adapter, where tomcat-adapter would be used for both tomcat8 and tomcat9. Another option which I like the least is to create a note in documentation that tomcat8 adapter is meant to be used with tomcat9.

**Comment by stianst** [comment]
Can you start a thread on mailing list around this? I'd go for the renaming to tomcat-adapter approach as it makes it consistent with WF approach.

**Comment by vramik** [comment]
https://keycloak-jenkins.com/job/keycloak-deploy-only/13/
https://keycloak-jenkins.com/job/universal-test-pipeline-server/158/
https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/255/

**Review by hmlnarik — APPROVED** [review]
Thanks @vramik!

**Pull request merged**
