### PR TITLE
KEYCLOAK-14103 Add Warn message for possibly missing SameSite configu…

### PR DESCRIPTION
**Pull request by mhajas**
…ration

### CODE REVIEW

**Review by vmuzikar — CHANGES_REQUESTED** [review]
Thanks @mhajas, good work, I like it! Just a few questions.

Have you tried to run the adapter test pipeline, just to be sure it didn't break anything.?

What are the changes in keystores for Jboss app servers? Were they necessary?

I'm wondering, should we add SSL support for Jetty too?

**Comment by mhajas** [comment]
Thanks for the review @vmuzikar. 

> Have you tried to run the adapter test pipeline, just to be sure it didn't break anything.?
No, but I will need to do it, there are still some failed tests even in base testsuite. It is probably because of changes in keystores.

> What are the changes in keystores for Jboss app servers? Were they necessary?
We are using `nip.io` for SameSiteTest, and we need to run it with TLS configured on the app-server side. Therefore I needed to add a subject alternative name (`app-saml-127-0-0-1.nip.io`) to `adapter.jks`. Also, I needed to add the changed certificate to `keycloak.truststore`.

**Comment by mhajas** [comment]
@vmuzikar Now the Travis passed, however, it is somehow stuck with orange colour. When you open it, it is green

**Comment by vmuzikar** [comment]
@mhajas Ok, thanks. What about the test pipeline? Does it make sense to run it?

**Review by vmuzikar — APPROVED** [review]
Just for the record, test runs provided by @mhajas:
https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/1455/
https://keycloak-jenkins.com/job/universal-test-pipeline-server/1865/

LGTM, thanks!

**Review by hmlnarik — APPROVED** [review]
Approving based on @vmuzikar 's review

**Pull request merged**
