### PR TITLE
Admin console tests for client scopes - Fixes and new tests

### PR DESCRIPTION
**Pull request by mposolda**
KEYCLOAK-7584 Fix some admin console tests broken by adding clientScopes
KEYCLOAK-8174 Admin console test for the "Client Scopes" tab of the client

### CODE REVIEW

**Comment by mposolda** [comment]
@pdrozd @vmuzikar I've fixed the admin console tests and also added some new tests for the "Client Scopes" tab of the Client (Not yet for the main "Client Scope" tab on the left side). I've used 2 commits - one for fixing some failing previous tests and another for the new tests. Is it ok or do you want separate PRs?

NOTE: I've fixed just some failing tests caused by the clientScopes changes. There are still some failing admin console tests, which are not related to clientScopes (mostly related to RequiredActions and TermsAndConditions)

**Review by vmuzikar — APPROVED** [review]
@mposolda Thanks a lot for fixing tests that were broken by Client Scopes and also for adding a few more! I can confirm the tests are passing with all supported browsers (even with the IE) - good job!! :)

**Comment by mposolda** [comment]
@vmuzikar Thanks!

**Review by pdrozd — APPROVED** [review]
based on vmuzikar's feedback

**Pull request merged**
