### PR TITLE
Issue #8749: Add an option to control the order of the event query and admin event query

### LINKED ISSUE #8749: Add an option to control the order of the event query and admin event query
### Description

To implement a event processing SPI, we would like to get a page of events ordered by ascending value of the field "time". 
Currently it is hard coded, that the events are ordered by descending time. 
We would like to implement an option at "EventQuery" / "JpaEventQuery" and "AdminEventQuery" / "JpaAdminEventQuery" to control the order behaviour.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by leischt**
Closes #8749

### CODE REVIEW

**Comment by hmlnarik** [comment]
@leischt Thank you for the PR. The test failures seem relevant. Have you checked those?

**Comment by sschu** [comment]
@hmlnarik I added timestamps for the events similarly how it is done in other tests.

**Comment by hmlnarik** [comment]
Thank you @sschu, the code after update looks good. Could you please check the model test failures in legacy-jpa profiles though?
Please update the commit messages and squash the commits, `keycloak#10656` is not related to this PR.

**Comment by sschu** [comment]
@hmlnarik Sorry for the delay, I stumbled across a really nasty bug not setting the realm as expected when creating events using the `AdminEventBuilder`. That led to events not properly cleaned up after tests and led to some longer debugging sessions. But the respective tests are green now locally, so I hope the CI agrees.

Btw. do you have any idea why this test here: https://github.com/keycloak/keycloak/blob/aec8e6af509af1aa83b3049edf38763a3b000e7c/testsuite/model/src/test/java/org/keycloak/testsuite/model/events/AdminEventQueryTest.java#L78-#L100
has to be broken up into two `withRealm` sections? If I put everything int he same section, the assertion fails since all four events are found instead of two (at least when using the MapStorageProvider).

**Comment by sschu** [comment]
@hmlnarik The failing test is `AccountRestServiceWithUserProfileTest>AccountRestServiceTest.listApplicationsThirdParty:966 expected:<[]> but was:<[web-origins]>`, probably not related.

**Comment by sschu** [comment]
@hmlnarik Now everything is green (except code check, but that seems to always fail currently).

**Review by hmlnarik — APPROVED** [review]
Thank you for the PR!

**Comment by hmlnarik** [comment]
> Btw. do you have any idea why this test here: https://github.com/keycloak/keycloak/blob/aec8e6af509af1aa83b3049edf38763a3b000e7c/testsuite/model/src/test/java/org/keycloak/testsuite/model/events/AdminEventQueryTest.java#L78-#L100
> has to be broken up into two `withRealm` sections? If I put everything int he same section, the assertion fails since all four events are found instead of two (at least when using the MapStorageProvider).

I am sad to hear this had crossed the development of your tests.

Does this happen for e.g. `map-jpa` or only for `map` profile? If the latter, this might be because the `ConcurrentHashMap` implementation of the `MapKeycloakTransaction` is relaxed in this regard: https://github.com/keycloak/keycloak/blob/1d2d3e5ca526a558ac7b320d290e5455c470133f/model/map/src/main/java/org/keycloak/models/map/storage/chm/ConcurrentHashMapKeycloakTransaction.java#L187-L199
This has been a conscious decision for this development storage - to avoid implementing tricky merging results coming from the underlying store with those from the current transaction. In the server code it does not hurt since the request processing either writes or reads the same data in a transaction, not both at the same time. For the tests, the right way would be exactly the way you did with splitting the transaction. In fact, such merging will be only implemented properly in the tree store (#9742).

**Comment by sschu** [comment]
@hmlnarik Indeed, it only happens on `map`, not on `map-jpa`. So I assume in the future I will consider tests on `map` primarily?

**Pull request merged**
