### PR TITLE
changed to use `ConfiguredProvider` instead

### LINKED ISSUE #15344: Support configurable custom Identity Providers
### Description

Identity Providers are not using `ConfiguredProvider`, but rather something bespoke, resulting in the ability to make configurable custom identity providers without extending the admin console.

The old admin console (somewhat of a hack) supported adding a custom template for configuring custom providers, but this is not supported in the new admin console, resulting in it not being possible to create custom identity providers and make them configurable through the new admin console.

We will have to refactor identity providers to be `ConfiguredProviders` and also update the new admin console to support configuring them like it does for other `ConfiguredProviders`.

This will have to be done prior to removing the old admin console, as otherwise we have lost functionality in the new admin console.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #15344

### CODE REVIEW

**Review by jonkoops — CHANGES_REQUESTED** [review]
The messages returned from the Java code should be localized, so that community translations can be added.

**Review by michalkutrzeba-odrabiamy — APPROVED** [review]

**Comment by edewit** [comment]
@jonkoops I don't know but it seems that this is an issue for all these properties

**Comment by jonkoops** [comment]
We can still localize these ones right? It's okay not this fix this now, but then we should log an issue so this is not forgotten.

**Review by ssilvert — APPROVED** [review]

**Comment by edewit** [comment]
added issue: #21179

**Pull request merged**
