### PR TITLE
Push oss-fuzz fuzzers to Keycloak repository

### LINKED ISSUE #22547: Create a new maven module for oss-fuzz fuzzing
### Description

OSS-Fuzz has recently integrated Keycloak and start fuzzing on the Keycloak code repository. This issue proposes a new fuzzing module in the Keycloak project root to store all fuzzers and related files in the keycloak project and also include them in the project build process.

### Discussion

_No response_

### Motivation

Currently Keycloak is integrated into OSS-Fuzz and has its fuzzers in the CNCF-Fuzzing repository: https://github.com/cncf/cncf-fuzzing/tree/main/projects/keycloak. These fuzzers should exist in the Keycloak repository so that the Keycloak project can maintain them and avoid breakages without having to make PRs to third-party repositories.

### Details

We should:
Move the fuzzers from CNCF-Fuzzing to the Keycloak repository.
Move the build infrastructure from CNCF-Fuzzing to Keycloak repository.
Set up OSS-Fuzz so that it builds the fuzzers from the Keycloak repository instead of CNCF-Fuzzing.

### PR DESCRIPTION
**Pull request by arthurscchan**
I have recently integrated Keycloak into OSS-Fuzz and have been adding fuzzers for Keycloak to the cncf-fuzzing repository. Currently OSS-Fuzz pulls the fuzzers from there to build and run them.
In this PR I move the fuzzers upstream to Keycloaks own repository so the Keycloak team has full control over the fuzzers and the OSS-Fuzz integration.

This PR does three things:
1. It adds a fuzzing module for flexibility.
2. It moves a big part of the fuzzers over from cncf-fuzzing (https://github.com/cncf/cncf-fuzzing/tree/main/projects/keycloak)
3. It adds a few seed files and dictionaries which help the fuzzers when OSS-Fuzz runs them.

This PR provide features for #22547.

### CODE REVIEW

**Comment by abstractj** [comment]
Thanks, @arthurscchan! I think it's okay to keep those fuzzers in the cncf-fuzzing repository for collaboration. I'm not sure what other @keycloak/maintainers think. Do you see any issues with it?

**Comment by ahus1** [comment]
My 2 cents: before accepting it into the main repository, I'd like to know who would maintain this added code. That team / group of people would need to have the knowledge and the time to do that.

**Comment by vmuzikar** [comment]
+1 for keeping it in the CNCF repository and not including it in the Keycloak repository, at least for now. I'm concerned about ownership and maintenance cost as well.

**Comment by stianst** [comment]
As mentioned by others we're not going to add this to our repository at least not for the time being, as we are not responsible for maintaining these fuzzers.

**Pull request closed without merging**
