### PR TITLE
Increasing the number of io threads for testing so that a single server can be used without blocking

### LINKED ISSUE #15152: Investigate test failures in GHA after upgrading Quarkus to 2.13.x version
### Description

This task is a follow-up on https://github.com/keycloak/keycloak/issues/15151 to investigate why we are facing test failures on GHA after upgrading to Quarkus 2.13 series.

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #15152

### CODE REVIEW

**Review by abstractj — DISMISSED** [review]

**Review by ahus1 — COMMENTED** [review]
Thanks for this change, the test results are really promising. 

I tried to reproduce it locally with a pool size set to 1, still I wasn't able to reproduce it locally. Has someone been able to record a full thread dump that shows the deadlock? 

Doing some debugging, I found that `context.next();` in the `QuarkusRequestFilter` creates some executions on the event loop, so this approach makes sense to me. Still I wonder how big the pool should be compared to the executor pool that has a size of 20.

Setting this value for the tests makes now the tests pass. How would we handle a setup were in a Kubernetes environment Quarkus sees only a single CPU (for example via a CPU limit) - would we need to handle that as well?

**Comment by stianst** [comment]
Shouldn't we make this configuration change on the real distribution rather than only in the tests?

**Comment by hmlnarik** [comment]
Thank you @pedroigor, great investigation done!

> Shouldn't we make this configuration change on the real distribution rather than only in the tests?

I agree. Could we have lower bound for the `quarkus.vertx.event-loops-pool-size` property, say 4, and set it to 4 if its value (or the number of CPUs) is lower than that?

**Comment by mposolda** [comment]
I think increasing pool will help with our testsuite, which use single user (WebDriver). But I am wondering if it is sufficient for avoid deadlocks for other cases in production? For example assume scenario like this:
- The pool size is 4
- There are 4 concurrent HTTP requests from 4 different users, who want to login to realm `consumer` .
- All 4 requests want to send "background" HTTP request to realm `provider` around the same time at some stage of IDP login/logout. Now it won't be possible to open new request to `consumer` realm due the fact there are already 4 HTTP requests in progress. So effectively deadlock. 

Is this scenario possible or not? Just something to consider, but feel free to ignore my comment if this scenario is not possible. For example I recall undertow has 2 types of pools (workers and IO) and it seems quarkus/vert.x has something similar, but in theory, it can be also worker thread-pool, which can be full in some situations like this...

**Comment by pedroigor** [comment]
Fixed by https://github.com/keycloak/keycloak/pull/15193

**Pull request closed without merging**
