### PR TITLE
[KEYCLOAK-19830] Update Quarkus distribution dependencies

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Review by pedroigor — APPROVED** [review]
@abstractj Thanks!

**Comment by thomasdarimont** [comment]
Just notices that the latest stable version of infinispan is 13.0.2.Final -> https://infinispan.org/download/
Any particular reason why we need to use 13.0.0.Final? Is this not compatible with Quarkus 2.4.2.Final?

**Comment by DGuhr** [comment]
@abstractj @pedroigor @thomasdarimont As timing wants it, latest quarkus final (which I just check locally and want to create a PR for today) also uses inifinispan 13.0.0 - see [here](https://github.com/quarkusio/quarkus/blob/2.5.0.Final/bom/application/pom.xml#L130) so I'll remove the explicit version for infinispan, as we want to rely as much as we can on the versions quarkus provides.

@thomasdarimont  having said the above, when there are good reasons to update to a version even newer than the one used in quarkus, we can for sure make exceptions (as we did here), but in general it may be a good idea to stick with the quarkus bom dependency versions imo, to be sure everything is "supported" by the underlying quarkus distribution. The update circle of quarkus is currently only a few weeks, so I expect to have 13.0.2 in kind of fast.

**Comment by abstractj** [comment]
@thomasdarimont the intention of this change was to keep the Infinispan version aligned with the same one used on Quarkus.

**Comment by thomasdarimont** [comment]
@abstractj It looks like as infinispan 13.0.2 contains some fixes for potential resource leaks (ISPN-13439 Result Set is not closed, ISPN-13400 HybridQuery.executeStatement does not close a CloseableIte...) the rest seems to be minor changes like  documentation and test fixes 
See: https://github.com/infinispan/infinispan/compare/13.0.0.Final...13.0.2.Final

**Pull request merged**
