### PR TITLE
KEYCLOAK-6056 Map user by Subject Alternative Name (otherName) when a…

### PR DESCRIPTION
**Pull request by mposolda**
…uthenticating user with X509

### CODE REVIEW

**Comment by mposolda** [comment]
Documentation PR: https://github.com/keycloak/keycloak-documentation/pull/601

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Pull request merged**
