### PR TITLE
Search Identity Providers by alias or display name

### LINKED ISSUE #32588: Search Identity Providers by alias or display name
### Description

Users in account console see Identity Provider display name (if exists).
Moreover, alias is not always user friendly.

Propose for `SEARCH `option in `JpaIdentityProviderStorageProvider` to search in alias or in display name.
This will affect search of Identity Providers both in admin console and new linked account console.

### Discussion

_No response_

### Motivation

[Comment in linked account console pagination](https://github.com/keycloak/keycloak/issues/21261#issuecomment-2324738233)

### Details

_No response_

### PR DESCRIPTION
**Pull request by cgeorgilakis**
Closes #32588

### CODE REVIEW

**Comment by ahus1** [comment]
Pinging @keycloak/core-iam as this might be interesting for the organisations feature as well as you plan to support a lot of IDPs now.

**Comment by sguilhen** [comment]
Thanks @ahus1  - would you be able to re-run the CI for this PR? The changes look good to me

**Review by sguilhen — APPROVED** [review]
Overall looks good to me. Let's see if the CI errors are transient - operator will prob pass when we re-run the test, but the account UI test failure is a bit odd

**Review by ahus1 — APPROVED** [review]
Approving based on @sguilhen's review

**Pull request merged**
