### PR TITLE
KEYCLOAK-17400: allow installed adapter to be reused

### PR DESCRIPTION
**Pull request by jeffmaury**
Also add a close method to stop callback if response has not been received yet

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Review by pedroigor — COMMENTED** [review]
@jeffmaury Thanks.

Your proposal is to allow people to override `getDesktopProvider` with their own `DesktopProvider` implementation?

And the `callback` only changed to allow forcing a call to stop the underlying server?

**Comment by jeffmaury** [comment]
> 
> 
> @jeffmaury Thanks.
> 
> Your proposal is to allow people to override `getDesktopProvider` with their own `DesktopProvider` implementation?
> 
> And the `callback` only changed to allow forcing a call to stop the underlying server?

Yes

**Review by pedroigor — COMMENTED** [review]
I see, thanks. I would avoid instantiating `DesktopProvider` every time though and just add a new constructor that accepts the `DesktopProvider`. The default constructor is going to call this new constructor passing a new instance. People that need to provide their own `DesktopProvider` can just do the same thing in subclasses.

The `getDesktopProvider` method would be unnecessary too.

**Comment by jeffmaury** [comment]
Yes, see my last commit

**Review by pedroigor — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
