### PR TITLE
Fix for empty realm name issue during api update

### LINKED ISSUE #17449: Removing the Realm ID and saving causes the realm to be vanished from the list of the realms
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Create a relam.
Then select it.
Then go to its general settings.
Remove the field content for the `Realm ID` field.
Then save.
The form is saved (which should not, because `Realm ID` is a required field), and the relam gets vanished from the realm list.

I don't know if it's removed from the database or not.

### Version

20.0.2

### Expected behavior

These are expected:

- Required field should become red as soon as it gets invalid
- Form should not submit while it has an invalid field
- Or if it submits, backend code should not accept that form
- A realm that has no id should be shown in the realms list, with an **Undefined ID** tag for example

### Actual behavior

- Required field does not show any UI/UX feedback when it becomes invalid (when it's empty and dirty)
- Form submits even when it has invalid fields
- Backend code does not check the validity of the form
- A realm without ID would be not shown in the relams list

### How to Reproduce?

- Create a relam.
- Then select it.
- Then go to its general settings.
- Remove the field content for the `Realm ID` field.
- Then save.
- The form is saved (which should not, because `Realm ID` is a required field), and the relam gets vanished from the realm list.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by atharvakshi**
Added a check to ignore renaming if it is an empty string.

Closes #17449

### CODE REVIEW

**Review by ahus1 — COMMENTED** [review]
Thank you @atharvakshi for this PR. I reviewed it and pushed one more commit. 

Looking at the tests in `RealmTest` and the code, there is already functionality to prevent creating a realm with an invalid character or renaming it in such a way. So I removed your changes related to that. 

I also update the tests to verify the new behavior that empty realm names can't be created or renamed. 

The name of the realm is validated with `validate(name)` in other places already, therefore I didn't see the need to expose the existing patterns and use a different pattern to validate the name of the realm. This allowed me to keep the encapsulation of the patterns. 

The `ReservedCharException` extends already `BadRequestException`, so there is no need to catch it, as it will be converted automatically to a `400` return code. 

Please have a look at the changes, and let me know in a comment if you're ok with them. Thanks!

**Comment by atharvakshi** [comment]
@ahus1 Thank you for reviewing and adding tests, the changes make sense and are more DRY-er. I wanted to check the realm name for following characters too - "{", "}", and "%" because that is what breaks the UX especially "%" at beginning of the name according to #15848

**Comment by ahus1** [comment]
@atharvakshi - I assume preventing more characters would need some additional discussion, including possibly a migration strategy and/or release notes. Let's fix one issue at a time. This issue description on GitHub didn't reference the other issue, so I missed it. 

I'll update this PR to squash the commits, and then ask another Keycloak team member to review it.

**Comment by atharvakshi** [comment]
@ahus1 Understood, sounds good!

**Review by martin-kanis — APPROVED** [review]
@atharvakshi @ahus1 Looks good, thank you!

**Review by ahus1 — APPROVED** [review]
approving as of @martin-kanis review

**Pull request merged**
