### PR TITLE
[KEYCLOAK-9646] Increase import range for javax.servlet API to cover …

### PR DESCRIPTION
**Pull request by grgrzybek**
…EAP 7.2, servlet-api 4.0

### CODE REVIEW

**Review by mposolda — DISMISSED** [review]
@grgrzybek PR looks fine to me, Thanks! Adding also @hmlnarik as reviewer of the PR. I've executed our internal testsuite, but not sure if fuse tests are part of it. Will doublecheck it...

**Comment by mposolda** [comment]
@grgrzybek It seems that we don't test Fuse adapter by default in our testsuite. If you have an opportunity to test with the current Fuse version based on these instructions https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md#run-the-fuse-adapter-tests it will be nice.

I suppose this PR doesn't break the older Fuse, just rather asking to confirm :) Thanks!

**Comment by grgrzybek** [comment]
I try contacting @hmlnarik but he seems to be on PTO.
servlet-api is quite good in terms of backward compatibility and I already used such increased range (`[3.1,5)`) in Camel, CXF, Karaf and pax-web without issues.

My PR changes only one POM (adapters/oidc/undertow) - but ideally all bundles having import on javax.servlet packages should have increased range.

**Comment by grgrzybek** [comment]
@mposolda I'll test it on Monday.

**Comment by grgrzybek** [comment]
OK, I:
* need wider Import-Package range for few more bundles
* after talking to @mposolda, I run all the tests for Fuse 7.1.1 (7.1.1.fuse-711005-redhat-00001)
```
# prepare the container
mvn -f testsuite/integration-arquillian/servers/pom.xml clean install -Papp-server-fuse7x -Dfuse7x.version=7.1.1.fuse-711005-redhat-00001 -Dapp.server.karaf.update.config=true -Dmaven.local.settings=$HOME/.m2/settings.xml -Dmaven.repo.local=$HOME/.m2/repository -Drepositories=,http://download.eng.bos.redhat.com/brewroot/repos/sso-7.1-build/latest/maven
# run tests
mvn -f testsuite/integration-arquillian/tests/base/pom.xml clean test -Papp-server-fuse7x -Dtest=Fuse*AdapterTest -Dauth.server.ssl.required=false
```
* 2 tests for 7.3.0 fail
```
Failed tests: 
  FuseExampleAdapterTest.testProductPortal:155 
Expected: a string containing "401: Unauthorized"
     but: was "Product with ID 1 - unsecured request (it should end with failure): Can't receive product. Reason: Could not find wsdl:binding operation info for web method getProduct."
Tests in error: 
  FuseAdminAdapterTest.hawtio2LoginTest:155 » NoSuchElement {"errorMessage":"Una...
```

`hawtio2LoginTest` failure may be related to some changes in hawtio, but I'm not sure about the first one.

**Comment by stianst** [comment]
This is probably something we'll need backported to RH-SSO 7.3 so it can support new Fuse

**Comment by grgrzybek** [comment]
it'd be great @stianst

**Comment by grgrzybek** [comment]
I'm closing this PR in favor of #5935. Please check the comments under https://issues.jboss.org/browse/KEYCLOAK-9646.

**Pull request closed without merging**
