### PR TITLE
Fix confusing SAML NameId mapper format tooltip

### LINKED ISSUE #26051: Name ID Format field is confusing for User Attribute Mapper For NameID
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

There is a SAML mapper named: `User Attribute Mapper For NameID`. The purpose of this mapper is to set the value of the `NameID` element in assertions produced by Keycloak.

For the mapper, it is possible to configure `Name ID Format`. The tooltip for this says: [Name ID Format using Mapper
](https://github.com/keycloak/keycloak/blob/70e15bdaa49a8babc5dd76882ca5c66462e548fe/js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties#L496)

This isn't very clear because users may think this mapper also changes `NameID.Format` of the resulting assertion while this field is used to filter when the mapper should be applied: [only if the `AuthnRequest`'s `NameIDPolicy` is equal to the value of this field](https://github.com/keycloak/keycloak/blob/70e15bdaa49a8babc5dd76882ca5c66462e548fe/services/src/main/java/org/keycloak/protocol/saml/SamlProtocol.java#L614C5-L614C5).

### Example of how the mapper works:
There are two nameId mappers:
1. `mapper.nameid.format = email, user.attribute = custom_email_attribute`
2. `mapper.nameid.format = unspecified, user.attribute = another_custom_attribute`

Then we have a user:
`Username: testUsername, custom_email_attribute = test@username.com, another_custom_attribute = foo`

#### Scenario 1
The client sends an authentication request with following NameId policy:
`<samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" />`

in this case:
Keycloak sees that the client expects a response with `emailAddress` NameID format. When responding it will query all `NameIdMappers` and find out there is mapper number 1. with the mapper.nameid.format equal to `emailAddress`. Therefore it applies the mapper by obtaining the custom_email_address:
`<saml:NameID  Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">test@username.com</saml:NameID>`

#### Scenario 2 
The client sends an authentication request with the following NameId policy:
`<samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified" />`

In this case Keycloak uses mapper 2 with the result:
`<saml:NameID  Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">foo</saml:NameID>`

#### Scenario 3
If another NameIdPolicy is sent, for example: `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent` no mapper is applied because there is no mapper for such format present.

Also, the field `Name ID Format` lists NameID formats even when they are not supported by Keycloak and `AuthnRequest`s with other formats are refused. Maybe we should not list those there?
https://github.com/keycloak/keycloak/blob/70e15bdaa49a8babc5dd76882ca5c66462e548fe/services/src/main/java/org/keycloak/protocol/saml/SamlService.java#L470-L477

### Version

main

### Expected behavior

The tooltip should better explain this

### Actual behavior

The tooltip says only: Name ID Format using Mapper

### How to Reproduce?

1. Open the admin console and go to Client Scope
2. Create a new Client Scope with Protocol `SAML`
3. Open the Client Scope -> Mappers
4. Configure a new mapper -> User Attribute Mapper For NameID
5. You should see the following page: 
image

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mhajas**
Closes #26051
Signed-off-by: Michal Hajas <mhajas@redhat.com>

The list of NameId formats was updated based on the following condition:
https://github.com/keycloak/keycloak/blob/70e15bdaa49a8babc5dd76882ca5c66462e548fe/services/src/main/java/org/keycloak/protocol/saml/SamlService.java#L523-L524

### CODE REVIEW

**Comment by mhajas** [comment]
@rmartinc Could you please have a look?

**Review by rmartinc — APPROVED** [review]
Thanks  @mhajas! LGTM!

**Comment by mhajas** [comment]
Thank you @rmartinc!

@hmlnarik Could you please review on behalf of the UI team and merge if you approve?

**Review by jonkoops — DISMISSED** [review]

**Review by hmlnarik — COMMENTED** [review]
@mhajas Does this mapper need any migration?

**Comment by mhajas** [comment]
Per offline discussion with @hmlnarik I updated the PR with the release notes update.

**Review by hmlnarik — DISMISSED** [review]

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
