### PR TITLE
Switches the merging logic to using the override as the basis

### LINKED ISSUE #10503: Revisit Pod-Template in Keycloak CR
This is a follow-up from #10098.

The current approach has several severe downsides:
* It is done by [explicitly merging every field](https://github.com/keycloak/keycloak/blob/87b4ee41d42966f19e3a248e7d931cb55eccb795/operator/src/main/java/org/keycloak/operator/v2alpha1/KeycloakDeployment.java#L202-L349) that is very error-prone and hard to validate (a field could be easily missed and/or wrongly merged).
* The test coverage is incomplete, doesn't cover all fields.

To consider this issue resolved:
* Increase test coverage to include every field.
* If possible, merge the fields in a generic way (probably by using reflections).
* Consider removing Pod-Templates completely if not required anymore.

### PR DESCRIPTION
**Pull request by shawkins**
An alternative to the merging logic that uses the unsupported template as the basis for the template builder.  This cuts down a bit on the code and allows for anything new added to the pod template to be picked up automatically.  It does not address the concerns about how to merge the other lists, like ports, evn vars, volume mounts, etc.  Obviously it makes the base case of simply constructing the statefulset without the unsupported template a little harder to follow, but some minor reorganization helped with readability a bit.  It should be somewhat clear what prpoerties defer to the unsupported template.

The insertion ordering for the volume mounts was just done to line the logic up with an existing test.

The only thing that is somewhat different with what came before is that the template metadata labels from the operator are forcibly set over whatever is on the unsupported template. 

@vmuzikar please let me know if this is along the lines of what you are looking for and I'll add whatever additional tests seem relevant.

Of course the naming convention baseDeployment could change as well.

Closes #10503

### CODE REVIEW

**Review by vmuzikar — COMMENTED** [review]
@shawkins Sorry, didn't have time today for in-depth review today. But in general I'm happy with this approach, it's much cleaner and even existing tests pass!

> The only thing that is somewhat different with what came before is that the template metadata labels from the operator are forcibly set over whatever is on the unsupported template.

I think that's ok. It's in any case in the "unsupported" (a.k.a. best effort only) territory.

**Review by mabartos — COMMENTED** [review]
@shawkins Sorry, I won't be able to review it due to my PTO until 17.7.

 The code is much more readable and simplified; nice job, I like it!

**Comment by shawkins** [comment]
Made some minor refinements.  The only thing of note is to always set the image pull secrets from the cr - which seems consistent with the existing warning.

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@shawkins Thanks for the update. LGTM in general but I noticed we changed the order of how env vars are added to the final list. Before, we first added ours env vars (generated by the Operator) and then the user defined env vars from the podTemplate. Now (if I'm not mistaken) it's the other way around. AFAIK, if there are multiple occurrences of an env var with the same key, the last takes precedence. Therefore the user defined env vars need to come last to allow users to overwrite our env vars if needed. Could you also please add a test of it if possible?

**Comment by vmuzikar** [comment]
> Edit: based upon the warning I would expect that the template env variables would be of lowest priority. The user should use the first class option first, then additionalOptions, finally the template.

The warning doesn't mean it was correct in the first place. :) However, it's more about preventing user from using the generic additional options field over first class citizen. Not directly about env vars. The pod template field is IMHO something a bit different, though. It serves as sort of back door for workaround.

Let's say the Operator is setting some env vars that are based on either first class fields, additional options, or even some derived defaults that user didn't specify directly. What if the user needs to override some of the derived values for some reason? I know it's unsupported, undefined behaviour, they should eventually file an RFE but they should have the option to override what they need.

So from my perspective the order should be: pod template > first class fields > additional options.

> That's true for a post, but it's unfortunately a little more complicated than that with SSA. If there are multiple env in the patch with the same name, it will fail to validate. So yes the handling will need to be corrected to account for that. That would also be a bug in 22 / main - I can separate off a fix for that if need be.

Good point, we can fix that in 22.0.1.

**Comment by shawkins** [comment]
> So from my perspective the order should be: pod template > first class fields > additional options.

The pr has been updated to enforce this and ensure there won't ever be duplicate envvars.

> Good point, we can fix that in 22.0.1.

Would that be by pulling in this commit, or do you want a more targetted fix?

**Review by vmuzikar — APPROVED** [review]
@shawkins LGTM, thanks.

The logic for merging env vars from various different sources is a bit complex and hard to read (especially for someone who might not be too familiar with the code base). But it was similar case even before this PR and we can refactor later.

I believe this also solve a bug around how we treat env vars, so from my opinion this should be backported to 20.0.1. WDYT?

**Comment by shawkins** [comment]
> The logic for merging env vars from various different sources is a bit complex and hard to read (especially for someone who might not be too familiar with the code base). But it was similar case even before this PR and we can refactor later.

Yes unfortunately list merging is currently a little painful and a lot of logic is being triggered by the KeycloakDeployment constructor.  Moving forward we'll be moving the logic out of the constructor and will probably want to redo the dist config logic to return a map of env vars rather than working on the container directly.

> I believe this also solve a bug around how we treat env vars, so from my opinion this should be backported to 20.0.1. WDYT?

Yes it should target 22.0.1 as well.

**Comment by vmuzikar** [comment]
> Yes it should target 22.0.1 as well.

Can you please prepare the backport (similarly to e.g. https://github.com/keycloak/keycloak/issues/21607)?

**Comment by shawkins** [comment]
@vmuzikar opened #21711

**Pull request merged**
