### PR TITLE
KEYCLOAK-8100 Fix UsernameTemplateMapperTest

### PR DESCRIPTION
**Pull request by thomasdarimont**
Adapted UsernameTemplateMapperTest to changes in AbstractBaseBrokerTest.

### CODE REVIEW

**Comment by thomasdarimont** [comment]
@pedroigor thanks for merging the commit: 
https://github.com/keycloak/keycloak/commit/92ab9c08ae8594f531efb7ee4d6ca54ea7ed3ac9
However the current master does not compile since the `UsernameTemplateMapperTest` was not aware of the `IdentityProviderSyncMode`.

This PR fixes this.

**Comment by abstractj** [comment]
@pedroigor not sure if we need another Jira for this, assuming that https://issues.redhat.com/browse/KEYCLOAK-8100 was marked as resolved. It's up to you and @vmuzikar.

**Comment by vmuzikar** [comment]
I believe this actually duplicates #7178.

**Comment by vmuzikar** [comment]
@abstractj @pedroigor The JIRA for this is: https://issues.redhat.com/browse/KEYCLOAK-13206

**Comment by thomasdarimont** [comment]
@vmuzikar I rebased the PR and changed the commit to reflect to correct JIRA issue.

**Comment by thomasdarimont** [comment]
Just saw that there is #7178, both work for me. You can close this PR if you like.

**Comment by pedroigor** [comment]
Fixed by https://github.com/keycloak/keycloak/pull/7178

**Pull request closed without merging**
