### PR TITLE
[KEYCLOAK-14570] Feature/fix npe

### PR DESCRIPTION
**Pull request by ghost**
NullPointerException occurs when application uses the endpoint with URI:

`/auth/admin/realms/{realm}/authentication/config-description/{providerId} 
`
While body of response (representation) is being populated and iterating over properties of ProviderFactory may lead to NPE. Because of some ProviderFactory returns null instead EmptyList or whatever.

For example CookieAuthenticatorFactory, ConditionalUserConfiguredAuthenticatorFactory.

JIRA: https://issues.redhat.com/browse/KEYCLOAK-14570

### CODE REVIEW

**Review by mposolda — CHANGES_REQUESTED** [review]
@kurisumakise2011 Thanks for the pull request! The fix looks good.

However for the tests, we don't want to introduce mockito or stuff like that to our testsuite. Instead we prefer to focus on the integration testing. We already have class, which contains the tests for the authenticator configs. It is here https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/AuthenticatorConfigTest.java . So instead of adding mockito, can you please add the new test method to this class? Thanks!

**Comment by kurisumakise2011** [comment]
Hello, @mposolda I have changed recently, please have a look once again. Thanks.

**Comment by kurisumakise2011** [comment]
Hello, @mposolda any updates on that?

**Review by mposolda — APPROVED** [review]
@kurisumakise2011 Thanks and sorry for the delay in reviewing this.

**Pull request merged**
