### PR TITLE
Users in Role (federation) fixed

### LINKED ISSUE #19516: Users in role Rest API returns empty when User federation used.
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

Hi Team,

I have successfully implemented User Federation using an external REST API. Users are pulled from external services, and their extra information is stored in Keycloak. Everything is working well, except for the **Users In Role** tab, which appears empty when clicked. 

image

Upon inspection, I noticed that none of my custom user federation methods were called when clicked on this tab. I even attempted to use the admin API GET `/{realm}/clients/{id}/roles/{role-name}/users`, but received the same result.

I already assigned roles to the user and can see the same when clicking on user's **Role Mapping** tab.

When I don't use user-federation and directly add users in Keycloak then it works.

### Version

20.0.5, 21.0.2

### Expected behavior

It should return filtered users by role.

### Actual behavior

Empty response.

### How to Reproduce?

Create a custom user-storage provider and implement `UserStorageProvider, UserLookupProvider, UserQueryProvider` interfaces. 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shankaryadavy9**
Closes #19516

### CODE REVIEW

**Comment by ahus1** [comment]
Assigning this to @martin-kanis as you've been involved in the parent issue.

@shankaryadavy9 - I see you merged the main branch into this PR several times. There is usually no need to do that, as your PR will be rebased before it is being merged anyway. When there are conflicts with the main branch (and only then), you might need to rebase your PR and resolve any conflicts that exist. For now, please wait for a first review of your pull request.

**Comment by martin-kanis** [comment]
@shankaryadavy9 I looked into the testsuite and I created https://github.com/martin-kanis/keycloak/commit/59ef4b720b3afa94afc696f05cab38a18a2b6ca0 (I wasn't able to add it here as a commit). 
I also needed to change name of `getRoleMembersStream` method because otherwise, there was a clash with `UserQueryMethodsProvider#getRoleMembersStream` when I tried to implement both `UserRoleMappingsFederatedStorage, UserQueryProvider` interfaces.
Could you incorporate the test into this PR please?

**Comment by mhajas** [comment]
@martin-kanis I incorporated your suggestions to this PR, could you review it again?

**Comment by martin-kanis** [comment]
Sorry, I already created a new PR with added test https://github.com/keycloak/keycloak/pull/23318
I'm than closing this one in favor of the new one.

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Pull request closed without merging**
