### PR TITLE
Can't start Keycloak 22.0.3 on Windows

### LINKED ISSUE #23563: Can't start Keycloak 22.0.3 on Windows
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

I can't start Keycloak 22.0.3 on Windows 10. 
I also checked the latest nightly release, and the same problem happens.

```
Unrecognized option: -
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

I copied the `kc.bat` file from version 21.0.1, and it works successfully. 
It seems that something changed, and it broke the start process.

### Version

22.0.3

### Expected behavior

Successful start of Keycloak 22.0.3 via `kc.bat`.

### Actual behavior

Error during start of Keycloak 22.0.3 via `kc.bat`.

### How to Reproduce?

`bin\kc.bat start`

### Anything else?

I checked the latest changes to kc.bat. There I found a commit: [ "Removed lots of unnecessary quotes.."](https://github.com/keycloak/keycloak/commit/1c9992fdaeff9566fd8f734ec5fdbf82c7fb5720). Maybe not all of them are unnecessary. Because Windows commands fail when you call directory including spaces. We need quotes for these cases.
I am not sure whether this is the actual reason, but it may be one of the possible causes.

### PR DESCRIPTION
**Pull request by Pepo48**
* added necessary double quotes to kc.bat

Closes #23563

### CODE REVIEW

**Review by shawkins — APPROVED** [review]
LGTM

**Comment by Pepo48** [comment]
I realized that there is a long open PR https://github.com/keycloak/keycloak/pull/20212/ from @jsorah that fixes the same and closes https://github.com/keycloak/keycloak/issues/20115.

Joshua went a bit further with proposed changes, on the contrary, I provided the bare minimum to fix https://github.com/keycloak/keycloak/issues/23563 issue. The reason is that some time ago @sschu did [a cleanup](https://github.com/keycloak/keycloak/pull/16229), so I don't want to accidentally re-introduce anything that the original cleanup fixed.

Regardless, I'm fine with the Joshua's PR, I reviewed it multiple times and we were just waiting for a final confirmation from QE.

If there are no objections, I'm totally fine with merging his PR in favour of mine. 😊

**Comment by vmuzikar** [comment]
@Pepo48 +1 for continuing with the older PR https://github.com/keycloak/keycloak/pull/20212.

**Comment by vmuzikar** [comment]
Superseded by #20212.

**Pull request closed without merging**
