### PR TITLE
KEYCLOAK-9947 KEYCLOAK-10451 Better support for DB manual migration t…

### PR DESCRIPTION
**Pull request by mposolda**
…est with DB provided by docker or dballocator plugin

### CODE REVIEW

**Comment by mposolda** [comment]
@vramik @pdrozd Do you have a chance to review please? Will send the pipeline build in the other PR sent to the pipeline repo. Thanks

**Review by vramik — CHANGES_REQUESTED** [review]
Edit: the comment was meant for pipeline PR

**Review by vramik — DISMISSED** [review]

**Review by pdrozd — DISMISSED** [review]
Mostly based on @vramik review

**Review by vramik — APPROVED** [review]

**Review by pdrozd — APPROVED** [review]

**Comment by mposolda** [comment]
@vramik @pdrozd Thanks for the review!

**Pull request merged**
