### PR TITLE
KEYCLOAK-4544 Broker Login w/t "Create User If Unique" Step

### PR DESCRIPTION
**Pull request by diodfr**
Hi,
First of all, thank you for your work.
Like other users describe in the JIRA ticket, I use an Id provider and I want to restrict users by linking only on existing account.
That is why I control on the IdpAutoLinkAuthenticator class that the user exist and register it to the session.

Hope my contribution will help.
Didier

### CODE REVIEW

**Comment by mposolda** [comment]
@diodfr Thanks for your PR. It will be actually better if this is handled in the IdpCreateUserIfUniqueAuthenticator and there is an option on the authenticator like "Disable User Creation", which will be OFF by default. That will ensure that solution is not limited to the flow with IdpAutoLinkAuthenticator, but will work also in default FirstBrokerLogin flow where user is required to provide his password/email validation etc.

I would use something like suggested in this comment: https://issues.jboss.org/browse/KEYCLOAK-4544?focusedCommentId=13513040&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13513040

It will be also good to have test added and we may also need separate PR for the documentation (In keycloak-documentation repository).

**Review by mposolda — CHANGES_REQUESTED** [review]
@diodfr Thanks for your PR. It will be actually better if this is handled in the IdpCreateUserIfUniqueAuthenticator and there is an option on the authenticator like "Disable User Creation", which will be OFF by default. That will ensure that solution is not limited to the flow with IdpAutoLinkAuthenticator, but will work also in default FirstBrokerLogin flow where user is required to provide his password/email validation etc.

I would use something like suggested in this comment: https://issues.jboss.org/browse/KEYCLOAK-4544?focusedCommentId=13513040&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13513040

It will be also good to have test added and we may also need separate PR for the documentation (In keycloak-documentation repository).

**Comment by diodfr** [comment]
Hi @mposolda ,
Thanks you for your review.

My understanding is that there is two use cases:
1. you want to autorise the creation of the user if it does not exist.
2. you want the user to be present in your user base to enable access

As a user I would like this for each use case:
1. IdpCreateUserIfUniqueAuthenticator -> IdpAutoLinkAuthenticator
2. IdpAutoLinkAuthenticator (only)

I don't get your point about FirstBrokerLogin workflow. Could you explain me a little bit more ?

I would start to do the test (maybe I would need some help) and the documentation update as soon as I receive your answer.

Thanks again.
Didier

**Comment by mposolda** [comment]
@diodfr In addition, to the cases you mentioned, you have also the case when you don't want user to be auto-created in Keycloak, but at the same time, you want existing Keycloak user to re-authenticate in Keycloak. Re-authenticate means that user will need to confirm linking by email or by providing password. In other words, you don't want to use IdpAutoLinkAuthenticator at all.

The case when you want existing Keycloak user to re-authenticate in Keycloak is setup by default with the firstBrokerLogin and described here: https://www.keycloak.org/docs/latest/server_admin/index.html#default-first-login-flow .

It will be good if the PR supports this case as well. Hence will be nice to avoid any changes in IdpAutoLinkAuthenticator, but handle the scenario in IdpCreateUserIfUniqueAuthenticator in similar way as described in the mentioned JIRA comment: https://issues.jboss.org/browse/KEYCLOAK-4544?focusedCommentId=13513040&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13513040

**Comment by diodfr** [comment]
Hi @mposolda ,
As a user I find it strange that you will have an IdpCreateUserIfUniqueAuthenticator that does not create users and an IdpAutoLinkAuthenticator that needs an IdpCreateUserIfUniqueAuthenticator to work properly.
But never mind, I will do it the way you want to maintain it.
I will certainly ask for help on mailing list to test this because I don't know how I could do this.

Thanks for your time.
Didier

**Comment by mposolda** [comment]
@diodfr Thanks, I agree that name of the class IdpCreateUserIfUnique is a bit strange considering that it some environments it won't create users at all. But it will work with both the cases when you want to auto-link users and re-authenticate.

For testing, you can take a look at KcOidcBrokerTest and possibly add the new scenario with disabled user creation. One with disabled user creation and throwing error when user doesn't exists. Another with successful link to existing account.

**Comment by mposolda** [comment]
@diodfr Are you still working on this PR? The broker tests were re-structured a bit, so you may possibly add new tests to AbstractFirstBrokerLoginTest instead. Thanks

**Comment by stianst** [comment]
Closing this one as it is a bit of a mess. Feel free to re-open once it's been cleaned up.

**Comment by Queuecumber** [comment]
@stianst @mposolda 

I think there's a good case to be made for the `IdpAutoLinkAuthenticator` in that it solves the most common and simplest cases effectively. It's also better to have that than what you currently have: which is nothing. 

Putting this as a config in `IdpCreateUserIfUniqueAuthenticator` is also somewhat iffy. The class is called "CreateUserIfUnique" and you're asking for a setting that disables "User Creation" A user creation class that doesn't create users? At the very least I think you'd want to rename it. (I see now this was discussed already but the point still stands)

I think the right way to do this is to have two basic flows:

1. You want to allow social login with automatic creation of new users: use the `IdpCreateUserIfUniqueAuthenticator` and the default first login flow doesnt change

2. Social login but *dont* automatically create users: use `IdpAutoLinkAuthenticator` instead of `IdpCreateUserIfUniqueAuthenticator` (drop in replacement). Login will fail if there is no existing user

For option (2) you can either auto-link and conclude authentication *or* you can continue the flow in the same way as the default first login and make them verify ownership. The *only* thing that `IdpAutoLinkAuthenticator` would be doing in this case is setting the existing user so that the later step doesnt error out, or failing if there is no existing user. I think this covers all the user cases pointed out in the previous discussion.

Would you accept a new PR under these circumstances?

**Comment by garritschroeder0001** [comment]
This feature would be really appreciated.

**Comment by Hokwang** [comment]
this is needed!

**Comment by Hokwang** [comment]
I raise issue https://issues.redhat.com/browse/KEYCLOAK-15629 related this.
@mposolda can you see this issue?

**Comment by otgrkiss** [comment]
Any updates on this. This is needed.

**Comment by tulequ** [comment]
currently I use following snippet to temporary solve this problem
https://gist.github.com/tulequ/f0d810d7bfcf6cb5db3bba5aad07b7cd

```
1. User Must Exists --> ALTERNATIVE
2. Automatically Set Existing User --> ALTERNATIVE
```

This code is based on "Create User If Unique"

**Pull request closed without merging**
