### PR TITLE
Check credential confirmation on server side.

### PR DESCRIPTION
**Pull request by ssilvert**

### CODE REVIEW

**Comment by ssilvert** [comment]
Accidentally left this out of the larger PR.

**Comment by stianst** [comment]
The confirmation shouldn't be sent/checked on the server side. That's for the client to do if it wants to.

**Review by stianst — COMMENTED** [review]
The confirmation shouldn't be sent/checked on the server side. That's for the client to do if it wants to.

**Comment by ssilvert** [comment]
I did this because you didn't want me to @JsonIgnore the confirmation param.  So now, if the param is sent, I check it for you.  If it is not set, the API doesn't complain.

**Comment by ssilvert** [comment]
Also, I'll point out again that not sending the confirmation param leads to really ugly code on the client side.  I have break out of the Angular framework I'm using for form processing.

**Comment by stianst** [comment]
The REST API should really be designed as a generic nice REST API, not to have loads of workarounds in place. The admin endpoints are full of horrible usability as they where created through the need for the admin console, not as a nice friendly API. I don't want that to happen this this API as well.

As I'm not fully convinced if the confirmation check on the server side shouldn't be there and it's optional I'm OK with including it.

**Review by stianst — APPROVED** [review]

**Pull request closed without merging**
