### PR TITLE
Add failedLoginNotBefore to AttackDetectionResource

### LINKED ISSUE #17574: Add failedLoginNotBefore field to existing brute force detection status API
### Description

There is one field returned in existing brute force detection status API that seems to be forgotten : _failedLoginNotBefore_. This one is however also in _UserLoginFailureModel_.

### Discussion

_No response_

### Motivation

For me it's one of the most useful field in order to know for how many time this user is currently locked. So if it's only an oversight I think it should be added.

### Details

Actually the Brute force detection status api return a map with the following fields:

* _numFailures_
* _disabled_
* _lastIPFailure_
* _lastFailure_

There is one that seems to be forgotten : _failedLoginNotBefore_. This one is however also in _UserLoginFailureModel_.

So in _AttackDetectionResource#bruteForceUserStatus_ maybe we just have to add _data.put("failedLoginNotBefore", model.getFailedLoginNotBefore());_

### PR DESCRIPTION
**Pull request by gilvansfilho**
Closes #17574

### CODE REVIEW

**Review by douglaspalmer — APPROVED** [review]
LGTM

**Comment by mposolda** [comment]
@gilvansfilho @douglaspalmer Thanks for the PR and review!

@gilvansfilho Could you please rebase and fix the conflict in AttackDetectionResourceTest class? Also could you please add your documentation note to 24_0_0.adoc to the brute-force section, which was introduced in this PR, which was just merged - https://github.com/keycloak/keycloak/commit/b0ef746f3945fa12668ea18decad30f9d1edcbcc#diff-10ee7495a04ba89225ddef18d2efb18ce71d5644d7068fecd3c8719a29da26d5 ? Maybe adding point 3 would be best (in addition to existing points (1) and (2)) will be best?

**Comment by gilvansfilho** [comment]
@mposolda done 😀

**Review by mposolda — APPROVED** [review]
@gilvansfilho @douglaspalmer Thanks for the updates and review!

**Pull request merged**
