### PR TITLE
KEYCLOAK-10158 Use full certificate as user identity for X.509 client cert authentication

### PR DESCRIPTION
**Pull request by sventorben**
Allows to use the full PEM encoded X.509 certificate from client cert authentication as a user identity.

Also allows to validate user's identity against LDAP in PEM (String and binary format), when custom attribute mapper is used.

In addition, a new custom attribute mapper allows to validate against LDAP when certificate is stored in DER format (binary, Octet-String).

Further information can be found [in this thread](http://lists.jboss.org/pipermail/keycloak-dev/2019-March/011858.html) from the mailing list.

### CODE REVIEW

**Comment by sventorben** [comment]
@mposolda What is the status of this? Is the PR in review?

**Comment by mposolda** [comment]
@sventorben Yes, I hope to provide some feedback today or next week... Sorry for the delay.

**Comment by sventorben** [comment]
I'm sorry if I'm too pushy here, but is there any initial feedback you can give?

**Review by mposolda — APPROVED** [review]
@sventorben Thanks for the PR and sorry it took so long to review

**Pull request merged**
