### PR TITLE
KEYCLOAK-13047 LDAP no-import fixes. Avoid lost updates - dont allow …

### PR DESCRIPTION
**Pull request by mposolda**
…update attributes, which are not mapped to LDAP

### CODE REVIEW

**Comment by mposolda** [comment]
https://keycloak-jenkins.com/view/pipelines/job/universal-test-pipeline-server/1712/

**Comment by mposolda** [comment]
Docs PR: https://github.com/keycloak/keycloak-documentation/pull/940

**Review by iankko — APPROVED** [review]
LGTM AFAICT (JFTR didn't test all metadata / field updates, this PR is touching. But those I tested, seems to be working fine)

In previous Keycloak versions (tried with v9.0.2) having LDAP federation provider configured with `Import Users = Off` and `Edit Mode = Writable`, login under LDAP federated user into the account console and attempt to change some metadata (firstname, lastname etc.), after clicking the `Save` button success `Success: Your account has been updated.` message was displayed. But the e.g. the firstname wasn't really updated, which was obvious right after the page reload (the updated value got replaced with the original one). With this change, login under federated user account into `masters` account console & updating the firstname really works (same success message is returned and the field is truly updated).

With `Import Users = Off` and `Edit Mode = Readonly` metadata updates is prohibited due to readonly nature (expected). Also, it's not possible to configure both `Import Users = Off` & `Edit Mode = Unsynced` any more (OK too, since attempt to use this combination of settings doesn't make much sense).

**Comment by mposolda** [comment]
@iankko Yes, exactly about the `Import Users = Off` & `Edit Mode = Unsynced` together. Thanks for the review.

**Pull request merged**
