### PR TITLE
Edit Keycloak 23 part of Upgrading Guide

### LINKED ISSUE #27484: Edit 23.0 changes part of Upgrading Guide
### Description

Minor changes

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andymunro**
Closes #27484
@ahus1 Please review.  Minor edits.

### CODE REVIEW

**Comment by andymunro** [comment]
@ahus1 Can you check if this look  good and, if so, merge it so it can be reviewed in Pantheon?

**Review by ahus1 — APPROVED** [review]

**Comment by ahus1** [comment]
I tested these changes locally with ccutil, and the output renders without errors. Thanks!

**Comment by andymunro** [comment]
Thanks, @ahus1. Does this need a backport?

**Comment by ahus1** [comment]
Yes, as it was merged only to main yet.

**Pull request merged**
