### PR TITLE
Add a client policy disabling client registration access token rotation

### LINKED ISSUE #11698: Add an option allowing to disable client registration access token rotation
### Description

Follows [KEYCLOAK-17707](https://issues.redhat.com/browse/KEYCLOAK-17707)

> Realm settings do have an option to configure the rotation of refresh tokens, we could introduce a similar option for registration tokens. That would be a feature request though, and the default behaviour should be that rotation of registration tokens are enabled.

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-17831

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by reda-alaoui**
Fix #11698

This adds a new client policy: `registration-access-token-rotation-disabled` .
This new policy disables client registration access token rotation.

Screenshot from 2022-11-20 20-15-10

### CODE REVIEW

**Comment by reda-alaoui** [comment]
Hello? :)

**Comment by reda-alaoui** [comment]
@stianst could someone review this change?

**Comment by reda-alaoui** [comment]
Ping :pray:

**Review by pedroigor — COMMENTED** [review]
Functional-wise, I think we should also consider managing rotation on a per-client basis. Clients might have different requirements than others so you might want to force rotation for some.

@mposolda Wdyt?

**Comment by reda-alaoui** [comment]
@mposolda Wdyt? :blush:

**Comment by mposolda** [comment]
@pedroigor @reda-alaoui I wonder if to use client policy instead of the boolean switch for the whole realm? We use client policy also for "Client Secrets" rotation, so that would be aligned with that.

Also client policy is much more flexible - for example it allows to enable rotation just for some clients (EG. those which are supposed to be FAPI compliant) and disable for other clients etc. So pretty much to cover use-case mentioned by @pedroigor in the comment above?

Maybe the option is to add new client policy executor, which can skip rotation (so by default, we will rotate tokens to have backwards compatible behaviour). In the future, we can have more flexibility if needed (EG. add the expiration for registration access tokens to ensure rotation for them every X days etc). WDYT?

**Comment by reda-alaoui** [comment]
@mposolda looks good to me

**Comment by mposolda** [comment]
@reda-alaoui Cool, Thanks!

This should also simplify this PR as adding new flag to realm settings is a bit painful (lots of changes needed in lots of files in both new and old store). When with client policy, it is about adding new executor (changes just in few files including tests) and there is not a need to send PR to the keycloak-admin-ui repository to update new admin console (which would be needed if we add new realm flag).

There are tests for client policies (like for example `ClientPoliciesTest`). It is possible to add new method there, but maybe it is also fine to just keep the test in the `RegistrationAccessToken` and just adjust setup of your test to use client policies instead of the flag? Whatever you prefer...

**Comment by reda-alaoui** [comment]
@mposolda , from my new `ClientPolicyExecutorProvider`, I need access to `ClientRegistrationAuth#isRegistrationAccessToken(JsonWebToken jwt)` and `RegistrationAuth` to move this code block:
```java
if (auth.isRegistrationAccessToken()) {
            String registrationAccessToken = ClientRegistrationTokenUtils.updateRegistrationAccessToken(session, client, auth.getRegistrationAuth());
            rep.setRegistrationAccessToken(registrationAccessToken);
        }
```

Should I add `ClientRegistrationAuth` to `DynamicClientUpdatedContext` ?

**Comment by reda-alaoui** [comment]
I followed client secret rotation and understood I got it backward. So forget my question :)

**Comment by reda-alaoui** [comment]
@mposolda , as discussed, I turned the realm setting into a client policy.

**Comment by mposolda** [comment]
@reda-alaoui This looks good to me! Thanks for the updates! I am sorry for the late review.

I have only last 2 things:

1) Is it possible to also add documentation PR for this to "keycloak/keycloak-documentation" repository? I think that some small changes may be needed in:
- This section of the client policies documentation: https://www.keycloak.org/docs/latest/server_admin/index.html#executor (Possibly just one line with the new executor can be added similar to other executors)
- This section in the "Securing Apps guide": https://www.keycloak.org/docs/latest/securing_apps/#_registration_access_token - there can be possibly something that it's possible to disable client registration access token rotation with the info about new executor and link to the "Client Policies" section mentioned above.

2) There is PR in progress for refactoring of ClientPoliciesTest. In case this PR would be merged before yours, you may have small conflict in your PR. But this is minor concern and hopefully you will be able to solve it soon (it is also a chance that your PR will be merged quicker and in this case the other PR will need to be updated, so no action from you would be needed. Just fyi :-) )
FYI. the other PR is: https://github.com/keycloak/keycloak/pull/16187

**Comment by reda-alaoui** [comment]
@mposolda , I created https://github.com/keycloak/keycloak-documentation/pull/1736 to document the executor.

**Review by mposolda — APPROVED** [review]
@reda-alaoui Thanks!

**Comment by mposolda** [comment]
@reda-alaoui One small note for the future: Please try to follow indentation of 4 spaces in the sources. That is the standard used in the Keycloak codebase

**Pull request merged**
