### PR TITLE
KEYCLOAK-11684 Add support to display passwords in password fields

### PR DESCRIPTION
**Pull request by hmlnarik**

### CODE REVIEW

**Comment by vmuzikar** [comment]
@hmlnarik I am unable to test your changes in the CI due to some dependency misconfiguration.
```
[ERROR] Failed to execute goal org.wildfly.build:wildfly-server-provisioning-maven-plugin:1.2.10.Final:build (server-provisioning) on project keycloak-wildfly-adapter-dist: Execution server-provisioning of goal org.wildfly.build:wildfly-server-provisioning-maven-plugin:1.2.10.Final:build failed: java.lang.RuntimeException: java.lang.RuntimeException: failed to resolve artifact org.jboss.security:jboss-negotiation-common:jar:3.0.6.Final: Failure to find org.jboss.security:jboss-negotiation-common:jar:3.0.6.Final in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```
Could you please rebase so that https://github.com/keycloak/keycloak/pull/6370 would be included in this PR?

**Comment by hmlnarik** [comment]
@vmuzikar: Done, hope it will behave better by now

**Review by ssilvert — COMMENTED** [review]
I'm OK with the UI part of this.  I don't know enough about the rest to review it.

**Review by stianst — COMMENTED** [review]
Missing some tests to check admin endpoints returns ${vault..} and not masked secret. Also, would be great if the credentials in UI are displayed by default when page is re-loaded if value is ${vault.} so that I can see it's a vault value straightaway without having to view/hide. The latter should be pretty straightforward to do.

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@hmlnarik Technically looks good to me.

Do you think you could add a simple Admin Console UI test for that? Just choose one field and test it. It adds some (seemingly simple) functionality to UI, so we should have a test that verifies all browsers are cool with that.

However, it seems to me a bit confusing for users. When a vault value is not used (i.e. a plain password is entered) and user clicks the unmask button, the "dots" OS uses for passwords are just replaced with `*******`. In this case the unmask feature doesn't have any effect.
Couldn't we do either:
Don't mask vault values at all (so we wouldn't need the unmask button). Plain passwords would be still masked as before.
-- OR --
Display the unmask button only when needed (i.e. when it has some effect).

**Comment by stianst** [comment]
When the value has changed, but not saved yet it should show the mask/unmask option. It should definitively not show it unmasked always as that would result in admins having to write in passwords visible and they would be visible until they click save button.

The ideal would be:
* Unsaved/edited value - show mask/unmask button
* Loading saved value - show unmasked if value is ${vault...}, or disable/hide mask/unmask button if value is *******. If edited the mask/unmask button would be enabled/visible

**Comment by hmlnarik** [comment]
Thanks for the reviews. Tests added I am giving up.

@stianst If the mask/unmask button manipulation is a must for this PR, please advise how this should be done generically. Angular events (`change` and similar) do not trigger on ajax load in `kcPassword`. CSS is completely spoiled when toggling the mask/unmask button visibility. I am giving up, feeling that this needs expertise from Angular / PF that I am missing.

**Comment by stianst** [comment]
Made some improvements here: https://github.com/keycloak/keycloak/pull/6395

**Comment by stianst** [comment]
If #6395 is approved this can be closed

**Comment by hmlnarik** [comment]
Superseded by #6395

**Pull request closed without merging**
