### PR TITLE
[KEYCLOAK-13385] - Better message when saving a provider with invalid URLs

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by stianst** [comment]
Does any of the messages include anything from the request? Need to make sure it doesn't in otherwise it can be considered an xss

**Comment by pedroigor** [comment]
Nothing from the request is used to build the response. `IllegalArgumentException` should only be thrown by validators with a proper message without exposing any internals.

I see your point though, so if we want to be safe we could return a general message for any URL provided, instead of a specific one for each URL.

**Comment by stianst** [comment]
@pedroigor Fix itself looks okay, but we should consider doing validation differently in the future I think. Perhaps we can do some ValidationResponse + ValidationException combo, which can have validation results for multiple fields rather than single fields. Any ways would be good to have a test for this though?

**Comment by pedroigor** [comment]
@stianst test added

**Review by stianst — APPROVED** [review]

**Pull request merged**
