### PR TITLE
Fix incorrect description of offline session

### PR DESCRIPTION
**Pull request by k-tamura**

### CODE REVIEW

**Comment by ahus1** [comment]
@martin-kanis - could you please review this if this suggestion is valid? Even though now parent issue exists, I can merge it with the ID or the PR by using a squash. Thanks!

**Review by martin-kanis — CHANGES_REQUESTED** [review]
In fact, two offline sessions are created. One offline user session (if it doesn't exist) and one offline client session.

**Comment by k-tamura** [comment]
Thank you for your comment. Updated.

**Review by martin-kanis — APPROVED** [review]
@k-tamura Thanks!

**Review by ahus1 — APPROVED** [review]
Approving as of @martin-kanis' review

**Pull request merged**
