### PR TITLE
Add missing additions/modifications to Arabic labels

### LINKED ISSUE #23487: Add missing additions/modifications to Arabic labels
### Description

These additions/modifications were introduced in #23472 #23137 #22665 #22673 #22068

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by Eng-Fouad**
Resolves #23487

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]
LGTM!

**Comment by jonkoops** [comment]
@Eng-Fouad as per usual, could you get someone else from the community that is a native speaker to review your work? Thanks for the hard work!

**Comment by alfayez91** [comment]
LGTM

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
Thanks @Eng-Fouad and @alfayez91! I'll set the PR to merge automatically.

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Review by ahus1 — APPROVED** [review]

**Comment by ahus1** [comment]
@hamzaseif13 - when using Keycloak in the current main branch, use a UTF-8 encoded file. 

When using Keycloak 22, there is still the need to add a header

```
# encoding: UTF-8
``` 

to the file. See https://www.keycloak.org/docs/latest/server_development/#messages for more details.

**Pull request merged**
