### PR TITLE
KEYCLOAK-13104 Signed and Encrypted ID Token Support : AES 192bit and 256bit key support

### PR DESCRIPTION
**Pull request by tnorimat**
This PR is for [KEYCLOAK-13104](https://issues.redhat.com/browse/KEYCLOAK-13104).

### CODE REVIEW

**Comment by mposolda** [comment]
@tnorimat Thanks again for the great contribution. The PR looks nice to me.

However I have some fear that it may not work on some JDK versions. Especially IBM JDK 8 can be problematic and maybe more. See for example https://github.com/keycloak/keycloak/blob/master/core/src/test/java/org/keycloak/jose/JWETest.java#L61 .

I will try to run this in our CI environment on various JDK versions and will get back to you with the details if this suspicion is correct...

**Comment by mposolda** [comment]
@tnorimat Could you please rebase the PR on latest master? This will help to make this possible to run in our CI

**Comment by tnorimat** [comment]
@mposolda I've rebased on the latest master as you said.

**Review by mposolda — APPROVED** [review]
@tnorimat Thanks. The build passed in our lab even with IBM JDK 8 on RHEL 6 and RHEL 7. So it looks we are fine in this regards. We will see if there are some issues in the future :)

**Comment by tnorimat** [comment]
@Marek Thank you. By the way, I've prepared the documentation (https://github.com/Hitachi/keycloak-documentation/commit/ed6a02cc1a66b25c9fd874eae2d2f6ee099b2d53) . Should I send this documentation PR ?

**Comment by mposolda** [comment]
@tnorimat Ah, nice. Thanks for pointing that. Yes, please send the documentation PR

**Comment by tnorimat** [comment]
@mposolda OK, I'll sent this documentation PR.

**Pull request merged**
