### PR TITLE
Added PayPal IDP

### PR DESCRIPTION
**Pull request by petlys**
Originating from a need for a PayPal OIDC login on a project I'm working on, this PR adds PayPal as a dedicated social identity provider.

### CODE REVIEW

**Comment by stianst** [comment]
Thanks for your contribution. 

Is login with PayPal free to use? We need at a minimum to be able to setup accounts for testing purposes.

To be able to accept this we'd need it to come with:

* Documentation - should contains steps on using, including how to configure on PayPal side.
* Testing - see SocialLoginTest and https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md#social-login

**Comment by petlys** [comment]
> To be able to accept this we'd need it to come with...

Added said tests and documentation (https://github.com/keycloak/keycloak-documentation/pull/185).

**Comment by petlys** [comment]
> Is login with PayPal free to use? 

Forgot to address this. Yes, from all I've gathered it's free. They provide a standard Open ID Connect API for login.

**Comment by stianst** [comment]
Thanks. Will get someone to check the tests on our internal CI jobs.

**Comment by vmuzikar** [comment]
Hi, @petlys. Here's Václav from the QE. Once again thank you for the contribution.

Before merging, could we ask you one more thing? Could you add an option to the Identity Provider to use the PayPal's sandbox API? It could be done e.g. as some ON/OFF switch.
It would help us a lot with testing it in our jobs and I can imagine others could use this too when setting up and trying this function.

**Comment by petlys** [comment]
Hi, @vmuzikar 

Are you sure that would bring any value? From what I've gathered, the only value in using sandbox PayPal is dealing with sample transactions and the like. In other words, login/authentication of sandbox users would be kind of pointless. For jobs you would need to create a real test account in order to create a sandbox account, and there would inherently be no difference authenticating against the two of them. Or what are your thoughts?

**Comment by vmuzikar** [comment]
Thank you for your response.

The point is, the sandbox environment is not only for the sample transactions but also for creating test user accounts and API credentials as well. So, it is designed and meant exactly for our purpose - testing.
Yes, surely, to use the sandbox you need an existing (personal) PayPal account to configure it. But once you create the test accounts, you use those it the test jobs.
And since those are test accounts I'm pretty sure we wouldn't need to worry about banning them.

If we were to use the live production environment, we'd need to create a fake business account since standard personal accounts cannot create live API credentials (unlike sandbox).
And I believe this could cause some problems. We'd surely break some PayPal's terms and from my POV creating a fake business account is not unlike creating a fake bank account (although PayPal is not a bank, of course).
Other thing is I'm not sure what it takes to create a business account - if it's not required to pair it with a real bank account in order to activate it or something. And even if it's not, it would be surely a really suspicious account (no money transfers, just API credentials and regular login actions) so I wouldn't be surprised if we had some real struggle with banning those fake accounts on regular basis.

From this reason we would greatly appreciate if we could use the environment which is meant for testing - the sandbox.
And I'm sure anyone else who would need to test the social providers would appreciate it as well since not everyone would be willing to create a business account just for a test.

**Comment by petlys** [comment]
@vmuzikar Valid points 👍 Added support for sandbox now

**Comment by vmuzikar** [comment]
Thank you for adding the support for sandbox!

I ran the test in our CI job and I encountered a few minor issues:
- missing support for the sandbox config in the `SocialLoginTest`
- wrong web element selectors in the `PayPalLoginPage`
- some other stability issues on `PayPalLoginPage` mainly related to the case when the user is already logged in

I've quickly fixed them. You can pull my changes if you want: https://github.com/vmuzikar/keycloak/tree/paypal-idp

**Comment by petlys** [comment]
> I've quickly fixed them. You can pull my changes if you want

Thank you, appreciated! 👍

**Comment by vmuzikar** [comment]
Thank you for pulling the changes.

As a last thing, please squash the commits. Other than that, from my PoV we are ready to merge.

**Comment by petlys** [comment]
> As a last thing, please squash the commits

Fixed 👍

**Comment by stianst** [comment]
Nice work, thanks for this :)

**Pull request merged**
