### PR TITLE
Remove unnecessary lookup of an entity via the session

### LINKED ISSUE #11744: Remove `session.area().getById(id)` from Map provider methods
### Description

Currently, for some queries, we obtain just ids of entities that fulfil the search and then call `getById` method. This was done so the legacy cache can store the entity which results in less traffic from the database (in other words, we load just ids from DB and ask the cache whether the entity is already present in the caching layer).

After disabling legacy cache in new storage we no longer want that, because the caching is solved differently. 

An example:
https://github.com/keycloak/keycloak/blob/2474ca73f9b9aac3f62180634e9485efcdb75fdf/model/map/src/main/java/org/keycloak/models/map/authorization/MapPolicyStore.java#L156

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #11744

### CODE REVIEW

**Review by sguilhen — COMMENTED** [review]
@ahus1 any particular reason for this to be a draft? Are there more occurrences of `get*ById()` that also need some rework?

**Comment by ahus1** [comment]
@sguilhen - the reason

**Comment by ahus1** [comment]
@sguilhen - the reason why this is still a draft is that one build was read - probably due to being unstable. Now the artifacts have expires, and I closed/re-opened it to trigger all builds to see how green it ends up :-(

**Comment by ahus1** [comment]
@sguilhen - build is green, now it's ready for review.

**Review by sguilhen — APPROVED** [review]

**Comment by ahus1** [comment]
@hmlnarik - it would be great if you could eventually merge it, @sguilhen has already reviewed it. Thanks!

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
