### PR TITLE
Fix the performance issue when keycloak admin logs into the web console

### PR DESCRIPTION
**Pull request by hqch0708**
Problem:
   If we have more than 1000 realms in keycloak, when the keycloak admin logs into the web console, the whoami api is very slow, even may get a 5XX response.

Change:
  I have changed the code in "whoami" and "realms" APIs in admin resource to use native SQL to get data instead of JPA.

### CODE REVIEW

**Comment by pedroigor** [comment]
@hqch0708 The problem is a bit deeper. First of all, thanks for your time on this.

In the past, we had several attempts (PRs) to fix this in order to support multiple realms. You are fixing on the places and the core issue with the `whoami` endpoint is that it tries to load all realms rather than on-demand and based on the realm you are managing.

I'm afraid we won't have this fixed now because this involves other changes around SaaS and multiple realm support.

**Comment by matt-rauch** [comment]
> @hqch0708 The problem is a bit deeper. First of all, thanks for your time on this.
> 
> In the past, we had several attempts (PRs) to fix this in order to support multiple realms. You are fixing one of the places and the core issue with the `whoami` endpoint is that it tries to load all realms rather than on-demand and based on the realm you are managing.
> 
> I'm afraid we won't have this fixed now because this involves other changes around SaaS and multiple realm support.

@pedroigor Are you referring to https://github.com/keycloak/keycloak/discussions/11074 with "other changes around Saas and multiple realm support"? 
Could you give a rough timeline, when the performance issues regarding large number of realms will be fixed?

**Comment by kkcmadhu** [comment]
> @hqch0708 The problem is a bit deeper. First of all, thanks for your time on this.
> 
> In the past, we had several attempts (PRs) to fix this in order to support multiple realms. You are fixing one of the places and the core issue with the `whoami` endpoint is that it tries to load all realms rather than on-demand and based on the realm you are managing.
> 
> I'm afraid we won't have this fixed now because this involves other changes around SaaS and multiple realm support.

why not whoami i simply loads the realm name alone using select  name from realm table and just populate that alone instead of the briefRepresentation? would that work?

**Comment by kkcmadhu** [comment]
> why not whoami i simply loads the realm name alone

i realized thats exactly what @hqch0708  fixs does! whats the issue you see @pedroigor  with @hqch0708's fix ?

**Comment by pedroigor** [comment]
@kkcmadhu Yes, it is about https://github.com/keycloak/keycloak/discussions/11074.

I'm not closing because of how it is fixed and we appreciate a lot the contribution. However, it is part of a bigger epic that we are not even sure how to properly deliver.

**Pull request closed without merging**
