### PR TITLE
KEYCLOAK-5032 Forward request parameters to another IdP

### PR DESCRIPTION
**Pull request by ckEriksen**
Forwarding of prompt, acr_values and nonce, if provided in the authorization request.
If prompt is set in the configuration for the identity provider, the configuration overrules the request parameter.

### CODE REVIEW

**Comment by patriot1burke** [comment]
I do agree that prompt should be propagated to external broker.  I'm not sure I agree that nonce and acr_values should be propagated.  The initiating client is not supposed to be aware that there is an external IDP involved with authentication.

**Comment by patriot1burke** [comment]
One more thing.  You can't even be sure that the initiating client is an OIDC client.  You could have a mixed environment.  For example, there is a SAML sort-of equivalent to PROMPT.  You should also make sure that that is propagated as well.

**Comment by ckEriksen** [comment]
I agree on the nonce, that's more for the communication between the client and the broker, and the broker may have it's own nonce towards the external IdP. Should I remove the nonce handling from this PR?

Regarding the acr, I think the values should be forwarded to the IdP, in order to allow the IdP to fulfill the clients request for a particular acr level.

For the SAML equivalent of prompt I found: ForceAuthn and isPassive, mapping to prompt=login and prompt=none, and the spec declaring that: "if both ForceAuthn and IsPassive are "true", the identity provider MUST NOT freshly authenticate the presenter unless the constraints of IsPassive can be met", giving isPassive precedence over ForceAuthn. Should I add support for these values?

**Comment by patriot1burke** [comment]
Ok, let's get rid of nonce.  Keep prompt as you've implemented it.  Create a separate JIRA for the SAML case.  Would be nice if you could add support for that too.  Up to you if you have time or not.

I changed my mind about acr_values.  Keep the support for it.  I understand it a bit more and it makes sense to propagate it.  I think there is a SAML equivalent for acr_values too.   Open a separate JIRA for that too.  Thanks.

**Comment by nxadm** [comment]
I am very excited about this feature, and now Keycloak 8.0.1 is released I will test it thoroughly. In our setup we use a Shibboleth 3 IDP as a backend for Keycloak. Multi Factor Authentication (MFA) is done on the Shibboleth IDP. 

MFA with the SAML backend works like this:
-  SAML Service Provides (clients) need to add a AuthnContextClassRef to enfore MFA:
```
<saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:MobileTwoFactorContract</saml2:AuthnContextClassRef>
```
A oicd plugin for Shibboleth will send this to the IDP to trigger it: 
```
{"id_token":{"acr":{"essential":true,"values":["MobileTwoFactorContract"]}}}
```

I am confused about a few things on how the Keycloak implementation will work in the case of a SAML Idp.
- How will "acr_values" be wrapped in the SAML request created by Keycloak? I had a look at the code and the SAML request generation looks not very dynamic. What I am missing?
- Part of the MFA equation is checking the response of the IDP,. It normally returns something like this so the client knows MFA was done:
```
{"acr":"MobileTwoFactorContract"}
```
(or when failed or skipped, you get {'"acr":0})

So @ckEriksen and @patriot1burke, in case you have more information on what the request and the answer should look like, it will speedy my tests so I can give feedback.

Thank you!

**Pull request merged**
