### PR TITLE
Update TestContainers to 1.4.2 to remove some hacks

### PR DESCRIPTION
**Pull request by bsideup**
Hi! 

I spotted that you use TestContainers, and decided to help you to update to 1.4.2.

We released some great features like Docker Networks support (so that you don't have to do `withExtraHost` anymore 🎉  )

### CODE REVIEW

**Comment by bsideup** [comment]
Hi @vmuzikar! 

SELinux is configurable now, see
https://github.com/testcontainers/testcontainers-java/pull/334

I didn't change the test in Keycloak because I didn't have an environment to test it, but left TODO to highlight that it's doable now :)

**Comment by vmuzikar** [comment]
Ok, thank you for clarification.

I've tried to run the test and I've run into some issue, unfortunately.
The test is failing after your changes. To be honest, this test was very, very problematic and unstable in the past, so don't worry about it - see https://github.com/keycloak/keycloak/pull/3565.

The test should be primarily targeted for Fedora/RHEL - of course it should be platform independent but Fedora and RHEL is the bare minimum, since it's mostly run in our CI job which is hosted on RHEL, of course.

I've run the test both on my local Fedora machine and in the CI as well and it failed on both.

On Fedora it failed with:
> Error response from daemon: Get https://registry.localdomain:5000/v2/: Get http://172.17.0.1:8180/auth/realms/docker-test-realm/protocol/docker-v2/auth?account=docker-user&client_id=docker&offline_token=true&service=docker-test-client: dial tcp 172.17.0.1:8180: getsockopt: connection refused

I.e. the container fails to communicate with Keycloak which is running locally (outside the container).

On RHEL:
> com.github.dockerjava.api.exception.DockerClientException: Could not pull image: Digest: sha256:129a7f8c0fae8c3251a8df9370577d9d6b96ca6f1bea33ada677bc153d7b1867
 	at org.keycloak.testsuite.docker.DockerClientTest.beforeAbstractKeycloakTest(DockerClientTest.java:113)

It seems to me that it's caused by the new network configuration in the test - instead of using docker0 interface as before, a new interface is created and `iptables` are blocking it.

Could you please try to fix the test, so - ideally - no manual `iptables` modifications would be necessary before running the test? (If you'd also add the SELinux configuration, so the "hack" wouldn't be necessary anymore, it would be awesome and a huge added value to this PR. ;))

Or at least, could you please update the instructions in [HOW-TO-RUN](https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md#run-docker-authentication-test) to reflect your changes when running on Fedora?
But again, it's highly preferred if no `iptables` modifications would be required since those require root permissions.

**Comment by stianst** [comment]
@bsideup any comments to @vmuzikar last comment?

**Comment by bsideup** [comment]
Hi @stianst @vmuzikar,

I'll try to figure out why it fails on Fedora/RHEL, but it's not easy because I don't have it anywhere :D

Since I added Docker Networks, maybe it's not related to the change, but in general how they work in Fedora/RHEL environments?

**Comment by vmuzikar** [comment]
I believe the main (and possibly the only) problem here are the `iptables` which are configured differently for the Docker Network / Interface on each OS / Linux distro.
The best solution would be to somehow force Docker to configure `iptables` properly to allow traffic from container to host, container to internet and container to container. But not sure if it's possible to do it in automated way.

Or at least [HOW-TO-RUN](https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md#run-docker-authentication-test) needs to be updated with a specific straightforward instructions on what to do with the `iptables`.

**Comment by vmuzikar** [comment]
Hi @bsideup!
The test started failing recently so we needed to rewrite it and use a bit different approach. With that we also updated the Testcontainers. See https://github.com/keycloak/keycloak/pull/5176.

From that reason I believe we could close this PR if you'd agree. WDYT?

**Pull request closed without merging**
