### PR TITLE
Update documentation for removal of the map store

### LINKED ISSUE #24092: Map Store Removal: Revisit documentation
### Description

With the Map Store being removed, we need to revisit Keycloak's documentation to ensure references to it are not present and also fix any section that uses the term `legacy` to refer to the current store.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #24092

### CODE REVIEW

**Comment by ahus1** [comment]
@vramik - it would be great if you could review this PR. I looked at the existing docs and only found the one warning where we talk about "legacy store". All other places are the migration guide and change log, which we would keep unchanged.

This is also a follow-up on the initial wording of the release notes / change log.

**Comment by vramik** [comment]
> @vramik - it would be great if you could review this PR. I looked at the existing docs and only found the one warning where we talk about "legacy store". All other places are the migration guide and change log, which we would keep unchanged.
> 
> This is also a follow-up on the initial wording of the release notes / change log.

Thank you @ahus1 for the PR, it looks good to me. Could you please confirm that we should mention experimental feature in release notes? I've seen https://github.com/keycloak/keycloak/pull/24333#issuecomment-1786871898 which states that _"experimental features should not be part of the release notes"_.

**Comment by ahus1** [comment]
@vramik - I confirmed with @stianst earlier today that the removal should be mentioned, so I assume we're good here.

I know we mentioned the map storage in the release notes earlier (KC 19) due to the refactorings which it introduced , so I assume it is now symmetric. 

We might do it more consistently for all other experimental features in the future and neither mention removal and addition as the previous comment you cited suggests.

**Review by vramik — APPROVED** [review]
Thank you @ahus1 for confirmation!

**Review by abstractj — APPROVED** [review]

**Pull request merged**
