### PR TITLE
Simplify obtaining Keycloak Quarkus configuration

### PR DESCRIPTION
**Pull request by mabartos**
This PR should simplify gathering information about Keycloak configuration.

I'd like to avoid statements like:
`StorageOptions.StorageType.jpa.name().equals(getOptionalValue(NS_KEYCLOAK_PREFIX.concat(STORAGE.getKey())).orElse(null))`

as we can query the configuration like this: `KeycloakConfiguration.isMapJpa()`.

### CODE REVIEW

**Review by pedroigor — COMMENTED** [review]
@mabartos The `Configuration` class looks similar to the newly introduced `KeycloakConfiguration`.

I'm also not sure how much it is making configuration simpler. I'm probably missing the reasoning.

However, I do see space for improvements such as removing the need for appending the namespace wherever you want to query an option.

**Comment by pedroigor** [comment]
@mabartos I think it is valid and we should improve how we obtain configuration.

IMO, we could just leverage the existing `Configuration` class for very common options and remove all that complexity when querying options:

```
Configuration.hasValue(STORAGE, StorageOptions.StorageType.jpa)
```

Or something similar ...

**Comment by abstractj** [comment]
@mabartos do you still want to continue with the changes proposed here?

**Comment by mabartos** [comment]
Not relevant ATM.

**Pull request closed without merging**
