### PR TITLE
[KEYCLOAK-7254] - Intermittent CME during server start

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by MaysaraMohamed** [comment]
Is there a way to integrate keycloak with spring boot version 2 or higher ?

**Comment by pedroigor** [comment]
@MaysaraMohamed, best place to ask is keycloak-user mailing list :)

But Spring Boot 2 work has started and you should be able to use it. See https://github.com/keycloak/keycloak/pull/4976.

**Comment by stianst** [comment]
@vramik can you review this please?

**Review by vramik — CHANGES_REQUESTED** [review]
I still get intermittent CMEs. But afaik @pedroigor haven't finished the work on this one yet

**Comment by stianst** [comment]
@pedroigor @vramik what's the status on this?

**Comment by vramik** [comment]
@stianst I got intermittent CMEs with this PR, so it needs to be fixed. I have no update from @pedroigor. So it's the question mainly for him.

**Comment by stianst** [comment]
@pedroigor bump

**Comment by pedroigor** [comment]
@stianst @vramik need to get back to this one. I know what is causing the issue but need to find out another way to fix it.

**Comment by hmlnarik** [comment]
@vramik @pedroigor Is this issue still relevant after latest WildFly upgrade?

**Pull request closed without merging**
