### PR TITLE
KEYCLOAK-8462 Close delegates properly

### PR DESCRIPTION
**Pull request by hmlnarik**

### CODE REVIEW

**Review by mposolda — DISMISSED** [review]

**Comment by stianst** [comment]
This is strange. The EntityManager should be created and closed by DefaultJpaConnectionProvider. Further, looking at implementations of StoreFactory, the JPAStoreFactory close method doesn't actually do anything. So can't see how this changes anything.

**Comment by mposolda** [comment]
@stianst True, Sorry, I didn't reviewed this very carefully.

**Comment by pedroigor** [comment]
@hmlnarik, the correct fix should be changing `StoreFactoryCacheSession` constructor to initialize the `delegate` field as follows:

```java
delegate = session.getProvider(StoreFactory.class);
```

The way it is, the provider could be initialized only at the end of the transaction an may not be in the map of registered provides when closing a session.

**Comment by hmlnarik** [comment]
@stianst It does change the behaviour since it follows pattern set by `UserCacheSession` on caching layer with lazy `delegate` initialization rather than using JPA-layer like `JPAStoreFactory` does.

@pedroigor That indeed is the case, delegate is initialized in commit method. Reason is that `delegate` is created lazily, similarly to `UserCacheSession`, where the `close` method uses just the same way to deal with delegates.

Both fixes are valid. Putting the `delegate` initialize into constructor would change the logic though since it would relax the condition on line https://github.com/keycloak/keycloak/blob/4.5.0.Final/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/authorization/StoreFactoryCacheSession.java#L400 as the initialization would be unconditional.

If that's desirable, I'll be happy to change it.

**Comment by mposolda** [comment]
My vote is to merge this PR. Adding the check like:
````
if (delegate!=null) delegate.close()
````
doesn't break anything and it follows the pattern by other cache providers (RealmCacheSession, UserCacheSession). 

However it doesn't actually fix the memory leak, I am still seeing the memory leak even after this fix is applied. That's indeed because delegate of StoreFactoryCacheSession is JPAStoreFactory class, which has empty close method as @stianst pointed. However it is more proper to close it and add this PR (the fact that "delegate.close()" method doesn't do anything is in theory implementation detail).

What helped me to fix the leak is this change https://github.com/keycloak/keycloak/pull/5618 .

@pedroigor I think that what you propose will help us well. However calling the "delegate = session.getProvider(StoreFactory.class);" from constructor will have one bad side-effect IMO that it will always starts JPA/Hibernate transaction even if there is no need for it.

**Comment by hmlnarik** [comment]
Updated the PR with the proper fix. The delegate should be created lazily to prevent EntityManager instantiation if not needed. On the other hand, the issue is that `commit` should not create delegate via `getDelegate` everytime it is called. Since the code never uses `clearAll`, the code has been removed. The `runInvalidations()` does not do anything if there was no write (and thus no invalidations)

**Review by mposolda — APPROVED** [review]
@hmlnarik Thanks! I think this should help. I've closed mine https://github.com/keycloak/keycloak/pull/5618 and approving this one.

**Review by stianst — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
