### PR TITLE
Fixing broken build after merging conflicting PRs.

### LINKED ISSUE #12898: Keycloak main fails to build JpaSingleUseObjectModelCriteriaBuilder
### Describe the bug

After merging #9852 there was an undiscovered conflict between two PRs, and now `main` fails to build.

### Version

999-SNAPSHOT

### Expected behavior

The changes from #11844 need to be added main for the new files added by the PR #9852

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
This was introduced via #9852 when #11844 was merged.

Closes #12898

### CODE REVIEW

**Review by sguilhen — APPROVED** [review]

**Review by mhajas — APPROVED** [review]
It compiles correctly now and the change makes sense. Thank you for the quick fix @ahus1

**Review by pedroigor — APPROVED** [review]

**Comment by ahus1** [comment]
@pedroigor - all except one test completed. I had a look and LoginTest#loginWithForcePasswordChangePolicy completes when I run it locally, so I assume an unstable test case here. 

Please go ahead and merge this PR. Thanks!

**Comment by pedroigor** [comment]
Re-running, test is required and I can't force. Tks.

**Comment by ahus1** [comment]
Thanks @pedroigor for using your maintainer proviledge to re-run the check - now I know that this can't be forced.

I searched the issue tracker and there is already an open issue for this unstable test #12845.

**Pull request merged**
