### PR TITLE
KEYCLOAK-10013 Do not reject tokens with issuedAt == notBefore

### PR DESCRIPTION
**Pull request by mhajas**

### CODE REVIEW

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by stianst** [comment]
Would be good to also check the logic on the server-side as well as Node.js and Gatekeeper. Should be relatively quick so can we just handle that as part of the same issue?

**Comment by mposolda** [comment]
@stianst We discussed node.js and gatekeeper with @mhajas already. Michal mentioned that node.js has already correct logic for not-before check. Gatekeeper on the other hand doesn't yet have support for not-before at all. It seems adding not-before to gatekeeper should be likely separate task than part of this? @mhajas Do you know if we have JIRA for gatekeeper and not-before support already?

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mhajas** [comment]
@mposolda I checked all JIRAs for gatekeeper and haven't found anything with not-before, so I created issue https://issues.jboss.org/browse/KEYCLOAK-10032 feel free to update or comment.

@stianst I forgot to check server-side logic I will do that, @mposolda please do not merge until I do it.

**Comment by stianst** [comment]
Thanks for the update, so yes please create a task for Gatekeeper and add it to Supported Gatekeeper epic. Leave it in triage for now.

@mhajas thanks for checking the server-side logic :)

**Comment by mhajas** [comment]
@keycloak-ci-bot test

**Comment by mhajas** [comment]
@stianst I have found those relevant server-side occurrences. They all seem good to me. If you know about something else, or you think something should be fixed on those, let me know. @mposolda From my point of view, the PR is ready to merge.

https://github.com/keycloak/keycloak/blob/master/core/src/main/java/org/keycloak/representations/JsonWebToken.java#L99

In TokenManager there are more checks like this, but all are basically the same as this one:
https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java#L158

https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java#L1174

**Pull request merged**
