### PR TITLE
Add generated ECDH key provider

### LINKED ISSUE #23596: Support generated ECDH realm keys
### Description

Add key provider that can generate ECDH keys that can support the ECDH-ES, ECDH-ES+A128KW, ECDH-ES+A192KW and ECDH-ES+A256KW JWE algorithms.

### Discussion

_No response_

### Motivation

To support the ECDH-ES, ECDH-ES+A128KW, ECDH-ES+A192KW and ECDH-ES+A256KW JWE algorithms.

### Details

_No response_

### PR DESCRIPTION
**Pull request by justin-tay**
Adds a key provider to generate ECDH realm keys for use for the ECDH-ES, ECDH-ES+A128KW, ECDH-ES+A192KW and ECDH-ES+A256KW JWE algorithms.

Closes #23596

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Comment by mposolda** [comment]
@rmartinc @tnorimat Do you please have a chance to review this whenever you have some spare time?

**Comment by rmartinc** [comment]
@justin-tay I think PR #23928 is more complete and contains all the changes in this PR, right?
If I'm OK I would close this one and just work on #23928.

**Comment by justin-tay** [comment]
Superseded by
* #23928

**Pull request closed without merging**
