### PR TITLE
KEYCLOAK-15238: Fix potential resource leak

### PR DESCRIPTION
**Pull request by testn**
Fix potential resource leak from not closing Stream/Reader

### CODE REVIEW

**Comment by hmlnarik** [comment]
Thank you for the PR.
While the most of the fixes would be improvements, please note that some of the streams might be intentionally left open. The test failures are relevant.

**Comment by testn** [comment]
@hmlnarik  can you help identify which tests you are referring to?

**Comment by hmlnarik** [comment]
> can you help identify which tests you are referring to?

Those from the Checks tab above.

**Review by hmlnarik — APPROVED** [review]
Thank you for the PR!

**Pull request merged**
