### PR TITLE
[KEYCLOAK-4132] Content Security Policy: Directive 'frame-src' has been deprecated

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Comment by stianst** [comment]
This will only be effective for new installations and not upgrades. Do we not also need both frame-src and child-src? I believe child-src is not supported by all browsers yet?

**Comment by abstractj** [comment]
@stianst here is the fantastic confusion created by CSP spec. `frame-src` was deprecated on CSP Level 2. Currently supported by most of browsers http://caniuse.com/#feat=contentsecuritypolicy2. On CSP Level 3, they are going to "undeprecate" this. But it's still a draft.



What can we do? Leave the warning and wait for browsers to implement CSP Level 3. Or, move to `child-src` and put `frame-src` back later.

**Comment by stianst** [comment]
I'd say we just leave frame-src then. Not all browsers IE11 for one uses child-src so that would mean no protection at all on those browsers which is not good at all.

**Comment by stianst** [comment]
My vote is we reject this issue and revist as part of the other issue to review the content security policy in 3.x

**Comment by abstractj** [comment]
Fair enough. I'm, closing it and the issue https://issues.jboss.org/browse/KEYCLOAK-4132 was rejected.

**Pull request closed without merging**
