### PR TITLE
KEYCLOAK-11300 :  Creating CustomEnforcer functionality for spring adapters

### PR DESCRIPTION
**Pull request by sushil-singh-guavus**
KEYCLOAK-11300 : Creating CustomEnforcer functionality for spring adapters

https://issues.jboss.org/browse/KEYCLOAK-11300

### CODE REVIEW

**Comment by stianst** [comment]
Hi, thanks for your PR. Can you please open a discussion around this on the dev ML?

**Comment by sushil-singh-guavus** [comment]
Hi ,

Actually I am already in discussion with Pedro Igor Silva

Thanks,

Sushil Pratap Singh
________________________________

**Comment by stianst** [comment]
Where? It would be good to have the discussion openly on the dev ML.

**Comment by sushil-singh-guavus** [comment]
> Where? It would be good to have the discussion openly on the dev ML.

@stianst,  i have initiated the discussion

**Comment by pedroigor** [comment]
> Where? It would be good to have the discussion openly on the dev ML.

@stianst the JIRA provides some background and a document with more details about what @sushil-singh-guavus is proposing.

I asked him to send the PR so that we could understand better the use-case and start discussing the changes.

**Review by pedroigor — COMMENTED** [review]
@sushil-singh-guavus, now that we have the code and based on the description you have in the doc (attached to the JIRA), the intent is much more clear.

Correct me if I'm wrong, please. The objective here can be summarized as follows:

* As a user I want to *programmatically* check whether or not a request is authorized to access a protected resource, so that I can pass the resource identifier/name and/or the set of scopes

* As a user I want to be able to programmatically manage resources (CRUD) so that I can manage the resources that should be protected by Keycloak

If my assumption is correct, I think we can solve that differently by leveraging the `AuthorizationContext` class, which is available from the `KeycloakSecurityContext` that is usually available in the request scope.

The `AuthorizationContext` already provides methods for checking permissions, but today, they rely on any permissions carried by the token and do not interact with the server if no permission (for a resource/scope) is available.

It seems to me that we can simplify this implementation while addressing the same requirements.

In fact, recently, we have implemented a policy enforcer for Quarkus`which provides a similar approach to check permissions programmatically. While it also does not interact with the server to query for permissions, the hook is there to adapt and enhance programmatic authorization.

Please, let me know your thoughts about what I said.

**Comment by sushil-singh-guavus** [comment]
> @sushil-singh-guavus, now that we have the code and based on the description you have in the doc (attached to the JIRA), the intent is much more clear.
> 
> Correct me if I'm wrong, please. The objective here can be summarized as follows:
> 
> * As a user I want to _programmatically_ check whether or not a request is authorized to access a protected resource, so that I can pass the resource identifier/name and/or the set of scopes
> * As a user I want to be able to programmatically manage resources (CRUD) so that I can manage the resources that should be protected by Keycloak
> 
> If my assumption is correct, I think we can solve that differently by leveraging the `AuthorizationContext` class, which is available from the `KeycloakSecurityContext` that is usually available in the request scope.
> 
> The `AuthorizationContext` already provides methods for checking permissions, but today, they rely on any permissions carried by the token and do not interact with the server if no permission (for a resource/scope) is available.
> 
> It seems to me that we can simplify this implementation while addressing the same requirements.
> 
> In fact, recently, we have implemented a policy enforcer for Quarkus`which provides a similar approach to check permissions programmatically. While it also does not interact with the server to query for permissions, the hook is there to adapt and enhance programmatic authorization.
> 
> Please, let me know your thoughts about what I said.

@pedroigor Based on my understanding , When it comes to **AuthorizationContext** ,  it has methods to check permission for resource and a scope. So even if we extend it's functionalities for eg-: [Resource , Set <Scopes>] ,  it won't be able to provide UMA and other functionalities that the policy-enforcer provides as it directly work on tokens

In our case client may not know the permission to be able to access that resource and scope. So firstly it will just call with an access token and based on the permission ticket , it will bring out the RPT

We have seen most of the options and then decided that policy-enforcer functionalities is what we are looking for , but some what in a custom fashion

Following things are there in PolicyEnforcer flow and needed for us

- UMA i.e permission ticket flow working for us

- Caching of resources

- Lazy Loading (on demand resource)

- wildcard resource matching

So, that's why I created CustomEnforcer functionality which can be enabled using keycloak.json. And you just specify the map of <resource , Set<scopes> programatically. and just call the custom enforcer function. It will authenticate , authorize and set the applicable response status. 

Here I am using PolicyEnforcer caching , wildcardresource matching , Lazy loading and have customized UMA flow based on Map<Resource, Set<Scopes>>

So , I am afraid that extending functionality of AuthorizationContext won't work for us. 

I hope things are clear from my side , and also i will request to correct me if I am wrong somewhere

**Comment by stianst** [comment]
Didn't see any email about this on the dev ML yet. Could you please open a thread there so others can participate if they want to?

**Comment by sushil-singh-guavus** [comment]
Can you tell the mail ID of dev mailing list. I have mailed on keycloak-users but don't  know the dev mail id

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by stianst** [comment]
@sushil-singh-guavus check out https://www.keycloak.org/community for details on ML. @pedroigor started a thread on this there, so let's continue the discussion on the ML

**Comment by sushil-singh-guavus** [comment]
@stianst @pedroigor , It's been pending for a lot of days .

I have  created a quickstart

https://github.com/sushil-singh-guavus/keycloak-quickstarts/tree/keycloak-11300-quickstarts
https://github.com/sushil-singh-guavus/keycloak/tree/keycloak-11300

Can you check !!

**Comment by stianst** [comment]
Was a discussion opened on the dev mailing list around this? If so what was the conclusion here? From my perspective this may seem a bit to complex and seems like something we may not want to consider. @pedroigor wdyt?

**Comment by pedroigor** [comment]
@stianst We had some discussion, can't find now the thread. But we ended up with this PR.

@sushil-singh-guavus After looking at your quickstart, I think I see now what you really want. And I still think we can do something along the lines with what I mentioned before.

It seems that we could just change the `AuthorizationContext` so that you can call specific methods to directly invoke the server. It should require fewer changes.

**Comment by sushil-singh-guavus** [comment]
@pedroigor , I am fine with the changes suggested by you that i have modified a bit because some things were breaking in  https://github.com/sushil-singh-guavus/keycloak/commits/keycloak-11300

**Comment by pedroigor** [comment]
@sushil-singh-guavus I see, so I think we should just have this PR with the changes you have in https://github.com/sushil-singh-guavus/keycloak/commits/keycloak-11300 plus the additional method and related changes to the `AuthorizationContext` so that you can pass that map with permissions.

Makes sense ? It should be much simpler, I think.

**Comment by sushil-singh-guavus** [comment]
@pedroigor right !!

I think changes related to passing map as a parameter is there in the PR https://github.com/sushil-singh-guavus/keycloak/commits/keycloak-11300 

I have also demonstrated that in quickstart also
Let me put it here also,

AuthorizationContext authzContext = keycloakSecurityContext.getAuthorizationContext();
        AdapterAuthorizationContext clientContext = AdapterAuthorizationContext.class.cast(authzContext);
        Map<String, Set<String>> permissionMap = new HashMap();
        Set<String> scopes = new HashSet();
        scopes.add("CREATE");
        String namespace = piplineData.getNamespace();
        String name = piplineData.getName();
        Object resource = new Object();
        permissionMap.put(namespace,scopes);
        clientContext.authorize(permissionMap);

**Comment by pedroigor** [comment]
Yeah, so we should just change this PR to have that instead of all the changes herein ...

**Comment by sushil-singh-guavus** [comment]
> Yeah, so we should just change this PR to have that instead of all the changes herein ...

This PR was created from https://github.com/sushil-singh-guavus/keycloak/tree/feature/custom-policy-enforcer
Should i create new PR with https://github.com/sushil-singh-guavus/keycloak/commits/keycloak-11300 
or
Should i revert the changes in this feature/custom-policy-enforcer branch and commit changes from branch keycloak-11300 in to it 

plzz suggest

**Comment by pedroigor** [comment]
Changes from keycloak-11300. They are enough, right?

**Comment by sushil-singh-guavus** [comment]
> Changes from keycloak-11300. They are enough, right?

yes

**Comment by pedroigor** [comment]
It has been a while and plans have changed. We are avoiding drastic changes to this area of Keycloak.

Sorry and thanks for your contribution.

**Pull request closed without merging**
