### PR TITLE
Display IDP Display Name instead of IDP Alias

### LINKED ISSUE #33408: Link to existing account form: IDP Alias displayed instead of IDP Display Name
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

I am using an additional identity provider (another keycloak instance) and I am logging in.
Keycloak detects that the EMail address is already known and shows a dialog to link the other keycloak instance's user account to the current one.

The dialog says: "Authenticate to link your account with {0}"

The placeholder {0} gets resolved to what I suppose is the IDP's Alias name, NOT as I would expect the IDP's Display Name (!)

### Version

25

### Regression

- [ ] The issue is a regression

### Expected behavior

I would expect the IDP's Display Name (!)

### Actual behavior

The placeholder {0} gets resolved to what I suppose is the IDP's Alias name.

### How to Reproduce?

- As admin: Configure a second keycloak as IDP in the first keycloak.
- Login into the first one using an account from the second.
- As admin: In the 1st keycloak, unlink the user account from the second keycloak.
- Attempt a second time the login into the first one using an account from the second.
- Keycloak will report, the account already exists.
- Choose the second button, "Link to existing account" or so.
- Now notice the message above the username input field.

### Anything else?

cf. https://github.com/keycloak/keycloak/blob/c682536dae36e1aa35d90cf2cf24aa81864b46cd/themes/src/main/resources/theme/base/login/messages/messages_en.properties#L282

cf. https://github.com/keycloak/keycloak/blob/a35edeb48803dd356f0e947a276f22544176afe4/services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpUsernamePasswordForm.java#L96

### PR DESCRIPTION
**Pull request by NobelNerdBenne**
This commit close the Issue where the IDP alias is displayed instead of the IDP display name in the existing account link. The alias will continue to be used when no display name is set.

Close #33408

### CODE REVIEW

**Comment by fjf2002** [comment]
Any advances here?

**Comment by ahus1** [comment]
@jonkoops / @rmartinc - this PR references and issue that you've commented on earlier. Please review this PR when you have the time. Thanks!

**Review by rmartinc — APPROVED** [review]
Thanks @NobelNerdBenne! The change LGTM.

**Review by ahus1 — APPROVED** [review]
Approving as of @rmartinc's review

**Pull request merged**
