### PR TITLE
Remove effective roles filtering to avoid inconsistency

### LINKED ISSUE #29615: Get effective roles for user needs more privileges than expected
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When retrieving the effective roles via the `/ui-ext/effective-roles/users/{id}` endpoint, only roles the user / administrator is allowed to map are returned.

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

All effective roles of the user are returned.

### Actual behavior

Only roles the user / administrator is allowed to map are returned.

### How to Reproduce?

Call the endpoint `/ui-ext/effective-roles/users/{id}` with a user which only has the roles `view-users` and `view-realm`.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by andreas-blaettlinger**
Fixes #29615.

I noticed a weird inconsistent behaviour at the users role-mapping tab. In following example there is a newly created user with additional client (master-realm) roles (view-realm, view-users).

When "Hide inherited roles" is ON it looks like this:
original-hide-on

But when it is OFF the assigned client roles are nowhere to be seen:
original-hide-off

Following code is responsible for that:

```
        return toSortedClientRoles(
                addSubClientRoles(Stream.concat(
                user.getRoleMappingsStream(),
                user.getGroupsStream()
                        .flatMap(g -> addParents(g))
                        .flatMap(GroupModel::getRoleMappingsStream))) // Up until this point all assigned roles are being found, including the client-roles
                .filter(auth.roles()::canMapRole) // But this filter removes them.
        );
```

It looks like a user has to be able to assign roles just to be able to see them and I'm not really sure whether this is intended or not.

So I just removed the `.filter(...)`with my PR and this results in following.

my-version-hide-off
my-version-hide-on

With this changes, the endpoints `/admin/realms/master/ui-ext/effective-roles/users/{user-id}` and `/admin/realms/master/users/{user-id}/role-mappings` are consistent.

WDYT?

### CODE REVIEW

**Comment by andreas-blaettlinger** [comment]
BTW this also seems to be in the case in following other methods/endpoints in `EffectiveRoleMappingResource` which are not adjusted within this PR yet:

* listCompositeClientScopeRoleMappings
* listCompositeClientsRoleMappings
* listCompositeGroupsRoleMappings
* listCompositeRealmRoleMappings

**Comment by martin-kanis** [comment]
@andreas-blaettlinger Thanks for the PR, looking into this, I'm also not sure why we would need show only those roles that user is able to assign. @sschu do you recall, why you added the filter to all the methods listed above? Thanks!

**Comment by sschu** [comment]
@martin-kanis I didn't add it. The behaviour was already in place before and I already thought it was odd. I just kept the current behaviour to only touch efficiency when I was working on it.

**Comment by martin-kanis** [comment]
@sschu right sorry, at the first glance it looked as an addition. Actually, it was added by https://github.com/keycloak/keycloak/pull/16668 @edewit Can you elaborate why a user needs "canMapRole" role in order  to see it as an effective role?

**Comment by pedroigor** [comment]
Isn't better to change the filter (removed in this PR) to also consider the view-users role?

**Comment by sschu** [comment]
@pedroigor Wouldnt it be best to use `canViewRole()` instead?

**Comment by andreas-blaettlinger** [comment]
With .canView() it would look like this:
canView-hide-on
canView-hide-off
Compared to my version there are less entries here. Just as @sschu mentioned, depends on what is expected.

**Comment by pedroigor** [comment]
@andreas-blaettlinger @sschu Makes sense for me too. I suggested considering `view-users` because if you can view a user you should be able to see the roles, IMO.

But if using `canView` works to solve this issue, it works for me too. But `canView` might require either the `manage-clients` or `view-clients` roles. I think that is why you see fewer entries there.

We are planning to start looking at admin authz soon and hopefully we'll make these checks/intentions more clear.

**Comment by martin-kanis** [comment]
@andreas-blaettlinger `canView` make sense to me. As Pedro mentioned, user might be required to have `view-clients` role (besides `view-users` and `view-realm`) but that also make sense to me as there are client-roles besides realm-roles. 
So I would suggest to change `canMapRole` to `canView` in all 5 methods in `EffectiveRoleMappingResource` and see if tests are happy.

**Comment by sschu** [comment]
@martin-kanis `canList` (see https://github.com/keycloak/keycloak/blob/030f42ec83b5474fdfa1946907ef76deec5a1ddf/services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissionEvaluator.java#L29) would be another option. It really depends if `view` is about seeing the details of some thing or that the thing exists in the first place.

**Comment by sschu** [comment]
I had another quick look at other entities, it looks like the follow read permissions are known

- Users: Query, View
- Client: List, View
- Groups: List, View
- Roles: List, View

To me it sounds like List/Query means you are able to see that a thing exists without the details, while View means you can see the details of a thing. But maybe @stianst remembers the original intention behind these verbs?

**Comment by pedroigor** [comment]
> To me it sounds like List/Query means you are able to see that a thing exists without the details, while View means you can see the details of a thing.

That is how I see it. And why I think we should consider the view permissions on the user (not for roles). If we change the code to:

```
.filter(auth.users()::canView))
```

We are sure access is granted because the admin is already granted to view (in the sense you mentioned above) the user. If that works for all, we can update the PR and proceed with merging it.

As a side note, the class changed in this PR is similar to `RoleMapperResource`. We have that one specifically for the Admin UI. The same for a few others that are "replicating/changing" existing endpoints from the Admin API. If you look how `RoleMapperResource` grants permission for user roles, it is using `requireVire` (see https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/UserResource.java#L654) which in turn uses `UserPermissions.canView` behind the scenes.

**Comment by andreas-blaettlinger** [comment]
@pedroigor I adjusted also the other endpoints. The view check is already in place with lines like:

- auth.users().requireView(user);
- auth.groups().requireView(group);
- ...

**Review by martin-kanis — APPROVED** [review]
Thanks all for the discussion. I think the current state of the PR make sense. 

@andreas-blaettlinger I think, you will need to sign your commit with `git commit -s` to satisfy failing DCO check.

**Comment by andreas-blaettlinger** [comment]
Yea thank you guys! @martin-kanis my bad, signed the commits now :)

**Comment by edewit** [comment]
I think originally this was added to have "composite" roles in the view as well

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@edewit Is it OK from UI perspective then? IIRC, the change here is basically granting view/list permissions to listing effective roles if the "target" entity is already granted with view permissions.

**Comment by edewit** [comment]
yeah it's fine

**Review by edewit — APPROVED** [review]

**Pull request merged**
