### PR TITLE
Adding support for nonce generation into auth requests

### PR DESCRIPTION
**Pull request by dennisrichter**
I added support for adding nonce to tomcat adapters:
https://issues.jboss.org/browse/KEYCLOAK-10798

### CODE REVIEW

**Comment by mposolda** [comment]
IMO for this one it will be good to start discussion on keycloak-dev ML first.

My suggestion is to not introduce the switch "use-nonce", but just always use nonce.

It will be also good to make sure that it works with all the java adapters. Having it supported just for the tomcat adapters is a bit pointless. IMO it can be useful if it uses the cookie similarly like it's used for the verification of "state" parameter. Cookies have generic support on HttpFacade interface, so should just work fine.

Will be good to also have a test in the adapters testsuite - ideally one test for success and one test for failure when nonce verification fails.

Finally the commit message should have JIRA number at the beginning, but that's just minor.

**Review by mposolda — CHANGES_REQUESTED** [review]
Thanks for the contribution. See comment above

**Comment by dennisrichter** [comment]
Hi, i decided to go with the switch because, depending on the container that has the AuthenticatorValve configured, this means requests can only be issued and used once (that's a nonce), meaning replay requests (attacks) are prevented.
Also i went with the session store to ensure there is no possibility that an attacker can tamper with the cookie. This is why i went with the session store. The principle is very simple:
1) user requests resource (not authorized)
2) authorization request and a freshly generated nonce are sent to Keycloak, nonce being stored in Catalina session
3) access and id token are generated with nonce
4) user requests resource, access is granted
5) nonce checked against session (ok)
6) nonce is being deleted from session

As is write this, i did notice that there are limitations to this approach:
1) the instance that generated this nonce is the only one that allows access (unless you run a fancy session replication)
2) you cannot issue a token for one time use and just hand it someone

There might be a smarter way to implement this using persistence. I'm not so sure about the Keycloak Cookie if this is safe against tampering. Any information on that?

**Comment by abstractj** [comment]
@dennisrichter thanks for taking the time by submitting this change, although I suggest to look at our [contributing guideline](https://github.com/keycloak/keycloak/blob/master/CONTRIBUTING.md) before. Like @mposolda mentioned, for enhancements, feature requests we require Jira, tests and also a discussion on keycloak-dev mailing list.

For now I'm closing this, but please reopen when you think it's ready.

**Pull request closed without merging**
