### PR TITLE
Make `post_logout_redirect_uri` configurable for legacy admin UI

### LINKED ISSUE #14246: post_logout_redirect_uri causes "invalid redirect_uri" for clients created in keycloak 19 with old admin console
### Describe the bug

On our dev system we have clients created in keycloak v17 and clients created in v19.

For example: 
`https://my.keycloak.com/realms/my-realm/protocol/openid-connect/logout?post_logout_redirect_uri=https://valid.redirect.uri&client_id=my-client` should work but did not, even though `https://valid.redirect.uri` is a valid `redirect_uri` configured in `my-client`.

I was able to compare export jsons of old and new clients and found this difference:
```
{
    ...
    "protocol": "openid-connect",
    "attributes": {
        "saml.force.post.binding": "false",
        "saml.multivalued.roles": "false",
        "post.logout.redirect.uris": "+", //<--- this line exists in old but not in the new clients
        "frontchannel.logout.session.required": "true",
        ...
```

This is also the way to hotfix this issue: 
* export the client
* delete exported client from keycloak
* add the line above to the exported json under `"attributes"` object
Line: `"post.logout.redirect.uris": "+"`
* import the edited json 
* redirect works again

### Version

19.0.0

### Expected behavior

That the valid redirect URIs in the client configuration are used to validate post logout redirect URIs.
Or have a separate configuration in each client for valid post-logout URIs.
And - of course - a successful redirect.

### Actual behavior

Error: invalid redirect_uri

### How to Reproduce?

* Create new client in keycloak v19
* log in to client successfully
* build post_logout_redirect_url using URL provided  in `end_session_endpoint` in `realms/my-realm/.well-known/openid-configuration`, adding the following URL params `client_id` & `post_logout_redirect_uri`
* see "Error invalid redirect_uri" both in browser and in logs
`keycloak_1  | 2022-09-06 16:10:00,122 WARN  [org.keycloak.events] (executor-thread-129) type=LOGOUT_ERROR, realmId=my-realm, clientId=null, userId=null, ipAddress=1.1.1.1, error=invalid_redirect_uri, redirect_uri=https://valid.redirect.uri`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by lexcao**
Closes #14246 

Added a configuration for `post_logout_redirect_uri` for legacy admin UI.
image

### CODE REVIEW

**Comment by sschu** [comment]
The failing test says: `AccountRestServiceTest.listApplicationsThirdParty:967 expected:<[]> but was:<[web-origins]>`. It seems to be unstable currently, I also had issues with it on other PRs.

**Review by mposolda — APPROVED** [review]
@lexcao Thanks for the PR!

And Thanks for all your recent Keycloak contributions!

One minor note: When you send PR next time, please include something like "Closes #14246" in the second line of the commit message. It is a policy to have something like that in the commit messages - for example see commit to Keycloak main: https://github.com/keycloak/keycloak/commit/3518362002676d0bb7629f8460956ca9277ca8dc . I can add it to the end of the commit message during the merge, but it is simpler when it is done by you when you are sending the PR (EG. it helps that PR is automatically linked with the GH issue)

**Comment by sschu** [comment]
@mposolda I would really like to see this in 19.0.2. Do you think that would be possible? I can provide a backport PR...

**Comment by mposolda** [comment]
@sschu I will doublecheck backporting this. If you can send PR to "19.0" branch with cherry-picked commit, it will be nice. I am not sure if it's too late for 19.0.2 release (It is possible that this release is already WiP). But hopefully at least 19.0.3.

**Comment by lexcao** [comment]
Hi, @mposolda 
Thanks for your mention.

I just added it to the GitHub PR but not in the commit message.
I will include that in the next PR.

**Comment by sschu** [comment]
@mposolda Done: https://github.com/keycloak/keycloak/pull/14342

@lexcao Thanks for your work. I was also going to do this, but you were faster... ;)

**Pull request merged**
