### PR TITLE
Fix Ingress creation/deletion loop

### LINKED ISSUE #12274: Ingress creation loop
### Describe the bug

The nightly operator stucks in an ingress creation loop, even when ingress creation is disabled.

First, the operator removes the Ingress when `disableDefaultIngress: true` and existing ingress is found. Then a new ingress is created again. And so on...
https://github.com/keycloak/keycloak/blob/8f54f03f17cbe985e763fb4ce101c569d2842740/operator/app/src/main/java/org/keycloak/operator/v2alpha1/KeycloakIngress.java#L46-L51

### Version

nightly

### Expected behavior

Ingress should not be created when `disableDefaultIngress: true`

### Actual behavior

Ingress is created, then removed, then created again in a loop manner.

### How to Reproduce?

Deploy nightly operator and apply a Keycloak CRD with `disableDefaultIngress: true`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by andreaTP**
Resolves #12274 

as agreed the logic is unit tested.

### CODE REVIEW

**Review by DGuhr — DISMISSED** [review]
LGTM, thanks for the quick fix! Have you also provided a PR to prod REL branch so we can backport it?

**Comment by andreaTP** [comment]
Thanks for the quick review @DGuhr , I will as soon as this gets merged.

**Comment by andreaTP** [comment]
I forgot to fix this line:
https://github.com/keycloak/keycloak/pull/12404/files#diff-00edd1bca104c131c6f17155aabc886316bd90bda62d2dd48a71f2b2298cdb9cR121

Let's hope the tests are green now 🤞

**Review by vmuzikar — APPROVED** [review]
@andreaTP LGTM, thank you!

**Comment by andreaTP** [comment]
@abstractj can we please, prioritize merging this PR as it should be backported to `18.0.1`?

**Pull request merged**
