### PR TITLE
CLI args not recognized when running Quarkus dev mode

### LINKED ISSUE #23253: CLI args not recognized when running Quarkus dev mode
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

Running:

```
mvn -f quarkus/server/pom.xml compile quarkus:dev -Dquarkus.args='start-dev --features=preview'
```

Does not enable preview features.

The reason is that the build steps to configure the `Profile` are executed before calling `KeycloakMain`. See https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java.

It was initially reported by @jonkoops and I'm not sure what is the change that introduced this issue. Perhaps related to the last Quarkus upgrade or by #19251.

### Version

22.0.3

### Expected behavior

Quarkus dev is working using CLI options.

### Actual behavior

Quarkus dev is not working using CLI options.

### How to Reproduce?

```
mvn -f quarkus/server/pom.xml compile quarkus:dev -Dquarkus.args='start-dev --features=preview'
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #23253

### CODE REVIEW

**Review by mabartos — APPROVED** [review]
The approach works for me; I don't see any problems with that. Everything works as expected. Thanks

**Review by vmuzikar — APPROVED** [review]
Approving based on @mabartos' review.

Thanks @pedroigor!

**Comment by mabartos** [comment]
Omg, we need to get rid of building the dependent modules during the Quarkus tests. The failures are caused by it in CI again :)

**Comment by pedroigor** [comment]
> Omg, we need to get rid of building the dependent modules during the Quarkus tests. The failures are caused by it in CI again :)

Sorry, could you elaborate? Anything I can do in a separate PR?

**Comment by mabartos** [comment]
@pedroigor It's not related to this PR. 

The thing is that when we execute the Quarkus tests, we use the `-am` Maven parameter. It'll build all dependent modules again on the particular module. For integration tests, all these modules are rebuilt:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Keycloak                                                           [pom]
[INFO] Keycloak Common                                                    [jar]
[INFO] Keycloak Core                                                      [jar]
[INFO] Keycloak Server SPI                                                [jar]
[INFO] Keycloak Server Private SPI                                        [jar]
[INFO] Keycloak Crypto Parent                                             [pom]
[INFO] Keycloak Crypto Default                                            [jar]
[INFO] Keycloak SAML Core Public API                                      [jar]
[INFO] Keycloak SAML Core                                                 [jar]
[INFO] Keycloak REST Services                                             [jar]
[INFO] Keycloak Crypto FIPS 140-2 Integration                             [jar]
[INFO] Keycloak JavaScript Adapter (JAR)                                  [jar]
[INFO] Keycloak Themes                                                    [jar]
[INFO] Keycloak Model Parent                                              [pom]
[INFO] Keycloak Legacy Database Support                                   [jar]
[INFO] Keycloak Legacy Database Support - Private classes                 [jar]
[INFO] Keycloak Model JPA                                                 [jar]
[INFO] Keycloak Model Java Annotations and Processor                      [jar]
[INFO] Keycloak Model Map                                                 [jar]
[INFO] Keycloak Model Map JPA                                             [jar]
[INFO] Keycloak Kerberos Federation                                       [jar]
[INFO] Keycloak LDAP UserStoreProvider                                    [jar]
[INFO] Keycloak Legacy Database Support - REST services                   [jar]
[INFO] Keycloak Model Infinispan                                          [jar]
[INFO] Keycloak Model Hot Rod                                             [jar]
[INFO] Keycloak Model Map File                                            [jar]
[INFO] Keycloak SSSD Federation                                           [jar]
[INFO] Keycloak Authz: Parent                                             [pom]
[INFO] Keycloak AuthZ: Policy Provider Parent                             [pom]
[INFO] Keycloak AuthZ: Common Policy Providers                            [jar]
[INFO] Keycloak Quarkus Parent                                            [pom]
[INFO] Keycloak Configuration API                                         [jar]
[INFO] Keycloak JavaScript Parent                                         [pom]
[INFO] Keycloak Account UI                                                [jar]
[INFO] Keycloak Admin UI                                                  [jar]
[INFO] Keycloak Administration UI                                         [pom]
[INFO] Admin UI REST extensions                                           [jar]
[INFO] Keycloak Quarkus Server Extension                                  [jar]
[INFO] Keycloak Quarkus Server Deployment                                 [jar]
[INFO] Keycloak Integration                                               [pom]
[INFO] Keycloak Client CLI                                                [pom]
[INFO] Keycloak Client Registration CLI                                   [jar]
[INFO] Keycloak Admin CLI                                                 [jar]
[INFO] Keycloak Client CLI Distribution                                   [pom]
[INFO] Keycloak Quarkus Server App                                        [jar]
[INFO] Keycloak Quarkus Server Distribution                               [pom]
[INFO] Keycloak Quarkus Test Parent                                       [pom]
[INFO] Keycloak Quarkus Server JUnit 5 Internal Test Framework            [jar]
[INFO] Keycloak Quarkus Server Integration tests                          [jar]
[INFO] 
``` 

You can notice the Themes module is included there, which consumes much time, and also UI modules, which are often unstable during the build for these tests.

Instead, we can leverage the cached artifacts. 
I've tried to make an improvement[1] around that, but there were some problems with ClassLoader and some modules.
I'll create an issue and look at it more deeply.
 
[1] https://github.com/keycloak/keycloak/pull/21952/commits/95fafa44979d0c48926544dbcef70c220ab1ca98

**Pull request merged**
