### PR TITLE
Refactor CacheExpirationTest for readability and structure

### LINKED ISSUE #9869: Improve readability of CacheExpirationTest
### Description

During investigation of this test failing in #9648 I found it hard to understand why CacheExpirationTest is structured in a way it is. This issue re-structure it to make it simpler and better understandable for future developers.

### Motivation

It should be clear why this test exists, what it does and how it achieves this.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #9869

### CODE REVIEW

**Comment by ahus1** [comment]
This refactoring tries to focus on the expiry of objects in the end, therefore not counting the objects so much, instead ensures that they are zero at the end.

Handling of putTime is removed, as test proved to be stable enough without it. Waiting for expiration is no longer timed, instead it relies of the timer set by inIndependentFactories.

**Comment by ahus1** [comment]
The test failures I see are due to unstable tests, and unrelated to that change. Should I create new issues for these unstable tests? Besides that, I think it is ready for review and merge. Thanks.

**Comment by hmlnarik** [comment]
Thanks @ahus1 for the refactor.

@martin-kanis I suspect the https://github.com/keycloak/keycloak/blob/100dbb8781d780d35ad0569222bcda3ef85bbe0a/testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/CacheExpirationTest.java#L91-L98 should be kept, is that correct?

> Handling of putTime is removed, as test proved to be stable enough without it. Waiting for expiration is no longer timed, instead it relies of the timer set by inIndependentFactories.

@ahus1 Could you please keep the `putTime` guard in the test. While locally it would (almost) always be fast enough, GH runners might be very slow given the cpu / mem limitations.

**Comment by ahus1** [comment]
@martin-kanis: The cache.get("1-2") / cache.get("1-2-3") is now called on every node, I assumed this would be ok. and I wouldn't need to call it only on that site. Please let me know what you think.

cc: @hmlnarik

**Comment by ahus1** [comment]
@hmlnarik - you asked to keep the putTime guard in the test. 

When we can risk to skip this test on a GitHub runner as the GitHub runner slow, I wonder how important this test actually is, and if it would make a difference when we would skip it all the time. This test is actually quite costly (~35 seconds per single run).

The previous assumeThat() wasn't effective as it was called from within another thread, and JUnit would never see the exception. The exception would then needed to be handled in inIndependentFactories() to ignore the complete test completely. The previous behavior was that a thread that timed out would terminate due to the exception, and the assert() statements below the block would still run. 

As the old version before stabilizing the Infinispan tests also swallowed this an other exceptions, the instability on the GitHub actions might have resulted from a different situation. 

Having said all that: I'd rather see if this test is really unstable due to timing on GitHub actions after this and the previous fixes, and then only apply this assume() when needed.

**Comment by martin-kanis** [comment]
> @martin-kanis: The cache.get("1-2") / cache.get("1-2-3") is now called on every node, I assumed this would be ok. and I wouldn't need to call it only on that site. Please let me know what you think.

I think these lines are not needed at all now because the do-while above will make sure that there are two instances of `AuthenticationSessionAuthNoteUpdateEvent` in the cache on the all nodes.

**Comment by martin-kanis** [comment]
One thing which puzzling me is that when I remove the `cache.get("1-2") / cache.get("1-2-3")` lines, the test passes but max number of instances of `AuthenticationSessionAuthNoteUpdateEvent` in memory is 6 instead of 10 for `jpa+cross-dc-infinispan` profile. So somehow the every node eventually has those entries in the cache but not on every node at the same time.

**Comment by ahus1** [comment]
@martin-kanis - I was just about to remove the asserts, then I saw your comment. The latest force-push now still contains them. There might be some optimization in Infinispan going on here, so I'd rather keep it. The main focus of this test is that it returns to zero.

**Review by martin-kanis — APPROVED** [review]
Thanks @ahus1!

**Review by hmlnarik — APPROVED** [review]
Approving per @martin-kanis 's approval. Thanks @ahus1!

**Pull request merged**
