### PR TITLE
Flaky test: AuthenticationSessionTest

### LINKED ISSUE #35015: Flaky test: org.keycloak.testsuite.model.session.AuthenticationSessionTest#testConcurrentAuthenticationSessionsRemoval
## org.keycloak.testsuite.model.session.AuthenticationSessionTest#testConcurrentAuthenticationSessionsRemoval
[Keycloak CI - Store Model Tests](https://github.com/keycloak/keycloak/actions/runs/11874364080/job/33090361740)

```
java.lang.AssertionError: expected null, but was:<BaseUpdater{cacheKey=861a0ba2-b51e-4365-a66d-d9bcf0e95542, cacheValue=RootAuthenticationSessionEntity [ id=861a0ba2-b51e-4365-a66d-d9bcf0e95542, realm=efa9659a-55e5-40c6-9492-d47e99086278 ], state=READ, versionRead=17}>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotNull(Assert.java:756)
	at org.junit.Assert.assertNull(Assert.java:738)
	at org.junit.Assert.assertNull(Assert.java:748)
...
```

```
java.lang.AssertionError: expected null, but was:<BaseUpdater{cacheKey=76ed64c6-6112-477d-893d-458d299b80af, cacheValue=RootAuthenticationSessionEntity [ id=76ed64c6-6112-477d-893d-458d299b80af, realm=f5c63e0c-37d7-46ef-a886-294b2f8656b0 ], state=READ, versionRead=25}>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotNull(Assert.java:756)
	at org.junit.Assert.assertNull(Assert.java:738)
	at org.junit.Assert.assertNull(Assert.java:748)
...
```

### PR DESCRIPTION
**Pull request by pruivo**
Workaround for flaky test AuthenticationSessionTest#testConcurrentAuthenticationSessionsRemoval

Closes #35015

### CODE REVIEW

**Review by graziang — APPROVED** [review]
@pruivo Thanks!

**Review by ahus1 — APPROVED** [review]
Approving based on @graziang's review.

**Comment by ahus1** [comment]
@pruivo - I assume this was cased by the latest authentication session changes. 

Is that flakiness we see here a serious issue that we would need to fix for the upcoming KC 26.1 release? If yes, please create a new bug issue, reference the upstream ISPN issue, add it to the 26.1 milestone, and mark it with the necessary priority.

**Comment by ahus1** [comment]
I assume we want to remove the workaround from the test suite once a ISPN release that includes the fix has arrived? Maybe we want to ensure that a ISPN upstream release is available at the time we release KC 26.1?

**Comment by pruivo** [comment]
Yes, we can remove the workaround. IMO, blocking KC 26.1 is not required except if you tell me that users are running a single-node multi-site Infinispan deployment. 
Even in this scenario, only the first user to log in would most likely hit it. Even if it happens, the session will expire.

**Comment by ahus1** [comment]
Thank you for the explanation. Please create an issue to track the removal of the workaround. Given the explanation, it would be a normal priority item with the chance to postpone it if no updated ISPN version in upstream would be available at the time KC 26.1 is released.

**Pull request merged**
