### PR TITLE
[KEYCLOAK-16139] Serialize the calls for groups tab on admin console

### PR DESCRIPTION
**Pull request by rmartinc**
Serializing part of the group calls to not call user membership methods at the same time (in ldap they can create groups and errors are displayed). Two main modifications:

* Function `refreshUserGroupMembership` and `refreshAvailableGroups` serializes the query and the count (one after the other). And they return the promise of the last call (to allow to do a `then` with it).
* The initial calls are now executed this way:

```javascript
    refreshUserGroupMembership().then(function() {
        refreshAvailableGroups();
        refreshCompleteUserGroupMembership();
    });
```

This way all the user group requests are done separately and the available group call takes into account new groups possibly discovered by the user query.

@mposolda commented about removing `refreshCompleteUserGroupMembership` which returns all the groups for the user. This is used to detect what groups are already assigned to the user (`join` button). We can remove the call because the endpoint detects the group is already assigned and returns no error. The idea would be only mark as assigned the groups we already know as assigned (from the visited pages). For the moment the PR contains the function (as it is now), if you prefer to remove it just let me know.

### CODE REVIEW

**Comment by abstractj** [comment]
@rmartinc could you please update your PR with integration tests?

**Comment by rmartinc** [comment]
Where are the tests for the JS/Console code? (I have just done tests for java.)

**Comment by mposolda** [comment]
@rmartinc Those are in "tests/integration-arquillian/tests/other/console" . However the thing is, that this PR does not change any functionality from the user's point of view, it is rather just re-structuring promises to avoid some concurrent REST calls. So IMO I don't think that this deserves any new tests to be added and I don't see how we can test this. I would just run the existing admin console tests to make sure they still pass after this refactoring is done and that should be enough testing for this IMO.

**Comment by mposolda** [comment]
https://keycloak-jenkins.com/view/pipelines/job/universal-test-pipeline-server/2303 : The tests passed with the exception of ClientMappersOIDCTest, which fails with latest keycloak master and it is unrelated to this PR

**Review by mposolda — APPROVED** [review]
@rmartinc Thanks again for the PR

**Pull request merged**
