### PR TITLE
Same SHA for operator images

### LINKED ISSUE #12507: `keycloak-operator` Docker images published from the same workflow should have the same SHA
### Description

Currently, we run several times the maven command to build and push the keycloak operator images.

Unfortunately, each build ends up having a different SHA due to https://github.com/quarkusio/quarkus/issues/676 despite not having any functional difference.

We should produce stable SHA references.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andreaTP**
Resolves #12507

A little improvement of the workflow comes along.

### CODE REVIEW

**Review by DGuhr — APPROVED** [review]
assuming that the undertow problem is the general problem that will be solved by merging #12505 - LGTM :)

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@andreaTP Thanks for the fix! I'm probably doing something wrong but I don't see how this produces images with the same SHA.

Image ID (the SHA saved in the txt file) is obviously different with each build (probably due to https://github.com/quarkusio/quarkus/issues/676) so even when we tag them and push them using Docker, the SHA is not the same.

Can you please share the steps to reproduce, what SHA should be the same between builds?

**Comment by andreaTP** [comment]
@vmuzikar with this change we run Maven once and we [iterate re-using](https://github.com/keycloak/keycloak/pull/12508/files#diff-f18ce8ea228681f1dadf510ac77301b0210bf980f3ccee2c7b8c3db51e7fac1fR62) one single Docker image.

The current implementation instead is re-creating and pushing multiple images using `mvn` commands.

**Review by vmuzikar — APPROVED** [review]
@andreaTP Thanks for clarifying! I see this is the culprit (multiple tags):
https://github.com/keycloak/keycloak/blob/a3346f6d1670b21cb5e9e2c9ffacb5cfcdfe557a/.github/workflows/release-operator-container.yml#L50-L51

LGTM.

**Comment by andreaTP** [comment]
For future reference:

> (multiple tags)

Correct, and multiple repositories as well (quay.io and docker.io).

**Review by vmuzikar — CHANGES_REQUESTED** [review]
Actually, this breaks the generation of K8s YAML resources setting up image to e.g. `keycloak/keycloak-operator:999-SNAPSHOT`.

**Comment by andreaTP** [comment]
@vmuzikar would you mind to elaborate, please. not sure I'm getting this.

**Comment by vmuzikar** [comment]
@andreaTP Sure. I meant this one:
https://github.com/keycloak/keycloak-k8s-resources/blob/18.0.0/kubernetes/kubernetes.yml#L208
And for a fix something along [these lines](https://github.com/keycloak-rel-testing/keycloak-rel/pull/28/files).

But I just realized we're doing this manually in this old release process. So this brings me to a question whether this is even worth fixing here with the new release process just around the corner.

**Comment by andreaTP** [comment]
@vmuzikar I'm sorry to say that I still don't understand.
This fix is for having the same SHA for published images and, as far as I can tell, it doesn't break(at least any further) any of the other existing automations/processes.
Can I kindly ask you to elaborate a little further on the possible issues that this PR will bring to the project?

Thanks in advance!

**Comment by vmuzikar** [comment]
@andreaTP Before this change, we were correctly generating the [image field in the K8s YAMLs](https://github.com/keycloak/keycloak-k8s-resources/blob/153d9308503380fa076780a01669e4c9751a0c69/kubernetes/kubernetes.yml#L208). That was thanks to the `quarkus.container-image.image` config value. This PR removes this config, so the [image field in the K8s YAMLs](https://github.com/keycloak/keycloak-k8s-resources/blob/153d9308503380fa076780a01669e4c9751a0c69/kubernetes/kubernetes.yml#L208) contains invalid value. But as I said:
> But I just realized we're doing this manually in this old release process.

We are not using the YAML files anyway in this old release process. But this process (and this GHA flow in particular) is going away in any case, so that's ok the YAML files are broken here.

I hope this helps. 🙂

**Pull request closed without merging**
