### PR TITLE
Upgrade to Quarkus 3.2.0.Final and QOSDK 6.2.0

### LINKED ISSUE #21272: Upgrade to Quarkus 3.2.0.Final
### Description

Upgrade to Quarkus 3.2.0.Final as soon as it is released

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes #21272

### CODE REVIEW

**Comment by vmuzikar** [comment]
@abstractj The netty CVE seems like an unrelated issue to Quarkus upgrade. Infinispan 14.0.10 (which we [use](https://github.com/keycloak/keycloak/blob/0d4e236f4b299995a5943c021c797f915521bd94/pom.xml#L86)) appears to be still [using](https://github.com/infinispan/infinispan/blob/14.0.10.Final/build/configuration/pom.xml#L186) Netty 4.1.91. Quarkus is [using](https://github.com/quarkusio/quarkus/blob/3.2.0.Final/bom/application/pom.xml#L141) Infinispan 14.0.9, which we [override](https://github.com/keycloak/keycloak/blob/0d4e236f4b299995a5943c021c797f915521bd94/quarkus/pom.xml#L59-L74) to 14.0.10. So if we want to bump the Infinispan and/or Netty version, I think we should do it separately.

**Comment by vmuzikar** [comment]
> I'd also say that we need to check the dependency versions to make sure they are aligned.

Updated bouncycastle and hibernate. Hopefully, we'll align more dependencies as part of https://github.com/keycloak/keycloak/pull/21078

**Comment by vmuzikar** [comment]
Actually, removed that bouncycastle property as it's not used anywhere anymore. :)

**Review by mabartos — APPROVED** [review]
@vmuzikar LGTM

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@vmuzikar @abstractj Just noticed I should have waited for your review. Sorry.

**Comment by abstractj** [comment]
@pedroigor nah, it's all good, thanks for merging Pedro.

**Pull request merged**
