### PR TITLE
KEYCLOAK-2604: Added Proof Key for Code Exchange support

### PR DESCRIPTION
**Pull request by willsr**
See KEYCLOAK-2604.

### CODE REVIEW

**Comment by stianst** [comment]
We have two PRs for the same thing: https://github.com/keycloak/keycloak/pull/3831

**Comment by patriot1burke** [comment]
2 Questions:

1) Why did you remove the admin console switch?  Seems like something the IDP might want to enforce for some clients.

2) Can you review this PR?  I think I want to take it over yours as it adds support for PKCE for our java adapter

https://github.com/keycloak/keycloak/pull/3831

You did some charset work that I don't see in the other PR.

**Comment by tnorimat** [comment]
Hi, Will and all.

I've reviewed your patch, I think our patch(#3831) includes your feature.

RFC 7636 is very important for keycloak, and it should be supported as soon as possible, but it seems that the review is pending.

To accelerate the process, could you agree to proceed the review based on our implementation (#3831) and help us the review ? > willsr If you have any idea, please tell me > stianst, patriot1burke.

This is because, in addition to your patch, we have following features and it will be much faster to begin from  #3831.

1) Strict RFC 7636 compliance
In addition to yours, we implement following checks

https://tools.ietf.org/html/rfc7636#section-4.1
https://tools.ietf.org/html/rfc7636#section-4.2
Authorization Endpoint -
     https://github.com/keycloak/keycloak/pull/3831/commits/88bfa563df56dc031aa7b2f5a56d772f10914c38#diff-edd254f99e029a615bd0544fceee689e
     line 53,54,74,123-126,274-330
Token Endpoint -
     https://github.com/keycloak/keycloak/pull/3831/commits/88bfa563df56dc031aa7b2f5a56d772f10914c38#diff-ec5f9626f53934cdc3ad494e198f1902
     line 67,68,86,539-550

And tests for the above are also included.

2) Client adapter
Java client adapter (for servlet-oauth) and tests are included

3) The same point
patriot1burke  said;
> Why did you remove the admin console switch? Seems like something the IDP might want to enforce for some clients.

 I agree on removing the admin console switch, we also do not have that.
 I think that RFC 7636 can detect Authorization Code Substitution (not mentioned in RFC 7636) which happens for confidential client.
   Details are shown in
   https://github.com/Hitachi/contributions/wiki/Description-of-RFC7636-for-keycloak
   > 1.2. Benefit
   > Authorization Code Substitution (not mentioned in RFC 7636)

Best Regards,

**Comment by willsr** [comment]
@tnorimat I agree. Your implementation in #3831 is more comprehensive than mine, and should be merged.
For reference, I removed the console switch, to be compliant with section 5 of RFC 7636. (https://tools.ietf.org/html/rfc7636#section-5)

**Comment by tnorimat** [comment]
Thank you very much for your accepting my proposal and sincere cooperation.
And I've read your reference and totally understood why you had removed the console switch.

**Pull request closed without merging**
