### PR TITLE
[KEYCLOAK-8070] - wrong expose headers when enable cors and policyenforcer

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by mhajas** [comment]
@pedroigor why our tests didn't catch this? Could you please add some test for it?

**Comment by pedroigor** [comment]
@mhajas, when trying to implement a test for this one I found some issues with `CorsExampleAdapterTest`. They should be fixed now by https://github.com/keycloak/keycloak/pull/5536.

Still, the mentioned test does not check for cors without headers set in adapter config. What explains the reason for not getting this if the test was running.

I need to figure out how to include a test for this scenario. I don't want to include another module into "test-apps". Maybe we can change somehow configuring during runtime ?

**Comment by pedroigor** [comment]
@mhajas, test added.

**Comment by mhajas** [comment]
Thanks @pedroigor.

**Review by mhajas — APPROVED** [review]

**Review by stianst — APPROVED** [review]

**Pull request merged**
