### PR TITLE
Enable virtual threads in Infinispan and JGroups by default

### LINKED ISSUE #33939: Enable virtual threads in Infinispan and JGroups by default
### Description

Enable virtual thread in Infinispan and JGroups. Testing didn't show any performance penalty and it decreases the number of live threads by ~20 (if my memory doesn't fail me). 

### Discussion

_No response_

### Motivation

The main motivator for this change is the JGroups thread pool. The max size of the JGroups thread pool is 200 threads and, for large deployments, it may not be enough. If the thread pool is exhausted, messages are dropped increasing the Keycloak response time. The dropped messages are retransmitted. 

With virtual threads, a per-task virtual thread pool is used. Not only does it reduce resource usage (platform threads are expensive, 2MB RAM per thread), but it never gets full. 

### Details

To enable virtual threads, the java option `org.infinispan.threads.virtual` must be set. I'm planning to enable it in the `KeycloakMain` class.

For JDK 17 deployment, this option has no effect since Virtual Threads are not available.

### PR DESCRIPTION
**Pull request by pruivo**
Closes #33939

### CODE REVIEW

**Comment by pruivo** [comment]
Infinispan logs when virtual threads are enabled
```
[kc-server] 2024-10-18 11:09:49,925 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Starting Infinispan embedded cache manager
[kc-server] 2024-10-18 11:09:50,132 INFO  [org.infinispan.CONTAINER] (ForkJoinPool.commonPool-worker-1) Virtual threads support enabled
```

**Review by ahus1 — APPROVED** [review]
Thank you for PR, looks good to me! Thank you for reducing Keycloak's memory usage and the need to configure things!

**Comment by ahus1** [comment]
@pruivo - the reasons that drove me to update the documentation: 

* I wanted to put more emphasis in the change log that the changes are backwards compatible and not breaking, as this is what we now promise with our minor releases
* The documentation of Keycloak focuses only on the current release, so I removed a reference to KC 26.0

**Comment by pruivo** [comment]
@ahus1 sounds good!

**Pull request merged**
