### PR TITLE
KEYCLOAK-5086:add Chinese translation into messages.

### PR DESCRIPTION
**Pull request by martinyunify**

### CODE REVIEW

**Comment by stianst** [comment]
Would it not be better to use utf-8 encoding?

**Comment by Martindlut** [comment]
I don't think so. Existing translation are in unicode.

**Comment by martinyunify** [comment]
@stianst I don't think so. Existing translation are in unicode.
Sorry I got a wrong id to send comments

**Comment by stianst** [comment]
What do you mean about existing translations are in unicode? You're adding new translations now. Look at:
https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources-community/theme/base/login/messages/messages_ja.properties

It uses utf-8 encoding which makes it readable on github when reviewing the PR. You can use tools to automatically convert the encoding or simply write a little Java snippet that does the job.

**Comment by martinyunify** [comment]
https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources-community/theme/base/login/messages/messages_ca.properties
https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources-community/theme/base/login/messages/messages_pt_BR.properties

I think Japanese translation is using wrong encoding. 
And java is based on unicode http://www.oracle.com/technetwork/java/javase/tech/intl-139810.html

**Comment by stianst** [comment]
Keycloak supports both unicode and utf-8 encoding. We added support for utf-8 encoding for exactly this reason. If you look at Japanese translation as I said it is readable on Github, while your translation in unicode is not. That makes it very hard to review PR to it. Please change the encoding to utf-8.

**Comment by stianst** [comment]
Most of the encodings you linked to there where added before we added support for utf-8.

**Comment by martinyunify** [comment]
@stianst Could you please review the change set? Thanks!

**Comment by stianst** [comment]
Thanks, I'll ask for someone to review this on the mailing lists.

**Comment by stianst** [comment]
I'd ideally like someone to review this before merging, but I'm not getting any volunteers on the mailing lists.

**Comment by martinyunify** [comment]
well, This tool is not widely used in china and I think one of the reason why it is not popular is language barrier. Maybe you can just merge it in order to let more user to adopt this tool first.

**Comment by chexxor** [comment]
I'm not a Chinese pro, but I recognize most of these phrases from my using Chinese apps. Seems legit.

**Comment by stianst** [comment]
Ok, thanks for the review.

**Comment by cetsupport** [comment]
@stianst, You are correct, we should add utf-8. Current version without utf-8 not works. Shall I create a PR for this one?

**Comment by stianst** [comment]
Sure

**Pull request merged**
