### PR TITLE
Client Policies : An executor rejecting all requests

### LINKED ISSUE #9097: Client Policies : An executor rejecting all requests
### Description

Creating an executor that reject all client's requests.

### Discussion

_No response_

### Motivation

In some situation, it is beneficial from the viewpoint of security to reject a request that meet some criteria. For example, some client is suspected to be compromised, keycloak want to block requests from this client. It can be achieved by disabling this client, but this proposal can incorporate other existing client policies' conditions.

### Details

- Add new executor `RejectRequestExecutor`.
- The executor does not holds any configuration.
- The executor throw ClientPolicyException(OAuthErrorException.INVALID_REQUEST, "not allowed request").

### PR DESCRIPTION
**Pull request by tnorimat**
fixes [#9097](https://github.com/keycloak/keycloak/issues/9097)

### CODE REVIEW

**Comment by tnorimat** [comment]
@stianst I've amended the commit message to follow the contribution rule and force-pushed it.

**Comment by mposolda** [comment]
@tnorimat This looks good to me and Thanks for it, But there are some coflicts. Could you please resolve the conflicts?

**Comment by tnorimat** [comment]
@mposolda I've resolved the conflicts.

**Review by mposolda — APPROVED** [review]
@tnorimat Thanks!

**Pull request merged**
