### PR TITLE
Updated keycloak.js with error messages to increase debuggability.

### PR DESCRIPTION
**Pull request by HNygard**

### CODE REVIEW

**Comment by stianst** [comment]
Thanks. Rather than simply passing a string in the error function it would be a lot more useful if it sent an object back. Something like:

{code}
{
   error: short-error-name,
   errorDescription: long-error-description,
   <other useful variables like response code, login iframe event data>
}

**Comment by stianst** [comment]
Closing due to lack of feedback

**Comment by HNygard** [comment]
WHAT?!
9 days ago you set yourself as assignee indicating that you would look at this.
Now you just throw away this pull request because of no feedback?
Way to inspire contributions!

You have no debug messages right now. It's horrible to work with.

cc @stianst

**Review by stianst — CHANGES_REQUESTED** [review]
Thanks. Rather than simply passing a string in the error function it would be a lot more useful if it sent an object back. Something like:

    {
       error: short-error-name,
       errorDescription: long-error-description,
       <other useful variables like response code, login iframe event data>
    }

**Comment by stianst** [comment]
Closing due to lack of feedback.

**Pull request closed without merging**
