### PR TITLE
Map Store Removal: Rename Legacy* classes

### LINKED ISSUE #24105: Map Store Removal: Rename Legacy* classes
### Description

During the Map Store development, several classes associated to the current store were renamed as `Legacy*` classes. Now that we are removing the Map Store, we have to revert these changes.

### PR DESCRIPTION
**Pull request by martin-kanis**
Closes #24105

### CODE REVIEW

**Review by mabartos — DISMISSED** [review]
Changes in the `quarkus` module LGTM.

**Review by sguilhen — APPROVED** [review]
I haven't tried KC locally with these changes, but they seem good to me!

**Review by vramik — APPROVED** [review]
Thank you @martin-kanis for the PR.

**Review by mabartos — APPROVED** [review]
Changes in the `quarkus` module LGTM. Failures for Quarkus IT job are not related; executed again.

**Review by mhajas — APPROVED** [review]
Thanks @martin-kanis! LGTM

**Pull request merged**
