### PR TITLE
KEYCLOAK-5385 add not null constraint for user_entity.not_before

### PR DESCRIPTION
**Pull request by vramik**

### CODE REVIEW

**Comment by hmlnarik** [comment]
This issue cannot be fixed this way - it would fail on startup because the checksums of the changesets would be different.

Proper way of fixing this issue is either adding by a default value (0) in a _new_ changeset or making the field in UserEntity nullable (Integer instead of int) with null converted to 0 in respective get methods. I'm slightly biased towards the latter as that would mean no change in database schema which is preferrable in this unfortunate situation.

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Please rework as per the comment above

**Comment by stianst** [comment]
We don't support migration from CR releases though so the checksums of changesets shouldn't be a problem?

**Comment by hmlnarik** [comment]
If this would be going to get into 3.3.0.Final then yes, please go on with merging this PR.

**Comment by stianst** [comment]
Merged and added to 3.3.x branch for 3.3.0.Final

**Pull request merged**
