### PR TITLE
Testing ldap connection should not process or bind the credentials

### LINKED ISSUE #30821: Testing connection to ldap on the settings page does not work in 25.0.1
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

Testing connection to ldap on the settings page does not work.

### Version

25.0.1

### Regression

- [x] The issue is a regression

### Expected behavior

success ldap test

### Actual behavior

After pressing the button "Test connection" on the ldap settings page , I get an error in the interface:
`Error when trying to connect to LDAP: 'UnknownError'`
 in the logs:
`{"timestamp":"2024-06-26T16:42:01.048130619+03:00","sequence":681143,"loggerClassName":"org.jboss.logging.Logger","loggerName":"WebApplicationException","level":"DEBUG","message":"Restarting handler chain for exception exception","threadName":"executor-thread-21","threadId":113,"mdc":{},"ndc":"","hostName":"iva-keycloak-test-1","processName":"QuarkusEntryPoint","processId":1,"exception":{"refId":1,"exceptionType":"org.keycloak.services.ErrorResponseException","message":"HTTP 500 Internal Server Error","frames":[{"class":"org.keycloak.services.ErrorResponse","method":"error","line":43},{"class":"org.keycloak.services.ErrorResponse","method":"error","line":36},{"class":"org.keycloak.services.resources.admin.TestLdapConnectionResource","method":"testLDAPConnection","line":96},{"class":"org.keycloak.services.resources.admin.TestLdapConnectionResource$quarkusrestinvoker$testLDAPConnection_d65ae9343a71f2736595679e81594225f9de5d6f","method":"invoke"},{"class":"org.jboss.resteasy.reactive.server.handlers.InvocationHandler","method":"handle","line":29},{"class":"io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext","method":"invokeHandler","line":141},{"class":"org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext","method":"run","line":147},{"class":"io.quarkus.vertx.core.runtime.VertxCoreRecorder$14","method":"runWith","line":582},{"class":"org.jboss.threads.EnhancedQueueExecutor$Task","method":"run","line":2513},{"class":"org.jboss.threads.EnhancedQueueExecutor$ThreadBody","method":"run","line":1538},{"class":"org.jboss.threads.DelegatingRunnable","method":"run","line":29},{"class":"org.jboss.threads.ThreadLocalResettingRunnable","method":"run","line":29},{"class":"io.netty.util.concurrent.FastThreadLocalRunnable","method":"run","line":30},{"class":"java.lang.Thread","method":"run","line":1583}]}}`
User synchronization continues to work without errors, the Sync all users button also works.

### How to Reproduce?

On the page for setting up a connection to ldap, click the button "Test connection" 

### Anything else?

_No response_

### LINKED ISSUE #31001: User Federation settings changing when saving
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

When saving the configuration for User Federation, the Bind credentials field is getting reset instead of saving.

### Version

25.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Save the new property as specified

### Actual behavior

Set the Bind Credentials.  Click Test Authentication, it works.  Click Save button.  Click Test Authentication, it now fails.

### How to Reproduce?

Import realm with user federation where the password is not correct.  Go to User federation tab,  correct the password (bind credentials).  Test authentication.  Save.  Test Authentication.

### Anything else?

I am including screen shots taken quickly as I set the password, tested, saved and tested again.  I circled the bind credentials field - you can see where the mask changes length when saved and no longer works.

ok
bad
save

I am also including the trace log when this happens.  
[kc.log](https://github.com/user-attachments/files/16068866/kc.log)

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #30821
Closes #31001

### CODE REVIEW

**Review by rmartinc — APPROVED** [review]
Thanks @pedroigor! LGTM!

**Review by jonkoops — APPROVED** [review]

**Review by stianst — APPROVED** [review]
Approving based on previous reviews

**Comment by puggimer** [comment]
I tested this by running from quay.io/keycloak/keycloak:nightly today (July 9th, 2024).  It still failed.
To make a better test case (I hope), I created a new realm.  Then I added an Active Directory ldap.   I tested connection, it passed.  I tested authentication, it passed (though the message it gave was "Successfully connected to LDAP".  Then I saved it.  Clicked test connection and it now fails.  Clicked test authentication it now fails.  Reset the BindCredentials to the original value and both test succeed until I save it, then they fail again.

I am attaching the new realm, and the trace log (though there is nothing in the log when the errors occur)
[realm-export.zip](https://github.com/user-attachments/files/16163400/realm-export.zip)
[keycloak.zip](https://github.com/user-attachments/files/16163401/keycloak.zip)

**Comment by rmartinc** [comment]
Argggh! It's because you are using email format for the bind DN and not a proper DN. If you use a Dn instead of the email of the admin proxy user in ldap it will work. I'm going to file a new issue. It's incredible the mess I did with such a simple change. Sorry.

**Comment by puggimer** [comment]
Hmmm - when I was given the credentials is was the email address and password which worked before.
Took me a while to find the DN for the account, but using that the issue goes away (well the mask still changes size, which is a bit weird to me, but inconsequential.
Thanks!!!

**Comment by rmartinc** [comment]
I created https://github.com/keycloak/keycloak/issues/31014 for the samaccountname@domain format.

**Comment by puggimer** [comment]
Thanks - but I think you meant to reference #31196

**Pull request merged**
