### PR TITLE
KEYCLOAK-11193 Allow JavaScript logging to be disabled

### PR DESCRIPTION
**Pull request by jonkoops**
This change adds a new option called `disableLogging` to the initialization of Keycloak to disable any logging to the console.

### CODE REVIEW

**Comment by mhajas** [comment]
Thank you very much for the PR @jonkoops. Could you please add a tracking issue in Jira? More information can be found [here](https://github.com/keycloak/keycloak/blob/master/CONTRIBUTING.md#contributing-to-keycloak).

**Comment by jonkoops** [comment]
@mhajas I've created a new Jira issue for this specific functionality.

**Comment by mhajas** [comment]
@jonkoops the PR looks good. I think this might be very useful. We are unable to test console logs in testsuite, so I would say it is ok this is missing tests (I tried it manually and it works as expected). However, what we need to add is documentation. Do you think you could open a PR for documentation with an explanation of your addition? It should be enough to add disableLogging option [here](https://github.com/mhajas/keycloak-documentation/blob/master/securing_apps/topics/oidc/javascript-adapter.adoc#initoptions)

**Comment by jonkoops** [comment]
@mhajas Yes, not a problem I will open up a PR there as well.

**Comment by jonkoops** [comment]
Documentation has been updated, I also pushed a small fix for the description in this PR.

**Review by mhajas — DISMISSED** [review]

**Review by ssilvert — DISMISSED** [review]

**Comment by jonkoops** [comment]
I haven't checked why the build on this is failing, I will do so after I come back from vacation in a week or so.

**Comment by jonkoops** [comment]
I've rebased the PR so there should be no merge conflicts any more. It seems that the CI is failing on some kind of connection error, I have no idea what is causing this. Running the test suite locally on my machine everything is green (see command below).

```
mvn clean install -f testsuite/integration-arquillian/pom.xml -Dtest=JavascriptAdapterTest -Djs.browser=firefox
```

@ssilvert @mhajas Any idea what might be causing these failures?

**Comment by mhajas** [comment]
Those tests are running in phantomjs by default (in Travis as well). Looks like phantomjs is complaining about this line for some reason: `fn.apply(null, arguments);`. Maybe phantomjs is lacking support for something that is necessary for this line to execute. You can run tests in phantom js by discarding -Djs.browser=firefox argument. 

I can come up with two options on how to proceed.
1. Change this PR to run on phantomjs
2. Get rid of phantomjs, if I can recall correctly almost all tests everywhere are running on chrome. The last missing puzzle is Travis. We are already using chrome in nodejs [repo](https://github.com/keycloak/keycloak-nodejs-connect/blob/master/.travis.yml) so it should be possible to use it here too.

@stianst WDYT? I am not sure, but I think there was already some discussion on this, but I don't recall the result. Should we use chrome in Travis? If yes should we add it to this PR or introduce a separate task?

**Comment by jonkoops** [comment]
@mhajas Great thanks, I will take a look at running the tests with PhantomJS and see if I can come up with a fix.

**Comment by mhajas** [comment]
> @mhajas Great thanks, I will take a look at running the tests with PhantomJS and see if I can come up with a fix.

@jonkoops Thanks.

**Comment by jonkoops** [comment]
@mhajas I am running the tests verbosely using `mvn clean install -f testsuite/integration-arquillian/pom.xml -Dtest=JavascriptAdapterTest -X` and I can't make heads or tails of what is failing (see below).


<details><summary>Logs</summary>
<p>

```
[INFO] Running org.keycloak.testsuite.javascript.JavascriptAdapterTest
Sep 10, 2019 4:42:47 PM org.keycloak.testsuite.arquillian.containers.MultipleContainersExtension register
INFO: Multiple containers extension registering.
16:42:47,547 INFO  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] arquillian.xml: /home/jon/Projects/personal/keycloak/testsuite/integration-arquillian/tests/base/target/dependency/arquillian.xml
16:42:47,683 INFO  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Registering container: auth-server-undertow
16:42:47,686 WARN  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Cannot load adapterImpl class for auth-server-undertow
16:42:47,687 WARN  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Cannot load adapterImpl class for auth-server-remote
16:42:47,695 WARN  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Cannot load adapterImpl class for auth-server-jboss-migration
16:42:47,695 INFO  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Registering container: app-server-undertow
16:42:47,699 WARN  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Cannot load adapterImpl class for auth-server-undertow-backend1
16:42:47,700 WARN  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Cannot load adapterImpl class for auth-server-undertow-backend2
16:42:47,700 INFO  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Container is disabled: auth-server-undertow-backend1
16:42:47,701 INFO  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Container is disabled: auth-server-undertow-backend2
16:42:47,701 INFO  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Container is disabled: auth-server-balancer-undertow
16:42:47,703 WARN  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Cannot load adapterImpl class for cache-server-cross-dc-1
16:42:47,704 WARN  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Cannot load adapterImpl class for cache-server-cross-dc-2
16:42:47,705 INFO  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Container is disabled: auth-server-balancer-cross-dc
16:42:47,705 INFO  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Container is disabled: auth-server-undertow-cross-dc-0_1
16:42:47,705 INFO  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Container is disabled: auth-server-undertow-cross-dc-0_2-manual
16:42:47,706 INFO  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Container is disabled: auth-server-undertow-cross-dc-1_1
16:42:47,706 INFO  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Container is disabled: auth-server-undertow-cross-dc-1_2-manual
16:42:47,707 WARN  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Cannot load adapterImpl class for auth-server-jboss-cross-dc-0_1
16:42:47,709 WARN  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Cannot load adapterImpl class for auth-server-jboss-cross-dc-0_2-manual
16:42:47,711 WARN  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Cannot load adapterImpl class for auth-server-jboss-cross-dc-1_1
16:42:47,713 WARN  [org.keycloak.testsuite.arquillian.containers.RegistryCreator] Cannot load adapterImpl class for auth-server-jboss-cross-dc-1_2-manual
Configuration of Arquillian Reporting extension:
report                                   xml
rootDir                                  target
file                                     target/arquillian_report.xml
template                                 template.xsl
reportAfterEvery                         class
language                                 en
maxImageWidth                            500
imageWidth                               100%
imageHeight                              100%

Configuration of Arquillian Browser Screenshooter:
rootDir                                  target/screenshots
screenshotType                           PNG
takeBeforeTest                           false
takeAfterTest                            false
takeWhenTestFailed                       true
takeOnEveryAction                        false

16:42:47,719 INFO  [org.keycloak.testsuite.drone.HtmlUnitScreenshots] Screenshots disabled as htmlUnit is used
16:42:48,292 INFO  [org.keycloak.testsuite.arquillian.AuthServerTestEnricher] 

SUITE CONTEXT:
Auth server: auth-server-undertow

16:42:48,294 INFO  [org.keycloak.testsuite.arquillian.AuthServerTestEnricher] 

TEST PROCESS INFO: 
Available processors: 8
Total memory: 619 MB
Max memory (Xmx): 1820 MB
Metaspace Max: 256 MB
Sep 10, 2019 4:42:48 PM org.jboss.arquillian.drone.webdriver.factory.remote.reusable.ReusedSessionPermanentFileStorage readStore
INFO: Reused session store is not available at /home/jon/.drone-webdriver-session-store, a new one will be created.
Sep 10, 2019 4:42:48 PM org.jboss.arquillian.container.impl.MapObject populate
WARNING: Configuration contain properties not supported by the backing object org.keycloak.testsuite.arquillian.undertow.KeycloakOnUndertowConfiguration
Unused property entries: {adapterImplClass=org.keycloak.testsuite.arquillian.undertow.KeycloakOnUndertow, enabled=true && ! false}
Supported property names: [bindHttpPortOffset, bindHttpsPort, keycloakConfigPropertyOverrides, route, bindHttpPort, bindHttpsPortOffset, remoteMode, workerThreads, resourcesHome, bindAddress]
16:42:48,336 INFO  [org.keycloak.testsuite.arquillian.undertow.KeycloakOnUndertowConfiguration] KeycloakOnUndertow will listen for http on port: 8180 and for https on port: 8543
Sep 10, 2019 4:42:48 PM org.jboss.arquillian.container.impl.MapObject populate
WARNING: Configuration contain properties not supported by the backing object org.keycloak.testsuite.arquillian.undertow.UndertowAppServerConfiguration
Unused property entries: {adapterImplClass=org.keycloak.testsuite.arquillian.undertow.UndertowAppServer, enabled=true}
Supported property names: [bindHttpPortOffset, bindHttpPort, bindAddress]
16:42:48,339 INFO  [org.keycloak.testsuite.arquillian.undertow.UndertowAppServerConfiguration] App server undertow will listen on port: 8280
16:42:48,339 DEBUG [org.keycloak.testsuite.arquillian.AuthServerTestEnricher] Starting auth server before suite
16:42:48,340 INFO  [org.keycloak.testsuite.arquillian.AuthServerTestEnricher] ************************auth-server-undertow*****************************************************************************
16:42:48,342 INFO  [org.keycloak.testsuite.arquillian.undertow.KeycloakOnUndertow] Starting auth server on undertow.
16:42:48,355 INFO  [org.keycloak.testsuite.KeycloakServer] Using jboss.server.data.dir /home/jon/Projects/personal/keycloak/testsuite/integration-arquillian/tests/base/target/keycloak-server-24420772154985824/data
16:42:48,355 INFO  [org.keycloak.testsuite.arquillian.undertow.KeycloakOnUndertow] Starting auth server on embedded Undertow on: http://0.0.0.0:8180
16:42:50,614 INFO  [org.infinispan.factories.GlobalComponentRegistry] ISPN000128: Infinispan version: Infinispan 'Infinity Minus ONE +2' 9.4.14.Final
16:42:51,744 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] Node name: node_293628, Site name: null
16:42:52,861 DEBUG [org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory] Initializing JPA connections
16:42:52,862 DEBUG [org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory] Database info: {databaseUrl=jdbc:h2:mem:test, databaseUser=SA, databaseProduct=H2 1.4.193 (2016-10-31), databaseDriver=H2 JDBC Driver 1.4.193 (2016-10-31)}
16:42:55,247 INFO  [org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider] Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
16:42:56,421 INFO  [org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider] Initializing database schema. Using changelog META-INF/example-changelog.xml
16:43:01,455 INFO  [org.keycloak.testsuite.arquillian.undertow.KeycloakOnUndertow] Auth server started in 13100ms on http://0.0.0.0:8180/auth
16:43:01,500 INFO  [org.keycloak.testsuite.arquillian.AppServerTestEnricher] 

TEST CONTEXT: org.keycloak.testsuite.javascript.JavascriptAdapterTest

Sep 10, 2019 4:43:02 PM org.jboss.arquillian.drone.webdriver.factory.HtmlUnitDriverFactory setClientOptions
INFO: Setting HtmlDriver web client options: {htmlunitCssEnabled=false, htmlunitHistoryPageCacheLimit=1}
16:43:02,551 INFO  [org.keycloak.testsuite.drone.KeycloakDronePostSetup] Configuring driver settings. implicitWait=750, pageLoadTimeout=10000
Sep 10, 2019 4:43:03 PM org.jboss.arquillian.drone.webdriver.binary.BinaryFilesUtils extract
INFO: Extracting zip file: /home/jon/.arquillian/drone/phantomjs/2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2 to /home/jon/Projects/personal/keycloak/testsuite/integration-arquillian/tests/base/target/drone/2a490bb643d5fc7365526daea8cec7c9
Sep 10, 2019 4:43:03 PM org.arquillian.spacelift.Spacelift$SpaceliftInstance <init>
INFO: Initialized Spacelift from defaults, workspace: /home/jon/Projects/personal/keycloak/testsuite/integration-arquillian/tests/base, cache: /home/jon/.spacelift/cache
16:43:08,110 ERROR [org.keycloak.testsuite.javascript.JavascriptAdapterTest] [JavascriptAdapterTest] null() FAILED
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 21.188 s <<< FAILURE! - in org.keycloak.testsuite.javascript.JavascriptAdapterTest
[ERROR] org.keycloak.testsuite.javascript.JavascriptAdapterTest  Time elapsed: 21.186 s  <<< ERROR!
java.lang.RuntimeException: Could not create statement
	at org.jboss.arquillian.junit.Arquillian.methodBlock(Arquillian.java:313)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:166)
	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:350)
	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:54)
	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:177)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Caused by: java.lang.IllegalStateException: Something bad happened when Drone was trying to download and prepare a binary. For more information see the cause.
	at org.jboss.arquillian.drone.webdriver.binary.handler.AbstractBinaryHandler.checkAndSetBinary(AbstractBinaryHandler.java:63)
	at org.jboss.arquillian.drone.webdriver.factory.PhantomJSDriverFactory.getCapabilities(PhantomJSDriverFactory.java:99)
	at org.jboss.arquillian.drone.webdriver.factory.PhantomJSDriverFactory.createInstance(PhantomJSDriverFactory.java:72)
	at org.jboss.arquillian.drone.webdriver.factory.PhantomJSDriverFactory.createInstance(PhantomJSDriverFactory.java:37)
	at org.jboss.arquillian.drone.webdriver.factory.WebDriverFactory.createInstance(WebDriverFactory.java:127)
	at org.jboss.arquillian.drone.webdriver.factory.WebDriverFactory.createInstance(WebDriverFactory.java:38)
	at org.jboss.arquillian.drone.impl.DroneConfigurator$1.createInstance(DroneConfigurator.java:112)
	at org.jboss.arquillian.drone.impl.CachingCallableImpl.call(CachingCallableImpl.java:44)
	at org.jboss.arquillian.core.impl.threading.ThreadedExecutorService$ContextualCallable.call(ThreadedExecutorService.java:88)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.arquillian.spacelift.execution.ExecutionException: Execution of a task failed. Unable to execute task UntarTool
	at org.arquillian.spacelift.execution.ExecutionException.prependMessage(ExecutionException.java:63)
	at org.arquillian.spacelift.execution.impl.FutureBasedExecution.unwrapException(FutureBasedExecution.java:71)
	at org.arquillian.spacelift.execution.impl.FutureBasedExecution.await(FutureBasedExecution.java:130)
	at org.jboss.arquillian.drone.webdriver.binary.BinaryFilesUtils.extract(BinaryFilesUtils.java:58)
	at org.jboss.arquillian.drone.webdriver.binary.handler.PhantomJSDriverBinaryHandler.prepare(PhantomJSDriverBinaryHandler.java:43)
	at org.jboss.arquillian.drone.webdriver.binary.handler.AbstractBinaryHandler.downloadAndPrepare(AbstractBinaryHandler.java:227)
	at org.jboss.arquillian.drone.webdriver.binary.handler.AbstractBinaryHandler.downloadAndPrepare(AbstractBinaryHandler.java:209)
	at org.jboss.arquillian.drone.webdriver.binary.handler.AbstractBinaryHandler.downloadAndPrepare(AbstractBinaryHandler.java:176)
	at org.jboss.arquillian.drone.webdriver.binary.handler.AbstractBinaryHandler.checkAndSetBinary(AbstractBinaryHandler.java:61)
	... 12 more
Caused by: java.io.IOException: unexpected end of stream
	at org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.getAndMoveToFrontDecode(BZip2CompressorInputStream.java:726)
	at org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.initBlock(BZip2CompressorInputStream.java:312)
	at org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.setupNoRandPartA(BZip2CompressorInputStream.java:846)
	at org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.setupNoRandPartB(BZip2CompressorInputStream.java:893)
	at org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.read0(BZip2CompressorInputStream.java:218)
	at org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.read(BZip2CompressorInputStream.java:173)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read(TarArchiveInputStream.java:656)
	at org.arquillian.spacelift.task.archive.UncompressTool.process(UncompressTool.java:120)
	at org.arquillian.spacelift.task.archive.UncompressTool.process(UncompressTool.java:36)
	at org.arquillian.spacelift.task.Task.run(Task.java:100)
	at org.arquillian.spacelift.task.Task$1.call(Task.java:71)
	... 4 more

16:43:08,115 INFO  [org.keycloak.testsuite.arquillian.undertow.KeycloakOnUndertow] Stopping auth server.
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   JavascriptAdapterTest.org.keycloak.testsuite.javascript.JavascriptAdapterTest » Runtime
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Keycloak Arquillian Integration TestSuite 8.0.0-SNAPSHOT SUCCESS [  1.200 s]
[INFO] Test apps .......................................... SUCCESS [  0.171 s]
[INFO] Test apps distribution ............................. SUCCESS [  2.109 s]
[INFO] Keycloak Authz: PhotoZ  Test Parent ................ SUCCESS [  0.147 s]
[INFO] Keycloak Authz Test: Photoz RESTful API ............ SUCCESS [  1.689 s]
[INFO] Keycloak Authz Tests: Photoz HTML5 Client .......... SUCCESS [  0.678 s]
[INFO] Keycloak Authz Tests: Photoz Authz Rule-based Policy SUCCESS [  0.404 s]
[INFO] Keycloak Authz Tests: Hello World Example .......... SUCCESS [  0.420 s]
[INFO] Keycloak Authz: Servlet Authorization Test ......... SUCCESS [  0.493 s]
[INFO] Keycloak Authz: Simple Servlet App with Policy Enforcer SUCCESS [  0.400 s]
[INFO] integration-arquillian-test-apps-servlets .......... SUCCESS [  0.871 s]
[INFO] Keycloak Test App Profile JEE ...................... SUCCESS [  0.514 s]
[INFO] integration-arquillian-test-apps-cors-parent ....... SUCCESS [  0.146 s]
[INFO] Angular Product Portal JS .......................... SUCCESS [  0.933 s]
[INFO] JAX-RS Database Service Using OAuth Bearer Tokens .. SUCCESS [  0.528 s]
[INFO] Fuse Test Applications ............................. SUCCESS [  0.148 s]
[INFO] Customer Portal - Secured in Karaf/Fuse ............ SUCCESS [  1.628 s]
[INFO] CXF JAXRS Example - Secured in Karaf/Fuse .......... SUCCESS [  0.835 s]
[INFO] CXF JAXRS Example - Secured in Karaf/Fuse 7 on Undertow SUCCESS [  0.731 s]
[INFO] CXF JAXWS Example - Secured in Karaf/Fuse .......... SUCCESS [  0.704 s]
[INFO] CXF JAXWS Example - Secured in Karaf/Fuse 7 on Undertow SUCCESS [  0.706 s]
[INFO] Product Portal - Secured in Karaf/Fuse ............. SUCCESS [  0.740 s]
[INFO] Product Portal - Secured in Karaf/Fuse 7 on Undertow SUCCESS [  1.160 s]
[INFO] Camel endpoint example - Secured in Karaf/Fuse ..... SUCCESS [  0.723 s]
[INFO] Camel endpoint example - Secured in Karaf/Fuse 7.0 on Undertow SUCCESS [  0.636 s]
[INFO] Keycloak Fuse Example - Features ................... SUCCESS [  0.522 s]
[INFO] Keycloak Examples - External Config ................ SUCCESS [  0.640 s]
[INFO] spring-boot-adapter-app ............................ SUCCESS [  0.701 s]
[INFO] Servers ............................................ SUCCESS [  0.143 s]
[INFO] Auth Server ........................................ SUCCESS [  0.145 s]
[INFO] Auth Server Services ............................... SUCCESS [  0.150 s]
[INFO] Auth Server Services - Testsuite Providers ......... SUCCESS [  2.656 s]
[INFO] Auth Server - JBoss ................................ SUCCESS [  0.149 s]
[INFO] Test Util .......................................... SUCCESS [  1.013 s]
[INFO] Auth Server - Undertow ............................. SUCCESS [  1.908 s]
[INFO] App Server ......................................... SUCCESS [  0.145 s]
[INFO] App Server - SPI ................................... SUCCESS [  0.449 s]
[INFO] App Server - JBoss ................................. SUCCESS [  0.144 s]
[INFO] App Server - Karaf ................................. SUCCESS [  0.141 s]
[INFO] App Server - Tomcat ................................ SUCCESS [  0.145 s]
[INFO] App Server - Undertow .............................. SUCCESS [  0.755 s]
[INFO] App Server - Jetty Parent .......................... SUCCESS [  0.147 s]
[INFO] Cache Server ....................................... SUCCESS [  0.139 s]
[INFO] Cache Server - JBoss Family ........................ SUCCESS [  0.142 s]
[INFO] Tests .............................................. SUCCESS [  0.223 s]
[INFO] Base TestSuite ..................................... FAILURE [ 43.212 s]
[INFO] Other Tests Modules ................................ SKIPPED
[INFO] Adapter Tests ...................................... SKIPPED
[INFO] Adapter Tests - JBoss .............................. SKIPPED
[INFO] Adapter Tests - Karaf .............................. SKIPPED
[INFO] Adapter Tests - WAS ................................ SKIPPED
[INFO] Adapter Tests - WLS ................................ SKIPPED
[INFO] SSSD tests 8.0.0-SNAPSHOT .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:13 min
[INFO] Finished at: 2019-09-10T16:43:08+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project integration-arquillian-tests-base: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jon/Projects/personal/keycloak/testsuite/integration-arquillian/tests/base/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project integration-arquillian-tests-base: There are test failures.

Please refer to /home/jon/Projects/personal/keycloak/testsuite/integration-arquillian/tests/base/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /home/jon/Projects/personal/keycloak/testsuite/integration-arquillian/tests/base/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
    at org.apache.maven.plugin.surefire.SurefireHelper.throwException (SurefireHelper.java:240)
    at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution (SurefireHelper.java:112)
    at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary (SurefirePlugin.java:364)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:1052)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:868)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :integration-arquillian-tests-base
```
</p>
</details>

Are you getting some other output?

**Comment by jonkoops** [comment]
@mhajas Looks like for some reason PhantomJS cannot use apply without providing the original context. I've changed the code to pass in the console as a context and this seems to resolve the issue.

**Review by mhajas — APPROVED** [review]
Thank you @jonkoops. If Phantomjs is happy, I am happy too.

**Review by ssilvert — APPROVED** [review]
Looks fine to me.

**Comment by jonkoops** [comment]
Whoops, pressed something by accident. Ignore the review request.

**Review by mhajas — APPROVED** [review]

**Comment by stianst** [comment]
Wouldn't it be better to have enableLogging option and have logging disabled by default?

**Comment by jonkoops** [comment]
Yeah, I would prefer that as well actually. In this case I tried to make things as much the same as they were as to not confuse users that might expect the logging to be there.

**Comment by jonkoops** [comment]
Well can't go back now :raised_hands:

**Comment by abstractj** [comment]
@jonkoops we can always go back, it's Git :)

**Comment by jonkoops** [comment]
Hahah, well I can make the changes @stianst proposed if you guys want. Makes sense to have the default behaviour be that the logging is disabled with an opt-in.

**Comment by stianst** [comment]
Why not just a new PR changing it to enableLogging?

**Comment by abstractj** [comment]
@jonkoops thank you and @stianst apologies about that. I didn't see your comment before merge it, just all the approvals in this PR.

**Comment by jonkoops** [comment]
No prob, I'll whip up a PR real quick. I'll update the documentation PR as well.

**Comment by jonkoops** [comment]
Ok, created a new PR. Should take a bit for the CI to complete. I'll update the documentation as well.

**Comment by jonkoops** [comment]
Documentation PR has also been updated, let me know if any further changes are needed :+1:

**Pull request merged**
