### PR TITLE
use logged in realm as default

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Review by agagancarczyk — APPROVED** [review]
LGTM!

**Review by ahus1 — COMMENTED** [review]
I see that this make the realm parameter introduced in #21554 optional, still it wouldn't make it backward compatible as it previously iterated over all realms. 

I don't see a parent issue linked here, so could you please share more about the motivation of this change and the situation where using the current realm would be the right thing to do?

**Comment by ssilvert** [comment]
> I see that this make the realm parameter introduced in #21554 optional, still it wouldn't make it backward compatible as it previously iterated over all realms.
> 
> I don't see a parent issue linked here, so could you please share more about the motivation of this change and the situation where using the current realm would be the right thing to do?

@ahus1 I believe the original motivation for adding the `currentRealm` param was to make the `whois` endpoint performant when you have many, many realms.  So if we added back the original logic then that would be broken again.

The reason we want a reasonable default is so that the `whois` call will not throw an NPE when the `currewntRealm` is missing.  This will also allow the old admin console to run.  While the old console is not supported, it is still used by development for comparison purposes and potentially by others in the community.

**Review by ahus1 — APPROVED** [review]
> This will also allow the old admin console to run.

Thank you @ssilvert for this explanation. This makes sense, although I am quite sure that the old admin console would depend on the original logic which wasn't added.

I'm approving this PR, so you can merge this PR you think this is sufficient to run the old Admin console.

**Pull request merged**
