### PR TITLE
Avoid NPE if RelayState is null and return a proper error

### LINKED ISSUE #24079: Could not process response from SAML identity provider - because "this.text" is null
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

identity-brokering

### Describe the bug

We have configured an AD based IDP with SAML v2.0 in Keycloak v22. When a user tries to login they get an unexpected error

```
2023-10-17 15:55:43,163 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-40) Uncaught server error: org.keycloak.broker.provider.IdentityBrokerException: Could not process response from SAML identity provider.
	at org.keycloak.broker.saml.SAMLEndpoint$Binding.handleLoginResponse(SAMLEndpoint.java:596)
	at org.keycloak.broker.saml.SAMLEndpoint$Binding.handleSamlResponse(SAMLEndpoint.java:679)
	at org.keycloak.broker.saml.SAMLEndpoint$Binding.execute(SAMLEndpoint.java:278)
	at org.keycloak.broker.saml.SAMLEndpoint.postBinding(SAMLEndpoint.java:189)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
	at java.base/java.util.regex.Pattern.split(Pattern.java:1262)
	at org.keycloak.broker.provider.util.IdentityBrokerState.encoded(IdentityBrokerState.java:66)
	at org.keycloak.services.resources.IdentityBrokerService.getAndVerifyAuthenticationSession(IdentityBrokerService.java:1057)
	at org.keycloak.broker.saml.SAMLEndpoint$Binding.handleLoginResponse(SAMLEndpoint.java:418)
	... 46 more
```

I do not see any obvious issues with the SAML response, though I am no expert. Some data is redacted to hide our customers identity

```xml
<samlp:Response ID="_cb4a52ac-5a1c-49de-bc77-b649d45cb3ae" Version="2.0" IssueInstant="2023-10-17T16:07:24.394Z" Destination="https://kcl.customer.cluster.region.aws.org/auth/realms/app/broker/samlapp/endpoint" Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified"
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
    <Issuer
        xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://ida.customer.com/adfs/services/trust
    
    </Issuer>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
    <Assertion ID="_69bc87bc-b69f-4f36-8c1e-a57df96aad24" IssueInstant="2023-10-17T16:07:24.394Z" Version="2.0"
        xmlns="urn:oasis:names:tc:SAML:2.0:assertion">
        <Issuer>http://ida.customer.com/adfs/services/trust</Issuer>
        <ds:Signature
            xmlns:ds=http://www.w3.org/2000/09/xmldsig#>
            <ds:SignedInfo>
                <ds:CanonicalizationMethod Algorithm=http://www.w3.org/2001/10/xml-exc-c14n# />
                <ds:SignatureMethod Algorithm=http://www.w3.org/2001/04/xmldsig-more#rsa-sha256 />
                <ds:Reference URI="#_69bc87bc-b69f-4f36-8c1e-a57df96aad24">
                    <ds:Transforms>
                        <ds:Transform Algorithm=http://www.w3.org/2000/09/xmldsig#enveloped-signature />
                        <ds:Transform Algorithm=http://www.w3.org/2001/10/xml-exc-c14n# />
                    </ds:Transforms>
                    <ds:DigestMethod Algorithm=http://www.w3.org/2001/04/xmlenc#sha256 />
                    <ds:DigestValue>D5wluEmrbn35Y++bfxp4mQ83h2+MTfUxxSCMecx933A=</ds:DigestValue>
                </ds:Reference>
            </ds:SignedInfo>
            <ds:SignatureValue>signature-redacted</ds:SignatureValue>
            <KeyInfo
                xmlns=http://www.w3.org/2000/09/xmldsig#>
                <ds:X509Data>
                    <ds:X509Certificate>cert-redacted</ds:X509Certificate>
                </ds:X509Data>
            </KeyInfo>
        </ds:Signature>
        <Subject>
            <NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">user</NameID>
            <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <SubjectConfirmationData NotOnOrAfter="2023-10-17T16:12:24.394Z" Recipient=https://kcl.customer.cluster.region.aws.org/auth/realms/app/broker/samlapp/endpoint />
            </SubjectConfirmation>
        </Subject>
        <Conditions NotBefore="2023-10-17T16:02:24.300Z" NotOnOrAfter="2023-10-17T17:02:24.300Z">
            <AudienceRestriction>
                <Audience>APPAWS</Audience>
            </AudienceRestriction>
        </Conditions>
        <AttributeStatement>
            <Attribute Name="SID">
                <AttributeValue>user</AttributeValue>
            </Attribute>
            <Attribute Name="Email">
                <AttributeValue>user.name@customer.com</AttributeValue>
            </Attribute>
            <Attribute Name="Firstname">
                <AttributeValue>User</AttributeValue>
            </Attribute>
            <Attribute Name="Lastname">
                <AttributeValue>Nam</AttributeValue>
            </Attribute>
        </AttributeStatement>
        <AuthnStatement AuthnInstant="2023-10-17T16:07:24.285Z" SessionIndex="_69bc87bc-b69f-4f36-8c1e-a57df96aad24">
            <AuthnContext>
                <AuthnContextClassRef>urn:federation:authentication:windows</AuthnContextClassRef>
            </AuthnContext>
        </AuthnStatement>
    </Assertion>
</samlp:Response>
```

### Version

22.0.0

### Expected behavior

user should be able to log in via their IDP initiated login

### Actual behavior

Error as above

### How to Reproduce?

Configure SAML v2.0 IDP with Active Directory backend

### Anything else?

I will not be able to reproduce the issue with a different version as this keycloak lives in a customer Kubernetes environment

### PR DESCRIPTION
**Pull request by rmartinc**
Closes https://github.com/keycloak/keycloak/issues/24079

Just avoiding the NPE when the `RelayState` parameter is not returned by the SAML IdP to the identity provider. This is something that I've seen several times in different issues. So better if the server returns a proper error instead of the NPE/500 error. With the PR the response is 400 and the message is unexpected error in the provider, an error trace is also dumped saying the `RelayState` was null when it should be returned by the IdP. Test added.

@pedroigor @hmlnarik @mhajas Take a look when you have time.

### CODE REVIEW

**Review by douglaspalmer — APPROVED** [review]
It would be good if the test verified the Error event too but none of the other tests do so I think it's fine.

**Comment by rmartinc** [comment]
Thanks @douglaspalmer! Yes, events are not checked at all in that test so I prefer not to add them for just the new one. The new test method is just to show the NPE is not there and a normal 400 is returned.

**Comment by ahus1** [comment]
@rmartinc - I see you asked for three reviewers initially, and then received a review from @douglaspalmer. 

Would you like to wait for more reviewers, or would you consider this ready to be merged?

**Comment by rmartinc** [comment]
Just asked for someone to review. :smile: I think it's OK with @douglaspalmer review, this is a simple NPE fix.

**Review by ahus1 — APPROVED** [review]
Approving as of @douglaspalmer's review. Thank you for this fix!

**Pull request merged**
