### PR TITLE
Fixes KEYCLOAK-7114 Fix localization for Welcome page - HTML/FTL

### PR DESCRIPTION
**Pull request by junezhang**
Fixes KEYCLOAK-7114 Fix localization for Welcome page - HTML/FTL
https://issues.jboss.org/browse/KEYCLOAK-7114

This PR is aim to add the language selector
1, When user haven't login, the language selector is on the top navigation
2, After user log in, the language selector is on the dropdown menu of User icon.
Like the attachment.

screen shot 2018-04-16 at 1 51 06 pm
screen shot 2018-04-16 at 1 50 56 pm

### CODE REVIEW

**Comment by junezhang** [comment]
@ssilvert Hello, Stan, In this PR, I would have thought that move the Login Button below the Main Title, but I found the content is blank. 
Would like to get your suggestion.

**Comment by ssilvert** [comment]
I was expecting that this PR would include translating all the text like I showed for the accountManagementTitle?  (see the JIRA)

I've already done the dropdown html in top-nav.component.html.  Can you remove yours so we won't have a conflict?  We can leave the one you did for index.ftl.

Just leave out the part about moving the login button.  It's a little tricky since it is controlled by javascript.  I'll have to take a closer look once everything else is done.  At that point we can just assign the JIRA to me.

**Comment by junezhang** [comment]
@ssilvert, thanks for your review.
- Update to use messages_en.properties instead of the text.
- Remove the update of top-nav.component.html

Please help to review it again, thanks.

**Comment by ssilvert** [comment]
I still don't see where you changed the English text in index.ftl.  It should be translated like I did for the title:

<title>${msg("accountManagementTitle")}</title>

**Comment by junezhang** [comment]
@ssilvert please check the line#134, the English text is `${msg("locale_en")}` Is it right?
screen shot 2018-04-18 at 9 48 45 am

**Comment by junezhang** [comment]
@ssilvert Could you help to review it again, please? I updated the rest of English text.

**Review by ssilvert — APPROVED** [review]
Approve

**Pull request merged**
