### PR TITLE
KEYCLOAK-18846 URL param kc_locale doesn't work on info and error pages

### PR DESCRIPTION
**Pull request by ch219318**
URL param kc_locale doesn't work on info and error pages

### CODE REVIEW

**Comment by ch219318** [comment]
@mposolda 
please review

**Review by stianst — CHANGES_REQUESTED** [review]
This is an incorrect fix. See https://github.com/keycloak/keycloak/issues/14025 for more details.

**Review by mposolda — APPROVED** [review]
@ch219318 Thanks and sorry for the late review

**Comment by stianst** [comment]
Closing as it's not the correct fix I'm afraid

**Pull request closed without merging**
