### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by andymunro**
@stianst, @pedroigor Can you review this change, which fixes a broken links.  The links to quick starts don't exist yet, but I believe these are the planned URLs.  

@mposolda Can you verify?

### CODE REVIEW

**Comment by andymunro** [comment]
We need to update this with RHBK quick starts once we have them.

**Review by ahus1 — APPROVED** [review]
Thank you for this PR. I removed changes around the quickstarts, as the the description ("Spring") didn't match the contents of the link ("JAXRS"). I also talked to Stian and while not all quickstarts will be available for RHBK, those listed will probably be available. 

Let's merge and backport the other changes, and double-check once the quickstart repo has been updated.

**Comment by ahus1** [comment]
@andymunro - please create a backport for this PR. Thanks!

**Comment by andymunro** [comment]
@ahus1 Do we need to ask @stianst to remove the Embargo, so I can backport it?

**Comment by ahus1** [comment]
@andymunro - you can prepare the PR regardless of the blocked branch. Only to merge it we then need Stian.

**Pull request merged**
