### PR TITLE
Update greek translation

### LINKED ISSUE #33352: Wrong translation issues in greek translation
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

translations

### Describe the bug

We use Keycloak on our site and recently we found two spelling mistakes when in translation from english to greek language. 
image-20240918-091513
image-20240918-091445

### Version

22.05

### Regression

- [ ] The issue is a regression

### Expected behavior

1. image-20240918-091513
It should be translated as "επιπλέον"

2. 
image-20240918-091445
It should be translated as "τον", because the word "κωδικός" is male noun. Word "το" is used for neutral singular gender.

### Actual behavior

1. It is translated "επιπλέων"

2. It is translated "το"

### How to Reproduce?

Just click to change between language

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nsotirakos**
I've updated the greek translation cause it had 50-100 typos/grammar issues. 

Closes #33352

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you for this contribution! Please ask a second greek native speaker to review your changes and comment in this pull request if they are good to be merged.

**Review by firstroad — APPROVED** [review]
LGTM! Well done @nsotirakos ! Thanks a lot!

**Comment by nsotirakos** [comment]
[heart]         Nikos Sotirakos reacted to your message:
________________________________

**Review by ahus1 — APPROVED** [review]
Thank you for the translation and the collaboration!

**Pull request merged**
