### PR TITLE
KEYCLOAK-6758

### PR DESCRIPTION
**Pull request by moremagic**

### CODE REVIEW

**Review by stianst — CHANGES_REQUESTED** [review]
Test is missing

**Comment by stianst** [comment]
@moremagic can you add some test to this please?

**Comment by moremagic** [comment]
I'm sorry

I do not know how to add a test and I can not add tests.
I will add as soon as I understand it.

**Review by patriot1burke — DISMISSED** [review]

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
Ideal would be to have a test here, but it's better to get the check for null included as it doesn't hurt regardless

**Comment by stianst** [comment]
Fixing merge conflicts in PR: https://github.com/keycloak/keycloak/pull/6580

**Pull request closed without merging**
