### PR TITLE
Upgrade tested version of Postgresql to 15

### LINKED ISSUE #21338: Update supported configuration for Postgresql 15
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ci

### Describe the bug

KC 22 will officially support Postgres 14 and 15, although only 15 will be tested.

### Version

latest

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by miquelsi**
Closes #21338

### CODE REVIEW

**Review by ahus1 — COMMENTED** [review]
Hi @miquelsi - thanks for creating the PR. Looking at the summary in this PR, I don't see a reference to an existing issue or description of a previous discussion or reference to a doc. 

Looking at the PostgreSQL docs, PostgreSQL 11 is the earliest version that is supported as of today, see https://www.postgresql.org/support/versioning/

So would we eventually test 11 and 15? Or only the very lastest version of PostgreSQL?

I see that the following docs point PostgreSQL 10 to be supported, see https://github.com/keycloak/keycloak/blob/76ee1be76cd20dbffe056a5a342843bf14266125/docs/guides/server/db.adoc#L24

**Comment by miquelsi** [comment]
> Hi @miquelsi - thanks for creating the PR. Looking at the summary in this PR, I don't see a reference to an existing issue or description of a previous discussion or reference to a doc.
> 
> Looking at the PostgreSQL docs, PostgreSQL 11 is the earliest version that is supported as of today, see https://www.postgresql.org/support/versioning/
> 
> So would we eventually test 11 and 15? Or only the very lastest version of PostgreSQL?
> 
> I see that the following docs point PostgreSQL 10 to be supported, see
> 
> https://github.com/keycloak/keycloak/blob/76ee1be76cd20dbffe056a5a342843bf14266125/docs/guides/server/db.adoc#L24

Sorry I didn't create an issue for this, let me do it.

It was agreed with @stianst that KC 22 would support Postgresql 15, but we first tested 14 during a transition period. I will update the documentation also.

**Comment by stianst** [comment]
The thought was we could test the latest version of PostgreSQL, and it would be safe enough to claim that we still support the older versions, without having to continuously test all versions. If we multiple vendors and versions the full list becomes fairly length.

**Comment by ahus1** [comment]
@miquelsi - as part of this PR, I assume it is safe to upgrade the docs from "10" to "11" as this is also the oldest version PostgreSQL supports. 

Maybe we could test at least version 11 and 15 and then claim that the versions in between are also supported. But I would need a discussion in the storage team on this first. 

So the change that I would support unless @stianst has a different perspective on this: 
* Update the community docs from "10" to "11-15" for PostgreSQL for now until we've discussed that in the storage team.
* The supported database versions the product release might then be only a subset - I leave that to other to decide that.

cc: @hmlnarik as you might have been involved in this in the past.

**Comment by ahus1** [comment]
@miquelsi / @stianst - sorry I need to comment again, I now read the docs that the heading is "supported databases" and the text then talks about "tested databases", which is actually a mismatch. 

As this PR changes the "tested database" version, "15" is now the correct value. Still the docs have room for improvement to clarify the "tested" vs. "supported" element. But this is a follow-up thing.

**Comment by stianst** [comment]
@ahus1 cool, can you review/approve/merge this one then? and follow-up with follow-ups? ;)

**Review by ahus1 — APPROVED** [review]
LGTM, will create follow-up docs to update other database, and discuss how we would want to update the docs to "supported" vs. "tested" databases.

**Comment by ahus1** [comment]
Follow-up issues: 

* https://github.com/keycloak/keycloak/issues/21349
* https://github.com/keycloak/keycloak/issues/21350

**Pull request merged**
