### PR TITLE
KEYCLOAK-11582 Fix ldap groups sync which fails when syncing back to MSAD

### PR DESCRIPTION
**Pull request by h1f1x**
Fixed LDAP search doesn't fetch more than 1000 groups when syncing back to MSAD.

The correct method (getAllLDAPGroups) already exists but was not used in `syncDataFromKeycloakToFederationProvider`.

### CODE REVIEW

**Comment by mhajas** [comment]
@h1f1x Could you please rebase? Also add Jira number (KEYCLOAK-11582) to commit message.

**Review by mposolda — CHANGES_REQUESTED** [review]
@h1f1x Thanks, besides the comments mentioned by @mhajas I have also one more minor concern: the variable ldapQuery declared on 453 is unused now with your changes. So it should be possible to remove the declaration of this variable on line 453 (it will effectively remove the whole try block, so one more line with bracket will need to be removed). Thanks

**Comment by h1f1x** [comment]
Fixed everything.

**Review by mposolda — APPROVED** [review]
@h1f1x Thanks!

**Pull request merged**
