### PR TITLE
SessionTimeoutsTest flaky test fix

### LINKED ISSUE #20983: Flaky test: org.keycloak.testsuite.model.session.SessionTimeoutsTest#testOnlineUserClientMaxLifespanSmallerThanSessionOverrideInClient
## org.keycloak.testsuite.model.session.SessionTimeoutsTest#testOnlineUserClientMaxLifespanSmallerThanSessionOverrideInClient
[Keycloak CI - Store Model Tests]()

```
java.lang.AssertionError: expected null, but was:<org.keycloak.models.sessions.infinispan.AuthenticatedClientSessionAdapter@d5e04ab>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotNull(Assert.java:756)
	at org.junit.Assert.assertNull(Assert.java:738)
	at org.junit.Assert.assertNull(Assert.java:748)
...
```

### PR DESCRIPTION
**Pull request by wburns**
Closes #20983

Due to the replication happening a later point, the test could run in such a way that the session replication write to the cache was performed after the session had already "expired". In this test specifically the maxIdle would be -2 which SessionTimeouts signals as it is expired. This value of -2 was then passed to the ISPN cache which is inferred to be it cannot expire via maxIdle and thus it would not expire.

Note that this is only one of two issues I identified with the flaky test, but this one happens much more frequently. Please check #20983 or other issues regarding the other issue with the test that is not fixed here.

### CODE REVIEW

**Review by martin-kanis — COMMENTED** [review]
@wburns Thank you for the investigation and the fix. It looks good to me, however some other model tests failed. I'm not able to reproduce the failures locally. 
I'm going to run more experiments in GHA to see if there is any problem.

**Comment by wburns** [comment]
> @wburns Thank you for the investigation and the fix. It looks good to me, however some other model tests failed. I'm not able to reproduce the failures locally. I'm going to run more experiments in GHA to see if there is any problem.

I am not familiar with the other tests, but is it possible the test was inserting expired entries on accident and assuming it was not expired? It could be related to needing a pause to assert that an entry was inserted at the proper time like you did in https://github.com/keycloak/keycloak/pull/21701

**Comment by wburns** [comment]
Rebased to main

**Comment by martin-kanis** [comment]
With the "fix", there is still one timeout. It is happening also in `main` as reported in https://github.com/keycloak/keycloak/issues/21665, where I put my findings. Therefore, I'm approving this PR.

**Review by martin-kanis — APPROVED** [review]

**Review by martin-kanis — CHANGES_REQUESTED** [review]
Actually, I just noticed the second commit. @wburns Can you please squash the commits?

**Comment by ahus1** [comment]
@wburns  / @martin-kanis - I think the second commit is a merge commit, and I can squash this when merging PR. Ideally I'd like to see only one commit (as Martin mentioned), but I can fix this (hopefully) by pressing the right buttons here.

**Review by ahus1 — APPROVED** [review]
Approving as per @martin-kanis's approval.

**Comment by wburns** [comment]
Oh weird, sorry about the merge commit. I thought the rebase button did a rebase :(

**Pull request merged**
