### PR TITLE
Making metrics with labels for embedded Infinispan the default

### LINKED ISSUE #25935: Create Infinispan metrics with labels instead of long metric names
### Description

When enabling metrics for Infinispan, the cache manager name and the cache name are part of the metric name which makes it difficult to iterate over all caches in dashboards.

Infinispan can be configured to do this using `<metrics names-as-tags="true" />`

### Discussion

_No response_

### Motivation

Simpler dashboard setup in tools like Grafana

### Details

I'll create a PR with the chances we've been using in Keycloak Benchmark for a while

### PR DESCRIPTION
**Pull request by ahus1**
Closes #25935

### CODE REVIEW

**Review by vmuzikar — COMMENTED** [review]
@ahus1 Thanks for the PR!

> Question to reviewers: is this really needed in the release notes?

I'd probably include this in the upgrading guide instead. It's changing some of the metrics names if I understand correctly, which makes it kinda a breaking change?

**Comment by ahus1** [comment]
@vmuzikar - ok, moved the contents to `changes-24_0_0.adoc`, and left only the pointer in `24_0_0.adoc`.

**Review by vmuzikar — APPROVED** [review]
@ahus1 Thanks! LGTM.

Not sure if we need another approve from someone from @keycloak/store?

**Comment by sschu** [comment]
@ahus1 Can you maybe use the chance to fix the typo "the the" here? https://github.com/keycloak/keycloak/blob/ddcaa6dcbf04f4c3283d090f2e3351113d0e3cf9/docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc#automatic-redirect-the-the-administration-console

**Comment by ahus1** [comment]
@sschu - please create a new PR for this as it is unrelated to this one. As it is a small correction to the documentation and we don't plan to backport it, feel free to create just a PR and mention me.

**Review by martin-kanis — APPROVED** [review]
LGTM, thanks Alexander.

**Pull request merged**
