### PR TITLE
Convert authz entities into interfaces

### LINKED ISSUE #9740: Convert authorization services entities into interface
### Description

Convert implementation of Map*Entity into interfaces in authorization services area

### PR DESCRIPTION
**Pull request by mhajas**
Closes #9740

### CODE REVIEW

**Review by martin-kanis — CHANGES_REQUESTED** [review]
Thanks Michal! Looks good but I'd just remove unused imports.

**Comment by mhajas** [comment]
Thanks for the review @martin-kanis!

**Review by martin-kanis — APPROVED** [review]
Thanks @mhajas. I believe the failure in Model tests is not relevant to this PR. Is that correct?

**Review by hmlnarik — APPROVED** [review]
Approving per @martin-kanis 's review

**Pull request merged**
