### PR TITLE
Support for MultivaluedString in dynamic fields (protocol mappers, Id…

### LINKED ISSUE #30168: Support MultivaluedString dynamic String fields (new admin-ui)
### Description

Keycloak already has ProviderConfigProperty.MULTIVALUED_STRING_TYPE for supporting multivalued dynamic String attributes like in Protocol and Identity Providers Mappers. Moreover, this type is used for cases that value is send in the back end as List<String>. However, new admin console can not render properly and save as a String possible fields  in Protocol and Identity Providers Mappers.

Keycloak official mappers does not use this value type. However, this value type is useful for custom mappers. We believe also that this field can be used to extend current Keycloak mappers to more appropriate way. Fe it will be nice HardcodedAttributeMapper to be able to support List<String> of hardcored attributes.

### Discussion

_No response_

### Motivation

Support ProviderConfigProperty.MULTIVALUED_STRING_TYPE for supporting multivalued dynamic String attributes like in Protocol and Identity Providers Mappers. 

### Details

_No response_

### PR DESCRIPTION
**Pull request by cgeorgilakis**
…entityProvider mappers)

Closes #30168
Signed-off-by: cgeorgilakis-grnet <cgeorgilakis@admin.grnet.gr>

### CODE REVIEW

**Comment by cgeorgilakis** [comment]
Example :
example_for_multivalue

**Comment by mposolda** [comment]
@cgeorgilakis Thanks, Could you please clarify what is the mapper, which you used in the screenshot? Does this improve how the mappers in the admin console are rendered?

ATM I am missing how just adding "stringify" property can cause improvements of the behaviour in the UI layer, but it is very possible that I am missing something in how this works...

**Comment by cgeorgilakis** [comment]
> @cgeorgilakis Thanks, Could you please clarify what is the mapper, which you used in the screenshot? Does this improve how the mappers in the admin console are rendered?
> 
> ATM I am missing how just adding "stringify" property can cause improvements of the behaviour in the UI layer, but it is very possible that I am missing something in how this works...

Mapper in the example is _HardcodedClaim_ protocol mapper (claim field).
A real case that we want - at least as extension- use this feature is Identity Provider _HardcodedAttributeMapper_ in _User Attribute Value_ field. We want it also in extension mappers.

ProviderConfigProperty.MULTIVALUED_STRING_TYPE is already used in fields that return List<String>.
However, if you try to add it in a protocol or Identity Provider mapper ProviderConfigProperty.MULTIVALUED_STRING_TYPE, ui will be rendered well. config of these mappers is Map<String, String>. However, save will be failed because it will try to send the map value as List<String>. 
With _stringify_, the value will convert to a String with '##' between values. So, mapper save will be successful. Furthermore, already saved values with '##' will be converted successfully and rendered as List<String>.

**Comment by edewit** [comment]
@cgeorgilakis unfortunately in some places these settings are stored as strings and some use maps, so changing it to all be strings can't work

**Comment by cgeorgilakis** [comment]
> @cgeorgilakis unfortunately in some places these settings are stored as strings and some use maps. Why can't you use Map<String, String> in this case?
> 
> Also this will add the option to add `stringfy` as an attribute, but on it's own that will not be enough you'll also have to change the ui to use it

Ui already supports it if 'stringfy' exists. See my screenshot. I could create a draft branch with a real example of it. You need to build and run it only.

I know that sometimes they are stored as String and other times as Map. How can we have a List<String> value configuration of a protocol mapper with a nice ui? Something like multivalue User attributes in User profile. We do not want user write value with '##' separator.

**Comment by edewit** [comment]
Regardless of the type when the the property type is `MULTIVALUED_STRING_TYPE` the UI renders this nice ui

**Comment by cgeorgilakis** [comment]
> Regardless of the type, when the the property type is `MULTIVALUED_STRING_TYPE` the UI renders this nice ui

Although you are right, when you click save an error is thrown and mapper is never saved.
This is because it is trying to send a representation Map<String, List<String>> instead of Map<String, String>.

**Comment by edewit** [comment]
This PR doesn't solve that issue though, closing

**Pull request closed without merging**
