### PR TITLE
KEYCLOAK-6455 Ability to require email to be verified before changing

### LINKED ISSUE #11875: Ability to require email to be verified before changing
### Description

Currently when the email is changed in the account management console or the admin console it is updated immediately. There should at least be an option on the realm to require the email to be verified first.

When the email is updated it should be added to a temporary attribute as unverified and an email sent to the user to verify. This should use required actions to drive the verification. When it is verified the email should be updated and the temporary email attribute should be removed.

See https://issues.redhat.com/browse/KEYCLOAK-6455

Pr is already open here https://github.com/keycloak/keycloak/pull/7943

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by reda-alaoui**
Fix #11875

This PR adds an UPDATE_EMAIL action (enabled by default) that can be used as an AIA or a required action. The action is associated with a single email input form. If the realm has email verification disabled, this action will allow to update the email without verification. If the realm has email verification enabled, the action will send an email update action token to the new email address without changing the account email. Only the action token triggering will complete the email update.

In the account application personal info (Keycloak V2), this PR turns the email input field into a permanent readonly field. If the UPDATE_EMAIL action is enabled, an "Update Email" link will allow to trigger UPDATE_EMAIL action as an AIA. If the UPDATE_EMAIL action is disabled, there will be no link and therefore no way to update the email from the personal info page.

This PR conditionally removes the email field from `login-update-profile.ftl` form:
- if the form is opened in a brokered identity context, the email field is kept
- otherwise, the email field is removed

keycloak-1
keycloak-2
keycloak-3
keycloak-4
keycloak-5
keycloak-6
keycloak-7
keycloak-8

### CODE REVIEW

**Comment by jbman** [comment]
> * if the form is opened in a brokered identity context, the email field is kept
> * otherwise, the email field is removed

Why should it be removed on a brokered context. It is still ok, to let a mapper copy the email value initially in a brokered identity context (Mapper mode "import"). Then it could be managed in the account at Keycloak including verification on updates.
Making any fields like email, first name or last name non-updateable is a different story and probably can not be solved within this PR.

**Comment by mabartos** [comment]
@reda-alaoui Well done! Could you please resolve the conflicts and rebase it with master? Then we can make a review for this. And last thing, I see there are some failing tests; it'd be great to check it.

**Comment by reda-alaoui** [comment]
Hi @mabartos ,
Sorry for my unresponsiveness.
I will fix the conflict and the test asap. I hope to do that this week.

**Comment by marziman** [comment]
@reda-alaoui many thanks for your work, mate.
This is actually an important PR. We really would need this for Security reasons.

Any chance you can please fix conflicts and tests?
That would be aweseome as it is open for some while now.

@stianst will this be possible to come into 16 or 17 release?

Thanks.

**Comment by reda-alaoui** [comment]
Hello,
I didn't forget the PR :)
But I didn't find the time yet. I hope to work on it by next week :pray:

**Comment by lajosthiel** [comment]
@marziman Would be really great to get this feature in the next release. I think it's one of the few major shortcomings of Keycloak at the moment because the current change email process is kind of error prone and a bit insecure. Would love to get this feature from core Keycloak and not have to implement my own workaround in the meantime just to ditch it again in a few months.

**Comment by marziman** [comment]
@lajosthiel I agree. We might be even forced to apply this now by hand to Keycloak.
@reda-alaoui let me know if we can help you in any matters. I think without your rebase and fixing tests, it wont be reviewed.
Your work is hihghly appreciated, and you see people are in line for this one :-)

BR Mehmet

**Comment by stianst** [comment]
This is an important change to get into Keycloak, but we'll have to target Keycloak 17 for it. Would be great if the PR could get rebased, and tests fixed, soon, then we can get a review priorities for this one.

**Comment by marziman** [comment]
> This is an important change to get into Keycloak, but we'll have to target Keycloak 17 for it. Would be great if the PR could get rebased, and tests fixed, soon, then we can get a review priorities for this one.

Thank you @stianst. Is it possible to know when KCv17.0 will be released? Just to prepare ourselfs if we can catch the version or we need to apply this by hands.

@reda-alaoui thanks for already touching it.

**Comment by stianst** [comment]
My current estimate for Keycloak 17 is towards the end of January '22. It was supposed to be earlier, but KC16 isn't even out yet, so...

**Review by mposolda — COMMENTED** [review]
@reda-alaoui Thanks for this nice contribution! The change itself looks good to me based on the description of the PR and the screenshots.

I did not deeply reviewed the PR (line by line) yet. From very quick spot, I don't see anything obvious.

**Comment by marziman** [comment]
@reda-alaoui I ve a question to this MR: 
We tried to use this without the KC UIs. Can it be that you developed this mainly for scenarios where Keycloak UI (Account page) etc. is used. How about using this by the REST API? Did you thought about this?

I think many folks might want to use this without being tight to the UI.

**Comment by reda-alaoui** [comment]
@marziman My approach was to consider that using the REST API is the same as using the Keycloak Admin UI.
If I am not mistaken, this approach is already broadly applied to the Keycloak project.

Therefore, this PR does not change the behaviour of the REST services regarding user email management.

`As a Keycloak user, I want to change my own email address` is the only use case covered by this PR.

**Comment by reda-alaoui** [comment]
Just to be sure, is the Keycloak team expecting any action from me?

**Comment by marziman** [comment]
@reda-alaoui I am not sure if we speak about the same. Lets say the Keycloak Admin / Account UI is not used at all. How can this email change feature be used at REST API. What I understood from the code in your PR, it is meant that the Admin console is used to click on „Change Email“. But what if a company uses Keycloak and do not propagate the Admin UI / Account SelfService page?

We could not fully see, how this will be working if only REST APIs without the Admin Console and its pages are used. Maybe you can shed some light on it or give us a pointer. We might got it wrong. Thank you 🙏🏻

@mabartos @mposolda @stianst as you mentioned to prioritize this PR, could you give a short signal what is missing to merge it? 

Many Thanks!

**Comment by reda-alaoui** [comment]
@marziman , IMO, you can’t use safely this feature without at least redirecting the end user to the Keycloak UI via https://github.com/keycloak/keycloak-community/blob/main/design/application-initiated-actions.md

**Comment by mposolda** [comment]
@reda-alaoui @marziman I am planning to look at the PR this week. From quick look, it is great work. I am planning some testing and possibly more deep review of the PR to doublecheck things.

**Comment by sschmiedleitner** [comment]
an update here - when will it be part of a release? I deparately need this and I bet this is something a lot of people need.

**Comment by marziman** [comment]
Any chance to get this into v17.0 Quarkus distro release please?

**Comment by reda-alaoui** [comment]
Merge conflict fixed.

**Comment by marziman** [comment]
@mposolda any chance to review and merge? 
I think @reda-alaoui did his part and fixed merge conflicts. Would be great!

**Comment by mposolda** [comment]
@marziman @reda-alaoui Yes, you are right and I am sorry for not yet reviewed this. I am stuck in some other priority work... :/

I hope to do that in the March.

One thing, which we discussed with @stianst would be to introduce some feature inside `Feature` enum of `org.keycloak.common.Profile` class and make sure that it is PREVIEW by default. When disabled, it should not be possible enable the flag in the admin console or admin REST API. Also the providers should be disabled (See for example `WebAuthnAuthenticatorFactory` and how it implements `EnvironmentDependentProviderFactory`, which means provider available just if feature enabled).

**Comment by reda-alaoui** [comment]
Merge conflict again :disappointed:

**Comment by marziman** [comment]
Hello @mposolda or @stianst,
will you find time to review this? I think @reda-alaoui already fixed second time merge conflicts.
It would be very kind if you give short update. Of course I understand many things are priority 1, but lets not forget that this is a great improvement of security for the email verification.

Thanks & BR
Mehmet

**Comment by marziman** [comment]
@reda-alaoui I am bumpin it last time, in hope it can get some review. We think to take it from here directly, as it doesnt get merged.

**Comment by reda-alaoui** [comment]
Merge conflicts fixed.

**Comment by webmozart** [comment]
@stianst Could you review this please?

**Comment by mabartos** [comment]
Hi guys! Thank you very much for your patience and understanding. I can ensure you that we didn't forget this PR to review. It's just a crazy time with a lot of tasks with high priority and we didn't have a chance to take a look at this further yet. I presume, it can be done in the following weeks. I'll execute tests in our test pipeline for that in order to verify that everything works as expected. 

Just a question. Does anybody already use this approach and encountered some issues with it? Thanks!

**Comment by reda-alaoui** [comment]
Merge conflicts fixed.

**Comment by mabartos** [comment]
@reda-alaoui Pipeline tests results seem quite good, but there's one failure for test case `UpdateEmailTest#navigationTest` with all tested browsers. It's possible to execute the tests with some browsers by adding the `-Dbrowser` property [1]. 

Could you please check it? Thank you

[1] https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/HOW-TO-RUN.md#different-browsers

Related log: 
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for wrapped: element to be clickable: GrapheneElement -> GrapheneElement -> [[[[FirefoxDriver: firefox on LINUX (d42f9a40-0b4b-4e40-a5f8-c6271b576168)] -> id: page-sidebar]] -> id: nav-link-personal-info] (tried for 5 second(s) with 500 milliseconds interval)
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'paas.psi.redhat.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-240.22.1.el8_3.x86_64', java.version: '1.8.0_311'
Driver info: org.openqa.selenium.firefox.FirefoxDriver$$EnhancerByGraphene$$11cadc95
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 87.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210318103112, moz:geckodriverVersion: 0.30.0, moz:headless: false, moz:processID: 12753, moz:profile: /tmp/rust_mozprofilejSnW8W, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.18.0-240.22.1.el8_3.x86_64, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: d42f9a40-0b4b-4e40-a5f8-c6271b576168
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:113)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:283)
	at org.jboss.arquillian.graphene.wait.WebDriverWaitImpl.until(WebDriverWaitImpl.java:96)
	at org.jboss.arquillian.graphene.wait.WebDriverWaitImpl.commit(WebDriverWaitImpl.java:102)
	at org.jboss.arquillian.graphene.wait.IsNotElementBuilderImpl.clickable(IsNotElementBuilderImpl.java:62)
	at org.keycloak.testsuite.util.UIUtils.clickLink(UIUtils.java:75)
	at org.keycloak.testsuite.ui.account2.page.fragment.Sidebar.lambda$clickNav$0(Sidebar.java:94)
	at org.keycloak.testsuite.ui.account2.page.fragment.Sidebar.performOperationWithSidebarExpanded(Sidebar.java:71)
	at org.keycloak.testsuite.ui.account2.page.fragment.Sidebar.clickNav(Sidebar.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.graphene.proxy.GrapheneProxyHandler.invokeReal(GrapheneProxyHandler.java:129)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$1.invoke(GrapheneContextualHandler.java:169)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$2.call(GrapheneContextualHandler.java:241)
```

**Comment by mabartos** [comment]
@reda-alaoui I've also encountered an issue with a non-localized error message on the update email page. 
image

When the login properties `User Registration` and `Email as username` are enabled, an error related to _read-only_ attribute occurs. Perhaps, it'd be good to verify the email can be updated already in the account console. WDYT?

**Comment by reda-alaoui** [comment]
@mabartos I will take a look at this asap

**Comment by reda-alaoui** [comment]
> @reda-alaoui Pipeline tests results seem quite good, but there's one failure for test case `UpdateEmailTest#navigationTest` with all tested browsers. It's possible to execute the tests with some browsers by adding the `-Dbrowser` property [1].
> 
> Could you please check it? Thank you
> 
> [1] https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/HOW-TO-RUN.md#different-browsers
> 
> Related log:
> 
> ```
> org.openqa.selenium.TimeoutException: 
> Expected condition failed: waiting for wrapped: element to be clickable: GrapheneElement -> GrapheneElement -> [[[[FirefoxDriver: firefox on LINUX (d42f9a40-0b4b-4e40-a5f8-c6271b576168)] -> id: page-sidebar]] -> id: nav-link-personal-info] (tried for 5 second(s) with 500 milliseconds interval)
> Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
> System info: host: 'paas.psi.redhat.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-240.22.1.el8_3.x86_64', java.version: '1.8.0_311'
> Driver info: org.openqa.selenium.firefox.FirefoxDriver$$EnhancerByGraphene$$11cadc95
> Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 87.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210318103112, moz:geckodriverVersion: 0.30.0, moz:headless: false, moz:processID: 12753, moz:profile: /tmp/rust_mozprofilejSnW8W, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.18.0-240.22.1.el8_3.x86_64, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
> Session ID: d42f9a40-0b4b-4e40-a5f8-c6271b576168
> 	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:113)
> 	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:283)
> 	at org.jboss.arquillian.graphene.wait.WebDriverWaitImpl.until(WebDriverWaitImpl.java:96)
> 	at org.jboss.arquillian.graphene.wait.WebDriverWaitImpl.commit(WebDriverWaitImpl.java:102)
> 	at org.jboss.arquillian.graphene.wait.IsNotElementBuilderImpl.clickable(IsNotElementBuilderImpl.java:62)
> 	at org.keycloak.testsuite.util.UIUtils.clickLink(UIUtils.java:75)
> 	at org.keycloak.testsuite.ui.account2.page.fragment.Sidebar.lambda$clickNav$0(Sidebar.java:94)
> 	at org.keycloak.testsuite.ui.account2.page.fragment.Sidebar.performOperationWithSidebarExpanded(Sidebar.java:71)
> 	at org.keycloak.testsuite.ui.account2.page.fragment.Sidebar.clickNav(Sidebar.java:94)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.jboss.arquillian.graphene.proxy.GrapheneProxyHandler.invokeReal(GrapheneProxyHandler.java:129)
> 	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$1.invoke(GrapheneContextualHandler.java:169)
> 	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$2.call(GrapheneContextualHandler.java:241)
> ```

@mabartos , the test is ok on my linux machine with `Chrome` and `Firefox`. Maybe a flacky test?

**Review by mposolda — CHANGES_REQUESTED** [review]
@reda-alaoui I've did a deeper review of this and it looks nice to me. This is great contribution and Thanks a lot for this! I hope we can have this available in Keycloak 19.

However as I pointed in the comment above (which you probably missed): https://github.com/keycloak/keycloak/pull/7943#issuecomment-1056555818, it will be good to have this available behind feature flag. Maybe the name of the feature can be directly `UPDATE_EMAIL` (not sure about better name right now) and it can be PREVIEW by default. In general, we try now to have most of the new features to be behind "feature flags" to have some flexibility if we want to improve/rewrite some features based on the feedback without need to care about backwards compatibility etc.

In the case when the feature is disabled, the behaviour should be ideally same as before so:
- The `UpdateEmail` required action provider won't be available. This can be done for example with the usage of `EnvironmentDependentProviderFactory` (See for example WebAuthn providers for the inspiration)
- The "Update profile" screen should still contain the email field and email should be updateable by the "Update Profile" required action
- The "email" field in the new account console should be writable and directly editable as before

This also means that this won't be the default required action (at least not now), which will also mean that migration changes can be reverted.

This will allow to revert some changes in the tests to make sure that old behaviour is still the same. But the new tests, which you already added, are able to test this functionality. Just a note that you will need to enable the feature in your new tests, which is doable with the `@EnableFeature` annotation (See for example `RecoveryAuthnCodesAuthenticatorTest` for the inspiration).

Also it will be good to write some documentation about this feature. Some possible places to update docs are:
https://www.keycloak.org/docs/latest/server_installation/#profiles - Your new feature can be listed here as the preview feature
https://www.keycloak.org/docs/latest/server_admin/index.html#controlling-login-options  maybe new section worth to be added here? With the note/warning that "Update Email" required action is available just with the feature enabled. See for example this section how this warning can look like: https://www.keycloak.org/docs/latest/server_admin/#_recovery-codes

**Comment by webmozart** [comment]
@mposolda Should this really be controlled by a feature flag? For me, turning on email confirmation but then not being able to guarantee that the email is actually confirmed is both a bug and a security implication. IMO this is not nice to have, but a must have in order to fix that feature.

**Comment by reda-alaoui** [comment]
> @reda-alaoui I've also encountered an issue with a non-localized error message (only name of message property) on the update email page. image
> 
> When the login properties `User Registration` and `Email as username` are enabled, an error related to _read-only_ attribute occurs. Perhaps, it'd be good to verify the email can be updated already in the account console. WDYT?

@mabartos , I fixed the message localization and made sure the email update link of the personal info page is not displayed when registration email is the username and username edition is disallowed.

**Comment by mposolda** [comment]
> @mposolda Should this really be controlled by a feature flag? For me, turning on email confirmation but then not being able to guarantee that the email is actually confirmed is both a bug and a security implication. IMO this is not nice to have, but a must have in order to fix that feature.

Thanks for your input. It is questionable if this can be considered a bug or rather enhancement (I personally see it as the latter). 

The point is, that this is change in the behaviour for users and having feature flag provides us some flexibility for eventually do some changes later based on the feedback and/or slightly change the behaviour without need to care about backwards compatibility. For example it is a chance that we will reuse this capability for other attributes as well and have this more integrated with the user profile (which is also preview feature right now).

**Comment by reda-alaoui** [comment]
@mposolda It is ready for review. I am polishing my PR for the documentation.

**Comment by reda-alaoui** [comment]
@mposolda I added 2 commits that seemed important to me. Sorry for the noise.

**Comment by yoransabern** [comment]
Has anyone recreated this issue in github issues yet? Would like to follow the progression again now that the original redhat issue is closed https://issues.redhat.com/browse/KEYCLOAK-6455

**Comment by alexted** [comment]
@yoransabern you could create it yourself

**Comment by yoransabern** [comment]
Thats alright, I just wanted to make sure there's no duplicate or if it needed to be linked to this pr somehow. Anyway here's he new issue on github https://github.com/keycloak/keycloak/issues/11875

**Review by mposolda — APPROVED** [review]
@reda-alaoui Thanks for the changes!

I am approving. I've just added one small note to the documentation PR and requested review from our documentation guru. However I hope that documentation will be finished soon and this will be merged soon.

**Comment by reda-alaoui** [comment]
Thank you ! :partying_face:

**Comment by mposolda** [comment]
@reda-alaoui Finally merged. Should be ready in Keycloak 19. Thanks for your patience and for your hard work on this issue!

**Comment by marziman** [comment]
Many thanks @reda-alaoui for this hard work. And also thx @mposolda for the review.
Would be great to have it in KC v19.0.

**Comment by sparkmylife** [comment]
@reda-alaoui Thanks for your work, we have got the latest V19.0.1 for keycloak. This feature works fine when we enable update_email. But once we enable the "User Profile Enabled" from Realm General setting, we are getting error while confirming new email id on update. 
image

**Comment by sparkmylife** [comment]
> 

@reda-alaoui Also we find that when "User Profile Enabled" is disabled, first name and last name became empty, and clicking on the email validation link.

**Comment by reda-alaoui** [comment]
@sparkmylife please create new issues to report this kind of problems.

**Comment by sparkmylife** [comment]
@reda-alaoui Raised https://github.com/keycloak/keycloak/issues/13561

**Comment by megicivovic** [comment]
Hi all, do you maybe have any info, when will this PR be released? which Keycloak version?

**Comment by Guesch** [comment]
Hey there.

I'm using "email as username" (& enabled "Edit username" specifically for this); but when the users are changing their email using this feature, the username is not updated at all.
Considering that the "change email" button is specifically not displayed if "Edit username" is not enabled for those using "email as username", I reckon this is a bug isn't it?

Or did I miss any settings anywhere that would allow for this feature to properly change both email & username?

**Comment by pedroigor** [comment]
@Guesch It should be fixed by https://github.com/keycloak/keycloak/pull/22393.

Can you please tell me in which context (Admin API, Update Profile, Account, etc) are you trying to update the e-mail?

**Comment by Guesch** [comment]
> @Guesch It should be fixed by #22393.
> 
> Can you please tell me in which context (Admin API, Update Profile, Account, etc) are you trying to update the e-mail?

I have been trying using the Keycloak "Personal information update" UI. Going through all the steps expected from this PR (click on update email, form asking me what email I want to use, confirmation email with link sent, clicking on the link to validate the change). Email is properly changed but not the username.

We have our own Account Management page so eventually we will want to have it work outside of the KC default UI; but the testing in the default UI is not conclusive already ;(

Happy to be told this is a misconfiguration on my end though!

**Comment by pedroigor** [comment]
It looks more like a bug. Which version you are using?

**Comment by Guesch** [comment]
> It looks more like a bug. Which version you are using?

v20.0.2 if I'm not mistaken

**Comment by pedroigor** [comment]
It should be a bug then. I would ask you to try out 21.1.2 or wait for 22.0.2.

The PR I mentioned is fixing a nasty issue in 22.0.0 and 22.0.1 so better try out 22.0.2.

**Pull request merged**
