### PR TITLE
Upgrade to Quarkus 3.7.3

### LINKED ISSUE #26799: java.lang.IndexOutOfBoundsException when using relative path
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Request to /auth throws java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### Version

23.0.6

### Expected behavior

No exception

### Actual behavior

I use the bitnami helm chart with `httpRelativePath: "/auth/"` which causes an exception when making requests to https://url/auth but no exception to https://url/auth/

### How to Reproduce?

Deploy keycloak with `httpRelativePath: "/auth/"` and make a request to url/auth

### Anything else?

Also documented here:  https://github.com/aerogear/keycloak-metrics-spi/issues/190

### LINKED ISSUE #27036: Upgrade to Quarkus 3.7.3
### Description

https://github.com/quarkusio/quarkus/releases/tag/3.7.3

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes #27036

### CODE REVIEW

**Review by mabartos — APPROVED** [review]

**Review by abstractj — APPROVED** [review]

**Comment by ghenadiibatalski** [comment]
@vmuzikar  Would you please backport it to 23.0.x?

**Comment by vmuzikar** [comment]
@ghenadiibatalski Sorry, we're backporting only micro Quarkus releases. Major/minor often introduce braking cganges which we need to reflect at Keycloak's end and as such introduce a regression risk. Is there any reason in particular you need Quarkus 3.7 backported to Keycloak 23? 23 is using Quarkus 3.2 LTS which still receives security fixes.

**Comment by ghenadiibatalski** [comment]
@vmuzikar only because of this bug: https://github.com/keycloak/keycloak/issues/26799 , i don't know, if it affects the functionality beyond the metrics https://github.com/aerogear/keycloak-metrics-spi/issues/190

**Comment by vmuzikar** [comment]
@ghenadiibatalski I see. It will be fixed in the upcoming Keycloak 24.

**Comment by ghenadiibatalski** [comment]
@vmuzikar  okay thanks, i'll wait for 24. and hope, there are no breaking changes as we need the regression :-)

**Comment by michbeck100** [comment]
I've created a PR to back port the fix to Quarkus 3.2: https://github.com/quarkusio/quarkus/pull/38981.

**Pull request merged**
