### PR TITLE
KEYCLOAK-6262 Incorporate new visual design from PatternFly

### PR DESCRIPTION
**Pull request by junezhang**
Currently, UXD team finished the new login design in PatternFly. http://www.patternfly.org/pattern-library/application-framework/login-page/

### This PR is for
-  incorporating the new visual design from PatternFly to Keycloak.
-  updating the latest PatternFly

#### Basic Login Page (no social provider)
screen shot 2018-02-07 at 6 30 08 pm

Responsive Design (on mobile)
screen shot 2018-02-07 at 6 32 37 pm

#### Login with social provider
One column (when the amount is less or equal 4)
screen shot 2018-02-07 at 6 35 54 pm

Two columns (when the amount is more than 4)
screen shot 2018-02-07 at 6 34 59 pm

Responsive Design (on mobile)
screen shot 2018-02-07 at 6 36 05 pm

### CODE REVIEW

**Comment by stianst** [comment]
The updated PatternFly files are they from a released version of PatternFly? How did you update those?

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
Merged this too early by mistake. I've reverted the changes, could you send a new PR please?

**Comment by junezhang** [comment]
@stianst Sure, I will do it later.

**Comment by stianst** [comment]
PatternFly 3.38.1 is landed in master - https://github.com/keycloak/keycloak/pull/4979

**Pull request merged**
