### PR TITLE
Use `crypto.randomUUID()` instead of `uuid` module

### LINKED ISSUE #35714: Replace `uuid` module with `crypto.randomUUID()`
### Description

The `crypto` global is available in all supported Node.js versions as well as [in all major browsers](https://caniuse.com/mdn-api_crypto_randomuuid). The uuid module is rendered unnecessary for uuidv4.

### Discussion

_No response_

### Motivation

Less dependencies.

### Details

_No response_

### PR DESCRIPTION
**Pull request by nikeee**
The `crypto` global is available in all supported Node.js versions as well as [in all major browsers](https://caniuse.com/mdn-api_crypto_randomuuid). The uuid module is rendered unnecessary for uuidv4.

Closes #35714

### CODE REVIEW

**Review by jonkoops — DISMISSED** [review]
LGTM, but please also run the tests locally to ensure things work in all browsers.

**Comment by nikeee** [comment]
I ran some tests locally. Some failed, but I suspect that they are just flaky tests.
The tests that were directly changed in this PR (e.g. `authentication_test.spec.ts`, `authentication_policies_ciba.spec.ts`) still pass.

<details>
<summary>
Chrome
</summary>
````
     Spec                                              Tests  Passing  Failing  Pending  Skipped  
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ✖  authentication_policies.spec.ts          02:07        3        2        1        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  authentication_policies_ciba.spec.t      00:06        3        3        -        -        - │
│    s                                                                                           │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  authentication_test.spec.ts              00:51       36       35        -        1        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  client_authorization_test.spec.ts        00:35       12       11        -        1        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  client_registration_policies.spec.t      00:10        9        9        -        -        - │
│    s                                                                                           │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✖  client_scopes_test.spec.ts               06:58       25       22        3        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  clients_saml_advanced.spec.ts            00:05        2        2        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  clients_saml_test.spec.ts                00:25        9        9        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✖  clients_test.spec.ts                     02:50       64       63        1        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  events_test.spec.ts                       61ms       41        -        -       41        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  group_test.spec.ts                       01:00       46       46        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  i18n_test.spec.ts                        00:07       10        9        -        1        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  identity_providers_oidc_test.spec.t      00:23        6        6        -        -        - │
│    s                                                                                           │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  identity_providers_saml_test.spec.t      00:38       13       13        -        -        - │
│    s                                                                                           │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✖  identity_providers_test.spec.ts          03:08       31       29        1        1        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  masthead_test.spec.ts                    00:11        9        9        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  organization.spec.ts                      27ms        6        -        -        6        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  partial_export_test.spec.ts              00:04        3        3        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  partial_import_test.spec.ts              00:08        5        5        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  realm_roles_test.spec.ts                 00:36       22       22        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  realm_settings_client_policies_test      00:28       18       18        -        -        - │
│    .spec.ts                                                                                    │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  realm_settings_client_profiles_test      00:36       23       23        -        -        - │
│    .spec.ts                                                                                    │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  realm_settings_events_test.spec.ts       00:39       22       21        -        1        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  realm_settings_general_tab_test.spe      00:17       17       17        -        -        - │
│    c.ts                                                                                        │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  realm_settings_tabs_test.spec.ts         00:59       35       35        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  realm_settings_user_profile_enabled      00:48       14       14        -        -        - │
│    .spec.ts                                                                                    │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✖  realm_test.spec.ts                       02:20        6        5        1        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  realm_user_registration.spec.ts          00:04        3        3        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  sessions_test.spec.ts                    00:11       13        8        -        5        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  user_fed_kerberos_test.spec.ts           00:37       14       13        -        1        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  user_fed_ldap_hardcoded_mapper_test      00:43       12       12        -        -        - │
│    .spec.ts                                                                                    │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  user_fed_ldap_mapper_test.spec.ts        00:49       15       15        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✖  user_fed_ldap_test.spec.ts               03:39       21       20        1        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  user_fed_test.spec.ts                    00:01        1        1        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  users_attribute_search_test.spec.ts      00:04        2        2        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  users_enable_disable.spec.ts             00:09        3        3        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  users_test.spec.ts                       01:27       44       44        -        -        - │
└────────────────────────────────────────────────────────────────────────────────────────────────┘
  ✖  6 of 37 failed (16%)                     34:28      618      552        8       58        -  
````
</details>

<details>
<summary>
Firefox
</summary>

```
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  authentication_policies.spec.ts          02:08        3        2        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  authentication_policies_ciba.spec.t      00:06        3        3        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  authentication_test.spec.ts              00:56       36       35        -        1        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  client_authorization_test.spec.ts        00:39       12       11        -        1        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  client_registration_policies.spec.t      00:11        9        9        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  client_scopes_test.spec.ts               07:06       25       22        3        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  clients_saml_advanced.spec.ts            00:05        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  clients_saml_test.spec.ts                02:23        9        8        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  clients_test.spec.ts                     02:50       64       64        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  events_test.spec.ts                       61ms       41        -        -       41        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  group_test.spec.ts                       01:11       46       46        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  i18n_test.spec.ts                        00:08       10        9        -        1        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_oidc_test.spec.t      00:25        6        6        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_saml_test.spec.t      00:42       13       13        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  identity_providers_test.spec.ts          03:15       31       29        1        1        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  masthead_test.spec.ts                    00:14        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  organization.spec.ts                      25ms        6        -        -        6        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  partial_export_test.spec.ts              00:04        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  partial_import_test.spec.ts              00:09        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  realm_roles_test.spec.ts                 02:59       22       21        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_client_policies_test      00:30       18       18        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_client_profiles_test      00:41       23       23        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_events_test.spec.ts       00:41       22       21        -        1        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_general_tab_test.spe      00:18       17       17        -        -        - │
  │    c.ts                                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_tabs_test.spec.ts         01:10       35       35        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_user_profile_enabled      00:53       14       14        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  realm_test.spec.ts                       02:23        6        5        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_user_registration.spec.ts          00:05        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  sessions_test.spec.ts                    00:12       13        8        -        5        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_kerberos_test.spec.ts           00:39       14       13        -        1        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_hardcoded_mapper_test      00:47       12       12        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_mapper_test.spec.ts        00:53       15       15        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  user_fed_ldap_test.spec.ts               03:46       21       20        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_test.spec.ts                    00:01        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  users_attribute_search_test.spec.ts      00:05        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  users_enable_disable.spec.ts             00:10        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  users_test.spec.ts                       03:32       44       40        1        -        3 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  8 of 37 failed (22%)                     42:36      618      547       10       58        3  
```
</details>


`npm test` ion `account-ui`:
```
Running 26 tests using 1 worker

  ✓  1 [import realms] › realm.setup.ts:10:1 › import realm (690ms)
  ✓  2 [chromium] › account-security/device-activity.spec.ts:5:3 › Sign out test › Sign out one device (1.8s)
  ✓  3 [chromium] › account-security/device-activity.spec.ts:47:3 › Sign out test › Sign out all devices (886ms)
  ✓  4 [chromium] › account-security/linked-accounts.spec.ts:67:3 › Account linking › Linking (826ms)
  ✓  5 [chromium] › account-security/signing-in.spec.ts:16:3 › Signing in › Should see only password (626ms)
  ✓  6 [chromium] › account-security/signing-in.spec.ts:51:3 › Signing in 2 › Password removal (625ms)
  ✓  7 [chromium] › account-security.spec.ts:4:1 › Check page heading (447ms)
  ✓  8 [chromium] › applications.spec.ts:22:3 › Applications test › Single application (1.2s)
  ✓  9 [chromium] › applications.spec.ts:33:3 › Applications test › Single application twice (1.1s)
  ✓  10 [chromium] › applications.spec.ts:58:3 › Applications test › Two applications (1.2s)
  ✓  11 [chromium] › groups.spec.ts:5:3 › Groups page › List my groups (494ms)
  ✓  12 [chromium] › groups.spec.ts:11:3 › Groups page › List direct and indirect groups (561ms)
  ✓  13 [chromium] › my-resources.spec.ts:7:3 › My resources page › List my resources (500ms)
  ✓  14 [chromium] › my-resources.spec.ts:14:3 › My resources page › Nothing is shared with alice (424ms)
  ✓  15 [chromium] › my-resources.spec.ts:23:3 › My resources page › Share one with alice (934ms)
  ✓  16 [chromium] › my-resources.spec.ts:55:3 › My resources page › One is shared with alice (548ms)
  -  17 [chromium] › oid4vci/oid4vci.spec.ts:7:8 › Verifiable Credentials page › Get offer for test-credential.
  ✓  18 [chromium] › personal-info/personal-info.spec.ts:20:3 › Personal info page › sets basic information (516ms)
  ✓  19 [chromium] › personal-info/personal-info.spec.ts:55:3 › Personal info with userprofile enabled › render user profile fields (331ms)
  ✓  20 [chromium] › personal-info/personal-info.spec.ts:66:3 › Personal info with userprofile enabled › render long select options as typeahead (422ms)
  ✓  21 [chromium] › personal-info/personal-info.spec.ts:80:3 › Personal info with userprofile enabled › render long list of locales as typeahead (448ms)
  ✓  22 [chromium] › personal-info/personal-info.spec.ts:94:3 › Personal info with userprofile enabled › save user profile (747ms)
  ✓  23 [chromium] › personal-info/personal-info.spec.ts:121:3 › Realm localization › change locale (537ms)
  ✓  24 [chromium] › referrer.spec.ts:8:3 › Signing in with referrer link › shows a referrer link when a matching client exists (296ms)
  ✓  25 [chromium] › referrer.spec.ts:29:3 › Signing in with referrer link › shows no referrer link when an invalid URL is passed (282ms)
  ✓  26 [del realms] › realm.teardown.ts:4:1 › delete realm (447ms)

  1 skipped
  25 passed (19.9s)
```

Ran in Firefox and Chrome.

**Review by jonkoops — DISMISSED** [review]

**Comment by jonkoops** [comment]
@nikeee could you log an issue and link it to this PR? We need this for tracking purposes for release notes and possible backports, thanks.

**Comment by nikeee** [comment]
Yeah sorry, forgot that part. Done in #35714

**Comment by jonkoops** [comment]
Thanks! Looks like there is a merge conflict, could you rebase your work so I can merge it?

**Comment by nikeee** [comment]
Done

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
Thanks @nikeee! I've set the PR to merge automatically when the CI passes.

**Pull request merged**
