### PR TITLE
KEYCLOAK-10029 Offline token migration fix. Always test offline-token…

### PR DESCRIPTION
**Pull request by mposolda**
… migration when run MigrationTest

### CODE REVIEW

**Comment by vramik** [comment]
@mposolda thank you for the PR, overall it looks good to me. I think it would be useful to run migration tests against it. It requires @tkyjovsk's work to be finished first.

**Comment by stianst** [comment]
@mposolda once the migration tests have been run let me know and I'll approve this. I looked at the changes to code, not tests, and it looks good to me. I assume @vramik has reviewed the tests sufficiently ;)

**Comment by mposolda** [comment]
@vramik @stianst Thanks for the review!

I've tried to run migration tests just for MariaDB with this PR. DB migration tests currently don't work in the pipeline for most of the databases AFAIK. There is some other tasks for the pipeline related to fixing DB migration tests (@tkyjovsk is working on it). Once that is done and DB migration tests will pass in the pipeline with this PR, I will let you know.

**Comment by vramik** [comment]
@mposolda fyi https://github.com/keycloak/keycloak/pull/6863, https://github.com/keycloak/keycloak-pipeline/pull/211

**Comment by mposolda** [comment]
@vramik Thanks for the heads-up. Hope those PRs are merged soon, so this PR can be tested in the pipeline :)

**Comment by mposolda** [comment]
@stianst @vramik Migration tests passed for this in the pipeline for all the databases in auto and manual mode https://keycloak-jenkins.com/view/pipelines/job/universal-test-pipeline-server/1457/flowGraphTable/ . Do you have a chance to approve this as discussed above?

**Review by vramik — APPROVED** [review]
@mposolda thanks

**Comment by mposolda** [comment]
@vramik Thanks!

**Pull request merged**
