### PR TITLE
KEYCLOAK-19701 Load offline client session after evicted while user session is still in cache

### PR DESCRIPTION
**Pull request by lexcao**
https://issues.redhat.com/browse/KEYCLOAK-19701

### CODE REVIEW

**Comment by mposolda** [comment]
Thanks for the fix. However I think that it is rather a problem with your configuration as I pointed in the JIRA comment https://issues.redhat.com/browse/KEYCLOAK-19701 . Keycloak doesn't support to limit size in "offlineSessions" and "offlineClientSessions" caches.

I think if we ever want to support download of the "evicted" sessions from the DB, it would need to be done more properly as lookup of the session by ID is just one scenario, but there are others (For example when user or administrator displays all sessions in account mgmt or admin console and he needs to query sessions rather than simply lookup them by ID).

**Comment by peps14** [comment]
I've the same problem with 500k offline sessions on two nodes in production. Any tips for offlineClientSessions and offlineSessions caches tuning?

**Comment by ghilainm** [comment]
I got the same issue but have no clue about how it happened. I don't know either how to reproduce. I am not in production, I have not a lot of sessions, I have one Keycloak node, and I use the default infinite span cache settings. I am using Kecyloak 18.x.x.

**Comment by SimonMacIntyre** [comment]
We are also experiencing this issue

**Comment by thomasdarimont** [comment]
I've seen this problem quite often in practice as well. The problem that this PR addresses often arises in scenarios where keycloak is used as an IdP / OpenID provider for mobile apps which quite often use large quantities (~100k - ~10Mio) of offline-sessions.

If all offline-sessions are kept in memory the resource consumption of a single Keycloak instance can grow to 10s of GBs, even if most offline-sessions aren't accessed! To save memory consumption (and cost!) developers often try to limit the amount of cache entries while relying on the lazy offline-session fetching mechanism. Unfortunately, due to the lack of lazy-loading of offline-client sessions users are effectively logged from their apps, although there are still valid offline-sessions in the database.
This usually leads to a poor user experience and eventually bad app reviews.

I think it would be very useful for a lot of users if offline-session /offline-client-session retrieval would be more robust. 

Regarding the possibility to list offline-sessions in the admin-ui. Actually I've rarely seen admins using this functionality, especially if the number of offline sessions goes beyond a certain limit.

**Comment by davidfrickert** [comment]
We are also experiencing this issue. 
It's kind of weird how "offlineSessions" are fetched from DB but "offlineClientSessions" aren't.
We are using Keycloak for the exact scenario that @thomasdarimont described, and don't want to have millions of entries in cache when they could be lazily fetched from DB...
Since Keycloak doesn't intend on supporting this scenario I guess we'll just patch it.

**Comment by martin-kanis** [comment]
Closing in favour of https://github.com/keycloak/keycloak/pull/17490

**Pull request closed without merging**
