### PR TITLE
Fix for KEYCLOAK-3961

### PR DESCRIPTION
**Pull request by danren**

### CODE REVIEW

**Comment by stianst** [comment]
With this change promises are not removed from the list, so they end up being called again and again. The promises should only be invoked once.

**Comment by danren** [comment]
Why not? The whole array is spliced, so it's effectively emptied. Should be fine.

**Comment by stianst** [comment]
Never mind, it's Friday and about time I shutdown for the weekend! It's all good and I'll merge it now.

Takker og bukker for PR! Kjekt å se Nordmenn som bruker Keycloak :)

**Comment by danren** [comment]
Værsågod - og god helg :-)

**Pull request merged**
