### PR TITLE
KEYCLOAK-13740 use children as Msg parameters

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Comment by ssilvert** [comment]
@edewit The code looks fine.  Please run the tests and provide a link to successful run.
https://docs.jboss.org/display/RHSSO/How+to+execute+account+and+admin+console+tests+on+Jenkins

**Comment by edewit** [comment]
@ssilvert I don't see the buttons wrote @pdrozd a mail

**Comment by edewit** [comment]
build result: https://keycloak-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/keycloak-account2-matrix/844/

**Review by ssilvert — DISMISSED** [review]

**Comment by edewit** [comment]
build result: https://keycloak-jenkins.com/job/keycloak-account2-matrix/852/

**Review by ssilvert — APPROVED** [review]

**Pull request merged**
