### PR TITLE
LDAP: Show error message when groups synchronization fails

### PR DESCRIPTION
**Pull request by dinutine**

### CODE REVIEW

**Review by pedroigor — DISMISSED** [review]

**Review by pedroigor — COMMENTED** [review]
@dinutine This change https://github.com/keycloak/keycloak/pull/28307/files#diff-ca5f45e45d739bb326caf5d47a57060b66917a8394f91923628460bed8467cca. Why a rename here?

Otherwise, LGTM.

**Comment by pedroigor** [comment]
@dinutine Please, also create an issue and sign-off the commit ...

**Comment by dinutine** [comment]
> @dinutine This change https://github.com/keycloak/keycloak/pull/28307/files#diff-ca5f45e45d739bb326caf5d47a57060b66917a8394f91923628460bed8467cca. Why a rename here?
> 
> Otherwise, LGTM.

Sorry, rename sneaked in accidentally

**Comment by pedroigor** [comment]
Other than that, LGTM.

**Comment by dinutine** [comment]
> @dinutine Thanks. Do you have an issue somewhere describing the issue you are fixing? I know it is clear what is it about but we need one with a bit more details and history behind it ...

I described it here:
https://github.com/keycloak/keycloak/issues/28436

and referenced it from my (updated) commit message

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@dinutine Sorry, thanks!

**Pull request merged**
