### PR TITLE
Multiple active tabs when realm name equals name of the tab in Admin console

### LINKED ISSUE #9421: Multiple active tabs when realm name equals name of tab in Admin console
### Describe the bug

When realm name is the same like name of tab in Admin console, then the particular tab is also active. For term 'name of tab', I mean the specific endpoint name for the tab. It's related to all tabs in Admin console.

Related PR: [KEYCLOAK-5906](https://github.com/keycloak/keycloak/pull/4746)

For instance:
adminConsoleClientBug

### Version

16.0.0

### Expected behavior

The active tab in admin console menu should be only the specified one. 

### Actual behavior

There are two active tabs in admin console: the current one and related to the tab endpoint.

### How to Reproduce?

- Create realm with name "client".
- Check if the Clients tab is also active

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
Closes #9421

@ssilvert @jonkoops @Aboullos Could you please take a look at it? Thank you very much.

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]
LGTM

**Comment by mabartos** [comment]
Pipeline tests passed. (those 2 failures are not related to this)
See https://keycloak-pipeline.com/job/universal-test-pipeline-server/1139/

**Review by Aboullos — APPROVED** [review]
LGTM!

**Review by ssilvert — APPROVED** [review]
Did manual tests and observed the fix.  Code looks good.

**Pull request merged**
