### PR TITLE
KEYCLOAK-19373 Update quarkus version to 2.2.3.Final

### PR DESCRIPTION
**Pull request by thomasdarimont**
Signed-off-by: Thomas Darimont <thomas.darimont@googlemail.com>

### CODE REVIEW

**Comment by thomasdarimont** [comment]
I tested this by manually building the keycloak.x distribution with `mvn -f ../distribution/server-x-dist/pom.xml clean install`.

I could login into keycloak and create a realm, client and user.

**Comment by pedroigor** [comment]
@thomasdarimont Thanks, could you also update the following dependencies:

```
<jackson.version>2.12.4</jackson.version>
<hibernate.core.version>5.5.7.Final</hibernate.core.version>
```

These versions are wrong even for v2.2.2.Final (current).

**Comment by thomasdarimont** [comment]
@pedroigor done

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@thomasdarimont Thanks.

**Pull request merged**
