### PR TITLE
KEYCLOAK-6884 KEYCLOAK-3454 KEYCLOAK-8298 Default 'roles' and 'web-or…

### PR DESCRIPTION
**Pull request by mposolda**
…igins' client scopes. Add roles and allowed-origins to the token through protocol mappers

### CODE REVIEW

**Comment by mposolda** [comment]
Documentation PR: https://github.com/keycloak/keycloak-documentation/pull/487

**Comment by stianst** [comment]
I can review

**Review by stianst — COMMENTED** [review]
* Should access token actually have RP? The reason I ask is that I was just experimenting with the js-console and end up with js-console in the aud, and in this case at least the js-console is not an intended aud of the access token
* Should access token have azp? I don't think it should (not related to this PR, but came across it when testing this PR)
* With no scope on the client I still get "resource_access: {}" should we include this empty field if there are no roles? I'd say no. I even get this empty field when I remove the roles client scope. That's definitively not correct
* I wonder if we should remove the client scope templates. It makes it more awkward to create client scopes as there's the extra (probably confusing to a lot of people) step. With the addition of automatic audience from client roles I don't think this is all that useful anymore. It's more straightforward to me to create a empty client scope, then add a mapper for the audience to the service. One way of doing it is better than two ;)

**Comment by stianst** [comment]
Added the following follow-up issues:
* https://issues.jboss.org/browse/KEYCLOAK-8481
* https://issues.jboss.org/browse/KEYCLOAK-8482
* https://issues.jboss.org/browse/KEYCLOAK-8483
* https://issues.jboss.org/browse/KEYCLOAK-8484

**Review by stianst — APPROVED** [review]

**Comment by mposolda** [comment]
@stianst Thanks for the JIRAs

PR should fix those JIRAs:
https://issues.jboss.org/browse/KEYCLOAK-3454
https://issues.jboss.org/browse/KEYCLOAK-6884
https://issues.jboss.org/browse/KEYCLOAK-8346
https://issues.jboss.org/browse/KEYCLOAK-8298
https://issues.jboss.org/browse/KEYCLOAK-5259

**Pull request merged**
