### PR TITLE
KEYCLOAK-10973 OpenShiftTokenReviewEndpointTest fix

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.jboss.org/browse/KEYCLOAK-10973

### CODE REVIEW

**Comment by mabartos** [comment]
Already solved here : https://github.com/keycloak/keycloak/pull/6208

**Comment by slaskawi** [comment]
@mabartos Definitely not! As it now (without my PR), all the test in this particular file are ignored. They are omitted due to a failing Assumption. My patch turns them back on.

See my Travis logs from Group 4:
```
[INFO] Running org.keycloak.testsuite.openshift.OpenShiftTokenReviewEndpointTest
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 98.954 s - in org.keycloak.testsuite.openshift.OpenShiftTokenReviewEndpointTest
```

And yours:
```
[INFO] Running org.keycloak.testsuite.openshift.OpenShiftTokenReviewEndpointTest
[WARNING] Tests run: 12, Failures: 0, Errors: 0, Skipped: 12, Time elapsed: 17.017 s - in org.keycloak.testsuite.openshift.OpenShiftTokenReviewEndpointTest
```

**Comment by mabartos** [comment]
@slaskawi I know it's ignored, but at this time, I think, it can be. There's another PR (#6207 ) in which "OpenShiftTokenReviewEndpointTest" is edited. It's subtask of `Merge preview features test into base test` (https://issues.jboss.org/browse/KEYCLOAK-8361).

The bug in "OpenShiftTokenReviewEndpointTest" was caused by "OpenShiftClientStorageTest" commit (#6201 ). The test enabled feature `OPENSHIFT_INTEGRATION` and then disabled it. So, first was executed "OpenShiftClientStorageTest" and then "OpenShiftTokenReviewEndpointTest". `ProfileAssume.assumeFeatureEnabled()` assumed the feature was enabled, but it wasn't. So, the test was executed with disabled feature, ergo the `openshift-token-review` endpoint didn't work. :)

**Comment by slaskawi** [comment]
@mabartos Ok, that makes sense to me.

Let me close this PR as all the bits have been addressed in https://github.com/keycloak/keycloak/pull/6207.

**Pull request closed without merging**
