### PR TITLE
KEYCLOAK-7925 Initial UI tests for the new Account Console

### PR DESCRIPTION
**Pull request by vmuzikar**
UI tests for the Welcome Screen, Personal Info and Change Password. Also contains some testsuite optimizations required by the new Account Console.

Unfortunately, currently only Safari passes with those tests.
* Chrome fails due to [KEYCLOAK-8016](https://issues.jboss.org/browse/KEYCLOAK-8016)
* Firefox mostly fails due to [KEYCLOAK-8180](https://issues.jboss.org/browse/KEYCLOAK-8180)
* Internet Explorer fails due to [KEYCLOAK-8219](https://issues.jboss.org/browse/KEYCLOAK-8219)
* Smartphones fail due to [KEYCLOAK-7496](https://issues.jboss.org/browse/KEYCLOAK-7496)

We'll also need to rewrite support for vertical navigation bar (blocked by [KEYCLOAK-8217](https://issues.jboss.org/browse/KEYCLOAK-8217)) and add missing tests for it.

### CODE REVIEW

**Comment by pdrozd** [comment]
@keycloak-ci-bot test

**Comment by pdrozd** [comment]
@keycloak-ci-bot test keycloak-pr-pipeline-structured

**Comment by pdrozd** [comment]
@keycloak-ci-bot test keycloak-pr-pipeline-structured

**Comment by pdrozd** [comment]
@keycloak-ci-bot test keycloak-pr-pipeline-structured

**Review by ssilvert — APPROVED** [review]

**Review by pdrozd — APPROVED** [review]

**Pull request merged**
