### PR TITLE
Enable near-caching for HotRod store

### LINKED ISSUE #13303: Use near caching for HotRod storage

### PR DESCRIPTION
**Pull request by mhajas**
Closes #13303

Unfortunately, I was not able to make this work with bloom filter enabled so I created a follow-up issue to investigate why it fails.

### CODE REVIEW

**Comment by martin-kanis** [comment]
@mhajas Thanks for the PR. Do we want to enable near caches for model tests or for base testsuite?

**Comment by mhajas** [comment]
> @mhajas Thanks for the PR. Do we want to enable near caches for model tests or for base testsuite?
While I was testing the difference between enabled/disabled near-cache I set default value to `true/false` and then I forgot to enable it when sending PR :facepalm:

**Comment by mhajas** [comment]
The performance difference is noticeable when doing repeating `get()` operations on the same id. I tried it in model tests with a pure `get` call on `RemoteCache`. The problem is, that we are not reading by `id` so often and in other cases the cache is not used. We will see the performance difference now when the cache is finally enabled.

**Review by martin-kanis — APPROVED** [review]
Thanks @mhajas. Model tests failure is caused by an instability not related to this PR.

**Review by hmlnarik — APPROVED** [review]
Approving per @martin-kanis 's approval

**Pull request merged**
