### PR TITLE
Enable simple-cache for local-cache

### LINKED ISSUE #20486: Enable `simple-cache` for `local-cache`
### Description

Infinispan internal architecture is composed of `Interceptors` and `Command`s where each `Interceptor` has its own functionally (replication, persistence, locking, etc). The `simple-cache` mode, available for `local-cache`s, drops all `Interceptor`s and `Command`s. 

This is a possible nano-optimization where neither large objects, `Interceptor`, and the short-lived objects, `Command`, are not created. 

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by pruivo**
Closes #20486

### CODE REVIEW

**Review by ahus1 — APPROVED** [review]
I did a local test with docker containers and I see a small improvement in the area of less than one percent on the `AuthenticationCode` scenario. As that scenario spends most of its time in hashing, other scenarios will benefit more from it.

**Comment by ahus1** [comment]
@mhajas - please merge when you have the time. Thanks!

**Comment by sschu** [comment]
If I recall correctly, simple caches don't emit metrics. So it would not be possible to check cache sizes for realms, users etc. at runtime. I am not 100% sure on this though, I might be wrong.

**Comment by pruivo** [comment]
@sschu they do. Simple caches emit metrics from the methods annotated with `@ManagedAttribute` in this class https://github.com/infinispan/infinispan/blob/8b7189e1cb3b482cf0e17fdc851e5414a5c39fbd/core/src/main/java/org/infinispan/stats/impl/StatsCollector.java which includes the cache size (number of entries).

**Comment by pruivo** [comment]
Feel free to check if all metrics required are available. I have an image built which includes this commit (and some other experiments):
```
podman run -p 8080:8080 quay.io/pruivo/keycloak:experimental start-dev --cache=ispn --cache-config-file=cache-ispn.xml --metrics-enabled=true -Dinfinispan.stats.enabled=true
```
Access `http://127.0.0.1:8080/metrics` and search for `vendor_cache_manager_keycloak_cache_realms_statistics` to get all metrics.

**Review by mhajas — APPROVED** [review]
Thank you @pruivo @ahus1!

@sschu I checked the metrics for embedded caches with the image provided by @pruivo they work as expected. Do you still have some concerns or I can go ahead and merge?

**Comment by sschu** [comment]
@pruivo Looks like I was wrong but learned something.
@mhajas The other differences I could imagine might to be a problem is the lack of transaction support and indexing for simple caches. But if that is not needed, I don't see an issue.

**Comment by mhajas** [comment]
> @mhajas The other differences I could imagine might to be a problem is the lack of transaction support and indexing for simple caches. But if that is not needed, I don't see an issue.

At the moment, we don't need that for the caches that were flagged with `simple-cache=true`.

Thank you for looking into this @sschu, I am merging then.

**Pull request merged**
