### PR TITLE
KEYCLOAK-11984 Remove unused fields and imports from module core

### PR DESCRIPTION
**Pull request by Captain1653**

### CODE REVIEW

**Comment by abstractj** [comment]
@Captain1653 could you please review our https://github.com/keycloak/keycloak/blob/master/CONTRIBUTING.md guidelines? We need a Jira for that with description and the motivation for this change.

**Comment by Captain1653** [comment]
Hi, @abstractj  . Thanks,  Yes, I have reviewed it. I thought it's only small refactoring and I wasn't sure about creating Jira-Issue. But if it's the strong rule, then I'll create issue. It's not a problem. Should I create it?

**Comment by abstractj** [comment]
@Captain1653 yes, please.

**Comment by Captain1653** [comment]
@abstractj I have done it. I'm sorry, but I'm not sure about my jira issue. I mean about your workflow, about resolved, about affect versions and others. How do you manage this? Where can I read about it? And I don't know why, but I can't assign jira issue myself.

**Comment by stianst** [comment]
We just need a JIRA to know about the change. What you've done is fine. Affected versions only apply to bugs really, and we set the fix version when we merge. JIRA annoyingly doesn't allow us to assign issues to the community right now, but we know you resolved it by looking at the PR so that's okay.

**Review by stianst — APPROVED** [review]

**Pull request merged**
