### PR TITLE
Update GitHub actions dependencies

### LINKED ISSUE #11953: Update GitHub actions dependencies
### Description

Update the issues reported by dependabot.

### PR DESCRIPTION
**Pull request by abstractj**
- Bump aquasecurity/trivy-action from 0.2.3 to 0.2.5
- Bump github/codeql-action from 2.1.8 to 2.1.9
- Bump docker/setup-buildx-action from 1 to 2
- Bump docker/build-push-action from 2 to 3
- Bump manusa/actions-setup-minikube from 2.4.3 to 2.6.0
- Bump docker/setup-qemu-action from 1 to 2
- Bump docker/metadata-action from 3 to 4
- Bump docker/login-action from 1 to 2

Resolves #11953

Signed-off-by: dependabot[bot] <support@github.com>

### CODE REVIEW

**Review by andreaTP — DISMISSED** [review]
LGTM, thanks!!!

**Comment by DGuhr** [comment]
@andreaTP what's with the error in the operator CI?

**Comment by jonkoops** [comment]
What is the motivation for pulling this into a manual PR versus merging the individual Dependabot PRs?

**Review by jonkoops — DISMISSED** [review]
Changes look good to me, but I have no idea if any of these actions require some sort of migration.

**Comment by andreaTP** [comment]
@DGuhr fixed here: https://github.com/abstractj/keycloak/pull/22

**Comment by abstractj** [comment]
@jonkoops the reason is to reduce the amount of noise of merging 8 PRs from Dependabot, when we are able to squash into a single one.

**Review by andreaTP — APPROVED** [review]
LGTM

**Review by DGuhr — APPROVED** [review]

**Comment by abstractj** [comment]
Thanks for your changes @andreaTP

**Pull request merged**
