### PR TITLE
Update webauth4j dependency version to 0.19.3.RELEASE

### PR DESCRIPTION
**Pull request by ynojima**
Addresses #9506

Commit 94ed5b7 updates `keycloak/licenses.xml` and `keycloak-server-galleon-pack-licenses.xml`, 
but `rh-sso/licenses.xml` and `rh-sso-server-galleon-pack-licenses.xml` also needs update.
Could someone from Red Hat engineering team create a Red Hat build webauthn4j 0.19.3.RELEASE and update `rh-sso/licenses.xml` and `rh-sso-server-galleon-pack-licenses.xml` ?

### CODE REVIEW

**Comment by mabartos** [comment]
@ynojima Thanks for the PR!

@pskopek @drichtarik Could you please take a look at it? Thanks

**Comment by drichtarik** [comment]
@mabartos noted. And thanks for letting me know. Give me a few days though.This needs a prod build

**Comment by drichtarik** [comment]
Done

**Review by mposolda — APPROVED** [review]
@ynojima Thanks for the update and for the heads-up!

I am approving considering just the code changes.

I did not check if this is good from the perspective of automated tests and productization. I am leaving for others to approve this when testing and productization aspects of this PR are good to go.

**Comment by mabartos** [comment]
Those tests seem quite good, except for the `WebAuthnPolicySettingsTest`. 

@ynojima I've created a PR to your branch in order to fix it.

Pipeline tests: https://keycloak-jenkins.com/job/universal-test-pipeline-server/1493/testReport/

**Review by mabartos — CHANGES_REQUESTED** [review]
@ynojima Please, see my previous comment.

**Review by drichtarik — APPROVED** [review]

**Pull request merged**
