### PR TITLE
KEYCLOAK-3327 Make realm attributes accessible via the RealmModel

### PR DESCRIPTION
**Pull request by dteleguin**

### CODE REVIEW

**Comment by thomasdarimont** [comment]
Cool stuff!

Will you also provide a view in the admin-console to edit this attributes?

Cheers,
Thomas

**Comment by stianst** [comment]
I'm not convinced about a view in the console. Would it not be confusing to most users? Also, what's the use-case?

BTW we're working on a generic component storage mechanism that might be a better option for custom providers than using realm attributes.

**Comment by dteleguin** [comment]
Hi guys,

@stianst, if there is going to be a superior mechanism, I'm totally for it. Could you please tell us more about it, will it serve our needs? I'm mostly [interested](http://lists.jboss.org/pipermail/keycloak-dev/2016-July/007616.html) in the mechanism to store custom settings for my extension; @thomasdarimont expressed his idea (a very cool one) in the yesterday's ML [thread](http://lists.jboss.org/pipermail/keycloak-dev/2016-August/007977.html).

As for the use case for the attribute editor GUI, I think @thomasdarimont meant something similar to `about:config` in Firefox, i.e. a complete list of settings/attributes, for majority of which there's no dedicated GUI (and no point in creating one); definitely a "power-user" class feature. Let's look at the attribute list of the typical KeyCloak realm:

```
keycloak=> select name, value from realm_attribute where realm_id = 'master';
                 name                  |                         value                         
---------------------------------------+-------------------------------------------------------
 _browser_header.xContentTypeOptions   | nosniff
 _browser_header.xFrameOptions         | SAMEORIGIN
 _browser_header.contentSecurityPolicy | frame-src 'self'
 maxFailureWaitSeconds                 | 900
 minimumQuickLoginWaitSeconds          | 60
 waitIncrementSeconds                  | 60
 quickLoginCheckMilliSeconds           | 1000
 maxDeltaTimeSeconds                   | 43200
 displayName                           | Keycloak
 displayNameHtml                       | <div class="kc-logo-text"><span>Keycloak</span></div>
 bruteForceProtected                   | true
 failureFactor                         | 30
 ru.cargosoft.tms.innerWindow          | 20  // <- custom attribute
 ru.cargosoft.tms.outerWindow          | 200 // <- custom attribute
```

I'm not sure if each and every attribute has its corresponding GUI field, but I can imagine situations where even the most infrequently-used attribute would need to be edited. ATM, this is achievable either programmatically or via the direct DB manipulation.

**Comment by dteleguin** [comment]
@thomasdarimont, I think I could work on that (I've got an experience in extending KeyCloak GUI), but let's listen to what @stianst says. Maybe there's no point doing it if it will be superseded by another (better) mechanism.

**Comment by stianst** [comment]
All built-in properties of the realm are currently configurable through the admin console. An attributes list would only apply to attributes for custom providers.

Bill is working on the component storage, you can find some info on the dev mailing list http://lists.jboss.org/pipermail/keycloak-dev/2016-August/007765.html

**Comment by thomasdarimont** [comment]
@dteleguin yes something like an about:config would be nice, especially if different data types / validators would be supported as well. A generic component could be used to manage client and user attributes as well :)
It should also be possible to refer to realm attributes in user attributes (e.g. via `${realm.attributes.myRealmVariable}`).

@stianst I think the scope for such attributes should be a bit wider than the currently proposed "only for custom providers".
Think of properties that need to be shared accross multiple pages or client configurations.
Even user attribute or client attribute definitions could benefit from being able to share some common attribute definitions. Having realm / client attributes would give developers much more freedom and hooks for implementing custom functionality.

**Comment by stianst** [comment]
I'm merging this - feel free to create a JIRA to add something like about:config

**Pull request merged**
