### PR TITLE
add adapters dist artifact

### PR DESCRIPTION
**Pull request by sebastienblanc**
https://issues.jboss.org/browse/KEYCLOAK-4543

### CODE REVIEW

**Comment by stianst** [comment]
Why is this needed?

**Comment by sebastienblanc** [comment]
For the quickstart testing "framework" we will be using the BOM and also the adapter-dist for the arquillian's tests.

**Comment by stianst** [comment]
Oki, that makes sense. Can you create a JIRA for this please?

**Comment by sebastienblanc** [comment]
done

**Comment by sebastienblanc** [comment]
:notes:  I got the power :notes:

**Pull request merged**
