### PR TITLE
 KEYCLOAK-9708 Enable SmallRye Health and Metrics extensions

### PR DESCRIPTION
**Pull request by vramik**
https://github.com/keycloak/keycloak/pull/5920 should be merged prior to this one

### CODE REVIEW

**Comment by vramik** [comment]
@keycloak-ci-bot test

**Review by slaskawi — CHANGES_REQUESTED** [review]
The changes look good to me (apart from the failures of course). However the title is a bit misleading. It says this PR enables metrics, but it also rebases Keycloak on top of WildFly 16, which is much more important in my opinion than introducing metrics :)

I would suggest to change the title to mention that this PR rebases us on top of WildFly 16 and enables metrics.

**Comment by slaskawi** [comment]
> I would suggest to change the title to mention that this PR rebases us on top of WildFly 16 and enables metrics.

I'm taking this back, I've just noticed you created a WF 16 upgrade PR https://github.com/keycloak/keycloak/pull/5920.

**Comment by stianst** [comment]
@vramik I think the microprofile config subsystem needs to be enabled as well, otherwise the server will fail at startup. Noticed this when I was playing with metrics on WF16

**Comment by vramik** [comment]
@stianst thank you for the tip, I've updated the PR.

**Comment by slaskawi** [comment]
@vramik One thing just popped into my mind (sorry I didn't mentioned it before). Could we write at least one test to make sure those metrics are up & running?

**Comment by vramik** [comment]
@slaskawi good point, I'll add the test. thanks

**Comment by vramik** [comment]
@keycloak-ci-bot test

**Review by slaskawi — APPROVED** [review]

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
