### PR TITLE
KEYCLOAK-10097 Fix register method in javascript adatper for cordova

### PR DESCRIPTION
**Pull request by Wobow**
[KEYCLOAK-10097](https://issues.jboss.org/browse/KEYCLOAK-10097)
In the javascript adapter, the cordova "register" method implementation was broken and inconsistent with its other implementations. These changes fix this issue:

1) Added the missing parameter "options" to the method
2) The method now returns a promise that parses and processes the callback from the register process

### CODE REVIEW

**Comment by mhajas** [comment]
@Wobow thank you for your PR. I was able to reproduce the bug and I also checked that the register method works after your fix. 

Could you please rebase your PR?

**Comment by ssilvert** [comment]
The copy of keycloak.js under /themes is no longer there.  It was a temporary thing.  Kudos for noticing that version of the file.

Are you saying that the "register" method never worked at all?  I'm a little concerned about change the return value if someone is already using that method.

**Comment by ssilvert** [comment]
Also, since this is part of the public API for the adapter, it will need a documentation change.

**Comment by mhajas** [comment]
Thank you @ssilvert for clarification about the /themes keycloak.js file. I have never seen it before. 

Yes, you are right, the register function never worked as the option argument is undefined. 

Also, does it make sense to return promise when the user is redirected to registration page?

**Review by ssilvert — DISMISSED** [review]
Merging.  Thanks for the PR.

**Comment by ssilvert** [comment]
Hmm.  I thought this didn't have conflicts any more.

@Wobow Can you fix this?

**Comment by Wobow** [comment]
@ssilvert I rebased master onto my branch, should be ok now.

**Comment by ssilvert** [comment]
@Wobow Now this includes 43 commits.  Something is wrong.

**Comment by Wobow** [comment]
@ssilvert Sorry about that, I messed up somewhere. I created another pull request with the one commit : https://github.com/keycloak/keycloak/pull/6059

I'm closing this one.

**Pull request closed without merging**
