### PR TITLE
fix(KEYCLOAK-18309): update federated user during account linking

### LINKED ISSUE #11195: Sync user attributes on identity provider account linking
### Describe the bug

Currently, user attributes do not seem to sync when using account linking from an identity provider, despite mappers being set up for the identity provider.

I can see a PR open that seems to address the issue (though no issue open on Github as far as I can see), could this be reviewed?

https://github.com/keycloak/keycloak/pull/8139

### Version

17.0.1

### Expected behavior

When a user has their account linked from an identity provider and attribute mappers are set up for the provider, the attributes are created for the Keycloak user using their identity provider account.

### Actual behavior

A user can successfully link to an identity provider account but no attributes are created for the user.

### How to Reproduce?

Enable account linking only for an identity provider and mappers for some attributes.

### Anything else?

PR seems to be open here:
https://github.com/keycloak/keycloak/pull/8139

### PR DESCRIPTION
**Pull request by AndreasSi**
Based on that issue: https://issues.redhat.com/browse/KEYCLOAK-18309

Federated User should be updated during account linkin process.

### CODE REVIEW

**Review by mposolda — CHANGES_REQUESTED** [review]
@AndreasSi Sorry for the late review.

I think that your fix is good and IDP mappers should be called during the account linking.

I see the only missing piece is the auomated test. Will you be able to provide some?

**Comment by mposolda** [comment]
I am closing the PR as there are no tests for this. Feel free to re-open once automated test is added for this scenario.

**Comment by AndreasSi** [comment]
Sorry for my late answer. I was on vacation.

I will add an automated test shortly.

**Comment by apavlenko-tp** [comment]
Hello @AndreasSi!
I recently hit into the issue which this PR solves, and want it to be merged :) 

Are you going to work on automated tests in the near future?
If you don't have time for finishing your work - please let me know, I'll add the tests myself and we can push this thing forward.

**Comment by AndreasSi** [comment]
Hello @apavlenko-tp ,

please feel free to add automated Tests. Currently i am very busy at work, so i cant promise, when i will finish the automated tests.

Kind regards,
Andreas

**Comment by ch-lepp** [comment]
I was just looking for a suitable spot to add the requested automated tests, but couldn't find any automated tests for the IdentityBrokerService class at all...

As far as I can see, there are none in the [test section of the services project](https://github.com/keycloak/keycloak/tree/168734b817da2138548bacba973204e80f566b2c/services/src/test).
And I could not find any tests for the account linking in the [test suite project](https://github.com/keycloak/keycloak/tree/main/testsuite).

 Where are automated tests for this class supposed to be?
Are there any so far?

**Pull request closed without merging**
