### PR TITLE
Promote Account Console v3 to default and deprecate v2

### LINKED ISSUE #19660: Deprecate Account Console v2
As part of replacing the older Account Console versions with the new one we will have to deprecate version 2 of the console.

### LINKED ISSUE #19663: Promote Account Console v3 to 'default'
The new Account Console introduced under #19641 must be promoted to 'default' so that more users will have access to it.

### PR DESCRIPTION
**Pull request by jonkoops**
Closes #19663
Closes #19660

### CODE REVIEW

**Review by ssilvert — DISMISSED** [review]
LGTM

**Comment by mabartos** [comment]
WebAuthn account tests are not prepared to run with Account3. I'd suggest using Account2 for now.

Once the https://github.com/keycloak/keycloak/issues/26080 is resolved, the feature can be enabled for the WebAuthn tests. As we need to verify WebAuthn functionality, the version of the supportive account console should be negligible.

@jonkoops Created PR to your fork:  https://github.com/jonkoops/keycloak/pull/16

**Comment by jonkoops** [comment]
Nice, thanks @mabartos I went ahead and merged in your solution, thanks for the assist.

**Review by pedroigor — DISMISSED** [review]
@mposolda FYI

**Review by ssilvert — DISMISSED** [review]

**Review by hmlnarik — DISMISSED** [review]

**Review by mposolda — DISMISSED** [review]

**Comment by jonkoops** [comment]
Had to do a rebase because of some merge conficts.

**Review by mposolda — APPROVED** [review]

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
