### PR TITLE
KEYCLOAK-1421 - added timestamp of keycloak user creation and shown in admin app

### PR DESCRIPTION
**Pull request by velias**

### CODE REVIEW

**Comment by patriot1burke** [comment]
can't be automatically merged anymore

**Comment by velias** [comment]
Ok, I'll rebase it, probably next week

**Comment by velias** [comment]
rebased, you can merge it if Travis build will succeed

**Comment by patriot1burke** [comment]
You need to remerge

**Comment by velias** [comment]
Thanks for merging @stianst

**Pull request merged**
