### PR TITLE
[KEYCLOAK-19006] User Profile: Patched handling of the "whitespace-only" texts in pattern and length validators

### PR DESCRIPTION
**Pull request by velias**

### CODE REVIEW

**Comment by danielFesenmeyer** [comment]
Hi @velias, I have tested your changes. It works great for our use cases :thumbsup:

**Comment by velias** [comment]
Thanks @danielFesenmeyer for checking
@pedroigor any chance to merge this? Thanks in advance.

**Review by pedroigor — APPROVED** [review]

**Comment by velias** [comment]
thanks @pedroigor

**Comment by pedroigor** [comment]
@velias We should review that flag to skip validation when values are empty. Not sure if makes sense and I think we can improve that area.

**Pull request merged**
