### PR TITLE
#16161 implement an EventBuilder constructor which can be called from scheduled tasks

### LINKED ISSUE #16161: it'd be nice if we could throw events from `ScheduledTask`
### Description

It'd be nice if we could throw events from `ScheduledTask`. Currently, the `EventBuilder` constructor needs a `ClientConnection` and throws an NPE if none is provided.

As far as I can see the ClientConnection is only used to save the IP address of the caller in the event.

### Discussion

_No response_

### Motivation

If I'd like to throw an Event from some background service (eg.: I'd like to disable all users who didn't login in the past year and implement this in a `ScheduledTask`) then I cannot create this Event.

### Details

_No response_

### PR DESCRIPTION
**Pull request by vilmosnagy**
Closes #16161 for reasoning.

### CODE REVIEW

**Comment by stelewis-redhat** [comment]
I can't approve but I'll tell you what I see:

you're adding a new constructor that skips the client connection/IP address parameter so that you can create an EventBuilder without having the IP address.

What will show in the event log? Will the IP address be null, or empty string?

Other than that it makes sense.

**Comment by vilmosnagy** [comment]
@stelewis-redhat it's gonna be null as far as I understand the code (the `ipAddress` field will be uninitialized, so it defaults to `null`).

I've run some examples, and this is how it looks on the UI:

image


The `ip_address` column in the `event_entity` table in the database will have the value `null`.

```
"id"	"client_id"	"details_json"	"error"	"ip_address"	"realm_id"	"session_id"	"event_time"	"type"	"user_id"
"d6541a80-0053-43a0-9f2e-cf0ecbf897b9"		"{""reason"":""Automatic deletion: did not finish the registration"",""disabled"":""true""}"			"public"		1676885328579	"DELETE_ACCOUNT"	"3a025b5a-1183-45d8-ab78-315d17256a2c"
```

**Review by pedroigor — APPROVED** [review]
LGTM.

**Comment by vilmosnagy** [comment]
❤️ Thanks.

**Pull request merged**
