### PR TITLE
Simplify Upgrade Guide structure

### LINKED ISSUE #27632: Integrate downstream Upgrading Guide changes into upstream
### Description

Go back to a more single source strategy for the upgrading guide

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andymunro**
Closes #27632
@ahus1 I am still working on this, but you see where I am going.

I will need to set attributes for the download topic.  Also, I will need an overlay topic for intro.adoc and changes.adoc.

### CODE REVIEW

**Comment by andymunro** [comment]
@ahus1, @mposolda, @jonkoops  I welcome your review on this attempt to have mostly one upstream/downstream source for Upgrading.  This PR will require downstream PR with a different version of intro.adoc, changes.adoc (including only the 23.x and 24.x changes) and a definition of micro release (if we need it) in the Preparing to upgrade topic.

**Comment by ahus1** [comment]
@andymunro - I'm ok with the structural changes. Good to see that the structure has been simplified.  

I've added one more commit to add the missing attributes. I also renamed `{version}` to `{project_version}` as that is the attribute used in the classic docs.

**Comment by jonkoops** [comment]
@andymunro looks like there are some conflicts with the base branch, could you resolve them?

**Comment by andymunro** [comment]
Conflicts resolved. I need to address the statement about " In a minor upgrade of Keycloak, all user sessions are lost. After the upgrade, all users will have to log in again. " Is that true? Does it apply to major and micro releases?

**Comment by andymunro** [comment]
Removed the phrase "for minor upgrades" as related to "all user sessions are lost" It affects all upgrades.

**Comment by andymunro** [comment]
@ahus1 Can you merge this and then I can work on a downstream version?

**Comment by ahus1** [comment]
I've done a small change to the docs (see review commit): 

* Using the `{product_name}` in one place
* Changing the loosing session statements a bit, pointing out that offline sessions are not lost:
   > After upgrade of Keycloak, except for offline user sessions, user sessions are lost. Users will have to log in again.

Will approve and merge this now to main. 

For working on this downstream, you'll need to first backport this change to KC24.

**Review by ahus1 — APPROVED** [review]

**Pull request merged**
