### PR TITLE
Add clientId to successful logout event

### LINKED ISSUE #24510: Add clientId to successful LOGOUT event
### Description

When logging out of an app the `clientId` is not included in the `LOGOUT` event details:

```jmillard-keycloak-1  | Event Occurred:type=LOGOUT, realmId=6630d323-ee8e-441c-8338-44d632c9de36, clientId=null, userId=7147da01-9310-483e-92b6-4e50f5b1b4ed, ipAddress=172.18.0.1, redirect_uri=http://localhost:9000/admin/master/console/```

I was looking through the source and I believe this is the path of a successful logout:

https://github.com/keycloak/keycloak/blob/7d7880b6f6aae5112d4b67f94bc9f1697d1e0c06/services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java#L467-L484

I'm not sure if the `clientId` is still available at this point, but it would be great to have.

### Discussion

_No response_

### Motivation

I need it in an application to support collecting metrics.

### Details

```http://localhost:9000/realms/master/protocol/openid-connect/logout?client_id=security-admin-console&post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fmaster%2Fconsole%2F&id_token_hint=...```

So I know the `client_id` is definitely in the original request.

### PR DESCRIPTION
**Pull request by gabrielpadilh4**
Closes #24510

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you for this contribution, the code change looks good. 

Would you mind extending the tests for this? There is the class `AssertEvents` which already has a method `expectLogout` which verifies the event. You could add for example a check that the `clientId` is not null.

**Comment by mposolda** [comment]
@gabrielpadilh4 @jsm174 Just to doublecheck: Did you test if the issue is still present in the newest Keycloak 23 release?

We recently had the PR with the commit https://github.com/keycloak/keycloak/commit/c1575326, which should add clientId to the event, but it's possible that it was missing some places. Could you please confirm if still present in 23?

**Comment by gabrielpadilh4** [comment]
No @mposolda i didn't have tested at version 23. I will test and let you know.
@ahus1 will add the test once i validated that is already working or not in version 23.

**Comment by gabrielpadilh4** [comment]
Hello @mposolda tested in Keycloak 23, it seems that is already working:
`2023-11-24 21:50:58,989 DEBUG [org.keycloak.events] (executor-thread-3) type=LOGOUT, realmId=2c798753-f25b-4cdf-a9a7-e076ebe713a3, clientId=security-admin-console, userId=fc5ced1a-084b-4693-ab1e-b6f7772a5034, ipAddress=0:0:0:0:0:0:0:1, redirect_uri=http://localhost:8080/admin/master/console/#/master/events, authSessionParentId=71741f12-32c1-4397-8fac-2d32c2b44868, authSessionTabId=2kG0OJy_yuU`

Will answer in [#24510](https://github.com/keycloak/keycloak/issues/24510)

**Pull request closed without merging**
