### PR TITLE
Support for transient users for brokered accounts

### LINKED ISSUE #11334: Add option to not import user from brokers
### Description

Hello,
We use Keycloak as a bridge to authenticate our service users with some brokers that do not support standard protocols like OpenID or SAML.

The problem is that a few brokers (ex. one provided by the state of France) refuse us because our Keycloak store the data in its own database.
They tell us that it's not conform to the GPDR.

It will be great to add an option to by-pass user creation in Keycloak when using broker authentication. 

Thanks,
Christophe

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-4429

### Motivation

Be conform to the GPDR by not storing information we don't need (the data could be only pass to the service provider)

### Details

_No response_

### PR DESCRIPTION
**Pull request by hmlnarik**
This PRototype adds capability of _not_ importing brokered users into keycloak database, also known as transient users for brokering feature.

The core of the PR is that the user data is stored as a part of an authentication session (modifiable) and once authentication is done, it is stored in user session.

To do so, lightweight user model based on existing [`InMemoryUserAdapter`](https://github.com/keycloak/keycloak/blob/eedc4ceb181df7f89b9133cc8dcdd6378aef892b/model/legacy-private/src/main/java/org/keycloak/storage/adapter/InMemoryUserAdapter.java) class is introduced, and is de/serialized into a auth / user session attribute when needed.
An option is added in identity provider configuration to not store user into database. This option is disabled by default, keeping the behaviour backward compatible. When enabled, instead of creating a user in user database, a read/write lightweight user is created and its representation stored in authentication session. Once authentication finishes and user session is created, the user is stored as **EDIT:** read-write **END** object there.

This has several implications:
- The authentication of the user relies purely on the trusted identity provider. For example, MFA on Keycloak side is not applicable (there is no place to store configuration).
- The user is never stored in user database, thus it cannot be searched or updated. The user can still be viewed in admin console when navigating to it from client session of the respective client
- **EDIT:** Since there is no persistent user,  **END** the user roles and groups can only be assigned using mappers
   - Specifically, the user can view its account console as long as there is a mapper which maps respective roles in the identity provider settings
- Removing the user session with lightweight user e.g. by logging out effectively removes the user
- Every mapper of a transient identity provider effectively behaves as `Import` sync mode since it always treats the user as new. Hence sync mode settings is hidden in admin console identity provider screen when transient users are enabled

This PR is split into multiple commits:
- The first commit is a visibility change which abstracts `InMemoryUserAdapter` so that it is visible both for services and model modules
- Next commit adds the classes necessary for storing lightweight user representation, based on `InMemoryUserAdapter`
- The third commit represents the core of the changes:
   - It modifies places where the user was added into database to account for the `Do not store users` settings, specifically instead of creating records in database, it creates lightweight users instead
   - Ensures that when a user was looked up from database, it can be reconstructed from auth / user session as needed
- Next commit updates admin console functionality: Ensures that the user details can be viewed and identity provider can be configured accordingly
- The fifth commit updates broker tests to account for transient session settings and adds specific test case for transient sessions

For this to become a full-blown PR, the approach needs to be confirmed and remaining tasks finished:
- [ ] Documentation

cc: @keycloak/core 

Closes: #11334

### CODE REVIEW

**Review by jonkoops — DISMISSED** [review]
Changes to the front-end look fine to me.

**Comment by hmlnarik** [comment]
Rebased to include fix for #23965

**Comment by thomasdarimont** [comment]
Is this supposed to work with the offline_access / OfflineSession feature?

**Comment by mposolda** [comment]
@hmlnarik Thanks for the PR! It looks great!

Few questions:
1) Do we want feature flag for this capability? IMO it is sufficient to handle new broker option in admin console and in the configuration to be available just when feature enabled. Or is it unnecessary overhead?

2) Is it possible to add test for those scenarios to ensure they work as expected?:
-- SSO login
-- Refresh token
-- Refresh of offline token (to @thomasdarimont question: I think that offline sessions would work fine and user would be "transient" for the whole lifecycle of offline user session if I understand correctly?)
-- Sending request to UserInfo endpoint (on `consumer` realm side)
-- Sending request to introspection endpoint (on `consumer` realm side)

3) I am not 100% sure if we want user to be read-write once it finished authentication and is saved in userSession? I understand it needs to be writable when still in authenticationSession (due update-profile page often displayed to user after first IDP login etc). In general, it might be more clear to me to indicate that if such user tries to update himself in account console (or admin tries to update him), that the message like "User is read-only" is displayed instead of silently updating user, which would be lost upon next login. But I don't know what is best regarding usability here? I am curious for more opinions (WDYT @thomasdarimont @pedroigor ?

4) Documentation

IMO if we have flag (1), we don't need 2,3,4 in this PR, but can be done in follow-up PRs (if we need 3 at all, depends on the feedback...) as we have more "freedom" to change the behaviour and/or fix possible bugs and provide docs afterwards in the follow-up PRs if needed.

**Comment by hmlnarik** [comment]
> Is this supposed to work with the offline_access / OfflineSession feature?

@thomasdarimont This is a good question. It should (as also @mposolda replied) and I've added a test for it based on `OfflineSessionTest` into the code base.

@mposolda 
>     1. Do we want feature flag for this capability? IMO it is sufficient to handle new broker option in admin console and in the configuration to be available just when feature enabled. Or is it unnecessary overhead? PREVIEW feature at 1st can be nice.

I've added `TRANSIENT_USERS` feature flag. Could you please check if this approach works for you?

> 2\. Is it possible to add test for those scenarios to ensure they work as expected?:
>         -- SSO login
>         -- Refresh token
>         -- Refresh of offline token (to @thomasdarimont question: I think that offline sessions would work fine and user would be "transient" for the whole lifecycle of offline user session if I understand correctly?)
>         -- Sending request to UserInfo endpoint (on `consumer` realm side)
>         -- Sending request to introspection endpoint (on `consumer` realm side)

It is. I have currently only added the offline_access test since that one is most cumbersome, and will work on the others later. Could you please check if they are sufficient?

> 3\. I am not 100% sure if we want user to be read-write once it finished authentication and is saved in userSession? I understand it needs to be writable when still in authenticationSession (due update-profile page often displayed to user after first IDP login etc). In general, it might be more clear to me to indicate that if such user tries to update himself in account console (or admin tries to update him), that the message like "User is read-only" is displayed instead of silently updating user, which would be lost upon next login. But I don't know what is best regarding usability here? I am curious for more opinions (WDYT @thomasdarimont @pedroigor ?

I would not mind either way, but I need to check if this is possible. Not sure especially in case of consents (case where the user authenticates to two applications but additional consent is required for the second one). Also when the user in the user session is writable, it is possible for the admin to tune the roles by assigning the roles to the user from admin console directly instead of doing that via mappers and logout-login trial rounds which may lead to more convenient user (admin) experience.

**Comment by mposolda** [comment]
> I've added `TRANSIENT_USERS` feature flag. Could you please check if this approach works for you?

@hmlnarik Thanks! I would like to approve your PR once tests are OK (Updates are needed in quarkus integration tests always when new feature is added. You can check recent PR from @thomasdarimont on what needs update when new feature is added https://github.com/keycloak/keycloak/pull/23892 )

> > 2. Is it possible to add test for those scenarios to ensure they work as expected?:
> > -- SSO login
> > -- Refresh token
> > -- Refresh of offline token (to @thomasdarimont question: I think that offline sessions would work fine and user would be "transient" for the whole lifecycle of offline user session if I understand correctly?)
> > -- Sending request to UserInfo endpoint (on `consumer` realm side)
> > -- Sending request to introspection endpoint (on `consumer` realm side)
> 
> It is. I have currently only added the offline_access test since that one is most cumbersome, and will work on the others later. Could you please check if they are sufficient?

That works for me, Thanks!

> 
> > 3. I am not 100% sure if we want user to be read-write once it finished authentication and is saved in userSession? I understand it needs to be writable when still in authenticationSession (due update-profile page often displayed to user after first IDP login etc). In general, it might be more clear to me to indicate that if such user tries to update himself in account console (or admin tries to update him), that the message like "User is read-only" is displayed instead of silently updating user, which would be lost upon next login. But I don't know what is best regarding usability here? I am curious for more opinions (WDYT @thomasdarimont @pedroigor ?
> 
> I would not mind either way, but I need to check if this is possible. Not sure especially in case of consents (case where the user authenticates to two applications but additional consent is required for the second one). Also when the user in the user session is writable, it is possible for the admin to tune the roles by assigning the roles to the user from admin console directly instead of doing that via mappers and logout-login trial rounds which may lead to more convenient user (admin) experience.

Good points. Regarding consents, it looks that they may still work even for read-only users? The methods for CRUD consents are not part of the `UserModel` itself. Which makes me wondering if consents are really stored in-memory for "transient users" in your PR or if they are stored in the DB? It will be good to make sure to not persist them to the DB for transient users IMO (dead records in the DB after transient user is removed from memory etc). However IMO this can be done as a follow-up PR (if it is really an issue) as we have the PREVIEW flag?

**Review by jonkoops — DISMISSED** [review]

**Review by mposolda — DISMISSED** [review]

**Comment by mposolda** [comment]
@hmlnarik Approving, Thanks! IMO all the other things can be addressed as follow-ups if needed.

**Comment by hmlnarik** [comment]
Thank you for your reviews @jonkoops and @mposolda.

Due to conflicts, I have rebased, and also added SSO, introspection and userinfo endpoints tests.

> [...] if consents are really stored in-memory for "transient users" in your PR or if they are stored in the DB? It will be good to make sure to not persist them to the DB for transient users IMO (due "dead" records in the DB after transient user is removed from memory etc). However IMO this can be done as a follow-up PR (if it is really an issue) as we have the PREVIEW flag?

That's a good observation, consents are stored explicitly via [`UserProvider` methods](https://github.com/keycloak/keycloak/blob/fb6af4d301f7a6f1f8efa3c4770b8f471689c193/server-spi/src/main/java/org/keycloak/models/UserProvider.java#L103-L158). They should be rather part of `UserModel` which would allow them to be overridden in the `LightweightUserAdapter` class. I agree this should be done in a follow-up task.

Once the tests finish and this PR is approved, I would create two follow-up issues before its merging: one for docs and the other for updating the consents behaviour.

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Review by jonkoops — APPROVED** [review]

**Review by mposolda — APPROVED** [review]

**Comment by thomasdarimont** [comment]
Thanks for your clarifications @hmlnarik! However, what worries me a bit is how this will impact memory consumption in usage scenarios with a large number of offline sessions which might be valid for quite a long time (multiple days, weeks, months...).
Currently I see customer systems which have 10s of millions of offline sessions and 10s GB of heap consumed just by offline session foot-print in memory (although [this idea](https://github.com/keycloak/keycloak/discussions/24263)  might help with that a bit). 

For reference: currently an offline user session entry looks like this:
image
The base64 encoded `KC_DEVICE_NOTE`   decodes to a string something like this:

```
'{"ipAddress":"172.26.0.1","os":"Other","osVersion":"Unknown","browser":"Apache-HttpClient/4.5.14","device":"Other","lastAccess":0,"mobile":false}'
````

This is IMHO quite wastefull as the information is rarely used. I think there is room for optimization here :)

 From your PR I see that you use the offline session entity to store the "transient" user data as a session note here: https://github.com/keycloak/keycloak/pull/23977/files#diff-1445188baf4e2f8d90de96fc76d0423dd86425d2a0a9ede5c3e20d88c3f85077R762

I was wondering whether this will blow up memory consumption even more, if this is used in large real world CIAM use cases.

For completeness a offline client session looks like that:
image

**Comment by mposolda** [comment]
@thomasdarimont Good points!

IMO the stable user identifier might be useful for most of the cases. If we can use ID relying on "ID from IDP" instead of using broker session ID (which is not stable as it would differ between logins), we can ensure stable ID IMO?

One advantage can be application compatibility, but also when returning back to consents: Stable ID will allow to use persistent consents as even if the user himself is not saved in the Keycloak DB, the consents can be persisted and user won't need to confirm consent at every login as long as IDP ID is stable and consents are persisted in Keycloak DB. Here I am not 100% sure if consents should be persistent or transient by default. Looks rather transient as I suppose lots of people, who want "Transient users" feature, usually want this due to very rare login of their users? Also not 100% sure if there is foreign key from "consents" table to the USER_ENTITY table (or other tables), which would prevent to save consent for the user, which is not persisted anywhere in Keycloak DB, but I guess this can be solved if needed...

Regarding memory: It looks that we have lots of space for improvements in general. Some notes are not relevant for offline sessions at all. Also the "keys" can be shortened to avoid repeating and/or we can maybe come with more memory friendly format than using JSON for the "data". Maybe we can come with some SPI, which will allow flexibility for what should go to offline sessions? Like "Offline session mapper SPI" or something like that?

IMO both those points can be addressed as follow-ups. Especially "offline session tuning" is separate topic not directly related to this one though as it is already a problem (without this PR being merged). I would just add a note (or warning) to the documentation that using "transient users" can increase memory consumption. And especially for offline sessions, people might be encouraged to consider whether to use this or rather use "persistent" users if they need offline sessions.

**Comment by thomasdarimont** [comment]
Thanks for your thoughts Marek!

I wonder if it make sense to still store dedicated entities for brokered users, e.g. when the scope offline_access is used - instead of just storing the user data as a session note (SESSION_NOTE_LIGHTWEIGHT_USER). Having dedicated user entities allows to use the existing structures, store consents, and easier queries. I mean the user session note SESSION_NOTE_LIGHTWEIGHT_USER, when persistet in the database, is just another form to make the user persistent - but it's a lot harder to use (queries, consents, etc.).

**Comment by hmlnarik** [comment]
@thomasdarimont Thank you for the detailed concerns.

 - _Stable identifiers._ The transient users do not intentionally have stable identifiers of their own. The users leave no trace in Keycloak database. However, as long as it is desirable, it can be done similarly to similar handling transient name ID in SAML assertions: A claim or SAML attribute containing a stable identifier from the original identity provider can be mapped to the lightweight user attribute and later mapped from there to individual clients.

 - _Memory consumption._ I agree with @mposolda that this is much wider problem than the lightweight sessions and should be approached as such. The specific problem for offline sessions is there only if the mapper for offline_access exists for lightweight users, enabling offline sessions, which can and should be documented, and explicitly discouraged since it seems to be in conflict with the original intention of _transient_ users. Decision to enable it should be very well justified.
   The querying for the users can be still done similarly to what has been supported up until now, i.e. by broker alias, broker username and / or broker session ID.
   Perhaps could you introduce an issue / discussion on optimizing offline session storage? On a related note I also wonder whether disabling offline session preloading and limiting the number of offline sessions in the cache would not solve this issue, but that's for a separate discussion?

**Comment by thomasdarimont** [comment]
Thanks for your comments @hmlnarik! Perhaps we could use the discussion here: https://github.com/keycloak/keycloak/discussions/24263 to collect ideas for optimizing the offline session feature.

I agree that the offline session limitations for transient users must be clearly documented.

**Comment by hmlnarik** [comment]
I believe that there are the following use cases, each covering a differrent feature:
1. Users are stored in Keycloak until explicitly deleted by admin - this is what we have now
2. Users are stored in Keycloak until expired or explicitly deleted - not implemented yet, see #10370
3. Users are stored in Keycloak until logged out (in memory) - this PR [consents excluded]
4. Users are stored in Keycloak until logged out with ability create in offline sessions - this PR [consents excluded]

The difference between Options 1,2 and 3,4 is whether the user owns the decision when their data is removed from Keycloak. This PR adds capability to do so, supporting cases 3 and 4. Technically it uses purely the sessions to make it straightforward to implement and assure correct behaviour. For this reason I would prefer storing consents (in a follow-up PR) in the session data only, similarly to the user record. Related to Thomas's comment: it can use custom session notes storage in the future, the rule would be to keep it local to the session.

> Stable ID will allow to use persistent consents as even if the user himself is not saved in the Keycloak DB, the consents can be persisted and user won't need to confirm consent at every login as long as IDP ID is stable and consents are persisted in Keycloak DB.

The aim of the transient users feature is to leave any trace of the user or information correlable with a user out of Keycloak database. (This relates e.g. to storage limitation as specified in [GDPR Art. 5](https://gdpr-info.eu/art-5-gdpr/).) Keycloak as a system cannot determine what the appropriate storage period is however an admin can. If the admin determines that the users should be kept in Keycloak as transient, they may knowingly disable or enable offline access and I believe it is correct to assume that Keycloak does not accidentally store any such information which would lead to personally-identifiable data.

Keeping consents of transient users in the database with a identifiable stable identifier would leave a trace of the user there which can lead to identification of the user: consents relate to (group of) applications which may be used by a specific (group of) users. This seems to me to go against the original intention of keeping no direct or indirect information about the user stored after the user vanishes from the system. Persistent consents would only be possible for persistent users.

I will copy / summarize this discussion into an follow-up issue for consents.

**Comment by hmlnarik** [comment]
Thank you everyone for comments and reviews. I've introduced #24277, #24278, and #24279 as follow-up issues, and am merging the PR now.

**Comment by mposolda** [comment]
@hmlnarik +1 for having "transient consents for transient users" as the default user and priority. We can see later based on the feedback if we ever need also "persistent consents for transient users".

**Pull request merged**
