### PR TITLE
Improve Quarkus configuration tests execution

### PR DESCRIPTION
**Pull request by mabartos**
Prerequisite of https://github.com/keycloak/keycloak/pull/28597 to separate test changes and make PR review smoother.

@vmuzikar @shawkins @Pepo48 Could you please check these small improvements?

### CODE REVIEW

**Review by shawkins — APPROVED** [review]
LGTM, makes sense to have a base class rather than extending the test class.

**Review by vmuzikar — APPROVED** [review]
@mabartos LGTM, thank you!

@Pepo48 Do you want to review as well?

**Comment by mabartos** [comment]
I don't think these minor changes require so many eyes :P

**Comment by vmuzikar** [comment]
> I don't think these minor changes require so many eyes :P

Agree, I just saw @Pepo48 was assigned as a reviewer.

**Review by Pepo48 — APPROVED** [review]
LGTM. Thanks, @mabartos.

**Pull request merged**
