### PR TITLE
KEYCLOAK-3050 - fix npe on deployment

### PR DESCRIPTION
**Pull request by tubbynl**
Fix on npe in RefreshableKeycloakSecurityContext

fixed on the 1.9.x branch but it's also eligible for the master as far as i can tell

### CODE REVIEW

**Comment by stianst** [comment]
Do you have steps to reproduce deployment being null? I'm pretty sure it shouldn't be and that's the issue rather than this.

**Comment by tubbynl** [comment]
we are also working on the fix on our side; it's something during load-time and is probably related to our KeycloakConfigResolver implementation returning a KeycloakDeployment having a null realmKey.

My guess is that based on such a KeycloakDeployment (thus having configured: false) results in having a null KeycloakDeployment further down the line.

But aside of that problem; the class accepts a null KeycloakDeployment on construct and setCurrentRequestInfo thus checking for null is good practice (if the null is an invalid scenario it should be checked upon construct/set).

And inside refreshExpiredToken it is also checked for null but that's one line after the isActive is triggered so adding the null check inside isActive is needed or the if statement around the isActive check inside refreshExpiredToken should also check for a null deployment.

**Comment by stianst** [comment]
As I said the deployment shouldn't be null. If the code can expect the deployment to never be null there's no need to check in the constructor and/or methods. That will just end up with a whole bunch of boilerplate code. I appreciate that the adapter should probably check that the deployment isn't null if a custom KeycloakConfigResolver is used, but that's a separate issue. Feel free to create a JIRA for that and PR as well if you want.

**Comment by tubbynl** [comment]
For the ticket see https://issues.jboss.org/browse/KEYCLOAK-3050 

as mentioned inside RefreshableKeycloakSecurityContext there are already nullchecks on deployment but too late so according to your statement those null checks are also not required?

**Comment by stianst** [comment]
If RefreshableKeycloakSecurityContext can be guaranteed that deployment isn't null then yes that shouldn't be required. I can't quite understand how deployment could be null unless a custom broken KeycloakConfigResolver is used. My main point is that there may be several places that would break if deployment is null. I'll get someone that knows the adapter code more in detail to take a look at this PR.

**Comment by tubbynl** [comment]
thank you 👍 

i do agree with you that it's nullability will probably result on more issue's but i think it should be either nullable or not; and not partially nullable :)

**Comment by patriot1burke** [comment]
IIRC, a null deployment means that the adapter isn't configured.  This is a valid condition and is so that the KeycloakConfigResolver can be triggered.

**Comment by tubbynl** [comment]
cool, thank you!

**Comment by tubbynl** [comment]
is more followup required from my side to update the ticket? KEYCLOAK-3050

as mentioned in the ticket this fix is also eligible for the master; that is merged automatically?

**Pull request merged**
