### PR TITLE
KEYCLOAK-1542 more informations shown on Server Info page

### PR DESCRIPTION
**Pull request by velias**

### CODE REVIEW

**Comment by stianst** [comment]
I don't like the way mongo/jpa details are added. Firstly it shows details for both JPA and Mongo regardless of which is actually used. Secondly jpa/mongo connections SPIs are internal SPIs and only used indirectly by other SPIs so shouldn't really be used directly from server-info.

We need a generic way of showing information from providers. One problem with that is that we need to know what providers are actually in use. We know for example if JPA realm provider is in use (as that's the configured provider for realms), but we don't not if JPA Connection Providers (as that's only consumed indirectly from JPA realms). We may also need to add more endpoints for this though as server-info is used quite heavily by admin console so it needs to be light-weight.

Can you drop the db/mongo specific stuff from this PR then we can merge it? Then we can discuss on how to proceed with adding provider specific details?

**Comment by velias** [comment]
JPA and Mongo providers are maybe internal providers not so important for you from functional point of view, but they are very important from operational/management point of view I believe. They define points where KC integrates with other systems. They require specific configuration which may vary in different environments where you deploy them, so it is important to be able to check this configuration quickly when troubleshooting is necessary.

Also I don't think that in production environment somebody configures JPA or Mongo provider if he does not use it. If provider is not configured then it is not shown on the Server Info page. I believe this is correct.
Generic way how to get info from providers may be cool, but for Server Info page you still need to know how to present this information to the user. I'm not sure if this can be done in a generic way but still human readable enough ;-)

I had no idea that server-info endpoint is used in other parts of Admin console. In this case we should create another endpoint as you propose, or add some param to existing endpoint which allows to define what kind of info you want to get back (without the param it will return only minimal info necessary in all parts of Console). But JPA and Mongo info is not so big just now ;-)

OK, I can drop the JPA or Mongo part now, or we can keep it for now as is (as I believe it is useful still) and replace it by generic mechanism later.

**Comment by stianst** [comment]
I'm not arguing against adding this information, I'm just commenting on how to add it.

I don't see any issues with adding a generic way for providers to deliver more info about themselves. It's just as simple as allowing a provider to return a map<string,string> with additional info. What you're display for jpa/mongo providers above is just that (a list of key->value). So I'd rather we add something like that.

With that in mind I'd much prefer to have PR without the jpa/mongo stuff, merge that straight away. Then we can discuss how a generic mechanism for providers would look like.

**Comment by velias** [comment]
OK, but remove and then add back may be extra work. If we can quickly agree solution now which is cloase to what I implemented already then it may be less work. If you think it is more complicated to add generic way or it should be done by completely different way then I can remove this part of code.

What about only change `MonitorableProviderFactory.getOperationalInfo()` to return `Map<String, String>` instead of `ProviderOperationalInfo` object, and maybe rename this method and/or interface? `MonitorableProviderFactory` is marker interface to mark providers which are able to provide some extra info about itself. If we add this method directly into `ProviderFactory` then it requires change of lot of code (as there is lots of providers), not sure if it is necessary to do.
If you think this is wrong then I go to remove the code ;-)

**Comment by stianst** [comment]
Sure, we can hold off. FIY it'll have to be completed and merged today or wait until after 1.4 is released.

What you propose sounds good - with regards to admin console I think the providers that support it should have a link to view details about it. This can just open a modal dialog (like what's used for events to display representations or auth info). Further the standard server-info endpoint shouldn't return provider details, this should be a separate endpoint used by the modal dialog.

Does that make sense?

**Comment by velias** [comment]
OK, I'd like to have this in 1.4 as we plan to deploy it, so I'll try to do my best to update this PR to be mergeable today.

**Comment by velias** [comment]
OK, obtaining of info from providers is generic now, it is shown in table of providers, and is collapsed by default. Finally I decided to create completely new endpoint `/serverinfopage` for this page not to pass too much data into `/serverinfo` which is used on other admin gui pages. `/serverinfo` is now same as was before I started.

**Comment by velias** [comment]
OMG, what is going on? I rebased my branch to latest master and now this PR contains all changes even from other peoples.

**Comment by velias** [comment]
Looks like some Github bug. When I hit "Create new PR" from my branch then it shows only 15 changed files, but this PR shows much more

**Comment by velias** [comment]
closing this PR as it contains some unrelated commits, will create new one

**Pull request closed without merging**
