### PR TITLE
Remove dependency on snapshot repository for the regular build

### LINKED ISSUE #25892: Test suite depends on artifacts built only when distribution profile is active
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

When starting the build with `mvn clean install` the first time of the day, you'll see that Keycloak downloads artifacts from the Sonatype snapshot repository.

This effectively leads to a situation that a current build depends on the previous build, which is a cyclic dependency.

### Version

nightly

### Expected behavior

The build should not depend on Keycloak artifacts in the snapshot repository.

### Actual behavior

It depends for example on `integration-arquillian-servers-app-server-wildfly`

### How to Reproduce?

Delete all contents from the local Maven repo in the `org/keycloak` folder. 

The build also failed the repository was not available in build  https://github.com/keycloak/keycloak/actions/runs/7400254873/job/20133515228

### Anything else?

I'll prepare a PR

### PR DESCRIPTION
**Pull request by ahus1**
Closes #25892

### CODE REVIEW

**Comment by ahus1** [comment]
@ASzc / @stianst / @miquelsi - I found a strange circular build loop between Keycloak and Keycloak testing, where Keycloak's snapshot artifacts where downloaded from the snapshot repository in the test suite. 

This PR is an attempt to remove that repo connection, and to build the necessary bits in the default build. It is a bit more messy, but it works. The configuration could be simpler if we would choose to build more parts of the distribution. 

Happy to hear your thoughts. I think this change is necessary to have reliable builds in our release branches. 

Thanks!

**Comment by miquelsi** [comment]
Thanks for catching this @ahus1. Let me run an internal test pipeline before merging.

**Comment by ASzc** [comment]
This PR should be fine for product

**Comment by ahus1** [comment]
I rebased it as it acquired some conflicts. As it again lead to a strange behavior for one of our engineers today where it mixed a nightly build with a local build, I'd really like to get this merged with KC24 coming up. 

cc: @stianst

**Comment by ASzc** [comment]
Still LGTM

**Review by stianst — CHANGES_REQUESTED** [review]
This is a bit of a step backwards as it will now build WF feature-packs/etc with a default build. Looking at a different solution, but if I can't find a simple approach we can merge this as a temporary solution. Let's hold it a little bit for now though.

**Comment by stianst** [comment]
WIP on a different approach here: https://github.com/keycloak/keycloak/pull/26962

**Pull request closed without merging**
