### PR TITLE
Update Angular 2 example to Angular 2 final

### PR DESCRIPTION
**Pull request by eppsilon**
I've run this example against my own Keycloak instance, but I could use some info on how to run it the way the examples are meant to be run. Do I need to set up my own demo realm? Where is the product database the example tries to fetch from?

### CODE REVIEW

**Comment by benneq** [comment]
There's already Angular 2.0.0 final

**Comment by thomasdarimont** [comment]
Angular2 is final since today - perhaphs you'd like to update your example? :)
http://angularjs.blogspot.de/2016/09/angular2-final.html

**Comment by stianst** [comment]
@eppsilon take a look at preconfigured-demo dir in examples download from keycloak.org. It contains all the bits for the 'demo' including the example realm import, product database service, etc.

**Comment by eppsilon** [comment]
Ha, 2.0.0 came out a few hours after I made the PR. I've updated everything to use the final release.

@stianst Thanks for the info - I was able to test that the product list shows up and signing in/out works as expected.

**Comment by ssilvert** [comment]
I tried it too.  I'm going to go ahead and merge this, but it would be really nice if we could integrate better into maven so that we don't have to run npm install and tsc manually.

**Pull request merged**
