### PR TITLE
fix: fail to start if the admin user can't be added

### LINKED ISSUE #31160: Failed admin bootstrap behavior
If a user / service account fails to be created we should cause the creation of the master realm to fail. Otherwise the behavior is that the master realm will be created and the user must then use the cli to perform the bootstrap admin operation.

### PR DESCRIPTION
**Pull request by shawkins**
also allowing the bootstrap options to be used by the cli

and minor refactoring for clarity

closes: #31160 #31340

### CODE REVIEW

**Comment by shawkins** [comment]
@mabartos @vmuzikar @Pepo48 it was missed in the earlier pr that the bootstrap admin property mappers needed to be added to be used directly by the cli. Once added however they still showed up in the help system, even though they were marked as hidden. This was a side effect of the disabled mapper logic, so the help visibility check was simplified. If need be that could be separated to a different pr or backported individually.

**Review by Pepo48 — APPROVED** [review]
Thanks, @shawkins.

**Review by ahus1 — APPROVED** [review]
Approving as of @Pepo48's review. Let me know if it you're waiting for more reviews or if it should be merged.

**Comment by shawkins** [comment]
> Approving as of @Pepo48's review. Let me know if it you're waiting for more reviews or if it should be merged.

I think we are good. Created #31340 to track that aspect separately - we'll discuss with @vmuzikar and @mabartos if a backport is desirable.

**Pull request merged**
