### PR TITLE
Expected Scopes of ClientScopesCondition created on Admin UI are not saved onto ClientScopesCondition.Configuration

### LINKED ISSUE #9371: Expected Scopes of ClientScopesCondition created on Admin UI are not saved onto ClientScopesCondition.Configuration
### Describe the bug

On Admin Console - Realm Settings - Client Policies - Policies - Form View - [some policy], we created client scope condition and set some scope value to Expected Scopes.
After that, I sent an authorization request to keycloak with scope including one in Expected Scopes.
I expect that this request would be processed by the policy. However, keycloak's client scope condition judges "No".

### Version

15.0.2

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

I've already root cause of this issue and how to resolve it.

ClientScopesConditionFactory :
```
    public static final String SCOPES = "scopes";
```

ClientScopesCondition:
```
    public static class Configuration extends ClientPolicyConditionConfigurationRepresentation {

        protected String type;
        protected List<String> scope;
```

ClientScopesConditionFactory 's SCOPES value must much with ClientScopesCondition.Configuration 's scope field name.

In this case, 
```
        protected List<String> scope;
```
should be refactored as (also its getter/setter)
```
        protected List<String> scopes

        public List<String> getScopes() {
            return scopes;
        }

        public void setScopes(List<String> scope) {
            this.scopes = scope;
        }
```

Keycloak's UI codes read ClientScopesConditionFactory's property and its name, construct JSON representation automatically using this name. In this case,
```
          "configuration": {
            "scopes": [
              "read_account",
              "dummy"
            ],
            "type": "Optional"
```

However, the current keycloak tries to parse "scope" not "scopes" because current ClientScopesCondition.Configuration's field name is "scope".

Workaround is as follows.

On Admin UI, open JSON editor and rename "scopes" to "scope" like
```
          "configuration": {
            "scope": [
              "read_account",
              "dummy"
            ],
            "type": "Optional"
```

However, "scopes" might be appropriate as its representation, not "scope".

### PR DESCRIPTION
**Pull request by tnorimat**
Closes #9371

### CODE REVIEW

**Review by mposolda — CHANGES_REQUESTED** [review]
@tnorimat Thanks for catching this! The changes itself looks fine to me, but I have one question: Should we also add small note to the migration guide about this issue? The thing is, that if someone currently already set JSON manually and used something like:
```
"scope": [ "foo" ]
```
in the JSON configuration, the things will stop working for him. Hence we can likely add some note that guys may need to edit the policy and update the field name in their config? WDYT?

**Comment by tnorimat** [comment]
@mposolda I agree with you. How about the following instruction?
```
Migrating to 17.0.0

Client Policies Migration : client-scopes

If you used a policy including client-scopes condition and edited JSON document directly, you will need to change "scope" field name in a JSON document to "scopes".
```

I'm not sure how to write upgrade guide. Is the following step is appropriate?

1. add changes-17_0_0.adoc to /upgrading/topics/keycloak of keycloak-documentation
2. write instructions on changes-17_0_0.adoc
3. modify changes.adoc to include changes-17_0_0.adoc

**Comment by mposolda** [comment]
> @mposolda I agree with you. How about the following instruction?
> 
> ```
> Migrating to 17.0.0
> 
> Client Policies Migration : client-scopes
> 
> If you used a policy including client-scopes condition and edited JSON document directly, you will need to change "scope" field name in a JSON document to "scopes".
> ```
> 
> I'm not sure how to write upgrade guide. Is the following step is appropriate?
> 
>     1. add changes-17_0_0.adoc to /upgrading/topics/keycloak of keycloak-documentation
> 
>     2. write instructions on changes-17_0_0.adoc
> 
>     3. modify changes.adoc to include changes-17_0_0.adoc

@tnorimat Yes, I think that your steps for the documentation are correct and text itself is nice to me. Once you have the PR for these changes, we can merge both the PRs together (This PR for the "keycloak" repository and your next PR for the "keycloak-documentation").

**Comment by tnorimat** [comment]
@mposolda Thank you. I will send PR for keycloak-documentation.

**Comment by mposolda** [comment]
@tnorimat Thanks!

**Comment by tnorimat** [comment]
@mposolda I've sent PR for documentation https://github.com/keycloak/keycloak-documentation/pull/1394

**Review by mposolda — APPROVED** [review]

**Pull request merged**
