### PR TITLE
[WIP] Integrate the new login code to KeyCloak

### PR DESCRIPTION
**Pull request by junezhang**
Integrate the new login code to KeyCloak

# Currently Progress
- Basic Login - Done
- Forgot the password - Done
- Register - Done
- One Column Social Account - Done
- Two Column Social account - Need developer's effort

# Next step
- Refine social account style
- Refine the Login.css style file
- Add responsive design 
- Switch Language Bug

### Basic Login
screen shot 2018-01-25 at 11 08 02 pm

### Social Account - one column
screen shot 2018-01-31 at 4 35 33 pm

### Social Account - two column
screen shot 2018-01-31 at 4 30 49 pm

### CODE REVIEW

**Comment by junezhang** [comment]
@stianst @ssilvert 

- Have updated the new PatternFly version.
- Remove the annotation code

# Next step
- Refine social account style
- Refine the Login.css style file
- Add responsive design 
- Switch Language Bug

**Comment by ssilvert** [comment]
June, please fix conflicts.

**Comment by junezhang** [comment]
@ssilvert please re-check there is no conflicts here.

**Comment by stianst** [comment]
I think GitHub is complaining due to the merge commit in the PR. You shouldn't send PRs with merge commits in.

**Comment by junezhang** [comment]
@ssilvert @stianst Re-send a commit. 
In this commit, I updated the social account part, but here I need the developer's effort on it.
When the amount of social account is less than 4, then it displays in one column.  like the attachment (social account - one column) in the first comment.
When the amount of social account is more than 4 and less than 8, then it displays in two columns.

The new design html page is here
One column - https://rawgit.com/matthewcarleton/patternfly/login-responsive-dist/dist/tests/login-social-account.html
Two column - https://rawgit.com/matthewcarleton/patternfly/login-responsive-dist/dist/tests/login-social-account-two-column.html

I already added the class `${properties.kcFormSocialAccountDoubleListClass!}`.

when one column(<=4),
`<ul class="${properties.kcFormSocialAccountListClass!}">`

when two column(4<social account number<=8)
`<ul class="${properties.kcFormSocialAccountListClass!} ${properties.kcFormSocialAccountDoubleListClass!}">`

When social account > 8, hide by default. and click the "More" to show all the social account.

**Review by stianst — CHANGES_REQUESTED** [review]
zocial.css is an external library and we can't make changes to that

**Comment by junezhang** [comment]
@stianst Thanks for the external library reminder. Re-send a commit.
But if we can't change the zocial.css, then the icon will be on the left, and different with the new login as the icon is in the center.
Attached one screenshot as below:
 
screen shot 2018-02-02 at 4 12 02 pm

**Comment by stianst** [comment]
I think it's better to keep it as defined in zocial.css. Alternative would be to override the behaviour in zocial.css in login.css (or a zocial-override.css). We're already planning on upgrading zocial.css soon as there are some new icons (GitLab for one) and when we do we'd just end up overwriting any changes made here.

**Comment by stianst** [comment]
@junezhang By the way I think this is so good work that it would be great if you sent a PR with a single commit with all changes from this branch to the master branch then we can review it from there and get it into master soon. What do you think?

**Comment by junezhang** [comment]
@stianst Sure, I can do it. and now I haven't finished the responsive design and fixing the switch language bug. When I finish that, I will send PR to master.

But for the social account, I need developer's help. because when the amount of social account is less than 4, it is one column; when the amount of social account is more than 4, it is two columns. It needs some back-end code. :-)

**Comment by stianst** [comment]
We'll need to figure out a way to split it into columns either with some smart CSS3 (ideal) or with FreeMarker. I can take a look at that.

**Pull request merged**
