### PR TITLE
fix: added PATCH and PUT methods to get FormBodyHandler

### LINKED ISSUE #24986: `getMultiPartFormParameters()` always returns `EmptyMultivaluedMap` after upgrade to Resteasy Reactive
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

In `RealmResourceProvider` extensions that use `session.getContext().getHttpRequest().getMultiPartFormParameters()` to retrieve parts of a `multipart/form-data` request, the method now always returns an `EmptyMultivaluedMap` instead of the parts of the request.

### Version

23.0.0

### Expected behavior

This should return a `MultivaluedMap` with the parts represented in the request when given a valid `multipart/form-data` request. This worked properly in <23. 

### Actual behavior

It always returns an `EmptyMultivaluedMap`.

### How to Reproduce?

Create a `RealmResourceProvider` extension that returns the following `Object` for the `getResource()` method:
```java
public class TestResource {
  @PUT
  @Consumes(MediaType.MULTIPART_FORM_DATA)
  public Response test() {
    HttpRequest req = session.getContext().getHttpRequest();
    log.infof("mediaType %s", req.getHttpHeaders().getMediaType());
    log.infof("contentType %s", req.getHttpHeaders().getHeaderString("content-type"));

    MediaType mediaType = req.getHttpHeaders().getMediaType();
    log.infof("isCompatible %b", MULTIPART_FORM_DATA_TYPE.isCompatible(mediaType));
    log.infof("hasBoundary %b", mediaType.getParameters().containsKey("boundary"));

    MultivaluedMap<String, FormPartValue> formDataMap = session.getContext().getHttpRequest().getMultiPartFormParameters();
    if (formDataMap != null) {
      log.infof("formDataMap %s", formDataMap);
      for (String k : formDataMap.keySet()) {
        log.infof("key %s", k);
      }
    }
    return Response.noContent().build();
  }
}
```

Make any `multipart/form-data` request to it (doesn't matter what's in it, as long as it's valid). The resource method outputs:
```
[INFO] mediaType multipart/form-data;boundary=hkfxPWUJazkCuZXCBiD7pU6vV0WRLpsBsHhVrqJ
[INFO] contentType multipart/form-data; boundary=hkfxPWUJazkCuZXCBiD7pU6vV0WRLpsBsHhVrqJ
[INFO] isCompatible true
[INFO] hasBoundary true
[INFO] formDataMap org.keycloak.quarkus.runtime.integration.jaxrs.EmptyMultivaluedMap@dfc8632
```
-----

### Anything else?

There is a more complete example you can run in an existing extension and see the result in the unit test.

Pull the `xgp/23` branch https://github.com/p2-inc/keycloak-themes/tree/xgp/23 

Run: 
`mvn clean install -Dtest=EmailsResourceTest#testGetUpdateTemplateMaster`

### PR DESCRIPTION
**Pull request by xgp**
Fixes the issue of `PATCH` and `PUT` methods not getting a `FormBodyHandler` that was introduced in the transition to Resteasy Reactive. While the core Keycloak code only uses `POST` methods in processing `multipart/form-data`, REST extensions may use `PATCH` and `PUT`. This fix enables that.

cc @pedroigor @rmartinc 
closes #24986

### CODE REVIEW

**Review by rmartinc — CHANGES_REQUESTED** [review]
@xgp Change is OK for me but can you please add the signature for the commit. Just do something like:

```
git commit -s --amend
```

And push again. Now that is needed and there is also a DCO check that is failing.

Thanks for the PR!

**Comment by xgp** [comment]
Thanks @rmartinc I added the signature to the commit.

**Comment by pedroigor** [comment]
@xgp You should either squash commits and sign it or sign all of them ... If possible, please prefer the former approach.

**Comment by xgp** [comment]
@pedroigor I think I made the update to one, signed commit correctly. Let me know if it's still wrong. Apologies as my git-fu is not strong.

**Review by rmartinc — APPROVED** [review]
Thanks @xgp!

**Review by pedroigor — APPROVED** [review]
@xgp Nice catch around checking the `isFormParamRequired`. Thanks.

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
