### PR TITLE
Make base theme hidden for admin and account UIs.

### LINKED ISSUE #21421: After switching the Admin UI theme to "Base," an error occurred when attempting to access the keycloak login
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Hi,

We were able to install the quarkus based keycloak ( 21.1.1 ) and access its GUI. 
Later we changed the **Realm setting --> Themes --> Admin UI theme** to "base" and save it. 
Now after logging out from the UI if we again try to login to the keycloak UI we are facing the following error 

image

### Version

21.1.1

### Expected behavior

After changing the Admin UI theme to "base" and signing out we should be directed to the keycloak UI page.

### Actual behavior

After changing the Admin UI theme to "base" and signing out we are not able to get the keycloak login page.

### How to Reproduce?

Described in detail in the above section

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ssilvert**
Fixes #21421 

This just provides a quick patch for the issue above so users don't see the problem any longer.  It just removes the base theme from the dropdown.

The real fix will come when we solve https://github.com/keycloak/keycloak/issues/22671.

### CODE REVIEW

**Review by jonkoops — COMMENTED** [review]
The code changes look good to me, but a couple of questions/notes:

1. Should we not also prevent the selection of the `base` theme for the other UIs?
2. Perhaps a better approach would be to filter these options out at an API level (including the setting of a theme)?
3. Should we provide a database migration to unset the `base` theme if it has been set by the user?

**Comment by jonkoops** [comment]
> 1. Other themes like email and login can still use base as a starting point for theming. So it still needs to be there.

Ok, good to know, that might change in the future, but indeed is not relevant for now. Let's leave this as-is.

> 2. I'm not sure if that's a good idea or not. The base theme still technically exists for admin and account. I'm not sure if there would be some side effect of filtering it at the API level.

Not sure what the fallout would be, but I think this would still be the best place to solve this. In the spirit of keeping the front-end as 'dumb' as possible, which is something I believe @stianst feels strongly about. Also this would prevent us (or others) from having to re-implement this in the future for other/newer UIs.

> 3. Maybe.  But the base theme was really never meant to be used on its own.  So I don't see how anyone would have it set to `base` in a migration scenario.  I do admit it's possible though.  This PR is just to prevent catastrophic failure if someone sets the theme to `base` by mistake.  I think providing migration would be a wasted effort.

There are already users that have ended up in a situation where they have set the theme to `base` (including [reports from the issue](https://github.com/keycloak/keycloak/issues/21421#issuecomment-1664623735) this PR closes), so I don't this this is an extremely unlikely scenario. In any case, setting the theme to `base` for the new Account and Admin consoles should be considered harmful, so I think a migration might be sensible here.

**Review by jonkoops — DISMISSED** [review]
I am approving this since it addresses a quite critical problem, but I still feel we need a more complete solution in the future. But perhaps that is better addressed somewhere else.

**Comment by ssilvert** [comment]
> I am approving this since it addresses a quite critical problem, but I still feel we need a more complete solution in the future. But perhaps that is better addressed somewhere else.

Definitely agree.  That's why I opened #22671.

**Comment by ssilvert** [comment]
> There are already users that have ended up in a situation where they have set the theme to `base` (including [reports from the issue](https://github.com/keycloak/keycloak/issues/21421#issuecomment-1664623735) this PR closes), so I don't this this is an extremely unlikely scenario. In any case, setting the theme to `base` for the new Account and Admin consoles should be considered harmful, so I think a migration might be sensible here.

This PR only addresses the situation where they set the theme to `base` and it locked them out.  It is extremely unlikely that anyone has set their theme to `base` in a production situation that would need migration.

Some may have extended the `base` theme.  But that's a different problem for which there is no migration available without re-introducing AngularJs or fixing #22671.

**Review by jonkoops — APPROVED** [review]

**Pull request merged**
