### PR TITLE
Use the appropriate database dialect to add quotes to the schema name

### LINKED ISSUE #25961: Native SQL Schema names broken on MySQL
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When trying to delete a Role while running on MySQL, an error is thrown complaining about invalid SQL syntax, because the schema name is being wrapped in double quotes.

### Version

23.0.3

### Expected behavior

Should be able to delete realm without throwing a SQL error

### Actual behavior

An error is thrown and the Role is not deleted.

### How to Reproduce?

Run Keycloak on MySQL/MariaDB

### Anything else?

The bug was introduced in this commit: https://github.com/keycloak/keycloak/commit/dc9970f578144557d75e6e1e21f57dcdf6c70f38

### PR DESCRIPTION
**Pull request by ahus1**
Closes #25961

### CODE REVIEW

**Comment by ahus1** [comment]
This can be tested manually when testing with a schema specified. Use a CLI like the following: 

```
bin/kc.sh start --http-enabled true --hostname-strict false --health-enabled true --db mariadb  --db-username root --db-password pass --db-schema keycloak
```

**Comment by ahus1** [comment]
@sguilhen - please review when you have the time. The build looks quite green already.

**Comment by sguilhen** [comment]
Tested locally and it worked as expected. Approving, thanks @ahus1 !

**Review by sguilhen — APPROVED** [review]

**Comment by ahus1** [comment]
@mhajas - please merge when you have the time. Thanks!

**Review by mhajas — APPROVED** [review]
Approving based on review from @sguilhen

**Pull request merged**
