### PR TITLE
Decoupling legacy and dynamic user profiles and exposing metadata from admin api

### LINKED ISSUE #22532: Decoupling legacy and dynamic user profiles and exposing metadata from admin api
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

The legacy and dynamic user profile should be decoupled in order to avoid one impacting the other when managing user attributes.

In the 22 release, this coupling is causing:

* Username and e-mail fields are not properly managed depending on how the registration as username and edit username settings are set to a realm (using the different combinations of both)
* E-mail not properly managed and shown in UI when the update email feature is enabled
* Admin UI not properly rendering attributes when the user profile is enabled
* Admin API failing to update username/email depending on how the registration as username and edit username settings are set to a realm

### Version

22

### Expected behavior

Username and email are properly managed depending on how the registration as username and edit username settings are set to a realm.

Changes to legacy should not directly affect the dynamic user profile behavior, and vice-versa.

### Actual behavior

Username and email are not properly managed depending on how the registration as username and edit username settings are set to a realm.

Changes to legacy is affected by the dynamic user profile behavior, and vice-versa.

### How to Reproduce?

N/A

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #22532
Backport https://github.com/keycloak/keycloak/pull/22533

### CODE REVIEW

**Review by ahus1 — APPROVED** [review]

**Comment by stianst** [comment]
Not sure what's going on here, but the new store tests are taking a very long time in this PR:
image

Compared to latest run in release/22:
image

**Review by jonkoops — APPROVED** [review]

**Review by stianst — CHANGES_REQUESTED** [review]
For some reason in this PR the following jobs consistently times out (after 90 minutes):

* New Store IT (hot-rod)
* New Store IT (jpa-postgres)

Latest run in release/22.0 these completed well within the timeout:

* New Store IT (hot-rod): 31m
* New Store IT (jpa-postgres): 38m

I have no clue what's going on, but there is something in this PR that is causing this, as I've not seen the same for runs against release/22.0 or other PRs to release/22.0.

**Comment by pedroigor** [comment]
@stianst Talked with @vramik and we need to backport https://github.com/keycloak/keycloak/pull/21828. The `ZeroDowntimeTest`is ignored in `main` and that is why the same change set works there.

**Review by stianst — CHANGES_REQUESTED** [review]
Due to updating conditional tests in release/22.0 from main the store tests no longer run against this PR, so we can't verify if the store issues are resolved.

I've opened an issue to resolve this and sent a PR for it as well:
https://github.com/keycloak/keycloak/issues/23001

**Review by stianst — APPROVED** [review]

**Pull request merged**
