### PR TITLE
Use separate transactions for each bulk update of offline sessions in…

### LINKED ISSUE #13684: Offline User Session dead lock caused by PersisterLastSessionRefreshStore
### Describe the bug

There is a deadlock under some circumstances with latest Keycloak.

In case there are 2 cluster nodes and both updating DB at the same time from persister:

Node1 calling something like (real Ids replaced with placeholders):
```
update OFFLINE_USER_SESSION set LAST_SESSION_REFRESH=1656332405 where REALM_ID='X' and 
OFFLINE_FLAG='1' and (USER_SESSION_ID in ('a' , 'b' , 'c' , 'd'))
```
Node2 calling something like (real Ids replaced with placeholders):
```
update OFFLINE_USER_SESSION set LAST_SESSION_REFRESH=1656332405 where REALM_ID='Y' and 
OFFLINE_FLAG='1' and (USER_SESSION_ID in ('aa' , 'bb' , 'cc' , 'dd'))
```
From the lock monitor, both are named JPQL "updateUserSessionLastSessionRefresh" called from different RH-SSO node.

JPQL "updateUserSessionLastSessionRefresh" definition:
```
update PersistentUserSessionEntity sess set lastSessionRefresh = :lastSessionRefresh where sess.realmId = :realmId AND 
sess.offline = :offline AND sess.userSessionId IN (:userSessionIds)
```
https://github.com/keycloak/keycloak/blob/19.0.1/model/jpa/src/main/java/org/keycloak/models/jpa/session/PersistentUserSessionEntity.java#L38-L39

When token refresh or token introspection is requested to an offline session, RH-SSO need to update LAST_SESSION_REFRESH culumn of the OFFLINE_USER_SESSION table record,
but instead of issuing the update query immediately, RH-SSO enqueue the update request in AbstractLastSessionRefreshStore, and update them periodically.
JPQL "updateUserSessionLastSessionRefresh" is the query for this bulk update.

Since token refresh or token introspection requests from clients are distributed to RH-SSO nodes,
it may happen that multiple LAST_SESSION_REFRESH update queries are issued from different RH-SSO nodes at the same time.
If it happens to multiple sessions, it ends up in the dead lock because RH-SSO node wraps the multiple update request into one transaction.

### Dead lock flow example

If clients requests offline sessions X and Y to different RH-SSO nodes(A and B), RH-SSO Node A and B issues update queries in one transaction. This will cause dead lock. 

```
RH-SSO Node A ----> Begin Tx ----> Update Realm001 session X ---------------> Update Realm002 session Y  -----------> Dead 
Lock!(Waiting for Realm002 session Y)
RH-SSO Node B --------> Begin Tx ------------> Update Realm002 session Y -------------> Update Realm001 session X  -> Dead 
Lock!(Waiting for Realm001 session X)
```

### Solution proposal

Sorting the session update order will resolve the dead lock.

I think sorting the items by key here will work.
https://github.com/keycloak/keycloak/blob/19.0.1/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/sessions/PersisterLastSessionRefreshStore.java#L64
https://github.com/keycloak/keycloak/blob/19.0.1/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/sessions/PersisterLastSessionRefreshStore.java#L72

```
RH-SSO Node A ----> Begin Tx ----> Update Realm001 session X ---------------> Update Realm002 session Y ---> Commit ---> 
Finish!
RH-SSO Node B --------> Begin Tx ------------> Update Realm001 session X ------> (Wait for Realm001 session X lock) -----> 
Update Realm002 session Y --> Commit --> Finish!
``` 

Could you check my analysis? and if it valid, could you provide a fix and include it to the next RH-SSO 7.6 patch update?

### Version

19.0.1

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

This is related to ticket 293.

Originally reported by @ynojima

### PR DESCRIPTION
**Pull request by mposolda**
… PersisterLastSessionRefreshStore to avoid deadlocks

closes #13684

### CODE REVIEW

**Comment by mposolda** [comment]
@ynojima Do you have a chance to review and/or eventually test in your environment?

**Comment by ynojima** [comment]
Splitting transactions is a good way to reduce the life time of transaction and will contribute to reduce the probability of dead lock, but it still leaves some room to cause a dead lock.
Even within one realm, updating multiple sessions in unsorted order simultaneously may cause a dead lock.
What kind of regression do you have in mind if we sort sessions by the session id and realm name?
I think it is better to introduce both approach.

**Comment by mposolda** [comment]
@ynojima Thanks for the feedback. I've updated this a bit by adding sorting of `userSessionIds` . It should not hurt.

On the other hand, I think that deadlock should not happen even with my previous approach though? I am missing how can deadlock happen considering that each transaction will do only 1 SQL update request? I suppose that when transaction wants to call SQL update and it is not able to obtain the "update" lock for any of the updated rows, then the transaction needs to wait until the concurrent transaction ends before obtaining the locks. And none of the locks is obtained until all locks are free.

In other words, when transaction1 calls something like:
```
update OFFLINE_USER_SESSION set LAST_SESSION_REFRESH=1656332405 where REALM_ID='X' and 
OFFLINE_FLAG='1' and (USER_SESSION_ID in ('a' , 'b' , 'c' , 'd'))
```
And there is concurrent transaction2, which already has lock for the row 'b', then transaction1 needs to wait before it obtains locks for any of 'a', 'b', 'c' or 'd'. And once the concurrent transaction is finished and 'b' is free, then transaction should be able to obtain lock for all of 'a', 'b', 'c', 'd' at the same time.

Or am I wrong here?

Ad regressions: In general, I just wanted to have as small changes as possible as more changes in theory increases the probability of bug/regression. However sorting likely doesn't hurt as I pointed.


However concurrent transaction should always end in the small time (as it also does just 1 update request)

**Comment by ynojima** [comment]
>In other words, when transaction1 calls something like:
>
>update OFFLINE_USER_SESSION set LAST_SESSION_REFRESH=1656332405 where REALM_ID='X' and 
>OFFLINE_FLAG='1' and (USER_SESSION_ID in ('a' , 'b' , 'c' , 'd'))
>
>And there is concurrent transaction2, which already has lock for the row 'b', then transaction1 needs to wait before it obtains locks for any of 'a', 'b', 'c' or 'd'.

Are you saying transaction1 will ensure that all of the 'a', 'b', 'c', and 'd' locks are not taken before taking any of them?
Umm, in my understanding, transaction1 takes the lock for the row 'a', and waits for the lock for the row 'b'.
Sorry, I have no reference documents that explain this behavior, but from the MySQL implementation point of view, is it possible to ensure that all of the 'a', 'b', 'c', and 'd' locks are not taken before taking the locks? Ensuring locks are not taken sounds equal to taking locks.

**Comment by sschu** [comment]
AFAIK locks are obtained incrementally, that's why it is important for different transactions to obtain them in the same order to prevent deadlocks. The reason is it's generally not clear which rows will be touched at the start of the transaction because which data is touched down the road might depend on data read in earlier stages of a transaction.

**Comment by mposolda** [comment]
@ynojima @sschu Ok, Thanks guys! So my assumptions about the "update" SQL command takes all the locks as an "atomic operation" (either all locks taken at the same time before update command OR none of them) might be wrong. Also it may be DB dependent - also did not found any docs clearly describing this.

As I mentioned, latest version of this PR contains the ordering. Review (and eventually approve of this PR if you are fine with the changes) is welcome!

**Comment by ynojima** [comment]
Code looks good to me, but could you give me some time to test it in my local environment?

**Comment by mposolda** [comment]
@ynojima Sure, I am not in a hurry at all with this :-) Just a note that this is my last day before PTO - returning on Monday August 22 (just so you are not surprised by inactivity in this or other tickets).

**Review by ynojima — APPROVED** [review]
I confirmed it works in my test environment.

I attached remote debugger to the patched Keycloak NodeA and NodeB, and tried to cause dead lock by putting break points to join the concurrent requests, but Keycloak works well without dead lock.

**Comment by ynojima** [comment]
@mposolda gentle ping

**Comment by mposolda** [comment]
@ynojima Thanks for the confirmation!

@pedroigor Can I kindly ask you to review this one?

**Review by pedroigor — APPROVED** [review]

**Comment by mposolda** [comment]
@pedroigor Thanks!

**Pull request merged**
