### PR TITLE
Restore the Cache tab in Realm Settings

### LINKED ISSUE #17727: Restore the Cache tab in Realm Settings
### Description

I noticed that the Cache tab has been removed from the Admin UI since Keycloak v19.
I can still access it in v20 by switching the Admin Console Theme to "Keycloak" but I understand it will be removed in v21.

I'd like to ask to re-enable this tab.

### Discussion

https://github.com/keycloak/keycloak/issues/18313

### Motivation

As mentioned in [the discussion above](https://github.com/keycloak/keycloak/issues/18313) this function is supposedly rarely used. I can imagine that that's the case for server administrators, but for me as a developer of custom SPI's, having the ability to quickly flush the user cache is extremely useful.

Of course I _can_ use the `./kcadm.sh` utility, but in a typical scenario of manually editing timestamps in the DB and executing the custom REST endpoint to debug the code, having a simple button to make KC aware of the DB changes is really convenient. 

I can't judge whether or not that weighs up to the added effort of maintaining that tab, but I felt I should mention it in any case.

Thanks.

### Details

_No response_

### PR DESCRIPTION
**Pull request by yanxch**
closes keycloak#17727

### CODE REVIEW

**Review by edewit — DISMISSED** [review]

**Review by edewit — DISMISSED** [review]

**Comment by sschu** [comment]
@edewit I havent checked this PR but I do remember a discussion with @stianst where we agreed this should only be added to the master realm to not create the false impression that caches could be cleared for individual realms. It also makes sense from a permissions perspective that only master admins are allowed to do this.

**Comment by yanxch** [comment]
I thought that was a joke ;) 
https://github.com/keycloak/keycloak/issues/17727#issuecomment-1617563715

but no problem, just tell how you want it

**Comment by sschu** [comment]
Granted, it looked like one. But it was true. So it would be cool if you could add it to the master realm only.

**Comment by sschu** [comment]
@edewit Can you have another look, please?

**Review by edewit — APPROVED** [review]

**Pull request merged**
