### PR TITLE
Fix Hungarian translations

### LINKED ISSUE #35414: Capitalization in Hungarian translation needs improvement
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

translations

### Describe the bug

Capitalization in Hungarian translation needs improvement

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Correct translation

### Actual behavior

Incorrect capitalization

### How to Reproduce?

See translations

### Anything else?

PR already exists

### PR DESCRIPTION
**Pull request by vilmosnagy**
Closes #35414

 - change a few capitalizations and word order to sound more natural
 - add the translation for `selectALocale`, which was added in #21398

### CODE REVIEW

**Comment by ahus1** [comment]
@vilmosnagy - thank you for this contribution. Can you please sign-off your commit as outlined in the `CONTRIBUTING.md` file? 

We would also need a second native speaker to approve your changes. Can you please a friend or colleague to approve your changes?

**Comment by vilmosnagy** [comment]
@ahus1 signed-off, thanks for the reminder. Looking for a second reviewer :)

**Comment by vilmosnagy** [comment]
for future reference this is the capitalization issue i'm mentioning in the opening: 

image

after this change it'll be: `Új jelszó hozzáadása` (instead of `Új Jelszó hozzáadása`, see the capital `J`).

**Review by ahus1 — APPROVED** [review]
Approving based on native speaker's review

**Review by jonkoops — APPROVED** [review]
Thanks for the fix and the reviews!

**Pull request merged**
