### PR TITLE
Add setup erase command to example for adding more RPMs to the server container

### LINKED ISSUE #23637: Some container implementations don't work with the documented additional RPM install procedure
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

docs

### Describe the bug

It appears docker's handling of /etc/passwd does not interact well with the documentated procedure for installing additional RPM packages in a customized container. podman and kubernetes appear unaffected.

https://www.keycloak.org/server/containers#_installing_additional_rpm_packages

See https://github.com/keycloak/keycloak/discussions/23166

### Version

main

### Expected behavior

The customized container should boot

### Actual behavior

The customized container fails with an error about the 1000 user being missing

### How to Reproduce?

Run the extra RPM procedure as documented with a system that uses original docker for container management

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ASzc**
Closes #23637

### CODE REVIEW

**Comment by SomeDeveloper13** [comment]
@ASzc - When I tested this locally on my windows machine with Docker Desktop, this appears to have fixed the issue.
image

**Review by shawkins — APPROVED** [review]
LGTM, testing the old method with plain docker the container comes up for me but running a docker exec with whoami say it can't find the 1000 user.  With the new one it reports keycloak.

**Review by vmuzikar — APPROVED** [review]
@ASzc Thanks! Approving based on @shawkins' review.

@ASzc Can you please prepare a backport to 22?

**Comment by ASzc** [comment]
@vmuzikar Backport branch: https://github.com/keycloak/keycloak/pull/23668

**Pull request merged**
