### PR TITLE
Return Oracle JDBC driver to the upstream

### LINKED ISSUE #22999: Return Oracle driver
### Description

Return the Oracle driver back to upstream Keycloak as there're no requirements to remove it here. The driver should be removed only when `product` product is activated. We can use similar approach as  [here](https://github.com/keycloak/keycloak/commit/aae4569071fdb115394dfb5dce506a57852d1706#diff-8c389ae6ee129b90bd762d101c2c3c00fe0b0af41cb3b352150706552682c28b).

### PR DESCRIPTION
**Pull request by mabartos**
Closes #22999

I've been following #22577 and #22598.

Tested built Keycloak distro in community/product mode and also the `auth-server-quarkus`. Everything should be working as expected.

@vmuzikar @ahus1 Could you please check it?

### CODE REVIEW

**Review by vmuzikar — DISMISSED** [review]
LGTM, thanks

**Review by ahus1 — DISMISSED** [review]

**Comment by mabartos** [comment]
@vmuzikar @ahus1 Sorry, forgot to include changes for the present test (https://github.com/keycloak/keycloak/pull/22934/).

**Review by ahus1 — APPROVED** [review]

**Review by vmuzikar — APPROVED** [review]

**Comment by mabartos** [comment]
Something bad happened to GHA CI. 

@ahus1 @vmuzikar Could you rerun it, please?

**Comment by ahus1** [comment]
@mabartos - ok, did a re-run of all jobs. Let's wait a moment. If it doesn't help, please rebase and force-push.

**Pull request merged**
