### PR TITLE
Improved french translation

### PR DESCRIPTION
**Pull request by gaetancollaud**
In french, the "forgot password" email displays the full link instead of having a message like other languages.

`Lien pour réinitialiser votre mot de passe` = `Link to reset your password`.

The english message use _credentials_ instead of _password_ but there is no such word in french.

### CODE REVIEW

**Review by jayblanc — APPROVED** [review]

**Review by stianst — APPROVED** [review]

**Comment by antoine-roux** [comment]
In french, _credentials_ can be translated by _identifiants_

**Comment by jayblanc** [comment]
I think in that application context it is better to speak about password. It is the goal of this link. 'identifiants' means association between login and password in my mind and it is only possible to change the password...

**Comment by antoine-roux** [comment]
@jayblanc Yes, I agree :)

**Comment by kvart2006** [comment]
"Lien pour réinitialiser votre mot de passe" 
is correct!
You could also say:
"Lien pour réinitialiser le mot de passe"

**Pull request merged**
