### PR TITLE
KEYCLOAK-12431: don't use user agent but patternfly

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Comment by abstractj** [comment]
Reassigning it to @ssilvert as he's the best person to take care of this PR.

**Comment by ssilvert** [comment]
@edewit We need to defer this until after 7.4.  Please remind me to take a look after that.

**Review by ssilvert — COMMENTED** [review]
The code looks fine.  I assume the screens look good on both desktop and mobile?

Just need a successful UI tests run before we can merge.

**Comment by edewit** [comment]
UI test run: https://keycloak-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/keycloak-account2-matrix/845/

**Comment by edewit** [comment]
UI test run: https://keycloak-jenkins.com/job/keycloak-account2-matrix/845/

**Review by vmuzikar — COMMENTED** [review]
@edewit Could you please rebase? It's currently based on some very old branch and I'm not even able to build it. All of the tests were skipped for some reason. Please run them again as well once you've rebased.

**Comment by edewit** [comment]
rebased @vmuzikar new build: https://keycloak-jenkins.com/job/keycloak-account2-matrix/864/

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@edewit Thanks!

It seems there are some missing margins in mobile layout:
Screenshot 2020-04-23 at 10 47 26

Also, one test is failing.

**Comment by edewit** [comment]
@vmuzikar fixed the test and the padding https://keycloak-jenkins.com/job/keycloak-account2-matrix/865/

**Review by vmuzikar — APPROVED** [review]
LGTM, thank you @edewit!

**Review by ssilvert — APPROVED** [review]
Code looks good.   @vmuzikar is happy with the screens.  Approving.

**Pull request merged**
