### PR TITLE
Could not format default value for log formats

### LINKED ISSUE #25908: Could not format default value for log formats
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

When the `help` or `help-all` is executed, there are warnings about the inability to format provided default value for the console and file log format, in the header. It leads to ugly log messages.

See:
```
[picocli WARN] Could not format 'The format of unstructured console log entries. If the format has spaces in it, escape the value using "<format>". Default: %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n.' (Underlying error: Conversion = 'p'). Using raw String: '%n' format strings have not been replaced with newlines. Please ensure to escape '%' characters with another '%'.
[picocli WARN] Could not format 'The format of unstructured console log entries. If the format has spaces in it, escape the value using "<format>". Default: %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n.' (Underlying error: Conversion = 'p'). Using raw String: '%n' format strings have not been replaced with newlines. Please ensure to escape '%' characters with another '%'.
[picocli WARN] Could not format 'The format of unstructured console log entries. If the format has spaces in it, escape the value using "<format>". Default: %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n.' (Underlying error: Conversion = 'p'). Using raw String: '%n' format strings have not been replaced with newlines. Please ensure to escape '%' characters with another '%'.
[picocli WARN] Could not format 'Set a format specific to file log entries. Default: %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n.' (Underlying error: Conversion = 'p'). Using raw String: '%n' format strings have not been replaced with newlines. Please ensure to escape '%' characters with another '%'.
[picocli WARN] Could not format 'Set a format specific to file log entries. Default: %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n.' (Underlying error: Conversion = 'p'). Using raw String: '%n' format strings have not been replaced with newlines. Please ensure to escape '%' characters with another '%'.
[picocli WARN] Could not format 'Set a format specific to file log entries. Default: %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n.' (Underlying error: Conversion = 'p'). Using raw String: '%n' format strings have not been replaced with newlines. Please ensure to escape '%' characters with another '%'.
Start the server.

Usage: 

kc.sh start [OPTIONS]

Use this command to run the server in production.

Options:

-h, --help           This help message.
--help-all           This same help message but with additional options.
--import-realm       Import realms during startup by reading any realm configuration file from the
                       'data/import' directory.
--optimized          Use this option to achieve an optimal startup time if you have previously
                       built a server image using the 'build' command.
-v, --verbose        Print out error details when running this command.

```

### Version

999

### Expected behavior

No warnings

### Actual behavior

Warnings about the format

### How to Reproduce?

Execute `./kc.sh start --help-all`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
Closes #25908 

Log after providing these changes (no warnings about these formats):
```
Start the server.

Usage: 

kc.sh start [OPTIONS]

Use this command to run the server in production.

Options:

-h, --help           This help message.
--help-all           This same help message but with additional options.
--import-realm       Import realms during startup by reading any realm configuration file from the
                       'data/import' directory.
--optimized          Use this option to achieve an optimal startup time if you have previously
                       built a server image using the 'build' command.
-v, --verbose        Print out error details when running this command.

```

### CODE REVIEW

**Comment by shawkins** [comment]
@mabartos another option would be to add the escaping in our Picocli class where it calls optBuilder.defaultValue

**Review by vmuzikar — COMMENTED** [review]
@shawkins +1

IMHO escaping is cleaner than ignoring the logs.

This would seem like the right place:
https://github.com/keycloak/keycloak/blob/667ce4be9e233737b2279685eaff6dd3e189bb4f/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java#L641

**Comment by mabartos** [comment]
@shawkins @vmuzikar Yep, the approach with the output decorator should be the way.

**Comment by mabartos** [comment]
@vmuzikar @shawkins Are you ok with this small change?

**Review by vmuzikar — APPROVED** [review]
@mabartos LGTM, thanks!

**Review by shawkins — APPROVED** [review]
LGTM

**Pull request merged**
