### PR TITLE
org.keycloak.admin.client.Keycloak implements javax.ws.rs.client.Client

### PR DESCRIPTION
**Pull request by lippling**
This is very handy. Is there any reason why it shouldn't be done?

### CODE REVIEW

**Comment by stianst** [comment]
Can you explain why you are adding this?

**Comment by lippling** [comment]
We have several projects where Keycloak will be added. The existing code uses injected `Client` instances and I thought it would make sense to see `Keycloak` as a `Client` with added token handling.

**Comment by stianst** [comment]
I can see the need to have that, but this is not the right thing to use. I'd rather see the "token" part extracted into a separate util that you can leverage than to extend the KC admin client.

**Comment by stianst** [comment]
I'm going to reject this as the admin client is not a general purpose "rest client"

**Pull request closed without merging**
