### PR TITLE
Allow Quarkus configuration to mix different storage providers

### LINKED ISSUE #13312: Allow Quarkus Map storage to configure stores for different areas
### Description

Enable the configuration of Quarkus to configure different stores for each area; for example mix CHM and JPA. 

> bin/kc.sh start-dev --storage=jpa --db-password=pass --db-username=keycloak --db-url=jdbc:postgresql://localhost:5432/keycloak --spi-realm-map-storage-provider=chm

### Discussion

_No response_

### Motivation

This should show how different storages can be mixed

### Details

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #13312

### CODE REVIEW

**Comment by ahus1** [comment]
@DGuhr - this is a first attempt for a PR. The good news: it works as expected with the CLI provided in the ticket. 

Let's have a look at this together tomorrow.

@hmlnarik - this enables all providers by default. A more minimal future solution would review all stores for all areas, and then build a minimal version of Quarkus. Please let me know what you think.

**Comment by ahus1** [comment]
BTW: my changes around the public key storage are probably wrong, I need to first understand how to test this, first.

**Comment by ahus1** [comment]
I managed to resolve the problems around the public key storage; this will always use the `concurrenthashmap` implementation. At the moment no other store implements those. With this change the broker tests succeed. 

@DGuhr - this is now ready for a (final) review. Thanks!

**Review by DGuhr — APPROVED** [review]
Given the tests get green, LGTM :)

**Comment by ahus1** [comment]
The failures in the model tests are unrelated as only Quarkus releated classes have been changed.

**Review by hmlnarik — APPROVED** [review]
Approving based on @DGuhr 's approval
Thanks @ahus1 and @DGuhr !

**Pull request merged**
