### PR TITLE
[KEYCLOAK-8835] Add constraint to remember-me columns to avoid migrat…

### PR DESCRIPTION
**Pull request by sguilhen**
…ion issues on mssql

### CODE REVIEW

**Comment by mposolda** [comment]
@sguilhen The Keycloak 4.7.0 release was already available to community (can't be seen on keycloak download page, but it is in maven repo and Stian confirmed that we need to assume that release was available).

In other words, it means that some people may already migrated to 4.7.0.Final, which makes things slightly complicated as the existing changelog file can't be changed. So it seems that new changelog file needs to be created and constraints added to it. Hopefully it's doable with "addNotNullConstraint" (was used in the jpa-changelog-4.7.0 for some other stuff related to offline sessions, but you can take a look for the inspiration).

**Comment by sguilhen** [comment]
@mposolda Done, added a jpa-changelog-4.8.0 and updated the changelog-master. I've tried the MigrationTest using mssql and with these changes the test passes just fine locally.

**Comment by hmlnarik** [comment]
Lgtm, thanks! Before approving I'd like @vramik to verify JPA and migration jobs

**Review by mposolda — APPROVED** [review]
@sguilhen Approving as well. Still need to wait for the @vramik's approve.

**Review by vramik — APPROVED** [review]
@sguilhen thank you, both DB matrix and migration matrix passed.

**Pull request merged**
