### PR TITLE
Upgrade old Keycloak version for DB migration tests

### LINKED ISSUE #29883: Upgrade old Keycloak version for DB migration tests
### Description

During the work on the https://github.com/keycloak/keycloak/issues/28517, it is required to test the old Keycloak version with the OpenJDK 21 support, which is provided in the underlying Quarkus version >=3.5.0. However, the first Keycloak version with the required Quarkus version is Keycloak 24.0.0, so for the test stability and ability to have DB migration tests running with JDK 21, I'd suggest changing the version of the old tested Keycloak version. 

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
Closes #29883

### CODE REVIEW

**Comment by mabartos** [comment]
@miquelsi @lhanusov Migration tests passed. For more info, see the issue description.

**Review by miquelsi — APPROVED** [review]
Thanks for this, @mabartos!

**Review by lhanusov — APPROVED** [review]
LGTM

**Review by vmuzikar — APPROVED** [review]
LGTM based on the reviews from @lhanusov and @miquelsi.

**Pull request merged**
