### PR TITLE
Add tests for lb-check endpoint

### LINKED ISSUE #25113: Add a test for the LoadBalancerCheck
### Description

This is a follow-up on #25077 for adding a test case for the new load balancer check suggested in: https://github.com/keycloak/keycloak/pull/25056#pullrequestreview-1754904120

### PR DESCRIPTION
**Pull request by mhajas**
Closes #25113

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Review by ahus1 — APPROVED** [review]
I have reviewed the code changes and also found that the GitHub actions execute the new test. 

I added one small in-line comment to explain the "why" of the following lines. I also found a snippet of outdated docs. I pushed one more commit. 

@mhajas - if you agree with those changes, please show your approval by squashing and merging this PR. Thanks!

**Comment by mhajas** [comment]
@ahus1 I agree with your changes but I would like to wait for a review from the @keycloak/cloud-native team as this is doing changes to the Quarkus testsuite.

**Comment by ahus1** [comment]
Merging this as we need this in time for the next patch release.

**Review by mabartos — COMMENTED** [review]
@mhajas Additional approval from me to have it confirmed by @keycloak/cloud-native :) Thanks @mhajas, nice work!

**Pull request merged**
