### PR TITLE
Filter first, then sort, and avoid atomics

### LINKED ISSUE #20394: Optimize use of sorted protocol mappers
### Description

For the KC22 performance review, optimize the retrieval and use of sorted property mappers. 

For example, avoid `Atomic*` classes which are supposed to be used with synchronization across threads, and do filtering before sorting.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #20394

### CODE REVIEW

**Comment by ahus1** [comment]
@mhajas - this is a small performance optimization I found when reviewing KC22. Instead of first sorting then filtering, it reverses the steps. As a result, fewer items need to be sorted. It also avoid Java's Atomic* classes wich are intended for synchronizing threads.

I'd be happy if you could review it. Thanks!

**Review by mhajas — APPROVED** [review]
Thank you @ahus1, this looks good to me. I really like the solution with `TokenCollector`

As this is mostly touching on code in the core part of Keycloak I would like to have also an opinion on that from the @keycloak/core team

**Comment by ahus1** [comment]
@mposolda - could one in your team please have a look? Thanks!

**Comment by ahus1** [comment]
@pedroigor - I'm still waiting for a @keycloak/core-maintainers review here. Could you please have a look at this PR? Thanks!

**Review by mposolda — APPROVED** [review]
@ahus1 LGTM, Thanks!

**Pull request merged**
