### PR TITLE
KEYCLOAK-11772 Fix temporary credential property to work correctly

### PR DESCRIPTION
**Pull request by k-tamura**
Please refer to : https://issues.jboss.org/browse/KEYCLOAK-11772

### CODE REVIEW

**Comment by stianst** [comment]
This is not strictly a bug as we have never supported setting the user credentials in the create user endpoint. The issue should probably be changed to a feature request to support that, rather than as a bug as it is now.

I don't see any issue with adding this, and it's probably something we should have supported all along, but could you please drop a mail around this on the dev ml to check if anyone has any concerns? I'm not 100% sure if there was a specific reason why we don't support this, or if it just simply wasn't added by mistake.

**Comment by k-tamura** [comment]
@stianst 

> This is not strictly a bug as we have never supported setting the user credentials in the create user endpoint. The issue should probably be changed to a feature request to support that, rather than as a bug as it is now.

I have changed "type" to "Feature Request".

> I don't see any issue with adding this, and it's probably something we should have supported all along, but could you please drop a mail around this on the dev ml to check if anyone has any concerns? I'm not 100% sure if there was a specific reason why we don't support this, or if it just simply wasn't added by mistake.

I sent a mail to Keycloak ML now.

Best regards,

**Comment by stianst** [comment]
Not sure, but there could be conflicts with https://github.com/keycloak/keycloak/pull/6459. So would like to wait until that one is merged, which should be fairly soon.

**Comment by k-tamura** [comment]
Okay. No problem.

**Review by stianst — APPROVED** [review]

**Pull request merged**
