### PR TITLE
KEYCLOAK-16913 Fix FuseAdapterTest

### PR DESCRIPTION
**Pull request by mabartos**
JIRA: 
[KEYCLOAK-16913 - Failed FuseAdapterTest - NoSuchFieldError: lock](https://issues.redhat.com/browse/KEYCLOAK-16913)
[KEYCLOAK-14777 - FuseAdapterTest failing with fuse63](https://issues.redhat.com/browse/KEYCLOAK-14777)

Squashed cherry-picked commits which were provided by @pdrozd and @drichtarik.

For more details, see the JIRA tickets.

### CODE REVIEW

**Comment by vramik** [comment]
@mabartos thank you for the PR, do we have links to pipeline runs?

**Comment by mabartos** [comment]
> @mabartos thank you for the PR, do we have links to pipeline runs?

@vramik Unfortunately not right now. I'm not able to execute it due to the Jenkins maintenance.

**Comment by vramik** [comment]
> @vramik Unfortunately not right now. I'm not able to execute it due to the Jenkins maintenance.

Please paste the links here once the maintenance is done. Thank you.

**Comment by mabartos** [comment]
@vramik Adapter tests for Fuse 6.3 and Fuse 7.x in pipeline. https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/143/

**Review by vramik — APPROVED** [review]
@mabartos thank you, LGTM.

**Review by hmlnarik — APPROVED** [review]
Approving based on @vramik's approval

**Pull request merged**
