### PR TITLE
KEYCLOAK-14218 Fixes some missing localizations in admin console.

### PR DESCRIPTION
**Pull request by devopsix**
# KEYCLOAK-14218
## Fixes missing localization of date/time values
* Added two new messages `dateFormat` and `timeFormat` for supplying locale specific date and time formats.
* Piping these messages through Angular's `translate` filter and using the result as argument to Angular's `date` filter.
* Added messages for “en” locale which render date and time exactly as before.
* Added messages for “de” locale which render date and time as a German speaking user would expect.

## Fixes missing localization of user and group dialogs/notifications
* Substituted `$translate.instant(string)` for all message found in `groups.js`, `users.js` and the `Dialog` and `Notifications` services in `services.js` and extracted all message to `admin-messages_en.properties`.
* Messages rendered for “en” locale are exactly the same as before.
* Supplied messages for “de” locale.
* There are still many unlocalized dialogs/notifications left. Yet it seems worth merging these changes because they enable users with the `"realm-management"/["manage-users", "query-groups", "query-users", "view-users"]` roles for a realm to have a fully localized admin console experience.

## Fixes missing localization of groups tree root node name
* Injecting `$translate` into controllers and using translation of existing `groups` message for the groups tree root node name.

## Fixes missing localization of Select2 controls
* Once the user locale has been determined, load the corresponding vendor-supplied Select2 i18n file.
* Check if Select2 actually has a translation for a given locale before attempting to load it in order to avoid 404 errors.
* As an alternative to using the vendor's translation files I considered supplying translation functions in the Select2 options object. These translation functions could then use `$translate` and resolve messages the ususal Keycloak way. But I discarded that idea because that would have been a lot more effort for an unclear benefit.

# KEYCLOAK-10927 Side Fix
## Fixes use of language features not supported in Internet Explorer
* Substituted string concatenation for [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)
* Substituted regular `function` expressions for [arrow function expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)

### CODE REVIEW

**Review by ssilvert — COMMENTED** [review]
This all looks good.  I'll need to run our UI testsuite against it just to make sure nothing is broken.

Then I'll do a little manual testing and we should be good to go.

**Comment by ssilvert** [comment]
https://keycloak-jenkins.com/job/keycloak-admin-console-matrix/161/

**Comment by ssilvert** [comment]
@devopsix 

The UI tests showed regressions on Internet Explorer.
22:15:58 [ERROR] Tests run: 181, Failures: 43, Errors: 27, Skipped: 5

Let me know if you want me to send you the log.

**Comment by devopsix** [comment]
@ssilvert 

Are the failures related to the “Users” section and are due to missing Angular controllers?

I have built from master and tried admin console locally in IE11: IE11 fails to parse [`users.js` at around line 1713](https://github.com/keycloak/keycloak/blob/8d6f8d046535d403746f89d9af0b7461755a616a/themes/src/main/resources/theme/base/admin/resources/js/controllers/users.js#L1713). This code has been inserted in commit 3382682115063220495c1b06f87dd4112e76f01c (pull request #6962) which is related to [KEYCLOAK-10927](https://issues.redhat.com/browse/KEYCLOAK-10927). In this code [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) and [arrow function expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) are being used which IE seems not to support.

Is it possible that the regressions already exist on master and are unrelated to the changes in this pull request?

**Comment by devopsix** [comment]
Resolved merge conflicts by rebasing and force-pushing branch.

**Comment by ssilvert** [comment]
> @ssilvert
> 
> Are the failures related to the “Users” section and are due to missing Angular controllers?
> 
> I have built from master and tried admin console locally in IE11: IE11 fails to parse [`users.js` at around line 1713](https://github.com/keycloak/keycloak/blob/8d6f8d046535d403746f89d9af0b7461755a616a/themes/src/main/resources/theme/base/admin/resources/js/controllers/users.js#L1713). This code has been inserted in commit [3382682](https://github.com/keycloak/keycloak/commit/3382682115063220495c1b06f87dd4112e76f01c) (pull request #6962) which is related to [KEYCLOAK-10927](https://issues.redhat.com/browse/KEYCLOAK-10927). In this code [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) and [arrow function expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) are being used which IE seems not to support.
> 
> Is it possible that the regressions already exist on master and are unrelated to the changes in this pull request?

Yes, I think that's what happened.  That was not supposed to be merged without running the UI tests against it first.  Thanks for looking into it.  I'll have to figure out what we are going to do.

**Comment by ssilvert** [comment]
> > @ssilvert
> > Are the failures related to the “Users” section and are due to missing Angular controllers?
> > I have built from master and tried admin console locally in IE11: IE11 fails to parse [`users.js` at around line 1713](https://github.com/keycloak/keycloak/blob/8d6f8d046535d403746f89d9af0b7461755a616a/themes/src/main/resources/theme/base/admin/resources/js/controllers/users.js#L1713). This code has been inserted in commit [3382682](https://github.com/keycloak/keycloak/commit/3382682115063220495c1b06f87dd4112e76f01c) (pull request #6962) which is related to [KEYCLOAK-10927](https://issues.redhat.com/browse/KEYCLOAK-10927). In this code [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) and [arrow function expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) are being used which IE seems not to support.
> > Is it possible that the regressions already exist on master and are unrelated to the changes in this pull request?
> 
> Yes, I think that's what happened. That was not supposed to be merged without running the UI tests against it first. Thanks for looking into it. I'll have to figure out what we are going to do.

@devopsix Would you be willing to fix the IE11 problem as part of this PR?  I think that's the fastest way to move forward.

**Comment by ssilvert** [comment]
Thanks @devopsix.  I kicked off a new test run.  Fingers crossed.

Assuming this looks good I'll ask you to squash the commits after the tests are done.

**Comment by ssilvert** [comment]
@devopsix  UI tests look good now.  I'm going to manually run your code just poke around a bit.  Can you go ahead and squash the commits?

**Comment by devopsix** [comment]
Commits squashed.

**Review by ssilvert — APPROVED** [review]
Finally done.

Thanks for your hard work and patience on this!

**Pull request merged**
