### PR TITLE
KEYCLOAK-6759 Create the databases for import during perf tests

### PR DESCRIPTION
**Pull request by mstruk**
- Added data configurations and dump files for testing number-of-realms limits
- Improved ability to continue import on top of existing data

### CODE REVIEW

**Comment by mstruk** [comment]
Actually, I think the location of .properties files is no longer correct, and should be tests/parameters/datasets?

Also maybe it's better to drop *27kh suffix from names?

**Comment by mstruk** [comment]
One thing I noticed - if specifying a wrong dataset name, there is no error. The -Pgenerate-data is simply executed with default values. We should exit with error in such a case.

**Comment by mstruk** [comment]
Fixed properties files location and names. I still need to upload the .gz dump files.
It would make sense to add steps to generate all these dump files locally.

**Comment by mstruk** [comment]
I noticed that while we have versioned dump files on the server there is no such thing on the client.
That's a problem because it's possible to request a specific version of the dataset - e.g.:
```
mvn verify -Pimport-dump -Ddataset=20r100u1c -Dserver.version=4.0.0.Beta1
```

Sadly, using this against the server provisioned from 4.0.0.Beta2-SNAPSHOT fails while migrating schema. The following works fine though:
```
mvn verify -Pteardown
mvn clean install -Dserver.version=4.0.0.Beta1
mvn verify -Pprovision
mvn verify -Pimport-dump -Ddataset=20r100u1c -Dserver.version=4.0.0.Beta1
```

**Comment by mstruk** [comment]
I added README.datasets.md which contains instructions for recreating multirealm datasets.

**Comment by hmlnarik** [comment]
Obsoleted by #5219

**Pull request closed without merging**
