### PR TITLE
KEYCLOAK-2056: Removal of file model provider

### PR DESCRIPTION
**Pull request by abstractj**
See: https://issues.jboss.org/browse/KEYCLOAK-2056

All the integration tests are passing for me, but let me know if something goes wrong.

### CODE REVIEW

**Comment by stianst** [comment]
There's some issue running the distribution. Also, did you run the Arquillian tests not just the regular integration tests?

**Comment by stianst** [comment]
To build dist run:
    mvn install -Pdistribution

For Arquillian tests run:
    mvn test -Parquillian-integration-tests

**Comment by abstractj** [comment]
@stianst I'm going to check why travis is unhappy. Meanwhile, I'm going to just close and will reopen after make sure that the distribution is ok.

**Comment by abstractj** [comment]
@stianst heres what I did before submit:

```
mvn clean install
mvn -f testsuite/integration/pom.xml exec:java -Pkeycloak-server
```

So I noticed that Travis was failing and saw the default command at your .travis.yml and did the following steps:

```
rm -rf ~/.m2/repository/org/keycloak/*
mvn install -Pdistribution -DskipTests=true -B -V
```

All tests pass for my surprise, but not with `mvn test -Parquillian-integration-tests`. To make sure that the issue is really on this change, I switched to the latest changes from `master` and ran:

``` 
mvn clean test -Parquillian-integration-tests
```

I got the following error message:

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:09 min
[INFO] Finished at: 2015-11-13T11:00:43-02:00
[INFO] Final Memory: 358M/742M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wildfly.build:wildfly-server-provisioning-maven-plugin:1.0.0.Final:build (server-provisioning) on project keycloak-server-dist: Execution server-provisioning of goal org.wildfly.build:wildfly-server-provisioning-maven-plugin:1.0.0.Final:build failed: java.lang.RuntimeException: java.lang.RuntimeException: Failed to process feature pack /home/abstractj/.m2/repository/org/keycloak/keycloak-server-feature-pack/1.7.0.Final-SNAPSHOT/keycloak-server-feature-pack-1.7.0.Final-SNAPSHOT.zip modules: Could not extract resources from org.keycloak:keycloak-events-mongo: /home/abstractj/opensource/keycloak/keycloak/events/mongo/target/classes (Is a directory) -> [Help 1]
```

Now I'm investigating what's wrong on `master`. But let me know if I missed something.

**Comment by stianst** [comment]
The problem is actually caused by arquillian-integration-tests profile included the distribution module, which it shouldn't. For now you can run the tests with:
mvn -file testsuite/integration-arquillian test -B

**Comment by stianst** [comment]
The below command starts the server on an embedded Undertow container:
mvn -f testsuite/integration/pom.xml exec:java -Pkeycloak-server

What's failing on Travis is building the dist (wildfly + server feature pack) as there's still references to the file provider in some modules. Make sure you can build the dist first:
```
mvn install -Pdistribution
```
This will build everything inside distribution, which is disabled in a default build

You also need to make sure there's no reference to the file provider modules anymore. With a quick grep I found the following places:
```
$ grep -R 'model-file' --include module.xml .
./distribution/server-overlay/eap6/eap6-server-modules/src/main/resources/modules/org/keycloak/keycloak-model-file/main/module.xml:<module xmlns="urn:jboss:module:1.1" name="org.keycloak.keycloak-model-file">
./distribution/server-overlay/eap6/eap6-server-modules/src/main/resources/modules/org/keycloak/keycloak-services/main/module.xml:        <module name="org.keycloak.keycloak-model-file" services="import"/>
./distribution/server-overlay/eap6/eap6-server-modules/target/classes/modules/org/keycloak/keycloak-model-file/main/module.xml:<module xmlns="urn:jboss:module:1.1" name="org.keycloak.keycloak-model-file">
./distribution/server-overlay/eap6/eap6-server-modules/target/classes/modules/org/keycloak/keycloak-services/main/module.xml:        <module name="org.keycloak.keycloak-model-file" services="import"/>
./distribution/feature-packs/server-feature-pack/src/main/resources/modules/system/layers/base/org/keycloak/keycloak-model-file/main/module.xml:<module xmlns="urn:jboss:module:1.3" name="org.keycloak.keycloak-model-file">
./distribution/feature-packs/server-feature-pack/src/main/resources/modules/system/layers/base/org/keycloak/keycloak-model-file/main/module.xml:        <artifact name="${org.keycloak:keycloak-model-file}"/>
./distribution/feature-packs/server-feature-pack/src/main/resources/modules/system/layers/base/org/keycloak/keycloak-services/main/module.xml:        <module name="org.keycloak.keycloak-model-file" services="import"/>
./distribution/feature-packs/server-feature-pack/target/classes/modules/system/layers/base/org/keycloak/keycloak-model-file/main/module.xml:<module xmlns="urn:jboss:module:1.3" name="org.keycloak.keycloak-model-file">
./distribution/feature-packs/server-feature-pack/target/classes/modules/system/layers/base/org/keycloak/keycloak-model-file/main/module.xml:        <artifact name="${org.keycloak:keycloak-model-file}"/>
./distribution/feature-packs/server-feature-pack/target/classes/modules/system/layers/base/org/keycloak/keycloak-services/main/module.xml:        <module name="org.keycloak.keycloak-model-file" services="import"/>
```

**Comment by abstractj** [comment]
@stianst oh shit, I did a `git grep` but not just `grep`. Lessons learned, sorry about that. Will fix and update the PR, after run all the tests.

**Comment by abstractj** [comment]
@stianst it might be a silly question but, are you running grep against KEYCLOAK-2056`?. Here `grep` will return empty against my branch.

**Comment by stianst** [comment]
Nope, I did it on master

**Comment by stianst** [comment]
You should also delete connections/file module. As it was only used by the model/file provider.

**Comment by abstractj** [comment]
Seems like Travis is in a bad mood about this change. Running the same steps against my branch:

```
rm -rf ~/.m2/repository/org/keycloak && rm -rf ~/.m2/repository/org/wildfly && mvn install -Pdistribution -DskipTests=true -B -V && mvn test -B && mvn -file testsuite/integration-arquillian test -B
```

I get a successful build and the following log: https://gist.githubusercontent.com/abstractj/e2215f3ad9f9c0faf43b/raw/b7396bf9712acf2ddde9003c5cf81b6947e40fde/KEYCLOAK-2056.log

**Comment by abstractj** [comment]
@stianst seems like Travis was just being mean! See:

[Imgur](http://i.imgur.com/6gdnoWr.png)

What can I say? It's Friday 13th :fearful:

**Comment by stianst** [comment]
Naughty Travis!

Thanks

**Pull request merged**
