### PR TITLE
KEYCLOAK-12176 WebAuthn: show the attestation statement format in the admin console

### PR DESCRIPTION
**Pull request by tnorimat**
This PR is for https://issues.redhat.com/browse/KEYCLOAK-12176 .

### CODE REVIEW

**Comment by mposolda** [comment]
@tnorimat Thanks for the PR! It will be good to rebase to fix the conflicts.

**Comment by tnorimat** [comment]
I've fixed the conflicts and rebased.

**Review by mposolda — APPROVED** [review]
@tnorimat Thanks!

**Comment by tnorimat** [comment]
Arquillian integration tests can not test this feature. Therefore, I've tested this feature manually. I've tested "none", "tpm", "packed" format.

**Pull request merged**
