### PR TITLE
KEYCLOAK-6849 - LinkedIn social login provider updated to new LinkedIn OAuth2 endpoint

### PR DESCRIPTION
**Pull request by velias**

### CODE REVIEW

**Comment by patriot1burke** [comment]
Did you test with the SocialProviderTest?  This testsuite is not run with the build.

**Review by mposolda — DISMISSED** [review]

**Comment by mposolda** [comment]
Sorry, missed the comment by Bill before I approve. 
@velias If you need, here are the steps how to run it https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md .

**Comment by velias** [comment]
@mposolda thanks, going to run it

**Comment by stianst** [comment]
Maybe @vmuzikar can run it for you on our CI. @vmuzikar?

**Comment by velias** [comment]
@mposolda @patriot1burke hmm, looks like running the `SocialProviderTest` is not so easy, it needs configuration for all distinct social login providers, which may be really time consuming for me to setup (and even example of setup file is not complete which makes things even more complicated for me). Do you know anybody who has this setup already prepared and who can run (and probably patch) the test? Maybe @vmuzikar who created the `LinkedInLoginPage.java`?

**Comment by stianst** [comment]
@velias Can you not run a single one from ide or with -Dtest=SocialLoginTest#linkedinLogin ?

**Comment by velias** [comment]
@stianst thanks, you are right. But still I miss some important info, for example what to set as an "Authorized Redirect URLs" on LinkedIn app side. I have no idea under which port, realm etc are the tests running. The documentation for Social tests should be improved in this, I'll try to find this info and even extend the documentation

**Comment by velias** [comment]
Test has been updated. I also improved test doc a bit to provide better info how to run SocialLogin tests.

**Comment by vmuzikar** [comment]
@velias Thank you for you contribution!
I'm afraid the Consent Page you've added with your last commit seem to broke the test.
The user consent is required by LinkedIn only when logging in for the first time. This is same for most of the other social providers as well. Since the tests then basically never run into the IdP's consent page we don't handle the consents within the test to keep it simple.

Could you please remove the consent page?
Other than that looks good to me.

**Comment by velias** [comment]
@vmuzikar I updated test to handle consent page conditionally. Unfortunately I'm not able to test case without consent as my linkedin shows it always.
I implemented consent page support bit more generally, so it can be used for other provider tests also if necessary.

**Comment by vmuzikar** [comment]
@velias That's really weird. LinkedIn never asks me for the consent unless I remove the "Permitted Service" in the LinkedIn profile settings.

So, let's do it conditionally. However, I'm not sure if we should make such extensive changes to the test just for one consent button. This test is particularly delicate, so the less changes we made, the better for its stability. :) Also, we already have consents handled within some login pages - see e.g. [GitLabLoginPage](https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/social/GitLabLoginPage.java) and [TwitterLoginPage](https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/social/TwitterLoginPage.java).

I've significantly simplified the LinkedIn authorization. You can pull my changes if you want: https://github.com/velias/keycloak/pull/1.

**Comment by vmuzikar** [comment]
Also, I've run the test several times (with my changes from https://github.com/velias/keycloak/pull/1), and looks good to me, the new API's working fine.

**Comment by velias** [comment]
@vmuzikar thanks, the simplified test looks good to me. I rebased the change to resolve conflicts with master. I believe it can be merged into master now.

**Comment by vmuzikar** [comment]
@velias Thank you
@stianst I think we're good to go. Will you squash the commits while merging, or do we need @velias to do it beforehand?

**Review by patriot1burke — APPROVED** [review]

**Comment by stianst** [comment]
Thanks @velias

**Pull request merged**
