### PR TITLE
Align code with H6 DefaultAutoFlushEventListener

### LINKED ISSUE #16334: Hibernate 6 upgrade: API changes in JpaAutoFlushListener
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

After upgrading to Hibernate 6, JpaAutoFlushListener fails to compile because `EventSource.getDontFlushFromFind()` doesn't exist anymore. Code in quarkus3 branch has commented out the line that uses this method, but we need to figure out how to properly migrate this API change.

### Version

quarkus3 branch

### Expected behavior

JpaAutoFlushListener should use updated APIs.

### Actual behavior

Current code in quarkus3 branch commented out a line that calls a method that no longer exists.

### How to Reproduce?

Use quarkus3 branch

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
This is taken from Version 6.1.6

Closes #16334

### CODE REVIEW

**Comment by ahus1** [comment]
@hmlnarik  - this is cleaning up this issue by copying over the latest code from H6 DefaultAutoFlushEventListener while keeping our changes. 
The build completed, everything else is expected to fail. Ready for review. Thanks!

**Review by vramik — APPROVED** [review]
lgtm, thanks @ahus1

**Review by hmlnarik — CHANGES_REQUESTED** [review]
LGTM, but re code style please remove the spaces in parentheses.

**Review by hmlnarik — APPROVED** [review]
Thank you!

**Pull request merged**
