### PR TITLE
Add property replacement into realm import process

### PR DESCRIPTION
**Pull request by fabianschlier**
I'm using export and import feature to transfer configuration between the different stages. But the configuration contains stage dependent values, like LDAP URIs. I changed the import mechanism to activate sysprops replacing within realm config by switching to another signature of the JsonSerialization.readValue(..) and this works fine. Would be nice to have this feature upstream.

Fabian

### CODE REVIEW

**Comment by fabianschlier** [comment]
JIRA entry https://issues.jboss.org/browse/KEYCLOAK-5801

**Comment by stianst** [comment]
Thanks for your PR. We are currently in feature freeze for Keycloak 3.x and will not be able to review/merge this work until we open the doors for Keycloak 4.x development.

**Comment by fabianschlier** [comment]
Good to know, thanks for your reply. If seen that there is not yet a date proposed for Keycloak 4.x in JIRA release tab. Is there a rough schedule for the first 4.x release? If I'm looking at the historic release velocity, probably somewhere in Jan 2018?

**Comment by stianst** [comment]
Yes, it'll be Jan/Feb 2018.

**Comment by stianst** [comment]
You'll need to add tests for this to be merged though

**Pull request closed without merging**
