### PR TITLE
[fixes #9920] Fixes collection comparison ignoring order

### LINKED ISSUE #9920: Bug when updating user attributes with duplicated values
### Describe the bug

Hi,

We are trying to update an user attribute :
* my-attribute = [ “A”, “B” ]
with the new value :
* my-attribute = [ “B”, “B” ]

In DefaultUserProfile.java#L116, Keycloak is checking if values are updated like this :
```
    if (currentValue.size() != updatedValue.size() || !currentValue.containsAll(updatedValue)) {
        …
    }
```
As size are the same, it checks if currentValue contains all values from updatedValue… As updatedValue contains twice the same value which is also contained once in currentValue, Keycloak considers that my-attribute value has not been updated.

currentValue and updatedValue are lists created just before the if statement using streams… if those streams are sorted and containsAll replaced by equals, it should fix the issue. (a little bit less performant but I suppose we would not be sorting thousands of values)

### Version

14.0 to 16.1.1

### Expected behavior

When updating a user with an attribute with values [ A, B ] becoming [ B, B ], the user should be updated in Keycloak

### Actual behavior

When updating a user with an attribute with values [ A, B ] becoming [ B, B ], the update is not effective and values remain [ A, B ]

### How to Reproduce?

Go to admin console, choose a user, select "Attributes" tab and add this attribute : `myAttribute = A##B`, then save
Choose another tab then come back to "Attributes" tab. Value is still A##B or B##A.
Edit attribute and change value to B##B, then save. You get a confirm message and new value B##B is displayed.
If you choose another tab then come back, you can notice that the value has not been updated and remains A##B

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by fperot74**
I reused CollectionUtil.collectionEquals(...) for both MultivalueHashMap and DefaultUserProfile
Previous implementation of CollectionUtil.collectionEquals(...) was not taking care of specific cases where you can have [ A, A, B ] and [ A, B, B ] and complexity was O(n²)
Using Map, complexity is now O(n)

Closes #9920

### CODE REVIEW

**Comment by fperot74** [comment]
@ahus1 , PR is submitted

**Comment by ahus1** [comment]
Thanks @fperot74, I reviewed the code and it looks good. I see that the tests you added have 100% line coverage of the method you've been changing. 

Thank you for your thorough search to find more instances to make this code base more consistent.

I had a look for more containsAll() instances that could have the same issue, and found just one more instance in ImmutableAtttributeValidator that looks similar. I suppose this snippet should call the collectionEquals() method as well, please double-check: 

```
        if (!(currentValue.containsAll(values) && currentValue.size() == values.size())) {
            if (currentValue.isEmpty() && !notBlankValidator().validate(values).isValid()) {
                return context;
            }
            context.addError(new ValidationError(ID, inputHint, DEFAULT_ERROR_MESSAGE));
        }
```

Reviewing the code I see that the imports were re-ordered in DefaultUserProfile. While this project doesn't have formatting guidelines as of now, I ask you not to re-order imports.

This repository changes its [contribution guidelines](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md#commit-messages-and-issue-linking) recently about the commit message, and for all new PRs I ask the commit comment to be as follows: 

```
A brief descriptive summary

Optionally, more details around how it was implemented

Closes #1234
``` 

With this commit comment, GitHub will automatically link the pull request to the issue, and close the issue once the PR is merged. 

In total, I ask for (1) reviewing and possibly changing another occurrence of the same pattern, (2) restoring the order of imports in one file, and an updated commit message. 

As usual with this repository, please squash your changes to a single commit in each pull request.

**Comment by fperot74** [comment]
Yes @ahus1, it was the same issue for ImmutableAtttributeValidator.
I fixed it. Other uses of containsAll() seem valid.
Sorry for the imports... I didn't pay attention to this. It is restored.
Commit message has been updated

**Review by ahus1 — DISMISSED** [review]
Reviewed changes, look good to me. GitHub actions are all green.

**Comment by ahus1** [comment]
@mposolda - I reviewed this PR and approve it. As you were one of the people involved in the code here, I wonder if you want to have another look, and then finally approve and merge it. Thanks!

cc: @hmlnarik

**Comment by fperot74** [comment]
Just rebased PR

**Review by hmlnarik — DISMISSED** [review]
Given `CollectionUtil.collectionEquals` is not used from many places that would hurt the performance even with the changes from this PR incorporated, I am approving this PR.
Before merging I would like to have this PR approved by someone familiar with user profile area though.

**Comment by mposolda** [comment]
@hmlnarik @ahus1 I am adding @pedroigor for review as he is most familiar with user profile

**Review by pedroigor — DISMISSED** [review]

**Comment by ahus1** [comment]
@pedroigor - can you please leave a note here about the performance issues you found? If we know more details, we can look for a remedy. For example: if the comparison is usually for one element only, I could see a faster branch for one element collections. Thanks!

**Comment by pedroigor** [comment]
IMO we should have this one after 17. @hmlnarik wdyt?

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@fperot74 Thanks. Looks like @stianst already started the release. That is the only blocker to merge it right now.

**Pull request merged**
