### PR TITLE
URI based configuration of MongoDB to support Replica Sets

### PR DESCRIPTION
**Pull request by kodemaniak**
A mongodb connection can now be configured via a [mongodb:// URI](http://docs.mongodb.org/manual/reference/connection-string/). This also enables one to configure a mongo replica set.

The database that keycloak uses to store information is still defined by the `db` configuration property. The database name within the mongodb URI is only used for authentication.

### CODE REVIEW

**Comment by stianst** [comment]
Did you create a JIRA for this? Also could you update the docs? Documentation for Mongo is in "docbook/auth-server-docs/reference/en/en-US/modules/server-installation.xml"

**Comment by kodemaniak** [comment]
JIRA created: https://issues.jboss.org/projects/KEYCLOAK/issues/KEYCLOAK-1951

I will add docs to the pull request. Is there any documentation how to build the docs?

**Comment by stianst** [comment]
Merged, thanks

**Comment by kodemaniak** [comment]
Great, thanks!

**Pull request merged**
