### PR TITLE
Add X509 thumbprint to JWT when using private_key_jwt

### LINKED ISSUE #12946: Add X509 thumbprint to JWT when using private_key_jwt
### Description

Some identity providers, notably Azure AD, will not use JWKS to obtain the public key used for JWT signing and expect the thumbprint of the signing certificate to be included in the JWT header. Since Keycloak only includes `kid` in the JWT header, this means that such providers will fail to map the signing certificate to one that has been provided to the provider out of band (i.e. through the Azure console). 

It would be nice to have the option of including the `x5t` parameter in the JWT header when using JWT signed with a private key in order to use Azure and similar providers as an IdP for authenticating with Keycloak. 

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-17609

### Motivation

At least one popular enterprise IdP requires the x5t parameter to be present and many enterprises are switching to the private_key_jwt method as a requirement for authenticating with those IdPs to avoid security concerns with client secret management.

### Details

An inactive PR has been open since March 2021: https://github.com/keycloak/keycloak/pull/7890

### PR DESCRIPTION
**Pull request by MikeTangoEcho**
Update `OIDCIdentityProvider` to retrieve the x509 Certificate SHA-1 Thumbprint from the RSA key, and inject into the JWS Header on `authenticateTokenRequest`.

Closes #12946

Another implementation https://github.com/Product-Live/keycloak/commit/5d87b9fa1b0441563dd366c5f8f39114f6f2e9ac

### CODE REVIEW

**Comment by MikeTangoEcho** [comment]
@mposolda hi, you labeled the issue https://github.com/keycloak/keycloak/issues/12946 with `help/wanted`. This PR add the X509 thumbprint when using private key. Can you take a look and give me a feedback ?

**Review by pedroigor — COMMENTED** [review]
@MikeTangoEcho Any reason to not update `AbstractOAuth2IdentityProvider.authenticateTokenRequest` instead?

**Comment by MikeTangoEcho** [comment]
> @MikeTangoEcho Any reason to not update `AbstractOAuth2IdentityProvider.authenticateTokenRequest` instead?

`AbstractOAuth2IdentityProvider` is used in other Identity Providers, i didn't read most of the code base around identity providers to identify potential collateral damage, so i chose to update `OIDCIdentityProvider`.

I made another implementation https://github.com/Product-Live/keycloak/commit/5d87b9fa1b0441563dd366c5f8f39114f6f2e9ac that only modifies JOSE libs, but impacts all JWS.

@pedroigor  Can you tell me where is the most suited place for this feature, OIDCIdentityProvider, AbstractOAuth2IdentityProvider, or Keycloak Crypto Libs ? By the way RFC mentions other x5~ headers, do you want them included in this PR ? I only added x5t because that the only header required by Azure, and the only mentioned  in the issue.

**Comment by pedroigor** [comment]
@MikeTangoEcho Sorry for not being more clear:

* It makes more sense to change `AbstractOAuth2IdentityProvider` because it is not strictly related to OpenID Connect.
* We should have a new configuration property for OAuth2-based brokers to choose between using the `kid` or the `ktc` to reference the certificate.
* I don't think we should introduce other headers now (I see the `x5c` being a good candidate but not for now).

The new configuration property can be added that will show up when `JWT Signed with private key` so that you can choose if the certificate thumbprint should be added to the JWS header. By default, we keep usng the `kid` header.

By making changes in `AbstractOAuth2IdentityProvider` you are going to avoid duplicating code too.

**Comment by MikeTangoEcho** [comment]
@pedroigor Alright thanks, i will make the changes.

> The new configuration property would show up when `JWT Signed with private key` is selected so that you can choose if the certificate thumbprint should be added to the JWS header. By default, we keep using the `kid` header.

The option name: `addX509HeaderParameters` as boolean.
The description: `Add x5t (X.509 Certificate SHA-1 Thumbprint) Header parameter to JWT when using 'private_key_jwt' authentication method. `
I will make the modification on `OAuth2IdentityProviderConfig`.
Can you give me a lead, example of implementation for the frontend modification for the admin ui ? I am not familiar with it.

**Comment by pedroigor** [comment]
Naming is always hard :) I think the name could be `useKeyId` (or something), enabled by default. If disabled, it will use the certificate thumbprint. We can discuss the name at the end if you prefer. The description would be: `If enabled, the certificate used to sign the JWT is referenced by the kid JOSE header. Otherwise, the x5t (X.509 Certificate SHA-1 Thumbprint) header will be used instead.`

W.r.t. to UI, you can look at https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/README.md. The file should be https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx. @jonkoops Am I right?

**Comment by pedroigor** [comment]
@MikeTangoEcho another approach would be to leverage the client authentication mechanism field and add:

* `private_key_jwt_kid`
* `private_key_jwt_x5t`

And handle them accordingly on the server side. The good thing about leveraging this field is that it won't add another field and keep things a bit simpler. But I'm not sure if it is the best from a UX perspective.

**Comment by MikeTangoEcho** [comment]
> We should have a new configuration property for OAuth2-based brokers to choose between using the kid or the ktc to reference the certificate.

What is `ktc` ? I don't see it in the JWS header parameters list https://www.rfc-editor.org/rfc/rfc7515#section-4.1.4

`kid` is OPTIONAL, but becomes mandatory when signing the JWT if the server has multiple keys. By default keycloak has two RSA keys, with alg RS256 and RSA-OAEP documented on `[realm]/protocol/openid-connect/certs`
>  If there are multiple keys in the referenced JWK Set document, a kid value MUST be provided in the JWS header.
https://openid.net/specs/openid-connect-core-1_0-15.html#Signing

On JWS Builder, there are no check of keys, `kid` header is always added when signing. https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/jose/jws/JWSBuilder.java#L107

@pedroigor I don't think kid and x5t headers are mutually exclusive from what i read from the RFC up to now, and with my test with AzureAD. `kid` presence is conditional, but x5~ headers are purely optional since the jwks_uri can help find the certificate from a kid.

I think i will stay in the issue's scope and only add the explicit option `addX509CertificateThumbprint` and not allow the removal of the `kid`. If the need arise to add another headers then it will be another option.

**Comment by MikeTangoEcho** [comment]
> It might end up making hard to extend it in the future.

This may be a source of confusion too, since `private_key_jwt_kid` and `private_key_jwt_x5t` don't exist in the RFC as explicit authentication method. https://openid.net/specs/openid-connect-core-1_0-15.html#ClientAuthentication

**Comment by pedroigor** [comment]
> > We should have a new configuration property for OAuth2-based brokers to choose between using the kid or the ktc to reference the certificate.

Sorry ... Typo. It was supposed to be `x5c`.

> 
> What is `ktc` ? I don't see it in the JWS header parameters list https://www.rfc-editor.org/rfc/rfc7515#section-4.1.4
> 
> `kid` is OPTIONAL, but becomes mandatory when signing the JWT if the server has multiple keys. By default keycloak has two RSA keys, with alg RS256 and RSA-OAEP documented on `[realm]/protocol/openid-connect/certs`
> 
> > If there are multiple keys in the referenced JWK Set document, a kid value MUST be provided in the JWS header.
> > https://openid.net/specs/openid-connect-core-1_0-15.html#Signing
> 
> On JWS Builder, there are no check of keys, `kid` header is always added when signing. https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/jose/jws/JWSBuilder.java#L107
> 
> @pedroigor I don't think kid and x5t headers are mutually exclusive from what i read from the RFC up to now, and with my test with AzureAD. `kid` presence is conditional, but x5~ headers are purely optional since the jwks_uri can help find the certificate from a kid.

I thought they are, or least not clear enough about how they should work together (mainly `kid` and others`). What happens then when you send both `kid` and `x5c` to Azure? Which one will be used to resolve the certificate?

> 
> I think i will stay in the issue's scope and only add the explicit option `addX509CertificateThumbprint` and not allow the removal of the `kid`. If the need arise to add another headers then it will be another option.

I'm afraid of how other OPs can react to having both headers within the same JOSE header. That is why I'm more in favor of isolating them.

**Comment by pedroigor** [comment]
@MikeTangoEcho Or we can introduce this change only to Microsoft Broker?

**Comment by MikeTangoEcho** [comment]
> I thought they are, or least not clear enough about how they should work together (mainly `kid` and others). What happens then when you send both `kid` and `x5c` to Azure? Which one will be used to resolve the certificate?

Azure ignores the `kid` when you connect with a private_key_jwt https://learn.microsoft.com/en-us/azure/active-directory/develop/certificate-credentials 
With a custom keycloak build, i even added other x5~ headers, and didn't notice any changes from Azure, he resolved the certificate correctly.

From my understanding, `kid` is used to find the entry in the json document hosted at `jwks_uri` that holds all the information that could have been set in x5~ headers, but some OPs, like Azure, chose to not use this path and directly compute the  thumbprint on certificate upload on the client application to match with the x5c headers during JWT assertion.

> @MikeTangoEcho Or we can introduce this change only to Microsoft Broker?

A possibility, but x5~ headers are part of JWS specification, and used by OAuth2, it is not specific to Microsoft, nor AzureAD.
The worst that can happen is that other OPs are not compliant with the RFC.

@pedroigor I will be away, and come back on August. Tell me which way is the most preferable for keycloak code base, and i will make the modification. Until then other devs can cherry pick the code, i used it and tested it on Azure. Thanks!

**Comment by pedroigor** [comment]
Thanks @MikeTangoEcho. I would go making this change specific to azure, for now.

Later on, we can improve better generic support. I'm afraid that we might break other brokers by introducing this change. There are always surprises when how specs are implemented :)

**Comment by MikeTangoEcho** [comment]
> I would go making this change specific to azure, for now.

Hi, i looked up the `Microsoft` Broker, and it uses the `common` endpoint (hard coded), is unique to the keycloak's realm, doesn't allow specific configuration based on tenant, and only supports multi-tenant AD applications.
@pedroigor It is not our usage, i will need to modify the `Microsoft` to allow choosing endpoint, before adding the option to use x5t header. Is that ok ? or should i make the modification in a new Broker ?

---

You can connect to microsoft with either the `tenant`, `common` or `organizations` endpoints.
- https://login.microsoftonline.com/{tenantId} for applications processing accounts in Single tenant. **Our usage with OIDC, for tailored usage**
- https://login.microsoftonline.com/common for applications processing accounts in any organizational directory (any Azure AD directory) and personal Microsoft accounts (e.g. Skype, XBox).
- https://login.microsoftonline.com/organizations for applications processing accounts in any organizational directory (any Azure AD directory)

**Comment by pedroigor** [comment]
Sorry for the delay, resuming tasks.

@MikeTangoEcho Is there a name to group the different endpoints you can use so that we can have a single field where people can type the name of the endpoint? If not set, we keep the current behavior and default to `common`.

If Azure decides to add a new one we don't need to change anything in the future ...

**Comment by MikeTangoEcho** [comment]
@pedroigor Hi, it seems that on the Admin UI components are the same for all social providers, and doesn't allow to customize alias, or display name, or choosing the client authentication method.

For Social:
https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/identity-providers/add/GeneralSettings.tsx#L15-L17
For OIDC:
https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/identity-providers/add/OIDCGeneralSettings.tsx#L24-L54
https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx

I can alter Microsoft Broker to minimize collateral, but cannot avoid adding specific condition in UI for component rendering for all social provider.

**Review by pedroigor — COMMENTED** [review]
@MikeTangoEcho Thanks for the updates.

It looks simpler now from a server perspective and I'm fine about how you did the UI. However, would be nice to hear from @keycloak/ui-maintainers too.

I'm also missing a test to cover sending the new header but I don't know now how we could write it in our test suite. IIRC, we have a similar test requirement for some other capability ...

**Comment by MikeTangoEcho** [comment]
> I'm also missing a test to cover sending the new header but I don't know now how we could write it in our test suite. IIRC, we have a similar test requirement for some other capability ...

If you have a lead on where i can implement it, i will do it. Until then, i will fix the react error.

**Comment by MikeTangoEcho** [comment]
@pedroigor I think i got mislead on variable name. Can i add the correction to the PR ?

```ts
 export enum ClientAuthentication { 
   post = "Client secret sent as post", 
   basicAuth = "Client secret sent as basic auth", 
   jwt = "Client secret as jwt", 
   jwtPrivKey = "JWT signed with private key", 
 } 
```

instead of 

https://github.com/keycloak/keycloak/blob/c491c070605db0edc67d7c3c11500d9e609f6d08/js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts#L31-L36

**Review by jonkoops — DISMISSED** [review]

**Comment by pedroigor** [comment]
@MikeTangoEcho Thanks. Noticed you changed the text for the client auth options. Running tests.

**Comment by jonkoops** [comment]
@MikeTangoEcho could you rebase your work on `main` and fix the merge conflicts? It also seems there are some failures on CI you might want to take a look at.

**Review by pedroigor — COMMENTED** [review]
@MikeTangoEcho The test failures seem related. See https://github.com/keycloak/keycloak/actions/runs/6012581593/job/16481942671?pr=20366.

**Comment by MikeTangoEcho** [comment]
@jonkoops @pedroigor I force-pushed the fixes. But i am still looking in the unit tests for a way to validate the JWK x5t headers, so if you have a lead it would help me.

**Review by pedroigor — DISMISSED** [review]

**Review by jonkoops — DISMISSED** [review]

**Comment by pedroigor** [comment]
@MikeTangoEcho Would you mind rebasing and solving conflicts?

**Review by mposolda — DISMISSED** [review]

**Review by jonkoops — APPROVED** [review]

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
@MikeTangoEcho Sorry to ask again, but is it possible to rebase one more time please? We had some issues with WebAuthn tests due the chrome update at some point and it looks that you rebased exactly at the moment when Keycloak main was broken due to this last month :-/ Hopefully another rebase will do fine and will help with having all the tests green.

**Comment by MikeTangoEcho** [comment]
@mposolda Done

**Comment by mposolda** [comment]
@MikeTangoEcho Huge thanks and sorry for all the delays/issues during your work on this!

**Comment by MikeTangoEcho** [comment]
@mposolda thanks you too

**Pull request merged**
