### PR TITLE
Modify `start` script of `keycloak-server` so it works on Windows

### PR DESCRIPTION
**Pull request by jonkoops**
See https://github.com/keycloak/keycloak/issues/25897#issuecomment-1882448604

### CODE REVIEW

**Comment by jonkoops** [comment]
@dipeshsingh253 does this resolve your issues?

**Comment by dipeshsingh253** [comment]
Hi @jonkoops , now the script is executing but still facing the issue while fetching. 

``script execution on windows``

```bash
PS D:\dipesh-temp\keycloak\keycloak\js\apps\keycloak-server> pnpm run start

> keycloak-server@ start D:\dipesh-temp\keycloak\keycloak\js\apps\keycloak-server
> wireit

Server installation found, skipping download.
Starting server…
Option '--features' expects a single value (feature) Expected values are: account-api[:v1], account2[:v1], account3[:v1], admin-api[:v1], admin-fine-grained-authz[:v1], admin2[:v1], authorization[:v1], ciba[:v1], client-policies[:v1], client-secret-rotation[:v1], declarative-user-profile[:v1], device-flow[:v1], docker[:v1], dpop[:v1], dynamic-scopes[:v1], fips[:v1], impersonation[:v1], js-adapter[:v1], kerberos[:v1], linkedin-oauth[:v1], multi-site[:v1], par[:v1], preview, recovery-codes[:v1], scripts[:v1], step-up-authentication[:v1], token-exchange[:v1], transient-users[:v1], update-email[:v1], web-authn[:v1]
Try 'kc.bat start-dev --help' for more information on the available options.
Authenticating admin client…
Authentication failed, retrying in 10 seconds.
Authenticating admin client…
Authentication failed, retrying in 10 seconds.
Authenticating admin client…
Authentication failed, retrying in 10 seconds.
Authenticating admin client…
node:internal/deps/undici/undici:11576
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchWithError (file:///D:/dipesh-temp/keycloak/keycloak/js/libs/keycloak-admin-client/lib/utils/fetchWithError.js:11:22)
    at async getToken (file:///D:/dipesh-temp/keycloak/keycloak/js/libs/keycloak-admin-client/lib/utils/auth.js:46:22)
    at async KeycloakAdminClient.auth (file:///D:/dipesh-temp/keycloak/keycloak/js/libs/keycloak-admin-client/lib/client.js:67:47)
    at async authenticateAdminClient (file:///D:/dipesh-temp/keycloak/keycloak/js/apps/keycloak-server/scripts/start-server.js:167:5)
    at async authenticateAdminClient (file:///D:/dipesh-temp/keycloak/keycloak/js/apps/keycloak-server/scripts/start-server.js:183:5)
    at async authenticateAdminClient (file:///D:/dipesh-temp/keycloak/keycloak/js/apps/keycloak-server/scripts/start-server.js:183:5)
    at async authenticateAdminClient (file:///D:/dipesh-temp/keycloak/keycloak/js/apps/keycloak-server/scripts/start-server.js:183:5)
    at async importClient (file:///D:/dipesh-temp/keycloak/keycloak/js/apps/keycloak-server/scripts/start-server.js:110:3) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:8180
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 8180
  }
}

Node.js v18.18.1

❌ [start] exited with exit code 1.
❌ 1 script failed.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by jonkoops** [comment]
Looks like that might be a different issue, could you try this with Node.js 20+ instead?

**Comment by dipeshsingh253** [comment]
Still throws the same error : 

```bash

PS D:\dipesh-temp\keycloak\keycloak\js\apps\keycloak-server> node --version
v20.10.0
PS D:\dipesh-temp\keycloak\keycloak\js\apps\keycloak-server> pnpm run start

> keycloak-server@ start D:\dipesh-temp\keycloak\keycloak\js\apps\keycloak-server
> wireit

Server installation found, skipping download.
Starting server…
Option '--features' expects a single value (feature) Expected values are: account-api[:v1], account2[:v1], account3[:v1], admin-api[:v1], admin-fine-grained-authz[:v1], admin2[:v1], authorization[:v1], ciba[:v1], client-policies[:v1], client-secret-rotation[:v1], declarative-user-profile[:v1], device-flow[:v1], docker[:v1], dpop[:v1], dynamic-scopes[:v1], fips[:v1], impersonation[:v1], js-adapter[:v1], kerberos[:v1], linkedin-oauth[:v1], multi-site[:v1], par[:v1], preview, recovery-codes[:v1], scripts[:v1], step-up-authentication[:v1], token-exchange[:v1], transient-users[:v1], update-email[:v1], web-authn[:v1]
Try 'kc.bat start-dev --help' for more information on the available options.
Authenticating admin client…
Authentication failed, retrying in 10 seconds.
Authenticating admin client…
Authentication failed, retrying in 10 seconds.
Authenticating admin client…
Authentication failed, retrying in 10 seconds.
Authenticating admin client…
node:internal/deps/undici/undici:11730
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchWithError (file:///D:/dipesh-temp/keycloak/keycloak/js/libs/keycloak-admin-client/lib/utils/fetchWithError.js:11:22)
    at async getToken (file:///D:/dipesh-temp/keycloak/keycloak/js/libs/keycloak-admin-client/lib/utils/auth.js:46:22)
    at async KeycloakAdminClient.auth (file:///D:/dipesh-temp/keycloak/keycloak/js/libs/keycloak-admin-client/lib/client.js:67:47)
    at async authenticateAdminClient (file:///D:/dipesh-temp/keycloak/keycloak/js/apps/keycloak-server/scripts/start-server.js:167:5)
    at async authenticateAdminClient (file:///D:/dipesh-temp/keycloak/keycloak/js/apps/keycloak-server/scripts/start-server.js:183:5)
    at async authenticateAdminClient (file:///D:/dipesh-temp/keycloak/keycloak/js/apps/keycloak-server/scripts/start-server.js:183:5)
    at async authenticateAdminClient (file:///D:/dipesh-temp/keycloak/keycloak/js/apps/keycloak-server/scripts/start-server.js:183:5)
    at async importClient (file:///D:/dipesh-temp/keycloak/keycloak/js/apps/keycloak-server/scripts/start-server.js:110:3) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:8180
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 8180
  }
}

Node.js v20.10.0

❌ [start] exited with exit code 1.
❌ 1 script failed.
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by charuchauhan** [comment]
@jonkoops @dipeshsingh253 I am getting the same issue, any solution to this?

**Comment by jonkoops** [comment]
This is probably some Windows-specific quirk, most of our devs are on Linux or macOS, so we lack the capacity to test this properly. @ssilvert since you work an  Windows machine, are you able to reproduce this?

**Comment by dipeshsingh253** [comment]
Hi @jonkoops @ssilvert , I was free so I tried to debug the script on my Windows device. 
image

The URL is: `http://127.0.0.1:8180/realms/master/protocol/openid-connect/token` which is not accessible, but when I debugged the script on Linux and tried to access the above URL in the browser when the pointer reaches the method shown in the image. 
this `fetchWithError` is not working on Windows while working on Linux and the reason for that according to me is not availability of the server running on `127.0.0.1:8180` on Windows which starts automatically on Linux. 

Port 8180 on Linux during run : 
image

Port 8180 on Windows during script run
image

**Note:** In the above two images the script just has started executing. for example, take this state on Linux.
image

I hope this will help !!!

**Comment by ssilvert** [comment]
@jonkoops I tried this on my Windows machine and found that the problem is with the `--features` flag.

When I run the server by hand, it looks like this:
`kc start-dev --http-port=8180 --features="preview,account3,dynamic-scopes"`

Note the double quotes around the list of features.  But if I am only turning on one feature, I don't need the double quotes.

So if I change line 43 of `start-server.js` to say:
`"--features=account3"`

Then everything works.  

But I haven't figured out how to get all three features working.  I tried this, but no luck:
`"--features=\"account3,admin-fine-grained-authz,transient-users\""`

**Comment by jonkoops** [comment]
@ssilvert @charuchauhan @dipeshsingh253  pushed some changes that might make this work, could you validate this for me?

**Comment by dipeshsingh253** [comment]
Hi @jonkoops , still facing the same issue. 

```bash
PS D:\dipesh-temp\keycloak\js\apps\keycloak-server> pnpm run start

> keycloak-server@ start D:\dipesh-temp\keycloak\js\apps\keycloak-server
> wireit

Downloading and extracting server…
Starting server…
The syntax of the command is incorrect.
Authenticating admin client…
Authentication failed, retrying in 10 seconds.
Authenticating admin client…
Authentication failed, retrying in 10 seconds.
Authenticating admin client…
Authentication failed, retrying in 10 seconds.
Authenticating admin client…
node:internal/deps/undici/undici:12344
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:12344:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchWithError (file:///D:/dipesh-temp/keycloak/js/libs/keycloak-admin-client/lib/utils/fetchWithError.js:11:22)
    at async getToken (file:///D:/dipesh-temp/keycloak/js/libs/keycloak-admin-client/lib/utils/auth.js:46:22)
    at async KeycloakAdminClient.auth (file:///D:/dipesh-temp/keycloak/js/libs/keycloak-admin-client/lib/client.js:67:47)
    at async authenticateAdminClient (file:///D:/dipesh-temp/keycloak/js/apps/keycloak-server/scripts/start-server.js:174:5)
    at async authenticateAdminClient (file:///D:/dipesh-temp/keycloak/js/apps/keycloak-server/scripts/start-server.js:190:5)
    at async authenticateAdminClient (file:///D:/dipesh-temp/keycloak/js/apps/keycloak-server/scripts/start-server.js:190:5)
    at async authenticateAdminClient (file:///D:/dipesh-temp/keycloak/js/apps/keycloak-server/scripts/start-server.js:190:5)
    at async importClient (file:///D:/dipesh-temp/keycloak/js/apps/keycloak-server/scripts/start-server.js:117:3) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:8180
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 8180
  }
}

Node.js v20.11.0

❌ [start] exited with exit code 1.
❌ 1 script failed.
 ELIFECYCLE  Command failed with exit code 1.
PS D:\dipesh-temp\keycloak\js\apps\keycloak-server>
```

**Comment by jonkoops** [comment]
have other priorities, and no Windows machine, so someone else will have to take it from here. I will close this PR and log an issue for this (see #26832).

**Pull request closed without merging**
