### PR TITLE
KEYCLOAK-2000 WS-Fed support for both protocol and broker.

### PR DESCRIPTION
**Pull request by dbarentine**

### CODE REVIEW

**Comment by pedroigor** [comment]
Hi @dbarentine, can you also provide integration tests based on a running Keycloak instance and covering the most important use cases for both protocol and broker ?

**Comment by pedroigor** [comment]
Does this implementation supports token transformation ? For instance, when you want to exchange a SAML2 Assertion to a OIDC ID Token or even a OAuth2 Access Token ?

**Comment by dbarentine** [comment]
At the moment due to changes going on with my job I'm not going to be able to implement any additional tests sorry. It's pretty well covered via unit tests. I have a coverage report for it but github won't allow me to attach it.

As for as token transformation... On the broker side it only supports a SAML2 assertion. There is some issue in the Picketlink libraries parsing the response when a JWT is passed back. We didn't need that so I never looked at it closely.

On the protocol side it will send either a SAML2 Assertion or an Access Token based on a switch in the client options. It uses a lot of the existing SAML and OIDC code to generate those tokens.

**Comment by pedroigor** [comment]
Thanks @dbarentine. What about using WS-Security token profiles to authenticate and obtain tokens from the STS ? Or your implementation (login protocol) assumes that you were previously authenticated by KC ?

**Comment by pedroigor** [comment]
I think the same idea applies to the broker side. It seems you are performing a POST with some data to the brokered STS. I'm wondering if we should not consider other types of authentication against the brokered STS.

For instance, instead of a POST we could also support a direct/sync invocation to the STS using a ```RequestSecurityToken``` within a SOAP envelope using WS-Security.

**Comment by dbarentine** [comment]
In the case of a login it's using a GET with the query parameter wa=wsignin1.0. So it currently doesn't send any RequestSecurityToken. On the protocol side it works the same with. It's essentially predetermined at set up what token type will be sent.

We looked at the RequestSecurityToken/SOAP stuff but all the relying parties libraries that we were working with didn't use it and instead just sent the query parameters. The IDPs didn't seem to care either so it never got implemented. Although for completeness it probably should be at some point.

**Comment by stianst** [comment]
As it stands we can't accept this PR for a few reasons. Implementation is not complete enough for generic use, there's a lack of tests and finally documentation and examples are missing.

Assuming that you don't have time to provide a complete WS-Fed implementation we could investigate if this could be provided as an external project which would be maintained by you. We could then work together to define what would be required to maintain this as a pluggable extension to Keycloak which could easily be installed by others without requiring forking/modifying any Keycloak code.

**Comment by srehorn** [comment]
Thanks for reviewing the PR and we understand. At the moment, we aren’t able to build out the  implementation further or maintain it actively as an separate, external project. The implementation we did fulfills our immediate needs for our RPs and IdPs, but we have had some org reshuffling on our side and can't immediately commit to achieving full spec-compliance. Let's do discuss the feasibility of making it a straightforward add-on as we've found it quite useful as is and believe we've done the right things to make it pluggable already to Keycloak (i.e., as a peer to the other protocols).  

We are still happy to contribute the code (as is) to Keycloak as a foundation should someone need or want to implement the complete WS-Fed specification. 

Thanks!

\- scott r
(on behalf of our team including Dane and Doug)

**Comment by ruchg1337** [comment]
Hi all,

I am writing this message on behalf of a small team of my company. We are really interested in having WS-Federation in KeyCloak. We might be able to provide resources to implement it. 

Do you think, @dbarentine, @stianst and @srehorn, that you could provide us few information about what you consider as needed to be done in order to provide what is missing to this pull request. I am wondering if we have to restart from scratch due to the fact that the PR was done more than one year ago or if most the work is still up to date and reusable.

@anybody interested in working on this topic, do not hesitate to contact me we can work together.

Thanks!
Greg

**Comment by dbarentine** [comment]
@ruchg1337 We still have the code. I need to do some work to separate it from some other code we have and then I can check it in for you.

The code we currently have was updated to run on 2.5.5.Final. There isn't a ton of active testing going on with it as we had a very narrow use case for supporting it.

@stianst will have to answer the questions about what they want to see. There is some information above on it though.

From our side we only implemented the bare minimum we needed to support a couple of specific IdPs and clients. As such the implementation doesn't handle a large part of the spec currently.

**Comment by dbarentine** [comment]
@ruchg1337 https://github.com/dbarentine/keycloak-wsfed

That code should build with "mvn clean package" and then you should just need to drop the jar into a Keycloak install.

There is an admin theme change. Right now I'm only finding one for the Idp side but I thought there was one needed for the protocol side as well. If I find it I will update the Git repo with it.

**Comment by ruchg1337** [comment]
@dbarentine 
Thank you for your quick answer !

**Comment by stianst** [comment]
@dbarentine please start a thread on keycloak-dev mailing list about this. In general we would most likely be able to accept a contribution around this. However, it would have to be a complete implementation and include good test coverage as well as documentation. We would also have to discuss it further within the team to decide if we can include this or not. Adding support for a new protocol is not something we can do lightly as it can (and will most likely) result in a significant maintenance burden.

**Comment by braoru** [comment]
Hello @dbarentine, as @ruchg1337 said, we are very interested in improving this contribution. We could simply start by improving the module/providers approach until it reach a satisfying level of quality.

What would be the best approach, directly contributing on @dbarentine repository or we make a new one and post something on keycloak-dev ?

**Comment by stianst** [comment]
My above comment was aimed at @ruchg1337, not @dbarentine. Please get in touch with us on the mailing list before spending time on this as I can't promise we will be able to accept the contribution.

**Comment by braoru** [comment]
@dbarentine do you mind if we create a public fork of your code to improve it?

**Comment by dbarentine** [comment]
@braoru That's fine by me. Ultimately your team will need to own it as we won't have the resources to be able to assist in it so forking it is probably the way to go.

**Comment by braoru** [comment]
@dbarentine We putted it under https://github.com/cloudtrust/keycloak-wsfed and added you to an external team so you can add change you where speaking of :-) I send an email to the mailing list today. Thanks again for sharing !

**Comment by braoru** [comment]
@dbarentine Did I need to do something else than just declaring dependencies & register it within the standalone.xml file ? I try to make it run from a few day without success. But I admit, I just created some very small module and never a big one like this one :-)

**Comment by dbarentine** [comment]
@braoru could you enable issues and log one for this in your forked repo? I just want to extract this particular discussion out of this Keycloak PR since it could be noisy.

In that issue put what you are seeing when you try to run it. I may not be able to look at it until tomorrow. But if I know better what you are seeing and the steps you are trying that will make it easier for me to help.

**Comment by braoru** [comment]
done https://github.com/cloudtrust/keycloak-wsfed/issues/1

**Pull request closed without merging**
