### PR TITLE
Removing workaround for H6 as this is now fixed

### LINKED ISSUE #16551: Quarkus 3: RealmModelTest.testRealmLocalizationTexts fails
BLOCKED: see https://github.com/keycloak/keycloak/issues/16551#issuecomment-1400633351

### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

testsuite

### Describe the bug

The `org.keycloak.testsuite.model.RealmModelTest.testRealmLocalizationTexts` test fails in the quarkus3 branch in `legacy-jpa` profile

### Version

quarkus3

### Expected behavior

Test passes

### Actual behavior

Test fails

### How to Reproduce?

Run the test in `legacy-jpa` profile

### Anything else?

https://github.com/keycloak/keycloak/actions/runs/3966487788/jobs/6799050521

### PR DESCRIPTION
**Pull request by ahus1**
This reverts commit c74b832995759d4c9f330a4ba1767d01f9e3c174.

Closes #16551

### CODE REVIEW

**Comment by ahus1** [comment]
@vramik - I'd be happy if you could find the time to review this pull request.

It removes the workaround (it actually reverts the commit). Looking at the executed checks, they are as green as the regular Quarkus 3 branch. Especially the model tests are all-green which this workaround fixed earlier. This proves that this workaround is no longer necessary. 

Thanks!

**Review by vramik — APPROVED** [review]
Thank you @ahus1 for preparing this PR! LGTM.

**Comment by ahus1** [comment]
@vmuzikar / @hmlnarik - this is now ready to be merged. If it can't be merged before the weekly freeze, let me know and I'll rebase it. Thanks!

**Review by vmuzikar — APPROVED** [review]
@ahus1 Thank you!

**Pull request merged**
