### PR TITLE
Breadcrumbs are not correct in the authorization part in the admin console

### LINKED ISSUE #19533: Breadcrumbs are not correct in the authorization part in the admin console
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When I enable "Authorization" for some confidential OIDC client.

Then go to: My client -> Authorization -> Policies -> Default Policy

Now I am editing the existing policy `Default Policy`. However the breadcrumbs (links in the top part of the screen) show:
`Clients` -> `Client Details` -> `Create Policy`. See screenshot (FYI. same screenshot used also for reporting the other related issue #19532 )

Screenshot from 2023-04-04 17-14-33

Here I am not creating new policy, but I am editing existing policy. So strictly said, it should say something like `Policy Details` to be compatible with some other objects in the admin console (EG. users)? The last part should be `Create Policy` just when I am creating new policy.

Same issue exists for other authorization objects (`resources`, `scopes`, `policies`). It seems it is correct only for `permissions`.

### Version

21.0.2

### Expected behavior

When editing existing `policy`, `resource` or `scope`, the last part of the breadcrumb link should be likely something like `Policy Details` instead of `Create Policy`. The `Create Policy` should be just when I am creating new policy (Similar for Resources, Scopes).

### Actual behavior

Breadcrumb is showing `Create Policy` (or `Resource` or `Scope`) even if I am updating existing policy.

### How to Reproduce?

See above

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedro-hos**
closes #19533

### CODE REVIEW

**Comment by pedro-hos** [comment]
Hey @jonkoops can you please review the PR? Thanks =D

**Review by jonkoops — APPROVED** [review]
LGTM

**Comment by jonkoops** [comment]
Thanks for this @pedro-hos!

**Comment by pedro-hos** [comment]
Many thanks @jonkoops \o

**Pull request merged**
