### PR TITLE
Address QE comments on Server Admin Guide

### LINKED ISSUE #34916: Addresse QE comments on Server Administration guide
### Description

Minor changes

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andymunro**
Closes #34916

### CODE REVIEW

**Comment by andymunro** [comment]
Please review so I can backport downstream.

**Comment by andymunro** [comment]
This will still require one change in downstream doc-attributes for the link to the new location of the Securing Apps guides once this is merged and backported.

**Review by mposolda — APPROVED** [review]
Approving. But I suppose @miquelsi should also review since these changes were initiated by QE review?

**Review by ikhomyn — APPROVED** [review]
@andymunro LGTM

**Comment by mposolda** [comment]
@ikhomyn Thanks for the review!

**Pull request merged**
