### PR TITLE
Add again Client fields( Logo URL, Policy URL and Terms of service UR…

### LINKED ISSUE #11825: Client fields( Logo URL, Policy URL and Terms of service URL ) have been removed from ApplicationsPage.tsx in AccountConsole
### Describe the bug

Client fields( Logo URL, Policy URL and Terms of service URL ) have been removed from ApplicationsPage.tsx in AccountConsole!

Although Logo URL, Policy URL and Terms of service URL have been configured  and 'Consent Required' is true, fields  Logo URL, Policy URL and Terms of service URL are not shown in ApplicationsPage.tsx in AccountConsole!

The bug ( removal) have been introduced in [Keycloak account console PatternFly design system alignment PR](https://github.com/keycloak/keycloak/pull/10748).

Policy URL and Terms of service URL (if existed) must be shown as before.  I propose Logo URL (if existed) to be shown in the right part of application.

### Version

18.0.0

### Expected behavior

application_16 1 0

As you can see from attached screenshot until at least Keycloak 16.1.0, client fields( Logo URL, Policy URL and Terms of service URL ) have been shown in ApplicationsPage.tsx in AccountConsole - if they have been set.

### Actual behavior

application_18 0 0

As you can see from attached screenshot until at least Keycloak 16.1.0, client fields( Logo URL, Policy URL and Terms of service URL ) have been removed from ApplicationsPage.tsx in AccountConsole!

client_configuration18 0 0
Logo URL, Policy URL and Terms of service URL have been configured to the client.

### How to Reproduce?

Admin must configure Logo URL, Policy URL and Terms of service URL in the client and make 'Consent Required' true.

After accepting consent for this Client, user goes to AppliactionsPage in AccountConsole and fields  Logo URL, Policy URL and Terms of service URL are not shown!

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cgeorgilakis**
…L ) in  ApplicationsPage.tsx of  AccountConsole

Closes #11825

### CODE REVIEW

**Comment by cgeorgilakis** [comment]
Kind reminder for checking this PR.
I remind you that these fields are showing in account console( Keycloan main branch) and a false PR merge remove them.

**Comment by stianst** [comment]
@ssilvert can someone from UI team review this one?

**Comment by cgeorgilakis** [comment]
Any progress in reviewing it?
This functionality has been removed by false PR merged.

**Review by ssilvert — APPROVED** [review]

**Comment by crowmedia** [comment]
Additional to the entry before: 
image

**Comment by jonkoops** [comment]
@crowmedia I would recommend you start a [discussion](https://github.com/keycloak/keycloak/discussions), we generally do not look at closed issues with discussions on them.

**Comment by crowmedia** [comment]
Okay. sorry I did not recognize that it was closed. Thank you!

**Comment by cgeorgilakis** [comment]
@crowmedia you must configure these attributes in admin console. By default clients does not have these values.
I do not know if any problem exists in new admin console. Our PR was firstly originated in old admin console.

**Comment by crowmedia** [comment]
@cgeorgilakis I did configure it in the admin console already. That's the reason, why I started to search, why it is not available in the account console. If it will be in the response, I can add it to my own theme.

Because of [jonkoops](https://github.com/jonkoops) hint I added it to a open discussion about the account console.

**Comment by crowmedia** [comment]
@cgeorgilakis I think I found out what you mean, but that was not the result I expected.  I wanted to add a client logo to the list of my applications in the account console.

**Pull request merged**
