### PR TITLE
Summary

### LINKED ISSUE #20848: Convert all properties files to UTF-8
### Description

A lot of our property files are not using UTF-8, which makes some of the translations hard to read. Under the issue the following should happen:

1. All `.properties` files should start with `# encoding: utf-8`
2. All encoded texts should be written in their plain UTF-8 representation.

### PR DESCRIPTION
**Pull request by siddharth-sable**
Converting all properties file to utf-8

Closes #20848

### CODE REVIEW

**Review by edewit — COMMENTED** [review]
seems you remove a lot of properties is that intended?

**Comment by siddharth-sable** [comment]
No, it was not intended. My job was just to add `# encoding: utf-8` to all .properties files and convert all unicode escapes to their plain Unicode format.

I am not sure why the properties were removed, I will check and revert asap.

**Comment by siddharth-sable** [comment]
@edewit I have checked the files one by one, now there should be no issues.

**Comment by jonkoops** [comment]
@siddharth-sable a lot of the changed files contain only white-space changes (such as adding an extra line of white-space). Could you remove these from the PR?

**Comment by siddharth-sable** [comment]
Sure, will do

**Comment by siddharth-sable** [comment]
I tried but was little puzzled regarding the white spaces, can you mention some files which have white-space changes?

**Comment by jonkoops** [comment]
For example, `adapters/oidc/wildfly/wildfly-subsystem/src/main/resources/org/keycloak/subsystem/adapter/extension/LocalDescriptions.properties` now has a new line at the end of the file, but none of the contents were touched.

**Comment by siddharth-sable** [comment]
yeah, got your point. Adding this files into the PR makes no sense. So by removing you mean I should delete those files from the PR right? I tried doing two of them. Just to make sure its done correctly.

Please suggest if there's a better way to do this.

**Comment by jonkoops** [comment]
@siddharth-sable can you re-base your PR on `main`? There have been some changes that have landed that are causing conflicts.

**Comment by jonkoops** [comment]
Hi @siddharth-sable, are you still interested in landing this? I think we should probably narrow the scope of this PR to the properties files that contain localized messages, such as those in the themes. That way we can merge this PR faster.

WDYT?

**Comment by siddharth-sable** [comment]
works, we can narrow the scope. Actually as you asked to rebase the PR on main, after doing that I am facing merge conflicts, I am not sure how to resolve those as of now 😕.  Can you share some blog or anything which might help me get along faster?

**Comment by jonkoops** [comment]
> Can you share some blog or anything which might help me get along faster?

I'd recommend you check out the [GitHub documentation](https://docs.github.com/en/get-started/using-git/resolving-merge-conflicts-after-a-git-rebase) on this topic, it's pretty comprehensive.

If you are running into a lot of conflicts you can also reset the branch, and remove the changes that do not touch the localization files.

**Comment by siddharth-sable** [comment]
I tried resolving merge conflicts, I am not sure if its done correctly, if not please provide your feedback.

**Comment by jonkoops** [comment]
Looks like there are now a lot of unrelated changes in the PR. Can you do a rebase from your branch using `git pull --rebase upstream main`?

**Comment by siddharth-sable** [comment]
I did the rebase, it says `Could not apply e6a2075d05... Summary`

I am sorry, if there has been lot of confusion, you can assign this issue to some other contributor

**Comment by jonkoops** [comment]
I think the best course of action is probably to close this PR and create a new one, as it has become to hard to rebase.

**Pull request closed without merging**
