### PR TITLE
set default ldap connection pooling to plain and ssl

### LINKED ISSUE #35758: Set the LDAP connection pooling protocols by default to plain and tls
### Description

Currently, the only LDAP connection protocol which gets pooled is `plain` by default, if not set explicitly by system property `-Dcom.sun.jndi.ldap.connect.pool.protocol=ssl`.
As LDAP connections should only be done via LDAPS protocol, these connections get not pooled if not enabled. But this is most of the times not done and thus this yields into massive new created connections when retrieving user lists from LDAP.

I vote for setting both protocols by default, if none is set explicitly. This way also secure connections are as most as performant as possible.

### Discussion

_No response_

### Motivation

Most (hopefully all) companies who use LDAP user federation, use with LDAPS protocol, which makes sense as sensitive information is being sent. But most companies doesn't care enough about proper connection pooling settings and might forget to set the property for having secured connections pooled, as by default, if nothing is configured explicitly, only plain connections will be pooled.
This new default setting will set the property automatically to pool plain and ssl/tls connections, if nothing is explicitly configured. This will yield in faster connections/communication between the Keycloak server and the LDAP directory.

### Details

I'll provide a PR for having a default config.

### PR DESCRIPTION
**Pull request by dasniko**
closes #35758

### CODE REVIEW

**Comment by dasniko** [comment]
Testing this properly is currently being blocked by #35762

**Review by pedroigor — DISMISSED** [review]

**Comment by pedroigor** [comment]
@dasniko Thanks. I think the other settings are OK to rely on the defaults, right? For instance, timeout and pool (max) size.

**Comment by dasniko** [comment]
@pedroigor Thanks for approval.
Yes, I think for the other properties it's ok to rely on the defaults.

**Comment by pedroigor** [comment]
Thank you. Added a single line to advertise the new default.

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@dasniko Please, see https://github.com/keycloak/keycloak/issues/35762#issuecomment-2531832706. It should not be a blocker.

**Pull request merged**
