### PR TITLE
Make general cache options runtime

### LINKED ISSUE #27549: Make general `cache` options runtime
As we've marked the `cache-config-file` as a build time option, we parse it in a runtime anyway. IMHO, it makes sense to provide the capability to specify the config file for cache in runtime. In addition, AFAIK, it could help many deployments. The `cache` and the `cache-stack` are closely tied to the config file. 

I'm not aware of any use cases where the general `cache` options are required to be handled in build time.

More improvements around the `cache` options management will come with the outcome of the discussion https://github.com/keycloak/keycloak/discussions/24055.

### PR DESCRIPTION
**Pull request by mabartos**
Closes #27549

### CODE REVIEW

**Review by shawkins — APPROVED** [review]
LGTM, great work @mabartos this will help with import / export confusion around caching as well.

**Comment by ahus1** [comment]
@mabartos - LGTM, I trust our tests.

**Comment by mabartos** [comment]
@ahus1 Thanks for the review

**Review by vmuzikar — APPROVED** [review]
@mabartos High level LGTM, approving based on review from @shawkins.

**Pull request merged**
