### PR TITLE
KEYCLOAK-11974: Handle PasswordPolicyNotMetException in UsersResource.createUser()

### PR DESCRIPTION
**Pull request by maksymgendin**
JIRA https://issues.jboss.org/browse/KEYCLOAK-11974

### CODE REVIEW

**Comment by stianst** [comment]
Changes looks good, but we need a test added. You can extend https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java

**Comment by mposolda** [comment]
@maksymgendin @stianst It seems that this may conflict wit this PR https://github.com/keycloak/keycloak/pull/6339/ and addresses the same thing? Just quickly checked that the additional PR already has some tests added.

**Comment by stianst** [comment]
@mposolda yes, with that in mind we should close this PR as #6339 covers this case and others as well.

**Comment by stianst** [comment]
Closing this. @maksymgendin please check out #6339 as it will resolve this issue as well when it is merged.

**Pull request closed without merging**
