### PR TITLE
KEYCLOAK-14961 SAML Identity Provider: Add ability to request specific AuthnContexts to remote IdPs

### PR DESCRIPTION
**Pull request by lscorcia**
Allows Keycloak SAML Identity Broker to request specific AuthnContexts to remote IdP. It requires small plumbing changes in the SAML Identity Provider and three additional fields in the SAML Configuration UI to enter the required parameters:

* Comparison Type: can be one of the fixed values `Exact`, `Minimum`, `Maximum`, `Better`;
* AuthnContext ClassRefs: a list of URIs corresponding to well-known types of authentication (can also have provider-specific URIs);
* AuthnContext DeclRefs: a list of URIs corresponding to a provider-specific authentication context declaration;

immagine

There is no change to `AuthnRequests` if no classes or declarations are set: if both ClassRefs and DeclRefs are empty, the `RequestedAuthnContext` element is not emitted at all, otherwise the element is generated and will also have its `Comparison` attribute set to the Comparison Type.

Points of attention:

* Since the IdP Config does not support multivalued attributes, data is stored as a JSON-serialized array of objects;
* I have added the parameters as a separate, initially-collapsed section - if you prefer they can be merged in the already existing "SAML Config" section;
* I am not a native English speaker so any suggestions to the translation strings are welcome.

This issue replaces PR #7292 which was initially meant to be just the plumbing code, but it wasn't much effort to also add the required UI and complete the feature.

### CODE REVIEW

**Review by pedroigor — COMMENTED** [review]
@hmlnarik Looks like a good addition for me.

**Comment by lscorcia** [comment]
Added documentation changes for the feature.

**Comment by lscorcia** [comment]
@hmlnarik , do you have any feedback about this?

**Review by hmlnarik — CHANGES_REQUESTED** [review]
@lscorcia Thank you, this looks like indeed a nice addition. Before running the UI tests, I'd like to understand whether there is a strict need to introduce the special classes for the `AuthnContextClassRefJsonObject` / `AuthnContextDeclRefJsonObject` or whether this can be achieve with plain `String`s? It seems that using plain `String` array would lead to easier handling in the UI as well as shorter representation in the database.

**Comment by lscorcia** [comment]
Hello @hmlnarik , thank you for your review! I will apply the suggested fixes.

Regarding the use of plain strings instead of classes, my reasoning was that if in the future we needed to change the attribute structure we'd have a hard time migrating any already-existing value. For example, it could be useful to add a priority index - SAML specs say that these should be ordered sets. It is easier to accommodate an extra attribute this way.

If you think this is too far-fetched let me know and I will change the code accordingly.

**Comment by hmlnarik** [comment]
> Hello @hmlnarik , thank you for your review! I will apply the suggested fixes.
> 
> Regarding the use of plain strings instead of classes, my reasoning was that if in the future we needed to change the attribute structure we'd have a hard time migrating any already-existing value. For example, it could be useful to add a priority index - SAML specs say that these should be ordered sets. It is easier to accommodate an extra attribute this way.
> 
> If you think this is too far-fetched let me know and I will change the code accordingly.

This is a fair point, thank you for raising it. Adding few other arguments in this regard:
1. The priority seems a reasonable requirement, yet the list already encodes the priority implicitly via position
2. The new store shall make it possible to easily handle such updates when necessary.
3. Occam's razor / KISS principle

Given these arguments, I incline to the plain string list unless there is any other argument.

**Comment by hmlnarik** [comment]
Thank you @lscorcia!

Running UI tests: https://keycloak-jenkins.com/job/keycloak-admin-console-matrix/200/

**Review by hmlnarik — DISMISSED** [review]

**Comment by hmlnarik** [comment]
UI tests passed. Looks good to merge once the docs are reviewed.
There is a conflict with a recently merged PR. Could you please rebase?

**Comment by lscorcia** [comment]
Rebase done! Thank you for all of your help!

**Review by hmlnarik — APPROVED** [review]
Thank you!

**Comment by lscorcia** [comment]
Hi @hmlnarik , I think that this merge also allows closing the old JIRA issue at https://issues.redhat.com/browse/KEYCLOAK-5224 . While the discussion has somewhat morphed into full AuthnContext support for Keycloak as IdP, the original issue just needed AuthnContext support for Keycloak as SP.
Have a nice day!

**Pull request merged**
