### PR TITLE
Exclude Operator dependencies when building API docs

### LINKED ISSUE #29984: Nightly build for API docs is broken
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

The nightly API docs depend on the Operator, which is not built  https://github.com/keycloak-rel/keycloak-rel/actions/runs/9278480146/job/25529571886#step:4:44135

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

This is broken as the API docs build now depends on the Operator, which is not built and shouldn't need to be built (see https://github.com/keycloak-rel/keycloak-rel/pull/122#issuecomment-2137595779)

This issue supersedes https://github.com/keycloak-rel/keycloak-rel/issues/121

### Actual behavior

The build fails and misses some Operator dependencies

### How to Reproduce?

```
# remove previously locally built artifacts
rm -rf ~/.m2/repository/org/keycloak/
# do a build as in https://github.com/keycloak-rel/keycloak-rel/blob/52687e78792330893533b608b727af1ed8c69836/.github/workflows/x-keycloak.yml#L65
./mvnw -Pjboss-release,distribution-downloads,all clean install -DskipTests -DskipTestsuite
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #29984

This removes parts of the changes from 25548a7ccc65bb7a426f15a95f2472628790147b

### CODE REVIEW

**Review by abstractj — APPROVED** [review]
LGTM

**Comment by abstractj** [comment]
@keycloak/cloud-native would you like to review?

**Comment by ahus1** [comment]
IMHO as it is removing some of the changes from  25548a7ccc65bb7a426f15a95f2472628790147b is should be fine without the CND team reviewing. 

When those dependencies where added, it had some unintended consequences.

**Comment by ASzc** [comment]
The way the api-docs build is set up is really fragile and I wouldn't be surprised if this PR breaks them again for product

**Comment by ahus1** [comment]
@ASzc - Hm, that's unfortunate, and I'm sorry forthat. 

Still we need to take one step back to get upstream working again. 

For the next PR, I now know at least how I need to test the upstream release build separately to avoid it breaking again :-(

cc: @pskopek

**Pull request merged**
