### PR TITLE
Support JavaEE for Admin client

### PR DESCRIPTION
**Pull request by mabartos**
The admin-client should support JavaEE, and admin-client-jakarta should support JakartaEE. We need to revert changes for the admin-client as there were provided changes related to the JakartaEE.

### CODE REVIEW

**Comment by mabartos** [comment]
@vmuzikar GHAs passed; could you please take a look at it? Thank you :))

**Comment by pedroigor** [comment]
I would rather make `keycloak-admin` migrated to Jakarta and (optionally) release a `keycloak-admin-jee` for backward compatibility.

It does not make sense to me to distribute a library with JEE if we are actually migrating to Jakarta (similar to other projects).

**Comment by mposolda** [comment]
> I would rather make `keycloak-admin` migrated to Jakarta and (optionally) release a `keycloak-admin-jee` for backward compatibility.
> 
> It does not make sense to me to distribute a library with JEE if we are actually migrating to Jakarta (similar to other projects).

@pedroigor I see your point, but not 100% sure as it would mean that people currently using JEE client will need to update their `pom.xml` . Also people already using `keycloak-admin-client-jakarta` will need to update their dependencies to be `keycloak-admin-client` instead. So I am slightly more to keep as is (just to avoid people having migration issues).

**Comment by vmuzikar** [comment]
I'm even wondering if we need Java EE version of the admin client at all. :) Keycloak is moving to Jakarta, that's it. I assume we don't want to keep JEE support indefinitely. However, I understand it wouldn't be very wise to remove JEE version without a heads up to users (or would it? they could still use older version of the client, the API doesn't change that often). Hence, +1 for moving the JEE version to `keycloak-admin-jee`.

> Also people already using `keycloak-admin-client-jakarta` will need to update their dependencies to be `keycloak-admin-client` instead. So I am slightly more to keep as is (just to avoid people having migration issues).

I think that's ok. They would need to update the version in any case, so they can update the name as well.

**Comment by mabartos** [comment]
I've been thinking about it a bit, and after considering your comments, I'd prefer to have `keycloak-admin-client` with Jakarta EE and `keycloak-admin-client-jee` with JavaEE support. Yes, users need to change their dependencies in their poms, but I think now is the right time to do it, as we're migrating the whole codebase to the JakartaEE. 

From the long-term point of view, it makes sense to get rid of building artifacts with JakartaEE mentions (the same fits for projects like Hibernate, Infinispan,..). It could cause some confusion and some "messiness" ;) in the future.

We can support `keycloak-admin-client-jee` for some time in order to leave some time for proper projects migrations. 
WDYT?

**Comment by vmuzikar** [comment]
@mabartos +1

If we make the JEE version the one with the suffix (`-jee`), it'll also be easier to deprecate and remove in the future, IMHO.

**Comment by pedroigor** [comment]
@vmuzikar I would also remove it. But I agree with @mabartos that we did not do well making this public and dropping it now is not so nice ...

Change your dependency graph should be better than being forced to migrate to Jakarta and break existing deployments without previous notice.

**Comment by mposolda** [comment]
@mabartos @pedroigor @vmuzikar Good points. I agree with this PR as it is now (keycloak-admin-client -> jakarta, keycloak-admin-client-jee -> jee). I guess we also need migration guide docs, but this can be done as a follow-up?

**Comment by mabartos** [comment]
Thanks, guys, for your feedback!

I've created follow-up tasks for this PR:
#20026
#20027

ATM, the current approach with `admin-client-jee`(JavaEE) and `admin-client`(JakartaEE) stays the same. It means we're keeping the JavaEE version of the client in our codebase. For JakartaEE, we migrate the JavaEE module to the JakartaEE one by using a script provided by Eclipse. 

Once we drop support for the Admin Client JavaEE, we can keep the generated code in our codebase as the main one and remove the `admin-client-jee` module. If there are some changes needed to Admin Client JakartaEE during the continuous support of Admin Client JavaEE, we can only easily add the particular changed file in the module and the Eclipse script will ignore the migration for this file. 

IMHO, it's the best solution we have ATM as keeping code for JakartaEE in our codebase would require quite a lot of effort as we'd need to be able to support backward compatibility for JavaEE. 
If both could be present, any change to these admin clients would have to be duplicated regarding the code.

Is it ok for you?

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks @mabartos!

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
Not sure if we need a migration guide now but a follow-up.

**Review by mposolda — APPROVED** [review]

**Pull request merged**
