### PR TITLE
fix: ensuring quarkus-embedded does does not use system.exit

### LINKED ISSUE #35550: JVM crash when running base testsuite test from command line using auth-server-quarkus-embedded
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

When a test is run from command line with profile `auth-server-quarkus-embedded` there is an JVM crash at the end. The test seems to pass correctly. 

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

no JVM crash :)

### Actual behavior

```log
[INFO] Tests run: 38, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 78.61 s - in org.keycloak.testsuite.forms.LoginTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 38, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:01 min
[INFO] Finished at: 2024-12-03T10:24:32+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project integration-arquillian-tests-base: 
[ERROR] 
[ERROR] Please refer to /keycloak/testsuite/integration-arquillian/tests/base/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd '/keycloak/testsuite/integration-arquillian/tests/base' && '/usr/lib/jvm/java-17-openjdk-17.0.12.0.7-2.fc39.x86_64/bin/java' '-Djava.awt.headless=true' '-Xms2048m' '-Xmx2048m' '-XX:MetaspaceSize=512m' '-XX:MaxMetaspaceSize=1024m' '--add-opens=java.base/java.lang=ALL-UNNAMED' '--add-opens=java.base/java.util=ALL-UNNAMED' '-Duser.language=en' '-Duser.region=US' '-XX:+ExitOnOutOfMemoryError' '-XX:+HeapDumpOnOutOfMemoryError' '-jar' '/keycloak/testsuite/integration-arquillian/tests/base/target/surefire/surefirebooter-20241203102312423_3.jar' '/keycloak/testsuite/integration-arquillian/tests/base/target/surefire' '2024-12-03T10-23-12_300-jvmRun1' 'surefire-20241203102312423_1tmp' 'surefire_0-20241203102312423_2tmp'
[ERROR] Process Exit Code: 0
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd '/testsuite/integration-arquillian/tests/base' && '/usr/lib/jvm/java-17-openjdk-17.0.12.0.7-2.fc39.x86_64/bin/java' '-Djava.awt.headless=true' '-Xms2048m' '-Xmx2048m' '-XX:MetaspaceSize=512m' '-XX:MaxMetaspaceSize=1024m' '--add-opens=java.base/java.lang=ALL-UNNAMED' '--add-opens=java.base/java.util=ALL-UNNAMED' '-Duser.language=en' '-Duser.region=US' '-XX:+ExitOnOutOfMemoryError' '-XX:+HeapDumpOnOutOfMemoryError' '-jar' '/keycloak/testsuite/integration-arquillian/tests/base/target/surefire/surefirebooter-20241203102312423_3.jar' '/keycloak/testsuite/integration-arquillian/tests/base/target/surefire' '2024-12-03T10-23-12_300-jvmRun1' 'surefire-20241203102312423_1tmp' 'surefire_0-20241203102312423_2tmp'
[ERROR] Process Exit Code: 0
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:714)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:311)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:268)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1334)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1167)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:931)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
[ERROR] 	at org.apache.maven.buildcache.BuildCacheMojosExecutionStrategy.execute(BuildCacheMojosExecutionStrategy.java:145)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:827)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:272)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:195)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### How to Reproduce?

```bash
cd keycloak/testsuite/integration-arquillian/tests/base/
mvn clean install -Pauth-server-quarkus-embedded -Dtest=LoginTest
```

### Anything else?

```
java -version
openjdk version "17.0.12" 2024-07-16
OpenJDK Runtime Environment (Red_Hat-17.0.12.0.7-2) (build 17.0.12+7)
```

### LINKED ISSUE #35591: Embedded test server fails when running from `mvn`
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

When running tests with the new tests framework with the embedded server mode the JVM is terminated unexpectedly.

```
org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
```

This is caused by the following code:

https://github.com/keycloak/keycloak/blob/0f72fa283d161ba31755bc71f2a0e2da4f6b8521/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java#L196-L199

The changes around this was likely introduced by https://github.com/keycloak/keycloak/commit/799ee85b7f55b52048c9ec567e4f7e612b59efbe

The embedded test server is started with:

https://github.com/keycloak/keycloak/blob/0f72fa283d161ba31755bc71f2a0e2da4f6b8521/test-framework/core/src/main/java/org/keycloak/test/framework/server/EmbeddedKeycloakServer.java#L15-L21

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Embedded Keycloak server is not terminated abruptly with System.exit

### Actual behavior

`System.exit` is invoked causing Surefire VM to exit

### How to Reproduce?

```
cd test-framework
KC_TEST_SERVER=embedded mvn clean install -Dtest=FancyRealmTest
```

To enable remote debugging edit `test-framework/examples/tests/pom.xml` and update config for surefire-plugin to:

```
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=8787</argLine>
                    <systemPropertyVariables>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                        <java.util.concurrent.ForkJoinPool.common.threadFactory>io.quarkus.bootstrap.forkjoin.QuarkusForkJoinWorkerThreadFactory</java.util.concurrent.ForkJoinPool.common.threadFactory>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
```

Start tests, and run remote debugging from the IDE with a breakpoint on L197 in Picocli

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #35550, closes #35591

### CODE REVIEW

**Comment by shawkins** [comment]
@vramik this was introduced by some recent picocli changes.

@vmuzikar @mabartos @Pepo48 we don't have any usage of the quarkus-embedded profile in the GHA tests, is that intentional?

**Comment by stianst** [comment]
Had the same issue with the new test framework (#35591) and this PR fixes the issues for that

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks!

**Comment by vmuzikar** [comment]
> we don't have any usage of the quarkus-embedded profile in the GHA tests, is that intentional?

Yeah, embedded is meant for dev purposes only. But it might be for a discussion if we want to spend some GHA resources on that, maybe nightly at least.

**Pull request merged**
