### PR TITLE
Forward quarkus server output to console in testsuite

### LINKED ISSUE #13512: Exceptions are not visible in testsuite output
### Describe the bug

I'm running the test suite under maven with `-Pauth-server-quarkus`. 
Exceptions in the server are not visible in the log output.

The server logs are also missing from the testsuite output.

### Version

main

### Expected behavior

When code run by the server throws an exception, lets say `NullPointerException`, I'd like full backtrace to be displayed in the test suite output.

### Actual behavior

The exception from failing test case is shown, but the original exception in the server that caused the test case to fail is not shown.

### How to Reproduce?

Modify server to throw unhandled exception.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tsaarni**
This change proposes adding a thread that reads the output from the server process during test suite execution and writes it to `System.out`.

Motivation:

When running tests via maven with `-Pauth-server-quarkus` the server output is lost. Only output from test cases themselves is found from the logs but not the the output from the server. In most cases the server logs would pinpoint any problem. For example if there was exception at the server, the backtrace will not be visible currently.

Previously, it seems that `inheritIO()` is called in attempt to connect `stdout` and `stderr` of the server process to console. In practise it connects it the JVM process. This causes the output to be written in `testsuite/integration-arquillian/tests/base/target/surefire-reports/*.dumpstream` in quite non-practical format.

Fixes #13512

### CODE REVIEW

**Review by mabartos — APPROVED** [review]
@tsaarni Thanks for the PR! Works as expected. _Please, it'd be great if you have a chance to create an issue for that and address it in the commit message._

@DGuhr @pedroigor Could you please take a look at it? Thanks

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@tsaarni Good one :)

**Comment by tsaarni** [comment]
> _Please, it'd be great if you have a chance to create an issue for that and address it in the commit message._

@mabartos Sorry, I did not manage to add the issue number into the actual git commit message, I was too slow.

@pedroigor Thank you for merging!

**Comment by tsaarni** [comment]
By the way, some projects get the PR number automatically appended to the commit title.  I _think_ it is because squash merge setting in github project settings 
image
Obviously, this does not then preseve the original commits, which may be even preferred by some.

**Comment by mabartos** [comment]
@tsaarni No worries. Thanks!

**Pull request merged**
