### PR TITLE
[Admin UI] Allow DynamicComponents on OIDC and SAML IDP

### LINKED ISSUE #25666: [Admin UI] Allow to customize built-in components administration UI via ConfiguredProvider
### Description

`org.keycloak.provider.ConfiguredProvider` allows to provide a list of `org.keycloak.provider.ProviderConfigProperty`. This list is then interpreted by the admin UI to generate a list of UI inputs. As of today, almost all `ProviderFactory` implement `ConfiguredProvider`.

This nice feature can be used to add custom fields on a third-party `ProviderFactory`, but not on a built-in one.

I'd like to be able to add custom fields to built-in components.

### Discussion

_No response_

### Motivation

I need to add some config properties to all `org.keycloak.broker.provider.IdentityProviderFactory` and `org.keycloak.broker.social.SocialIdentityProviderFactory` implementations, including the built-in ones. I need them to be seizable via the Admin UI.

### Details

This could take the form of a new SPI allowing to "complete/enrich" the list returned by `org.keycloak.provider.ConfiguredProvider#getConfigProperties`.

### PR DESCRIPTION
**Pull request by reda-alaoui**
Closes: #25666

### CODE REVIEW

**Review by hmlnarik — APPROVED** [review]
Thank you for the PR!

**Comment by nicolabeghin** [comment]
Any hint if this will be released in v24? Thanks!

**Comment by jonkoops** [comment]
You can see the issue labels to see what release this would end up in.

**Comment by nicolabeghin** [comment]
> You can see the issue labels to see what release this would end up in.

thanks for the explanation! don't know if it's too much to ask, but would it be possible to know why it wasn't picked for the latest releases like [23.0.6](https://github.com/keycloak/keycloak/releases/tag/23.0.6) released on February 2nd 2024 given the PR was merged at beginning of January?

**Comment by jonkoops** [comment]
I am not sure why, it could be a mistake on the labeling side, we introduced a bot to label things for us, and it might have some bugs still. You can check the `release/23.0` branch and see if the commit for this work is in there, that should tell you.

**Pull request merged**
