### PR TITLE
KEYCLOAK-7270 - Support for automatically linking brokered identities

### PR DESCRIPTION
**Pull request by slominskir**
See: https://issues.jboss.org/browse/KEYCLOAK-7270

### CODE REVIEW

**Comment by mposolda** [comment]
@slominskir Thanks for the PR! We may need an automated test, which is likely the last remaining thing pending. Is it possible to add the test for this to AbstractFirstBrokerLoginTest class (real test subclasses are OIDCFirstBrokerLoginFlow, SAMLFirstBrokerLoginFlow).

**Comment by mposolda** [comment]
@slominskir Likely yes as existing tests for 'first-broker-login' flow are there. We have plan to migrate all remaining identityProvider tests to the new testsuite, but not yet done...

**Comment by slominskir** [comment]
I might need some tips for getting tests working.  The current build / test suite fails if run naively.  This makes it difficult to create new tests.  I can successfully compile the project with the command:

`mvn install --DskipTests `

Without the skipTests argument the build fails though with messages such as:

> testMultipleResponseTypes(org.keycloak.test.ResponseTypeTest)  Time elapsed: 0 sec  <<< ERROR!
> java.lang.NoClassDefFoundError: Could not initialize class org.keycloak.test.ResponseTypeTest

I've tried manually starting a test server following the directions here: https://github.com/keycloak/keycloak/blob/master/misc/Testsuite.md, but this fails with:

> Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (default-cli) on project keycloak-bom-parent: The parameters 'mainClass' for goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java are missing or invalid

I assuming adding a new test might start with copying the method OIDCFirstBrokerLoginTest.testLinkAccountByReauthenticationWithDifferentBroker to another one named something like testAutoLinkAccountWithDifferentBroker.

**Comment by mposolda** [comment]
How about this:

```
cd keycloak
mvn clean install -DskipTests=true
mvn -f testsuite/integration-deprecated/pom.xml -Dtest=OIDCFirstBrokerLoginTest clean install
```

My maven version:
```
mposolda@mposolda-w541:~/IdeaProjects/keycloak$ mvn --version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /home/mposolda/software/apache-maven-3.3.3
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-128-generic", arch: "amd64", family: "unix"

```

**Comment by slominskir** [comment]
Yeah, the targeted test build works.  Thanks.

So, I know how to configure a new flow from the command line via the JSON endpoint, and via the GUI, but not programmatically.  It looks like the OIDCFirstBrokerLoginTest just uses the default first login flow, with individual test cases disabling and re-enabling parts like the email validator, and I assume I'll need to instead programmatically create a new flow with just the two authenticators (1. handle unique and 2. auto link).  Any examples of doing this sort of thing within the test scaffolding?  Or maybe some documentation?  Most of the code isn't documented inline so I'm doing a lot of guessing and poking around.

**Comment by slominskir** [comment]
@mposolda It isn't clear to me how many people will want to use the AutoLink authenticator - if not the majority then perhaps we keep it out of the default flow.  An alternate flow does make the test case harder though...

I think I might have the basic form of the Test case now, but I'm getting a Hibernate error.  Maybe the issue I'm seeing is the creation of a new Flow isn't committed to the database before the new Execution tries to find and link to it.  I'm not sure though.  See gist of code: 

> https://gist.github.com/slominskir/02f0c4a429fd9a30a25539596dc145e0

And exception: 

```
testAutoLinkAccountWithBroker(org.keycloak.testsuite.broker.OIDCFirstBrokerLoginTest)  Time elapsed: 0.034 sec  <<< ERROR!
org.keycloak.models.ModelException: java.lang.IllegalArgumentException: id to load is required for loading
        at org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:93)
        at org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:63)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2759)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2741)
        at org.hibernate.internal.SessionImpl.get(SessionImpl.java:978)
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.find(AbstractEntityManagerImpl.java:1075)
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.find(AbstractEntityManagerImpl.java:1033)
        at sun.reflect.GeneratedMethodAccessor351.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:49)
        at com.sun.proxy.$Proxy60.find(Unknown Source)
        at org.keycloak.models.jpa.RealmAdapter.addAuthenticatorExecution(RealmAdapter.java:1553)
        at org.keycloak.models.cache.infinispan.RealmAdapter.addAuthenticatorExecution(RealmAdapter.java:1170)
        at org.keycloak.testsuite.broker.OIDCFirstBrokerLoginTest$4.config(OIDCFirstBrokerLoginTest.java:177)
        at org.keycloak.testsuite.rule.AbstractKeycloakRule.update(AbstractKeycloakRule.java:142)
        at org.keycloak.testsuite.broker.OIDCFirstBrokerLoginTest.testAutoLinkAccountWithBroker(OIDCFirstBrokerLoginTest.java:157)
```
Any tips?   How do I add logging to tests?  System.out.println doesn't show up.  Also, adding JBoss Logger at WARNING level doesn't show up either.  Maybe I'm not setting a providerId or Alias correctly somewhere.

**Comment by mposolda** [comment]
@slominskir That could be it. Perhaps add flow in one transaction and executions in another might help?

**Comment by slominskir** [comment]
@mposolda I'm not familiar with the internals of the Keycloak framework - how do I get an EntityManager to commit the transaction?  I'm working with POJOs (at least on the surface) in the test case.  The database transactions are at a lower layer of the architecture.

**Comment by mposolda** [comment]
@slominskir You don't need that, sorry to not being very clear. Every rule is automatically in it's own transaction. So you may need just something along those lines (didn't test the code, just quick prototype to show the idea):

{code}
        // Transaction 1 - creating flow
        brokerServerRule.update(new KeycloakRule.KeycloakSetup() {
            @Override
            public void config(RealmManager manager, RealmModel adminstrationRealm, RealmModel appRealm) {
                AuthenticationFlowModel newFlow = new AuthenticationFlowModel();
                newFlow.setAlias("AutoLink");
                newFlow.setDescription("AutoLink");
                newFlow.setProviderId("basic-flow");
                newFlow.setBuiltIn(false);
                newFlow.setTopLevel(true);
                newFlow = appRealm.addAuthenticationFlow(newFlow);      
           }, APP_REALM_ID)l;

        // Transaction 2 - lookup flow and create executions
         brokerServerRule.update(new KeycloakRule.KeycloakSetup() {
            @Override
            public void config(RealmManager manager, RealmModel adminstrationRealm, RealmModel appRealm) {
                AuthenticationFlowModel newFlow = realm.getFlows().stream().filter((AuthenticationFlowModel flow) -> {
                    return "AutoLink".equals(flow.getAlias());
                }.getFirst();

                AuthenticationExecutionModel execution = new AuthenticationExecutionModel();
                execution.setFlowId(newFlow.getId());
                execution.setRequirement(AuthenticationExecutionModel.Requirement.ALTERNATIVE);
                execution.setAuthenticatorFlow(false);
                execution.setAuthenticator("idp-create-user-if-unique");
                execution.setPriority(1);
                execution = appRealm.addAuthenticatorExecution(execution);

                AuthenticationExecutionModel execution2 = new AuthenticationExecutionModel();
                execution2.setFlowId(newFlow.getId());
                execution2.setRequirement(AuthenticationExecutionModel.Requirement.ALTERNATIVE);
                execution2.setAuthenticatorFlow(false);
                execution2.setAuthenticator("idp-auto-link");
                execution2.setPriority(2);
                execution2 = appRealm.addAuthenticatorExecution(execution2);

                appRealm.getIdentityProviderByAlias(getProviderId()).setFirstBrokerLoginFlowId(newFlow.getId());
            }
           }, APP_REALM_ID);
{code}

**Comment by slominskir** [comment]
@mposolda Looks like the issue was using execution.setFlowId when I should be using execution.setParentFlow.  Separating the config into two separate transactions seems unnecessary after making that change.   

I'm not sure what to do next though as after loginIDP("pedroigor"); I was expecting the current page to match http://localhost:8081/test-app, but instead this.idpConfirmLinkPage.assertCurrent(); succeeds.

**Comment by mposolda** [comment]
@slominskir hmm... and if you configure flows manually as pointed in your documentation, is it working as expected (which means directly redirect to the app and check if idpConfirmLinkPage is not displayed)?

If yes, will be good to compare why it works for the "manually configured" environment and not in the test. In the test, you can add debug point or temporarily something like: Thread.sleep(3600000); after flows are reconfigured and check in the admin console if flows are configured as expected.

**Comment by slominskir** [comment]
What is the username and password for admin user to login to keycloak admin console launched from test framework?  Also, looks like two keycloaks are launched, one on port 8081 and one on port 8082.  What is that about?  A single keycloak instance could host multiple realms.  Looks like realm-with-broker is on port 8081 and realm-with-oidc-identity-provider and realm-with-saml-idp-basic are on port 8082?

**Comment by slominskir** [comment]
Nevermind, searching through code I see admin username and password is "admin" and "admin".  I now see the problem is that the "kc-oidc-idp" identity provider of the "realm-with-broker" doesn't have the first login flow set to "AutoLink".  Instead it is still set to the default "first broker login".  Not sure why though as I thought the following command would have taken care of it:

`appRealm.getIdentityProviderByAlias(getProviderId()).setFirstBrokerLoginFlowId(newFlow.getId());`

**Comment by slominskir** [comment]
OK, looks like that single line to set the first broker login flow should actually be:

```
IdentityProviderModel idp = appRealm.getIdentityProviderByAlias(getProviderId());                
idp.setFirstBrokerLoginFlowId(newFlow.getId()); 
appRealm.updateIdentityProvider(idp);
```

Now it seems to works, except I think the cleanup isn't working so later tests now fail.   I've updated the cleanup code at the end of the test method to attempt to revert the first broker login back to the default - it looks like:

```
        brokerServerRule.update(new KeycloakRule.KeycloakSetup() {
            @Override
            public void config(RealmManager manager, RealmModel adminstrationRealm, RealmModel appRealm) {
                IdentityProviderModel idp = appRealm.getIdentityProviderByAlias(getProviderId());                
                idp.setFirstBrokerLoginFlowId(DefaultAuthenticationFlows.FIRST_BROKER_LOGIN_FLOW); 
                appRealm.updateIdentityProvider(idp);                
            }
        }, APP_REALM_ID);
```

However, the test output now shows errors such as:

> Not found configured flow with ID 'first broker login' for identity provider 'kc-oidc-idp'

**Comment by slominskir** [comment]
OK, got it working.  Had to set original first broker login ID in a variable and then reference it later in the restore/cleanup code.  Looks like the ID was one of those random strings.  The new code now has a new assignment as the first line in the test method:

`final String originalFirstBrokerLoginFlowId = getRealm().getIdentityProviderByAlias(getProviderId()).getFirstBrokerLoginFlowId();`
        
I'll work on committing this test case and merging it into one commit and such.

**Comment by slominskir** [comment]
@mposolda - OK, I think this pull is now ready.  I've added a test case and after a lot of wrestling with git I squashed all the changes into a single commit.

**Comment by slominskir** [comment]
@mposolda - I've updated the ProvidersTests and now tests are passing.

**Review by mposolda — APPROVED** [review]
@slominskir Thanks!

**Pull request merged**
