### PR TITLE
KEYCLOAK-17622  Terms and Conditions - periodically ask for reacceptance

### PR DESCRIPTION
**Pull request by laskasn**
Resolves issue: 
https://issues.redhat.com/browse/KEYCLOAK-17622

### CODE REVIEW

**Review by stianst — CHANGES_REQUESTED** [review]
Firstly, I'm sorry for the long time to respond to this PR.

There's a few issues I see with the approach taken in this PR:

* T&C are periodically invalidated, which means a user could have to approve terms and conditions again a few minutes after they've already done so.
* Background/timer task to periodically expire T&C is fairly expensive and not needed really. It would be better to simple check during authentication time if a given users acceptance has expired or not.
* The approach to providing configuration for the T&C is not ideal, and should rather be configuration on the required action itself, instead at the realm level. This makes it quite a bit more tricky to implement this change as a first step would be to support configuration options for required actions themselves.

Rather than having a time that invalidates terms and conditions periodically for all users I'd rather like to see an max-age on terms and conditions approval, and then check that when users authenticate.

**Comment by laskasn** [comment]
> Firstly, I'm sorry for the long time to respond to this PR.
> 
> There's a few issues I see with the approach taken in this PR:
> 
> * T&C are periodically invalidated, which means a user could have to approve terms and conditions again a few minutes after they've already done so.
> * Background/timer task to periodically expire T&C is fairly expensive and not needed really. It would be better to simple check during authentication time if a given users acceptance has expired or not.
> * The approach to providing configuration for the T&C is not ideal, and should rather be configuration on the required action itself, instead at the realm level. This makes it quite a bit more tricky to implement this change as a first step would be to support configuration options for required actions themselves.
> 
> Rather than having a time that invalidates terms and conditions periodically for all users I'd rather like to see an max-age on terms and conditions approval, and then check that when users authenticate.

First of all, thanks @stianst for evaluating this PR.

Let me answer on your points, one by one (i am struggling a bit to remember what i have done many months before :P )

Regarding the first one, the T&C are not just periodically invalidated. What really happens is that they are periodically checked and if an expiry has occured, then they get invalidated :)

- The last time (timestamp) user has accepted the task is stored in the user attributes (by the requiredActionModel.getProviderId() field name). The task checks for all users 
if(epochSecondsNow > expiryOffset + userLastAcceptTime)
and if true, it resets the relevant required action. 
If the user accepts at some time the required action, then the userLastAcceptTime will be updated and the (epochSecondsNow > expiryOffset + userLastAcceptTime) of the next task will be false till the expiryOffset has elapsed. (So no invalidation will occur) 


- About the second point, the background task runs every 900 sec (15 mins) which i think is quite "sparce" to add a large processing burden on a running instance (moreover, it's asynchronous). 
Of cource, this depends on the number of users in a realm, and the user list might grow really large. 
What you propose is a nice idea though, and i will try to add the check during the authentication flow (hopefully, it will not add any delay to the authentication hotcode path), instead of having a periodic task.


- About the third point, why not have both? We could have a default-global, and an override (if an override is specified for the user, it is evaluated instead of the realm's default).


@stianst Please, check also the PR https://github.com/keycloak/keycloak/pull/7841 which is also important (and is simpler) - whenever an admin changes the T&C, he/she might want to ask all users to reaccept the new one!!!

**Comment by stianst** [comment]
With regard to performance this is going to be pretty horrible. Let's say you have 1000+ realms you're fetching and looping over all those realms every 15 minutes. Now let's say you have 100+ million users in one realm, you're again fetching and looping over all those users every 15 minutes.

**Comment by stianst** [comment]
With regard to how it is configured it really isn't suitable to hard-code the config for a specific action like you're doing in the admin console. Nor is it really ideal to use realm config for this purpose. This results in code that is hard for us to maintain, so I'm afraid we really can't accept this approach.

**Comment by laskasn** [comment]
> With regard to how it is configured it really isn't suitable to hard-code the config for a specific action like you're doing in the admin console. Nor is it really ideal to use realm config for this purpose. This results in code that is hard for us to maintain, so I'm afraid we really can't accept this approach.
 
How would you envisage the configuration of the "max-age on terms and conditions approval" you mention? We could change the way the whole thing is defined.

**Comment by laskasn** [comment]
> With regard to performance this is going to be pretty horrible. Let's say you have 1000+ realms you're fetching and looping over all those realms every 15 minutes. Now let's say you have 100+ million users in one realm, you're again fetching and looping over all those users every 15 minutes.

Indeed. I'll remove the periodical task and add the checks during the auth phase.

**Comment by stianst** [comment]
> > With regard to how it is configured it really isn't suitable to hard-code the config for a specific action like you're doing in the admin console. Nor is it really ideal to use realm config for this purpose. This results in code that is hard for us to maintain, so I'm afraid we really can't accept this approach.
> 
> How would you envisage the configuration of the "max-age on terms and conditions approval" you mention? We could change the way the whole thing is defined.

It's a non-trivial thing I'm afraid as it would require updating required actions to be configurable like authenticators are. @mposolda wdyt?

**Comment by mposolda** [comment]
> > > With regard to how it is configured it really isn't suitable to hard-code the config for a specific action like you're doing in the admin console. Nor is it really ideal to use realm config for this purpose. This results in code that is hard for us to maintain, so I'm afraid we really can't accept this approach.
> > 
> > 
> > How would you envisage the configuration of the "max-age on terms and conditions approval" you mention? We could change the way the whole thing is defined.
> 
> It's a non-trivial thing I'm afraid as it would require updating required actions to be configurable like authenticators are. @mposolda wdyt?

Yes, we don't have configuration at the level of required actions, we have just the configuration at the level of authenticators in the authentication flow.

And agree that adding configuration for the required actions would be non-trivial thing. I am not sure if we should rather do it as part of the "Authentication policies" effort instead of introducing "required action configuration" now?

**Comment by stianst** [comment]
@mposolda with auth policies in mind, perhaps we would just need to allow this PR to configure through realm attributes for now, with an plan to refactor it down the line?

**Comment by mposolda** [comment]
> @mposolda with auth policies in mind, perhaps we would just need to allow this PR to configure through realm attributes for now, with an plan to refactor it down the line?

@stianst +1

**Comment by stianst** [comment]
@laskasn are you still interested in working on this issue? For it to reach a mergeable state we'd need:

* To resolve performance issues move te check of terms and conditions expirations to authentication time, instead of using a background
* Revert changes to the old admin console and send a PR to https://github.com/keycloak/keycloak-ui, we may want to reconsider how it is configured in the admin-ui. Perhaps it should be a separate section that is visible when the t&c required action is enabled. @ssilvert wdyt?
* We'd probably want to update docs as well to mention this capability

**Comment by laskasn** [comment]
YES ! i have completed the reform!
Now it's done during the authentication of the user (i admit your idea was very good)
Reformed/Created 2 tests το cover the basic "execution" paths.
Rebased on main branch.
I am updating the PR!

**Comment by ssilvert** [comment]
> @laskasn are you still interested in working on this issue? For it to reach a mergeable state we'd need:
> 
> * Revert changes to the old admin console and send a PR to https://github.com/keycloak/keycloak-ui, we may want to reconsider how it is configured in the admin-ui. Perhaps it should be a separate section that is visible when the t&c required action is enabled. @ssilvert wdyt?
> * We'd probably want to update docs as well to mention this capability

@stianst  @mposolda 
Maybe I missed something but it does seem to me that this belongs in authentication policies.  Is there some reason we can't put the UI for it in auth policies now so we don't have to refactor later?

@laskasn Once this is settled and an API is place, open an issue at https://github.com/keycloak/keycloak-ui/issues.  The UI team will work with you to get this done quickly.

**Comment by laskasn** [comment]
> > @laskasn are you still interested in working on this issue? For it to reach a mergeable state we'd need:
> > 
> > * Revert changes to the old admin console and send a PR to https://github.com/keycloak/keycloak-ui, we may want to reconsider how it is configured in the admin-ui. Perhaps it should be a separate section that is visible when the t&c required action is enabled. @ssilvert wdyt?
> > * We'd probably want to update docs as well to mention this capability
> 
> @stianst @mposolda Maybe I missed something but it does seem to me that this belongs in authentication policies. Is there some reason we can't put the UI for it in auth policies now so we don't have to refactor later?
> 
> @laskasn Once this is settled and an API is place, open an issue at https://github.com/keycloak/keycloak-ui/issues. The UI team will work with you to get this done quickly.

ok, decide how this will be merged, and then let me know what else you would like me to do from my side ;)

**Comment by laskasn** [comment]
I have split the 

> > @laskasn are you still interested in working on this issue? For it to reach a mergeable state we'd need:
> > 
> > * Revert changes to the old admin console and send a PR to https://github.com/keycloak/keycloak-ui, we may want to reconsider how it is configured in the admin-ui. Perhaps it should be a separate section that is visible when the t&c required action is enabled. @ssilvert wdyt?
> > * We'd probably want to update docs as well to mention this capability
> 
> @stianst @mposolda Maybe I missed something but it does seem to me that this belongs in authentication policies. Is there some reason we can't put the UI for it in auth policies now so we don't have to refactor later?
> 
> @laskasn Once this is settled and an API is place, open an issue at https://github.com/keycloak/keycloak-ui/issues. The UI team will work with you to get this done quickly.

OK, i removed the UI part, and i am posting an issue on the keycloak-ui team to see how this is going to be implemented in the new UI.

Please, note that it looked like this on the old admin console! It was getting enabled only if the "terms and conditions" flag (leftmost one) was "true".  
reset_interval

**Comment by laskasn** [comment]
@ssilvert 
I am thining about the removal you asked of the UI part on the old admin console. Why do you prefer to remove it and not let it there (since it's a deprecated/fallback UI) and just add also the required stuff on the new admin console?

**Comment by ssilvert** [comment]
> I am thining about the removal you asked @ssilvert of the UI part on the old admin console. Why do you prefer to remove it and not let it there (since it's a deprecated/fallback UI) and just add also the required stuff on the new admin console? I believe the addition on the old admin console would allow people using the old console to have access to this feature, plus the js and the html would help the guys from the new UI admin console to understand what we are trying to do. What do you think @stianst @mposolda ?

Actually, it was @stianst who suggested reverting the UI part from the old console.  My personal opinion is that I don't mind as long as it is relatively small and you understand that the old console won't be around too much longer.

Mainly, I just want to make sure that you open an issue at https://github.com/keycloak/keycloak-ui/issues so we can get it implemented in the new console.

**Comment by cgeorgilakis** [comment]
@ssilvert @ssilvert I can roll back the change in old admin console.

The main issue for finishing this PR are ;

- Do you have any comments in this Pr or only related PRs blocks this PR?
- How do you want to be implemented in new admin console? @edewit? Do you want us to make a keycloak-ui PR for this after christmas holidays?
- Do you want extra PR in [keycloak-documentation for terms and condtions](https://www.keycloak.org/docs/latest/server_admin/index.html#proc-enabling-terms-conditions_server_administration_guide)?

**Comment by ssilvert** [comment]
> @ssilvert @ssilvert I can roll back the change in old admin console.
> 
> The main issue for finishing this PR are ;
> 
> * Do you have any comments in this Pr or only related PRs blocks this PR?
> * How do you want to be implemented in new admin console? @edewit? Do you want us to make a keycloak-ui PR for this after christmas holidays?
> * Do you want extra PR in [keycloak-documentation for terms and condtions](https://www.keycloak.org/docs/latest/server_admin/index.html#proc-enabling-terms-conditions_server_administration_guide)?

@cgeorgilakis My main concern at the moment is that the back end is complete and merged before we change the front end.

I'll let @xianli123 and @edewit make the final call on UI since they designed and developed this screen.  But given what you showed, I think that having a column called "Reset interval" doesn't make sense.  It only applies to one action so it doesn't deserve its own column header.  I suspect we would add a kabab menu to trigger a popup for required actions that have config settings.

Yes, we do need a PR for any changes that need to be made to the docs.

**Comment by cgeorgilakis** [comment]
I have created [Keycloak documentation PR](https://github.com/keycloak/keycloak-documentation/pull/1741)

**Comment by cgeorgilakis** [comment]
I have rebased this PR and have added already accepted [documentation PR](https://github.com/keycloak/keycloak-documentation/pull/1741).

@xianli123 and @edewit For new admin console, if I have understood well we want a new column (config settings) that will have kabab menu with reset interval for 'Terms and Conditions' and will be empty for other values. I hope I will do it next week.

**Comment by cgeorgilakis** [comment]
> @cgeorgilakis do you need help? Is this still something that needs to go in?

@edewit We need to implement the kebab menu in new admin console. 
I am not so familiar with react js and code is in draft mode. Unfortunately, react responsible team member could help me at least after 2 weeks.

Could you help me or will we postpone PR acceptance until our team could commit the admin console ui changes?

**Comment by stianst** [comment]
Thinking some more about this I wonder if we should have some version/hash on T&C instead of period re-acceptance? In summary we could version or create a hash of the T&C message, and ask a user to re-accept T&C if they have been updated. I could imagine that would make more sense to ask users to accept T&C again if they have indeed changed, rather than just accepting the same T&C as they've done in the past?

May be related to the use-case in: https://github.com/keycloak/keycloak/pull/7841#issuecomment-1651435560

**Comment by ssilvert** [comment]
> Thinking some more about this I wonder if we should have some version/hash on T&C instead of period re-acceptance? In summary we could version or create a hash of the T&C message, and ask a user to re-accept T&C if they have been updated. I could imagine that would make more sense to ask users to accept T&C again if they have indeed changed, rather than just accepting the same T&C as they've done in the past?
> 
> May be related to the use-case in: [#7841 (comment)](https://github.com/keycloak/keycloak/pull/7841#issuecomment-1651435560)

A change in T&C doesn't necessarily mean the user needs to re-accept.  It could be just a formatting change or a textual change that doesn't alter the legal terms of the agreement.  Maybe when T&C is edited it should prompt the administrator and ask if all users need to re-accept?

**Comment by stianst** [comment]
> > Thinking some more about this I wonder if we should have some version/hash on T&C instead of period re-acceptance? In summary we could version or create a hash of the T&C message, and ask a user to re-accept T&C if they have been updated. I could imagine that would make more sense to ask users to accept T&C again if they have indeed changed, rather than just accepting the same T&C as they've done in the past?
> > May be related to the use-case in: [#7841 (comment)](https://github.com/keycloak/keycloak/pull/7841#issuecomment-1651435560)
> 
> A change in T&C doesn't necessarily mean the user needs to re-accept. It could be just a formatting change or a textual change that doesn't alter the legal terms of the agreement. Maybe when T&C is edited it should prompt the administrator and ask if all users need to re-accept?

True, how do you prompt the administrator though? The T&C comes from message bundles, which could be deployed through the theme, or could come through realm specific localization. That's why I was thinking about something simple that just looked at if the translation had changed. Could perhaps add an optional key `.t&c.version` or something like that?

**Comment by mposolda** [comment]
Yes, true. We can have the "version property" saved in some resource bundle. Administrator can always change it when he wants users to ask for re-acceptance when there is new version of terms&conditions.

However that will solve the problem of "Ask users for re-acceptance always when terms&conditions are changed" .
It won't solve the problem of "Ask users for re-acceptance every 6 months (even if nothing is changed)".
In the description of https://issues.redhat.com/browse/KEYCLOAK-17622, it seems they rather want 2nd scenario? There is possibility that administrator can change the version manually every 6 months or so to ask users for re-acceptance. This is not entirely same like periodic re-acceptance (as also users who accepted yesterday will be asked again today for re-acceptance due version change), but maybe it is sufficient compromise?

**Comment by ssilvert** [comment]
On Wed, Jul 26, 2023 at 9:00 AM Stian Thorgersen ***@***.***>
wrote:

> Thinking some more about this I wonder if we should have some version/hash
> on T&C instead of period re-acceptance? In summary we could version or
> create a hash of the T&C message, and ask a user to re-accept T&C if they
> have been updated. I could imagine that would make more sense to ask users
> to accept T&C again if they have indeed changed, rather than just accepting
> the same T&C as they've done in the past?
> May be related to the use-case in: #7841 (comment)
> <https://github.com/keycloak/keycloak/pull/7841#issuecomment-1651435560>
>
> A change in T&C doesn't necessarily mean the user needs to re-accept. It
> could be just a formatting change or a textual change that doesn't alter
> the legal terms of the agreement. Maybe when T&C is edited it should prompt
> the administrator and ask if all users need to re-accept?
>
> True, how do you prompt the administrator though? The T&C comes from
> message bundles, which could be deployed through the theme, or could come
> through realm specific localization. That's why I was thinking about
> something simple that just looked at if the translation had changed. Could
> perhaps add an optional key .t&c.version or something like that?
>
I don't think you would want to force a million users to re-accept every
time there is an insignificant change to T&C, so version key sounds like
the solution to me.

Or instead of a version key, just have the key be a flag called something
like "RequireReAccept".   If a new version is detected and
"RequireReAccept" is true, then all users must re-accept.  Then you
wouldn't need to prompt the administrator in the UI.

**Comment by xianli123** [comment]
I am so sorry for missing so many discussions around this issue. I will take a look and see if I can help do something.

**Comment by cgeorgilakis** [comment]
The "RequireReAccept" flag and "version property" could be viable solutions in our other [related PR]( https://github.com/keycloak/keycloak/pull/7841). We are determined not to impose all users reaccepting Terms & Conditions each time there is a change in it. Instead, we propose that the responsibility lies with the Admin user, who can prompt all users to reaccept when necessary. Our proposed solution in the related PR involves implementing a simpler approach, controlled by a button.

I concur with @stianst's suggestion that we must find a more efficient way, especially considering the potential impact on numerous users. A plausible solution could involve the execution of background tasks per 1000 (fe) users. It is of utmost importance for Keycloak to offer this functionality, ensuring that users are appropriately informed about any modifications to the Terms & Conditions. To further discuss this matter, I propose to continue the conversation within the related issue.

It's worth mentioning that this particular PR addresses another valuable feature related to Terms & Conditions. For our use cases, we need to implement a policy of requiring users to re-accept the terms and conditions every 12 months. This means that every 12 months from the date of their last acceptance, users are prompted to review the terms and conditions and explicitly agree to them again. This approach ensures that our users continue to express their explicit agreement to the terms. For further details, please refer to Section 5.5 of the policy document accessible through the following link: https://documents.egi.eu/public/RetrieveFile?docid=3234&filename=EGI-SPG-Community-Member-Manage-V1.pdf&version=3

**Comment by fjrial** [comment]
I agree with latest comments suggesting to add a new flag version to the terms and conditions content, so the admin can force all users to re-accept them.

It would be also nice for us to have this option.

**Comment by xianli123** [comment]
I looked through all the comments.  I'm curious if we decided to add editing capabilities to T&C. In addition, should the version control be added? Once we have the final decision, I can come up with some UX solutions for the requirements.

**Comment by mposolda** [comment]
One generic question: Are the use-cases for "periodic re-acceptance" or "versioning" specific only to Terms & Conditions? Or do we want them to be applied also for other required actions?

I can imagine periodic updates for more actions (Like `Make sure user is required to update his profile every 12 months` or `Make sure user is required to update his TOTP every 12 months` etc), however things like "versioning" with the use-case like (`Make sure all users are required to update their profile now`) likely does not makes sense to every action? Just trying to figure if we should introduce "configuration options" in the `RequiredActionProvider` and make sure that admin console UI will render just the configuration options, which are applicable for the particular required-action implementation?

**Comment by ssilvert** [comment]
> One generic question: Are the use-cases for "periodic re-acceptance" or "versioning" specific only to Terms & Conditions? Or do we want them to be applied also for other required actions?
> 
>with the **use-case like (`Make sure all users are required to update their profile now`)** likely does not makes sense to every action? 

Apply required action to all users immediately could make sense for most required actions.  It would be a simple change to the UI in the Authentication section.

**Comment by xianli123** [comment]
@mposolda @ssilvert Thanks. If I understand correctly, we need to allow administrators to configure T&C and periodically make the general users accept new or old T&C at the UI level. Is that right?

**Comment by mposolda** [comment]
I guess it makes sense to plan the UI if we agree on what we want to achieve? I am still not 100% sure if it is clear TBH. Few use-cases come to me, which we might agree on:

1) Use-case `Ask all users for re-acceptance terms & conditions during their next login` (aka versioning). Do we want to support this? AFAIK answer is yes

2) Use-case `Apply required action XY to all users during their next login`. More generic version of above, which is not specific only to "terms & conditions", but pretty much to all required actions. @ssilvert mentioned it can makes sense for most required actions. I agree with that, however I think that required actions makes sense only to some "applicable users", not to all users of the realm. For instance "Ask all users to update their TOTP" - this would makes sense only to users with TOTP, likely not to all users in the realm? Similarly "Verify email" applicable only to users with the email, which may not be all realm users etc.

3) Use-case `Ask all users to re-accept terms & conditions every 12 hours` . Do we want to support this? IMO yes as "versioning" (or "Asking all users to re-acceptance") is not exactly same use-case as periodic re-accept

4) Periodic re-acceptance for all required actions (not specific only to terms & conditions). IMO makes sense to have this capability for all required actions, but again, usually just for "Applicable" users. So for instance: Ask users to update their TOTP every 6 months, but just those users with TOTP already set. For `Update Password`, we already have password policy `Expire Password`, which effectively does this, so no need to have this also through required action IMO.


I guess that for Milestone 1, we can do this only for Terms & Conditions and then at next stage extend to other required actions? Maybe in tab `Authentication` -> `Required actions`, we can have "Config" action to allow configure particular required actions? Similarly like we have in the `Authentication` -> `Flows` for individual authentication executions?

**Comment by ssilvert** [comment]
> I guess it makes sense to plan the UI if we agree on what we want to achieve? I am still not 100% sure if it is clear TBH. Few use-cases come to me, which we might agree on:
> 
> 1. Use-case `Ask all users for re-acceptance terms & conditions during their next login` (aka versioning). Do we want to support this? AFAIK answer is yes
> 2. Use-case `Apply required action XY to all users during their next login`. More generic version of above, which is not specific only to "terms & conditions", but pretty much to all required actions. @ssilvert mentioned it can makes sense for most required actions. I agree with that, however I think that required actions makes sense only to some "applicable users", not to all users of the realm. For instance "Ask all users to update their TOTP" - this would makes sense only to users with TOTP, likely not to all users in the realm? Similarly "Verify email" applicable only to users with the email, which may not be all realm users etc.
> 3. Use-case `Ask all users to re-accept terms & conditions every 12 hours` . Do we want to support this? IMO yes as "versioning" (or "Asking all users to re-acceptance") is not exactly same use-case as periodic re-accept
> 4. Periodic re-acceptance for all required actions (not specific only to terms & conditions). IMO makes sense to have this capability for all required actions, but again, usually just for "Applicable" users. So for instance: Ask users to update their TOTP every 6 months, but just those users with TOTP already set. For `Update Password`, we already have password policy `Expire Password`, which effectively does this, so no need to have this also through required action IMO.
> 
> I guess that for Milestone 1, we can do this only for Terms & Conditions and then at next stage extend to other required actions? Maybe in tab `Authentication` -> `Required actions`, we can have "Config" action to allow configure particular required actions? Similarly like we have in the `Authentication` -> `Flows` for individual authentication executions?

I think this is very good @mposolda.  I agree with all of it.

The only part that might be a little tricky is figuring out who an "applicable user" is.  I guess you would need some sort of callback where you pass the user and ask the required action to decide if the user is "applicable".  It's doable though.

**Comment by pedroigor** [comment]
@mposolda Sounds like a good plan.

However, I agree with @cgeorgilakis that we should let administrators indicate whether a required action should run for users. I'm wondering how the "version property" considering that themes are also deployed as JARs.

Looking at the T&C required action, a timestamp is already set for the user. What we need now is to allow administrators to set a global timestamp to compare and check if the action should run again for a particular user (similar to not-before when expiring sessions at the realm level, I think). For now, we could store the global config as a realm attribute ... Or just think about enabling a component model to required actions.

**Comment by xianli123** [comment]
@mposolda @ssilvert @pedroigor I will come up with some designs based on the discussions and decisions. Once I have some deliverables, I will share them with you.

**Comment by xianli123** [comment]
Hi @mposolda @pedroigor , if the admin can configure the T&C, what attributes should be included in the T&C configurations? Does it just include the **Reset interval** including some number input fileds and time units, like the image shows below?
image

**Comment by pedroigor** [comment]
For now, and based on the discussions, I would say the `Reset interval` (not sure if the name is the best, perhaps `Expires in` or something) is enough for now and allows defining the validity period for the T&C acceptance.

However, in case you want to force users to accept the T&C when it changes, we need something else. Something along the lines suggested by Stian like a version. As I'm not sure how to deal with a version property, we could have an option to set the "not-before" timestamp.  This timestamp will basically invalidate any previous T&C accepted by the user before it and force the user to re-accept the T&C.

Makes sense?

I see you are also working with the old administration console ... Ideally, you should consider developing on top of the new admin console.  I think they have specific components there that can be re-used from authentication flows to configure required actions.

**Comment by xianli123** [comment]
@pedroigor Thanks. 

What's the deadline for your plan? @laskasn @mposolda @pedroigor @stianst

**Comment by pedroigor** [comment]
@xianli123 Not sure. As this is touching the UI (in addition to storing new data to realm/actions) we probably need more discussions to make sure we agree about the solution.

I see a lot of benefit on this proposal so it would be nice to have it done before 23.

**Comment by ssilvert** [comment]
> Hi @mposolda @pedroigor , if the admin can configure the T&C, what attributes should be included in the T&C configurations? Does it just include the **Reset interval** including some number input fileds and time units, like the image shows below? image

@xianli123 I believe this needs a way to select that you want no reset interval.  Maybe some sort of enable/disable.

**Comment by xianli123** [comment]
> As this is touching the UI (in addition to storing new data to realm/actions) we probably need more discussions to make sure we agree about the solution.

Thanks @pedroigor  Who can help us review the solution and make the final decisions? Is it necessary to have a meeting to discuss the solution?

**Comment by xianli123** [comment]
> I believe this needs a way to select that you want no reset interval. Maybe some sort of enable/disable.

@ssilvert Yes. I agree. That's also a use case.

**Comment by xianli123** [comment]
Can users upload or create a term and condition in the UI? The [Keycloak documentation](https://www.keycloak.org/docs/22.0.1/server_admin/#proc-enabling-terms-conditions_server_administration_guide) mentioned that `Edit the terms.ftl file in the base login theme`. So I wonder if it's possible to allow the admin to edit the content of the terms and conditions when the admin can configure the **Terms and conditions**. @pedroigor @mposolda

**Comment by ssilvert** [comment]
@xianli123 Yes, it is possible to upload the text.  If you are using our version of ftl files like `terms.ftl` and `register-commons.ftl`, you can override the text in those files if you re-define these messages:
```
termsTitle=Terms and Conditions
termsText=<p>Terms and conditions to be defined</p>
termsPlainText=Terms and conditions to be defined.
termsAcceptanceRequired=You must agree to our terms and conditions.
acceptTerms=I agree to the terms and conditions
```

So, an administrator can go to Realm settings --> Localization and define these from the UI.  

BTW, I'm not sure where all those messages are used.

**Comment by xianli123** [comment]
@ssilvert I think the message will display on the login page if the admin enables the "**Terms and conditions**". 

Screenshot 2023-08-21 at 17 36 51

**Comment by ssilvert** [comment]
> @ssilvert I think the message will display on the login page if the admin enables the "**Terms and conditions**".
> 
> Screenshot 2023-08-21 at 17 36 51

Yeah.  Some of those messages are easy to track down.  Others take a little more digging to find out what they are for.

**Comment by cgeorgilakis** [comment]
> So if I understand correctly, there are really 2 separate use-cases:
> 
> 1. Ask users for re-acceptance always when terms&conditions are changed
> 2. Ask users for re-acceptance every 12 months (even if nothing is changed in terms & conditions).
> 
> @cgeorgilakis Could you confirm that (1) is not sufficient for you and you also need to cover use-case (2) ? For instance, if you can live with (1), it means that administrator will need to update the terms & conditions required action every 12 months to enforce that users will re-approve them during their next authentication. This is not entirely same like periodic re-acceptance (as also users who accepted yesterday will be asked again today for re-acceptance due version change), but maybe it is sufficient compromise?

@mposolda yes we want both uses cases. [This issue](https://github.com/keycloak/keycloak/issues/17739) is for use case 1 and [this](https://issues.redhat.com/browse/KEYCLOAK-17379) for use case 2. What you describe after can not work in a real environment. Although now we want these only for T&C, I agree that it would be nice to have them for all Required Actions.

terms_and_conditions

@xianli123 the previous icon was for reset button in old admin console. @ssilvert has proposed for new admin console:

> I suspect we would add a kabab menu to trigger a popup for required actions that have config settings.

Finally, T&C can be changed with custom theme ( changing terms.ftl). We use this.

**Comment by xianli123** [comment]
@cgeorgilakis What is the aim of the **Reset** icon, to refresh the T&C or reset the intervals？

**Comment by ssilvert** [comment]
> > @cgeorgilakis What is the aim of the **Reset** icon, to refresh the T&C or reset the intervals？
> 
> Refresh T&C. This is from our PR. We could decide the appropriate name.

So does it mean, "Make all users perform the action on next login."?

**Comment by xianli123** [comment]
@cgeorgilakis Ok. I created a conceptual design as shown in the screen below. I put the configurations on this separate page. Users can configure the T&C in this page. Does it make sense?

Create_conditional_flow 2

**Comment by cgeorgilakis** [comment]
> @cgeorgilakis Ok. I created a conceptual design as shown in the screen below. I put the configurations on this separate page. Users can configure the T&C in this page. Does it make sense?
> 
> Create_conditional_flow 2

Yes. It looks good.

**Comment by jonkoops** [comment]
I am closing this PR as it has already been out there for some time and seems to be stuck in eternal review. We have this tracked under #19275, so we can continue further discussion there.

**Pull request closed without merging**
