### PR TITLE
New message variables to webauthn-register.ftl

### LINKED ISSUE #20744: Support for custom label message for WebAuthn authenticator's input label
### Description

It is simpler than it sounds. I was customizing the WebAuthn messages to portuguese and I noticed that there is no variable in the messages file that would allow me to change two texts from `webauthn-register.ftl`. Those messages are in line 117 and 118 and are: "WebAuthn Authenticator (Default Label)" and "Please input your registered authenticator's label".

### Discussion

_No response_

### Motivation

Simple to be added and gives more support to other languages beyond english.

### Details

I already did a fix for it in my application theme by creating the custom message variables. I only would have to translate to the other pending languages to make a PR.

### PR DESCRIPTION
**Pull request by VictorSCamargo**
Closes #20744

### CODE REVIEW

**Review by mposolda — DISMISSED** [review]
@VictorSCamargo Thanks!

**Comment by VictorSCamargo** [comment]
I'm embarrassing myself on my first contribution. Should have tested better first.

**Comment by mabartos** [comment]
@VictorSCamargo Thanks for the PR!

@mposolda Instability of the WebAuthn tests is related only to the WebAuthn with Firefox browser. Chrome should not be affected by that. It seems the provided changes in this PR cause the test failures.

**Comment by VictorSCamargo** [comment]
I will try to setup soon the tests on my machine to understand and fix this PR

**Comment by mposolda** [comment]
@VictorSCamargo I am closing as we're trying to reduce the count of opened PRs in the queue. But feel free to re-open (or open new PR) when you manage to have tests working.

**Pull request closed without merging**
