### PR TITLE
Entity version is not updated when the entity is root entity

### LINKED ISSUE #17339: Entity version is not updated when the entity is root entity

### PR DESCRIPTION
**Pull request by vramik**
Closes #17339

### CODE REVIEW

**Review by ahus1 — DISMISSED** [review]
Thank you for this change, LGTM!

**Comment by vramik** [comment]
@hmlnarik this one should be ready to be merged

**Comment by ahus1** [comment]
@vramik - I see that some actions failed, and the model tests timed out. Due to that the required actions didn't complete. With the latest change from Michal that fixes the timeout problem in the model tests, it might be worth rebasing this PR to get the PR green so it can be merged by a maintainer straight away.

**Review by ahus1 — APPROVED** [review]
LGTM. Ready to be merged once all builds are green.

**Review by hmlnarik — APPROVED** [review]
Approving per @ahus1 's approval

**Pull request merged**
