### PR TITLE
Fix connection reset error for remote identity providers such like github, Redhat SSO.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What does this pr do

Fix hard reproducible and random issue: https://issues.redhat.com/browse/CRW-1426

Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
Sorry, could you share link to your JIRA, please. I can't find it...

**Comment by mposolda** [comment]
JIRA is here: https://issues.redhat.com/browse/KEYCLOAK-17736 . Will be great to add the JIRA number to the commit message with the fix (See the other commits in the "/keycloak/keycloak" repository).

**Comment by AndrienkoAleksandr** [comment]
> Will be great to add the JIRA number to the commit message

done.

**Comment by pskopek** [comment]
I would like you to close this PR as the one in downstream PR is bit more general. Thanks for this one, anyway, downstream has been inspired by you.
Here is my forward port PR: https://github.com/keycloak/keycloak/pull/7956

**Pull request closed without merging**
