### PR TITLE
KEYCLOAK-4743 Add proxy support to HttpClient SPI

### PR DESCRIPTION
**Pull request by thomasdarimont**
We now provide a configurable way for dynamic proxy route selection
for the default HttpClient based on regex based targetHostname patterns.

Introduced `ProxyMapping` to describe a regex based ordered mapping
between target hosts and the proxy URL to use. The first matching pattern is
used to denote the proxy to use.

A `ProxyMapping` can be build from an ordered list of string based
mapping representations, e.g:
```
      .*\.(google|googleapis)\.com;http://www-proxy.acme.corp.com:8080
      .*\.acme\.corp\.com;NO_PROXY
      .*;http://fallback:8080
```
To denote that no proxy should be used for a host pattern, `NO_PROXY` can be used as www-proxy-uri.
If the targetHost does not match a configured proxy mapping,
no proxy is used.

Multiple `ProxyMapping`s  can be configured via standalone.xml / jboss-cli, e.g.:
```
  echo SETUP: Configure proxy routes for HttpClient SPI
  /subsystem=keycloak-server/spi=connectionsHttpClient/provider=default:add(enabled=true)
  /subsystem=keycloak-server/spi=connectionsHttpClient/provider=default:write-attribute(name=properties.proxy-mappings,value=[".*\\.(google|googleapis)\\.com;http://www-proxy.acme.corp.com:8080",".*\\.acme\\.corp\\.com;NO_PROXY",".*;http://fallback:8080"])
 
```
The new `ProxyMappingWareRoutePlanner` uses a configured `ProxyMapping`
to decide which proxy to use for a given request based on the target host
denoted by the HTTP request to execute.

### CODE REVIEW

**Comment by thomasdarimont** [comment]
I verified this manually with the BurpProxy Suite.

**Comment by thomasdarimont** [comment]
@stianst FYI I just revised the implementation of the Proxy Support for HttpClients as discussed in #4040

**Comment by stianst** [comment]
One big problem with adding support for HTTP proxy is testing. I'm not sure how we would test it, but we need proper integration tests before we can state that this is supported.

**Comment by stianst** [comment]
Merging this won't be considered until we have an option to test it as well as any related documentation has been updated. We also need to postpone merging this until 4.x as we are not adding more features to 3.x at this point.

**Comment by thomasdarimont** [comment]
Added proposed keycloak-documentation

**Comment by stianst** [comment]
@pdrozd any thoughts on how/if we should test support for running Keycloak behind an outgoing web proxy?

**Review by stianst — CHANGES_REQUESTED** [review]
We need to figure out how to test this

**Comment by stianst** [comment]
@thomasdarimont talked to QE and we've agreed that we'll take care of writing tests for this issue. So I'll just need to give this a spin and check it manually first. Could you give me hints to what web proxy you used and how to check it out?

**Comment by stianst** [comment]
Tested with docker run --name squid -p 3128:3128 sameersbn/squid

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
Thanks Thomas. Sorry it's taken so long to get this merged.

**Comment by thomasdarimont** [comment]
Thanks for merging :)

**Comment by thomasdarimont** [comment]
For the record: I tested this with a BurpSuite Proxy as discussed in:
http://lists.jboss.org/pipermail/keycloak-dev/2017-October/010072.html

**Comment by EggIt** [comment]
@thomasdarimont  what if the proxy requires credentials?

I have tried with a proxy mapping in the format http://username:password@proxy-url but it didn't work, the proxy still complains about credentials missing.

**Comment by thomasdarimont** [comment]
Hi @eggit, proxies authentication is currently not supported by this proxy support.

**Comment by ashirvadgupta** [comment]
Hi @thomasdarimont Did this configuration supports https based proxy URLs?

**Pull request merged**
