### PR TITLE
KEYCLOAK-8098 added email validation

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Comment by stianst** [comment]
Thanks for the PR, but validation should happen on the server side in the account rest endpoints, which will eventually be hooked into user profile spi so validation can be customised/configured.

**Comment by edewit** [comment]
Okay, but doing a simple validation like this helps the user entering the right data as he / she immediately sees that the email address that has been entered is wrong. The server side check can be more thorough

**Comment by vmuzikar** [comment]
+1 to have some simple client side validation (at least for now).
Of course we'll have some server side validation in the future but we could do some simple always-present basic validations on client side too (like check for emptiness which is already there, or simple email validation).

**Comment by stianst** [comment]
Okay, so we can add some basic validation on client-side. A couple questions:

* An email address like user@local-domain is valid in some cases, does this allow that?
* An email address once user profile is wired-in can be option. Does this allow that?

And a more general one - why not just use HTML5 email input type for client-side validation?

**Review by stianst — COMMENTED** [review]
See previous inline comments

**Pull request closed without merging**
