### PR TITLE
Fixes to hostname

### LINKED ISSUE #10627: Keycloak admin UI drops https port if --hostname is used
### Describe the bug

If I do
```
docker run --name keycloak -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -p 8543:8443 -v "$(pwd)"/target/classes/server-keystore.jks:/etc/server-keystore.jks quay.io/keycloak/keycloak:17.0.0 start  --hostname=localhost --https-key-store-file=/etc/server-keystore.jks
```
and then go to `https://localhost:8543` to the Admin UI which is displayed correctly and then click on an option to administer Keycloak, it fails with `404` the link has something like `https://localhost/somepath`, without `:8543`.

Replacing `--hostname=localhost` with `--hostname-strict=false` fixes it.

Perhaps it is a misconfiguration issue

### Version

17.0.0

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
* Removes the `none` value for the `proxy`option. Users should not really set this value but don't set `proxy`. It also causes issues when resolving `kc.proxy` because if `none` is set, the resolved value is `none` and not `false`.
* Added a `hostname-port` option to allow setting the port the proxy is using to expose the frontend URL.
* Removed the `hostname-admin` option because it is causing a lot of unnecessary confusion. We instead default to using the request info (scheme, port, etc) to build the admin Url and rely on the proxy to expose or not this URL.
* Added specific tests for hostname within the distribution test suite. We no longer need to run the tests from the base test suite.
* Fixes the test suite to properly remove the distribution before running tests.

Closes #10627
Closes #10331

### CODE REVIEW

**Review by DGuhr — CHANGES_REQUESTED** [review]
Nice, thanks! PR itself LGTM (assuming the tests are green) - but could you also change the https://www.keycloak.org/server/hostname guide pls to reflect these changes?

edit: seems there are also regressions to the operator testsuite.

**Comment by pedroigor** [comment]
@DGuhr Updated the guide.

**Comment by DGuhr** [comment]
@pedroigor think i spotted a bug, iirc the behaviour was different before:

scenario: run start-dev with https. want to access admin login after creating initial admin user.

0) create host entry for id.keycloak.test in local HOSTS
1) run `./kc.sh start-dev --hostname=id.keycloak.test --https-certificate-file=../conf/id.keycloak.test.pem --https-certificate-key-file=../conf/id.keycloak.test-key.pem --https-port=8555`
2) access welcomepage using https://localhost:8555, create initial admin user
3) click on "Administration console" link

outcome: invalid redirect_uri, see screenshot. also it now opens with id.keycloak.test instead of localhost.
Screenshot 2022-03-18 at 16 46 09

expected behaviour: login page for master realm opens with uri localhost:8555, as `hostname-strict` and `hostname-strict-https` are false in devmode and login is called from internal link.

Would be nice if we could check these also using automated tests (like assertAdminPage in the old testsuite), e.g. https://www.testcontainers.org/modules/webdriver_containers/ or using RestAssured.

**Comment by pedroigor** [comment]
@DGuhr Not really a bug because the client is not configured to allow that redirect URI. Try accessing using the hostname and it should work.

**Comment by DGuhr** [comment]
@pedroigor uh yes, absolutely right, my apologies. So then LGTM here :) 

Not 100% sure we would not need a `hostname-http-port` and `hostname-https-port`, but if so could be done in another iteration i guess.

**Review by DGuhr — DISMISSED** [review]

**Review by DGuhr — DISMISSED** [review]
seen tests working on https://github.com/andreaTP/keycloak/runs/5630710431?check_suite_focus=true so lgtm :)

**Review by DGuhr — APPROVED** [review]

**Review by stianst — APPROVED** [review]

**Comment by RVSO-NC** [comment]
Please also update "Relevant options":
image

None is still an option

**Comment by joao-rebelo** [comment]
I'm having troubles having the admin GUI behind a proxy since 17.0.1. I'm not sure if it would be caused by this issue and if it is an issue or a feature.
The details for my scenario / investigations so far are described at discourse:
https://keycloak.discourse.group/t/keycloak-17-0-1-admin-console-on-edge-mode/14584

Should I be configuring something differently now?

**Comment by AllexVeldman** [comment]
@pedroigor I was using the `hostname-admin` to expose the admin console to our development team using cloudflared tunnel on a separate subdomain with the frontend endpoints behind a proxy with `hostname-strict=true`.

What is the recommended migration for this scenario?

**Comment by pedroigor** [comment]
@AllexVeldman Now the admin URLs are solely based on the request info. That also means obtaining the info from the HTTP headers forwarded by your proxy.

**Comment by AllexVeldman** [comment]
@pedroigor The redirect_url is correctly built, it's the request for the login form that does not accept the redirect_uri:
```
2022-04-26 11:32:58,360 WARN  [org.keycloak.events] (executor-thread-0) type=LOGIN_ERROR, realmId=master, clientId=security-admin-console, userId=null, ipAddress=<ip>, error=invalid_redirect_uri, redirect_uri=https://subA.domain.com/auth/admin/master/console/
```

with keycloak.conf
```
hostname=subB.domain.com
hostname-admin=subA.domain.com
hostname-strict=false
hostname-strict-backchannel=false
```

So my flow is
- `https://subA.domain.com/auth/admin` (admin endpoint)
- redirects to `https://subA.domain.com/auth/admin/master/console/`
- requests (frontend endpoint) `https://subB.domain.com/auth/realms/master/protocol/openid-connect/auth?...redirect_uri=https%3A%2F%subA.domain.com%2Fauth%2Fadmin%2Fmaster%2Fconsole%2F`

**Comment by AllexVeldman** [comment]
I got it to work by setting the frontendUrl of the master domain as suggested in https://keycloak.discourse.group/t/frontendurl-and-adminurl-how-to-restrict-admin-console-to-internal-ip-only/2655

**Comment by pedroigor** [comment]
+1. It should also be possible to register the `https://subA.domain.com/auth/admin/master/console/` as a valid redirect URI for the `security-admin-console` client.

**Pull request merged**
