### PR TITLE
Fix differences between OpenAPI spec and admin API

### LINKED ISSUE #24960: OpenAPI spec doesn't match the admin API
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

This is a continuation of #23733 with two more problems in the generated OpenAPI spec for the Admin API:

- POST-methods returning `void` will return a 204 No Content response in the Keycloak API. This can be easily validated by looking at the browser's network trace in the Admin UI when, for example, adding a role mapping to a group. The OpenAPI spec currently defines these operations to return 201 Created though, which leads to issues in generated API clients. This is due to [this default in `smallrye-open-api`](https://github.com/smallrye/smallrye-open-api/blob/23842c0c95a937ba2bc1fc5e7789d636a7e8fbac/core/src/main/java/io/smallrye/openapi/runtime/scanner/spi/AnnotationScanner.java#L545). The fix is to either manually add `@APIResponse` annotations with the correct status code to these methods as I've done in this PR or to change these methods to return a `Response` setting the status code to 201.
- Some API endpoints duplicate the `{id}` parameter in their path, for example `/admin/realms/{realm}/clients/{id}/protocol-mappers/models/{id}`. This is fixed by this PR by changing some path parameters to be more specific, for example changing `clients/{id}` to `clients/{client-uuid}` to avoid the duplication and make it more obvious that the client's UUID instead of the client ID is required here.

### Version

22.0.5

### Expected behavior

The generated OpenAPI spec should match the admin API.

### Actual behavior

The generated OpenAPI spec doesn't match the admin API and an API client generated from the spec runs into deserialization issues when calling API endpoints.

### How to Reproduce?

    Generate the OpenAPI spec using mvn -pl services -am -DskipTests -P jboss-release
    Generate an API client from the spec in services/target/apidocs-rest/swagger/apidocs/openapi.json
    Call the given API endpoints using the generated client
    Deserialization into generated types fails because the OpenAPI spec doesn't match what the API actually returns

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by 999eagle**
Fixes #24960 

This is somewhat of a continuation of #23785 and fixes two more issues with the generated OpenAPI spec:

- POST-methods returning `void` will return a 204 No Content response in the Keycloak API. This can be easily validated by looking at the browser's network trace in the Admin UI when, for example, adding a role mapping to a group. The OpenAPI spec currently defines these operations to return 201 Created though, which leads to issues in generated API clients. This is due to [this default in `smallrye-open-api`](https://github.com/smallrye/smallrye-open-api/blob/23842c0c95a937ba2bc1fc5e7789d636a7e8fbac/core/src/main/java/io/smallrye/openapi/runtime/scanner/spi/AnnotationScanner.java#L545). The fix is to either manually add `@APIResponse` annotations with the correct status code to these methods as I've done in this PR or to change these methods to return a `Response` setting the status code to 201.
- Some API endpoints duplicate the `{id}` parameter in their path, for example `/admin/realms/{realm}/clients/{id}/protocol-mappers/models/{id}`. This is fixed by this PR by changing some path parameters to be more specific, for example changing `clients/{id}` to `clients/{client-uuid}` to avoid the duplication and make it more obvious that the client's UUID instead of the client ID is required here.

### CODE REVIEW

**Comment by 999eagle** [comment]
@rmartinc @mposolda can you please take a look at this when you have time?

**Comment by rmartinc** [comment]
@999eagle I see it OK but please create a new issue and link the commit/PR to it. The issue can be just what you are adding in the description. Thanks!

**Comment by 999eagle** [comment]
@rmartinc I've created an issue and linked it in this PR now.

**Review by rmartinc — APPROVED** [review]
Thanks @999eagle! Approving, maybe maintainers request you to also link the issue in the commit, but let's see what they say.

**Review by ahus1 — APPROVED** [review]
Approving as of @rmartinc's review. Thank you for fixing this!

**Comment by ahus1** [comment]
@999eagle / @rmartinc - when squashing a maintainer can add those "Closes #24960", although it is extra work. In this case looking at the commit it makes sense to keep them separately, so I updated each commit manually. 

For future PRs, it would be nice to have the issue number referenced in the commit as outlined in the `CONTRIBUTING.md` file. A maintainer updating the commit messages should be the exception.

**Comment by ahus1** [comment]
Adding to my previous comment the "why we need the issue number in commits": Those IDs are essential for to track changes in the source code back to the original ticket which details why things were changed, and what the discussions were. Without that number, the details would be lost, and a future contributor might have a hard time figuring out why something was changed. 

The second best solution is that a maintainer chooses to squash the changes via the GitHub API, and then GitHub adds by default the issue ID to the commit message. It requires manual work, and not clicking the wrong button. For very small changes this is sometimes an option even if there is no parent issue.

**Pull request merged**
