### PR TITLE
Do not store empty attributes when updating user profile

### LINKED ISSUE #22960: Do not store empty attributes when updating user profile
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

When an attribute value is set to an empty string it should not be persisted.

### Version

22.0.1

### Expected behavior

Attribute values set with an empty string should not be persisted.

### Actual behavior

When an attribute value is set to an empty string it should not be persisted.

### How to Reproduce?

* Create a user and do not set any root attribute like first and last names.
* Check the response from the User API and see if these attributes are set with an empty string.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #22960

### CODE REVIEW

**Comment by sschu** [comment]
Please see my comment on the issue and don't merge this, yet: https://github.com/keycloak/keycloak/issues/22960#issuecomment-1705973070

**Comment by sschu** [comment]
So I checked the change it does not actually seem to be that big. Also in the current code, empty values are not stored for attributes (unless the special removeAttribute flag is provided), the only difference is that this now only happens for custom attributes. So for builtin attributes empty values will be stored. If my understanding is correct, I don't see an issue with this.

**Comment by pedroigor** [comment]
@sschu As you can see from the test we are also not persisting empty values for root attributes like email, first, and last names.

We should be good to go then ...

**Review by mposolda — APPROVED** [review]
For me, this change is ok

@sschu Would you mind to approve as well if it looks ok to you?

**Review by sschu — APPROVED** [review]
LGTM.

**Pull request merged**
