### PR TITLE
make cli usable on OpenBSD

### PR DESCRIPTION
**Pull request by epsilon-0**
Signed-off-by: Aisha Tammy <aisha@bsd.ac>

### CODE REVIEW

**Comment by epsilon-0** [comment]
Hi, is there anyway in which I can help move this forward?

**Comment by ahus1** [comment]
Sorry it took us so long to respond. Could you please ask someone from the OpenBSD community to review this change and comment here? Once the builds are green and the review is in, I'm happy to merge this PR.

**Comment by epsilon-0** [comment]
> Sorry it took us so long to respond. Could you please ask someone from the OpenBSD community to review this change and comment here? Once the builds are green and the review is in, I'm happy to merge this PR.
> 
> For future pull requests, we usually as for an issue to be created first, that is then referenced in the pull request. See `CONTRIBUTING.md` for details.

Apologies, I will create an issue next time.
Sorry about not being clear, I'm an openbsd developer and the maintainer of the keycloak port in openbsd, so I don't know if you want anyone else as well.

**Comment by ahus1** [comment]
> I'm an openbsd developer and the maintainer of the keycloak port in openbsd, so I don't know if you want anyone else as well.

Thanks for pointing this out - I wasn't aware of this. Still, every pull request in this repository needs to be reviewed by a second person. As I'm unable to test the script on openbsd, I ask you to find someone from the openbsd community to confirm that this is correct. 

I'm especially curious about the added `javaPathHelper` - is that something that is commonly installed on openbsd?

**Comment by epsilon-0** [comment]
> > I'm an openbsd developer and the maintainer of the keycloak port in openbsd, so I don't know if you want anyone else as well.
> 
> Thanks for pointing this out - I wasn't aware of this. Still, every pull request in this repository needs to be reviewed by a second person. As I'm unable to test the script on openbsd, I ask you to find someone from the openbsd community to confirm that this is correct.

Of course, @qbit, could you check if this looks fine.

> 
> I'm especially curious about the added `javaPathHelper` - is that something that is commonly installed on openbsd?

Yes, this is an openbsd specific helper script which helps in find what Java version is used by a port. So it's installed by default on almost every users machine who uses a Java package. In our case for keycloak on openbsd, we are using Java 17, so `javaPathHelper -h keycloak` would say `/usr/local/jdk-17`. This is useful for the rc service script that ships with it for starting the service and also in the cli scripts, as we are doing here.

**Review by qbit — APPROVED** [review]
LGTM!

**Review by ahus1 — APPROVED** [review]
LGTM, thank you for contributing this change and organizing the review.

**Pull request merged**
