### PR TITLE
Node registration fix

### PR DESCRIPTION
**Pull request by wvdhaute**
Bugfix for node registration

### CODE REVIEW

**Comment by stianst** [comment]
Please add tests and create a JIRA bug report

**Comment by mposolda** [comment]
@wvdhaute This looks like a workaround. I am not sure why the formParameters can't be read directly in the authenticator and why it requires the separate session attribute. Please create JIRA with some details.

**Comment by wvdhaute** [comment]
@mposolda Sorry for the late answer, created a [JIRA issue](https://issues.jboss.org/browse/KEYCLOAK-5063)

I agree that it feels like a workaround, I've quickly dug a bit into the keycloak code but had no luck yet why this happens

**Comment by mposolda** [comment]
I've closed this because:
- The PR contains 2 changes unrelated to each other. We ideally want to have every PR focused on one thing.
- There are no JIRAs for any of those 2 changes in PR and there are no tests
- I think that both changes are either workarounds or not needed.
1) For formParameters I don't have clue why it's even needed. See my comment above. Please create JIRA with steps to reproduce.
2) Admin REST endpoint for validating user password - not sure if we want this OOTB. If we have similar endpoint, it won't be tightly coupled to "password" credential, but generic endpoint for credentials validation. Anyway, we already have possibility of pluggable REST endpoints. So you can add custom REST endpoint for validating passwords in your environment without a need to change anything inside Keycloak codebase.

**Comment by wvdhaute** [comment]
Sorry, lazily did not make a feature branch and committed the validatePassword on the same PR
Reverted that one fyi

**Pull request closed without merging**
