### PR TITLE
Ignore HibernateOrmProcessor logs related to persistence.xml

### LINKED ISSUE #19995: Ignore HibernateOrmProcessor logs related to `persistence.xml`
### Description

After offline discussions within our team, we've decided it'd be good to ignore logs related to the `persistence.xml` file. We specify our default datasource via the mentioned file, but the Quarkus preferred way is to use Quarkus properties.

See:
```
2023-04-27 09:29:15,096 INFO  [io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor] (build-27) Persistence unit 'keycloak-default': Enforcing Quarkus defaults for dialect 'org.hibernate.dialect.H2Dialect' by automatically setting 'jakarta.persistence.database-product-version=2.1.210'.                                                                                           
2023-04-27 09:29:15,119 INFO  [io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor] (build-27) A legacy persistence.xml file is present in the classpath. This file will be used to configure JPA/Hibernate ORM persistence units, and any configuration of the Hibernate ORM extension will be ignored. To ignore persistence.xml files instead, set the configuration property 'quarku
s.hibernate-orm.persistence-xml.ignore' to 'true'.        
```

### PR DESCRIPTION
**Pull request by mabartos**
Closes #19995

@pedroigor @vmuzikar Could you please check it? 

When the server starts, these mentioned logs are not part of the log anymore.

### CODE REVIEW

**Review by pedroigor — DISMISSED** [review]

**Comment by ahus1** [comment]
@mabartos / @pedroigor - it it logged at "INFO" level. If you want to hide those messages, it is sufficient to raise the level to WARN, to that warnings and errors are still logged. So I'd recommend to update this PR.

**Comment by mabartos** [comment]
@ahus1 Thanks for your comment. After an offline discussion with @pedroigor and @vmuzikar, the decision was to turn it off completely. I've checked the `HibernateOrmProcessor` class, and there are no logs with an Error level, and the ones with Warn level, they seem not so important in our context. Users can always override these props.

**Comment by ahus1** [comment]
@mabartos - thanks for explaining this. My concerns here: 

* "the ones with warn level [...] seem not so important in our context" sounds like "famous last words". 
* "users can always override these props" is not something they will do, as they will not know about this logging setting for this class

I'll not veto this one, so please go ahead and merge if you think this is good as it is.

**Comment by mabartos** [comment]
@ahus1 :smile: Yep, you're right. 

Don't need to be completely turned off; probably more reasonable is to specify only the WARN level. 

@pedroigor @vmuzikar WDYT?

**Review by vmuzikar — COMMENTED** [review]
I've been thinking about this. If there are no >=`WARN` level messages currently and we don't expect any at normal conditions, I think it makes sense to keep the `WARN` level. That way we will know something's not behaving as we expect.

**Review by vmuzikar — APPROVED** [review]

**Pull request merged**
