### PR TITLE
[KEYCLOAK-6764] Add an ability to pass the combined user properties as a single SAML attribute

### PR DESCRIPTION
**Pull request by shimkiv**

### CODE REVIEW

**Review by hmlnarik — CHANGES_REQUESTED** [review]
This change is inconsistent with the rest of mappers and while I acknowledge that Keycloak would benefit from feature allowing combining the attribute values, the implementation is not ideal since it hardwires the output format. I can imagine that having a mapper that would substitute ${..} parts of expressions of form e.g. "${firstName} ${lastName}" with the actual values would be better perceived. But since such a change needs approval from wider audience, I suggest to close this PR, discuss the expectation from users in keycloak-user list, then its implementation in keycloak-dev mailing list, and then contributing a new PR.

**Comment by shimkiv** [comment]
@hmlnarik thanks for comments
I actually was thinking about almost the same generalization of the approach right after the MR has been created. So, yes, I agree that kind of template variables will suit better.
Will follow your suggestions and closing this one.

**Comment by shimkiv** [comment]
And just as the reminder for those who will face similar needs:
- you always can create the `org.keycloak.protocol.ProtocolMapper` SPI for your project and deploy it as independent artifact.

**Comment by shimkiv** [comment]
Hey @davido ,
AFAIK there are several ways to do so:
- Earlier mentioned custom ProtocolMapper SPI;
- Script based ProtocolMapper (https://issues.jboss.org/browse/KEYCLOAK-5520)

The original discussion was here: 
- http://lists.jboss.org/pipermail/keycloak-dev/2018-May/010834.html

Please let me know if you need any further assistance

**Comment by davido** [comment]
@shimkiv Thanks for the pointer. I see, that https://issues.jboss.org/browse/KEYCLOAK-5520 is done. Is that meant that I need this extension:

https://github.com/cloudtrust/keycloak-client-mappers/blob/master/src/main/java/org/keycloak/protocol/saml/mappers/ScriptBasedMapper.java

I don't find ScriptBasedMapper.java in keycloak repository, somhow.

Do you have a working example what should I put in the script for computed full_name property?

**Comment by shimkiv** [comment]
@davido I can't help you with the script-based approach since I'm not using it. But I can provide you an example of the custom SPI, which should be deployed into the Wildfly AS in order to have the extension work

**Comment by davido** [comment]
@shimkiv Yes, custom SPI example would be appreciated. Can you also point me to the instructions, how to deploy the extension in Wildfly AS? Currently, I'm using standard Keycloak docker image from here: [1]. Thanks!

* [1] https://github.com/jboss-dockerfiles/keycloak/blob/master/docker-compose-examples/keycloak-postgres.yml

**Comment by shimkiv** [comment]
@davido Ok, I'll prepare the example and let you know where to look at

**Comment by shimkiv** [comment]
@davido Here you go: https://github.com/shimkiv/keycloak-saml-protocol-mapper-spi
(check the `start.sh` script for the commands involved and `docker-compose.yml`, `keycloak/Dockerfile` - for the configuration)

**Comment by davido** [comment]
@shimkiv Thanks! I will try to use it in the next days.

**Comment by shimkiv** [comment]
@davido I know nothing about the reasons (if any)

**Comment by davido** [comment]
@shimkiv Have someone tried to upload a PR with hard coded FullName-Saml-Protocol-Mapper? Would you have resources to upload something like that? I mean everyone using SAML protocol would require something like that anyway ;-)

**Pull request closed without merging**
