### PR TITLE
KEYCLOAK-9833 Large SSO Session Idle/SSO Session Max causes login failure

### PR DESCRIPTION
**Pull request by hokuda**
Please review this.
Thanks in advance.

### CODE REVIEW

**Comment by mposolda** [comment]
@hokuda I think that the PR is good. Thanks for this! It is just missing one small thing, which is this stuff https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserModelTest.java#L49-L57 . The fact that it's missing is causing the test is failing on Wildfly (See the travis log). I believe travis will be happy when you add this.

**Comment by hokuda** [comment]
@mposolda Thanks a lot for guiding me!
I added the code you suggested. Hope travis likes it.

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@hokuda Thanks!

**Pull request merged**
