### PR TITLE
missing message entry added

### LINKED ISSUE #9424: Missing translation for webauthn-doAuthenticate
### Describe the bug

There is no entry in the message file for webauthn-doAuthenticate

### Version

16.1.0

### Expected behavior

a entry like
`webauthn-doAuthenticate=Anmelden mit Security Token`

### Actual behavior

fallback to
`webauthn-doAuthenticate=Sign in with Security Key`

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by aruehl**
Missing translation of webauthn-doAuthenticate added

closes #9424

### CODE REVIEW

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thanks for preparing this PR. I tested it and found two things I would like you to change: 

* In the new message, "Security Token" is spelled without a hyphen. All other occurrences in this file are spelled with a hyphen. Therefore, please change it in your commit to "Anmelden mit Security-Token" to make it consistent.
* In the English file, the item is placed just below the key webauthn-unsupported-browser-text", while in this PR it is placed below "webauthn-error-user-not-found". Having the translation aligned with the original message file helps to keep translations in sync. Therefore, please move your translation up to the previous paragraph. 

Sorry I missed this in my previous review. 

To make small changes on this PR, you can allow maintainers to contribute code changes - this is of course fully optional. Please look in the GitHub UI for a checkbox like this: 

image

**Comment by ahus1** [comment]
Another note: This project recently changed its [contributing guidelines](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md) to ask for a specific commit message that should look like this: 

```
A brief descriptive summary

Optionally, more details around how it was implemented

Closes #1234
``` 

It would be great if you could adjust your commit message when you're updating your commit. Thanks!

**Comment by aruehl** [comment]
Hi @ahus1 ,
I have done the requested changes. The checkbox was already checked: 
grafik

**Comment by ahus1** [comment]
Hi @aruehl - thanks for updating this PR. 

I now realize that I don't have the proper permissions for edits as I am no maintainer on the Keycloak repoository, therefore I can't help by pushing changes to your PR branch. 

I see that you pushed the additional changes as separate commits. Please squash them to a single commit (see [CONTRIBUTING.md](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md#submitting-your-pr)):

> When preparing your PR make sure you have a single commit and your branch is rebased on the main branch from the project repository.

When squashing the commit, please update your commit message [so that it contains the issue number](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md#commit-messages-and-issue-linking):

```
A brief descriptive summary

Optionally, more details around how it was implemented

Closes #1234
```

Thanks,
Alexander

**Comment by aruehl** [comment]
Hi Alexander,
I have sqashed the commits and changed the commit message. 
Hope everything is correct now. :-)

Regards
Andreas

**Review by ahus1 — APPROVED** [review]
Tested this change locally and compared the translation to other German translations. As a German native speaker, this translation is great. Thanks for contributing!

**Comment by ahus1** [comment]
Hi @hmlnarik, I reviewed and tested this PR and I'd be happy if you could merge it.

I'm not sure who usually merges translation PRs - please advise I should contact someone else.

**Review by hmlnarik — APPROVED** [review]
Approving per @ahus1 's approval

**Pull request merged**
