### PR TITLE
[KEYCLOAK-1385] Unify source code line endings

### PR DESCRIPTION
**Pull request by lkubik**
Unification of the line endings. I used the unix lf. If you want the windows crlf I can redo the unification.

### CODE REVIEW

**Comment by patriot1burke** [comment]
This isn't going to cause merge conflicts is it?  I'm currently working on 50+ files.

**Comment by lkubik** [comment]
I suppose you already commit those in your local repo? If not then you can cherry-pick the first commit (https://github.com/lkubik/keycloak/commit/ccf4cc7f3edc0a0a02d8ac1221fc7c6e44fa25c8) and use the repo settings to let normalize your commit. There is a good tutorial how to do it. https://help.github.com/articles/dealing-with-line-endings/

If you already have commits in your local repo then it probably will result in conflicts. I will look at possible solution tomorrow.

**Comment by stianst** [comment]
If we want to change all files in this way, we need to a) be 100% sure it's correct and more importantly b) sync with everyone when to do it (i.e. no-one has large non-committed pieces of work).

**Comment by mposolda** [comment]
Also we may want to sync around IDE templates. Otherwise everyone will use bit different templates with different line endings and the issue will be back after some time.

**Comment by stianst** [comment]
AFAIK the .gitattribute file is supposed to sort out line-endings automatically when committing new stuff

**Comment by mposolda** [comment]
ah, ok. Good to know

**Comment by stianst** [comment]
I think the best way forward is to add whatever is needed to make sure there's no issues with new changes. Then at some point when everyone agree we'll format existing files and that would be a good chance to do full code formatting (make sure xml/json files are indented properly, make sure java source is formatted properly, etc.).

Looking at https://github.com/wildfly/wildfly/blob/master/.gitattributes that's much simpler than ours, surely they've figured it out ;)

**Comment by stianst** [comment]
@lkubik did you do some testing/experimentation with the .gitattributes to check if it actually works as expected?

**Comment by stianst** [comment]
Looking at this some more I think our .gitattributes file should be:
````
*.txt  text
*.java text
*.sh   text
*.bat  text
*.xml  text
*.json  text
*.properties  text
````

**Comment by lkubik** [comment]
@stianst I've tested it and it converts line endings correctly. When you push something it is converted to the line endings that are set in the .gitattributes.

Yes I agree that normalization should be done when contributors have as less locally edited files as possible. I've tried different settings of the git config core.autocrlf today but it seems that we need to do the normalization first to make this work. I will test what happens if we make the normalization and someone has changes on local.

As far as the .gitattributes file concerns I was confused about the text option meaning: "Explicitly declare text files you want to always be normalized and converted to native line endings on checkout.". I was afraid of it would change the line endings to lf on unix and crlf on windows but it seems to change the line endings to the machine native line endings on checkout and stores the line endings as LF to the repo on commit/push.

Why you don't want to have the .jsp, .html and other files normalized?

I've found a .gitattributes templates repository:
https://github.com/Danimoth/gitattributes
I would prefer merging mine .gitattributes with few simplifications and Java.gitattributes from that repository because there is a line endings chaos currently. For instance if I look on the .jsp files there are few of them with CRLF and most of them with LF. If you look into Wildfly repo they don't have .jsp files in the .gitattibutes but all of the jsp files have LF endings. Many file types in Keycloak haves this type of endings mixture.

Another option is to ask Wildfly devs how they deal with this problem. I will write them a mail.

Just to summarize this: 
1)I will check how git reacts if you normalize the repo and somebody has local changes. If it won't resolve in conflict while rebase then we can probably normalize easily after everyone push they local work.
2)I will write WF team a mail about how they deal with the line endings and then we can have more info in the .gitattributes content discussion.

**Comment by stianst** [comment]
Yep, we need to add jsp, html and ftl

I guess we should use https://github.com/Danimoth/gitattributes/blob/master/Java.gitattributes and add to that?

**Comment by lkubik** [comment]
I agree but let's wait for the WF team response about how they deal with that. (https://developer.jboss.org/thread/260037) If they don't respond within few days I'll ask on their IRC channel.

**Comment by lkubik** [comment]
So I asked on the wildfly-dev mailing list about the line endings and .gitattributes settings and Jason replied me that it is mistake that they don't have for example .jsp files in the .gitattributes file and it is a luck that nobody pushed them any CRFL line endings. So I suggest to use a little edited .gittatributes file from Danimoth and unify the line endings. I wrote a document about avoiding rebase conflicts of your local work after we unify the repo line endings.
https://docs.google.com/a/redhat.com/document/d/1t8__or2aOaQBCy8dKYrRb0API-AuRJ1-aQha23IDN1s/edit?usp=sharing
Fell free to look at it and make some comments/questions.

Could you please spread the info that we sync all devs local work before unification to minimize the risk? I haven't figured out how to do this only step by step without changing all the repo files so the all repo files unification has to be done. It would really help me to have unified line endings so I don't get much rebase/patch conflicts during productization.

**Comment by stianst** [comment]
In the doc you say that users should set local settings, but isn't this exactly what .gitattribute is supposed to prevent?

**Comment by lkubik** [comment]
Good point, I thought that git won't work well on Windows without that property and it won't convert LF to CRLF but I tried that just now and it appears that .gitattributes really overrides this git property. I deleted this part in the document.

**Comment by stianst** [comment]
Closing pull request as I'm preparing a new one to make sure new changes are updated as well

**Pull request closed without merging**
