### PR TITLE
KEYCLOAK-5662

### PR DESCRIPTION
**Pull request by pkadej**

### CODE REVIEW

**Comment by patriot1burke** [comment]
I don't see a test here.

**Comment by pkadej** [comment]
Done.
Pushed test twice. First run with travis should fail (fixed it in second push). 
Please consider rerun travis again.

**Comment by patriot1burke** [comment]
Looks good, but the cacheUser() method needs the same check. Can you add it there too?  Also, can you add a test for that?  You'd have to make sure that an unloaded user obeys the cache policy. i.e. if user is imported, and NO_CACHE is set.

**Comment by pkadej** [comment]
@patriot1burke Done. I used method getUserById which calls cacheUser.

**Comment by patriot1burke** [comment]
Thank you so much.  Nice work.

**Pull request merged**
