### PR TITLE
KEYCLOAK-10262 DBLockTest.testLockConcurrently fails with MariaDB Gal…

### PR DESCRIPTION
**Pull request by mposolda**
…era 10.1

### CODE REVIEW

**Comment by mposolda** [comment]
@hmlnarik @vramik @pdrozd Anyone of you has a chance to review? Added comment with some details to the https://issues.jboss.org/browse/KEYCLOAK-10262 . Will add the links to the jenkins builds in the corresponding pipeline PR.

**Review by vramik — APPROVED** [review]
Thanks @mposolda

**Review by hmlnarik — APPROVED** [review]

**Comment by hmlnarik** [comment]
Thanks @mposolda!

**Review by pdrozd — APPROVED** [review]

**Comment by mposolda** [comment]
@vramik @hmlnarik @pdrozd Thanks everyone for the review!

**Pull request merged**
