### PR TITLE
Remove Oracle Database JDBC driver from the Keycloak distribution

### LINKED ISSUE #22452: Ask admins to install the Oracle Database driver separately
### Description

Due to the Oracle driver being proprietary and not open source, it shouldn't be shipped as part of the Keycloak distribution. 

As [Oracle recommends](https://www.oracle.com/database/technologies/appdev/jdbc-downloads.html), "The best practice is use the latest version of the Oracle JDBC driver that supports the JDK and Database version that you use and is compatible with your support requirements."

Admins will need to download and install the drivers separately, depending among others on the Oracle database version they are using.

### Discussion

_No response_

### Motivation

Keycloak should ship only open source database drivers.

### Details

I'll prepare a PR for this

### PR DESCRIPTION
**Pull request by ahus1**
Closes #22452

### CODE REVIEW

**Comment by ahus1** [comment]
Tests are green. 

There is now a warning when doing a re-augmentation for Keycloak independent of the database being chosen: 

>  WARN  [io.quarkus.deployment.steps.ClassTransformingBuildStep] (build-19) Could not remove configured resources from the following artifacts as they were not found in the model: {com.oracle.database.jdbc:ojdbc11::jar=[oracle/nativeimage/CharacterSetFeature.class, oracle/nativeimage/Target_java_io_ObjectStreamClass.class]}

After #22443, this warning is only shown when the Oracle Database is selected - even when `ojdbc11-23.2.0.0.jar` is present in the `providers` folder.

**Comment by ahus1** [comment]
@mabartos - in this PR we want to skip distributing the Oracle JDBC driver as part of Keycloak. Rebasing this PR on top of your PR #22443 removes the warning in all cases except when using the Oracle driver. When the Oracle driver is chosen, it still prints: 

> WARN [io.quarkus.deployment.steps.ClassTransformingBuildStep] (build-19) Could not remove configured resources from the following artifacts as they were not found in the model: {com.oracle.database.jdbc:ojdbc11::jar=[oracle/nativeimage/CharacterSetFeature.class, oracle/nativeimage/Target_java_io_ObjectStreamClass.class]}

Do you know a way to avoid this warning? All tests are green.

cc: @vmuzikar, @pedroigor

**Comment by vmuzikar** [comment]
jFTR - I think we don't want to backport #22443 (and other related PRs) to 22 to be on the safe side with regressions. It's basically a feature/enhancement, not really a bug fix or critical enhancement. @mabartos WDYT?

**Comment by mabartos** [comment]
> After https://github.com/keycloak/keycloak/pull/22443, this warning is only shown when the Oracle Database is selected - even when ojdbc11-23.2.0.0.jar is present in the providers folder.

@ahus1 If the Oracle DB is not selected, all the Oracle stuff is ignored. Ignored in terms of all related artifacts are not loaded by class loader and shouldn't be packed in the distribution at all. This warning is probably shown there because the Quarkus Oracle extension is still present and the related build steps still see it available and handle it in some way.
I'll try to find some solution for that. 

>jFTR - I think we don't want to backport https://github.com/keycloak/keycloak/pull/22443 (and other related PRs) to 22 to be on the safe side with regressions. It's basically a feature/enhancement, not really a bug fix or critical enhancement. @mabartos WDYT?

@vmuzikar Yep, that's the plan; we don't want to backport that stuff.

**Comment by vmuzikar** [comment]
@mabartos I think we might need to remove the whole extension and write instructions how to re-add it.

**Comment by mabartos** [comment]
AFAIK, the problem is on the Quarkus side. I'll create an issue and send a PR for the Oracle JDBC extension.

**Comment by vmuzikar** [comment]
@mabartos Thanks for investigating! Not sure how's that an issue on Quarkus side if we're removing a direct dependency of the extension. :) But let's see...

In any case, if there's a fix on Quarkus side, we'd need to make sure it gets backported to 3.2 which might be too late to do.

**Comment by mabartos** [comment]
> Not sure how's that an issue on Quarkus side if we're removing a direct dependency of the extension.

IMO, I'd like to avoid removing the Oracle JDBC Quarkus extension. We'd simplify the whole process around connecting to the Oracle DB as customers do not have to add the extension itself + the JDBC driver. We'll save time for them and even for us when writing documentation for that. There should not be any problem with the productization of the Quarkus Oracle JDBC extension, right? :)

> In any case, if there's a fix on Quarkus side, we'd need to make sure it gets backported to 3.2 which might be too late to do.

Yep, I understand your concerns. These warnings should be related only to the native images. I'd suggest ignoring the warnings from the `io.quarkus.deployment.steps.ClassTransformingBuildStep` class for the 22 backport (set the log level to ERROR). From the long-term perspective, discuss the possible approach with the Quarkus team.

@vmuzikar @ahus1 WDYT?

**Comment by vmuzikar** [comment]
@mabartos Decreasing the log level works for me.

**Comment by mabartos** [comment]
Related Quarkus issue: https://github.com/quarkusio/quarkus/issues/35402

**Comment by ahus1** [comment]
@vmuzikar / @mabartos - I've updated the PR and the warning has been suppressed. I also added some docs. 

Please have a look. 

I saw that there is a very long error message message when the driver is not available with lots of `io.quarkus.runtime.configuration.ConfigurationException` and `java.lang.ClassNotFoundException: oracle.jdbc.xa.client.OracleXADataSource` during the build command. I want to handle this as a follow-up pull request if you agree.

**Review by vmuzikar — APPROVED** [review]
@ahus1 LGTM, thank you.

@mabartos Do you want to review as well?

> I saw that there is a very long error message message when the driver is not available with lots of `io.quarkus.runtime.configuration.ConfigurationException` and `java.lang.ClassNotFoundException: oracle.jdbc.xa.client.OracleXADataSource` during the build command. I want to handle this as a follow-up pull request if you agree. Ideally it would still make it for a KC22 backport.

+1
But I see it just as a non-blocking UX enhancement. We could perhaps even prohibit the `db=oracle` value (incl. `help` command) if the driver is not found on the classpath.

**Comment by mabartos** [comment]
@vmuzikar Yes, I'd like to review it. Did you follow these steps for the docker image? Can you confirm everything works as expected?

**Review by vmuzikar — CHANGES_REQUESTED** [review]
Based on https://github.com/keycloak/keycloak/issues/22452#issuecomment-1678970336, I discussed this a bit more with @stianst. Seems we should take a little bit different approach here.

**`main` branch**
* Remove the driver completely, i.e. no need for `includeProprietaryDependencies` profile.
* For testing (to better reflect real world scenario) include the driver in `providers` directory instead of building KC with the driver included.

**Backport to 22**
* The driver would remain in upstream included by default as it's a breaking change to do in a micro.
* Introduce `-DskipProprietary` property to remove the driver. This would be used only by RHBK 22 pipelines. (CC @ASzc)
* Docs and testsuite would need to be adapted to reflect the different behaviour (driver included vs removed) between Keycloak and RHBK.

@mabartos Would you be please able to take over as @ahus1 is on PTO?

**Pull request closed without merging**
