### PR TITLE
16188 added quotes to logging documentation to also work under Windows

### LINKED ISSUE #16188: Keycloak Quarkus Distro is not able to process the log multiple log handler
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I'm trying to start Keycloak with multiple log handler as the document suggests and it's failing in windows but the same works in mac 

**kc.bat start-dev --log=console,file --log-file=../data/kc.log
Option '--log' expects a single value (<handler>) Expected values are: console, file, gelf
Try 'kc.bat start-dev --help' for more information on the available options.**

I have tested it with latest also and it's failing 

image

Doc
image

### Version

20.0.1

### Expected behavior

It should not fail and run.

### Actual behavior

It's failing with multiple log handlere

### How to Reproduce?

Execute this command in windows 

kc.bat start-dev --log=console,file --log-file=../data/kc.log

And it will fail

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sschu**
Fixes #16188

### CODE REVIEW

**Comment by ahus1** [comment]
@sschu - could you please rebase this PR? 

At the time you created this PR, check "Status Check - Keycloak JavaScript CI" didn't complete as it was misconfigured in the main branch at that time. As it is technically required, I hope that all required checks pass once you rebase this PR. Thanks!

**Comment by sschu** [comment]
@ahus1 Sure, done.

**Review by vmuzikar — COMMENTED** [review]
@sschu Thanks, LGTM.

I believe the same issue also concerns the [features guide](https://github.com/keycloak/keycloak/blob/7899c6c80adebebc651688c9e2b7741b18f99d82/docs/guides/src/main/server/features.adoc?plain=1#L15). Feel free to open a follow-up issue, or update this PR. Either way works for me.

**Comment by ahus1** [comment]
@vmuzikar - we're about to move some docs, so it would be great if you could merge it rather now than later, otherwise this PR will be in conflict.

**Review by vmuzikar — APPROVED** [review]
@ahus1 Works for me. Created  https://github.com/keycloak/keycloak/issues/17376 for the Features guide.

**Pull request merged**
