### PR TITLE
KEYCLOAK-16249 Client Policy - Condition : Client - Any Client

### PR DESCRIPTION
**Pull request by tnorimat**
This PR is for [KEYCLOAK-16249 Client Policy - Condition : Client - Any Client](https://issues.redhat.com/browse/KEYCLOAK-16249 ) in [KEYCLOAK-13933 Client Policies](https://issues.redhat.com/browse/KEYCLOAK-13933), also is the part of the project [Client Policy Official Support](https://github.com/keycloak/kc-sig-fapi/projects) of [FAPI-SIG](https://github.com/keycloak/kc-sig-fapi) activity.

Generally speaking, the aim of this PR is to support policy conditions defined in [Client Policy design document](https://github.com/keycloak/keycloak-community/blob/master/design/client-policies.md#condition--which-client)

It behavior has been specified in [the JIRA ticket](https://issues.redhat.com/browse/KEYCLOAK-16249).

### CODE REVIEW

**Comment by tnorimat** [comment]
@mposolda This PR is not directly about Client Policy Official Support I mentioned in [page 16 of FAPI-SIG 6th Meeting Agenda](https://github.com/keycloak/kc-sig-fapi/blob/master/FAPI-SIG/meetings/6th/presentations/FAPI-SIG_6th_MTG_agenda%20.pdf) but relates to them. Could you or your team also review this PR? As discussed in https://github.com/keycloak/keycloak/pull/7594, this PR is needed to realize the built-in policy which can be applied to all clients and enforce basic level of security to them.

**Comment by mposolda** [comment]
@tnorimat PR looks good, but it has a conflict. Will probably just require rebase and should be fine?

**Review by mposolda — CHANGES_REQUESTED** [review]
Only requires rebase

**Comment by tnorimat** [comment]
@mposolda Yes, I'll rebase.

**Comment by tnorimat** [comment]
@mposolda I've rebased.

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
@tnorimat Thanks!

**Comment by tnorimat** [comment]
@mposolda Should we prepare other "Any" condition not applying to the special client?  (e.g. default clients generated automatically when creating a realm : account, account-console, admin-cli, broker, realm-management, security-admin-console)

The merged this "Any" condition may apply to these special clients.

**Pull request merged**
