### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Keycloak/Admin UI](https://hosted.weblate.org/projects/keycloak/admin-ui/).

It also includes following components:

* [Keycloak/Theme base/account](https://hosted.weblate.org/projects/keycloak/theme-baseaccount/)

* [Keycloak/Account UI](https://hosted.weblate.org/projects/keycloak/account-ui/)

* [Keycloak/Theme base/email](https://hosted.weblate.org/projects/keycloak/theme-baseemail/)

* [Keycloak/Theme base/login](https://hosted.weblate.org/projects/keycloak/theme-baselogin/)

* [Keycloak/Theme base/admin](https://hosted.weblate.org/projects/keycloak/theme-baseadmin/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by ahus1** [comment]
@jmallach - thank you for the CA translations you added. I see that some use single quotes in the translated term, like `l'administrador`. For the Java message format we're using here, all single quotes must be escaped as double quotes. Please have a look at the updated translations in this PR and update them to have two single quote where they should be printed on screen with a single quote.

**Comment by jmallach** [comment]
@ahus1, I'm confused. In this same PR I see French messages without escaped `'`. How do we know, in the Weblate interface, when to escape and when not to escape?

Have a look at one of my Keycloak 25 deploys:

image
image

I guess in at least some cases, the escaping is not necessari and in fact it is harmful. Since working on Weblate, I basically try to see if the unescaped string raises a "Java properties format" error, and in that case I add them back. How should I proceed?

**Comment by ahus1** [comment]
@jonkoops - Looking at @jmallach's response, my knowledge seems to be outdated. Looking at the code for the Admin UI and the Account Console, no escaping seems to be necessary in the Java message properties style in the code path where the frontend interpolates the messages using `i18n`. 

There are other places where some message interpolation happens in the backend, like in `FreeMarkerLoginFormsProvider#formatMessage()`. Can you please share your thoughts on this?

**Comment by jonkoops** [comment]
The properties file is parsed using the standard `Properties` class AFAIK, so any known limitations that apply there should apply here as well. The front-end doesn't do any additional escaping that I am aware of, we simply load the messages in from a REST API endpoint.

> There are other places where some message interpolation happens in the backend, like in `FreeMarkerLoginFormsProvider#formatMessage()`. Can you please share your thoughts on this?

What would you like to know? I am aware this is done inconsistently in many places. Some APIs return keys that the front-end needs to map. Some APIs return fully translated message. Sometimes these are translated in templates sometimes not. It's a mess, and I would really like to move it all to the API/backend, but the UI team has decided that all translations should happen on the front-end (which I disagree with, but that ship has sailed).

**Comment by ahus1** [comment]
@jmallach - ok I stand corrected. And I read from @jonkoops's reply that it is complicated. For all account and admin UI theme elements, you should use single quotes. If it is an error message, you should check twice, and probably test it. The login and email theme are probably different, as they don't use JavaScript.

Sorry for the mess. Clearing it up is beyond this issue, so let's try to cope with it for now. If you gain insights from your local tests, please document them in the `translation.md` file.

**Review by ahus1 — APPROVED** [review]
Approving translations from translation maintainers

**Pull request merged**
