### PR TITLE
KEYCLOAK-17267 Add index to user attribute name and value to support …

### PR DESCRIPTION
**Pull request by mhajas**
…user sync from ldap

The changes in model tests were needed because we had some files like `RequireProvider.java` or `KeycloakModelParameters.java ` doubled in both test and main sources. I removed them from the test source directory and updated the main ones to the latest changes.

### CODE REVIEW

**Review by vramik — APPROVED** [review]
Thank you @mhajas for the PR. LGTM

https://master-jenkins/job/universal-test-pipeline-server/404

**Review by hmlnarik — APPROVED** [review]
Approving, based on @vramik's approval

**Comment by arnou** [comment]
Thanks, this PR also closes KEYCLOAK-16757 😉

**Comment by mhajas** [comment]
Thanks for the heads up @arnou! I closed the Jira.

**Pull request merged**
