### PR TITLE
KEYCLOAK-12329 Fix linking accounts in the new Account Console

### PR DESCRIPTION
**Pull request by vmuzikar**
Tests will be added as part of [KEYCLOAK-12104](https://issues.jboss.org/browse/KEYCLOAK-12104).

### CODE REVIEW

**Comment by abstractj** [comment]
@vmuzikar Travis is complaining `testBuildLinkedAccountUri`, could you please review?

See:

```
-- [ERROR] Failures: 
-- [ERROR]   LinkedAccountsRestServiceTest.testBuildLinkedAccountUri:165 expected:<account[]> but was:<account[-console]>
```

**Comment by vmuzikar** [comment]
@abstractj Right, I somehow missed that, thanks! Should be fixed now.

**Review by ssilvert — APPROVED** [review]
This change effectively hard-codes the client id so that the API is only usable by the account console.

If that's what we want then this is fine.  But originally, this method was meant to be used by anyone who wanted an easy way to create the URL.  I don't want to go into the long, sordid history here.  

I'll approve the change as this method is deprecated on arrival and nobody is meant to use it except us anyway.

**Comment by vmuzikar** [comment]
@ssilvert Thanks for the review. As you mentioned, it's deprecated so I wouldn't worry too much about it – it's temporary in any way.

Btw, the client was hardcoded here even before this fix – just, it was done a few levels above it:
https://github.com/keycloak/keycloak/blob/35ada9d636b88ba0aa8b20f3fe757aac51dc88e4/services/src/main/java/org/keycloak/services/resources/account/AccountLoader.java#L52

**Pull request merged**
