### PR TITLE
Adding Copyright configuration for IntelliJ based IDEs

### LINKED ISSUE #29915: Automatically add copyright headers in IntelliJ
### Description

When new files are added, contributors now and then forget to add the copyright headers.

This can be automated with an IntelliJ configuration committed to the repository.

### Discussion

_No response_

### Motivation

Be more compliant with our code.

### Details

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #29915

### CODE REVIEW

**Comment by ahus1** [comment]
@pruivo - please have a look at this PR, as we talked about this during another PR. Is it working for you? Do you think it is helpful?

**Comment by pruivo** [comment]
I don't think it is useful. Devs using other IDE will have to configure on their own anyway.

**Comment by jonkoops** [comment]
Do we really need to add copyright notices to everything? The code in the repository is already under a specific license, why would that not be enough?

**Comment by ahus1** [comment]
> Do we really need to add copyright notices to everything? The code in the repository is already under a specific license, why would that not be enough?

I seems it is a common practice in open source projects. Maybe the lawyers suggest that practice?

I've seen instances where someone borrows a file and copies it other to another open source projects, and then license mix-ups occur. Yes, you want to detect those.

**Comment by jonkoops** [comment]
> I seems it is a common practice in open source projects. Maybe the lawyers suggest that practice?

To be very honest, I thnk it's just something that people do because they have always done so, not because of any relevant reason (aside from legal perhaps wanting to gate everything). All the code is already licensed clearly in the root of the project, and if someone really wanted to 'steal' code they could easily strip the copyright notice.

**Comment by ahus1** [comment]
Closing this as there is not much interest in this

**Pull request closed without merging**
