### PR TITLE
KEYCLOAK-14233 Support for generating SSL keystore before running testsuite

### PR DESCRIPTION
**Pull request by vmuzikar**
Test runs:
https://keycloak-jenkins.com/job/universal-test-pipeline-server/1831/
https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/1418/

Failed tests don't seem to be related to this change.

### CODE REVIEW

**Review by mhajas — DISMISSED** [review]
LGTM! Thanks @vmuzikar

**Comment by vmuzikar** [comment]
Thanks for the review! I've squashed the commits.

**Review by mhajas — APPROVED** [review]

**Comment by vmuzikar** [comment]
This block #7148.

**Review by abstractj — APPROVED** [review]
Approving based on @mhajas's review.

**Pull request merged**
