### PR TITLE
KEYCLOAK-17491 Move the key settings to the new Keys tab

### PR DESCRIPTION
**Pull request by y-tabata**
JIRA: https://issues.redhat.com/browse/KEYCLOAK-17491

# Changes
- Move the following components from Signed Jwt Authenticator in the "Credentials" tab to the new "Keys" tab.
  - `Use JWKS URL` switch
  - `JWKS URL` text area
  - `Certificate` text area
  - `Public key` text area
  - `Kid` text box
  - `No client certificate configured` message
  - `Generate new keys and certificate` button
  - `Import Certificate` button
  - `Save` button
  - `Cancel` button

- Display `Configure JWKS URL or Signing key in the Keys tab` message in Signed Jwt Authenticator in the "Credentials" tab
- Change the path of the `Generate Private Key` screen and `Import Client Certificate` screen
- Change the name of the `Saml Keys` tab to `Keys`
- Delete `Saml Keys` message from admin-message including all locales

### CODE REVIEW

**Comment by y-tabata** [comment]
Docs PR: https://github.com/keycloak/keycloak-documentation/pull/1143

**Review by mposolda — CHANGES_REQUESTED** [review]
@y-tabata Thanks for the PR and sorry for the late review! The changes itself looks good to me. Just few things:
- Is it possible to rebase on top of latest master?
- Did you try to run admin console tests with your changes? Unfortunately, I afraid that there might be test failures. Could you try it please after you do the rebase? Here are some instructions how to run the admin console tests with either Chrome or FF - https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md#admin-console-ui-tests

**Comment by mposolda** [comment]
@y-tabata Thanks for the rebase. I've tried to run the admin console tests after your rebase. I see the test failures in the admin console tests, which would require fixing:
```
    Run tests / Admin Console Tests / admin_console_tests / rhel8 / firefox / org.keycloak.testsuite.console.authorization.GroupPolicyManagementTest.testSaveWithInInvalidGroup
    Run tests / Admin Console Tests / admin_console_tests / rhel8 / firefox / org.keycloak.testsuite.console.clients.ClientCredentialsTest.generateNewKeysAndCert
    Run tests / Admin Console Tests / admin_console_tests / rhel8 / firefox / org.keycloak.testsuite.console.clients.ClientSAMLKeysTest.importSAMLKeyPKCS12
    Run tests / Admin Console Tests / admin_console_tests / rhel8 / firefox / org.keycloak.testsuite.console.clients.ClientSAMLKeysTest.importSAMLKeyJKS
    Run tests / Admin Console Tests / admin_console_tests / rhel8 / firefox / org.keycloak.testsuite.console.clients.ClientSAMLKeysTest.importSAMLKeyPEM
    Run tests / Admin Console Tests / admin_console_tests / win2016 / chrome / org.keycloak.testsuite.console.BasicConsoleTest.testUserWithViewUsersRoleCanOpenConsole
    Run tests / Admin Console Tests / admin_console_tests / win2016 / chrome / org.keycloak.testsuite.console.clients.ClientCredentialsTest.generateNewKeysAndCert
    Run tests / Admin Console Tests / admin_console_tests / win2016 / chrome / org.keycloak.testsuite.console.clients.ClientSAMLKeysTest.importSAMLKeyPKCS12
    Run tests / Admin Console Tests / admin_console_tests / win2016 / chrome / org.keycloak.testsuite.console.clients.ClientSAMLKeysTest.importSAMLKeyJKS
    Run tests / Admin Console Tests / admin_console_tests / win2016 / chrome / org.keycloak.testsuite.console.clients.ClientSAMLKeysTest.importSAMLKeyPEM
```

**Comment by y-tabata** [comment]
@mposolda Thanks for reviewing. I'm trying to run console tests in my local environment after rebase, but with chrome, almost all tests failed because of the client certificate selection popup. Is there any walkaround of this? 
chrome version is 90.0.4430.212 and the driver version is 90.0.4430.24.

Unfortunately, with firefox, almost all tests failed because of the proxy authentication popup. I think this is a unique issue in my environment.

**Comment by y-tabata** [comment]
@mposolda I prepared another test environment and fixed the failure of ClientCredentialsTest and ClientSAMLKeysTest. Could you please confirm this?

**Comment by y-tabata** [comment]
@mposolda Is there anything I can do for this PR?

**Comment by mposolda** [comment]
@y-tabata Could you please rebase again? I am still running admin console tests and saw some test failures. I think it is not a regression of your PR, but not 100% sure. Rebase will be nice.

**Comment by y-tabata** [comment]
@mposolda I rebased. How is it?

**Comment by mposolda** [comment]
@y-tabata Unfortunately in the last run, I saw the test failure in the admin console tests with Chrome. It is a chance that some minor tweak is needed (For example add some "waitForElementToLoad" or "waitForPageToLoad" or something like that in the correct place?) . The error was like this:
```
Error Message

Alert should displayed

Stacktrace

java.lang.AssertionError: Alert should displayed
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.keycloak.testsuite.page.AbstractPatternFlyAlert.assertDisplayed(AbstractPatternFlyAlert.java:73)
	at org.keycloak.testsuite.page.PatternFlyClosableAlert.assertDanger(PatternFlyClosableAlert.java:83)
	at org.keycloak.testsuite.page.PatternFlyClosableAlert.assertDanger(PatternFlyClosableAlert.java:79)
	at sun.reflect.GeneratedMethodAccessor439.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.graphene.proxy.GrapheneProxyHandler.invokeReal(GrapheneProxyHandler.java:129)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$1.invoke(GrapheneContextualHandler.java:169)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$2.call(GrapheneContextualHandler.java:241)
	at org.jboss.arquillian.graphene.context.BrowserActions.performAction(BrowserActions.java:62)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.invoke(GrapheneContextualHandler.java:237)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.intercept(GrapheneContextualHandler.java:263)
	at org.keycloak.testsuite.page.PatternFlyClosableAlert$$EnhancerByGraphene$$4a304773.assertDanger(<generated>)
	at org.keycloak.testsuite.console.AbstractConsoleTest.assertAlertDanger(AbstractConsoleTest.java:138)
	at org.keycloak.testsuite.console.clients.ClientCredentialsTest.generateNewKeysAndCert(ClientCredentialsTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by mposolda** [comment]
@y-tabata Also one more thing: If you do some updates to this PR for the test fix above, then please always do the rebase. AFAIK there can be changes in the admin console tests and missed rebase can mean that some tests might be failing.

**Comment by y-tabata** [comment]
@mposolda Thanks.
> Also if you want to simulate this, maybe you can try to run the test for the few times, as it looks it is just "Unstable" test, not the "Always failing" test.

I tried the ClientCredentialsTest 10 times but always successful (win10 and chrome).
So could you check my understanding is correct?

Regarding the test failure, according to your comment, the alert was not displayed because the "Generate new keys and certificate" button had not yet seemed to be created, right?

> It is a chance that some minor tweak is needed (For example add some "waitForElementToLoad" or "waitForPageToLoad" or something like that in the correct place?) .

Regarding this, I've already implemented "waitUntilElement" and "waitForPageToLoad" to generateNewKeysAndCert method in OIDCClientCredentialsForm class, but do you think is it not enough?

Just in case, I rebased but the test successful again.

**Comment by mposolda** [comment]
Thanks for the patience with this. Finally after few more re-runs, I can confirm there is no issue caused by this change. Still has some test failures, but those are not related to this PR:
https://keycloak-jenkins.com/job/universal-test-pipeline-server/448/
https://keycloak-jenkins.com/job/universal-test-pipeline-server/452/

**Review by mposolda — APPROVED** [review]

**Comment by y-tabata** [comment]
@mposolda Thanks!

**Pull request merged**
