### PR TITLE
KEYCLOAK-13163 Fixed searching for user with fine-grained permissions

### PR DESCRIPTION
**Pull request by sschu**
Fixes https://issues.redhat.com/browse/KEYCLOAK-13163.

### CODE REVIEW

**Comment by pedroigor** [comment]
@sschu Please, take a look at https://github.com/pedroigor/keycloak/tree/KEYCLOAK-13163. Tests are failing.

Your change will break clients querying by either the username, email, first or last names. The changes I'm proposing makes the target method at the `JpaUserProvider` (which does the group filtering) behave like the method you are no longer calling from `UsersResource`.

**Review by pedroigor — CHANGES_REQUESTED** [review]
See comments.

**Comment by pedroigor** [comment]
@sschu Could you please remove changes related to code format before sending your test changes?

**Comment by sschu** [comment]
I did. It was a bit more involved as other UserProviders were affected as well. Tests are green on my machine, hopefully Travis agrees.

**Comment by pedroigor** [comment]
@sschu LGTM, but a test is missing. Could you write one?

**Comment by sschu** [comment]
> 
> 
> @sschu LGTM, but a test is missing. Could you write one?

I added another test exactly capturing my scenario, the first page of 20 users would have been empty with the old code as they would be removed by fine-grained permissions and now the first 20 viewable users are returned correctly.

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
