### PR TITLE
KEYCLOAK-18597 Product distribution ZIP does not include rh-sso-7.5 folder

### PR DESCRIPTION
**Pull request by pskopek**
https://issues.redhat.com/browse/KEYCLOAK-18597

### CODE REVIEW

**Review by miquelsi — APPROVED** [review]
Changes tested and working as expected. Thanks @pskopek!

**Comment by drichtarik** [comment]
When I ran a product build a `keycloak-15.0.0-SNAPSHOT.zip` file was created and `rh-sso-15.0.0-SNAPSHOT` was created in distribution/server-dist/target directory. After unzipping the zip file it's correctly named `rh-sso-15.0.0-SNAPSHOT`. Is the zip intended to be named keycloak even though it contains an rh-sso named dist?

**Comment by miquelsi** [comment]
Yes, I think that is correct @drichtarik

**Comment by pskopek** [comment]
@drichtarik as per our discussion. Product profile has to be activated using -Dproduct.

**Comment by drichtarik** [comment]
Yes. I ran the build using -Product which delivers a different result. An incorrect one. PNC build, using -Dproduct flag, was correct.

**Review by drichtarik — APPROVED** [review]

**Pull request merged**
