### PR TITLE
Align RestEasy version with Quarkus

### LINKED ISSUE #29351: RestEasy version is not aligned to the one used by Quarkus
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dependencies

### Describe the bug

Quarkus 3.2.12.Final depends on RestEasy 6.2.7.Final. 
pom.xml refers for older version of RestEasy (6.2.4.Final). 
This causes further artifacts misalignment when building in restricted environment. 

### Version

22.0.10

### Regression

- [ ] The issue is a regression

### Expected behavior

Maven build of project that depends on org.keycloak:keycloak-admin-client:jar has to finish with success.

### Actual behavior

Customers cannot build their applications based on keycloak dependencies in their restricted environments.

### How to Reproduce?

Maven build of project that depends on org.keycloak:keycloak-admin-client:jar has to finish with success.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pskopek**
Closes #29351

### CODE REVIEW

**Review by vmuzikar — APPROVED** [review]
Thank you for the fix. LGTM.

**Comment by pskopek** [comment]
Changes in UncaughtErrorPageTest are due to change released since ReastEasy 6.2.5.Final related to [RESTEASY-3380](https://issues.redhat.com/browse/RESTEASY-3380).

See: https://github.com/jamezp/resteasy/blob/638b5270f275b6dc0f58b5d82a53fb4bfbef8eb7/providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/JsonProcessingExceptionMapper.java#L38

**Review by shawkins — APPROVED** [review]
> Changes in UncaughtErrorPageTest are due to change released since ReastEasy 6.2.5.Final related to [RESTEASY-3380](https://issues.redhat.com/browse/RESTEASY-3380).
> 
> See: https://github.com/jamezp/resteasy/blob/638b5270f275b6dc0f58b5d82a53fb4bfbef8eb7/providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/JsonProcessingExceptionMapper.java#L38

@pskopek @vmuzikar I don't follow why the response code was switched from 400 to 500 upstream. With resteasy reactive on 24 / main these remain 400 errors - presumably it's the clients fault for sending invalid json.

However that's probably not enough of a concern to hold this up.

**Review by mposolda — APPROVED** [review]
@pskopek @shawkins @vmuzikar Thanks for the update and review!

**Pull request merged**
