### PR TITLE
Set JVM FlightRecorderOptions to capture full stacks depth 

### LINKED ISSUE #23508: Set JVM FlightRecorderOptions to capture full stacks depth
### Description

When using Keycloak with Java Flight Recorder, the stack traces generated will only be meaningful if the stack depth is set to a higher number than default. In tests, 512 was enough for this.

Update both `kc.sh` and `kc.bat` to override the default option.

It relates to https://github.com/keycloak/keycloak-benchmark/issues/519

### PR DESCRIPTION
**Pull request by vramik**
Closes https://github.com/keycloak/keycloak/issues/23508

### CODE REVIEW

**Comment by vmuzikar** [comment]
@vramik Thanks for the PR!
We should also update kc.bat.

**Comment by ahus1** [comment]
@vramik - could you please open a new issue in Keycloak's main repository for this as the issue in KCB is too broad to be linked here, and wouldn't be closed by just this one issue. 

The new issue in the Keycloak main repository should capture only the rationale for this change. The issue in the Keycloak main repository should link to the KCB project.

**Comment by ahus1** [comment]
@vramik - and the of the commit/issue should be instead of "Add JVM FlightRecorderOptions by default to match Keycloak configuration [in helm charts]" be rather "Set JVM FlightRecorderOptions to capture full stacks depth"

**Review by ahus1 — APPROVED** [review]
Thank you for the contribution. I see that @vmuzikar's comment was also addressed, so I'm approving and merging it.

**Pull request merged**
