### PR TITLE
KEYCLOAK-9167 Using kcadm to update an identity-provider instance via…

### PR DESCRIPTION
**Pull request by vramik**
… a json file does not work without an "internalId" present in the json

### CODE REVIEW

**Comment by vramik** [comment]
@keycloak-ci-bot test

**Review by mposolda — DISMISSED** [review]

**Comment by pdrozd** [comment]
@keycloak-ci-bot test

**Comment by pdrozd** [comment]
@keycloak-ci-bot test

**Comment by pdrozd** [comment]
@keycloak-ci-bot test

**Comment by vramik** [comment]
@keycloak-ci-bot test

**Review by mposolda — APPROVED** [review]

**Review by pdrozd — APPROVED** [review]

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
Need separate PR for 4.8.x branch

**Comment by vramik** [comment]
@stianst I have the PR to 4.8.x prepared. I'm just waiting for merging this one (to be able to specify the commit)

**Pull request merged**
