### PR TITLE
Fix for User status shows as "-" when user is enabled

### LINKED ISSUE #24470: User status shows as "-" when user is enabled
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

User status is showing in the user data table as "-" when the user is enabled, leading to some confusion in the actual status of the user

### Version

Nightly

### Expected behavior

User status should show something more informative like "Enabled" 

### Actual behavior

Status shows as "-"

### How to Reproduce?

Navigate to user table in keycloak admin UI

### Anything else?

Appears to be an issue with this section of code in UserDataTable component: 

```
const StatusRow = (user: BruteUser) => {
    return (
      <>
        {!user.enabled && (
          <Label key={user.id} color="red" icon={<InfoCircleIcon />}>
            {t("disabled")}
          </Label>
        )}
        {user.bruteForceStatus?.disabled && (
          <Label key={user.id} color="orange" icon={<WarningTriangleIcon />}>
            {t("temporaryLocked")}
          </Label>
        )}
        {user.enabled && !user.bruteForceStatus?.disabled && "—"}
      </>
    );
  };
```

### PR DESCRIPTION
**Pull request by kaustubh-rh**
Closes #24470

### CODE REVIEW

**Review by edewit — DISMISSED** [review]
@xianli123 what do you think about this?

**Comment by ssilvert** [comment]
Showing most users as "Enabled" is going to be kind of ugly.  Perhaps status column was originally meant for any unusual status?  I think it makes sense to keep using the dash or show nothing at all for enabled users.  We will wait for @xianli123 opinion.

**Comment by xianli123** [comment]
Hi @kaustubh-rh @ssilvert @edewit I left a comment in the original issue #24470. I have 2 ideas to update it.

1. Change the label to the switch.

> image

2. Move the label next to the user name.

> image

In my opinion, it's better to change the label to the switch. In this way, users can directly switch users' status in the table. I am open for any thoughts. What do you think?

**Comment by xianli123** [comment]
Sorry for missing the status "Temporarily locked". @edewit  and I looked through the solutions. 

The better solution could be removing the Status column and putting the label next to the **User name**. We just show the abnormal status. If the user is enabled, we don't show the **Enabled** label as the first user shows in the screenshot below. Does it make sense?

Screenshot 2023-11-10 at 16 29 31

**Review by jonkoops — CHANGES_REQUESTED** [review]

**Review by jonkoops — APPROVED** [review]
Code changes look good to me. Not sure what the final call on the UX is here @xianli123

**Comment by ssilvert** [comment]
> Code changes look good to me. Not sure what the final call on the UX is here @xianli123

FWIW, I like the suggestion from @xianli123.

**Comment by stianst** [comment]
Could we get this PR updated to what @xianli123 is proposing? I agree that would be nicer

**Comment by ssilvert** [comment]
@kaustubh-rh Can you fix the conflicts on this one?

Then we can try it out, remove it from draft status, and maybe get it merged soon.

**Comment by kaustubh-rh** [comment]
Hi @ssilvert @stianst  yes

**Comment by kaustubh-rh** [comment]
Hi @ssilvert @stianst , I will create a new PR for the same.

**Comment by ssilvert** [comment]
@kaustubh-rh OK.  Just make sure you link back to this old one.  I wouldn't want to lose track of the discussion.

**Pull request closed without merging**
