### PR TITLE
KEYCLOAK-11527 Change type of jboss-as-subsystem-test artifact to pom…

### PR DESCRIPTION
**Pull request by martin-kanis**
@vmuzikar @hmlnarik Please have a look when you have a minute. More info is in the Jira.

### CODE REVIEW

**Comment by vmuzikar** [comment]
@martin-kanis Could you please provide a link to successful build? Thanks!

**Comment by vmuzikar** [comment]
@martin-kanis Never mind. Found it in the JIRA.

**Review by vmuzikar — APPROVED** [review]
@martin-kanis Sorry for the delay. Looks good to me, thanks!

One last question. Does this mean we'll probably face similar issue in the future once jboss-as-subsystem have aligned upstream and downstream again?

**Comment by martin-kanis** [comment]
@vmuzikar Thanks for the review.

Hopefully not because upstream can't be bumped to newer version as there's no more development. Only potential changes are in downstream. This issue happened because we introduced a new dependency (jboss-as-subsystem-test) which strangely changed in downstream. (from jar type to pom type)

**Comment by martin-kanis** [comment]
@stianst Do you want to merge this to unblock "core" pipeline or you prefer to wait for Hynek?

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
