### PR TITLE
client-jwt authentication fails on Token Introspection Endpoint

### LINKED ISSUE #30599: client-jwt authentication fails on Token Introspection Endpoint
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

A client whose authentication method is `client-jwt` cannot access Keycloak's Token Introspection Endpoint.

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Token Introspeciton endopont returns a normal response.

### Actual behavior

Token Introspeciton endpoint returns the follwoing error:

```
2024-06-20 11:31:18 2024-06-20 02:31:18,406 ERROR [org.keycloak.services] (executor-thread-18) KC-SERVICES0025: Error when validating client assertion: java.lang.RuntimeException: Token audience doesn't match domain. Expected audiences are any of [https://as.keycloak-fapi.org/auth/realms/test, https://as.keycloak-fapi.org/auth/realms/test/protocol/openid-connect/token, https://as.keycloak-fapi.org/auth/realms/test/protocol/openid-connect/ext/par/request, https://as.keycloak-fapi.org/auth/realms/test/protocol/openid-connect/ext/ciba/auth] but audience from token is '[https://as.keycloak-fapi.org/auth/realms/test/protocol/openid-connect/token/introspect]'
2024-06-20 11:31:18     at org.keycloak.authentication.authenticators.client.JWTClientAuthenticator.authenticateClient(JWTClientAuthenticator.java:108)
...
```

### How to Reproduce?

1. prepare a client  whose authentication method is `client-jwt`.
2. the client receives an access token from Keycloak.
3. the client send a request to Token Introspeciton endpoint with parameters like client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&client_assertion=...

### Anything else?

The body of client_assertion is as follows:
```
{
  "exp": 1718850519,
  "iat": 1718850459,
  "iss": "resource-server",
  "jti": "8fde33a23066cdaa42ac07d28574aa50",
  "aud": "https://as.keycloak-fapi.org/auth/realms/test/protocol/openid-connect/token/introspect",
  "sub": "resource-server"
}
```
Keycloak check its audience claim and returns an error because Keycloak recognized the follwoing url as valid values:
```
https://as.keycloak-fapi.org/auth/realms/test
https://as.keycloak-fapi.org/auth/realms/test/protocol/openid-connect/token,
https://as.keycloak-fapi.org/auth/realms/test/protocol/openid-connect/ext/par/request,
https://as.keycloak-fapi.org/auth/realms/test/protocol/openid-connect/ext/ciba/auth
```
It should be as follows:
```
https://as.keycloak-fapi.org/auth/realms/test
https://as.keycloak-fapi.org/auth/realms/test/protocol/openid-connect/token,
https://as.keycloak-fapi.org/auth/realms/test/protocol/openid-connect/token/introspect,
https://as.keycloak-fapi.org/auth/realms/test/protocol/openid-connect/ext/par/request,
https://as.keycloak-fapi.org/auth/realms/test/protocol/openid-connect/ext/ciba/auth
```

### PR DESCRIPTION
**Pull request by tnorimat**
closes #30599

### CODE REVIEW

**Comment by tnorimat** [comment]
@mposolda Due to [the issue](https://github.com/keycloak/keycloak/issues/30599), OAuth SIG's automatic conformance test running environement does not work since keycloak 25 ([the issue](https://github.com/keycloak/kc-sig-fapi/issues/581)). the PR can resolve the  [the issue](https://github.com/keycloak/keycloak/issues/30599).

To make OAuth SIG's automatic conformance test running environment work for keycloak 25, coud you check the PR?

**Comment by tnorimat** [comment]
@mposolda All CI tests succeeded. Could you check the PR?

**Review by mposolda — APPROVED** [review]
@tnorimat Thanks!

**Comment by tnorimat** [comment]
@mposolda Thank you.
But the issue of the automatic conformance testing can be resolved by an alternative method ([the issue](https://github.com/keycloak/kc-sig-fapi/issues/581)).

**Pull request merged**
