### PR TITLE
KEYCLOAK-12183 Refactor login screens. Introduce try-another-way link…

### PR DESCRIPTION
**Pull request by mposolda**
…. Not show many credentials of same type in credential selector

### CODE REVIEW

**Comment by mposolda** [comment]
Document, which may be used to help with testing of this PR. Contains example scenarios etc: https://docs.google.com/document/d/1CzeupDtp0mTqizJx1Cm5DPHybwMURnE_-OLQDRnnID8/edit?folder=0AHId3drMGt2GUk9PVA#heading=h.osymnhnga2td

**Comment by Pepo48** [comment]
> Document, which may be used to help with testing of this PR. Contains example scenarios etc: https://docs.google.com/document/d/1CzeupDtp0mTqizJx1Cm5DPHybwMURnE_-OLQDRnnID8/edit?folder=0AHId3drMGt2GUk9PVA#heading=h.osymnhnga2td

Thank you @mposolda !

**Review by stianst — COMMENTED** [review]
LGTM - I didn't review the code though, just tried it out. Did find quite a few usability issues when looking at it, but I imagine a lot of them are already being planned, so might be better to review again when more things are ready?

**Comment by mposolda** [comment]
@stianst Thanks for the feedback. Yes, this PR contains mostly just "logic" and the functionality. There are separate tasks planned to apply the "nice" design and address some usability issues. More accurately:
KEYCLOAK-12426 Add username to the login form + icon to reset login 
KEYCLOAK-12469 Implement nice design to the screen with authentication mechanisms 
KEYCLOAK-12186 Improve the OTP login form - showing OTP credentials etc (this will mean also adding select cart for choosing OTP etc)
KEYCLOAK-12184 Remove BACK button from login forms

Do you mean something else regarding usability?

Last time, we discussed to rather send more smaller PRs rather than one big PR, which will address everything. Hence I was hoping that this one can be merged first and then the usability tasks can be addressed as a follow-up? Ideally with single PR per single usability thing.

**Review by pskopek — APPROVED** [review]
Looks fine to me. I had some issues with tests, but that was due to my local environment.

**Comment by mposolda** [comment]
@pskopek Thanks Peter!

@stianst Should I wait for your review as well? TBH this is currently blocking some other tasks (some of them are WiP already), so will be nice to have it asap and eventually improve later if there are some more concerns.

**Review by Pepo48 — APPROVED** [review]
Looks good to me too

**Comment by mposolda** [comment]
@Pepo48 Thanks!

**Pull request merged**
