### PR TITLE
Add lang attribute to html tag

### LINKED ISSUE #19965: Add `lang` attribute to HTML tag of UIs
### Description

See #17112 for more details.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by Miguel-Bento-Github**
Related to https://github.com/keycloak/keycloak/pull/17039, closes #19965

### CODE REVIEW

**Review by jonkoops — COMMENTED** [review]
Code changes look good, but I still need to test if the language tag is correctly rendered for all these pages.

**Review by jonkoops — CHANGES_REQUESTED** [review]
Looks like these changes are causing some issues, presumably because `currentLanguageTag` is not available in every template. @Miguel-Bento-Github could you take a look?

**Comment by jonkoops** [comment]
Closing this PR due to inactivity, I've logged #19965 so we can track this in the future because this is certainly a useful addition.

**Comment by Nefcanto** [comment]
We do need this. I'm discussing it here:

https://github.com/keycloak/keycloak/discussions/20483#discussioncomment-5979225

**Pull request closed without merging**
