### PR TITLE
[KEYCLOAK-10397] Update Red Hat logo in RH-SSO theme

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Comment by mposolda** [comment]
@abstractj Thanks Bruno for looking into this. BTV. There is also "logo-example" theme in the old keycloak-examples. That one is not big priority as examples are deprecated anyway and likely shouldn't block this PR. Just pointing it in case that you have time for look into it too.

**Comment by hmlnarik** [comment]
@ssilvert  / @vmuzikar Could you please review this PR?

**Review by ssilvert — DISMISSED** [review]

**Comment by abstractj** [comment]
@mposolda good catch, thank you. I just updated this PR based on your comments.

**Review by ssilvert — COMMENTED** [review]
Why were favicon.ico and log.png deleted from themes?  These are the new-logo files you wanted to add, right?

**Comment by abstractj** [comment]
@ssilvert not sure why GitHub shows like this, but if you look at https://raw.githubusercontent.com/keycloak/keycloak/33a651505d36b1a855ad53a597cc9817c892cd2a/themes/src/main/resources-product/theme/rh-sso/common/resources/img/favicon.ico, you may notice that they were not deleted, but just replaced.

One thing that I noticed when downloading the new favicon is the fact that the size now is 228x228 instead of 32x32. @ssilvert do you think would be better to just resize?

**Comment by ssilvert** [comment]
> One thing that I noticed when downloading the new favicon is the fact that the size now is 228x228 instead of 32x32. @ssilvert do you think would be better to just resize?

I don't know.

**Review by ssilvert — APPROVED** [review]

**Review by vmuzikar — CHANGES_REQUESTED** [review]
The favicon.ico doesn't match its extension - it's actually a PNG.
I'm not sure if PNG is already fully supported as a favicon in all browsers (incl. IE) - we used true ICO with the old logo. Anyway, if we stick to PNG, we should update our FTL templates as well with `type="image/png"`.

**Comment by abstractj** [comment]
@vmuzikar unfortunatelly PNG was the only format provided in the list of static assets. Answering your question, most of the browsers support it https://caniuse.com/#feat=link-icon-png

**Comment by vmuzikar** [comment]
@abstractj Ok, PNG it is then (even though iOS doesn't support it at all - which is kinda bad as it appears to be a company wide issue). Should we update the `link` tag with the correct `type` attribute?

**Comment by vmuzikar** [comment]
Also I think we should keep the original `.png` extension.

**Review by vmuzikar — APPROVED** [review]
Ok, turned out redhat.com website uses the same favicon (renamed PNG to ICO). And we can't be better than redhat.com. 😜 So I'm gonna approve.

If anyone's interested, this article sums up quite nicely the whole favicon complexity: https://css-tricks.com/favicon-quiz/

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
