### PR TITLE
KEYCLOAK-6573 No auto escaping 'totpStep1' message variable

### PR DESCRIPTION
**Pull request by frekele**
Added auto-escaping in 'totpStep1' message variable

### CODE REVIEW

**Comment by stianst** [comment]
Can you please explain why you want to do this? totpStep1 doesn't contain any HTML characters and as such can be escaped and left as it is today.

**Review by stianst — COMMENTED** [review]
Please explain the reason for this change

**Comment by frekele** [comment]
Hi @stianst 

See:

totpstep1

**Comment by stianst** [comment]
The problem there is that the Brazilian Portuguese message bundle hasn't been updated with the updates in the English message bundle. So if you can update the message bundle instead I can accept the PR.

**Comment by frekele** [comment]
hi @stianst ,

ok,I will make a PR for pt-BR.

Is it just here(https://github.com/keycloak/keycloak/tree/master/themes/src/main/resources-community), or should I look elsewhere for update?

**Comment by stianst** [comment]
That's the one

**Pull request closed without merging**
