### PR TITLE
Replace operation set wrong lifespan in remote infinispan database an…

### LINKED ISSUE #10755: Replace operation set wrong lifespan in remote infinispan database and leads to session eviction
### Describe the bug

Hi,

This discussion describes the bug and leads to fix it : https://github.com/keycloak/keycloak/discussions/10577 

**To sum up here :** new session lifespan gets corrupted in database (set in past) when trying to refresh it and session entry is evicted from Infinispan database

**Technical stack :** 
Keycloak 17.0.0 (legacy, wildfly) (will be migrated to Quarkus in a few months)
Infinispan 13.0.6.Final with JDBC persistence (PostgreSQL 14.X)

Number of nodes in cluster does not matter.

**Note** : this bug does not occur with a remote Infinispan cluster without JDBC persistence.

### Version

17.0.0

### Expected behavior

When a remote-store is configured pointing to an external Infinispan cluster with JDBC persistence, the following update must be done for the `timestamp `field in Infinispan database  : 

1. Create a new Session on App A. In database, new lifespan value (`timestamp`) is set to :  _now () + SSO Session Max configured in Realm_
2. Navigate to another app App B of same realm (or even same app A in another tab).  Lifespan value (`timestamp`) should be updated to : _now() + SSO Session Max configured in Realm_

### Actual behavior

1. Create a new Session on App A. In database, new lifespan value (timestamp) is set to :  _now () + SSO Session Max configured in Realm_
2. Navigate to another app App B of same realm (or even same app A in another tab).  Lifespan value (timestamp) is updated to : _Unix timestamp (01/01/1970 ) + SSO Session Max configured in Realm_
3. As a consequence, because this lifespan is in the past, User session is evicted quickly and user is logged out

### How to Reproduce?

Full example here : https://github.com/olivierboudet/keycloak-infinispan-jdbc 

### Anything else?

Lead from @thomasdarimont here : https://github.com/keycloak/keycloak/discussions/10577#discussioncomment-2333456

### PR DESCRIPTION
**Pull request by martin-kanis**
…d leads to session eviction

Fixes #10755

### CODE REVIEW

**Comment by martin-kanis** [comment]
@mposolda Hi, do know why we use -1 for a lifespan when we add an entry to the remote cache for the first time instead of actual lifespan which is calculated for the entry? This seems to be causing problems with `replace` operation which sets timestamp in the past in the DB.

**Comment by martin-kanis** [comment]
@daviddelannoy Would you have a chance to verify the fix please? I think we don't have a easy way to test it in our testsuite as it involves a remote Infinispan with a database.

**Comment by daviddelannoy** [comment]
I will try to see if we still have some test environment to test it, but not quite soon (not this month)
Because of this bug we dropped the external ISPN cluster with DB solution 8 months ago in favor of direct JDBC store from a distributed cache, which also required a small fix proposed before by @thomasdarimont involving the SKIP_CACHE_STORE flag.

As other few people were interested in a fix for this issue I will try to test it, thanks for the PR 😉👍

**Comment by thomasdarimont** [comment]
@martin-kanis thank you very much for your efforts! Your code change seems to do the trick. 

I just gave this a quick spin with my example setup: https://github.com/thomasdarimont/keycloak-project-example/tree/main/deployments/local/clusterx#run-keycloakx-cluster-with-database-backed-user-sessions
and I could verify that the timestamp calculations (discussed here https://github.com/keycloak/keycloak/discussions/10577) in the  string_table  used by  infinispan-cachestore-jdbc`  are now correct :dancers: 

However, I still needed to apply my fix for `org.keycloak.models.sessions.infinispan.CacheDecorators` to ignore `skipCacheStore` hints.

**Review by mposolda — APPROVED** [review]
@martin-kanis @thomasdarimont Thanks for the fix and for the testing with the fix applied.

TBH I don't recall the reasoning for using `-1` here. I don't see a problem with your change and hence I am approving this PR.

We can run cross-dc to doublecheck if there is a regression, but I don't know if it is possible to run cross-dc tests against `main` branch with the latest changes (removed Wildfly etc).

I am approving and leaving to you whether you want to run some more tests or whether you want also someone else approval for this PR.

**Comment by martin-kanis** [comment]
@thomasdarimont Thank you for the verification! 
@daviddelannoy @thomasdarimont Regarding the `skipCacheStore` flag. I would keep it in the separate issue https://github.com/keycloak/keycloak/issues/10803 which I plan to pick up soon :) This issue is about wrong lifespan in JDBC store which is present only with a remote Infinispan (`RemoteCacheInvoker` file).

**Comment by martin-kanis** [comment]
> @martin-kanis @thomasdarimont Thanks for the fix and for the testing with the fix applied.
> 
> TBH I don't recall the reasoning for using `-1` here. I don't see a problem with your change and hence I am approving this PR.
> 
> We can run cross-dc to doublecheck if there is a regression, but I don't know if it is possible to run cross-dc tests against `main` branch with the latest changes (removed Wildfly etc).
> 
> I am approving and leaving to you whether you want to run some more tests or whether you want also someone else approval for this PR.

Thank you Marek for the review. Yeah, it is not possible to run cross-dc test with current `main` as we removed all the Wildfly stuff. I can try to apply my patch to older Keycloak and let the cross-dc tests run on it.

**Comment by martin-kanis** [comment]
> Thank you Marek for the review. Yeah, it is not possible to run cross-dc test with current `main` as we removed all the Wildfly stuff. I can try to apply my patch to older Keycloak and let the cross-dc tests run on it.

At the end, GHA keycloak build was failing because of a node js issue so I run cross-dc locally on Keycloak 19 + this patch and tests passed.

**Comment by mposolda** [comment]
@martin-kanis Thanks for doublecheck with the tests. I am merging the PR then.

**Comment by thomasdarimont** [comment]
@martin-kanis another note: When using a database for cache storage, then we currently have to explicitly configure either a jdbc connection-pool or a datasource. It would be great if we could just reference the quarkus datasource somehow. Perhaps this could be implemented with a custom ` QuarkusDataSource` or a `QuarkusJdbcDriver` ... or implement a dummy JNDI lookup.

In my spring-boot-keycloak-server-example I use the later approach for exposing the Spring Boot datasource with a "interal" JNDI lookup to the Keycloak infrastructure.
See: https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server/blob/master/embedded-keycloak-server-spring-boot-support/src/main/java/com/github/thomasdarimont/keycloak/embedded/support/KeycloakInitialContext.java#L11
See: https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server/blob/96915013a024320f84f450a6571eac494e2c5892/embedded-keycloak-server-spring-boot-support/src/main/java/com/github/thomasdarimont/keycloak/embedded/support/DynamicJndiContextFactoryBuilder.java#L49

I think the same would work for quarkus keycloak without any modifications to infinispan.

**Pull request merged**
