### PR TITLE
Make optional the use of PKCE for Clients configured with PKCE only f…

### LINKED ISSUE #13244: Make optional the use of PKCE for Clients configured with PKCE only for Device Code Flow
### Description

We propose for Clients configured with PKCE to make optional the use of PKCE only for Device Code Flow. See motivation.

### Discussion

_No response_

### Motivation

Our team has made the PR for supporting PKCE in the Device  Authorization Flow in order to mitigate against interception attacks for devices supporting PKCE making it mandatory for PKCE configured clients. However, PKCE is designed and mainly is used in auth code flow. Some of our Clients use PKCE both for auth code flow and Device  Authorization Flow , others clients use PKCE only for auth code flow. 

### Details

_No response_

### PR DESCRIPTION
**Pull request by cgeorgilakis**
…or Device Code Flow

Closes #13244

### CODE REVIEW

**Comment by mposolda** [comment]
@cgeorgilakis I am not sure about this approach as there can be cases, when people use Device Flow and want to enforce that PKCE is really used in the device flow.

I wonder about using of client policies for this to have better flexibility? Current client policies already have the executor to enforce PKCE. So it should be possible to have the client policy, with the condition triggered only in "auth code flow" or "par", but not during "device flow" . So the enforcing of PKCE will be done by this policy. If there is no condition for the "flow type", it may be good to add such condition implementation IMO to handle the use-case like this.

@tnorimat WDYT about this

**Comment by tnorimat** [comment]
Hello @cgeorgilakis , @mposolda ,

I also think that it might be good to use client policies instead of modifying keycloak's body codes. One of the goal of introducing client policies to add logics without modifying keycloak's body codes that may affect other functionalities.

Client policies are called when keycloak receives an authz request and a token request of device grant:

https://github.com/keycloak/keycloak/blob/0eb10f2128cba95692147b89aeac98b7a310f82a/services/src/main/java/org/keycloak/protocol/oidc/grants/device/endpoints/DeviceEndpoint.java#L149

https://github.com/keycloak/keycloak/blob/0eb10f2128cba95692147b89aeac98b7a310f82a/services/src/main/java/org/keycloak/protocol/oidc/grants/device/DeviceGrantType.java#L322

For example, creating a class `DeviceGrantPKCEEnforcerExecutor` extending `PKCEEnforcerExecutor` and overriding methods `executeOnEvent`, `executeOnAuthorizationRequest`, and `executeOnTokenRequest`.

WDYT?

**Comment by mposolda** [comment]
@tnorimat @cgeorgilakis Thanks for the insight Takashi. To me, it will be good to deprecate/remove the client option "Proof Key for Code Exchange Code Challenge Method" and instead rely as much as possible on the client policies.

Regarding the `PKCEEnforcerExecutor`, my vote is to extend directly this executor to support also other type of flows (Device Flow, PAR etc) instead of supporting only authorization code flow like it is today. To address the use-case by @cgeorgilakis, we can possibly introduce the "Flow Condition", which will allow to filter based on the flow? For example you will select in which flows the condition should evaluate to true (Authorization Code, PAR, Device Flow, Client Credentials etc). IMO this will allow better flexibility and re-usability instead of introducing `DeviceGrantPKCEEnforcerExecutor` .

Out of curiosity, if I understand correctly, the use-case by @cgeorgilakis can be already supported with using of current client policies? For example if you use client policy with the `Any client` condition and with the `PKCE Enforcer Executor` instead of using the `Proof Key for Code Exchange Code Challenge Method` on the client, then the PKCE will be enforced just in the authorization code flow. It won't be executed during device flow. That is because `PKCEEnforcerExecutor` currently supports only Authorization Code grant as Takashi mentioned above. Could you try to test this setup?

**Comment by cgeorgilakis** [comment]
We want PKCE for requests of authz code grant. Thanks for your help. It works with PKCEEnforcerExecutor.
The only problem that I see is that PKCEEnforcerExecutor enforces S256 for authorization request and that you can not exclude other PKCE from executed for authz code grant. Although S256 is more commonly used ( and best practice), plain text also is used.
So my proposal for PKCEEnforcerExecutor are:
- Remove obligatory S256 for authorization request 
- Add option for control specific challenge method
- Add multiselection method for execution (by default only authz code grant) 

Generaly, @mposolda I agree with your proposal. We need to think migration plan after client field removal. We now have to change many clients configuration!

**Comment by mposolda** [comment]
@cgeorgilakis +1 to add the option to `PKCEEnforcerExecutor` for the challenge method. It will be good to make sure that S256 is the default one and also the FAPI profiles should have the `S256` option selected as FAPI explicitly allows only S256 and that's how it works right now.

Regarding the multiselection, I would use the separate condition implementation rather than multiselection method directly on the executor. Condition has more flexibility as it would allow to be used with various executors. In general, client policies have executors to specify `what` should be executed and conditions to specify `when` should it be executed, so conceptually condition will likely matches better with this use-case.

**Comment by cgeorgilakis** [comment]
I close the PR because as we discussed PKCEEnforcerExecutor need to be extended.

**Pull request closed without merging**
