### PR TITLE
Move saml documentation to guides

### LINKED ISSUE #31330: Convert chapter 3: Using SAML to secure applications and services

### PR DESCRIPTION
**Pull request by rmartinc**
Closes #31330

Moving the SAML securing applications documentation to guides. The idea is the following:

* All relevant chapters have been moved from documentation to guides.
* The detailed configuration for the `keycloak-saml.xml` file is moved to separate guide but is hidden (there is a link in the default saml guide, configuration chapter, to it, but there is no box for it in the guides).
* The external guides that currently are placed in `keycloak-web` are also moved to the guides `securing-apps` folder.
* The `keycloak-web` also needs a little PR to generate the `securing-apps` guides correctly: https://github.com/rmartinc/keycloak-web/tree/issue-31330

In order to tests this just compile the keycloak fully and then in the `keycloak-web` use my branch and compile using the 999 version (`mvn clean install -Dversion.keycloak=999.0.0-SNAPSHOT`).

Draft for the moment. @mposolda @pskopek WDYT?

### CODE REVIEW

**Review by jonkoops — DISMISSED** [review]
I can't comment on some of the specifics, but code-wise and logically this all looks good to me.

**Comment by mposolda** [comment]
@rmartinc Looks great to me, Thanks! Just for the reference, adding screenshot on how the corresponding part of the web page looks like (Link to SAML Galleon points to the SAML adapter documentation in the "Guides" format):

Screenshot from 2024-07-22 14-48-50

@stianst What do you think?

**Review by mposolda — APPROVED** [review]

**Review by jonkoops — APPROVED** [review]

**Comment by rmartinc** [comment]
I have also sent the PR for web: https://github.com/keycloak/keycloak-web/pull/478. It's a draft until we decided about this.

**Comment by mposolda** [comment]
@rmartinc Thanks!

Discussed with @stianst and he is fine with the approach of moving this way.

**Pull request merged**
