### PR TITLE
Add timeout option for updateToken in the js adapter

### LINKED ISSUE #25: Javascript adapter: updateToken timeout configuration
### Description

It should be possible to specify a timeout, say 2 minutes, for the `updateToken` HTTP request. Currently if the HTTP request is stuck as "Pending", Keycloak will be stuck and can't refresh the token anymore (due to how the updateToken method is implemented).

### Discussion

_No response_

### Motivation

If the HTTP request is stuck, Keycloak JavaScript adapter can't update the token anymore even with repeated updateToken requests.

### Details

This could be specified as an option when constructing Keycloak. Alternatively (less ideal in my opinion), as a parameter to `updateToken` method.

The timeout is simple to implement with https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout.

### LINKED ISSUE #10514: Javascript adapter: updateToken timeout configuration
### Description

It should be possible to specify a timeout, say 2 minutes, for the `updateToken` HTTP request. Currently if the HTTP request is stuck as "Pending", Keycloak will be stuck and can't refresh the token anymore (due to how the updateToken method is implemented).

### Discussion

_No response_

### Motivation

If the HTTP request is stuck, Keycloak JavaScript adapter can't update the token anymore even with repeated updateToken requests.

### Details

This could be specified as an option when constructing Keycloak. Alternatively (less ideal in my opinion), as a parameter to `updateToken` method.

The timeout is simple to implement with https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout.

### PR DESCRIPTION
**Pull request by panuhorsmalahti**
Closes keycloak/keycloak-js#25

I'll make a PR to the documentation repo once this change is approved.

### CODE REVIEW

**Comment by panuhorsmalahti** [comment]
Should create a PR to add documentation?

**Review by jonkoops — CHANGES_REQUESTED** [review]
Please also update the TypeScript definitions for this option with some documentation.

**Comment by jonkoops** [comment]
@panuhorsmalahti Are you still interested in landing this change?

**Review by jonkoops — APPROVED** [review]

**Review by abstractj — COMMENTED** [review]
I'd also suggest including tests for this new option. You can find some examples here: https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java

**Comment by jonkoops** [comment]
@panuhorsmalahti could you rebase your PR on `main`? We've made some changes to the directory structure so the adapter is now located in `js/libs/keycloak-js`. Also, the Keycloak documentation has now been moved into this repository so those changes can also be included here.

**Comment by jonkoops** [comment]
I am closing this PR as we first want to do a refactor of Keycloak JS itself, which will not be happening soon-ish. This is definitely a useful addition that we want to land, but the bandwidth isn't there at the moment.

I am keeping the issue around so we can get back to this change when we are in a better condition.

**Pull request closed without merging**
