### PR TITLE
Handle current time in seconds as long

### LINKED ISSUE #11053: Handle current time in seconds as long in Keycloak
### Description

Keycloak has several places where it handles the current time and the expiration time as an integer. This prevents a current time after 2038, and also expiry dates after 2038. 

Some methods in JsonWebToken are deprecated as they return an integer, but they are still used in lots of places. Currently Time.currentTime() still returns an integer. 

### Discussion

_No response_

### Motivation

Allow token expiry longer than 2038. Clean up deprecated methods.

### Details

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
This avoids the overflow of the integer in 2038. Old getXXX methods remain for now as they provide null-safe access to the values.

Closes #11053

### CODE REVIEW

**Comment by ahus1** [comment]
@hmlnarik / @stianst - I've prepared this (draft) PR to handle seconds as long.

After the change I was able to start Keycloak locally and log in. Test on CI are still running. 

I'd be happy if you could comment if this PR is going into the right direction. There are also 4 DB columns that will be enhanced from INT to BIGINT.

**Comment by ahus1** [comment]
This is now ready for review. I reviewed the Cross-DC-Tests, and they seem to be unstable. I didn't find a related exception, only some Infinispan locking exceptions. The operator fails due to #11642 and builds locally just fine. 

There are some changes in [AuthenticationSessionEntity.java](https://github.com/keycloak/keycloak/pull/11611/files#diff-ba12bd74b5f2d04471c6e7de13f9f6ddaaf2adc3cd562b77d27ecbfa3267438a) where I add a new serialization version as the old contained a Integer, and the new contains a Long. A short feedback if that was really necessary would be nice.

**Comment by ahus1** [comment]
Closing this PR as priorities are with the new store.

**Comment by tsaarni** [comment]
Would this PR be valid now again (if rebased) as the new storage got dropped?

**Pull request closed without merging**
