### PR TITLE
Feature to filter Login Events by IP Address

### LINKED ISSUE #19289: Feature to filter Login Events by IP Address as already exists in the Admin Events filter option
### Description

In the Events -> Admin Events tab -> Filter button, we have the option to search using the IP Address. It would be great to have the same option as a filter to the Login Events tab.

### Discussion

https://github.com/keycloak/keycloak/discussions/19288

### Motivation

Filter the Login Events using the IP Address.

### Details

Add the input to search by IP Address and apply the value to query of Login Events.

### PR DESCRIPTION
**Pull request by gabrielpadilh4**
Closes https://github.com/keycloak/keycloak/issues/19289

Feature to filter Login Events by IP Address in the Login Events tab.

### CODE REVIEW

**Comment by gabrielpadilh4** [comment]
Hello @pedro-hos this is the PR with the commit squash.

Could you please review ?

Thank you.

**Comment by pedro-hos** [comment]
@gabrielpadilh4 LGTM, but I would like to ask to @stianst or someone from admin console take a look =D

**Comment by gabrielpadilh4** [comment]
Nice @pedro-hos thank you!

**Review by edewit — DISMISSED** [review]

**Comment by gabrielpadilh4** [comment]
Hello @edewit, i notice that some checks are failing.

Could you please review ?

**Comment by gabrielpadilh4** [comment]
@edewit i forgot to commit one change. Now it is okay.

Thank you.

**Review by edewit — DISMISSED** [review]

**Review by jonkoops — DISMISSED** [review]

**Comment by jonkoops** [comment]
@gabrielpadilh4 can you fix the linting issues in your code?

**Comment by gabrielpadilh4** [comment]
Hello @jonkoops i try to fix the lint, could you approve please ?

**Review by jonkoops — DISMISSED** [review]

**Comment by jonkoops** [comment]
@gabrielpadilh4  the CI is still showing me linting errors

**Review by jonkoops — APPROVED** [review]

**Pull request merged**
