### PR TITLE
KEYCLOAK-3300 Add support for jetty in spring-boot-adapter

### PR DESCRIPTION
**Pull request by thomasdarimont**
This adds support for using Jetty together with the Keycloak
spring-boot-adapter. Sadly the KeycloakSpringBootProperties.SecurityCollection
definition is mostly inspired by Tomcats SecurityConstraint/SecurityCollection
which doesn't provide a good fit for jettys structures.
In cases where jetty only allows one setting, we use the first value.

### CODE REVIEW

**Comment by foo4u** [comment]
We should really base the Spring Boot adapter on the Spring Security adapter just making it an alternative configuration option.

**Comment by thomasdarimont** [comment]
Hi @foo4u,

yes that would be nice - would you mind opening a JIRA issue for this?
Perhaps this can be done for 2.1.x ?

Cheers,
Thomas

**Comment by thomasdarimont** [comment]
I updated the PR and prepared it for merging. I also implemented the Undertow support for the 
[Keycloak Spring Boot Adapter](https://github.com/thomasdarimont/keycloak/commit/81d660abf216f74d5d8dacf77bc7bb4c17f20ef2) based on the code from this PR.
Once this PR is merged I sent another one for the Undertow support.

Cheers,
Thomas

**Comment by thomasdarimont** [comment]
Just rebased on (current) master

**Comment by stianst** [comment]
Does this not result in requiring Jetty dependencies when deployed to Tomcat?

**Comment by thomasdarimont** [comment]
No, the maven dependencies with scope `provided` are only on the classpath for compilation of the spring-boot-adapter module. Further more the KeycloakSpringBootConfiguration class has been carefully designed to not cause classloading problems due to missing classes.

In the consumer side one has to declare the dependencies to undertow, tomcat or jetty which is usually done via spring-boot's starters like (spring-boot-starter-tomcat (default), spring-boot-starter-jetty and spring-boot-starter-undertow).

As an example the configuration to use the keycloak-spring-boot-adapter with jetty looks like the following:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>de.tdlabs.dev</groupId>
	<artifactId>keycloak-example-spring-boot-adapter-jetty</artifactId>
	<version>1.0.0.BUILD-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>keycloak-dev-spring-boot-adapter-jetty</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.6.RELEASE</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<keycloak.version>2.1.0-SNAPSHOT</keycloak.version>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-spring-boot-adapter</artifactId>
			<version>${keycloak.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jetty</artifactId>
			<scope>provided</scope>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-jetty92-adapter</artifactId>
			<version>${keycloak.version}</version>
			<scope>provided</scope>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
```

The resulting fat jar does not contain any tomcat-embedded jars (with the exception of tomcat-el which is required by the spring-validation module).

**Pull request merged**
