### PR TITLE
KEYCLOAK-12690 Upgrade to liquibase 3.8.6

### PR DESCRIPTION
**Pull request by martin-kanis**

### CODE REVIEW

**Review by vramik — CHANGES_REQUESTED** [review]
@martin-kanis thank you for the PR. All supported databases works fine except MSSQL.

I get 
`10:52:53,150 INFO  [org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider] (ServerService Thread Pool -- 68) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
10:52:54,052 ERROR [org.keycloak.connections.jpa.updater.liquibase.conn.DefaultLiquibaseConnectionProvider] (ServerService Thread Pool -- 68) Change Set META-INF/jpa-changelog-1.3.0.xml::1.3.0::bburke@redhat.com failed.  Error: Incorrect syntax near '('. [Failed SQL: (102) CREATE TABLE ADMIN_EVENT_ENTITY (ID varchar(36) NOT NULL, ADMIN_EVENT_TIME bigint, REALM_ID varchar(255), OPERATION_TYPE varchar(255), AUTH_REALM_ID varchar(255), AUTH_CLIENT_ID varchar(255), AUTH_USER_ID varchar(255), IP_ADDRESS varchar(255), RESOURCE_PATH varchar(2550), REPRESENTATION varchar (max) (25500), ERROR varchar(255))]
10:52:54,060 FATAL [org.keycloak.services] (ServerService Thread Pool -- 68) java.lang.RuntimeException: Failed to update database`

during server startup.

It is reproducible both locally and in pipeline.

- `mvn install:install-file -Dfile=/path/to/mssql-jdbc-7.4.1.jre8.jar -DgroupId=test.jdbc.eap7 -DartifactId=mssql2017 -Dversion=EAP_7.3.0 -Dpackaging=jar`
- `mvn -f keycloak/testsuite/integration-arquillian/pom.xml -Djdbc.mvn.groupId=test.jdbc.eap7 -Djdbc.mvn.artifactId=mssql2017 -Djdbc.mvn.version=EAP_7.3.0 -Pjpa,auth-server-wildfly,db-mssql2017 clean install`

**Comment by dteleguin** [comment]
Liquibase 3.8.7 is out; one of the highlights is that `Liquibase` is now auto-closeable.

Liquibase is known not to close DB connection automatically. In Keycloak, the connection gets closed anyway (via GC I guess) somewhere around Hibernate EMF initialization. We can make it happen earlier with the help of try-with-resources.

Please see this [discussion](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Agroal.20JDBC.20Resources.20Leaked/near/189305073) for more.

**Comment by martin-kanis** [comment]
@dteleguin Thank you for suggestion. We can't see the auto-closeable improvement in the 3.8.7 changelog.  Maybe it was added in one of the previous versions? In either way our release is pretty close and I am afraid we can't manage to include the improvement right now. Can you create a Jira please, so we can add it later?

**Comment by dteleguin** [comment]
> @dteleguin Thank you for suggestion. We can't see the auto-closeable improvement in the 3.8.7 changelog. Maybe it was added in one of the previous versions?

Just double checked - this happened in 3.8.7 exactly ([commit](https://github.com/liquibase/liquibase/commit/5fa1026fa000a1aabf86a16a8a22e2082c119a24)), probably the authors just decided not to mention it in the changelog.

> In either way our release is pretty close and I am afraid we can't manage to include the improvement right now. Can you create a Jira please, so we can add it later?

Done: https://issues.redhat.com/browse/KEYCLOAK-13242

**Comment by martin-kanis** [comment]
Thanks. However we hit a blocker for this upgrade and we need to close it for now. See the Jira for more info.

**Pull request closed without merging**
