### PR TITLE
KEYCLOAK-19283 Implemented new "Advanced claim to group" idp mapper

### PR DESCRIPTION
**Pull request by artur-baltabayev**
This PR implements a new IdP mapper called "Advanced claim to group" mapper, which functions similar to the "Advanced claim to role" mapper. Instead of assigning a role to the user, the new mapper assigns the selected group to the user (if the chosen claims are present). UI changes to the Admin Console alongside integration tests are also implemented here.

You can find the Jira issue here: https://issues.redhat.com/browse/KEYCLOAK-19283

### CODE REVIEW

**Comment by stianst** [comment]
@mposolda do you have a chance to review this PR?

**Review by mposolda — APPROVED** [review]
@artur-baltabayev Thanks for the PR! The PR looks good to me. I will merge it after Keycloak 16 release (We are very close to the Keycloak 16 release and don't include new features to avoid the potential regression right before the release)

**Comment by mposolda** [comment]
@artur-baltabayev I will also need to run admin console tests in our pipeline to doublecheck there is no regression here. So temporarily un-approving it until the admin console tests are checked.

**Review by mposolda — COMMENTED** [review]
Foo

**Review by mposolda — CHANGES_REQUESTED** [review]
Foo

**Comment by mposolda** [comment]
@artur-baltabayev Could you please rebase this on top of latest Keycloak "main" branch?

**Comment by artur-baltabayev** [comment]
@mposolda Hello Marek, thank you a lot for your time ! I rebased the branch and will try to run the admin console tests locally. I don't know how it will work out though since i didn't do this before.

**Comment by artur-baltabayev** [comment]
I tried running the tests after the rebase and they were not quite successful. However i don't think that my changes are related. The following tests failed :
- ClientSettingsTest.alwaysDisplayInAccountConsole:123 >> ElementClickIntercepted
- ClientsTest.clientsNavigationTest:114 >> NoSuchElement Unable to locate element ...

**Review by mposolda — APPROVED** [review]
@artur-baltabayev Thanks for the doublecheck!

**Comment by bergner** [comment]
@artur-baltabayev  is this MR enabling group mapping for both SAML and OIDC, or only OIDC IdPs? If only OIDC do you have an idea on what would be needed for this to work for SAML identity providers as well?

I've been trying to figure out how Keycloak group mapping worked for SAML recently and after running out of ideas I asked a question on the forums  https://keycloak.discourse.group/t/map-groups-from-saml-idp-into-keycloak/12266 but based on my findings and stumbling on this MR the answer probably is that so far no such mapping capability has existed.

**Comment by artur-baltabayev** [comment]
@bergner This mapper only works for OIDC. I didn't investigate mapping functionality for SAML so sadly i cannot give a good answer on Keycloak's capabilities here.

To make the mapper work with SAML, it would have to be reimplemented for that protocol specifically, as the current implementation is based on OIDC specific logic.

**Pull request merged**
