### PR TITLE
Add conditional step to GHA for testing jpa-map storage with postgres

### LINKED ISSUE #12046: Add conditional step to GHA for testing jpa-map storage with postgres
There should be added new step to GHA for testing `jpa-map-storage` with postgres. There is similar step for hotrod already.

### PR DESCRIPTION
**Pull request by vramik**
Closes #12046

### CODE REVIEW

**Comment by vramik** [comment]
Depends on https://github.com/keycloak/keycloak/pull/12089

**Comment by vramik** [comment]
There are test failures in base testsuite. Tracked as https://github.com/keycloak/keycloak/issues/12118

**Review by sguilhen — APPROVED** [review]
I'm not a CI expert but this change looks good to me when compared to the hotrod tasks

**Review by hmlnarik — APPROVED** [review]
Approving per @sguilhen 's approval

**Pull request merged**
