### PR TITLE
Fix user-facing typos in Java code

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
This includes documentation and user-visible messages, but excludes log messages.

This is a follow-up to #28890. This is currently an incomplete draft, I want to make sure I have got "only user-facing content excluding log messages" right.

### CODE REVIEW

**Comment by ahus1** [comment]
@DimitriPapadopoulos - some of the tests fail as they test for error messages in the responses. 
I'd prefer (but not require you) to split this PR into two parts: One that changes JavaDoc only, and another one that changes error messages which then would require also changes to the tests.

**Review by thomasdarimont — APPROVED** [review]
LGTM. Thanks for your contribution! Error messages in tests need to be aligned, of course.

**Comment by DimitriPapadopoulos** [comment]
I have modified this pull request to include only fixes in Javadoc.

Changes to error messages will follow in a distinct merge request.

**Review by ahus1 — APPROVED** [review]

**Comment by ahus1** [comment]
Thank you for this PR, @DimitriPapadopoulos. Once you start changing Java code, please open a GitHub issue first and then link it to the PR as outlined in the CONTRIBUTING.md guide.

**Pull request merged**
