### PR TITLE
Wrong Welcome page image in the documentation

### LINKED ISSUE #27719: Wrong Welcome page image in the documentation
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

Documentation contains the old welcome page. 

Old:
 The documentation

### Version

999

### Regression

- [ ] The issue is a regression

### Expected behavior

Contains new Welcome page screen

### Actual behavior

Contains old Welcome page screen

### How to Reproduce?

See https://www.keycloak.org/docs/latest/server_admin/index.html#creating-the-account-on-the-local-host

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
Fixes #27719

I've noticed the documentation contains the old welcome page. 

@jonkoops Could you please review it?

Old:
 

New (EDIT: removed the LastPass):

### CODE REVIEW

**Comment by mabartos** [comment]
@jonkoops It'd also be good to unify the forms with regard to the used font, paddings...

Login page:
login-page

Welcome page:
initial-welcome-page

**Review by jonkoops — CHANGES_REQUESTED** [review]
Can you disable LastPass so that we get a clean screenshot?

**Comment by mabartos** [comment]
@jonkoops Oh shoot, totally missed it.

**Comment by mabartos** [comment]
@jonkoops Fixed now

**Review by jonkoops — APPROVED** [review]
LGTM

**Review by ahus1 — CHANGES_REQUESTED** [review]
This needs to be updated in the KC24 RHBK docs as well, so it need to be backport. 

To be able to track the backport, it needs an issue. 

Please create an issue with the backport tag, and then it will be read to be merged. 

I can add the issue number to the commit when I squash it via the UI, so no need to rebuilt it.

**Comment by mabartos** [comment]
@ahus1 You're right.

Issue: https://github.com/keycloak/keycloak/issues/27719
Backport PR: https://github.com/keycloak/keycloak/pull/27720

**Review by ahus1 — APPROVED** [review]

**Comment by ahus1** [comment]
Thank you for this PR and the backport!

**Pull request merged**
