### PR TITLE
KEYCLOAK-15849 : removed duplicated annotations + fixed @Test(timeout) bug

### PR DESCRIPTION
**Pull request by lhanusov**
auth-remote-server exclude -> removed duplicated annotation, fixed @Test(timeout) bug -> replaced by lambda expression.

### CODE REVIEW

**Comment by lhanusov** [comment]
@vramik @pdrozd Please, can you take a look and make a review? I triggered new Jenkins build recently.

**Comment by lhanusov** [comment]
pipeline tests: https://master-jenkins.com/job/universal-test-pipeline-adapters/26/flowGraphTable/
https://master-jenkins.com/job/universal-test-pipeline-server/54/flowGraphTable/

**Review by vramik — APPROVED** [review]
Thank you @lhanusov, changes looks good to me. Leaving to you to check the pipeline results.

**Comment by lhanusov** [comment]
@pdrozd @vramik There are no failures in case of this fix, I checked Test results recently: https://master-jenkins.com/job/universal-test-pipeline-server/54/testReport/
ClientStorageTest, RoleStorageTest, GroupStorageTest, SamlXMLAttacksTest failures are connected with Windows server Wildfly configuration failure.

**Review by pdrozd — APPROVED** [review]

**Pull request merged**
