### PR TITLE
KEYCLOAK-7166 Added the possibility of not logging out of remote idp …

### PR DESCRIPTION
**Pull request by torbjornsk**
…on browser logout, by passing a query param containing the id of the identity provider

This replaces https://github.com/keycloak/keycloak/pull/5153.

### CODE REVIEW

**Review by mposolda — DISMISSED** [review]

**Comment by mposolda** [comment]
@torbjornsk Thanks it looks good to me. I've approved your changes here, but merge will need to wait until the docs is done and approved as well. So likely will be in Keycloak 4.2.0 release (as Keycloak 4.1.0 release is about to start).

**Comment by torbjornsk** [comment]
I'm having a look at the documentation, and I'm wondering if perhaps this is a better place to document this: https://www.keycloak.org/docs/3.3/securing_apps/topics/oidc/java/logout.html It seems a bit more connected to the logout endpoint in question.

**Comment by torbjornsk** [comment]
Couldn't get it to fit in the identity broker documentation, took a chance and added it to the OIDC logout doc: https://github.com/keycloak/keycloak-documentation/pull/426

**Comment by mposolda** [comment]
@torbjornsk Sorry it took so long to review (PTO etc...) Just added a comment to your docs PR.

This implementation PR looks good to me, but seems that rebase will be needed.

**Comment by torbjornsk** [comment]
Just to make sure that I don't mess it up like the last PR, I should do the following:

- git fetch upstream
- git rebase upstream/master
- git push

Will this be correct?

**Comment by mposolda** [comment]
Yes, correct. However after doing "git rebase upstream/master", you will likely see some error messages added by git. And then when you do "git status", you will see the conflicting files (should be same files, which are mentioned in this PR). Then you will be probably need to do some changes in the conflicting files to fix the conflicts. After this is done, you can do:
```
git add -A
git rebase --continue
```
and hopefully things should be ok after. So then "git push" as the last step :)

**Comment by torbjornsk** [comment]
~/keycloak (KEYCLOAK-7166_make_broker_logout_optional_when_browser_logout_take2)$ git log upstream/master..KEYCLOAK-7166_make_broker_logout_optional_when_browser_logout_take2 
commit 9d143d37728f7ce94215a2ab0f34263fe86b4ff4
Merge: d8e8ed3 1de265f
Author: Torbjørn Skyberg Knutsen <torbjornk@netcompany.com>
Date:   Thu Aug 30 11:13:24 2018 +0200

    Merge branch 'KEYCLOAK-7166_make_broker_logout_optional_when_browser_logout_take2' of https://github.com/torbjornsk/keycloak into KEYCLOAK-7166_make_broker_logout_optional_when_browser_logout_take2

commit d8e8ed3222a7ac8eaedd8a480dc01988939c5581
Author: Torbjørn Skyberg Knutsen <torbjornk@netcompany.com>
Date:   Thu Aug 30 11:04:32 2018 +0200

    Merge remote-tracking branch 'upstream/master'

commit 1de265fab24b0e695005335501bced4ae73987cb
Author: Torbjørn Skyberg Knutsen <torbjornk@netcompany.com>
Date:   Tue Jul 3 15:47:45 2018 +0200

    KEYCLOAK-7166 Added the possibility of not logging out of remote idp on browser logout, by passing a query param containing the id of the identity provider

**Comment by mposolda** [comment]
@torbjornsk Any chance to clean this PR? I suggest to start from latest master and just cherry-pick the single commit with your work on top of it.

**Comment by mposolda** [comment]
Closing as there is no more feedback. Feel free to re-open if you manage to clean/rebase this PR

**Comment by torbjornsk** [comment]
Created a clean PR here: https://github.com/keycloak/keycloak/pull/5689

Hopefully this will be merged before i need to merge from master again, since it just causes troubles.. Will fix my documentation PR next.

**Pull request closed without merging**
