### PR TITLE
Remove GELF

### LINKED ISSUE #27365: Remove GELF
### Description

This is a follow-up on https://github.com/keycloak/keycloak/issues/27364

This included:
* Dependencies
* Options
* Tests
* Docs
* Maven profile

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes #27365

### CODE REVIEW

**Review by mabartos — DISMISSED** [review]
@vmuzikar LGTM. Thanks!

Out of scope: As I see the guide with the GELF description, we could maybe a little bit comprehend the Syslog part with some more examples and mimic the behavior to ensure we have a proper replacement. I'll verify it.

**Comment by mabartos** [comment]
@vmuzikar There is some conflict.

**Comment by vmuzikar** [comment]
@mabartos Thanks, rebased.

**Review by mabartos — DISMISSED** [review]
@vmuzikar LGTM

**Review by ahus1 — DISMISSED** [review]
Approving based on @mabartos' approval

**Comment by abstractj** [comment]
@vmuzikar there are some conflicts to solve.

**Comment by vmuzikar** [comment]
Rebased, thanks.

**Review by mabartos — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]
Approving based on @mabartos' review

**Pull request merged**
