### PR TITLE
Fix facebook social login tests

### LINKED ISSUE #22282: Facebook social login tests not working
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

testsuite

### Describe the bug

Facebook social login tests `SocialLoginTest.facebookLogin` and `SocialLoginTest.facebookLoginWithEnhancedScope`, are failing due to 2 different reasons.

1. reason - While test is run in headless mode it fails due to WebElements overlapping and WebDriver being unable to click login button.

2. reason - While running without headless. Login flow requires to accept cookies in testing browser and also to click continue as button in case user is being logged into facebook web app for the first time.

### Version

22.0.1

### Expected behavior

Tests should log in user into the TestApp page through facebook web app and tests should pass green.

### Headless:
```
ElementClickIntercepted element click intercepted: Element <button value="1" class="_42ft _4jy0 _52e0 _4jy6 _4jy1 selected _51sy" id="loginbutton" name="login" tabindex="0" type="submit">...</button> is not clickable at point (952, 364). Other element would receive the click: <span class="_al53">...</span>
  (Session info: headless chrome=114.0.5735.133)
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'fedora', ip: '192.168.1.106', os.name: 'Linux', os.arch: 'amd64', os.version: '6.3.8-200.fc38.x86_64', java.version: '17.0.7'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 114.0.5735.133, chrome: {chromedriverVersion: 114.0.5735.90 (386bc09e8f4f..., userDataDir: /tmp/.com.google.Chrome.OulU9z}, goog:chromeOptions: {debuggerAddress: localhost:46441}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: d463f4d572758361d4625acd1e9e567b
```

### Non headless:

Login flow gets stuck on page requiring cookies permission.
image

### How to Reproduce?

1. Setup facebook web app following Keycloak documentation - https://www.keycloak.org/docs/latest/server_admin/index.html#_facebook
2. Prepare social-login.properties file containing login information and facebook app key + secret
3. Run the testsuite with following command with your custom social-login.properties file - `mvn -f testsuite/integration-arquillian/pom.xml clean install -Dtest=SocialLoginTest#facebookLogin -Dbrowser=chrome -Dsocial.config=/home/fwojnar/Documents/social-login/custom-social.properties`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by wojnarfilip**
Closes #22282

### CODE REVIEW

**Comment by ahus1** [comment]
@wojnarfilip - I see the parent issue, but no link to a failed test run. Is the test you're fixing here running the GitHub actions CI build, or rather somewhere else?

Another note: When creating a new pull request, please open them in draft mode first, and only switch them to ready once the CI build is green. This avoids sending a notification to maintainers while the build is still running. Thanks!

**Comment by wojnarfilip** [comment]
> @wojnarfilip - I see the parent issue, but no link to a failed test run. Is the test you're fixing here running the GitHub actions CI build, or rather somewhere else?

@ahus1 I am afraid those tests are not running in any CI for some time. We are currently trying in Continuous Testing team to go through them and get them up to date. In order to restore CI build for this in our internal pipeline.

> Another note: When creating a new pull request, please open them in draft mode first, and only switch them to ready once the CI build is green. This avoids sending a notification to maintainers while the build is still running. Thanks!

Sorry I wasn't aware of this. Will keep this in mind in the future.

**Comment by ahus1** [comment]
> We are currently trying in Continuous Testing team to go through them and get them up to date. In order to restore CI build for this in our internal pipeline.

@wojnarfilip - thank you for putting the effort into this. I'd be happy to see this test being running in the upstream pipelines as well once as you are comfortable with it! 

Please ask someone from your team to review it and test the change. Once that review is in, me or another maintainer will merge it.

**Comment by tondrusk** [comment]
Tried both FB login test cases using my private account and they passed with these changes. I also appreciate the handling of logging into the application for the first time but I needed to try this with my hard-coded name in the test as my name contains **áš** which the test can't handle properly while getting it from `social.properties`.

I just nit-picked some things 😉 and suggested some minor changes where you can decide if they shoud be incorporated or not.

**Review by tondrusk — APPROVED** [review]

**Review by tondrusk — APPROVED** [review]
LGTM

**Comment by wojnarfilip** [comment]
@ahus1 Could you take a look now please ? The minor issue with `getConfig("profile.firstName")` being unable to read diacritics from `social.properties` file isn't related to the parent issue.

**Review by ahus1 — APPROVED** [review]
Thank you for this fix! Approving as of @tondrusk's review.

**Pull request merged**
