### PR TITLE
Make role mapping tab visible with view user permissions (backport of #26386)

### LINKED ISSUE #20125: Role mapping tab no longer visible when using fine grained permissions after upgrade from 20.0.3 to 21.0.2
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

We have been using fine grained permissions with Keycloak [20.0.3](https://github.com/keycloak/keycloak/releases/tag/20.0.3).

A user using fine grained permissions was able to view the `Role mapping` tab when navigating a `Group` found in `Groups` in the admin UI.

image

The issue: this tab "disappeared" after upgrading Keycloak to version [21.0.2](https://github.com/keycloak/keycloak/releases/tag/21.0.2).

image

Note:
* No Keycloak configuration or permissions changes had been made meanwhile
* We also tested to see whether upgrading to version [21.1.1](https://github.com/keycloak/keycloak/releases/tag/21.1.1) would resolve it, which it unfortunately did not

### Version

21.0.2

### Expected behavior

A user using fine grained permissions should be able to view the `Role mapping` tab when navigating a `Group` found in `Groups` in the admin UI.

image

### Actual behavior

A user using fine grained permissions is unable to view the `Role mapping` tab when navigating a `Group` found in `Groups` in the admin UI.

This tab "disappeared" after upgrading Keycloak to version [21.0.2](https://github.com/keycloak/keycloak/releases/tag/21.0.2).

### How to Reproduce?

- in a Keycloak instance version `20.0.3`
- setup basic fine grained permissions for a specific user with a groups "manage" role linked to a policy granting that specific user these permissions
- verify that the user is able to see for a group in groups, the `Role mapping` tab
- upgrade the Keycloak instance to version `21.0.2`

expected:
- the user is able to see for a group in groups, the `Role mapping` tab 

actual:
- the user does not longer see the `Role mapping` tab

### Anything else?

_No response_

### LINKED ISSUE #25054: Read Only Access of the realm users' "Role mapping" tab is broken for Admin Console
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Users in the master realm with "view-users" role of a sub realm can't see the "Role mapping" tab of the users of that sub realm.

### Version

22.0.3

### Expected behavior

Users in the master realm with "view-users" role of a sub realm should be able to see the "Role mapping" tab of the users of that sub realm.

### Actual behavior

Users in the master realm with "view-users" role of a sub realm can't see the "Role mapping" tab of the users of that sub realm.

### How to Reproduce?

1. Create a User in the master realm and assign these roles to that user (Make sure to assign your sub realm view-users role to that user).

1a

<br><br>
2. Login/impersonate that user, then go to your sub realm users and click on one of the users you have already set up.
You won't be able to see the "Role mapping" tab even tho that you have the role view-users of that sub realm:

2a

### Anything else?

If I assign the sub realm manage-users role to that user, the "Role mapping" tab shows up, but of course, the user will have write access to the "Role mapping" tab, which is not a desirable solution for read-only users.

3a

### PR DESCRIPTION
**Pull request by sschu**
Closes #25054 
Closes #20125 
Backport to 23 of #26386 

Plain cherrypick of the commit [8807562593667860fabdaafe2ea4eb2813d55dca](https://github.com/keycloak/keycloak/commit/8807562593667860fabdaafe2ea4eb2813d55dca)

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]

**Comment by sschu** [comment]
Thanks a lot @jonkoops !

**Comment by toporek3112** [comment]
In which version is this fix implmented? And also, will this be included in any previouse version like version 22.
Sorry for asking but I cant find anything in the release notes. 
Thanks you.

**Comment by jonkoops** [comment]
Unless someone back-ports this it will be included in version 24. There will be no further releases in the 22.x series, so a back-port would be part of v23.

**Comment by toporek3112** [comment]
Ok, thank you for the quick response!
I was just wondering because these commits are included in release 23.0.6:
image

https://github.com/keycloak/keycloak/compare/23.0.6...main

**Comment by jonkoops** [comment]
Ah, my bad. I didn't notice this PR is already a back-port, this change was part of 23.0.5.

**Pull request merged**
