### PR TITLE
KEYCLOAK-9531 Fix broken Arquillian tests in the "other" module

### PR DESCRIPTION
**Pull request by vmuzikar**

### CODE REVIEW

**Comment by vmuzikar** [comment]
@keycloak-ci-bot test

**Comment by pdrozd** [comment]
ping @keycloak-ci-bot

**Comment by pdrozd** [comment]
@keycloak-ci-bot ping

**Comment by pdrozd** [comment]
@keycloak-ci-bot test

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
