### PR TITLE
Making Token verification more robust by parsing the URL of the issue…

### PR DESCRIPTION
**Pull request by akovari**
…r and the realm

This avoids problems caused by some proxies which turn the issuer address into http://something:80/... vs http://something/...

### CODE REVIEW

**Comment by stianst** [comment]
This is a fairly costly comparison (it requires creating URL objects as well as resolving IP addresses) so is not a good way to do it.

It's also not correct. The issuer should be equal using simple string comparison, not be the equivalent. 

What is the actually issue you are trying to solve here?

**Comment by akovari** [comment]
I'm encountering an issue when for some reason (both my application and keycloak) are behind nginx proxy, at port 80, the token issuer or the realm address has the :80 added to the address. This doesn't happen on other port than 80. I'll need to dig deeper into why this is happening, I'm not entirely sure yet.

**Comment by stianst** [comment]
Have you by any chance specified :80 in the auth-server-url or in the proxy config?

**Comment by akovari** [comment]
Yes, I think I have found the problem, it is in one of the library dependencies of the OIDC implementation I'm using. It's probably best to keep the keycloak code as is, so closing this request.
Thank's for your advice.

**Pull request closed without merging**
