### PR TITLE
[KEYCLOAK-11214] Hotrod event received is failed with null value of key

### PR DESCRIPTION
**Pull request by nicholas-fwang**
[#11214](https://issues.jboss.org/browse/KEYCLOAK-11214)

### CODE REVIEW

**Comment by mposolda** [comment]
@fisache Thanks for the PR.

The changes look fine to me, however there are automated travis tests failing. Could you please rebase your PR against latest master? That should help to fix the "RefreshTokenTest" failing - it was fixed by other PR in the meantime in latest master.

For cross-dc tests, rebase may help too, but not 100% sure, as they are failing in latest master on travis. If cross-dc tests still fail on travis, could you please try to run them on your laptop as described in the instructions - https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md#cross-dc-tests ? Ideally with the keycloak on auth-server-wildfly: so steps a2 and b2 . Thanks

**Comment by fisache** [comment]
@mposolda Thanks for review!
I have rebased to latest master, but still cross-dc test is failed
I need to check this test case and after fix it, remind to you :)

**Comment by mposolda** [comment]
@fisache Test is failing in travis, but in your environment, it may just pass. Let me know if test passes in your environment (on your laptop) when you run them as I mentioned in the comment above.

**Comment by mposolda** [comment]
@fisache Any chance to try to run cross-dc tests on your laptop and doublecheck they work on your laptop? Thanks

**Comment by fisache** [comment]
@mposolda Thanks for remind!
I didn't check cross-dc test. ASAP I will check and update cross-dc tests if need

**Comment by mposolda** [comment]
I am closing as:
- We did not see the error in our environment or any other environment
- Cross-dc tests are failing in travis and there is no confirmation that they are passing in your (or any other) environment
- In theory, there can be side-effects. For example performance of trying the lookup 10 times if you know that particular value is not available. Also NullPointerException is always thrown (even for last attempt), but the previous impl, did not throw NullPointerException in case that value is not available.

Feel free to re-open if you want more discussion around this, but we may need to further clarify the points above.

**Comment by ihostage** [comment]
Hi, @mposolda 👋 
I very want to discuss this 😄 
Right now we have a big problem with our Multi DC cluster. 😞
After changing the credential, the user can't authenticate on one node, because this node can't get an event from `work` cache for remove record from local `users` cache.

Filtered log:
```
2020-02-04 02:39:14,141 WARN  [org.keycloak.cluster.infinispan.InfinispanNotificationsManager] (EE-ManagedExecutorService-default-Thread-14) Event object wasn't available in remote cache after event was received. Event key: 5fc9f537-bb71-491f-9e25-7cf991248abc
2020-02-04 02:39:25,367 WARN  [org.keycloak.cluster.infinispan.InfinispanNotificationsManager] (EE-ManagedExecutorService-default-Thread-6) Event object wasn't available in remote cache after event was received. Event key: 3d9b228d-dfb6-47fd-8a99-c06c38d767d8
2020-02-04 02:39:36,468 WARN  [org.keycloak.cluster.infinispan.InfinispanNotificationsManager] (EE-ManagedExecutorService-default-Thread-5) Event object wasn't available in remote cache after event was received. Event key: 0c873c5e-e01b-42ee-9913-c63b90ac235d
2020-02-04 02:39:39,277 WARN  [org.keycloak.cluster.infinispan.InfinispanNotificationsManager] (EE-ManagedExecutorService-default-Thread-7) Event object wasn't available in remote cache after event was received. Event key: 233763b4-8f32-44e8-bf6f-6877d7be1d4e
2020-02-04 02:39:41,803 WARN  [org.keycloak.cluster.infinispan.InfinispanNotificationsManager] (EE-ManagedExecutorService-default-Thread-14) Event object wasn't available in remote cache after event was received. Event key: b60e5209-045f-401b-9876-872f8365726b
2020-02-04 02:39:43,873 WARN  [org.keycloak.cluster.infinispan.InfinispanNotificationsManager] (EE-ManagedExecutorService-default-Thread-12) Event object wasn't available in remote cache after event was received. Event key: 8ca7b068-378d-4466-bd31-f967ee884ee3
2020-02-04 02:39:44,768 WARN  [org.keycloak.cluster.infinispan.InfinispanNotificationsManager] (EE-ManagedExecutorService-default-Thread-15) Event object wasn't available in remote cache after event was received. Event key: b71f37b3-dec8-48b3-8fab-78714f0b4a21
2020-02-04 02:39:48,741 WARN  [org.keycloak.cluster.infinispan.InfinispanNotificationsManager] (EE-ManagedExecutorService-default-Thread-16) Event object wasn't available in remote cache after event was received. Event key: 08ad25ff-995f-4fe2-aef9-63dbae8e337d
2020-02-04 02:39:51,920 WARN  [org.keycloak.cluster.infinispan.InfinispanNotificationsManager] (EE-ManagedExecutorService-default-Thread-3) Event object wasn't available in remote cache after event was received. Event key: 98f95388-9eb5-41a0-9d39-b1f5d314f83a
2020-02-04 02:39:56,703 WARN  [org.keycloak.cluster.infinispan.InfinispanNotificationsManager] (EE-ManagedExecutorService-default-Thread-9) Event object wasn't available in remote cache after event was received. Event key: b46b0de8-61e7-4a3f-a124-50e84aaced08
2020-02-04 02:39:57,644 WARN  [org.keycloak.cluster.infinispan.InfinispanNotificationsManager] (EE-ManagedExecutorService-default-Thread-6) Event object wasn't available in remote cache after event was received. Event key: bba1540e-81e3-49b9-be40-ce275a485ff0
2020-02-04 02:40:00,820 WARN  [org.keycloak.cluster.infinispan.InfinispanNotificationsManager] (EE-ManagedExecutorService-default-Thread-13) Event object wasn't available in remote cache after event was received. Event key: 80f21dd9-178d-4f63-bb34-601606d27a98
2020-02-04 02:40:16,739 WARN  [org.keycloak.cluster.infinispan.InfinispanNotificationsManager] (EE-ManagedExecutorService-default-Thread-7) Event object wasn't available in remote cache after event was received. Event key: 3daeebea-f8f7-46bb-a60d-5031689ed89c
2020-02-04 02:40:22,267 WARN  [org.keycloak.cluster.infinispan.InfinispanNotificationsManager] (EE-ManagedExecutorService-default-Thread-8) Event object wasn't available in remote cache after event was received. Event key: f2be387d-1b26-4119-8d39-0105fe6ac030
2020-02-04 02:40:23,878 WARN  [org.keycloak.cluster.infinispan.InfinispanNotificationsManager] (EE-ManagedExecutorService-default-Thread-4) Event object wasn't available in remote cache after event was received. Event key: d5f8b2f4-d22c-408b-92e8-4167f2d6f02e
```

I'm sure on 1000%, that object exists in the cache because I can manually get this object by another client. Moreover, the problem node can also get an object from the cache just by yet another call. See screenshot: 

59e2dc4ff3

Maybe it's a bug of Infinispan HotRod client, I don't know. 
But `@ClientListener` get events before the objects will available on every nod of Infinispan cluster.
What do you think?

**Pull request closed without merging**
