### PR TITLE
KEYCLOAK-8175 Possibility of clientScope not being used if user doesn…

### PR DESCRIPTION
**Pull request by mposolda**
…'t have a role

### CODE REVIEW

**Comment by mposolda** [comment]
Docs PR: https://github.com/keycloak/keycloak-documentation/pull/506

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by stianst** [comment]
Haven't looked at this properly, but from my understanding this only allows "filtering" role based client scopes. We also need a way to be able to decide if a user has permissions to a scope when there are no roles being used.

**Comment by mposolda** [comment]
@stianst Yes, this is just about filtering role based client scopes. User won't be able to have the clientScope applied if he is not member of any roles of the clientScope. I think this is what we agreed on, especially we discuss to not introduce any more switches or configurations for this. And this behaviour is sufficient for the backwards compatibility perspective.

So you mean we should be also able to restrict user of having clientScope applied even if client scope doesn't have any role scope mappings defined on itself? How exactly to do it? Integration with the authorization services? Or just simply have a way to define one mandatory role on the clientScope and user won't be allowed to use the clientScope if he is not member of that role?

**Comment by stianst** [comment]
Actually, thinking about it some more it works in all scenarios we discussed. If the client uses scope, but not roles, the roles can be used to decide if scope should be available or not, but it's just a matter of not including roles in the claims.

**Review by stianst — APPROVED** [review]

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by pdrozd** [comment]
@keycloak-ci-bot test

**Pull request merged**
