### PR TITLE
KEYCLOAK-19052: Optimised (split) the clearExpiredEvents query to reduce execution time

### PR DESCRIPTION
**Pull request by KashifSaadat**
**Related:** [KEYCLOAK-16801](https://issues.redhat.com/browse/KEYCLOAK-16801), #7718, [KEYCLOAK-19052](https://issues.redhat.com/browse/KEYCLOAK-19052)

### CODE REVIEW

**Comment by KashifSaadat** [comment]
**Before:**
```
> explain delete from EVENT_ENTITY where REALM_ID in (select realm.id from REALM realm where realm.EVENTS_EXPIRATION > 0) and EVENT_TIME < 1635524216;

+------+--------------------+--------------+-----------------+---------------+---------+---------+------+---------+-------------+
| id   | select_type        | table        | type            | possible_keys | key     | key_len | ref  | rows    | Extra       |
+------+--------------------+--------------+-----------------+---------------+---------+---------+------+---------+-------------+
|    1 | PRIMARY            | EVENT_ENTITY | ALL             | NULL          | NULL    | NULL    | NULL | 2072725 | Using where |
|    2 | DEPENDENT SUBQUERY | realm        | unique_subquery | PRIMARY       | PRIMARY | 38      | func | 1       | Using where |
+------+--------------------+--------------+-----------------+---------------+---------+---------+------+---------+-------------+
2 rows in set (0.001 sec)
```

**After (can use index):**
```
> explain delete from EVENT_ENTITY where REALM_ID in ("realm1", "realm2") and EVENT_TIME < 1635524216;

+------+-------------+--------------+-------+-----------------------------------+--------------------+---------+------+------+-------------+
| id   | select_type | table        | type  | possible_keys                     | key                | key_len | ref  | rows | Extra       |
+------+-------------+--------------+-------+-----------------------------------+--------------------+---------+------+------+-------------+
|    1 | SIMPLE      | EVENT_ENTITY | range | EVENT_ENTITY_INDEX,IDX_EVENT_TIME | EVENT_ENTITY_INDEX | 267     | NULL | 2    | Using where |
+------+-------------+--------------+-------+-----------------------------------+--------------------+---------+------+------+-------------+
1 row in set (0.001 sec)
```

**Comment by KashifSaadat** [comment]
Hi @stianst, would you be able to review this PR please if possible?

**Comment by KashifSaadat** [comment]
Hi @stianst @hmlnarik, are there any updates on a review for this please? We've been running in production successfully with much better behaviour, and the PR is pretty small and simple to review.

**Comment by vramik** [comment]
Thank you @KashifSaadat for the PR, changes looks good to me, could you please rebase it to latest main so I could run DB tests?

@hmlnarik could you please approve running GHA?

**Comment by KashifSaadat** [comment]
Thanks! I've just rebased now.

**Review by vramik — APPROVED** [review]
Thank you @KashifSaadat 

https://master-jenkins.com/job/universal-test-pipeline-server/991

**Review by hmlnarik — APPROVED** [review]
Approving per @vramik 's approval

**Comment by hmlnarik** [comment]
@KashifSaadat Thank you for your contribution!

**Pull request merged**
