### PR TITLE
Closes #10582 : db-schema param conflict with db url

### LINKED ISSUE #10582: Keycloak 17 Quarkus is not using db-schema parameter properly
### Describe the bug

I am trying to deploy Keycloak 17 Quarkus with MariaDb and schema name different from default 'keycloak'.

I created database with name 'db4keycloak' and trying to start Keycloak. 

```
 bin/kc.sh start-dev \
  --db mariadb \
  --db-url-host localhost \
  --db-username keycloak \
  --db-password mypwd \
  --db-schema db4keycloak
```

And getting error:

`022-03-03 21:17:17,040 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLSyntaxErrorException: Could not connect to address=(host=localhost)(port=3306)(type=master) : (conn=45) Unknown database 'keycloak'
`
Keycloak is still trying to connect to default database 'keycloak' in JdbcEnvironmentInitiator.

### Version

17.0.0

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

1. Install MariaDb
2. Create database user 'keycloak' and database 'db4keycloak'

```
create database db4keycloak;
GRANT ALL PRIVILEGES ON db4keycloak.* to keycloak@'%' IDENTIFIED BY 'mypwd'; 
GRANT ALL PRIVILEGES ON db4keycloak.* to keycloak@'localhost' IDENTIFIED BY 'mypwd';
flush privileges;
```
3. Start Keycloak:

```
 bin/kc.sh start-dev \
  --db mariadb \
  --db-url-host localhost \
  --db-username keycloak \
  --db-password mypwd \
  --db-schema db4keycloak
```

You will see error message:

```
[org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLSyntaxErrorException: Could not connect to address=(host=localhost)(port=3306)(type=master) : (conn=50) Unknown database 'keycloak'
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by hc42**
respect DB schema parameter in DB url if not specified otherwise

Closes https://github.com/keycloak/keycloak/issues/10582

### CODE REVIEW

**Review by DGuhr — DISMISSED** [review]
LGTM, and thanks for the contribution! 

@andreaTP afaict the operator CI fail is not caused by these changes, could you pls confirm? 

@pedroigor would be nice if you could also have a look here and merge if you think its fine :)

**Comment by andreaTP** [comment]
@DGuhr , confirm the CI failure is spurious as far as I can tell.

**Comment by ahus1** [comment]
Hi  @hc42 - thanks for contributing this PR. 

As I'm triaging bugs and PRs today I ask one favor from you for this pull request: Please update the description of this PR to include `Closes #10582`. 

This will help collaboration on GitHub in two ways:
* it populates the right hand column on both the issue and the PR with a reference to the issue you're about to fix
* it will close the issue once the PR has been merge automatically.

For **future** pull requests, the recently updated contributing guidelines for this repository ask for the following commit comment format: 

```
A brief descriptive summary

Optionally, more details around how it was implemented

Closes #1234
``` 

Using this format, the phrase to link and close the issue will be part of the PR description automatically.

Thanks in advance!

**Comment by hc42** [comment]
Hi,
I updated the commit message to include "Closed #...".

**Comment by ahus1** [comment]
@hc42 - thanks for updating this PR. 

I see that you update the title of this PR with the issue number. Instead, please add the description (the text are just below the title) the text `Closes #10582`. 

Unfortunately GitHub accepts this special comment only in the description, not in the title.

Thank you!

**Comment by hc42** [comment]
Hi,
I updated the first comment.

**Comment by ahus1** [comment]
@hc42 - thanks for taking the time to update it. It is now linked nicely (screenshot below)!

image

**Review by stianst — CHANGES_REQUESTED** [review]
For MySQL/MariaDB `--db-url-database` should be used instead. Instead of adding a synonym for `--db-schema` like what is done here we should just print an error message if `db-schema` is used with MySQL or MariaDB.

**Comment by DGuhr** [comment]
Closing here, see #10582

**Pull request closed without merging**
