### PR TITLE
KEYCLOAK-9509 Upgrade to Wildfly 15

### PR DESCRIPTION
**Pull request by hmlnarik**

### CODE REVIEW

**Comment by hmlnarik** [comment]
@keycloak-ci-bot test

**Comment by hmlnarik** [comment]
@keycloak-ci-bot test

**Comment by hmlnarik** [comment]
@keycloak-ci-bot test

**Comment by hmlnarik** [comment]
Branch was rebased to the current master

**Comment by hmlnarik** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
Changes looks good, Thanks! I would approve, but there is still label "Incomplete" in the PR. I guess you want to squash commits at least?

**Comment by hmlnarik** [comment]
@keycloak-ci-bot test

**Comment by hmlnarik** [comment]
Rebased to current master and squashed

**Comment by hmlnarik** [comment]
@keycloak-ci-bot test

**Review by stianst — APPROVED** [review]

**Review by stianst — APPROVED** [review]

**Pull request merged**
