### PR TITLE
Remove conditionals about Linux vs. Windows

### LINKED ISSUE #26028: Remove conditional statements about Windows / Linux from the docs

### PR DESCRIPTION
**Pull request by ahus1**
Closes #26028

### CODE REVIEW

**Comment by ahus1** [comment]
@andymunro - for an upcoming release of RHBK22 Windows will be supported. Please review and approve this change as it is reverting conditionals that have been added in the past. Thanks!

**Review by andymunro — APPROVED** [review]
Looks good.

**Comment by ahus1** [comment]
@mhajas - could you please merge it when you have the time? Thanks!

**Review by mhajas — APPROVED** [review]
LGTM! Thanks @ahus1!

**Pull request merged**
