### PR TITLE
Remove deprecated adapters

### LINKED ISSUE #28778: Remove Tomcat OIDC adapter
May include codebase, distribution, documentation, testsuite (To be doublechecked what exactly as part of this task...).

### LINKED ISSUE #28779: Remove Jetty OIDC adapter
May include codebase, distribution, documentation, testsuite (To be doublechecked what exactly as part of this task...). Not 100% sure if this is not already done for Keycloak 24 (at least partially...).

### LINKED ISSUE #28780: Remove Spring adapters
May include codebase, distribution, documentation, testsuite (To be doublechecked what exactly as part of this task...).

### LINKED ISSUE #28781: Remove SpringBoot adapters
May include codebase, distribution, documentation, testsuite (To be doublechecked what exactly as part of this task...).

### LINKED ISSUE #28782: Remove Jetty SAML adapter
May include codebase, distribution, documentation, testsuite (To be doublechecked what exactly as part of this task...).

Not 100% sure if this was not already done in Keycloak 24 (at least partially).

### LINKED ISSUE #28783: Remove Tomcat SAML adapter
May include codebase, distribution, documentation, testsuite (To be doublechecked what exactly as part of this task...).

### LINKED ISSUE #28786: Remove servlet filter saml adapters
May include codebase, distribution, documentation, testsuite (To be doublechecked what exactly as part of this task...).

### LINKED ISSUE #28789: Remove JAAS login modules
This is about those login modules: https://www.keycloak.org/docs/latest/securing_apps/index.html#_jaas_adapter

May include codebase, distribution, documentation, testsuite (To be doublechecked what exactly as part of this task...).

This can be used by Fuse adapter tests, so we might not be able to do this if Fuse tests would need to be kept inside Keycloak codebase (hopefully not needed to be kept).

### LINKED ISSUE #28790: Remove KeycloakInstalled
May affect codebase, documentation (this part https://www.keycloak.org/docs/latest/securing_apps/index.html#_installed_adapter ). Not sure if it affects also distribution or testsuite (to be doublechecked, but maybe not as not sure if we have any tests for this at all).

### PR DESCRIPTION
**Pull request by douglaspalmer**
Closes keycloak#28783
Closes keycloak#28778
Closes keycloak#28781
Closes keycloak#28780
Closes keycloak#28782
Closes keycloak#28779
Closes keycloak#28786
Closes keycloak#28790
Closes keycloak#28789

### CODE REVIEW

**Review by jonkoops — DISMISSED** [review]
LGTM, but let's link the issues this closes in the PR.

**Comment by douglaspalmer** [comment]
> LGTM, but let's link the issues this closes in the PR.

Done

**Review by jonkoops — APPROVED** [review]
Still LGTM

**Review by rmartinc — CHANGES_REQUESTED** [review]
I would have preferred to send different PRs because this is an enormous change. But once it is here let's try to merge it. :smile:

Just two things:

* It seems that app severs for tomcat and jetty are completely gone now. So probably we can get rid of them in the [app-server](https://github.com/keycloak/keycloak/tree/24.0.3/testsuite/integration-arquillian/servers/app-server) directory too. They create the app server to test adapters in that container.
* And I would also remove them from the [ContainerConstants](https://github.com/keycloak/keycloak/blob/24.0.3/testsuite/integration-arquillian/util/src/main/java/org/keycloak/testsuite/utils/arquillian/ContainerConstants.java#L39-L41). You need to tweak the tests that contains them (if you see a test only for tomcat and/or jetty, you can remove it too). IIRC the adapter IT CI is only executed for wildfly right now (and maybe EAP in some other chain).

Probably we will need some changes in documentation, but we can do that once everything is removed in a follow-up.

Thanks!

**Review by rmartinc — APPROVED** [review]
We'll finally manage my comments in a follow-up #29089. So approving it.

**Review by mposolda — APPROVED** [review]
@douglaspalmer @jonkoops @rmartinc Thanks everyone for the review!

+1 that we can cleanup stuff from testsuite etc as a follow-up. I assume that we may review testsuite after we remove all adapters and do some more cleanup there https://github.com/keycloak/keycloak/issues/28795 . In the meantime, we can cleanup smaller chunks from testsuite (like jetty and tomcat etc), so separate task for https://github.com/keycloak/keycloak/issues/29089 is also good.

**Pull request merged**
