### PR TITLE
KEYCLOAK-16625 : Testsuite -> auth.server.remote: adding keystore and certificate files

### PR DESCRIPTION
**Pull request by lhanusov**

### CODE REVIEW

**Comment by lhanusov** [comment]
@hmlnarik @vramik @iankko Please, can you make a review. Thanks.

**Comment by lhanusov** [comment]
https://keycloak-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/pipelines/job/universal-test-pipeline-server/2537/console

**Review by iankko — COMMENTED** [review]
@lhanusov 
1) Thanks for the PR, Lukas!
2) Since the referenced testing job seems to have ended up prematurely, tested the change locally. Not completely sure the supplied truststore is the right one -- not sure the JBoss common Wildfly one -- ```./testsuite/integration-arquillian/servers/auth-server/jboss/common/keystore/keycloak.truststore``` shouldn't be used instead. IIRC from previous research, it might be even necessary to delete the ```localhost``` entry from the keystore / truststore first, so it's regenerated properly for the auth server remote endpoint during the build.

  a) While it's true this fixes the failure of the ```MetricsRestServiceTest```:

```
$ mvn clean install -B -Pauth-server-remote -f testsuite/integration-arquillian/tests/base/pom.xml -Dtest=org.keycloak.testsuite.metrics.MetricsRestServiceTest
```

  b) The rest of the base testsuite tests while running with ```-Pauth-server-remote```:

```
$ mvn clean install -B -Pauth-server-remote -f testsuite/integration-arquillian/tests/base/pom.xml
```

are still failing with the

```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

error message. E.g. the following ones (stopped the output after some time)

``` 
[iankko@localhost surefire-reports]$ grep -r 'sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target' * | sort | uniq 
org.keycloak.testsuite.account.custom.CustomAuthFlowCookieTest.txt:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.keycloak.testsuite.account.custom.CustomAuthFlowOTPTest.txt:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.keycloak.testsuite.account.custom.CustomThemeTest.txt:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.keycloak.testsuite.account.LinkedAccountsRestServiceTest.txt:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.keycloak.testsuite.account.ResourcesRestServiceTest.txt:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.keycloak.testsuite.account.SessionRestServiceTest.txt:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.keycloak.testsuite.actions.AppInitiatedActionResetPasswordTest.txt:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.keycloak.testsuite.actions.AppInitiatedActionTotpSetupTest.txt:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.keycloak.testsuite.actions.AppInitiatedActionUpdateProfileTest.txt:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.keycloak.testsuite.actions.DeleteAccountActionTest.txt:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.keycloak.testsuite.actions.RequiredActionMultipleActionsTest.txt:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.keycloak.testsuite.actions.RequiredActionResetPasswordTest.txt:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.keycloak.testsuite.actions.RequiredActionTotpSetupTest.txt:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.keycloak.testsuite.actions.RequiredActionUpdateProfileTest.txt:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.keycloak.testsuite.actions.TermsAndConditionsTest.txt:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
TEST-org.keycloak.testsuite.account.custom.CustomAuthFlowCookieTest.xml:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
TEST-org.keycloak.testsuite.account.custom.CustomAuthFlowOTPTest.xml:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
TEST-org.keycloak.testsuite.account.custom.CustomThemeTest.xml:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
TEST-org.keycloak.testsuite.account.LinkedAccountsRestServiceTest.xml:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
TEST-org.keycloak.testsuite.account.ResourcesRestServiceTest.xml:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
TEST-org.keycloak.testsuite.account.SessionRestServiceTest.xml:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
TEST-org.keycloak.testsuite.actions.AppInitiatedActionResetPasswordTest.xml:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
TEST-org.keycloak.testsuite.actions.AppInitiatedActionTotpSetupTest.xml:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
TEST-org.keycloak.testsuite.actions.AppInitiatedActionUpdateProfileTest.xml:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
TEST-org.keycloak.testsuite.actions.DeleteAccountActionTest.xml:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
TEST-org.keycloak.testsuite.actions.RequiredActionMultipleActionsTest.xml:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
TEST-org.keycloak.testsuite.actions.RequiredActionResetPasswordTest.xml:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
TEST-org.keycloak.testsuite.actions.RequiredActionTotpSetupTest.xml:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
TEST-org.keycloak.testsuite.actions.RequiredActionUpdateProfileTest.xml:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
TEST-org.keycloak.testsuite.actions.TermsAndConditionsTest.xml:Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
...
```

Originally wanted to have both of those issues fixed at once (that's the reason the PR wasn't submitted yet).

But whatever, I am OK if this is split into more tasks (fix the ```MetricsRestServiceTest``` first, and fix the PKIX issue later), since due to other duties won't be able to return to this sooner than in ~2 weeks.

@miquelsi What's your take on this? Is it OK if just the ```MetricsRestServiceTest``` is fixed, and those PKIX issues are fixed later?

Thanks
Jan

**Comment by hmlnarik** [comment]
> https://keycloak-jenkins.com/view/pipelines/job/universal-test-pipeline-server/2544

This job has not been run correctly. Please run the job from the build job.

**Comment by hmlnarik** [comment]
@iankko Please keep fixes to any specific tests (e.g. MetricsRestServiceTest) separately from fixes for reenabling execution of auth-server-remote tests

**Review by vramik — CHANGES_REQUESTED** [review]
Thank you @lhanusov for the PR.

edit: Please share the latest pipeline results from both server and adapter pipeline.

**Comment by lhanusov** [comment]
@vramik I added adapter tests recently, but I will rerun it again, because my PR has little bit changed.

**Comment by lhanusov** [comment]
@iankko @hmlnarik Thank you for your hints, I have edited auth-remote-server profile like jboss https configuration. I am running tests locally right now and the certificate issue seems to be fixed.

**Comment by lhanusov** [comment]
@iankko @vramik New build:
https://keycloak-jenkins.com/view/pipelines/job/universal-test-pipeline-server/2578/console
https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/2073/console

**Review by vramik — CHANGES_REQUESTED** [review]
@lhanusov thank you

https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/2073/execution/node/4747/log/?consoleFull unfortunately shows the issue is still present when running `pipeline/test-pipeline-universal/scripts/adapter_tests.sh remote`

**Comment by lhanusov** [comment]
https://keycloak-jenkins.com/view/pipelines/job/universal-test-pipeline-server/2583/console
https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/2078/console

**Review by vramik — APPROVED** [review]
@lhanusov Thank you.

**Review by iankko — APPROVED** [review]
LGTM, thanks @lhanusov !

**Review by hmlnarik — APPROVED** [review]
Approving based on @vramik 's and @iankko 's reviews

**Pull request merged**
