### PR TITLE
Promote preview feature "update email" to be supported by default

### LINKED ISSUE #16739: Check if preview feature "update email" can be supported by default
### Description

See the checklist on https://github.com/keycloak/keycloak/issues/16737

### PR DESCRIPTION
**Pull request by reda-alaoui**
Fix #16739

### CODE REVIEW

**Review by jonkoops — CHANGES_REQUESTED** [review]
There should also be a note about this in the release notes for 24.

**Comment by reda-alaoui** [comment]
@jonkoops ok, I will add a note. Would you have advices regarding https://github.com/keycloak/keycloak/issues/16739#issuecomment-1961010846 ?

**Comment by jonkoops** [comment]
I don't have an answer for those questions unfortunately, perhaps someone from the core team could shine a light on it. @keycloak/core

**Review by mposolda — CHANGES_REQUESTED** [review]
@reda-alaoui Thanks for the PR, but AFAIk it is not yet planned to promote "update-email" from preview to officially supported. We will need to do some more testing and verification within the team regarding this (possibly with included more automated tests to avoid bugs like https://github.com/keycloak/keycloak/issues/27234 to happen again in the future).

BTW. If you are open to add some more automated tests (especially for instance the one for https://github.com/keycloak/keycloak/issues/27234, which was fixed without the test), it can be nice.

**Comment by reda-alaoui** [comment]
Hello @mposolda ,
I opened this PR because I saw zero pending tasks on https://github.com/keycloak/keycloak/issues/16739#issue-1564291729 .

I'll try to add some automated tests.

**Pull request closed without merging**
