### PR TITLE
KEYCLOAK-3883 Allow combining attributes for a multivalued

### PR DESCRIPTION
**Pull request by wvdhaute**

### CODE REVIEW

**Comment by stianst** [comment]
Thanks, can you please add some tests?

**Comment by wvdhaute** [comment]
Would a basic unit test suffice or do you require a more extensive integration test?
If the latter, could you point me to a good starting point / similar test to save me some time maybe? :)

**Comment by stianst** [comment]
We require integration tests. I don't even really know this code that you are changing so not sure about where to add tests to be honest.

**Comment by stianst** [comment]
I'm going to close this, feel free to reopen once there are tests.

**Comment by yuri1969** [comment]
@wvdhaute Do you feel like writing the integration tests any time soon? I could try to do it, but you seem to have the first hand experience with the code :]

**Comment by wvdhaute** [comment]
Hmm @yuri1969 . I have switched to another project and forget about this issue. 
Afraid I will probably not find the time to figure out how to write an integration test for this one.

**Comment by yuri1969** [comment]
Thanks for the answer @wvdhaute. I'll try to handle this.

**Pull request closed without merging**
