### PR TITLE
Added danish translation.

### PR DESCRIPTION
**Pull request by FuKe**
Added danish translation to account, email and login in base theme.

### CODE REVIEW

**Comment by stianst** [comment]
Thanks, I've asked on the mailing lists if there's anyone that can review this.

**Comment by stianst** [comment]
No takers, so I will try to review as best I can. I'm Norwegian, so it will definitively be a best effort review ;)

**Review by stianst — DISMISSED** [review]

**Comment by stianst** [comment]
Looks good (at least to my Norwegian eyes). Can you resolve merge conflicts and squash to a single commit please? Also please create a JIRA issue.

**Comment by FuKe** [comment]
@stianst I've did the squash and resolved merge conflicts.
Now the Travis build fails because of unit test: "UserSessionInitializerTest.testUserSessionInitializer"
Is this related to something else?

**Comment by stianst** [comment]
There's 5 commits there now, including a few merge commits. Ideally I want a single clean commit on top. As you said you squashed it already, did you forget to push to your branch or something?

The failing tests shouldn't have anything to do with your work. We have some unstable tests that randomly fail on Travis, so it's probably that. I've reschedule the job that failed to see if it passes second time.

**Comment by stianst** [comment]
The work looks good, but I can't accept this until there's a single rebased/squashed commit.

**Comment by FuKe** [comment]
@stianst I need to give it a second try.. Is using the "git rebase" command the right thing to do? That was what I did, but I couldn't manage to squash my commits into one without pushing a new commit :)

**Comment by stianst** [comment]
Squashing is more complicated as you have merge commits in your branch now, which happens when you do a git pull, rather than a git rebase. Simplest option now is probably to checkout master, then cherry-pick your 3 commits, and finally use git rebase -i HEAD~3 to squash to a single commit.

**Comment by FuKe** [comment]
Yeah I realized that, when I tried to the squashing again.. I'll try again with a fresh checkout, and let you know when it is done, in one commit ;)

**Comment by stianst** [comment]
Thanks, I've had this same issue myself in the past. Once you get lost in squash hell, there's no recovering ;)

**Pull request closed without merging**
