### PR TITLE
Fixes for FIPS IT in CI (24.0)

### LINKED ISSUE #33875: [Keycloak CI] - FIPS IT - Failed to fetch maven
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

[Example of failing job](https://github.com/keycloak/keycloak/actions/runs/11318888099/job/31474218364)

It fails in all branches and looks like a CI issue (not related to any code change).

Failure is in the stage "Build adapter distributions" with the exception like:
```
Run ./mvnw install -DskipTests -f distribution/pom.xml
wget: Failed to fetch https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.8/apache-maven-3.9.8-bin.zip
Error: Process completed with exit code 1.
```

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

### Anything else?

_No response_

### LINKED ISSUE #33881: Add back FIPS IT builds
### Description

In the https://github.com/keycloak/keycloak/pull/33876 , the FIPS IT are removed due they are always failing and blocking all the CI builds and all the PRs.

This task is to investigate this further and fix and uncomment FIPS IT again.

### LINKED ISSUE #34004: Expired certificates for SAML tests (previous branches)
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

testsuite

### Describe the bug

Some certificates are expired in previous branches (22 and 24). The certificates were updated for upstream in this commit: https://github.com/keycloak/keycloak/commit/e9c9efc3f4dac20cf6a791fd3efaa246612038bd. But I forgot of backporting to previous branches. As the commit should be stripped to remove the BC upgrade I'm opening this issue to assign an issue for the PRs.

```
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 1413463563620 (0x14918fe5d64)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=http://localhost:8080/sales-post-sig/
        Validity
            Not Before: Oct 16 12:44:23 2014 GMT
            Not After : Oct 16 12:46:03 2024 GMT
        Subject: CN=http://localhost:8080/sales-post-sig/
```

### Version

22.0 and 24.0

### Regression

- [ ] The issue is a regression

### Expected behavior

CI must pass OK.

### Actual behavior

CI fail for several SAML tests (Adapter IT, Base IT 6, FIPS IT).

### How to Reproduce?

https://github.com/keycloak/keycloak/actions/runs/11365953261/job/31615689264?pr=33915

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Backport for the issue in FIPS IT. Two PRs:

Closes #33875
Closes #33881
Closes #34004

PR 1: https://github.com/keycloak/keycloak/pull/33876
PR 2: https://github.com/keycloak/keycloak/pull/33893

Commit 1: 272d59be889e56c1933ae1681c29a3362de10396
Commit 2: 10aca5552314d6e5c9226f3c6d0107861c38c693 

There are issues with cache maven wraper and it's removed in upstream (https://github.com/keycloak/keycloak/commit/e2e47f14dd4e502243bb5433005a95280cbb29fb) so I have removed that part too. The reason is that inside the container tests are executed as root and there are issues with permissions to create the cache.

### CODE REVIEW

**Review by mposolda — APPROVED** [review]

**Review by jonkoops — APPROVED** [review]

**Comment by rmartinc** [comment]
Rebased to incorporate operator changes.

**Comment by rmartinc** [comment]
Rebased again to include the playwright upgrade that fixes the account failure in js-ci. Let's see this time. :smile:

**Comment by rmartinc** [comment]
Added the commit to fix issue #34004.

**Comment by mposolda** [comment]
@rmartinc Thanks for all the work on this!

**Pull request merged**
