### PR TITLE
Avoid sorting items returned from the database which are already stable

### LINKED ISSUE #29319: Don't sort persistent sessions when retrieving a list
### Description

The list is already stable and sorted by sessionId. The current sorting in PersistentUserSessionProvider is a wrong leftover where the original code sorted the items it retrieved from Infinispan. 

### Discussion

_No response_

### Motivation

Don't pull all items from the database when displaying them in the UI. Only retrieve as many items necessary for pagination.

### Details

I'll create a PR.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #29319

### CODE REVIEW

**Comment by ahus1** [comment]
@mhajas - I found this sort which shouldn't be necessary and will cause otherwise performance issues as it will load all entries from the database. 

Please review this PR when you have the time. Thanks!

**Review by sguilhen — APPROVED** [review]
Yes, please! Found similar things being done to groups and other entities, which kinda makes fetching the results from the DB in a stream pointless as the sorting requires the whole list of entities to be performed.

**Review by mhajas — APPROVED** [review]
Thank you for the change @ahus1, it makes sense to remove the line.

However, one question. It seems this was kind of broken for offline sessions in the old provider too. The Infinispan cache is sorted by `lastSessionRefresh` but the JPA queries  are ordered by `userSessionId`. Should we change the ordering for queries to lastSessionRefresh too? 

I don't think this ^ would be a blocker for merging this PR as the line is currently useless for persistent sessions (the important thing is that queries are consistently ordered and it doesn't really matter whether it is by lastRefresh or userSessionId). We can create a follow-up if we want to change the ordering.

**Comment by ahus1** [comment]
In a short call we agreed that pagination needs to be handled more properly eventually: ordering by user session Id is not a stable sorting when new sessions of users arrive or are expired. A stable sorting would be sorting by creation time and user session ID, but this is beyond this issue.

**Pull request merged**
