### PR TITLE
KEYCLOAK-12852: Internal query params not removed after AIA

### PR DESCRIPTION
**Pull request by ssilvert**
PR for Keycloak 11

https://issues.redhat.com/browse/KEYCLOAK-12852

### CODE REVIEW

**Review by edewit — DISMISSED** [review]
LGTM

**Comment by ssilvert** [comment]
UI Test success: https://keycloak-jenkins.com/job/keycloak-account2-matrix/882/

**Comment by ssilvert** [comment]
@abstractj Can you approve this so we can merge?

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@ssilvert Please uncomment some parts of the SigningInTest that are related to this. (Just search for KEYCLOAK-12852 in the test.)

**Comment by abstractj** [comment]
@ssilvert could you please follow up on @vmuzikar's comments?

**Comment by ssilvert** [comment]
Uncommented tests.

New UI test run success: https://keycloak-jenkins/job/keycloak-account2-matrix/885/

@abstractj Please review.  Thanks.

**Comment by abstractj** [comment]
@ssilvert changes look same for me, but I'm afraid I won't have the time to try it today. So I will trust in another round of reviews from @Aboullos @edewit @vmuzikar

**Review by abstractj — APPROVED** [review]
@edewit @vmuzikar @Aboullos taking into consideration the comments on this PR, plus the fact that the latest changes was just the matter of uncomment the tests that @vmuzikar requested and it blocks the progress on snowpack. I'm approving it.

**Pull request merged**
