### PR TITLE
Respect permissions configured to firstName and lastName when configu…

### LINKED ISSUE #12109: Account REST endpoint does not respect view permission settings from user profile on lastName and firstName
### Describe the bug

When the feature *declarative user profile* is enabled, it's possible to configure permissions to user attributes - whether the user or admin can view or edit specific attributes.

The account rest endpoint does not respect this setting for `lastName` and `firstName` - they are always shown to the user, regardless what is configured in the user profile. 

Even though this only affects some very special and probably rare use cases, the behavior is not consistent and should be fixed.

### Version

18.0

### Expected behavior

When the user profile does not allow view access to *firstName* and/or *lastName*, the account rest endpoint should not provide these attributes. The account UI should not shown them.

### Actual behavior

The attributes `firstName` and/or `lastName` are always returned by the account rest endpoint, regardless of the permissions configured in the user profile.

### How to Reproduce?

* enable declarative user profile by setting `-Dkeycloak.profile.feature.declarative_user_profile=enabled`
* remove view permission for user on `lastName` and `firstName`, e.g. like this: 
```
...
{ "name": "firstName", 
  "displayName": "${firstName}", 
  "permissions": { "view": ["admin"], "edit": ["admin" ]  } 
},
...
```

### Anything else?

I'll provide a fix for this

### PR DESCRIPTION
**Pull request by ioemat**
…red in user profile

Resolves #12109

### CODE REVIEW

**Review by pedroigor — APPROVED** [review]
@ioemat Thanks, sorry for the delay.

**Comment by pedroigor** [comment]
@ioemat I'm not quite comfortable resolving conflicts when backporting. Can we have it in 19 instead? Otherwise, I'll need some help from UI team to see if I do not break the account console when resolving conflicts.

**Comment by sschu** [comment]
@pedroigor Since @ioemat is on holiday, I will step in. I think it is fine to just have this in KC19.

**Comment by pedroigor** [comment]
@sschu tks

**Comment by ioemat** [comment]
Thanks for reviewing and merging this @pedroigor

**Pull request merged**
