### PR TITLE
KEYCLOAK-2075 KEYCLOAK-2107 - support for SAML IsPassive mode

### PR DESCRIPTION
**Pull request by velias**
on both IdP server side and SP adapter side. Implemented in one PR as they use each other in integration tests.
On server side I did some refactoring and created common codebase used by both openid and SAML protocols, so code initiating auth request handling is same for both protocols now. This allows simpler implementation of other common features like reauthentication requests.

### CODE REVIEW

**Comment by stianst** [comment]
@vellas can you rebase please? I'll get Bill to review it once you've done that.

**Comment by velias** [comment]
@stianst rebased
I forgot to mention that I also patched org.keycloak.saml.SAML2ErrorResponseBuilder - before my patch SAML error responses from Keycloak was completely empty. 
And I also added correct validation of login response Status into SAML adapter.

**Comment by velias** [comment]
Rebased again. My patch of SAML2ErrorResponseBuilder removed as it had been patched in meantime

**Comment by velias** [comment]
@stianst Travis build failed in "Base Test Suite"  at 
Failed tests: 
  RealmRolesTest.crudRole:96->addRole:45->AbstractAuthTest.assertFlashMessageSuccess:106 Success! The role has been created.

Any idea what is going on? This looks completely outside code I changed in PR.

**Pull request merged**
