### PR TITLE
[KEYCLOAK-11755] Support for setting "other claims" in access token response

### PR DESCRIPTION
**Pull request by mouse256**
Please let me know if this is something acceptable

### CODE REVIEW

**Comment by stianst** [comment]
This is abusing the access token response as it should not be used to return claims, but rather only details around the response and included tokens. As such this is not something we should add.

**Comment by mouse256** [comment]
OK, I was under the impression the spec is lenient about that and you can add fields if you want. Especially since the otherclaims field is already present in the pojo, there's currently just no way to set a value.
Would you have another suggestion on how to achieve https://issues.jboss.org/browse/KEYCLOAK-11755 ?

**Comment by stianst** [comment]
Can you please describe what the information it is that you want to pass?

**Comment by mouse256** [comment]
Sure.
We have a few api's, and we'd like to have the flexibility to change the endpoints of those api's (in case we'd need to scale, change technology, or even some customer having specific requirements).
So the only thing we'd like to hardcode is the URL of our authentication service (keycloak). And when you get a token, we'd like to pass along additional information where all the endpoints for different services are (for that specific customer).
So it being some kind of customer-specific service discovery.

We have this information stored already in keycloak (as attributes on a group), and like a clean way to pass this on.

**Comment by stianst** [comment]
Nifty, but I do believe this is quite a bit of a corner case (and perhaps even a bit abusing an IdP). I'd suggest if you want to do it this way to just add the details to the ID token rather than the token response.

I'm going to close this as it really doesn't convince me that there's a general need to add random claims to the token response and further there is really no reason to rather add this to the ID token instead.

**Comment by mouse256** [comment]
Ok, I feared it might not be considered generic enough. Thanks for the feedback anyway.

**Pull request closed without merging**
