### PR TITLE
Remove AngularJS based examples

### LINKED ISSUE #13694: Remove examples that are still using AngularJS
### Description

We still have several example projects that have not been maintained for years that are based on AngularJS (which has been EOL since a while). Since no-one has stepped up to maintain these examples and have little relevance for modern development it would be best to simply remove them.

### PR DESCRIPTION
**Pull request by jonkoops**
Closes #13694.

### CODE REVIEW

**Review by abstractj — APPROVED** [review]
LGTM @jonkoops I'd suggest to also include a follow-up task of creating a quick start in React. If it makes sense.

**Comment by jonkoops** [comment]
Thanks @abstractj. I'm curious if it's relevant to keep making these examples as they seem to just end up unmaintained and out of date with what is actually recommended nowadays. Preferably we'd document these things in the documentation, which is probably a more accessible resource anyways.

**Comment by abstractj** [comment]
@jonkoops we definitely should get rid of those examples at some point, and eventually suggest an alternative to the community. 
Having those as part of the documentation has some disadvantages like easily becoming out of date, and forcing people to copy and paste the code, instead of just cloning the repo and running it (if I understood what you propose correctly).

**Comment by jonkoops** [comment]
> Having those as part of the documentation has some disadvantages like easily becoming out of date

To be very frank, the same applies for these very examples we are removing here. We have a tendency to create these things and then just let the code rot over time.

Besides that I have the gut feeling that folks don't really look at the examples in the repository. At the very least we don't have any documentation pointing to them as a quick Google search for "Keycloak examples" results in nothing of the sort.

**Review by edewit — APPROVED** [review]

**Comment by jonkoops** [comment]
@ssilvert can I ask you to take a look at this PR and let me know if the changes look good?

**Review by ssilvert — APPROVED** [review]
LGTM

Before we merge, I'd like to give @stianst a chance to respond in case he knows some reason why we shouldn't remove these examples.

**Review by stianst — APPROVED** [review]

**Comment by jonkoops** [comment]
:fire::fire::fire:

**Pull request merged**
