### PR TITLE
KEYCLOAK-12568 Remove unused method from org.keycloak.saml.processing.core.saml.v2.factories.JBossSAMLAuthnResponseFactory

### PR DESCRIPTION
**Pull request by Captain1653**
Next PR with deleting unused method. I have tried to compile without this method and it was ok. I want to be sure about "green"  build. I think it's better to wait review and then (if it makes sense) create JIRA-issue. I have found many classes with unused methods, but, I suppose, it's better to clean up code carefully. Step by step, class by class.

### CODE REVIEW

**Review by martin-kanis — COMMENTED** [review]
createResponseType method indeed seems to be not used. I run pipeline tests on this PR and I didn't find any regression. However I'm wondering whether someone from community could use that method in their stuff as it's in publicly available artifact keycloak-saml-core. @hmlnarik WDYT?

**Review by hmlnarik — CHANGES_REQUESTED** [review]
The changes seem ok, but please fix the commit message (introduce KEYCLOAK JIRA if not already there, and update the commit and PR summary to include the JIRA key in it)

**Comment by Captain1653** [comment]
@hmlnarik Done

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Thanks @Captain1653

**Review by hmlnarik — APPROVED** [review]
Thanks @Captain1653

**Pull request merged**
