### PR TITLE
Fixed dialog title when deleting a user

### LINKED ISSUE #35475: Delete user confirm title is wrong
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When using the admin console and attempting to delete a user, a confirmation popup appears with a wrong title.

"Are you sure you want to permanently delete the provider '{{provider}}'?"
grafik

However, this is only the case if the delete button is pressed from the user specifig settings page. If it is used from the user list, the title is "Delete user?".

### Version

26.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

The title is the same as from the user list delete button

### Actual behavior

The title is obviously wrong.

### How to Reproduce?

1. Get a keycloak instance
2. Create a user
3. Open the user list, click the three dots on the right next to the user and select "delete"
   - A popup appears with the right text
4. Click on the user to get to his settings, click on the "action" button top right and select "delete"
   - A popup appears with the wrong text

### Anything else?

The issue is in EditUser.tsx in [line 238](https://github.com/keycloak/keycloak/blob/faf36dd2f061fe0c0392b5b731f3fdaf7c33c34b/js/apps/admin-ui/src/user/EditUser.tsx#L238).

````typescript
  const [toggleDeleteDialog, DeleteConfirm] = useConfirmDialog({
    titleKey: "deleteConfirm",
    messageKey: "deleteConfirmCurrentUser",
    continueButtonLabel: "delete",
    continueButtonVariant: ButtonVariant.danger,
    onConfirm: async () => {
      try {
        if (lightweightUser) {
          await adminClient.users.logout({ id: user!.id! });
        } else {
          await adminClient.users.del({ id: user!.id! });
        }
        addAlert(t("userDeletedSuccess"), AlertVariant.success);
        navigate(toUsers({ realm: realmName }));
      } catch (error) {
        addError("userDeletedError", error);
      }
    },
  });
````

`deleteConfirm` is `Are you sure you want to permanently delete the provider '{{provider}}'?` ([messages_en.properties](https://github.com/keycloak/keycloak/blob/faf36dd2f061fe0c0392b5b731f3fdaf7c33c34b/js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties#L2786))

The other delete button uses `deleteConfirmUsers`, which is `Delete user?`.

Maybe it can just use this text instead? Or could this be a problem since this text is meant for deleting multiple users?

### PR DESCRIPTION
**Pull request by agagancarczyk**
Closes https://github.com/keycloak/keycloak/issues/35475

### CODE REVIEW

**Review by jonkoops — COMMENTED** [review]
FYI https://www.i18next.com/translation-function/plurals

**Comment by SebastEnn** [comment]
> FYI https://www.i18next.com/translation-function/plurals

So we would need
````
deleteConfirmUser_one=Delete user?
deleteConfirmUser_other=Delete users?
````
in [messages_en.properties](https://github.com/keycloak/keycloak/blob/d553f3967b19d7f833c20c5eaf1537b48292bd01/js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties#L365).

This would break compatibility with other translations tho 🤔

**Comment by jonkoops** [comment]
> This would break compatibility with other translations tho

Would it? This just means they need to be updated.

**Comment by SebastEnn** [comment]
> Would it? This just means they need to be updated.

Well, the key is `deleteConfirmUsers` and the value `Delete user?`.
Some languages might have set the value to something that would fit _other, and some other maybe for _one.

Either way, translations would need to be updated. So I guess we can ignore this and eventually someone will notice and fix the translation 🙂

**Comment by edewit** [comment]
@SebastEnn we add and update the translations constantly and we only maintain the English version, so broken translations can't be helped

**Review by edewit — APPROVED** [review]

**Pull request merged**
