### PR TITLE
KEYCLOAK-8414 use the clientId when the ClientScopeModel is an instan…

### PR DESCRIPTION
**Pull request by sguilhen**
…ce of ClientModel

### CODE REVIEW

**Comment by mposolda** [comment]
I think it is good, but will be good to add a test as well. I guess ExportImportTest?

**Comment by sguilhen** [comment]
@mposolda looking into it. Not sure yet where to properly test this

**Comment by sguilhen** [comment]
@mposolda Found out the existing test was almost complete. Just added a few granted scopes, including the 'account' one in the testrealm.json and updated the util class to check for the presence of all the scopes in the consent.

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Pull request merged**
