### PR TITLE
Add a Maven profile to remove GELF support

### LINKED ISSUE #22515: Add a Maven profile to remove GELF support
### Description

Add a prod profile that will remove GELF from Keycloak dist. This concerns configuration, tests (need to be selectively skipped) and the following dependencies:
```
biz.paluch.logging:logstash-gelf
io.quarkus:quarkus-logging-gelf-deployment
io.quarkus:quarkus-logging-gelf
```

### PR DESCRIPTION
**Pull request by mabartos**
Closes #22515

Backport of https://github.com/keycloak/keycloak/pull/22615

### CODE REVIEW

**Review by vmuzikar — CHANGES_REQUESTED** [review]
Should we make the `product` profile activated by a property `-Dproduct`?
https://github.com/keycloak/keycloak/blob/9d8f334c8eedd22bf062b5ccf7175b8fec21b9db/quarkus/runtime/pom.xml#L728

**Comment by mabartos** [comment]
@vmuzikar I thought I'd manage all activation of "product" things via the property in a follow-up task. However, I rechecked it, and the only place is here, so I agree to include it in this PR.

**Comment by mabartos** [comment]
@vmuzikar done

**Comment by vmuzikar** [comment]
> However, I rechecked it, and the only place is here

There seem to be one more:
https://github.com/keycloak/keycloak/blob/aae4569071fdb115394dfb5dce506a57852d1706/testsuite/integration-arquillian/servers/auth-server/quarkus/pom.xml#L340-L376
Can you please update it too?

**Comment by mabartos** [comment]
@vmuzikar Oops. I have some struggles with finding things in IDE these days :smile:

**Review by vmuzikar — APPROVED** [review]
@mabartos LGTM, thanks!

@ASzc jFYI – product needs to be build with `-Dproduct`, not just `-Pproduct`.

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Pull request merged**
