### PR TITLE
8877 Make KeycloakMetricsHandler aware of context-path

### LINKED ISSUE #8877: KeycloakMetricsHandler does not respect a custom context-root
### Description

Currently the `KeycloakMetricsHandler` is bound with a strict path binding to `/metrics`. 
This works fine with the default context-path of `/` however, when a different context-path is configured the `/metrics` endpoint doesn't work anymore and only returns an error message.

If we enable metrics via `-Dkc.metrics.enabled=true` and configure a custom context-path via `-Dquarkus.http.root-path=/auth`, we see the following error response returned if the `/auth/metrics` endpoint is accessed:
```
The expected context root of metrics is /metrics, but a request with a different path was routed to MetricsRequestHandler
```

The problem is that the `org.keycloak.quarkus.runtime.services.health.KeycloakMetricsHandler` is configured with a fixed `/metrics` path which is used to check an incoming request.

### Discussion

_No response_

### Motivation

To remain compatible with older Keycloak deployments, we want to use the custom context-path `/auth`. At the same time we also want metrics to be available out of the box.

### Details

A small fix is to make `KeycloakMetricsHandler` aware of the configured context path:
```
package org.keycloak.quarkus.runtime.services.health;

import io.quarkus.smallrye.metrics.runtime.SmallRyeMetricsHandler;
import org.keycloak.quarkus.runtime.configuration.Configuration;

import static org.keycloak.quarkus.runtime.configuration.MicroProfileConfigProvider.NS_QUARKUS_PREFIX;

public class KeycloakMetricsHandler extends SmallRyeMetricsHandler {

    public static final String DEFAULT_METRICS_ENDPOINT = "/metrics";

    public KeycloakMetricsHandler() {
        String contextPathPrefix = Configuration.getOptionalValue(NS_QUARKUS_PREFIX.concat("http.root-path")).orElse("");
        String metricsPath = (contextPathPrefix + DEFAULT_METRICS_ENDPOINT).replaceAll("//","/");
        setMetricsPath(metricsPath);
    }
}

```

### PR DESCRIPTION
**Pull request by thomasdarimont**
With this fix the metrics endpoint is correctly served also if a custom context-path is used.

With `-Dkc.metrics.enabled=true` and `-Dquarkus.http.root-path=/auth` a request to `/auth/metrics` yields the correct metrics response. If no custom context-path is configured `/metrics` still returns the correct response.

Fixes #8877

Signed-off-by: Thomas Darimont <thomas.darimont@googlemail.com>

### CODE REVIEW

**Comment by pedroigor** [comment]
@thomasdarimont Thanks. 

Ideally, you should be able to achieve the same thing by avoiding going through MP config at runtime (a bit expensive). Please, take a look at https://github.com/pedroigor/keycloak/tree/tmp.

Note that I have also removed the `KeycloakMetricsHandler`. If you do not need it for your observability work, I would just remove it too.

I'm also using a `NonApplicationRootPathBuildItem` to resolve the path. Not sure if we need that now, but in the future, we should be able to set a specific relative path for metrics/health (similarly to what Quarkus does).

Let me know if it makes sense and if it works for you.

**Review by pedroigor — COMMENTED** [review]
Just a comment.

**Comment by thomasdarimont** [comment]
@pedroigor thanks for looking into this. I think the runtime config lookup is not a big issue, since it only happens once. 
However, I like your approach much better than mine :) So I'm happy with ditching this PR to in favor of your approach.

**Comment by pedroigor** [comment]
@thomasdarimont Yeah, it only happens once but at runtime. One of the things we should try as much as we can is to move processing to build time. Mainly those related to building time properties. With that in mind, we could make sure we don't impact startup or memory footprint.

Please, let me know when you update the PR. Thanks again.

**Comment by pedroigor** [comment]
@thomasdarimont Btw, added a test for this here https://github.com/keycloak/keycloak/pull/8858/files#diff-0234d8b8e504f5225d4a26fe05c95fe8d8dc7e6988526617a2b51261a546515bR40.

**Comment by pedroigor** [comment]
Hey @thomasdarimont, are you able to update your PR with those changes? It would be nice to have this in v16 ...

**Comment by thomasdarimont** [comment]
@pedroigor Thanks for the heads-up. I just updated the branch to be aligned with your changes. I also enabled the test you added in your tmp branch. I gave it a quick spin and it seems to work well. I ran the integration test and it worked, additionally I built a new kcx distribution from scratch and tested the metrics support:
```
bin/kc.sh start-dev --http-enabled=true --metrics-enabled=true --http-relative-path=/
```
shows the metrics via http://localhost:8080/metrics

The command
```
bin/kc.sh start-dev --http-enabled=true --metrics-enabled=true --http-relative-path=/auth
```
shows the metrics via http://localhost:8080/auth/metrics

I'd say that this works as expected :)

**Comment by thomasdarimont** [comment]
@pedroigor @DGuhr sorry for the noise I messed up a rebase... I just updated the PR with the latest version and tested everything again as mentioned above, the metrics support still works well - with the latest kcx on quarkus 2.5.1.
```
2021-12-09 17:32:47,926 INFO  [io.quarkus] (main) Keycloak 16.0.0-SNAPSHOT on JVM (powered by Quarkus 2.5.1.Final) started in 3.832s. Listening on: http://0.0.0.0:8080
```

**Comment by DGuhr** [comment]
> @pedroigor @DGuhr sorry for the noise I messed up a rebase... I just updated the PR with the latest version and tested everything again as mentioned above, the metrics support still works well - with the latest kcx on quarkus 2.5.1.
> 
> ```
> 2021-12-09 17:32:47,926 INFO  [io.quarkus] (main) Keycloak 16.0.0-SNAPSHOT on JVM (powered by Quarkus 2.5.1.Final) started in 3.832s. Listening on: http://0.0.0.0:8080
> ```

No Problem. Happy to help - should be always that easy ;)

**Review by pedroigor — APPROVED** [review]
Thanks @thomasdarimont !

**Pull request merged**
