### PR TITLE
Refactor kc.sh, kcadm.sh and kcreg.sh scripts, make kc.sh POSIX shell compatible

### LINKED ISSUE #22041: Make kc, kcadm and kcreg scripts POSIX shell compatible and fix some issues
### Description

`kc.sh`, `kcadm.sh` and `kcreg.sh` currently requires Bash, which may not be available by default on the system (e.g. Alpine Linux) or not preferred (e.g. Debian with `dash` for non-interactive shell). It’s unnecessary because they can be easily rewritten to be portable – compatible with all commonly used POSIX shell implementations (e.g. dash, busybox ash, yash, …). This also improves security because Bash is not the most secure shell…

The scripts also use obsolete syntax for subshells (backticks) and obsolete “x-hack” for a bug in one particular shell that was fixed many decades ago.

`kcadm.sh` and `kcreg.sh` also forks Java process instead of replacing it and they don’t handle signals – when a Java process gets stuck and the user kills the script, then the process is orphaned and keeps running.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by jirutka**
Please read the commit messages.

Closes #22041

### CODE REVIEW

**Review by mabartos — APPROVED** [review]
@jirutka LGTM, thanks!

@ASzc @Pepo48 Do you have any objections to this?

@abstractj Could you please execute the CI in order to have it properly covered? Thanks

**Comment by ASzc** [comment]
Appears to be a legitimate refactor, in the sense that the functionality is completely unchanged, as far as I can see. Hopefully we have some tests to double check that it still works as expected.

The syntax used is the modern preferred syntax, and should in theory allow POSIX compatibility. However, this is very hard to verify on Linux, where bash is the standard shell. `/bin/sh` just launches bash in POSIX emulation mode, which is not very accurate. I don't think we especially care if the script is POSIX compatible, so I'm fine assuming that it is without verification.

LGTM

**Comment by Pepo48** [comment]
LGTM. Just to be completely on a safe side, I would ask QE to run the PR in our internal CI environment.

**Comment by mabartos** [comment]
Executed build pipeline in our internal CI pipeline[1].
Pipeline tests will be executed after.

https://keycloak-jenkins.com/view/Keycloak/job/keycloak-build-pipeline/177/

**Comment by mabartos** [comment]
Changes LGTM. However, I need to analyze the test results more. Keycloak is properly started, but then something bad happens, and I don't know what ATM. 

@jirutka Could you please also check the test failures if you spot something that could be related?

**Comment by jirutka** [comment]
@mabartos, can you please approve the workflows?

**Comment by jirutka** [comment]
> Keycloak Documentation / External links check (pull_request) Failing after 17m 

This is unrelated to this PR.

**Comment by abstractj** [comment]
Thank you @jirutka those changes look good, but I also would like a review from the @keycloak/cloud-native considering the impact.

Added to that @jirutka I noticed that we don't have a GitHub issue to address the changes here. Could you please create one [following our guidelines](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md)?

**Comment by mabartos** [comment]
Executed additional internal pipeline job in order to properly verify behavior with the new changes. Otherwise, I'm ok to proceed with this. 

See: https://keycloak-jenkins.com/view/Keycloak/job/keycloak-build-pipeline/215/

**Review by mabartos — APPROVED** [review]
Changes LGTM.

AFAIK, the failures in pipelines should not be related to this PR; server started properly and I don't see any problems there.
@miquelsi Could you please double-check it? Thanks

Server pipeline: https://keycloak-jenkins.com/view/Keycloak/job/universal-test-pipeline-server/2814/
Adapter pipeline: https://keycloak-jenkins.com/view/Keycloak/job/universal-test-pipeline-adapters/1759/

Commits might be squashed during merging by a maintainer. 

@ASzc @Pepo48 So, are you ok with these changes?

**Review by Pepo48 — APPROVED** [review]

**Comment by vmuzikar** [comment]
Synced with main to resolve test failures

**Comment by jirutka** [comment]
I noticed another problem in the scripts, so I fixed it in the next commit and when on it, rebased against master.

What is this PR waiting for?

**Comment by mabartos** [comment]
@vmuzikar I believe these Operator test failures are not related to this PR; could you please rerun it?

**Review by mabartos — APPROVED** [review]
Provided changes LGTM and IMO, the additional ones after executing pipelines do not require another build. Locally verified on Fedora, and everything works as expected. 

@jirutka Thanks for the PR!

**Review by Pepo48 — APPROVED** [review]
The proposed changes LGTM as well.

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@jirutka Noticed one last thing. Can you please create an issue for this?

**Comment by jirutka** [comment]
Okay… #22041.

**Review by vmuzikar — APPROVED** [review]
@jirutka Thank you!

**Pull request merged**
