### PR TITLE
Fix OpenAPI spec POST /admin/realms/{realm}/clients #25601

### LINKED ISSUE #25601: OpenAPI: POST /admin/realms/{realm}/clients response is 201
POST /admin/realms/{realm}/clients response is 201 (OpenAPI spec said 200)

### PR DESCRIPTION
**Pull request by y-tabata**
Closes #25601

### CODE REVIEW

**Review by ahus1 — APPROVED** [review]
Thank you for this change. It is definitely an improvement, and I therefore approve it. 
As a next step, it would be good to have also possible error responses documented using the ` @APIResponses` annotation.

Still, I'm approving and about to merge this PR. I'm looking forward to a future PR.

**Comment by ahus1** [comment]
@y-tabata - one note for future PRs: As outlined in the CONTRIBUTING.md file, the Keycloak project prefers a separate line that references the issue in the format of

```
Closes #1234
```

in its commit messages. I fixed it manually for this PR, and I'd like you to use this format for future PRs.

**Comment by ahus1** [comment]
@y-tabata - please rebase this PR as the lastest main branch contains a fix for the failing WebAuthn test.

**Comment by y-tabata** [comment]
@ahus1 I rebased it.

**Pull request merged**
