### PR TITLE
SAML element EncryptionMethod can consist any element

### LINKED ISSUE #12585: False implementation of SAML element EncryptionMethod
### Describe the bug

Schema Definition of [SAML element EncryptionMethod](https://www.w3.org/TR/2002/REC-xmlenc-core-20021210/Overview.html#sec-EncryptionMethod) is : 

>   <complexType name='EncryptionMethodType' mixed='true'>
    <sequence>
      <element name='KeySize' minOccurs='0' type='xenc:KeySizeType'/>
      <element name='OAEPparams' minOccurs='0' type='base64Binary'/>
      <any namespace='##other' minOccurs='0' maxOccurs='unbounded'/>
    </sequence>
    <attribute name='Algorithm' type='anyURI' use='required'/>
  </complexType>

Keycloak only honors and parses KeySize and OAEPparams. If an EncryptionMethod exists with any other valid xml element, Keycloak throws a RuntimeException. Due to it, valid xml files can not be parsed and inserted as SAML Identity Provider or SAML Client. Examples can be found to https://md.aai.grnet.gr/feeds/edugain-samlmd.xml ( fe SP with entity id 'https://sam.ihsmarkit.com/sso/Ukfed-W228SA1MKb' ).

EncryptionMethod must be enhanced with a List<Object> any and SAMLEncryptionMethodParser must add in this least all xml elements expect from KeySize and OAEPparams.

### Version

16.1

### Expected behavior

Xml element must be parsed as any elemnt

### Actual behavior

A RuntimeExceptio is thrown.

### How to Reproduce?

Try to add entity with entity id 'https://sam.ihsmarkit.com/sso/Ukfed-W228SA1MKb' from https://md.aai.grnet.gr/feeds/edugain-samlmd.xml as SAML Client.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cgeorgilakis**
closes #12585

### CODE REVIEW

**Comment by mposolda** [comment]
Thanks a lot for the PR and sorry for it not yet being reviewed. We will try to review this once we have some time...

**Comment by mposolda** [comment]
@rmartinc Do you please have a chance to review?
@cgeorgilakis Is it possible to add automated test for this?

**Review by rmartinc — CHANGES_REQUESTED** [review]
@cgeorgilakis I think the changes are OK but as @mposolda commented please add a test for the failed scenario. You can add a method similar to [testSamlImportAndExport](https://github.com/keycloak/keycloak/blob/24.0.2/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java#L720-L755). You will need another idp metadata configuration file similar to [saml-idp-metadata.xml](https://github.com/keycloak/keycloak/blob/24.0.2/testsuite/integration-arquillian/tests/base/src/test/resources/admin-test/saml-idp-metadata.xml), define in it an encryption key with several `EncryptionMethod` and in one of them add any data like in the failed examples.

**Review by rmartinc — CHANGES_REQUESTED** [review]
Thanks @cgeorgilakis! LGTM!
Just squash the commits into one and sign (`--signoff`) it to pass the DCO test and it's fine to me.

**Comment by cgeorgilakis** [comment]
> Thanks @cgeorgilakis! LGTM! Just squash the commits into one and sign (`--signoff`) it to pass the DCO test and it's fine to me.

I have done them.

**Review by rmartinc — APPROVED** [review]
Thanks @cgeorgilakis!

**Review by mposolda — APPROVED** [review]

**Pull request merged**
