### PR TITLE
Add a media type to error responses on OID4VC endpoints

### LINKED ISSUE #31585: Credential offer endpoint fails with 500 when bearer token has expired
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oid4vc

### Describe the bug

When hitting the credential offer endpoint with an expired token, the server fails internally, returning a 500 status.

### Version

25.0.2 

### Regression

- [ ] The issue is a regression

### Expected behavior

The endpoint must return a 4xx status, indicating that the error is the client's fault. The logic in the code expects this to be a 400.

### Actual behavior

Error responses are not correctly mapped due to a missing media type.
```
2024-07-24 16:57:04,210 ERROR [org.keycloak.headers.DefaultSecurityHeadersProvider] (executor-thread-1) MediaType not set on path /realms/master/protocol/oid4vc/credential-offer/1RdDCZMHPP7LFQ4ugZi8v3mSxFUv6EqA, with response status 400
2024-07-24 16:57:04,213 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /realms/master/protocol/oid4vc/credential-offer/1RdDCZMHPP7LFQ4ugZi8v3mSxFUv6EqA failed, error id: 6a99ea99-548c-4aa5-a709-ddbbe3866a31-1: jakarta.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
```

### How to Reproduce?

Hit a valid credential offer enpoint with a bearer token that has expired.

```bash
curl --location 'https://localhost:8443/realms/master/protocol/oid4vc/credential-offer/1RdDCZMHPP7LFQ4ugZi8v3mSxFUv6EqA' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <expired-token>'
```

### Anything else?

I'll send a short PR to address this.

### PR DESCRIPTION
**Pull request by IngridPuppet**
Closes #31585

### CODE REVIEW

**Review by tnorimat — CHANGES_REQUESTED** [review]
@IngridPuppet Thank you. Could you add integration tests for checking this modification?

**Review by tnorimat — COMMENTED** [review]
@IngridPuppet Thank you. Could you add integration tests for checking this modification?

**Comment by IngridPuppet** [comment]
@tnorimat Thank you for suggesting integration tests, which will also prevent regression in the future. I will add some in the course of next week.

**Comment by IngridPuppet** [comment]
> Could you add integration tests for checking this modification?

@tnorimat There were tests on the negative paths of interest. I added the check in there.

**Review by tnorimat — APPROVED** [review]
LGTM

**Comment by tnorimat** [comment]
@mposolda I approved the PR. Could you check it?

**Review by mposolda — APPROVED** [review]
@IngridPuppet @tnorimat Thanks!

**Pull request merged**
