### PR TITLE
Create an FAQ section in docs

### LINKED ISSUE #16018: Create an FAQ section in docs
### Description

We should have an FAQ section in the docs on Keycloak website. This should cover our most reccuring issues reported by the community.

### PR DESCRIPTION
**Pull request by andre-nascimento6791**
Added the first FAQ documents in order to improve the UX when setting and deploying Keycloak.

This is the initial attempt, just to propose one main structure of the possible FAQ.

It is suggested 2 options to edit, keep and browse the FAQ:

* Option 1) Via "hackmd.io" website:
  - https://hackmd.io/@jFN9Md-pQ22qDudvIrxr9A/rJNuFi8oj/edit
    - Which is linked and pushing to this file: 
      - "keycloak/docs/faqs/from-hackmd.io/keycloak-faq-01.md"

* Option 2) Via HTML/CSS/JS files based on a free Template for FAQs:
  - In this branch, find the files under: "keycloak/docs/faqs/site-pages/index.html"

Feel free to edit this FAQ, by adding, updating or removing any categories or questions and their content. It should be enriched by all the team members.

We should decide which way would be better to keep the FAQ in an easier and attractive way for our End Users/Customers.

Closes #16018

### CODE REVIEW

**Review by stianst — CHANGES_REQUESTED** [review]
I'm not in favor of adding this. We already have more tools involved in building docs, etc. than we can handle, and also more channels to communicate with the community than we can handle.

In general I think questions like these should be answered by the documentation, or in https://github.com/keycloak/keycloak/discussions/categories/q-a.

**Comment by vmuzikar** [comment]
@stianst Thanks for the feedback. The motivation for an FAQ is to have a single place for the most common issues that users report. While we have good docs and I believe we already have a good coverage for most topics, from our experience people often miss important informations and create a GH Issue right away reporting e.g. a bug, which then unnecessarily takes time from the users and the team. The FAQ should not replicate and duplicate existing documentation in any way. It should be just sort of navigation to the docs, showing where to quickly find answers to most common questions, hence keeping the maintenance costs to minimum.

Now we're not yet sure with the form. We're at the beginning of exploring the idea of FAQ, mostly collecting the topics and evaluating what should be covered and how.

I'm personally not convinced yet this belongs to the docs on Keycloak web (we might as well leverage the GH Discussions as you mentioned) but it's still a subject to discuss.

**Comment by stianst** [comment]
> @stianst Thanks for the feedback. The motivation for an FAQ is to have a single place for the most common issues that users report. While we have good docs and I believe we already have a good coverage for most topics, from our experience people often miss important informations and create a GH Issue right away reporting e.g. a bug, which then unnecessarily takes time from the users and the team. The FAQ should not replicate and duplicate existing documentation in any way. It should be just sort of navigation to the docs, showing where to quickly find answers to most common questions, hence keeping the maintenance costs to minimum.
> 
> Now we're not yet sure with the form. We're at the beginning of exploring the idea of FAQ, mostly collecting the topics and evaluating what should be covered and how.
> 
> I'm personally not convinced yet this belongs to the docs on Keycloak web (we might as well leverage the GH Discussions as you mentioned) but it's still a subject to discuss.

What specifically is this trying to achieve that can't be done with GitHub Discussions? The problem there is essentially down to maintenance/capacity, not the tool itself. Adding yet another source of FAQ just makes this worse, and adds yet another channel to the community we're not maintaining properly.

**Comment by vmuzikar** [comment]
@stianst Not arguing against GitHub Discussions, I can imagine e.g. a pinned post there with the questions and links to the docs. The aim is to help with the maintenance to prevent irrelevant bug reports we often see. In any case, we're now at the point of exploring the idea, evaluating pros/cons based on the topics we'd like to cover. It is true that this PR might be a bit premature as we don't know, as mentioned, what form of it we'll choose.

**Comment by vmuzikar** [comment]
@andre-nascimento-rh I would suggest to close this PR and continue with the HackMD document for now. WDYT?

**Comment by stianst** [comment]
I'm not really understanding the plans around this. Why are we introducing a FAQ in the first place? Why are we not considering then a tool that we already using instead of a new tool?

If many people regularly are having an issue, the solution isn't some separate FAQ. The solution is fix the problem, better usability, or better documentation. No one will check a separate FAQ, however they may search GitHub Issues/Discussions though.

**Comment by vmuzikar** [comment]
@stianst As discussed earlier, the motivation for an FAQ is to have a concentrated list of most common questions/issues with links to docs. That does not mean we don't have an existing documentation for these issues. People just apparently don't go through all the guides, and create bug reports right away. An FAQ might help with that. And I agree we might use the GH Discussions for it.

**Pull request closed without merging**
