### PR TITLE
Fix logic error in AbstractOAuth2IdentityProvider

### LINKED ISSUE #24943: Fix logic error in AbstractOAuth2IdentityProvider
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

The first if statement in this block references the wrong constant. VALIDATED_ACCESS_TOKEN should be used in place of VALIDATED_ID_TOKEN.

        if (context.getContextData().containsKey(OIDCIdentityProvider.VALIDATED_ID_TOKEN))
            userSession.setNote(FEDERATED_ACCESS_TOKEN, params.getFirst(OAuth2Constants.SUBJECT_TOKEN));
        if (context.getContextData().containsKey(OIDCIdentityProvider.VALIDATED_ID_TOKEN))
            userSession.setNote(OIDCIdentityProvider.FEDERATED_ID_TOKEN, params.getFirst(OAuth2Constants.SUBJECT_TOKEN));

### Version

999.0.0-SNAPSHOT

### Expected behavior

FEDERATED_ACCESS_TOKEN should be stored when the context data contains a validated access token.

### Actual behavior

FEDERATED_ACCESS_TOKEN should be stored when the context data contains a validated id token.

### How to Reproduce?

I don't have a reproducer. Spotted the error redding code.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by douglaspalmer**
Closes #24943

### CODE REVIEW

**Comment by mposolda** [comment]
@douglaspalmer Thanks, seems good, but rather assigning to @pedroigor to doublecheck this.

**Comment by jbman** [comment]
Note: Independently of the condition, the same user session note is overwritten at [DefaultTokenExchangeProvider.java#L516](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java#L516) right after `AbstractOAuth2IdentityProvider.exchangeExternalComplete` is executed. 
Should the the first two lines at `AbstractOAuth2IdentityProvider.exchangeExternalComplete` rather be removed?

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@jbman That is a good point ... I think we should actually remove the like at the `DefaultTokenExchangeProvider` because we can assume a subject token will always be an access token.

The provider should be agnostic to the token type ...

@douglaspalmer Does it deserve a follow-up to improve this? I think I merged to quickly even though we need this fix anyways ...

**Comment by douglaspalmer** [comment]
@pedroigor I agree that we should remove line 516 from DefaultTokenExchangeProvider. It doesn't differentiate whether the subject token is an access token or an id token. It does explain why the broken logic didn't break anything though.

**Pull request merged**
