### PR TITLE
[KEYCLOAK-17031] - ClientInvalidationClusterTest failing on Quarkus due to unreliable comparison

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by mposolda** [comment]
@pedroigor I see `GroupInvalidationClusterTest` failing now. Could it be a regression of your change?

**Comment by pedroigor** [comment]
@mposolda Should be fixed now. I've changed it a bit.

Btw, I noticed that in some places in the code we are not reverting the accessible flag when marking it as `true`. Maybe we should fix those places in another PR?

**Review by mposolda — APPROVED** [review]
@pedroigor Thanks for the fix!

Regarding revert of accessible, maybe yes, but I am not 100% sure if this is needed and what is the priority of it. So leaving this to you.

**Comment by pedroigor** [comment]
> @pedroigor Thanks for the fix!
> 
> Regarding revert of accessible, maybe yes, but I am not 100% sure if this is needed and what is the priority of it. So leaving this to you.

I would say the main issue is making it possible to access whatever field we are marking as accessible directly, without going through methods to properly, and securely, change the state. It usually a best practice. I'm going to create a JIRA.

**Pull request merged**
