### PR TITLE
KEYCLOAK-17306 Add field to modify Referrer-Policy header through admin console

### PR DESCRIPTION
**Pull request by micedre**
This PR adds a new field in Security Defenses Menu in administration console to control the value of the `Referrer-Policy` header in keycloak responses.

### CODE REVIEW

**Comment by madhukkc** [comment]
would love to see this merged in latest

**Review by stianst — COMMENTED** [review]
I'm not convinced this is a good idea to add as it basically removes a layer of protection that can prevent leaking sensitive information through the referrer headers.

Can you explain why you need to make this change?

**Comment by kkcmadhu** [comment]
The referal urls were available till keycloak 4.7 or 4.8 i guess and later removed without notice, so this broke backward compatiblities in our case, 
How and where do we use referer?

 Since keycloak has scablity issues (more than couple of 100 realms per keycoak instance), we run multiple keycloak clusters under single domain ( say mykeycloak.com), we keep these keycloak clusters behind a reverse proxy (nigix, envoy)) and based on the url (realm name) route the traffic to correct cluster.

Well there are some urls say keycloak/auth/realms and few toher which donot have the patter /auth/relams/<reamlid>/blah or /auth/admin/<realmid>/blah

in those cases the refer used to contain the correct realm id, and we were depending on it to load the admin consoles.. 

refer my orignal post about this here : https://lists.jboss.org/pipermail/keycloak-user/2019-April/017798.html

**Comment by stianst** [comment]
@kkcmadhu Is that UI or API for admin console? If it's UI perhaps you could link to a specific realm with "/admin/master/console/#/realms/<realm name>"?

**Comment by zanettea** [comment]
I was using the referrer for another reason. Our app allows customizing the themes (including login) for suborganization (with 3rd level hostname) in the same realm. Moreover we used a common IDP for all realms. So we used the referrer to pass the initial requested url down to the IDP, so that the IDP can render the login with the right theme for the original hostname.
Oddly enough, once in the IDP login page, after a refresh the referrer is available (I guess because the referrer gets lost during the redirect).

From the given above explanations I can't understand why many other security headers are configurable, yet not referrer-policy ?

Thanks

**Pull request closed without merging**
