### PR TITLE
KEYCLOAK-16115 Remove need for MapStorage.keySet() and values()

### PR DESCRIPTION
**Pull request by hmlnarik**

### CODE REVIEW

**Review by vramik — CHANGES_REQUESTED** [review]
LGTM, though there are test failures, I can reproduce them locally as well.

**Review by vramik — APPROVED** [review]
Thank you @hmlnarik, as far as I'm concerned this PR is good to go in.

**Review by mposolda — APPROVED** [review]
Approving. Did just brief review and mostly relying on the @vramik review.

**Comment by hmlnarik** [comment]
Travis error is irrelevant (build failed for crossdc-server that would be skipped anyway).

**Pull request merged**
