### PR TITLE
15234 switch to micrometer metrics

### PR DESCRIPTION
**Pull request by sschu**
Implements https://github.com/keycloak/keycloak/issues/15234.

This is a breaking change, lots of metrics will be renamed, some added and removed.

### CODE REVIEW

**Comment by sschu** [comment]
It probably makes sense to wait for https://github.com/keycloak/keycloak/pull/14925 since with Infinispan also switches to Micrometer with version 14.

**Review by pedroigor — COMMENTED** [review]
@sschu LGTM.

For me, once you squash the commits and update the commit message we should be good to merge it.

**Comment by sschu** [comment]
@pedroigor I'll do another test to check if the Infinispan metrics appear now that it was updated to 14.0.2. Merging this PR will change a lot of metrics so this might break dashboards for people.

**Comment by pedroigor** [comment]
@sschu Yeah, it will break but we can have some notes in migration/upgrade guide about it.

I'm also wondering if it makes sense to provide more fine-grained control over which metrics you can enable/disable. Too much, right? Perhaps the best is to be opinionated about the metrics and rely on a single option to enable everything.

**Comment by sschu** [comment]
@pedroigor I just realised that cache metrics are disabled in Keycloak, so they won't be visible via micrometer either. I would say enabling them is a different issue. So I just squashed the commits.

**Comment by pedroigor** [comment]
Yeah, we don't have metrics for ISPN. That is something we are missing. I thought you were planning to include them too :)

**Comment by ahus1** [comment]
As I'm currently travelling, it would be nice to have a metrics output before/after as a text file as an attachment in this issue. This wouldn't be requirement to merge it, it would be nice for collaborators and reviewers.

**Comment by sschu** [comment]
@pedroigor It is as simple as adding "statistics=true" in the ISPN cache config xml.

**Comment by sschu** [comment]
[smallrye-metrics.txt](https://github.com/keycloak/keycloak/files/10094496/smallrye-metrics.txt)
[micrometer_metrics.txt](https://github.com/keycloak/keycloak/files/10094497/micrometer_metrics.txt)
@ahus1 I added what I get from a Keycloak 20.0.1 from smallrye-metrics vs. what I get from micrometer using this branch.

**Review by ahus1 — APPROVED** [review]
I looked at the metrics before/after, and I find all the metrics we used in keycloak-benchmark for both JVM metrics (memory and GC), and for the DB connection pool. 

The metrics changed their name/namespace (`vendor_agroal_...` -> `agroal_...`). @pedroigor  - I assume this should be in the release notes? If yes, I'd be happy to prepare a note.

Infinispan metrics are missing in both, and I'm looking forward to see them enabled in a future PR.

**Review by pedroigor — APPROVED** [review]

**Comment by sschu** [comment]
@ahus1 Thanks a lot!
@pedroigor I am still wondering whether this should be merged right now. Is the update to Infinispan 14 still scheduled for KC21? Otherwise it might be difficult to get Infinispan metrics enabled.

**Comment by sschu** [comment]
Looks like I was a few seconds too slow with my comment...

**Comment by ahus1** [comment]
@pedroigor / @sschu - the update to Infinispan 14.x has been completed, see #12494. The main branch is currently on 14.0.2.Final 

@sschu - once you have an issue/PR for the Infinispan metrics ready, don't hesitate to ping me.

**Comment by sschu** [comment]
@ahus1 I am not sure, the update was essentially in https://github.com/keycloak/keycloak/pull/15601 but this was rolled back due to https://github.com/keycloak/keycloak/pull/15766.

**Comment by ahus1** [comment]
@sschu - although the Quarkus upgrade has been rolled back, the update of Inifispan stayed. I also talked to @mhajas about this, and as of now the Infinispan upgrade is there to stay. So KC21 will contain Infinispan 14.x, regardless of the rolled back Quarkus update.

**Pull request merged**
