### PR TITLE
Pass Admin Console client id when sending credential reset e-mail

### LINKED ISSUE #17857: New Admin UI does not send e-mails if account-client is disabled
### Describe the bug

The new admin UI does not send User-Mails if account client is disabled. Instead an error is shown "Client not enabled". In the browser console I can see a 400 bad-request error.

### Version

20.0.3

### Environment

Chrome, Windows

### Expected behavior

E-Mail is send

### Actual behavior

UI shows Error "Client is not enabled" and Mail not send.

### How to Reproduce?

1. Disable client "account"
2. Try to send a Mail via "Reset Actions" (e.g. in User -> Credentials -> Credential Reset -> "Update Password")
3. See Error "Client is not enabled" and Mail not send

### Anything else?

Workaround: Switch back to old Admin UI. Anything works as expected or enable account-client.

### PR DESCRIPTION
**Pull request by jonkoops**
Supersedes #20960. Closes #17857

### CODE REVIEW

**Review by agagancarczyk — APPROVED** [review]
LGTM!

**Comment by jonkoops** [comment]
Sounds good to me, I will put this on hold until the discussion has been resolved.

**Comment by pedroigor** [comment]
@rmartinc Running actions as part of the authentication flow is different than executing action tokens. We can't blindly trust how action tokens are executed and they should be constrained to run in the context of a user-facing client. That is probably one of the reasons why the endpoint defaults to the account client.

If you want to change email templates, or if we eventually enable specific capabilities to clients when executing their actions, we probably don't want to be forced to update the client used by the admin console.

We can't remove the parameter either because you might want your own client to manage the user account.

IMO, it is not just weird but unsafe to execute end-user actions within the scope of the security-admin-console.

**Comment by pedroigor** [comment]
I think we should wait for feedback from @mposolda to see what he thinks. I'm not sure about using the admin console client for this.

**Comment by jonkoops** [comment]
@mposolda any chance you could weigh in on this one?

**Comment by jonkoops** [comment]
Considering the lack of activity I am closing this PR.

**Pull request closed without merging**
