### PR TITLE
Upgrade to latest Infinispan version 14.0.8

### LINKED ISSUE #20067: Upgrading to Infinispan 14.0.8
### Description

Infinispan 14.0.8 is the latest release. When attempting an upgrade as part of #20011 there was an exception 

```
Caused by: java.lang.RuntimeException: Component org.keycloak.models.KeycloakSessionFactory is already registered
    at org.infinispan.factories.impl.BasicComponentRegistryImpl.registerComponent(BasicComponentRegistryImpl.java:368)
    at org.infinispan.factories.AbstractComponentRegistry.registerComponentInternal(AbstractComponentRegistry.java:133)
    at org.infinispan.factories.AbstractComponentRegistry.registerComponent(AbstractComponentRegistry.java:125)
    at org.infinispan.factories.AbstractComponentRegistry.registerComponent(AbstractComponentRegistry.java:117)
    at org.keycloak.models.sessions.infinispan.initializer.InfinispanCacheInitializer.initCache(InfinispanCacheInitializer.java:68)
    at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory$6.run(InfinispanUserSessionProviderFactory.java:342)
```

This issue is about to investigate it.

### Discussion

_No response_

### Motivation

To be able to upgrade to the latest version of Infinispan to benefit from the latest bug fixes. The exception shown above might prevent this.

### Details

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #20067

### CODE REVIEW

**Comment by ahus1** [comment]
Waiting for #20011 to be merged first.

**Comment by ahus1** [comment]
@mhajas - this build has now completed green, and includes the changes we discussed earlier today. I'd be happy if you could review it. Thanks!

**Review by vmuzikar — APPROVED** [review]
Thanks, @ahus1! LGTM from the Cloud Native side.

**Review by mhajas — APPROVED** [review]
Thanks @ahus1, LGTM

**Pull request merged**
