### PR TITLE
Allow changing the session id on login in Tomcat adapter

### LINKED ISSUE #8727: KeycloakAuthenticatorValve (Tomcat) does not implement createRequestAuthenticator()
### Describe the bug

Because of the missing override of createRequestAuthenticator(), the valve uses the CatalinaRequestAuthenticator instead of the TomcatRequestAuthenticator. The CatalinaRequestAuthenticator has no prevention against the session fixation attack. This security issue should be fixed as soon as possible.
see https://github.com/keycloak/keycloak/blob/dd69bb5d33d0ee825fcfc2f1a0502709a60fdacf/adapters/oidc/tomcat/tomcat/src/main/java/org/keycloak/adapters/tomcat/KeycloakAuthenticatorValve.java

### Version

9.0.3 - 15.0.2

### Expected behavior

Change of the session id after a successful login

### Actual behavior

Session id remains after login.

### How to Reproduce?

Check the session id before/after a login

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ammannmi**
Closes #8727

### CODE REVIEW

**Comment by crechberger** [comment]
any update?

**Review by pedroigor — APPROVED** [review]
@ammannmi Can you please rebase and update the PR?

**Comment by ammannmi** [comment]
@pedroigor - I merged the PR with the new commit now

**Comment by pedroigor** [comment]
Build https://cd-jenkins-csb-rhsso.apps.ocp4.prod.psi.redhat.com/job/keycloak-build-pipeline/424/.

**Comment by pedroigor** [comment]
@ammannmi Here we go again, sorry. The build is failing because your branch does not have a fix that allows resolving the new admin console artifact. Could you please, rebase?

**Comment by ammannmi** [comment]
Sorry, back again. I merged the pull request with the new commits now

**Comment by ammannmi** [comment]
merged again because build failed

**Comment by pedroigor** [comment]
@ammannmi Thanks, running CI to check adapter tests status: 449.

**Comment by pedroigor** [comment]
@ammannmi Tks.

**Pull request merged**
