### PR TITLE
GH Actions -> archive surefire reports (#21913).

### LINKED ISSUE #21913: GH Actions - Surefire reports artifact upload
### Description

QE requires archived Surefire Reports per particular release branch. This change will allow to archive such artifacts and be available for download, from different workflow or CI.

* store every test case -> TEST*.xml file per particular test suite in a separate folder
* trigger it per specified release branch and for events: push and workflow_dispatch
* initial retention policy: 1 day

### PR DESCRIPTION
**Pull request by lhanusov**
Closes #21913

### CODE REVIEW

**Comment by lhanusov** [comment]
@stianst @miquelsi Hi, please can you take a look on this PR, related to surefire reports? Currently it will be triggered only with release branch 22.0 and retention policy = 1 day.

**Comment by lhanusov** [comment]
Getting multiple artifacts from GH can be simply achieved by gh cli: gh run download 5621318494 -p surefire-*tests*.

**Review by stianst — CHANGES_REQUESTED** [review]
* Remove reference to internal JIRA.
* Refactor into a composite action. 
* Only trigger for push and workflow_dispatch events (not for pull_requests)

Can you also elaborate on how the logs will be fetched? Retention days 1 seems a bit short perhaps?

**Comment by lhanusov** [comment]
@stianst In case of the Surefire reports PR, do you think it's worth to convert it into composite action? I am not sure if it will spare the lines and still it will be multiplied.

**Comment by lhanusov** [comment]
@stianst @miquelsi Comments addressed, in case of the artifact handling and process explanation -> Another CI will poll scm every 10 minutes and will get GH surefire artifacts based on change -> GH webhook is for internal service impossible. The CI will store it for longer period. Those artifact will be uploaded to reporting tool only once per release (will select particular revision), manual approval. Does it make sense?

**Pull request closed without merging**
