### PR TITLE
Need to build feature packs before they are used.

### PR DESCRIPTION
**Pull request by ssilvert**

### CODE REVIEW

**Comment by stianst** [comment]
server-dist should have a dependency on the feature pack, it shouldn't rely on ordering

**Comment by ssilvert** [comment]
I agree.  Do you want me to fix it?

**Comment by stianst** [comment]
No thanks, I've fixed it already and will commit it once I get internet working again.

**Comment by ssilvert** [comment]
OK.  Glad I asked.  Sorry about your internet connection.  :-(

**Pull request closed without merging**
