### PR TITLE
Fixed Elasticsearch version

### PR DESCRIPTION
**Pull request by distinguished-sre**
- update Mongo https://docs.graylog.org/docs/upgrade
- update Graylog https://www.graylog.org/post/announcing-graylog-v4-3-3

### CODE REVIEW

**Comment by eabykov** [comment]
@DGuhr please also add option `snapshot.max_concurrent_operations: 1` https://www.elastic.co/guide/en/elasticsearch/reference/7.10/release-notes-7.10.2.html#known-issues-7.10.2

**Review by DGuhr — CHANGES_REQUESTED** [review]
@eabykov Thanks, I haven't looked up the compatibility matrix - just looked at the docker tags and used what worked :) That said: would you please create an issue and link it in the commit msg as per the [contrib guidelines](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md#submitting-your-pr)? Please also elaborate on `snapshot.max_concurrent_operations: 1` i am unsure if that is a config option you want in log-gelf namespace, or an addition to the examples, or sth else?!

**Comment by eabykov** [comment]
> Please also elaborate on `snapshot.max_concurrent_operations: 1` i am unsure if that is a config option you want in log-gelf namespace, or an addition to the examples, or sth else?!

@DGuhr this limit applies in total to all ongoing snapshot creation, cloning, and deletion operations. Elasticsearch will reject any operations that would exceed this limit. Default is `1000`. But if we use Elasticsearch `7.10.2` we have issue:
> If an index is deleted while the cluster is concurrently taking more than one snapshot then there is a risk that one of the snapshots may never complete and also that some shard data may be lost from the repository, causing future restore operations to fail. To mitigate this problem, prevent concurrent snapshot operations by setting `snapshot.max_concurrent_operations: 1`

So we need to add this option to the `docker-compose.yml` environment for the Elasticsearch:
```yaml
version: '3.8'

services:
  elasticsearch:
    image: docker.io/elastic/elasticsearch:7.10.2
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
      snapshot.max_concurrent_operations: "1"
    networks:
      - graylog
```

**Review by pedroigor — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@eabykov Thanks.

**Pull request merged**
