### PR TITLE
KEYCLOAK-8855: Store rewritten redirect URL in adapter-core

### PR DESCRIPTION
**Pull request by sakanaou**
We faced the problem that, while rewrite rules for redirect URLs are applied in general, they are not taken into account for the final redirect call in https://github.com/keycloak/keycloak/blob/master/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/RequestAuthenticator.java#L154

By storing the rewritten redirect URL the final redirect call also succeeds.

### CODE REVIEW

**Comment by stianst** [comment]
Thanks for your PR. Please create a JIRA and include a better description on why this is needed. Also we need a test-case for changes like this.

**Review by pedroigor — CHANGES_REQUESTED** [review]
Could you please provide a JIRA with more details about the problem you are solving ?

**Comment by sakanaou** [comment]
@pedroigor I have created https://issues.jboss.org/browse/KEYCLOAK-8855 with a detailed description of the issue.

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Comment by pedroigor** [comment]
@pedroigor tks, I'll now check if our testsuite is already covering this. Otherwise I'll be back with some information about how we can write a test for it.

**Review by pedroigor — DISMISSED** [review]

**Review by pedroigor — CHANGES_REQUESTED** [review]
@sakanaou , could you please include tests from this commit https://github.com/pedroigor/keycloak/commit/304975106fbdfd56f6fdd77e83adbdf4c4fa7f38 ?

It should work fine with your changes and it provides more coverage to rewrite configuration.

**Comment by sakanaou** [comment]
@keycloak-ci-bot test

**Comment by hmlnarik** [comment]
@pdrozd Could you please confirm whether this can go to 4.x or 5.x?

**Comment by pedroigor** [comment]
@hmlnarik @pdrozd LGTM. Can we get this in? I think it is an important fix in order to get rewrite rules applied properly.

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Review by pdrozd — APPROVED** [review]
LGTM

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
