### PR TITLE
KEYCLOAK-11781 Some dutch translations contain strange characters

### PR DESCRIPTION
**Pull request by codemasterover9000**
Fixes a display error with Dutch translations containing accented characters.
Bug report: https://issues.jboss.org/browse/KEYCLOAK-11781

### CODE REVIEW

**Review by stianst — CHANGES_REQUESTED** [review]
It would probably be better to add "# encoding: utf-8" to the top of the file, as that makes it readable. See messages_ja.properties for an example.

**Comment by codemasterover9000** [comment]
That's not in the [spec](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html). Which tool implements that?

**Comment by stianst** [comment]
Keycloak does ;)

**Comment by codemasterover9000** [comment]
The title of this PR doesn't reflect the actual change anymore, is that a problem?

**Comment by stianst** [comment]
Created a new clean PR with the single commit that sets encoding here: https://github.com/keycloak/keycloak/pull/6420

**Pull request closed without merging**
