### PR TITLE
KEYCLOAK-15434 Http proxy settings ignored by X509 Auth CRL Distribution Point check

### PR DESCRIPTION
**Pull request by lscorcia**
In an Authentication flow set up with an `X509 browser flow` to authenticate users with digital certificate, if the option `Enable CRL Distribution Point to check certificate revocation status` is set, Keycloaks' proxy settings are not used when doing the CRL Distribution Point verification, and if the `http_proxy`/`https_proxy` env vars are not set globally, Keycloak is not able to download the CRL from the remote path.
This is because the CRL downloader uses the `URLConnection` class which only picks up the system proxy settings, but not Keycloak ones. This PR replaces its usage with an `HttpClientProvider` invocation.

The tests are already present: https://github.com/keycloak/keycloak/blob/1fa93db1b4df7c2133004d4ac96a0134372c7cb5/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/X509BrowserCRLTest.java#L179
It seems to me that there is no way to actually configure the test setup to prepare the appropriate proxy configuration. Any suggestions? I have tested the build in my target environment and with the changes it works fine.

By the way, the same problem is present for OCSP validation but it's much harder to fix it there because its code is in a different package and lacks the required dependencies (`common/src/main/java/org/keycloak/common/util/OCSPUtils.java#L161`).

### CODE REVIEW

**Review by slaskawi — APPROVED** [review]
The code itself LGTM. Perhaps @vmuzikar or @mposolda have any idea about the testsuite.

**Comment by vmuzikar** [comment]
I haven't investigated the issue here much deeply but maybe we could use some lightweight test proxy class like [this](https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/ReverseProxy.java)?

**Comment by lscorcia** [comment]
Thanks for your input. I'm actually wondering if additional tests are really needed, considering that it's not a new feature. I'm just swapping one implementation class with another that already has its tests. What do you think?

**Comment by lscorcia** [comment]
I am closing this pull request as it has been superseded by #7534 .

**Pull request closed without merging**
