### PR TITLE
Revise use of Keycloak term

### LINKED ISSUE #27953: Address feedback to Keycloak Server guide
### Description

Making changes in upstream for the use of "Keycloak" for reuse in downstream.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andymunro**
Closes #27953

Signed-off-by: AndyMunro <amunro@redhat.com>
(cherry picked from commit f2fb3d9bf3a6938024502d8f7a90402c14af3d68)

@ahus1 please approve

### CODE REVIEW

**Review by ahus1 — APPROVED** [review]

**Comment by andymunro** [comment]
Branch updated. Is this ready to be merged, @ahus1?

**Comment by ahus1** [comment]
@andymunro - please don't add merge commits to this branch. I now see that it has 3 commits due to that. 
I'll squash those commits now. No further action is necessary from your side. Thanks.

**Comment by andymunro** [comment]
Thanks for the correction, @ahus1. It's too early here.

**Comment by andymunro** [comment]
Thanks for the fix @ahus1

**Pull request merged**
