### PR TITLE
Provide an HTTP 503 response when the thread pool rejected the request

### LINKED ISSUE #21962: Minimal load shedding support for incoming requests
### Description

When doing performance and chaos tests for Keycloak in the Keycloak Benachmark project, we've seen a large number of request queuing up in Keycloak, leading to long wait times. 

We're now experimenting with limiting the number of threads and the queue size: 

QUARKUS_THREAD_POOL_MAX_THREADS=30
QUARKUS_THREAD_POOL_QUEUE_SIZE=1000

When doing this, Keycloak will log errors, as there is no proper response created in Keycloak. 

This can be tested when opening the welcome page of Keycloak:

QUARKUS_THREAD_POOL_MAX_THREADS=1
QUARKUS_THREAD_POOL_QUEUE_SIZE=1

### Motivation

Support load shedding, as queuing the requests in Keycloak leads to pod restarts and overloading components.

CLI options for Keycloak could be added later, this will be "just" for avoiding the errors in log, and providing a more proper response. 

### Details

I'll prepare a PR for this. I've created an issue at Quarkus upstream to provide metrics for the thread pool: https://github.com/quarkusio/quarkus/issues/34998

### PR DESCRIPTION
**Pull request by ahus1**
This allows for limiting the queue of the thread pool to avoid overloading Keycloak.

Closes #21962

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Review by vmuzikar — CHANGES_REQUESTED** [review]
Thanks for the PR @ahus1. This change makes sense to me, although I still think it'd make sense to have this logged (perhaps as a warning?) on top of the HTTP 503 response. That'd help to make it clear what's happening to a user who's not very familiar with the internals.

**Comment by ahus1** [comment]
@vmuzikar - logging a warning for each dropped request would be an anti-pattern as it would amplify the load on the logging system. In our load tests I expect this to drop thousands of messages in an overloaded situation.

I've updated this PR to log a warning when Keycloak starts dropping requests and then another warning once it continues processing with an approximation of the dropped requests. 

The output is as follows: 

> 2023-07-26 11:36:01,982 WARN  [org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter] (vert.x-eventloop-thread-0) Executor thread pool exhausted, starting to reject requests
2023-07-26 11:36:02,031 WARN  [org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter] (vert.x-eventloop-thread-0) Executor thread pool no longer exhausted, request processing continues after 4 discarded request(s)

We can tune this more once we see it is useful in our tests.

**Review by vmuzikar — APPROVED** [review]
@ahus1 Thanks for the update.

Yeah, makes sense to aggregate the logs to just start and end of the pool exhaustion.

**Comment by sschu** [comment]
@ahus1 Would it be possible to expose the number of rejected requests and also the waiting queue length as metric?

**Comment by ahus1** [comment]
@sschu - I've raised an issue here: https://github.com/quarkusio/quarkus/issues/34998

I still need to reply there, as I think Vert.x is not exposing of all the metrics we would want to see. 

When running with the OTEL agent, I saw the 503 in the responses as a counter, which was working for me.

The current queue length would be nice indeed. Maybe even nicer: A histogram of the queue length capturing the length of the queue when something was added, so we wouldn't be limited to the value which is polled every some seconds? But I think the chances to get that would be nearly zero.

**Pull request merged**
