### PR TITLE
KEYCLOAK-18891 Add support for searching users by attributes

### PR DESCRIPTION
**Pull request by bartmentech**
Users can now be searched by custom attributes using query parameters. Any query parameters that are not in the list of method arguments will be considered to be custom attributes. In this implementation query keys need to be unique, otherwise the first value is assumed.

Because the JAX-RS client does not support dynamic query parameters, a Map will be accepted as query parameters for custom attributes, it will be flattened to query parameter by a request filter.

### CODE REVIEW

**Review by zabih-alipour — DISMISSED** [review]
LGTM
Thank you for your efforts.

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Thank you for the PR. Search by attribute logic and schema needs to be consistent with existing client attribute search (#7870) and also needs to be working for the map store. Please update the PR accordingly without introducing yet another specific method for search.

**Comment by bartmentech** [comment]
@hmlnarik Thanks for the review, I will get back to this in a few weeks.

**Comment by bartmentech** [comment]
@hmlnarik Any indication when you can review this?

**Comment by hmlnarik** [comment]
@bartmentech Thank you for the PR. The changes seem being in the right direction, but there are test failures. Could you please rebase and fix those?

**Review by vramik — CHANGES_REQUESTED** [review]
Thank you @bartmentech for the PR. Overall it looks good to me, thanks. I have just two things regarding the javadoc and in the end commits should be squashed.

**Review by vramik — APPROVED** [review]
Thank you @bartmentech, lgtm.

**Review by hmlnarik — APPROVED** [review]
Approving based on @vramik's review. Thank you for the PR!

**Pull request merged**
