### PR TITLE
KEYCLOAK-10095 Cordova logout fix - show logout window and do not auto login

### PR DESCRIPTION
**Pull request by richardyee**
1. There is an interactive logout from Microsoft's v2 of its OAuth2 logout endpoint - by default do not hide Cordova browser window for logout and follow existing pattern already used for login (where the window options are generated by createCordovaOptions function). Window can be hidden using the same options that are passed into login (where prompt = 'none'). The window automatically closes if no user interaction is required.
2. Also, do not auto-login after a logout.  This causes a race-condition with the Cordova in app browser on Android, since the previous window (even if hidden) is closing while the new window to login is opening.  Since it's an explicit call to logout, then a second explicit call to login should be made if that is required.

### CODE REVIEW

**Comment by abstractj** [comment]
@edewit I believe you would be the best candidate to review a PR related to Cordova. //cc @ssilvert

**Comment by edewit** [comment]
@richardyee how can we test this?

**Comment by richardyee** [comment]
@edewit how was this tested before?  I can re-use that process ideally.

**Comment by edewit** [comment]
We have this java based test case:
https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java#L64

**Comment by ssilvert** [comment]
@richardyee @edewit Any progress on this?

**Comment by ssilvert** [comment]
I think I'll just close this due to inactivity.  We can reopen if needed.

**Pull request closed without merging**
