### PR TITLE
fix kc.sh for cygwin

### LINKED ISSUE #12130: kc.sh fails on cygwin
### Describe the bug

Hello,

since there is explicit support for cygwin in kc.sh, it would be nice if it also works.

If this issue is accepted, I can also provide a PR to fix the two issues described below (and replace the backticks):

https://github.com/keycloak/keycloak/compare/main...elkman:feature/fix_kc.sh_cygwin

Perhaps someone could test the change for Darwin and FreeBSD, to which I currently have no easy access.

cheers

### Version

18.0.0

### Expected behavior

1. no bash syntax error
2. pass path parameters in windows style to JVM process

### Actual behavior

1. bash syntax error
2. path parameters are passed in cygwin style to JVM process

### How to Reproduce?

1. call kc.sh inside cygwin environment -> syntax error `bin/kc.sh: line 5: CFILE: command not found`

2. fix 1. and call kc.sh -> entry point io.quarkus.bootstrap.runner.QuarkusEntryPoint not found due to wrong path to quarkus-run.jar 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by elkman**
Closes #12130

Fixes kc.sh to work in a cygwin environment.

The detailed problems and fixes for this PR are described with #12130.

I'm not sure if I should squash the two commits or better keep the different concerns separate (maybe in two PRs).

### CODE REVIEW

**Comment by elkman** [comment]
The failed _test remote_ does not seem to be related to this change.

**Comment by elkman** [comment]
@DGuhr / @andre-nascimento-rh just rebased my PR to latest main

**Comment by pedroigor** [comment]
@elkman Sorry for the delay. Would you be interested in moving forward with the changes? In addition to cygwin support, I think it also brings a bit more sanity to `kc.sh`. If you can rebase and resolve the conflicts I'll test your changes in addition to running our testsuite.

**Comment by elkman** [comment]
Hi @pedroigor,

I have rebased the PR. Unfortunately I don't have Cygwin and Linux clients to test the changes because I'm on vacation, but I think the changes are pretty safe (macOS looks ok). But if you could test all environments, it wouldn't hurt.

Do I have to worry about the build/test failuers in module-tests shown for the old PR state?

**Comment by pedroigor** [comment]
@elkman Thanks. No, you shouldn't worry about model test failures.

I run some tests locally and your changes look fine for Windows.

I did not check yet Windows/cygwin though as I was expecting they were tested. But I do it.

In any case, the changes help to improve the script code.

**Comment by pedroigor** [comment]
@elkman I run on Windows using cygwin and got the following:

```
$ ./kc.sh start-dev
./kc.sh: line 2: $'\r': command not found
./kc.sh: line 3: syntax error near unexpected token `$'in\r''
'/kc.sh: line 3: `case "$(uname)" in
```

It seems to work fine on Linux.

**Comment by elkman** [comment]
@pedroigor Looks like a line ending problem in kc.sh but I cannot see this problem, even after I updated my branch on cygwin.

Is their any on-the-fly line ending conversion active or needed?

CR (\r) looks like macOS, but I check out or download the raw version from github I get LF (\n) (on Win/cygwin).

(Why do we still have to struggle with line endings in 2022?)

**Comment by pedroigor** [comment]
@elkman Sorry, false alarm from my side. I actually copy/paste the code and messed it up.

Thanks for your contribution!

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
