### PR TITLE
Map Store Removal: deprecate model legacy module

### LINKED ISSUE #26598: Map Store Removal: deprecate model legacy module
Follow-up to https://github.com/keycloak/keycloak/pull/26273. We should first deprecate classes in model/legacy and remove it in a later release. Also mention this in the upgrading guide.

### PR DESCRIPTION
**Pull request by martin-kanis**
Closes #26598

### CODE REVIEW

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for this PR. I see that you copied over the old classes to the legacy module. 

Could you instead try the following: Create "empty" classes and interfaces which inherit from the new ones? The `pom.xml` should then contain as a dependency only the new module. 

WDYT?

**Comment by martin-kanis** [comment]
@ahus1 That makes sense. Please have a look.

**Review by ahus1 — APPROVED** [review]
LGTM, thank you for the change.

**Comment by martin-kanis** [comment]
@ahus1 Follow-up PR for quickstarts https://github.com/keycloak/keycloak-quickstarts/pull/533

**Pull request merged**
