### PR TITLE
Manipulate OpenID redirect-response with custom implementation

### LINKED ISSUE #31086: Manipulate redirect on OpenID redirect with custom implementation
### Description

We have a slightly modified OpenID protocol that follows the standard but with some additional parameters that must be returned from the OpenID login. 
There are two possible solutions:
1. Creating a new SPI that can be implemented and that is used to expand the redirect with custom parameters.
2. adding overridable methods to class `OIDCLoginProtocol` override it with a custom implementation that extends the class `OIDCLoginProtocol`. This class can then override the new methods that build the redirectUri and will allow to add additional parameters if needed. (This would also be my preferred solution since it is an uncommon scenario and thus some new ProviderFactories would be an overkill here.)

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by Captain-P-Goldfish**
fixes #31086

### CODE REVIEW

**Review by tnorimat — APPROVED** [review]
LGTM.

**Comment by tnorimat** [comment]
@mposolda The PR lacks the test codes, but the current Keycloak's test codes are enough for regression.

**Comment by mposolda** [comment]
@Captain-P-Goldfish @tnorimat Thanks for the PR and review.

Question: Do we really need 3 new methods added to OIDCLoginProtocol? Is it ok to go with single method having all the arguments possibly with the `null` arguments passed in some calls?

**Comment by Captain-P-Goldfish** [comment]
> @Captain-P-Goldfish @tnorimat Thanks for the PR and review.
> 
> Question: Do we really need 3 new methods added to OIDCLoginProtocol? Is it ok to go with single method having all the arguments possibly with the `null` arguments passed in some calls?

You are right. I have broken it down to 2 methods. One for error responses and the one for success

**Review by mposolda — APPROVED** [review]
@Captain-P-Goldfish Thanks for the update!

**Pull request merged**
