### PR TITLE
fix: removing erroneous warnings

### LINKED ISSUE #33638: Non-optimized start command gives erroneous warnings for runtime spi options
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

A non-optimized start command gives erroneous warnings for runtime spi options:

2024-10-07 16:52:42,791 WARN [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following run time options were found, but will be ignored during build time: kc.spi-realm-restapi-extension-mytest-identity-provider-vault-password ...

### Version

26.0

### Regression

- [X] The issue is a regression

### Expected behavior

No warnings should be emitted.

### Actual behavior

A warning about runtime spi options being ignored.

### How to Reproduce?

Run a non-optimized start command that includes a runtime spi option, or a value that maps to one such as --hostname-strict=false.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #33638

A targeted version of #33648 for quick inclusion / backporting.

### CODE REVIEW

**Review by vmuzikar — APPROVED** [review]
@shawkins Thanks for the fix. We can do the [further optimizations](https://github.com/keycloak/keycloak/pull/33648) as a follow up targeting main only.

Is this ready to be merged?

**Comment by shawkins** [comment]
> Is this ready to be merged?

Yes, was just waiting for the tests to run clean before moving it out of draft.

**Comment by vmuzikar** [comment]
@shawkins Can you please create the backport?

**Comment by shawkins** [comment]
> @shawkins Can you please create the backport?

https://github.com/keycloak/keycloak/pull/34008

**Pull request merged**
