### PR TITLE
[KEYCLOAK-18030] Upgrade Freemarker

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Comment by martin-kanis** [comment]
@abstractj @pskopek This will require productization of Freemarker 2.3.31 in PNC.

**Comment by abstractj** [comment]
@martin-kanis @pskopek added you guys to the Jira, so we can decide what to do about this.

**Comment by drichtarik** [comment]
@martin-kanis @abstractj I'm on it

**Comment by abstractj** [comment]
Thank you Denis!

**Review by drichtarik — APPROVED** [review]

**Pull request merged**
