### PR TITLE
KEYCLOAK-15459 Fix serialization of multi-subtag locales in admin console's “whoami” response

### PR DESCRIPTION
**Pull request by devopsix**
* Serialize locale as a well-formed IETF BCP 47 language tag.
* Alter test to cover a locale made of more than one subtag.

### CODE REVIEW

**Comment by rushairer** [comment]
When can I merge this code and fix the bug?

**Review by rushairer — COMMENTED** [review]
When can I merge this code and fix the bug?

**Comment by ssilvert** [comment]
@abstractj I am unable to restart tests to get them passing.  Are you able to do this?

**Comment by abstractj** [comment]
@ssilvert let me give it a try

**Review by ssilvert — APPROVED** [review]

**Pull request merged**
