### PR TITLE
KEYCLOAK-10700 non blocking desktop login and logout

### PR DESCRIPTION
**Pull request by dpolivaev**
https://issues.jboss.org/browse/KEYCLOAK-10700

### CODE REVIEW

**Comment by dpolivaev** [comment]
~~~~
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.concurrent.CompletableFuture;

import org.keycloak.representations.AccessToken;

public class LoginAsync {

    public static void main(String[] args) throws Exception {
        KeycloakInstalled keycloak = new KeycloakInstalled();
        final CompletableFuture<Void> loginDesktopAsync = keycloak.loginDesktopAsync();
        loginDesktopAsync.thenAccept(v ->
        {
            AccessToken token = keycloak.getToken();
            System.out.println("Logged in as " + token.getPreferredUsername());
        })
        .whenComplete((x1, t1) -> {
			if(t1 != null)
				t1.printStackTrace();
            try {
				CompletableFuture<Void> logoutAsync = keycloak.logoutAsync();
				logoutAsync.whenComplete((x2, t2) -> {
					if(t2 == null)
						System.out.println("Logged out");
					else
						t2.printStackTrace();
				});
			} catch (IOException | InterruptedException | URISyntaxException e) {
				throw new RuntimeException(e);
			}
            System.out.println("Completed");
        }
        );
       System.out.println("Started");
       Thread.sleep(10000);
       loginDesktopAsync.cancel(false);
       System.out.println("Main finished");
    }
}

~~~~

**Comment by dpolivaev** [comment]
Use of the old blocking API
~~~~
import org.keycloak.representations.AccessToken;

public class StarterSync {

    public static void main(String[] args) throws Exception {
        KeycloakInstalled keycloak = new KeycloakInstalled();
        keycloak.loginDesktop();
        AccessToken token = keycloak.getToken();
        System.out.println("Logged in as " + token.getPreferredUsername());
        keycloak.logout();
		System.out.println("Logged out");
		System.out.println("Completed");
    }
}
~~~~

**Comment by dpolivaev** [comment]
I have not written automatic tests because I have not found any other tests for the desktop login in the entire code base.

**Comment by stianst** [comment]
Hi, thanks for the PR. I would like to put this on hold a little bit as we need to rewrite KeycloakInstalled since we have decided to remove kcinit.

**Comment by stianst** [comment]
It'll be a while until we get a chance to remote kcinit and refactor KeycloakInstalled, so let's just try to get this merged.

@dpolivaev would you be able to resolve merge conflicts?

**Comment by dpolivaev** [comment]
@stianst I am going to do it  in December before Christmas.

**Comment by dpolivaev** [comment]
@stianst conflicts resolved. I have not tested the result now because of the long break we had.

In my project I have to use my proprietary version because of https://issues.redhat.com/browse/KEYCLOAK-10752,  https://issues.redhat.com/browse/KEYCLOAK-10790 and unnecessary dependency on ResteasyClient which makes troubles with ivy / sbt build

**Comment by stianst** [comment]
Since this PR is getting quite old and there is no progress here I'm going to close it. I appreciate that lack of progress is most likely down to lack of review/response on our end, so feel free to open a new PR for this if there is still interest in contributing this, and we will try our best to be more responsive next time.

**Pull request closed without merging**
