### PR TITLE
[KEYCLOAK-13393] Account2 marked as experimental

### PR DESCRIPTION
**Pull request by abstractj**
@ASzc @ssilvert running more tests here only to be safe. But I'd appreciate your input if you have some time.

## Instructions to run the tests

- https://github.com/vmuzikar/keycloak/blob/5091f5452b04a2424cd0bf9b38109efa31847264/themes/src/main/resources/theme/keycloak-preview/account/resources/README.md#running-tests

### CODE REVIEW

**Comment by ssilvert** [comment]
@stianst I haven't been able to find anywhere that the "EXPERIMENTAL" designation is being used.  Looking at the history, it appears that we wanted a different designation for account console because it was not code complete.

Maybe we can get rid of EXPERIMENTAL altogether now?

**Comment by abstractj** [comment]
@ssilvert +1 I can do the changes about this. I will just wait to hear if @stianst has any objections about this.

**Comment by stianst** [comment]
Experimental should remain

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
Docs PR here https://github.com/keycloak/keycloak-documentation/pull/883

**Pull request merged**
