### PR TITLE
KEYCLOAK-19489 Verify WebAuthn settings in admin console

### PR DESCRIPTION
**Pull request by mabartos**
JIRA: [KEYCLOAK-19489](https://issues.redhat.com/browse/KEYCLOAK-19489)

@mposolda @miquelsi @Pepo48 Could you please take a look at it? Thanks.

### CODE REVIEW

**Comment by mposolda** [comment]
@mabartos Thanks for the console tests!

Few questions:
- Do we have successful pipeline run for this? I am just asking, but I am not saying that we need successful pipeline run for each PR as long as you guys from QA team are fine with it. So for example if WebAuthn tests are temporarily broken after some PR, there will be a plan to quickly fix them in a follow-up PR.

- WebAuthn feature is still disabled for RHSSO. And AFAIK WebAuthn tabs are not shown in RHSSO in the admin console? Will the new tests pass with RHSSO? I guess it can be an issue as I don't see any "Feature checks" for the WebAuthn feature for the new tests unless I am missing something? Again, I am fine with WebAuthn tests not yet working with RHSSO as long as you have a plan to make it working with the follow-up PRs.

In shortcut: I am fine with the WebAuthn tests "temporarily broken" as long as it will simplify the work for the other PRs (EG. if you prefer to run pipeline after some more PRs is done and make it working for both Keycloak and RHSSO)

**Comment by mabartos** [comment]
@mposolda Thanks for your feedback!

> Do we have successful pipeline run for this? I am just asking, but I am not saying that we need successful pipeline run for each PR as long as you guys from QA team are fine with it. So for example if WebAuthn tests are temporarily broken after some PR, there will be a plan to quickly fix them in a follow-up PR.

Not as this moment, I noticed that there are a few failing tests in pipeline. Those tests passed on my local machine, so those failures are mostly related to some runtime issues. It might be solved easily. However, I'd like to have all newly added tests successful. I'll probably solve this today.

> WebAuthn feature is still disabled for RHSSO. And AFAIK WebAuthn tabs are not shown in RHSSO in the admin console? Will the new tests pass with RHSSO? I guess it can be an issue as I don't see any "Feature checks" for the WebAuthn feature for the new tests unless I am missing something? Again, I am fine with WebAuthn tests not yet working with RHSSO as long as you have a plan to make it working with the follow-up PRs.

To be honest, I didn't try to execute those tests with RHSSO. However, I believe it'll work, because the tabs are displayed regarding the feature status and for the RHSSO the feature is enabled. I'd like to create a "whole-grained" testsuite for WebAuthn and then polishing it.

**Comment by mabartos** [comment]
@mposolda Pipeline tests passed.
See https://keycloak-jenkins.com/job/universal-test-pipeline-server/1048/

**Review by mposolda — APPROVED** [review]
@mabartos Thanks!

**Pull request merged**
