### PR TITLE
Removing testsuite/performance from main Keycloak repository

### LINKED ISSUE #14192: Removing testsuite/performance from main Keycloak repository
### Description

The dataset provider and the Gatling tests are now available in the kecloak-benchmark repository.

This issue is about to remove the folder `testsuite/performance` from the main Keycloak repository, as all new developements will take place in `keycloak-benchmark`.

While not all functionality like for example a cross-dc Infinispan setup, this will eventually be added to the keycloak-benchmark project when needed.

### PR DESCRIPTION
**Pull request by ahus1**
There's a separate repository keycloak-benchmark for this.

Closes #14192

### CODE REVIEW

**Comment by ahus1** [comment]
Hi @kami619 / @tkyjovsk - this removes the old performance tests suite from the main Keycloak repository as previously discussed in the ticket. 

It would be good if one of you could review and approve this PR so it can be merged. Thanks!

**Comment by kami619** [comment]
@ahus1 thanks for the PR,I will review and get back if any further changes are needed. At the first glance, it seems to be covering everything thats needed.

**Comment by tkyjovsk** [comment]
@ahus1 LGTM.

**Review by tkyjovsk — DISMISSED** [review]
@ahus1 LGTM.

**Comment by ahus1** [comment]
Rebased due to new CI checks in main.

**Comment by kami619** [comment]
everything looked from my end as well @ahus1 I can re-approve this PR, once the CI jobs are completed

**Comment by ahus1** [comment]
@kami619 / @tkyjovsk - ready for a re-approval.

I don't consider the CodeQL alert valid as this PR only removes code.

**Review by kami619 — APPROVED** [review]
lgtm, even though looks like, @tkyjovsk have to approve this again, as I dont have write access to this git repo and @ahus1 do you wanna mark this PR out of draft state ?

**Comment by ahus1** [comment]
It is no longer in draft as the build have now passed. Thanks for the review. As before, I don't consider the CodeQL alert valid as this PR only removes code.

**Review by stianst — APPROVED** [review]

**Pull request merged**
