### PR TITLE
KEYCLOAK-2463 Fix performance issue with just 2 default connections p…

### PR DESCRIPTION
**Pull request by mposolda**
…er route in Apache HTTP client

### CODE REVIEW

**Comment by stianst** [comment]
Isn't 100 per route and Max 200 connections to much? That's a lot of threads and concurrent requests

**Comment by mposolda** [comment]
Not sure about best defaults. I looked for the inspiration in this post: http://dev.bizo.com/2013/04/sensible-defaults-for-apache-httpclient.html . What's your proposal for default values?
Right now, we have 200 max and 2 per route, which doesn't have much sense.

**Comment by mposolda** [comment]
Btv. adapter is using 20 max and 20 per route . IMO it makes sense to have both same as adapter communicates just with Keycloak server. Is that good default or should we rather increase a bit?

**Comment by mposolda** [comment]
Another question is, if socketTimeout and connectionTimeout should be kept to -1 or rather changed to some better defaults? According to blog, -1 can cause issues.

**Comment by mposolda** [comment]
I am going to run some performance test with enabled logging for Apache HTTPClient connection pool. Maybe that could help too.

**Pull request merged**
