### PR TITLE
KEYCLOAK-7043 Certificate Expiration Notification Feature

### PR DESCRIPTION
**Pull request by benjaminjacobberg**
**Description**
You can now setup email notifications for when certificates in the realm(s) and client(s) are about to expire (or have already expired).

**High Level Overview of Changes**
Front-End: Incorporated a field to the "Realm Settings" tab "Email" called "Certificate Notification Email Address" where you enter an email address that you want to have certificate expiration notifications sent to.
Back-End: Created classes that are scheduled to check both the realm(s) and client(s) for certificates that have or are about to expire.

**Testing**
Created unit tests for added code and Travis-CI tests pass.

**JIRA**
_Link_: [KEYCLOAK-7043](https://issues.jboss.org/browse/KEYCLOAK-7043)
_Description_: Certificates in the realm(s) and client(s) need to send out an email notification if they are about to expire (or have already expired).

### CODE REVIEW

**Comment by stianst** [comment]
Please open a discussion around this on the keycloak-dev mailing list

**Review by stianst — COMMENTED** [review]
A few comments here:

* Please remove changes to import and other formatting changes
* We do not use Mockito for testing so please don't introduce that. Look at other existing tests on how we tests
* This needs to be a feature that can be enabled/disabled. By default it should be disabled
* It should be configured to notify a specific user, not by taking a specific email address. That would remove the need to make changes to EmailSenderProvider as well
* I'm concerned with this impacting performance in cases where there are loads of realms and many clients per realm. I would rather prefer an option that checks the certificates when they are being used rather than periodically scans everything. That would also make it easier to make it configurable on a per-realm basis.

**Comment by cainj13** [comment]
@stianst Thanks for the feedback!  Some follow-up questions:

- When you say "feature", do you mean simply being able to disable this at the realm level, or a switch similar to what tech preview flags do?
- On the note of making this notify a specific user - that seems like a really untenable solution for managing multiple disparate realms.  For instance, if I've got several realms to manage disparate domains, potentially backed by different stores (I.E. corporate LDAP, web user DB, Keycloak DB, etc), we have the task of creating and maintaining a service account in each realm and potentially disparate system of information?  I get that it's already user-centric in implementation, but this seems like a logical extension of administrative functionality.
 - I'd worry that checking the certificate *only* when it's being used could result in something like an expiry notification being missed, or hampering lead time.  Suppose there's a seasonal application (around summit, fiscal reporting, take your pick) that goes unused for a large part of the year.  If it went unused for an arbitrary expiration lead time (say 30 days), and then someone went to authenticate against the client, it's possible that the administrators would only be notified of certificate expiry on failure.  Admittedly, not the mainstream use case, but if we were to work to scan on really long intervals and do so in a light of fashion as possible here, can we come to some compromise?

**Comment by stianst** [comment]
@hmlnarik @mposolda can you guys join the conversation here please :)

**Comment by stianst** [comment]
* Not sure what is best. Switch on realm or switch similar to Docker protocol. It should probably be disabled by default though?

* I agree we should just use email like what you've done. I was mainly thinking about the use-case where someone within the realm is responsible for managing, but that is obviously not always (probably most often) not the case. Rather than calling it certification notification email would it be better to make it more generic? Something like realm admin notification email? I can see it being used for other things in the future.

* I agree that simple checking on use only is not sufficient. I didn't consider infrequently used applications.

* For situations where there are few realms and not to many clients everything will be in the cache in either case so periodically scanning won't be an issue. However, we are going to work on supporting large number of realms soon (100-1000 realms per server) and some have 10K+ clients. I'm worried in those cases that doing a large scan of everything will result in a stop the world scenario. A longer interval won't affect how long the world is stopped, but rather just making it less frequent. Perhaps this may be tricky to implement, but what about building a list table of expiration times? That could be updated when certificates are added. With that checking for expired certificates is a simple SQL query that will only return results that are indeed expired.

**Comment by mposolda** [comment]
- I agree that it will be better to use configured email address rather than UserModel. I can also imagine even more - having possibility to override the email address per client. As there might be environments with thousands clients where it makes more sense to send the email to the administrator of client "foo" rather than always send it to per-realm admin email. But that can be added in the future if needed...

- I agree about adding the list table of expiration times. Especially considering that converting strings to certificates (method "convertStringToCertificate" ) is likely quite expensive operation. It will need to ensure that table is updated always when certificate is added or updated.

- This is not specific to this PR, but we need to improve on periodic jobs though. For example if you have cluster with 5 nodes, then the administrator may receive the email 5 times. Moreover if you have 2 datacenters and each having 5 nodes, then he may receive it 10 times. The ClusterAwareScheduledTaskRunner just prevents the task from running in case that it's already running at this moment on other cluster node. This is sufficient for things like periodic check of expired events or userSessions, however for this periodic notification it's not so great as admin can still receive many emails. Will be good to have better support for this use-case to ensure that just 1 node on single datacenter will send notifications. But that will probably need to be separate PR...

**Comment by cainj13** [comment]
@stianst here!  @benjamin-berg  is set to be back tomorrow.  I'll see if he can poke this and address some of the feedback.

**Comment by thomasdarimont** [comment]
An alternative to sending an email would be to have an `Advisory` section in the admin console.
This section could have a view with a table of action items like: `Certificate for xxx is about to expire in xxx days` with some links to actions or documentation about how to proceed.

**Comment by mposolda** [comment]
NOTE: I referenced this PR in the keycloak-dev mailing list discussion: http://lists.jboss.org/pipermail/keycloak-dev/2018-August/011157.html

**Comment by mposolda** [comment]
This is nice feature, but I consider to close this PR or mark as "Incomplete" (or with some other flag, which would signal that PR is useful just for the future reference). As the PR has few issues as mentioned above. Most important IMO are:

- It is quite bad for performance. Iterating over realms and clients and manually retrieve the certificate to check the time is performance killer. It will be good to track the times of certificate expiration separately - either as attribute of the client/realm or separate table. We may also need to re-use this for other "Certificate" types - not just for realm RSA keys and the "saml.signing.certificate" of client.

- The periodic task may be triggered on all cluster/cross-dc nodes. Hence if there are 5 nodes in the cluster and 2 datacenters, admin may receive 10 mails as task may be triggered 10 times. This is general issue in Keycloak (not specific to this PR), but with this PR it will be quite visible.

- Other minor things in the PR (mockito etc)

**Comment by mposolda** [comment]
I am closing the PR and commented in the JIRA. If you want to re-visit in the future, we can discuss in the JIRA or on keycloak-dev mailing list.

**Pull request closed without merging**
