### PR TITLE
KEYCLOAK-10757 Replaying assertion with signature in SAML adapters

### PR DESCRIPTION
**Pull request by hmlnarik**

### CODE REVIEW

**Review by sguilhen — CHANGES_REQUESTED** [review]
Overall this PR looks good but it is missing a couple of things:

1- I don't see the new attribute in the keycloak-saml schema. I'm not sure if you need to bump the version or not. @hmlnarik What is the policy for bumping the schema version? In WF, the current version can be updated if it hasn't been part of a .Final release. Otherwise you need to create a new schema and bump the version.
 - It would also be good to update the KeycloakSamlAdapterXMLParseTest to use the updated schema and check if the new attribute is being correctly parsed.

2- Every change to keycloak-saml.xml should be reflected in the keycloak-saml subsystem. So this PR is missing the changes to the subsystem to make it consistent with the adapter.

3- It is also missing the documentation for the new attribute. Please add a brief section to the saml adapter documentation and link the PR for the doc here.

**Comment by hmlnarik** [comment]
@sguilhen Thanks for the review. We can employ the same policy, i.e. only increase schema version with new WF.

**Comment by rmartinc** [comment]
@sguilhen Ok, I think that I have done the three changes. It was harder than expected (a lot of things should be changed). I tested with EAP6 and widlfly 17 and the `keepDOMAssertion` works for the configuration inside the standalone.xml.

The PR for documentation is:
https://github.com/keycloak/keycloak-documentation/pull/721

I'll be off the next two weeks, so if something more is needed I'll try to do it when I come back.

**Comment by sguilhen** [comment]
@rmartinc Thanks for updating the PR, I will take a good look into it next Monday.

**Review by sguilhen — CHANGES_REQUESTED** [review]
This PR is almost good to go. I just miss a small change in the KeycloakSamlAdapterXMLParserTest to include the new attribute in the default keycloak-saml.xml test file and check its value in the corresponding test method.

**Comment by rmartinc** [comment]
@sguilhen OK, I have updated the year in the new files and finally I have created a new file `keycloak-saml-keepdomassertion.xml` to test the attribute inside the `KeycloakSamlAdapterXMLParserTest.java`. This way the default false is tested and the explicit true in the new file. Sorry for the delay, but I was on vacation until today.

**Comment by rmartinc** [comment]
@sguilhen I have resolved the conflicts, I did not rebase the PR before.

**Review by sguilhen — APPROVED** [review]
Great work @rmartinc! It looks good to me, thank you!

**Comment by hmlnarik** [comment]
Good work, @rmartinc! LGTM but I cannot approve this as I have authored the PR (even though I've not authored the commits within it). I'll ask someone to do the honors.

**Review by abstractj — APPROVED** [review]
Approving based on @hmlnarik and @sguilhen review.

**Comment by rmartinc** [comment]
Remember to finally merge this one. Maybe you are waiting for something, but I prefer to not rebase it again. :-)

**Comment by hmlnarik** [comment]
Done. I was waiting for docs review but I decided not to risk another rebase ;)

**Pull request merged**
