### PR TITLE
KEYCLOAK-15909 - Sort Client realm sessions & IDP mappers

### PR DESCRIPTION
**Pull request by jermarchand**
https://issues.redhat.com/browse/KEYCLOAK-15909

Use Angular `orderBy` to sort tables

### CODE REVIEW

**Comment by hmlnarik** [comment]
Thank you for the PR. Could you please add KEYCLOAK-15909 prefix to the commit message?

**Review by ssilvert — APPROVED** [review]
LGTM

**Comment by ssilvert** [comment]
@hmlnarik The code looks fine and runs properly.  However, I can't figure out how to restart the clustering tests to get this passing and merged.  Do you know what to do?

**Comment by hmlnarik** [comment]
Cluster tests in this PR are irrelevant, merging

**Pull request merged**
