### PR TITLE
[KEYCLOAK-10731] - Change role policies to not only rely on the roles within the token

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by stianst — COMMENTED** [review]
By looking up roles directly it seems that you are effectively bypassing scoped tokens effectively making all tokens have access to all user roles. From that point of view I'm not in favour of this change.

**Comment by pedroigor** [comment]
@stianst, if a role requires consent, I'm checking that here https://github.com/keycloak/keycloak/pull/6163/files#diff-413f1a6f7be59a79b399fee24ec63b8bR322. Maybe I'm missing the same for realm roles ?

**Comment by stianst** [comment]
That will only work assuming that there was no optional client scopes. This just adds complexity IMO without any real value.

**Comment by pedroigor** [comment]
@stianst, I see your point and I have the same concerns. We also have tests in our testsuite that make sure that roles/client scopes that require consent are taken into account when processing a "roleless" token.

The main argument for this change is that when using resource-based access control you don't really care about the roles, groups, or any other claim within a token. A decision is made by the server and that is everything you need to know. As a consequence, when using authorization services you are able to drastically reduce the size of tokens. In fact, that was the main requirement for this change.

I'm also considered creating a new configuration option in authorization settings to enable/disable this behavior, instead of choosing the expected behavior automatically based on the availability of roles from the token. This could provide a safer implementation.

**Review by stianst — DISMISSED** [review]

**Comment by abstractj** [comment]
@pedroigor there are some conflicts. I believe we just need to rebase, so we can merge it.

**Comment by stianst** [comment]
TBH I'm still a bit on the fence about this one.

**Review by stianst — COMMENTED** [review]
I'm not in favour of adding this. It adds complexity and also overhead as roles for the user has to be calculated. In general I think the policy engine should really focus on information from the token and not obtaining additional content from the Keycloak DB. That would be useful in the future if we want to have the ability to scale authz services independent of Keycloak, or even be able to have Gatekeeper (or some similar thing) be a PDP by downloading policies from Keycloak.

**Comment by hmlnarik** [comment]
I would be reluctant to include this since it is the roles in the token that the requestor presents which should be assessed for determining access.

**Comment by stianst** [comment]
Closing this, open a discussion on mailing list if you disagree ;)

**Comment by reste85** [comment]
Hi guys,
We've experienced some problems in adding all the realm roles to the access token, basically related to the fact that some browser does not support cookies > 4KB. If you have a lot of roles (as in our case) you can incur in this problem. 
I saw your previous discussions about that, and i know that in OAuth is typical to validate only what it's carried by the token. However i think we can introduce this kind of functionality in order to validate roles linked to the user, looking on the database, in order to avoid to carry a lot of roles inside the token itself. In our use case tokens doesn't represent user consent to third parties, but instead they represent the result of the authentication of users against our authentication system, and those tokens are used only by them. 
In addition to the "validate only token contents" problem, i think that currently we can already validate something external to the token: javascript policies, group belonging etc. When we're validating those policies we're not validating the contents of the token, but sometimes we go directly to check the data on the db. 

What do you think about that? It could be possible to add this feature?

Thank you!

**Comment by reste85** [comment]
Hi guys, did you read the previous comment? @stianst @pedroigor

**Pull request closed without merging**
