### PR TITLE
Extract timestamp from Expirable entity

### LINKED ISSUE #12225: Extract timestamp from Expirable entity
Not all map entities require both expiration and timestamp fields to be set. This is the case for `MapSingleUseObjectEntity` that needs only `expiration` field. 
Timestamp should be moved to individual entities with proper javadoc which states how the field should be used.

### PR DESCRIPTION
**Pull request by martin-kanis**
Closes #12225

### CODE REVIEW

**Review by mhajas — APPROVED** [review]
Thanks @martin-kanis

**Review by mhajas — CHANGES_REQUESTED** [review]
The changes look good, but It seems the build failed. Could you have a look?

**Comment by martin-kanis** [comment]
> The changes look good, but It seems the build failed. Could you have a look?

Fixed now. I had to remove `extends AbstractEntity` because `MapAuthenticationSessionEntity` where I use `EntityWithTimestamp` doesn't have `id` field.

**Review by mhajas — DISMISSED** [review]
Thanks @martin-kanis

**Comment by martin-kanis** [comment]
@mhajas @hmlnarik I removed `timestamp` from `ExpirableEntity` and moved it to individual entities. There is a javadoc in each entity which states how the methods should be used.
So far I did't introduced new field "timestampUpdated" in client sessions or root auth sessions. It would be difficult to adjust adapters to manipulate correct field (`timestampCreated` vs `timestampUpdated`) by calling `setTimestamp(int)`. Cleaner solution would be adjust also models and logical level but I'm not sure we can/want to do it right now. Let me know WDYT.

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
