### PR TITLE
Add Attribute to Group Mapper for SAML IDP

### LINKED ISSUE #12950: Implement "advanced claim to group" mapping for SAML
### Description

Currently, Keycloak supports mappers for Identity Providers.  Recently the ability to map an "advanced claim to [a] group" [was added](https://github.com/keycloak/keycloak/pull/8467) as a new Mapper Type, but only implemented for "OpenID Connect v1.0" Identity Providers.  Adding the same for SAML Identity Providers would help to keep feature parity between the 2 common standards.

### Discussion

_No response_

### Motivation

Many identity providers still utilize SAML and would like to map in groups.  It would therefore be helpful to implement the same mapper for SAML that was added for OpenID Connect.

### Details

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes https://github.com/keycloak/keycloak/issues/12950.

Changes from https://github.com/keycloak/keycloak/pull/16771 plus tests.

### CODE REVIEW

**Comment by pedroigor** [comment]
@mposolda @bernard-denis I would like to see if you guys have a better name for this mapper. Like, `SamlAttributeToGroupMapper` ...

Otherwise, LGTM.

**Comment by bernard-denis** [comment]
@pedroigor 
Thank for your update with the test. 
I just coming in my PR to asking help with the test as it not working and the skill need is higher mine to solve it with good delay. 

About the name. The code is based on the same approach of the Advanced Claim to Group for OIDC mapper by allow maximum customisation. 
It's for that I use same name convention for it (**Advanced**AttributeToGroupMapper). 
for the SAML prefix, I think this will be redundancy with the class path (org.keycloak.broker.saml.mapper.) 
But if you think it's better, we will need to rename all other mapper to add the prefix like this one for standardisation ;) 
**Feel free** about the prefix ;) 

Thank again for your work.

**Review by mposolda — APPROVED** [review]
@pedroigor This looks good to me.

I am not sure if the test failures are "real" test failures or false alarms. Leaving to you doublecheck? Maybe rebase of this PR can help, but not 100% sure...

**Comment by pedroigor** [comment]
@bernard-denis Yeah, you just followed the same approach as roles. Let's at least keep consistency then and see if we can improve both mappers (role and groups) later so that they are more clear about the intent. Thanks.

**Pull request merged**
