### PR TITLE
KEYCLOAK-10340: Create independent message bundle

### PR DESCRIPTION
**Pull request by ssilvert**
This PR removes the dependency on the base message bundle for the new account console.

The main reason to do this is so that we are not making changes to "live" code that users rely on today.

Also, this will make it easier to clean up the bundle when we are done.  We can quickly identify the messages we are no longer using and get rid of them.

I only added English and German bundles so that we can continue to test changing locales.

### CODE REVIEW

**Comment by ssilvert** [comment]
So if you look at the bundles you see that I just copied them over from the base and commented out the messages we are not using.  That way, if there is an existing message you want to use then you can just uncomment that message from both English and German bundles.  If you are creating a new message then add it to the English bundle only.

**Review by pedroigor — COMMENTED** [review]
The motivation is fine, I'm just concerned about duplicating the common messages while we still have the two console versions. Or the new console will completely remove the current version once it is finished ?

**Comment by ssilvert** [comment]
> The motivation is fine, I'm just concerned about duplicating the common messages while we still have the two console versions. Or the new console will completely remove the current version once it is finished ?

The plan is to remove the old console when we are done.  But that's another debate for another time.

I just realized we've been doing this wrong.  We should have never added new messages to the old bundle.  I think the theme mechanism takes care of merging the parent and child bundles.  Need to look into that.

**Comment by ssilvert** [comment]
This is wrong.  For now we need to just put new messages in a new bundle and continue to inherit old messages from the old bundle.

**Pull request closed without merging**
