### PR TITLE
10227: RelayState max length not respected (fix2)

### LINKED ISSUE #10227: RelayState max length not respected
### Describe the bug

According to 3.5.3 in the specification
https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf
"RelayState data MAY be included with a SAML protocol message transmitted with this binding. The valueMUST NOT exceed 80 bytes in length and SHOULD be integrity protected by the entity creating themessage independent of any other protections that may or may not exist during message transmission"
Keycloak does not respect this.

### Version

17.0.0

### Expected behavior

Keycloak should respect the length restriction.

### Actual behavior

The relay state length restriction is not enforced

### How to Reproduce?

Test will be provided

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by evtr**
Closes https://github.com/keycloak/keycloak/issues/10227 RelayState max length not respected

### CODE REVIEW

**Comment by evtr** [comment]
@ahus1 and @mposolda: I finally managed to make the change we disussed in https://github.com/keycloak/keycloak/pull/10231. I hope you will take a look at it.

**Comment by evtr** [comment]
Closes https://github.com/keycloak/keycloak/issues/10227 RelayState max length not respected

**Comment by evtr** [comment]
@ahus1: Can you approve running the workflows?

**Comment by ahus1** [comment]
Hi @evtr, thanks for this PR.

Two things I note here: 
* Please put the `Closes #10227` in the very first comment of the issue. Only then will it link the PR to the issue. 
* This project doesn't use Mockito. If you can't write the test without it, there needs to be an integration test for this new feature. One of those SAML integration tests is for example `KcSamlXPathAttributeMapperTest`. 

Please let me know if you can think of a way to write such a test without Mockito, or if you need help writing such a SAML test case.

**Comment by evtr** [comment]
The objects that are mocked in the tests mocks very extensive interfaces. I can create TestClientModel and TestRealmModel classes but there are many methods to override. Is that ok?

**Comment by evtr** [comment]
@ahus1: I changed the unit tests to not using mockito

**Comment by evtr** [comment]
@ahus1: I don't really understand what is failing here? Can you help?

**Comment by evtr** [comment]
My thoughts one the SAML integration tests. Perhaps I shouldn't create new tests but choose one of the "sunshine" scenarios that are already in the test suite and add an assertion on the relaystate length somehow?

**Comment by ahus1** [comment]
@hmlnarik - this PR adds a class IdentityBrokerStateTestHelpers.java to avoid using a mocking framework like Mockito as I know that adding such dependencies is discouraged. 

Could you please provide a hint if this is the way to go, or if the contributor should go for an Arquillian based integration test. 

Thanks!

**Review by hmlnarik — APPROVED** [review]
Thank you for the PR!

**Pull request merged**
