### PR TITLE
KEYCLOAK-17947 Propagate security domain to ejb

### PR DESCRIPTION
**Pull request by pazepaze**
same fix as in https://github.com/keycloak/keycloak/pull/5977 just for the offline installer

See https://issues.redhat.com/browse/KEYCLOAK-17947

### CODE REVIEW

**Comment by pazepaze** [comment]
To Reproduce and verify fix:

Using keycloak 12.0.4 and wildfly 23.0.1.Final:

Install keycloak adapter with
{code:java}
./bin/jboss-cli.sh --file=bin/adapter-elytron-install-offline.cli
{code}
 * Make a sample rest application with the code below and configure a user with client role "my-admin-role".
 * Get token from keycloak and call /admin route with token

Result: javax.ejb.EJBAccessException, Invocation on method of bean SampleService is not allowed

Expected: Returns 200 OK and ""This user is allowed to call sampleMethod!" in log

```
@ApplicationPath("/")
public class RestApplication extends Application {
}
```
```
@Path("/")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class RestResource {

    @Inject
    SampleService sampleService;

    @GET
    @Path("/admin")
    public String getAdminJSON() {
        sampleService.sampleMethod();
        return "hello world";
    }
}
```

```
@Stateless
public class SampleService {

    @RolesAllowed("my-admin-role")
    public void sampleMethod() {
        System.out.println("This user is allowed to call sampleMethod!");
    }
}
```

web.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd"
         version="4.0">
    <security-constraint>
        <web-resource-collection>
            <web-resource-name>Admins</web-resource-name>
            <url-pattern>/admin/*</url-pattern>
        </web-resource-collection>
        <auth-constraint>
            <role-name>my-admin-role</role-name>
        </auth-constraint>
    </security-constraint>

    <login-config>
        <auth-method>KEYCLOAK</auth-method>
        <realm-name>this is ignored currently</realm-name>
    </login-config>

    <security-role>
        <role-name>my-admin-role</role-name>
    </security-role>
</web-app>
```

keycloak.json
```
{
  "realm": "testrealm",
  "bearer-only": true,
  "auth-server-url": "http://keycloak:8080/auth/",
  "ssl-required": "none",
  "resource": "my-wildfly-api-service",
  "verify-token-audience": true,
  "use-resource-role-mappings": true,
  "principal-attribute": "preferred_username"
}
```

**Review by pedroigor — DISMISSED** [review]
LGTM. Thanks!

**Comment by pedroigor** [comment]
@pazepaze Could you please rebase?

**Comment by pazepaze** [comment]
done

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@pazepaze Tks.

**Pull request merged**
