### PR TITLE
Allow authorization changes with fine-grained client access and manag…

### LINKED ISSUE #24219: admin-fine-grained-authz + client authorization settings requires view-client role
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When using the preview feature admin-fine-grained-authz to allow certain users to manage their clients, some clients are using the Authorization capabilities. In Keycloak <=v19 using the old Admin UI Console, the only realm-management client roles that were needed to these users were: manage-authorization, query-clients, query-users, query-groups. In the new Admin UI Console, the role view-clients is required to create resources, client policy, or authorization scope in the Authorization settings for the client.

This is a problem as view-clients role allows users to view other clients and the client secrets of all applications.

### Version

nightly

### Expected behavior

When using admin-fine-grained-authz settings users with manage permissions to a client should be able to configure and create authorization policies for their client without requiring access to ALL clients in the realm.

### Actual behavior

To create new Authorization policies, client resources, or authorization scopes the user must have `view-client` realm management client role.

### How to Reproduce?

- Follow instructions at [Fine Grain Admin Permissions](https://www.keycloak.org/docs/latest/server_admin/#_fine_grain_permissions) to configure a user to manage one specific client.
- Add realm-management client role of manage-authorization to the user as well.
- Turn on Authorization for the client.
- Login as user to the security-admin-console for the realm.
- View the configured managed client and select the Authorization tab.
- Select one of these sub-tabs of Authorization - Resources, Scopes, Policies
- On the tab, click the `Create (X)` button like `Create resource` button on the Resources sub-tab.
- You'll be met with an error message: Forbidden, permission needed: view-clients

### Anything else?

Related to: https://github.com/keycloak/keycloak/issues/23294

### PR DESCRIPTION
**Pull request by ssilvert**
…e-authorization.

Fixes #24219

### CODE REVIEW

**Comment by sschu** [comment]
@ssilvert Are you sure `manage-authorization` is the (only) missing permission compared to the original implementation? I am asking because in other places the UI looks for the respective `query-*` roles to decide whether elements are shown, i.e. `query-clients` in this case.

**Review by jonkoops — APPROVED** [review]

**Comment by ssilvert** [comment]
> @ssilvert Are you sure `manage-authorization` is the (only) missing permission compared to the original implementation? I am asking because in other places the UI looks for the respective `query-*` roles to decide whether elements are shown, i.e. `query-clients` in this case.

I don't know compared to the original implementation.  I do still consult it sometimes, but I've learned from experience that there were problems there too.

The thing that the UI needs to do is to keep the user from submitting something to the server that will be rejected because of access controls.  If you don't have "query-clients", you can't get to this part of the UI.  This particular part of the UI works fine without the other query-* permissions.  So there is no reason to add extra restrictions here.

However, you did force me to take a closer look and I found a couple of small bugs in policy creation.  You can't create a group policy without some sort of group access and you can't create a user policy without user access.  So maybe those options shouldn't show up in the list.  I may fix that here if I can or I will create a new issue for it.

**Comment by sschu** [comment]
Thanks, makes sense to me.

**Comment by ssilvert** [comment]
Created https://github.com/keycloak/keycloak/issues/25331.  Merging now.

**Pull request merged**
