### PR TITLE
Added attribute tab for client in admin console as per jira: https://issues.jboss.org/browse/KEYCLOAK-5615

### PR DESCRIPTION
**Pull request by sankks**
- Added new partial for client attribute
- Included the attribute tab in kc-tabs-client.html
- Added methods for adding and removing client attributes in
clientDetailCtrl in client.js
- Added path for client attributes in app.js

### CODE REVIEW

**Comment by stianst** [comment]
Please create a JIRA and explain what this does and why it is needed.

**Comment by ssilvert** [comment]
Sorry it has taken so long to get to this.  I tried it out against master and the UI doesn't seem to work.  I add a key/value pair and nothing happens.  When I hit save, it says the operation was successful, but the key/value pair disappears.

I'm also unclear about what this is for and how it is supposed to work.  Are you wanting to customize the login screens?  Exactly what is being customized and how are the attributes read?

**Comment by ssilvert** [comment]
Hi.  Do you still want to discuss this PR?

**Comment by stianst** [comment]
Due to feature freeze we can't consider merging this until 4.x

**Comment by sankks** [comment]
Sorry about the delay in responding. (Committed minor changes now). 

We have a identity broker application that  extends Keycloak and have customized themes for sign in sign up etc. The main goal of adding attributes is for minor customization of sign in or sign up pages based on client. For instance some clients do not want certain social providers to be shown on the sign in page. To accomplish this we use some attributes set for the clients. We have admins who control these in admin console. So having UI tab for attributes make easy for those admin personnel to manage those features.

Note: I have added logic to hide attributes that contain 'saml',  'user.info.response.signature.alg' and 'request.object.signature.alg', as they are added by other means. So if you try to add any of those, it will not show up after saving.
Please test again with other attributes and let me know.

Thanks.

**Comment by stianst** [comment]
We've added support to override theme directly on the client. See KEYCLOAK-3370.

**Comment by soufian044** [comment]
+1

**Comment by pendula95** [comment]
Why is this closed. The possibility to add custom attributes to client is available in the ClientModel, but the GUI is admin console is non existent. We use these attributes on our custom extension of KC SPI and have different behaviour based on the custom client attribues. Curretly the only way you can do this is by directly adding value to KC DataBase or by making custom rest call and logic that would do this. 
I suggest adding this as tab on client page in KC admin console so people can use this values in their custom code easy. It isn't related to just one case of client theme. +1

**Comment by juv** [comment]
+1 on @pendula95

**Pull request closed without merging**
