### PR TITLE
KEYCLOAK-10837 Add possibility to disable certificate verification

### PR DESCRIPTION
**Pull request by ykvasetskiy**
for outgoing https connections

### CODE REVIEW

**Review by lrozenblyum — DISMISSED** [review]
The fix looks nice and solves a real problem of outgoing https connection

**Comment by abstractj** [comment]
@ykvasetskiy could you please rebase your pull request to include the latest changes from master?

**Review by lrozenblyum — APPROVED** [review]
Great long-waiting change

**Comment by ykvasetskiy** [comment]
@abstractj Done

**Comment by stianst** [comment]
I'm okay with introducing an option to disable cert verification for development purposes only. We need the additional option to be documented as well, and it should clearly stress that it is for development purposes only and should never be used in production.

**Review by slaskawi — COMMENTED** [review]
I honestly don't like this change. 

To me it's a bit unintuitive - when there's no trust store, we just ignore TLS verification. I believe it's just wrong as it's perfectly valid to install all CA certificates in your system (`$JRE/lib/security`). In such scenario, we do want to have certificate validation and do not declare Truststore Provider.

At the same time, I do understand the frustration on self-issued certificate validation in development environment. Although, I think it's better to configure it explicitly (by disabling trust manager) and not implicitly (by not declaring it at all). This way, there's no room for a mistake.

**Comment by ykvasetskiy** [comment]
Well, The changes were promoted only to have the possibility to disable TrustManager. Variable name used the same as in docs https://www.keycloak.org/docs/latest/securing_apps/index.html#_java_adapter_config . Variable disableTrustManager used for Truststore Provider so I renamed it to disableTruststoreProvider to have consistency.

**Comment by slaskawi** [comment]
> Well, The changes were promoted only to have the possibility to disable TrustManager. 

@ykvasetskiy I think I partially misinterpreted the code and confused this with `HttpClientBuilder` from `org.keycloak.adapters` package (where the method signatures are very similar to this Pull Request).

I also noticed, that currently there is no way of turning the trust manager off. The method `org.keycloak.connections.httpclient.HttpClientBuilder#disableTrustManager` is not called anywhere.

But still, all my points remain valid. I believe it is a perfectly legal configuration to have a null-TruststoreProvider and using Truststore built into Java (`$JRE/lib/security`). How about modifying this Pull Request and adding an explicit `disable-trust-manager` option (for the symmetry to the adapters configuration [here](https://github.com/keycloak/keycloak/blob/5880efe77554329baf5169a2c33da3c0499eab62/core/src/main/java/org/keycloak/representations/adapters/config/AdapterConfig.java#L49))? I'm a bit worried that users won't realize that if they won't specify a Trust Store Provider, there will be absolutely zero host verification (even if Keycloak gets challenged by an app with `client.auth=required`).

BTW, of course, due to my mistake, I'm changing my review from "Change Required" to "Comment"

**Review by slaskawi — COMMENTED** [review]
Changing the review state.

**Comment by ykvasetskiy** [comment]
@slaskawi 
1. Explicit call disable-trust-manager property on line 147 `boolean disableTrustManager = config.getBoolean("disable-trust-manager", false);`
2. I applied default false value to do not affect old configurations
3. org.keycloak.connections.httpclient.HttpClientBuilder#disableTrustManager called on line 176

**Comment by lrozenblyum** [comment]
This pull request provides backwards compatibility - for customers who doesn't use the property disable-trust-manager, SSL validation works exactly like before.

**Comment by slaskawi** [comment]
@ykvasetskiy Indeed, I missed the configuration check on line 147. Now everything makes sense, thanks for explaining it.

This one looks good to me.

**Review by slaskawi — APPROVED** [review]

**Review by abstractj — APPROVED** [review]

**Comment by ykvasetskiy** [comment]
@abstractj @stianst @slaskawi Thank you.

**Pull request merged**
