### PR TITLE
Fix label for IdpReviewProfileAuthenticatorFactory

### LINKED ISSUE #16658: Label for "Review Profile config" modal is not displayed properly in new admin console
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

This is issue in the main codebase related to https://github.com/keycloak/keycloak-ui/issues/3707 (as some changes may be needed also in the main codebase)

### Version

20.0.3

### PR DESCRIPTION
**Pull request by zak905**
Fixes keycloak/keycloak#17957

### CODE REVIEW

**Review by mposolda — CHANGES_REQUESTED** [review]
I think that this is an issue just in the new admin console, but not in the old admin console. Is it correct?

If yes, it will be better to rather create issue for the new admin console (issue in keycloak/keycloak-ui repository) so that new admin console supports localization for this. Removing localized label and replace it with hardcoded text does not look like good solution to me.

**Comment by zak905** [comment]
Thanks for the input. Yes indeed, the issue is just in the new console. However, the `{{:: 'update-profile-on-first-login' | translate}}` syntax is only specific to AngularJs, and cannot work with the new console which is based on React. Also, I have seen in many places where the `setLabel` does not use this syntax, but rather use plain english, like:

* https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpCreateUserIfUniqueAuthenticatorFactory.java#L102
* https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/authenticators/browser/IdentityProviderAuthenticatorFactory.java#L76

I thought that we might want to keep in line with other Authenticators. What do you think?

**Comment by mposolda** [comment]
@zak905 Thanks for pointing this and creating the issue in keycloak-ui repository. Yes, it is possible that format is specific to Angular 1. In any case, we may need to figure some solution to support localization for those cases and figure how to make sure that stuff can be localized in the new admin console.

Replacing the localized message with the hardcoded one is not good approach. I know that we have already some hardcoded labels for other authenticators, but in general, the effort should be rather to localize existing hardcoded labels rather than the opposite (Make the labels hardcoded just because localization does not work).

**Comment by zak905** [comment]
Hi @mposolda, I tend to agree. I have done some experiments, and I am thinking of the following solution which would require changes both here and in the keycloak-ui repository:
* Instead of using plain text in `setLabel` and the `setHelpText` methods in `ProviderConfigProperty` , We can use the message properties key. This would work out of the box with the legacy console, because we already have the translate directive in the templates (for example [here](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/admin/resources/templates/kc-provider-config.html#L3) for the authenticator config case ). I just tried now and it seems lke doing `property.setLabel("update-profile-on-first-login");` instead of `{{:: 'update-profile-on-first-login' | translate}}` works as well. This would require converting all the `setLabel` and `setHelpText` calls to use the property keys instead of plain text, and also adding new keys to `messages.properties` if they do not exist already. 
* In the keycloak-ui repository, the react-i18next library is used handle internationalization. We can add a new `.json` file to support all the legacy keys with their translation [here](https://github.com/keycloak/keycloak-ui/tree/main/apps/admin-ui/public/resources) for each of the keys that we will use in step one. We can call it for example `legacy.json` or `legacyConsole.json` The only thing that we need to keep in mind is that the keys need to have the same case as the ones we have in `messages.properties`. In other words, the key need to be same in both repos. I have noticed that some keys in the admin legacy theme are in kebab case while some other are in camelCase. To respect the convetion used in keycloak ui, we may want to convert those to camelCase. 

This would ensure having backward compatibility between the new and the old console and also avoid having plain english for labels and in help text. I am gonna open a thread in dev group for this to prompt for the community input.

**Comment by mposolda** [comment]
@zak905 Thanks for your proposal. Few quick points:

- The old admin console is going to be removed from the keycloak/keycloak repository. So it is not needed at all to care about preserving compatibility with it. Whatever solution is fine as long as old admin console is not completely broken and it is still able to render without any UI errors :-) This is needed as it is still not clear when exactly it would be removed (it may take few months though). However if some labels (or help texts) are broken and unlocalized, it is not a huge issue IMO

- For the labels and helpTexts, it will be still nice if it works same way in the new admin console like it worked with the old admin console. So both "key" and "plain text" somehow works. In other words, if the particular "key" referenced by label/helpText doesn't exists, then the label/helpText would be used as is (which in fact imply that particular label/helpText is probably in plain text format).

**Comment by zak905** [comment]
Awesome thanks. I have added a new commit to address the case of  `{{:: 'update-profile-on-first-login' | translate}}` being displayed in the new console. I have also opened a PR in the keycloak-ui repo: https://github.com/keycloak/keycloak-ui/pull/3870
This should do it. For the others, they will be displayed as plain english, since they are not localized. I guess it would require a fair amount of effort to localize all the calls to `setLabel` and `setHelpText` ( I counted around 160 calls) , and since the console is to be removed, I am not convinced it's worth the trouble. By the way, I have been hearing from 2019 that the new console will be removed soon hehe

**Comment by jonkoops** [comment]
> I have been hearing from 2019 that the legacy console will be removed soon hehe

This time for real 😉

**Comment by jonkoops** [comment]
@mposolda could you give this another look over to see if we can get it merged?

**Comment by mposolda** [comment]
@zak905 Thanks!

**Review by mposolda — APPROVED** [review]

**Comment by zak905** [comment]
great. thanks

**Pull request merged**
