### PR TITLE
fix: overriding base image labels

### LINKED ISSUE #24414: Container labels inherited from UBI image
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

A number of labels are set on the container metadata that are simply inherited from UBI:

```
$ podman image inspect quay.io/keycloak/keycloak | jq .[0].Config.Labels
{
  "architecture": "x86_64",
  "build-date": "2022-06-17T04:19:16.231674",
  "com.redhat.build-host": "cpt-1001.osbs.prod.upshift.rdu2.redhat.com",
  "com.redhat.component": "ubi8-minimal-container",
  "com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI",
  "description": "The Universal Base Image Minimal is a stripped down image that uses microdnf as a package manager. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
  "distribution-scope": "public",
  "io.k8s.description": "The Universal Base Image Minimal is a stripped down image that uses microdnf as a package manager. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
  "io.k8s.display-name": "Red Hat Universal Base Image 8 Minimal",
  "io.openshift.expose-services": "",
  "io.openshift.tags": "minimal rhel8",
  "maintainer": "Red Hat, Inc.",
  "name": "ubi8-minimal",
  "org.opencontainers.image.created": "2022-07-29T11:17:24.398Z",
  "org.opencontainers.image.description": "",
  "org.opencontainers.image.licenses": "Apache-2.0",
  "org.opencontainers.image.revision": "55316db91317e8a22aa91fa9abf37b10e21cb6c9",
  "org.opencontainers.image.source": "https://github.com/keycloak-rel/keycloak-rel",
  "org.opencontainers.image.title": "keycloak-rel",
  "org.opencontainers.image.url": "https://github.com/keycloak-rel/keycloak-rel",
  "org.opencontainers.image.version": "19.0.1",
  "release": "854",
  "summary": "Provides the latest release of the minimal Red Hat Universal Base Image 8.",
  "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8-minimal/images/8.6-854",
  "vcs-ref": "50293e4ba66ca2194d8ee5a149a665cb9a375c71",
  "vcs-type": "git",
  "vendor": "Red Hat, Inc.",
  "version": "8.6"
}
```

We should investigate if we can replace some (like `name`, `maintainer`, and `io.k8s.*`), and potentially remove some (`com.redhat.*`). 

### Version

main

### Expected behavior

Container metadata labels contain information relevant to Keycloak and not the base image

### Actual behavior

Container metadata labels contain information relevant to the base image

### How to Reproduce?

```
$ podman image inspect quay.io/keycloak/keycloak | jq .[0].Config.Labels
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
closes: #24414

### CODE REVIEW

**Review by abstractj — APPROVED** [review]
Changes LGTM, but I just wonder if instead of using the keycloak website as a maintainer reference, we should follow something close to what Falco does by providing an e-mail as the main point of contact.

**Comment by vmuzikar** [comment]
@ASzc Is this change ok for downstream? I imagine we'd have to do some overrides there. Do we need to make it build args perhaps?

**Comment by mabartos** [comment]
@shawkins It seems to me these env vars specified in the builder phase are not properly propagated. Could you please check it?

Left side = Old one
Right side = New one (This PR)

```
{                                                               {
  "architecture": "x86_64",                                       "architecture": "x86_64",
  "build-date": "2024-02-29T16:04:33",                            "build-date": "2024-02-29T16:04:33",
  "com.redhat.component": "ubi9-micro-container",                 "com.redhat.component": "ubi9-micro-container",
  "com.redhat.license_terms": "https://www.redhat.com/en/abou     "com.redhat.license_terms": "https://www.redhat.com/en/abou
  "description": "Very small image which doesn't install the  |   "description": " Image",
  "distribution-scope": "public",                                 "distribution-scope": "public",
  "io.buildah.version": "1.33.7",                                 "io.buildah.version": "1.33.7",
  "io.k8s.description": "Very small image which doesn't insta |   "io.k8s.description": " Image",
  "io.k8s.display-name": "Ubi9-micro",                        |   "io.k8s.display-name": "",
  "io.openshift.expose-services": "",                             "io.openshift.expose-services": "",
  "maintainer": "Red Hat, Inc.",                              |   "maintainer": "",
  "name": "ubi9/ubi-micro",                                   |   "name": "",
  "release": "15",                                                "release": "15",
  "summary": "ubi9 micro image",                                  "summary": "ubi9 micro image",
  "url": "https://access.redhat.com/containers/#/registry.acc     "url": "https://access.redhat.com/containers/#/registry.acc
  "vcs-ref": "303dc144996db01765d69e8ea45d2d617d953e42",          "vcs-ref": "303dc144996db01765d69e8ea45d2d617d953e42",
  "vcs-type": "git",                                              "vcs-type": "git",
  "vendor": "Red Hat, Inc.",                                      "vendor": "Red Hat, Inc.",
  "version": "9.3"                                                "version": "9.3"
}                                                               }

```

Steps to reproduce:

1. Build image
2. `podman inspect <IMAGE> | jq '.[].Config.Labels'`

**Comment by shawkins** [comment]
> It seems to me these env vars specified in the builder phase are not properly propagated. Could you please check it?

It looks like what happened, and what originated my question on the issue, was that for some of my experimentation I was checking the wrong image for the labels. I now do see that the quarkus supported way does work as expected for all values, and that the env vars are not resolving here. I'll probably stick with the Dockerfile approach and see if I can get it to render properly.

**Comment by ASzc** [comment]
At present we're building product with a non-synchronized Dockerfile, due to incompatibilities between upstream needs and product needs. There's an open issue in the backlog to synch them, or do automatic translation between them, but it's not been a priority because the Dockerfiles are so simple and functionally equivalent

The changes I'm seeing in this PR look like they wouldn't have an impact on the product build, assuming that the new environment variables and overridden labels aren't something the the server or operator code will be looking for now. If it's just container-level changes so that things look right in Kubernetes then this PR should have no real impact on product

**Pull request closed without merging**
