### PR TITLE
[KEYCLOAK-2517] - Doesn't work always refresh token

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by stianst** [comment]
@pedroigor do you want someone to review this? Maybe @sebastienblanc could take a look?

**Comment by pedroigor** [comment]
+1

**Comment by sebastienblanc** [comment]
@trecloux Hi Thomas ! Could you also give your feedback on this PR ?

**Comment by sebastienblanc** [comment]
Tested with my sample app and it's all good.
@stianst you can merge this.

**Pull request merged**
