### PR TITLE
Allow incremental build for the themes

### LINKED ISSUE #25404: Adapt incremental build for latest changes in themes module
### Description

The incremental build with the Maven cache extension doesn't work for the themes module any more after some changes to the folder structure. 

This updates the exclusions and also the extension.

### Discussion

_No response_

### Motivation

Allow an incremental build for Keycloak

### Details

I'll submit a pull request.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #25404

### CODE REVIEW

**Comment by ahus1** [comment]
@jonkoops - for the build cache plugin I updated the filters for the themes folder. It would be great if you could review it for the UI team. This will safe me some seconds / minutes when the themes haven't changed and I rebuild the Java parts.

Thanks!

**Review by jonkoops — APPROVED** [review]
The paths here do look correct, but I am a bit worried this will become unwieldy and out of sync in the future. Either way, this looks good enough for now.

**Comment by jonkoops** [comment]
@ahus1 You probably already know this, but it you want to re-build the themes then running Maven as `mvn install -Dskip.pnpm -DskipTests` makes things pretty quick. The main problem remains the amount of code that is bundled into the JAR, which I hope we can at least partially address by fixing #24861.

**Comment by ahus1** [comment]
@jonkoops - this extension also reduces the number of rebuilt Maven modules, so this is not only about the themes when it comes to the overall effect. Therefore I plan to maintain it at least for now.

**Comment by ahus1** [comment]
@mhajas - when you have the time, could you please approve and merge it, based on @jonkoops' review? Thanks!

**Review by mhajas — APPROVED** [review]
Approving based on review from @jonkoops

**Pull request merged**
