### PR TITLE
Backport operator secret sequencing fix

### LINKED ISSUE #22170: Operator secrets sequencing
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

When deploying using the operator the operator checks if the db secrets exist and if they do not then it stops further deployment.

If the secrets are later provisioned this does not get picked up by the operator so the deployment becomes stuck.

Successful deployment requires the secrets are in place prior to creating the keycloak definition. This makes an implied sequencing.

Ideally the operator will retry the creation of the deployment/statefulset or it will create the stateful regardless of the secret and allow the sts and pod operations to implement the retries.

### Version

22.0.0

### Expected behavior

Creation of the stateless set occurs regardless of the presence of the db credentials secret or the operator checks for presence of secrets after a timeout

### Actual behavior

After the initial check for secrets when the keycloak object is created and faulted no further updates or progress is made.

### How to Reproduce?

Create a keycloak definition using secret references to db username and password referring to a secret that does not exist.
The stateful set will not be created.
Create the appropriate secret.
The operator will not update.

Now delete the keycloak object then recreate.
The stateful set is now constructed. Showing that the operator has an implied sequencing that should ideally be removed or avoided to ensure consistent deployments

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Jamstah**
This bug makes scenarios where applying the `Keycloak` CR at the same time as the `Certificate` CR that is expected to generate the secret used by Keycloak will, more often than not, end up in a bad state. This forces bad behaviour like sequencing CRs onto the cluster.

We are expecting to use 22.0 with our customers, so would like to backport the fix from #22404 (and #21162 as a dependency)

Fixes #22170

### CODE REVIEW

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@Jamstah Thanks for the PR.

I'm afraid we can't backport changes that significantly alter functionality. If there's a need for fixing #22170 in a 22 micro (I'm not 100% sure it's affected), I'd rather have a smaller targeted fix while keeping current implementation.

**Comment by Jamstah** [comment]
Its definitely affect, we've been testing with it.

I'm happy to look at a more targetted fix, but it would be a different fix to the one in 23.x. I thought it would be cleaner to apply the same fix.

I guess its the `WatchedSecretsController` that you want to avoid bringing in? That's only there to know when to apply the missing secrets annotation used to trigger the scheduled reconcile. I could have a go at applying the label with based on the previous `WatchedSecretsStore` implementation, if that suits?

**Comment by vmuzikar** [comment]
> I'm happy to look at a more targeted fix, but it would be a different fix to the one in 23.x. I thought it would be cleaner to apply the same fix.

That's generarly true backports should be 1:1. However, in 23 we did more major changes to Operator implementation we want to avoid dragging in back to 22 to limit the risk of regressions in a micro.

In this case, I think we need a tailored fix for 22 to keep previous implementation.

@shawkins WDYT?

**Comment by shawkins** [comment]
Other than some additional risk, probably the biggest issue for a point release is that this will trigger a rolling restart of the keycloak instance.

As long as we're okay with that, then I think the additional risk is worth not having a skew in the implementations.

**Comment by vmuzikar** [comment]
> the biggest issue for a point release is that this will trigger a rolling restart of the keycloak instance.

You mean upgrading to the micro will cause the restart? It will trigger a restart in any case to roll the new image.

I'm not really comfortable with backporting anything this big, especially not now before prod release. I'd rather have a different fix implementation.

**Comment by Jamstah** [comment]
OK. I need to fix the tests anyway (I only ran the unit tests, whoops!), so shall I go for an alternative implementation?

**Comment by shawkins** [comment]
> You mean upgrading to the micro will cause the restart? It will trigger a restart in any case to roll the new image.

Just to make sure I'm following you, are you saying that every release of the operator will be accompanied by a different keycloak image?

**Comment by pgodowski** [comment]
> > You mean upgrading to the micro will cause the restart? It will trigger a restart in any case to roll the new image.
> 
> Just to make sure I'm following you, are you saying that every release of the operator will be accompanied by a different keycloak image?

Let me ask a question - I thought that the operator <-> operand is 1:1 currently, and every time there is (even a security update) of the operator, it means that there is also updated operand image. For example, UBI9 security updates are there in both operator and operands.

So, isn't it that ALWAYS when  operator is updated, operand also will be updated, thru the rolling update?

Otherwise, the `Keycloak` CR would need to have something like `.spec.version` indicating the _exact_ version of the operand image to use. Currently I see that operator can cope with single operand image.

Having said that, what is wrong with the direct backport, i.e. is the only concern due to the rolling update of the operand?

**Comment by vmuzikar** [comment]
> Just to make sure I'm following you, are you saying that every release of the operator will be accompanied by a different keycloak image?

Yes, the release processes of Operator and Operand are now 100% aligned. We can't release new Keycloak version without releasing a new Operator version and vice versa.

> Having said that, what is wrong with the direct backport, i.e. is the only concern due to the rolling update of the operand?
> (I do understand the motivation to lower the risk of introducing regression in the last runaway before the release - but can we assess where the risks are perhaps?)

I see the risk in the potential regressions. #21162 significantly changed how we handle watching Secrets. This change has not yet been released in any Keycloak version, just nightlies. We have integration tests of course, but there's always risk we missed something. And from my perspective it's safer to release something like that in a major version than risk breaking stuff in micro release (just before a major prod release). And I see less risk in creating a smaller targeted fix just for #22404.

**Comment by Jamstah** [comment]
Looking at the failure on 22.0, it actually crashing because it can't find the secret and then giving up on reconcile because it crashed too much. I think that's a different cause (although the same symptoms).

I have a more targetted fix coming in a second pr, just letting the tests run this time :)

**Comment by Jamstah** [comment]
Closing for a more targeted fix for 22.0 in #23741

**Pull request closed without merging**
