### PR TITLE
updated organization table name to not conflict.

### LINKED ISSUE #28246: Use a reserved naming space for tables related to organization
See https://github.com/keycloak/keycloak/discussions/23948#discussioncomment-8927678.

### PR DESCRIPTION
**Pull request by xgp**
fixes #28246

cc @pedroigor

### CODE REVIEW

**Review by pedroigor — COMMENTED** [review]
@xgp Thanks!

@vramik Would mind reviewing this one? I remember you mentioned about using a `KC_` prefix or something?

**Comment by sguilhen** [comment]
In Map Store we used to have the `KC_` prefix, but that is not used anywhere in the current store. So I would say using ORG is fine

**Review by vramik — APPROVED** [review]
@xgp thanks for the PR. LGTM.

**Comment by xgp** [comment]
@pedroigor @vramik Thank you both for this. There are lots of users of the `keycloak-orgs` extension that will be relieved that there won't be a collision here.

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
