### PR TITLE
fix: moves jgroups.dns.query to a system property

### LINKED ISSUE #21830: Operator doesn't pass on system property 'jgroups.dns.query' to Keycloak but an env variable, leading to a warning in the log
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

To configure discovery for Infinispan on Kubernetes, the [docs](https://www.keycloak.org/server/caching) as for the `jgroups.dns.query` to be added as a Java System Property using `-D...`. Instead the Operator passes an environment variable which leads to a warning. 

### Version

main

### Expected behavior

No warning logged.

### Actual behavior

Warning logged by Infinispan, which is misleading and wrong, as it is evaluated by JGroups in a second step:

> ISPN000901: Property jgroups.dns.query could not be replaced as intended!

This is what is happening:

The Keycloak Operator set an environment variable `jgroups.dns.query`: 

https://github.com/keycloak/keycloak/blob/fa830344743c987e71c2d6cf3eea161e51e7c43b/operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java#L350-L353

The environment variable is not visible inside of a shell, as shells ignore environment variable names which contain a dot. It is still there when I look at /proc/1/environ, and the Java process picks it up as it is started directly, and not from a shell. 

After some debugging with @ryanemerson I found that Infinispan's [`StringPropertyReplacer`](https://docs.jboss.org/infinispan/14.0/apidocs/org/infinispan/commons/util/StringPropertyReplacer.html) doesn't look at environment variables and prints the warning, while JGroup's `ProtocolConfiguration.substituteVariables` calls `Util.substituteVariable()` which then takes into account the environment variables as well.

### How to Reproduce?

Look at the logs of Keycloak started by the Operator in Kubernetes.

### Anything else?

Looking at the JavaDoc of `StringPropertyReplacer`, environment variables need to be prefixed by `env.` to be replaced by Infinispan.

As we're using the default stacks and don't want to duplicate them, we can't use an environment variable. 

The JAVA_OPTS shouldn't be overwritten, as it would overwrite all defaults in `kc.sh`. The `JAVA_OPTS_APPEND` is usually overwritten using the `podTemplate`, so if the Operator wants to use that path, it should only append that option there.

### PR DESCRIPTION
**Pull request by shawkins**
This makes the assumption we can always update command to support this.  My assumption is that this does not need to be picked up by the import logic.

closes #21830

### CODE REVIEW

**Review by vmuzikar — COMMENTED** [review]
Should we rather use the `JAVA_OPTS_APPEND` env var as suggested in docs?

We would need to document it in upgrade guide, though.

**Comment by shawkins** [comment]
> Should we rather use the JAVA_OPTS_APPEND env var as suggested in docs?

We'll have to do a little more mechanics to see if the user is already setting that in the template so that we can create the merged entry.  It seems simpler to just alwasy append to the command args - or it can be prepended if you think there's a chance a user may want thier setting to take precedence.

**Comment by vmuzikar** [comment]
@shawkins I would not introduce additional merging logic. If user overrides the env var via the "unsupported" pod template, it takes precedence. We might want to introduce a first class citizen field for JVM options in general (related to #21996). That would then require a merging logic.

In any case, I think we don't have much of options other than using the env var. `kc.sh` does not support direct passing of system props.

**Comment by vmuzikar** [comment]
> From what I have seen it does support that. The logic takes a pass over the arguments and re-arranges the -D options into the SERVER_OPTS variable.

Ah, missed [this](https://github.com/keycloak/keycloak/blob/dfe64f6271f18d902d0030bbcc324c8464e5f424/quarkus/dist/src/main/content/bin/kc.sh#L70), you're right. Ok, works for me.

However, Operator tests seem to have failed. Could you please check it?

**Comment by shawkins** [comment]
> However, Operator tests seem to have failed. Could you please check it?

I hadn't run with a custom image, so I missed those checks.

The other failures I couldn't quite pin down.

**Comment by shawkins** [comment]
The assumption about not being needed by import was incorrect.  Added that as well.

**Comment by vmuzikar** [comment]
> The assumption about not being needed by import was incorrect. Added that as well.

I'm not sure why the import Job should be connecting to the cluster. Quite contrary I think. Should we switch to `cache=local` in the Job?

**Comment by shawkins** [comment]
> I'm not sure why the import Job should be connecting to the cluster. Quite contrary I think. Should we switch to cache=local in the Job?

After seeing the error I wasn't sure if it was somehow accessing the cache to reconcile the import - check for existing things, etc.  If that's not expected, local sounds fine - or an issue could be created to disable that behavior when using the import command.

**Comment by shawkins** [comment]
Error from the pod log without providing the system property:

```
2023-10-19T13:29:37.3291228Z WARN: example-count0-kc-99ndn not ready log: start(DefaultCacheManager.java:747)
2023-10-19T13:29:37.3292598Z 	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:411)
2023-10-19T13:29:37.3294579Z 	at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.startCacheManager(CacheManagerFactory.java:96)
2023-10-19T13:29:37.3296408Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-10-19T13:29:37.3298126Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-10-19T13:29:37.3299710Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-10-19T13:29:37.3300884Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2023-10-19T13:29:37.3311314Z Caused by: org.infinispan.commons.CacheConfigurationException: ISPN000541: Error while trying to create a channel using the specified configuration '[TCP(bundler.max_size=64000, sock_conn_timeout=300, port_range=0, thread_pool.keep_alive_time=60000, diag.enabled=false, bind_port=7800, thread_naming_pattern=pl, thread_pool.thread_dumps_threshold=10000, send_buf_size=640k, thread_pool.max_threads=200, bundler_type=transfer-queue, logical_addr_cache_expiration=360000, thread_pool.min_threads=0), RED(), dns.DNS_PING(num_discovery_runs=3), MERGE3(max_interval=30000, min_interval=10000), FD_SOCK2(offset=50000), FD_ALL3(), VERIFY_SUSPECT2(timeout=1000), pbcast.NAKACK2(xmit_table_num_rows=50, use_mcast_xmit=false, xmit_table_msgs_per_row=1024, xmit_table_max_compaction_time=30000, xmit_interval=200, resend_last_seqno=true), UNICAST3(conn_close_timeout=5000, xmit_interval=200, xmit_table_num_rows=50, xmit_table_msgs_per_row=1024, xmit_table_max_compaction_time=30000), pbcast.STABLE(desired_avg_gossip=5000, max_bytes=1M), pbcast.GMS(join_timeout=2000, print_local_addr=false), UFC(min_threshold=0.40, max_credits=4m), MFC(min_threshold=0.40, max_credits=4m), FRAG4(frag_size=60000)]'
2023-10-19T13:29:37.3321415Z 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.channelFromConfigurator(JGroupsTransport.java:779)
2023-10-19T13:29:37.3323476Z 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.buildChannel(JGroupsTransport.java:748)
2023-10-19T13:29:37.3325390Z 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.initChannel(JGroupsTransport.java:503)
2023-10-19T13:29:37.3327207Z 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:484)
2023-10-19T13:29:37.3328950Z 	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:42)
2023-10-19T13:29:37.3330609Z 	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:27)
2023-10-19T13:29:37.3332465Z 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
2023-10-19T13:29:37.3334558Z 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
2023-10-19T13:29:37.3336638Z 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
2023-10-19T13:29:37.3338775Z 	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
2023-10-19T13:29:37.3340563Z 	at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:84)
2023-10-19T13:29:37.3341922Z 	at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:41)
2023-10-19T13:29:37.3343270Z 	at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:34)
2023-10-19T13:29:37.3345016Z 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
2023-10-19T13:29:37.3457909Z 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
2023-10-19T13:29:37.3460292Z 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
2023-10-19T13:29:37.3462441Z 	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
2023-10-19T13:29:37.3464640Z 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
2023-10-19T13:29:37.3466985Z 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
2023-10-19T13:29:37.3469522Z 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
2023-10-19T13:29:37.3471658Z 	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
2023-10-19T13:29:37.3473728Z 	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:379)
2023-10-19T13:29:37.3475695Z 	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:252)
2023-10-19T13:29:37.3477377Z 	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:779)
2023-10-19T13:29:37.3478445Z 	... 7 more
2023-10-19T13:29:37.3479200Z Caused by: java.lang.IllegalArgumentException: dns_query can not be null or empty
2023-10-19T13:29:37.3480472Z 	at org.jgroups.protocols.dns.DNS_PING.validateProperties(DNS_PING.java:85)
```

**Comment by shawkins** [comment]
@vmuzikar is it because cache-stack has been left as the default of kubernetes?

**Comment by vmuzikar** [comment]
> @vmuzikar is it because cache-stack has been left as the default of kubernetes?

Yes, looks like it. This theory corresponds with:
```
2023-10-19T13:29:37.3479200Z Caused by: java.lang.IllegalArgumentException: dns_query can not be null or empty
2023-10-19T13:29:37.3480472Z 	at org.jgroups.protocols.dns.DNS_PING.validateProperties(DNS_PING.java:85)
```
DNS_PING is used with `stack=kubernetes` AFAIK.

**Comment by shawkins** [comment]
> Yes, looks like it.

Updated the pr to remove the cache-stack, that seems to work.  Not sure why this wasn't reproducible locally.

**Review by vmuzikar — APPROVED** [review]

**Pull request merged**
