### PR TITLE
KEYCLOAK-13971 + KEYCLOAK-13636 Upgrade to EAP 7.4.0.CD19

### PR DESCRIPTION
**Pull request by martin-kanis**

### CODE REVIEW

**Review by douglaspalmer — DISMISSED** [review]
LGTM

**Review by douglaspalmer — APPROVED** [review]
LGTM

**Comment by stianst** [comment]
FIY I need this merged today

**Review by vramik — APPROVED** [review]
LGTM

**Review by abstractj — APPROVED** [review]

**Pull request merged**
