### PR TITLE
KEYCLOAK-14162 Uplifted Apache DS version for LDAPEmbeddedServer

### PR DESCRIPTION
**Pull request by tsaarni**
LDAPEmbeddedServer and KerberosEmbeddedServer depend on old version of ApacheDS which hangs occasionally on LDAP federation tests when StartTLS is used. This problem seems to happen very frequently with OpenJDK 11 (and later) on Ubuntu.

To fix the problem, update to the latest version of ApacheDS.

### CODE REVIEW

**Comment by tsaarni** [comment]
@mposolda, @iankko could you please review? Thank you!

### Removal of storage backend specific subclasses

This PR keeps both file and in-memory backend options, but I removed the `FileDirectoryServiceFactory` and `InMemoryDirectoryServiceFactory` subclasses since I believe they are not necessary anymore.  It is possible to configure a property for ApacheDS to choose the partition factory.  `DefaultDirectoryServiceFactory` then uses that to instantiate the correct partition type.

### Installing interceptor

There are two test cases that depend on adding `RangedAttributeInterceptor` for ApacheDS to impact the search behavior.  The test case code depending on the behavior is here, and it is also inherited by  `LDAPGroupMapperNoImportTest`
https://github.com/keycloak/keycloak/blob/38195ca789cb2c91fc1cd0393a75767f2f6ed3f2/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java#L725

The interceptor has been installed when in-memory server is used here 
https://github.com/keycloak/keycloak/blob/2602c222cda545b28eeb993e7f128bcf08695d25/util/embedded-ldap/src/main/java/org/keycloak/util/ldap/InMemoryDirectoryServiceFactory.java#L152

I have now copied this behavior: I add the interceptor always when in-memory backend is used. See here  https://github.com/Nordix/keycloak/blob/apacheds-uplift/util/embedded-ldap/src/main/java/org/keycloak/util/ldap/LDAPEmbeddedServer.java#L218

This maybe now looks bit stranger than previously, since it is now bit more visible and not really explained why the directory server partition type has any impact on ApacheDS interceptors.
  
*Question:* in theory there could be a new property to enable the interceptor per test case when needed. Do you think it would be worth of adding this property or is it ok like this?

**Comment by mposolda** [comment]
@tsaarni Thanks! PR looks nice to me.

I've tried locally that LDAPEmbeddedServer and KerberosEmbeddedServer can be still executed and "persistence" works as expected. I've tried to run our internal pipeline with the PR and will approve if that passes.

**Review by mposolda — APPROVED** [review]
Tests passed in our lab with all the JDK versions, so seems to be fine. Approving.

**Review by iankko — APPROVED** [review]
LGTM @tsaarni Thanks, Tero!

The former JDK11 hang seems to be gone with this version (AFAICT from testing) for all of the cases:
1. no debug options used at all,
2. using the `-Djavax.net.debug=ssl` one,
3. using the `-Djavax.net.debug=all` one.

**Comment by mposolda** [comment]
@tsaarni @iankko Thanks!

**Pull request merged**
