### PR TITLE
SLF4J for keycloak-adapter-core module

### PR DESCRIPTION
**Pull request by hendrikebbers**
As described in KEYCLOAK-6063 (https://issues.jboss.org/browse/KEYCLOAK-6063) the logging of keycloak and in special for the adapters is not well defined. In the code you can find several different patterns how logging is used. Based on this it is very hard to configure logging for keycloak.

I would love to refactor the code of all adapters to use SLF4J as logger facade and the same pattern for logging in all sources.

This PR does it for the `keycloak-adapter-core` module to give an overview what I want to do. Once this PR is merged I will do the same refactoring for all other modules.

### CODE REVIEW

**Comment by hendrikebbers** [comment]
@sebastienblanc 👋🍌😎

**Comment by stianst** [comment]
We shouldn't switch to use sl4j for adapters like this. The Keycloak code-base uses JBoss logging abstraction throughout and this refactoring results in the code-base using two different log abstraction frameworks.

Resolving KEYCLOAK-6063 can simply be done by just fixing the places where the log is not initialize correct. It doesn't entitle refactoring everything to use a different log abstraction framework.

**Review by stianst — CHANGES_REQUESTED** [review]
Remove changing to slf4j and just fix the broken log initalizations. Also, please squash to a single commit.

**Comment by hendrikebbers** [comment]
@stianst why not using SLF4J API? It is internally mapped to JBoss logging. So at the end it will be the same. The benefit comes into place when you use the adapters in a JavaEE or Spring application for example. Here most people do not use JBoss Logging. Based on that they can simple exclude the JBoss Logger and use it's own SLF4J implementation / logger. I for example often miss keycloak logging since it is not logged by slf4j and the logging config of the application just do not fit to keycloak. Next to this you already use SLF4J in several modules (spring-security-adapter, services, model-jpa...)

**Comment by hendrikebbers** [comment]
> Resolving KEYCLOAK-6063 can simply be done by just fixing the places where the log is not initialize correct. It doesn't entitle refactoring everything to use a different log abstraction framework.

Right! I just thought that it would make sense to have the same logger framework in all Java based modules in the repo. And this should not be JBoss logging ;)

**Comment by stianst** [comment]
Switching to sl4fj as the log abstraction may make sense, but that requires a wider discussion on the dev mailing list. It is certainly beyond the scope of what is described in KEYCLOAK-6063.

**Pull request closed without merging**
