### PR TITLE
KEYCLOAK-18470 Admin events trigger transaction rollback if exception is thrown

### PR DESCRIPTION
**Pull request by artur-baltabayev**

### CODE REVIEW

**Review by hongquyen196 — APPROVED** [review]

**Comment by hongquyen196** [comment]
Hello @artur-baltabayev  this topic I am interested in. When will the pull request merge?

**Comment by hongquyen196** [comment]
It seems you linked it with the wrong Jira. Can you fix please? KEYCLOAK-17841 or KEYCLOAK-17524

**Comment by artur-baltabayev** [comment]
@hongquyen196 Hello, thank you for the response ! It was decided to split the issue into two PR's. So this PR doesn't have a specific JIRA issue, but rather a parent issue (KEYCLOAK-17841).

**Comment by hongquyen196** [comment]
@artur-baltabayev What about KEYCLOAK-18740?. I see it in this title.

**Comment by artur-baltabayev** [comment]
@hongquyen196 You were correct ! The title was was wrong and there is a Jira issue. Sorry about that. Here is the correct issue : https://issues.redhat.com/browse/KEYCLOAK-18470

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
GitHub actions is not executing for some reason, so opened a new PR here https://github.com/keycloak/keycloak/pull/8424

**Comment by stianst** [comment]
Merged in https://github.com/keycloak/keycloak/pull/8424

**Pull request closed without merging**
