### PR TITLE
[KEYCLOAK-3213] getResponseCode was deprecated in Undertow 1.3

### PR DESCRIPTION
**Pull request by iperdomo**
- Use getStatusCode instead of the deprecated getResponseCode

### CODE REVIEW

**Comment by stianst** [comment]
This may break on older versions of Undertow though. When was getStatusCode introduced?

**Comment by iperdomo** [comment]
@stianst you have the exact commit in the issue. It seems that was introduced in version: `1.3.0.Beta10`

undertow-api-change

**Comment by iperdomo** [comment]
Keycloak was changed to use Undertow 1.3 in 1.9.x series - See: https://github.com/keycloak/keycloak/commit/1ee76a126f5a4a7e15c5277cf47d0bad0efd78e5

**Comment by stianst** [comment]
Undertow adapter is not used by Keycloak itself. It's used on WildFly. So what version is used in Keycloak is not relevant. The issue is when getStatusCode was introduced in Undertow. If that was introduced in 1.3 this change would break support for WildFly 8 and 9.

**Comment by stianst** [comment]
getStatusCode was introduced in Undertow 1.3. That means this change would break support for WildFly 8 and 9.

**Comment by iperdomo** [comment]
@stianst I fail to understand that if Keycloak was changed to use Undertow 1.3 as dependency (rev 1ee76a1) also broke the support for Wildfly 8 and 9 ? If this is not a valid question, it's just fine to close the pull request and reject the change. Thanks.

**Comment by stianst** [comment]
The version of Undertow is determined by the version of WildFly the adapter is used on, not what version is used by the Keycloak server. Hence we need to support Undertow 1.1, 1.2 and 1.3 with the adapter. Annoyingly the fact that getResponseCode is deprecated will mean that eventually we'll need multiple versions of the Undertow adapter, but we will probably change it once it's removed rather than before.

**Pull request closed without merging**
