### PR TITLE
Delete `Profile.Feature.MAP_STORAGE`

### LINKED ISSUE #24102: Map Store Removal: Delete Profile.Feature.MAP_STORAGE and all its usages
### Description

With the Map Store being removed, we have to ensure the `MAP_STORAGE` feature and it's usages are also removed.

### PR DESCRIPTION
**Pull request by vramik**
Closes #24102

### CODE REVIEW

**Comment by ahus1** [comment]
@vramik - unfortunately this PR picked up conflicts from other PRs in the meantime. Could you please rebase and resolve them? I'll see that I'll provide a timely review once it has been rebased. Thanks!

**Comment by martin-kanis** [comment]
@ahus1 I already reviewed it. Looks good. Waiting for the rebase and then I will approve.

**Review by mabartos — DISMISSED** [review]
Changes in Quarkus module LGTM

**Review by martin-kanis — APPROVED** [review]
@vramik Thanks for the PR. Looks good.

**Review by mhajas — DISMISSED** [review]
Thank you @vramik @martin-kanis and @mabartos!

**Review by martin-kanis — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]
Approving as of @martin-kanis's review. Thank you for this PR!

**Pull request merged**
