### PR TITLE
[KEYCLOAK-17933] Upgrade Keycloak to Wildfly 23.0.2.Final

### PR DESCRIPTION
**Pull request by iankko**
[KEYCLOAK-17933] Upgrade Keycloak to Wildfly 23.0.2.Final
    
    Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

### CODE REVIEW

**Comment by iankko** [comment]
@pskopek @hmlnarik @martin-kanis @vramik PTAL once got a chance

Thanks,
Jan

**Review by martin-kanis — APPROVED** [review]

**Comment by iankko** [comment]
Testing pipeline runs:
- Adapter: https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/222/
- Server: &nbsp; https://keycloak-jenkins.com/job/universal-test-pipeline-server/330/

**Comment by iankko** [comment]
JFTR, filed [KEYCLOAK-17943](https://issues.redhat.com/browse/KEYCLOAK-17943) to track the ```ClientPoliciesImportExportTest.testSingleFileRealmExportImport``` GHA failure above.

**Comment by vramik** [comment]
Adapter: https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/224/
Server:   https://keycloak-jenkins.com/job/universal-test-pipeline-server/332/

**Review by vramik — APPROVED** [review]

**Review by mhajas — APPROVED** [review]
I went through CI failures and I believe there is nothing caused by this PR. Approving.

**Review by hmlnarik — APPROVED** [review]
Thank you for your contribution!
Approving, based on previous approvals.

**Pull request merged**
