### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by TheKeeroll**
Signed-off-by: Zakhar Stepanov <57570053+TheKeeroll@users.noreply.github.com>

### CODE REVIEW

**Comment by mhajas** [comment]
@TheKeeroll Could you please [sign off](https://github.com/keycloak/keycloak/pull/26526/checks?check_run_id=20894482975) your commit?

**Review by jonkoops — DISMISSED** [review]
LGTM 🎪

**Comment by jonkoops** [comment]
@TheKeeroll could you [sign off](https://github.com/keycloak/keycloak/pull/26526/checks?check_run_id=20894482975) on your commit? Thanks!

**Comment by TheKeeroll** [comment]
Will do it in 4 hours

**Comment by TheKeeroll** [comment]
done!

**Comment by jonkoops** [comment]
Looks like the commit isn't signed yet, please amend it so that it is signed off.

**Review by ahus1 — APPROVED** [review]
Thank you for this fix!

**Pull request merged**
