### PR TITLE
Retrieve ClientConnection by invoking getConnection() instead of getContextObject()

### PR DESCRIPTION
**Pull request by Eng-Fouad**
Fixes #25231

### CODE REVIEW

**Comment by mabartos** [comment]
@pedroigor Can you check it? Might be related to the RR changes. Weird stuff that we haven't caught it in CI, so probably some tests are missing for this case.

**Comment by pedroigor** [comment]
@mabartos Yeah, I'm wondering the same.

**Comment by pedroigor** [comment]
I think the reason is because of the HTTP scheme that is being used when reproducing the error. The report is using `http` and in this case, the check using the client connection will run.

Given that our test suite only runs on `https` we did not catch it.

@Eng-Fouad does it make sense for you?

**Review by pedroigor — APPROVED** [review]
I did a quick search in the code base and these should be the last and remaining places  where we did not update usages of client connection.

**Comment by Eng-Fouad** [comment]
> I think the reason is because of the HTTP scheme that is being used when reproducing the error. The report is using `http` and in this case, the check using the client connection will run.
> 
> 
> 
> Given that our test suite only runs on `https` we did not catch it.
> 
> 
> 
> @Eng-Fouad does it make sense for you? 

Yes, it could be that. I'm using http in development (launching Keycloak using Quarkus devservices).

Would this PR help fixing the error?

**Comment by pedroigor** [comment]
@mabartos Do we want a test for this? I mean, if so we probably need a job running not only tests for CIBA/PAR but at least a few others to sanity check usages of the `http` scheme... Not sure if we want that now.

**Pull request merged**
