### PR TITLE
[KEYCLOAK-10407] - Avoiding redundant calls on identity.getid

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by tkyjovsk — COMMENTED** [review]
Code seems fine. Let me run a quick perf test early next week to see if it helped.

**Comment by pedroigor** [comment]
@tkyjovsk do you have any clue why I'm getting the failures from Travis ? Not sure if they are related and they are compilation issues. The branch is rebased accordingly.

**Comment by tkyjovsk** [comment]
> @tkyjovsk do you have any clue why I'm getting the failures from Travis ? Not sure if they are related and they are compilation issues. The branch is rebased accordingly.

The compilation error looks like related to some IO failure..
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] error reading /home/travis/.m2/repository/org/jboss/as/jboss-as-web/7.2.0.Final/jboss-as-web-7.2.0.Final.jar; error in opening zip file
[ERROR] error reading /home/travis/.m2/repository/org/jboss/as/jboss-as-web/7.2.0.Final/jboss-as-web-7.2.0.Final.jar; cannot read zip file
```

**Comment by stianst** [comment]
@tkyjovsk did you get a chance to run a perf test on this?

**Comment by tkyjovsk** [comment]
> @tkyjovsk did you get a chance to run a perf test on this?

Sorry, not yet. Looking into it now.

**Comment by tkyjovsk** [comment]
So I managed to somewhat reproduce the reported performance problem with master branch, and verify the KEYCLOAK-10407.

The permission evaluation with the second client (with service account disabled) takes consistently 2-3 times longer than with the first client (with service accounts enabled). In the KEYCLOAK-10407 branch the performance is roughly the same for both clients.

(I used a slightly modified authz dataset from the performance testsuite (1k resources, 10 scopes, 1k permissions, 100 role policies), with some additional JS policies from the JIRA mixed-in.)

**Review by tkyjovsk — APPROVED** [review]

**Review by stianst — APPROVED** [review]

**Pull request merged**
