### PR TITLE
[KEYCLOAK-3723] Fixed updated of protocol mappers within client updater

### PR DESCRIPTION
**Pull request by kris2kris**
I just rebase https://github.com/keycloak/keycloak/pull/5267 on my own repository to merge it

### CODE REVIEW

**Comment by stianst** [comment]
@mposolda could this introduce some security vulnerabilities? Or is the client registration policies handling this properly?

**Comment by mposolda** [comment]
@stianst yes, the client registration policies handle this. The "untrusted" protocol mappers shouldn't be allowed. We already test that updating protocol mappers will fail if untrusted mapper was used - even if update of mappers itself won't work :) It is ClientRegistrationPoliciesTest.testProtocolMappersUpdate()

@kris2kris Thanks for the PR! LGTM.

**Review by mposolda — APPROVED** [review]

**Comment by sharpedavid** [comment]
@mposolda Hi Marek, I have a quick question. I've tested this a bunch on Keycloak 9.0.2 and Keycloak 11.0.2. What I'm seeing is that it's working in 11.0.2, but not 9.0.2. I'm confused because this was merged in March 3 2019, and Keycloak 5.0.0 was released March 6, and so this fix should be working in Keycloak 9.0.2.

In either case I run a simple test using the Admin CLI:

```cmd
C:\>cd C:\Dev\keycloak-11.0.2\bin

C:\Dev\keycloak-11.0.2\bin>kcadm config credentials --server http://localhost:8080/auth --realm master --user admin --client admin-cli
Logging into http://localhost:8080/auth as user admin of realm master
Enter password: *****

C:\Dev\keycloak-11.0.2\bin>kcadm create clients -r master -s clientId=my_client -s "redirectUris=[\"http://localhost:8980/myapp/*\"]" -i > clientid.txt

C:\Dev\keycloak-11.0.2\bin>set /p CID=<clientid.txt

C:\Dev\keycloak-11.0.2\bin>kcadm get clients/%CID% > my_client.json

REM Here change the client description and add a protocol mapper.

C:\Dev\keycloak-11.0.2\bin>kcadm update clients/%CID% -f my_client.json
```

This doesn't work in 9.0.2, but it does work in 11.0.2.

Anyhow, of course I'm not asking anyone to fix this in an old version, I'm just trying to understand a little why it's not working, maybe there is something I could do better. Am I misunderstanding when this commit would have been released?

**Comment by mposolda** [comment]
@sharpedavid Hi, not sure TBH. This is old thing and lots had changed since then. It will be an effort to track exactly why it works as expected in new version and doesn't work in the historic version. If it is an option for you, I suggest to upgrade to the newest version (not just because of this, but because of other fixes and security patches).

**Pull request merged**
