### PR TITLE
[account-ui] Move PatternFly dependencies into peer dependencies and make them external

### PR DESCRIPTION
**Pull request by antoine-roux**
According to #31526, embedding the PatternFly code into the `account-ui` library make the `PageContext` duplicated.
This breaks the sidebar because `isManagedSidebar` uses this context.

Moving these dependencies into peer dependencies and make them external evacuate the code of PatternFly away, letting the opportunity to the final bundler to pack all this "library mix" properly.

### CODE REVIEW

**Review by edewit — APPROVED** [review]

**Comment by edewit** [comment]
@antoine-roux can you  `rollup-plugin-peer-deps-external` to the `pnpm-lock.yaml` ?

**Review by edewit — CHANGES_REQUESTED** [review]
@antoine-roux can you rollup-plugin-peer-deps-external to the pnpm-lock.yaml ?

**Review by edewit — DISMISSED** [review]

**Comment by antoine-roux** [comment]
@edewit sorry, I was not available
I see you pushed a commit for this. Do you need me for more?

**Comment by edewit** [comment]
@antoine-roux still something wrong with the lock file, I can have a look

**Review by edewit — DISMISSED** [review]

**Review by edewit — DISMISSED** [review]

**Review by edewit — DISMISSED** [review]

**Review by edewit — APPROVED** [review]

**Comment by edewit** [comment]
with this change the UI no longer runs

**Comment by antoine-roux** [comment]
Hello @edewit,

I will adapt my PR the same way you did for the LIB mode. This change is crucial if you want us to use your library.
I agree the PatternFly code must be bundled for your "app" version, but absolutely not into the distributed "lib" one.

(let me finish my day before I make changes)

Antoine

**Pull request closed without merging**
