### PR TITLE
Revert "removing admin ui excludes (#13752)"

### PR DESCRIPTION
**Pull request by edewit**
This reverts commit 15b258bf26a1771f0419b15fc9563166ff6485ac.

### CODE REVIEW

**Comment by stianst** [comment]
PR itself looks good, but we shouldn't merge this one until admin-ui endpoints have removed the additional dependencies, and we have a nightly build of the admin-ui ready with that change included.

**Comment by edewit** [comment]
we don't have to wait for a nightly build as our tests run against main but we do have to wait until this PR is merged https://github.com/keycloak/keycloak-ui/pull/3183

**Review by stianst — APPROVED** [review]

**Comment by edewit** [comment]
@stianst #13963 is not a duplicate, this one updates the main build config and the other the tests

**Comment by stianst** [comment]
@edewit sorry, was looking only on changes, and completely missed it was changes in different files. Re-opened the other PR now.

**Pull request merged**
