### PR TITLE
Add the resourceTypes query parameter to the admin clients getAdminEvents method

### PR DESCRIPTION
**Pull request by jhollmannk**
The REST endpoint to get the admin events has the resourceTypes query parameter (as a list of strings) but this query parameter is missing in the getAdminEvents method of the admin-client.

This missing query parameter is added in this pull request.

Tested this by creating the admin-client-jar and successfully used it in our application with the new resourceTypes query parameter.

### CODE REVIEW

**Comment by stianst** [comment]
Due to backwards compatibility of the admin client we'd need a new method added that includes the new parameter, rather than just extending the current one. Can you just keep the current one as is, and introduce a new method in the way it's done in this PR?

**Comment by jhollmannk** [comment]
Uups! You're right, backward compatibility!
I have added an additional getAdminEvents method. You will have to look closely to see the difference in the parameter list though. I think this is acceptable.

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
> Uups! You're right, backward compatibility! I have added an additional getAdminEvents method. You will have to look closely to see the difference in the parameter list though. I think this is acceptable.

Great, thanks. LGTM, just need to wait for CI to finish before merging.

**Comment by jhollmannk** [comment]
I don't think that the Quickstart Tests fail because of my changes. The log says "The process '/usr/bin/git' failed with exit code 1".
Can someone look into this or try to run the CI Tests again?

**Pull request merged**
