### PR TITLE
Aurora Postgres IT: Upload flaky and surefire test reports

### LINKED ISSUE #26967: Aurora Postgres IT: Upload flaky and surefire test reports
### Description

The Store IT CI for Aurora Postgres utilises ansible playbooks to execute the Store IT tests in a EC2 instance in the same AWS region as the Aurora cluster. 

* Currently all test flakes/failures are reported to the std err/out of the CI action, however their counterpart files are not updated to GitHub as an artifact and so will not be centrally reported.
* Maven is run without the batch flag `-B` which creates a lot more output than needed
* The Aurora tasks should be skipped if now AWS token is available to avoid errors on forked repositories
* If possible, use the logtrimmer.sh but ensure the exitcode is preserved. This should be possible using `set -o pipefail
`

### PR DESCRIPTION
**Pull request by ryanemerson**
Closes #26967

Store IT test run: https://github.com/ryanemerson/keycloak/actions/runs/7919275570

### CODE REVIEW

**Comment by ahus1** [comment]
@ryanemerson - thank you for this PR. 

In the parent issue you mention that you didn't add `pipefail` as it would change the default behavior. While the analysis of the XML files picks up unstable tests, the test failure rely on Maven exiting with a non-zero exitcode.

I did some research and found: 

* The workflow `ci.yml` specifies `bash` as the default shell
* The shell `bash` on GitHub actions defines by default the `pipefail`, see [this overview of shells in jobs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell)

I'm adding one more commit to the `run.yml`, let me know what you think about this. Adding the `executable` might not be 100% necessary if the default shell on the remote is already `bash`, but let's be safe.

**Comment by ryanemerson** [comment]
> In the parent issue you mention that you didn't add `pipefail` as it would change the default behavior. While the analysis of the XML files picks up unstable tests, the test failure rely on Maven exiting with a non-zero exitcode.

The other store IT tests are executed with the following code:

```
          TESTS=`testsuite/integration-arquillian/tests/base/testsuites/suite.sh database`
          echo "Tests: $TESTS"
          ./mvnw test ${{ env.SUREFIRE_RETRY }} -Pauth-server-quarkus -Pdb-${{ matrix.db }} -Dtest=$TESTS -pl testsuite/integration-arquillian/tests/base 2>&1 | misc/log/trimmer.sh
```

In ^ `set -o pipefail` is not set, so a mvn failure exit code will be hidden by `trimmer.sh`, or am I missing something?

**Comment by ahus1** [comment]
> or am I missing something?

See below for a screenshot of the GitHub docs. The set it automatically one you choose bash as a shell. And bash is set as a default in this workflow.

image

**Comment by ryanemerson** [comment]
> See below for a screenshot of the GitHub docs. The set it automatically one you choose bash as a shell. And bash is set as a default in this workflow.

Great to know, thanks for explaining :+1:

**Review by ahus1 — APPROVED** [review]
Thank you for this PR!

**Pull request merged**
