### PR TITLE
KEYCLOAK-3429 Fix behaviour of redirect_uri parameter with query components

### PR DESCRIPTION
**Pull request by vmuzikar**

### CODE REVIEW

**Comment by stianst** [comment]
I'm not 100% sure this is correct. It's also changes the current behavior that can break existing clients as used to simply ignore the query parameters when comparing redirect uri.

**Comment by vmuzikar** [comment]
Yes, I agree, I don't like it either, because it may change behavior in some cases, as you say.
However, I don't think we have other option as we want to comply with the OIDC Dynamic Profile.

**Comment by stianst** [comment]
I assume there are some tests in the conformance testing that fails due to this? Can you provide some details around what's expected there?

**Comment by vmuzikar** [comment]
This PR is related to `OP-redirect_uri-Query-Added` and `OP-redirect_uri-Query-OK` of the Dynamic Profile.

`OP-redirect_uri-Query-Added` registers a client with Redirect URI without a query, something like `http://localhost/auth`. Then it performs an authorization request with Redirect URI which has a query, something like `http://localhost/auth?foo=bar` and expects the OP to reject this request.

Whereas `OP-redirect_uri-Query-OK` registers URI with a query like `http://localhost/auth?foo=bar` and performs auth request with the same URI and expects this to success.

Both test are failing (not just a warning), so we can't ignore this.

You can see the test results and related JIRAs at https://docs.google.com/spreadsheets/d/1TMDcpQznLEPE4sLXWgL802wm116OQvQcyZ77hQXWpQQ/edit?pref=2&pli=1#gid=0

**Pull request merged**
