### PR TITLE
Move from NPM to PNPM

### PR DESCRIPTION
**Pull request by jonkoops**
Changes the default package manager for code under the `js` directory from NPM to [PNPM](https://pnpm.io/).

This has several reasons but primarily it will help us simplify the release workflow. Specifically PNPM allows packages to be linked together in a workspace using the [workspace protocol](https://pnpm.io/workspaces#workspace-protocol-workspace).

This means that packages in the workspace do not have to share a version, removing the need to set these versions in `set-version.sh` except for the packages that need to be published.

Another major benefit of PNPM is that unlike [`npm ci`](https://docs.npmjs.com/cli/v9/commands/npm-ci) it preserves the `node_modules` directory between installs, allowing for faster install times (especially in Maven builds). This should significantly reduce time spent installing dependencies for each of [the modules](https://github.com/keycloak/keycloak/blob/6b3eb463144763ade3afb4b4d29378eecafffc2b/js/pom.xml#L18-L23) (this command is repeated for each of them).

There are more reasons as mentioned in [pnpm vs npm](https://pnpm.io/pnpm-vs-npm), mostly it avoids some [silly bugs](https://www.kochan.io/nodejs/pnpms-strictness-helps-to-avoid-silly-bugs.html) that we experience with NPM.

### CODE REVIEW

**Review by edewit — APPROVED** [review]

**Review by ssilvert — APPROVED** [review]
LGTM

**Comment by tnorimat** [comment]
@jonkoops 

I'm afraid that the keycloak's build (mvn clean install -DskipTests) fails when the proxy exists in front of the PC that builds keycloak. "proxy" and "https-proxy" settings are in .npmrc file.

I am not sure whether this PR causes this problem.

The maven's log is as follows (win 10 PC):

[INFO] --- frontend-maven-plugin:1.12.1:pnpm (run-build) @ keycloak-js-admin-client ---
[INFO] Found proxies: [http{protocol='http', host='ZZZZZZZZ', port=8080, nonProxyHosts='local.net|some.host.com', with username/passport authentication}, https{protocol='https', host='ZZZZZZZZ', port=8080, nonProxyHosts='local.net|some.host.com', with username/passport authentication}]
[INFO] Running 'pnpm run build --https-proxy=ZZZZZZZZ --proxy=ZZZZZZZZ --noproxy=local.net,some.host.com' in C:ZZZZZZZZ\keycloak\js\libs\keycloak-admin-client
[INFO]
[INFO]  @keycloak/keycloak-admin-client@999.0.0-SNAPSHOT build C:ZZZZZZZZ\keycloak\js\libs\keycloak-admin-client
[INFO]  wireit "--https-proxy=ZZZZZZZZ" "--proxy=ZZZZZZZZ "--noproxy=local.net,some.host.com"
[INFO]
[INFO] ?? Unrecognized Wireit argument(s): "--https-proxy=ZZZZZZZZ", "--proxy=ZZZZZZZZ", "--noproxy=local.net,some.host.com". To pass arguments to the script, use a double-dash, e.g. "npm run build -- --extra".
[INFO] ? [build] Already fresh
[INFO]
[INFO] --- maven-antrun-plugin:1.8:run (create-target-dir) @ keycloak-js-admin-client ---
[INFO] Executing tasks

main:
[INFO] Executed tasks
[INFO]
[INFO] --- maven-source-plugin:3.1.0:jar-no-fork (attach-sources) @ keycloak-js-admin-client ---
[INFO]
[INFO] --- frontend-maven-plugin:1.12.1:pnpm (pack) @ keycloak-js-admin-client ---
[INFO] Found proxies: [http{protocol='http', host='ZZZZZZZZ', port=8080, nonProxyHosts='local.net|some.host.com', with username/passport authentication}, https{protocol='https', host='ZZZZZZZZ', port=8080, nonProxyHosts='local.net|some.host.com', with username/passport authentication}]
[INFO] Running 'pnpm pack --pack-destination=target --https-proxy=ZZZZZZZZ --proxy=ZZZZZZZZ --noproxy=local.net,some.host.com' in C:ZZZZZZZZ\keycloak\js\libs\keycloak-admin-client
[INFO] ?ERROR? ?ERROR? Unknown options: 'https-proxy', 'proxy', 'noproxy'
[INFO] For help, run: pnpm help pack

**Comment by jonkoops** [comment]
Looks like the proxy arguments are also being passed into `pnpm pack` for some reason, which does not support these command like arguments. I also see a warning for other commands that are getting these arguments passed into them.

I suspect this is an issue in the [`maven-frontend-plugin`](https://github.com/eirslett/frontend-maven-plugin) detecting your proxy settings and passing it into every command (which it shouldn't). Could you raise an issue on their repo?

**Comment by jonkoops** [comment]
@tnorimat Might also be able to get this to work by passing the following the configuration of said plugin:

```xml
<configuration>
  <pnpmInheritsProxyConfigFromMaven>false</pnpmInheritsProxyConfigFromMaven>
</configuration>
```

**Comment by jonkoops** [comment]
Awesome, feel free to shoot us a PR if this feels like it could be a generic fix.

**Comment by tnorimat** [comment]
@jonkoops I confirmed that your suggestion works in [frontend-maven-plugin](https://github.com/eirslett/frontend-maven-plugin/blob/ec9f8050bc4c4014bbeb1ea84ae92e11682d9764/frontend-maven-plugin/src/main/java/com/github/eirslett/maven/plugins/frontend/mojo/PnpmMojo.java#L28) .
Also I confirmed that I can build keycloak in the build environment with and without proxy.
Therefore, I will create an issue and send a PR for adding this configuration. WDYT?

**Comment by ASzc** [comment]
So this broke the product build in a moderately severe way. NPM is not installed by maven in the product build, it's provided by the OS. I'm still figuring out how best to make PNPM work without installing it at build time. We might need that `pnpmInheritsProxyConfigFromMaven` config option too.

**Comment by ASzc** [comment]
Honestly the most tempting thing to do is to rip out PNPM and put NPM back in for the product build. It doesn't seem like PNPM and NPM are interchangeable though. I may have to request a special build environment with PNPM. This is not a tool normally available in the product build system

**Comment by jonkoops** [comment]
If you can access NPM packages in your environment it should be possible to install PNPM through NPM as it is [published on the registry](https://www.npmjs.com/package/pnpm). You can install it globally as follows:

```bash
npm i -g pnpm
```

**Comment by ASzc** [comment]
@tnorimat @jonkoops I have filed an issue and PR to fix this here:

https://github.com/keycloak/keycloak/issues/20372
https://github.com/keycloak/keycloak/pull/20373

**Pull request merged**
