### PR TITLE
Removing version overrides and further aligning with quarkus versions

### LINKED ISSUE #26535: Post Quarkus 3.7 dependency alignment
A breakdown of dependency issues following the quarkus upgrade:

Versions where we trail quarkus - may need individual issues:
- bc-fips to 1.0.2.4 - exhibited classloading problems
- liquibase to 4.25.1 - even after updating CustomLockService, there is still a test failure 
- osgi to 6.0 - didn't build successfully

Versions where we are ahead of quarkus, and that are used for more than tests:
- jakarata.mail - quarkus is actually still using com.sun.mail, rather than jakarta.mail https://github.com/quarkusio/quarkus/issues/26989

Versions where we are even with quarkus, but have our own property:
- slf4j - used only for an additional test dependency not covered by the quarkus bom
- infinispan - used for more than tests and need the version to import the infinispan bom

Versions where we are trail quarkus, and that are used for more than tests, but seem to upgrade without an issue:
- resteasy
- wildfly-elytron

And a lot of test related dependencies / overlap - mostly drivers, but also awaitility, hamcrest, and testcontainers. Driver versions cannot be removed because we reference them as variables in our tests to switch between databases.

_Originally posted by @shawkins in https://github.com/keycloak/keycloak/pull/26203#discussion_r1467792077_

### PR DESCRIPTION
**Pull request by shawkins**
This further aligns us to quarkus versions and removes some test overrides where we can use the quarkus version.

closes #26535 

cc @Pepo48 @vmuzikar

### CODE REVIEW

**Review by vmuzikar — COMMENTED** [review]
@shawkins Thank you for this PR!

I wonder if we still need to keep the explicitly set versions for resteasy, db drivers and elytron. Can't we just rely on Quarkus BOM with those too?

**Comment by shawkins** [comment]
> I wonder if we still need to keep the explicitly set versions for resteasy, db drivers and elytron. Can't we just rely on Quarkus BOM with those too?

No, we make use of all of those versions in some way that is not covered by the bom import. There's some description of that in the issue.

**Review by Pepo48 — APPROVED** [review]
LGTM. Thanks @shawkins.

**Review by vmuzikar — APPROVED** [review]
@shawkins Ah, right, thanks!

@keycloak/store Do you want to review as well since this concerns DB drivers?

**Review by ahus1 — APPROVED** [review]
Approving for the store team. Thank you for this change!

**Pull request merged**
