### PR TITLE
quarkus-next: keystore/trust store type is determined based on file extension

### LINKED ISSUE #29207: quarkus-next: keystore/trust store type is determined based on file extension
### Description

Keycloak should be aligned with the most recent Quarkus changes in this area:

> In 3.9, JKS is no longer the default keystore and trust store format. Quarkus makes an educated guess based on the file extension:
> * .pem, .crt and .key are read as PEM certificates and keys
> * .jks, .keystore and .truststore are read as JKS key stores and trust stores
> * .p12, .pkcs12 and .pfx are read as PKCS12 key stores and trust stores
> If your file does not use one of these extensions, you need to set the format using:
> `quarkus.http.ssl.certificate.key-store-file-type=JKS # or P12 or PEM`
> `quarkus.http.ssl.certificate.trust-store-file-type=JKS # or P12 or PEM`

Source: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9#keystore-and-trust-store-default-format-change

This change causes `FipsDistTest#testHttpsPkcs12TrustStoreInNonApprovedMode` to fail. The problems were first spotted in the `quarkus-next` branch.

### PR DESCRIPTION
**Pull request by Pepo48**
- reflect the new [default truststore/keystore format mechanism](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9#keystore-and-trust-store-default-format-change), which causes some FipsDistTests to fail

Closes: #29207

### CODE REVIEW

**Review by shawkins — APPROVED** [review]
LGTM, thanks @Pepo48

**Comment by vmuzikar** [comment]
@Pepo48 I took the liberty of changing the PR name to better reflect the changes.

Tests seems to be failing due though. But I assume we're blocked by https://github.com/keycloak/keycloak/issues/29438 in any case.

**Comment by Pepo48** [comment]
@vmuzikar yes, #29438 needs to be merged first and then I can rebase this one in order to make the CI work.

**Comment by Pepo48** [comment]
@vmuzikar given the PR name change I would then definitely split it into two separate PRs since d41a975238c57c72add4cd275f02293b7d149961 is now kinda unrelated.

**Comment by vmuzikar** [comment]
@Pepo48 Works for me 👍

**Comment by Pepo48** [comment]
I split the PRs, here's the other one: https://github.com/keycloak/keycloak/pull/29584

I think that both are ready to be merged into the `quarkus-next` branch at this point.

cc: @vmuzikar

**Review by vmuzikar — COMMENTED** [review]
Changes LGTM but I wonder what can we do about release notes, it's essentially a breaking change that the type is now assumed from the file extension. Maybe we could start release notes for 26?

**Comment by Pepo48** [comment]
@vmuzikar should it be part of this commit or should I create a follow-up that will go directly to the main branch?

**Comment by Pepo48** [comment]
@vmuzikar I added a release note as you suggested. PTAL. Thanks!

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@Pepo48 Thank you for adding the release notes. I realized I said "release notes" but it's more of a breaking change that should be in the [upgrading guide](https://github.com/keycloak/keycloak/tree/main/docs/documentation/upgrading/topics/changes). Could you please move it there? Sorry about that.

I also noticed this PR now includes the version bump from bot. Can you please remove it?

**Comment by Pepo48** [comment]
@vmuzikar I moved it, can you, please, check it again? Thanks!

**Review by vmuzikar — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
