### PR TITLE
KEYCLOAK-10303 configure JS Adapter to use PKCE

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Comment by stianst** [comment]
Looks good. Would be nice to double check that the code_challenge is being sent to the login screen just to be double sure that PKCE is actually enabled.

**Comment by stianst** [comment]
Basically when not logged-in the first request after opening the admin console (when it displays username/password) should include the code_challenge query parameter.

**Comment by mposolda** [comment]
Just noticed this PR. Few points to it:
- Description in JIRA talks about admin console, but this PR seems to change the account console? I guess that we want PKCE for both the admin console and new account console. So we can just keep the change for the account console and add the admin console on top of that?
- There is new switch for the client like "Proof Key for Code Exchange Code Challenge Method" . It is in the admin console in client settings and you need to click on "Advanced Settings" in client details. When this is changed to "S256", then Keycloak server will enforce that client MUST authenticate with S256 . So maybe we should change that default value for the built-in clients for admin console and account console to S256? In that case, we might change this also when migrating from previous version.

**Comment by stianst** [comment]
There should be one JIRA for account and one for admin console, and yes we want both.

Wasn't aware that we had the switch - so yes, for sure we want to enable that for built-in clients.

**Comment by abstractj** [comment]
@edewit @stianst @mposolda there's a PR for that for the new Account console https://github.com/keycloak/keycloak/pull/6675

@edewit https://issues.redhat.com/browse/KEYCLOAK-10303 is for the Admin console

**Comment by stianst** [comment]
I can do the changes to client config updates next week, so can hijack/takeover the PR.

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
Added a follow-up to update the admin client settings here https://issues.redhat.com/browse/KEYCLOAK-12829

**Pull request merged**
