### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Keycloak/Admin UI](https://hosted.weblate.org/projects/keycloak/admin-ui/).

It also includes following components:

* [Keycloak/Theme base/account](https://hosted.weblate.org/projects/keycloak/theme-baseaccount/)

* [Keycloak/Theme base/login](https://hosted.weblate.org/projects/keycloak/theme-baselogin/)

* [Keycloak/Theme base/email](https://hosted.weblate.org/projects/keycloak/theme-baseemail/)

* [Keycloak/Account UI](https://hosted.weblate.org/projects/keycloak/account-ui/)

* [Keycloak/Theme base/admin](https://hosted.weblate.org/projects/keycloak/theme-baseadmin/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by ahus1** [comment]
@DimitriDR / @gilbert-fernandes - can one of you please review the French translations in this PR? Thanks!

**Comment by ahus1** [comment]
@jmallach / @Ecron - can one of you please review the Catalan translations in this PR? Thanks!

**Comment by ahus1** [comment]
@DimitriDR / @gilbert-fernandes - this is a gentle reminder to review the *French translations*. A timely feedback ensures that these PRs that combine multiple languages can be merged. As an alternative, we could revert for the French language to go back to regular pull requests without Weblate. 

If you think the current process is lacking or insufficient in any way, please reach out so we can look into ways to resolve it. Thanks!

**Comment by ahus1** [comment]
@jmallach / @Ecron -  this is a gentle reminder to review the *Catalan translations* in this PR. A timely feedback ensures that these PRs that combine multiple languages can be merged. As an alternative, we could revert for the French language to go back to regular pull requests without Weblate.

If you think the current process is lacking or insufficient in any way, please reach out so we can look into ways to resolve it. Thanks!

**Comment by DimitriDR** [comment]
> @DimitriDR / @gilbert-fernandes - this is a gentle reminder to review the _French translations_. A timely feedback ensures that these PRs that combine multiple languages can be merged. As an alternative, we could revert for the French language to go back to regular pull requests without Weblate.
> 
> If you think the current process is lacking or insufficient in any way, please reach out so we can look into ways to resolve it. Thanks!

Hello, I don't use Keycloak anymore for a long time now, thus, my long response times (plus the fact that I don't go on GH regularly). I won't be able to review this one. I'll get back to you when I have time to get involved in the project again. Thanks!

**Comment by ahus1** [comment]
Closing this PR as there haven't been reviews for CA and FR translations. 

Any native speaker who want to re-submit this as a verified translation, please create new PRs from this one. CA and FR will be removed from Weblate for the time being.

**Comment by jmallach** [comment]
Hi @ahus1! Sorry, I would swear I had given my 👍 here, in fact I made some minor changes in weblate before going ahead with the approval!

**Pull request closed without merging**
