### PR TITLE
Issue: Admin UI doesnt allow to un-select a theme in the realm

### LINKED ISSUE #24119: Admin UI doesn't allow to un-select a theme in the realm
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When I open the themes tab of a new realm, no themes are selected. I assume Keycloak then uses a default theme. 

Once I've chosen a theme, I can't unselect it any more. I  

### Version

999-SNAPSHOT

### Expected behavior

The open "Select..." or "Choose..." should be available even if I have previously selected a theme.

### Actual behavior

The open "Select..:" or "Choose..." is not available after I've chosen a theme

### How to Reproduce?

* Create a new realm
* Choose the realm's "Themes" tab
* Select a theme
* Save -> The option "Select..." is now gone

### Anything else?

Allowing to select no theme allows users to always use the default theme. If they can't unselect a previously selected theme, there is no way for them to go back to the default.

### PR DESCRIPTION
**Pull request by vikasrajputin**
Solution: Added a new option in ThemesTab.tsx for "Choose..." option in all four dropdowns appearing in admin theme setting - login theme, account theme, admin theme and email theme

Closes #24119

### CODE REVIEW

**Review by edewit — APPROVED** [review]

**Comment by vikasrajputin** [comment]
Hello @edewit @ssilvert
Do let me know if anything is required from my end.

**Review by ahus1 — DISMISSED** [review]
Approving based on @edewit's review

**Comment by ahus1** [comment]
@vikasrajputin - it seems that the newly added test "Go to themes tab, Reset selected theme" currently fails in CI. While it is failing, this PR can't be merged. Please have a look.

**Comment by vikasrajputin** [comment]
@ahus1 - Any documentation link where I can see how to run frontend test cases on my local?

**Comment by ahus1** [comment]
maybe from the frontend team like @edewit can help here?

**Comment by jonkoops** [comment]
@keycloak/ui

**Comment by jonkoops** [comment]
The documentation on how to run the test can be found in the [contribution guide](https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/CONTRIBUTING.md#keycloak-admin-ui) of the admin console.

**Comment by edewit** [comment]
closed in favour of https://github.com/keycloak/keycloak/pull/33822

**Pull request closed without merging**
