### PR TITLE
Impossible to update a federated user credential label

### LINKED ISSUE #16613: Impossible to update a federated user credential label
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

When an administrator modifies a federated user credential's label from the admin UI and click on "Save", the new user label is not saved.

### Version

20.0.3

### Expected behavior

When modifying a federated user credential's label from the admin UI and click on "Save", the new user label is saved.

### Actual behavior

When modifying a federated user credential's label from the admin UI and click on "Save", the new user label is not saved.

### How to Reproduce?

1) Create a federated user with a credential
2) In the admin UI, search for this user
3) In the credentials tab, modify the credential label and click on save

### Anything else?

The bug comes from org.keycloak.storage.jpa.JpaUserFederatedStorageProvider#updateCredential(org.keycloak.models.RealmModel, java.lang.String, org.keycloak.credential.CredentialModel) : the entity is not updated with the user label coming from the credential model given in parameter, it is the other way around

### PR DESCRIPTION
**Pull request by arthur25000**
Closes #16613

### CODE REVIEW

**Review by mposolda — APPROVED** [review]
PR looks good to me, Thanks!

We just need to make sure that tests are passing (hopefully I am able to run CI once our testsuite is fixed).

**Review by mposolda — CHANGES_REQUESTED** [review]
@arthur25000 Tests are failing for the new store. Those needs to be fixed. In other words, you need to fix this in the new store as well (even if new store is currently not used in Keycloak by default).

**Review by mhajas — APPROVED** [review]
Thanks @arthur25000. The PR LGTM. Also, ignoring the test for `MapStorage` is the correct thing to do in this case.

**Comment by arthur25000** [comment]
Hi @mposolda 

Would you mind have a look at this PR and approve it if it's ok for you ?

**Review by mposolda — APPROVED** [review]
@arthur25000 Thanks

**Pull request merged**
