### PR TITLE
Add Arabic locale to messages

### LINKED ISSUE #15933: Add Arabic translations
### Description

I want to participate in Arabic translations. Which files should be translated?

### PR DESCRIPTION
**Pull request by Eng-Fouad**
Closes #15933

### CODE REVIEW

**Comment by jonkoops** [comment]
@Mouhand-Kaddo could I ask you to review this for us? AFAIK we don't have any Arabic speakers on the team, but it would be good to get another set of eyes on this.

**Review by Mouhand-Kaddo — APPROVED** [review]
@jonkoops I have reviewed the branch and believe it to be ready for merging.

**Review by jonkoops — APPROVED** [review]
LGTM. But I'd like to see another pair of eyes on this.

**Comment by Eng-Fouad** [comment]
> LGTM. But I'd like to see another pair of eyes on this.

cc @zak905 @wowi42

**Comment by jonkoops** [comment]
No worries, I mean on the technical side of things :)

**Comment by zak905** [comment]
It seems to me that all translation messages have been removed from the old account console recently in this PR: https://github.com/keycloak/keycloak/pull/16905

so I am guessing everything under themes/src/main/resources-community/theme/base/admin/messages/ should be ported to the new admin console: https://github.com/keycloak/keycloak-ui

Do you confirm @jonkoops ?

**Comment by jonkoops** [comment]
@zak905 That is correct, yes. There is an issue open on our repo for that as well https://github.com/keycloak/keycloak-ui/issues/4397

**Comment by Eng-Fouad** [comment]
@jonkoops Arabic locale was added to release 21.0.0. Thanks.

BTW, the [release announcement](https://www.keycloak.org/2023/02/keycloak-2100-released.html) did not mention anything about it.

**Comment by zak905** [comment]
Great effort. I think this deserve a dedicated annoucement.

**Pull request merged**
