### PR TITLE
Use temurin instead of zulu in CI

### LINKED ISSUE #11016: CI should run on the same Java distribution we use to publish
### Description

Currently most workflows in GH Action are using zulu as distribution to run the tests.

Since we are releasing on `temurin` we should align our CI on it:
https://github.com/keycloak-rel/keycloak-rel/blob/93aa65a4a6b2d6921183f6d5b22fbf10f2175dcd/.github/workflows/nightly.yml#L21

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andreaTP**
Resolves #11016

### CODE REVIEW

**Review by abstractj — COMMENTED** [review]
@andreaTP @stianst the motivation to prefer `zulu` over `temurin` was to keep our jobs stable, consistent and use the same distribution as v1.

This is stated in the [docs](https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md):
"Use the zulu keyword if you would like to continue using the same distribution as in V1."

From my understanding, there are no major differences between those distributions. But whatever we agree as a group, that's fine from me.

**Comment by DGuhr** [comment]
I'd prefer to align CI JDK and release JDK, to make sure we test the same thing we publish. which JDK distribution doesn't matter for me personally. What's interesting though is that even the build seems to fail on temurin when I see it right here..

**Comment by abstractj** [comment]
@DGuhr GH is unstable with GH actions, probably the failures are not related with the changes proposed:

**Comment by DGuhr** [comment]
@abstractj thx for the clarification. Just to clarify: imo we should test the product we ship in the same environment (say: jdk), so wouldnt it be a "less invasive" alternative to also use zulu in the release instead of switching everything to temurin?

**Comment by andreaTP** [comment]
@DGuhr this is a bigger discussion, Zulu is a commercial solution from a third party, while Temurin is a more independent release bundle (e.g. ex Adopt).
I do believe that we should switch to a more independent platform to avoid any vendor lock in for this project.

**Comment by DGuhr** [comment]
@andreaTP I try to keep my head out of ideologic discussions around .. kind of "nuances". Some people would say the same about Red Hat. ;) but, as said before: As long as it's the same on CI/Publish, i am not hard on either.

**Comment by stianst** [comment]
Adoptium Eclipse Temurin is what we should adopt for sure, there's no question about that.

**Review by stianst — APPROVED** [review]

**Comment by hmlnarik** [comment]
Softly approving until the tests pass. For the same reasons as stated above I also prefer temurin.
That said, I stand with that original decision to go with zulu in #10972 since that change was a significant by itself and keeping the JDK distro represented a safer path.

**Review by DGuhr — APPROVED** [review]

**Review by abstractj — APPROVED** [review]
Approving based on the consensus. I don't have a strong opinion about it.

**Pull request merged**
