### PR TITLE
KEYCLOAK-2606: add support for native browsers on cordova

### PR DESCRIPTION
**Pull request by gtudan**
Adds support for OAuth on Cordova using the native Browser and Universal Links.
This relies on two cordova-plugins:

- browsertab: https://github.com/google/cordova-plugin-browsertab
- universal-links: https://github.com/nordnet/cordova-universal-links-plugin

See http://lists.jboss.org/pipermail/keycloak-dev/2018-May/010864.html for discussions about this feature.

There's an example app here: https://github.com/gtudan/ionic2-keycloak

### CODE REVIEW

**Comment by stianst** [comment]
Thanks for the PR. Will take a look at this as soon as I can, but may be a week or two

**Comment by stianst** [comment]
@mhajas can you give this a go?

**Comment by mhajas** [comment]
@stianst I will look at it.

**Comment by barrynorman** [comment]
Awesome! Looking forward to use this :)

**Comment by mhajas** [comment]
Hey @gtudan, thank you for PR I was able to run your example application, but is it correct it redirects me to example.com webpage which is publicly available webpage (The problem is I am not able to set it so that it redirects me back to cordova application)? Could you please help me to make our [example application](https://github.com/keycloak/keycloak/tree/master/examples/cordova) work with cordova-native adapter?  I tried to simply change cordova to cordova-native and added plugins which are necessary (inappbrowser, browsertab and universal-links-plugin) and I am not able to make it work, right after redirection to keycloak I am getting http://localhost not found. 

Also @stianst I won't be here whole next week (18 - 22 june), so I won't be able to finish this review until I return.

**Comment by gtudan** [comment]
I'm afraid this is a little more complicated, as this is not a drop-in-replacement for the cordova-adapter. The old adapter relies on redirects to localhost, for the native variant you'll need a real domain and associate your app with it.

I've created a branch for the example which illustrate the necessary changes: https://github.com/gtudan/keycloak/commit/0a92c3e120351ba7110185706d1a5b725aea4eec

While the "open-link-in-native-browser"-part works out of the box, the redirect to the app needs quiet a lot of setup. Please follow the instructions of the universal-links-plugin: https://github.com/nordnet/cordova-universal-links-plugin
Branch.io can help you set up a domain with the necessary links if you don't have one at hand. I noticed that it might take some time until apple or google update their indexes and the redirects work. You will need to sign the app (with android) or have a valid apple team id (personal or organizational account).

Things could be a little easier if we used custom-urls, but these are deprecated since iOS 9 and have questionable security (basically any app can register them on a device). The domain associations are rather uncomfortable, but add an extra security layer as you can be sure that your redirects don't get hijacked.

**Comment by stianst** [comment]
Looks like there are steps to test though:
https://github.com/nordnet/cordova-universal-links-plugin#testing-ul-for-android-locally

**Comment by gtudan** [comment]
@stianst Yes, I used this for testing locally as well. You can use this by triggering a login in the app and finish it by calling the app through adb with the url from the browser on your device.

**Comment by stianst** [comment]
Tried using query responseMode and same result there. For some reason the deep link only includes first parameter from hash or query. Weird.

**Comment by stianst** [comment]
Yah, here's the issue for that:
https://stackoverflow.com/questions/35645414/android-deep-linking-with-multiple-query-parameters

**Comment by gtudan** [comment]
Sorry, forgot about that. I stumbled over this as well and got around it by escaping the `\&`. With apple I had a similar problem that the universal links didn't get recognized when using response-mode fragment. Response-mode "query" worked fine.

**Comment by stianst** [comment]
I would like to see a working example of this as well as documentation before we merge.

Been trying a bit to add a working example by creating a copy of the cordova example called cordova-native in the examples directory. I've also added a GitHub pages at https://keycloak-cordova-example.github.io where we can host the required files.

I'm still trying to puzzle together how the links work and what is required to get it to automatically open in the app instead of showing the "Redirect to app" in the browsertab.

If needed we can even add whatever is needed to sign the app including the sha256_cert_fingerprints to the assetlinks.json on the github pages site.

**Comment by stianst** [comment]
So managed to make some progress. It's certainly a bit hacky at the moment though.

Added cordova-native example to this PR. That uses the stuff hosted on github. The hacky part is that it doesn't seem to pick up the redirect in the app, but rather just displays it in the browser tab. I added a javascript window.open that opens the direct link in android. You need to confirm a warning though.

It seems to be that if you're already in a browser tab it doesn't open the redirect in the app, but rather the browser tab. Perhaps the only way to get it to work properly is to support the android_app://... url in the redirect uri and use that.

**Comment by stianst** [comment]
Some more updates. I finally got this working fully on Android with login and logout. Did some tweaks to keycloak.js: use single url/event for everything as it makes setup simpler; add support to set redirectUri in initOptions so you don't have to set it in login/logout. Did a few things to the example as well to make it work well on Android. It's a bit strange that I have to use redirectUri with android_app:// scheme. Otherwise it just loads in the browser tab, but it works. What's missing now is to get it to work on iOS as well.

**Comment by gtudan** [comment]
Hey Stian, wow, looks like you poured a lot of work into this. Is there anything I can help with?

I also found getting the android deep-links to work the hardest part, but somehow managed it. The App needs to be signed for it and my best guess was that the json-file on the server needs to be there during the installation of the app. We will add a "return to app"-button that uses an app schema link on the redirect page as a fallback, as it never seems to work 100% of the time. 

iOS universal links worked smoother for me, except that they require explicit interaction with the browser to be fully automated. If I didn't click on the button of the login page but just confirmed using the keyboard, the redirect to the app did not work and an "open this in the app"-banner was shown upon scrolling down in the page instead.

**Comment by stianst** [comment]
I'm pretty happy with what we have now. Using the app schema link makes it easy to get the example to work. Can you review it and make sure you're happy with the changes I've done?

Next step would be to get some documentation together. We should add a new Cordova section to https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter. In there we should cover:

* Different link types with pros/cons
* How to get started on Android/iOS
* Links to resources like browsertab, universal-link plugin as well as links to relevant Android and iOS pages on links
* A few gotchas I guess. I found at least one on Android. The browser tab close doesn't work on Android, but if you use AndroidLaunchMode=singleTask there's only one task active in the app which results in the browser tabs being closed when it returns to the main app window.

Would you be able to work on some docs? I should probably return to the task I actually had planned. Got a bit to exited about your work ;)

By the way great work, I'm super pleased to finally have support for this added to Keycloak!

**Comment by stianst** [comment]
Just tried having two different apps open to check SSO works, and indeed it does. One last piece of the puzzle which may be a bit tricky is figure out how to do the session-iframe magic to get logout to work cross the apps as well. That would probably mean opening the session-iframe in a browser tab or something along those lines.

**Comment by gtudan** [comment]
Sure thing, I'll get started on the docs.

The session status iframe could get a little tricky - browsertab is usually ment to prevent app access to session info and the browser isn't active if the app has the focus. I'll sleep over it, maybe we can figure something out...

BTW great YouTube demo, you really seem to be excited about this 😄

**Comment by gtudan** [comment]
I took a first shot at the documentation: https://github.com/keycloak/keycloak-documentation/pull/412

**Comment by mhajas** [comment]
@stianst Thank you very much for working on this, sorry I didn't have time to finish it. Although, when I look at it, I am not sure I would be able to do work you did as I don't have so many experiences with Cordova. Do you need something else from me?

**Comment by stianst** [comment]
@mhajas np. I can take it from here. Thanks for your help so far.

**Comment by PixelJonas** [comment]
Hey we are currently trying to get this working on iOS. We are kinda confused about the steps we need to do in order to get a working example. 

To keep it simple you are using the `browsertab` plugin to get a valid session at the KeyCloak and since every app will get the same `browsertab` where the user is already logged in (with a redirect to the specific app) you "share" the login between all this apps. Is this right? And were you able to test this?

Is there any way to test the scenario locally? We looked into the `UniversalLinks` and and seems like we have to setup everything on a SSL WebServer in order to get a working example. Is there any way around that?

We'll document our testing/experience and like to contribute to any iOS specific Documentation. Right now we are struggling to get a "simple" working example - any help appreciated.

**Comment by gtudan** [comment]
Hi Jonas,

testing on iOS is a bit of a hassle, as there is no real way of doing it locally. If you want to skip the setup of a webserver you can use branch.io to do it for you (though I haven‘t tested this myself).

Stain had the idea good idea to use Github pages for hosting the config, though I am not sure if that will get the mime-type (application/json) right.

I‘m using nginx to host the files, if it helps I can share my Config.

Gregor

**Comment by PixelJonas** [comment]
So to get started I tried to use the `cordova-native` example from `gtudan:KEYCLOAK-2606` with android. I followed the instructions in the `README.md`. For me it's still not working
So I did:

- `git clone https://github.com/gtudan/keycloak.git && cd keycloak && git checkout KEYCLOAK-2606`
- `cd examples/cordova-native`
- Copied `keycloak.js` and `keycloak.json` to `www`
- added the cordova plugins from the [README.md](https://github.com/gtudan/keycloak/tree/KEYCLOAK-2606/examples/cordova-native#install-to-android-phone-or-emulator)
- `cordova run android`

for some reason he is using `http://localhost` as the redirectURI which is not working. 
I added `http://localhost` as a valid redirectURI but then I will get an `ERR_CONNECTION_REFUSED` 

I've setup a redhat-sso instance on openshift-online with the example realm.
https://secure-sso-ionic-sso.1d35.starter-us-east-1.openshiftapps.com/auth/realms/example/account

here is the corresponding `keycloak.json`:
```{
  "realm": "example",
  "auth-server-url": "https://secure-sso-ionic-sso.1d35.starter-us-east-1.openshiftapps.com/auth",
  "ssl-required": "external",
  "resource": "cordova",
  "public-client": true,
  "confidential-port": 0
}
```

as `keycloak.js` I used the one from [ionic2-keycloak](https://github.com/gtudan/ionic2-keycloak/blob/master/src/keycloak-service/keycloak.js). 

Do you guys have any idea why this is not working?

**Comment by gtudan** [comment]
Hard to tell without looking at the code. Double-check that you configured the adpater type to 'cordova-native' when calling  `init` and that you've set a redirect uri in the login method.

**Comment by stianst** [comment]
@PixelJonas  if you are using cordova-native from this PR without any changes it seems you're not using keycloak.js from this PR as well. That would explain why it's using localhost redirect uri.

**Comment by PixelJonas** [comment]
I extracted the `cordova-native` example from this PR to [a new repository](https://github.com/PixelJonas/keycloak-cordova-example). 

I double-checked the keycloak.js from this PR with the one provided in the repo (both are identical)
Just tested it again with a new project setup (following the instructions in the README.md) and a fresh Android Emulator. I'm still getting the same results.

**Comment by gtudan** [comment]
The adapter there does not have the redirect-option in the init-method - you still need to specify it in login() and logout(). Otherwise the adapter will fall back to localhost. Speaking of it, that doesn‘t make much sense. I extended the old adapter and didn‘t remove it. It would probably make more sense to reject the promise if the redirect uri is missing.

@stian: you mentioned that you added this to init but haven‘t updated the PR. Was this by intention and should I add the parameter?

- Gregor

**Comment by PixelJonas** [comment]
ah ok.

I got a first working version now. I updated the `login` Button to use the same config as the `init`.

Next I realized that in the provided [keycloak.js](https://raw.githubusercontent.com/gtudan/keycloak/KEYCLOAK-2606/adapters/oidc/js/src/main/resources/keycloak.js) we are subsribing to the `universalLinks` events `login` and `logout` - in the [config.xml](https://github.com/gtudan/keycloak/blob/KEYCLOAK-2606/examples/cordova-native/config.xml) we are only creating an event `keycloak` for the login path.

I changed the event in the `config.xml` to `login` and got a first working version.
I will invest some time tomorrow to and may improve the `README.md` with more information.

Next step would be a creating a second app and see if the **single** sign on is working. 
Afterwards I'd like to get a working iOS version going.

**Comment by gtudan** [comment]
@stianst Do you want to add your updated keycloak script (with the altered events and the redirectOption in init)? Or should I update my MR?

**Comment by PixelJonas** [comment]
Hey @gtudan,
do you have any configuration available for an iOS demo? I'm still struggling to set everything up.
As far as I understand I have to do the following steps:

- [x] add a build.json contining the Team-ID
- [x] add ios platform to project
- [x] generate apple-app-site-association
- [ ] sign file with ssl certificate
- [x] host file on server
- [x] change content-type for file to `application/pkcs7-mime`
- [x] change redirectUri for example to `https://...`

am I missing something?

The OpenShift starter won't allow me to change the host for a route so I used our company setup...
right now I'm still missing the signing stuff  - I guess this is why currently the `browsertab` is still trying to open the url in the tab. @gtudan You got a working on iOS right?

I found https://gist.github.com/anhar/6d50c023f442fb2437e1 which states the file should be signed by the certificate. Can anybody confirm this?

@stianst do you have any idea how we can setup everything for a working iOS example with the github pages?

**Comment by gtudan** [comment]
Hey Jonas,

you don‘t need to sign the file itself, hosting it on a server reachable through https will do. The plugin will generate the association file for you, all you have to do is add your teamId (NOT the certificate id). The tricky part is to make sure that site-association file is served with mime type „application/JSON“ despite not having a json file extension.

You can use this validator to check if you got everything right:

https://branch.io/resources/aasa-validator/?domain=branchster.app.link#resultsbox

I don’t know if the Keycloak Project has an an Apple developer account. Maybe we can add an iOS example on the Github pages example if we get the mimetype right.

- Gregor

**Comment by PixelJonas** [comment]
thanks @gtudan I will give it a try tomorrow. I was confused by https://limitless-sierra-4673.herokuapp.com/ which states the file itself should be signed 😕

**Comment by PixelJonas** [comment]
so I managed to host a valid file here https://redhat-sso-nginx-ionic-sso.1d35.starter-us-east-1.openshiftapps.com/.well-known/apple-app-site-association

I added our team-id and a valid bundle identifier.
I changed the `redirectUri` to `https://redhat-sso-nginx-ionic-sso.1d35.starter-us-east-1.openshiftapps.com/login` but the redirect is still opened within the browsertab for ios. I don't get a redirect to the app...

for testing purposes i added `*` as a valid redirectUrl in keycloak. If anybody wants to jump in for testing I can add more identifiers to the AASA just send me a PR for https://github.com/PixelJonas/redhat-sso-nginx

**Comment by gtudan** [comment]
Hi Jonas, 

A couple of things that could go wrong here:

* first, the website you are linking to should exist, so make sure to add at least a dummy there
* make sure your app is signed by the team specified in the association
* make sure the associated domain capability is configured and included your domain. This can be checked in xcode 
* I‘m not really sure about when these the app really checks the association - my best guess is during installation. Try to have your domain in place and then install the app.
* the universal links sometimes don‘t work on redirects without interaction. It worked for me if I clicked the login button in the form, but then failed when hitting then open button on the iOS Keyboard. In those cases the website opened in the browser and a banner appeared when scrolling down on the page. The workaround is to add a „back to the app“ button on the redirect page.

Universal Links on iOS are painful to get right - try to really follow the instructions on the plugin page to the letter.

**Comment by StephenCoady** [comment]
Hi,

I am currently working on an issue on our offering that this PR would go a long way to solving. If there is anything I can do to help test it let me know. For now I will try it out on iOS and offer any feedback I can.

**Comment by PixelJonas** [comment]
Hey @StephenCoady I'm still working on an working iOS solution. If you make any progress please share. I try to test the stuff @gtudan mentioned ^^

**Comment by PixelJonas** [comment]
So i got it working for like 5min today but broke it again (and I don't know why...) I will try again.
After some digging around in the internet I found some articles about some changes in iOS11.
AFAIK the main advantage of `cordova-native` would be a shared single-sign-on between multiple apps. KeyCloak is using Cookies to get this working which should *not* work anymore in iOS11 right?

I found this article: https://www.pingidentity.com/en/company/blog/2017/08/08/single_sign-on_and_ios_11.html

@gtudan do you know If this approach will still work on iOS11 if we want to share the login session between multiple apps? Seems to me we should use a cordova library implementing an `SFAuthenticationSession` interface

**Comment by gtudan** [comment]
Hey Jonas!

No, I wasn’t aware of this issue, as we don’t do SSO with multiple apps. My main goal when implementing this was to fix the performance issues of the InAppBrowser and get the login process working with required actions like “verify email”.

Sadly, the state of the plugin ecosystem of Cordova isn’t at its best. But maybe we can contribute such a feature to the browsertab-plugin?

**Comment by stianst** [comment]
Has anyone had this working on iOS yet? I'm unable to test on iOS as I don't have the kit available.

From my POV this is ready to be merged. Just need to review the docs first. Would be great to have a working iOS example, but I think that can be covered in a new JIRA.

**Comment by gtudan** [comment]
We have an iOS-App running with this plugin. The trouble is that it's hard to share one, as it's always tied to a payed apple developer team id and you need to sign the app to get it running. So I'm not sure on how to provide one other than by a barebone one and step-by-step-instructions.

@stianst You did some tuning to the PR that you haven't commited yet. The current version still uses two seperate events for login and logout, are you fine with that?

**Comment by stianst** [comment]
Hmm.. I see I've forgotten to commit some changes and there's also some new changes that doesn't look quite right. I will have to take another look at this.

**Comment by stianst** [comment]
I've re-introduced the single event (keycloak) which removes the need to set a redirect-uri in the logout and done a few other minor tweaks. Also, I squashed the commits into a single commit and opened a new PR here https://github.com/keycloak/keycloak/pull/5387.

I'm going to close this PR as it's replaced by https://github.com/keycloak/keycloak/pull/5387. Please review the new PR which will be merged tomorrow unless someone has comments on it.

**Comment by viktorot** [comment]
Hello all. 

First of all, I would like to thank you for all your great work.
Recently we moved away from the InAppBrowser and implemented the `cordova-native` plugin. 
It works flawlessly on Android, but we had some issues with iOS. 

Following the documentation and Apple's guide for implementing universal links, we created and uploaded an AASA file to our server, which seems to work fine.

The issues we have is with login and the `redirectUrl`. Everything works fine, unil the last step, when the redirect to the application needs to happen.
What happens is that, the redirect is always handled by the browser. We've looked into it a bit further and it seems that redirects will always be [handled](https://stackoverflow.com/a/42772094) by the browser, which means that the universal link will never be triggered and the user will never be redirected back to the application. Universal links launch the application only when they are triggered by a user action (ie. click).

Up until this point, we were not able to find any solution to this problem and we had to revert to using the InAppBrowse on iOS devices. Do you know of any possible workarounds or have any suggestion of how to get this working on iOS?

**Comment by gtudan** [comment]
Yeah, the universal links stuff - apple is making it harder with every version to get this working with redirects. The safest way to do it is having a real web page as redirect page with a „back to the app“ link on it. 
This way if the redirect fails you can recover by hitting the button. Real links work reliable.

For a proper fix: I‘m not quiet sure how to do it, as I don‘t fully understand what‘s going on in iOS. For example I noticed that if you click on the „login“ button the redirect to the app does work, but if you hit the submit button on the iOS keyboard it doesn’t. 🤔

**Comment by viktorot** [comment]
Ah Apple, the bane of my existence :)

We also thought about doing something similar, by making a different page, where the user manually triggers the universal link and is directed back in to the app. There is just one weird use-case: when the user closes the browser window by clicking "Done" instead of the universal link button. Then he returns to the app to an "undefined" state, even tho he logged in successfully.
Currently I see no good way of handling that use-case, aside for hoping that the user follows the "happy path".

I'll try implementing this and update on my progress sometime next week.

Thanks again.

**Pull request closed without merging**
