### PR TITLE
switch to using setFirstName and setLastName in TwitterIdentityProvider

### LINKED ISSUE #12912: #7539 does not fully solve KEYCLOAK-15167
### Describe the bug

[KEYCLOAK-15167](https://issues.redhat.com/browse/KEYCLOAK-15167) had as an objective to add the option to include the email in the user info to avoid having  Keycload redirect to the user profile form after redirecting from the twitter login. 

The changes introduced by #7539 fix the issue except when the twitter name has only a single word (e.g name of a company, or even a person that uses just a nickname). In this case, the `identity.setName(twitterUser.getName());` will set the first name only and Keycloak will redirect to the profile form asking the user to enter a last name. 

I think we should move away from using `setName`, which is deprecated anyway, here  https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/social/twitter/TwitterIdentityProvider.java#L221 

Since the twitter name can be also the name of a company or something else than a person, unlike Google or other idps, we can for example set the whole twitter name as a first name, and leave the last name as a blank string. 

I suggest replacing 

```
identity.setName(twitterUser.getName());
```

By 

```
                identity.setFirstName(twitterUser.getName());
                identity.setLastName("");
```

### Version

16.0.0

### Expected behavior

 Keycload should not redirect to the user profile form after redirecting from the twitter login. This is the case only if the twitter name is made of at least two words

### Actual behavior

If the twitter name is for example `keycloak`, keycloak will still redirect to the user profile update form asking the user to fill the last name, which means that the last name was not set up by the idp logic 

### How to Reproduce?

* configure twitter as idp
* try logging in with an account which has only one word as a name

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by zak905**
fixes #12912

### CODE REVIEW

**Review by mposolda — CHANGES_REQUESTED** [review]
@zak905 Thanks for the PR!

One note: How about to keep the old logic in case that `twitterUser.getName()` is something like `John Doe` ? In that case it is likely better to keep the old logic? In other words something like:
```
if (twitterUser.getName() != null && twitterUser.getName().contains(" ")) {
    identity.setName(TwtitterUser.getName());
} else {
    identity.setFirstName(twitterUser.getName());
    identity.setLastName("");
}
```

Also could you please try to run twitter related tests in the `SocialLoginTest` with your changes and doublecheck it works? Here some hint about running this test: https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/HOW-TO-RUN.md#social-login


WDYT?

**Comment by zak905** [comment]
Thanks @mposolda. It sounds good.

I think twitter requires always the usage of a username, so I think we can omit `twitterUser.getName() != null`. 

I am working on running the login test for twitter.

**Comment by mposolda** [comment]
@zak905 I am not sure about using default value like `(your twitter account has no last name)` (or something else) as default value approach has some other potential issues....

Maybe some possibilities how to address your use-case:
- Make the alternative version of `First Broker Login` flow and remove the `Review Profile` authenticator from it and set this as the first login flow to the Twitter IDP. See the docs for more details. Alternative is to switch the default `First Broker Login` flow and change the configuration of `Review Profile` authenticator to `OFF` (this will affect also other brokers in case you have them). In this case, the update profile screen will never be displayed. But maybe it is what you want for your use-case?

- Remove the `Blank Attribute` validator from the Last name for the user profile. I don't have much experiences with user profile and not 100% sure if this is possible and how exactly should it be done.

**Comment by zak905** [comment]
@mposolda apologies for the late response. 

Thanks for the suggestions. Actually, I tried both alternatives and they both seem to work around the issue. For the user profile, I just disabled the last name as required attribute and it worked. I think I am going to stick to a custom flow with the review profile step disabled, because user profile is preview feature after all. 

In this case, we can close this PR? instead we can add some section in docs about this maybe?

**Comment by mposolda** [comment]
@zak905 Ok, I am closing the PR then.

Regarding the First Login Flow, it is already documented quite extensively IMO: https://www.keycloak.org/docs/latest/server_admin/index.html#_identity_broker_first_login . But there is nothing in the twitter section about this potential issue. If you have some idea how to improve the docs, feel free to create separate issue in the keycloak/keycloak-documentation repository (possibly with the reference to the discussion in this PR) and send the PR to the keycloak-documentation with some short note about this. Contributions are always welcome! Thanks

**Pull request closed without merging**
