### PR TITLE
Pin Ansible version for Aurora Store IT tests to 9.x.y stream

### LINKED ISSUE #30201: Keycloak CI - failure in Store IT (aurora-postgres)
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

```
TASK [Gathering Facts] *********************************************************
fatal: [3.90.144.164]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"ansible.legacy.setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "failed": true, "module_stderr": "Shared connection to 3.90.144.164 closed.\r\n", "module_stdout": "/bin/sh: /usr/bin/python3: No such file or directory\r\n", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127, "warnings": ["No python interpreters found for host 3.90.144.164 (tried ['python3.12', 'python3.11', 'python3.10', 'python3.9', 'python3.8', 'python3.7', '/usr/bin/python3', 'python3'])"]}}, "msg": "The following modules failed to execute: ansible.legacy.setup\n"}
```

https://github.com/keycloak/keycloak/actions/runs/9392974293/job/25868350613

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ryanemerson**
Closes #30201

Successful run on my fork: https://github.com/ryanemerson/keycloak/actions/runs/9399087517/job/25886139601

### CODE REVIEW

**Comment by ahus1** [comment]
@ryanemerson - thank you for this PR. 

Looking at the fix, I searched `keycloak-benchmark` and found a similar comment `pip3 install --user boto3 botocore` there, but which doesn't contain the `ansible` part. As it still worked in the last nightly run, I wonder if it would also be sufficient to remove the `ansible` part here instead of adding the pinned version, or if we should adapt the command in `keycloak-benchmark` to look the same like this one.

**Comment by ryanemerson** [comment]
@ahus1 In the `keycloak-benchmark` repo we state that a prerequisite for running the benchmark is to "Install Ansible CLI (on Fedora, use dnf install ansible)". As we never execute `aws_ec2.sh` in the keycloak-benchmark actions, ansible is not included in the `pip install` command. Whereas here we execute using actions, so we need to install all dependencies.

**Comment by ahus1** [comment]
> As we never execute `aws_ec2.sh` in the keycloak-benchmark actions, ansible is not included in the `pip install` command.

Not so sure about that - IMHO we use it to run the benchmarks. See https://github.com/keycloak/keycloak-benchmark/blob/406553252e6c5eee7ae0d2d2869e1838d101adfd/.github/actions/ec2-create-instances/action.yml#L16 

Do you want to reconsider, or should I merge?

**Comment by ryanemerson** [comment]
Argh sorry, I was very wrong indeed! I completely forgot about the benchmark execution :upside_down_face: 

Looking at keycloak-benchmark some more, it seems we use `ansible-core` that's actually included with the Ubuntu distribution which is version 2.12.0-1 https://packages.ubuntu.com/jammy/ansible-core, whereas we have an issue with 2.17.x. So we don't need to change anything there.

I *think* the Keycloak repository should work using the same method as ^, so maybe I should change this PR so we use the same approach as `keycloak-benchmark`?

**Comment by ahus1** [comment]
> I think the Keycloak repository should work using the same method as ^, so maybe I should change this PR so we use the same approach as keycloak-benchmark?

I'd think so, too. Please give it a try. 

Looking at the commands, I see that we call `ansible-galaxy` before calling `pip3` in both places, so IMHO we assume Ansible is pre-installed each time.

**Comment by ryanemerson** [comment]
Aurora CI job passing on my fork with the latest changes: https://github.com/ryanemerson/keycloak/actions/runs/9403943881/job/25901942052

**Review by ahus1 — APPROVED** [review]
Thank you for this PR - we are now better aligned with the KCB project than ever!

**Pull request merged**
