### PR TITLE
KEYCLOAK-7804: Option to return resource body

### PR DESCRIPTION
**Pull request by cdupont**
When querying /resource_set API endpoint: If the query parameter "deep" is set to True, the body of the resources will be returned (instead of just resource ids).

### CODE REVIEW

**Comment by pedroigor** [comment]
@cdupont, thanks. We are about to release next version, so your changes would need to wait.

Changes look good to me, however, we also need tests for this new parameter. I simple test here `org.keycloak.testsuite.admin.client.authorization.ResourceManagementWithAuthzClientTest` should be enough. That test is using the Java AuthZ Client API to access the Protection API.

**Comment by cdupont** [comment]
It the file you mentioned there is one test called "testFindMatchingUri", however at the level of the Java API the body of the resource is already returned. How to test the REST API instead?
Actually I don't see any test for the REST API?

**Comment by pedroigor** [comment]
A call to `org.keycloak.authorization.client.resource.ProtectedResource#find` will reach the Protection API. If you look at the body of this method `deep` is already being passed but always `false`, so it is always expecting ids as response. If you could add a new `find` method returning instances of the representation with a fixed `deep == true` it should be fine.

We don't have specific tests for this method because it is kind of called by other methods such as `findByName`. But yeah, we need more tests to make sure we are covering everything.

**Comment by pedroigor** [comment]
@cdupont, could you please rebase your branch and have squash your two commits ?

**Comment by cdupont** [comment]
Closing this PR in order to re-open it with cleaned commits.

**Pull request closed without merging**
