### PR TITLE
authz/client: Fix getPermissions returning wrong type (#16520)

### LINKED ISSUE #16520: AuthzClient getPermissions() deserializes to List<LinkedHashSet> and not List<Permission>
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authorization-services

### Describe the bug

Using the Java AuthzClient the `List<Permission> permissions = authorizationResource.getPermissions(authorizationRequest);` returns a list of `LinkedHashSet` and not a `List<Permission>`

This is because the type is not available at runtime and default deserialization of jackson is LinkedHashSet. Following line does not work for:

https://github.com/keycloak/keycloak/blob/5ddb79cbe6ae4bd591df81428139aa468d23ad24/authz/client/src/main/java/org/keycloak/authorization/client/resource/AuthorizationResource.java#L122

### Version

20.0.3

### Expected behavior

Expected is the List<Permission> deserializes to a list of Permission objects.

### Actual behavior

List<Permission> contains a list of LinkedHashSet.

### How to Reproduce?

```
            AuthorizationResource authorizationResource = authClient.authorization(token);

            AuthorizationRequest authorizationRequest = new AuthorizationRequest();
            authorizationRequest.setAudience(audience);
            authorizationRequest.setScope("read");
            AuthorizationRequest.Metadata metadata = new AuthorizationRequest.Metadata();
            metadata.setResponseMode("permissions");
            authorizationRequest.setMetadata(metadata);

            List<Permission> permissions = authorizationResource.getPermissions(authorizationRequest);
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by clezag**
Fixed an issue with getPermissions() ALWAYS returning the wrong Type `List<LinkedHashMap>` instead of `List<Permission>` at runtime, differing from the compile time type.

Due to the nature of this problem, this fix will probably break most code that used this method before and not give any compiler errors. 

Closes #16520

### CODE REVIEW

**Comment by sguilhen** [comment]
@pedroigor changes here make sense to me. Would you be able to take a look?

**Review by pedroigor — COMMENTED** [review]
@clezag Can you please add a note to https://github.com/keycloak/keycloak/blob/main/docs/documentation/release_notes/topics/25_0_0.adoc?

**Comment by clezag** [comment]
@pedroigor I've added a section to the release notes. Happy to get feedback on it.

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
Thanks @clezag!

**Pull request merged**
