### PR TITLE
KEYCLOAK-4593 Flush and clear when fetching multiple realms

### PR DESCRIPTION
**Pull request by wvdhaute**
Fixes a performance hit with a large number of realms (200+) when called from various points.

For example when called during startup when timers are started for syncing users if this is configured for a realm ( i.e when fetching all realms which have a custom UserStorageProvider )

### CODE REVIEW

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Thank you for the contribution. Unfortunately this patch cannot be accepted since while it solves one performance issue, it causes performance degradation at numerous other places by clearing the EM cache.

This particular use case has no straightforward solution and would span big part of the code base, and would involve lazy loading of the realms, changing the `List` to `Stream`, and other optimizations.

**Comment by wvdhaute** [comment]
@hmlnarik Can you point us where you see other performance degradation introduced by our patch? Case we encounter this later on?

Also does the infinispan realm cache not shield us from any performance dip once all realms are loaded into the cache?

**Comment by hmlnarik** [comment]
@wvdhaute Feel free to find recursively find the usages of this method. All those places should be inspected one by one. Those of concern are mostly scheduled tasks and realm admin endpoints.

Anyway, the way to fix this is really via lazy loading of the Realm fields (cf. https://github.com/mposolda/keycloak/commit/b4b3527df7656bfaaee351ec414e56c683c134c2#diff-99e590ff1a5d4b89767173cfa4708f88R83) and using `LazyLoader` class in the respective infinispan entity (cf. https://github.com/mposolda/keycloak/commit/b4b3527df7656bfaaee351ec414e56c683c134c2#diff-6d9f9dc6967eecafcf91ed3cdd30f707R66), and replacing Lists with Streams.

**Comment by hmlnarik** [comment]
@wvdhaute Do you expect to have time to work on this issue anytime soon?

**Comment by wvdhaute** [comment]
Hey @hmlnarik ,

Don't expect I will find time to do this refactoring I'm afraid.
For our case, we see no harm in using our approach right now after some testing.

**Comment by hmlnarik** [comment]
Still, thanks @wvdhaute for your time and the contribution, as well as the testing. Could you please share the scenarios you've tested, and any results?

**Comment by wvdhaute** [comment]
We tested a scenario with 600+ realms which all have a custom user storage provider.
This triggered the unable to start Keycloak within a reasonable time because of the first level cache growing too big and becoming a performance bottleneck.

We increased the jboss.as.management.blocking.timeout and txn timeout but after inspecting it wasn't even close ( <200 done within 10' ) so not acceptable

With this fix and the explicit flush/clear where all realms are looped over this was now < 1minute.

Once loaded, our realms stay fairly static. We tested with a serialized update all realms by adding a new client and client role but saw no issues there.
We tested with explicitly clearing the realm cache for each realm but again no performance issues here.

There is also a period monitoring task that fires every 5s and goes over each realm whilst doing above operations but also had no trouble here

**Comment by hmlnarik** [comment]
Thanks @wvdhaute, that is impressive. I'll check the details of the other scenarios to see the impact.

**Comment by damianofontana85** [comment]
Hi @hmlnarik we are worried about keycloak performance with 200+ realms. Do you check if this fix could have impact in other scenarios?

**Review by hmlnarik — APPROVED** [review]
@wvdhaute, Thank you for your contribution. It helps in many cases.
Generally speaking, the code in the current JPA layer should have been restricted from calls to `flush` in the first place, but now another `flush` does not bring much of additional harm. Hopefully less hacky store provider would be provided in (a variant of) KEYCLOAK-9354.

**Comment by hmlnarik** [comment]
Caused #6847

**Pull request merged**
