### PR TITLE
Remove Legacy migration tests from testsuite

### LINKED ISSUE #14300: Remove Legacy migration tests from testsuite
### Description

Remove Legacy migration tests from the testsuite, which uses WildFly.

### PR DESCRIPTION
**Pull request by mabartos**
Closes #14300

Pipeline MR: https://keycloak-gitlab.com/keycloak/keycloak-pipeline/-/merge_requests/182

I'll execute the pipeline for DB migration tests.

@wojnarfilip @leonardobrancalhao @miquelsi Could you please check it? Thanks

### CODE REVIEW

**Comment by mabartos** [comment]
Execution of pipeline tests completed as expected and I can confirm, that the new DB migration is not affected.
Pipeline run: https://keycloak-jenkins.redhat.com/job/universal-test-pipeline-server/2172/

**Review by wojnarfilip — DISMISSED** [review]
@mabartos Thanks !

**Review by leonardobrancalhao — DISMISSED** [review]
LGTM

**Comment by mabartos** [comment]
@leonardobrancalhao @wojnarfilip Just rebased. No changes made

**Review by wojnarfilip — APPROVED** [review]

**Review by leonardobrancalhao — APPROVED** [review]

**Review by pdrozd — APPROVED** [review]

**Pull request merged**
