### PR TITLE
Reviewing references to user attribute management and UIs

### LINKED ISSUE #26155: Review documentation for references on user management

### PR DESCRIPTION
**Pull request by pedroigor**
* Rename section `Defining user profile` to `Managing user attributes` and move it to the top of the `Managing users` top-level section
* Replace some of the screenshots to match the new UI for user details UI

Closes #26155

### CODE REVIEW

**Review by mposolda — DISMISSED** [review]

**Comment by andymunro** [comment]
@pedroigor This looks good, but eventually it will become part of RHBK documentation, so the Keycloak banner would need to be replaced.  So we have been capturing all screens excluding the section at the banner.  Is it possible recapture them?

**Comment by andymunro** [comment]
@pedroigor Actually, it is only effective-role-mappings.png that needs to be updated to remove the Keycloak banner if possible, so we can reuse for RHBK

**Comment by pedroigor** [comment]
@andymunro Thanks. The images are not referencing upstream anymore. Please, let me know if it works for you.

**Review by andymunro — APPROVED** [review]
Okay, thanks for the update @pedroigor.  Looks good.

**Review by mposolda — APPROVED** [review]
@pedroigor @andymunro Thanks!

**Pull request merged**
