### PR TITLE
fixes port not recognized when setting hostname and port without proxy

### LINKED ISSUE #10627: Keycloak admin UI drops https port if --hostname is used
### Describe the bug

If I do
```
docker run --name keycloak -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -p 8543:8443 -v "$(pwd)"/target/classes/server-keystore.jks:/etc/server-keystore.jks quay.io/keycloak/keycloak:17.0.0 start  --hostname=localhost --https-key-store-file=/etc/server-keystore.jks
```
and then go to `https://localhost:8543` to the Admin UI which is displayed correctly and then click on an option to administer Keycloak, it fails with `404` the link has something like `https://localhost/somepath`, without `:8543`.

Replacing `--hostname=localhost` with `--hostname-strict=false` fixes it.

Perhaps it is a misconfiguration issue

### Version

17.0.0

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DGuhr**
more info see https://github.com/keycloak/keycloak/issues/10627#issuecomment-1064942048

Closes #10627

Closes #10331

### CODE REVIEW

**Comment by DGuhr** [comment]
Link to video with fixed behaviour: https://youtu.be/M7YcWZPII4s 

Before, when clicking on "Administration Console" this resulted in an error as the port was not added to the url bc we always assumed running behind a proxy and thus using standard ports.

**Review by pedroigor — DISMISSED** [review]

**Comment by abstractj** [comment]
@DGuhr would make sense to add a test to prevent any regressions in the future?

**Comment by DGuhr** [comment]
@abstractj working on it. :) seems the existing `DefaultHostnameTest` always uses nip.io domain with standard ports, so this wasn't catched. Just wanted to see first if other regressions happen - and they do, as the operator tests are now failing.

**Comment by DGuhr** [comment]
just ftr: please do not merge yet (still searching a button to put this back to draft state). had some trouble writing the tests in the old arquillian testsuite bc port was not appended in the discovery endpoint. Best guess is some dark magic changed the authserver to start with proxymode again though it should not. 

If it's ok i'll provide tests in the new testsuite, as this is quarkus specific and far easier to do with RestAssured. Got some already working (and showing the behaviour when calling the discovery endpoint is actually as we want it).

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
