### PR TITLE
KEYCLOAK-6773 XML vulnerability test

### PR DESCRIPTION
**Pull request by hmlnarik**

### CODE REVIEW

**Comment by hmlnarik** [comment]
Failure in AccountPageTest is unrelated.

**Review by pedroigor — CHANGES_REQUESTED** [review]
In addition to signature, we also need to test if we are parsing contents without ignoring comments or CDATA elements.

**Comment by hmlnarik** [comment]
@pedroigor "... if we are parsing contents without ignoring comments": No, we are not. We ignore comments globally and only allow Characters, StartElement, and EndElement events. See https://github.com/keycloak/keycloak/blob/3.4.3.Final/saml-core/src/main/java/org/keycloak/saml/common/parsers/AbstractParser.java#L136-L146

**Comment by hmlnarik** [comment]
The failure is caused by KEYCLOAK-6777, PR with fix is here: #5047

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
