### PR TITLE
Upgrade to Quarkus 3.8.4

### LINKED ISSUE #28880: Upgrade to Quarkus 3.8.4
### Description

https://github.com/quarkusio/quarkus/releases/tag/3.8.4

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes #28880

### CODE REVIEW

**Review by mabartos — DISMISSED** [review]

**Comment by vmuzikar** [comment]
@mabartos Had to make some changes, can you please review again?

**Comment by mabartos** [comment]
@vmuzikar I believe the work around these `Optional`s is related to the same problem as @Pepo48 fixes for the Quarkus next. Is it correct?

https://github.com/keycloak/keycloak/issues/28856

**Comment by mabartos** [comment]
@vmuzikar Oops, created conflicts after merging the related one. Can you resolve them?

**Comment by vmuzikar** [comment]
@mabartos Good point, didn't notice that. I reverted the changes around optionals, they are no longer needed.

**Review by Pepo48 — APPROVED** [review]
LGTM.

**Review by ahus1 — APPROVED** [review]
Approving based on @Pepo48's review. Not merging yet as I leave the decision when to merge it the CND team members

**Review by mabartos — APPROVED** [review]

**Pull request merged**
