### PR TITLE
KEYCLOAK-11201: Use snowpack instead of SystemJs.

### PR DESCRIPTION
**Pull request by ssilvert**

### CODE REVIEW

**Comment by stianst** [comment]
Please open a discussion around Snowpack on the dev mailing list. This really should have been done a long time ago. In general I have no input/rejections to Snowpack, but for bigger decisions like these we should include the wider community.

**Comment by edewit** [comment]
@stianst IMO this is more of an internal change. It affects the way the code is build and loaded by the browser and it doesn't effect the user.

**Comment by ssilvert** [comment]
@edewit 

@stianst is right.  This is the kind of thing we discuss on the dev list.  I'm planning to start a discussion later today, but maybe someone in the community would have had some good feedback when we were discussing it privately a few weeks ago.

**Comment by edewit** [comment]
If it's common knowledge to discuss these things before we implement them why have do we have a PR already. On top of that system.js isn't really something we can keep as we can't update to newer versions of patternfly with it. And other options like webpack or rollup will disable the 'easy to update without build step' functionality we would like to keep. So that only leaves snowpack.

**Comment by ssilvert** [comment]
Yeah, I don't think things would have turned out any differently.  Our process is to discuss major changes on the dev list.  But given that this is still tech preview it never occurred to me until Stian mentioned it earlier this week.  So I decided to use the dev list to open up the code review to a wider audience.

**Comment by ssilvert** [comment]
And before I post to the dev list, I'm going to open a new PR.  The PR for this doesn't need a meta-discussion about how we have discussions. :-)

**Pull request closed without merging**
