### PR TITLE
KEYCLOAK-5088 - More feedback on refresh token result in RefreshableK…

### PR DESCRIPTION
**Pull request by wvdhaute**
…eycloakSecurityContext

### CODE REVIEW

**Comment by mposolda** [comment]
@wvdhaute Few things:
- We need a test before PR is accepted . There are adapter tests in testsuite/integration-arquillian package "org.keycloak.testsuite.adapter"
- It looks the change is in conflict with your other PR https://github.com/keycloak/keycloak/pull/4235 ?

By the way: why you sent PR with those changes? Are you develop something like your own adapter and you're using RefreshableKeycloakSecurityContext class in your own code?

**Comment by wvdhaute** [comment]
@mposolda Ok will add a test for this PR and maybe add the changes of PR #4235 in this one? Or rather not?

Not really our own adapter, I just need more feedback on a refresh token attempt for a Swing client

**Comment by mposolda** [comment]
@wvdhaute Ah, thanks. Maybe if you fix https://github.com/keycloak/keycloak/pull/4235 first including test and then rebase this PR on top of that once 4235 is merged? WDYT?

**Comment by mposolda** [comment]
@wvdhaute Left some comment in your other PR https://github.com/keycloak/keycloak/pull/4235

**Comment by starJammer** [comment]
FYI, I've been looking at other PRs in this repo and I noticed someone mentioned that `RefreshableKeycloakSecurityContext` should not be used in application code. 

We have a SpringBoot API and in it we have a Filter to pull out information from the token.

```
@Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {

        if (!(request instanceof HttpServletRequest)) {
            throw new RuntimeException("Expecting a HTTP request");
        }

        RefreshableKeycloakSecurityContext context = (RefreshableKeycloakSecurityContext) request.getAttribute(KeycloakSecurityContext.class.getName());

        if (context == null) {
            handleNoSecurityContext(request, response, chain);
            return;
        }

        AccessToken accessToken = context.getToken();
        securityService.setAccessToken(accessToken);
        securityService.setAccessTokenString(context.getTokenString());
        securityService.setMemberIdentity(new MemberIdentity(accessToken.getOtherClaims()));
        securityService.setIssuedFor(accessToken.getIssuedFor());

        chain.doFilter(request, response);
    }
```

Is there another way to get this context from the token without using the `RefreshableKeycloakSecurityContext`? The API pulls in context info from the token.

**Comment by mposolda** [comment]
@starJammer I think it's fine to use the code in a way, which you did. You use our adapters and the token is set by the adapter, you use it just to pull the info from it. However in your case, it's better to rather use superclass KeycloakSecurityContext, which is more intended to be used in the application code:

KeycloakSecurityContext context = (RefreshableKeycloakSecurityContext) request.getAttribute(KeycloakSecurityContext.class.getName());

BTV. It's likely better to send questions to keycloak-user mailing list instead of there :)

**Comment by stianst** [comment]
@mposolda @wvdhaute what's the status on this?

**Comment by mposolda** [comment]
Closing this PR for now due the:

- It's not complete and there is some work pending for a long time. Especially there is slight risk that the change will break some adapter impls.
- It adds some improvements to RefreshableKeycloakSecurityContext class, but this class was originally meant to be used internally by our adapters, not as an util class for handling adapter flows manually from the client applications. 

Feel free to reopen if you really think that this require fixing and if you have complete PR and all the adapter tests passing (including EAP6, AS7, Wildfly, EAP7, Spring, all Tomcat and all Jetty versions). However if you really want the customizations, it's maybe better and easier to rather create your own class (or subclass of RefreshableKeycloakSecurityContext) and do it by yourself in your own way.

**Pull request closed without merging**
