### PR TITLE
KEYCLOAK-19014 Check if refresh token is expired before using it

### PR DESCRIPTION
**Pull request by tobilarscheid**
As described in [KEYCLOAK-19014](https://issues.redhat.com/browse/KEYCLOAK-19014) we are currently ignoring the refresh tokens validity in the Keycloak Java Client. This PR changes this behaviour and grants a new token should the refresh token be expired.

### CODE REVIEW

**Comment by tobilarscheid** [comment]
@hmlnarik can you flag this for build?

**Comment by tobilarscheid** [comment]
Hey @pedroigor, could certainly do this, but then you would always grant a new token on each invocation - pretty wasteful.

**Review by pedroigor — APPROVED** [review]
@tobilarscheid I meant, your code calling `grantToken` when the RT is expired. But we can do better. LGTM.

**Comment by tobilarscheid** [comment]
> I meant, your code calling grantToken when the RT is expired.
Yes, can be used as a workaround. But now we have the proper solution :-)

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@tobilarscheid Thanks.

**Pull request merged**
