### PR TITLE
KEYCLOAK-14306 OIDC redirect_uri allows dangerous schemes resulting in potential XSS

### PR DESCRIPTION
**Pull request by vmuzikar**
(cherry picked from commit e86bec81744707f270230b5da40e02a7aba17830)

Conflicts:
    testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientRegistrationTest.java
    testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ClientTest.java
    services/src/main/java/org/keycloak/validation/DefaultClientValidationProvider.java

All of them are related to https://github.com/keycloak/keycloak/pull/7272.

### CODE REVIEW

**Comment by vmuzikar** [comment]
Since Travis doesn't work, I'm waiting for test results in the test pipeline.

**Comment by vmuzikar** [comment]
Successful base testsuite run: https://keycloak-jenkins.com/job/universal-test-pipeline-server/2293/

**Comment by stianst** [comment]
There's some failures in "Keycloak CI" job: https://github.com/keycloak/keycloak/pull/7586/checks?check_run_id=1359650110

**Comment by vmuzikar** [comment]
> There's some failures in "Keycloak CI" job: https://github.com/keycloak/keycloak/pull/7586/checks?check_run_id=1359650110

@stianst That's weird... It's some Quarkus check, isn't it? I mean, why else would it fail when the test pipeline passed?

**Comment by vmuzikar** [comment]
I think the test failures are unrelated to this as it apparently affects other PRs too (e.g. #7546).

**Comment by pedroigor** [comment]
Now we have a real overlap with https://github.com/keycloak/keycloak/pull/7324.

So far, it was only about client validation. We need to figure out how to align the different proposals we have on the table.

**Comment by vmuzikar** [comment]
@pedroigor So what is your proposal how to handle this in the best way? :)
IMHO however we decide, I think we should merge this, and if needed, refactor later. This PR is just a forwardport of something that was already merged in the downstream – so, for the consistency sake, we should have this in the upstream too. At least for now before we replace it with something else.

**Review by pedroigor — DISMISSED** [review]

**Comment by pedroigor** [comment]
@vmuzikar I have no clue :) But work later to finally have a single validation approach.

**Comment by vmuzikar** [comment]
I rebased this onto current master but there are still test failures. I was unable to reproduce it locally (all pass for me), so I'm not sure what's happening here. Doesn't GH Actions use some cache or something?

**Comment by stianst** [comment]
This is a blocker to get merged into master for Keycloak 12, as it is fixing a CVE that is already public and resolved in 11.0.3. So any refactoring is out of scope, and this should get merged assuming it is okay, and passes CI.

For sure later we do need to refactor/align on a more consistent approach to validation throughout.

**Comment by pedroigor** [comment]
@stianst @vmuzikar I know GA is not as stable yet from my experiences with Quarkus tests. I guess you can successfully run the failing ones locally without any problem.

I'm OK to merge this one but I don't have the rights to do it due to those failures.

**Review by mposolda — APPROVED** [review]

**Pull request merged**
