### PR TITLE
Shorter lifespan for offline session cache entries in memory

### LINKED ISSUE #26810: Shorter lifespan for offline session cache entries in memory
### Description

see https://github.com/keycloak/keycloak/discussions/24274

### Discussion

https://github.com/keycloak/keycloak/discussions/24274

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by martin-kanis**
Closes https://github.com/keycloak/keycloak/issues/26810

This is a new PR instead of https://github.com/keycloak/keycloak/pull/24302 where I added a model test and rebased the code. I also added documentation.

### CODE REVIEW

**Comment by pedroigor** [comment]
@martin-kanis Is it basically about providing a server-wide setting to avoid setting the lifespan on per realm-basis?

**Comment by sschu** [comment]
@pedroigor I would assume this is to have some way to evict data from the cache, especially for offline sessions that have no max session length. Since we have lazy loading now, it is definitely an improvement.
@martin-kanis I am wondering why we do not offer to limit the size of caches instead of adding an expiration? This would give much more predictability when it comes to Keycloak's memory consumption (I understand this is the main goal of this issue, to reduce memory consumption).

**Comment by pedroigor** [comment]
> @pedroigor I would assume this is to have some way to evict data from the cache, especially for offline sessions that have no max session length. Since we have lazy loading now, it is definitely an improvement.

Yeah, but does it make sense to include yet another server-level setting instead of just setting a lifespan to offline sessions in your realm? The ultimate goal is the same, no?

Also, as you mentioned, why not just set a limit to the corresponding caches in the cache configuration?

**Comment by sschu** [comment]
@pedroigor There is a difference from the offline session settings int he realm: offline sessions that are evicted from the cache might still be valid and will be lazy-loaded from the database into the cache.

**Comment by martin-kanis** [comment]
@sschu We picked the lifespan override as safer variant that will still safe some memory but removes a risk that you set fixed size for a cache, then you have many parallel offline token refreshes and a session got evicted from the cache in the middle of a request, just after it got imported from the DB. Infinispan uses tiny LFU algorithm (modification of least frequently used) for eviction and we are not fully sure how it would behave.

We still might add and evaluate the cache size approach for future. We hope users will start experimenting with this lifespan override option and provide a feedback how it works or doesn't work for them.

**Comment by sschu** [comment]
@martin-kanis OK, I think I get the point. It is probably the safer approach. But I would say the problem you described isn't very likely to happen as long as you have reasonable cache sizes > 10.000? You need to have really high load to have problems with parallel requests evicting each others' entries. Couldn't we also just document that we recommend a certain minimum size depending on the expected load?

**Comment by thomasdarimont** [comment]
I'm really happy that this lands in main :) 

As far as I understand the implementation the new lifespan overrides for in memory items only affect cache items that are created (loaded-into memory) by Keycloak instances with that setting. So perhaps it would make sense to add a small note that a cluster restart might be needed to apply the new timestamps to all cache entries.

**Comment by sschu** [comment]
@thomasdarimont This is a KC24 feature. When you roll out KC24, won't you restart all nodes anyways?

**Comment by thomasdarimont** [comment]
@sschu it depends on whether an external infinispan is used and whether cached sessions from (<KC24) are compatible with KC24. Some folks might cycle their Keycloak cluster but perhaps not the infinispan cluster.

**Comment by sschu** [comment]
You are right. I didn't check the implementation. I thought the expiration was added on a cache level on the embedded cache, but it looks like it is added when adding individual session entries...

**Comment by thomasdarimont** [comment]
Would it be possible to backport this to 23.0.x / 22.0.x?

**Comment by ahus1** [comment]
> You need to have really high load to have problems with parallel requests evicting each others' entries. Couldn't we also just document that we recommend a certain minimum size depending on the expected load?

@sschu - Infinispan uses "least frequently used" to expire entries, which I find hard to reason about in this scenario. Therefore, we'll stick with the expiry option.

**Comment by ahus1** [comment]
> Would it be possible to backport this to 23.0.x / 22.0.x?

We're considering a backport. We had backporting in mind when we planned for this to keep the changes as minimal as possible.

**Comment by sschu** [comment]
> > You need to have really high load to have problems with parallel requests evicting each others' entries. Couldn't we also just document that we recommend a certain minimum size depending on the expected load?
> 
> @sschu - Infinispan uses "least frequently used" to expire entries, which I find hard to reason about in this scenario. Therefore, we'll stick with the expiry option.

Oh, OK. I quite naturally assumed this to be least-recently-used.

**Comment by ahus1** [comment]
Another note on people using remote caches: There is `RemoteCacheSessionsLoader` which will load for all distributed caches the entries from the remote cache into the local cache. When doing this, it will not honor the lifespan set in the remote cache, and it will (as I understand it) use the default lifespan configured in the Infinispan configuration. 

Therefore, for those who are using this in an environment with a remote store, I recommend to set the lifespan for all distributed caches in their Infinispan XML file to a value that matches their environment. I'll open a follow-up issue for this to document this in the HA guide. We'll still need to analyze where that loading is really necessary (we know it is necessary for online user sessions).

**Review by ahus1 — APPROVED** [review]
Thank you for this change, @thomasdarimont, and @martin-kanis for documenting and testing it!

**Pull request merged**
