### PR TITLE
Deleting a User or User Group might cause that all users suddenly get the permissions of the deleted user.

### LINKED ISSUE #24651: Deleting a User or User Group might cause that all users suddenly get the permissions of the deleted user.
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

When a user is removed from keycloak, also a "User policy" selecting only this user is also removed.

If you have defined a permission which selects this policy and other policies with Decision strategy Unanimous. The user policy is bluntly removed, suddenly giving this permission to all users in the system.

### Version

22

### Expected behavior

User and User group policy is not removed, but after removal of the User or User group the policy always evaluates to false.

### Actual behavior

User policy is deleted from the database when the user is deleted. In permissions using this policy, this policy is removed.

### How to Reproduce?

Create a user "user1"
Create a client with Authorization enabled.
Create in this client a resource "resource1"
Create a user policy "user is user1", add only user1 to the list of users in this policy
Create some other policy, for instance time based "dayshift". Repeat. Hour min 8 max 17.
Create a permission "user1 has access to resource1 during the dayshift"
Add resource1 to the list of resources. Add policies "user is user1" and "dayshift" to the permission
Set decision strategy to Unanimous

Delete user1
Policy "user is user1" is deleted.
The permission only contains 1 policy anymore being "dayshift"
As a result, suddenly all other users are granted access to resource1 during the dayshift.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by douglaspalmer**
Closes #24651
Signed-off-by: Douglas Palmer <dpalmer@redhat.com>

### CODE REVIEW

**Review by pedroigor — DISMISSED** [review]

**Review by ghost — COMMENTED** [review]
Unreported flaky test detected, please review

**Review by pedroigor — DISMISSED** [review]

**Comment by pedroigor** [comment]
@ahus1 Looks like we need a review from store team, would you mind doing it?

**Review by ahus1 — CHANGES_REQUESTED** [review]
@pedroigor / @douglaspalmer - I see a lot of newly unstable tests reported in this PR. Could you please have a look? It would at least be good to improve the logging of some of these, as `Unrecognized field "error"` doesn't reveals too much information. Possibly the response code should be tested first before parsing the response. If the response code is unexpected, it would be helpful to see the error message. 

I suspect (but might be wrong) that some of the test data was touched here, and rerunning a test might clean up the test data so a second run then completes. So I suggest to check if some data would need to be cleaned in some of the tests.

This PR changes the public API of the admin client in `PoliciesResource` (`roles` -> `role`, `users` -> `user`). While I support this change, this is a breaking change for users. I don't know if you could keep the old methods with a deprecated annotation, or (if that is not possible) write a paragraph to the migration guide.

**Comment by pedroigor** [comment]
@ahus1 Sorry, would you mind elaborating more about the API changes you are referring to?

As for the tests, we can check if they are somewhat unstable because of the changes being introduced here.

**Comment by ahus1** [comment]
@pedroigor - sorry about the confusion about the API, I took a wrong turn when reviewing, please disregard. 

Thank you for looking into the unstable tests.

**Comment by ahus1** [comment]
@douglaspalmer - I gave it a try locally, and this is what I found: 

* When running all tests in `org.keycloak.testsuite.admin.UsersTest` on the CLI locally with no retry, the tests marked above as flaky always fail. I assume this is due to the modifications of the realm in the test class. Once I override `isImportAfterEachMethod` and make it return true, it will re-create the realm for every test method, and then all tests succeed. This is slower, fixed that `setupTestEnvironmentWithPermissions` doesn't have a cleanup. Maybe you come up with a better idea. 

* Similar reasons for `UserPolicyManagementTest` and `ClientPolicyManagementTest`, but it can be fixed by removing the entities created in the tests

Looking at these changes, IMHO those tests now fail as the permissions are no longer removed once the users are removed.

I've created a PR https://github.com/douglaspalmer/keycloak/pull/620 that adds my local changes to this PR. Please have a look and let me know what you think of it.

**Comment by ahus1** [comment]
@douglaspalmer - the reported test `SessionTimeoutsTest` is a valid flaky test and it is unrelated to your code. 

Do you want to revisit any code changes, or is this PR now ready to be reviewed again and then merged?

**Comment by douglaspalmer** [comment]
> @douglaspalmer - the reported test `SessionTimeoutsTest` is a valid flaky test and it is unrelated to your code.
> 
> Do you want to revisit any code changes, or is this PR now ready to be reviewed again and then merged?

@ahus1 I think it's ready to merge.

**Review by ahus1 — DISMISSED** [review]
Approving as of @pedroigor's previous review. Thank you @douglaspalmer for reviewing my changes to the test suite.

**Comment by douglaspalmer** [comment]
> Approving as of @pedroigor's previous review. Thank you @douglaspalmer for reviewing my changes to the test suite.

@ahus1 Can you kick the checks off again? The build seems to have glitched.

**Comment by pedroigor** [comment]
@douglaspalmer GHA is failing for other PRs too. Not sure what is causing this and I'm also stuck because of it.

**Review by pedroigor — APPROVED** [review]
@ahus1 @douglaspalmer LGTM. Looks like tests are more stable now? Thanks for your help @ahus1.

**Pull request merged**
