### PR TITLE
#14045 -  Handled error during decoding form parameters 

### PR DESCRIPTION
**Pull request by ShefeeqPM**
#14045 - The error was due to the NPE when trying to get the decoded form params. Handled it by the try catch statement

### CODE REVIEW

**Review by pedroigor — CHANGES_REQUESTED** [review]
@ShefeeqPM Thanks.

We have now a wrapper around the underlying request, so we should make the change there.

Could you please look at this issue/comment @ShefeeqPM Could you please look at this issue/comment https://github.com/keycloak/keycloak/issues/11971#issuecomment-1432044158?.

The issue above should be related.

**Comment by ShefeeqPM** [comment]
> @ShefeeqPM Thanks.
> 
> We have now a wrapper around the underlying request, so we should make the change there.
> 
> Could you please look at this issue/comment @ShefeeqPM Could you please look at this issue/comment [#11971 (comment)](https://github.com/keycloak/keycloak/issues/11971#issuecomment-1432044158)?.
> 
> The issue above should be related.

Can you please elaborate your comment? Can you specify which is the Wrapper class for underlying request?

**Comment by ShefeeqPM** [comment]
Hi, Could you please reply

**Comment by pedroigor** [comment]
@ShefeeqPM Sorry. 

Yes I meant changing the `org.keycloak.services.HttpRequestImpl#getDecodedFormParameters` to something like this:

```
MediaType mediaType = getHttpHeaders().getMediaType();

if (!MULTIPART_FORM_DATA_TYPE.isCompatible(mediaType)) {
    return new MultivaluedHashMap<>();
}
```

The issue you are facing is more likely to Resteasy not able to resolve the media type and not properly handling a `null` value.

See the `getFormParameters` method on that same class, it does this check to fail fast and return an empty map rather than return `null`.

**Pull request closed without merging**
