### PR TITLE
KEYCLOAK-4559 Filter users by realm id when search for user by attribute

### PR DESCRIPTION
**Pull request by knutz3n**
See https://issues.jboss.org/browse/KEYCLOAK-4559 for details

### CODE REVIEW

**Comment by stianst** [comment]
This is not the correct approach. The query should be updated instead of filtering the results.

**Comment by knutz3n** [comment]
Sure, I can update the pull request.
However, the whole method should be considered to be changed since the query now fetches all UserAttributeEntities and afterwards loops through the result to do a getUser on each attribute entity.
Would you like me to change the query to join the UserEntity directly instead? Or should that rather be a separate issue?

**Comment by stianst** [comment]
Yes, please.

**Comment by knutz3n** [comment]
@stianst I have updated the pull request and changed the query to fetch UserEntities filtered by realm. Please let me know if you would like any more changes to this before merging.

**Comment by stianst** [comment]
That's much better thank you

**Pull request merged**
