### PR TITLE
KEYCLOAK-9676 Cannot login to Admin Console with just manage-* role

### PR DESCRIPTION
**Pull request by drichtarik**
I've got several notes to this so I'm creating this as a draft PR.

**mange-realm role**: Can edit Realm Settings, list Realm Roles but can't edit them and can't list Default Roles. Can edit User Federation and Authentication. Can list/see Sessions and access Import, Export buttons.

**manage-clients role**: Can see and edit Clients but no Client Storage(needs either view-realm or manage-realm roles). Can see the Client Storage tab though. Can see and edit Client Scopes. Can see Groups, Users, Events buttons/tabs but can't access these.

**manage-events role**: Can see and edit Events.

**manage-identity-providers role**: Can see and edit Identity Providers.

**manage-users role**: Can see and edit Groups. Can see and edit Users and their Realm Roles but can't see or edit Client Roles. For editing Client Roles, the admin needs + manage-clients role.

**manage-authrorization role**: A user can have only this role but there is no use case for that. It is a sub-role for manage-cliets when a user can manage authorizations for each client he has access to. If he has only manage-clients role, he can still see the Authorization tab.

When we agree on what is supposed to be redone, I should also write proper documentation on this because now it's minimal. + it needs tests

### CODE REVIEW

**Comment by drichtarik** [comment]
@pedroigor @stianst Can you let me know what you think please?

**Comment by stianst** [comment]
Can you explain why a user with only manage-user role can not access the console?

**Comment by pedroigor** [comment]
@drichtarik I see the point here, but I'm not sure if we want to ave all manage-roles before knowing the impact.

It does make sense and you did great work by describing what each role is supposed to do. But to have this one we really need to review fine-grained admin permissions more deeply first.

**Comment by stianst** [comment]
Closing this as it's out of date. We should discuss this on the dev (or team) mailing list on what would be the next steps here.

**Pull request closed without merging**
