### PR TITLE
KEYCLOAK-12926 Improve Locale based message lookup

### PR DESCRIPTION
**Pull request by thomasdarimont**
We now consider intermediate Locales when performing a Locale based
ResourceBundle lookup, before using an Locale.ENGLISH fallback.

### CODE REVIEW

**Comment by stianst** [comment]
There's one issue with the way this is implemented, which it will re-create the message bundle for a "parent" locale rather than using the already cached version.

I've refactored your PR a little bit and opened a new PR here: https://github.com/keycloak/keycloak/pull/6783

**Comment by stianst** [comment]
Also, not sure if "variant" needs to be supported. That would mean you'd need to create a message bundle for the variant, have support for a variant in the theme, and the user would get more choices than they need. Also, don't think browser will send variant in the accept-languages would they? However, end of the day I can't see there being anything bad happening by including it.

**Comment by thomasdarimont** [comment]
I think having support for variant is useful... this would allow to for audience / customer specific translations in the same base Locale (de_DE) in shared Keycloak environments.

**Comment by stianst** [comment]
@thomasdarimont I've merged https://github.com/keycloak/keycloak/pull/6783, so closing this one. Thanks for the contribution :)

**Pull request closed without merging**
