### PR TITLE
Ensure hide_on_login has the default value set to 0 on MSSQL

### LINKED ISSUE #34450: [26.0.2] Migration from 25.0.1 Identity Provider Errors
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

After Upgrading to 26.0.2 from 25.0.1 unable to access Identity Provider Page on admin console and users advise IDP disappears from login screen. 

Error recieved is "unknown error" and logs show that the SQL Statement is not expecting HIDE_ON_LOGIN to be null.

### Version

26.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

For Identity Providers to migrate correctly to the new version with no changes necessary 

OR

For the breaking changes to be detailed in the migration guide with how to resolve

I have been able to resolve this with a workaround of setting HIDE_ON_LOGIN to 0 in the database

Unsure if this is something to do with our particular setup or if its common across users

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sguilhen**
Closes #34450

Signed-off-by: Stefan Guilhen <sguilhen@redhat.com>
(cherry picked from commit ac258447317d3e52a3d44b98f58ab73e42f59a87)

### CODE REVIEW

**Review by pedroigor — DISMISSED** [review]

**Comment by pedroigor** [comment]
@rmartinc Do we need anything else ?

**Review by rmartinc — CHANGES_REQUESTED** [review]
I have tested and a previously keycloak at version 26.0.2 complains with the following message whe upgrading to current 999:

```
Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
     1 changesets check sum
          META-INF/jpa-changelog-26.0.0.xml::26.0.0-idps-for-login::keycloak was: 9:51f5fffadf986983d4bd59582c6c1604 but is now: 9:ac427966f1e52713b0c97a88b8d1351d
```

So we need to add the `9:51f5fffadf986983d4bd59582c6c1604` as valid checksums for that task.

**Review by pedroigor — COMMENTED** [review]
Waiting https://github.com/keycloak/keycloak/pull/34521.

**Comment by sguilhen** [comment]
@rmartinc @pedroigor updated this PR to also include the commit that adds the valid checksum to jpa-changelog-26.0.0.xml

**Review by rmartinc — APPROVED** [review]
Thankd @sguilhen !

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
