### PR TITLE
'Bevestiging' is raar daar.

### PR DESCRIPTION
**Pull request by mihxil**

### CODE REVIEW

**Comment by edewit** [comment]
:+1: as a Dutch speaker I can see that "Bevestiging raar is daar"

**Comment by stianst** [comment]
@mihxil Please use English in descriptions as most of the team do not understand Dutch, so will have to look into the changes to understand what it is about.

raar is daar makes no sense to me as a non-Dutch speaker - @edewit is this a good change or not?

**Comment by stianst** [comment]
Which is correct this one or:
https://github.com/keycloak/keycloak/pull/7003

**Comment by tim-hanssen** [comment]
This is the right one, agreed!

**Comment by mihxil** [comment]
Of course, but i figured that one can't  judge the change without knowing dutch anyways....

**Comment by stianst** [comment]
Thanks folks

**Review by stianst — APPROVED** [review]

**Pull request merged**
