### PR TITLE
KEYCLOAK-19313 configure the name format in Attribute Importer IdP Ma…

### PR DESCRIPTION
**Pull request by cgeorgilakis**
~BUG FIX -~ version 15.0.0

Edited by @hmlnarik - this is not a bug but an enhancement request

### CODE REVIEW

**Review by sguilhen — COMMENTED** [review]
The change itself looks good to me, I'm just missing a testcase for it.

**Review by sguilhen — DISMISSED** [review]

**Comment by cgeorgilakis** [comment]
@hmlnarik could you review this PR?

**Comment by cgeorgilakis** [comment]
Could you please accept this PR in order to being able to configure our SAML Identity Provider with url and not by changing a configuration file?
As you can see from SAML specification and the examples that I have already sent to you, some SAML identity providers accept only ATTRIBUTE_FORMAT_URI as attribute.name.format in UserAttributeMapper. This PR keeps previous Keycloak implementation as default.

**Comment by cgeorgilakis** [comment]
@hmlnarik could you accept this important PR for SAML Identity Provider attributes?
As I see also other people(@AlexanderNeumann and @FBasels) are interested in this enhancement.

**Comment by hmlnarik** [comment]
@cgeorgilakis Could you please add a testcase for this issue?

@sguilhen has mentioned this too in his comment to the PR: "The change itself looks good to me, _I'm just missing a testcase for it._"

**Comment by cgeorgilakis** [comment]
> > The change itself looks good to me, I'm just missing a testcase for it.
> 
> There are SAML Identity Providers that current SP metadata is not working.
> 
> You could see [SAML V2.0 Deployment Profile for Federation Interoperability](https://kantarainitiative.github.io/SAMLprofiles/saml2int.html) for example. In section 4.1.4. Attributes it says:
> 
> > saml:Attribute elements MUST contain a NameFormat of urn:oasis:names:tc:SAML:2.0:attrname-format:uri.
> > This requirement ensures unique, non-conflicting naming of SAML Attributes even in cases involving custom requirements for which no standard SAML Attributes may exist.

@hmlnarik As you can see, I have already given a testcase. Our SAML Identity Providers require ATTRIBUTE_FORMAT_URI.

**Comment by hmlnarik** [comment]
@cgeorgilakis There is no testcase contained in this PR. Have you checked the PR files? There is only a single file - the changed mapper.

image

Kindly provide a testcase that well covers the added functionality. Please refer to Item 8 of https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md#contributing-to-keycloak

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
