### PR TITLE
Apply the principle of least privilege for GitHub workflows

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for this change. Overall this looks good. Still I think on of the workflows need more permissions:

* The `label.yml` would add labels to issues, so that's writing

I'm surprised the the CodeQL work as it uploads some results, but it is green so it should be ok.

**Comment by abstractj** [comment]
> Thank you for this change. Overall this looks good. Still I think on of the workflows need more permissions:
> 
> * The `label.yml` would add labels to issues, so that's writing
> 
> I'm surprised the the CodeQL work as it uploads some results, but it is green so it should be ok.

@ahus1 That's a valid point, but after reviewing the file, I believe it won't be an issue. For example, in lines [6-7](https://github.com/abstractj/keycloak/blob/issue-token-readonly/.github/workflows/label.yml#L6-L7), we set the top-level permissions to read-only. However, in lines [14-15](https://github.com/abstractj/keycloak/blob/issue-token-readonly/.github/workflows/label.yml#L14-L15), we grant write permissions. Does that make sense to you?

**Review by ahus1 — APPROVED** [review]
Thank you for the explanation @abstractj - I now see that this should work. Approving!

**Comment by ahus1** [comment]
Created a follow-up issue #33625 as some scheduled tasks don't run any more

**Pull request merged**
