### PR TITLE
KEYCLOAK-6095 KEYCLOAK-6108 Schema-aware custom SQL

### PR DESCRIPTION
**Pull request by hmlnarik**

### CODE REVIEW

**Comment by hmlnarik** [comment]
@vramik Could you please check the supported DBs with this PR?

**Comment by vramik** [comment]
Hey @hmlnarik, I face following error on mariadb and myslql database:

ERROR [org.keycloak.connections.jpa.updater.liquibase.conn.DefaultLiquibaseConnectionProvider] (ServerService Thread Pool -- 53) Change Set META-INF/jpa-changelog-authz-3.4.0.CR1.xml::authz-3.4.0.CR1-resource-server-pk-change-part3-fixed::glavoie@gmail.com failed.  Error: (conn:1458) Cannot drop index 'IDX_RES_SERV_POL_RES_SERV': needed in a foreign key constraint [Failed SQL: DROP INDEX IDX_RES_SERV_POL_RES_SERV ON dballo19.RESOURCE_SERVER_POLICY]: liquibase.exception.DatabaseException: (conn:1458) Cannot drop index 'IDX_RES_SERV_POL_RES_SERV': needed in a foreign key constraint [Failed SQL: DROP INDEX IDX_RES_SERV_POL_RES_SERV ON dballo19.RESOURCE_SERVER_POLICY]

**Comment by hmlnarik** [comment]
@vramik Thanks for spotting this. The change is apparently necessary only for mssql, not for every db except for postgres and h2 like it was in previous version. Can you please recheck

**Comment by vramik** [comment]
I've tested initialization of all DBs and run base testsuite form default configuration. I've also tested migration from 3.4.2.Final to th PR and all it works fine (I had to disable OfflineToken migration test, need to investigate further). I've tested the PR with postgres locally and it seems fine to me.

**Pull request merged**
