### PR TITLE
add support for wildcard persistent nameId attribute to SAML protocol

### PR DESCRIPTION
**Pull request by josh-cain**
We have a requirement for a persistent NameID attribute that's based on the username.  Wanted to override the default GUID behavior without having to implement on a per user/sp basis.  As such, implemented a wildcard attribute to allow for this kind of override.

### CODE REVIEW

**Comment by patriot1burke** [comment]
I don't like this.  Consider you have 2 SPs, one that uses the wildcard, and the other needs email format.  With this fix, the email-requiring SP would never be able to override the default behavior.

**Comment by cainj13** [comment]
Unless I missed something, this shouldn't effect formats other than persistent.  What's more, it will still provide a mechanism for individual SP's to override the wildcard, as clientID will be evaluated first.  The goal was just to provide an alternative for the generated GUID that happens now.

**Comment by patriot1burke** [comment]
Ok, sorry, you're right :)

If you add documentation for this, I'll accept the PR.

**Comment by cainj13** [comment]
Awesome!  documentation on its way shortly.

**Comment by cainj13** [comment]
Got the docs ready @patriot1burke.  This gonna make 1.9?

**Pull request merged**
