### PR TITLE
Use http-pool-max-threads in HA guides

### LINKED ISSUE #26849: Use http-pool-max-threads in HA guide
### Description

#26455 a new operator option to specify `http-pool-max-threads` we should use it in our HA guide

### PR DESCRIPTION
**Pull request by mhajas**
Closes #26849

### CODE REVIEW

**Review by kami619 — APPROVED** [review]
lgtm

**Comment by ahus1** [comment]
@mhajas - I replaced some occurrences of `Keycloak` with `{project_name}` as we must not use plain `Keycloak` in the downstream docs. In the downstream docs, it is always `Red Hat Build of Keycloak`.

**Review by ahus1 — APPROVED** [review]
Thank you for updating the documentation! One more step towards only supported configurations in HA!

**Comment by mhajas** [comment]
Thank you for the update @ahus1!

**Pull request merged**
