### PR TITLE
Fix creation of domains when creating the organization

### LINKED ISSUE #29005: Review the creation of domains upon creating the organization
Currently when Organization is being created the provider takes organization name and list of string domain as parameters: https://github.com/keycloak/keycloak/blob/9486432f3f48da8a87040bfd192162919d1b301f/services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java#L79

The implementation first creates and persists `OrganizationEntity`  

https://github.com/keycloak/keycloak/blob/9486432f3f48da8a87040bfd192162919d1b301f/model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java#L73-L80 

and then sets domains (by creating OrganizationDomainModel for each of them) to the created organization adapter

https://github.com/keycloak/keycloak/blob/9486432f3f48da8a87040bfd192162919d1b301f/model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java#L84

There the validation is being performed

https://github.com/keycloak/keycloak/blob/9486432f3f48da8a87040bfd192162919d1b301f/model/jpa/src/main/java/org/keycloak/organization/jpa/OrganizationAdapter.java#L169-L180

Then the `OrganizationResource` calls https://github.com/keycloak/keycloak/blob/9486432f3f48da8a87040bfd192162919d1b301f/services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java#L81

where setDomains is being called again
https://github.com/keycloak/keycloak/blob/9486432f3f48da8a87040bfd192162919d1b301f/services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java#L189

This issue is about deciding what approach we should take when working with domains, where the validation should happen and to avoid setting domains twice upon its creation

### PR DESCRIPTION
**Pull request by vramik**
Closes #29005

### CODE REVIEW

**Review by sguilhen — APPROVED** [review]
It looks good to me - we were indeed processing the domains twice during org creation, this is cleaner.

CI has a failed test but really doesn't like it is related to this PR at all.

**Comment by ahus1** [comment]
WebAuthn IT has been fixed in main, re-running that part of the CI

**Comment by ahus1** [comment]
@vramik - please rebase. I thought a full rerun of a job would use the latest merge commit contents, but apparently it doesn't.

**Review by sguilhen — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]
Approving based on @sguilhen's review

**Pull request merged**
