### PR TITLE
[KEYCLOAK-16886] - Updating user account removes attributes

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by mposolda** [comment]
@pedroigor Thanks!

**Review by mposolda — APPROVED** [review]

**Comment by shacal** [comment]
This seems to have zero effect on login "Update profile" and old account page update. Correct?

**Comment by pedroigor** [comment]
@shacal Correct. Could you please check https://github.com/keycloak/keycloak/pull/7778?

**Comment by pedroigor** [comment]
@shacal There was a mistake. The changes to user profile and user apis were not in any of the PRs. Please, check https://github.com/keycloak/keycloak/pull/7800.

**Comment by shacal** [comment]
@pedroigor thanks for the link.
Im currently having issues of lost attributes after upgrade to 12.0.2 and after seeing 12.0.3 for the fix,, was hopeful.
I mitigated issue by disabling profile updates atm.
But, as fix is already on on works, can't wait to get my hands on it when ready.

#7800 looks much better for it <3

**Pull request merged**
