### PR TITLE
Unify fundamental terms throughout the application

### LINKED ISSUE #11301: Unify fundamental terms throughout the application
### Describe the bug

AFAIK, the official term used in Keycloak is `Sign in` instead of `Log in`. Recently, there were added some changes to the account console and those messages changed. It'd be great to take it back.

### Version

999

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
Fixes #11301

@andymunro @tyandor Could you please take a look at this? Thank you.

### CODE REVIEW

**Review by tyandor — APPROVED** [review]
Looks good to me 👍

**Comment by andymunro** [comment]
Generally our documentation always use log in rather than sign in.  I think it is a good topic to suggest for the whole documentation set, but not for one PR.

**Comment by mabartos** [comment]
@andymunro I'm not sure about this. In PR #10748, there were some changes related to those terms and I don't see any benefit by changing it there, rather the opposite. The account console was using the `Sign in` term before those changes[1] and it was consistent with the login screens. The documentation is more separated than the login and account screens together. I think this PR is relevant. 

[1] https://github.com/keycloak/keycloak/pull/10748/files#diff-c9960d63791e169b1bd22eaa9d37a256f2e76c3738a9aa35365f1f62e9ec0ccaL98-L104

**Comment by andymunro** [comment]
Thanks @mabartos.  Okay, I see either way, there is some inconsistency with the UI or the documentation.  If so, I agree with your suggested changes.

**Review by andymunro — APPROVED** [review]

**Review by abstractj — APPROVED** [review]

**Comment by abstractj** [comment]
Adding @ssilvert here considering the impact in the UI

**Review by jonkoops — APPROVED** [review]

**Review by abstractj — APPROVED** [review]

**Pull request merged**
