### PR TITLE
KEYCLOAK-1305 Add possibility to change username

### PR DESCRIPTION
**Pull request by dasniko**
Be able to change the username of a user in admin api and admin console.
For admin console, there's a new "Edit Username" switch, to allow the modification of the username.

### CODE REVIEW

**Comment by stianst** [comment]
There's a lot of outstanding work before this can be committed:

* Switch to edit username should not be on user details - it should be a realm option. It also needs to be persisted
* UsersResource should only allow updating username if above option is enabled
* Need to be able to update username from account management as well

**Comment by dasniko** [comment]
Ok, I'm on it...

**Comment by dasniko** [comment]
switch in realm, persistence and UsersResource should be ok, now working on the account app...

**Comment by stianst** [comment]
Finished?

**Comment by dasniko** [comment]
Yes, I think so.
If there are more resources involved/dependend, then please tell me which/where!

**Comment by stianst** [comment]
Would you mind squashing your commits? and also rebasing on master?

**Comment by dasniko** [comment]
squashed and rebased!

**Comment by stianst** [comment]
Awesome, thanks.. I'll review and merge soon.

**Pull request merged**
