### PR TITLE
Remove realm model storage from OAuth2DeviceConfig class 

### LINKED ISSUE #23943: Session/EntityManager is closed when using infinispan and attempting to update the realm
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

This bug most readily presents itself when attempting to use the session revocation feature in the admin UI. 

Only happens when using infinispan, any request to update the realm fails. 

### Version

Nightly

### Expected behavior

The realm should be able to update and the hibernate entity manager should not be closed for the current session

### Actual behavior

Error returns, request fails, realm does not update, error message says that the entity manager is closed

### How to Reproduce?

This bug most readily presents itself when attempting to use the session revocation feature in the admin UI. 

### Anything else?

I have diagnosed this issue and will be submitting a PR to resolve. It is caused by persistence of a cached realm model on OAuth2DeviceConfig in infinispan, causing a reference to an old session and entity manager instead of the most up to date

### PR DESCRIPTION
**Pull request by alice-wondered**
avoid persisting old session and entity manager in infinispan 

fixes keycloak/keycloak#23943

### CODE REVIEW

**Comment by mposolda** [comment]
@keycloak/store-maintainers  Are you please able to review this PR?

**Comment by ahus1** [comment]
@Michito-Okai / @pedroigor - this is a note to you that we're changing the realm reference which is cached inside of the model and we need to avoid it. The change looks good to me, so we soon plan to merge this. 

The original change was done for https://issues.redhat.com/browse/KEYCLOAK-7675 in commit 298ab0bc3eee93b35512211cba4d37edaf1905e3

**Review by ahus1 — APPROVED** [review]
LGTM, seeing the reference is likely to cause troubles.

**Comment by ahus1** [comment]
@mposolda / @Redhat-Alice - do you want to have this change in 22.0.5, or can we wait for the reply of the original authors? I see that this pattern exists in other places as well, and we might want to revisit that one as well to keep the code consistent.

**Comment by Redhat-Alice** [comment]
It's not pressing on our end, I came across this while working on other behavior and figured I'd submit a fix!

**Comment by Redhat-Alice** [comment]
I see that this is flagged as approved and merge-able. Should I go ahead and do that or is the plan for this to sit for the time being?

**Pull request merged**
