### PR TITLE
[fix: #9213] Partial workaround for QuarkusMainTests streams spilling

### PR DESCRIPTION
**Pull request by andreaTP**
This is a partial and temporary mitigation for #9213

### CODE REVIEW

**Comment by pedroigor** [comment]
@andreaTP Shall we have this one prior to your changes to docker tests? Or the latter by itself is enough to wait until your changes to Quarkus are available to us?

**Comment by andreaTP** [comment]
@pedroigor this is unrelated with the docker tests, this fix flaky test on the JVM.
I would merge both PRs and remove the detailed code in this PR only when we upgrade Quarkus to (unreleased >= 2.6.1)

**Review by pedroigor — APPROVED** [review]

**Review by DGuhr — APPROVED** [review]
Thanks for providing the workaround. @pedroigor @andreaTP shall we create a follow-up issue so this doesn't get lost?

**Comment by andreaTP** [comment]
@DGuhr I would say that we can simply keep #9213 until this is finished, wdyt?

**Comment by DGuhr** [comment]
just ftr: Release 2.5.4 contains the fix to quarkus itself, so instead of applying this workaround, let's try to update instead :)

**Pull request closed without merging**
