### PR TITLE
Keycloak 6512 Open workload injection model

### PR DESCRIPTION
**Pull request by tkyjovsk**
Requires/includes commit for KEYCLOAK-5372.

### CODE REVIEW

**Comment by mstruk** [comment]
Needs to be rebased before continuing review - KEYCLOAK-5372 is now in master.

**Comment by tkyjovsk** [comment]
Rebased. It seems that the log filtering doesn't work well with the `usersPerSec` injection. If I enable filtering I can see the reported number of active users steadily growing even if it was constant during the test run and is reported as constant with filtering switched off. Can you try this out?

**Comment by tkyjovsk** [comment]
@mstruk I've incorporated your fixes of LogProcessor. 
Additionally:
- I added adjusting of start time of the simulation in filtered log.
- I set both flags to `false` because the outlayed=true was behaving weird at the end of AdminConsoleSimulation with `usersPerSec >= 1`.
- I added `CommonSimulation.scala`

**Comment by mstruk** [comment]
I made some minor fixes. See https://github.com/tkyjovsk/keycloak/pull/12

**Comment by tkyjovsk** [comment]
@mstruk Fixes incorporated and rebased.

**Review by mstruk — APPROVED** [review]

**Pull request merged**
