### PR TITLE
removes the SSA logging that is capturing the entire resource

### LINKED ISSUE #22607: performance regression with running the local tests after realm import dependent resource conversion
There appears to be a performance regression with running the local tests: https://github.com/keycloak/keycloak/actions/runs/5927179684/job/16070891213?pr=22299

It may be related to the additional overhead of logging the full realm secret into the console log that is captured by ci - as the remote tests do not seem to have the same issue.  If this does turn out to be the problem, it has already been addressed by upstream changes in the operator sdk.

_Originally posted by @shawkins in https://github.com/keycloak/keycloak/issues/22223#issuecomment-1687282963_

### PR DESCRIPTION
**Pull request by shawkins**
Closes #22607

### CODE REVIEW

**Comment by shawkins** [comment]
@vmuzikar this does seem to resolve the issue.  The local runtime is back down to the pre-conversion level.

**Comment by vmuzikar** [comment]
I wonder if it even makes sense to have the debug log level for JOSDK in tests. I don't remember actually using this when investigating any CI runs. WDYT?

**Comment by shawkins** [comment]
> I wonder if it even makes sense to have the debug log level for JOSDK in tests. I don't remember actually using this when investigating any CI runs. WDYT?

You could go a step further and only run the remote tests as part of the CI.

**Comment by vmuzikar** [comment]
> You could go a step further and only run the remote tests as part of the CI.

Nah, let's keep it. Local operator is used during dev and we want to make sure nothing broke this. We can always remove if we see it's becoming a bottleneck.

**Comment by shawkins** [comment]
> Nah, let's keep it. Local operator is used during dev and we want to make sure nothing broke this. We can always remove if we see it's becoming a bottleneck.

See if you like this better, it's an override specifically for the CI.

**Comment by shawkins** [comment]
> IMHO no need to have debug level by default.

Sorry, I took you literally about CI runs.  The other thought to support just changing it for CI was that we're still undergoing a lot of changes with the operator sdk and it makes things like unexpected reconciliation loops easier to spot.

It's fine with me though if you want to just remove the debug in general.

**Comment by vmuzikar** [comment]
> It's fine with me though if you want to just remove the debug in general.

If it works for you, then we're aligned. :) Log level can be always increased if we need it.

**Comment by shawkins** [comment]
> If it works for you, then we're aligned. :) Log level can be always increased if we need it.

Ok, it's done.

**Review by vmuzikar — APPROVED** [review]

**Pull request merged**
