### PR TITLE
KEYCLOAK-2743: Port OAuthClient to new testsuite

### PR DESCRIPTION
**Pull request by ssilvert**
This PR ports the legacy OAuthClient and provides other various fixes to make it work.  It also ports two test classes that hit the ported OAuthClient to make sure that it works.  In addition to that, there is some adapter code that makes legacy tests easier to port.

At this point the legacy OAuthClient is not unified with the new OAuthClient.  We can discuss that as a next step.  The main concern I have is that the two classes are designed in a completely different way with different internals and goals.

You can also see that ported stuff is under the org.keycloak.testsuite.legacy package.  Bruno and I have discussed this and feel that, for now, there is value in being able to quickly identify the ported tests and supporting classes.

### CODE REVIEW

**Comment by patriot1burke** [comment]
what about to 1.9.x branch?

**Comment by ssilvert** [comment]
I want to make sure this is acceptable first.  Then I'll do the 1.9.x branch.

**Comment by stianst** [comment]
-1 Please remove legacy package, this will just remain. Please port the tests and oauth client properly when it's first done.

**Comment by stianst** [comment]
Please do the changes we discussed on the chat and remove incomplete label

**Comment by ssilvert** [comment]
Need to close this PR and replace it with https://github.com/keycloak/keycloak/pull/2635.  Git did some flaky stuff and I had to start with a fresh branch.

**Pull request closed without merging**
