### PR TITLE
KEYCLOAK-18518 Add expiration lifespan configuration to every distrib…

### PR DESCRIPTION
**Pull request by vramik**
…uted and replicated cache

### CODE REVIEW

**Comment by sschu** [comment]
According to https://docs.wildfly.org/21/wildscribe/subsystem/infinispan/cache-container/distributed-cache/component/expiration/index.html the unit is milliseconds. This gives an expiration of ca. 23 days. If I understand this right, this will then be the maximum session length. Isn't that too short?

**Comment by hmlnarik** [comment]
> According to https://docs.wildfly.org/21/wildscribe/subsystem/infinispan/cache-container/distributed-cache/component/expiration/index.html the unit is milliseconds. This gives an expiration of ca. 23 days. If I understand this right, this will then be the maximum session length. Isn't that too short?

That's right, thank you for spotting this. Per https://issues.redhat.com/browse/WFLY-14935, the recommended value for the workaround is `9223372036854775807`.

**Comment by vramik** [comment]
> That's right, thank you for spotting this. Per https://issues.redhat.com/browse/WFLY-14935, the recommended value for the workaround is `9223372036854775807`.

I've updated values according to it.

**Review by pedroigor — DISMISSED** [review]
Quarkus change looks good.

**Review by pskopek — DISMISSED** [review]
Feature pack and galleon pack changes look good.

**Comment by vramik** [comment]
https://master-jenkins/job/universal-test-pipeline-server/580

**Comment by vramik** [comment]
https://master-jenkins/job/universal-test-pipeline-server/603

**Review by hmlnarik — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
