### PR TITLE
KEYCLOAK-8813 Avoid Need for allow-bean-definition-overriding in boot 2.1

### PR DESCRIPTION
**Pull request by ryandawsonuk**
Issue at https://issues.jboss.org/browse/KEYCLOAK-8813

Linked activiti issue https://github.com/Activiti/Activiti/issues/2201

### CODE REVIEW

**Comment by ryandawsonuk** [comment]
Actually I now think it would be better to exclude HttpSessionManager from the ComponentScan as boot annotations like ConditionalOnMissingBean aren't available in the spring-security adapter

**Comment by salaboy** [comment]
@sebastienblanc, Hi there..  is there any planned version release with Spring boot 2.1 in the near future? We only found this one when upgrading..

**Comment by ryandawsonuk** [comment]
If we go with this PR we should probably also add a note in the docs under combining spring security with spring boot. There's an example in the docs for spring security that suggests using exactly this componentscan under https://www.keycloak.org/docs/4.6/securing_apps/index.html#_spring_security_adapter

**Comment by hmlnarik** [comment]
Thank you for the contribution. Sadly, current priorities and bandwidth does not allow us to work on this PR at this moment. Therefore this PR is currently marked on hold. We will be happy to continue the work after 4.x is wrapped up.
Thank you for understanding.

**Comment by ryandawsonuk** [comment]
Actually I have realised there is no need to change the code as the documentation change alone is enough to avoid this. Hence I am closing this PR in favour of https://github.com/keycloak/keycloak-documentation/pull/533

**Pull request closed without merging**
