### PR TITLE
Use the github /user/emails api endpoint if the github user did not set any public email

### PR DESCRIPTION
**Pull request by GregoireW**
Github can send a null email on the user info endpoint if there is no public email on the user profile.
This commit look for email on the /user/emails endpoint, selecting the primary email.

### CODE REVIEW

**Comment by lusoalex** [comment]
Hi,

That PR would be great. Even if we request the email scope, github do not return it on the first call if the user choose to hide it from it's public github profil.

But as our app has requested this scope, we can retrieve it anyway using /user/emails endpoint.

github_scopes

So that would be really helpful to manage it on the 1st login.
We tried this PR, it works fine 👍

**Review by stianst — CHANGES_REQUESTED** [review]
We'd need tests to be added for this one. The social login tests are kept in:
https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java

There's details on how to run them in:
https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md

**Comment by stianst** [comment]
This is missing a JIRA and tests.

**Comment by GregoireW** [comment]
Hello,

Currently test are made against a user  in a config file somewhere hidden (because login / password...) I'm not sure how you want to play this one :  duplicate the test to use 1 user with public mail, and 1 user with private mail ?  ( if so i'm afraid of change to do to the current test, as there is one use case per provider)

**Comment by vmuzikar** [comment]
Hi @GregoireW! Here's Václav from the QE.
Thank you for your contribution.

I've created a JIRA for this enhancement: https://issues.jboss.org/browse/KEYCLOAK-6330

I've also prepared the SocialLoginTest (as well as our CI environment) for this, so now there are two GitHub tests with separate configurations, and created a [PR in your repo](https://github.com/GregoireW/keycloak/pull/1). You can merge it if you want.

After that, we'll be ready to merge this PR.

**Comment by stianst** [comment]
Sent a new PR with tests included:
https://github.com/keycloak/keycloak/pull/4937

**Comment by stianst** [comment]
Closing in favour of the new PR with tests included

**Comment by GregoireW** [comment]
Thank you, I was planning this for the week end, now I have some time (or not :D )

**Pull request closed without merging**
