### PR TITLE
converts the ingress logic to a conditional dependent resource

### LINKED ISSUE #22206: Convert KeycloakIngress to a dependent resource
### Description

KeycloakIngress presents some challenges in conversion.  The first issue is that the basic dependent resource logic does not handle a null desired state - but we want to remove the Ingress if it has been disabled on the CR.  

The next issue is that more about the direction this logic will take in the future - it seems like we're going to need one dependent resource type for kubernetes, and another for openshift that directly creates routes rather than ingresses.

cc @csviri

### PR DESCRIPTION
**Pull request by shawkins**
conflicts with the admin conversion, but that is easy to resolve.  Thanks @csviri on the pointer to the reconcilePrecondition.

The unit test changes were minimal due to maintaining the same contract, but we can of course refine that more.

Closes #22206

### CODE REVIEW

**Comment by shawkins** [comment]
@csviri I'm hitting a problem with the pull request that I've been able to reproduce locally.  There are non-deterministic test failures that seem to be due to a mixup in the cache state.  While the underlying informer cache knows of the approriate latest state, the actual resource known during reconciliation is an older version - which is used to set the resourceVersion on the current update.  That will then fail and keep failing until the retries are exhausted and the test errors out.

**Comment by shawkins** [comment]
@csviri when this happens the log sequence looks like:

```
2023-08-03 14:08:59,877 DEBUG [io.jav.ope.pro.eve.sou.inf.InformerEventSource] (pool-18-thread-4) Starting event recording for: ResourceID{name='example-kc-ingress', namespace='keycloak-test-89a8708a-cc7a-41d9-bb8f-69e79158f7a9'}
2023-08-03 14:08:59,877 DEBUG [io.jav.ope.pro.dep.kub.KubernetesDependentResource] (pool-18-thread-4) Updating target resource with type: class io.fabric8.kubernetes.api.model.networking.v1.Ingress, with id: ResourceID{name='example-kc-ingress', namespace='keycloak-test-89a8708a-cc7a-41d9-bb8f-69e79158f7a9'}
2023-08-03 14:08:59,947 DEBUG [io.fab.kub.cli.inf.imp.cac.Reflector] (-717974682-pool-14-thread-2) Event received MODIFIED Ingress resourceVersion v1825358 for networking.k8s.io/v1/namespaces/keycloak-test-89a8708a-cc7a-41d9-bb8f-69e79158f7a9/ingresses
2023-08-03 14:08:59,947 DEBUG [io.jav.ope.pro.eve.sou.inf.InformerEventSource] (-717974682-pool-14-thread-1) On update event received for resource id: ResourceID{name='example-kc-ingress', namespace='keycloak-test-89a8708a-cc7a-41d9-bb8f-69e79158f7a9'} type: Ingress
2023-08-03 14:08:59,947 DEBUG [io.jav.ope.pro.eve.sou.inf.InformerEventSource] (-717974682-pool-14-thread-1) Recording event for: ResourceID{name='example-kc-ingress', namespace='keycloak-test-89a8708a-cc7a-41d9-bb8f-69e79158f7a9'}
```

v1825358 is the latest state we should be using, but it seems to get swallowed in the event recording.  This could be related to how quickly the api server is creating an additional revision of the Ingress - noted here https://github.com/kubernetes/kubernetes/issues/118519#issuecomment-1596272620

I think the converstation that spawned https://github.com/operator-framework/java-operator-sdk/issues/1958#issue-1767111315 was also related to this as well as https://github.com/fabric8io/kubernetes-client/issues/4077 - it might be good continue that dicussion.

For event filtering it seems like we could consider having the operator add an annotation that contained a unique identifier for that operator instance and the previous revision of the resource - 
```
annotations:
  some.operator.key: uuid,previous
```
The add and update filters given the instance uuid could easily determine if that is something that was already known.

For cache updates, I probably need to understand how recording is functioning more, but intitively it seems like those need to be done in a locked way like https://github.com/fabric8io/kubernetes-client/issues/4077#issuecomment-1104394207 with the problem of potentially moving too far ahead, or like what kubernetes is doing and just parse the resourceVersions https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/staging/src/k8s.io/client-go/tools/cache/mutation_cache.go#L35

**Comment by csviri** [comment]
@shawkins investigating now.

> v1825358 is the latest state we should be using, but it seems to get swallowed in the event recording.

this should not matter, basically it is recorded that was received, that time already in the informer cache, this code should make sure that we cache explicitly to on overlay cache the recently updated resource only if we did not received the event about it:

https://github.com/java-operator-sdk/java-operator-sdk/blob/077bbc2f224ee7fcc9da933aefd6c46aa51f95dd/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSource.java#L280-L294

**Comment by shawkins** [comment]
> this should not matter, basically it is recorded that was received, that time already in the informer cache, this code should make sure that we cache explicitly to on overlay cache the recently updated resource only if we did not received the event about it:

I think it's just a timing issue.  After the latest event is received:

```
2023-08-04 06:25:43,897 DEBUG [io.fab.kub.cli.inf.imp.cac.Reflector] (-1477861846-pool-14-thread-1) Event received MODIFIED Ingress resourceVersion vXXX for networking.k8s.io/v1/namespaces/keycloak-test-3b5a38f9-d6c4-473e-bbb0-d274a5f0081c/ingresses
```
There are no debug logs from handleRecentResourceOperationAndStopEventRecording that indicate anything was done with the event.  

It appears to be because eventRecorder.containsEventWithResourceVersion is true (it did record the event) and eventRecorder.containsEventWithVersionButItsNotLastOne is false (there's only a single event).  However we're still left with the stale entry in temporaryCache once the call completes.  

If the event was not already recorded, then we see "Did not found event in buffer..." and everything proceeds as normal.

**Comment by csviri** [comment]
However the only place where we put resource into temp cache is here:

https://github.com/java-operator-sdk/java-operator-sdk/blob/077bbc2f224ee7fcc9da933aefd6c46aa51f95dd/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSource.java#L284-L284

**Comment by shawkins** [comment]
@csviri the add has the side effect of populating the temporary cache:

```
2023-08-04 06:25:30,765 DEBUG [io.fab.kub.cli.inf.imp.cac.Reflector] (-1477861846-pool-14-thread-1) Event received ADDED Ingress resourceVersion v1938442 for networking.k8s.io/v1/namespaces/keycloak-test-3b5a38f9-d6c4-473e-bbb0-d274a5f0081c/ingresses
2023-08-04 06:25:30,765 DEBUG [io.jav.ope.pro.eve.sou.inf.InformerEventSource] (pool-18-thread-1) Did not found event in buffer with target version and resource id: ResourceID{name='example-kc-ingress', namespace='keycloak-test-3b5a38f9-d6c4-473e-bbb0-d274a5f0081c'}
2023-08-04 06:25:30,765 DEBUG [io.jav.ope.pro.eve.sou.inf.InformerEventSource] (-1477861846-pool-14-thread-2) On add event received for resource id: ResourceID{name='example-kc-ingress', namespace='keycloak-test-3b5a38f9-d6c4-473e-bbb0-d274a5f0081c'} type: Ingress
```

The logic then assumes that reconciliation is needed again - however that is not accurate, there are "false" differences between the desired and the actual 1938442 state

```
2023-08-04 06:25:31,035 DEBUG [io.jav.ope.pro.dep.kub.SSABasedGenericKubernetesResourceMatcher] (pool-18-thread-3) Pruned actual: 
 {metadata={annotations={a=b, route.openshift.io/termination=passthrough, nginx.ingress.kubernetes.io/backend-protocol=HTTPS}, labels={app=keycloak, app.kubernetes.io/managed-by=keycloak-operator, app.kubernetes.io/instance=example-kc}, ownerReferences=[{name=example-kc, uid=18ed3cbd-8647-4d6b-b099-631e74afed80, apiVersion=k8s.keycloak.org/v2alpha1, kind=Keycloak}]}, spec={defaultBackend={service={port={number=8443, name=null}, name=example-kc-service}}, rules=[{host=example.com, http={paths=[{backend={service={name=example-kc-service, port={number=8443}}}, pathType=ImplementationSpecific}]}}]}} 
 desired: 
 {metadata={annotations={a=b, route.openshift.io/termination=passthrough, nginx.ingress.kubernetes.io/backend-protocol=HTTPS}, labels={app=keycloak, app.kubernetes.io/managed-by=keycloak-operator, app.kubernetes.io/instance=example-kc}, ownerReferences=[{apiVersion=k8s.keycloak.org/v2alpha1, kind=Keycloak, name=example-kc, uid=18ed3cbd-8647-4d6b-b099-631e74afed80}]}, spec={defaultBackend={service={name=example-kc-service, port={name=, number=8443}}}, rules=[{host=example.com, http={paths=[{backend={service={name=example-kc-service, port={name=, number=8443}}}, path=, pathType=ImplementationSpecific}]}}]}} 
```
That also updates the temporary cache:

```
2023-08-04 06:25:31,086 DEBUG [io.jav.ope.pro.eve.sou.inf.InformerEventSource] (pool-18-thread-3) Did not found event in buffer with target version and resource id: ResourceID{name='example-kc-ingress', namespace='keycloak-test-3b5a38f9-d6c4-473e-bbb0-d274a5f0081c'}
```

It doesn't receive the actual event of that update until later:
```
2023-08-04 06:25:37,148 DEBUG [io.fab.kub.cli.inf.imp.cac.Reflector] (-1477861846-pool-14-thread-2) Event received MODIFIED Ingress resourceVersion v1938485 for networking.k8s.io/v1/namespaces/keycloak-test-3b5a38f9-d6c4-473e-bbb0-d274a5f0081c/ingresses
2023-08-04 06:25:37,149 DEBUG [io.jav.ope.pro.eve.sou.inf.InformerEventSource] (-1477861846-pool-14-thread-1) On update event received for resource id: ResourceID{name='example-kc-ingress', namespace='keycloak-test-3b5a38f9-d6c4-473e-bbb0-d274a5f0081c'} type: Ingress
2023-08-04 06:25:37,149 DEBUG [io.jav.ope.pro.eve.sou.inf.InformerEventSource] (-1477861846-pool-14-thread-1) Resource found in temporal cache for id: ResourceID{name='example-kc-ingress', namespace='keycloak-test-3b5a38f9-d6c4-473e-bbb0-d274a5f0081c'} resource versions equal: false
```
That last log should imply that the temporary cache is cleared of 1938485.  It is then processed again because the ssa diffing logic assumes there are differences when there are not, it's added back into the temporary cache:

```
2023-08-04 06:25:37,232 DEBUG [io.jav.ope.pro.eve.sou.inf.InformerEventSource] (pool-18-thread-5) Did not found event in buffer with target version and resource id: ResourceID{name='example-kc-ingress', namespace='keycloak-test-3b5a38f9-d6c4-473e-bbb0-d274a5f0081c'}
```
That's where it seems like things are off track.  I'm not sure why, but that appears to be adding back 1938485 into the tempoary cache instead of moving ahead to 1938509.

We don't see the actual event for 1938509 until later:
```
2023-08-04 06:25:43,897 DEBUG [io.fab.kub.cli.inf.imp.cac.Reflector] (-1477861846-pool-14-thread-1) Event received MODIFIED Ingress resourceVersion v1938509 for networking.k8s.io/v1/namespaces/keycloak-test-3b5a38f9-d6c4-473e-bbb0-d274a5f0081c/ingresses
```

And it has no effect on the temporary cache, and we're stuck.

**Comment by csviri** [comment]
created a fix: https://github.com/operator-framework/java-operator-sdk/pull/1994

On matcher will check separatelly.

**Comment by shawkins** [comment]
> On matcher will check separatelly.

Should I create an issue for that?

I'll update this pr to add back the MetadataAwareOnUpdateFilter for now.

**Comment by shawkins** [comment]
> I'll update this pr to add back the MetadataAwareOnUpdateFilter for now also.

Instead of doing that, I've removed the places where we are using empty strings on the ingress.  By the same reasoning we used with #22257 if a user were to try to switch from a port number to a name, we'd consider that unsupported and they would have to roll their change back or delete the resource - that expectation has been removed from the ingress durability tests.

This should also mean that we don't have to wait for https://github.com/operator-framework/java-operator-sdk/issues/2000 and https://github.com/operator-framework/java-operator-sdk/pull/1994 to proceed with this change - I'll remove the hold if everyone is comfortable with this.

**Comment by shawkins** [comment]
Removed the hold.

**Review by vmuzikar — APPROVED** [review]
@shawkins LGTM, thank you.

**Comment by vmuzikar** [comment]
Rebased to fix CI.

**Pull request merged**
