### PR TITLE
[KEYCLOAK-12960] Set nbf on AccessToken

### PR DESCRIPTION
**Pull request by diodfr**
Compute  and set not before on AccessToken like not before policy on AccessTokenResponse.Select the more recent between realm, client and user "not before"values.

I can't find where in the testsuite/integration-arquillian/tests/base to write tests. Could you help me ?

Thanks for your work.

### CODE REVIEW

**Comment by stianst** [comment]
From the specification nbf = 0 is a valid value. See https://tools.ietf.org/html/rfc7519#section-4.1.5 and https://tools.ietf.org/html/rfc7519#section-2 / NumericDate.

The value should be set based on nbf value of realm, client and user. However, in practice that makes little sense as any newly issued tokens would always have a nbf value in the past, as it makes no sense to set the nbf value for a realm/client/user to some time in the future.

It seems this is an attempt to work around an issue found elsewhere rather than resolving the issue where it actually should be fixed?

**Comment by diodfr** [comment]
> It seems this is an attempt to work around an issue found elsewhere rather than resolving the issue where it actually should be fixed?
I agree and I will send ask them to correct.

In the other hand, the nbf policy is sent within the access token response but not in the access token. It looks like an inconsistency for me.
Also nbf is not mandatory as far as I understand, so why send it with 0 value ?

Anyway, thanks for your time and your work.
Regards,
Didier

**Comment by stianst** [comment]
I think what makes sense to me is to either not include nbf, or set it to the current time. Setting to the current time has an issue if the client is not allowing for a slight time skew there could be problems, but it does at the same time prevent a client that is significantly out of sync with Keycloak from accepting a token.

The proposed changes you have here doesn't make all that much sense to me. I really don't see the use-case for setting the nbf based on the realm/client/user nbf values as I said they will always be in the past, so there's just no point.

The not-before-policy in the token response is another issue, but IMO that shouldn't be there either. It's non-standard and an app would have no clue if that is for the specific token, a user, a realm or a client. So it's meaningless.

**Comment by stianst** [comment]
Looking at the code for token response it seems adapters sets the deployment notbefore to whatever is in the token. That means it'll change randomly as different users with different not-before logs in.

**Comment by stianst** [comment]
This needs to have a bigger discussion on the mailing list to address this properly. From my POV the concept of setting notbefore policies on realms/clients/users is fairly broken, as there are no standard ways to communicate that to clients.

I will open a discussion on the mailing list

**Comment by stianst** [comment]
Actually found the root cause of this. nbf value is not explicitly set. It is however set to 0 by the fact that it's an int in JsonWebToken, while it should be an Integer which would result in it only being included in the token if actually set.

**Comment by diodfr** [comment]
I think I could close this PR according to your answers.
Thank you again for your amazing WORK.

**Pull request closed without merging**
