### PR TITLE
Outdated kcadm.sh help examples can be misleading to our users

### LINKED ISSUE #23402: Outdated kcadm.sh help examples can be misleading to our users
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/cli

### Describe the bug

The help instructions provided by kcadm.sh are out of date. Specifically, they instruct users to use the /auth/ path, which is no longer applicable in the most recent distributions of Keycloak. This can be misleading, as users often rely on these CLI help instructions for guidance.

### Version

22.0.3

### Expected behavior

Instructions with the updated URL. For example: http://localhost:9080

### Actual behavior

Instructions with out of date URL. For example: http://localhost:9080/auth

### How to Reproduce?

Run `./kcadm.sh config credentials` and help instructions with `http://localhost:9080/auth` and `http://localhost:8080/auth` will be printed.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by abstractj**
Closes #23402

### CODE REVIEW

**Comment by vmuzikar** [comment]
@shawkins Can you please review when you get a chance?

**Review by shawkins — APPROVED** [review]
LGTM, don't see any other references to /auth in the keycloak-client-cli-parent

**Review by vmuzikar — APPROVED** [review]
@abstractj Thank you! LGTM based on @shawkins' review.

I think it might be worth also backporting this.

**Comment by abstractj** [comment]
@vmuzikar done https://github.com/keycloak/keycloak/pull/23436

**Pull request merged**
