### PR TITLE
[KEYCLOAK-14282] Add filtering for GET /users endpoint for enabled/disabled users

### PR DESCRIPTION
**Pull request by kostoww**
Hello team Keycloak!
I've created a pull request to add additional filtering for users whether there are disabled on enabled. I hope i don't miss any tests. If everything seems ok I will create also documentation PR.
Thanks!

### CODE REVIEW

**Comment by pedroigor** [comment]
@kostoww Changes LGTM. The test failure is in your test case, probably because there is another user in the realm that you are not expecting when asserting the number of enabled users.

I would also add another test for using the different search parameters ("search", username, first, last names, etc).

**Comment by kostoww** [comment]
Hi, @pedroigor, 
Thank you for your notes, I tried to fix tests as you've mentioned, I hope now it's ok

**Comment by pedroigor** [comment]
@kostoww Sorry for the delay. Could you just rebase your branch? Other than that, it is good to go.

**Review by pedroigor — CHANGES_REQUESTED** [review]
@kostoww Sorry for the delay. Could you just rebase your branch? Other than that, it is good to go.

**Comment by pedroigor** [comment]
@kostoww There is a test failure here https://github.com/keycloak/keycloak/pull/7096/files#diff-0b313f9d585a39b2e3286f6fa414924eR645. Could you please check it out?

**Comment by kostoww** [comment]
Hi, @pedroigor 
I tried to fix the test, but I fail in part of rebasing the two commits.
I also fix one thing that was missed in the other PR that conflicts with my PR.

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@kostoww Thanks.

**Pull request merged**
