### PR TITLE
Upgrading Hibernate in line with WildFly 26.0.1.Final to support building Keycloak with OpenJDK 17

### LINKED ISSUE #9993: Make Keycloak Model Map JPA module JDK 17 ready
### Description

I built Keycloak using OpenJDK 17.0.2 and maven 3.8.4 (using `mvn clean install -DskipTests -Pdistribution` on latest main). The build failed for module `Keycloak Model Map JPA` with the following error:

```
[ERROR] Failed to execute goal org.hibernate.orm.tooling:hibernate-enhance-maven-plugin:5.3.20.Final:enhance (default) on project keycloak-model-map-jpa: Unable to enhance class: JpaRoleMetadata.class: Failed to enhance class org.keycloak.models.map.storage.jpa.role.entity.JpaRoleMetadata: Unsupported class file major version 61 -> [Help 1]
```
So atm a (not currently planned) update to use JDK17 as default would fail due to the Problem with the enhancer. So the enhancer needs to be updated i guess.

### Discussion

_No response_

### Motivation

Have an easy mid-term upgrade path to use more modern java versions.

### Details

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #9993

### CODE REVIEW

**Comment by ahus1** [comment]
I was waiting for this to run on the internal Jenkins pipeline to see that this change works on all databases.

**Comment by ahus1** [comment]
@sguilhen - I ran a build pipeline keycloak-build-pipeline/587 and test pipeline universal-test-pipeline-server/1347. The peid is cfe60c30.

The Oracle DB tests failed probably due to a DB not being available. Please have a look at the pipeline parameters and also the result - it's the first time I'm running this pipeline. Thanks!

**Comment by sguilhen** [comment]
Thanks @ahus1 . I'll take a look

**Comment by sguilhen** [comment]
Something funky happened in the pipeline, the migration tests were not executed and some of the db tests didn't run as well. I've triggered a rebuild to see how it goes.

**Comment by sguilhen** [comment]
Pipeline run: https://keycloak-jenkins.com/job/universal-test-pipeline-server/1351

**Review by sguilhen — APPROVED** [review]
Hibernate 5.3.24 is already productized internally and pipeline db_tests and db_migration_tests results are clean. Approving!

**Review by hmlnarik — APPROVED** [review]
Approving per @sguilhen 's approval

**Pull request merged**
