### PR TITLE
[KEYCLOAK-11712] - Request body not buffered when using body CIP in Undertow

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by pedroigor** [comment]
FYI, we had a similar change in Quarkus to fix the same issue. See https://github.com/quarkusio/quarkus/pull/5978.

**Review by mhajas — CHANGES_REQUESTED** [review]
Hi @pedroigor the PR is failing with app-server-wildfly. Wildfly adapter is using `ElytronHttpFacade` not `UndertowHttpFacade` by default. So we should probably adjust also `ElytronHttpFacade` to buffer inputStream properly.

**Comment by pedroigor** [comment]
@mhajas Thanks. Isn't the tests running in Travis? Wondering why I have an OK from Travis for this one.

**Comment by mhajas** [comment]
@pedroigor In Travis only auth server is running on wildfly, app server is on undertow.

**Comment by pedroigor** [comment]
@mhajas Tks. Good catch then ... I'll change elytron too.

**Comment by mhajas** [comment]
Thanks @pedroigor

**Review by mhajas — APPROVED** [review]
Tks @pedroigor, LGTM now.

**Comment by mhajas** [comment]
btw. @pedroigor should we create bug/enhancement issues also for other adapters?

**Review by stianst — APPROVED** [review]
Approving based on review from @mhajas

**Pull request merged**
