### PR TITLE
Introduce profile 'feature' for step-up authentication enabled by def…

### LINKED ISSUE #10315: Introduce Keycloak "feature" for step-up authentication
### Description

We may need to introduce "Feature" inside "Profile" class. The feature will be enabled by default (due it is enabled already in Keycloak 17), but administrator has possibility to disable it.

In case the feature is disabled, the `acr` claim in the ID Token will behave the same as before this feature was introduced (Hence returning 1 for "normal" authentication and 0 for SSO authentication). Otherwise "acr" claim will be filled according to the levels from the authentication flow, which user achieved.

As a follow-up to this, the protocol mapper will be introduced (See #10161) and hence there would be a chance that "acr" claim can be skipped from the token entirely. Or added by some other way by other protocol mapper (EG. userSessionNote as mentioned in #9344)

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by mposolda**
…ault

Closes #10315

### CODE REVIEW

**Comment by mposolda** [comment]
@mabartos @tnorimat Anyone of you has a chance to review this PR?

**Review by tnorimat — APPROVED** [review]
LGTM.

**Review by mabartos — APPROVED** [review]
@mposolda LGTM! Could you please attach here a PR to the documentation? The feature should be included in the list of profiles[1], right?

[1] https://www.keycloak.org/docs/latest/server_installation/#profiles

**Comment by mposolda** [comment]
@tnorimat @mabartos Thanks! The PR for the documentation is here https://github.com/keycloak/keycloak-documentation/pull/1428 . I've added you as a reviewer of this PR. This documentation PR contains various changes related to step-up authentication. It also contains changes related to protocol mapper and client scope https://github.com/keycloak/keycloak/issues/10161 , which I did not yet sent PR to the main codebase, but I am going to do that soon (will ask you again for the review of that).

**Pull request merged**
