### PR TITLE
[KEYCLOAK-8012] - Fix offline session support in authorization services

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by nqbao** [comment]
👍 this looks great. I hope this will be merged soon.

**Comment by mhajas** [comment]
@pedroigor missing tests. Here is the example how to restart server in tests [1], the same code should work also for wildfly.

[1] https://github.com/keycloak/keycloak/blob/777ac38d66fbb027d9a4225eb7e7506160aaa2e8/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/url/FixedHostnameTest.java#L141

**Comment by pdrozd** [comment]
@keycloak-ci-bot test keycloak-pr-pipeline-structured

**Comment by pedroigor** [comment]
@mhajas test is there

**Review by mhajas — APPROVED** [review]
@pedroigor Thanks

**Comment by stianst** [comment]
@mposolda would it not be better to make sessions have a method that can get the session regardless if it's online/offline? I've seen this messy code allover the place.

**Review by stianst — APPROVED** [review]
Approving this, but would be nice to get this cleaned up and make sessions() responsible for it

**Pull request merged**
