### PR TITLE
KEYCLOAK-1547 Need to use overridable removeUserSession() method.

### PR DESCRIPTION
**Pull request by ssilvert**
See https://issues.jboss.org/browse/KEYCLOAK-1547

### CODE REVIEW

**Comment by stianst** [comment]
This will significantly impact performance as you end up doing a call to the cluster to retrieve each session that is being removed. We can't add this.

**Comment by ssilvert** [comment]
I don't think it would have a significant impact.  Sessions doen't go away that often.

However, we could also make the internal version of removeUserSession() public.  That would allow subclasses to do the same thing without the extra call to getUserSession().  Is that acceptable?

**Comment by stianst** [comment]
Depends on idle timeouts and also how often the "garbage collection" task runs. If idle timeout is set low and garbage collection doesn't run to frequently there could be thousands of sessions to be removed each time it runs.

Making it public is a better option.

**Comment by stianst** [comment]
It should be protected, not public ;)

**Comment by ssilvert** [comment]
Yes, protected.  I'll resubmit the PR a little later today.

**Pull request closed without merging**
