### PR TITLE
KEYCLOAK-11201: Use snowpack instead of SystemJs.

### PR DESCRIPTION
**Pull request by ssilvert**
Note that we now require ESM module loading.  This meant that in addition to changing our build system to use Snowpack+Babel, we also had to get rid of the Axios and Moment libraries.

This actually had some advantages.  We are now using the standard "fetch" and "Intl.DateTimeFormat" libraries instead.  So we no longer have to download the two aforementioned libraries.

### CODE REVIEW

**Comment by ssilvert** [comment]
Successful UI tests run: https://keycloak-jenkins.com/job/keycloak-account2-matrix/892/

**Comment by vmuzikar** [comment]
@ssilvert I'll look in to it in the 2nd half of this week, is that ok? Thanks!

**Review by edewit — APPROVED** [review]
Can't wait :+1:

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@ssilvert In general looks good to me. I really like it! We no longer need manual filters for used JS files when building the dist, Welcome Screen displays much faster on slow connections, there are no longer hundreds of requests, ...

Just one thing. Could you please [update the licenses](https://github.com/keycloak/keycloak/blob/master/docs/dependency-license-information.md)? For sure we can remove SystemJS and add Babel, but there can be more.

Also, I'm not sure if this PR should be tracked under KEYCLOAK-11201, i.e. "Optimize network overhead". Paradoxically, the overhead not only did not improve improve but actually got slightly worse.
Did some measurements in Firefox with similar results in Chrome. Loaded Welcome Screen in a private window (which loads the whole app in the background).

Without Snowpack:
Screenshot 2020-05-12 at 15 53 35

With Snowpack:
Screenshot 2020-05-12 at 15 55 16

So should this have a different JIRA and should we solve the network overhead separately?

**Review by ASzc — COMMENTED** [review]
Make sure the maven product build is ok with the changes to package.json. I had a look, and I think it should handle it ok, but I haven't tried it myself. No js module changes should be expected in git since they're now downloaded at build time.

**Review by Aboullos — APPROVED** [review]
LGTM

Checking with the previous performance benchmarks, even though the resources size has increased, and the load time with it. 
The time for the page to be visible with the styles has decreased in some seconds. So for the user may look like the page is faster now, at least for the account console home page.

image

And as there is room for more optimization this could be a good aproach.

**Comment by ssilvert** [comment]
There are many opportunities for further optimization.  This PR gives us a better platform for making those optimizations.

As @vmuzikar showed, this PR dramatically reduces the number of requests while the total payload went up slightly.  The expected effect is that you should see better performance in loading where performance is bound by the browser's ability to serve simultaneous requests.  In the case where perf is bound by payload, you would see performance that is roughly the same.

I haven't done the math, but what I expected was to see better performance gain under high bandwidth because it is not so much bound by payload.  Under low bandwidth the performance gains would not be as much.

Going forward, we should be able to further reduce the number of requests but I think we can greatly reduce payload.  There is a lot of stuff in the current downloads that we really don't need.  An example is the icon library where we are only using a few of the icons.

Also, Snowpack has a great caching story.  Unlike with WebPack, where a single change to the app typically means you need to download the entire app, Snowpack lets you only download the files that have changed.  In other words, with Snowpack your code is already code-split in the right places for browser caching to be the most advantageous.

Therefore, the next thing @Aboullos will want to look at is performance after the initial first-load.  I'd be interested to see what the user experience is with an old cell phone on a slow connection.  If the initial load is at least tolerable, is the user experience genuinely good for every subsequent load?  And, is what I said above really true?  Does a single small change result in no noticeable change in load-time performance?

**Comment by vmuzikar** [comment]
@ssilvert Btw, regarding the cache. Not sure if modern (paranoid :D) browsers somehow clear the cache after a week or so, see Verified Partitioned Cache at https://github.com/keycloak/keycloak-pipeline/pull/257.

**Comment by edewit** [comment]
@vmuzikar we can still use a service worker to prevent that https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

**Comment by ssilvert** [comment]
> Just one thing. Could you please [update the licenses](https://github.com/keycloak/keycloak/blob/master/docs/dependency-license-information.md)? For sure we can remove SystemJS and add Babel, but there can be more.
> 

I was going to take care of this, but the tools to complete this task don't run on Windows. :-{

So we will do this as a separate task.  https://issues.redhat.com/browse/KEYCLOAK-14176

**Comment by abstractj** [comment]
@ssilvert where the licenses where updated as @vmuzikar requested? I couldn't find the files.

**Comment by ssilvert** [comment]
@abstractj Like I said above, we are handling that in a subsequent task.  The shell script needed to do it won't run on my box so I'm asking Erik to do it.

**Review by abstractj — APPROVED** [review]
Unfortunately, I won't be able to give it a try, but I'm approving taking into consideration how important it is to unblock the UI team, plus the fact that @Aboullos and @edewit did the review and also the evidence that Jenkins is happy.

**Comment by vmuzikar** [comment]
@ssilvert Btw, you can always use [WSL](https://docs.microsoft.com/cs-cz/windows/wsl/install-win10). 😉

**Review by stianst — APPROVED** [review]

**Review by stianst — APPROVED** [review]

**Pull request merged**
