### PR TITLE
KEYCLOAK-2720: Should not allow two groups with the same path.

### PR DESCRIPTION
**Pull request by ssilvert**

### CODE REVIEW

**Comment by stianst** [comment]
This is not strictly sufficient as theoretically it would be possible to add groups if added at the same time. It'll need a db constraint to make sure that doesn't happen.

**Comment by stianst** [comment]
Oh and where's the tests ;)

**Comment by ssilvert** [comment]
Pushed the unit test for this.  Not sure how to create the db constraint.  This is not a simple unique constraint because the rule is only that siblings can not have the same name.  The name column is not globally unique.  Also, not sure if this would need to be done for Mongo as well?

**Comment by stianst** [comment]
Can you not just add the following:

    <addUniqueConstraint columnNames="NAME,PARENT_GROUP,REALM_ID" constraintName="....." tableName="KEYCLOAK_GROUP"/>

+ The same for Mongo:

    ensureIndex("groupEntity", new String[]{"realmId", "name", "parentId"}, true, false);

**Comment by ssilvert** [comment]
I committed a constraint for JPA.  Unfortunately, this constraint doesn't work for top-level groups.  Those groups  have a null parent, which isn't considered to be a unique value.  It looks like to make this work for top-level groups we would need a default parent name like "root".  Or we could add some sort of a flag column.  Both solutions sound messy.

For Mongo, I'm held up because Mongo doesn't seem to be working with 2.3 and 2.4.  See https://issues.jboss.org/browse/KEYCLOAK-3878.  Perhaps this is something I'm doing wrong, but it works fine for me with 2.2.

**Comment by ssilvert** [comment]
I should also report that after my latest commit, the build failed.  The test that failed was SAMLKeyCloakServerBrokerWithSignatureTest.  It passed on my machine and it also passed when I restarted the build.  Looks like we might have an intermittent failure.

**Comment by ssilvert** [comment]
Looking at the JPA unique constraint problem a little more, we can't just add a default parent name.  The constraint is on a null entity instead of a null name.  We would need a "ghostly" default parent to serve as the super-parent entity.  This would be a parent of all top-level groups that exists in the database, but is never displayed.  That would likely cause even more problems.

It looks like the best solution is to add a flag column that tells if this is a top-level group.  I'm not liking that solution either as it seems ridiculous to add a new column just to check this constraint for top-level groups.  But right now I don't see any other solution.  

I'm tempted to leave it alone for now as that might do more harm than good.  Right now, the only way to create two top-level groups with the same name is to do it outside the REST API or for it to happen as you said as part of some scenario where it is "theoretically possible to add them at the same time".

**Comment by ssilvert** [comment]
Ugh!!  Mongo has similar problems dealing with the constraint.  It's probably easier to hack, but the hack is not very straightforward.

With Mongo, the constraint disallows any group name that is the same name as a top-level group.  BTW, the constraint looks like this:
ensureIndex("groups", new String[]{"realmId", "name", "parentId"}, true, false);

You need to use "groups" instead of "groupEntity".

I'm giving up on this.  If it's going to be fixed then it need to be done by someone who better understands the group code.  It would take me too much time to fix this without making a mess and I've spent too much time already.

Stian, we could commit what I've done so far.  It doesn't disallow every possible way to create a duplicate group name but it is an improvement.

**Comment by stianst** [comment]
@ssilvert Let's just do it simple and have the check purely in code. Seems like your PR does exactly that, but there's also a unique constraint being added. I assume that constraint doesn't actually work and should be removed?

**Comment by ssilvert** [comment]
The unique constraint for JPA does work except for top-level groups.  So that constraint is still useful if we want to keep it.  Also, it does no harm.

The mongo constraint does not work at all and I've already left it out.

We can merge what is here and at least get improvement.  But I understand if you'd rather leave out the JPA constraint and revisit the issue later.

**Comment by stianst** [comment]
Closing as I've sent https://github.com/keycloak/keycloak/pull/3670 that deals with conflicts

**Pull request closed without merging**
