### PR TITLE
KEYCLOAK-2641 Test servers

### PR DESCRIPTION
**Pull request by tkyjovsk**
This PR moves configurations of app-servers into the `integration-arquillian/servers` module so the servers can be prepared beforehand - independently on the test modules.

### CODE REVIEW

**Comment by tkyjovsk** [comment]
I'm sorry about the number of commits. I was trying several ways to squash them but wasn't able to do it because of big number of conflicts. (I unfortunatelly performed several merge commits in my branch from upstream/master in between my commits.)

**Comment by stianst** [comment]
We need these changes both in master and 1.9.x and I'm not going to accept a single change/PR with this amount of commits. So I'm afraid I'm going to have to insist that you find some way of squashing these changes into one commit.

**Comment by mstruk** [comment]
My advice is to never merge master into your working branch - always rebase
on top of latest master - to keep it clean for squashing, and merging back
to master.

**Comment by mstruk** [comment]
And what I do in situations like this is I create another branch off of
master, and then cherry-pick my working branch commits one by one in the
original order. May take a while but it gives me a nice clean branch which
I can then squash.

Maybe there's an easier way to achieve the same but I don't know it.

**Comment by tkyjovsk** [comment]
There was, actually. Backup testsuite folder outside of git workspace. Checkout clean branch. Restore testsuite state from backup. Commit.

**Pull request closed without merging**
