### PR TITLE
Add @JsonProperty annotation to PathCacheConfig.lifespan.

### LINKED ISSUE #9756: lifespan property in PathCacheConfig is missing @JsonProperty annotation
### Describe the bug

Reported in: https://issues.redhat.com/browse/KEYCLOAK-19520

[PolicyEnforcerConfig.PathCacheConfig](https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/representations/adapters/config/PolicyEnforcerConfig.java#L332) is missing `@JsonProperty` annotation that results in the following error when it is set for example, in Spring security yaml config file:

```
Property: keycloak.policy-enforcer-config.path-cache.lifespan
 Value: 10000
 Origin: class path resource [application.yml] - 71:17
 Reason: The elements [keycloak.policy-enforcer-config.path-cache.lifespan] were left unbound.
```

### Version

16.1.0

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

Use following yaml configuration:
```
policy-enforcer-config:
 enforcement-mode: ENFORCING
 path-cache:
   lifespan: 30000
``

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by StitzL**
Closes #9756.

### CODE REVIEW

**Comment by StitzL** [comment]
First-timer here - I'd really have loved to also submit a test together with this PR, but to be honest, I am a bit overwhelmed by the project's structure. If you think it's necessary for such a small change, please let me know where such a test would fit best.

**Review by mhajas — DISMISSED** [review]
Thank you and congratulation on your first contribution. Regarding the tests, currently, we don't have a lot of tests using SpringBoot applications so I am afraid this would be quite hard to test since it is failing only Spring. 

We have a [test](https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/example/authorization/LifespanAdapterTest.java#L79) using keycloak.json though, but I checked it and it works correctly. It seems Jackson is able to map the lifespan JSON field to the Java field without the annotation, but SpringBoot is not able to do this for some reason.

I am not sure the test using SpringBoot is worth adding at the moment as we are [deprecating](https://www.keycloak.org/2022/02/adapter-deprecation.html) it in favor of Spring Security. 

@pedroigor Could you please approve the GHA workflow and if it passes merge?

**Comment by pedroigor** [comment]
@mhajas @StitzL Thanks.

**Review by pedroigor — DISMISSED** [review]

**Comment by abstractj** [comment]
@StitzL could you please rebase? The changes look good, I just want to make sure our tests pass on CI.

**Comment by StitzL** [comment]
@abstractj I did - but it seems that rebasing invalidated the reviews previously performed, and thus locking the CI workflow again.

**Comment by abstractj** [comment]
@StitzL no problem, I can see that @mhajas and @pedroigor previously approved it.

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
