### PR TITLE
use login realm (#25466)

### LINKED ISSUE #22431: Localization: Admin UI doesn't pick up message bundles from realms other than master
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

I use the User Profile functionality and inside Admin UI -> Users -> User detail I should be able to provide translated names, but this only works for non-english locales.

### Version

22.0.1

### Expected behavior

I add a custom property in the User profile section with a translated name `${customAttribute}`, then I add a message bundle with the correct translations `users:customAttribute`. Then I should see my `users:customAttribute` value in the User details page.

### Actual behavior

I see `customAttribute` written there, but if I do the same procedure for eg. german, than it works!

### How to Reproduce?

1. Add a new custom attribute with name `customAttribute` in the user profile.
2. Add a displayname of `${customAttribute}`
3. Add a message bundle `users:customAttribute`
4. Look at a user profile

### Anything else?

As far as I can tell, there is a difference between how the english translation is handled and any other. 

After my procedure I see that the Admin UI is loading the translations from: http://localhost:8080/admin/realms/master/localization/en

But if I switch the language to german the translations are loaded from: http://localhost:8080/admin/realms/my-realm/localization/de

Or if I don't login through the master realm the english translations also work and are loaded from: http://localhost:8080/admin/realms/my-realm/localization/en

### PR DESCRIPTION
**Pull request by sschu**
Closes #22431
Backport to KC23 of #25466

Cherrypick of https://github.com/keycloak/keycloak/commit/914fd39dd3eb83cfedfba0ce5573edab59d9f34d

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]

**Comment by sschu** [comment]
Thanks for approving @jonkoops ! The test failures look unrelated to me. Should I also create a PR for KC22 since you marked the issue also for backport to 22?

**Comment by jonkoops** [comment]
Sure, go right ahead. I'll re-start the tests, that might shake it out.

**Comment by sschu** [comment]
I just checked the source code of 22 and the code looks pretty different (see https://github.com/keycloak/keycloak/blob/dca71d84c305cca0c3d3c988f3e81012951b1fcd/js/apps/admin-ui/src/i18n/i18n.ts#L47) .To me it looks like pulling in realm-specific translations wasn't even supported back then?

**Comment by jonkoops** [comment]
> To me it looks like pulling in realm-specific translations wasn't even supported back then?

It used to work differently, we had both these translations loaded from static files, and the call to load them from another endpoint. You can see the logic in the [`OverridesBackend`](https://github.com/keycloak/keycloak/blob/dca71d84c305cca0c3d3c988f3e81012951b1fcd/js/apps/admin-ui/src/i18n/OverridesBackend.ts), which is used here. I am not sure if the same kind of patch should be applied here, but indeed this one does not apply cleanly on top of that code.

**Comment by sschu** [comment]
@jonkoops 
I checked with 22.0.5. There it looks like translations are pulled from the login realm which is exactly the behavior this PR recreates for KC23. I still could not get the UI to correctly translate a user profile attribute name based on the translation, but maybe this didn't work back then? In any case, backporting this change here is not necessary for 22 and getting the user profile attribute translation to work is probably not worth it since it wasnt supported in 22 anyways.

**Comment by jonkoops** [comment]
Yeah, I think that we weren't localizing the UP attributes at that point yet. We can omit the backport for 22, I will remove the label.

**Pull request merged**
