### PR TITLE
fix exception when user does not have view-realm role

### LINKED ISSUE #23954: FederatedUserLink errors when user does not have view-realm role
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When viewing "Credentials" tab of a federated user in the admin console, if the currently authenticated user does not have `view-realm` role, admin console throws exception.

### Version

22.0.3

### Expected behavior

User credential is displayed

### Actual behavior

Error `Missing ":providerId" param` is displayed

image

Browser console shows error:

image

### How to Reproduce?

1. User is granted only `query-users` and `manage-users` roles of a realm
2. User logs into the realm's admin console UI
3. Search and opened a user in the realm (the user is a federated user)
4. Go to the "Credentials" tab

### Anything else?

`providerId` is a mandatory path parameter for federation route

https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/user-federation/routes/CustomUserFederation.tsx#L18

but `providerId` is not returned from `userStorageProvider.name()`

https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/user/FederatedUserLink.tsx#L29-L31
https://github.com/keycloak/keycloak/blob/main/js/libs/keycloak-admin-client/src/resources/userStorageProvider.ts#L7-L17

Potential fix - update `FederatedUserLink` to show plain text of provider name instead of link

### PR DESCRIPTION
**Pull request by jackie-linz**
Closes #23954

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]
LGTM

**Comment by thomasdarimont** [comment]
@jonkoops is this also a candidate for 22.0.5?

**Review by ssilvert — APPROVED** [review]

**Comment by ssilvert** [comment]
> @jonkoops is this also a candidate for 22.0.5 (release/22.0)?

@thomasdarimont I marked this for 22.0.6 as we are getting close to the release of 22.0.5.

**Comment by jonkoops** [comment]
@ssilvert I've removed the milestone from this PR, as there is already one on the linked issue. I also went ahead and created a backport for this, so we could still land this for 22.0.5 if you like: https://github.com/keycloak/keycloak/pull/24231

**Comment by jonkoops** [comment]
Thanks for landing this @jackie-linz!

**Pull request merged**
