### PR TITLE
KEYCLOAK-17693 add config for loading custom IdMapper class

### PR DESCRIPTION
**Pull request by Yang-Xie-OSS**
This is the continuation of KEYCLOAK-13745(#6968) and I completed the test.
I will complete the documentation later and will update the information here.

### CODE REVIEW

**Comment by Yang-Xie-OSS** [comment]
Here is the documentation of this feature.
[keycloak/keycloak-documentation/1151](https://github.com/keycloak/keycloak-documentation/pull/1151)

**Comment by Yang-Xie-OSS** [comment]
@mposolda 
Could you please take a look at this PR?
We want to use this feature in our project as soon as possible.
So if possible, we want this PR can be merged in keycloak 14.

**Comment by mposolda** [comment]
@Yang-Xie-OSS Thanks for the PR. I will try to take a look next week

**Comment by Yang-Xie-OSS** [comment]
@mposolda 
Hello!
What is the current situation? Sorry for asking you many times.
This feature is very important to our project.

**Comment by tnorimat** [comment]
@mposolda Hello, I know you might be busy for other tasks but could you or your team guys take a look to this PR?

**Review by mposolda — COMMENTED** [review]
@Yang-Xie-OSS @tnorimat Thanks and sorry for late response. The change itself is possible good, but I need to check in our internal pipeline if there is no regression in the adapter tests and all the server combinations are passing.

**Review by mposolda — CHANGES_REQUESTED** [review]
@Yang-Xie-OSS Is it possible to rebase this to latest master? Before that, I won't be able to run the tests in our pipeline.

**Comment by Yang-Xie-OSS** [comment]
@mposolda
I rebased it to latest master. And all checks seem to have passed. Could you please have a look?

**Comment by mposolda** [comment]
@Yang-Xie-OSS Thanks! This looks ok to me. I need to run our internal pipeline with all adapter tests for all the servers (GH actions do just basic checks). Will merge this once everything is ok.

**Review by mposolda — APPROVED** [review]
@Yang-Xie-OSS Thanks!

Pipeline run was successful: https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/575/

**Pull request merged**
