### PR TITLE
KEYCLOAK-5720 Fix X.509 tests

### PR DESCRIPTION
**Pull request by vmuzikar**

### CODE REVIEW

**Comment by hmlnarik** [comment]
@vmuzikar Should the tests be run in Travis? If the tests are those from `org.keycloak.testsuite.x509` package, they are not, and the [travis-run-tests.sh](https://github.com/keycloak/keycloak/blob/master/travis-run-tests.sh) needs update too. On the first sight it seems the best to add them to `server-group4`.

**Comment by vmuzikar** [comment]
@hmlnarik Good point. Well, since X.509 auth naturally requires SSL, we'd need to run it with `-Dauth.server.ssl.required` which is not yet supported in `travis-run-tests.sh`, am I correct?
Should we then add a new group with this switch? There are more tests in the base testsuite which require SSL (e.g. some CLI tests).

**Comment by hmlnarik** [comment]
@vmuzikar seems this should have been fixed with #4593 for wf (that is run in travis), so it might be time to enable these tests. But it seems just a related task that should not block merging this PR. If that would be fixed in a separate JIRA/PR, I'm all in.

**Comment by vmuzikar** [comment]
Agree. I've created a separate JIRA for running SSL tests in Travis: [KEYCLOAK-5793](https://issues.jboss.org/browse/KEYCLOAK-5793)

**Pull request merged**
