### PR TITLE
Address comments on Securing Apps

### LINKED ISSUE #27867: Corrections to Securing Apps Guide
### Description

Some minor corrections to allow reuse in downstream

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andymunro**
Closes #27867

### CODE REVIEW

**Comment by ahus1** [comment]
@andymunro - do you already have someone in mind to review this?

**Comment by ahus1** [comment]
Sure!

**Review by vaceksimon — APPROVED** [review]
LGTM!

**Review by ahus1 — APPROVED** [review]
Approving based on @vaceksimon's review. Thanks!

**Pull request merged**
