### PR TITLE
Fix GitHub Link for Deployment

### LINKED ISSUE #35947: Broken links in getting-started guide pointing to quickstarts latest branch
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

There are some broken links in getting started guide pointing to quickstarts `latest` branch, which don't exists anymore. Should be replaced with `main` branch. There are 2 links in `getting-started-kube.adoc` and 1 link in `getting-started-openshift.adoc` .

### Version

nightly (from 2024-12-16), 26, 24

### Regression

- [X] The issue is a regression

### Expected behavior

Working links

### Actual behavior

Links not working

### How to Reproduce?

See above

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by imjoseangel**
Update GitHub Link as it is referring to a release and not to a file. The release doesn't exist.

closes #35947

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you for raising this, there is definitely something wrong here. Please create a GitHub bug issue for this first, and link it here. 

It seems that the latest tag got missing here, and that this should be fixed in the release process. Maybe @jonkoops can have a look at this?

Just pointing to "main" might lead people to content that hasn't been released yet, so it is IMHO not be the link we want to see here.

**Comment by mposolda** [comment]
@imjoseangel Thanks for the PR.

@ahus1 I think the PR is correct . We don't have the `latest` branch in quickstarts anymore and the branch `main` is supposed to be the branch, which will have reference to the last version of released Keycloak server (and last version of keycloak-client and last version of node.js adapter etc).

**Review by mposolda — DISMISSED** [review]

**Comment by mposolda** [comment]
@imjoseangel There is another link in the same file `getting-started-kube.adoc` pointing to the quickstarts `latest` branch. Can you fix that one as well?

**Comment by imjoseangel** [comment]
Sure, I do it right now. Thanks!

**Comment by imjoseangel** [comment]
@mposolda Added. I also modified another link in the K8S KS

**Review by mposolda — APPROVED** [review]
@imjoseangel Thanks!

**Pull request merged**
