### PR TITLE
Add @JsonIgnore to SingleUseObjectKeyModel's getExpiration()

### LINKED ISSUE #31171: Single use tokens, like action tokens,  has a claim `expiration`
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When the return type of `getExp()` in org.keycloak.models.SingleUseObjectKeyModel was changed from an int to a Long, the old int behaviour was kept as a getter `getExpiration()` which has a default implementation to get the int value from `getExp()`.

This causes the JSON serialization to include the value from `getExpiration()` as a claim `expiration`. Since the `DefaultActionToken` extends `DefaultActionTokenKey` which implements `SingleUseObjectKeyModel`, a `expiration claim is now included in all action tokens.

### Version

25.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Action tokens should have a claim `exp` for expiration.

### Actual behavior

Action tokens has both  `exp` and `expiration` claims for expiration.

### How to Reproduce?

Use the forgotten password method and decode the reset password token. It has both `exp` and `expiration`.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by knutz3n**
Closes #31171

### CODE REVIEW

**Comment by ahus1** [comment]
cc: @mposolda & @pedroigor: FYI as this relates to the Core teams, and touches a PR https://github.com/keycloak/keycloak/pull/27715 you were involved earlier.

**Review by ahus1 — APPROVED** [review]
Thank you for this PR, this field shouldn't have ended up there :-( 
I'm marking it as a regression as this enlarges the tokens unnecessarily, which might be a problem for some users that go to the limits with their token lenghts.

**Comment by ahus1** [comment]
@knutz3n - could you please create the same PR against the release branch `release/25.0` as well, so we can include this fix in the next patch release of KC25. Thanks!

**Comment by knutz3n** [comment]
Thanks for the quick response on this.
I've created a PR https://github.com/keycloak/keycloak/pull/31184 against release/25.0 for this.

**Pull request merged**
