### PR TITLE
fix: adds securitycontext to the keycloak statefulset

### LINKED ISSUE #22527: Properly configure operator and statefulsets created by the operator wrt allowPrivilegeEscalation
### Description

The keycloak operator and statefulsets created by the operator should follow the guidelines:

https://access.redhat.com/solutions/7002730 

https://docs.openshift.com/container-platform/4.12/operators/operator_sdk/osdk-complying-with-psa.html#osdk-ensuring-operator-workloads-run-restricted-psa_osdk-complying-with-psa

to prevent openshift 4.11+ from issuing warnings - at least for now these are being logged at the debug level and may not be noticable.

### PR DESCRIPTION
**Pull request by shawkins**
closes #22527

### CODE REVIEW

**Review by vmuzikar — COMMENTED** [review]
Should this be rather set on the Operator deployment? Or also on the Operator deployment (alongside Operand deployment).

**Comment by shawkins** [comment]
> Should this be rather set on the Operator deployment? Or also on the Operator deployment (alongside Operand deployment).

@vmuzikar I had logged the issue as both, but the actual complaint from the original case was just about the operator pod logs, so I thought I'd take a look at that first.  

While this change could address that (granted fabric8 won't actually log warnings unless debug is enabled), in trying things out again on openshift 4.13, I don't see any warnings, or audit log entries, when directly reproducing https://access.redhat.com/solutions/7002730 or creating the pg instance either with oc or kubectl.

The default configuration is still as expected:
```
{
  "configuration": {
    "apiVersion": "pod-security.admission.config.k8s.io/v1beta1",
    "defaults": {
      "audit": "restricted",
      "audit-version": "latest",
      "enforce": "privileged",
      "enforce-version": "latest",
      "warn": "restricted",
      "warn-version": "latest"
    },
    "exemptions": {
      "usernames": [
        "system:serviceaccount:openshift-infra:build-controller"
      ]
    },
    "kind": "PodSecurityConfiguration"
  }
}
```
- which has warn on resticted.  Adding an explicit label to the namespace didn't change things either - still no logs.

So unless I'm missing something their were some changes in 4.13 in regards to how this is handled.  We could certainly put this off until it gets raised as an actual issue.

**Comment by vmuzikar** [comment]
@shawkins If no warnings are emitted any more, I'd maybe close this to not add unnecessary noise to our deployment definition, and wait if it becomes an issue again in the future.

WDYT?

**Comment by shawkins** [comment]
@vmuzikar sounds good to me.

**Pull request closed without merging**
