### PR TITLE
Support profile projection parameter for LinkedIn IDP (#13384)

### LINKED ISSUE #13384: LinkedIn profile picture
### Description

I would like to use the LinkedIn social login to get access to a user’s profile picture.
But the profile information endpoint used by KeyCloak does not return useable information about the profile picture.

### Discussion

_No response_

### Motivation

I would like to use the LinkedIn social login to get access to a user’s profile picture to enhance the user experience of my app by displaying the profile picture in the frontend alongside the username.

### Details

Currently, KeyCloak makes a request to "https://api.linkedin.com/v2/me" to retrieve user information from LinkedIn (see https://github.com/keycloak/keycloak/blob/8470a30446cf1a8280353fb96f8e2152d5d186ac/services/src/main/java/org/keycloak/social/linkedin/LinkedInIdentityProvider.java).
But this endpoint does not return a profile picture URL. Therefore, one cannot create a mapper to get access to the profile picture URL.

I would, therefore, like to recommend changing that endpoint to "https://api.linkedin.com/v2/me?projection=(id,firstName,lastName,profilePicture(displayImage~:playableStreams))". (As seen in the LinkedIn Docs https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin in the section “Retrieving Member Profile Picture”)

An authorized request to this endpoint returns all the information of the current endpoint and detailed information about the profile picture. Because of the complex response format of the "profilePicture" field it might also make sense to implement some sort of custom mapping logic to extract a useable URL.

Sample API Response (Anonymized):
```
{
    "firstName": {
        "localized": {
            "en_US": "{{FIRST_NAME}}"
        },
        "preferredLocale": {
            "country": "US",
            "language": "en"
        }
    },
    "lastName": {
        "localized": {
            "en_US": "{{LAST_NAME}}"
        },
        "preferredLocale": {
            "country": "US",
            "language": "en"
        }
    },
    "profilePicture": {
        "displayImage": "urn:li:digitalmediaAsset:{{URN_ID}}",
        "displayImage~": {
            "paging": {
                "count": 10,
                "start": 0,
                "links": []
            },
            "elements": [
                {
                    "artifact": "urn:li:digitalmediaMediaArtifact:(urn:li:digitalmediaAsset:{{URN_ID}},urn:li:digitalmediaMediaArtifactClass:profile-displayphoto-shrink_100_100)",
                    "authorizationMethod": "PUBLIC",
                    "data": {
                        "com.linkedin.digitalmedia.mediaartifact.StillImage": {
                            "mediaType": "image/jpeg",
                            "rawCodecSpec": {
                                "name": "jpeg",
                                "type": "image"
                            },
                            "displaySize": {
                                "width": 100.0,
                                "uom": "PX",
                                "height": 100.0
                            },
                            "storageSize": {
                                "width": 100,
                                "height": 100
                            },
                            "storageAspectRatio": {
                                "widthAspect": 1.0,
                                "heightAspect": 1.0,
                                "formatted": "1.00:1.00"
                            },
                            "displayAspectRatio": {
                                "widthAspect": 1.0,
                                "heightAspect": 1.0,
                                "formatted": "1.00:1.00"
                            }
                        }
                    },
                    "identifiers": [
                        {
                            "identifier": "{{PROFILE_PIC_URL_100x100}}",
                            "index": 0,
                            "mediaType": "image/jpeg",
                            "file": "urn:li:digitalmediaFile:(urn:li:digitalmediaAsset:{{URN_ID}},urn:li:digitalmediaArtifactClass:profile-displayphoto-shrink_100_100,0)",
                            "identifierType": "EXTERNAL_URL",
                            "identifierExpiresInSeconds": 1664409600
                        }
                    ]
                },
                {
                    "artifact": "urn:li:digitalmediaMediaArtifact:(urn:li:digitalmediaAsset:{{URN_ID}},urn:li:digitalmediaMediaArtifactClass:profile-displayphoto-shrink_200_200)",
                    "authorizationMethod": "PUBLIC",
                    "data": {
                        "com.linkedin.digitalmedia.mediaartifact.StillImage": {
                            "mediaType": "image/jpeg",
                            "rawCodecSpec": {
                                "name": "jpeg",
                                "type": "image"
                            },
                            "displaySize": {
                                "width": 200.0,
                                "uom": "PX",
                                "height": 200.0
                            },
                            "storageSize": {
                                "width": 200,
                                "height": 200
                            },
                            "storageAspectRatio": {
                                "widthAspect": 1.0,
                                "heightAspect": 1.0,
                                "formatted": "1.00:1.00"
                            },
                            "displayAspectRatio": {
                                "widthAspect": 1.0,
                                "heightAspect": 1.0,
                                "formatted": "1.00:1.00"
                            }
                        }
                    },
                    "identifiers": [
                        {
                            "identifier": "{{PROFILE_PIC_URL_200x200}}",
                            "index": 0,
                            "mediaType": "image/jpeg",
                            "file": "urn:li:digitalmediaFile:(urn:li:digitalmediaAsset:{{URN_ID}},urn:li:digitalmediaArtifactClass:profile-displayphoto-shrink_200_200,0)",
                            "identifierType": "EXTERNAL_URL",
                            "identifierExpiresInSeconds": 1664409600
                        }
                    ]
                },
                {
                    "artifact": "urn:li:digitalmediaMediaArtifact:(urn:li:digitalmediaAsset:{{URN_ID}},urn:li:digitalmediaMediaArtifactClass:profile-displayphoto-shrink_400_400)",
                    "authorizationMethod": "PUBLIC",
                    "data": {
                        "com.linkedin.digitalmedia.mediaartifact.StillImage": {
                            "mediaType": "image/jpeg",
                            "rawCodecSpec": {
                                "name": "jpeg",
                                "type": "image"
                            },
                            "displaySize": {
                                "width": 400.0,
                                "uom": "PX",
                                "height": 400.0
                            },
                            "storageSize": {
                                "width": 400,
                                "height": 400
                            },
                            "storageAspectRatio": {
                                "widthAspect": 1.0,
                                "heightAspect": 1.0,
                                "formatted": "1.00:1.00"
                            },
                            "displayAspectRatio": {
                                "widthAspect": 1.0,
                                "heightAspect": 1.0,
                                "formatted": "1.00:1.00"
                            }
                        }
                    },
                    "identifiers": [
                        {
                            "identifier": "{{PROFILE_PIC_URL_400x400}}",
                            "index": 0,
                            "mediaType": "image/jpeg",
                            "file": "urn:li:digitalmediaFile:(urn:li:digitalmediaAsset:{{URN_ID}},urn:li:digitalmediaArtifactClass:profile-displayphoto-shrink_400_400,0)",
                            "identifierType": "EXTERNAL_URL",
                            "identifierExpiresInSeconds": 1664409600
                        }
                    ]
                },
                {
                    "artifact": "urn:li:digitalmediaMediaArtifact:(urn:li:digitalmediaAsset:{{URN_ID}},urn:li:digitalmediaMediaArtifactClass:profile-displayphoto-shrink_800_800)",
                    "authorizationMethod": "PUBLIC",
                    "data": {
                        "com.linkedin.digitalmedia.mediaartifact.StillImage": {
                            "mediaType": "image/jpeg",
                            "rawCodecSpec": {
                                "name": "jpeg",
                                "type": "image"
                            },
                            "displaySize": {
                                "width": 800.0,
                                "uom": "PX",
                                "height": 800.0
                            },
                            "storageSize": {
                                "width": 800,
                                "height": 800
                            },
                            "storageAspectRatio": {
                                "widthAspect": 1.0,
                                "heightAspect": 1.0,
                                "formatted": "1.00:1.00"
                            },
                            "displayAspectRatio": {
                                "widthAspect": 1.0,
                                "heightAspect": 1.0,
                                "formatted": "1.00:1.00"
                            }
                        }
                    },
                    "identifiers": [
                        {
                            "identifier": "{{PROFILE_PIC_URL_800x800}}",
                            "index": 0,
                            "mediaType": "image/jpeg",
                            "file": "urn:li:digitalmediaFile:(urn:li:digitalmediaAsset:{{URN_ID}},urn:li:digitalmediaArtifactClass:profile-displayphoto-shrink_800_800,0)",
                            "identifierType": "EXTERNAL_URL",
                            "identifierExpiresInSeconds": 1664409600
                        }
                    ]
                }
            ]
        }
    },
    "id": "{{{LINKEDIN_ID}}}"
}
```

### PR DESCRIPTION
**Pull request by lexcao**
Closes #13384

### CODE REVIEW

**Review by sguilhen — COMMENTED** [review]
Considering the linked issue, this change does make sense to me. I will, however, ask for @pedroigor to review this as well since he was in charge of updating the endpoint URLs for LinkedIn.

**Comment by sguilhen** [comment]
Another thought: the profile picture might be optional in the sense that most users won't really want to retrieve it and it significantly increases the data payload, so perhaps we should consider adding a configuration for the linked in provider factory and only use this "decorated" endpoint if the config explicitly tells the provider that it is needed?

**Comment by lexcao** [comment]
Hi, @sguilhen 
Thanks for your suggestion.
I am going to add them.

**Comment by lexcao** [comment]
Hi, @sguilhen 
I just made an update.
The screenshot shows what I implemented.
There is an input for customizing the `projection` parameter to profile requests.

image

**Comment by sguilhen** [comment]
@lexcao Thanks for the changes, I personally like the code better with the projection being configurable.

One thing I have to point out is that we shouldn't be making changes to the legacy console, and any UI changes should be directed at the new console. @ssilvert Can you provide some directions for adding a new config for the `LinkedIn` social provider?

I also believe we will have to amend the server documentation with a brief explanation of the projection config.

**Comment by lexcao** [comment]
Hi, @sguilhen 
I am glad you like the changes.
So, do I need to remove the changes on the `.ftl` file to the legacy console?

Sure, I think I need some directions for updating the new console UI.

Here is the document PR:
https://github.com/keycloak/keycloak-documentation/pull/1654

**Comment by ssilvert** [comment]
> Hi, @sguilhen I am glad you like the changes. So, do I need to remove the changes on the `.ftl` file to the legacy console?
> 
I'm fine with the changes to the legacy console.

As for the new console, we haven't implemented the extension mechanism for social providers yet.  But I will make sure we take care of that soon, including your changes here.  So you don't have to worry about it.  The UI team can do these changes.

**Review by ssilvert — DISMISSED** [review]

**Comment by ssilvert** [comment]
New admin console issue: https://github.com/keycloak/keycloak-admin-ui/issues/3089

**Comment by sguilhen** [comment]
Thanks, @ssilvert !

**Comment by lexcao** [comment]
Hi, @sguilhen 
Could you please help me with the failed tests?
I just found these logs, that help me nothing.

```
WARN: WFLYPRT0018: No such request (9) associated 
with channel Channel ID 8a95d74e (outbound) of Remoting 
connection 6bca7af5 to localhost/127.0.0.1:10090 of endpoint "cli-client" <6f7a2a5>

---

Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:
1.2.2.Final:execute-commands (add-spi-configurations) 
on project provider-action-token-authenticator: Execution add-spi-configurations of 
goal org.wildfly.plugins:wildfly-maven-plugin:1.2.2.Final:execute-commands failed: 
Command execution failed for command ':reload'. Communication error: 
java.util.concurrent.CancellationException: Operation was cancelled -> [Help 1]
```

**Comment by sguilhen** [comment]
@abstractj can you re-run the quickstarts tests for this PR? I don't think the failure is related

**Comment by sguilhen** [comment]
@abstractj I think the social login test covers the common config - it might be good to check if it is possible to enhance the LinkedIn test to include testing a config that uses the new attribute.

**Comment by lexcao** [comment]
Hi @sguilhen 
I found it depends on `social.config` to run the `SocialLoginTest`.
What should I do to add that testing?

I am wondering if a test for `getUserInfoUrl` would fit the need?

**Review by ssilvert — DISMISSED** [review]

**Comment by ssilvert** [comment]
I approve the changes to the old admin UI.

@hmlnarik @abstractj We are ready with changes to the new UI whenever you want to approve and merge this PR.
https://github.com/keycloak/keycloak-ui/pull/3190

**Comment by sguilhen** [comment]
> Hi @sguilhen I found it depends on `social.config` to run the `SocialLoginTest`. What should I do to add that testing?
> 
> I am wondering if a test for `getUserInfoUrl` would fit the need?

Hi @lexcao - you are right, the test relies on the `social.config` system property that points to a properties file containing the social config (see [README](https://github.com/keycloak/keycloak/blob/090f7f89d58738675d77e7306411087af4c25230/testsuite/integration-arquillian/HOW-TO-RUN.md#social-login))

In this case, I would expect something similar to the `SocialLoginTest.facebookLoginWithEnhancedScope` where you would enhance the common test to include an attribute mapper for, say, the profile picture, and check if the mapped value is there. Run this locally, with your own `social.config`, and if that works we can update our pipelines config so the test runs in the internal pipelines as well.

**Comment by sguilhen** [comment]
> Run this locally, with your own `social.config`, and if that works we can update our pipelines config so the test runs in the internal pipelines as well.

Perhaps a better approach yet, change the `buildIdp` method in `SocialLoginTest` to include the `projection` config if the provider is `LINKEDIN_WITH_PROJECTION`  (this enum type would need to be added at the beginning). Then add a mapper for it and check the result (much like what happens with the facebook login with birthday).

**Comment by lexcao** [comment]
Hi, @sguilhen 
Thanks for your kind advice.
I have added the `linkedinLoginWithProjection` test.

Currently, I have not tested from my local.
It is hard to run the test from my local, but I will figure it out later.

**Comment by jonkoops** [comment]
Looks like some of the test are failing, not sure if this is just flaky or actually an issue.

**Comment by jonkoops** [comment]
@ssilvert @sguilhen could y'all take another look at this?

**Comment by ssilvert** [comment]
@sguilhen @abstractj Can we get this one wrapped up?  The UI team is waiting for this to be merged so we can merge our changes to the new admin console.

**Review by abstractj — COMMENTED** [review]
@ssilvert even though I didn't have the time to experiment the changes proposed here, reading through the code it seems to me that the integration tests look good. I will wait for @sguilhen's approval and technical review before merging it.

**Comment by sguilhen** [comment]
I couldn't get the new test to pass for me locally. I've created a test app on Linked In, configured a `social.properties` for the test with the app's credentials and my own Linked In account credentials and the test failed.

The regular `linkedinLogin` test passes, but the new one fails:

```
[ERROR] org.keycloak.testsuite.broker.SocialLoginTest.linkedinLoginWithProjection  Time elapsed: 21.165 s  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.keycloak.testsuite.broker.SocialLoginTest.assertAttribute(SocialLoginTest.java:530)
	at org.keycloak.testsuite.broker.SocialLoginTest.linkedinLoginWithProjection(SocialLoginTest.java:402)
```

I've done some debugging and the projection URL is correctly being used by the new test, but the JSON response is not different than the one I got from the test without projection. They both look like this:

```
{
    "localizedLastName" : "Guilhen",
    "profilePicture": {
        "displayImage": "urn:li:digitalmediaAsset:C5603AQECwmHU2SZvDA"
    },
    "firstName": {
        "localized": {
            "en_US": "Stefan"
        },
        "preferredLocale": {
            "country": "US",
            "language": "en"
        }
    },
    "lastName": {
        "localized": {
            "en_US": "Guilhen"
        },
        "preferredLocale": {
            "country": "US",
            "language": "en"
        }
    },
    "localizedFirstName": "Stefan"
}
```

So I don't know if there's some config missing on my part because the response is the same with or without projection, or if there's something else going on. Technically it looks right to me but I couldn't figure out a way to make the test pass.

**Review by sguilhen — CHANGES_REQUESTED** [review]
I was finally able to run the test successfully after fixing a bug in the `LinkedInIdentityProvider`. Line 93 needs to updated:

https://github.com/keycloak/keycloak/blob/148c7695ff5b32f46f05a5f341ca5456da144987/services/src/main/java/org/keycloak/social/linkedin/LinkedInIdentityProvider.java#L93

to

```
 BrokeredIdentityContext identity = extractIdentityFromProfile(null, doHttpGet(getConfig().getUserInfoUrl(), accessToken)); 
```
Without this change, the projection parameter was never used in the HTTP request.

**Comment by lexcao** [comment]
Hi, @sguilhen 
Thanks for your kind help.
You are right, I just forgot to check `PROFILE_URL` and the lack of integration test on my local. 
I have replaced all `PROFILE_URL` to `getConfig().getUserInfoUrl()`.
Please review it again.
Thank you!

**Review by sguilhen — DISMISSED** [review]

**Review by sguilhen — APPROVED** [review]

**Pull request merged**
