### PR TITLE
Prevent EntityNotFoundException when ID doesn't exist in the DB

### LINKED ISSUE #21866: JPA Map store delete throws an entity not found exception when ID is gone
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

I've been switching in my tests between old and new JPA store, and when trying to log in to the new store, I received an exception which was caused by the AuthenticationSession ID presented by the client was not being able to be removed, because the ID was a legacy store. 

### Version

nightly

### Expected behavior

Any other store than the JPA map store would simply return if the entity doesn't exist. I would expect the same from the JPA map store.

### Actual behavior

The JPA store threw an EntityNotFoundException

### How to Reproduce?

* Start an authentication session with the old store
* Start Keycloak with the new JPA store
* Refresh the login screen -> error is shown

### Anything else?

I'll create a PR for this

### PR DESCRIPTION
**Pull request by ahus1**
This makes the behavior consistent with the other store implementations.

Closes #21866

### CODE REVIEW

**Comment by ahus1** [comment]
@vramik - as you've been working with the new JPA Map store quite a bit, I'd be happy if you could review this if you have the time. If not, let me know and I'll search for a different reviewer. Thanks!

**Review by vramik — APPROVED** [review]
Thank you @ahus1 for the PR

**Comment by ahus1** [comment]
@mhajas - please merge this PR when you have the time. Thanks!

**Review by mhajas — APPROVED** [review]
Approving per @vramik 's approval

**Pull request merged**
