### PR TITLE
[KEYCLOAK-11160] - adds "optional" as fallback for conditional OTP

### PR DESCRIPTION
**Pull request by tpohl**
This PR implements the functionality described in KEYCLOAK-11160 and shows what we implemented in our SSO Instance.

To be honest, I did not figure our how to run the Integration Tests successfully 🤷.

### CODE REVIEW

**Review by abstractj — CHANGES_REQUESTED** [review]
@tpohl thanks for submitting this PR, but all the tests are failing. I'd appreciate if you read our https://github.com/keycloak/keycloak/blob/master/CONTRIBUTING.md with the instructions about how to run the integration tests and update your PR.

**Comment by tpohl** [comment]
Hi, thank you. I will check, what went wrong and update the PR.

**Comment by tpohl** [comment]
I think I almost got the test working.  - Sorry for the trouble...

The test is currently passing if started alone and failing (on the before setup)  if run together with the other tests, so there must be some kind of left-overs from the other tests. 

I will check again tomorrow.

**Comment by tpohl** [comment]
Hey @abstractj , I have finally got the tests working. There were some interferences, which I cut by moving the tests to another TestClass (and creating a new AbstractCustomAuthFlowOTPTest Class to hold all the shared functionality) - This is why you see so many changes in the Test Sources.

**Comment by stianst** [comment]
Why not just extend the current test and add a testcase? It's pretty hard to review as it is now

**Comment by tpohl** [comment]
Unfortunately this cannot work as the user's settings are not cleared 100% when I add the Test to the existing Class.

When I was thinking about it, I thought it would be the cleanest solution to add an abstract BaseClass holding shared functionality and have both the existing and the new Test use it. 
It also looks to me to be similar to what you have been doing in the past.

Can I help somehow?

**Comment by stianst** [comment]
What we do elsewhere is that we set a sensible shared config for all testcases within the class, then we allow making tweaks for individual testcases. This is a lot more efficient and easier to maintain than what you have done here. It's a bit of overhead for each class as there's a lot more that needs tearing down and re-doing.

**Comment by abstractj** [comment]
@tpohl would you like to move forward with this PR? If yes, I suggest to do the changes that @stianst requested.

**Comment by mposolda** [comment]
One side note to this: There is currently some work in progress related to refactoring of authentication flows. The details here: https://github.com/keycloak/keycloak-community/blob/master/design/multi-factor-admin-and-step-up.md . 

Among other things, there will be built-in support for conditional authenticators, so you will be able to specify that for example OTPAuthenticator will be triggered just under certain conditions. Regarding this, we may remove ConditionalOTPAuthenticator in the future entirely. Just a heads-up that this PR may become obsolete after that. So it's the question whether to invest more time to it.

**Comment by stianst** [comment]
Closing this due to lack of feedback from contributor around the test, also things will change with new auth flow.

**Comment by tpohl** [comment]
Hi, I am sorry that I could not reply as I was on vacation. Nevertheless I agree that, if the whole auth flows are refactored, this PR can be closed.

**Pull request closed without merging**
