### PR TITLE
Quarkus

### PR DESCRIPTION
**Pull request by bb-matthewc**
Migration to Quarkus.

To build:
mvn -pl server-quarkus -am clean install

Uberjar will be created in server-quarkus/target

### CODE REVIEW

**Comment by stianst** [comment]
Thanks. I see you used merge rather than rebase. The ideal would be a rebase as otherwise we'll have a headache merging this back into Keycloak. Aim is to soonish be able to have this in master repo. We'll need some clean way of doing that though.

**Comment by stianst** [comment]
Ideal would be if we maintain a clean branch with clean commits that we can eventually merge back into master. As this is a feature branch we can have multiple commits, but should be cleaned up a bit. We'll also need to rebase from time to time as using merge makes it very hard to get back into master.

**Comment by pedroigor** [comment]
As you mentioned, we need a rebase. In addition to that, we can have all changes done after your first commit in a single commit. As an initial step.

@bb-matthewc, I can do the work for you if you want to.

**Review by pedroigor — COMMENTED** [review]
@stianst @bb-matthewc overall, these changes are pretty much what I was doing to get something work.

I have only a few concerns such as how we are changing dependencies and the possibility to have an extension instead of just a Quarkus application.

However, I would vote for merging this as-is once the PR is properly rebased. It is a great start.

Thanks again @bb-matthewc and @jonm-bb.

**Comment by bb-matthewc** [comment]
@pedroigor Thanks!

Will fix the rebase issue, that was my bad sorry.

**Comment by stianst** [comment]
Thanks @bb-matthewc can you also squash to a single commit?

**Comment by bb-matthewc** [comment]
Will close this off and fix up now.

**Pull request closed without merging**
