### PR TITLE
Upgrade Groovy dependencies to latest version

### PR DESCRIPTION
**Pull request by jonkoops**
Upgrades the Groovy dependencies to the latest version, which makes the build for the `licenses-processor` plugin compatible with Java 17 targets.

### CODE REVIEW

**Review by ASzc — APPROVED** [review]
Seems ok, as far as I can tell there's no difference to the licenses plugin jar as a result of this PR. I'll note though that the licenses plugin has been out of use for a long while, so I don't know how functional it is generally

**Comment by jonkoops** [comment]
> I'll note though that the licenses plugin has been out of use for a long while, so I don't know how functional it is generally

Yeah, @stianst is working on a new version, so this code will likely go away in the future. This PR is to ensure everything is Java 17 compatible in the mean time.

**Comment by ahus1** [comment]
How would you run this plugin / how can I test it? I also would like to understand the current problem / failure (I don't see a linked issue).

**Comment by jonkoops** [comment]
> How would you run this plugin / how can I test it? I also would like to understand the current problem / failure (I don't see a linked issue).

The failure occurs only when you start setting up the project to use Java 17 by default everywhere (see #29927). Groovy is used for the [`licenses-processor`](https://github.com/keycloak/keycloak/tree/e1418c1bbb78346d0e68c932d11eda83fc3be52b/distribution/maven-plugins/licenses-processor), when compiled with Java 17 the Groovy plugin will complain about an unknown compiler target version.

I did not link any issue, as the failure does not occur in `main`, so this is just a simple dependency upgrade.

**Comment by ahus1** [comment]
Thank you for adding the context. The reason I was looking for the issue was that I was lacking the context here. Even if there is nothing failing in main, are allowed to create an issue first :-)

**Review by ahus1 — APPROVED** [review]

**Pull request merged**
