### PR TITLE
password is a required field

### LINKED ISSUE #33967: password is a required field
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

In `themes/src/main/resources/theme/keycloak.v2/login/register.ftl`, if `passwordRequired` is set, then password is a required field. The html should reflect that. In most (all?) themes, required fields are indicated with an "*".

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Password to be required and indicated with an "*".

### Actual behavior

Passwords don't have the required property, and are not indicated with an "*".

### How to Reproduce?

Open the registration form. The password fields are not marked with an "*" and lack the html-required-property.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by petski**
Closes https://github.com/keycloak/keycloak/issues/33967

### CODE REVIEW

**Comment by jonkoops** [comment]
Hi @petski, thanks for your PR. Could you log an issue and link it to this PR? We need this so we can track changes and build a changelog for releases. Thanks!

**Comment by petski** [comment]
@jonkoops done. See #33967

**Review by agagancarczyk — APPROVED** [review]

**Comment by ahus1** [comment]
Thank you for your contribution. It will be part of the Release KC 26.1. If you want this to be part of an earlier release, please create a backport PR against the `release/26.0` branch.

**Comment by jonkoops** [comment]
Backport for v26 is up under #33984

**Pull request merged**
