### PR TITLE
Export import realm with organizations

### LINKED ISSUE #30006: Export and import organizations
It should be possible to export a realm and their organizations as well as import it back in the same state.

Should also fix https://github.com/keycloak/keycloak/issues/29693.

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #30006

### CODE REVIEW

**Review by vramik — COMMENTED** [review]
Thank you @pedroigor. I have few questions

- Is it ok to re-genarate the IDs of the organization upon export/import?
- What happens with the org when groups are not included into partial export?
- AFAIK we have to support import of export done in previous version. I guess it means we aim to provide a migrator in case of a need (e.g. when data structure changes), correct?

**Comment by pedroigor** [comment]
@vramik Updated the PR to ignore partial exports for organizations and added test to make sure you can at least import.

The partial export/import was actually broken and missing setting up the session context when running partial import.

**Comment by vramik** [comment]
> Yes, I don't see why not. Or do you have something else in mind?

It's really the question how it should behave. E.g. for most of other objects we preserve the IDs when exporting/importing: please see https://github.com/keycloak/keycloak/blob/d1756564a7f3e40897ac3afeabe7eedc5c410c2d/server-spi/src/main/java/org/keycloak/models/RealmProvider.java#L30-L45 and https://github.com/keycloak/keycloak/blob/d1756564a7f3e40897ac3afeabe7eedc5c410c2d/services/src/main/java/org/keycloak/services/managers/RealmManager.java#L519-L524 so I was wondering whether we need to keep the IDs not.

> I've no idea as I did not check partial export. I'll check it out and probably ignore organizations in partial export/import.

+1

> Can you elaborate? We have not yet released organizations not sure what you mean by "supporting import of export done in previous versions"?

I thought that you should be able to import the data exported in previous version. So e.g. when you export a realm from version 25 to a file, you should be able to successfully import it in future versions. I believe there is this method for this purpose: https://github.com/keycloak/keycloak/blob/82beee607ea22e9808cf4533127cc0f080de57b9/server-spi-private/src/main/java/org/keycloak/migration/migrators/Migration.java#L44
The organization feature should be enabled by default (in `PREVIEW`), therefore you will have organizations present the exported file. I assume we should allow to import it back in kc26. I am just wondering what is expected behavior in this case. Do we aim to provide a migration (if needed) for keycloak 26? I hope it make sense what I meant by "supporting import of export done in previous versions" now.

**Comment by pedroigor** [comment]
> > Yes, I don't see why not. Or do you have something else in mind?
> 
> It's really the question how it should behave. E.g. for most of other objects we preserve the IDs when exporting/importing: please see
> 
> https://github.com/keycloak/keycloak/blob/d1756564a7f3e40897ac3afeabe7eedc5c410c2d/server-spi/src/main/java/org/keycloak/models/RealmProvider.java#L30-L45
> 
> and
> https://github.com/keycloak/keycloak/blob/d1756564a7f3e40897ac3afeabe7eedc5c410c2d/services/src/main/java/org/keycloak/services/managers/RealmManager.java#L519-L524
> 
> so I was wondering whether we need to keep the IDs not.

Let's keep without ids and just use the natural identifiers we already have. Exposing such internal identifiers is not a good thing for several reasons:

* Block us from changing the format we use in our ids. We had issues in the past around this.
* Suggest that people can use those ids to reference data into their applications but they shouldn't. Instead, favor using natural identifiers da uniquely identify an entity

> > I've no idea as I did not check partial export. I'll check it out and probably ignore organizations in partial export/import.
> 
> +1
> 
> > Can you elaborate? We have not yet released organizations not sure what you mean by "supporting import of export done in previous versions"?
> 
> I thought that you should be able to import the data exported in previous version. So e.g. when you export a realm from version 25 to a file, you should be able to successfully import it in future versions. I believe there is this method for this purpose:
> 
> https://github.com/keycloak/keycloak/blob/82beee607ea22e9808cf4533127cc0f080de57b9/server-spi-private/src/main/java/org/keycloak/migration/migrators/Migration.java#L44
> 
> 
> The organization feature should be enabled by default (in `PREVIEW`), therefore you will have organizations present in the exported file. I assume we should allow to import it back in kc26. I am just wondering what is expected behavior in this case. Do we aim to provide a migration (if needed) for keycloak 26? I hope it make sense what I meant by "supporting import of export done in previous versions" now.

Sorry, I might be missing something. But still don't see why we need to address migration now as we are releasing the feature for the very first time.

**Review by sguilhen — APPROVED** [review]
LGTM but let's wait for Vlasta's input as he was the original reviewer.

**Review by vramik — APPROVED** [review]
Thank you @sguilhen. Approving based on Stefan's review.

**Review by ahus1 — APPROVED** [review]
Approving based on @sguilhen's and @vramik's review.

**Comment by danielwegener** [comment]
Uhm is it just me that using the cli full export , organizations with memberships (referencing usernames) would be exported as part of the realm.json 
and users exported within the users-0.json?
If I try to import it again, it would fail, because the realm json is then referencing yet unimported users and the start would fail

**Pull request merged**
