### PR TITLE
Store index data in memory instead of persistent store to make it con…

### LINKED ISSUE #15653: Make Infinispan index data stored in memory to be consistent with cached data
Currently, we store Infinispan index data in storage, while caching data in memory. We should make this consistent, probably by moving index to memory using in cache configuration:
```xml
<indexing storage="local-heap">
```

### PR DESCRIPTION
**Pull request by mhajas**
…sistent with cached data

Closes #15653

### CODE REVIEW

**Comment by mhajas** [comment]
I also updated Q&A discussion to document this change: https://github.com/keycloak/keycloak/discussions/12010

**Comment by martin-kanis** [comment]
> I also updated Q&A discussion to document this change: #12010

ISPN docs also states: `You should store indexes in JVM heap memory only for small datasets.` Shouldn't we also state this warning somewhere?
Also I'm concerned what "small" actually means and whether some of our areas can be too large for this setup.

**Review by martin-kanis — APPROVED** [review]
Approving per our offline discussion. @mhajas Will you create a follow-up issue to investigate the performance characteristics and memory consumption of both approaches?

**Review by hmlnarik — APPROVED** [review]
Approving per @martin-kanis 's approval. Please only merge after the follow-up issue is created

**Comment by mhajas** [comment]
@martin-kanis @hmlnarik I added it into the description of the HotRod benchmarking issue: #17573 . is it ok there or do we want to have a separate issue for that? Please let me know and I will update it accordingly.

**Comment by mhajas** [comment]
That makes sense @hmlnarik, I created a new issue: #17615

**Pull request merged**
