### PR TITLE
KEYCLOAK-1195 - added identity brokes ordering for login page

### PR DESCRIPTION
**Pull request by velias**

### CODE REVIEW

**Comment by velias** [comment]
Hi @stianst , looks I'm in conflict with your work on KEYCLOAK-1187. Can I rebase and resolve the conflict now, or should I wait until you finalize your work?

**Comment by stianst** [comment]
Now is a good time. I didn't merge it before as it failed on travis.

**Comment by velias** [comment]
OK, going to rebase it now. 
Seems travis build failed due some external reasons, not due problem with code :-(

**Comment by velias** [comment]
@stianst build is OK now

**Pull request merged**
