### PR TITLE
Make ProofType a string instead of enum

### LINKED ISSUE #30999: Make ProofType for CredentialRequest a string instead of enum
### Description

The class `org.keycloak.protocol.oid4vc.model.ProofType` should hold `String` constants instead of being an enum.

relatesTo #30875

### Discussion

_No response_

### Motivation

Enums are a bad choice for type-selection because it limits the extensibility for custom-data-formats if other formats are required.

### Details

_No response_

### PR DESCRIPTION
**Pull request by Captain-P-Goldfish**
enum-types are a bad choice because it limits the extensibility of the API

fixes #30999
relatesTo #30875
relatesTo #26328

### CODE REVIEW

**Comment by mposolda** [comment]
@wistefan @tnorimat Anyone of you available to review this PR please?

**Comment by tnorimat** [comment]
@mposolda Hello, I will review the PR.

**Review by tnorimat — APPROVED** [review]
LGTM.

**Review by mposolda — APPROVED** [review]
@Captain-P-Goldfish @tnorimat Thanks for the PR and review!

**Pull request merged**
