### PR TITLE
Added "secure-redirect-uris-enforcer" executor to FAPI 1.0 client profiles

### PR DESCRIPTION
**Pull request by kmzs**
fixes https://github.com/keycloak/keycloak/issues/29341

### CODE REVIEW

**Comment by tnorimat** [comment]
@mposolda I would like to check whether this modification can pass [fapi1-advanced](https://github.com/keycloak/kc-sig-fapi) 
 and its related conformance tests. Could you wait for the result of the tests ? It takes some time.

**Comment by tnorimat** [comment]
@mposolda I used keycloak 24.0.5 with adding "secure-redirect-uris-enforcer" executor to FAPI 1.0 client profile. Then, I ran fapi1-advanced conformance tests against it. I found that some tests fails, so that this keycloak could not pass fapi1-advanced conformance test.

I do not have enought time to investigate it.

As a workaround, we can add a new profile including only "secure-redirect-uris-enforcer" executor and apply both the global profile for fapi and this profile.

**Comment by mposolda** [comment]
@tnorimat Thanks for checking FAPI tests! My vote is to not introduce any additional profile.

@kmzs Could you please try to run our FAPI tests from https://github.com/keycloak/kc-sig-fapi in your environment and investigate why the test is failing with your change? Maybe it is just some configuration of `secure-redirect-uris-enforcer`, which can help here to make it working. Just a note that we cannot accept the PR if FAPI tests are failing with this change.

**Comment by mposolda** [comment]
@kmzs Closing the PR as there is no additional feedback to last comments. Please re-open just in case that you are able to addresss review comments and make FAPI testsuite passing with your changes.

**Pull request closed without merging**
