### PR TITLE
KEYCLOAK-3977 fix logicalFilePath for jpa-changelog-1.0.0.Final-db2.xml

### PR DESCRIPTION
**Pull request by vramik**

### CODE REVIEW

**Comment by stianst** [comment]
What's the logicalFilePath used for? I can't see a file called 'db2-jpa-changelog-1.0.0.Final.xml'

**Comment by vramik** [comment]
It is the reference to previous file name. In previous version of keycloak there was https://github.com/keycloak/keycloak/blob/2.3.0.Final/model/jpa/src/main/resources/META-INF/db2-jpa-changelog-1.0.0.Final.xml and liquibase uses logicalFilePath to link files (previous with renamed) to be able to decide whether the changelog was or wasn't be applied on the database.

**Comment by stianst** [comment]
@hmlnarik  can you review and comment on this PR please?

**Comment by stianst** [comment]
@vramik I assume you're right, but I've got no clue ;)

**Comment by hmlnarik** [comment]
@stianst :+1: from me, it is a correct fix

**Pull request merged**
