### PR TITLE
KEYCLOAK-13397 Creating role-ldap-mapper for realm-management client …

### PR DESCRIPTION
**Pull request by mposolda**
…id in ldap user federation fails - alternative

### CODE REVIEW

**Comment by mposolda** [comment]
Created the alternative (better) approach to the https://issues.redhat.com/browse/KEYCLOAK-13397 .

Manually tested those scenarios:
- Create and update of the LDAP role mapper with "Client ID" configuration property set and updated (The scenario from KEYCLOAK-13397)

- Create and update of the "User Client Role" protocol mapper for some OIDC client. Also tested this for some OIDC client scope.

- Create and update of "Audience" protocol mapper for some OIDC client with the "Included Client Audience" config property set and updated. Also tested this for some OIDC client scope.

- Create and update of "Audience" protocol mapper for some SAML client with the "Included Client Audience" config property set and updated. Also tested this for some SAML client scope.

Those are all the places, which use ProviderConfigProperty.CLIENT_LIST_TYPE and they are using the kc-provider-config and kc-component-config directive in combination with 'ClientList' type, which is the part affected by this fix.

**Review by vmuzikar — APPROVED** [review]
LGTM, tests passed as well (well, IE is still [running](https://keycloak-jenkins.com/job/keycloak-ui-matrix_nightly/147/browser=internetExplorer,jdk=win_oraclejdk8,label=win2016/console) but I don't expect any IE specific issues – manually the LDAP mapper works).

I think `kc-provider-config` is actually not affected by this change at all. It uses `multivalued=false` which is effectively the previous behavior, so there shouldn't be any risk of regression caused by this.
Our only concern should be `kc-component-config` and the only place I found that uses this template and clients at the same time is the LDAP mapper.

Nothing else seems to use `ProviderConfigCtrl`.

From my PoV we're good to go. Thank you @mposolda for the quick fix!

**Comment by vmuzikar** [comment]
@mposolda However, we still must not forget to add some test for this later.

**Comment by vmuzikar** [comment]
jFTR, IE passed too.

**Review by hmlnarik — APPROVED** [review]
Thank you very much!

**Comment by mposolda** [comment]
@vmuzikar @hmlnarik Thanks for the test and review!

**Comment by mposolda** [comment]
@vmuzikar Created follow-up JIRA for add tests. Sorry for the delay https://issues.redhat.com/browse/KEYCLOAK-13594 .

**Pull request merged**
