### PR TITLE
KEYCLOAK-6707 Improve clarity of verfiyEmail tooltip

### PR DESCRIPTION
**Pull request by jannikhuels**

### CODE REVIEW

**Review by abstractj — DISMISSED** [review]

**Comment by matthewhelmke** [comment]
Thank you, @jannikhuels, for your contribution.

A couple comments, from a language perspective. We could either keep the original version, which is linguistically correct but is missing the validation that occurs when a user submits an email address change, or we could use the edited version, but with further edits. Here is my suggestion:

Require users to verify their email address after initial login or after address changes are submitted.

**Comment by abstractj** [comment]
@jannikhuels please do the changes @matthewhelmke suggested and we can merge it afterwards.

**Review by hmlnarik — APPROVED** [review]

**Review by stianst — APPROVED** [review]

**Review by stianst — COMMENTED** [review]
Please squash into a single commit

**Review by stianst — CHANGES_REQUESTED** [review]
Please squash into a single commit

**Comment by abstractj** [comment]
@jannikhuels I'm closing this and moving it to https://github.com/keycloak/keycloak/pull/5395. What I did was just the rebase to get it merged.

Thanks for your contribution.

**Pull request closed without merging**
