### PR TITLE
Fix errors pointed out by Hibernate 6 in the queries

### LINKED ISSUE #16337: Hibernate 6 upgrade: Entity -> id mapping no longer automatically done
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

After upgrading to hibernate 6, some queries in the legacy JPA store failed with hibernate complaining about wrong types. For example:

https://github.com/keycloak/keycloak/blob/f11bef3e7f697935adf4c4a29e9225d62e5580d5/model/jpa/src/main/java/org/keycloak/authorization/jpa/entities/ResourceEntity.java#L70

`s.resourceServer` is actually a `ResourceServerEntity`, and the parameter is a `String`. In Hibernate 5, the entity would be mapped to it's id automatically, but Hibernate 6 shows an error saying the types are incompatible. The fix is easy, just replace `s.resourceServer` by `s.resourceServer.id`, but we might be missing some way to perform the mapping automatically.

Another example is in queries done via `CriteriaBuilder`. Such as 

https://github.com/keycloak/keycloak/blob/f11bef3e7f697935adf4c4a29e9225d62e5580d5/model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAResourceStore.java#L158

The query in this method actually returns the ids of the entities, not the entity type itself. Again, Hibernate 5 seemed to map these things automatically, whereas Hibernate 6 displays an error complaining about incompatible types. Again, fix is easy, just create the query using the `String` type:

```
        CriteriaQuery<String> querybuilder = builder.createQuery(String.class);
```

We need to check if there's anything that must be done now to perform this mapping automatically, or if this is a case of Hibernate 6 being more strict about the types used in the queries.

### Version

quarkus3 branch

### Expected behavior

Migration to Hibernate 6 should probably be accomplished without changes to the queries.

### Actual behavior

Queries are being changed to properly match the expected types in Hibernate 6.

### How to Reproduce?

Use quarkus3 branch.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
This fixes several integration tests around AuthZ: 

* o.k.t.authz.AuthorizationTest
* o.k.t.authz.AuthzClientCredentialsTest
* o.k.t.authz.ConflictingScopePermissionTest
* o.k.t.authz.EntitlementAPITest (for all tests to pass here, it also needs #16650 to be merged)
* o.k.t.authz.PermissionClaimTest
* o.k.t.authz.PermissionManagementTest
* o.k.t.authz.UmaGrantTypeTest
* o.k.t.authz.UserManagedPermissionServiceTest
* o.k.t.authz.admin.AuthorizationTest
* o.k.t.authz.admin.ClaimInformationPointProviderTest
* o.k.t.authz.admin.EnforcerConfigTest
* o.k.t.authz.admin.ExportAuthorizationSettingsTest
* o.k.t.authz.admin.GenericPolicyManagementAdminEventTest
* o.k.t.authz.admin.GenericPolicyManagementTest
* o.k.t.authz.admin.PolicyEnforcerClaimsTest
* o.k.t.authz.admin.PolicyEnforcerTest
* o.k.t.authz.admin.ResourceManagementTest
* o.k.t.authz.admin.ResourceManagementWithAuthzClientTest
* o.k.t.authz.admin.ResourceServerManagementTest
* o.k.t.account.ResourcesRestServiceTest

Closes #16337

### CODE REVIEW

**Review by sguilhen — APPROVED** [review]
@ahus1 thanks for looking into it. This is exactly what I had to do when I faced issues with the authz tests too, so this PR gets a +1 from me.

**Comment by ahus1** [comment]
@hmlnarik - with the review from Stefan already in, this is now ready to be merged. Thanks!

**Comment by ahus1** [comment]
back to draft due to quarkus3 branch frozen and due to be rebased.

**Review by vramik — APPROVED** [review]
Thanks @ahus1

**Comment by ahus1** [comment]
The IT (3) tests are now more green than ever: all authz related tests are green, except `EntitlementAPITest` which needs also the fixes in #16650.

The remaining list of errors:

```
023-01-27T18:02:39.3844540Z [ERROR] Tests run: 36, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 58.672 s <<< FAILURE! - in org.keycloak.testsuite.authz.EntitlementAPITest
2023-01-27T18:05:37.5921586Z [ERROR] Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 8.825 s <<< FAILURE! - in org.keycloak.testsuite.authz.adapter.example.DefaultAuthzConfigAdapterTest
2023-01-27T18:13:23.0886386Z [ERROR] Tests run: 17, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 465.355 s <<< FAILURE! - in org.keycloak.testsuite.authz.adapter.example.LifespanAdapterTest
2023-01-27T18:13:46.6848277Z [ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 23.571 s <<< FAILURE! - in org.keycloak.testsuite.authz.adapter.example.PermissiveModeAdapterTest
2023-01-27T18:25:13.2572832Z [ERROR] Tests run: 15, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 404.898 s <<< FAILURE! - in org.keycloak.testsuite.authz.adapter.example.PhotozExampleLazyLoadPathsAdapterTest
2023-01-27T18:31:55.5346421Z [ERROR] Tests run: 15, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 402.22 s <<< FAILURE! - in org.keycloak.testsuite.authz.adapter.example.PhotozExampleNoLazyLoadPathsAdapterTest
2023-01-27T18:34:44.4299967Z [ERROR] Tests run: 35, Failures: 3, Errors: 30, Skipped: 1, Time elapsed: 168.189 s <<< FAILURE! - in org.keycloak.testsuite.authz.adapter.example.ServletAuthzCIPAdapterTest
2023-01-27T18:37:18.3296727Z [ERROR] Tests run: 34, Failures: 3, Errors: 30, Skipped: 1, Time elapsed: 153.271 s <<< FAILURE! - in org.keycloak.testsuite.authz.adapter.example.ServletAuthzCacheDisabledAdapterTest
2023-01-27T18:39:51.7329496Z [ERROR] Tests run: 34, Failures: 3, Errors: 30, Skipped: 1, Time elapsed: 152.652 s <<< FAILURE! - in org.keycloak.testsuite.authz.adapter.example.ServletAuthzCacheLifespanAdapterTest
2023-01-27T18:42:28.2387064Z [ERROR] Tests run: 34, Failures: 3, Errors: 30, Skipped: 1, Time elapsed: 156.25 s <<< FAILURE! - in org.keycloak.testsuite.authz.adapter.example.ServletAuthzLazyLoadPathsAdapterTest
2023-01-27T18:44:51.1762135Z [ERROR] Tests run: 31, Failures: 3, Errors: 27, Skipped: 1, Time elapsed: 142.711 s <<< FAILURE! - in org.keycloak.testsuite.authz.adapter.example.ServletAuthzNoLazyLoadPathsAdapterTest
2023-01-27T18:48:07.6890262Z [ERROR] Tests run: 48, Failures: 3, Errors: 45, Skipped: 0, Time elapsed: 195.077 s <<< FAILURE! - in org.keycloak.testsuite.authz.adapter.example.ServletPolicyEnforcerLifespanTest
2023-01-27T18:51:18.2835692Z [ERROR] Tests run: 48, Failures: 3, Errors: 45, Skipped: 0, Time elapsed: 190.545 s <<< FAILURE! - in org.keycloak.testsuite.authz.adapter.example.ServletPolicyEnforcerTest
```

**Comment by ahus1** [comment]
@hmlnarik - please approve and merge based on the reviews before the rebase. The rebase was done without conflicts.

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
