### PR TITLE
Unify package files for JS adapter

### LINKED ISSUE #9788: Combine package files for JS adapter
### Description

Currently the package files for the JS adapter are duplicated for development and distribution. This means that there are two sources of truth for what the dependencies should be, which makes the development more complicated than it needs to be.

These files should be combined into a single file within the JS adapter directory and should also facilitate [linking ](https://docs.npmjs.com/cli/v8/commands/npm-link) the package during development.

### PR DESCRIPTION
**Pull request by jonkoops**
Combines the package files for the source and distribution of the JS adapter into a single file. This avoids duplication of the dependencies that are required by the JS adapter and allows [linking](https://docs.npmjs.com/cli/v8/commands/npm-link) the package locally during development.

Closes #9788

## Other changes
- Updates NodeJS to the latest LTS version
- Updates development dependencies to latest versions

### CODE REVIEW

**Review by edewit — DISMISSED** [review]

**Review by mhajas — DISMISSED** [review]
Thanks for the PR @jonkoops

**Comment by jonkoops** [comment]
@stianst @ssilvert can we get this one merged into `main`?

**Comment by jonkoops** [comment]
I've moved `es6-promise` to a dev dependency so that it is not installed for users of NPM. This should not impact other users as for them this is bundled into the script at compile time. 

All other dev dependencies have also been updated to their respective latest versions.

**Review by edewit — DISMISSED** [review]

**Review by mhajas — APPROVED** [review]

**Review by edewit — APPROVED** [review]

**Review by ssilvert — APPROVED** [review]
LGTM

**Pull request merged**
