### PR TITLE
Update user-list.html

### PR DESCRIPTION
**Pull request by howkymike**
**table-nav width fix** in the "Users" tabs (analogous to table search div).

### CODE REVIEW

**Review by ssilvert — CHANGES_REQUESTED** [review]
I'm fine with this change, but we need an issue to go with the PR.  It would be nice if the issue has a before and after image so we see exactly what the problem is.

**Review by jonkoops — DISMISSED** [review]
These changes look good to me, just be aware that this UI will be removed in the future and replaced. However that is no reason not to land bug fixes while we still support it.

**Comment by howkymike** [comment]
@ssilvert alright, [here](https://github.com/keycloak/keycloak/issues/14725) is an issue.

PS. I did not know the UI it is going to be replaced -  It looks quite modern.

**Comment by ssilvert** [comment]
Fixes #14725

**Pull request merged**
