### PR TITLE
[KEYCLOAK-3629] - Some Adapters do not work with SSL Redirect

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by stianst** [comment]
Looks good, but the config option is missing in the subsystem config

**Comment by sebastienblanc** [comment]
@pedroigor that would help to solve https://issues.jboss.org/browse/KEYCLOAK-4759 as well, correct ?

**Comment by pedroigor** [comment]
@stianst, also sent a PR with doc changes https://github.com/keycloak/keycloak-documentation/pull/245.

**Comment by pedroigor** [comment]
@sebastienblanc yeah, you are right. Will mark that one as duplicated.

**Comment by sebastienblanc** [comment]
@pedroigor Well, this one should still be updated I think https://github.com/keycloak/keycloak/blob/master/adapters/oidc/servlet-filter/src/main/java/org/keycloak/adapters/servlet/KeycloakOIDCFilter.java#L194

**Comment by pedroigor** [comment]
@sebastienblanc I'm not sure. The real logic is on {{OAuthRequestAuthenticator}}, where the confidential port is chosen depending whether the {{confidential-port}} option is defined or not. That line is basically setting a default port (after my changes) in case the new option is not provided.

**Comment by sebastienblanc** [comment]
But I think that the filter adapter don't use the OAuthRequestAuthenticator
but the FilterRequestAuthenticator that just extends the
RequestAuthenticator.

**Comment by pedroigor** [comment]
Which in turn uses the ```OAuthRequestAuthenticator```, no ?

See https://github.com/keycloak/keycloak/blob/master/adapters/oidc/servlet-filter/src/main/java/org/keycloak/adapters/servlet/FilterRequestAuthenticator.java#L58.

**Comment by sebastienblanc** [comment]
Ah true :) Sorry about that, I can close my PR and this one is to go then !

**Pull request merged**
