### PR TITLE
KEYCLOAK-18509 Fix permission error when deleting client

### PR DESCRIPTION
**Pull request by simenheg**

### CODE REVIEW

**Comment by pedroigor** [comment]
@simenheg Thanks. Going to send you a test so you can include it here.

**Comment by pedroigor** [comment]
@simenheg Could you add these changes and squash commits into one? See https://github.com/pedroigor/keycloak/commit/4b479dbdaf09e453e629ef5de0a7aacc9fee1993.

**Comment by simenheg** [comment]
> @simenheg Could you add these changes and squash commits into one? See [pedroigor@4b479db](https://github.com/pedroigor/keycloak/commit/4b479dbdaf09e453e629ef5de0a7aacc9fee1993).

Done, thanks! Though the test seems to run green even when I remove the fix from `ClientApplicationSynchronizer.java`?

**Review by pedroigor — APPROVED** [review]
@simenheg That is weird ... I just re-run and it fails for me without your changes.

Thanks for sending the fix.

**Pull request merged**
