### PR TITLE
Remove deprecated default roles methods

### LINKED ISSUE #15046: Remove methods for old default roles approach
### Description

Based on [KEYCLOAK-14846](https://issues.redhat.com/browse/KEYCLOAK-14846) there were a few methods deprecated. We should remove them.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by sguilhen**
Closes #15046

### CODE REVIEW

**Review by hmlnarik — COMMENTED** [review]
I like this approach, thanks @sguilhen!

**Comment by sguilhen** [comment]
@hmlnarik Thanks! I thought it would still be worth removing the deprecated methods from the model classes, even if we have to retain the representations for migration and client registration. I've switched the PR from draft to ready-to-review.

**Comment by sguilhen** [comment]
@mhajas adding you as reviewer in case you want to have a look as well

**Review by hmlnarik — APPROVED** [review]

**Comment by hmlnarik** [comment]
@mhajas I keep this PR open for you to have a look if you like to; feel free to unassign yourself / merge otherwise.

**Review by mhajas — APPROVED** [review]
Thank you @sguilhen, LGTM!

**Pull request merged**
