### PR TITLE
KEYCLOAK-17039 Local file in a webview fails with "Origin: null"

### PR DESCRIPTION
**Pull request by davidperrenoud**
https://issues.redhat.com/browse/KEYCLOAK-17039

### CODE REVIEW

**Comment by davidperrenoud** [comment]
@mhajas Why is this failing? Is there anything I can do to fix the pipeline?

**Comment by mhajas** [comment]
@davidperrenoud  Sorry I forgot about this completely. I am not sure why it is failing, but maybe rebasing is worth trying as your branch is `157 commits behind keycloak:master`

**Comment by davidperrenoud** [comment]
@mhajas Could you run the workflow again? I don't why it was failing. Some timeout issue maybe.

**Review by mhajas — CHANGES_REQUESTED** [review]
@davidperrenoud I don't have rights to run workflow here, however I tried to run internal CI. I will let you know whether everything passes. 

We will need also some test that is checking the behavior you described in Jira. I think it could be added similarly as this test:
https://github.com/keycloak/keycloak/blob/52ced98f92815c1d595bf4470c5939e061e07cd6/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCWellKnownProviderTest.java#L230-L242

**Comment by davidperrenoud** [comment]
> We will need also some test that is checking the behavior you described in Jira.

I added a test for the "null" origin and merged master again. @mhajas Could you test this on your internal CI?

**Review by mhajas — CHANGES_REQUESTED** [review]
@davidperrenoud Thank you for the test and sorry for the late reply. The changes look good to me and internal CI passed. 

https://keycloak-jenkins.com/job/universal-test-pipeline-server/627/
https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/541/

The last thing that needs to be done is squashing the commits so that there is only one commit in this PR.

**Comment by davidperrenoud** [comment]
Done! @mhajas

**Comment by davidperrenoud** [comment]
Could you tell us what more would be needed to get this merged? By the way, the 2 links up there (keycloak-jenkins.com) strangely point to some scam website.

**Review by mhajas — APPROVED** [review]
@davidperrenoud I am trying to find someone else from the Keycloak team to have a look at this. From my point of view, this doesn't require any action from your side. Note, we can't merge this at the moment as we are just before 15.0.0 release and KEYCLOAK-17039 is not planned to be part of it. We can proceed with this PR once 15.0.0 is released. Sorry for the delay.

Thank you for the heads-up with the scam website under keycloak-jenkins. We are using that host so that URL of our internal CI stays hidden, we don't want to publish it. I will make sure I don't use this url anymore.

**Review by hmlnarik — APPROVED** [review]
Approving based on @mhajas's review

**Pull request merged**
