### PR TITLE
ISPN 14 backport

### LINKED ISSUE #12494: Update Infinispan version to 14.x.x
After this change it is possible to start with the following issues: 
- #12493
- #10988
- #12497

### PR DESCRIPTION
**Pull request by martin-kanis**
Backport of ISPN 14 upgrade.
Fixes https://github.com/keycloak/keycloak/issues/12494
Fixes https://github.com/keycloak/keycloak/issues/15977

### CODE REVIEW

**Review by mhajas — APPROVED** [review]
Thanks @martin-kanis, the Pr looks good to me. I checked the distribution and seems to work with Infinispan 14.0.4.

**Comment by ahus1** [comment]
Hi @sschu - reading #15902 and the related issue, they are about enabling Inifinispan metrics. For me this implies that Infinispan metrics weren't available before via the `/metrics` endpoint. 

I gave it a short try with the KC20.0.3 distribution, started it with `bin/kc.sh start-dev --metrics-enabled true` and didn't see metrics in the endpoint. I also updated `cache-ispn.xml` to contain `statistics="true"` and still didn't see metrics.

Please let me know if I'm wrong here, and if there is a different way to see Infinispan metrics in KC20. 

If we would need to backport those other PRs, this would definitely lead to breaking changes for all metrics (like JVM memory, DB connection pools). Please note that there's another PR upcoming for metrics #16752 - was created yesterday, and I was planning to add you to the loop on this today. That one would need to be backported as well.

I'd argue that when there are no metrics on caches available in KC20, all those other PRs don't need to be backported.

**Comment by ahus1** [comment]
@sschu / @mhajas - I found that I was missing in my CLI the `--cache-config-file ...` parameter, without that the file in the conf folder didn't have any effect. Once I changed this, I saw metrics for Infinspan on KC20. 

While the metric names for Infinispan look similar at first sight, other metric names have changed due to #15235.

**Comment by sschu** [comment]
@ahus1 Exactly, and the metrics changes will definitely be unexpected for a patch release. There should probably be some release notes around that similarly to the ones for KC21.

**Comment by mhajas** [comment]
In the internal discussion, we decided this Infinispan update will not be backported. Therefore, I am closing the PR.

**Pull request closed without merging**
