### PR TITLE
KEYCLOAK-13026 Allow to set path of OAuth_Token_Request_State cookie

### PR DESCRIPTION
**Pull request by Leinorax**
Please see: https://issues.redhat.com/projects/KEYCLOAK/issues/KEYCLOAK-13026

### CODE REVIEW

**Comment by stianst** [comment]
Seems like this is a normal use-case and should require additional configuration. Perhaps I'm missing something here, but shouldn't the path to the cookie just be set to the root path of the application?

@pedroigor WDYT?

**Comment by laurem1381** [comment]
Looking at the comment of @pedroigor on my Jira ticket, there already exists a property "adapter-state-cookie-path" in the adapter config that is used to set the path of the "KEYCLOAK_ADAPTER_STATE" cookie.

Maybe is could use this adapter property instead of adding one?
If you agree, I will adapt my pull request.

**Review by stianst — CHANGES_REQUESTED** [review]
The bug is a valid bug, but this is a work-around and not a proper fix. This approach requires developers to be aware of this property and always set it, as this can happen in any deployment.

The correct solution to this issue is to change the code to find the correct cookie when there are more than one. It should do this by retrieving the cookie not just by name, but also consider the expected path.

**Comment by pedroigor** [comment]
@laurem1381 I didn't see your PR until now. Thanks for it. JIRA is updated.

@stianst As per discussions in that JIRA, the issue seems to be specific to Chrome (and specific version). In a nutshell, I did not find a reason why a browser would duplicate the cookie as they are set (and not added) to the response.

I think it does make sense to set the path using a config property given that this is something we already support for other cookies, where people using the cookie store, may want to set the path to the state cookie accordingly too.

**Comment by stianst** [comment]
@pedroigor it disagree - see my comments. We should really never have supported setting the cookie path, but rather fixed the problem properly in the way I'm suggesting.

**Comment by laurem1381** [comment]
@stianst The problem is that we would need a way to find several cookies of the same name and check if one of them matches (the browser only sends cookie names, never paths). As far as I can see, that requires a change to the HttpFacade and all of its implementations, so that's not a small change.

That also doesn't save the problem that the duplicate cookie will not be cleared (not a big problem, but it's not very clean...).

The easiest fix would be to force the cookie path to / in all cases. Normally it should not cause any problem because it will be cleared by the adapter after the check when coming back from the login page.
@pedroigor What do you think?

**Comment by pedroigor** [comment]
@laurem1381 I would say that if setting the path to `/` solves this specific issue you are facing, than we can do it.

By forcing `/` cookies should be sent for sub-directories as well, what should work if the adapter builds a redirect uri to sub-directories.

**Comment by laurem1381** [comment]
@stianst @pedroigor I changed my commit to set the cookie path to /, is it OK for you?

**Review by pedroigor — APPROVED** [review]

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
Thanks @laurem1381

**Pull request merged**
