### PR TITLE
KEYCLOAK-11596 Enable template cache when cacheTemplates attribute is…

### PR DESCRIPTION
**Pull request by JessThrysoee**
… true

### CODE REVIEW

**Comment by JessThrysoee** [comment]
https://github.com/keycloak/keycloak/pull/6349 should fix "Add checks have failed"

**Comment by mhajas** [comment]
@JessThrysoee PR https://github.com/keycloak/keycloak/pull/6349 is merged. Could you please rebase?

**Comment by JessThrysoee** [comment]
Thanks. Rebase done.

**Comment by stianst** [comment]
Thanks, looks like cache = null was probably added by a developer during development and not removed when committing. Please it wasn't there when I wrote it many years ago, as that would be pretty stupid by me ;)

**Review by stianst — APPROVED** [review]

**Pull request merged**
