### PR TITLE
SAML Broker - Introduce assertion Issuer validation

### LINKED ISSUE #10982: SAML Client does not validate IdP Issuer value
### Description

When receiving assertions from a remote IdP, the client should verify both that the signature is correct and that the claimed issuer is the expected one. At the moment, Keycloak SAML IdP configuration does not have an attribute to identify the remote IdP issuer and does not perform issuer validation.
Also, when importing a SAML IdP from metadata, the expected issuer can be automatically populated from the metadata document.

### Discussion

_No response_

### Motivation

Keycloak should validate that the SAML Issuer is set to the expected value in addition to the other already present checks, otherwise it should return a Bad Request error.

For retrocompatibility, if the expected Issuer is not set it should accept any Issuer in SAML responses.

### Details

I will provide a PR for this feature soon.

### PR DESCRIPTION
**Pull request by lscorcia**
This pull request adds support for validating the `Issuer` of incoming SAML assertions, as described in #10982 .
It adds a new optional attribute to the SAML Identity Provider configuration called `Identity Provider Entity ID` which is matched to both the `Issuer` value in the SAML response and in the SAML assertion. If validation fails, a `Bad Request/Invalid Requester` error is triggered.

It also adds the required logic to automatically populate the `Identity Provider Entity ID` field to the IdP metadata document import button.

For retrocompatibility, if the `Identity Provider Entity ID` attribute is empty, no additional validation is performed.

### CODE REVIEW

**Comment by lscorcia** [comment]
Test failures are not related to the changes.

**Comment by lscorcia** [comment]
Hello @hmlnarik , can you please add this to the review queue?

**Review by mhajas — DISMISSED** [review]
@lscorcia thank you very much for the PR. The code looks good to me. Could you please create a PR for [the new admin console](https://github.com/keycloak/keycloak-admin-ui) too?

**Comment by lscorcia** [comment]
Hello @mhajas , thanks for the review. I'm not really a client-side developer, however I think I completed the requested change in PR [#2561](https://github.com/keycloak/keycloak-admin-ui/pull/2561) .

Please let me know if I missed something.

**Comment by lscorcia** [comment]
Hello @hmlnarik , is everything ok here now?

**Review by mhajas — APPROVED** [review]
Thanks for the rebase @lscorcia. I believe the failures are caused by some maven repository outage. @hmlnarik could you please rerun GHA?

**Review by hmlnarik — APPROVED** [review]
Approving per @mhajas 's approval

**Comment by lscorcia** [comment]
Thank you!

**Pull request merged**
