### PR TITLE
WIP: KEYCLOAK-7195 Allow Java Adapters to stwitch to the implicit flow

### PR DESCRIPTION
**Pull request by haderlena**
https://issues.jboss.org/browse/KEYCLOAK-7195
added json property "response-type"

### CODE REVIEW

**Comment by stianst** [comment]
Can you elaborate on why the Java adapter should support the implicit flow? The implicit flow is mostly useful to client-side applications (single-page JS apps, mobile apps, etc.) and should not really be used for server side confidential clients.

**Comment by beikov** [comment]
Hey Stian!

I already wrote on the mailing list on this regard: http://lists.jboss.org/pipermail/keycloak-dev/2018-April/010717.html
haderlena is a work colleague and is acting upon my request. We just figured out, that simply adding the response type isn't enough so haderlena is going to provide a flow configuration similar to what the JS adapter offers instead.
We need this because our application and the keycloak server are in separate networks that can't reach each other directly. Using the implicit flow was suggested on the mailing list and to me it seems sufficient. Do you have an idea for an alternative approach?

**Comment by stianst** [comment]
@pedroigor @mposolda what do you guys think? To me it makes little sense to support the implicit flow in a server-side web application.

**Comment by stianst** [comment]
@beikov it would be simpler for you to allow the application to communicate with the Keycloak server. That way everything works the way it is supposed to work. You get a more secure flow, you can get keys from the server, you have support for admin URLs (backchannel logouts etc.). I don't quite understand why this is a problem. The Keycloak server surely is open to users and the application is as well. So why can't the application just connect to the Keycloak server using the same URL as users do?

**Comment by mposolda** [comment]
I wonder how is possible that implicit flow works here considering that implicit flow enforces fragment response_mode and server-side applications don't have access to fragment. Implicit flow is really not targeted for server-side applications.

@beikov @haderlena Did you really manage to have it working with implicit flow just with this patch for adapters or did you need to tweak some other code on server-side too?

Did you consider to use SAML instead of OIDC? AFAIK SAML should be better for the case when client application really can't connect to the Keycloak server and things should somehow work with some exceptions (EG. SAML backchannel logout)

I agree with @stianst that best is, if client application can talk to Keycloak.

**Comment by beikov** [comment]
SAML works for us, but I guess the FORM POST mode would still be an interesting option? Should I reword the JIRA and close this PR for now?

**Comment by stianst** [comment]
@beikov +1

**Pull request closed without merging**
