### PR TITLE
WIP: KEYCLOAK-14597 updated to new patternfly

### PR DESCRIPTION
**Pull request by edewit**
also fixes KEYCLOAK-8082:
image

### CODE REVIEW

**Comment by edewit** [comment]
UI build: https://keycloak-jenkins.com/job/keycloak-account2-matrix/937/

**Comment by vmuzikar** [comment]
@edewit I liked this version better. :)
image
It was like that before some force-push.

**Comment by edewit** [comment]
@vmuzikar yeah I like that one too, but @ssilvert mentioned that "Signing In" and "Device Activity" could only be seen as 2 separate links by hovering

**Comment by ssilvert** [comment]
> @vmuzikar yeah I like that one too, but @ssilvert mentioned that "Signing In" and "Device Activity" could only be seen as 2 separate links by hovering

It all looks like one long link.  As long as you can visually distinguish each link without hovering then it might be ok.

We also talked about using buttons instead of links.  But I don't think that would look very good.  I don't think we ever tried it to see how it turns out though.

There are also other things we could try like [Expandable Section](https://www.patternfly.org/v4/documentation/react/components/expandablesection) or [Inline List](https://www.patternfly.org/v4/documentation/react/components/list)

**Comment by ssilvert** [comment]
Out of date.

**Pull request closed without merging**
