### PR TITLE
[KEYCLOAK-14639] - Update ISPN schemas and how to run guide

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by mposolda — APPROVED** [review]
@pedroigor Thanks for fixing this!

**Comment by pedroigor** [comment]
@stianst @mposolda Any idea why GA is failing to download the maven repo ?

**Comment by mposolda** [comment]
@pedroigor Not much ideas. Just noticed that this is not specific to your PR (other PRs from today are failing with the same). Not sure if it can have any relation to the Keycloak 11 release and version changes in pom.xml etc?

**Comment by pedroigor** [comment]
@mposolda Just noticed that the `Build` is failing to upload the maven repo artifact. Not sure what can be, I'm going to merge this one to base my current work on it.

**Comment by mposolda** [comment]
@pedroigor Cool!

**Pull request merged**
