### PR TITLE
Keycloak-3297 : adding cors-exposed-headers to conf

### PR DESCRIPTION
**Pull request by sebastienblanc**
add missing field in the BaseAdapterConfig

cleaning for PR & adding unit test

Adding property to subsystem, removing formatting changes

@ebondu Can you check if it all looks okay ?

### CODE REVIEW

**Review by ebondu — COMMENTED** [review]
It looks ok to me

**Comment by stianst** [comment]
Do we have a docs update for this as well?

**Comment by stianst** [comment]
Never mind, found it https://github.com/keycloak/keycloak-documentation/pull/123

**Comment by stianst** [comment]
What we're missing is testing though. I can't see any tests at all here.

**Comment by sebastienblanc** [comment]
The `KeycloakDeploymentBuilderTest.java` has been updated

**Comment by stianst** [comment]
That's not really testing anything though. We need something that tests that this header is actually being sent.

**Comment by stianst** [comment]
Is there not some cors adapter tests we could extend?

**Comment by sebastienblanc** [comment]
In the unit test area not really but in the integration tests we have probably something around this.

**Pull request merged**
