### PR TITLE
Add subgroups sorting

### LINKED ISSUE #19348: Sort subgroups
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

Hi,

I have updated my Keycloak from 19.0.2 to 21.0.1.
Now I have the problem that the groups are not sorted. It doesn't matter whether I create new groups or move existing ones.

However, if I now set up a new Keycloak instance, the sorting works properly when creating and moving groups.

Here an example of my groups:

Screenshot from 2023-03-27 08-13-14

### Version

21.0.1

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Todor13**
Closes #19348

Apply the same sorting to subgroups as the sorting of the top level groups.

### CODE REVIEW

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for tackling this issue which has been open for quite some time. 

I saw that this PR was missing a test, so I created one: https://github.com/Todor13/keycloak/pull/1

Please have a look at the PR. Once it is merged, I can do a final review of this PR.

**Comment by Todor13** [comment]
> Thank you for tackling this issue which has been open for quite some time.
> 
> I saw that this PR was missing a test, so I created one: [Todor13#1](https://github.com/Todor13/keycloak/pull/1)
> 
> Please have a look at the PR. Once it is merged, I can do a final review of this PR.

@ahus1 Thank you for the review and the changes! I have merged your PR. Should I squash the commits so that we have only one commit?

**Review by ahus1 — APPROVED** [review]
Thank you for reviewing the test case and providing this PR in the first place. All tests are green, and it now ready to be merged.

**Comment by ahus1** [comment]
> Should I squash the commits so that we have only one commit?

Generally speaking, you're on the safe side to merge the commits before the final review, especially when they are related like in this case. It might make it simpler and more straightforward for a review and a maintainer in the process.

A maintainer can also squash the changes via the GitHub API (what I did in this case) if they feel this is the appropriate thing to do. Overall it is for the maintainer to make sure that the commit log is meaningful to read and all changes can be tracked to their issues and related pull requests.

Thank you again for this contribution - the parent issue had already several votes, and I assume even more subscribers. It will be part of Keycloak 23 once it is released. If you want to give it a try, the next nightly release of Keycloak will contain your change.

**Pull request merged**
