### PR TITLE
Add Java Distribution IT for Windows

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by miquelsi — APPROVED** [review]
Thanks @pedroigor!

**Review by ahus1 — APPROVED** [review]
Approve as of @miquelsi review

**Comment by Pepo48** [comment]
@miquelsi a week ago I raised a question about whether the Keycloak project is built on a windows runner. Meanwhile the discussion faded out among other topics, so I'm asking it again before we merge this PR:

Un the [console output](https://github.com/keycloak/keycloak/actions/runs/5547371372/jobs/10143528544?pr=21675#step:3:391) I noticed following `OS name: "linux", version: "5.15.0-1041-azure", arch: "amd64", family: "unix"`. Moreover, just the [bash shell](https://github.com/keycloak/keycloak/blob/main/.github/actions/build-keycloak/action.yml#L68) is used during build-keycloak action  If I understand correctly, with the current setup the project is not built on Windows, we just extract the maven artifacts that were uploaded during the build action and then we run the subset of tests. Am I right? Or does it somehow use [WSL2 feature](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#windows-features) under the hood?

Because that would explain the fact that in our internal pipelines we currently experience error during the build and here, we don't. 

I would love to see a keycloak-build action executed natively on a win VM.

**Comment by ahus1** [comment]
Created new unstable test issues, please review: 

* #21780
* #21779
* #21778

Maybe it is also a good idea to backport this to KC22.

**Comment by ahus1** [comment]
@Pepo48 sorry for merging this probably too early. Will wait for your review next time!

**Comment by Pepo48** [comment]
@ahus1 that's ok, we can eventually resolve it in a follow-up. But let's wait for the clarification from @miquelsi, first - I might've easily misunderstood the behaviour and the PR expectations.

**Pull request merged**
