### PR TITLE
Add getter-methods to OAuth2GrantType.Context

### LINKED ISSUE #31076: Oauth2GrantType.Context requires getter-methods
### Description

In order to implement custom-grantTypes it is necessary that the OAuth2GrantType.Context class receives getter-methods for its parameters.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by Captain-P-Goldfish**
fixes #31076

EDIT:
I haven't added a getter-method for the DPoP object to prevent a conflict with https://github.com/keycloak/keycloak/pull/29967

### CODE REVIEW

**Comment by ahus1** [comment]
@Captain-P-Goldfish - thank you for this PR. There is no need to rebase your PR unless a maintainer ask you for this, or a conflict appears in your PR. 

I don't know if you have discussed this change already with someone from the @keycloak/core-clients team. I'd assume they would be the ones to review it.

**Comment by Captain-P-Goldfish** [comment]
No I haven't discussed it with any of the maintainers. It is just that we need an adjusted workflow and I am currently trying to add this workflow into keycloak by using its superb externsibility possiblities. But I got stuck on several points and I added a few PullRequests for each of these problems.
Is there a good way to accelerate the review process by discussing it somewhere, or do I just have to wait patiently?

**Comment by ahus1** [comment]
When the changes you did, it seems that those are related to OIDC. There is an Keycloak OIDC special interest group (SIG). You can discuss your ideas there and you'll receive feedback from both OIDC experts and Keycloak maintainers. 
See https://github.com/keycloak/kc-sig-fapi for details. At the end of the page, you find the communication channels. IMHO the slack channel mentioned there is where I would recommend to start. 

For more general enhancements, an email to the Keycloak developer mailing list helps.

**Review by mposolda — APPROVED** [review]
@Captain-P-Goldfish Adding getters make sense. Thanks for this PR

**Pull request merged**
