### PR TITLE
KEYCLOAK-13397 KEYCLOAK-13568 Creating role-ldap-mapper for realm-man…

### PR DESCRIPTION
**Pull request by mposolda**
…agement client id in ldap user federation fails

### CODE REVIEW

**Comment by mposolda** [comment]
This PR is workaround, but on the other hand, it touches just the admin console parts related to LDAP Mappers create/update.

There is another possible better fix to this issue in this commit https://github.com/mposolda/keycloak/commit/8d85a51f35b63317010b65d9f7f215ef9a91335e . That one is more generic, however it touches some more parts of admin console and hence it is in theory more risky.

**Review by slaskawi — APPROVED** [review]
The code LGTM. Although, it would be great if you added a test.

**Comment by pedroigor** [comment]
@mposolda I agree that it makes more sense for now.

**Comment by mposolda** [comment]
@slaskawi Good point regarding tests. The thing is that we don't have tests for this part of the admin console. Developing new tests will take some non-trivial amount of time and possibility of regressions - as admin console tests depends a lot on the browsers etc.

In general, I think the amount of admin console tests is limited on purpose for now as they are not part of the travis and are often broken by various other admin console refactorings. More tests added would mean more maintenance with broken tests and not sure if it is intent now considering that we will rewrite admin console anyway. @vmuzikar Am I correct here?

**Comment by vmuzikar** [comment]
@mposolda IMHO I don't think that's the right approach. :) The tests are still not meant to be left behind, even though there'll be a new Admin Console – but that won't probably be sooner than let's say in a year. The test coverage is not great but that's definitely not on purpose and we shouldn't make it any worse. ;)

Since this is a blocker and needs to be fixed ASAP, I suggest to make an exception here and merge it even with missing tests. But please create a follow-up JIRA for them and try to add them when possible.

**Comment by slaskawi** [comment]
+1 for treating this as an exception and skipping the tests

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Thanks @mposolda for the quick fix. It fixes LDAP but I'm not 100% sure there are no other regressions there. 
@vmuzikar Can you please help here to develop the tests and look at #6567 to ensure that there are no other regressions.
The tests should be there. I'm in to do a reasonable exception if this has been tested manually to work, and there is no other regression coming from the #6567

**Comment by mposolda** [comment]
@hmlnarik @vmuzikar AFAIK there are no tests for the LDAP "Mappers" tab at all at this moment. So question is whether to hack some test just to cover this bug or whether to rather some more proper test coverage for the LDAP "mappers" in general. I rather vote for the second option.

Regarding the fix, I've tried to scope that to minimize the impact. So the fix is scoped just to 2 angular controllers related to LDAP mappers. So hopefully the risk of regression is minimal here. But another look and confirmation from others will be nice :)

As I pointed, there is possibly better solution to this problem, which I added in another commit https://github.com/mposolda/keycloak/commit/8d85a51f35b63317010b65d9f7f215ef9a91335e . But that one is more generic and affects more parts of admin console, so probably not so nice at this stage as risk of regression is bigger...

**Comment by vmuzikar** [comment]
> @vmuzikar Can you please help here to develop the tests and look at #6567 to ensure that there are no other regressions.


@hmlnarik To be honest, I'm not sure if I can do anything more for #6567. I did the review back the, spent quite a lot of time on that (and still somehow missed that LDAP issue :)). Unfortunately, I have currently a lot on my plate and I don't have much time to develop the tests myself. :(

> @hmlnarik @vmuzikar AFAIK there are no tests for the LDAP "Mappers" tab at all at this moment. So question is whether to hack some test just to cover this bug or whether to rather some more proper test coverage for the LDAP "mappers" in general. I rather vote for the second option.

+1 for second option

**Comment by mposolda** [comment]
Closing this PR and rather going with the alternative approach as agreed with @vmuzikar and @hmlnarik . The other PR is https://github.com/keycloak/keycloak/pull/6935 .

**Pull request closed without merging**
