### PR TITLE
Fix UserSessionProviderTest failures with CockroachDB

### LINKED ISSUE #13211: JPA Map Storage with CRDB: ConcurrentTransactionsTest failures
### Describe the bug

**org.keycloak.testsuite.model.ConcurrentTransactionsTest** presents failures/errors with `CockroachDB`:

```
[ERROR]   ConcurrentTransactionsTest.persistClient » RunOnServer java.lang.NullPointerException
```

- Required JPA stores to reproduce the failures: **realms**

The specific point where this happens follows:

 ```
 Caused by: java.lang.NullPointerException
	at org.keycloak.models.map.user.MapUserProvider.getUserByUsername(MapUserProvider.java:490)
	at org.keycloak.testsuite.model.ConcurrentTransactionsTest.tearDownRealm(ConcurrentTransactionsTest.java:284)
	at org.keycloak.testsuite.model.ConcurrentTransactionsTest.persistClient(ConcurrentTransactionsTest.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.keycloak.testsuite.rest.TestingResourceProvider.runModelTestOnServer(TestingResourceProvider.java:853)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

In this specific case, the `realm` that is being supplied to `getUserByUsername` is `null` - the test calls `session.realms().getRealmByName("original")` and this is returning `null`, even though the entry **exists** in the database (which can be verified by setting a breakpoint in `MapRealmProvider.getRealmByName()` and querying the DB right before hibernate does so.

### Version

main

### Expected behavior

Tests should run without failures or errors

### Actual behavior

_No response_

### How to Reproduce?

1- Setup CockroachDB according to the instructions in https://github.com/keycloak/keycloak/discussions/9596
2- Run the test with the correct parameters, enabling JPA storage for **realms** only:

```
cd testsuite/integration-arquillian

mvn clean install -Pmap-storage -Dpageload.timeout=90000 -Dkeycloak.realm.map.storage.provider=jpa \
-Dkeycloak.map.storage.connectionsJpa.url=jdbc:postgresql://localhost:26257/keycloak \
-Dkeycloak.map.storage.connectionsJpa.user=keycloak -Dkeycloak.map.storage.connectionsJpa.password=pass \
-Dtest=ConcurrentTransactionsTest
```

### Anything else?

_No response_

### LINKED ISSUE #13215: JPA Map Storage with CRDB: UserSessionProviderTest failures
### Describe the bug

**org.keycloak.testsuite.model.UserSessionProviderTest** presents failures/errors with `CockroachDB`:

```
[ERROR]   UserSessionProviderTest.testOnUserRemoved:754 expected:<0> but was:<2>
[ERROR]   UserSessionProviderTest.testRemoveUserSessionsByUser:273 expected:<0> but was:<2>
```

- Required JPA stores to reproduce the failures **userSessions**

In addition to these failures, that can be reproduced by simply configuring userSessions to use JPA storage, there are other failures when other stores are also set to JPA:

```
[ERROR]   UserSessionProviderTest.testGetByClient:544->assertSessions:800 array lengths differed, expected.length=3 actual.length=0; arrays first differed at element [0]; expected:<0cfa44ca-3ca0-42a6-b839-34f9cf62bc7c> but was:<end of array>
[ERROR]   UserSessionProviderTest.testGetByClientPaginated:572->assertPaginatedSession:668 expected:<1> but was:<0>
[ERROR]   UserSessionProviderTest.testGetCountByClient:679 expected:<3> but was:<0>
[ERROR]   UserSessionProviderTest.testGetUserSessions:253->assertSessions:800 array lengths differed, expected.length=2 actual.length=0; arrays first differed at element [0]; expected:<2bbb2239-c68b-453f-a277-e1fed458fead> but was:<end of array>
[ERROR]   UserSessionProviderTest.testRemoveUserSessionsByExpired:385

[ERROR]   UserSessionProviderTest.testCreateClientSession » RunOnServer java.lang.NullPointerException
[ERROR]   UserSessionProviderTest.testCreateSessions » RunOnServer java.lang.NullPointerException
[ERROR]   UserSessionProviderTest.testOnClientRemoved » InternalServerError HTTP 500 Internal Server Error
[ERROR]   UserSessionProviderTest.testRestartSession » RunOnServer java.lang.NullPointerException
[ERROR]   UserSessionProviderTest.testUpdateClientSession » RunOnServer java.lang.NullPointerException
[ERROR]   UserSessionProviderTest.testUpdateClientSessionInSameTransaction » RunOnServer java.lang.NullPointerException
[ERROR]   UserSessionProviderTest.testUpdateClientSessionWithGetByClientId » RunOnServer java.lang.NullPointerException
[ERROR]   UserSessionProviderTest.testUpdateSession » RunOnServer java.lang.NullPointerException
[ERROR]   UserSessionProviderTest.testUpdateSessionInSameTransaction » RunOnServer java.lang.NullPointerException
```

- Required JPA stores to reproduce the failures **userSessions**, **realms**, and **clients**

The NPEs reported here resemble the one reported in #13211, in that hibernate is not able to locate entries that exist in the database (in this case particular user sessions). Also, failures seen in tests like `testOnUserRemoved` also have to do with the fact that hibernate doesn't seem to detect that session entries were actually removed from the database and is returning some sort of stale data.

Other tests, such as `testOnClientRemoved` are failing due to transaction issues:

```
Caused by: org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): "sql txn" meta={id=4bfd0a61 key=/Table/3170/2/1/"OƍS\x91nAv\xb3Ϭ\xe9G\xe3\x18\xc9"/0 pri=0.01106863 epo=0 ts=1658256011.189340483,1 min=1658256011.182710187,0 seq=3} lock=true stat=PENDING rts=1658256011.182710187,0 wto=false gul=1658256011.682710187,0
  Hint: See: https://www.cockroachlabs.com/docs/v21.2/transaction-retry-error-reference.html#retry_serializable
```

### Version

main

### Expected behavior

Tests should run without failures or errors

### Actual behavior

_No response_

### How to Reproduce?

1- Setup CockroachDB according to the instructions in https://github.com/keycloak/keycloak/discussions/9596
2- Run any of the failing tests with the correct parameters, enabling JPA storage for **userSessions**, **realms** and **clients**:

```
cd testsuite/integration-arquillian

mvn clean install -Pmap-storage -Dpageload.timeout=90000 -Dkeycloak.realm.map.storage.provider=jpa \
-Dkeycloak.client.map.storage.provider=jpa \
-Dkeycloak.userSession.map.storage.provider=jpa \
-Dkeycloak.map.storage.connectionsJpa.url=jdbc:postgresql://localhost:26257/keycloak \
-Dkeycloak.map.storage.connectionsJpa.user=keycloak -Dkeycloak.map.storage.connectionsJpa.password=pass \
-Dtest=UserSessionProviderTest
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sguilhen**
- move assertions to a separate tx due to CRDB's SERIALIZABLE isolation level

Closes #13215

### CODE REVIEW

**Review by ahus1 — DISMISSED** [review]
With CockroachDB running on SERIALIZABLE instead of READ COMMITTED, moving those blocks to their own transaction is the way to go. 

Thanks for fixing this - one step more towards CockroachDB!

**Review by vramik — COMMENTED** [review]
Thank you @sguilhen! The code LGTM. I've just noticed the `UserSessionProviderTest` failed in GHA with `Base testsuite (quarkus, group3)]` and I was wondering whether it might be related.

**Comment by sguilhen** [comment]
> Thank you @sguilhen! The code LGTM. I've just noticed the `UserSessionProviderTest` failed in GHA with `Base testsuite (quarkus, group3)]` and I was wondering whether it might be related.

@vramik it looks related, somehow the changes seem to have introduced a regression on the legacy JPA store. Will investigate.

**Comment by sguilhen** [comment]
@vramik @ahus1 updated the PR, CI seems happy now

**Review by vramik — APPROVED** [review]
Thanks @sguilhen

**Review by ahus1 — APPROVED** [review]

**Pull request merged**
