### PR TITLE
KEYCLOAK-6615 Remove offline session from database on offline token logout

### PR DESCRIPTION
**Pull request by cgol**
Offline token session logout was leaving the token in the database. If keycloak was restarted the token became valid again.

### CODE REVIEW

**Comment by mposolda** [comment]
@cgol Thanks for the PR. Fix is good. Any chance you can also add a test? See OfflineTokenTest, which will be probably good place to add one. 

I suggest to add the test for the second scenario described in the JIRA as we don't have good possibility to simulate server restart during tests. I mean test for the scenario when you do another SSO login in browser for offline session and there is ConstraintViolationException). The test should simulate that there is error without your fix, but after the fix, the error is not here anymore.

**Comment by cgol** [comment]
OfflineTokenTest updated. Without the fix the assertion in line 614 will fail (due to 500 error).  This test will change again when KEYCLOAK-6617 is implemented and offline token logouts also logout the existing session.

hmm.. travis failed on an unrelated random test.

**Comment by mposolda** [comment]
@cgol Looks good to me. Random test failure was fixed. One last thing, could you please squash commits into single commit instead of 3 commits? Will be especially useful for this one PR especially if we want to cherry-pick commits to some other branch (EG. backport to RHSSO 7.2.x)

**Comment by mposolda** [comment]
@cgol I am closing this PR as I've created another PR #5007 , which fixes both 6615 and 6617. I've cherry-picked your commits, squash them and fixed KEYCLOAK-6617 . Thanks for the collaboration!

**Pull request closed without merging**
