### PR TITLE
Remove java.util.Date from VerifiableCredential

### LINKED ISSUE #30918: VerifiableCredential: Exchange java.util.Date for java.time.Instant
### Description

java.util.Date was always a problematic implementation causing several problems with timezone settings which is one reason why the java.time API was introduced with JDK8.
I would like to have the java.util.Date usage removed from the VerifiableCredential implementation

relatesTo https://github.com/keycloak/keycloak/issues/26328

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by Captain-P-Goldfish**
Ban java.util.Date from VerifiableCredential in exchange for java.time.Instant

fixes #30918
relatesTo https://github.com/keycloak/keycloak/issues/26328

### CODE REVIEW

**Comment by mposolda** [comment]
@wistefan @francis-pouatcha @tnorimat Anyone of you available to review this please?

**Comment by mposolda** [comment]
One point: This PR adds a dependency to keycloak-core module of fasterxml jsr310. That one is already bundled in Keycloak distribution and hence should be OK to include.

**Comment by Captain-P-Goldfish** [comment]
I needed to add the dependency because this specific module did not know of the JavaTimeModule from jackson.

**Comment by tnorimat** [comment]
@mposolda the main point for the PR is whether fasterxml jsr310 is acceptable or not. Could you determine it by your team?

**Comment by mposolda** [comment]
> @mposolda the main point for the PR is whether fasterxml jsr310 is acceptable or not. Could you determine it by your team?

@tnorimat Yes, adding this dependency in the `core` module is OK as the library `com.fasterxml.jackson.datatype.jackson-datatype-jsr310*.jar` is already bundled in Keycloak (in the directory `lib/lib/main` of the Keycloak quarkus distribution) and already productized in RH . Thanks for pointing that.

**Comment by tnorimat** [comment]
@mposolda I see. I will review the PR.

**Review by tnorimat — APPROVED** [review]
LGTM

**Comment by mposolda** [comment]
@tnorimat Thanks for the review!

@Captain-P-Goldfish Could you please rebase this on top of latest Keycloak main to resolve the conflict? Hopefully that will help with the failing test as well.

**Comment by Captain-P-Goldfish** [comment]
darn... seems like I broke something during rebase...

**Comment by Captain-P-Goldfish** [comment]
fixed

**Review by tnorimat — APPROVED** [review]
LGTM

**Review by mposolda — APPROVED** [review]
@Captain-P-Goldfish @tnorimat Thanks!

**Pull request merged**
