### PR TITLE
[KEYCLOAK-7206] - Search by user id on admin console

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by stianst** [comment]
What about user federation?

**Comment by stianst** [comment]
The whole fuzzy search thing is making all of this complicated. Ideally the search for users should allow specifying what attributes to search and allowing things like firstname:bob, lastname:la*

**Comment by stianst** [comment]
The ideal in this situation rather than requiring changes to user storage is probably something along the lines of what Marek suggests.

I can see two options:

* Do the search as today, if it returns no users then check getUserById
* Make it smarter. Add a field, or have something like "id:<uuid>".

**Comment by stianst** [comment]
Having a smart field could allow us to search for users by role and attribute as well. For instance:

"has-attr:my-key", "attr:my-key=my-value", "has-role:my-role", etc..

**Comment by mposolda** [comment]
@stianst So something similar like JIRA is doing regarding searches? That would be nice. 

At admin console level, we can probably improve our searching capabilities in UI to allow users search easily by any field, but we can always convert that to the format you mentioned. On admin REST API and on UserStorage API level, we may not need to do any changes and just reuse the existing method "searchForUser" (just add new javadoc). For backwards compatibility, we should probably still support the old "fuzzy" format, but we can add support the new "Advanced" format as well? Regarding UserStorage API, people are already able to support any format they want, so this won't affect existing UserStorage implementations anyhow.

**Comment by stianst** [comment]
Yup, like JIRA and Google.

If we do a single search field we don't need to touch the admin console at all. User storage provider can support it or not that's true.

So regular fuzzy search like now would just be "bob", but if you want to select a specific field or do more advanced search like roles you add "bob has-role:user" or for id you do "id:<uuid>".

For id for instance we could do that regardless if user storage supports it or not right?

**Comment by stianst** [comment]
@pedroigor and here you thought this was an easy thing to implement ;)

**Comment by pedroigor** [comment]
@stianst, yeah :) That is why I assign this one to myself (also because the user mentioned me in JIRA). But I like the new proposal. It will make user search really powerful.

I have a proposal though. Can we get this one in and create a separated JIRA for those new requirements?

**Comment by stianst** [comment]
I don't think we should merge this one. Firstly, it doesn't work for user storage providers. Secondly, if we decide to add a "id:" option to search for users by id the fuzzy search shouldn't search for users by id.

To proceed with this one I suggest adding support for two different searches for now:

* fuzzy search - as long as there's no special things in the search like 'id:'
* id search - if there is 'id:<uuid>' then search by id instead of fuzzy search

That would work with user storage, be (hopefully) future proof and will be simple to implement.

**Comment by mposolda** [comment]
IMO some admin console support will be good. It will be fine if admin has a way to manually fill the field and directly put "bob has-role:user attr:my-key=my-value" . On the other hand, admin console can provide some nice way to select attributes, roles etc, so that admin doesn't need to construct that search string manually?

I wonder whether to add support for some logical operators like AND, OR etc? For example JIRA is using AND by default. Keycloak is using OR by default at this moment - if you fill "bob" it defacto means "username=*bob* OR email=*bob* OR fullName=*bob*" . Will be probably good to add support for AND as well, especially for deployments with millions of users. Also support for wildcards etc (ability to specify attr:my-key=my-value which means that value must be exactly "my-value" or attr:my-key=my-value* means that value starts with "my-value" etc).

**Comment by stianst** [comment]
Having a form to allow specifying as well as a smart search field would be good.

Logical operators could be good as well, but would be tricky to do with user storage providers.

In any case I think for this specific issue which is about looking up a user by id we can just add a simple 'id:<uuid> to the search field that is handled differently. Anything beyond that would be a future JIRA.

**Comment by mposolda** [comment]
+1 to start support just for "id:" string now. Created another JIRA https://issues.jboss.org/browse/KEYCLOAK-7262 for future improvements. 

Regarding userStorage providers, we can define contract (language used by search field), but it's up to userStorage provider whether it supports. UserStorage providers already have freedom to support any super-advanced search string it wants or on the other hand, limit the searching abilities and not return anything. Like for example our summit JDG provider, which allows just search for single user with exactly matching "email" address.

**Comment by mposolda** [comment]
The only thing is, that besides javadoc of userStorage provider, we would likely need to add support for this advanced searching to our built-in LDAP and SSSD storage providers. For ID it shouldn't be a problem as long as we call the "session.users().getUserById" , so the KEYCLOAK-7206 should be probably fine without require any changes in LDAP or SSSD providers.

**Comment by stianst** [comment]
One interesting aspect is what happens when there are multiple user stores. How do search for users in all. How to search for users in one. What if the different stores have different search support. Etc..

**Comment by pedroigor** [comment]
@stianst, my latest changes to this PR are now using ```getUserById``` in case no user is returned, as a fallback.

That should work with user federation too.

Based on yours and Marek`s latest comments, I understand that for this particular issue we should add support for a ```id:``` parameter support and only search by id if this parameter is provided. Is that correct?

**Comment by pedroigor** [comment]
@stianst @mposolda, I have added support for ```id:``` search option.  We can come up with something more extensible when working with the improvements discussed here in order to support more easily different search options.

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
@pedroigor IMO it's good to go.

@stianst @pedroigor I've added a comment to the JIRA https://issues.jboss.org/browse/KEYCLOAK-7262 regarding user storages. Maybe it's better to place to discuss as this PR is likely going to be merged and discussion lost? Or keycloak-dev ML?

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
@mposolda +1 JIRA is better place to continue discussion.

**Pull request merged**
