### PR TITLE
KEYCLOAK-12776: Make it easier to change the logo and logo link.

### PR DESCRIPTION
**Pull request by ssilvert**

### CODE REVIEW

**Review by edewit — APPROVED** [review]
:+1:

**Comment by ssilvert** [comment]
UI Test run: https://keycloak-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/keycloak-account2-matrix/856/

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks @ssilvert!

I'm just wondering if we could somehow test the modification support (that changing the properties actually work). But that's probably part of a bigger task for testing the customization.

**Comment by ssilvert** [comment]
@vmuzikar Yes, there is a bigger task ahead.  Could be a bit challenging.

**Review by abstractj — APPROVED** [review]

**Comment by abstractj** [comment]
Approving based on @edewit and @vmuzikar review.

**Pull request merged**
