### PR TITLE
WIP: [KEYCLOAK-14343] Truststore SPI support for LDAP with StartTLS

### PR DESCRIPTION
**Pull request by tsaarni**
Fix the broken Truststore SPI support for LDAP with StartTLS by following changes

1. Do not set java.naming.ldap.factory.socket. This will allow cleartext LDAP connection to proceed.
2. Pass the SSL socket factory from truststore SPI when calling StartTlsResponse.negotiate().
3. Now the correctly initialized trustmanager gets used by the LDAP client. It uses it after successful StartTLS request/response to upgrade the cleartext LDAP connection to TLS.

This PR is continuation for #7049. 

Signed-off-by: Tero Saarni <tero.saarni@est.tech>

### CODE REVIEW

**Comment by tsaarni** [comment]
Hi @mposolda and @iankko,
 
Thanks to tip from @iankko https://github.com/keycloak/keycloak/pull/7049#issuecomment-636772405 I got rid of the cyclic dependency error in maven modules by moving `org.keycloak.truststore.SSLSocketFactory` from `keycloak-services` module to `keycloak-ldap-federation` module (if this is acceptable change?).

Now LDAPS login tests started to fail, at least with JDK11:

```
java.lang.ClassNotFoundException: org.keycloak.truststore.SSLSocketFactory
```

When `java.naming.ldap.factory.socket` is set to `org.keycloak.truststore.SSLSocketFactory` and we try to create LDAPS connection, the class cannot be found anymore. See [here](https://gist.github.com/tsaarni/c55bcf8ed1b288108f7c425d8b995db3) for full backtrace.

I have not figured out what causes this error. Now that the class is not part of `keycloak-services`anymore, but it is instead defined in dependency module, I wonder could there be something specific to Wildfly that needs to be done to expose classes for reflection?

**Comment by iankko** [comment]
Hello @tsaarni,

> Hi @mposolda and @iankko,
> 
> Thanks to tip from @iankko [#7049 (comment)](https://github.com/keycloak/keycloak/pull/7049#issuecomment-636772405) I got rid of the cyclic dependency error in maven modules by moving `org.keycloak.truststore.SSLSocketFactory` from `keycloak-services` module to `keycloak-ldap-federation` module (if this is acceptable change?).

No problem. AFAICT from looking, no other module / class from the `keycloak-services` seems directly to depend on that `SSLSocketFactory` implementation, and since `keycloak-ldap-federation` module is the one, which truly utilizes / calls that class, the move should be OK IMHO.

> 
> Now LDAPS login tests started to fail, at least with JDK11:
> 
> ```
> java.lang.ClassNotFoundException: org.keycloak.truststore.SSLSocketFactory
> ```
> 
> When `java.naming.ldap.factory.socket` is set to `org.keycloak.truststore.SSLSocketFactory` and we try to create LDAPS connection, the class cannot be found anymore. See [here](https://gist.github.com/tsaarni/c55bcf8ed1b288108f7c425d8b995db3) for full backtrace.

Right, this is what I am seeing / experiencing too. So far didn't find a solution for it. Tried to check the content of `keycloak-server.war`, which is being deployed within the test, but seems since the class is not found, `keycloak-server.war` isn't even deployed (or more exactly, the flow seems to go the way `Starting deployment of keycloak-server.war`, then after couple of minutes it ends up with `Stopping deployment of keycloak-server.war`.

> 
> I have not figured out what causes this error. Now that the class is not part of `keycloak-services`anymore, but it is instead defined in dependency module, I wonder could there be something specific to Wildfly that needs to be done to expose classes for reflection?

But let me ask wider team, if someone can shed more light, why this is happening? (if there's some explicit module load necessary to achieve the `SSLSocketFactory` class to be included into the final produced `keycloak-server.war`)

**Comment by iankko** [comment]
> Hi @mposolda and @iankko,
> 
> Thanks to tip from @iankko [#7049 (comment)](https://github.com/keycloak/keycloak/pull/7049#issuecomment-636772405) I got rid of the cyclic dependency error in maven modules by moving `org.keycloak.truststore.SSLSocketFactory` from `keycloak-services` module to `keycloak-ldap-federation` module (if this is acceptable change?).
> 
> Now LDAPS login tests started to fail, at least with JDK11:
> 
> ```
> java.lang.ClassNotFoundException: org.keycloak.truststore.SSLSocketFactory
> ```
> 
> When `java.naming.ldap.factory.socket` is set to `org.keycloak.truststore.SSLSocketFactory` and we try to create LDAPS connection, the class cannot be found anymore. See [here](https://gist.github.com/tsaarni/c55bcf8ed1b288108f7c425d8b995db3) for full backtrace.
> 
> I have not figured out what causes this error. Now that the class is not part of `keycloak-services`anymore, but it is instead defined in dependency module, I wonder could there be something specific to Wildfly that needs to be done to expose classes for reflection?

@tsaarni Got StartTLS tests working with use.truststore-spi=always working too. Unpolished (not final) change is [in this branch](https://github.com/iankko/keycloak/commits/KEYCLOAK-12305-starttls). See the last commit. Will do a polished version (another commit on top of your commit tomorrow). The only change (on top of your ones) I did is to change the package names, updated imports for necessary classes & updated one META-INF location with proper paths (see the last commit in that branch for further details). With these changes the `ClassNotFoundException` disappeared.

There's still one problem though - despite the StartTLS tests are now working properly with Wildfly, the LDAP over SSL (`ldaps://`) ones are now failing with the same issue. But I suspect, it's the same problem (former `org.keycloak.truststore.SSLSocketFactory.getDefault()` path needs to be updated to new / moved package name for SSL subcase too). Will look into this tomorrow too.

**Comment by tsaarni** [comment]
I've now tried renaming the classes and updating all references, instead of just moving the package from a module to another. I also tried to figure out some change in `services/META-INF` but nothing seems to make difference: the `SSLSocketFactory` still cannot be found :-(  Though, reading [this](https://stackoverflow.com/a/52756718/458531) I get an impression that  `services/META-INF` should impact on how SPIs are initialized...

**Comment by iankko** [comment]
@tsaarni 

> I've now tried renaming the classes and updating all references, instead of just moving the package from a module to another. I also tried to figure out some change in `services/META-INF` but nothing seems to make difference: the `SSLSocketFactory` still cannot be found :-(

Besides updating the package names, imports & META-INF, did you also update the references of `org.keycloak.truststore.SSLSocketFactory.getDefault();` to the new name (on all occurrences) when trying that?

FWIW regarding the META-INF change TBH it's a new concept to me too, but without updating it to proper (new) path, Wildfly failed to start (even before the test) somewhere around this step:

```
...
10:21:11,645 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-2) WFLYDS0013: Started FileSystemDeploymentService for directory /tmp/github/keycloak/testsuite/integration-arquillian/tests/base/target/containers/auth-server-wildfly/standalone/deployments
10:21:11,659 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0027: Starting deployment of "keycloak-server.war" (runtime-name: "keycloak-server.war")
...
```

Without that META-INF change SmallRye was complaining it's not able to find the `FileSystemDeploymentService`.

> Though, reading [this](https://stackoverflow.com/a/52756718/458531) I get an impression that `services/META-INF` should impact on how SPIs are initialized...

**Comment by iankko** [comment]
Another possible reason, why the class is still not found, might be by moving to `federation/ldap/src/main/java/org/keycloak/truststore/*.java` there are two `org.keycloak.truststore` packages now:
1) One is the original `server-spi-private/src/main/java/org/keycloak/truststore/TruststoreSpi.java`,
2) The other is the new `./federation/ldap/src/main/java/org/keycloak/truststore/SSLSocketFactory.java`

and each of them contains definitions of different classes (the definitions are complement to each other). In my change, I moved the SSLSocketFactory to `federation/ldap/src/main/java/org/keycloak/storage/ldap/truststore/*.java` to avoid this.

**Comment by mposolda** [comment]
@iankko @tsaarni I am sorry for not yet look into this in more details. Had some other priority work for this week... From the very brief look, I think that moving stuff from "services" module to "federation/ldap" is not ideal solution and can have some side-effects... But I don't have the solution from top of my head right now :(

One quick idea, which comes to my mind, is to somehow change Truststore SPI itself, so that it can be referenced from "federation/ldap", but still keep the implementation (FileTruststoreProvider) in "services" module.

I will try to take a look early next week and hopefully we will be able to figure something.

**Comment by tsaarni** [comment]
Maybe a method could be added to Truststore SPI to get `SSLSocketFactory` with properly initialized truststore.

**Comment by mposolda** [comment]
@tsaarni Yes, I believe something along the lines of this will work.

**Comment by iankko** [comment]
> @tsaarni Yes, I believe something along the lines of this will work.

@mposolda @tsaarni Got the version moving SSLSocketFactory completely working (for both SSL & StartTLS tests). For non-moving version, this seems to be feasible too by enhancing the `TruststoreProvider` / `TruststoreProviderFactory` interfaces with new `getSSLSocketFactory()` method, which would return the correct truststore SPI SSL socket factory to use for TLS (re)negotiation. The code compiles & runs (got rid of previous `Symbol not found` / `ClassNotFoundExceptions` issues) even without the move. But *doesn't work OK* for StartTLS yet. Looking into it yet (can share the branch if you want to look too)

**Comment by mposolda** [comment]
@iankko Thanks for the good news!

Will be good to have this working without a need of move Truststore SPI stuff to the "federation/ldap" . Conceptually the Truststore SPI is not specific to LDAP, so it's implementations shouldn't be moved to "federation/ldap" . In theory, we should be able to remove "federation/ldap" module from Keycloak sources to completely remove the LDAP and still have all the other things working :) This won't be possible with move of Truststore stuff to the "federation/ldap". But anyway, I believe you are close to have this working, so hopefully few other polishing will make this working in the end..

**Comment by iankko** [comment]
@mposolda Got it working without the move of `SSLSocketFactory` too. Created a [new PR](https://github.com/keycloak/keycloak/pull/7152), taking original @tsaarni 's changes from this PR & added changes to get it working for StartTLS tests too. Also enabled the StartTLS tests, since now they work with both Undertow & Wildfly).

This one can be closed once the other one is OK / approved. @mposolda @tsaarni PTAL at the other one once got a chance & let me know, if it's OK / can be as is, or there are some updates needed yet

Thanks!
Jan


> @iankko Thanks for the good news!
> 
> Will be good to have this working without a need of move Truststore SPI stuff to the "federation/ldap" . Conceptually the Truststore SPI is not specific to LDAP, so it's implementations shouldn't be moved to "federation/ldap" . In theory, we should be able to remove "federation/ldap" module from Keycloak sources to completely remove the LDAP and still have all the other things working :) This won't be possible with move of Truststore stuff to the "federation/ldap". But anyway, I believe you are close to have this working, so hopefully few other polishing will make this working in the end..

**Comment by tsaarni** [comment]
closed by https://github.com/keycloak/keycloak/pull/7152

**Comment by mposolda** [comment]
@tsaarni Thanks for all your help with those tests and issues!

**Comment by tsaarni** [comment]
No problem, glad to see it finally working!

**Pull request closed without merging**
