### PR TITLE
KEYCLOAK-13675 allow wildcard subdomains in redirect_urls

### PR DESCRIPTION
**Pull request by spurreiter**
Feature-Request: https://issues.redhat.com/browse/KEYCLOAK-13675

### CODE REVIEW

**Comment by stianst** [comment]
Thanks for your PR, but we will reject this. This has come up before and we have rejected it in the past.

We will not accept wildcards in domains for security reasons. Strictly speaking according to specifications we should not support wildcards in redirect-uris at all and these should be strict string matching.

**Comment by OJezu** [comment]
@stianst 
I cannot find extended discussion about this topic. I found an issue which mentions that spec requires strict matching: https://issues.redhat.com/browse/KEYCLOAK-13675
In which RFC6819 is referenced: https://tools.ietf.org/html/rfc6819#section-5.2.3.5
But, even the section on validating redirect_urls has a note

> Note: Pre-registering clients might not scale in some deployments
>    (manual process) or require dynamic client registration (not
>    specified yet).  With the lack of dynamic client registration, a
>    pre-registered "redirect_uri" only works for clients bound to certain
>    deployments at development/configuration time.  As soon as dynamic
>    resource server discovery is required, the pre-registered
>    "redirect_uri" may no longer be feasible.

RFC6749 https://tools.ietf.org/html/rfc6749#section-10.6 does not specify HOW should redirect_uri be validated:
>   (...) The authorization server
>    MUST require public clients and SHOULD require confidential clients
>    to register their redirection URIs.  If a redirection URI is provided
>    in the request, the authorization server MUST validate it against the
>    registered value.

Our usecase is: We are setting up multiple applications with different configuration with generic domain names of `*.appname.com`. I wanted to use Keycloak to facilitate access for users, who should be able to access all applications. My alternatives are subdomain wildcards, or amending the Keycloak configuration each time a new application is set up.

As are applications are under control of our company, I would say the risks due to wildcard are somewhat limited.

**Comment by ccravens** [comment]
@stianst then we need the ability to programmatically add / remove redirect uris to a client because not all applications know all subdomains. Subdomains can be programmatically launched (microservice architectures and cloud native proxies / kubernetes ingress controllers for example).

Either wildcards for subdomains should be supported or Keycloak needs to offer a way to programmatically add / remove the strict string subdomain as they are generated or deleted.

**Comment by stianst** [comment]
Please see the following discussion as a follow-up:
https://github.com/keycloak/keycloak/discussions/9278

**Pull request closed without merging**
