### PR TITLE
Fix typo in en/identity-providers.json

### PR DESCRIPTION
**Pull request by asyd**
Fix typo in identity-providers

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
@asyd we made some changes to the localization, they are now contained in a single file per locale. Could you rebase your PR on the latest of `main`?

**Comment by asyd** [comment]
@jonkoops done!

**Review by jonkoops — DISMISSED** [review]

**Comment by jonkoops** [comment]
I am still seeing conflicts on the PR so I don't believe the rebase has succeeded.

**Comment by asyd** [comment]
Should be ok now, sorry

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
Great! Thanks for your contribution @asyd!

**Pull request merged**
