### PR TITLE
KEYCLOAK-6073 Support different URLs for front and back channel requests in adapters

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by roidelapluie** [comment]
I know it seems rude to open a PR from someone else's repo but we would like to see this feature implemented. We will contribute changes if we find bugs.

**Comment by roidelapluie** [comment]
We have successfully released this.

**Comment by stianst** [comment]
Thanks for your PR. As a first step before we can review this can you please remove refactoring and code changes that are not required for the issue you are working on and also please squash to a single commit.

**Review by stianst — CHANGES_REQUESTED** [review]
Please cleanup the PR

**Comment by stianst** [comment]
Closing due to lack of feedback

**Comment by sarlaccpit** [comment]
@stianst  Do you know if there is any follow up to this, or some work superseding it?  I have seen the requests for this feature in various forums/JIRAs but never saw it come to fruition and it seems like such a critical feature to have as backend services that validate tokens sometimes just don't have access to the front door external facing public IP of keycloak.

**Comment by gaddamas** [comment]
it looks like @stianst is willing to review this PR if it removes all unrelated changes (like refactoring) and all commits are squashed into single commit.

**Comment by lgraf** [comment]
@sarlaccpit i recently started working on this (SEE: https://issues.jboss.org/browse/KEYCLOAK-6073), sadly i didn't find much time the last to weeks to complete it. I will try to find some time this week to get the current work in a state that can be reviewed.

Progress: https://github.com/keycloak/keycloak/compare/master...lgraf:issues/KEYCLOAK-6073

**Pull request closed without merging**
