### PR TITLE
KEYCLOAK-17841 Add transaction rollback on failed admin event persistence

### PR DESCRIPTION
**Pull request by artur-baltabayev**
https://issues.redhat.com/browse/KEYCLOAK-17841

### CODE REVIEW

**Comment by stianst** [comment]
Thanks, looking at the changes it looks like EventPersistenceFailedException is added but never thrown? I also can't see how this PR makes any changes to rollback if a event is not persisted, it seems to only make changes to how the id is set.

**Comment by artur-baltabayev** [comment]
Hello,
our idea was to make it optional, so that you can implement your own store and throw the excpetion if you want to.
This was due to concerns, that someone might depend on the old behavior.
The rollback would happen due to the exception being thrown at the API level, which then triggers a rollback automatically (by some handler).
Previously this exception was checked, so nothing happened even if the event couldn’t be persisted for any reason.

**Comment by jbman** [comment]
@stianst: An `EventStoreProvider` should get the chance to abort the requested operation and rollback the transaction if it could not process the event (=persist or forward to some messaging system). With proposed `EventPersistenceFailedException` it gets the option to do so while maintaining backward compatibility with any existing 'EventStoreProvider` including the default `JpaEventStoreProvider`.
The ID at the event is important to reference the stored event in a custom implementation which wraps `JpaEventStoreProvider`.
The custom implementation will send the event to a messaging system and will also ensure at least-once-delivery to this system.

**Comment by stianst** [comment]
I don't like the approach with the EventPersistenceFailedException as that requires a custom store to get this behaviour, and also is a bit odd. I actually think it was an outright mistake to catch this exception and that failing to store the event should be a failure to process the request by default. As I mentioned we can make this configurable in the default event store provider, where it would itself catch the exception and just log it, which provide the current behaviour for those that want it.

**Comment by stianst** [comment]
Can you elaborate a bit on the changes to IDs? I thought we already set the IDs to events, so not following why these changes are needed.

**Comment by jbman** [comment]
@stianst thanks for feedback.  We are also fine with your proposal, so that we could

- Remove the catch-and-log statement at `AdminEventsBuilder`. 
- Define an environment variable which is used at `JpaEventStoreProvider`. The variable must be set so that the provider restores old behavior of catch-and-log. Or is there an other way you had in mind to make this configurable?

We did not go this way initially, as existing custom `EventStoreProvider` implementations may rely on existing behavior where the transaction is completed with just the log entry. But of cause they can also by updated their authors to catch and log on their own.

**Comment by jbman** [comment]
The IDs are currently generated at `AdminEventEntity` level and not exposed to the SPI at the `AdminEvent` class. We would like to have the ID generated earlier when the AdminEvent is created. so that it as available to a custom provider implementation.

Use case:
Exposing the ID allows for wrapping the default `JpaEventStoreProvider` in an own provider implementation and managing additional data in relation to an event. This allows the custom provider to distribute events to another system reliably at-least-once. The custom provider needs an event ID to keep track of the events to be delivered (in an own storage, processed asynchronously).

**Comment by stianst** [comment]
> @stianst thanks for feedback. We are also fine with your proposal, so that we could
> 
> * Remove the catch-and-log statement at `AdminEventsBuilder`.
> * Define an environment variable which is used at `JpaEventStoreProvider`. The variable must be set so that the provider restores old behavior of catch-and-log. Or is there an other way you had in mind to make this configurable?
> 
> We did not go this way initially, as existing custom `EventStoreProvider` implementations may rely on existing behavior where the transaction is completed with just the log entry. But of cause they can also be updated their authors to catch and log on their own.

This stuff is how it should be configured, which would make it configurable through standalone.xml:
https://github.com/keycloak/keycloak/blob/master/server-spi/src/main/java/org/keycloak/provider/ProviderFactory.java#L41

**Comment by stianst** [comment]
> The IDs are currently generated at `AdminEventEntity` level and not exposed to the SPI at the `AdminEvent` class. We would like to have the ID generated earlier when the AdminEvent is created. so that it as available to a custom provider implementation.
> 
> Use case:
> Exposing the ID allows for wrapping the default `JpaEventStoreProvider` in an own provider implementation and managing additional data in relation to an event. This allows the custom provider to distribute events to another system reliably at-least-once. The custom provider needs an event ID to keep track of the events to be delivered (in an own storage, processed asynchronously).

Ah, okay, that makes sense

**Comment by mhajas** [comment]
@hmlnarik if I undestand correctly, the problem here is that `AdminEventBuilder` is ignoring all exceptions that come from calling `onEvent` method. The fix is that we choose one exception, that implementors of listeners can throw that will cause that error status is thrown out of the application. 

I believe the better way of solving this is using `EventListenerTransaction` (or some other implementation of `KeycloakTransaction`) as you suggested. Exceptions are not ignored when doing commit, therefore this will solve the issue as well.

@artur-baltabayev You can have a look at JavaDoc here: https://github.com/keycloak/keycloak/blob/master/server-spi-private/src/main/java/org/keycloak/events/EventListenerProvider.java. and https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/events/log/JBossLoggingEventListenerProvider.java#L44

**Comment by stianst** [comment]
The fix here is simple - we should just not catch the exception, which removes the need to introduce the new exception, and makes it easy for a provider itself to decide if it should throw the exception, or itself catch the exception. This can easily be made configurable through provider config for the built-in provider.

**Comment by stianst** [comment]
I'm going to close this for now - could you send two separate PRs instead please:

* Changes to how event ID is being set
* Not catching the exception if an event is not saved successfully

**Comment by artur-baltabayev** [comment]
Thank you very much for your suggestions !

@mhajas @hmlnarik Sorry for responding so late. The solution proposed by Stian fits us very well and we will be sending the PRs shortly.

**Comment by artur-baltabayev** [comment]
Here are the new PRs:

- https://github.com/keycloak/keycloak/pull/8166 (Admin Event exception handling)
- https://github.com/keycloak/keycloak/pull/8167 (Admin Event ID)

**Comment by hongquyen196** [comment]
Hello @artur-baltabayev  this topic I am interested in. When will the pull request merge?

**Pull request closed without merging**
