### PR TITLE
[PULL-REQUEST-3181 & PULL-REQUEST-3233] Username is not displayed on the login screen with that email

### PR DESCRIPTION
**Pull request by betovieirasilva**
When keycloak is set to login email and Username is different from email, to check the "Remember Me" username is not displayed on the login screen with that email because the KEYCLOAK_REMEMBER_ME cookie is always recorded the username field.

### CODE REVIEW

**Comment by stianst** [comment]
Can you create a JIRA issue please?

**Comment by betovieirasilva** [comment]
@stianst 

https://issues.jboss.org/browse/KEYCLOAK-3524

Thanks

**Comment by stianst** [comment]
Changes are good. A testcase is missing though. That can be added to org.keycloak.testsuite.forms.LoginTest. You've applied the changes to the wrong branch. You need to send PR to the master branch as we're no longer maintaining/releasing 1.9 in community.

**Comment by betovieirasilva** [comment]
@stianst

I have included the test case:
https://github.com/keycloak/keycloak/pull/3181/commits/aa169a6ac4c7c5ae696dd33f00e7045c41fbddc5

**Here, there is the fail in old version (1.9.4)**
17:22:10,647 INFO  [LoginTest] loginWithEmailUserAndRememberMe() STARTED
17:22:10,791 DEBUG loading test realms
17:22:10,792 INFO  importing test realms
17:22:10,792 DEBUG importing realm: test
17:22:11,321 INFO  removing test realms
17:22:11,716 ERROR [LoginTest] loginWithEmailUserAndRememberMe() FAILED
17:22:11,717 INFO  [LoginTest] loginWithEmailUserAndRememberMe() FINISHED


Tests run: 20, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 32.706 sec <<< FAILURE! - in org.keycloak.testsuite.forms.LoginTest
loginWithEmailUserAndRememberMe(org.keycloak.testsuite.forms.LoginTest)  Time elapsed: 2.535 sec  <<< FAILURE!
org.junit.ComparisonFailure: **expected:<login[@test.com]> but was:<login[-test]>**
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.keycloak.testsuite.forms.LoginTest.loginWithEmailUserAndRememberMe(LoginTest.java:507)


**Here, after applied the path**
17:48:14,841 INFO  [LoginTest] loginWithEmailUserAndRememberMe() STARTED
17:48:14,995 DEBUG loading test realms
17:48:14,996 INFO  importing test realms
17:48:14,996 DEBUG importing realm: test
17:48:17,242 INFO  removing test realms
17:48:17,336 INFO  [LoginTest] loginWithEmailUserAndRememberMe() FINISHED	

**I will do the merge to the master**

Thanks

**Comment by betovieirasilva** [comment]
@stianst

[PULL-REQUEST-MASTER]
https://github.com/keycloak/keycloak/pull/3233

**Comment by stianst** [comment]
Thanks - closing this PR, and will merge #3233

**Pull request closed without merging**
