### PR TITLE
add i8n for pt-BR

### PR DESCRIPTION
**Pull request by jean-merelis**

### CODE REVIEW

**Comment by stianst** [comment]
Rejecting this issue as there is no corresponding jira and no description of the work other than the commit comment. There are also changes that do not apply to adding pt-BR language (changes to messages_de.properties, locale_de=Deutsch and FreeMarkerEmailProvider).

**Comment by stianst** [comment]
To accept a translation we need to have someone that's willing to maintain it, not just provide the initial translation. Would you be willing to do this? If so I'd like a PR from you that only includes the translation. Any other changes please raise JIRA's and submit separate PRs for those.

**Comment by jean-merelis** [comment]
_"Would you be willing to do this?"_
Yes, I would be willing.

I'll make a PR.

**Comment by stianst** [comment]
Great, thanks :)

**Pull request closed without merging**
