### PR TITLE
KEYCLOAK-19159 KcSamlEncryptedIdTest failure for undertow

### PR DESCRIPTION
**Pull request by mabartos**
JIRA: [KEYCLOAK-19159](https://issues.redhat.com/browse/KEYCLOAK-19159)

### CODE REVIEW

**Comment by mabartos** [comment]
@mhajas Pipeline tests passed. See https://keycloak-jenkins.com/job/universal-test-pipeline-server/738/

**Review by mhajas — APPROVED** [review]
Thanks for the fix @mabartos! This is my fault it got there. 

The real reason behind the failure seems to be the wrong port setting on [this line](https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/saml/AbstractSamlTest.java#L46). It should be enough to use `AUTH_SERVER_PORT` as it already contains the correct port based on SSL enabled/disabled. On the other hand, we don't know how many tests would fail after the change, maybe for some tests it is important to have `8080` there, therefore I think it is a better idea to merge this as you suggested. We already use `getConsumerRoot()` in many similar places.

nitpick: This would work even without the addition of the `+ ".dot/ted"` suffix to the issuer, but since the client that is used for this test does not matter we can leave it as is.

**Comment by mabartos** [comment]
@mhajas Thanks for explanation!

**Review by hmlnarik — APPROVED** [review]
Approving per @mhajas 's review

**Pull request merged**
