### PR TITLE
explicitly set UTF-8 as stdin and stdout encoding

### PR DESCRIPTION
**Pull request by sbaeurle**
This fixes encoding issues when running Keycloak in nanoserver based windows containers! #16226

### CODE REVIEW

**Review by pedroigor — APPROVED** [review]
@sbaeurle It should work if you are using JDK up to 18.

But it changed in JDK 19. See https://www.oracle.com/java/technologies/javase/19-relnote-issues.html. In this version, the property changed to `stdout.encoding` and `stderr.encoding` . See https://bugs.openjdk.org/browse/JDK-8284778.

IMO, we can have those properties also set.

@vmuzikar The change here makes sense for me so that we can allow running in nanoserver containers.

**Review by pedroigor — CHANGES_REQUESTED** [review]
Pending discussion.

**Comment by pedroigor** [comment]
@sbaeurle Can you please:

* Squash your commits
* Change the commit message to reference the issue as per https://github.com/keycloak/keycloak-containers/blob/main/CONTRIBUTING.md

Thanks.

**Comment by sbaeurle** [comment]
@pedroigor adjusted git log according to your comments.

**Review by vmuzikar — CHANGES_REQUESTED** [review]
I'm a bit worried that since we don't have any tests for it to verify it actually fixes the Win nanoserver, we will simply miss the required changes for JDK 19+.

Should we maybe at least add the new env vars `stdout.encoding` and `stderr.encoding` right away? It shouldn't do any harm, right?

**Comment by sbaeurle** [comment]
okay, i will add ` -Dstdout.encoding=UTF-8 -Dstderr.encoding=UTF-8` to the java properties as well!

**Comment by sbaeurle** [comment]
updated the script and rebased the branch

**Review by pedroigor — DISMISSED** [review]

**Review by pedroigor — DISMISSED** [review]

**Comment by sschu** [comment]
Would it hurt to also have this in the `kc.sh` just for symmetry?

**Comment by pedroigor** [comment]
@sbaeurle Sorry. Can we also update `kc.sh` as suggested by `sschu`?

I was fine about having this only in `kc.bat` but let's avoid increasing the gap between the two scripts :)

**Comment by sbaeurle** [comment]
@pedroigor sorry for the delay, the scripts should be adjusted now 👍

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks @sbaeurle!

**Pull request merged**
