### PR TITLE
KEYCLOAK-19532 Finnish locales

### PR DESCRIPTION
**Pull request by EVP1989**
Added finnish locales

### CODE REVIEW

**Review by stianst — COMMENTED** [review]
Could you please change to utf-8 encoding (see other translations on how to do that, it's just a header on the property file)? We also need someone to review this. Could you add someone you know or ask on the dev mailing list for a review?

**Comment by EVP1989** [comment]
Hello @stianst, thanks for the reply. I have already joined the dev mailing list and asked (https://groups.google.com/g/keycloak-dev/c/hxkY6Yp0X5Q) someone to review this.

I will make the changes and fix that minor conflict.

**Comment by Daniilmass** [comment]
@stianst Hi! How is the review process going? Could this be merged?

**Comment by YuGongYu** [comment]
i'm a local who speaks Finnish fluently (dont let my name suprise you, yes in FIN xD). I have reviewed the translations and they seem good :).  We have an equity research company in Finland www.inderes.fi and we are planning to use Keycloak as our SSO in Sweden and Finland :) Tell me if you need more review.

**Comment by badrange** [comment]
Hi @stianst - did you notice @YuGongYu 's comment above where he states that he has reviewed the translation?

**Comment by badrange** [comment]
@EVP1989 we found a bug in one of the strings, we ended up using this string for federatedIdentityConfirmReauthenticateMessage. 

`federatedIdentityConfirmReauthenticateMessage=Tunnistaudu linkittääksesi {0}-tilin.`

**Comment by badrange** [comment]
Thank you @anttileppa ! 
We also found some strings in our use case (an external identity provider) that were missing translations (and I think they are not even translated inside Keycloak): 
```
idp-email-verification-display-name=Sähköpostilla
idp-email-verification-help-text=Tunnistaudu sähköpostiin lähetetyllä linkillä
idp-username-password-form-display-name=Kirjautumalla
idp-username-password-form-help-text=Tunnistaudu kirjautumalla sisään käyttäjänimellä ja salasanalla
```

**Comment by anttileppa** [comment]
@badrange do you mean org.keycloak.authentication.authenticators.broker.IdpEmailVerificationAuthenticatorFactory and org.keycloak.authentication.authenticators.broker.IdpUsernamePasswordFormFactory translations?

If that is the case, I think that it's a bit out of scope of this PR because those factory help texts and display types do not seem to be localizable in Keycloak (see https://github.com/keycloak/keycloak/blob/99c06d11023689875b48ef56442c90bdb744c869/services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpUsernamePasswordFormFactory.java#L45 for example).

**Comment by badrange** [comment]
> (...)  I think that it's a bit out of scope of this PR because those factory help texts and display types do not seem to be localizable in Keycloak (see
> 
> https://github.com/keycloak/keycloak/blob/99c06d11023689875b48ef56442c90bdb744c869/services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpUsernamePasswordFormFactory.java#L45
> for example).

Indeed out of scope!

"someone" should make an issue about these strings not being localizable..

**Comment by badrange** [comment]
> Great! So maybe it could be reviewed now?

From our perspective - yes!

We have been using these translations in our production sso for a few weeks, thank you so much for your efforts!

**Review by ahus1 — CHANGES_REQUESTED** [review]
Hi @EVP1989, I did a review and it looks good. The translation as such has already been approved by some native speakers, that's great!

I found just two things: 

* one miss-spelled property (see below)
* there is no entry `locale_fi=Suomi` in `account/messages_en.properties` and login/messages/messages_en.properties`. This leads to the following undesired behavior: When choosing English as the locale, the drop down box on the login screen shows only "fi" as the language to select where it should show "Suomi". Please add the entry to both files.

Please look after these two issues. Once they are in, I'll then reach out to a maintainer to merge it.

**Comment by anttileppa** [comment]
@ahus1 both issues should be fixed now

**Comment by ahus1** [comment]
@anttileppa - sorry, one last thing that I missed: Could you please add the issue number KEYCLOAK-19532 to the commit message? Without that issue number we would otherwise not be able to track back from the commit to the issue and this PR. Thanks!

**Review by ahus1 — APPROVED** [review]

**Comment by ahus1** [comment]
I have tested the latest theme with the current main branch it it works nicely; the login page and the account UI can be switched to Finnish locale.

**Comment by ahus1** [comment]
Hi @ssilvert - here's a new Finnish translation that I reviewed and tested. The translation has been done by the community, reviewed by the community and reading the comments is already actively used by the community. 

I'd be happy if you as the area lead for the UIs could give it a final approval and merge it. Thanks

**Review by ssilvert — APPROVED** [review]

**Pull request merged**
