### PR TITLE
Add missing Arabic messages

### PR DESCRIPTION
**Pull request by Eng-Fouad**

### CODE REVIEW

**Comment by Eng-Fouad** [comment]
@Mouhand-Kaddo Could you please review this? Thanks.

**Comment by alfayez91** [comment]
I reviewed this PR and it looks good to me.

**Comment by Eng-Fouad** [comment]
@jonkoops @ssilvert Could you please approve and merge this PR? Thanks.

**Review by edewit — APPROVED** [review]

**Review by ssilvert — APPROVED** [review]

**Comment by jonkoops** [comment]
Thanks @alfayez91 @Eng-Fouad!

**Pull request merged**
