### PR TITLE
[Keycloak-1427] Updated Delete icons with 'pointer' as hovering cursor.

### PR DESCRIPTION
**Pull request by girirajsharma**

### CODE REVIEW

**Comment by stianst** [comment]
CSS styles shouldn't be added directly to elements. Add the styles to the stylesheet and use a class instead. Need to make sure there's not an existing way to do this in PatternFly before adding custom styles though.

**Comment by girirajsharma** [comment]
patternfly pficon css doesn't already have cursor set to 'pointer'. agalante said as the pficons aren't always clickable, they haven't added any particular type of cursor to it's css. I will go with adding the style into a stylesheet and use it as a class.

**Comment by stianst** [comment]
You should be able to use a <button> instead of <i> and that'll have the correct cursor.

**Comment by girirajsharma** [comment]
I hope you mean adding required css into some existing css file used by KC and not in patternfly.css itself.

**Comment by stianst** [comment]
Yes, add to styles.css in the admin keycloak theme. Ideally there shouldn't be any styles in here though as we should rely on default PatternFly ways to do things. Hence why using a button is probably the better approach as it'll already have the correct cursor.

**Comment by stianst** [comment]
I don't like the addition of a custom class. We try to avoid that.

We should add the following styles instead:
```
.clickable {
	cursor: pointer;
}

h1 i {
    color: #999999;
    font-size: 18px;
    margin-left: 10px;
}
```

The HTML for the button should be:
```
<i class="pficon pficon-delete clickable" ...></i>
```

**Comment by girirajsharma** [comment]
Updated as stated/required.

**Pull request merged**
