### PR TITLE
KEYCLOAK-8098 use html5 email validation

### PR DESCRIPTION
**Pull request by edewit**
fixing KEYCLOAK-8098

### CODE REVIEW

**Comment by edewit** [comment]
opened in favor of #6510 now uses html5 email validation

**Comment by ssilvert** [comment]
@edewit The code itself looks fine.  Just make sure it follows https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/forms

Also, make sure you run linting and fix any errors.  Soon this will be part of the Travis build but for now we need to do it manually.

**Comment by edewit** [comment]
I ran `npm run lint` but that didn't output anything. I only extended the validation that was there with email, but it seems that the [`*` on all the fields](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/forms#indicating-required-fields) is wrong, but maybe that  needs to be a separate issue?

**Comment by ssilvert** [comment]
> I ran `npm run lint` but that didn't output anything. I only extended the validation that was there with email, but it seems that the [`*` on all the fields](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/forms#indicating-required-fields) is wrong, but maybe that needs to be a separate issue?

@edewit Go ahead and fix that if you want.

**Comment by edewit** [comment]
@ssilvert it's something that needs to be addressed in patternfly react

**Comment by ssilvert** [comment]
@edewit This is a little tricky.  Not all fields are necessarily required.  Also, this is customizable so that customers might add additional fields which may or may not be required.

**Comment by edewit** [comment]
Then it's all good:
image

**Comment by ssilvert** [comment]
> I ran `npm run lint` but that didn't output anything.

That's funny.  I'm getting a few hits on code I haven't touched.  Unless you aren't looking at recent code, you should at least see this one:
`C:\GitHub\keycloak\themes\src\main\resources\theme\keycloak-preview\account\resources\app\content\applications-page\ApplicationsPage.tsx
  135:121  warning  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank`

**Comment by edewit** [comment]
I get:
```
 KEYCLOAK-8098  git status
On branch KEYCLOAK-8098
Your branch is up to date with 'origin/KEYCLOAK-8098'.

nothing to commit, working tree clean
 edewit@localhost  ~/workspace/keycloak/keycloak/themes/src/main/resources/theme/keycloak-preview/account/resources   KEYCLOAK-8098  npm run lint

> keycloak-preview@1.0.0 lint /home/edewit/workspace/keycloak/keycloak/themes/src/main/resources/theme/keycloak-preview/account/resources
> eslint --ignore-pattern *.d.ts ./**/*.ts*

 edewit@localhost  ~/workspace/keycloak/keycloak/themes/src/main/resources/theme/keycloak-preview/account/resources   KEYCLOAK-8098  
```

**Comment by ssilvert** [comment]
> and also `ApplicationsPage` is not changed by this PR

I'm not changing that page either.  This one slipped by on another PR somewhere.  I wonder why I see it but you don't.  BTW, you should also see this one:
`C:\GitHub\keycloak\themes\src\main\resources\theme\keycloak-preview\account\resources\app\account-service\account.service.ts
  107:54  warning  'reject' is defined but never used  @typescript-eslint/no-unused-vars`

**Comment by edewit** [comment]
don't know what to tell you just removed my `node_modules` folder and did an `npm i` followed by a `npm run lint` and still no output maybe we should create a separate PR to fix all the linting errors as this PR doesn't introduce any new lint errors.

**Comment by edewit** [comment]
created #6687 to address the lint output problem

**Comment by edewit** [comment]
changed commit message to the standard

**Review by ssilvert — APPROVED** [review]
LGTM

**Pull request merged**
