### PR TITLE
KEYCLOAK-4776 include newly created tests to travis

### PR DESCRIPTION
**Pull request by vramik**

### CODE REVIEW

**Comment by stianst** [comment]
Looks like PolicyEvaluationCompositeRoleTest needs to be fixed first

**Comment by vramik** [comment]
@stianst indeed, there is https://issues.jboss.org/browse/KEYCLOAK-4732 for this.

**Comment by pedroigor** [comment]
@stianst and @vramik. Going to push a fix for KEYCLOAK-4732 today.

**Comment by pedroigor** [comment]
@vramik , can you check it out https://github.com/keycloak/keycloak/pull/4075 ?

**Comment by vramik** [comment]
@pedroigor checked, it works with https://github.com/keycloak/keycloak/pull/4075 on undertow, for wildfly I had to add https://github.com/keycloak/keycloak/pull/4076

**Pull request merged**
