### PR TITLE
[KEYCLOAK-8071] - Properly validating requested scopes

### PR DESCRIPTION
**Pull request by pedroigor**
I also added the check to the authorization endpoint as per OAuth2 spec. One may argue that it would introduce an additional check and potentially a performance penalty to authorization requests, but to be compliant we need it.

### CODE REVIEW

**Comment by mposolda** [comment]
LGTM and I am for including this PR.

However not sure whether to include this in 9.0.4 . It is potentially breaking change as some applications may already use invalid (non-existent/non-granted) "scope" parameter for some reason (similarly like our unit tests, which @pedroigor needed to fix in this PR).

So my personal vote is to postpone this to 10.0 and maybe also add some docs around this - at least mention that invalid scopes will be rejected. Because OAuth2 specification doesn't necessarily enforce that requests with invalid scopes must be rejected. See my JIRA comment for details https://issues.redhat.com/browse/KEYCLOAK-8071?focusedCommentId=14016762&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14016762 .

@stianst @pedroigor @hmlnarik @pdrozd WDYT?

**Comment by stianst** [comment]
From reading the spec that's not how I interpret it. I interpret that an invalid/unknown/etc scope should result in an invalid_scope error response.

Section 3-3 on the other hand is about the returned scope may not match the requested scope. This is for example when a user can opt-out of a requested scope and doesn't grant all the scopes.

From my understanding of the specification our implementation is incorrect. If anyone is using invalid scopes I would argue it is better for them to know about it and resolve the issue than for us to continue silently ignoring it. Then again I don't think this is such a critical thing that we need to make such a change in 9.0.4 and it can wait for Keycloak 10.

So my vote is +1 to postponing to 10 to be on the safe side.

**Comment by mposolda** [comment]
@stianst Thanks, you're indeed right regarding the specs. I am sorry for the confusion :)

Are we in agreement with move this to 10.0? I guess this would mean changing milestone of this PR, changing JIRA fix version and removing @hmlnarik and @pdrozd as assignees of this?

**Review by mposolda — APPROVED** [review]

**Comment by ricardofragacamelo** [comment]
Hello folks, I got a problem with this validation, and raised a bug in keycloak, but I agree with the validation that is implemented, but I disagree the way that it was Implemented, a static method directley in the token endpoint, couldn it be an SPI, that could be overriden, or that validation could be overriden in a client level?

**Pull request merged**
