### PR TITLE
[KEYCLOAK-9634] Keycloak Testhelper uses wrong url

### PR DESCRIPTION
**Pull request by yelhouti**
This is a small typo that is blocking me.

Thanks in advance

### CODE REVIEW

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Comment by yelhouti** [comment]
@pedroigor I think it's finished :)

**Comment by yelhouti** [comment]
@pedroigor, please can you merge this, thanks

**Comment by stianst** [comment]
JIRA is missing and commit message needs updating. Please see https://github.com/keycloak/keycloak/blob/master/CONTRIBUTING.md for details

**Comment by abstractj** [comment]
@yelhouti please, see the comments Stian made.

**Comment by pedroigor** [comment]
@yelhouti, thanks for this one. Could you please consider Stian's comments? 

Please, just create a JIRA and update both commit messages and PR title to reference it. Consider looking at any PR closed as an example.

**Comment by yelhouti** [comment]
https://issues.jboss.org/browse/KEYCLOAK-9634 it has been rebased and can be merged now.

**Comment by pedroigor** [comment]
@yelhouti, you are only missing the commit message. Please, change it to `[KEYCLOAK-9634] Keycloak Testhelper uses wrong url`

**Comment by yelhouti** [comment]
@pedroigor my bad, though I did, it's done now

**Review by pedroigor — DISMISSED** [review]

**Comment by pedroigor** [comment]
tks

**Comment by yelhouti** [comment]
@pedroigor thank you :)

**Comment by pedroigor** [comment]
@keycloak-ci-bot  test

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Comment by pedroigor** [comment]
@yelhouti, could you rebase again, please ? CI finally gave a green flag but I can't merge because of conflicts.

I hope next time CI will will not take so long :)

**Comment by yelhouti** [comment]
@pedroigor it's done

**Comment by yelhouti** [comment]
@keycloak-ci-bot test

**Comment by abstractj** [comment]
@keycloak-ci-bot test

**Review by abstractj — DISMISSED** [review]

**Comment by yelhouti** [comment]
@abstractj sorry for doing this to you again, it seems that a test file was deleted by me in the last commit, don't know how. I added it and forced push, sorry you have to run the tests again

**Comment by abstractj** [comment]
@yelhouti absolutely no problem. Test are automated, so we just need to hear something back from Travis and Jenkins :)

**Comment by abstractj** [comment]
@keycloak-ci-bot test

**Comment by abstractj** [comment]
@keycloak-ci-bot test

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
