### PR TITLE
[KEYCLOAK-6584] removed not-before-policy parameter from authorization response

### PR DESCRIPTION
**Pull request by alicerum**

### CODE REVIEW

**Comment by stianst** [comment]
@wyvie thanks. Looks good to me, but would like @mposolda to comment as well

**Comment by wyvie** [comment]
i also want to do pull-request on KEYCLOAK-6585.
issue is similar. should i add it as part of this same PR?

**Comment by stianst** [comment]
Should be separate PR

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
@wyvie Thanks. I bet KEYCLOAK-6585 will be now much easier for you with the lesson learned from this one :)

**Pull request merged**
