### PR TITLE
KEYCLOAK-19054 make form buttons consistent

### PR DESCRIPTION
**Pull request by McLaynV**
https://issues.redhat.com/browse/KEYCLOAK-19054

This PR fixes the button class inconsistency between login theme and account theme: 

https://github.com/keycloak/keycloak/blob/afa6e31d367ed90912a01dae279b0261ae737a74/themes/src/main/resources/theme/keycloak/login/theme.properties#L78

https://github.com/keycloak/keycloak/blob/afa6e31d367ed90912a01dae279b0261ae737a74/themes/src/main/resources/theme/keycloak/account/theme.properties#L11

### CODE REVIEW

**Comment by mposolda** [comment]
@Pepo48 Do you please have a chance to review this once you have time? I think it is not a top level priority, just fyi.

**Comment by Pepo48** [comment]
@McLaynV (cc: @mposolda) we changed this back when we were working on the upgrade of the Login screen to the PatternFly framework[1]. This PR is suggesting to use the same class as before the upgrade.

This happens with the main button design after applying the suggested:
image

This is how it looks like in the current master - when `kcButtonPrimaryClass=pf-m-primary` is used.
image

If there's still an inconsistency with the new account console I think it should be resolved on the account console level.
Therefore I would not merge this one. But let me know if the intention was different.

Thanks!

[1] https://github.com/keycloak/keycloak/commit/a8df7d88a1c9a223ec4a5f07999986d8a352b2be#diff-4265bb2b06e09bb38ba532b3437347f97ac8be455a4ff9f7e9ecd243deb68df0R70

**Comment by mabartos** [comment]
Agree with @Pepo48.

**Comment by mposolda** [comment]
@Pepo48 @mabartos Thanks!

@McLaynV I am closing this based on the feedback from @Pepo48 and @mabartos . Also I see lots of failing tests, which seem to be related to your latest change.

If you think this should be re-opened, please provide the details why it should be considered.

**Pull request closed without merging**
