### PR TITLE
Add nashorn javascript engine to Keycloak server

### LINKED ISSUE #17671: docker image 21.0.1 lacks a Javascript engine
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

Docker image 21.0.1 packs Java 17. Docker images of version 20 and below pack Java version 11 (or lower), which come with a built in Javascript engine. Java 17 doesn't include a Javascript engine, but the Dockerfile hasn't been adjusted accordingly. There are some policies within Keycloak that are implemented using Javascript. Keycloak crashes when it tries to execute these policies.

### Version

21.0.1

### Expected behavior

Keycloak is able to execute policies that are implemented using Javascript.

### Actual behavior

Keycloak crashes when trying to execute policies that are implemented using Javascript.
Stacktrace excerpt:
```
java.lang.IllegalStateException: Could not find ScriptEngine for script: Script{id='null', realmId='284fe926-ab97-4df7-bd7d-36702b20e869', name='Default Policy', type='text/javascript', code='// by default, grants any permission associated with this policy
$evaluation.grant();
', description='A policy that grants access only for users within this realm'}
	at org.keycloak.scripting.DefaultScriptingProvider.getPreparedScriptEngine(DefaultScriptingProvider.java:114)
	at org.keycloak.scripting.DefaultScriptingProvider.prepareEvaluatableScript(DefaultScriptingProvider.java:74)
	at org.keycloak.scripting.DefaultScriptingProvider.prepareEvaluatableScript(DefaultScriptingProvider.java:37)
	at org.keycloak.authorization.policy.provider.js.JSPolicyProviderFactory.lambda$getEvaluatableScript$0(JSPolicyProviderFactory.java:111)
	at org.keycloak.authorization.policy.provider.js.ScriptCache.lambda$computeIfAbsent$0(ScriptCache.java:81)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
	at org.keycloak.authorization.policy.provider.js.ScriptCache.computeIfAbsent(ScriptCache.java:81)
	at org.keycloak.authorization.policy.provider.js.JSPolicyProviderFactory.getEvaluatableScript(JSPolicyProviderFactory.java:108)
	at org.keycloak.authorization.policy.provider.js.JSPolicyProvider.evaluate(JSPolicyProvider.java:46)
	at org.keycloak.authorization.policy.provider.permission.AbstractPermissionProvider.evaluate(AbstractPermissionProvider.java:56)
	at org.keycloak.authorization.policy.provider.permission.ResourcePolicyProvider.evaluate(ResourcePolicyProvider.java:47)
	at org.keycloak.authorization.policy.evaluation.DefaultPolicyEvaluator.lambda$createPolicyEvaluator$0(DefaultPolicyEvaluator.java:117)

```

### How to Reproduce?

Start docker image:
`docker run -d -e "KEYCLOAK_ADMIN=admin" -e "KEYCLOAK_ADMIN_PASSWORD=admin" -e KC_HOSTNAME_STRICT=false -e KC_HOSTNAME_STRICT_HTTPS=false -p 8080:8080 --name keycloak "quay.io/keycloak/keycloak:21.0.1" start-dev`

Wait for Keycloak to be up and running.
Run this shell script:
```
#!/bin/bash

echo Login admin
RESPONSE=$(curl -s -d client_id=admin-cli -d username=admin -d password=admin -d grant_type=password http://localhost:8080/realms/master/protocol/openid-connect/token)
#echo response: $RESPONSE
ADMIN_TOKEN=$(echo -n $RESPONSE | node -pe "JSON.parse(require('fs').readFileSync('/dev/stdin').toString()).access_token")
echo create realm
curl -s -H "Authorization: bearer ${ADMIN_TOKEN}" --json '{"realm":"test_realm","enabled":true}' http://localhost:8080/admin/realms
echo create test user
RESPONSE=$(curl -s -H "Authorization: bearer ${ADMIN_TOKEN}" --json '{"username":"test_user","enabled":true,"credentials":[{"type":"password","value":"test-pass","temporary":false}]}' -w '%header{Location}' http://localhost:8080/admin/realms/test_realm/users)
#echo response: $RESPONSE
TEST_USER=$(echo -n $RESPONSE | node -pe "require('fs').readFileSync('/dev/stdin').toString().split('/').pop().trim()")
echo create test client
RESPONSE=$(curl -s -H "Authorization: bearer ${ADMIN_TOKEN}" --json '{"clientId":"test_auth_client","clientAuthenticatorType":"client-secret","redirectUris":["*"],"webOrigins":["*"],"bearerOnly":false,"serviceAccountsEnabled":true,"authorizationServicesEnabled":true,"publicClient":false,"protocol":"openid-connect"}' -w '%header{Location}' http://localhost:8080/admin/realms/test_realm/clients)
#echo response: $RESPONSE
TEST_AUTH_CLIENT=$(echo -n $RESPONSE | node -pe "require('fs').readFileSync('/dev/stdin').toString().split('/').pop().trim()")
echo get id of realm-management client
RESPONSE=$(curl -s -H "Authorization: bearer ${ADMIN_TOKEN}" http://localhost:8080/admin/realms/test_realm/clients?clientId=realm-management)
#echo response: $RESPONSE
REALM_MGMT_CLIENT=$(echo -n $RESPONSE | node -pe "JSON.parse(require('fs').readFileSync('/dev/stdin').toString())[0].id")
echo get id of realm mgmt role
RESPONSE=$(curl -s -H "Authorization: bearer ${ADMIN_TOKEN}" http://localhost:8080/admin/realms/test_realm/clients/${REALM_MGMT_CLIENT}/roles/realm-admin)
#echo response: $RESPONSE
REALM_MGMT_ROLE=$(echo -n $RESPONSE | node -pe "JSON.parse(require('fs').readFileSync('/dev/stdin').toString()).id")
echo assign mgmt role to test user
curl -H "Authorization: bearer ${ADMIN_TOKEN}" --json "[{\"id\":\"${REALM_MGMT_ROLE}\",\"name\":\"realm-admin\",\"description\":\"role_realm-admin\",\"composite\":true,\"clientRole\":true,\"containerId\":\"${REALM_MGMT_CLIENT}\",\"attributes\":{}}]" http://localhost:8080/admin/realms/test_realm/users/${TEST_USER}/role-mappings/clients/${REALM_MGMT_CLIENT}
echo Login test user
RESPONSE=$(curl -s -d client_id=admin-cli -d username=test_user -d password=test-pass -d grant_type=password http://localhost:8080/realms/test_realm/protocol/openid-connect/token)
#echo response: $RESPONSE
TEST_USER_TOKEN=$(echo -n $RESPONSE | node -pe "JSON.parse(require('fs').readFileSync('/dev/stdin').toString()).access_token")
echo get uma ticket
curl -s -H "Authorization: bearer ${TEST_USER_TOKEN}" -d audience=test_auth_client -d grant_type=urn:ietf:params:oauth:grant-type:uma-ticket http://localhost:8080/realms/test_realm/protocol/openid-connect/token
```

The last line will output `{"error":"server_error","error_description":"Unexpected error while evaluating permissions"}`. Command `docker logs keycloak` will show the server error.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mposolda**
closes #17671

### CODE REVIEW

**Review by pedroigor — APPROVED** [review]

**Comment by mposolda** [comment]
@andymunro Could you please review documentation changes in this PR?
@pskopek Could you please review this from the productization perspective? I will send some details related to this

**Review by pskopek — APPROVED** [review]
Nashorn version 15.4 is OK for productization.

**Comment by mposolda** [comment]
@pskopek Thanks!

**Comment by mposolda** [comment]
@pedroigor Thanks Pedro as well for the review!

**Pull request merged**
