### PR TITLE
Fix `DefaultHostnameTest` on Undertow

### PR DESCRIPTION
**Pull request by vmuzikar**

### CODE REVIEW

**Comment by vmuzikar** [comment]
Backporting due as the failing test was [affecting](https://github.com/keycloak/keycloak/actions/runs/3050415794/jobs/4917646548) 19.0 branch too.

**Comment by Pepo48** [comment]
@vmuzikar GH CI model tests failure is not related to the PR, right?

**Review by Pepo48 — APPROVED** [review]
Other than that the affected tests seem to be stable in both GH CI and even locally (I just reran them once again). Thus, I can approve this backport.

Thanks @vmuzikar!

**Comment by vmuzikar** [comment]
> @vmuzikar GH CI model tests failure is not related to the PR, right?

Yes, that is correct.

Thanks for the review!

**Pull request merged**
