### PR TITLE
Fixes typo in Server Administration guide

### PR DESCRIPTION
**Pull request by christian-2**
It's one letter, so title should suffice.

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
Please [sign off](https://github.com/keycloak/keycloak/pull/26543/checks?check_run_id=20933971335) on your commit.

**Comment by christian-2** [comment]
@jonkoops how do you want me to sign-off: is a `git push --force` (after `git commit --amend`) allowed in this situation?

**Comment by ahus1** [comment]
> is a `git push --force` (after `git commit --amend`) allowed in this situation?

Yes. Force-push is allowed and recommended for pull requests to fix commit messages. In other PRs (not applying here), we also it after rebasing or squashing commits.

**Review by ahus1 — APPROVED** [review]

**Comment by ahus1** [comment]
Thank you for taking the time to fix this typo!

**Pull request merged**
