### PR TITLE
[KEYCLOAK-12589] Support deserializing access token responses where scope is an array

### PR DESCRIPTION
**Pull request by intricate**
See [KEYCLOAK-12589](https://issues.redhat.com/browse/KEYCLOAK-12589) for details.

### CODE REVIEW

**Review by stianst — CHANGES_REQUESTED** [review]
I'm not in favour of adding this. Scope is very consistently a space separate list and not an array, and this would effectively allow possibly invalid values. It seems the provider mentioned in KEYCLOAK-12589 is one of very few (if not only) that uses an array.

**Comment by intricate** [comment]
@stianst:

> I'm not in favour of adding this. Scope is very consistently a space separate list and not an array, and this would effectively allow possibly invalid values. It seems the provider mentioned in KEYCLOAK-12589 is one of very few (if not only) that uses an array.

I'm inclined to agree with you here. Even the OAuth 2.0 spec is quite specific in that the `scope` parameter is a space-delimited string. 

However, it is unfortunate (for me, at least) that everything just breaks if the `scope` parameter in the `AccessTokenResponse` is incorrectly formatted. Is there any nice way that you can think of to make this more resilient without affecting the system's integrity like, for example, introducing some way to explicitly ignore a parameter in the `AccessTokenResponse`? If so, I'd be glad to implement it.

**Comment by stianst** [comment]
Of the top of my hand I can't think of an elegant way to solve the problem you have. Can you drop a mail to the dev mailing list and we can continue the discussion there?

One workaround could be that you create a custom provider for Twitch, but I can appreciate that's not necessarily what you want to do.

**Comment by intricate** [comment]
@stianst: 

> Can you drop a mail to the dev mailing list and we can continue the discussion there?

Sure, I'll do that.

> One workaround could be that you create a custom provider for Twitch

Do you mind elaborating on what you mean by "create a custom provider"?

**Comment by stianst** [comment]
Keycloak has support to deploy custom providers, and you can create a custom identity provider for Twitch that potentially works around this issue.

**Comment by stianst** [comment]
I'm going to close this for now. Let's discuss it on the dev mailing list, and if others agree that this is something we should support then we can discuss the approach and open a new PR.

**Comment by intricate** [comment]
For anyone stumbling upon this issue, I finally got around to creating a custom identity provider for Twitch: https://github.com/intricate/keycloak-twitch.

**Pull request closed without merging**
