### PR TITLE
Rework handling of Infinispan exceptions to stabilize the test

### LINKED ISSUE #13164: Test OfflineSessionPersistenceTest.testPersistenceMultipleNodesClientSessionsAtRandomNode failed randomly
### Describe the bug

In the run https://github.com/keycloak/keycloak/runs/7357900571?check_suite_focus=true the test named above failed randomly/possibly due to a timing issue.

### Version

999-SNAPSHOT

### Expected behavior

Test should be deterministic, and not depend on timing.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #13164

### CODE REVIEW

**Comment by ahus1** [comment]
The previous handling of expected Infinispan errors had two problems: 
* there was another Infinispan-Exception that could occur ("Read commands must ignore leavers")
* the retry failed, as the database might have received the information about this entity already, leading to a duplicate key exception. 

Therefore, this change adds the new exception, and removes the retry.

**Review by martin-kanis — COMMENTED** [review]
Changes made in this PR looks good to me. However, I struggle to understand the test itself. We create offline user sessions, then we start multiple nodes which are creating offline client sessions, storing them in `clientSessionIds` and at the end we check if original offline user sessions still exist. Ignoring the `clientSessionIds`. How would anything inside `inIndependentFactories` block could affect original offline user sessions?

**Comment by martin-kanis** [comment]
> @martin-kanis - the session are inserted to different Infinispan instances running in a cluster. At the end all the session created independently of where they have been created should still be available after restarting all instances:
> 
> ```
>         reinitializeKeycloakSessionFactory();
>         assertOfflineSessionsExist(realmId, offlineSessionIds);
> ```
> 
> That's at least my understanding of this test :-)

But offline user sessions are created before nodes of the cluster are started and the final check `assertOfflineSessionsExist(realmId, offlineSessionIds);` is done after the cluster is destroyed. Nodes of the cluster are creating only offline **client** sessions.

**Review by martin-kanis — APPROVED** [review]

**Comment by ahus1** [comment]
I assume that Bruno reset the review as he saw that the discussion wasn't finished. As your last comment starts with a "But", I assume that this state hasn't changed despite your approval. 

I therefore reset the approval again. I see that this code has been there from the beginning, and the one thing it shows is that offline (client) sessions can be reloaded. 

If you can approve this PR without a "but", please do, or continue the discussion here. If you think something should be clarified in the test as part of a different ticket, please create an issue or setup a short pairing session to analyze the code together. Thanks!

**Pull request merged**
