### PR TITLE
KEYCLOAK-5613 Add built-in optional client scope for MicroProfile-JWT

### PR DESCRIPTION
**Pull request by sguilhen**
Jira link: https://issues.jboss.org/browse/KEYCLOAK-5613

Documentation PR: https://github.com/keycloak/keycloak-documentation/pull/619

### CODE REVIEW

**Comment by sguilhen** [comment]
@pedroigor Tried requesting your review but that's an action I can't perform (missing some permission to request reviews maybe?).

As we've discussed, I've implemented the 'groups' claim by retrieving the realm roles associated with the subject by default. We currently have two mappers, one for realm roles and one for client roles, so I'm wondering if this is a sensible default for the scope or if we need to implement some sort of 'combined roles' mapper that includes both realm and client roles in the 'groups' claim. WDYT?

**Comment by stianst** [comment]
I haven't read the spec, but does it not cover something around roles?

**Comment by pedroigor** [comment]
@sguilhen I think it is OK to have realm roles as the default role mapping. We should allow people to easily  configure Keycloak to issue mp-jwt compliant tokens and realm roles as `groups` should cover majority of use cases.

I would just suggest you to also consider tests to assert the contents of access tokens. These are the tokens that clients will use to access mp-jwt protected services.

**Comment by pedroigor** [comment]
@stianst the `groups` claim is the standard claim for role mapping when processing bearer tokens and building a security context from it.

**Comment by pedroigor** [comment]
@sguilhen, btw I think we could also mention this new client scope in docs with some explanation about how to use it and why ?

**Comment by sguilhen** [comment]
@pedroigor absolutely, I'll add a section to the docs about this scope. It should also be pretty easy to enhance the test to check the AccessToken contents when the microprofile-jwt scope is in use.

**Review by pedroigor — CHANGES_REQUESTED** [review]
@sguilhen, it seems there is a test failing on Travis. It should be quite trivial to fix it. Please, let me know once you fixed the test and updated docs with the new microprofile scope.

I think these are the only things missing to get this one in.

**Comment by sguilhen** [comment]
@pedroigor I have a fix for the test. Will push it and this afternoon I'll push the changes to the documentation and will link the PR here

**Comment by sguilhen** [comment]
@pedroigor pushed a fix for the failing test and also linked the PR for the documentation changes.

**Review by mposolda — APPROVED** [review]
@sguilhen Approving. Thanks! I did not check the details of the specs, rely on you guys as you know better what is needed with regards to the specs and quarkus adapter.

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
