### PR TITLE
Update to Liquibase 4.8.0

### LINKED ISSUE #10678: Update to Liquibase 4.8.0
### Description

Update to Liquibase 4.8.0. Quarkus is [already using Liquibase 4.8.0](https://github.com/quarkusio/quarkus/blob/2a9ae4195c33a61fcbde2ab044d340164fac3b5d/bom/application/pom.xml#L161), it should be safe for us to update considering that the latest release fixes a couple of bugs.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by abstractj**
Closes #10678

- [ ] This version needs to be productized internally (check with @martin-kanis)
- [x] Licences need to be updated (see [the 4.6.2 upgrade](https://github.com/keycloak/keycloak/pull/9477/commits/0e15724ab95f1465b231ee854e380d1bca4f5899) as an example)
- [x] Run the db_migration_tests in the pipeline. (running also the db_tests wouldn't hurt) (done by @sguilhen )

### CODE REVIEW

**Comment by abstractj** [comment]
@pedroigor @DGuhr the CI is reporting `Caused by: java.net.UnknownHostException: localtest.me: Temporary failure in name resolution` on `quarkus, group3` but it seems unrelated with the current change. Whenever you have some time this week, could you please review this PR?

**Review by sguilhen — CHANGES_REQUESTED** [review]
1- This version needs to be productized internally (check with @martin-kanis)
2- Licences need to be updated (see [the 4.6.2 upgrade](https://github.com/keycloak/keycloak/pull/9477/commits/0e15724ab95f1465b231ee854e380d1bca4f5899) as an example)
3- I would like to at the very least run the `db_migration_tests` in the pipeline. (running also the `db_tests` wouldn't hurt)

**Review by DGuhr — APPROVED** [review]
@abstractj Can't see a connection between the error and the change. Could you re-run the CI step perhaps to see if it stays consistent? Apart from that LGTM. I've built quarkus locally with 4.8 and had no problem accessing keycloak. CI also ran the [databasetests](https://github.com/keycloak/keycloak/runs/5486590543?check_suite_focus=true#step:10:83) and seems for all testcontainers dbs we include it has started and applied the changesets correctly, so I am pretty confident. Also DB migration tests are green, should work 👍 
@sguilhen guess when you mention "pipeline", you don't talk about the gha ci? ;)

**Review by DGuhr — CHANGES_REQUESTED** [review]
oh, just read about the license update. that has to happen for sure, so apart from that lgtm, but removing approval for now ;)

**Comment by sguilhen** [comment]
> @sguilhen guess when you mention "pipeline", you don't talk about the gha ci? ;)

Right, I'm talking about the internal jenkins pipeline. I'm pretty sure we don't run the db tests or db migration tests in GHA, so we need to ensure we won't hit migration issues with this upgrade. This particular upgrade probably doesn't introduce any issues, but there have been cases in the past when a Liquibase release modified the changeset checksum algorithm for a release, causing migration issues. I just want to be on the safe side with this and ensure that migration with all supported DBs is working as expected.

I also need to check if this doesn't introduce regressions in the new storage before we proceed with this.

**Comment by abstractj** [comment]
Thank you @sguilhen and @DGuhr for the review, I will look into that and iterate over it.

**Comment by sguilhen** [comment]
@abstractj I've triggered a pipeline run to execute the db_tests and db_migration_tests. Build pipeline 563.

**Comment by sguilhen** [comment]
I'm also building locally to test the new storage with this liquibase version. Will update once I verify.

**Comment by abstractj** [comment]
Thanks for the update @sguilhen. I talked to @martin-kanis and productizing it shouldn't take too much time from what I understood.

**Comment by martin-kanis** [comment]
The temporary build is done in PNC. I noticed the same as @sguilhen. When running with WF there are bunch of messages printed to the console during the startup: 
```
18:39:33,796 INFO  [org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider] (ServerService Thread Pool -- 53) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
18:39:33,893 INFO  [stdout] (ServerService Thread Pool -- 53) Running Changeset: META-INF/jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::sthorger@redhat.com
18:39:33,979 INFO  [stdout] (ServerService Thread Pool -- 53) Running Changeset: META-INF/db2-jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::sthorger@redhat.com
18:39:33,982 INFO  [stdout] (ServerService Thread Pool -- 53) Running Changeset: META-INF/jpa-changelog-1.1.0.Beta1.xml::1.1.0.Beta1::sthorger@redhat.com
....
```
I'll proceed with a permanent build.

**Comment by martin-kanis** [comment]
@abstractj Regarding the licenses. Please run the `./distribution/licenses-common/update-licenses.sh` script and commit changes related to liquibase files (2 files deleted, 2 files added, rest of the changes made by the script can be discarded).

**Comment by abstractj** [comment]
@martin-kanis thank you, updated my PR with the outcome from the magic script.

**Comment by sguilhen** [comment]
Pipeline results: https://master-jenkins.keycloak.com/job/universal-test-pipeline-server/1311

Migration tests all succeeded - mariadb is currently stuck trying to shut down but the logs show the tests passed. All other DBs finished successfully.

DB Tests have a few errors that have been there from previous builds and a few errors on Oracle, which hasn't run for quite some time. Most are related to timeouts and I don't think they have anything to do with this particular PR. In my opinion the PR is good from a pipeline perspective.

**Comment by sguilhen** [comment]
> @martin-kanis thank you, updated my PR with the outcome from the magic script.

I'm afraid you've pushed more than what was needed. Only the two liquibase file changes (one for keycloak, one for sso) should have been included.

**Comment by abstractj** [comment]
@martin-kanis probably I'm missing something. I did run the script as you mentioned:

```
❯ ./distribution/licenses-common/update-licenses.sh
```

Outcome from git:
```
❯ git status
On branch issue-10678
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/OpenSans,Apache Software License 2.0.txt
        modified:   distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/history,MIT.txt
        modified:   distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/popper.js,MIT.txt
        modified:   distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/react-router,MIT.txt
        modified:   distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/react-router-dom,MIT.txt
        modified:   distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/rfc4648.js,MIT License.txt
        modified:   distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/OpenSans,Apache Software License 2.0.txt
        modified:   distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/history,MIT.txt
        modified:   distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/popper.js,MIT.txt
        modified:   distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/react-router,MIT.txt
        modified:   distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/react-router-dom,MIT.txt
        modified:   distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/rfc4648.js,MIT License.txt

```

**Comment by martin-kanis** [comment]
@abstractj You need to run the script when you have following changes in you branch https://github.com/martin-kanis/keycloak/commit/e0a920beb6fd203fb3b2d2ca0dc86427e1479a7c
Then you should see changes to the liquibase licenses and push only those. Ignore the noise regarding js and react licenses.

**Comment by sguilhen** [comment]
May I suggest one final change: https://github.com/sguilhen/keycloak/commit/b18c2fcebdb74145232604c103527dbeae720833#diff-87d46d493656c8f2f4bb8a2299d28d06bf1285f882cd4293449b22271b6e3b21R85

This redirects all the new messages that are printed in the console in this version to the configured logger. I'm basically trying to prevent all these new messages from polluting the console during startup.

**Comment by sguilhen** [comment]
@abstractj Just realized that our Quarkus server doesn't rely on the liquibase connection provider from `model-jpa`, so I had to adjust it's own provider as well to avoid all the noise from processing the changesets:

https://github.com/sguilhen/keycloak/commit/d5cf7a57b3da45b9be8d6d648d2575ba2c50a991#diff-fef553b65457aa8e548b37ce2af8302138a6bb781ba5bf830faf8e74143eced5

Could you incorporate that into the PR?

**Comment by abstractj** [comment]
@sguilhen done!

**Comment by sguilhen** [comment]
@abstractj I don't see the QuarkusLiquibaseConnectionProvider changes

**Review by sguilhen — CHANGES_REQUESTED** [review]
This is still missing the QuarkusLiquibaseConnectionProvider changes.

**Comment by abstractj** [comment]
@sguilhen done for real :) Thank you!

**Review by sguilhen — APPROVED** [review]
Thank you @abstractj ! The PR checks all boxes for me now, approving!

**Review by martin-kanis — APPROVED** [review]

**Comment by abstractj** [comment]
@hmlnarik @mhajas whenever you have some time, could you please tell if you see any impact for the storage?

**Review by hmlnarik — APPROVED** [review]
I'm approving per @martin-kanis 's and @sguilhen 's approval. I rely on them also re the impact on the new storage.

**Pull request merged**
