### PR TITLE
Correct translation of groups for Russian language

### PR DESCRIPTION
**Pull request by balkarov**
Change this messages.
image (1)

### CODE REVIEW

**Comment by jonkoops** [comment]
Hi @balkarov, thanks for your PR, as per our policy please get another native speaker to review your work.

**Review by genglik — APPROVED** [review]

**Review by jonkoops — APPROVED** [review]
LGTM, let's get this merged

**Comment by jonkoops** [comment]
@balkarov @genglik thanks for the contribution, the PR should merge automatically when all the CI checks pass.

**Comment by balkarov** [comment]
@jonkoops could you merge it please?

**Pull request merged**
