### PR TITLE
Update Infinispan examples in the High Availability guide

### LINKED ISSUE #35451: Update Infinispan examples in the High Availability guide
### Description

The examples need to be updated with
* Add indexing configuration for caches `loginFailures` and `authenticationSessions` (performance).
* Update transaction mode (safety).

### PR DESCRIPTION
**Pull request by pruivo**
Closes #35451

### CODE REVIEW

**Comment by ahus1** [comment]
This PR is now enabling indexing for the first time. 

AFAIK this requires a minimum version of the external ISPN 15.0.11 that is different from the initial release of KC 26.0

I'd say there is a fine line here about breaking vs. non-breaking changes. 

Given that in upstream the supported version of ISPN is only the latest patch release, I'd say we would be OK to proceed with having this change in KC 26.1 with a hint in the migration guide that the cache-configuration have been reworked (transactions and indexing).  

I would avoid backporting this change with indexing enabled to KC 26.0 due to that. Indexing would also change the performance characteristics. If we backport the transaction change, the transaction change would need to be listed in the migration guide as people would otherwise miss changing that option. 

Please let me hear your thoughts on this.

**Comment by pruivo** [comment]
Infinispan 15.0.11.Final is already the minimum required version for Infinispan in KC 26.0: https://www.keycloak.org/high-availability/deploy-infinispan-kubernetes-crossdc

I disagree and don't think we need to add these to the migration guide. Destroying existing caches to update their configuration is overkill. Everything works fine with the old configuration; this new one may be better for one or two rare edge cases. 

If you prefer to keep 26.0 docs unchanged, I'll be ok with that.

**Comment by pruivo** [comment]
> OK, I understand this setting can't be changed at runtime? If we don't put it in the migration guide, they will never change that configuration option. 
 
Except for some timeouts, no configuration change is possible at runtime. The cache has to be deleted and re-created again.
Users can update the configuration when upgrading the Infinispan cluster.

> Which leads me to the question: When we eventually have Keycloak manage the cache configurations, would it then change this setting from the old one to the new?

Not quite, the caches configured in the `infinispan.xml` or via the Infinispan CR (OpenShift) have priority over the configuration provided by Keycloak. 

> Given the above, I tend to keep 26.0 docs unchanged. Eager to hear your replies on the above.

OK, I'm going to close the PR for 26.0

**Review by ahus1 — APPROVED** [review]
Thank you for this update the Infinispan configuration!

**Pull request merged**
