### PR TITLE
Upgrade to latest Quarkus 2.13.2

### LINKED ISSUE #14817: Upgrade to latest Quarkus 2.13.z

### PR DESCRIPTION
**Pull request by abstractj**
Resolves #14817

### CODE REVIEW

**Comment by abstractj** [comment]
cc @keycloak/cloud-native-team

**Comment by abstractj** [comment]
Adding @keycloak/storage-x for awareness.

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@abstractj Thank you for the PR! Can you please update to Quarkus 2.13.2 which was [released yesterday](https://quarkus.io/blog/quarkus-2-13-2-final-released/)?

**Review by martin-kanis — CHANGES_REQUESTED** [review]
Thanks for the PR. I ran internal pipelines and it looks good.
https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/1331
https://keycloak-jenkins.com/job/universal-test-pipeline-server/2253

Maybe `<jackson.databind.version>` can be also removed in `keycloak-operator` and `keycloak-quarkus-parent` pom.xml?

**Comment by abstractj** [comment]
Thank you @martin-kanis incorporate the changes you suggested, plus the ones requested by @vmuzikar.

**Review by martin-kanis — CHANGES_REQUESTED** [review]
@abstractj There is one more `jackson.databind.version` property in `operator/pom.xml`

EDIT: Also there is another version of Jackson `<jackson-bom.version>2.13.3</jackson-bom.version>` and `<jackson.version>${jackson-bom.version}</jackson.version>` defined in `quarkus/pom.xml`.
And `<jackson.version>2.13.3</jackson.version>` defined in `operator/pom.xml`. My guess is that all of those can be removed and we can go with one Jackson version defined in parent pom.xml.

**Comment by abstractj** [comment]
Good catch @martin-kanis, thank you. Updated now, after the tests pass, and also your and @vmuzikar review I will squash those commits before merging it.

**Comment by stianst** [comment]
Issue and commit should mention explicitly what version is being upgraded to, and not "latest".

**Review by vmuzikar — APPROVED** [review]
@abstractj LGTM, thank you!

@stianst The original issue didn't state a specific Quarkus version as we weren't sure which micro we will use (as they release quite often), hence the `.z` placeholder. :)

**Review by martin-kanis — APPROVED** [review]

**Comment by stianst** [comment]
> @abstractj LGTM, thank you!
> 
> @stianst The original issue didn't state a specific Quarkus version as we weren't sure which micro we will use (as they release quite often), hence the `.z` placeholder. :)

Placeholder is fine initially, but we should update it before merging now that we know what version it is.

**Comment by stianst** [comment]
Updated the issue title, and fixed the commit message on squash commit

**Pull request merged**
