### PR TITLE
KEYCLOAK-12059 Upgrade to WildFly 18.0.1

### PR DESCRIPTION
**Pull request by martin-kanis**

### CODE REVIEW

**Comment by martin-kanis** [comment]
https://keycloak-jenkins.com/view/pipelines/job/universal-test-pipeline-server/1055/
https://keycloak-jenkins.com/view/pipelines/job/universal-test-pipeline-adapters/874/

**Review by stianst — DISMISSED** [review]

**Review by hmlnarik — CHANGES_REQUESTED** [review]
License files need fixing, there's HTML content in TXT files

**Review by hmlnarik — APPROVED** [review]

**Comment by martin-kanis** [comment]
https://keycloak-jenkins.com/view/pipelines/job/universal-test-pipeline-server/1066/

**Comment by hmlnarik** [comment]
Failures in pipeline seem unrelated to this change. Thanks @martin-kanis !

**Pull request merged**
