### PR TITLE
Upgrade to Quarkus 3.7.1

### LINKED ISSUE #23854: Use upstream Quarkus functionality for non-blocking probes
### Description

In #22109 a workaround was added to Keyclaok to support a non-block readiness and liveness probe. 

In upstream Quarkus, issue https://github.com/quarkusio/quarkus/issues/35099 is open to support non-blocking probes natively in Quarkus. This issue tracks the progress there. 

This also tracks https://github.com/eclipse-vertx/vert.x/issues/4900 and https://github.com/quarkusio/quarkus/issues/36419 where workarounds have been created in #23919. 

### Discussion

_No response_

### Motivation

Non-Blocking probes are essential to prevent the probes to fail under high load when blocking requests are queued.

### Details

See #22109 and #22112 for the discussion.

### LINKED ISSUE #26701: Upgrade to Quarkus 3.7.1
### Description

https://github.com/quarkusio/quarkus/releases/tag/3.7.1

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes #26701
Closes #23854

Quarkus 3.7.1 introduced revamped probes as part of https://github.com/quarkusio/quarkus/issues/35099. That introduced some breaking changes for us in health checks, so I took the opportunity to right away resolve now unblocked #23854 instead of patching our workaround.

### CODE REVIEW

**Comment by vmuzikar** [comment]
@ahus1 Could you please review as well?

I was wondering whether you still want to keep:
https://github.com/keycloak/keycloak/blob/ff5a5fa87e94d23625e3428c30c7f0f58a4bc5dd/quarkus/config-api/src/main/java/org/keycloak/config/HealthOptions.java#L12-L18

Might not be needed now that we removed our workaround for custom async probes.

**Comment by ahus1** [comment]
@vmuzikar - thank you for preparing this, LGTM. 

+1 for removing `health-classic-probes-enabled`. We added it as an escape hatch if it wouldn't work as expected. As our tests showed that it worked, and no-one complained, I assume it is no longer needed.

To clean up, `KeycloakReadyAsyncHealthCheck` should be kept, and `KeycloakReadyHealthCheck` should be removed, as we would prefer an async readiness check to avoid a pod to become non-ready under high load. Possibly you might want to rename `KeycloakReadyAsyncHealthCheck`  to `KeycloakReadyHealthCheck` as the last step.

**Comment by vmuzikar** [comment]
@ahus1 Thanks for the review. I removed the classic readiness check in a separate commit.

**Review by ahus1 — APPROVED** [review]
LGTM, thank you for preparing this change!

**Comment by ahus1** [comment]
@vmuzikar - didn't enable auto-merge as I wasn't sure if you want someone else to review it. Ready to be merged IMHO.

**Review by Pepo48 — APPROVED** [review]
@vmuzikar thanks for addressing this right away. The changes LGTM.

I assume that this will require a backport (since the original PR was [partially backported](https://github.com/keycloak/keycloak/pull/23855) back then), right?

**Comment by vmuzikar** [comment]
@Pepo48 Thanks for the review!

> I assume that this will require a backport

Nope, we don't do major/minor Quarkus upgrades in Keycloak micro releases.

**Comment by sschu** [comment]
@ahus You said "we want to avoid a pod to become non-ready under high load". Do you mean "non-live"? Shouldn't it become non-ready to get less traffic but still be live to not be killed?

**Comment by ahus1** [comment]
@sschu - no, I still meant what I wrote there. We actually want both: 

* We want it to be live so it doesn't get killed under high load
* We want it to be ready under high load, as the readiness probe is too slow (multiple readiness probes need to fail, and they have an interval). It might work if you have a readiness probe which you call each second, with a threshold of 2 as a liveness probe, but even that would be slow IMHO. Instead, I prefer load shedding (where some of the requests are successful). This can be further optimized at the load balancer. As a pass-through LB distributing the active connections equally, or as a re-encrypt LB balancing the number of active requests across the nodes. A node that is slow wouldn't get additional work this way.

The `KeycloakReadyHealthCheck` is only a readiness check, so not included in the liveness check.

**Comment by sschu** [comment]
Makes sense. What are conditions for Keycloak to become unready? No DB connection?

**Comment by ahus1** [comment]
> What are conditions for Keycloak to become unready? No DB connection?

More or less yet. See `KeycloakReadyHealthCheck` for the details. It is the only readiness check there is for Keycloak today.

**Pull request merged**
