### PR TITLE
KEYCLOAK-17483 Increase max size of additional request params

### LINKED ISSUE #14015: Increase max size of additional request params
### Description

See https://issues.redhat.com/browse/KEYCLOAK-17483

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by hawknewton**
Hello,

First and foremost I'd like to thank everyone that contributes to this project, it's really excellent world-class software.

I've increased the maximum size of additional parameters for oidc endpoints.  I'm working on an integration that requires a fairly large parameter (~1500 chars) be passed as part of the authorization flow.

Thank you.

PS -- As you likely know the build dies on apple silicone so I haven't been able to run the tests.

### CODE REVIEW

**Comment by hawknewton** [comment]
The only way I've found to increase this value is to fork, which is obviously not something I want to do.

If this isn't an agreeable solution, does anyone have any suggestions I might implement that would allow the maximum parameter size to be increased via config or some other mechanism?  This is a blocker for SMART on FHIR integrations as they require large additional parameters.

Thank you.

**Review by stianst — CHANGES_REQUESTED** [review]
Should be fine

**Review by stianst — APPROVED** [review]
LGTM @mposolda wdyt?

**Review by mposolda — APPROVED** [review]
LGTM. There is no test, but appreciate that this scenario is quite hard to test and the change is trivial (no risk of regression).

**Pull request merged**
