### PR TITLE
KEYCLOAK-15481: Display forbidden screen in new account console

### PR DESCRIPTION
**Pull request by ssilvert**
Display forbidden screen in new account console if user tries to do something he doesn't have rights to do.

forbidden

### CODE REVIEW

**Review by miquelsi — DISMISSED** [review]

**Review by edewit — DISMISSED** [review]

**Review by abstractj — DISMISSED** [review]

**Review by vmuzikar — COMMENTED** [review]
Changes look good, we just need to merge the tests (https://github.com/ssilvert/keycloak/pull/9) in order to merge this. Thanks @ssilvert

The test results with the new test:
https://keycloak-jenkins.com/job/universal-test-pipeline-server/2131/

**Comment by Aboullos** [comment]
Looks good, the only thing is that it shows the view for a short moment before redirecting to the "Forbidden", but don't know if that can be changed.

**Comment by vmuzikar** [comment]
> Looks good, the only thing is that it shows the view for a short moment before redirecting to the "Forbidden", but don't know if that can be changed.

I'm afraid there's no easy fix. It's the same issue as when you try to access the console without logging in first – the console is displayed for a split second before redirecting to the login page. IIRC Erik had some solution but it brought its own problems, so we decided to leave it as is.

**Comment by edewit** [comment]
It can be fixed there could be a loading screen for as long as the data is
being fetched instead of going to the screen first and then fetch the data
in the background, but that would mean a restructuring of the application.

**Comment by ssilvert** [comment]
> Changes look good, we just need to merge the tests ([ssilvert#9](https://github.com/ssilvert/keycloak/pull/9)) in order to merge this. Thanks @ssilvert
> 
> The test results with the new test:
> https://keycloak-jenkins.com/job/universal-test-pipeline-server/2131/

merged the new test

**Review by vmuzikar — APPROVED** [review]

**Review by Aboullos — APPROVED** [review]

**Comment by ssilvert** [comment]
@abstractj Sounds like we are ready to merge if you can give your approval.

**Review by abstractj — APPROVED** [review]

**Pull request merged**
