### PR TITLE
[KEYCLOAK-17997] Upgrade Spring Security

### PR DESCRIPTION
**Pull request by abstractj**
@pedroigor @miquelsi you both are my best references when it comes to Spring. Whenever you have a few minutes, could you please review and tell if this upgrade will make the world falls apart?

I tried to run the tests locally and they are passing, but there's a chance that I might be missing something.

### CODE REVIEW

**Comment by pedroigor** [comment]
@abstractj LGTM. Are the quickstarts happy with this change?

**Comment by abstractj** [comment]
@pedroigor that's a great point. I will double-check it.

**Comment by miquelsi** [comment]
@abstractj I would like to see Spring Boot adapter tests passing as well in Jenkins. If they pass and the quickstarts are working I don't have any objections.

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@abstractj Could you please rebase? Master now includes GH Actions for the QS.

**Comment by abstractj** [comment]
@vmuzikar rebased.

I also resolved the issues reported by GH actions.

**Comment by abstractj** [comment]
@vmuzikar I found some issues into _ArquillianJeeHtml5Test_ unrelated with the changes from this PR.

**Review by vmuzikar — DISMISSED** [review]
Approving based on the QS tests results.

@abstractj I think you discovered an instability in one of the QS. :) Should by fixed in https://github.com/keycloak/keycloak-quickstarts/pull/245 (basically switch from PhantomJS to Chrome). However, it seems like GH Actions updated some of its env and it's not even possible to build KC now due to [KEYCLOAK-17812](https://issues.redhat.com/browse/KEYCLOAK-17812). :(

**Comment by abstractj** [comment]
@vmuzikar rebased based on the fix provided on https://github.com/keycloak/keycloak/pull/8007

**Review by vmuzikar — APPROVED** [review]

**Comment by miquelsi** [comment]
Test pipeline run passed: https://keycloak-jenkins/job/universal-test-pipeline-adapters/261/

**Review by miquelsi — APPROVED** [review]

**Pull request merged**
