### PR TITLE
KEYCLOAK-16947 add error parameters to access token response

### PR DESCRIPTION
**Pull request by benjamin37**
Added additional logging info as well.

### CODE REVIEW

**Review by stianst — COMMENTED** [review]
Thanks, but thinking about this I'm not in favour of adding this for two reasons:

a) The client wouldn't know if the error is coming from Keycloak or the IdP
b) I'd say the error from the IdP should not be exposed to the client as it should be considered an "internal error"

I'd say these errors should rather be logged than sent to the client.

**Review by stianst — CHANGES_REQUESTED** [review]
See previous comment

**Comment by benjamin37** [comment]
Hi @stianst,

thanks for the feedback on this. Maybe I'm wrong but I thought the message in the exception is only logged and not returned to the client in the end. 

When the exception occurs it ends in Line 502, after that it's cached and logged in 515. The response to the client in line 517 does not contain the message of the exception.
https://github.com/keycloak/keycloak/blob/1e2db74d866bda50f3d78d42892f16e2d7efe4e7/services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java#L502-L521

Kind Regards
Benjamin

**Comment by benjamin37** [comment]
Hi @stianst,

just wanted to make sure if you saw my previous comment?

Kind regards
Benjamin

**Comment by stianst** [comment]
Yeah, I think you're right. I got confused due to the changes to representation thinking that would be the response from Keycloak, and not handling the response from the IdP.

**Review by mposolda — CHANGES_REQUESTED** [review]
@benjamin37 PR itself looks good to me, Thanks! However I think rebase is needed. Hopefully that will help with the test failures (it is not longer possible to see where they happen).

**Comment by benjamin37** [comment]
Thanks for the feedback! I rebased against master, let's see if the tests succeed now.

**Comment by benjamin37** [comment]
@mposolda Test succeed now, however the "CodeQL / Analyze (java) (pull_request)" job fails. From my understanding this is not related to the code changes I did.

**Review by mposolda — APPROVED** [review]
@benjamin37 Thanks!

**Pull request merged**
