### PR TITLE
Bruteforce protector does not work when using organizations

### LINKED ISSUE #31204: Bruteforce protector does not work when using organizations
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

When using the brute force protector, failures won't be processed because the realm is not propagated to the thread that process the failures.

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Brute force protector works when the `organization` feature is enabled.

### Actual behavior

Brute force protector not working when organization is enabled.

### How to Reproduce?

* Enable the `organization` feature
* Enable brute force protector to the realm to permanently lockout users
* Force a failure and check that users are never disabled

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #31204

### CODE REVIEW

**Review by douglaspalmer — APPROVED** [review]
LGTM

**Review by ahus1 — APPROVED** [review]
Approving based on @douglaspalmer's review.

**Comment by ahus1** [comment]
@pedroigor - I didn't see the backport labels on the parent issue. I assume you want it to be backported to 25.

**Comment by pedroigor** [comment]
@ahus1 Thanks. I won't backport this one. I will wait for 26 as it is not a blocker to evaluate the feature.

**Pull request merged**
