### PR TITLE
Document network ports for Keycloak clustering

### LINKED ISSUE #34658: Document network ports for Keycloak clustering
### Description

For the caching guide, help users configure their firewall. Specify which ports are required for the correct work of the clustering. 
Enhance the "Configuring for production" guide with this new information too.

As a side note, this is valid for single-site deployments. Multi-site doesn't have a cluster.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by pruivo**
Closes #34658

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you for the docs. I like that you removed the docs for the cloud stacks and pointed directory to the ISPN docs. 

I added some more deprecation for the stacks that we want to replace with `jdbc-ping`. As the mcast addresses need to be set, I also moved those to the stacks that need configuration. 

As you wrote in the docs that `FD_SOCK2` is required for JDBC_PING2, and that being the new default, I think it is not worth adding it to the docs for yet another concept to understand and another choice to make. 

Two things that I noted:

* Looking at the startup logs and thinking back to what you explained to me, the `jdbc-ping-udp` stack seems to use MultiCast - this is not reflected in the docs as `jgroups.mcast_port` is listed only for `tcp` and `udp`. 

```
ISPN000078: Starting JGroups channel `ISPN` with stack `jdbc-ping-udp`
WARN  [org.jgroups.protocols.UDP] (Quarkus Main Thread) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
WARN  [org.jgroups.protocols.UDP] (Quarkus Main Thread) JGRP000015: the receive buffer of socket MulticastSocket was set to 20MB, but the OS only allocated 212.99KB
WARN  [org.jgroups.protocols.UDP] (Quarkus Main Thread) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
WARN  [org.jgroups.protocols.UDP] (Quarkus Main Thread) JGRP000015: the receive buffer of socket MulticastSocket was set to 25MB, but the OS only allocated 212.99KB
```

* When using either `udp` or `jdbc-ping-udp`, the FD_SOCK2 is using a random port

```
[org.jgroups.protocols.FD_SOCK2] (Quarkus Main Thread) server listening on *.28544
```

If this is intended and "just the way it works", I suggest to reduce the section `Network Ports` to only `jdbc-ping` where there are stable ports.

**Comment by pruivo** [comment]
I've created https://issues.redhat.com/browse/ISPN-16827 to remove the random ports from UDP stack.

Because the `jdbc-ping*` stacks are created at runtime by KC, I don't have a way to create a stack in the XML to remove `FD_SOCK2`. It will throw an exception and it would require  changes in `CacheManagerFactory`, which would make the code more complex... 

Yes, `jdbc-ping-udp` is using the `mcast` port too. Why do we want to deprecate `jdbc-ping-udp`?

**Comment by ahus1** [comment]
> Why do we want to deprecate `jdbc-ping-udp`?

IMHO the reason we have it in 26.1 is that it is a drop-in replacement for `udp` as there are no network adjustments necessary for it. We also already know that `jdbc-ping` will be the new default for 27. 

With the need to configure multicast parameters for `jdbc-ping-udp` it adds complexity where we want Keycloak to "just work", so I don't see an advantage, given that TCP is proven to work in our Kubernetes environments. With this documentation about network configuration, I realize also things people need to understand to get this right (aka we put them through a lot of pain). 
I find myself searching of a way to change the default earlier, but it seems I am bound with the minor version compatibility constraints. 

"Perfection is achieved when there is nothing left to take away." (Antoine de Saint-Exupéry) - so `jdbc-ping-udp` needs to go away to make things better.

**Comment by ahus1** [comment]
> Because the `jdbc-ping*` stacks are created at runtime by KC, I don't have a way to create a stack in the XML to remove `FD_SOCK2`. It will throw an exception and it would require changes in `CacheManagerFactory`, which would make the code more complex...

If we at some point decide that not using `FD_SOCK2` is the best and simplest way to run the embedded Infinispan, we should remove it in the `CacheManagerFactory` as the default. You tell me when this is the case :-) Once we decide to go down that route, it shouldn't require an XML stack configuration, but it should be just the default, probably without any options for people to worry about.

**Comment by ahus1** [comment]
> I find myself searching of a way to change the default earlier

Maybe I found the wormhole to travel: As we now know that when we use UDP, the FD_SOCK is using a random TCP port to connect the other Keycloak nodes (https://issues.redhat.com/browse/ISPN-16827), then there should be no firewall rule blocking TCP on that fixed port 7800? Fast forward to `jdbc-ping`?

**Comment by pruivo** [comment]
> With the need to configure multicast parameters for jdbc-ping-udp

You don't have to configure anything. (except if you are using MacOS). Are you saying that because I mentioned the default multicast address? My intention is to suggest users to create a stricter firewall rule by allowing traffic from `239.6.7.8:46655` instead of opening the port to all addresses. 

I still think UDP has its place in large on-premises deployments. Although, on a second though, you can claim that `udp` stack would be better than `jdbc-ping-udp` stack :)

**Comment by pruivo** [comment]
> If we at some point decide that not using `FD_SOCK2` is the best and simplest way to run the embedded Infinispan, we should remove it in the `CacheManagerFactory` as the default. 

We need to schedule a meeting with Bela for this as he is the network expert. At the moment, `FD_SOCK2` is not required (we removed it from cross-site Infinispan deployments), but some failure cases could be detected quickly. 

https://github.com/infinispan/infinispan/blob/67f531638ffb71f717a81475e97c40932f396292/core/src/main/resources/default-configs/default-jgroups-tunnel.xml#L34

**Comment by pruivo** [comment]
> > I find myself searching of a way to change the default earlier
> 
> Maybe I found the wormhole to travel: As we now know that when we use UDP, the FD_SOCK is using a random TCP port to connect the other Keycloak nodes (https://issues.redhat.com/browse/ISPN-16827), then there should be no firewall rule blocking TCP on that fixed port 7800? Fast forward to `jdbc-ping`?

I don't understand what you are suggesting here @ahus1 
Do you want me to add a note about the UDP random port and how to fix it?

**Comment by ahus1** [comment]
@pruivo - based on our discussion last week, the previoius `udp` stack used dynamic ports for UDP (transport) and TCP (failure detection). Given that dynamic behavior, I doubt that it would be possible to specify a strict firewall rule for the old stack. So the the new `jdbc-ping` would only use TCP, and would use well-defined ports, and therefore it is IMHO a drop-in replacement for the old `udp`. 

I didn't come up with any new concerns which would prevent us from going this step, so my last commit switches to `jdbc-ping` by default. 

Let me know if you agree with this step and the changes in my last commit. Thanks!

**Comment by pruivo** [comment]
@ahus1 no objection to changing the default. 

I'm still not convinced that deprecating `jdbc-ping-udp` is right. In any case, this PR can be merged.

**Review by ahus1 — APPROVED** [review]

**Comment by ahus1** [comment]
> I'm still not convinced that deprecating jdbc-ping-udp is right.

Could you please create a new issue for that so we can start describing the advantages where `jdbc-ping-udp` would be beneficial? Once we can tell people when to use it, we can add it to the docs and make it supported.

**Comment by ryanemerson** [comment]
That's great that `jgroups-ping` can be the default going forward. +1 to removing `jgroups-ping-udp` unless we have a clear use-case for it. I agree with @ahus1 sentiment, less is more in this case.

**Pull request merged**
