### PR TITLE
Allow for the backend to return granted scopes in any order.

### LINKED ISSUE #12395: Nightly runs fail for AccountRestServiceWithUserProfileTest>AccountRestServiceTest.createConsentForClient
### Describe the bug

I looked into the latest nightly run https://github.com/keycloak/keycloak/actions/runs/2458274753 and found that undertow-map, group1 and undertow-map-hot-rod, group1 fail both for `AccountRestServiceWithUserProfileTest>AccountRestServiceTest.createConsentForClient:1033`.

### Version

999-SNAPSHOT

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #12395

### CODE REVIEW

**Comment by ahus1** [comment]
The order of the entries shouldn't matter. Even though ConsentRepresentation is containing a list, those are retrieved from the store as a set which is unordered.

**Review by DGuhr — APPROVED** [review]
LGTM, thanks for the fast fix :) 

edit: just seen this is draft for now, but still.. makes sense for me to not rely on the order. But may be good to consult @sschu as he introduced the change in #11198 :)

**Comment by ahus1** [comment]
Thanks @DGuhr - it was in draft state as I wanted the GHA to complete. Now that they are complete, it switched it to non-draft.

Thanks for the review!

**Comment by ahus1** [comment]
@DGuhr - and I've commented on the original PR that introduced the change. I assume they'll comment once the order would be required. I consider it reviewed for now.

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
