### PR TITLE
KEYCLOAK-5571

### PR DESCRIPTION
**Pull request by dhardiker**
**Completed:**
* Logic
* Manual Testing

**Outstanding:**
* Extension of Automated Tests
* Documentation on LDAP Schema requirements (with working OpenLDAP example)

_Before further effort it put in to automating the testing, it would be preferable to have some peer review to ensure I'm extending Keycloak in the right places!_

### CODE REVIEW

**Comment by mposolda** [comment]
@dhardiker Thanks for the PR and sorry that review took long time.. Yes, you're extending Keycloak in right place, however TBH I am not very convinced whether to include this due the increased complexity. Especially I am not sure if counterparts for the attributes like "enabled", "emailVerified" and/or specified requiredActions are available as standard LDAP attributes in standard LDAP schemas? If this addition requires to update LDAP schema to be able to save Keycloak metadata like "emailVerified" or "enabled", then I would rather prefer to avoid this OOTB and rather use your contribution as the community extension - https://www.keycloak.org/extensions.html .

BTV. right now, we support the "enabled" and UPDATE_PASSWORD requiredAction for MSAD in the MSADUserAccountControlsStorageMapper as MSAD has some built-in attributes in their schema, which handle the "state" of the user and can be mapped to the Keycloak user metadata like "enabled" attribute and UPDATE_PASSWORD required action.

**Comment by dhardiker** [comment]
Thanks for the feedback.

You're correct that the counterparts in LDAP schema for enabled / emailVerified / requriedActions aren't readily available. You need to repurpose attributes from other object classes, or provide your own object class and attributes. This is pretty standard practice for LDAP systems, and is why we have LDAP mappers, so it becomes an exercise for the application admin to decide how it wants to map over?

Adaptavist decided to get a PEN from ICANN so we can issue OIDs ourselves. We're comfortable with donating the schema we built with documentation so that anyone using OpenLDAP can work easily.

This seems better than the alternative, which is having a LDAP Provider in Keycloak not supporting the critical enabled field - meaning that you can't lock a user out of LDAP connected systems from Keycloak, a deal breaker for a centralised identity management by our security practices.

I'll have a look at refactoring this into an extension. We have other requirements which might better fit an extension approach anyway (such as a secondary email address for account reset, as their corporate email address wont be accessible if you dont know your password - and we don't think this will be of interested to the majority of Keycloak customers).

Given mappers are the route for giving flexibility for wiring up Keycloak models with LDAP attributes, do you feel that this is adding complexity - or just asking the application admin to wire up the model more completely in the same fashion?

**Comment by mposolda** [comment]
@dhardiker Thanks, I understand the point for the "enabled" attribute, however if OpenLDAP itself doesn't support it OOTB in the schema, I would rather avoid to have the more complex code in the Keycloak as well. As that code would be useful just for someone, who needs to update LDAP schema. And moreover, he would need to update it in same way as you did

- I understand that many admins/companies customize their LDAP schema, but AFAIK majority of them are not doing it. One of the big advantage of LDAP is portability, which is bit of lost with a need of schema customizations.

- There is still possible to track the "enabled" attribute in Keycloak (as well as all the other Keycloak metadata, which don't map to LDAP like requiredActions, social links, consents etc), by switch "Import users" to ON. This means that just the attributes, which fits into LDAP schema are propagated to the LDAP, but the others (like "enabled") are propagated to Keycloak DB. I understand this may not help much in your case if you want to use LDAP also for other systems than Keycloak

- The most important LDAP vendor for us is MSAD, which most of the customers are using. And that one has a way to track "enabled" attribute OOTB in their schema (and that's why Keycloak supports it OOTB). To officially support and test the customizations you added, we will need to test with OpenLDAP with the custom schema updated and that's what I would like to avoid.

- The point of LDAP mappers (as well as other SPI Keycloak has) is to have the list OOTB implementations, which are useful for 90% of the cases and then have the ability to "Extend" Keycloak for the remaining 10% cases with deployment-specific customizations. ATM I feel that your case rather falls to those 10% cases, so it's perfectly fine to create LDAP mapper for your environment and support it as an extension - eventually also offer to other people if you describe in the README the customizations to LDAP schema, which are needed.

**Comment by mposolda** [comment]
@dhardiker Closing this for now. Possibly this can be done as a community extension - https://www.keycloak.org/extensions.html

**Comment by dhardiker** [comment]
@mposolda Thanks for the suggestion, your reasoning against adopting this is understandable. We ended up maintaining a patched version ourselves pretty successfully until mid-2020, when we moved over our usage over to Okta (for a variety of reasons).

I comment here as I've had contact with others asking if I made such an extension, which we didn't attempt it due to having a workable solution. Also, if we were to approach this problem again in 2021, we would consider Google's Secure LDAP service, which wasn't available when we migrated to Okta.

Hope this helps anyone searching for a similar solution!

**Pull request closed without merging**
