### PR TITLE
Remove unused mixed-case themes/.../rcue/.../git-Logo.svg

### PR DESCRIPTION
**Pull request by nngo**
Fixes KEYCLOAK-13939 to get rid of warning when cloning this repo under Windows 10 machine.

```
$ git clone git@github.com:keycloak/keycloak.git
Cloning into 'keycloak'...
...
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

'themes/src/main/resources/theme/keycloak/common/resources/node_modules/rcue/dist/img/git-Logo.svg'
'themes/src/main/resources/theme/keycloak/common/resources/node_modules/rcue/dist/img/git-logo.svg'
```

This is until RCUE upstream PR (redhat-rcue/rcue#89) gets merged (then incorporated (i.e. delete git-Logo.svg unused mixed-case file) from this repo)

### CODE REVIEW

**Comment by stianst** [comment]
Can you create a JIRA please?

Also, it needs to be removed when we update deps. See:
https://github.com/keycloak/keycloak/blob/master/themes/pom.xml#L113

**Comment by stianst** [comment]
I see the JIRA was already created. Can you prefix the commit message with the JIRA number?

**Comment by nngo** [comment]
> 
> 
> Can you create a JIRA please?
> 
> Also, it needs to be removed when we update deps. See:
> https://github.com/keycloak/keycloak/blob/master/themes/pom.xml#L113
I agree that line 113 and the comment on line 112 should get removed once RCUE merges the PR and releases, but it is probably safer to leave it in right now.

Plus this commit addresses the git clone warning for this repo.

**Comment by nngo** [comment]
> 
> 
> I see the JIRA was already created. Can you prefix the commit message with the JIRA number?
Done and rebased with with current origin/master.


One funny side affect for someone that has a clone of this repo under OS that have case-insensitive filesystem (e.g. Windows and I hear MacOS has this "option" too) is that when you update an existing clone directory, it removes the file. to correct you have to restore the *deleted* git-Logo.svg (which also deletes git-logo.svg under these OSes b/c of the case-insensitive filesystem).

**Comment by nngo** [comment]
@stianst is there anything else to getting this PR approved and merged to address https://issues.redhat.com/browse/KEYCLOAK-13939 ?

**Comment by stianst** [comment]
It needs to be removed when we update deps, otherwise it will just be re-introduced when we update deps. See:
https://github.com/keycloak/keycloak/blob/master/themes/pom.xml#L113

**Review by stianst — APPROVED** [review]

**Pull request merged**
