### PR TITLE
Fix numbering of recovery codes when downloading or copying them

### LINKED ISSUE #33933: Recovery authentication codes are numbered inconsistently
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

During setup of the recovery authentication codes, the list showing the codes is numbered starting from 1. When the user chooses to "Download" or "Copy" the codes, the resulting file/copy is indexed from 0 instead.
During authentication, the requested code is counted from 1 again.
This will lead to confusion for users who chose to download/copy the codes.

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The recovery codes should be numbered in a consistent fashion.

### Actual behavior

The displayed codes are numbered starting from 1, while the copied/downloaded codes are numbered from 0. During authentication, the codes are counted from 1.

### How to Reproduce?

- Activate the recovery authentication code preview feature
- Configure recovery authorization codes for a realm
- Log into the account console and navigate to Account Security > Signing In
- Start the recovery authentication code setup
- Compare the displayed list of codes with the one that can be copied and the one that can be downloaded
- Try logging in a realm with recovery authentication codes. Compare the requested code index with the downloaded/copied list

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by NoseSnatcher**
Closes #33933

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]
LGTM

**Review by ahus1 — APPROVED** [review]

**Comment by ahus1** [comment]
@NoseSnatcher - please don't rebase your PR unless you've been asked to do so by a maintainer or a conflict occurs. It would otherwise reset previous approvals, and would require all CI to run again.

**Comment by NoseSnatcher** [comment]
@ahus1 Sorry, it's my first time doing this. I thought I had to either merge or rebase, since my fork is behind upstream by now.

**Comment by jonkoops** [comment]
No worries. The GitHub UI is kinda confusing, and seems to imply a rebase is required to get your PR merged. This is common issue that is reported on the support forum, but it seems they are unaware.

**Pull request merged**
