### PR TITLE
fix: refines the provider caching logic

### LINKED ISSUE #34219: Refine KeycloakSession provider caching
### Description

The current logic uses a hash directly as the key and risks collisions between providers with ids and component providers.

### PR DESCRIPTION
**Pull request by shawkins**
closes: #34219

### CODE REVIEW

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks @shawkins. It's a good improvement, hashcode doesn't guarantee uniqueness anyway.

I'd like to ask @keycloak/core to review as well.

**Review by pedroigor — APPROVED** [review]

**Review by sguilhen — APPROVED** [review]
LGTM as well

@pedroigor ^

**Review by pedroigor — COMMENTED** [review]
I think we should backport it too.

**Comment by shawkins** [comment]
> I think we should backport it too.

https://github.com/keycloak/keycloak/pull/34271

**Pull request merged**
