### PR TITLE
Trigger the invalidation of the realm when a client scope changes

### LINKED ISSUE #20426: ClientScope changes don't invalidate the realm cache
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

When changing the ClientScopes are modified via `session.clientScopes()`, the list of client scopes which is cached as part of the realm is not evicted. 

Due to that, an access in the next request will use the cached version that doesn't contain the updated list (for example an added clientScope).

This doesn't happen when using the UI to add a ClientScope as those go through `realm().addClientScope()`, which will expire the realm cache when fetching the delegate

### Version

nightly

### Expected behavior

The cached realm contents should expire.

### Actual behavior

The cached realm is not expired.

### How to Reproduce?

I will provide a model test case as part of a pull request.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #20426

### CODE REVIEW

**Comment by martin-kanis** [comment]
I was debugging this a bit, and I came to this solution https://github.com/martin-kanis/keycloak/commit/7acaf23258d246a983263fa0ad4784dc97b4eb93 which seems to be more aligned with other areas like roles, clients in `RealmAdapter` and `RealmCacheManager`. However, I'm not expert in this area so I would like to hear i.e @vramik opinion.

**Comment by ahus1** [comment]
Thank you for this suggestion, @martin-kanis - your change shows that the list of clientscopes is cached in two places, when it should be cached only in one place. It allowed me to remote the list of clientscopes from the `CachedRealm` altogether. I pushed commit that includes your changes and a cleanup. 

I now hope for a green build and another review round. Thanks!

**Review by martin-kanis — APPROVED** [review]
@ahus1  thanks, LGTM.

Model tests errors looks unrelated to this PR.

**Review by hmlnarik — APPROVED** [review]
Approving per @martin-kanis 's approval

**Pull request merged**
