### PR TITLE
fix: ensuring test state is clean between tests

### PR DESCRIPTION
**Pull request by shawkins**
related to: #27080

### CODE REVIEW

**Comment by shawkins** [comment]
Unfortunately with the additional changes that should detect / confirm when the problem starts, it no longer occurs. Need to tweak things to get a different confirmation.

**Comment by shawkins** [comment]
@vmuzikar I've run this and another version that was directly checking the state of the cache numerous times - where the RealmImportTests that are the ones most likely to fail have run hundreds of times. However that has never fully captured what is going on. I'll try a few more rounds with just one of the debug logs enabled and see if that makes a difference.

Beyond that all we're talking about doing is refining this pr to wait until cleanup of transitive resources has occurred before starting the next test - this should, but is not guarenteed to, have the operator receive the delete events prior to reconciling the new keycloak from the next test. Obviously we can consider other workarounds, such as a namespace per test, or restarting the operator after the transitive cleanup.

**Comment by shawkins** [comment]
@vmuzikar this should clear up the RealmImportTest failures. It also has a small cleanup to remove some extra test logs.

**Comment by shawkins** [comment]
This simple change does not work because we are not marking our dependent resources as blockOwnerDeletion=true - https://github.com/operator-framework/java-operator-sdk/issues/2318

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@shawkins Thank you for the PR.

Can you please create a follow-up issue (and mention it in a comment in the code) to revert it once https://github.com/operator-framework/java-operator-sdk/issues/2314 is resolved?

Other than that LGTM.

**Comment by shawkins** [comment]
The follow-up is #28244

**Review by vmuzikar — APPROVED** [review]
@shawkins Thank you!

**Pull request merged**
