### PR TITLE
[KEYCLOAK-7725] - CORS should be set based on client making the request

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by sguilhen — APPROVED** [review]

**Review by mposolda — APPROVED** [review]
Approving (also based on @sguilhen approval).

**Comment by mposolda** [comment]
@pedroigor @sguilhen However not sure if automated test should be added for this too?

**Comment by pedroigor** [comment]
@mposolda, I think this is already tested by CORs tests ...

**Comment by mposolda** [comment]
@pedroigor ah, ok

**Pull request merged**
