### PR TITLE
Add label `updateEmail` to Arabic translation

### LINKED ISSUE #22558: Add label `updateEmail` to Arabic translation
### Description

Add label `updateEmail` to Arabic translation which was introduced in #22361

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by Eng-Fouad**
Closes #22558

### CODE REVIEW

**Comment by jonkoops** [comment]
@Eng-Fouad as usual, can you get another native speaker to review this? Thanks!

**Comment by jonkoops** [comment]
When creating a PR, please also make sure to link the appropriate issue if it exists. This ensures the issue is closed when the PR is merged. I've gone ahead and linked the issue myself for now.

For more information consult the [GitHub documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

**Comment by Eng-Fouad** [comment]
> When creating a PR, please also make sure to link the appropriate issue if it exists. This ensures the issue is closed when the PR is merged. I've gone ahead and linked the issue myself for now.
> 
> For more information consult the [GitHub documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

I added the issue number in the commit message, but it seems that it didn't link it :)

**Comment by alfayez91** [comment]
LGTM

**Review by jonkoops — APPROVED** [review]

**Pull request merged**
