### PR TITLE
KEYCLOAK-11142: use resteasy 4.2.0.Final

### PR DESCRIPTION
**Pull request by bentatham**
Update to use Resteasy 4.2.0.Final.

The change from Resteasy 3 -> 4 has some API breaking changes that needed to be updated.

### CODE REVIEW

**Review by abstractj — COMMENTED** [review]
@bentatham out of curiosity why Keycloak has to be updated to Resteasy 4.x? Have you discussed this on Keycloak dev mailing list?

**Comment by lrozenblyum** [comment]
RestEasy has a severe problem https://issues.jboss.org/browse/RESTEASY-2313 (it affects also the currently used in Keycloak version, not sure if the 4 version is free of it)

**Comment by stianst** [comment]
This would probably introduce a breaking change for everyone using the admin client with an older Resteasy versoin. What version of Resteasy is included in Keycloak 7 btw?

**Comment by abstractj** [comment]
> This would probably introduce a breaking change for everyone using the admin client with an older Resteasy versoin. What version of Resteasy is included in Keycloak 7 btw?

The current version of Resteasy that we have is 3.7.0.Final.

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Since Keycloak server builds on WF / Undertow, we need to respect the version in WF which is 3.7.0. The change to 4 would break all the customizations we use. Hence the current PR cannot be accepted.

Perhaps keycloak-admin-client could be split to extract the REST interfaces and RestEasy-specific parts extracted to a separate module; then it would be easy to supplement it with RestEasy 4 variant.

**Comment by bentatham** [comment]
> Perhaps keycloak-admin-client could be split to extract the REST interfaces and RestEasy-specific parts extracted to a separate module; then it would be easy to supplement it with RestEasy 4 variant.

Are you suggesting modules like this, within this repo:
* keycloak-admin-client (modified to remove resteasy dependencies by using interfaces defined here).
* keycloak-admin-client-resteasy3 (implements those new interface with resteasy3)
* keycloak-admin-client-resteasy4 (implements those new interface with resteasy4)

This means current users of keycloak-admin-client would then need no code change other than their pom.xml to depend on keycloak-admin-client-resteasy3?

Alternatively, with a bit less obvious naming, but not requiring current users to modify their dependencies downstream, we could have the following 3 modules, corresponding to the 3 above:
* keycloak-admin-client-core
* keycloak-admin-client (uses resteasy3 as it does now)
* keycloak-admin-client-resteasy4

If you tell me which one you prefer, I can try to do that...

**Comment by hmlnarik** [comment]
The second option sounds good to me. Please check with keycloak-dev mailing list before going forward though. I suggest defining JAX-RS "keycloak-admin-client" as the client that respects JAX-RS keycloak implementation. Also note that the new modules need to be accompanied by tests, which specifically test headers (look for `Pragma: No-cache` via `@NoCache`).

**Comment by stianst** [comment]
Can't we use jax-rs client instead of using rest easy APIs?  That would make the whole thing more portable.  If that doesn't work we should keep the current as is so it doesn't break current users and add a new module for rest easy 4. Interface can be extracted to admin-client-core of course

**Comment by stianst** [comment]
Closing this as we can't upgrade to Resteasy. A PR for a separate client for RestEasy 4 would be welcome though. Or even better a Java client that is more portable.

**Comment by mihxil** [comment]
That the issue is 'CLOSED' suggest that the client is compatible with resteasy 4. Which is, as far as I understood, not the case.

**Comment by lrozenblyum** [comment]
In case of future possible upgrade of RestEasy I'd suggest using at least 4.3.0.Final version which due to change https://issues.jboss.org/browse/RESTEASY-2331
fixes https://issues.jboss.org/browse/RESTEASY-2313

**Comment by stianst** [comment]
The issue was rejected as we can't just upgrade to RestEasy 4, for reasons already explained. An issue requesting support for the admin client in RestEasy 4, with a PR for that would be welcome, but this PR was way to broad and would have broken a lot of things.

**Pull request closed without merging**
