### PR TITLE
Keycloak 19 cannot register post logout redirect URIs whose length in total is over 4000

### LINKED ISSUE #14013: Keycloak 19 cannot register post logout redirect URIs whose length in total  is over 4000
### Describe the bug

In the previous version of keycloak, we could register post logout redirect URIs whose length in total is over 4000 to `Valid Redirect URIs` field of client settings.
     In keycloak 19, post logout redirect URIs needs to be stored in `post logout redirect URIs` field of client settings inpendently. However, when I tried to register such the post logout redirect URIs that could be registered in the previous version on keycloak, I encountered the exception (javax.persistence.PersistenceException).

### Version

19.0.0, 19.0.1

### Expected behavior

Several post logout redirect URIs whose length in total is over 4000 can be successfully registered.

### Actual behavior

The exception (javax.persistence.PersistenceException) is thrown. 

### How to Reproduce?

On client settings, try to register  several post logout redirect URIs whose length in total is over 4000.

### Anything else?

It seems that this exception is thrown because `ClientAttributeEntity` put the following limitation on `value` field.

```
@Table(name="CLIENT_ATTRIBUTES")
@Entity
@IdClass(ClientAttributeEntity.Key.class)
public class ClientAttributeEntity {

    @Id
    @ManyToOne(fetch= FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    protected ClientEntity client;

    @Id
    @Column(name="NAME")
    protected String name;

    @Column(name = "VALUE", length = 4000)
    protected String value;
```
From keycloak 19.0.0, post logout redirect URIs are stored as Client Attribute.
     
I propose that we would lift the limitation on `value` field of `ClientAttributeEntity` the same as `RoleAttributeEntity`, `GroupAttributeEntity`, `UserAttributeEntity`, and `RealmAttributeEntity`.

### PR DESCRIPTION
**Pull request by tnorimat**
Closes #14013

### CODE REVIEW

**Comment by mposolda** [comment]
@hmlnarik Can I please ask for your review on this PR? It seems ok to me as we would use same for the client attributes like we already have for example for USER_ATTRIBUTE_ENTITY or GROUP_ATTRIBUTE_ENTITY. WDYT?

**Review by vramik — COMMENTED** [review]
Sorry for the late reply. I agree with the change and from my POV it's in good shape. Unfortunately I was not able to execute db migration tests as they seems to be broken atm. DB tests passed successfully.

**Review by hmlnarik — DISMISSED** [review]
Approving per @vramik 's approval

**Comment by hmlnarik** [comment]
@tnorimat Could you please rebase? The branch has now conflicts.

**Review by hmlnarik — APPROVED** [review]

**Comment by hmlnarik** [comment]
Thanks @tnorimat, once the tests are green, this is ready for merging

**Pull request merged**
