### PR TITLE
KEYCLOAK-18706 Add UPDATE_PASSWORD required action only to authentica…

### PR DESCRIPTION
**Pull request by mposolda**
…tionSession when MSAD requires user to change password

### CODE REVIEW

**Comment by mposolda** [comment]
@pskopek @pdrozd Do you please have a chance to review this?

**Comment by mposolda** [comment]
@pskopek @pdrozd Added some instructions with possible steps how to test this https://issues.redhat.com/browse/KEYCLOAK-18706?focusedCommentId=16451797&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16451797 .

**Review by pskopek — APPROVED** [review]
It looks good to me. Thanks Marek.

**Comment by mposolda** [comment]
@pskopek Thanks! I am re-assigning to @pdrozd to merge this if he is happy with it.

Pipeline:
https://keycloak-jenkins.com/job/universal-test-pipeline-server/632/ - There is no regression in comparison to master (as Kerberos tests seem to be failing with latest master as well (For example https://keycloak-jenkins.com/job/universal-test-pipeline-server/633/ or https://keycloak-jenkins.com/job/universal-test-pipeline-server/636/ ).

**Review by stianst — APPROVED** [review]

**Pull request merged**
