### PR TITLE
KEYCLOAK-9373 Arabic Translation

### PR DESCRIPTION
**Pull request by Mhmd-Ali**
Arabic translation for login, account, and email themes

### CODE REVIEW

**Comment by stianst** [comment]
Thanks for the PR. We need someone from the community to review this. I will ask on the mailing lists for a volunteer.

**Comment by stianst** [comment]
Closing due to lack of review by community. Please reach out to the community on dev and user mailing list to try to find a volunteer to review if you can find someone it would be great to have the PR re-opened.

**Comment by aaimsh** [comment]
Can I review this?

**Comment by senyahnoj** [comment]
Hi Mohammed. Are you still keen to contribute this work to the community? I too would like to get Arabic language translations into keycloak. Looks like this was closed due to lack of volunteer reviewers which I would be very happy to help with.

**Comment by hbadri3** [comment]
I am native Arabic speaker, I would like to volunteer

**Comment by ahus1** [comment]
@hbadri3 - please have a look at #8484. While this has been closed already, you can start from there, create a new PR and address the issues mentioned there. Please mention me in that new PR so I can guide you. When you open the PR, you'll need another volunteer to review the translation (once the technical comments have been addressed).

**Pull request closed without merging**
