### PR TITLE
KEYCLOAK-1267 Add dedicated SSO timeouts for Remember-Me

### PR DESCRIPTION
**Pull request by sguilhen**
Previously remember-me sessions where tied to the SSO max session
timeout which could lead to unexpected early session timeouts.
We now allow SSO timeouts to be configured separately for sessions
with enabled remember-me. This enables users to opt-in for longer
session timeouts.

SSO session timeouts for remember-me can now be configured in the
tokens tab in the realm admin console. This new configuration is
optional and will tipically host values larger than the regular
max SSO timeouts. If no value is specified for remember-me timeouts
then the regular max SSO timeouts will be used.

Work based on PR https://github.com/keycloak/keycloak/pull/3161 by
Thomas Darimont <thomas.darimont@gmail.com>. Review by Stian
on the original PR was used as a guideline for the necessary changes,
including:
- making both remember-me timeouts optional
- moving the test logic from the adapters testsuite to LoginTest
- cleaning up unnecessary changes throughout the code

Link for the PR that updates the documentation: https://github.com/keycloak/keycloak-documentation/pull/515

### CODE REVIEW

**Review by mposolda — DISMISSED** [review]
@sguilhen Approving, Thanks! We can wait for Matthew if he is fine with the docs

**Comment by sguilhen** [comment]
@mposolda Had to make a small change to one of the tests that failed on travis. Just updated the PR

**Review by mposolda — APPROVED** [review]
@sguilhen ah, ok

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Pull request merged**
