### PR TITLE
fix error : java.lang.ClassNotFoundException: org.keycloak.testsuite.…

### PR DESCRIPTION
**Pull request by gunayus**
…KerberosEmbeddedServer

when I try to run following command : [mvn exec:java -Pkerberos], I got error  : [java.lang.ClassNotFoundException: org.keycloak.testsuite.KerberosEmbeddedServer]

added the dependency for fixing this problem 

        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-testsuite-utils</artifactId>
        </dependency>

### CODE REVIEW

**Review by hdava — COMMENTED** [review]
The comment can be removed as it is already traced by this issue.

**Comment by gunayus** [comment]
> The comment can be removed as it is already traced by this issue.

@hdava sure, removed the comment and updated the PR.

**Review by hdava — APPROVED** [review]

**Comment by gunayus** [comment]
@hdava who can perform approving review? so that the fix is merged onto main branch

**Review by ahus1 — CHANGES_REQUESTED** [review]
@gunayus - thanks for sending the PR to make the example work again.

I see that there is one blank line too many after the closing `</dependency>`, please remove that surplus line. 

The [contributing guidelines of the repository](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md) ask for some formalities:
* Please open a bug describing the problem first. At the moment this is part of the commit message. 
* Update the bug's first comment to contain a "Closes #xxxx" so that it links the PR to the issue
* Update the commits for that PR so that it only contains a single commit, and the commit message has the format of 

```
A brief descriptive summary

Optionally, more details around how it was implemented

Closes #1234
``` 

Thanks!

**Comment by hmlnarik** [comment]
Thank you for the PR. Sadly, we cannot accept this one, as examples have been deprecated in favor of quickstarts and are no longer maintained.

**Pull request closed without merging**
