### PR TITLE
Make GHA Map-JPA base testsuite running with Quarkus

### LINKED ISSUE #13725: Make GHA Map-JPA base testsuite running with Quarkus
### Description

It'd be good to execute our base testsuite with the Map-JPA store.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by vramik**
Closes #13725

### CODE REVIEW

**Comment by mabartos** [comment]
@vramik Thanks for the PR! Could you please create some test PR on top of this, where the Map-JPA is executed? Thanks

**Comment by mhajas** [comment]
@mabartos You can see the jpa tests running here: https://github.com/vramik/keycloak/actions/runs/3427736234/jobs/5711265717

**Comment by mabartos** [comment]
@mhajas But the stage was triggered manually, right? Or not? So, are we sure the automatic triggering works?

**Comment by mhajas** [comment]
Ah, I see. You are right, we should test whether the stage is executed when it should. @vramik Could you try it?

**Comment by mabartos** [comment]
And one thing to consider regarding the testcontainers dependencies. As it's probably planned to create more DB containers for the base testsuite, it'd be good to only fetch the required dependency for it. So, maybe it'd be good to have the possibility to explicitly use a particular DB for these tests, right? I mean, keep the profiles `-Pdb-postgres` and so on - incrementally remove the docker-maven-plugin from use. (cc @nehachopra27 )

But it's not a blocker for this PR and could be done in some follow-up task. Thanks!

**Comment by vramik** [comment]
> Ah, I see. You are right, we should test whether the stage is executed when it should. @vramik Could you try it?

https://github.com/keycloak/keycloak/pull/15424

**Comment by vramik** [comment]
> And one thing to consider regarding the testcontainers dependencies. As it's probably planned to create more DB containers for the base testsuite, it'd be good to only fetch the required dependency for it. So, maybe it'd be good to have the possibility to explicitly use a particular DB for these tests, right? I mean, keep the profiles `-Pdb-postgres` and so on - incrementally remove the docker-maven-plugin from use. (cc @nehachopra27 )
> 
> But it's not a blocker for this PR and could be done in some follow-up task. Thanks!

Yeah, that might be possible follow-up. This change relates only to testing jpa-map store where there is only postgres supported (considering the omit of cocroachdb atm).

**Review by mhajas — COMMENTED** [review]
@vramik, I like the PR. I tested it locally and it works, correctly also with external DB.

@vramik @mabartos I have an idea, we don't need to add this to this PR, but I was wondering. [`HotRodStoreTestEnricher`](https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/HotRodStoreTestEnricher.java) and `PostgresContainerTestEnricher` are quite similar. Should we introduce something like `TestcontainerTestEnricher` that would spawn all Testconainers needed based on some configuration? We can, for example, extend `PostgreSQLContainer` with all code done in `beforeContainerStarted` to be part of `start()` and then `TestcontainerTestEnricher` can only call `start()` on all containers needed, WDYT?

**Comment by mhajas** [comment]
@mabartos @vramik I can confirm https://github.com/keycloak/keycloak/pull/15424 started jpa tests correctly, so I will cancel workflow so we don't waste our precious resources :grinning:

**Comment by vramik** [comment]
> @vramik @mabartos I have an idea, we don't need to add this to this PR, but I was wondering. [`HotRodStoreTestEnricher`](https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/HotRodStoreTestEnricher.java) and `PostgresContainerTestEnricher` are quite similar. Should we introduce something like `TestcontainerTestEnricher` that would spawn all Testconainers needed based on some configuration? We can, for example, extend `PostgreSQLContainer` with all code done in `beforeContainerStarted` to be part of `start()` and then `TestcontainerTestEnricher` can only call `start()` on all containers needed, WDYT?

Some kind of generalization sounds very reasonable. I'll look into it within this PR, unless you prefer to it as follow-up.

**Comment by mabartos** [comment]
@mhajas Definitely agree that these approaches could be more generalized and also easily extended. As we'll need to implement more DB containers for the testsuite and also support some sort of different configuration of the store, I'm totally in! 

It'd also be great to have a shared testsuite module for this. As we need to start DB containers for Base tests, Model tests, and also for Quarkus tests, which are part of `quarkus` module, where we duplicate the effort to quickly start the DB container.

**Review by mabartos — APPROVED** [review]

**Comment by mhajas** [comment]
If we want to make it more generic (usable by integration-arquillian, model and Quarkus tests) we should probably do it in a follow-up as the change would be probably large. We should start with a design proposal in Github discussions and get opinions from more teams. Let me know if you agree so we can proceed with merging this.

**Comment by mabartos** [comment]
@mhajas Yep, agree. Thanks!

**Review by mhajas — APPROVED** [review]
Thanks for the PR @vramik

**Pull request merged**
