### PR TITLE
KeycloakKEYCLOAK-1368: Not able to forward to error page.

### PR DESCRIPTION
**Pull request by code-vineet**
Setting errorPage() to true solves issue.

### CODE REVIEW

**Comment by stianst** [comment]
Tests are failing so can't merge this

**Comment by code-vineet** [comment]
Hi @stianst  do you think setting errorPage() to true is correct solution. If direction is right it might needs to update test-cases/write new ones. Could you please guide here?

**Comment by mposolda** [comment]
This doesn't seem to me like good solution as it changes the status code. For failed bearer authentication, we want to use status code 401 to be sent back to client. Could you try to configure error-page mapping with 401 like I replied you on mailing list?

**Comment by code-vineet** [comment]
@mposolda thanks for reply.
Yes for failed bearer KC should send standard 401 status code to client. On debugging what I found in case of failed bearer and though error-page is provided in <login-config> 
check    if (challenge.errorPage()) {..} in method AbstractKeycloakAuthenticatorValve::authenticateInternal()
prevents forwarding request to <error-page> that's why I set challenge.errorPage() to true in PR.

My point is if this check is false then there is no other way to forward error to custom error-page.

**Comment by mposolda** [comment]
@code-vineet closing this as I opened another PR #1322 , which fixes the tests and adds new test for this functionality

**Pull request closed without merging**
