### PR TITLE
Add tests and docs for relative path and health endpoints

### LINKED ISSUE #13659: Health checks fail when using relative paths in 19.0.0-1
### Describe the bug

When configuring relative paths at build time for both 19.0.0 and 19.0.1, health checks fail to respond even on the container itself. This works as expected on 18.0.2.

### Version

19.0.1

### Expected behavior

Building with a `--http-relative-path` configured along with `--health-enabled` and `--metrics-enabled` set to true should provide a health check responding on `http://localhost:8080/auth/health/live` and  `http://localhost:8080/auth/health/ready` when curling locally from the container.

This is with `--http-relative-path=auth`

### Actual behavior

Building with a `--http-relative-path` configured along with `--health-enabled` and `--metrics-enabled` set to true results in  the following errors when curling the health check paths locally from the container:

```
{"error":"RESTEASY003210: Could not find resource for full path: http://127.0.0.1:8080/auth/health/live"}
{"error":"RESTEASY003210: Could not find resource for full path: http://127.0.0.1:8080/auth/health/ready"}
```

This is with `--http-relative-path=auth`

Note: If `--http-relative-path` is not set during build time, the health checks work as expected from `http://localhost:8080/health/live` and `http://localhost:8080/health/ready`

### How to Reproduce?

Build keycloak container using version 19.0.0 or 19.0.1. Set the HTTP_RELATIVE_PATH during build along with HEALTH_ENABLED and METRICS_ENABLED set to true.

Exec into the container and attempt to curl for the health check against localhost.

### Anything else?

My Dockerfile (I'm electing to build using ENV Vars instead of the CLI Args but I've tested both ways with the same results):

```
FROM quay.io/keycloak/keycloak:19.0.1 as builder

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_HTTP_RELATIVE_PATH=auth
ENV KC_DB=postgres
ENV KC_CACHE=ispn
ENV KC_CACHE_STACK=kubernetes

# Install custom providers
RUN curl -sL https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar -o /opt/keycloak/providers/keycloak-metrics-spi-2.5.3.jar
RUN /opt/keycloak/bin/kc.sh build

RUN curl -sL https://github.com/DataDog/dd-trace-java/releases/download/v0.98.1/dd-java-agent-0.98.1.jar -o /opt/keycloak/dd-java-agent.jar

FROM quay.io/keycloak/keycloak:19.0.1
COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak

ENV KC_LOG_CONSOLE_OUTPUT=json
ENV KC_HTTP_ENABLED=true
ENV KC_HOSTNAME_STRICT=false
ENV KC_PROXY=edge

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--optimized"]
```

Current setup is Keycloak running in a replica set on Kubernetes and Postgres backed. Tested this locally as a single Docker container and Postgres backed with same results. 18.0.2 currently works as expected with only changes to Dockerfile being container version being pulled from quay.io as well as the removal of `--optimized` from entry point.

### PR DESCRIPTION
**Pull request by DGuhr**
Closes #13659

### CODE REVIEW

**Comment by DGuhr** [comment]
@vmuzikar @pedroigor another convenient option would be to have a transformer for relative path in `HttpPropertyMappers` like this: 

```
private static Optional<String> applyLeadingSlashToRelativePath(Optional<String> value, ConfigSourceInterceptorContext context) {

        if(value.isPresent() && !value.get().startsWith("/")) {
            value = of("/".concat(value.get()));
        }

        return value;
    }
```

I actually tried this first, but it seems somewhere in the config layer the transformation does not get applied. When you think it is worth it, I/we can look at it later

**Comment by DGuhr** [comment]
@vmuzikar @pedroigor just to confirm,  we have a regression: 
```
docker run --rm -it -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:18.0.2 start --auto-build --http-relative-path=auth --http-enabled=true --hostname-strict=false --hostname-strict-https=false --health-enabled=true
```

shows the health endpoints when calling `http://localhost:8080/auth/health`, 19.0.1 does not.

**Comment by pedroigor** [comment]
@DGuhr I would say the behavior is expected. Without a slash, paths are considered relative to the root path.

That said, the changes here make sense.

**Comment by pedroigor** [comment]
Could you please check the failing test in the dist test suite ?

**Comment by DGuhr** [comment]
@pedroigor oh, yes. that's a bit unexpected, running it in isolation worked. will investigate.

**Comment by DGuhr** [comment]
@pedroigor I have to admit I can't quite make sense of this error. on my local machine I am not able to reproduce it. I even deleted the test that checks for `--http-relative-path=auth` without the leading `/` to make sure this doesn't kill it. no change. Any ideas?

**Comment by pedroigor** [comment]
I forgot about this one ... Most of the changes here are being addressed here https://github.com/keycloak/keycloak/pull/14012.

Except for how documentation is done. In that PR, I'm just adding the information about the slash in the description. I think is enough.

**Pull request closed without merging**
