### PR TITLE
KEYCLOAK-5779  Czech and Slovak translation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by stianst** [comment]
Thanks for your PR. We are currently in feature freeze for Keycloak 3.x and will not be able to review/merge this work until we open the doors for Keycloak 4.x development.

**Comment by stianst** [comment]
Please update to use utf-8 encoding in properties files. See other translations for example on how to do that.

**Review by stianst — CHANGES_REQUESTED** [review]
Should use utf-8 encoding

**Comment by Joe32** [comment]
Okay i failed this PR somehow fast forward did not work. 
Anyways utf-8 is not working for me out of the box attaching screenshot how it looks. 
screenshot

What needs to be done?

**Comment by stianst** [comment]
Got no clue. I can't review this in this state. Please fix your PR.

**Comment by Joe32** [comment]
Here is new PR as I didn't know how to fix this one https://github.com/keycloak/keycloak/pull/4921.

**Pull request closed without merging**
