### PR TITLE
KEYCLOAK-12874 Align Destination field existence check with spec

### PR DESCRIPTION
**Pull request by hmlnarik**
Fixes per https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf, lines 661-664 and 843-846.

### CODE REVIEW

**Comment by hmlnarik** [comment]
https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/1354/
https://keycloak-jenkins.com/job/universal-test-pipeline-server/1704/

**Comment by hmlnarik** [comment]
Travis fails due to "MediaType not set on path /auth/realms/test/protocol/openid-connect/revoke, with response status 200" which is not related to this PR

**Comment by hmlnarik** [comment]
Pipeline runs:
* https://keycloak-jenkins.com/job/universal-test-pipeline-server/1707/
* https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/1356/

**Review by vramik — APPROVED** [review]
LGTM

**Review by sguilhen — APPROVED** [review]
Took me a while to go through this, sorry. Looks good to me!

**Review by mposolda — APPROVED** [review]
@hmlnarik Thanks for the fix. Approving and merging this. I am relying mostly on the reviews by @vramik and @sguilhen with this PR.

**Pull request merged**
