### PR TITLE
[KEYCLOAK-2035] - Add API ability to 'Get all users in roles in client'

### PR DESCRIPTION
**Pull request by ghost**
I have created a new service to get all the users with a role.

`/admin/realms/{realm}/clients/{id}/users-in-role/{role-id}`

The service returns the list of users

### CODE REVIEW

**Comment by jahenaor** [comment]
How can I fix the error?

**Comment by stianst** [comment]
It would be nice to have the ability to find users that have a specific role. However, there's a few problems here:

* UserQueryProvider is a supported API and needs to remain backwards compatible. It would somehow have to be an optional thing to implement for a UserQueryProvider
* We need the same for realm roles
* We need to have support for this in the UI
* There are no tests

**Comment by stianst** [comment]
I'm rejecting this PR as it's far from complete. To consider adding an option to search for users in a role we need both support for realm roles and client roles. We would also require it being added to the admin console at the same time.

**Comment by jahenaor** [comment]
I understand, sorry. I will work on the points mentioned.

Is the support of this in the UI totally necessary for it to be accepted?

**Comment by stianst** [comment]
Yes, we need the admin console to be updated when related features are added to the admin endpoints

**Comment by howcroft** [comment]
Hi @jahenaor, @stianst,
As this (closed) PR has more comments than the (active) Jira issue [KEYCLOAK-2035](https://issues.jboss.org/browse/KEYCLOAK-2035) I will leave my question here.

Regarding the necessary UI changes:
Is it enough to add a "Users in Role" to the following directives?
* For realm roles - Directive [kc-tabs-role](https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/base/admin/resources/templates/kc-tabs-role.html)
* For client roles - Directive [kc-tabs-client-role](https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/base/admin/resources/templates/kc-tabs-client-role.html)

I have looked at the partials, and it seems to make more sense to add a specific tab e.g. "Users with role". For "cleanness" I think that it would probably be helpful if the API endpoints would be under:
* /admin/realms/{realm}/roles/{role-id}/users
* /admin/realms/{realm}/clients/{client-id}/roles/{role-id}/users

Does this make sense to you?

**Comment by stianst** [comment]
I'd add a "Users" or "Members" tab to the role page like what is done for Groups. Not sure "Members" works for roles though so probably just Users. Your suggestion for REST API works also as it matches groups. Eventually it would be good to make the user search endpoint more powerful, but what you are proposing is good enough for now.

**Pull request closed without merging**
