### PR TITLE
Weak hashing algorithm usage in SSSD User federation

### LINKED ISSUE #23713: Weak hashing algorithm usage in SSSD User federation
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

identity-brokering

### Describe the bug

MD5 is known to be vulnerable to collision attacks, even though we can consider it a weakness this should be fixed to strengthen the security of SSSD module.

**Affected Code:**
- [DirectConnection.java - Line 99](https://github.com/keycloak/keycloak/blob/5ee89ea15ade80bc1d88e0bbe6b13e9c497f9719/federation/sssd/src/main/java/org/freedesktop/dbus/connections/impl/DirectConnection.java#L99-L99)
- [DBusDaemon.java - Line 422](https://github.com/keycloak/keycloak/blob/5ee89ea15ade80bc1d88e0bbe6b13e9c497f9719/federation/sssd/src/main/java/org/freedesktop/dbus/bin/DBusDaemon.java#L422-L422)

### Version

22.0.4

### Expected behavior

Usage of stronger algorithms.

### Actual behavior

Usage of weak algorithms.

### How to Reproduce?

Check the affected code.

### Anything else?

The issue was originally reported by CodeQL. If possible and there are no breaking changes we should aim to solve it.

### PR DESCRIPTION
**Pull request by abstractj**
Closes #23713

### CODE REVIEW

**Comment by rmartinc** [comment]
@abstractj Those classes are just there because I incorporated all `dbus-java` project into keycloak. I rather prefer to delete the files as they are not used in keycloak. Can you please try deleting the following files?

```
federation/sssd/src/main/java/org/freedesktop/dbus/bin/DBusDaemon.java
federation/sssd/src/main/java/org/freedesktop/dbus/bin/EmbeddedDBusDaemon.java
federation/sssd/src/main/java/org/freedesktop/dbus/connections/impl/DirectConnection.java
federation/sssd/src/main/java/org/freedesktop/dbus/connections/impl/DirectConnectionBuilder.java
```

I see that it compiles and I think it will work too. We'll check the SSSD CI tomorrow.

**Comment by abstractj** [comment]
@rmartinc that's even better, less code, less bugs :)

**Review by rmartinc — APPROVED** [review]
LGTM!

**Review by mposolda — APPROVED** [review]
@abstractj @rmartinc Thanks for the PR and review! Merging on behalf of the @rmartinc review.

**Pull request merged**
