### PR TITLE
KEYCLOAK-8977 Added method to get KeycloakSession from RealmCreationEvent

### PR DESCRIPTION
**Pull request by gideonray**

### CODE REVIEW

**Comment by hmlnarik** [comment]
Thank you for the contribution. Sadly, current priorities and bandwidth does not allow us to work on this PR at this moment. Therefore this PR is currently marked on hold. We will be happy to continue the work after 4.x is wrapped up.
Thank you for understanding.

**Comment by stianst** [comment]
Isn't KeycloakSession already available to the provider that is listening for this event?

**Review by stianst — APPROVED** [review]

**Review by stianst — APPROVED** [review]

**Comment by hutiantian04** [comment]
I want to use freemarkeremailtemplateprovider, but it needs keyloaksession as a parameter. How can I get keyloadsession?

**Comment by gideonray** [comment]
> I want to use FreeMarkerEmailTemplateProvider, but it needs KeycloakSession as a parameter. How can I get KeycloakSession?

Are you extending `FreeMarkerEmailTemplateProvider`? If you are, that will be provided in the constructor via the `EmailTemplateProviderFactory`.

**Comment by hutiantian04** [comment]
Thank you for your reply. I'm not extending FreeMarkerEmailTemplateProvider. I want to use the sendExecuteActions and sendPasswordReset methods to send emails. Or is there any other way for keycloak to send mail?

**Pull request merged**
