### PR TITLE
Use a newer version of the server-provisioning-plugin.

### PR DESCRIPTION
**Pull request by bobmcwhirter**
By using a newer version of the plugin, we can reduce
the amount of build code that replicates the provisioning
logic when building overlays.

This applies to both:

* Server distribution overlay
* Adapter distribution overlay

Both overlays are created purely by using the provisioning
plugin and the feature-packs produced elsewhere in the build,
along with the admin-cli artifact when appropriate.

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
@stianst Working with Stuart to get the required changes into the upstream server-provisioning-plugin.  When/if that occurs, this PR will address the usage of it within Keycloak.

I imagine the PR CI check will fail at this point.

**Comment by bobmcwhirter** [comment]
Resync'd this PR with the now-released version of the provisioning plugin for CI to take a look.

**Comment by bobmcwhirter** [comment]
Apparently still waiting for the sync of the plugins to Central.  Dangit.

**Comment by bobmcwhirter** [comment]
Let's try it again.

**Comment by bobmcwhirter** [comment]
@stianst Okay, so this finally passed.  Probably could use a KC person to try a local build `-Pdistribution` and verify the contents of the server and adapter -overlay.  Best I could tell, they are equivalent to the previous method.

**Comment by stianst** [comment]
@bobmcwhirter Will do. I'll take a look at it asap, but it'll be a few days probably. Thanks for this btw! It's something we wanted all along, but never got around to doing.

**Comment by stianst** [comment]
Closing this PR as it needed a few minor tweaks. Sent another PR here:
https://github.com/keycloak/keycloak/pull/4157

**Comment by bobmcwhirter** [comment]
Rock on!

**Pull request closed without merging**
