### PR TITLE
KEYCLOAK-7952 Authorization permissions evaluation cache

### PR DESCRIPTION
**Pull request by mhajas**

### CODE REVIEW

**Review by pedroigor — COMMENTED** [review]
Did you manage to document how to enable permission cache ?

I can write something if you want to.

**Comment by mhajas** [comment]
Hey, I didn't, but I will take a look.

**Comment by stianst** [comment]
What's the status on this PR?

**Comment by mhajas** [comment]
@stianst Unfortunately, I was not managed to finish it. Now it would require probably much more effort to finish it since there were lots of changes since then. I think we should close this PR and plan the issue again with the link to this branch.

**Pull request closed without merging**
