### PR TITLE
Identity-first login flow should be followed by asking for the user c…

### LINKED ISSUE #30339: Identity-first login flow should be followed by asking for the user credentials rather than allowing providing the username again
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

When running the identity-first login flow and once providing an email address, if an account already exists the user is redirected to the regular login page to continue the authentication by providing the credentials.

However, the second-step is still showing the username field and that does not make much sense given that the user already identified him/herself.

In Keycloak, we have a specific flow to only ask the user for credentials once the user is identified. For that, we need to change the `OrganizationAuthenticator` to set the user to the authentication context so that the next flow will only ask for the credentials.

Whether or not this make sense all the time or if we want a specific setting to decide on the expected behavior, we can discuss.

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

After running the identity-first login, do not ask for a username/email again.

### Actual behavior

The username/email field is shown again after running the identity-first login.

### How to Reproduce?

Try to authenticate to an org-aware realm using an account that already exists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by martin-kanis**
…redentials

Closes #30339

### CODE REVIEW

**Review by pedroigor — COMMENTED** [review]
I've update the PR with:

* Revert the removal of assertions when checking template customizations. We need to make sure templates have access to the organization once it is resolved during the identity-first login
* Make sure we respect the current logic where brokers are only shown in the login page for an existing user if they are linked with the user. For now, it is safer to keep existing behavior than ignore it and have it working differently than when not using organizations.

Please, let me know what you think.

**Comment by martin-kanis** [comment]
@pedroigor Thanks for the update. It makes sense to me and looks good!

**Comment by martin-kanis** [comment]
@pedroigor However, tests failures are related to the latest changes.

**Comment by pedroigor** [comment]
@martin-kanis Fixed tests. I'm also making sure organization brokers are filtered when the feature is disabled.

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
