### PR TITLE
narrows condition status to a string

### LINKED ISSUE #21299: Narrow condition status to string
### Description

In a release after 22, we should narrow the type of condition status to string to remove the AnyType workaround #21281

### PR DESCRIPTION
**Pull request by shawkins**
It should be fine to do this in 23 as the operator upgrades should go through the 22 release.

Closes #21299

### CODE REVIEW

**Comment by vmuzikar** [comment]
@shawkins Thanks for the PR. In order to make breaking changes to the CR, we have to figure out the migration story, probably something like:
* deprecate OLD CRD version
* introduce new CRD version with a mutation webhook
* remove OLD CRD version

**Comment by shawkins** [comment]
> In order to make breaking changes to the CR, we have to figure out the migration story, probably something like:

That doesn't apply here as the narrowing conversion will be compatible with all existing CRs.  But yes for any future changes where we change the type of field that is part of the spec in a way that may breaking existing crs, that will need a new crd version.

**Comment by vmuzikar** [comment]
What if somebody upgrades from Keycloak 21 (boolean status) to 23 (string status)? Won't OLM complain?

**Comment by shawkins** [comment]
> What if somebody upgrades from Keycloak 21 (boolean status) to 23 (string status)? Won't OLM complain?

What I meant in the description is that we should be causing the upgrades to go through 22 - https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/how-to-update-operators.md#upgrade-path - all it will take is for the 22 operator version to start and it will update all of the crs to strings rather than booleans.  The 23 upgrades will be fine after that.

**Comment by vmuzikar** [comment]
> all it will take is for the 22 operator version to start and it will update all of the crs to strings rather than booleans

Yeah, that's the theory but I think we should rather double check that to make sure there are no surprises (given it's OLM). I never noticed it installing and running (and waiting for first reconciliation) the versions sequentially.

> Or are you thinking that we'll declaratively allow the skipping of the entire 22 release?

No. What I mean is a use case when someone is on 21, has manual upgrades enabled and then approves an upgrade to 23.

**Comment by shawkins** [comment]
> No. What I mean is a use case when someone is on 21, has manual upgrades enabled and then approves an upgrade to 23.

My understanding is that unless the replaces for 23 specifies 21 or there are explicit skips for version 22, then OLM will have to upgrade in sequence.  I'll double check what is in the current subscription.

**Comment by shawkins** [comment]
> My understanding is that unless the replaces for 23 specifies 21 or there are explicit skips for version 22, then OLM will have to upgrade in sequence. I'll double check what is in the current subscription.

@vmuzikar confirmed with the community operator and manual approval that it walks through every version - there were no skips.

**Review by vmuzikar — APPROVED** [review]
LGTM, I tested OLM is not complaining about the change and Operator is able to update the status field.

It should be also fine in case RHBK skips some versions as the first version will be 22.

Thanks @shawkins!

**Pull request merged**
