### PR TITLE
KEYCLOAK-10393 Fix permission ticket pagination in Authz Client

### PR DESCRIPTION
**Pull request by skyfalke**
Please refer to [KEYCLOAK-10393](https://issues.jboss.org/projects/KEYCLOAK/issues/KEYCLOAK-10393) for details on this pull request.

If you agree to this change, it would be fabulous to get this ported back to the 4.x code base too.

### CODE REVIEW

**Comment by tea-mo903** [comment]
would be great to finally fix this. We noticed some issues too

**Comment by skyfalke** [comment]
My newly introduced test case {{org.keycloak.testsuite.authz.PermissionManagementTest#testGetPermissionTicketWithPagination}} currently fails despite working locally before (as usual, right ;)). 
Now, I realized that it is an intermittent failure even when executing it locally. The test case setup makes sure to make 4 permission tickets available. Then, it fetches 2 with an offset of 2. Afterward, it fetches 2 more with an offset of 0. Eventually, you would expect it to have fetched all 4.
However, intermittently the server returns, for example A & C and then C & D. That kind of implies there is an issue with an arbitrary sorting of the results before applying the pagination offset and page size.

Fortunately, my running Keycloak installation does not seem to have this issue when calling the REST API directly. It is an older version though. But could this be related to how the integration tests spin up the environment?

**Review by pedroigor — CHANGES_REQUESTED** [review]
Thanks for the fix. I'm OK to get it in once we fix the test.

I'm not sure why it is failing but I can take a look at it and see if I find something. If you can't figure out by yourself ....

**Comment by skyfalke** [comment]
I dug into this another half day or so, but came back almost empty handed. I added a busy wait to my test case after the initial setup. Then I started the 'PermissionManagementTest' using the embedded Undertow of Arquillian. 
This allowed me to bypass my updated authz client code and talk to the unmodified Keycloak REST API directly:

> curl -X POST \
>   https://localhost:8543/auth/realms/authz-test/protocol/openid-connect/token \
>   -H 'Accept-Language: application/json' \
>   -H 'Content-Type: application/x-www-form-urlencoded' \
>   -H 'cache-control: no-cache' \
>   -d 'grant_type=password&username=marta&password=password&client_id=resource-server-test&client_secret=secret'
>
> curl -X GET \
>   'https://localhost:8543/auth/realms/authz-test/authz/protection/permission/ticket?resource=42061b75-3cb4-4334-b284-b924968151a4&max=2&returnNames=true&first=2' \
>   -H 'Authorization: Bearer $INSERT_ACCESS_TOKEN_HERE' \
>   -H 'Content-Type: application/json' \
>   -H 'cache-control: no-cache'

The GET call returns inconsistent results. Sometimes, it gives me 'ScopeC' and 'ScopeA'. Other times, the result contains 'ScopeA' and 'ScopeB'. This kind of provides an unsettling proof of an issue that exists in `master` as we speak. Either only in the integration test environment or maybe even beyond that.

I followed the Keycloak server-side implementation up the point where Keycloak hands over to JPA's 'javax.persistence.Query#getResultList' in 'org.keycloak.authorization.jpa.store.JPAPermissionTicketStore#find'. As far as I can see, the pagination is not tampered with Keycloak itself. This is the point I got to so far. @pedroigor , I would truly appreciate your insight in this matter that has left me puzzled for now.

**Comment by pedroigor** [comment]
@skyfalke I'll check the failure and get back to you.

**Comment by pedroigor** [comment]
@skyfalke, I think I found the issue. It seems to be related to the order by clause which is currently based on the id of the resource. It does not guarantee idempotency thus you may have different results on each call.

We should change order by clause to:

```java
orderBy(builder.asc(root.get("id")));
```

After changing the query like above, I don't have any failures and inconsistencies when running the test.

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@skyfalke, thanks for this one.

**Comment by skyfalke** [comment]
Hi again @pedroigor , this morning I applied your proposal to my local code base and ran the test case in a loop for a while with repeated test environment initializations. Indeed that sorting order modification in `keycloak-model-jpa` resolves the intermittent issue.
The reason simply being that the filter condition of my new test case is based on the resource ID, thus, ordering by resource ID is arbitrary nonsense. Looking at the parameters supported by `org.keycloak.authorization.client.resource.PermissionResource#find`, I also believe that the correct way forward was the use of the ìd` as sort criteria. It is an internal field that does not interfere with any of the arguments clients can use with `find`.

It does not matter much now because you committed that change in the meantime. I just wanted to let you know that I had also confirmed this to be fixed.

Anyways, thanks a lot for getting this pull request sorted (no pun intended ;)) and merged! Do you think you will integrate the fix into the current major version of Keycloak, for example into a 6.0.2?

**Pull request merged**
