### PR TITLE
[KEYCLOAK-8980] - ElytronAccount not serializable

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by hmlnarik — COMMENTED** [review]
Lgtm, thanks @pedroigor! (and thanks for covering OIDC in adapter clustered tests! :) )

Before approving, @pdrozd / @mhajas / @vramik could you please review?

**Comment by pedroigor** [comment]
@hmlnarik, I'm about to push some more changes related to KEYCLOAK-9020, which is now incorporated to KEYCLOAK-8980.

I kind of resurrected a ghost, KEYCLOAK-733, which needs to be fixed properly in order to better handle distributable sessions.

My additional changes are about fixing the backchannel logout and tests for that. As well check if programmatic logout works fine. The changes are basically using the same workaround for KEYCLOAK-733 used for the wildfly (legacy) adapter.

**Comment by vramik** [comment]
@pedroigor thank you for the PR. 
@hmlnarik I'll do the review.

**Review by vramik — APPROVED** [review]
@pedroigor lgtm, thank you. There are some test failures with EAP6, but the same failures are there with master, so it's not related with you changes.

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
