### PR TITLE
KEYCLOAK-15137: Move PF4 css files to keycloak/common

### PR DESCRIPTION
**Pull request by ssilvert**

### CODE REVIEW

**Comment by ssilvert** [comment]
Kicked off UI tests for new account console.  Build number 973.

**Comment by ssilvert** [comment]
> Kicked off UI tests for new account console. Build number 973.

UI tests passed.

**Comment by Pepo48** [comment]
> > Kicked off UI tests for new account console. Build number 973.
> 
> UI tests passed.

Hi Stan,

regarding the #973 I see two failures - `applicationListTest` and `toggleApplicationDetailsTest`.
Just to make sure is that ok? If so the changes LGTM - I run couple more tests locally and everything seemed good.

**Comment by ssilvert** [comment]
> > > Kicked off UI tests for new account console. Build number 973.
> > 
> > 
> > UI tests passed.
> 
> Hi Stan,
> 
> regarding the #973 I see two failures - `applicationListTest` and `toggleApplicationDetailsTest`.
> Just to make sure is that ok? If so the changes LGTM - I run couple more tests locally and everything seemed good.

Yes, those are fine.  They are fixed in another pending PR.

**Comment by ssilvert** [comment]
@abstractj Can you review and/or approve?

**Review by abstractj — APPROVED** [review]
Hi @ssilvert my apologies. I'm afraid I won't have the time to review it. But I'm approving based on @Pepo48 review. Also, it would be nice to get his final approval prior to merge, but that's up to you.

**Review by Pepo48 — APPROVED** [review]

**Comment by Pepo48** [comment]
> Also, it would be nice to get his final approval prior to merge, but that's up to you.
Approved :)

**Pull request merged**
