### PR TITLE
Add Ukrainian localization

### PR DESCRIPTION
**Pull request by Zernov-A**
Added Ukrainian language support.

### CODE REVIEW

**Review by sergeysenja1992 — APPROVED** [review]

**Review by jonkoops — DISMISSED** [review]

**Comment by jonkoops** [comment]
Thanks for your contribution @Zernov-A @sergeysenja1992!

**Comment by Zernov-A** [comment]
Thank you for reply. I have asked some people for their review, and I anticipate receiving their feedback soon.
Additionally, I have made some minor enhancements to the translation and force-pushed the changes.

**Comment by Partiolainen** [comment]
I'm Ukrainian native speaker and this translation look good to me

_Нарешті український переклад_

**Review by ahus1 — APPROVED** [review]
Thank you for the community review!

**Review by jonkoops — APPROVED** [review]

**Comment by kammal07** [comment]
hi, when will it be released?

**Pull request merged**
