### PR TITLE
CodeQL won't trigger for backport branches

### LINKED ISSUE #10845: CodeQL won't trigger for backport branches
### Describe the bug

For backport branches like `17.0.0` for example, the pull-request event won't trigger CodeQL workflow, skipping the static analysis.

### Version

17.0.0

### Expected behavior

Trigger the static analysis on pull-requests for every branch.

### Actual behavior

Trigger the static analysis on pull-requests when targetting the `main` branch.

### How to Reproduce?

See: https://github.com/keycloak/keycloak/pull/10834

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by abstractj**
Resolves #10845

### CODE REVIEW

**Review by DGuhr — APPROVED** [review]
may I ask why the cronjobs are also deleted (also for main, i mean)? Don't have all the context, so I assume they make no sense anymore as we check on every PR? 

So as long as that's intended, LGTM - will give an approval, but pls answer ;)

**Comment by abstractj** [comment]
@DGuhr thanks for reviewing it. The cron jobs were removed from the pull-request event because they are redundant. CodeQL is triggered on every pull-request event, and there's no need to schedule its execution on pull-requests.

**Comment by abstractj** [comment]
Thinking a bit about it and our current backport flow. Maybe we should also run CodeQL on every push event. Instead of only `main`.

**Comment by andreaTP** [comment]
@abstractj `on every push event` but on `pull_request`?

We decided some time ago to avoid running CIs on every push to `main` to reduce the "used available runners", we can re-iterate that decision, but I would like to understand how we check/make use of CodeQl reports.

**Comment by abstractj** [comment]
@andreaTP thanks for the sanity check, and your feedback. Considering that we no longer use backport branches, I believe the chances proposed here are out of date, so I'm closing it

**Pull request closed without merging**
