### PR TITLE
KEYCLOAK-10946 Update auth.server.dist.version in testsuite pom.xml

### PR DESCRIPTION
**Pull request by vramik**

### CODE REVIEW

**Comment by stianst** [comment]
Looks like there's a bunch of tests broken with this change, even though the change itself looks sane.

**Comment by abstractj** [comment]
@stianst tests are passing now, I believe we just need a review. They LGTM, but I will wait for people's feedback and @pdrozd has the final saying on it.

**Comment by stianst** [comment]
@mhajas @pdrozd @tkyjovsk hello?

**Review by pdrozd — CHANGES_REQUESTED** [review]
This will not work in the z-stream where we have server.dist set to the latest GA and then we apply the patch. The providers version will be set to the last GA, but we need providers for actual patch testing. Not sure what is the added value of this PR. Will discuss it with @hmlnarik and @vramik

**Pull request closed without merging**
