### PR TITLE
JAVA_OPTS_APPEND does not allow overriding the ipv4/ipv6 setting

### LINKED ISSUE #15925: JAVA_OPTS_APPEND does not allow overriding the ipv4/ipv6 setting
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

See https://github.com/keycloak/keycloak/issues/10482#issuecomment-1343455845.

The steps in the [documentation](https://www.keycloak.org/server/configuration-production#_configure_keycloak_server_with_ipv6_or_ipv4) are also misleading as you can't override de settings.

### Version

20.0.1

### Expected behavior

Override the ipv4/ipv6 settings when setting the `JAVA_OPTS_APPEND` env var.

### Actual behavior

Does not override the ip4/ip6 settings.

### How to Reproduce?

See https://github.com/keycloak/keycloak/issues/10482#issuecomment-1343455845

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #15925

### CODE REVIEW

**Comment by pedroigor** [comment]
@vmuzikar I've run `kc.bat` and it works.

**Comment by pedroigor** [comment]
@ciphermenial Does it work for you?

**Review by vmuzikar — CHANGES_REQUESTED** [review]
Thanks @pedroigor.

I'm not sure about this change, TBH. It is basically a breaking change. Anyone who already uses `JAVA_OPTS_APPEND` for whatever use case, will now have to explicitly set `-Djava.net.preferIPv4Stack=true`.

Maybe we could add a separate variable for overriding just the IPv4/IPv6 setting? Or a switch that would completely disable the default Java opts we're setting and giving complete control about that to the user? WDYT?

**Comment by pedroigor** [comment]
@vmuzikar You're right ... But what you are proposing adds unnecessary complexity. We are actually fixing a bug and the documentation states the expected behavior.

We can certainly mention this in the upgrade/migration guide.

**Review by vmuzikar — APPROVED** [review]

**Pull request merged**
