### PR TITLE
@NoCache is not considered anymore

### LINKED ISSUE #25120: CORS issue in 'openid-connect/certs' endpoint
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

CORS issue in '/realms/{realm}/protocol/openid-connect/certs' endpoint due to change in Cache-Control header value starting in Keycloak 23

### Version

23.0.1

### Expected behavior

No CORS issue during access of '/realms/{realm}/protocol/openid-connect/certs' endpoint when switching from one application to another one configured as separated OpenID Connect clients in a same realm

### Actual behavior

It seems that starting from Keycloak 23.0.0 the Cache-Control header returned by the server when accessing https://{keycloak_domain}/realms/{realm}/protocol/openid-connect/certs endpoint has changed from 'no-cache' to 'max-age=2592000'. When logging in a application A and then accessing the application B on a separate domain (using the same realm but distinct OpenID Connect clients), the header 'Access-Control-Allow-Origin' remains configured to the first domain (of application A) and cause a CORS issue because the domain of application B is not the same.

Example of information captured in firefox : 
Request Headers
```
GET /realms/dummy-realm/protocol/openid-connect/certs HTTP/1.1
Host: accounts.dfakto.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0
Accept: application/json, text/plain, */*
Accept-Language: fr,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Origin: https://application1.example.com
Connection: keep-alive
Referer: https://application1.example.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
```

Respons Headers
```
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 29 Nov 2023 12:36:23 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 2965
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://application2.example.com
Cache-Control: max-age=2592000
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
```

### How to Reproduce?

Create a realm in Keycloak 23+ and then 2 separate OpenID Connect clients using separate domains. Log into the application using the first OpenID Connect client and then try to access the second application

### Anything else?

I'm using NGINX as reverse proxy sot I have a workaround for the moment by adding this block in my configuration :
```
location ~ /realms/.+/protocol/openid-connect/certs {
        # kill cache
        add_header Cache-Control 'no-cache';
        proxy_no_cache 1;
        proxy_cache_bypass 1;

        proxy_pass      http://127.0.0.1:80;
}
```

### PR DESCRIPTION
**Pull request by reda-alaoui**
Fix #25120

See https://github.com/keycloak/keycloak/issues/25120#issuecomment-1866517779 for the why.

### CODE REVIEW

**Comment by reda-alaoui** [comment]
> I see that you changed all annotations, still I didn't see an updated test case. Is there an existing test case that we can enhance so that we're testing for at least one resource that the no-cache headers are present?

I'll have to search for that. But I should be off for the christmas weekend. If someone else can point me directly to this kind of test case, that would be very helpful.

**Comment by reda-alaoui** [comment]
@ahus1 It looks like `org.jboss.resteasy.reactive.NoCache` is not supported by Undertow, but only by Quarkus. Therefore the @NoCache behaviour can only be tested in the Quarkus context. 

I add a test excluding the Undertow environment.

But be aware that in an Undertow test environment, even with this PR, @NoCache is still being ignored. If we want an unified behaviour between Undertow and Quarkus, the only solution I can think of is to get rid of @NoCache annotation and manage CacheControl only programmatically.

**Comment by hmlnarik** [comment]
Removing UI label since this is effectively a core change. Please consider approved from UI team perspective.

**Comment by pedroigor** [comment]
@reda-alaoui It would be nice if we could avoid using Resteasy-specific annotations directly. But I don't think we want to do that in this PR but as a follow-up.

I'll create a follow-up to discuss the introduction of a Keycloak-specific annotation for this purpose. By having an extension point for no-cache, we would avoid this issue in the future and make clear what we need from the underlying JAX-RS stack.

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@reda-alaoui Thanks!

**Comment by pedroigor** [comment]
@ahus1 @hmlnarik Can you help with the approval from ui and store teams?

Regarding Undertow, it should be fine to fix it for Quarkus for now. We can look at Undertow as a follow-up (not sure why one wants to use Undertow).

**Comment by ahus1** [comment]
@pedroigor - consider it approved by store, as it is not store related, and any maintainer can approve the changes (except for the UI changes).

Technically GitHub is expecting an approval from the UI team as there is a change in `rest/admin-ui-ext/pom.xml`, so someone from @keycloak/ui-maintainers would need to approve.

**Review by mabartos — APPROVED** [review]
@reda-alaoui Thanks!

**Review by jonkoops — APPROVED** [review]
Approving based on previous reviews

**Pull request merged**
