### PR TITLE
KEYCLOAK-2028: Support preemptively refreshing access token

### PR DESCRIPTION
**Pull request by bloy-smartling**
Add a new keycloak.json property and mechanism to automatically
refresh access tokens if they are going to expire in less than a configurable
amount of time.

### CODE REVIEW

**Comment by stianst** [comment]
Thanks, implementation looks good, but there's no tests and documentation has not been updated. Any chance you could add that as well?

**Comment by foo4u** [comment]
We'll provide the requested and update PR.

**Comment by stianst** [comment]
Are you able to do the tests for this one? Alternatively just remove the mockito based tests and we'll add tests later.

The default value should be 0, not 5. A longer value than 0 is only required if the application invokes an external service, which probably won't be the most likely scenario for a server-side web application.

**Comment by stianst** [comment]
Closing this PR. Please re-open once Mockito has been removed and it's not enabled by default.

**Comment by foo4u** [comment]
We removed the tests, I'd like to re-open this PR. @stianst I assume reopening this will cause the code to update since we force pushed after rebasing but you have to reopen, I cannot.

**Comment by stianst** [comment]
Seems I can't reopen either. Can you send a new PR?

**Comment by foo4u** [comment]
@stianst new PR coming.

**Comment by foo4u** [comment]
https://github.com/keycloak/keycloak/pull/2190 created.

**Pull request closed without merging**
