### PR TITLE
Move picketlink schema, fix schema resolver and some related tests

### PR DESCRIPTION
**Pull request by skjolber**
https://issues.jboss.org/browse/KEYCLOAK-4979

Imported XML Schema from dependencies

https://mvnrepository.com/artifact/org.jboss.security/jbossxacml/2.0.9.Final
https://mvnrepository.com/artifact/org.picketlink/picketlink-federation/2.7.1.Final

and fixed the schema resolver so that it resolves schema from SchemaManagerUtil as local resources. Fixed up some related unit test.

### CODE REVIEW

**Comment by hmlnarik** [comment]
This PR has been spawn from #4118 and is of lower priority than that. Hence it will be dealt with after the #4118.

**Comment by skjolber** [comment]
PR #4118 has been merged.

**Comment by stianst** [comment]
@hmlnarik @skjolber what's the status on this?

**Comment by hmlnarik** [comment]
@stianst This optimization is both a minor bug fix and enhancement at the same time, yet it spans over 50 files (most of them are added schemata), so it requires rather non-trivial time to have a look at, hence not for 3.4.x.

**Comment by skjolber** [comment]
@stianst 

Schema files can easily be validated by looking at the relevant dependencies. The files should be 100% equal. I suggest copying over the files in the PR and see whether git flags the result as update files.

The XML schema resolver improvements should be trivial for someone who has worked with it before. In general there is a lot of inter-file dependencies, so one of the unit tests is actually loads (creates validator) all schema containing 'saml' so to prove that the resolver works and that the schema are included.

**Comment by stianst** [comment]
@skjolber I've asked @pskopek if he can take a look at this. @hmlnarik just has to many things on his plate. We will try to get this in at least for 3.4.1.

**Comment by pskopek** [comment]
PR looks fine, just small change to make the map really unmodifiable. 
I have pulled changes from this PR and added mine suggested one. 
See https://github.com/keycloak/keycloak/pull/4704

**Comment by stianst** [comment]
@pskopek @hmlnarik @skjolber should we close this PR then as 4704 is the replacement?

**Comment by pskopek** [comment]
@stianst once the https://github.com/keycloak/keycloak/pull/4704 is merged and closed GitHub will automatically close this as well as all commits from this PR are merged as well.

**Comment by hmlnarik** [comment]
Replaced by #4704

**Pull request closed without merging**
