### PR TITLE
KEYCLOAK-17674 - Don't add default role when enable service account

### PR DESCRIPTION
**Pull request by tlereste**
Hello,

See https://issues.redhat.com/browse/KEYCLOAK-17674 for details.

Thanks

### CODE REVIEW

**Comment by pedroigor** [comment]
@tlereste Sorry for the delay. Your proposal makes lot of sense and LGTM.

Are you able to rebase so that we can move it forward?

**Comment by pedroigor** [comment]
@mposolda I think we should have this change in. Wdyt?

**Comment by mposolda** [comment]
@pedroigor I agree with this approach.

On the other hand, I see that someone may want to have something like "Default Roles for Service Accounts" ? It makes sense that it is different set of default roles then regular users, as it likely doesn't makes sense that service-accounts have roles like `manage-account`, `view-account` or `offline_access`.

But anyway, we can go with this PR and then see if some people claims that he needs default roles for service accounts? Another thing is, whether to document this (in migration guide at least)? Without documentation, people can report the bug that default roles doesn't work anymore for them and this bug would be a regression.

**Comment by pedroigor** [comment]
@mposolda True ... So perhaps the best here is to not remove default role support for service accounts but filter which roles should be added to SAs. As an initial approach, we could just filter the default roles targeted for users.

In the future, we might want to provide to switch to set whether a role should also be added to SAs or even provide a specific area for setting default roles for SAs.

The reason I think we should not remove it is that Kubernetes allows you to grant roles to SAs. And I think this requirement is not a corner case. I can see it being useful of OBB too, for example.

**Comment by mposolda** [comment]
@pedroigor Good points. So yes, maybe we should re-consider to not remove "service account default roles" for now.

Now I recall that default roles are now added by the pseudo-role `default-role-foo`, which is created in each realm. So perhaps, we can have similar role for service accounts like `default-sa-role-foo`, which will allow to add default roles for service accounts?

BTV. This also means that this PR may not be valid anymore as it was possibly created before this `default-role-foo` pseudo-role was created?

**Pull request closed without merging**
