### PR TITLE
[KEYCLOAK-18559] Fix SAML adapters so they allow unescaped characters…

### PR DESCRIPTION
**Pull request by sguilhen**
… in URIs

- Makes adapters bahavior consistent with containers that allow unescaped characters in URIs

As discussed with @pdrozd this PR doesn't include automated tests as all libraries used in the testsuite (and others I've experimented with) to send HTTP requests automatically encode the URLs, which makes it impossible to send an unencoded URL to the app server. So testing for this PR was done manually by using curl to send HTTP GET requests to the app server without encoding the test URLs.

When using WildFly as the app server, one has to first enable the 'allow-unescaped-characters-in-url' propery in the undertow subsystem:

    /subsystem=undertow/server=default-server/http-listener=default:write-attribute(name=allow-unescaped-characters-in-url,value=true)

Then, with the SAML adapter correctly installed and a sample app, send a request with unencoded curly braces. Example:

curl -v -L -g 'http://localhost:8280/employee2/x?jsonp={"firstName":"a","lastName":"1123"}'

Without this fix, the request above fails with a java.net.URISyntaxException: Illegal character in query at index 54: http://localhost:8080/test/TestCase02942127.jsp?jsonp={%22firstName%22:%22a%22,%22lastName%22:%221123%22}

When the fix is in place, the URL is correctly handled by the adapter code. Same thing happens when Undertow is used as the app server.

In Undertow the property that allows unencoded URLs can be set when booting the server. For example:

        UndertowJaxrsServer undertow = new UndertowJaxrsServer();
        undertow.start(Undertow.builder()
            .addHttpListener(configuration.getBindHttpPort(), configuration.getBindAddress())
            .setServerOption(UndertowOptions.ALLOW_UNESCAPED_CHARACTERS_IN_URL, Boolean.TRUE));

Then after setting up the adapter and deploying the sample app one can test the issue using the same curl command as shown above to see the exception being thrown when the fix is not applied.

### CODE REVIEW

**Review by mhajas — COMMENTED** [review]
Thank you for the fix @sguilhen! The fix for the SAML adapter looks correct. I am just wondering about other usages of the `KeycloakUriBuilder.build()` method whether we should fix it as well. For example [this](https://github.com/keycloak/keycloak/blob/master/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/ServerRequest.java#L295) or other adapters Tomcat/Jetty.

**Comment by hmlnarik** [comment]
@sguilhen Could you please address the comment above?

**Comment by sguilhen** [comment]
> Thank you for the fix @sguilhen! The fix for the SAML adapter looks correct. I am just wondering about other usages of the `KeycloakUriBuilder.build()` method whether we should fix it as well. For example [this](https://github.com/keycloak/keycloak/blob/master/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/ServerRequest.java#L295) or other adapters Tomcat/Jetty.

Yeah, there are other places that need to be checked. It depends on how the URI is being built essentially but definitely there are other places like in the OIDC adapters that would benefit from this fix. I'm looking into this.

**Comment by mhajas** [comment]
Thank you for the changes @sguilhen! It looks good. We should probably run the adapter pipeline for it. Can you trigger it?

**Comment by sguilhen** [comment]
@mhajas Good suggestion. Triggered a run just now.

**Comment by sguilhen** [comment]
Adapters pipeline run: https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/553/

**Review by mhajas — APPROVED** [review]
Thanks @sguilhen! LGTM

**Review by pdrozd — APPROVED** [review]
LGTM

**Review by hmlnarik — APPROVED** [review]
Approving based on @mhajas's approval

**Pull request merged**
