### PR TITLE
fix KEYCLOAK-7572 consistently perform duplicate user checks during ccount update only if email changes

### PR DESCRIPTION
**Pull request by Mobe91**

### CODE REVIEW

**Comment by abstractj** [comment]
@Mobe91 thanks for your contribution, but I believe the relevant Jira was closed some time ago https://issues.jboss.org/projects/KEYCLOAK/issues/KEYCLOAK-7572. If you still think this change makes sense, feel free to reopen and restart the discussion there. 

Also, please add integration tests to your change.

**Comment by Mobe91** [comment]
@abstractj I do not seem to have the permissions to reopen the issue.

I will add integration tests.

**Comment by abstractj** [comment]
@stianst do you think we should reopen this issue? See the latest comments when you get the chance.

@Mobe91 please squash your commits in a single one. Also your test should reflect exactly the scenario you mentioned, what you're doing in your test case is enabling registration with username.

I believe a good test case scenario:

* Enable the registration as username to test such scenario 
* Attempt to update the account
* Assert for error or success

**Comment by stianst** [comment]
JIRA is re-opened

**Review by abstractj — CHANGES_REQUESTED** [review]
See: https://github.com/keycloak/keycloak/pull/5353#issuecomment-405552502

**Comment by Mobe91** [comment]
@abstractj In my test I am enabling registration email as username and run the same tests as with registration email as username disabled. Are you saying that my test should only contain the account update test and not the other ones inherited by `org.keycloak.testsuite.account.AccountRestServiceTest`?

**Comment by stianst** [comment]
Please add a test to existing AccountRestServiceTest for this scenario rather than adding a whole new test. As it stands today it's hard to confirm the actual scenario you are testing.

**Comment by Mobe91** [comment]
@stianst Added test to existing AccountRestServiceTest

**Review by stianst — DISMISSED** [review]

**Comment by stianst** [comment]
@Mobe91 Nice thanks

**Comment by stianst** [comment]
@Mobe91 almost there - the test running after your new test is broken (AccountRestServiceTest.testGetProfile:82 expected:<[Tom]> but was:<[Homer1]>). You need to set the first name back to the original value to prevent breaking other tests.

**Comment by Mobe91** [comment]
@stianst Ok I did not think that resetting the data is necessary as `org.keycloak.testsuite.account.AccountRestServiceTest#testUpdateProfile` does not reset any data either. In fact, running `org.keycloak.testsuite.account.AccountRestServiceTest#testUpdateProfile` also causes `org.keycloak.testsuite.account.AccountRestServiceTest#testGetProfile` to fail. I will fix that.

**Comment by stianst** [comment]
Closing this PR as I've squashed the commits and fixed the test in https://github.com/keycloak/keycloak/pull/5608. 

@Mobe91 we require work to be squashed into single commits - also with regards to the test it's better to have the single test reset the firstName than to have every test re-import the realms again (we do this to reduce the execution time of the tests).

**Comment by Mobe91** [comment]
@stianst Thanks, I was going to squash the commits together once you approve the changes but will do that continuously in the future.

I saw that your commit does not address the ordering dependency between `org.keycloak.testsuite.account.AccountRestServiceTest#testUpdateProfile` and `org.keycloak.testsuite.account.AccountRestServiceTest#testGetProfile` as mentioned in my previous [comment](https://github.com/keycloak/keycloak/pull/5353#issuecomment-424999588). This was fixed by reimporting the realms for every test but is now broken again. Now the test data needs to be reset manually in `org.keycloak.testsuite.account.AccountRestServiceTest#testUpdateProfile` to fix it.

**Comment by stianst** [comment]
By just resetting the firstName (https://github.com/keycloak/keycloak/pull/5608/files#diff-9f9f04bc1a4250013bd040dfa1fd7914R167) there is no need to do anything more, at least it worked locally for me, on Travis and in our internal CI. Does the updated test in 5609 not work for you?

**Comment by Mobe91** [comment]
Yeah but I am not talking about the new test `testUpdateProfileWithRegistrationEmailAsUsername` but about `testUpdateProfile` that has already existed before. There the user is also altered but not reset which causes `testGetProfile` to fail if `testGetProfile` is executed after `testUpdateProfile`.

**Comment by stianst** [comment]
@Mobe91 ah. It passes on our end for some reason. Can you open a separate JIRA/bug for that one please? A fix would also be awesome, but would be ideal to have the test reset the changes rather than re-import on all the tests.

**Pull request closed without merging**
