### PR TITLE
KEYCLOAK-18386 New authenticator to limit sessions per user

### PR DESCRIPTION
**Pull request by leischt**

### CODE REVIEW

**Comment by stianst** [comment]
Just to clarify, but to enable this capability the "user-session-limit-authenticator" would be added as a last step in the authentication flow, and marked as required? I think we could consider adding it to the default flow rather than require a custom flow, but that can be done as a follow-up rather than as part of this PR.

I can certainly see the use-case to limit the number of active SSO sessions for a user, but not sure the use-case really exists as cleanly for offline sessions. Limiting offline sessions would effectively mean limiting the number of applications can get an offline session for a given user, which honestly doesn't make all that much sense to me.

One thing I find a bit confusing is why is there attr_sort and attr_offline_sort. I don't quite understand how this should be used, and would just expect the authenticator to order them by creation time.

With regards to performance I'm concerned if this approach will scale at all. It is relatively expensive to find users sessions when there are a large number of sessions and many nodes. We may find that we quickly get folks complaining about this being a problem. Have you done any performance testing in this regard?

**Comment by leischt** [comment]
@stianst thank you for your detailed feedback.

> 
> 
> Just to clarify, but to enable this capability the "user-session-limit-authenticator" would be added as a last step in the authentication flow, and marked as required? I think we could consider adding it to the default flow rather than require a custom flow, but that can be done as a follow-up rather than as part of this PR.
> 

Yes, that is right. It has to be integrated as a required step at the authentication flow.
We could provide a follow up to integrate this authenticator to the default flows.

>
> I can certainly see the use-case to limit the number of active SSO sessions for a user, but not sure the use-case really exists as cleanly for offline sessions. Limiting offline sessions would effectively mean limiting the number of applications can get an offline session for a given user, which honestly doesn't make all that much sense to me.
> 

We have a use case, where a mobile app stores a long living offline session, so the user do not need to login every time he want to use the app. If the user logs in again, a new offline session is crated, but the old one is not deleted. We see this additional logins quite often, because of failed refresh token flow executions. In this case the number of offline session will increase and we want to limit this behavior, because of other performance issues caused by a huge amount of offline sessions

>
> One thing I find a bit confusing is why is there attr_sort and attr_offline_sort. I don't quite understand how this should be used, and would just expect the authenticator to order them by creation time.
> 

The creation time is the default behavior, that’s right, but there are some use cases where the last access time is more useful. For example, the Admin User Interface refreshes the session regularly. Therefore, if the last access time is used here, most likely the browser tab, which is no longer actively used, will be logged out, instead of one that was created earlier, but is still in use.

>
> With regards to performance I'm concerned if this approach will scale at all. It is relatively expensive to find users sessions when there are a large number of sessions and many nodes. We may find that we quickly get folks complaining about this being a problem. Have you done any performance testing in this regard?

This authenticator relies on the performance of context.getSession().sessions().getUserSessionsStream(realm, user) .
There was a concern about the performance and a possible solution for a similar (not upstream contributed) authenticator from a different developer for KC 11: https://groups.google.com/g/keycloak-dev/c/vdNbqkUMkrk/m/Cu061iiCAQAJ?utm_medium=email&utm_source=footer
I tried to motivate the developer to share his fix, but I do not know if there were some improvements to get this method faster since KC11. Maybe we could provide a fix based on his idea as a follow up or enhance this PR.

**Comment by mposolda** [comment]
@leischt @stianst Few points:

- +1 for using "last access" time instead of "creation" time when sorting sessions

- The using of offline tokens for mobile application seems like a workaround. Offline tokens are intended to be used for refresh the token without user being present (For example when client needs to trigger some background task in the night without user being present). Isn't it possible that you use client-specific session timeouts for your mobile application? Can this work for your use-case? That will allow us to remove few config options related to offline sessions from the configuration of the authenticator.

- +1 for adding this to the default authentication flow. The authenticator can be disabled by default (Similarly like the other built-in "Kerberos" authenticator). I vote for have it disabled by default due the fact that `session().sessions().getUserSessionsStream(realm, user)` will probably always have some performance impact (likely even with the new store) and most of the people don't need this.

- However the tricky thing, that when adding as default authenticator, we will need to add to most of the flows (Reset Password, Direct Grant) and document that it should be added to "PostBroker Flow" during broker login. The fact that this would need to be added to all the flows in the realm makes me wonder if it is really great idea to implement this feature as the authenticator? Maybe it will be better to use some other centralized place for creating sessions (EG. UserSessionManager?) and makes sure that manager will handle the logic of reject the login if session limit is reached. The sessions limit might then be realm-level configuration option at the "Login Settings" tab of the realm?

**Comment by mposolda** [comment]
@stianst @leischt Marking this as "Requires discussion" as it will be good to clarify on the details and revisit whether authenticator approach is really the best idea (See above)...

**Comment by danielFesenmeyer** [comment]
Just found that there is a very similar (open) PR : https://github.com/keycloak/keycloak/pull/8260

**Comment by mposolda** [comment]
@leischt Thanks again for the contribution! In the end, we used different PR #8260, which was opened for this. I am closing your PR. Feedback is welcome if you missing something in the new authenticator.

**Pull request closed without merging**
