### PR TITLE
KEYCLOAK-12484 Allow conditional flow based on client attribute

### PR DESCRIPTION
**Pull request by sventorben**

### CODE REVIEW

**Review by stianst — CHANGES_REQUESTED** [review]
Thanks for your PR. However, I don't think this is something that should be added out of the box. Can you elaborate on your use-case here? If you are trying to achieve something along the lines of step-up authentication that should not be driven by client attributes, but rather by proper mechanisms supplied by OIDC and SAML, and a more built-in mechanism that allows different authentication level based on the requirements of the client.

**Comment by stianst** [comment]
Please open a discussion around this on the dev mailing list.

**Comment by sventorben** [comment]
@stianst I have a customer that implemented a feature similar to https://stackoverflow.com/questions/54305880/how-can-i-restrict-client-access-to-only-one-group-of-users-in-keycloak/57271777#57271777

With the new conditonal flow I thought it would be way better to make the condition more explicit. Since the execution is based on a 'feature' on per client base, I thought this would be a good way to go. 
However, I can simply implement this as a custom solution and not ootb, if you think this could lead in the wrong direction regarding step up authentication.

**Comment by stianst** [comment]
So the requirement is basically to be able to restrict access to clients based on some roles right? If so that is something that we have wanted to add for a while. We have a few ideas here:

* Require at least one client role
* Require a specific realm role
* Use authorization services to make it really flexible

As we don't have that today I understand the need to work around this limitation, but would rather see a more direct feature added to Keycloak around this than some requiring using some custom authenticator and conditions.

**Comment by stianst** [comment]
Going to close this one for now. Thanks for your PR though.

If you'd like to discuss this further drop an email to the dev mailing list and we can continue the conversation there with the wider community included.

**Pull request closed without merging**
