### PR TITLE
Upgrade to Quarkus 3.2.11

### LINKED ISSUE #27951: Upgrade to Quarkus 3.2.11
### Description

https://github.com/quarkusio/quarkus/releases/tag/3.2.11.Final

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes #27951

### CODE REVIEW

**Comment by vmuzikar** [comment]
Could not update mysql to 8.2.0 (which is what Quarkus uses) as there seem to be some [breaking changes](https://github.com/keycloak/keycloak/actions/runs/8300140262/job/22717406651?pr=27952). But AFAICT, it should be ok.

**Comment by ahus1** [comment]
@vmuzikar - mysql changed their `groupId` to `com.mysql` recently, see 402c7d9b18e8b542ac915e03b919c82dcdca55e4 for the change in main.

**Comment by vmuzikar** [comment]
@ahus1 Thanks. Question is whether we want to do this kind of alignment in a micro release. But I assume we do as that's what [Quarkus did](https://github.com/quarkusio/quarkus/pull/38097). Updated to PR so it now includes the mysql upgrade as well. We can remove it if needed.

**Comment by ahus1** [comment]
@vmuzikar - would we hold this PR until RHBQ 3.2.11 is productized / officially realeased, to avoid us having unproductized dependencies in the branch in case we would need to provide a CVE fix of any kind?

**Comment by vmuzikar** [comment]
Seems the test errors are relevant. Converting to draft.

**Comment by vmuzikar** [comment]
Closing in favor of #28886.

**Pull request closed without merging**
