### PR TITLE
Remove duplicate references on the main pom.xml for SnakeYAML

### PR DESCRIPTION
**Pull request by abstractj**
Depends on #16805

### CODE REVIEW

**Review by mhajas — COMMENTED** [review]
20.0 branch does not have multiple references. Do we need to backport?

**Comment by abstractj** [comment]
You are correct @mhajas. I'd say yes if we would like to move the component version to maven properties.

I believe it would be better than having it hardcoded.

**Comment by mhajas** [comment]
I agree 100% we should have the version within a property, however, is it necessary to have it backported to 20.0.x? To me, it seems it is not, however, if you think it is important I have no problem with it.

**Review by mhajas — APPROVED** [review]
Makes sense to me. I am approving then.

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
