### PR TITLE
clientId clientSecret in header

### PR DESCRIPTION
**Pull request by wqssyq**
set clientId clientSecret in header，with key name "Authorization"

### CODE REVIEW

**Comment by stianst** [comment]
Please create a JIRA and explain why you are making this change. Also, please add a test case as well.

**Comment by patriot1burke** [comment]
Not sure why you are doing this.  It is also allowed to pass client_id and secret as form parameters instead.

**Comment by patriot1burke** [comment]
And the code is already passing those parameters.

**Comment by wqssyq** [comment]
In our company，the client_id an client_securet must set in header.

**Pull request closed without merging**
