### PR TITLE
Make sure pagination is used even when first is null for getGroups en…

### LINKED ISSUE #25731: /admin/realms/{realm}/groups Endpoint is slow
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

After upgrading from Keycloak 22 to 23, the `/admin/realms/{realm}/groups` takes 40-60s for returning 7.5k groups.
It also seems to create a moderate amount of CPU utilization.

### Version

23.0.3

### Expected behavior

The endpoint returns within < 5s with 7.5k groups as it did with version 22.

### Actual behavior

The endpoint returns within 40-60s with 7.5k groups as it did with version 23.

### How to Reproduce?

I did not try to reproduce it with an empty new Keycloak. But I would guess, to create 7.5K groups and call the endpoint.

### Anything else?

We saw the issue with versions 23.0.0/23.0.1/23.0.2/23.0.3

### PR DESCRIPTION
**Pull request by mhajas**
…dpoint

Closes #25731

### CODE REVIEW

**Comment by mhajas** [comment]
Thanks for looking into this @sschu. I am opening this for review as I haven't found anything else to add.

**Review by sschu — APPROVED** [review]
Still LGTM.

**Review by martin-kanis — APPROVED** [review]
@mhajas Thanks for the investigation of the issue and the fix. I can confirm that it fixes the problem (tested by @timo-42 script):

This PR
```
1.80181722 | ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
1.35136291 | ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
0.90090861 | ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
0.45045430 | ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
         0 | ⣇⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣠⣀⣀⣀⣀⣀⣀⣄⣀⣀⣀⣀⣄⣀⣀⣀⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣢⣤⣢⣔⣤⣔⣤⣔⣤⣦⣤⣦⣔⣤⣔⣤⣤⣦⣤⣦⣔⣤
-----------|-|---------|---------|---------|---------|---------|---------|---------|---------|-> (Groups)
           | 0         250       500       750       1000      1250      1500      1750      2000     

```

23.0.3
```
2.35813049 | ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
1.88650439 | ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
1.41487829 | ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⣀⠔
0.94325220 | ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀⣀⠤⠤⠔⠤⠔⠒⠒⠒⠉⠉⠉⠀⠀⠀⠀
0.47162610 | ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⡀⣀⣀⣀⣀⡠⣀⠤⠤⠤⠔⠔⠒⠒⠒⠓⠑⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
         0 | ⣇⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣦⣔⣒⣒⣒⣒⣒⣊⣒⣒⣉⣉⣉⣉⣉⣉⣉⣈⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀
-----------|-|---------|---------|---------|---------|---------|---------|---------|---------|-> (Groups)
           | 0         250       500       750       1000      1250      1500      1750      2000     

```

**Comment by sschu** [comment]
@mhajas I can do the backport PR once this is merged.

**Review by ahus1 — APPROVED** [review]
approving as of @martin-kanis review

**Review by mposolda — APPROVED** [review]
Approving. But did not tried to test and relying mostly on the reviews from others

**Comment by sschu** [comment]
Could it be that there are currently a bit too many reviews required to get a PR merged?

**Comment by mhajas** [comment]
This PR currently conflicts with: https://github.com/keycloak/keycloak/pull/27010 we should decide which PR to merge. I am putting this PR on hold for now. 

Also, we need to include the first commit of this PR to the #27010 PR if we decide to go that route.

**Comment by pedroigor** [comment]
@mhajas I think we can go with your changes first to avoid introducing the index for now and also not assume we want the subgroup count every time you fetch a group.

**Review by pedroigor — APPROVED** [review]

**Comment by mhajas** [comment]
Thank you @pedroigor!

**Pull request merged**
