### PR TITLE
[Draft] Proposal improve probes

### PR DESCRIPTION
**Pull request by andreaTP**
This is a WIP proposal to improve `startup` and `liveness` probes by removing DB access from those.

### CODE REVIEW

**Comment by andreaTP** [comment]
@ahus1 the changes proposed in this PR look(to me) to improve the situation, would you like to have a look and try out this configuration?

**Review by ahus1 — COMMENTED** [review]
Hi @andreaTP - thanks for preparing this PR. I had a look at the new probes you added. 

Reading the command you're executing as the new liveness and readiness probe, I'm trying to reverse-engineer the intent.  

When running the command on a Linux machine and within a minikube pod, it provides me the following output: 

```
$ cat /proc/1/io
rchar: 5929516996
wchar: 177238332
syscr: 1068103
syscw: 109836
read_bytes: 833284096
write_bytes: 163753984
cancelled_write_bytes: 806912
```

When running the "content" part on a shell, I returns the following error messages to me: 

```
$ sh -c "content=$(cat /proc/1/io) && while true; do [[ $content != $(cat /proc/1/io) ]] && exit 0 || sleep 1 ; done"
sh: line 1: 5929517056: command not found
sh: line 2: wchar:: command not found
sh: line 3: syscr:: command not found
sh: line 4: syscw:: command not found
sh: line 5: read_bytes:: command not found
sh: line 6: write_bytes:: command not found
sh: -c: line 7: conditional binary operator expected
sh: -c: line 7: syntax error near `rchar:'
sh: -c: line 7: `cancelled_write_bytes: 806912 && while true; do [[  != rchar: 5929517056'
```

I suspect something is not working as expected here.

Looking at the results I'm not sure about the intent: Is it to check if a process with the ID 1 is running?

If that would be the case, I'd be hesitant if this would work for a startup probe: It would return true even if the Quarkus runtime is still starting. Especially with the auto-build feature it could take some seconds. If the user configured a rolling update, Kubernetes might already stop the old containers while new ones aren't started properly to send a response. Even worse, the startup could fail due to wrong configuration options, but as the startup probe would have shown an initial ok, Kubernetes wouldn't roll back. 

I'm not sure whether how this would behave for a liveness probe, maybe you could first explain to me how the script would work.

**Comment by andreaTP** [comment]
Thanks for checking this out @ahus1 !

I fixed the quoting of the command which was incorrect for interactive usage (the succeeding CI shows that the command was correctly executed in the pods though).

> Is it to check if a process with the ID 1 is running?

This check verifies that process 1 (always Keycloak using our container image) performs "some kind" of IO, so it's not "blocked".

I changed the startup probe following your suggestion back to an HTTP check, unfortunately, this will end up checking the DB too ...

**Comment by andreaTP** [comment]
@ahus1 thanks a lot for checking and experimenting this approach.
One clarification, was the idle instance you tested with connected to an external database? Since I was actually counting on the db connection keep alive

**Comment by andreaTP** [comment]
In my tests I haven't experienced the same, but now I understand that I have always been running on K8s and the IO performed on the Ready probe has, possibly, affected the result of my tests.

**Comment by andreaTP** [comment]
@ahus1 I managed to reproduce your configuration, removing the readiness probe and scaling replicas down to 1 (to exclude Infinispan messaging) I'm able to reproduce your results.

I have two proposals to proceed with:
 - I'm thinking that measuring the fact that the process accepts data/connections on the ready endpoint might not be a bad idea as a live check. Hence tuning accordingly the 2 probes should accomplish the desired result. WDYT?
- Alternatively I can propose to change the check on `io` to a more generic check over the process statistics (reference: https://man7.org/linux/man-pages/man5/proc.5.html):
```
/bin/sh -c 'content="$(cat /proc/1/stat)" && while true; do [[ "$content" != "$(cat /proc/1/stat)" ]] && exit 0 || sleep 0.2 ; done'
```
On an idle Keycloak instance this check returns consistently > 2 seconds.

Thanks again for the help @ahus1 !

**Comment by andreaTP** [comment]
@ahus1 any feedback regarding the last comment?

**Comment by ahus1** [comment]
Hi @andreaTP - it took me a while as I see problems with both approaches: 

* with a TCP connect probe on a HTTP endpoint, I've see too many issues with stacks complaining that a TCP connect is not a proper HTTP request. And even with the connect succeeding, it makes it difficult for me to reason what is currently working in the JVM process and what is not working.
* with the suggestion about the `/proc/1/stat` - this makes it even more difficult for me to reason what is currently working in the JVM and what is not working. 

Therefore I'd suggest to stick with a HTTP probe, even if it uses the same thread pool and port, and which leaves the problem with the dependency on the database to handle. 

There is already Quarkus' standard check at `/q/health/live` - this will return a rather empty JSON response. It will return as long as Vert.x standard worker pool is not exhausted, and will not depend on the database. Similar to this, there is `/q/health/started`, which returns the same. For `/q/health/ready` this checks the database, and for a readiness probe I wouldn't mind that. 

To mimic the behavior of Quarkus with Keycloak's endpoints, I'd suggest the following code change: 

```java
    @BuildStep
    void initializeMetrics(KeycloakRecorder recorder, BuildProducer<RouteBuildItem> routes, NonApplicationRootPathBuildItem nonAppRootPath) {
        final Handler<RoutingContext> healthHandler = (isHealthEnabled()) ? new SmallRyeHealthHandler() : new NotFoundHandler();
        final Handler<RoutingContext> livenessHandler = (isHealthEnabled()) ? new SmallRyeLivenessHandler() : new NotFoundHandler();
        final Handler<RoutingContext> readinessHandler = (isHealthEnabled()) ? new SmallRyeReadinessHandler() : new NotFoundHandler();
        final Handler<RoutingContext> startupHandler = (isHealthEnabled()) ? new SmallRyeStartupHandler() : new NotFoundHandler();
        Handler<RoutingContext> metricsHandler;

        if (isMetricsEnabled()) {
            String rootPath = nonAppRootPath.getNormalizedHttpRootPath();
            metricsHandler = recorder.createMetricsHandler(rootPath.concat(DEFAULT_METRICS_ENDPOINT).replace("//", "/"));
        } else {
            metricsHandler = new NotFoundHandler();
        }

        routes.produce(RouteBuildItem.builder().route(DEFAULT_HEALTH_ENDPOINT).handler(healthHandler).build());
        routes.produce(RouteBuildItem.builder().route(DEFAULT_HEALTH_ENDPOINT.concat("/live")).handler(livenessHandler).build());
        routes.produce(RouteBuildItem.builder().route(DEFAULT_HEALTH_ENDPOINT.concat("/ready")).handler(readinessHandler).build());
        routes.produce(RouteBuildItem.builder().route(DEFAULT_HEALTH_ENDPOINT.concat("/started")).handler(startupHandler).build());
        routes.produce(RouteBuildItem.builder().route(DEFAULT_METRICS_ENDPOINT).handler(metricsHandler).build());
    }
```

As @pedroigor mentioned that the request filter is triggered for any of those, I did a short debug session: I see that the filter is triggered for those, and it starts the JTA transaction. Still, it won't fetch a connection from the database pool yet: when I have a breakpoint in KeycloakReadyHealthCheck.call(), the activeCount is zero (I found that I needed to enable metrics to actually get a proper number here and not the default 0). 

So a `/health/live` will work for me after this code change fine as well. I also stopped the DB container, and then `/health/live` still return 200 OK, and `/health/ready` returns 503. 

WDYT?

**Comment by andreaTP** [comment]
@ahus1 on the theoretical level I have no issues with your reasoning, and I think that the changes you are proposing can be integrated into @pedroigor 's PR.

The only missing data point is the empirical measurement:
Have you already tested this configuration?
Should we compare the effect of those probes under load?

**Comment by ahus1** [comment]
@andreaTP - I did a load test for the liveness probe. It will work with a configuration that allows for load shedding, meaning: it shouldn't queue any requests but return an error. 

A load shedding setup I used: 
- number of Vert.x workers is a lot larger than the number of DB connections (`quarkus.vertx.worker-pool-size` with `100` and `db-pool-max-size` of `1`
- JDBC connection acquisition timeout is low (`quarkus.datasource.jdbc.acquisition-timeout` is `1`, meaning one seconds which is the minimum - `0` is waiting indefinitely AFAIK)

In this setup, there would be up to 100 requests waiting for a DB connection, and would time out after one second.

While the Quarkus instance was shedding the load, the liveness probe was still responding with an OK.

I believe this is as good as it gets with the current setup. 

Without a load shedding configuration, both the Keycloak endpoints and Quarkus endpoints would timeout.

Alternatives (outside of the scope of this):
* when using an opentelemetry or other metrics agent, use the metrics endpoint to return a HTTP probe. Crude, but efficient.
* It would be good to have a non-blocking endpoint for those checks, but AFAIK Quarkus Smallrye doesn't allow for that.
* I suppose load shedding could be improved in the future by limiting the queue size, and the queue size could even be specific to different paths. 

I'd be happy to look into a better load shedding based on the number of queued requests; limiting this by the number of database connections won't work sufficiently once we have for example LDAP that would also be blocking. Also the load should be shedded immediately, and not after waiting for one second as this builds up queues.

**Comment by andreaTP** [comment]
Thanks a lot for the information @ahus1 great job!

I think this is totally enough, for now, I'll speak with @pedroigor and we see how to move on incorporating this suggestion:
https://github.com/keycloak/keycloak/pull/12246#issuecomment-1150067216

**Comment by andreaTP** [comment]
Closing this PR.

cc. @pedroigor @vmuzikar for visibility over the discussion.

**Pull request closed without merging**
