### PR TITLE
KEYCLOAK-16880 Client Policy - Condition : Negative Logic Support

### PR DESCRIPTION
**Pull request by tnorimat**
This PR is for [KEYCLOAK-13933 Client Policies](https://issues.redhat.com/browse/KEYCLOAK-13933), also is the part of the project [Client Policy Official Support](https://github.com/keycloak/kc-sig-fapi/projects) of [FAPI-SIG](https://github.com/keycloak/kc-sig-fapi) activity.

As mentioned in [KEYCLOAK-16880](https://issues.redhat.com/browse/KEYCLOAK-16880), it realized the negative logic of condition you've mentioned in https://github.com/keycloak/keycloak/pull/7659 .

### CODE REVIEW

**Comment by tnorimat** [comment]
@mposolda This PR is not directly about Client Policy Official Support I mentioned in [page 16 of FAPI-SIG 6th Meeting Agenda](https://github.com/keycloak/kc-sig-fapi/blob/master/FAPI-SIG/meetings/6th/presentations/FAPI-SIG_6th_MTG_agenda%20.pdf) but relates to them. Could you or your team also review this PR?

**Comment by tnorimat** [comment]
@mposolda I've rebased and resolved the conflicts due to https://github.com/keycloak/keycloak/pull/7735 .

**Review by mposolda — APPROVED** [review]
@tnorimat Thanks and sorry for the late review..

**Comment by tnorimat** [comment]
@mposolda No problem. Thank you. Hopefully you and your team could other PRs.
- Client Policies
https://github.com/keycloak/keycloak/pull/7780
https://github.com/keycloak/keycloak/pull/7723
- Client Initiated Backchannel Authentication (CIBA)
https://github.com/keycloak/keycloak/pull/7679

**Pull request merged**
