### PR TITLE
[KEYCLOAK-6242] Increase "Wait Increment" value when user tries to lo…

### PR DESCRIPTION
**Pull request by douglaspalmer**
…gin while temporarily disabled

### CODE REVIEW

**Comment by patriot1burke** [comment]
The fact that the user is disabled is not a failure and should not be logged as one with Brute force detection.  Otherwise, they user could be permenently locked out if they keep checking. 

Please see https://issues.jboss.org/browse/KEYCLOAK-5420

FYI, IMO 6424 is invalid because we check validity of user before we check password.

**Comment by douglaspalmer** [comment]
Does the user know what the wait period /failure count? If so then the hacker could deduce the correct password during the wait period.

**Comment by stianst** [comment]
After reviewing this I have some general questions on how brute force protection should work. Clearing this out would help figure out what to do for this issue. We should at least update the docs to clarify these questions. Will probably also need a few more tests to make sure the behaviour is nailed down.

* Failure Reset Time - Is this after the first failed attempt or after the last failed attempt? I believe it should be after the last failed attempt

* Is failed login attempts cleared after a successful login? I don't think it should be and would have a negative impact on security if it was

* Minimum Quick Login Wait label in admin console - This doesn't seem to be a minimum, but rather the actual value used, should this be changed to just Quick Login Wait?

* Should login failures be counted while the account is locked? I don't think it should be (this is the root confusion in KEYCLOAK-6242 I believe)

* Should unlocking account in admin console reset login failures? I think it should

Also have a note that when the account is automatically unlocked after wait interval the login failures should not be cleared. Hence the wait increment would be an increment even if login failures are not counted while the account is locked, as there could be more login failures counted after the account is automatically unlocked.

**Comment by stianst** [comment]
@douglaspalmer @patriot1burke what's happening with this PR?

**Comment by douglaspalmer** [comment]
@patriot1burke Does the current behaviour not allow additional opportunities for brute force to succeed?

**Comment by stianst** [comment]
@abstractj I'm assigning you to this issue. I need someone that can resolve the conversation to figure out what we should do with this PR

**Comment by stianst** [comment]
@douglaspalmer @abstractj I believe we can close this PR as it seems the conclusion for brute force was that we only need documentation changes?

**Comment by hmlnarik** [comment]
+1 for closing it now.

**Comment by hmlnarik** [comment]
Closing as per previous comments.

**Pull request closed without merging**
