### PR TITLE
Added default roles management support to admin client.

### PR DESCRIPTION
**Pull request by pires**

### CODE REVIEW

**Comment by stianst** [comment]
There's compilation issues. Can you also create a JIRA for this? Ideally also add tests to org.keycloak.testsuite.admin.realm.RealmTest

**Comment by pires** [comment]
The cowboy here forgot to add the import which would have been picked if tests were present. I will add those, open a JIRA ticket and update the PR.

**Comment by pires** [comment]
[KEYCLOAK-3352](https://issues.jboss.org/browse/KEYCLOAK-3352)

**Comment by stianst** [comment]
First time around when I reviewed this I thought it was just about adding the admin client, but this is also adding to the admin endpoints. There is actually already support for changing the default roles, so I'm going to reject this PR. Default roles can be changed by changing the defaultRoles array on the realm representation.

**Comment by stianst** [comment]
Sorry about the confusion and wasted time

**Pull request closed without merging**
