### PR TITLE
[KEYCLOAK-5130] - Cookie token store not working in Spring Security adapter

### PR DESCRIPTION
**Pull request by pedroigor**
Follow-up on https://github.com/keycloak/keycloak/pull/4283

### CODE REVIEW

**Comment by pedroigor** [comment]
@scranen @rainerfrey here it is.

**Comment by pedroigor** [comment]
Added https://github.com/keycloak/keycloak-quickstarts/pull/156.

**Comment by rainerfrey** [comment]
@pedroigor I switched my application to this branch and quickly smoke tested it, works as before, so it seems fine to me.

**Comment by pedroigor** [comment]
@rainerfrey tks for checking.

**Comment by stianst** [comment]
This needs to be squashed to a single commit. See https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors for how to add co-author on the commit.

**Review by sebastienblanc — APPROVED** [review]

**Comment by pedroigor** [comment]
@stianst can you bless this one too ?

**Review by stianst — APPROVED** [review]

**Comment by pedroigor** [comment]
@scranen we appreciate your time on this one.

**Comment by JeremyReynard** [comment]
Hello guys,

We've recently upgraded to Keycloak 9.0.0 in order to use the Cookie Token Store in the Spring Boot Adapter.

For the moment, we only set the parameter "keycloak.token-store=COOKIE" for the adapteur.

We were looking for some documentation about how to use it correctly.

We have two use cases:

1) Users authentication to our webapp (using Keycloak of course) in a browser

2) Users authentication to our REST API (using Keycloak of course) via HTTP requests

For 1), we would like to use a standard authentication flow (access_token, refresh_token in HTTP session).

For 2), we would like to use the "Token Store Cookie mode" and exchange the authentication information via the "KEYCLOAK_ADAPTER_STATE" cookie.

We read the Spring Boot Keycloak filters and other Spring Boot adapter classes just to know how the KEYCLOAK_ADAPTER_STATE is managed, but we cannot find how to get this cookie :'(

Could you please give us some example, documentation,...?

Thanks a lot for your help!

**Comment by scranen** [comment]
Hi @JeremyReynard, I don't think it's that plug and play yet. I posted a snippet of our configuration here: https://github.com/keycloak/keycloak/pull/4283#issuecomment-507740785, that was enough for @rainerfrey to get it to work.

**Pull request merged**
