### PR TITLE
[KEYCLOAK-18729] - Support JAR when using PAR

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by pedroigor** [comment]
@tnorimat Could you check if it makes sense for you?

**Comment by tnorimat** [comment]
@pedroigor Yes, it follows https://datatracker.ietf.org/doc/html/draft-ietf-oauth-par#section-3 . This feature is treated as "MAY" so that it seems that the original PR for PAR did not treat it.

**Comment by pedroigor** [comment]
> @pedroigor Yes, it follows https://datatracker.ietf.org/doc/html/draft-ietf-oauth-par#section-3 . This feature is treated as "MAY" so that it seems that the original PR for PAR did not treat it.

Yes, it is. Some profiles might prefer this method when doing PAR so we should now be able to cover more use cases. PAR support is great :)

Btw, I'm also sending another round of changes related to messages. See https://issues.redhat.com/browse/KEYCLOAK-18741.

**Review by mposolda — APPROVED** [review]
@pedroigor Thanks!

**Pull request merged**
