### PR TITLE
CLI options to disable encryption and authentication to external Infi…

### LINKED ISSUE #28750: CLI options to disable encryption and authentication to external Infinispan
### Description

In production, it is recommended to encrypt and authenticate the communication between the Keycloak server and the Infinispan server. However, in some environments, like development, proofs-of-concept, and demos, it is easier to deploy Keycloak + Infinispan without configuring users or TLS  certificates.

The following options are proposed:

* `cache-remote-tls-enabled` -> defaults to true, set to false to allow plain text communication with an Infinispan Server without encryption configured.
* `cache-remote-auth-enabled` -> defaults to true, set to false to allow communication with an Infinispan server without security.

### PR DESCRIPTION
**Pull request by pruivo**
…nispan

Closes #28750

### CODE REVIEW

**Comment by pruivo** [comment]
just a heads-up, I clean up some code in class `quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java`

**Review by ahus1 — CHANGES_REQUESTED** [review]
There is a test failing which checks for the Infinispan histogram metrics, which might be related to your change. Please have a look. Thanks!

**Review by vmuzikar — DISMISSED** [review]
It seems a [mapper](https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/CachingPropertyMappers.java) is missing for the newly added option. @pruivo Can you please check it?

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for the PR. I had some changes to the help output in https://github.com/pruivo/keycloak/pull/3. 

@vmuzikar asked for a new property mapper, and only if there is a property mapper those items show up in the help file. There is also a more recent development where you can configuration option to be dependent on other options. I also sprinkled this new option in some places. 

In the docs, I avoided negated descriptions. I also exchanged SSL with TLS as TLS is the successor to TLS, and TLS is in sync with the naming of our other options.

**Review by ahus1 — APPROVED** [review]
Thank you for this PR! I see @vmuzikar's comments have been addressed.

**Pull request merged**
