### PR TITLE
Add test covering KEYCLOAK-3964 using a method in my previous uncommited pull

### PR DESCRIPTION
**Pull request by mtrue01**
It turns out the test for noImport is pretty close to what I had to do for my original test.  So I modified it and moved it over.   The other two files are from the earlier pull request that is still waiting for commit.

### CODE REVIEW

**Comment by stianst** [comment]
Please squash your PRs to a single commit. Also, please use the following message format:

KEYCLOAK-XXXX Description of what you did

Do not send commits to force re-testing. That can be manually triggered.

**Comment by mtrue01** [comment]
How can I manually trigger it without asking one of you to kick it off?  I can for my own synced repos but not for pull requests. 

Or just send an email saying it should pass and wait?

**Comment by pdrozd** [comment]
Test sent in another PR

**Comment by stianst** [comment]
Just check that it's not your fault that it was broken. If it wasn't your
fault it'll get retriggered by the reviewer of the PR.

**Comment by mtrue01** [comment]
Okay!  

By the way, you write really nice code. :)

—Mark

**Pull request closed without merging**
