### PR TITLE
Registration flow fixed

### LINKED ISSUE #17644: Can create a user without the registration flow finished properly
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

I can create a User entity with the registration flow throwing an Exception. Not all elements are run in the registration flow in such cases, but the user still exists. Neither a REGISTER event is saved for the user.

### Version

21.0.1 (but 19.0.1 is affected as well)

### Expected behavior

If the user entity is created then the registration flow should execute until the end successfully. Probably the whole flow should run in a single transaction.

### Actual behavior

The user entity is created, but an error page is shown to the user. The registration flow is not executed until the end.

### How to Reproduce?

A realm is required where the following is set:
 - registration enabled
 - forgot password enabled

To reproduce:
 - Open the login page
 - Click on the _register_ link
 - Click on the _back to the login_ link
 - Click on the _forgot password_ link
 - Enter a valid, existing e-mail address to the form. Click on the Submit button
 - Press the back button in the browser until you get back to the registration form (~3 times?)
   - a _page is expired_ error will be shown somewhere. Don't care about it, just press the back button until you get back to the login page
 - Fill out the registration form & submit your registration

An error page is shown, but the user is created in the database. From now on the freshly created user can ask for a reset password link, and log in after that with their newly created password.

### Anything else?

I have a fix and will submit a PR in a few minutes.

### LINKED ISSUE #21514: Can create a user without the registration flow finished properly (reopened #17644)
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

Reopening #17644 as suggested on [Slack here](https://cloud-native.slack.com/archives/C056XU905S6/p1688643055350429?thread_ts=1688559314.400539&cid=C056XU905S6)

There was a PR (#19488) that stated to solve the issue, but it did not. It can be reproduced with the latest nightly at the moment.

I can create a User entity with the registration flow throwing an Exception. Not all elements are run in the registration flow in such cases, but the user still exists. Neither a REGISTER event is saved for the user.

### Version

latest nightly (but present since at least 19.x)

### Expected behavior

If the user entity is created then the registration flow should execute until the end successfully. Probably the whole flow should run in a single transaction.

### Actual behavior

The user entity is created, but an error page is shown to the user. The registration flow is not executed until the end.

### How to Reproduce?

A realm is required where the following is set:
 - registration enabled
 - forgot password enabled

To reproduce:
 - Open the login page
 - Click on the _register_ link
 - Click on the _back to the login_ link
 - Click on the _forgot password_ link
 - Enter a valid, existing e-mail address to the form. Click on the Submit button
 - Press the back button in the browser until you get back to the registration form (~3 times?)
   - a _page is expired_ error will be shown somewhere. Don't care about it, just press the back button until you get back to the login page
 - Fill out the registration form & submit your registration

An error page is shown, but the user is created in the database. From now on the freshly created user can ask for a reset password link, and log in after that with their newly created password.

### Anything else?

This is a reopen of #17644 as suggested on [Slack here](https://cloud-native.slack.com/archives/C056XU905S6/p1688643055350429?thread_ts=1688559314.400539&cid=C056XU905S6)

There was a PR (#19488) that stated to solve the issue, but it didoes not. It can be reproduced with the latest nightly at the moment.

I have a PR in #19556 which solves the issue, opened months ago.

### PR DESCRIPTION
**Pull request by mposolda**
Closes #17644
Closes #21514

This is different version of the PR https://github.com/keycloak/keycloak/pull/19556

@ahus1 @sguilhen @vilmosnagy Please see my comment here for the details https://github.com/keycloak/keycloak/pull/19556#issuecomment-1710242950

### CODE REVIEW

**Review by ahus1 — APPROVED** [review]
Thank you @mposolda - I've testing this change and I see that the registration page doesn't show any more, which is a great UX improvement. Looking at the code, it is still checked on submission, so we're extra safe here.

Changes should be squashed once they are merged.

**Comment by ahus1** [comment]
@mposolda - might be a good idea to mark issue #21514 to be backported to KC22 once this is merged, leaving the decision to you as it is core releated.

**Comment by vilmosnagy** [comment]
@mposolda looks great, thanks for all the changes.

One small question though: shouldn't the whole registration flow run in one transaction? If an Exception happens in any "step" (either builtin or custom flow step) of them is it a correct state that we end in? Is there any way to handle rollbacks then?

**Comment by mposolda** [comment]
@ahus1 Thanks! Would you please mind to approve if it looks good to you?

@vilmosnagy The default registration flow runs in one transaction by default after click "Register" button AFAIK. Or more accurately, I think that it works like this:
- When the user clicks `Register` on login screen and the registration form is shown, there is call to `buildPage` for all `FormAction` steps under the `registration form` top subflow. This all happens in one transaction
- When user fills the form and clicks `Register` button, there is another transaction where all the `validate` and `success` steps of all `FormAction` are triggered.
 
So typically, there is one transaction for each HTTP request.

It is possible to re-configure registration flow to involve multiple transactions if administrator decides to add multiple steps under top flow (EG. if he wants something like "wizard" of multiple steps for registering user) and in this case it could be multiple transactions.

I think that throwing AuthenticationFlowException doesn't mean rollback of transaction, which is likely also why the user was created in DB. As a follow-up, we can consider throwing an `AuthenticationFlowException` to also do transaction rollback though, however I am not yet sure about all the side-effects on this, so it currently doesn't work this way. Especially during normal authentication, there are also updates to authenticationSession and we need to make sure that those are not lost. In other words, even if some step in the authentication flow is not successful - like for instance user failed to add proper username/password - the authenticationSession may still need to be updated in the particular HTTP request.)

**Comment by vilmosnagy** [comment]
> I think that throwing AuthenticationFlowException doesn't mean rollback of transaction, which is likely also why the user was created in DB.

Thanks, that answer's all my questions.

**Pull request merged**
