### PR TITLE
Enhance StartDevCommandDistTest to detect problems with URI scheme on Windows

### PR DESCRIPTION
**Pull request by Pepo48**
* added a test - a Windows drive letter within URI can cause issues

Related-to: https://github.com/keycloak/keycloak/issues/29329

Signed-off-by: Peter Zaoral <pzaoral@redhat.com>

Note:
#29329 was fixed earlier in #25333.

### CODE REVIEW

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@Pepo48 Thank you for the fix! Could you please add some test for it?

**Comment by Pepo48** [comment]
@vmuzikar this should be ready for a review.

Thanks!

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@Pepo48 Thank you for adding the test (the actual fix is no longer needed).

The test LGTM but I'm afraid we [don't run it on Win in the CI](https://github.com/keycloak/keycloak/blob/5d0cb7959eae7aaaeedc5d9f708cca05e8e863d3/.github/workflows/ci.yml#L247). We could probably move the test to a test class that runs with Win.

**Comment by Pepo48** [comment]
Sorry @vmuzikar, I forgot about that. I placed it to the StartDevCommandDistTest as I feel it's logically closest. Let me know if it can stay like that. Thanks.

**Review by vmuzikar — APPROVED** [review]
LGTM, thanks for the update! :)

**Pull request merged**
