### PR TITLE
[KEYCLOAK-12569] - User cannot be deleted if he has owned resources permission tickets

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by mhajas — CHANGES_REQUESTED** [review]
The Pr LGTM. However, we would need some more input from the original reporter. I am not sure it fixes his issue as he didn't provide any steps to reproduce and I was not able to reproduce the issue when I reverted your changes. Maybe it is causing issues only with some specific database.

If we won't hear from him, we can merge this as it fixes the issue with not removing PermissionTickets. However, could you please add some tests? When I was trying it I created this one: https://github.com/mhajas/keycloak/commit/544387b881772da470c80345f3f7d2ae85d919ba

**Comment by pedroigor** [comment]
@mhajas To reproduce the issue you need to prepare some things first such as creating a user-managed permission for a user, etc. I'll add tests.

**Review by sguilhen — COMMENTED** [review]
LGTM, pending tests

**Comment by pedroigor** [comment]
@sguilhen @mhajas Thanks.

@mhajas Added your test. I can't remember now how I was able to reproduce the problem, although the error I found was not really the same as reported by the user, as per my comment to that JIRA.

In any case, as you said, we are now removing tickets when users are removed and avoiding removing user policies twice when the user is removed (but just relying on the logic at `UserSyncronizer`).

I'm sure I'm not crazy and the issue happened. Maybe it is random and depends on when the events are processed.

**Review by mhajas — APPROVED** [review]
Thanks @pedroigor. I think it is ok now. We can reopen the issue if the reporter will still experience the problem.

**Review by stianst — APPROVED** [review]

**Pull request merged**
