### PR TITLE
Add model tests for Hot Rod starting multiple nodes

### LINKED ISSUE #12528: Check how HotRodConnectionProviderFactory handles multiple nodes creating caches at the same time
We need to make sure Keycloak is able to startup correctly when multiple nodes start at the same time. A test (probably in model tests) needs to be added that simulates this behavior

### PR DESCRIPTION
**Pull request by martin-kanis**
Closes #12528

### CODE REVIEW

**Comment by martin-kanis** [comment]
Test failures are not related to this PR.

**Review by mhajas — COMMENTED** [review]
Thank you @martin-kanis. The test looks good to me. I think it makes sense to wait for https://github.com/keycloak/keycloak/issues/13110 to be fixed so we can avoid workarounds added to `OfflineSessionPersistenceTest.java`

**Review by mhajas — APPROVED** [review]
Thanks @martin-kanis

**Review by hmlnarik — APPROVED** [review]
Approving per @mhajas 's approval

**Pull request merged**
