### PR TITLE
KEYCLOAK-4059 Support for duplicate emails

### PR DESCRIPTION
**Pull request by sldab**
Keycloak urgently needs support for duplicate email addresses as this blocks most enterprise usage scenarios, including ours.

This PR introduces two additional realm settings:
- Allow login with email
- Allow duplicate emails

The 'Allow duplicate emails' option only becomes available when 'Allow login with email' and 'Email as Username' are disabled.

Support for duplicate emails in the `JpaUserProvider` is realized by reusing the `email_constraint` column that was meant as a hack for MS SQL but fits well to introduce duplicate email support as a __reversible__ realm setting. If support for duplicate emails is enabled, a UUID is always written into the email_constraint column. An introduction of a new contact email attribute would have considerably increased complexity without a real benefit.

~~Of the existing `UserStorageProvider` implementations only the `LDAPStorageProvider` needed a small modification to make sure that the `searchForUser` implementation is able to return multiple users for a searched email address.~~ _(@mposolda already implemented this in one of his latest commits)_ As this is a non-breaking change, it's possible to consider this for new `UserStorageProvider` implementations even before applying this PR. The PR makes sure that  `getUserByEmail` is only called if the upper mentioned realm settings allow it.

The switch back from duplicate to unique emails may require to update the `email_constraint` columns of existing users. I didn't want to do this in a transaction when changing the setting as this possibly long-running transaction would cause a table lock and likely fail. A manual database cleanup is necessary in most cases anyway when switching back from non-unique emails.
If no manual cleanup is done, email constraints are restored lazily upon a user's next login with email, account update or if someone is trying to register with the same email address. A `ModelDuplicateException` is thrown if duplicates exist.

Please let me know if this implementation is fine from your perspective. I'd then write some additional tests for it.

### CODE REVIEW

**Comment by stianst** [comment]
Thanks for the PR. I'm afraid we don't have capacity to review this and merge it at the moment so it will have to wait for 3.x in the new year. I took a very quick glance and I can certainly see that there's a lack of proper testing for this feature.

**Comment by sldab** [comment]
Added a bunch of integration tests and moved DB changesets to 3.0.0.

**Comment by stianst** [comment]
Thanks, sorry about having to delay review/merge, but we're just in the process of wrapping up 2.x and are mainly accepting bug fixes at the moment. I will make sure this gets review early when we get started on 3.x.

**Comment by sldab** [comment]
That's fine. We are starting a big enterprise migration towards Keycloak in February and need to make sure that this gets supported before we reach production. Thanks for the update.

**Comment by stianst** [comment]
If you need it in RHSSO (7.1) for February we'll need to get it in for 2.5.x. Otherwise you'd have to wait for 7.2 to get it supported. I'll try to get this reviewed and merged sooner.

**Comment by stianst** [comment]
@mposolda can you take a look at this PR please?

**Comment by mposolda** [comment]
@sldab Great work!

Few comments:
- Since it is for this release, you can maybe rather add new changeset to the jpa-changelog-2.5.0.xml file? Just a note that we are going to release next week, so will be ideal if you have opportunity to update PR by the end of this week, so we can merge on Monday?

- In the tooltip for "duplicateEmailsAllowed", you mentioned that user's cache must be cleared manually. I think that it is better to rather do it automatically and remove this note from tooltip? You can call something like this: https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java#L869-L872 . Just make sure that it is cleared really if someone changes this switch, not on every realm update :)

**Comment by sldab** [comment]
Thanks for reviewing this so fast! I'll provide an update by tomorrow.

**Comment by sldab** [comment]
I have moved the JPA changeset and Mongo update to 2.5.0. The cache is now cleared automatically in `RealmAdminResource#updateRealm` if the settings have changed. I've also added a query parameter `?v=2.5.0` in URLs pointing to the `realm-login-settings.html` partial to force the browser to rather fetch the updated settings page from the server instead of its cache when accessing it for the first time.

**Comment by mposolda** [comment]
@sldab Thanks for the update! Just one last thing, can you remove the "v=2.5.0" parameter and related stuff? Will you have opportunity to do it today (as we're about to finish 2.5.0.CR1 cycle)?

Reason is, that we already handled updates for browser caches. We add the version to the URL of resources though. So anyone, who is not in "development" mode, but is upgrading from 2.4.0.Final to 2.5.0.Final will automatically see the updated page. For development, it's good idea to disable browser cache. See https://github.com/keycloak/keycloak/blob/master/misc/Testsuite.md and especially the part about "Keycloak server" and "Live edit of HTML and styles". Hope it will be useful for your next great Keycloak contributions :)

@stianst Once the minor change with removing "v=2.5.0" above is done, my vote is to merge this.

**Comment by sldab** [comment]
Ah OK, thanks for clarifying. Good to know this :) Removed the `v=2.5.0` parameter.

**Comment by mposolda** [comment]
@sldab Thanks!

**Pull request merged**
