### PR TITLE
KEYCLOAK-10910 login function now uses promise type specified in init

### PR DESCRIPTION
**Pull request by javfg**
Bugfix for [KEYCLOAK-10910](https://issues.jboss.org/browse/KEYCLOAK-10910).

### CODE REVIEW

**Comment by lucasrusso95** [comment]
Is this will go to air?

**Comment by lucasrusso95** [comment]
@javfg Are you predicting when keycloak-js will support using async / await using Promise without these errors?

**Comment by javfg** [comment]
No idea, the code is ready, they just have to review and accept the merge request.

**Comment by abstractj** [comment]
@javfg could you please rebase against the latest changes from master? Seems like Travis is happy with the latest changes.

**Comment by abstractj** [comment]
@javfg I'm afraid to say that something went wrong with your rebase. There are several commits unrelated with your changes.

**Comment by javfg** [comment]
> @javfg I'm afraid to say that something went wrong with your rebase. There are several commits unrelated with your changes.

Yep, I've noticed. Any ideas on how to if it?

**Comment by abstractj** [comment]
@javfg maybe just get the changes from master and cherry-pick your commit?

**Comment by javfg** [comment]
> @javfg maybe just get the changes from master and cherry-pick your commit?

Should I throw away the entire branch for that? I'll need some guidance, I'm not so knowledgeable on git.

**Comment by abstractj** [comment]
@javfg if you're not familiar with Git, I'd suggest to not throw away your branch, because you might need to look at the changes you had. Instead, create a new branch and add the changes you had on top of that. In this way, you can submit a new PR and close this one.

**Comment by javfg** [comment]
Thanks! On it.

**Comment by abstractj** [comment]
Thank you and take your time.

**Comment by javfg** [comment]
Ok, the new pull request is in https://github.com/keycloak/keycloak/pull/6243.

**Pull request closed without merging**
