### PR TITLE
fix: Incorrect Content-Type Expectation for organization api endpoints

### LINKED ISSUE #34401: Incorrect Content-Type Expectation for POST /admin/realms/{realm}/organizations/{id}/members in Keycloak API
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

When sending a request to the POST /admin/realms/{realm}/organizations/{id}/members endpoint, Keycloak expects the content type to be application/json. However, it only accepts a plain text string (e.g., `95f019a8-977f-b7d5-f781-c1b2a3ef288c`) rather than JSON-encoded data (`"95f019a8-977f-b7d5-f781-c1b2a3ef288c"`). This lead to the following issue with an auto-generated rest api client: https://github.com/fschick/Keycloak.RestApiClient/issues/11 where to client would convert the input into a json string with double quotes but the Keycloak api expects a plain string without double quotes.

### Version

26.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Either the api should change the [definition](https://www.keycloak.org/docs-api/latest/rest-api/openapi.json) to match the expected content type from application/json to text/plain or it accepts a JSON-encoded string.

### Actual behavior

Currently the definition is set to application/json.

### How to Reproduce?

I think https://github.com/fschick/Keycloak.RestApiClient/issues/11 shows pretty accurately what the issue is.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JonasDev17**
Simply changed the media type from APPLICATION_JSON to TEXT_PLAIN

Closes https://github.com/keycloak/keycloak/issues/34401.

### CODE REVIEW

**Comment by JonasDev17** [comment]
@martin-kanis here's the new PR. Does the commit have to be Verified?

**Comment by martin-kanis** [comment]
@JonasDev17  You need to fix also `services` like this https://github.com/martin-kanis/keycloak/commit/5d93096d8c54898808cd9185bccf086212be36ba
Also the commit message should be something meaningful i.e `git commit -s -m "Incorrect Content-Type Expectation for organization api endpoints" -m "Closes #34401"`
I'll check whether the PR doesn't break admin console. Also, we need to discuss internally whether this is a breaking change. If so, we would need to keep both versions in order to honor backwards compatibility.

**Comment by JonasDev17** [comment]
@martin-kanis Thank you for guiding me, this is my first proper OSS contribution. I changed the code to match yours and squashed the commits.

**Comment by martin-kanis** [comment]
@JonasDev17 So it does break admin console. If you try to build this PR locally, start Keycloak server and try to add a member to an organization, it will throw `Could not add users to the organization: RESTEASY003065: Cannot consume content type`. Will you be able to have a look into it?

**Comment by JonasDev17** [comment]
@martin-kanis I can't seem to get keycloak to run locally:  java.lang.ClassNotFoundException: oracle.sql.CharacterSet

**Comment by JonasDev17** [comment]
@martin-kanis I fixed the admin console. The issue was that the wrong header was set and when you change the header it would send the payload as [Object object] as it just turned an object to string instead of using the payloadKey to get the target value.

**Comment by martin-kanis** [comment]
@JonasDev17 Thanks for fixing the admin console. I let you know when we finish the discussion about backwards compatibility.

**Review by stianst — COMMENTED** [review]
This is a breaking change, and also a bit odd that we now suddenly have some endpoints in admin APIs that accept text-plain as the content type.

It should be json content type IMO, and not be a breaking change.

Perhaps we can fix this by just removing quotes?

Honestly, I'm not sure what the best practices are with json content-type when there's a single value/field, but mixing content types in a single API seems an oddity for sure even if it wasn't a breaking change.

**Comment by JonasDev17** [comment]
> This is a breaking change, and also a bit odd that we now suddenly have some endpoints in admin APIs that accept text-plain as the content type.
> 
> It should be json content type IMO, and not be a breaking change.
> 
> Perhaps we can fix this by just removing quotes?
> 
> Honestly, I'm not sure what the best practices are with json content-type when there's a single value/field, but mixing content types in a single API seems an oddity for sure even if it wasn't a breaking change.

You mean just strip out any quotes that are received by the api? That seems to be a bit of a hack to me but it would certainly be a solution...

Personally I would have supplied a single value as json like this:  `{ "userId": "xyz" }` but if we're trying to avoid a breaking change then just stripping out any quotes might just be the best solution.

What would have been even a better solution in my opinion would have been an array of strings to allow multiple users to be added to an org but that's besides the point and maybe something for the future.

**Comment by martin-kanis** [comment]
@JonasDev17 Yeah, just check for the quotes and strip them out if present. Then you can remove all the changes related to the admin console. 
For the future we will discuss and pick more carefully the right content-type. 
And sorry for the back and forth :)

**Comment by JonasDev17** [comment]
@martin-kanis You're all good! Should I also write a comment and link this PR or the Issue? Might help for people in the future coming across the code and wondering why the author stripped out double quotes of the Id

**Comment by JonasDev17** [comment]
e.g.:

image


or short form:

image

**Review by martin-kanis — APPROVED** [review]
Thanks @JonasDev17 LGTM

**Comment by JonasDev17** [comment]
@martin-kanis Tested it just now using postman and it works 👍

**Comment by JonasDev17** [comment]
It does not yet work with my OpenAPI client though but maybe I am using the wrong Id or too soon after the user has been created.  Probably something I am doing wrong on my end as it works with postman.

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
We could probably put this logic into Resteasy Reactive and have it applied to any endpoint using the same definition. Let's see if another case pops up and if it makes sense to have it in the upper layer.

**Review by sguilhen — APPROVED** [review]

**Review by ssilvert — APPROVED** [review]
I'm not sure why this is requiring ui-maintainer approval, but I can approve based on the others.

**Comment by JonasDev17** [comment]
@martin-kanis Is this gonna be released with 26.0.6 or 26.1.0 and when can I expect this release?

**Comment by WMartel** [comment]
This is still not working for some clients. We are using the Mendix low-code platform along with Keycloak, and it has this strange behavior of adding a newline character at the end of a JSON payload. For any other REST endpoint we are calling in any application, internal or external, if the endpoint is expecting and de-serializing a JSON object, the newline character doesn't matter because it is ignored or stripped during de-serialization, but these endpoints don't expect an object or array, just a single string. So if my payload is "the-user-id"\n, the endpoint should only receive the-user-id as the actual value, but it receives the-user-id\n which fails to retrieve the user from the database. I say \n here but I'm not sure it's actually a \n, just some kind of white-space character. I'm going to run some more tests to see exactly what character it is and if we could just change this regex a little bit to catch it as well, because I know we won't be able to fix this on the Mendix side in a timely manner.

**Pull request merged**
