### PR TITLE
JS loadUserInfo add http status to error

### LINKED ISSUE #12: loadUserInfo expose error to client
Area
keycloak-js

Description
Currently, loadUserInfo function doesn't not given error info to client if any error happen

Details
In my personal use case client site pulling userinfo to check current info status, admin site can disable or delete user and then force their session to logged out. so we need to check when loadUserInfo return 401 (unauthorize) system will notify to user and let them to login page.

### LINKED ISSUE #25529: loadUserInfo expose error to client
### Description

https://github.com/keycloak/keycloak/pull/25523

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by parnus01**
Area
keycloak-js

Description
Currently, loadUserInfo function doesn't not given error info to client if any error happen

Details
In my personal use case client site pulling userinfo to check current info status, admin site can disable or delete user and then force their session to logged out. so we need to check when loadUserInfo return 401 (unauthorize) system will notify to user and let them to login page.

```js
.loadUserProfile().catch(e => {
    if (e.status === 401) {
       //this case will notify user
    } else {
      // in any inconsistent cases like, network unstable, system down...
    }
});
```

Closes keycloak/keycloak-js#12

### CODE REVIEW

**Comment by jonkoops** [comment]
@parnus01 can you log an issue to go along with this enhancement and link it to this PR?

**Comment by parnus01** [comment]
> @parnus01 can you log an issue to go along with this enhancement and link it to this PR?

done

**Comment by edewit** [comment]
@parnus01 you need to sign off your commit

**Comment by parnus01** [comment]
signed off, add to loadUserProfile func too.

**Pull request closed without merging**
