### PR TITLE
#1074 - Allow registration with email as username

### PR DESCRIPTION
**Pull request by velias**
https://issues.jboss.org/browse/KEYCLOAK-1074
Allow registration with email as username (without username as separate field)

### CODE REVIEW

**Comment by stianst** [comment]
Can you please remove the formatting of code that's not related to your changes?

**Comment by velias** [comment]
I used code formatter recommended by mposolda (from liveoak). But it seems that KC source codes do not use any consistent formatting. I probably have to disable automatic formatting for KC at all. I'm really not used to rely on manual formatting recently. 
Coping with this will probably take me a lot more time than implementation of the feature itself ;-) OK, going to play with it.

**Comment by velias** [comment]
OK, formatting of unrelated parts is removed

**Comment by stianst** [comment]
Thanks for formatting the code.

When this option is enabled the login form should display 'Email' instead of 'Username or email'. We also need some tests added. Would you like to look at that? I can do it if you're busy.

**Comment by velias** [comment]
Thanks, I can add both. Can you point me to the right place to create tests please? You mean some integration tests?

**Comment by stianst** [comment]
In testsuite/integration there's two tests that should cover your needs:
* org.keycloak.testsuite.forms.LoginTest
* org.keycloak.testsuite.forms.RegisterTest

You can also add tests for the admin part, but that's less important as our coverage is not very good there. If you'd like to you can add it to org.keycloak.testsuite.admin.RealmTest.

**Comment by velias** [comment]
Label in login form changes and all relevant tests are added. Code is rebased to latest keycloak master.

**Pull request merged**
