### PR TITLE
Update Operator docs to reflect Keycloak CR changes

### LINKED ISSUE #14924: Update Operator docs to reflect Keycloak CR changes
This should cover documentation for https://github.com/keycloak/keycloak/issues/13456.
* Update [existing Operator guides](https://github.com/keycloak/keycloak/tree/main/docs/guides/src/main/operator) (mainly the examples) to reflect the breaking changes (moved  fields etc.).
* Remove ["Disabling required CR fields" chapter](https://www.keycloak.org/operator/advanced-configuration#_disabling_required_cr_fields) as the fields are now optional. As a replacement, document how to disable TLS and hostname natively via Quarkus dist options.
* Add a generic note explaining the alignment between Keycloak CR fields and Quarkus dist options. Emphasize that they have the same behavior and map 1:1.

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes #14924

### CODE REVIEW

**Review by pedroigor — APPROVED** [review]

**Review by mabartos — APPROVED** [review]

**Comment by mabartos** [comment]
@vmuzikar I guess you need to execute also the Build phase in the workflow as the retention time for Keycloak artifacts has already expired.

**Review by Pepo48 — APPROVED** [review]
LGTM, thanks Vašek.

**Comment by vmuzikar** [comment]
@mabartos I re-triggered the CI. It doesn't allow me to merge without the required steps green (even though it's just docs).

**Pull request merged**
