### PR TITLE
Rewrite changelog SQL to make it work on Oracle

### LINKED ISSUE #19841: Upgrade from 21.0.2 to 21.1.0 fails on oracle db
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

When updating keycloak 21.0.2 to 21.1.0 the database gets changed. 
jpa-changelog-21.1.0.xml tries to change the dataType of some columns.
This fails with the messages:
```
{​​​​​​​​"timestamp":"2023-04-20T10:56:56.122Z","sequence":8465,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler","level":"ERROR","message":"ERROR: Migration failed for changeset META-INF/jpa-changelog-21.1.0.xml::21.1.0-19404::keycloak:\n Reason: liquibase.exception.DatabaseException: ORA-01439: column to be modified must be empty to change datatype\n [Failed SQL: (1439) ALTER TABLE KEYCLOAK_MASTER_TEST.RESOURCE_SERVER_POLICY MODIFY DECISION_STRATEGY NUMBER(3)]","threadName":"main","threadId":1,"mdc":{​​​​​​​​}​​​​​​​​,"ndc":"","hostName":"keycloak-77d7b6c65c-ptd8z","processName":"QuarkusEntryPoint","processId":211}​​​​​​​​
{​​​​​​​​"timestamp":"2023-04-20T10:56:56.122Z","sequence":8466,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler","level":"ERROR","message":"ERROR: ORA-01439: column to be modified must be empty to change datatype\n [Failed SQL: (1439) ALTER TABLE KEYCLOAK_MASTER_TEST.RESOURCE_SERVER_POLICY MODIFY DECISION_STRATEGY NUMBER(3)]","threadName":"main","threadId":1,"mdc":{​​​​​​​​}​​​​​​​​,"ndc":"","hostName":"keycloak-77d7b6c65c-ptd8z","processName":"QuarkusEntryPoint","processId":211}​​​​​​​​
{​​​​​​​​"timestamp":"2023-04-20T10:56:56.123Z","sequence":8467,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler","level":"ERROR","message":"ERROR: ORA-01439: column to be modified must be empty to change datatype\n","threadName":"main","threadId":1,"mdc":{​​​​​​​​}​​​​​​​​,"ndc":"","hostName":"keycloak-77d7b6c65c-ptd8z","processName":"QuarkusEntryPoint","processId":211}​​​​​​​​
``` 

### Version

21.1.0

### Expected behavior

Update of the column types.

### Actual behavior

Server crash.

### How to Reproduce?

Setup Keycloak 21.0.2 from docker image sourced at quay.io against an oracle database.
Configure it, that the table RESOURCE_SERVER_POLICY gets an entry.
Run Keycloak 21.1.0 against the same database.
View it failing to start.

### Anything else?

In issue https://github.com/keycloak/keycloak/issues/19404 the broken changelog was introduced.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #19841

### CODE REVIEW

**Comment by ahus1** [comment]
I've performed the following local tests: 

PostgreSQL:
* Start Keycloak from main with PostgreSQL - changelog succeeds after I change the cast to `SMALLINT` instead of `TINYINT`

OracleDB:
* Start Keycloak from main with Oracle without the changeset - column is still `VARCHAR()`
* Added data to `RESOURCE_SERVER_POLICY` by enabling client authentication and authorization for one client
* Start Keycloak again with the changeset - column is now migrated to `NUMBER(3)`, value is filled with old values

@vramik - this is now ready for review (builds are still running)

**Comment by ahus1** [comment]
Tests failed for MySQL and MariaDB. Reworking.

**Comment by vramik** [comment]
@ahus1 if current changeset works for each database except oracle, maybe we can leave it as is, but make it conditional not to run with oracle [1] and introduce the new one for oracle only[2]?

[1]
```xml
<changeSet author="keycloak" id="21.1.0-19404">
    <preConditions onFail="MARK_RAN" onSqlOutput="TEST">
        <not>
            <dbms type="oracle"/>
        </not>
    </preConditions>
    ...
```

[2]
```xml
<changeSet author="keycloak" id="21.1.0-19404-oracle">
    <preConditions onFail="MARK_RAN" onSqlOutput="TEST">
        <dbms type="oracle"/>
    </preConditions>
    ...
```

**Review by vramik — APPROVED** [review]
@ahus1 Thank you for the fix!

**Review by mhajas — APPROVED** [review]
Approving per @vramik 's approval. Thank you both!

**Pull request merged**
