### PR TITLE
Inject the operand version as env var

### LINKED ISSUE #11287: Determine Keycloak image tag from Operator version
Currently the operator by default uses `latest` tag for Keycloak images. To avoid hardcoding the tag in every release, the operator can derivate the default matching Keycloak image tag from the operator version.

Proposed solution:
* Remove [`operator.keycloak.image`](https://github.com/keycloak/keycloak/blob/1661a4ecc76fee3ff86d8d8f5d3c91728b333662/operator/src/main/resources/application.properties#L8) config option.
* Add a new config option: `operator.keycloak.image.name=quay.io/keycloak/keycloak`.
* Add a new config option: `operator.keycloak.image.tag` (this will not be defined by default in [`application.properties`](https://github.com/keycloak/keycloak/blob/1661a4ecc76fee3ff86d8d8f5d3c91728b333662/operator/src/main/resources/application.properties).
* Use the following flow when [determining the Keycloak image](https://github.com/keycloak/keycloak/blob/1661a4ecc76fee3ff86d8d8f5d3c91728b333662/operator/src/main/java/org/keycloak/operator/v2alpha1/KeycloakDeployment.java#L406):
   * If `image` field is defined in the CR, use that.
   * If `operator.keycloak.image.tag` is defined by the user, use `operator.keycloak.image.name:operator.keycloak.image.tag`.
   * Otherwise, use `operator.keycloak.image.name:{calculatedTag}`. Calculate the tag as follows:
```
if (quarkus.application.version == "999-SNAPSHOT") {
   calculatedTag = "nightly"
} else {
   calculatedTag = quarkus.application.version
}
```

### PR DESCRIPTION
**Pull request by andreaTP**
Resolves #11287

### CODE REVIEW

**Review by vmuzikar — DISMISSED** [review]
Approving as long as the Operator CIs passed.

**Review by vmuzikar — APPROVED** [review]
Approving based on green Operator CI.

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@andreaTP I totally missed that we haven't removed the image override from the subscription:
https://github.com/keycloak/keycloak/blob/ba37f6a289f70ab552c99c948fa089e8ea38f005/operator/scripts/create-olm-test-resources.sh#L53-L56
Can you please remove it?

**Comment by andreaTP** [comment]
@vmuzikar forgot it! Fixed and rebased!

**Review by vmuzikar — APPROVED** [review]
@andreaTP Thanks!

**Review by stianst — APPROVED** [review]

**Pull request merged**
