### PR TITLE
Add a new identity provider for LinkedIn based on OIDC

### LINKED ISSUE #22383: LinkedIn as Identity provider not working
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

oidc

### Describe the bug

When using for the first time LinkedIn as an Identity Provider, Keycloak sends by default the "r_emailaddress" oAuth2 scope, to which LinkedIn responds : 

> error : unauthorized_scope_error
> error_description = "r_emailaddress" is not authorized for your application

The issue seems to be at : https://github.com/keycloak/keycloak/blob/1d444ff86228b741f85fd68aacf6e06e9d53031d/services/src/main/java/org/keycloak/social/linkedin/LinkedInIdentityProvider.java#L58

```
		// email scope is mandatory in order to resolve the username using the email address
		if (!config.getDefaultScope().contains(EMAIL_SCOPE)) {
			config.setDefaultScope(config.getDefaultScope() + " " + EMAIL_SCOPE);
		}
```

### Version

22.0.0

### Expected behavior

Keycloak should only send the requested scopes when dealing with LinkedIn (in my case, openid, profile and email).

### Actual behavior

When calling LinkedIn, keycloak always add the "r_emailaddress" scope that LinkedIn doesn't accept.

### How to Reproduce?

- Set up a new app in LinkedIn
- Request access to the "Sign In with LinkedIn using OpenID Connect" product
- Create a new LinkedIn IdP in keycloak, using the clientId and secretId from LinkedIn
- Copy the keycloak redirect URL to the LinkedIn app
- Try to login

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmartinc**
Closes https://github.com/keycloak/keycloak/issues/22383

Adding a new identity provider for LinkedIn based on OIDC but with workarounds for the two problems commented in the issue. Comments:

* The nonce problem has been fixed adding a new config option for OIDC common provider that disables the nonce at authentication (default enabled as it's now). LinkedIn extension forces the option to disabled.
* The jwks issue is different and it's fixed using a custom implementation of the PublicKeyLoader that adds the keys without use with the requested use.
* The old LinkedIn provider is not deleted but deprecated (don't know if old implementations are working now, so I have just deprecated it). It will be removed definitely in future versions.
* Only two mappers (LinkedInUserAttributeMapper and UsernameTemplateMapper) have been added to the new provider. We can add more OIDC mappers, but I have just added the same we are using in google or other OIDC based provs.
* Documentation for LinkedIn modified to explain how to add the new provider.

Just let me know if you prefer something different for any point.

@mposolda I suppose we need to add a paragraph for the release or migration notes. IMHO migration doc is better. What version 22.0.x or 23? Do we want backport for this one?

### CODE REVIEW

**Comment by mposolda** [comment]
@rmartinc +1 for add something to migration docs as you pointed before.

Is it possible to somehow emphasize in the UI that LinkedIn provider is deprecated? As the fact that java class is deprecated is not sufficient as normal Keycloak users/administrators won't see that info in the java sources. Maybe changing `LinkedIdIdentityProviderFactory.getName()` to something like `LinkedId - Deprecated` can be helpful as this is what is shown in the UI.

One additional question: How it look in the admin console when you open the page "Identity providers" and there are not any Identity providers in the realm? IMO it can be nice if both `LinkedIn - Deprecated` and `LinkedIn OpenId Connect` are shown with the LinkedIn logo. The fact that one is marked as deprecated is likely good enough to make it clear that people should use the `LinkedId OpenId Connect` . WDYT?

**Review by jonkoops — DISMISSED** [review]
Changes to the Admin Console look good to me.

**Review by mposolda — APPROVED** [review]
@rmartinc Thanks!

**Comment by rmartinc** [comment]
@mposolda Thanks! Added the upgrade comment in 22.0.2 version (I'll prepare the backport when this PR is merged). Added the new provider name to get the LinkedIn icon in the console. And the old provider was renamed to `LinkedIn (deprecated)` (sorry, I put that name without realizing you have already proposed one). I fixed a test that failed after the rename. :smile:

**Pull request merged**
