### PR TITLE
Fix types KeycloakInstance

### PR DESCRIPTION
**Pull request by deather**
I write 2 classes representing resourceAccess and roles, and I change the properties types of KeycloakInstance :

    realmResource
    resourceAccess

Thanks for reading.

### CODE REVIEW

**Review by ssilvert — APPROVED** [review]

**Comment by ssilvert** [comment]
Sorry I missed this earlier.  Looks fine but it will be a few more days before we can merge.

**Comment by ssilvert** [comment]
@keycloak-ci-bot test

**Comment by ssilvert** [comment]
Also needs JIRA.  I'll create one.

**Comment by ssilvert** [comment]
https://issues.jboss.org/browse/KEYCLOAK-8743

**Comment by deather** [comment]
@ssilvert Thanks for the ticket. There is one check failed, but I can't have the details.

How can I fix the error ?

**Comment by ssilvert** [comment]
@deather I looked at the failure and I don't understand it.  I'm going to let it run again and see if we get the same result.

**Comment by ssilvert** [comment]
@keycloak-ci-bot test

**Comment by ssilvert** [comment]
@keycloak-ci-bot test

**Comment by stianst** [comment]
@keycloak-ci-bot test

**Comment by stianst** [comment]
@keycloak-ci-bot test

**Pull request merged**
