### PR TITLE
KEYCLOAK-3586 Adding tests for updateToken

### PR DESCRIPTION
**Pull request by mhajas**

### CODE REVIEW

**Comment by stianst** [comment]
You shouldn't set the timeSkew in keycloak.js. Instead you should have two test scenarios:
* Time in sync - timeSkew ~= 0
* Set time offset on the server and check timeSkew ~= offset on server. You can set the time skew on the server using TestingResource#setTimeOffset

**Comment by mhajas** [comment]
But I am not testing timeSkew I can add another test if you want. What I am testing here is the scenario from issue KEYCLOAK-3586 and I am using timeSkew as a timeOffset on the browser side. 

The test case is: 
1. Login -> I should have a token for 33s
2. Offset time to 33s later.
3. Refresh token -> another token for 33s
4. Offset time to another 33s later (Issue was that in this moment js adapter set timeSkew wrongly and say that token is valid for another, I think 15s)
5. Refresh token only if validity is less than 5s (With bug there is no refresh in this moment)
6. Now I make bearer request to keycloak and with bug it will fail because the token is no longer valid

**Comment by stianst** [comment]
Ok, that makes more sense, but as you're setting timeSkew property you would actually not have detected the issue in KEYCLOAK-3586 as the problem was the timeSkew property was not set correctly. Better approach would probably be to use a large minValidity.

Would be good to test timeSkew as well. Checking the value of that would actually have identified the issue in KEYCLOAK-3586.

**Comment by mhajas** [comment]
It definitely will detect issue KEYCLOAK-3586, I tested it. I am not setting timeSkew with = but only add an offset to it with += [Here](https://github.com/keycloak/keycloak/pull/3265/files#diff-95ed3a00129d0e539d0313c079e47c5cR150). 

Okay, I agree with you, I will add also test for timeSkew. So, for now, I am closing this issue, I will create a new one then.

**Pull request closed without merging**
