### PR TITLE
[KEYCLOAK-10419] Added support for briefRepresentation param on the group/members endpoint

### PR DESCRIPTION
**Pull request by jeroentervoorde**

### CODE REVIEW

**Comment by stianst** [comment]
PR looks decent, but we need tests to be added.

**Comment by jeroentervoorde** [comment]
@stianst Thanks for the review, i added a test for the new parameter.

**Comment by stianst** [comment]
Thanks, but we can't accept tests using a mocking framework. Please read https://github.com/keycloak/keycloak/blob/master/docs/tests-development.md.

**Comment by jeroentervoorde** [comment]
I added a new test to the existing arquillian GroupTest now.

**Comment by stianst** [comment]
Code and test looks code except for one minor thing. It would be better to use a hardcoded group and username, then remove both at the end of the test. The reason is that we re-use the same realm for other tests (to reduce execution time). Leaving additional things in the realm may affect other tests.

**Comment by jeroentervoorde** [comment]
Hi @stianst, I updated the test as requested.

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
@jeroentervoorde nice - thanks for quick turnaround.

**Pull request merged**
