### PR TITLE
Avoid using JBoss dependency which contains some old Log4j classes

### LINKED ISSUE #15844: Keycloak contains EOL Log4j version
### Area

dependencies

### Describe the bug

Keycloak contains log4j 1.2.17 as reported by one of scan which is EOL. This needs an upgrade in the version in the upcoming releases. This dependency is present in the main pom.xml under keycloak/pom.xml.

### Version

19.0.3

### Expected behavior

Log4j version needs to be upgraded with the latest version.

### Actual behavior

NA

### How to Reproduce?

the dependency is visible in main pom.xml.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
This assumes all dependencies already use different logging frameworks

Closes #15844

### CODE REVIEW

**Comment by ahus1** [comment]
@abstractj / @vmuzikar - it seems that no-one is using log4j in the Quarkus distribution any more, as the tests show green.

Therefore I'd like to remove the JBoss Logger Log4j Adapter that causes false positives. Thanks!

**Review by vmuzikar — COMMENTED** [review]
I see a lots of
```
<java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
```
in various POMs. I wonder if we should safely remove them as well. WDYT @pedroigor?

**Comment by ahus1** [comment]
@vmuzikar - this PR is only about the Quarkus distribution to remove the Log4j bridge of the JBoss Logmanager. The JBoss Logmanager itself is still in use (otherwise there would be no logs showing in Quarkus), and it will receive logs from other sources like slf4j, commons logging, etc. 

The setting you mentioned above (`java.util.logging.manager`) should stay that way, so that logs from `java.util.logging` go to the the JBoss log manager.  

Independently from this PR, there are additional efforts necessary to remove log4j in other places as well - see for example PR #20422 - those should be tackled one-by-one outside of this PR.

**Review by vmuzikar — APPROVED** [review]
@ahus1 Sorry for the confusion, you are correct of course. LGTM.

**Pull request merged**
