### PR TITLE
[KEYCLOAK-6376] Fixing Conditional OTP by reusing existing API for ro…

### PR DESCRIPTION
**Pull request by hypery2k**
JIRA: [KEYCLOAK-6376](https://issues.jboss.org/browse/KEYCLOAK-6376)

### CODE REVIEW

**Comment by stianst** [comment]
Thanks for your PR. Assigning it to @hmlnarik to review himself or delegate to someone from his team.

As a quick feedback we do not accept tests using Mockito (please read the contributors guidelines https://github.com/keycloak/keycloak/blob/master/CONTRIBUTING.md), so the tests will have to be rewritten to use the same approach as we use for the rest of the testsuite.

**Comment by hypery2k** [comment]
I updated my PR, but the test is failing and i have to idea why it's not working out. Did I miss anything in the test setup?

**Comment by hypery2k** [comment]
@stianst could you retrigger the server-group1 run, it was failed due to an networking issue?

**Comment by hypery2k** [comment]
I think this fix should be also rolled out to 4.x and 6.x, especially for the rh-sso product

**Comment by abstractj** [comment]
@hypery2k could you please rebase your pull request to include the latest changes from master? Travis might be happy now.

**Comment by hypery2k** [comment]
thanks for the hint, CI passes now

**Review by stianst — CHANGES_REQUESTED** [review]
Looks pretty good, but needs a few minor tweaks

**Comment by hypery2k** [comment]
worked in your feedback, should be good now. Would be also great to backport this to older versions of keycloak, IMHO

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
@hypery2k Afraid we do not have capacity to maintain older versions of Keycloak. Rather, we put a lot of effort into making the upgrades seamless and highly recommend using the latest version always.

**Comment by hypery2k** [comment]
okay, got it. Thanks for merging.

**Pull request merged**
