### PR TITLE
Remove conditionals about Linux vs. Windows

### LINKED ISSUE #26028: Remove conditional statements about Windows / Linux from the docs

### PR DESCRIPTION
**Pull request by ahus1**
Closes #26028

### CODE REVIEW

**Comment by ahus1** [comment]
On hold until 22.0.8 docs have been published

**Comment by ahus1** [comment]
22.0.8 docs habe been published, no longer on hold

**Comment by ahus1** [comment]
@mhajas - please approve based on the parent PR's review and merge when you have the time. Thanks!

**Review by mhajas — APPROVED** [review]
Thanks for the backport @ahus1!

**Pull request merged**
