### PR TITLE
KEYCLOAK-14723 Compilation error in performance testsuite

### PR DESCRIPTION
**Pull request by tkyjovsk**
- removed outdated DatasetTest which caused the error
- some log tweaks
- removed js policies from the datasets (upload_scripts is disabled by default now)

### CODE REVIEW

**Review by pedroigor — APPROVED** [review]
I'm interested in this one :)

**Comment by pedroigor** [comment]
Btw, I also fixed the compilation error in another PR. Could you wait a bit before merging this one ?

**Comment by tkyjovsk** [comment]
> Btw, I also fixed the compilation error in another PR. Could you wait a bit before merging this one ?

Sure, it can wait. Do you see any issues with disabling the js policies in the datasets? Alternatively we could enable upload_scripts feature for the perf test and keep the js policies as they are.

**Comment by tkyjovsk** [comment]
Compilation error resolved by KEYCLOAK-14680. Closing.

**Pull request closed without merging**
