### PR TITLE
KEYCLOAK-19228: Prevent user enumeration in FIPS mode

### PR DESCRIPTION
**Pull request by trixpan**
Generate enough bits during DummyHash functions

### CODE REVIEW

**Comment by trixpan** [comment]
@pedroigor could you kindly verify / approve this PR? Valeu! ;-)

**Comment by mposolda** [comment]
@trixpan Can you please rebase this PR with latest main? GH actions are not able to build this PR. Hopefully rebase can help.

**Comment by trixpan** [comment]
@mposolda apologies for the delay. rebase done

**Review by mposolda — APPROVED** [review]
@trixpan Thanks

**Pull request merged**
