### PR TITLE
KEYCLOAK-8541: Admin console uses vulnerable AngularJS

### PR DESCRIPTION
**Pull request by ssilvert**

### CODE REVIEW

**Comment by ssilvert** [comment]
@keycloak-ci-bot test

**Review by vmuzikar — CHANGES_REQUESTED** [review]
I've build the distribution from your branch. Using Chrome's "incognito mode", I've logged in into the Admin Console. I can see that `angular.min.js` is loaded but looking at the header it's still v1.6.6.

@ssilvert Could you please review?

**Comment by ssilvert** [comment]
Glad you caught that.  Looks like we now have two node_modules directories.   It's possible that Stian added the second one by mistake, but it could have been intentional.

I'm going to update the other one and be done for now.  I'll create a separate JIRA to investigate.

**Comment by ssilvert** [comment]
Now I see what he did.  The second version is a "clean" directory with only the stuff that belongs in the distro.  We really need to pull that stuff out automatically so we don't have two copies of the same file in the repo.  But again, that's a task for another day.

**Comment by ssilvert** [comment]
@vmuzikar You should be able to retest this now.

**Comment by vmuzikar** [comment]
@ssilvert I suppose you've updated the files in the other node_modules directory "manually".
For the consistency, shouldn't we instead use the approach @stianst mentioned - `mvn clean install -P npm-update`?

**Comment by ssilvert** [comment]
I don't think it makes a difference.  The result is exactly the same.

**Comment by vmuzikar** [comment]
Ok, if we're sure the result is the same, I'll proceed with the testing...

**Review by vmuzikar — APPROVED** [review]
LGTM now, thanks.

**Comment by ssilvert** [comment]
@keycloak-ci-bot test

**Review by stianst — APPROVED** [review]

**Pull request merged**
