### PR TITLE
Add raw OpenApi documentation files to rest-api documentation

### LINKED ISSUE #21559: Provide raw OpenAPI specification alongside Keycloak Admin REST API html documentation
### Description

It would be nice for the Admin REST API html documentation to link to the raw OpenAPI specification that it was generated from so the community can have a reliable OpenApi specification source.

### Discussion

_No response_

### Motivation

With the merge of #20669 it should be trivial to also provide access to the raw specification for the purpose of generating clients in different programming languages. 

Currently there are only third party community projects that attempt to create a spec through best effort parsing of either the html documentation or the source code. They are not 100% reliable, lag behind keycloak releases and are a waste of effort if the HTML documentation generation step just needs an additional write to disk of the raw json/yml spec
https://github.com/ccouzens/keycloak-openapi
https://github.com/dahag-ag/keycloak-openapi

### Details

_No response_

### PR DESCRIPTION
**Pull request by DAHAG-ArisNourbakhsh**
Closes #21559

### CODE REVIEW

**Comment by abstractj** [comment]
Thanks, @DAHAG-ArisNourbakhsh, for your pull request. I think the changes you suggested have been replaced by the ones in https://github.com/keycloak/keycloak/pull/20669 by @jsorah.

**Comment by DAHAG-ArisNourbakhsh** [comment]
Could you point me to the url on the keycloak documentation page where either the raw open-api json/yml can be found at? I thought the PR you linked only generated the documentation html.

**Comment by jsorah** [comment]
@abstractj  - looks like this PR is taking the intermediate OpenAPI spec generated from the changes I made and making it available from the rest-api documentation page, so I would consider this additive to what I did previously. This seems like a middle ground between not giving devs an easily accessible OpenAPI spec and publishing it on a running KC instance, and instead, just publishing the API spec on the rest-api documentation page for a particular KC release.

**Comment by tohak22** [comment]
What would be the way to generate the openapi.json with the proposed changes? I cant seem to find them anywhere after running `mvnw clean install -Pdistribution`.

**Comment by DAHAG-ArisNourbakhsh** [comment]
> What would be the way to generate the openapi.json with the proposed changes? I cant seem to find it anywhere after running `mvnw clean install -Pdistribution`.

They were already generated even without this PR. This just copies them so the exported documentation also contains them 

From a blank checkout of keycloak:

```
mvnw -pl quarkus/deployment,quarkus/dist -am -DskipTests clean install
cd services
mvn -s ../maven-settings.xml -Pjboss-release clean package
```

and then they can be found under `\services\target\apidocs-rest\output`

**Comment by y-tabata** [comment]
@abstractj @jsorah @DAHAG-ArisNourbakhsh 
Are there any tasks to proceed with this PR to merge? Just rebasing?

**Comment by DAHAG-ArisNourbakhsh** [comment]
> @abstractj @jsorah @DAHAG-ArisNourbakhsh Are there any tasks to proceed with this PR to merge? Just rebasing?

As far as I'm concerned, only rebasing.

**Comment by ahus1** [comment]
I had a look, and I see at least two levels of problems: 

* Typo in the docs where it should be OpenAPI
* Using the passthrough syntax where it should use AsciiDoc

A more general question:
 
* Is the OpenAPI specification a fully supported feature that everyone should use, or is it rather a preview feature? I think I still see a lot of warnings when it is generated.

Looping in @999eagle as I know you have been working with the OpenAPI specs. I'd be happy if you could comment on how usable the currently generated OpenAPI documentation is.

**Comment by DAHAG-ArisNourbakhsh** [comment]
> Using the passthrough syntax where it should use AsciiDoc

The passthrough syntax was the only way I understood on how to get the html anchor tags into the final document. 

> Is the OpenAPI specification a fully supported feature that everyone should use, or is it rather a preview feature? I think I still see a lot of warnings when it is generated.

My opinion on this:

There are most likely still a lot of problems with the OpenAPI definition that go beyond warnings that can only be found when using it in real world scenarios. For example wrong status codes that the static validation can't pickup (dahag-ag/keycloak-openapi#8) (POST /admin/realms to be precise. Should be a 201/20X but says it's a 200) 

This status code is also completely wrong in the html APIDocs as they are based on the faulty OpenAPI specs. So I'd argue that if the keycloak teams feels comfortable to release the docs in this state then it should not be a problem to also host the faulty spec files. And in the end this will only help to get more eyes on them and find all the issues

**Comment by 999eagle** [comment]
I'm still finding (and trying to fix) more discrepancies between the OpenAPI spec and the actual API. I'm fairly certain most endpoints are documented now, but a lot of endpoints are still missing annotations in the source code to document the possible API responses.
As it stands right now, I personally feel like the OpenAPI spec is still more of a preview feature. I very much appreciate the raw spec files being added to releases and the rest-api docs but they probably should be accompanied by an explicit warning about their incompleteness.

**Comment by y-tabata** [comment]
IMO, it should be a preview feature. This is because there are warnings by following the OpenAPI notation and some deviations from the implementation.
However, I understand that these warnings and mistakes were latent in the existing HTML API specification, and have become more obvious by generating OpenAPI. So I believe that making it public and having more people contribute to the warnings and mistakes that have surfaced will improve the quality of the REST API, so it is worth making it public, even if it is just a preview feature.

**Comment by haker93** [comment]
I am also using the openapi spec in my project. I had to manually fix a few things:

1. POST for /admin/realms/{realm}/client-scopes response adjusted to be 201 (openapi spec said it was 200)
2. PUT for  /admin/realms/{realm}/client-scopes/{id} response adjusted to be 204 (openapi spec said it was 200)
2. DELETE for  /admin/realms/{realm}/client-scopes/{id} response adjusted to be 204 (openapi spec said it was 200)
3. POST for /admin/realms/{realm}/client-scopes/{id}/protocol-mappers/models response adjusted to be 201 (openapi spec said it was 200)
4. /admin/realms/{realm}/client-scopes/{id}/protocol-mappers/models/{id} has 2 times the same parameter. I changed the name of the first one to scopeId
5. POST /admin/realms/{realm}/clients response adjusted to be 201 (openapi spec said it was 200)
6. PUT /admin/realms/{realm}/clients-initial-access/{id} response adjusted to be 204 (openapi spec said it was 200)
7. In ClientRepresentation the property oauth2DeviceAuthorizationGrantEnabled was not known by the api. I removed it from the spec
8. In RealmRepresentation the properties oAuth2DeviceCodeLifespan and oAuth2DevicePollingInterval were included twice. I removed the duplicates.

There are probably more problems. I only changed the endpoints i am actually using.

**Comment by ahus1** [comment]
Thank you for all the feedback. I'll look into how to change this PR's content so that it shows this as a preview. 

While I'm doing it, please submit PRs to update the OpenAPI spec generation. As usual, small issues and PRs that focus on one topic at a time are preferred. If you want to work in pairs on this and have a community member review it, it might free up maintainer's time to work on other things / might get you ahead in the queue. 

To coordinate, there is already discussion here, so you can drop a note once you have a PR and are looking for another community member: https://github.com/keycloak/keycloak/discussions/8898

Be aware that there is a discussion about a v2 Admin API. But as that is not around the corner, we would all benefit from improving the existing documentation in the time being: https://github.com/keycloak/keycloak/discussions/8983

**Comment by ahus1** [comment]
I've updated this PR to include the following message, see screenshot below. 

Please comment here if you agree/disagree with this change. It will then be included in the KC24 community release. 

image

**Comment by y-tabata** [comment]
@ahus1 LGTM

**Comment by ahus1** [comment]
@mhajas - could you please review approve and merge this PR that has been reviewed by the community? Thanks!

**Review by mhajas — APPROVED** [review]
Thank you @DAHAG-ArisNourbakhsh and @ahus1

**Pull request merged**
