### PR TITLE
Added Turkish support to Account ui

### PR DESCRIPTION
**Pull request by mcihad**

### CODE REVIEW

**Comment by jonkoops** [comment]
Thanks for adding these. As a quality control we always ask another native speaker to take a look at pull requests that change translations. If you know of anyone who can do this for you, please include them as a reviewer.

**Comment by jonkoops** [comment]
This PR still needs a review from another native Turkish speaker before it can be merged. @ilhanyumer @adilarli considering your previous contributions, would you be able to take this on?

**Comment by ilhanyumer** [comment]
Hello @jonkoops . As a native Turkish speaker I have reviewed the translations and I don't see any problem. I approve the translations in this commit.

**Comment by jonkoops** [comment]
Thanks a lot @ilhanyumer! I'll go ahead and get this merged. Thanks for your contribution @mcihad.

**Review by jonkoops — APPROVED** [review]

**Pull request merged**
