### PR TITLE
Update messages_de.properties

### PR DESCRIPTION
**Pull request by Korsche09**
Friendlier adaption of loginTimeout Message

### CODE REVIEW

**Comment by stianst** [comment]
@thomasdarimont could you take a look at this one please?

**Comment by thomasdarimont** [comment]
@Korsche09 The "tone" of login messages is "somewhat" consistent across the supported locales in Keycloak and has been around for quite some time already. User documentation and tests might depend on this.

I'm inclined to not accept this as it might break existing testing infrastructures or lead to inconsistent documentation. 
Any particular reason why you don't override the `loginTimeout` message in a custom theme message resource bundle?

**Review by thomasdarimont — CHANGES_REQUESTED** [review]
Waiting for feedback.

**Comment by thomasdarimont** [comment]
@Korsche09 no worries :)

Generally if you contribute to an open-source project for the first time, you should take a look at the https://github.com/keycloak/keycloak/blob/master/CONTRIBUTING.md file if present.

**Pull request closed without merging**
