### PR TITLE
KEYCLOAK-8250: Save not disabled properly in token settings

### PR DESCRIPTION
**Pull request by ssilvert**

### CODE REVIEW

**Review by vmuzikar — CHANGES_REQUESTED** [review]
I believe I've found one marginal issue caused by this.

Steps to reproduce:
1. Go to the Realm's Token settings page
1. In "Override User-Initiated Action Lifespan" select:
    * Any token type
    * "1" as the time value
    * Leave the default time unit (minutes)
1. Save button is disabled even though the form is properly filled

**Comment by ssilvert** [comment]
I think it's finally correct now.  It's very tricky.  If I had to do it over I would change the UI, which is just awful for this thing.

**Review by vmuzikar — APPROVED** [review]
@ssilvert Thanks, LGTM.

I agree the UI is terrible and difficult to use. Created a JIRA for this: https://issues.jboss.org/browse/KEYCLOAK-8717

**Comment by ssilvert** [comment]
@keycloak-ci-bot test

**Review by stianst — APPROVED** [review]

**Pull request merged**
