### PR TITLE
Optimize settings for Hibernate ORM

### LINKED ISSUE #26162: Optimize query batching and result fetching by tuning Hibernate parameters
### Description

Hibernate offers a few performance tuning option which do not seem to be applied in Keycloak.

I propose to add the following defaults or at least offer an easy way to configure them:
```
<!-- execute multiple insert and update statements in a single call to improve bulk insert / update performance, see https://vladmihalcea.com/hibernate-performance-tuning-tips/ -->
<property name="hibernate.jdbc.batch_size" value="50" />

<!-- (optional) allows for more batching but according to https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/chapters/batch/Batching.html "Comes with a performance hit, so benchmark before and after to see if this actually helps or hurts your application." -->
<property name="hibernate.order_inserts" value="true" />
<property name="hibernate.order_updates" value="true" />

<!-- increase number of elements fetched from Oracle database query result up from 10 (MSSQL returns the whole result at once); see https://docs.oracle.com/en/database/oracle/oracle-database/21/jjdbc/resultset.html -->
<property name="hibernate.jdbc.fetch_size" value="50" />

<!-- (optional) pad in-clause queries to next power of 2 to improve query execution plan caching, see https://thorben-janssen.com/parameter-padding/ -->
<property name="hibernate.query.in_clause_parameter_padding" value="true" />
```

Due to https://github.com/keycloak/keycloak/issues/19427 persistence.xml / Quarkus properties issue the settings cannot be applied easily so I would propose to either offer them as Keycloak configuration options similar to some other Hibernate settings or extend the defaults.

See also https://access.redhat.com/documentation/de-de/jboss_enterprise_application_platform/5/html/performance_tuning_guide/sect-performance_tuning_guide-entity_beans-batching_database_operations

### Discussion

_No response_

### Motivation

Applying this settings by modifying the persistence.xml in the keycloak-model-jpa-22.0.5.jar tenant creation operations were sped up by about a factor of 2.

### Details

_No response_

### PR DESCRIPTION
**Pull request by sebastianh6r**
Closes #26162

### CODE REVIEW

**Review by u3r — APPROVED** [review]
Speed up on e.g. tenant creation confirmed.
No adverse effects seen (on local test)

**Comment by ahus1** [comment]
Thank you for the PR. The results look ok, still the need a bit of tweaking to handle the new JDBC batch exceptions. 

I prepared a PR for this PR. Please merge it, and then see the CI results: https://github.com/bci-oss/keycloak/pull/2

I wasn't able to push this commit directly, as it seems that the check box to allow maintainer to push changes to the PR is disabled.

**Comment by ahus1** [comment]
The tests are now green, so I gave it a short performance test using the Keycloak-Benchmark project: I deployed Keycloak with a local PostgreSQL database and created 100_000 clients using the dataset provider. The first numbers returned seem to be ~10% slower. 

I need to conduct more tests. But before I do so, I would like to know:

* Which operations did you test test in your performance test, and what impact did the changes have?
* What database setup have you been using (possibly my locally deployed database is too fast / too low latency to show the benefits of batching)?
* Which of the Hibernate options is the one that brings you the biggest benefit, so we could start with those options and test them if they work without regressions in other areas?

Thanks!

**Comment by sebastianh6r** [comment]
We've been testing creation of realms on a local Microsoft SQL Server database which showed a speedup of about 2x. That should mainly be affected by hibernate.jdbc.batch_size, hibernate.order_inserts and hibernate.order_updates.
hibernate.jdbc.fetch_size probably only affects setups with an Oracle database.
hibernate.query.in_clause_parameter_padding and hibernate.default_batch_fetch_size should speed up (nested) bulk queries.

**Review by ahus1 — APPROVED** [review]
Thank you for this PR. I've tested it a bit more, and I think with regular database which is not running ephemeral next to the Keycloak pods, the fewer round-trips to the database will outweigh the additional handling in Hibernate.

**Pull request merged**
