### PR TITLE
KEYCLOAK-17612- Invalid SAML Response : Invalid Destination

### PR DESCRIPTION
**Pull request by ayatb**
Please heve a look to this report https://issues.redhat.com/browse/KEYCLOAK-17612

### CODE REVIEW

**Review by mhajas — CHANGES_REQUESTED** [review]
Thank you for the PR @ayatb! The change looks correct to me. We are doing similar thing in SAMLService.

I have a few comments though:
1. Should we do the same on line SAMLEndpoint#286?
2. There are some test failures in Github Actions, could you have a look? (KcSamlIdPInitiatedSsoTest.testProviderIdpInitiatedLogin, LDAPSamlIdPInitiatedVaryingLetterCaseTest)
3. Before merging we need a test case testing this scenario. Do you think it would be possible to reproduce the failure using SamlClient in the testsuite?

Some hints to SamlClient in the testsuite:
1. It is a tool that can send and receive SAML messages
2. You can intercept any message in any step and adjust it to test something (for example change destination sent by broker provider a test how consumer reacts.)

It I understand the issue correctly, it should be possible to reproduce it using common login flow like for example [here](https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlBrokerTest.java#L257-L259). Then you can change the destination in the LoginResponse sent by broker provider using something like [this](https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlBrokerTest.java#L299).

**Comment by ayatb** [comment]
@mhajas 
the tests are fixed with my last commit, but they are other broken not related to my commit. i see that other PR are broken for the same reason. - I can't reproduce the defect using the saml client because our corporate instalation expose keycloak behind Openshift route which is exposed too to internet throught an nginx.
when the externel identity provider sent a samlResponse to keycloak(kyecloak is client in this cas) the expectedDestination is note well calculated and is not equal to the one in the SamlResponse.
https://issues.redhat.com/browse/KEYCLOAK-17612

**Comment by mhajas** [comment]
Thank you for the fix @ayatb! Could you please squash the commits into one?

I would say it should be possible to write a test, but maybe I don't fully understand the issue. Let me try to summarize the scenario that leads to the failure.

1. You have Keycloak server, SAML identity provider (IDP) and a proxy server between them.
2. This means that when the IDP issues a SAML message it issues it with destination set to proxy url instead of Keycloak's URL
3. The way you fixed it is that Keycloak is expecting the proxy url instead of real keycloak url is it correct?

Now if it is correct what you can do to reproduce is having following test case.
1. Keycloak consuming from some identity provider with frontend url set to something different than real keycloak url (in the broker package of our testsuite it is prepared so that Keycloak acts as both consumer and provider)
2. You can login to Keycloak using the IDP.
3. Now you can intercept message from the IDP and change message so that destination is not the one provided by the IDP, but the one that you set in frontend url setting
4. Then you can check that keycloak successfully validates the message after your fix.

Does it make sense or I misunderstood the scenario?

**Comment by ayatb** [comment]
@mhajas 
hello and thanks for your replay.
it's the url destination calculated by keycloak (consumer) which is wrong not the one provided by the external IDP.
i can't see how can i change it.
Identity Brokering

**Comment by mhajas** [comment]
The problem you solved is, that Keycloak expects destination to be equal to its url, for example `keycloak-server-url.com`. However, your IDP is configured to send SAML messages to proxy server. Hence it sets destination to `proxy-server-url.com`. Now, without your fix, this scenario always fails because keycloak rejects messages with destination set to `proxy-server-url.com`. You fixed it so that Keycloak uses `session.getContext().getUri().getBaseUri()` for validation of destination. After this change and configuring frontendUrl to `proxy-server-url.com`, Keycloak expects destination to start with `proxy-server-url.com` instead of `keycloak-server-url.com`.

This is correct, but we need a test scenario that will validate that this works correctly. 

Two test cases came to my mind:
1. Test that after setting frontendUrl to `proxy-server-url.com`, keycloak rejects messages with destination: `keycloak-server-url.com`.
2. Test that after setting frontendUrl to `proxy-server-url.com`, keycloak accepts messages with destination `proxy-server-url.com`.

I just found out that we have something similar for OIDC: https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerFrontendUrlTest.java#L25. The same thing can be reused also for SAML.

**Comment by mhajas** [comment]
Hello @ayatb, I have found some spare time and prepared some tests for this. Could you please have a look and possibly cherry-pick following commit? https://github.com/mhajas/keycloak/commit/5f573ef3afe3d92d5280aa26f1c4f21e3b79d318. Also, can you squash all commits into one?

**Comment by ayatb** [comment]
hello @mhajas 
i will do it to day
Thanks 👍

**Comment by ayatb** [comment]
hello @mhajas the commit is donne but we have always a some broken tests.
this tests are ok in my local env dev!!!

**Review by mhajas — CHANGES_REQUESTED** [review]
@ayatb The failures seem unrelated, I tested locally with quarkus and the test is passing. The changes look good to me. One last thing please squash the commits into one.

**Comment by mhajas** [comment]
@ayatb Hello, the PR contains commits that are not supposed to be here. Could you fix please? If you need a help I can try to send a PR on your behalf with correct commit.

**Comment by ayatb** [comment]
hello @mhajas, I have created a new PR (https://github.com/keycloak/keycloak/pull/7963) that group all the commit in one (https://github.com/keycloak/keycloak/pull/7963/commits/430af0cdd0868c2fc62b07dca038386e294f6b7d)

please ignore this one.

**Pull request closed without merging**
