### PR TITLE
KEYCLOAK-14584: Client w/ empty str as Base URL displayed in NAC

### PR DESCRIPTION
**Pull request by ssilvert**

### CODE REVIEW

**Comment by ssilvert** [comment]
Kicked off UI build number 931

**Review by douglaspalmer — DISMISSED** [review]
LGTM

**Comment by ssilvert** [comment]
There are some ApplicationsTest failures in master.  Doug is fixing those in PR #7206.  We need to re-run the UI tests after that is merged.

**Review by vmuzikar — DISMISSED** [review]
Looks good but will need to be rebased to run the tests.

**Comment by ssilvert** [comment]
Kicked off UI tests.  Build number 941.

**Comment by ssilvert** [comment]
Kicked off UI tests. Build number 944.

**Comment by ssilvert** [comment]
> Kicked off UI tests. Build number 944.

These tests passed except for the 4 known unrelated failures.

**Review by vmuzikar — APPROVED** [review]

**Review by abstractj — APPROVED** [review]

**Pull request merged**
