### PR TITLE
Document Hibernate 6 changes around JTA

### LINKED ISSUE #19639: Hibernate 6: Document use of JTA for Quarkus legacy store
### Description

When implementing the Hibernate 6 upgrade on Quarkus 3, the legacy store switched to JTA instead of resource local transactions. Due to this, the transaction manager is used on all transactions. 

There is a change of behavior for users as the default configuration of the transaction manager will use `quarkus.transaction-manager.default-transaction-timeout` which will time out after 60 seconds. 

If users run longer transactions, they would need to change this value. 

This should be noted in the migration notes. 

This is blocked until Quarkus 3 appears in main, as the documentation is currently prepared in the main branch to be ready for KC22 and we want to avoid conflicts.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #19639

### CODE REVIEW

**Comment by ahus1** [comment]
I'd first like to receive a review from the storage team. I'll then let a technical writer have a look.

**Review by vramik — COMMENTED** [review]
Changes LGTM, thanks @ahus1! I'd like to ask also @sguilhen to take a look.

**Review by sguilhen — APPROVED** [review]

**Review by vramik — APPROVED** [review]

**Comment by ahus1** [comment]
@andymunro - please have a look at this PR with the perspective of a technical writer. Thanks!

**Comment by ahus1** [comment]
On hold until #20119 is properly investigated.

**Comment by ahus1** [comment]
Further investigations on #20119 showed that JTA was always enabled by default in previous releases, and possibly disabling it with the hidden parameter doesn't work in all cases. With MSSQL, there are tests that disable XA, so this is also still working as expected. So there is not really a change here, and this PR is obsolete. Some of the changes done for Q3 are rolled back in the PR above to restore some of the old behavior, still this is not essential to be included in any migration documentation.

**Pull request closed without merging**
