### PR TITLE
KEYCLOAK-10863 Fix some install error

### PR DESCRIPTION
**Pull request by 16yuki0702**
On : Mac os 10.14.5
When I run following command got error.
```
mvn -Pdistribution -pl distribution/server-dist -am -Dmaven.test.skip clean install
```
it is for that.

### CODE REVIEW

**Comment by stianst** [comment]
What Maven version and JVM are you using? Somehow it seems you're the only one observing this issue and the PR that you have sent does not look correct/needed.

**Comment by 16yuki0702** [comment]
I'm sorry. I'm using belows.

maven
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-05T04:00:29+09:00)

jvm
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)

if it is no need, I'll close this PR and issue immediately.

**Review by abstractj — COMMENTED** [review]
@16yuki0702 I don't have a Mac OS, but I just tried to reproduce the issue witih JDK 8 and everything is working as expected.

@mposolda can you give it a try and see if you can reproduce this issue in your environment? For me, the issue reported will only happen if I switch to JDK 11, but we do not officially support it at the moment, as far as I know.

**Comment by 16yuki0702** [comment]
I’m so sorry, I’ve noticed only mvn is running on jdk12 runtime.
I’m using jenv and not set JAVA_HOME so I didn’t realize this mistake.
Again I’m so sorry, this PR and issue are totally no need so I”ll close these.

**Comment by abstractj** [comment]
@16yuki0702 absolutely no worries! Have a nice day.

**Pull request closed without merging**
