### PR TITLE
[KEYCLOAK-3628] - Using JBPM/BRMS BOM to resolve dependencies versions

### PR DESCRIPTION
**Pull request by pedroigor**
@stianst,

The reason for having `jboss-integration-platform-bom` declared in `keycloak-dependencies-server-all` is that the first defines a lot of versions and dependencies that may conflict with some Keycloak dependencies. That is why I`ve not defined it within root pom.xml.

### CODE REVIEW

**Comment by stianst** [comment]
Could we not still end up with pulling in dependency versions from the bom? As there's a lot of places we depend on server-all, which could end up using versions from jboss-integration-platform-bom instead of keycloak-parent now?

**Comment by pedroigor** [comment]
My assumption is that only the dependencies defined in server-all would be imported by those using it and not everything defined from ip-bom.

**Comment by stianst** [comment]
I was worried that we'd end up pulling in versions from the jboss-integration-platform-bom rather than Keycloak parent, but just checked with httpcore and it's still 4.4.1 from keycloak parent. So looks fine to add.

**Comment by stianst** [comment]
I did one minor change which was to move the version property to Keycloak parent so we have one single place to manage versions (https://github.com/keycloak/keycloak/commit/4ce5f9e08782218477c955cbb3dfa4d1fe3a66ec)

**Pull request merged**
