### PR TITLE
Backport non-blocking liveness probes

### LINKED ISSUE #22109: Add non-blocking liveness and readiness checks to Keycloak
### Description

When testing failover between Keycloak pods under load in Keycloak Benchmark, we saw that requests in Keycloak queue up for 5-10 seconds while Infinispan suspects a leaving node, and rebalances. 

The requests are eventually served successfully, but the delayed processing also affects liveness and readiness probes, which would time out. 

This is due to the probes in Quarkus 3.2.2 being blocking I've raised an issue in Quarkus upstream to make them non-blocking, see https://github.com/quarkusio/quarkus/pull/35100
Once they are non-blocking, the will not be enqueue in the blocking thread pool.
The liveness probe will then be always non-blocking as it doesn't contain any checks (as intended). The readiness probe should only block when it needs to connect to the database.

I'll prepare a PR to update the readiness probe, and also add a workaround until the upstream change is available in a release consumable by Keycloak.

This would allow Keycloak to have a liveness probe with a timeout of 1 second again, and avoids a pod restart if the request queue is filled.

### Discussion

_No response_

### Motivation

A full blocking request queue of Keycloak shouldn't lead to a restart of the Keycloak pod.

### Details

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #22109

This is a partial backport of #22112

Co-authored-by: Martin Bartoš <mabartos@redhat.com>
(cherry picked from commit 6a78e36d259e87bc5d95269252034ef4cf674473)

### CODE REVIEW

**Comment by ahus1** [comment]
@vmuzikar - this is the backport of this change. There haven't been any conflicts when cherry-picking this. Please review, approve and merge. Thanks!

**Review by mabartos — APPROVED** [review]

**Comment by vmuzikar** [comment]
@ahus1 Changes LGTM but I wonder if we tested this more extensively (that it behaves like it should) since 22 does not use RestEasy Reactive.

**Comment by ahus1** [comment]
@vmuzikar - I did additional testing, and found a regression introduced by the latest changes with `QuarkusAsyncHealthCheckFactory#callSync` which use the Vert.x thread pool in a "ordered" way and trigger a mis-behavior (bug?) in Vert.x where the thread pool rejected a request (which we do in our naive load shedding when we restrict the executor until we have a better one).

So I reduced the back port to only make the liveness probe non-blocking. The readiness probe will be as is, which makes this change even smaller. 

As a follow-up, I'll create a PR for Keycloak main, Quarkus, and Vert.x for the various issues :-(

Still good that we find all those things so we can eventually fix them on our journey to a better version of Keycloak.

I then did the usual testing test:

```
export DEBUG=true
export KEYCLOAK_ADMIN=admin
export KEYCLOAK_ADMIN_PASSWORD=admin
export QUARKUS_THREAD_POOL_MAX_THREADS=2
export QUARKUS_THREAD_POOL_QUEUE_SIZE=2
bin/kc.sh --verbose start --http-enabled true --hostname-strict false --health-enabled true --metrics-enabled true
```

* Setting a breakpoint at `QuarkusWelcomeResource#getWelcomePage()`
* Open the start page an exhaust the thread pool and the queue, and eventually see the welcome page fail
* Access the readiness probe -> fails as thread pool is exhausted (as expected)
* Access the liveness probe -> succeeds as the liveness probe is non-blocking

I'd hope we're now good to go. Please review.

**Review by vmuzikar — COMMENTED** [review]
Thanks for looking into this @ahus1.

To be completely honest, I'm becoming less and less comfortable with beckporting this given we have a prod release just around the corner. I see realistic risk of regressions. This is almost impossible to test properly and I'm not sure we (manually) covered everything.

But I won't veto this. If @pedroigor and @mabartos (reviewers of the original PR) approve, let's do this. :)

CC @stianst

**Review by mabartos — APPROVED** [review]
@ahus1 @vmuzikar From my perspective, I vote YES to backport it into the 22 in this form. 

It'll improve stability and performance concerning the thread pool utilization with a relatively low risk that something breaks. The logic behind the asynchronous handling is separated from handling these requests in a synchronous way, as it creates an alternative managed by the provided flag. 

When some issue occurs in production deployment, it's easy to fix it by specifying the flag. However, it's not possible to do it in the opposite case. 

I'd rather propose to customers using the flag than let them face pod restarts with no easy way to fix it :)) But it'd be good to wait for inputs of others.

@ahus1 It'd be reasonable to unify these approaches for `22.x` and `main` until the problem is fixed, right?

**Comment by ahus1** [comment]
@mabartos - while I like to keep this one as-is for KC22 (and as minimal as possible), there is a PR for main in #23920 to add workarounds for the Vert.x and Quarkus problems while we wait for the next releases. 

Let's discuss the details of that other PR once we have agreed on this one.

**Review by pedroigor — APPROVED** [review]

**Comment by ahus1** [comment]
Thank you for everyone involved in this. I'll keep an eye on this; please reach out to me if you see something suspecious.

**Pull request merged**
