### PR TITLE
Fix https://issues.jboss.org/browse/KEYCLOAK-3492

### PR DESCRIPTION
**Pull request by sebastienblanc**
@ebondu this is a rebased and a cleaned up PR of https://github.com/keycloak/keycloak/pull/3741 , can you review this and confirm quickly it's ok, this way we can continue with https://github.com/keycloak/keycloak/pull/3740

### CODE REVIEW

**Comment by sebastienblanc** [comment]
@ebondu ping !

**Comment by ebondu** [comment]
Sorry about the delay but I am currently in hollidays ^^. It is all good to me for the PR.

**Comment by scranen** [comment]
I'm a bit late to the party, but for me this construct breaks the redirect set by the `loginRedirect()` challenge in `OAuthRequestAuthenticator`:
```java
if (challenge != null) {
    challenge.challenge(facade);
}
throw new KeycloakAuthenticationException("Authorization header not found, see WWW-Authenticate header");
```
The 302 sent by the challenge is overwritten by a 401 in Spring Boot's `ErrorPageFilter` (we're running a Spring Boot webapp in an external Tomcat server). Would it be okay here to return `null` when the challenge is sent?
```java
if (challenge != null) {
    if (challenge.challenge(facade)) {
        return nulll;
    }
}
throw ...
```

**Comment by sebastienblanc** [comment]
@scranen I'm seeing the same , I pinged @ebondu on an another PR about this ;)

**Comment by sebastienblanc** [comment]
Copy/paste from @scranen from other PR
> The redirect is an OAuth redirect; the construction of this URL is something that should probably remain encapsulated in OAuthRequestAuthenticator. I think what's unclear here is the expected behaviour of the challenge. IMO, if the challenge returns true, meaning that the response was changed in a way that the challenge deemed appropriate, then the request is dealt with and we should not throw an AuthenticationException (this is not an exception flow). If I don't want the redirect to be sent, then I should be using an Authenticator that is configured not to send redirects.

Yes if you don't want a redirect you just specify it in your keycloak config with `bearer-only` , the developer should not worry about that. 

**This really needs to be fixed before the 3.2.0 Release otherwise we have no other choice to revert these commits.**

**Comment by ebondu** [comment]
By looking the code before this change, is not clear to me is how the 302/401 was decided by using the `bearer-only` property. If we consider any auth failure have to be managed by the spring failure handler, the decision to set 302/401 should be done in `KeycloakAuthenticationFailureHandler` ?

**Comment by ebondu** [comment]
Another option is to check the `bearer-only` in the filter and to throw the exception only if it is set to true ?

**Comment by sebastienblanc** [comment]
@ebondu this is handled by the `RequestAuthenticator` of the Core Adapter https://github.com/keycloak/keycloak/blob/master/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/RequestAuthenticator.java but for some reasons it's ignored or overidden.

**Comment by scranen** [comment]
Not sure where else to mention this: I tried replacing `challenge.challenge(facade)` by `if (challenge.challenge(facade)) { return null; }`, but that results in an infinite redirect. I'm entirely unsure it has anything to do with these changes, but in 3.1.0.Final this does not happen. It seems that after successful authentication, `SimpleUrlAuthenticationSuccessHandler` then redirects to the default relative URL `/`, which then authenticates succesfully and redirects to `/` etc. @sebastienblanc can you reproduce this behaviour?

**Comment by sebastienblanc** [comment]
@scranen @ebondu So it's not the adapter-core that decide on the redirect or not for the spring sec but this method https://github.com/keycloak/keycloak/blob/master/adapters/oidc/spring-security/src/main/java/org/keycloak/adapters/springsecurity/authentication/KeycloakAuthenticationEntryPoint.java#L89 and I can see it's never called since this PR has been merged. @ebondu Does that help you ?

**Comment by ebondu** [comment]
@scranen, I also tested the adapter modified as you describe with the app example from https://github.com/trecloux/spring-keycloak-classcastexception and the app loop on redirect to / after the login (so the filter let the request continue with success). So I think for this example, the problem of the infinite redirect is more an app issue.

**Comment by ebondu** [comment]
@sebastienblanc to me, the spring `AuthenticationEntryPoint` is another optionnal Spring component that can be used to configure the HTTP endpoint to initialize the login process if the user is not logged. So it is probably the proper/another way to enable redirection for web apps. The AuthEntryPoint does not handle the authentication itself (auth is done by the keycloak filter). It is normal the entry point is never called directly from the filter because they are separate components configured by the developper.

**Comment by ebondu** [comment]
To me the `bearer-only` was never used in previous versions of the filter but it should. Here is a possible modification in the filter to take it in account:

```
if (AuthOutcome.FAILED.equals(result)) {
       AuthChallenge challenge = authenticator.getChallenge();
       if (challenge != null) {
           challenge.challenge(facade);
       }
       if (deployment.isBearerOnly()) {
           // no redirection in this mode, throwing exception for the spring handler
           throw new KeycloakAuthenticationException("Invalid authorization header, see WWW-Authenticate header for details");
       } else {
            // let continue, if challenged it may redirect
            return null;
       }
}
```

**Comment by ebondu** [comment]
I tried this code with the example app and I can observe the expected behaviour (no redirect only if `bearer-only` at `true`). I still have the infinite redirect loop but I think it is due to the example itsef.

**Comment by sebastienblanc** [comment]
Well with 3.1.0 the redirect works in the example app.

**Comment by ebondu** [comment]
This PR just allows the response customization in the case of an auth failure by delegating the error to a spring handler. If we need to modify the PR to enable redirection in the filter in other modes (not  bearer-only mode), the proposed code fragment that check the `bearer-only` should fit. But we also have to keep [KEYCLOAK-3473](https://issues.jboss.org/browse/KEYCLOAK-3473) in mind (this PR depends on it) because if we don't, the proposed default handler will no be able to customize the response (due to the call to `sendError()` in the `BearerTokenRequestAuthenticator`). You can have a look at @patriot1burke 's comment  [KEYCLOAK-1368](https://issues.jboss.org/browse/KEYCLOAK-1368?focusedCommentId=13132381&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13132381) because to me it is also related to.

**Comment by sebastienblanc** [comment]
TBH I'm a bit lost here, @scranen and me are experiencing a regression here and not sure how to solve this. Would be nice to have @foo4u feedback as well as he is the original author of this adapter.

**Comment by ebondu** [comment]
Do you want me to share the code, you will be able to verify there is no regression ?

**Comment by sebastienblanc** [comment]
Sure ! That would be nice.

**Comment by ebondu** [comment]
Here is the modified class [KeycloakAuthenticationProcessingFilter.java](https://github.com/ebondu/keycloak/blob/bug-KEYCLOAK-3492/adapters/oidc/spring-security/src/main/java/org/keycloak/adapters/springsecurity/filter/KeycloakAuthenticationProcessingFilter.java)

**Comment by sebastienblanc** [comment]
So We are making progress, I have the redirect but then the too many redirect issue and this with my 2 differents samples so I don't think it's because of the samples. Any idea why we have this infinite redirect ?

**Comment by ebondu** [comment]
Based on logs, the redirection to `/` seems to be initialized from the Spring `AuthenticationSuccessHandler` after the keycloak auth filter.

**Comment by sebastienblanc** [comment]
Indeed the method is called in a loop creating the too many redirect, any idea why this happen ?

**Comment by ebondu** [comment]
If the app redirect to / after auth success (due to the app conf), then the app will try to auth again and will then redirect to / and so one...

**Comment by sebastienblanc** [comment]
Ok, that's because you changed the default redirect url `/sso/login` to `/**` , if I use `/sso/login` it's working again. Can you elaborate on this change ?

**Comment by ebondu** [comment]
Based on the previous version of the filter, the strategy was to attempt authentification only if the request was matching /sso/login OR if the authorization header was present. After the auth process, requests are authenticated from the cookie session id and the context stored on the server side. It could be relevant for web apps supporting sessions but is not convenient in the case of a stateless REST API (in that case a /** matcher is probably more relevant => bearer token must to be passed for each requests). BTW, as the request matcher is configurable in the Spring config, we can set back the default matcher to it previous value (/sso/login or auth header) ?

**Comment by sebastienblanc** [comment]
Yes if you can prepare a new PR that contains : 
* the first fix for the redirect 
* the previous value for the matcher (/sso/login)  (We see if the auth header is still needed later) 

That would be awesome, sounds like a plan ?

**Comment by ebondu** [comment]
I just committed these changes here [KeycloakAuthenticationProcessingFilter.java](https://github.com/ebondu/keycloak/blob/bug-KEYCLOAK-3492/adapters/oidc/spring-security/src/main/java/org/keycloak/adapters/springsecurity/filter/KeycloakAuthenticationProcessingFilter.java). Can you check on your side before ?

**Comment by sebastienblanc** [comment]
@ebondu looking now but the unit tests are not passing

**Comment by ebondu** [comment]
If tests are OK, don't you think we should also review [KEYCLOAK-3473](https://issues.jboss.org/browse/KEYCLOAK-3473) at the same time ?

**Comment by sebastienblanc** [comment]
Let's do one by one, I need a rebased and not a merged version of https://github.com/ebondu/keycloak/blob/bug-KEYCLOAK-3492/

**Comment by sebastienblanc** [comment]
But let me do it and you will review

**Comment by ebondu** [comment]
ok. I also rebased the branch...

**Comment by sebastienblanc** [comment]
@ebondu plese look at https://github.com/keycloak/keycloak/pull/4227

**Pull request merged**
