### PR TITLE
[KEYCLOAK-8522] - Migrate broker tests from old to new testsuite

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by abstractj** [comment]
@keycloak-ci-bot test

**Comment by pedroigor** [comment]
@mposolda travis is complaining about the size of the logs due to the amount of debug messages. Some of those messages are basically printing the page source. What do you think about removing this ?

**Comment by mposolda** [comment]
@pedroigor +1, It may be also possible to add another "group" of tests to the travis-run-tests.sh and add the broker tests there. But hopefully removing debug about page sizes can help a lot.

**Comment by pedroigor** [comment]
@mposolda do you prefer a specific group for broker tests ?

**Comment by mposolda** [comment]
@pedroigor If there is lots of them and it takes certain amount of time, maybe yes?

**Comment by pedroigor** [comment]
@mposolda I created a new group of tests for broker tests. I've also fixed issues when running the tests using `app-auth-server-wildfly`, so far I was running using undertow and everything was fine.

Let's see if travis is happy now.

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Review by mposolda — APPROVED** [review]
@pedroigor Thanks Pedro!

**Comment by abstractj** [comment]
@keycloak-ci-bot test

**Comment by abstractj** [comment]
@keycloak-ci-bot test

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Comment by abstractj** [comment]
@keycloak-ci-bot test

**Comment by pedroigor** [comment]
@keycloak-ci-bot test

**Pull request merged**
