### PR TITLE
Improve user search performance

### LINKED ISSUE #8893: Exact match user query by email is doing a full table scan
### Describe the bug

One of our internal projects needs a fast user lookup by email. Reading the API docs the GET user query with email query parameter and exact match query parameter seemed appropriate for this use case.

When tested against a user database of >2M rows the request took 13 seconds. The query was logged in the slow query log and an explain showed that it was filtering all rows. Removing the _lower_ function call from around the email in the where clause allowed it match on the index and return quickly.

We're using mysql 5.7.

### Version

11.0.2

### Expected behavior

Exact match email query should be fast.

### Actual behavior

Exact match email query took 13s to return when run against a user db of 2M rows.

### How to Reproduce?

Query a sizable user database using the Keycloak /users endpoint with the parameters ?email=<email>&exact=true.

### Anything else?

I tracked the source of this issue to the following line of code. It seems to me that the builder.lower around the email key is unnecessary since email is already forced to lower case on save. The builder.lower causes JPA to emit a lower function call in mysql syntax and the function is applied on every row prior to comparison.

https://github.com/keycloak/keycloak/blob/1e1a6779befb9c836069761fb70d86cadd47b4cb/model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java#L812

### PR DESCRIPTION
**Pull request by mparlee**
Removes bulder.lower() from user search queries on email and username.

Closes #8893

### CODE REVIEW

**Comment by mparlee** [comment]
@ahus1

**Comment by ahus1** [comment]
@hmlnarik - for this first-time contributor, the GitHub actions don't run automatically. Please trigger the GitHub action run for this PR. Thanks!

**Comment by ahus1** [comment]
LGTM from code review, did a local test with the UI for exact and wildcard search. Also tested the API as the UI doesn't trigger all code paths. Will defer the approval once I see the CI pass.

**Comment by ahus1** [comment]
closed and re-opened to re-trigger the builds that were cancelled.

**Review by ahus1 — APPROVED** [review]
Relevant builds are now green, also tested it manually before (see previous comment).

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
