### PR TITLE
KEYCLOAK-2045 Simple Validation SPI for UserProfile SPI

### PR DESCRIPTION
**Pull request by velias**
KEYCLOAK-2045 Simple Validation SPI - this PR is follow up of the original PR #7887 by @thomasdarimont. It is refined to work for UserProfile SPI. Main changes against the original PR:
* default "format" validators like email, length, pattern etc improved to work on List of Strings (as UserProfile attributes are List of Strings). Added reusable abstract base classes to make implementation for this kind of validators easier.
* improved handling of null values in default validators (treated as valid values now) to allow format validations for optional attributes in UserProfile.
* improved validation of configuration for some default validators
* added validator for integer and double numbers which also allows to validate configured min and max values
* changed package for default validators (agreed with @pedroigor )
* added error messages for errors produced by default validators into `/base/login` theme resources
* removed unnecessary changes to keycloak basic classes (like `KeycloakSession`)

### CODE REVIEW

**Comment by pedroigor** [comment]
@velias Could you please check https://github.com/pedroigor/keycloak/tree/KEYCLOAK-17399-validation?

**Comment by velias** [comment]
@pedroigor thanks, added few comments to your additional commit. My biggest concern is around format validations over empty strings and how it will work for optional fields in UserProfile (I think registration/update forms produce empty string for them now if not changed in meantime). Do we have final UserProfile functionality merged with this latest version of validators somewhere to test it?

**Comment by velias** [comment]
@pedroigor incorporated your changes with some additional changes from me mainly to patch number range validation
I kept your change when empty strings are treated as invalid by String format validators (Email, Pattern, length). We have to make sure UserProfile SPI parts where registration and profile update form data are processed work correctly for optional attributes.

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@thomasdarimont @velias Thanks.

**Pull request merged**
