### PR TITLE
Added support for the Croatian language

### LINKED ISSUE #34351: Support for the Croatian language
### Description

After couple of projects in which I had to make parts of the Keycloak theme available in Croatian language, I've decided to open an issue about adding full support for the Croatian language.

I'm looking for native Croatian speakers who can verify translations mentioned in the pull request. Any help is greatly appreciated 🙂

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by Petar-CV**
Closes #34351

Added support for the Croatian language.

I hope we have some volunteers from Croatia to verify these translations :)

### CODE REVIEW

**Comment by ahus1** [comment]
@Petar-CV - thank you for this contribution. To be able to merge this, please apply the following: 

* Create  a GitHub issue of type "enhancement", as you are about to add a new language
* Update the commit message with the issue, and also add the sign-off as described in `CONTRIBUTING.md` to the commit message
* Contact a Croatian native speaker and ask them to review your translations, and comment in this PR if everything is fine.

**Comment by ssilvert** [comment]
> @Petar-CV - thank you for this contribution. To be able to merge this, please apply the following:
> 
> * Create  a GitHub issue of type "enhancement", as you are about to add a new language
> * Update the commit message with the issue, and also add the sign-off as described in `CONTRIBUTING.md` to the commit message
> * Contact a Croatian native speaker and ask them to review your translations, and comment in this PR if everything is fine.

@Petar-CV @ahus1 Has all this been done?  Is this one ready to go upon review and CI passing?

**Comment by Petar-CV** [comment]
@ssilvert - I managed to get one native speaker to review the translations. I'll update the branch a bit later today so the pull request can be merged.

**Comment by Petar-CV** [comment]
@ahus1 - I've rebased my branch with the main branch and re-checked the keys of translations once again. Also, there was one native Croatian speaker that checked the translations.

**Comment by ahus1** [comment]
> Also, there was one native Croatian speaker that checked the translations.

We would usually want to see a native speaker commenting in this PR that they checked the translations. Please let me know if this is possible.

**Comment by Petar-CV** [comment]
> > Also, there was one native Croatian speaker that checked the translations.
> 
> We would usually want to see a native speaker commenting in this PR that they checked the translations. Please let me know if this is possible.

Sure. He commented on the issue, not the pull request. I'll tag him here @ilijaleko

**Review by ahus1 — APPROVED** [review]
Thank for this translation and the review!

**Pull request merged**
