### PR TITLE
KEYCLOAK-10728 Upgrade to WildFly 18 Final

### PR DESCRIPTION
**Pull request by martin-kanis**

### CODE REVIEW

**Review by vramik — DISMISSED** [review]
@martin-kanis thank you, lgtm

**Comment by martin-kanis** [comment]
http://keycloak-jenkins.com/job/universal-test-pipeline-adapters/755/
http://keycloak-jenkins.com/job/universal-test-pipeline-server/915/ compared to http://keycloak-jenkins.com/job/universal-test-pipeline-server/912/

**Comment by martin-kanis** [comment]
Updated <wildfly.deprecated.wildfly.core.version> to 9.0.2.Final in testsuite/integration-arquillian/pom.xml

**Review by mhajas — APPROVED** [review]

**Review by hmlnarik — APPROVED** [review]

**Comment by hmlnarik** [comment]
Thanks @martin-kanis, @vramik  and @mhajas!
Internal CI reports no extra failures when compared to previous version. Cross-DC tests work locally. Ignoring cross-dc server failure on travis.
This PR will be merged once related docs PR is approved.

**Pull request merged**
