### PR TITLE
KEYCLOAK-4997 KEYCLOAK-4866 KEYCLOAK-4895 Upgrade js libraries

### PR DESCRIPTION
**Pull request by ssilvert**
This may or may not be ready for merge.  First, I want to see how it does with Travis.

This uses yarn/npm to manage all the upgraded js packages.  But it doesn't yet integrate automatic download during maven build.  You execute yarn manually.  We really can't do this automatically until we have a stable internal npm repo that we can point to.

So, this adds a lot of stuff to the build and distribution.

### CODE REVIEW

**Comment by stianst** [comment]
Doesn't this add a large amount of files to the repo as well as the server dist that aren't actually used?

**Comment by ssilvert** [comment]
As it stands now, yes.  We need to talk over a strategy for dealing with it.  I mainly wanted to make sure it would pass Travis and then talk about it with you in detail.

**Comment by stianst** [comment]
Ideally I'd like only the resources we need and perhaps also drop the node_modules folder (mainly to keep it consistent with how it was before).

What about having a special Maven profile that is used to "download and filter" the stuff?

**Comment by ssilvert** [comment]
Let's go through our options tomorrow.  What we are able to do depends on how much time we have.

Can you let me know a drop dead date for when this must be merged?

**Comment by stianst** [comment]
Ideally we should have this in for 3.2, but not sure how viable that is. Let's discuss today.

**Comment by stianst** [comment]
Merged here https://github.com/keycloak/keycloak/pull/4275

**Pull request closed without merging**
