### PR TITLE
KEYCLOAK-18031 Update to 13.0.0 fails due to liquibase error

### PR DESCRIPTION
**Pull request by vramik**

### CODE REVIEW

**Comment by vramik** [comment]
https://master-jenkins/job/universal-test-pipeline-server/408/

**Comment by stianst** [comment]
As 13.0.0 is already released, we can't merge changes to the 13.0.0 changeset as that is already installed by some users.

**Review by stianst — CHANGES_REQUESTED** [review]
See previous comment

**Comment by vramik** [comment]
> As 13.0.0 is already released, we can't merge changes to the 13.0.0 changeset as that is already installed by some users.

There is a check the new changeset will be allied only in case the original ona was not applied. Please see https://github.com/keycloak/keycloak/pull/8031/files#diff-3374e8fe71e9cf4c16ff00d889e8305734333b2c059d8673aaa1060750d0ac79R84

**Review by hmlnarik — APPROVED** [review]

**Review by stianst — APPROVED** [review]

**Pull request merged**
