### PR TITLE
KEYCLOAK-1280: Create seperate logging module.  Refactor.

### PR DESCRIPTION
**Pull request by ssilvert**
You probably want to take a look at the loggers created in logging/src/main/java/org/keycloak/logging/KeycloakLogger.java.

Each localized log message is assigned to a logger that logs to a specific category.  Sometimes it is difficult to determine where a log message belongs.   Of course, the original developer is the best one to make this determination.  I tried to make my best guess without spending excessive time on any particular message.

### CODE REVIEW

**Comment by patriot1burke** [comment]
why do you have a separate module for logging?  We did a lot of work to consolidate modules.

**Comment by ssilvert** [comment]
Because that's the way everyone on the call wanted to do it.  Before that it was on a per-module basis.

**Comment by ssilvert** [comment]
I can fix the conflicts later this afternoon.  This PR has been a conflict magnet!

**Comment by stianst** [comment]
+1 To not introduce a separate module. It should be put in a shared module, like common or server-spi.

**Comment by stianst** [comment]
Or core is probably the best one

**Comment by patriot1burke** [comment]
Logging classes should be kept in the same exact modules that they are invoked in.  I hope that the logging isn't in one giant class....?!?

**Comment by ssilvert** [comment]
Again, my original implementation worked exactly as Bill describes.  The new one is what everyone on the call (except me) wanted.  It lets you classify your log message based on broad categories rather than the module it comes from.

If, for example, we move it to core, then every module that ever needs to use it must depend on core.  Can we make that assumption now and forever in the future?

**Comment by ssilvert** [comment]
BTW, can we settle this soon?  It's not a problem to make whatever changes you want, but this is the kind of PR that constantly attracts conflicts.  It would be nice to finally have it merged.

**Comment by stianst** [comment]
We can't have a new module just to keep a few log classes. If having a a logger per-module is what you and Bill want then I'm happy with that. So just go for that then.

**Comment by ssilvert** [comment]
I think that will work out better in the long run.  So in that case, we don't need this PR.  

There are several messages in the services module that have not been converted.  I'll take care of that.  Then we need a plan to convert the rest of the modules.

**Pull request closed without merging**
