### PR TITLE
KEYCLOAK-15251 keycloak-themes build fails in windows

### PR DESCRIPTION
**Pull request by tnorimat**
This PR is for https://issues.redhat.com/browse/KEYCLOAK-15251 .

### CODE REVIEW

**Comment by testn** [comment]
@hmlnarik  can you take a look?

**Comment by hmlnarik** [comment]
@ssilvert , can you please look at this PR?

@tnorimat could you please fix the commit message to start with `KEYCLOAK-15251`?

**Comment by tnorimat** [comment]
@hmlnarik I've fixed the commit message.

**Review by ssilvert — APPROVED** [review]

**Comment by ssilvert** [comment]
Thanks @tnorimat

**Pull request merged**
