### PR TITLE
Fix hardcoded conditional rendering of client secret input field

### LINKED ISSUE #22660: Implementing custom ClientAuthenticator loses access to Client Secret Input Field in the Admin UI
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

In the client credentials tab, the `ClientSecret` input field in the UI is conditionally rendered with a hardcoded names of ClientAuthenticator implementation. [Link to code line](https://github.com/keycloak/keycloak/blob/660d17f8ec113558e520be97007f6b4a72f0fca6/js/apps/admin-ui/src/clients/credentials/Credentials.tsx#L208C28-L208C28)

```jsx
{(clientAuthenticatorType === "client-secret" ||
            clientAuthenticatorType === "client-secret-jwt") && (
    <CardBody>
        <ClientSecret
            client={client}
            secret={secret}
            toggle={toggleClientSecretConfirm}
         />
    </CardBody>
)}
```

### Version

21.1.1

### Expected behavior

Client Secret conditional rendering should depend on the value of

```java
boolean supportsSecret() {
        return true;
 }
```

which is defined by the interface [ClientAuthenticatorFactory](https://github.com/keycloak/keycloak/blob/660d17f8ec113558e520be97007f6b4a72f0fca6/server-spi-private/src/main/java/org/keycloak/authentication/ClientAuthenticatorFactory.java#L37)

This value can be brought to frontend using the existing REST endpoint that keycloak Admin UI uses to get a list of client authenticators. `/admin/realms/${realm-name}/authentication/client-authenticator-providers`

The current response of this endpoint is as follows

```json
[
    {
        "displayName": "Signed Jwt",
        "description": "Validates client based on signed JWT issued by client and signed with the Client private key",
        "id": "client-jwt"
    },
    {
        "displayName": "Client Id and Secret with license check.",
        "description": "Validates client based on 'client_id' and 'client_secret' sent either in request parameters or in 'Authorization: Basic' header. It also ensures the realm have a valid license.",
        "id": "client-secret-license"
    },
    {
        "displayName": "Client Id and Secret",
        "description": "Validates client based on 'client_id' and 'client_secret' sent either in request parameters or in 'Authorization: Basic' header",
        "id": "client-secret"
    },
    {
        "displayName": "X509 Certificate",
        "description": "Validates client based on a X509 Certificate",
        "id": "client-x509"
    },
    {
        "displayName": "Signed Jwt with Client Secret",
        "description": "Validates client based on signed JWT issued by client and signed with the Client Secret",
        "id": "client-secret-jwt"
    }
]
```

The response of this endpoint can be extended to include the the `supportsSecret` attribute as follows:

```json
[
    {
        "displayName": "Signed Jwt",
        "description": "Validates client based on signed JWT issued by client and signed with the Client private key",
        "id": "client-jwt",
        "supportsSecret": false
    },
    {
        "displayName": "Client Id and Secret with license check.",
        "description": "Validates client based on 'client_id' and 'client_secret' sent either in request parameters or in 'Authorization: Basic' header. It also ensures the realm have a valid license.",
        "id": "client-secret-license",
        "supportsSecret": true
    },
    {
        "displayName": "Client Id and Secret",
        "description": "Validates client based on 'client_id' and 'client_secret' sent either in request parameters or in 'Authorization: Basic' header",
        "id": "client-secret",
        "supportsSecret": true
    },
    {
        "displayName": "X509 Certificate",
        "description": "Validates client based on a X509 Certificate",
        "id": "client-x509",
        "supportsSecret": false
    },
    {
        "displayName": "Signed Jwt with Client Secret",
        "description": "Validates client based on signed JWT issued by client and signed with the Client Secret",
        "id": "client-secret-jwt",
        "supportsSecret": true
    }
]
```

Which can be done in [AuthenticationManagementResource](https://github.com/keycloak/keycloak/blob/660d17f8ec113558e520be97007f6b4a72f0fca6/services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java#L164) as follows:

```java
public Stream<Map<String, Object>> buildProviderMetadata(Stream<ProviderFactory> factories) {
        return factories.map(factory -> {
            Map<String, Object> data = new HashMap<>();
            data.put("id", factory.getId());
            ClientAuthenticatorFactory configured = (ClientAuthenticatorFactory)factory;
            data.put("description", configured.getHelpText());
            data.put("displayName", configured.getDisplayType());
            data.put("supportsSecret", configured.supportsSecret());
            return data;
       });
}
```

In the Admin UI source code, the conditional rendering of the client secret field can then depends of this value

```jsx
{(clientAuthenticatorType.supportsSecret == true) && (
    <CardBody>
        <ClientSecret
            client={client}
            secret={secret}
            toggle={toggleClientSecretConfirm}
         />
    </CardBody>
)}
```

### Actual behavior

client secret input field, will only be rendered when the PROVIDER_ID is`client-secret` or `client-secret-jwt`.

When attempted to implement ClientAuthenticator, The access to the client secret field is lost, because the provider name cannot be  `client-secret` or `client-secret-jwt`, as they are already in use.

### How to Reproduce?

Implement [ClientAuthenticator](https://github.com/keycloak/keycloak/blob/660d17f8ec113558e520be97007f6b4a72f0fca6/server-spi-private/src/main/java/org/keycloak/authentication/ClientAuthenticator.java#L34C11-L34C11) or extend [AbstractClientAuthenticator](https://github.com/keycloak/keycloak/blob/660d17f8ec113558e520be97007f6b4a72f0fca6/services/src/main/java/org/keycloak/authentication/authenticators/client/AbstractClientAuthenticator.java#L29). Then select your new authenticator in the admin ui, in the credentials tab of the client settings. The client secret field will disappear.

Screenshot from 2023-08-23 15-10-53
Screenshot from 2023-08-23 15-48-13

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ImFlog**
As stated in the original MR, I would like to bring the change to the main branch to fix this UI issue and allow to fetch and modify secrets based on the authenticator secret flag.

Replace https://github.com/keycloak/keycloak/pull/22681
Closes https://github.com/keycloak/keycloak/issues/22660

CC @jonkoops

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]
The front-end changes look good to me, as with the older PR. I cannot judge the changes to the Java-side.

**Comment by jonkoops** [comment]
@ImFlog could you squash your commits and add @useresd as [a co-author](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) since he authored the original code?

**Comment by ImFlog** [comment]
@jonkoops It's done ✅

**Comment by jonkoops** [comment]
Thanks! @keycloak/core can I get a review for the rest of this PR?

**Comment by ImFlog** [comment]
@jonkoops any chance to find someone to review the back part ? As it was the same as the previous PR that was validated I hoped It would be a bit faster to approve :(

**Review by mposolda — APPROVED** [review]

**Comment by jonkoops** [comment]
Thanks for landing this @ImFlog!

**Pull request merged**
