### PR TITLE
KEYCLOAK-5289 Add support for Google's hd parameter

### PR DESCRIPTION
**Pull request by brushmate**

### CODE REVIEW

**Comment by stianst** [comment]
Implementation itself looks good, but I'm concerned with how it's tested. We do not currently use any mocking when testing Keycloak and that has been a conscious decision. Before we introduce any mocking libraries into the codebase we would have to have a wider discussion about that. The ideal would be an integration test by extending SocialTest, but that may be difficult as it would require us to have a test user that is part of a hosted domain at Google which is probably not feasible.

**Comment by stianst** [comment]
I started a thread on keycloak-dev around mocking libraries

**Comment by brushmate** [comment]
I have added a new namespace in the social.properties file for the SocialLoginTest. You have to configure it like so to run the integration test:

    google-hosted-domain.clientId=<google client id>
    google-hosted-domain.clientSecret=<google client secret>
    google-hosted-domain.hostedDomain=example.com
    google-hosted-domain.username=account@example.com
    google-hosted-domain.password=<password>
    google-hosted-domain.profile.firstName=Hans
    google-hosted-domain.profile.lastName=Wurst
    google-hosted-domain.profile.email=account@example.com

**Comment by brushmate** [comment]
Docs PR: keycloak/keycloak-documentation#400

**Comment by brushmate** [comment]
Hey guys, any updates on this PR? Can I do something to help you with it?

**Comment by stianst** [comment]
@brushmate next steps is ours here. Thanks for adding the tests. We now need to figure out how we can run this in the internal CI. The challenge will be to get a user account associated with a domain that we can use for testing.

**Comment by stianst** [comment]
@pdrozd @vmuzikar would be great if we can pick this up

**Comment by vmuzikar** [comment]
@brushmate I've reviewed the tests. The newly added tests are in conflict with the regular Google test because now we need more than one Google account in the SocialLoginTest. Just a few minor tweaks to GoogleLoginPage should fix that. It was just a few lines of code so I've done it by myself. You can merge my changes if you want: .

We need to discuss one more aspect of the test. We currently don't test that the `hd` parameter is actually present in the request. The thing is, in case the param is not present, the login is still successful, i.e. the test passes. I believe we should somehow test that the hosted domain policy is actually applied. WDYT?

Also, we still need to figure out the test environment for this, i.e. some test G Suite account.

**Comment by brushmate** [comment]
@vmuzikar Thank you for the patch, I just merged it.

I agree that we should test the hd param as well. Can't we just check if the current URL contains the param when we navigate to the login page?

Regarding the test account: I only found information about [a 14 day trial ](https://support.google.com/a/answer/6388094?hl=en). But that won't help us. I was hoping that you have some good connections to Google :D

**Comment by vmuzikar** [comment]
@brushmate Ok, I agree. Imho checking the URL for the `hd` param would be sufficient.
Could you please add that to the test?

**Comment by brushmate** [comment]
@vmuzikar I added the the assertion for the parameter. Therefore I split up the `performLogin()` method to avoid code duplication.

**Comment by brushmate** [comment]
Hi @stianst & @vmuzikar, sorry to bother you again, but did you find a solution for the CI issue?

**Comment by stianst** [comment]
What happens if you use a regular free Google account with the hd param? Can we for instance set hd=google.com and see that work, then use hd=nosuch.com and see that fails?

If that doesn't work I don't think we'll have any other option, but to merge without the test running in CI. We can create a JIRA to try to address it, but we can merge before that's resolved. @vmuzikar I would assume we'd need to add a condition to the social login test to only run those that are configured or something to prevent it to break CI?

**Comment by vmuzikar** [comment]
@stianst Unfortunately, it doesn't work with regular (gmail) accounts as they're not GSuite accounts (GSuite account != Google account).

+1 for merging it. I'll set this test as skipped in the CI for now and create a JIRA so we could try to resolve it in the future.

**Review by vmuzikar — DISMISSED** [review]
Created https://issues.jboss.org/browse/KEYCLOAK-7897

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
@brushmate thanks for your work, and thanks for your perseverance with regards to testing issues ;)

**Comment by brushmate** [comment]
Great news. Thanks for merging!

**Pull request merged**
