### PR TITLE
load user before opening infopage (#17233)

### LINKED ISSUE #17233: the InfoPage after an ExecuteActionsEmail is not localized based on the user's locale
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

token-exchange

### Describe the bug

In my case an execute-actions-email is sent to a user for them to update their password. After the user clicks on the link in the execute-action-email they will visit an infopage listing the actions to execute followed by the update-password-page. The infopage is translated according to the locale accepted by the browser-request but update-password-page is translated according to the locale set in the user's profile.

If these two locales are not equal the translation changes during the workflow.

### Version

20.0.5

### Expected behavior

The first page should be translated by the user's locale aswell.

### Actual behavior

The first page and the second page are translated differently if the browser-requested locale and the user-profile's locale are not equal. 

### How to Reproduce?

precondition:
- a realm with a working smtp config and two supported languages (for example: german and english)
- a browser without a cookie specifying a locale for keycloak that is set to one of the supported languages (for example: german)

1. create a user with a specific locale (for example: english)
2. trigger an execute-actions-email for the UPDATE_PASSWORD action
3. the email is in english
4. open the link send by mail in the browser
5. the infopage will open in german, the language accepted by the browser
6. the following update-password-page will open in englisch, the use-profile's locale

### Anything else?

I might have already identified the underlying issue: the authenticed user is not loaded into the loginformsprovider in ExecuteActionsActionTokenHandler::handleToken.

I plan to provide a pull-request shortly.

### PR DESCRIPTION
**Pull request by markus-csx**
closes #17233

loads the user from the token into the LoginFormsProvider to enable localization of the infopage based on the locale in the userprofile

### CODE REVIEW

**Comment by mposolda** [comment]
Similar PR: #15284 (I liked this one better due the less amount of changes, but not 100% sure what is the best solution for this right now. Also tests are missing).

**Comment by mposolda** [comment]
@markus-csx Any chance to add automated test? For the ispiration, you can try to take a look at `AbstractI18NTest` and it's subclasses.

**Comment by markus-csx** [comment]
Thank you for the hint. I would like to add the missing tests. I will hopefully get to it in the next week or so.

**Comment by mposolda** [comment]
@markus-csx Any luck with the automated test?

**Comment by markus-csx** [comment]
I found a little time but had no luck.
Unfortunately this merge has a low priority for us right now so I am afraid I wont be able to invest more time to add the tests.

**Pull request closed without merging**
