### PR TITLE
Remove workaround for fix available in Hibernate 6.2.1

### LINKED ISSUE #19323: Hibernate 6: Entity in Key not returned when querying
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

After migrating from Hibernate 5 to Hibernate 6 in #17664, there is the exception:

```
Caused by: org.hibernate.HibernateException: identifier of an instance of org.keycloak.models.jpa.entities.FederatedIdentityEntity was altered from org.keycloak.models.jpa.entities.FederatedIdentityEntity$Key@3970c62a to org.keycloak.models.jpa.entities.FederatedIdentityEntity$Key@cf2e436d
KcOidcBrokerTest ++ 	at org.hibernate.event.internal.DefaultFlushEntityEventListener.checkId(DefaultFlushEntityEventListener.java:93)
KcOidcBrokerTest ++ 	at org.hibernate.event.internal.DefaultFlushEntityEventListener.getValues(DefaultFlushEntityEventListener.java:175)
KcOidcBrokerTest ++ 	at org.hibernate.event.internal.DefaultFlushEntityEventListener.onFlushEntity(DefaultFlushEntityEventListener.java:134)
KcOidcBrokerTest ++ 	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
KcOidcBrokerTest ++ 	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEntities(AbstractFlushingEventListener.java:221)
KcOidcBrokerTest ++ 	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:90)
KcOidcBrokerTest ++ 	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:38)
KcOidcBrokerTest ++ 	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
KcOidcBrokerTest ++ 	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1412)
```

### Version

quarkus3 branch

### Expected behavior

There shouldn't be this exception

### Actual behavior

An exception: The query returns the entity without the `user` set (it is `null`)

### How to Reproduce?

Run the test `KcOidcBrokerTest` with Quarkus

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #19323

### CODE REVIEW

**Comment by ahus1** [comment]
Waiting for #20010 to be merged first to upgrade to latest Hibernate version

**Comment by ahus1** [comment]
@vramik - I've removed the Hibernate workaround. It would be great if you could review it. Thanks!

**Review by vramik — APPROVED** [review]
Thanks @ahus1!

**Review by mhajas — APPROVED** [review]
Approving per @vramik 's approval

**Pull request merged**
