### PR TITLE
KEYCLOAK-13842 Detect correct content-type for ClientDescriptionConverter in Admin-Console

### PR DESCRIPTION
**Pull request by thomasdarimont**
We now use an heuristic to detect the use of xml files and use
the content-type application/xml in that case.
Previously the content-type of a request to the client-description-converter
endpoint was always set to application/json.

### CODE REVIEW

**Review by stianst — COMMENTED** [review]
There are a few other places if memory serves me correctly where we support upload of files. So it would make sense to extract this into a service rather than code it here perhaps.

Also, we would need to get a test added for this.

**Comment by thomasdarimont** [comment]
@stianst I thought so too, but I wasn't sure whether this would make sense for every file upload.
Can you give me a hint where I can find the generic angular http/resource configuration?

**Comment by thomasdarimont** [comment]
@stianst I think I found a generic way to fix this. Can you suggest me a starting point for a test?

**Comment by stianst** [comment]
My memory on this stuff is rather dated by now I'm afraid, but we allow uploading PEMs/keys/json/xml I think. 

Does this issue also apply in those cases? I don't have a WAF ready at hand to test it out myself ;)

@vmuzikar do you have some suggestions on where we a test for this can be added to the admin console tests?

**Comment by ssilvert** [comment]
@thomasdarimont,

In addition to getting the rest of the tests to run, we now have a requirement for all UI PR's to run the UI tests (either admin console or account console).  It's easy to do.

Here are the instructions to kick off the Jenkins test for your branch.  When it has run successfully, just post the URL in the format shown at the top of the instructions: https://docs.jboss.org/display/RHSSO/How+to+execute+account+and+admin+console+tests+on+Jenkins

**Comment by vmuzikar** [comment]
@ssilvert I'm afraid those instructions are not publicly accessible (because they describe our CI system).

@thomasdarimont For instructions on how to run UI tests locally, please follow:
https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md#admin-console-ui-tests
https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/keycloak-preview/account/resources/README.md#running-tests

**Comment by thomasdarimont** [comment]
@vmuzikar I tried to run the ui-tests locally via:
```
mvn \
  -f testsuite/integration-arquillian/tests/other/console/pom.xml \
  clean test \
  -Pconsole-ui-tests \
  -Dbrowser=chrome \
  -Dwebdriver.chrome.driver=/home/tom/dev/tools/chromedriver/chromedriver
```

A few observations:
- Client Certificate selection pops up, although the necessary ssl cert expections are in place.
This means that everytime the chrome browser is restarted, I need to click cancel before the tests can proceed...
https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/drone/KeycloakWebDriverConfigurator.java#L67
Perhaps this can be solved if the testsuite runs in their own browser profile and not within the one of the current user.

- I see quite a few red error messages in the admin-console like "No response from server"

Could you trigger a UI test run for this in your CI environment?

**Comment by vmuzikar** [comment]
@thomasdarimont I'm sorry for late response. Many of the tests failed in CI but we had some problems with them recently which now seem to be fixed. Could you please rebase? I'll respin the tests immediately.

The tests always use a fresh browser profile. You probably have some cert in OS store so it's picked by every profile.

**Comment by thomasdarimont** [comment]
@vmuzikar thanks for the heads up - I just rebased the code.

**Review by vmuzikar — COMMENTED** [review]
To be honest, I don't much like this solution. It seems a bit unsystematic to me, feels more like a bit dirty workaround for the real issue. It can potentially easily break something else as it affects all requests and I'm afraid our test coverage for uploads in Admin Console is far from ideal.

The browser should automatically determine the correct `Content-Type` for uploaded file, right? The real issue here is why the Console is constructing requests for file uploads in a way that this detection is skipped.

But if @stianst and @ssilvert say it's OK, I'm cool with this change.

Test run: https://keycloak-jenkins.com/job/keycloak-admin-console-matrix/155/ (still running)

**Comment by vmuzikar** [comment]
Also we'd need a test to be added for this in case we decide to go with this solution.

**Comment by thomasdarimont** [comment]
@vmuzikar thanks for the feedback. I tried to adjust the request submission by dynamically setting the proper content-type, but I couldn't find the right spot... (e.g.: generic way to intercept $resource posts/ put requests, preferably configurable at the call-site)
The interceptor was the first solution that worked.

**Review by ssilvert — COMMENTED** [review]
The issue I see is that the heuristic doesn't look very strong.  It is only checking to see if the first character is a '<'.  

I believe this issue only applies to POST requests?  So perhaps we could do this only for POST?

Also, a more thorough way to check if the content is XML is to see if it can be successfully parsed.  You could use the DOMParser and see if it returns an error.  However, I don't know if that would slow down other requests.

**Comment by ssilvert** [comment]
This PR has been stale for a long time so I'm going to close it.

@thomasdarimont if you want to bring it back to life just say the word and we can continue.

**Pull request closed without merging**
