### PR TITLE
Fixes update email for impersonated users

### PR DESCRIPTION
**Pull request by windwinkel**
After impersonating a user the auth_session_id is not updated correctly, and therefore still contains the impersonated users session id. This will create errors on the account page for the impersonated user.

In our case after changing the email of the impersonated user, the user was redirected to the 'already logged in page' and was unable to use the app again, due to inconsistent state. 
With this fix, the user is redirected to the 'verify email page'. 

Closes #21690

### CODE REVIEW

**Review by pedroigor — COMMENTED** [review]
Isn't this change enough https://github.com/keycloak/keycloak/issues/19677?

I can't reproduce the issue upstream (but 20.0.5). Steps I did:

- start server with `features=update-email`
- create realm
- create user
- click on impersonate action on the user details page
- click on update email link to update the email
- Try change the email

**Comment by zyv** [comment]
The corresponding PR to check is here: https://github.com/keycloak/keycloak/pull/19748

**Comment by zyv** [comment]
@pedroigor on Keycloak 20.0.5 doesn't work for us without our fix. I understood you wanted us to try to backport the mentioned PR to 20.0.5 and see if it fixes this issue. We would need time to try it out.

**Pull request closed without merging**
