### PR TITLE
KEYCLOAK-12326 when `WebAuthnCredentialModel` is set as a "password" removing the IdP should be allowed

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Review by ssilvert — COMMENTED** [review]
Needs a test.

**Comment by edewit** [comment]
can we mock hardware tokens?

**Comment by vmuzikar** [comment]
@edewit Sort of. Please see https://github.com/keycloak/keycloak/blob/601bf8d63ed64b09fa05af79b3a1f407faebe768/testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/SigningInTest.java#L270

**Comment by edewit** [comment]
don't know how to test this, closing

**Pull request closed without merging**
