### PR TITLE
KEYCLOAK-6228

### PR DESCRIPTION
**Pull request by patriot1burke**

### CODE REVIEW

**Comment by mposolda** [comment]
I've tried to review, but not 100% sure I didn't miss anything. Maybe time will show if everything still works :) Few things:

1) RealmAdminResource.getClientSessionStats -- I think this will be quite bad for performance. For example when you have cluster with 2 nodes and one million of user sessions, then calling of "session.sessions().getUserSessions(realm)" will need to download 500K of sessions from the other infinispan node over the network. This will probably break in many environments (customer had similar issues reported for similar things). 

My vote is to remove performance-killer methods:

{code}
List<UserSessionModel> getUserSessions(RealmModel realm);
List<UserSessionModel> getOfflineUserSessions(RealmModel realm);
{code}

and do something better for performance. Maybe:
a) Isn't it possible to somehow track all "already available" clients, which have at least one clientSession and call "getActiveUserSessions" for those clients?
b) Add some methods to UserSessionProvider, which will allow to cover this usecase with better performance and delegate the work to the provider implementation. Infinispan has streaming API to deal with filters, consumers, collectors etc. This allows better performance as every cluster node do the work for his own entities. Especially it doesn't require caller to download everything, and then iterate over everything and do the whole work by itself.

If you don't have time to deal with performance for this PR, I can create followup JIRA and take a look later at it.


2) DB Migration - Did you try it already or not yet at this stage? I afraid especially of non-null entities with default value "local" in OFFLINE_CLIENT_SESSION table. I think it won't work if there are already some existing entries in the table. I recall it's needed first to create nullable column, then update all data to have value "local" and finally switch to non-null. But not 100% sure...


3) UserStorageManager.preRemove(realm, component) now handles calling of ClientStorageProvider.preRemove. Looks strange to me that UserStorageManager is somehow interested in clients stuff. Shouldn't it be rather responsibility of ClientStorageManager?


4) One general note (just partially related to this PR). It looks quite bad to me, that we have 2 UserStorageTest implementations (one in old testsuite, and one in new). IMO when tests are migrated from the old testsuite, they should be always removed from the old testsuite. Keeping them in both places means that both places will be more and more unsynced (as for example this PR edits just the old test, but not new). But seems that this is something for separate discussion :)

**Comment by patriot1burke** [comment]
**Response to Question 1**
 
Are you sure that the prior code wasn't just as inefficient?  Are you sure Infinispan is optimizing anything in the old code?  Or maybe you're just concerned by all the extra object creation by creating full fledged session objects?  The old code had to basically hit every single client session.  It might have been more inefficient as it had to search every single client session for each client.  Here's a condensed version of the old code:

        for (ClientModel client : realm.getClients()) {
            long size = session.sessions().getActiveUserSessions(client.getRealm(), client);
                 cache.entrySet().stream()
                .filter(UserSessionPredicate.create(realm.getId()).client(clientUuid))
                .count();
Isn't the above old code doing the same query N times where N is the number of clients in the system?

I'll rewrite it to be one query that gathers count data and doesn't create session models.  That's about as optimized as I can make it.

**Response to Question2 ** 

Need an answer to this one.  Maybe Ill just do your suggestion to be safe?

**Response to Question 3**

UserConsents needs to be removed for client's whose ClientStorageProvider has been moved.  ClientStorageProviders should not be aware how consents are stored.

**Comment by mposolda** [comment]
**Response to Question  1** 

Yes, infinispan is doing optimizations in the old code. This code is using infinispan distributed streams:

```
             cache.entrySet().stream()
            .filter(UserSessionPredicate.create(realm.getId()).client(clientUuid))
            .count();
```

it works in a way that every node iterates through the entities, which he is primary owner and just send the overall count to the caller. There is minimal overhead regarding the need of marshalling and network communication, which are usually major performance bottlenecks when using infinispan. See details here - http://infinispan.org/docs/8.2.x/user_guide/user_guide.html#distribution_replication .

Yeah, agree that old code is also not very great and need to iterate over the cache count-of-client times. It can be improved by add the needed method to UserSessionProvider and collect data by iterating whole cache once. As I mentioned, if you want, I can help and follow-up on your work and check that performance is fine in cluster.

**Response to 2)** 

We have MigrationTest and it is doing some testing of offline tokens. If it pass, it's likely ok, but I bet like 80% it will fail :) Some details how to run it: https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md#migration-test

**Response to 3)** 

Ah ok. Sorry, I should read code more properly.

**Comment by patriot1burke** [comment]
@mposolda  Everything should be good now

**Question 1**
I created a new method that uses the stream API to build session stats.  Cross DC tests this operation in cluster right? (I had to debug some NotSerializable exceptions).


**Question 2***

Take a look at 4.0.xml.  That should be good enough?

**Comment by mposolda** [comment]
**Question 1** Cool, Thanks! Yes it is tested in SessionExpirationCrossDCTest. And this is tested in travis on PR. So should be fine.
**Question 2** Yeah, it should be fine if it passes MigrationTest. I had some doubts about the fact, that you first add non-nullable column and then update it with the values. But maybe it's sufficient if databases evaluate it at the end of transaction as default values are filled in the column at that point? Maybe @hmlnarik knows?

I am adding approve (assuming MigrationTest is fine).

**Review by mposolda — APPROVED** [review]

**Pull request merged**
