### PR TITLE
Quarkus3 upgrade hibernate 6.2

### PR DESCRIPTION
**Pull request by ahus1**
Upgrade to Hibernate 6.2.0.Final and remove all workarounds that are no longer necessary.

### CODE REVIEW

**Comment by ahus1** [comment]
@vramik - this PR removed all workarounds that are no longer necessary after some issues have been fixed in the Hibernate 6.2.0 final release.
Please give it a review. Thanks!

**Review by vramik — APPROVED** [review]
Thank you @ahus1 for this PR. Changes lgtm. 

Do you plan to squash the commits? If so, I'd suggest to list the issue numbers of the workarounds. 

If not, I think one commit per issue would be great, so I'd suggest squashing commit 2 and 3. wdyt?

**Comment by ahus1** [comment]
@vramik - the build is now as green as possible on the Q3 branch: only those tests that failed before the change are failing. Ready for review when you have the time. Thanks!

**Review by vramik — APPROVED** [review]
Thank you @ahus1! It's ready to be merged IMO.

**Comment by ahus1** [comment]
@vmuzikar - could you please merge it? Thanks!

**Review by vmuzikar — APPROVED** [review]

**Pull request merged**
