### PR TITLE
KEYCLOAK-15911: Fix UserStorageManager does not pick up new LDAP Config

### PR DESCRIPTION
**Pull request by hongthang152**
This PR fixes the issue where the LDAP configuration is not updated when sync period or enabled flag is not changed.

### CODE REVIEW

**Review by mhajas — CHANGES_REQUESTED** [review]
Thank you for the PR @hongthang152, it seems that `SyncFederationTest` tests are failing. Could you please have a look?

The failed test class: https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/sync/SyncFederationTest.java
Full log of the failures:  https://github.com/keycloak/keycloak/pull/7498/checks?check_run_id=1253951578
How to run tests: https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md#running-tests-in-the-development-mode-keycloak-on-embedded-undertow

Also, we won't be able to merge this unless we provide a test for the issue described in KEYCLOAK-15911. I would be happy to help you with developing it.

**Comment by hmlnarik** [comment]
@hongthang152 Could you please address the comment above?

**Comment by hongthang152** [comment]
Hi @hmlnarik ,

I am still trying to allocate my time for this PR.

**Comment by hongthang152** [comment]
I am still looking into the failed test cases. My code change should affect the onUpdate test case only, but for some reason the onCreate test gets affected as well. Maybe there is something that I am missing here.

**Comment by mhajas** [comment]
Hi @hongthang152, do you plan to continue with this PR?

**Comment by hongthang152** [comment]
@mhajas Unfortunately I havent allocated much of my time for this PR. Do you want to continue with my work and finish it ?

**Comment by hmlnarik** [comment]
Thank you for the PR. There has been no activity on this PR for considerable amount of time, and thus is being closed. Feel free to reopen the PR if you still feel it is valid.

**Pull request closed without merging**
