### PR TITLE
KEYCLOAK-2283 added truststore test for email

### PR DESCRIPTION
**Pull request by fkiss**
added tests for verifying email through ssl
replaced greenmail with subethasmtp to be able to configure ssl with custom certs
added support for using truststore on all servers by default
I will remove greenmail server totally in next PR because is used by other tests

### CODE REVIEW

**Comment by stianst** [comment]
I don't like replacing greenmail, it's worked well and we've never had any problems with it. Looks like it's fully possible to configure SSL with greenmail (first search on Google revealed http://stackoverflow.com/questions/6552829/using-javamail-and-greenmail-for-smtps-ssl).

For changes like this please raise on Keycloak dev list first.

**Comment by fkiss** [comment]
I know about solution in link you have posted, it was in previous PR. There is no problem to run GreenMail with SSL. However, GreenMail has hardcoded it's own certificate so I needed to use another SMTPs server which allows using own certificates.

**Comment by stianst** [comment]
How can GreenMail hardcode it's own certificate? A certificate is bound to a hostname.

**Comment by stianst** [comment]
Never mind, I get it. However, you should be able to replace the certificate with the steps from the above Stackoverflow by using a different SSLSocketFactory

**Comment by stianst** [comment]
Closing this, please send a new PR once ready

**Pull request closed without merging**
