### PR TITLE
Skip grant role if exists for federated storage

### LINKED ISSUE #26507: Failed to link the user with an existing read-token role from the federation provider when AddReadTokenRoleOnCreate was enabled for the IdP.
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

As title said,
failed to link the user with an existing read-token role from the federation provider when AddReadTokenRoleOnCreate was enabled for the IdP.

The error logs are like
```
org.hibernate.exception.ConstraintViolationException: could not execute statement [Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_41 ON PUBLIC.FED_USER_ROLE_MAPPING(ROLE_ID, USER_ID) VALUES ( /* key:1 */ 'f7977142-8b66-428a-9941-d473a9d43771', 'f:3ca9bed7-f7c3-49ba-bfc6-d6faf45e82fb:testuser')"; SQL statement:
insert into FED_USER_ROLE_MAPPING (REALM_ID,STORAGE_PROVIDER_ID,ROLE_ID,USER_ID) values (?,?,?,?) [23505-224]] [insert into FED_USER_ROLE_MAPPING (REALM_ID,STORAGE_PROVIDER_ID,ROLE_ID,USER_ID) values (?,?,?,?)]
```

### Version

nightly

### Expected behavior

Link success

### Actual behavior

Error on first broker login

### How to Reproduce?

1. Setup the IdP with `AddReadTokenRoleOnCreate` enabled
2. Setup a federation provider
3. Create a user and grant `broker.read-token` role with the user into the federation storage
4. Login from the IdP to link to the user

### Anything else?

The JPA `UserAdapter` has check the role before granting.
https://github.com/keycloak/keycloak/blob/28c9f98930e38852e23ffbdb7b4cd7546efe46f8/model/jpa/src/main/java/org/keycloak/models/jpa/UserAdapter.java#L452-L455

The `AbstractUserAdapterFederatedStorage` should check as well.
https://github.com/keycloak/keycloak/blob/28c9f98930e38852e23ffbdb7b4cd7546efe46f8/model/legacy/src/main/java/org/keycloak/storage/adapter/AbstractUserAdapterFederatedStorage.java#L179-L181

I will prepare the fix.

### PR DESCRIPTION
**Pull request by lexcao**
Closes #26507

### CODE REVIEW

**Review by mhajas — DISMISSED** [review]
Thank you @lexcao! Nice catch

**Comment by mhajas** [comment]
@lexcao Could you please rebase?

**Comment by lexcao** [comment]
Hi @mhajas updated.

**Review by mhajas — APPROVED** [review]
Thank you @lexcao

**Pull request merged**
