### PR TITLE
Revisit parent-child relationship in jpa map store 

### LINKED ISSUE #14278: Revisit parent-child relationship in jpa map store
https://github.com/keycloak/keycloak/discussions/13229

### PR DESCRIPTION
**Pull request by vramik**
Closes https://github.com/keycloak/keycloak/issues/14278

### CODE REVIEW

**Comment by ahus1** [comment]
Hi Vlasta, I had a look at the code as you asked for, and here're some thoughts. I'm replying in the chat here, we could also transfer this to the GitHub PR. Should I copy and paste this comment there?

* I agree with the changes about the indexed entity version

* I see that the entityVersion is updated in all root entities when traversing up in the tree, while the locking assumes that the child is only one step away from the parent, and optimistically locks only the immediate parent. 

I wonder what assumptions we should make/state here, starting with the OptimisticLockingListener.lockRootEntity: Can the parent of a child be a non-root entity? If not, then optimistically locking of the parent is sufficient from my point of view. If there can be multiple non-root parents, then it should traverse upwards until it finds the first root component. Looking at the next paragraph, this should probably be done to be consistent.

With the EntityVersionListener, I think the previous assumption was that there be multiple childs until one reaches the first real root parent, that would then have its entityVersion bumped (updateEntityVersion()). The new implementation would bump all parent's entity versions, which is safe but a bit too much I think: We bump the entity version as that entity version would be the one that serializes the JSON in the new format. I think it would be enough to add a break statement in the while loop of updateEntityVersion() once there is the first JpaRootEntity found.

**Comment by vramik** [comment]
> I wonder what assumptions we should make/state here, starting with the OptimisticLockingListener.lockRootEntity: Can the parent of a child be a non-root entity? If not, then optimistically locking of the parent is sufficient from my point of view. If there can be multiple non-root parents, then it should traverse upwards until it finds the first root component. Looking at the next paragraph, this should probably be done to be consistent.

Currently the assumption is that any parent of a child entity is root entity, even though it could also be a child of another parent. So it'd optimistically lock the parent entity in case it's not the child entity at the same time.

> With the EntityVersionListener, I think the previous assumption was that there be multiple childs until one reaches the first real root parent, that would then have its entityVersion bumped (updateEntityVersion()). The new implementation would bump all parent's entity versions, which is safe but a bit too much I think: We bump the entity version as that entity version would be the one that serializes the JSON in the new format. I think it would be enough to add a break statement in the while loop of updateEntityVersion() once there is the first JpaRootEntity found.

When I was thinking about it one scenario came into my mind which inspired me to implement it in this way. Let's say we would have realms in v1 and next version of keycloak we'd need to extract some entity to its own table, e.g. auth-flows and auth-flows would have collection of child entities - auth-executions. Then once we read the realm into a memory and one of the auth-exections would be changed - then we should set the entity version to the auth-flow (v1) and also to the realm (v2). So the entity versions would be set to all entities in the tree unless it's detected that the entity version actually hasn't changed.

As discussed in a call: let's see how it potentially affects performance and then possibly update it in future.

I'll also (as discussed in the call) add the info into a java-doc to record current assumptions.

**Review by ahus1 — APPROVED** [review]
Thanks for updating the docs and the JavaDoc! I've reviewed the changes and tested them look fine to me. 

The tests are green, the failed operator test is not related.

Ready to be merged!

**Review by hmlnarik — APPROVED** [review]
Approving per @ahus1 's approval

**Pull request merged**
