### PR TITLE
KEYCLOAK-5285: Adding protected access.

### PR DESCRIPTION
**Pull request by johnament**
Allows FreemarkerEmailTemplateProvider to be more extensible.

### CODE REVIEW

**Comment by stianst** [comment]
There are reasons to keep the methods private as that allows refactoring/changing things without affecting backwards compatibility. If there are to much things that are public/protected we'll end up being stuck not being able to change anything in the future.

**Comment by gaetancollaud** [comment]
@stianst I understand your point. But currently we need to duplicate a lot of codes if we want to "extend" the FreemarkerEmailTemplateProvider. I prefer to have to update my code to fit the new version than having hundreds of copied lines with potential bugs. By extending this provider and not an interface I'm aware of compatibility issues with new version.

Maybe a warning can be added to the class.

**Comment by johnament** [comment]
@stianst I would be happy to refine this further to identify API methods vs internal methods.  I'll admit that I was purposely overzealous in these changes.  In my case, I need to override the follow methods:

- `getRealmName()`
- `setRealm`&`setUser` since I don't have access to the fields
- `sendExecuteActions` which is public so makes sense that its overridden
- `send(String subjectKey, String template, Map<String, Object> attributes) throws EmailException`

Everything else could be private in my use case, I'm not sure how this lines up with your needs @gaetancollaud

**Comment by gaetancollaud** [comment]
@stianst Just see that now, but we have a warning when we start keycloak saying that SPI interface can change. So I don't see why you couldn't change anything in the future.
```
keycloak-server | 15:36:30,154 WARN  [org.keycloak.services] (ServerService Thread Pool -- 55) KC-SERVICES0047: morphean-email (ch.morphean.authenticator.email.MorpheanEmailTemplateProviderFactory) is implementing the internal SPI emailTemplate. This SPI is internal and may change without notice
```

**Comment by stianst** [comment]
Ok, I'm going to merge this as the SPI is private and FreeMarkerEmailTemplateProvider is going to remain in server-spi-private module even when the SPI is moved to public.

**Comment by johnament** [comment]
Awesome, thanks!

**Pull request merged**
