### PR TITLE
 KEYCLOAK-8991 Keycloak Installed Application: provide OSGi meta data

### PR DESCRIPTION
**Pull request by puce77**

### CODE REVIEW

**Comment by puce77** [comment]
Solution explained:

-     introduced new module keycloak-installed-desktop-adapter
-     keycloak-installed-adapter depends on keycloak-installed-desktop-adapter
-     keycloak-installed-desktop-adapter only contains a minimal dependency set which can be loaded in an OSGi environment
-     keycloak-installed-desktop-adapter: new class org.keycloak.adapters.installed.desktop.KeycloakInstalledDesktop
-     keycloak-installed-desktop-adapter: new class org.keycloak.adapters.installed.core.AbstractKeycloakInstalled
-     AbstractKeycloakInstalled is in a different package than KeycloakInstalledDesktop to allow to move it to a different module later, if required, without getting a split package
-     keycloak-installed-adapter: new class org.keycloak.adapters.installed.KeycloakInstalledCommandLine (package private for now -> can be moved to a different module later, if required, without getting a split package)
-     keycloak-installed-adapter: new class org.keycloak.adapters.installed.KeycloakInstalledManual (package private for now -> can be moved to a different module later, if required, without getting a split package)
-     KeycloakInstalledDesktop, KeycloakInstalledCommandLine and KeycloakInstalledManual extend AbstractKeycloakInstalled
-     KeycloakInstalled delegates to KeycloakInstalledDesktop, KeycloakInstalledCommandLine and KeycloakInstalledManual

**Comment by puce77** [comment]
I've tried to retain the KeycloakInstalled API as much as possible (an exception is e.g. CallbackListener, a non-static nested class, which has been moved to KeycloakInstalledDesktop. I guess it's only used internally though the class is public.

There could be several API and code clean-ups (e.g. using more try-with-resource to properly close resources), but I didn't want to change too much in one PR, so I mainly just moved some code around.

I've marked some deprecated code as deprecated.

**Comment by puce77** [comment]
I could successfully login from a Drombler FX application (JavaFX + OSGi) using the new KeycloakInstalledDesktop class.

**Comment by puce77** [comment]
The issue KEYCLOAK-8991blocks the integration of Keycloak in a JavaFX + OSGi application.

This pull request resolves that issue.

It would be great if someone could review and integrate my pull request.

**Comment by stianst** [comment]
I'm not to clued up on OSGI, but I don't like this approach. Introducing new modules and copying classes etc. does not seem to be the right approach here. Unless you can find a cleaner approach we can't accept this.

**Comment by puce77** [comment]
@stianst Could you explain in more detail why you think this is not the right approach? Please note that I didn't copy classes, I refactored them. OSGi requires dependencies with OSGi meta data. This is currently not the case thus the additional (only one) module. I'm not sure in which direction you would like the code to go to fix this blocker.

**Comment by puce77** [comment]
@stianst In https://issues.jboss.org/browse/KEYCLOAK-8991?focusedCommentId=13682133&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13682133 you mentioned: 

> It didn't use to require Resteasy, but rather HttpClient. Not sure when/why this change was done, but it should be reverted.

Should I really just remove the Resteasy code? Will this not break other things? Or are you OK with this and the issues will be fixed when and where they pop-up?

**Comment by stianst** [comment]
@hmlnarik will review and comment on this, but it won't be until next week at the earliest.

**Comment by puce77** [comment]
I've written an alternative patch for this issue: #5909 
It replaces Resteasy with Jersey in keycloak-installed-adapter to support OSGi-based Keycloak clients.
Since the Resteasy code was mainliy written using JAX-RS, the code changes are minimal.

**Comment by hmlnarik** [comment]
Replaced by simpler #5909.

**Pull request closed without merging**
