### PR TITLE
KEYCLOAK-12249 added test to test that time is localized

### PR DESCRIPTION
**Pull request by edewit**
UI build: https://keycloak-jenkins.com/job/keycloak-account2-matrix/946/

### CODE REVIEW

**Comment by ssilvert** [comment]
> UI build: https://keycloak-jenkins.com/job/keycloak-account2-matrix/946/

@edewit  The test InternationalizationTest.shouldDisplayTimeUsingSelectedLocale failed on that build.  Need to fix and build again.

**Comment by edewit** [comment]
UI build: https://keycloak-jenkins.com/job/keycloak-account2-matrix/956/

**Comment by ssilvert** [comment]
> Just needed a rebase: https://keycloak-jenkins.com/job/keycloak-account2-matrix/956/

Still showing failure for InternationalizationTest.shouldDisplayTimeUsingSelectedLocale

**Comment by edewit** [comment]
closed in favor of #7260

**Pull request closed without merging**
