### PR TITLE
[KEYCLOAK-8411] Migrate ModelClass: ClientModelTest

### PR DESCRIPTION
**Pull request by mabartos**

### CODE REVIEW

**Review by mposolda — COMMENTED** [review]
@mabartos Thanks for the PR! It looks nice IMO. 

Just one small thing: it will be good to remove the original ClientModelTest from the old testsuite. Having it on both places is not good (duplicated code, more maintenance etc)

**Comment by mabartos** [comment]
You're right. Thanks for your remarks @mposolda :)

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Review by mposolda — APPROVED** [review]
@mabartos Thanks!

**Pull request merged**
