### PR TITLE
Removing the extra two-minute Window for persistent user sessions

### LINKED ISSUE #28418: SSO Session Idle: session is still active after session idle time expired
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

I am trying SSO Session Idle scenario
I have:
Token Lifespan: 5 minutes
SSO Session Timeout: 30 minutes
SSO Session Max: 10 hours

If I create session at for example 20:00 then I will have:
access_token expiration to 20:05
refresh_token expiration to 20:30.

Problem is session after 20:30 (user is inactive). It should be invalided but it is not. The session is still valid and I see session valid in administration console too. But the session will invalided next +2 minutes at 20:32.

After doing some research it seems this is standard Keycloak behavior where it keeps 2 min allowance for synchronization between Keycloak cluster and there is no way to change.
https://www.keycloak.org/docs/latest/server_admin/index.html#_idle_timeouts_note

But my environment is not using cluster.  But still it adds 2 mins buffer.
How i can avoid this 2 mins buffer?

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

For non-cluster env, Keycloak should not add 2mins buffer to remove session when session idle time is reached. 
I would suggest that this can be made as a configuration option to set the deployment type.

### Actual behavior

Irrespective of how keycloak is deployed (cluster or non-cluster), 2 mins buffer is added to session idle time

### How to Reproduce?

As mentioned in description

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #28418

### CODE REVIEW

**Comment by ahus1** [comment]
@mhajas - please review when you have the time. Thanks!

**Review by mhajas — COMMENTED** [review]
I am quite surprised there were no failures in the testsuite after this change but probably the testcases are just written in a way they do not fail if the sessions are invalid sooner. 

Should we remove all occurrences of `IDLE_TIMEOUT_WINDOW_SECONDS` from the testsuite? I would say after this change the testsuite should be passing also without it.

**Comment by ahus1** [comment]
@mhajas - I remember it failed when I set it to "0" as in some places we are adding 2x the `IDLE_TIMEOUT_WINDOW_SECONDS` to ensure a session has expired. When setting it to 0 that logic didn't work any more, and then tests started to fail. 

The tests would still need to pass for the old implementation without the persistent sessions, so I'd keep it. 

WDYT?

**Comment by mhajas** [comment]
I did this change: https://github.com/mhajas/keycloak/commit/6d62520a016395f9ce13f8799a7e541f656a860b and the ci passed: https://github.com/mhajas/keycloak/actions/runs/10739667552 do you think it makes sense?

**Comment by ahus1** [comment]
@mhajas - thanks, looks good. Added your commit to this PR. Builds are still running, should still be good for a review.

**Review by mhajas — APPROVED** [review]
Thank you @ahus1. LGTM.

**Pull request merged**
