### PR TITLE
KEYCLOAK-8542 Remove resteasy workaround - KeycloakStringEntityFilter

### PR DESCRIPTION
**Pull request by vramik**

### CODE REVIEW

**Comment by vramik** [comment]
@keycloak-ci-bot test

**Review by slaskawi — COMMENTED** [review]
LGTM apart from the failures.

**Comment by vramik** [comment]
@keycloak-ci-bot test

**Comment by hmlnarik** [comment]
@keycloak-ci-bot test

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
