### PR TITLE
KEYCLOAK-2664 - QRCodeResource should prohibit caching of the generated image

### PR DESCRIPTION
**Pull request by thomasdarimont**
Added cache-control headers to avoid caching for generated QRCode images.

### CODE REVIEW

**Comment by stianst** [comment]
Can you move the creation of CacheControl to org.keycloak.services.util.CacheControlUtil?

**Comment by thomasdarimont** [comment]
Sure, may I just add
```
       cacheControl.setMustRevalidate(true);
        cacheControl.setNoCache(true);
        cacheControl.setNoStore(true);
```
to `org.keycloak.services.util.CacheControlUtil#noCache` and use `CacheControlUtil. noCache()` instead of introducing a new method?

**Comment by stianst** [comment]
We need this in 1.9.x branch as well as master

**Comment by thomasdarimont** [comment]
Adjusted the code as requested - I squashed the change into the former commit, so you should be able to just cherry pick 3e6b650 into master / 1.9.x.

**Pull request merged**
