### PR TITLE
Userinfo endpoint doesn't accept charset

### LINKED ISSUE #20671: Userinfo endpoint doesn't accept charset
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authorization-services

### Describe the bug

After https://github.com/keycloak/keycloak/issues/15429 `Content-Type: application/x-www-form-urlencoded` header is required to be passed for token introspection endpoint:
```java
if (MediaType.APPLICATION_FORM_URLENCODED.equalsIgnoreCase(headers.getHeaderString(HttpHeaders.CONTENT_TYPE))) {
      // some code
 }
```

Thus it rejects a valid header when `charset` is specified, e.g. `Content-Type: application/x-www-form-urlencoded;charset=UTF-8` which is a default value added to all form requests in some popular Java libraries. For instance, 
https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/http/converter/FormHttpMessageConverter.java#L420.

### Version

21.1.1

### Expected behavior

`Content-Type: application/x-www-form-urlencoded;charset=UTF-8` is accepted. 

### Actual behavior

`Content-Type: application/x-www-form-urlencoded` is only accepted as is.

### How to Reproduce?

```bash 
curl -u $client_auth $url/realms/$realm/protocol/openid-connect/userinfo \
        -H 'Content-Type: application/x-www-form-urlencoded;charset=UTF-8' -d "access_token=$atoken"
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedro-hos**
Closes #20671

### CODE REVIEW

**Review by jonkoops — CHANGES_REQUESTED** [review]
@pedro-hos could you also add a test to verify this fix?

**Comment by pedro-hos** [comment]
@jonkoops I have finished the tests. Let me know if you need some other adjustments. Thanks

**Review by jonkoops — APPROVED** [review]
LGTM

**Review by ssilvert — APPROVED** [review]
LGTM

**Review by mposolda — APPROVED** [review]
@pedro-hos @jonkoops @ssilvert Thanks for the PR and for the reviews!

**Comment by dalbani** [comment]
I just ran into this issue after an upgrade to Keycloak 21.
I was wondering: any plan to backport this fix to the 21 branch?

**Comment by jonkoops** [comment]
No, we currently are not planning a patch release. This will come along in 22.

**Pull request merged**
