### PR TITLE
[KEYCLOAK-884] - OpenID Connect UserInfo Endpoint.

### PR DESCRIPTION
**Pull request by pedroigor**
Initial support for KEYCLOAK-884.

These changes are enough to get KC brokering itself.

### CODE REVIEW

**Comment by stianst** [comment]
Changing the IDToken to have the UserClaims is messy and requires changes to apps and adapters. It would be much better to introduce a UserInfoRepresentation that is used by the userinfo endpoint and leave everything else alone.

**Comment by stianst** [comment]
There's also no need to use cache control private as it also has @NoCache.

**Comment by pedroigor** [comment]
What about keeping the methods in IDToken ? The whole motivation for these changes is to avoid code replicatiion for claims declaration.

And also, makes more sense to have it as is instead of directly defined inside the IDToken.

**Comment by patriot1burke** [comment]
This breaks backward compatibilty with existing user app code, BUT...I'll have to refactor IDToken anyways to support custom claims and claim mappings, i.e. if somebody feels the need to rename the "phone" claim to "phone_number".  Also, you'll have to change the examples too as the JSP pages use the old

**Comment by pedroigor** [comment]
Changed examples.

**Pull request merged**
