### PR TITLE
Quarkus relational database setup documentation error

### LINKED ISSUE #9324: Quarkus relational database setup documentation error
### Describe the bug

Quarkus relational database setup documentation (docs/guides/src/main/server/db.adoc) mentions `kc.sh start` command line parameters `--db-host` and `--db-user` which don't exist. When used, the following error messages are displayed:

```
Unknown options: '--db-host', '[REDACTED]', '--db-user', '[REDACTED]'
Possible solutions: --db-pool-min-size, --db-schema, --db-username, --db-password, --db-url-host, --db-url, --db-pool-max-size, --db-url-properties, --db-pool-initial-size, --db-url-database, --db
```

### Version

16.1.0

### Expected behavior

Documentation should mention the right command line parameters: `--db-url-host` and `--db-username`

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vanrar68**
Closes #9324

### CODE REVIEW

**Review by pedroigor — COMMENTED** [review]
@vanrar68 Thanks.

**Comment by vanrar68** [comment]
There may something else. If I submit the `--db-schema` command line parameter like mentioned in the doc I get the following warning message at runtime:

`WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.datasource.schema" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo`

**Comment by pedroigor** [comment]
@vanrar68 Created https://github.com/keycloak/keycloak/issues/9328.

**Comment by vanrar68** [comment]
> There may be something else. If I submit the `--db-schema` command line parameter like mentioned in the doc I get the following warning message at runtime:
> 
> `WARN [io.qua.config] (main) Unrecognized configuration key "quarkus.datasource.schema" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo`

The only way I found to get around the `--db-schema` problem is to use the `--db-url` command line parameter like this:

`./kc.sh start-dev --db-url jdbc:mysql://[REDACTED_HOST:PORT]/[REDACTED_SCHEMA] --db-username [REDACTED_USERNAME] --db-password [REDACTED_PASSWORD]`

 but then I hit the following problem:

WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: No suitable driver found for jdbc:mysql://[REDACTED_HOST:PORT]/[REDACTED_SCHEMA]
        at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:191)
        at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:352)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:210)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:509)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:490)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by pedroigor** [comment]
@vanrar68 You do not need to run `build` when running `start-dev`. It will happen automatically based on the options you are using.

In your case, `start-dev` is reverting your configuration to `mysql` and using `h2-file`. Try this:

```
./kc.sh start-dev --db mysql --db-url jdbc:mysql://[REDACTED_HOST:PORT]/[REDACTED_SCHEMA] --db-username [REDACTED_USERNAME] --db-password [REDACTED_PASSWORD]
```

**Comment by vanrar68** [comment]
Thanks @pedroigor , that solves the SQL connection problem for the start-dev profile.
Now with the prod profile (start command) is it OK to assume that if all the environment variables are set correctly (KC_DB, KC_DB_URL, KC_DB_USERNAME, KC_DB_PASSOWRD) the following 2 commands are enough to start a Keycloak.X instance:
```
kc.sh build
kc.sh start
```
Because there seem to be a problem with `kc.db.passowrd`. As you can see below, there seem to be 2 different values for this data (one persisted and one from the env variable). Unfortunately the wrong one is used at runtime and the SQL connection fails.

```
./kc.sh show-config
kc.config.args =  show-config (KcSysPropConfigSource)
kc.db =  mysql (PersistedConfigSource)
kc.db.passowrd =  [REDACTED] (KcEnvVarConfigSource)
kc.db.password =  ******* (PersistedConfigSource)
kc.db.url =  jdbc:mysql://[REDACTED]:[REDACTED]1/[REDACTED] (EnvConfigSource)
kc.db.username =  [REDACTED] (PersistedConfigSource)
kc.home.dir =  /opt/keycloak/bin/../ (KcSysPropConfigSource)
kc.hostname.strict =  false (EnvConfigSource)
kc.http.enabled =  false (PersistedConfigSource)
kc.metrics.enabled =  false (PersistedConfigSource)
kc.proxy =  edge (EnvConfigSource)
kc.show.config =  none (KcSysPropConfigSource)
kc.version =  16.1.0 (KcSysPropConfigSource)
```

I can start the Keycloak.X instance with the following command:
`./kc.sh start --db-password [REDACTED]`
but I guess it should be possible to run an instance with only the env variables set (without command line arguments)

**Comment by vanrar68** [comment]
Forget about the last message. There was a typo in the setting name

**Comment by pedroigor** [comment]
@vanrar68 Actually, you also found an issue :) And I've created https://github.com/keycloak/keycloak/issues/9335.

**Comment by vanrar68** [comment]
The documentation is missing a Feature category. Is this intentional ?
`kc.sh` inline help indicates that it's possible to enable features with the `--features-[FEATURENAME] enabled` option but I found out it's also possible to enable features with env vars. The following command seems to work fine:
```
export KC_FEATURES_ADMIN2=enabled
./kc.sh start-dev
```
It might be a good idea to add this to the documentation

**Review by pedroigor — APPROVED** [review]

**Comment by pedroigor** [comment]
@vanrar68 Thanks.

**Pull request merged**
