### PR TITLE
NPE when Default Role is not present on CachedRealm 

### LINKED ISSUE #33817: NEP when Default Role is not present on CachedRealm
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

If we haven't a default role configured, we get `NullPointerException` at [1] like:

```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-3) Uncaught server error: java.lang.NullPointerException
at [org.keycloak.keycloak-model-infinispan@18.0.0.redhat-00002](mailto:org.keycloak.keycloak-model-infinispan@18.0.0.redhat-00002)//org.keycloak.models.cache.infinispan.entities.CachedRealm.<init>(CachedRealm.java:266)
at [org.keycloak.keycloak-model-infinispan@18.0.0.redhat-00002](mailto:org.keycloak.keycloak-model-infinispan@18.0.0.redhat-00002)//org.keycloak.models.cache.infinispan.RealmCacheSession.getRealm(RealmCacheSession.java:414)
(...)
```

https://github.com/keycloak/keycloak/blob/ef47eee2dda29a0f08187ae67970323c28947f11/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedRealm.java#L266### 

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

We need to prevent `NullPointerException` and log in [1] and log some information, like Realm name etc.

[1] https://github.com/keycloak/keycloak/blob/ef47eee2dda29a0f08187ae67970323c28947f11/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedRealm.java#L266### 

### Actual behavior

We get the following message when the default role is null:

```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-3) Uncaught server error: java.lang.NullPointerException
at [org.keycloak.keycloak-model-infinispan@18.0.0.redhat-00002](mailto:org.keycloak.keycloak-model-infinispan@18.0.0.redhat-00002)//org.keycloak.models.cache.infinispan.entities.CachedRealm.<init>(CachedRealm.java:266)
at [org.keycloak.keycloak-model-infinispan@18.0.0.redhat-00002](mailto:org.keycloak.keycloak-model-infinispan@18.0.0.redhat-00002)//org.keycloak.models.cache.infinispan.RealmCacheSession.getRealm(RealmCacheSession.java:414)
(...)
```

### How to Reproduce?

For example, remove the default role from the database.

### Anything else?

Maybe we need to review the `CachedRealm.java` class and check for possible other points that could throw NPW

### PR DESCRIPTION
**Pull request by pedro-hos**
closes: #33817

### CODE REVIEW

**Comment by jonkoops** [comment]
Thanks for the PR @pedro-hos! Could I ask you to [sign off](https://github.com/keycloak/keycloak/pull/33909/checks?check_run_id=31516315995) on your commit?

**Comment by pedro-hos** [comment]
> Thanks for the PR @pedro-hos! Could I ask you to [sign off](https://github.com/keycloak/keycloak/pull/33909/checks?check_run_id=31516315995) on your commit?

Thanks, I have just sign off. Do you usually have an `alias` to apply the `git commit -s` instead of adding `Signed-off-by: Author Name <authoremail@example.com>` in every commit? What is the best way to automatically add this?

**Comment by jonkoops** [comment]
I myself add `-s` (--signoff`) to every commit I make. To my knowledge there is no way to do this automatically. The reason for this is that it forces the author of the commit to add a formal declaration, stating explicitly they agree to the license under which they are contributing their code.

You could probably automate this with an alias, or with a script or something, but I don't believe it is possible with as simple Git config.

**Review by ahus1 — APPROVED** [review]
Thank you for this contribution!

**Comment by jonkoops** [comment]
Backport for 26 up under #33928

**Pull request merged**
