### PR TITLE
Fixes #KEYCLOAK-7751 Auth welcome page

### PR DESCRIPTION
**Pull request by junezhang**
This PR is aim to update HTML code for the new Auth welcome page.
The JIRA task is here: https://issues.jboss.org/browse/KEYCLOAK-7751

@ssilvert, have finished the html code for the new auth welcome. 
Here, I have one question, how to link the PatternFly css in auth welcome page, currently, I haven't used any patternfly css code. but I think if we can use PatternFly code, it will be better.

This PR is working in progress, next step as following:

- Add the PatternFly Css code
- Add the responsive code

### CODE REVIEW

**Comment by ssilvert** [comment]
@junezhang 

Patternfly CSS lives in /resources/theme/keycloak/common/resources/lib/patternfly

You will need to add a theme.properties an import common/keycloak.  It will be similar to the theme.properties in  /resources/theme/keycloak/admin.  See Keycloak docs for details on using theme.properties.

Unfortunately, we can't merge this PR until it is fully functional because it replaces an existing page.  Need to talk to @stianst about the time line for this.

**Comment by stianst** [comment]
We've forgotten about RH-SSO here. We also need a similar look and feel for the RH-SSO theme.

I've added support for theme.properties as well as made RH-SSO welcome theme load index.ftl from Keycloak theme here https://github.com/stianst/keycloak/tree/welcome

**Comment by junezhang** [comment]
Based on the new design and including PatternFly CSS code, I refine my previous HTML code and the screenshot as following:

Laptop with HiDPi Screen
screen shot 2018-08-14 at 6 03 44 pm

screen shot 2018-08-14 at 6 02 54 pm

screen shot 2018-08-14 at 5 59 40 pm

Responsive Design
screen shot 2018-08-14 at 6 04 19 pm

**Comment by junezhang** [comment]
@ssilvert @stianst 
Based on the new design and RH-SSO requirement, I've done my code refinement.
Screenshots as the following:

KeyCloak Welcome Page




RH-SSO Welcome Page




Please help to review this PR.

Thanks

**Comment by junezhang** [comment]
@stianst Hello, Stian, The WelcomeResource.java file has one error, would you mind to have a look at it, please? Thanks.

**Comment by stianst** [comment]
Fixed the build issue

**Comment by stianst** [comment]
* Line around boxes are a bit to subtle with the white background. I would make the drop-shadow a bit stronger.
* Icon and title should be on the same line. This applies to icon/Admin Console and icon/Documentation
* To large top margin within boxes. Keycloak Project / Maling list / Report an issue boxes have a larger margin at the top than bottom/left/right
* Admin Console / Documentation boxes are very big compared to the content. This looks odd, especially on RH-SSO view
* JBoss Community logo doesn't have transparent background so displays white box around it
* On the create user form there isn't enough spaces between "Please create an initial.." and the "Username" label. It looks to squashed. Same applies to the create button. The create button is also not very nice and has a slightly strange style. I do go for a more traditional square button that matches the buttons in the admin console.
* I'd keep the "Icon/Administration Console" header there when the create user form is displayed. Also, I'd move the "User created notification" below the "Icon/Administrion Console" header as it looks out of place when it is above the header, but doesn't have any frame/notification styling.

**Comment by junezhang** [comment]
@stianst Thanks for checking the style stuff. But all the code is based on the invision design.  yes, we still can make it to be better. I have some comments left inline:

> Admin Console / Documentation boxes are very big compared to the content. This looks odd, especially on RH-SSO view

Because we have a form in the Admin Console, we need user to create a user in a form, so if we look at the form, then we won't find it is bigger.

> JBoss Community logo doesn't have transparent background so displays white box around it

Could I know your browser and version, in my browser, it is transparent.
screen shot 2018-08-22 at 6 49 47 pm

> On the create user form there isn't enough spaces between "Please create an initial.." and the "Username" label. It looks to squashed. Same applies to the create button. The create button is also not very nice and has a slightly strange style. I do go for a more traditional square button that matches the buttons in the admin console.

The form screenshot is following, is it different with yours?
screen shot 2018-08-22 at 6 51 51 pm
And the new create button is same with PatternFly 4. It is a round button.

**Comment by stianst** [comment]
I appreciate that it is based on the design, but I didn't spot those things before. It looks OK now, but I think with a little bit of polish it will look great.

* JBoss Community logo is working for me now. Must have had an old version cached or something.
* The screenshot looks like mine. [started.] and [Username] are too close together. Same with Password confirmation and Create button
* I really don't like that button. It looks very dated, but hey if it's PatternFly 4 let's stick with it
* My other comments still apply

**Comment by junezhang** [comment]
@stianst I did a update to the style issues as following:

1. update the drop shadow a bit stronger
2. update the margin-top to the Keycloak Project / Maling list / Report an issue boxes
3. update to add large space to the user create form, as well as bold the "Please create an initial ...", let user easily know this is two part things.
4. update the notification styling
5, update the create button to current PF3 normal button, keep consistent with the Admin Console buttons.

two things not updating that I want to discuss with you:

> Icon and title should be on the same line. This applies to icon/Admin Console and icon/Documentation

Why Icon/Admin Console and Icon/Documentation are two rows? I think this is one style design from visual design perspective, the box height is larger than the KeyCloak Project/Mailing List/Report an issue.

> I'd keep the "Icon/Administration Console" header there when the create user form is displayed. 

This is what we thought as before, if the user haven't been created, is there any user cases for user to click the link of Administration Console.

**Comment by stianst** [comment]
Changes look good. For two remaining:

* The create user form lacks a heading/context to tell the user what type of user they are creating. Simply leaving the "Administration Console" there will give them this information. There's not a use-case for clicking it until a user has been created, but I don't think it's a big problem that it's there even though they can't actually log in at this point. I find it worse that there's nothing there to tell the user that the create user form is about creating an admin user.

* I appreciate trying to fill the space, but it just looks odd to have the icon on one line and the heading on another.

**Comment by junezhang** [comment]
@stianst Have update the style issues, please have a review.

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
NEW PR with conflicts resolved https://github.com/keycloak/keycloak/pull/5527

**Comment by stianst** [comment]
Merged here https://github.com/keycloak/keycloak/pull/5527

**Pull request closed without merging**
