### PR TITLE
Rename keycloak-wf9-subsystem directory to keycloak-wildfly-subsystem to match t

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by stianst** [comment]
Can you create a JIRA for this please?

**Comment by ppalaga** [comment]
@stianst No, I'd prefer not creating a Jira for such an apparent fix. If you really need a Jira number I can reword with "KEYCLOAK-2099 fixup: "

**Comment by stianst** [comment]
All commits should have an associated JIRA issue. This is important so we can track what has been changed. Dangling commits like this are very hard to identify later on. It also helps a lot when reviewing PRs if there's an associated JIRA with a description of what was wrong.

You should either create a new JIRA or re-open KEYCLOAK-2099. The commit message should have had the JIRA issue included as that would automatically link it to JIRA. This is extremely helpful when we try to identify what was done for a particular issue.

**Comment by ppalaga** [comment]
KEYCLOAK-2099 reopened and the commit reworded.

**Comment by stianst** [comment]
Great, thanks

**Comment by ppalaga** [comment]
@stianst Is this good to merge now?

**Comment by stianst** [comment]
Yep, I'll merge it soon and add to 1.7.x branch as well

**Pull request merged**
