### PR TITLE
GH Issue #11888 - Bump Elytron version

### PR DESCRIPTION
**Pull request by trixpan**

### CODE REVIEW

**Comment by trixpan** [comment]
@abstractj can you please review this one? Minor version bump to address 3PP vulnerabilities.

**Comment by trixpan** [comment]
On a separate note. A great example of stuff dependabot could be doing for the community. Maybe it is time to extend dependabot beyond its current scope?

**Comment by abstractj** [comment]
@trixpan thanks for bringing it to our attention, and unfortunately, we need to wait until the next upgrade of Quarkus and WildFly. 

Keycloak legacy is built on top of WildFly 26.1.1.Final, while the current Keycloak is based on Quarkus 2.7.6.Final, we try to keep those dependencies aligned with WildFly and Quarkus as much as we can. And we have been working to improve it. You can find the whole discussion here: https://github.com/keycloak/keycloak/pull/12211#issuecomment-1148718886

Now switching to your suggestion. We already have [dependabot, Snyk, Trivy and CodeQL](https://github.com/keycloak/keycloak/tree/main/.github) configured for our project, the reason we cannot perform automatic upgrades today is mentioned [here](https://github.com/keycloak/keycloak/pull/12211#issuecomment-1148718886). 

cc @stianst @pedroigor

**Comment by pedroigor** [comment]
@abstractj @trixpan IIRC, `wildfly-elytron` was added to the distribution to make it possible to use remote stores (hotrod) when doing legacy. See https://github.com/keycloak/keycloak/pull/10048.

Looks like ISPN 13.0.9 (the version we are using) is using a lower version too. See https://github.com/infinispan/infinispan/blob/13.0.9.Final/build-configuration/pom.xml#L182.

As we don't have cross-dc tests enabled to the distribution, is hard to say if the upgrade works. I would say it is, but we need to double-check. See https://github.com/keycloak/keycloak/issues/9831.

**Comment by trixpan** [comment]
@pedroigor interesting. 

So if I understand correctly:

1. We use [infinisipan 12.1.7.Final](https://github.com/keycloak/keycloak/blob/a82f08fdb2842cc0e1782b6d9a3d420ea0eaf143/pom.xml#L95) in keycloak 
2. That happens to use [wildfly-elytron 1.15.1.Final ](https://github.com/infinispan/infinispan/blob/12.1.7.Final/build-configuration/pom.xml#L186)
3. despite we using [wildfly-elitron 1.18.3.Final](https://github.com/keycloak/keycloak/blob/a82f08fdb2842cc0e1782b6d9a3d420ea0eaf143/pom.xml#L122)

Good news is: The resulting packaged version seems to be the one specified by us.

The not so good news is: Gosh... One gotta love dependency management.

:-)

**Comment by pedroigor** [comment]
> @pedroigor interesting.
> 1. We use [infinisipan 12.1.7.Final](https://github.com/keycloak/keycloak/blob/a82f08fdb2842cc0e1782b6d9a3d420ea0eaf143/pom.xml#L95) in keycloak

The distribution is using `13.0.9.Final`. 

The legacy distribution is ahead of time and uses `13.0.10`.

> The not so good news is: Gosh... One gotta love dependency management.

Definitely :)

**Comment by abstractj** [comment]
@trixpan @pedroigor the WildFly Elytron project resolved the issue on their 1.19.1 release, moving it to 1.20.0 is a major bump and that also mean getting out of sync with the WildFly distribution. In order to merge this PR the following steps are required from my perspective:

1. Update Keycloak to use WildFly 26.1.2.Final, which contains the fixed version of Elytron
2. Change the version of Elytron to 1.19.1.Final
3. Make sure that all our dependencies in the legacy distribution are in sync

@pedroigor it does make sense? If yes, I can take over this PR keeping the authorship.

**Comment by abstractj** [comment]
@trixpan those changes are related with the WildFly distribution, which will be removed in the upcoming release. See: https://github.com/keycloak/keycloak-documentation/pull/1708/files

The issues with Elytron on Quarkus distribution were solved by https://github.com/keycloak/keycloak/pull/15034

Thanks for submitting those changes and bringing to our attention those issues.

**Pull request closed without merging**
