### PR TITLE
KEYCLOAK-16844 Create an index to support offline sessions loading

### PR DESCRIPTION
**Pull request by Michito-Okai**
Add the following index
CREATE INDEX IDX_OFFLINE_USS_PRELOAD ON offline_user_session(offline_flag, created_on, user_session_id);
https://issues.redhat.com/browse/KEYCLOAK-11019

### CODE REVIEW

**Review by vramik — CHANGES_REQUESTED** [review]
Thank you @Michito-Okai very much for the PR. It looks good to me. 

From conversation on https://issues.redhat.com/browse/KEYCLOAK-11019 it seems that creating the index itself doesn't solve the issue completely. Therefor I've created a sub-task for that issue. There is a link: https://issues.redhat.com/browse/KEYCLOAK-16844. Could you please change commit message, PR name and id of changeset to the corresponding jira issue? Thank you

https://keycloak-jenkins.com/job/universal-test-pipeline-server/2504
https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/2027/

**Comment by Michito-Okai** [comment]
@vramik @hmlnarik 
Thank you very much for confirming this PR and creating a sub-task. I changed commit message, PR name and id of changeset accodrding to your comment. Could you confirm those changes, please?

**Review by vramik — APPROVED** [review]
Thanks @Michito-Okai!

**Review by hmlnarik — APPROVED** [review]
@Michito-Okai Thank you for the contribution!

Approving based on @vramik 's approval

**Pull request merged**
