### PR TITLE
Incorrect error messages used during failed OIDC client authentication

### LINKED ISSUE #12162: Incorrect error messages used during failed OIDC client authentication
### Describe the bug

OIDC client authentication uses different error messages in the case when client does not exists and/or in the case when client is disabled and/or in the case when client is enabled, but bad client credentials are used. This allows "client enumeration" and also error messages returned are not 100% aligned with the OAuth2/OIDC specifications, so will be good to fix this IMO .

### Current behaviour

I am sending this request:
```
curl -d "client_id=account1" -d client_secret=wDVOYAWe8R0LxkVGe1MOI5PcuVyWlZ14 -d "username=admin" -d "password=admin" -d "grant_type=password" "http://localhost:8081/auth/realms/master/protocol/openid-connect/token"
```

1. In case the client `account1` does not exists, the response is:
```
{"error":"invalid_client","error_description":"Invalid client credentials"}
```

2. In case the client `account1` exists, but the client secret is incorrect, the response is:
```
{"error":"unauthorized_client","error_description":"Invalid client secret"}
```

3. In case the client `account1` exists, but is disabled, the response is:
```
{"error":"unauthorized_client","error_description":"Invalid client credentials"}
```

### OAuth2 specification

I've checked the OAuth2 specification https://datatracker.ietf.org/doc/html/rfc6749#section-5.2 . According to the specification, the error "unauthorized_client" should be returned just when client is not authorized for the specified grant type. It should be never returned when client authentication failed (which is what we are doing right now).

### Fix suggestion

I suggest to change the logic like this:

- client_id parameter missing: Return error "invalid_request" . This is ok per OAuth2 specification. Same applies when request is otherwise malformed (EG. Contains multiple client authentication methods)

For all the other cases below, we can return the generic error to hide the reason:
```
{"error":"invalid_client","error_description":"Invalid client or Invalid client credentials"} 
 ```

However we should differentiate the cases below in the error event, which is thrown to event SPI. The cases are:

- Case when "client_id" points to non-existing client
- Case when "client_secret" is missing as parameter and "Authorization" header is missing as well
- Case when client exists, but is disabled
- Case when client secret is invalid
- Case when client uses different client authentication than the default "Client secret", but invalid client credentials are provided

When refactoring this, we should check that the "framework", which triggers client authentication, checks that client is enabled or not. Right now, I see that there is check in the client authenticator itself - https://github.com/keycloak/keycloak/blob/18.0.0/services/src/main/java/org/keycloak/authentication/authenticators/client/ClientIdAndSecretAuthenticator.java#L113-L115 , which is likely not very great as in the case when there is alternative client authentication method and the "Client Authenticator implementation" forget to check the client enablement status, it might be possible to authenticate with disabled client, which is incorrect.

### Version

18.0.0

### PR DESCRIPTION
**Pull request by pedro-hos**
closes #12162

### CODE REVIEW

**Review by mposolda — CHANGES_REQUESTED** [review]
@pedro-hos Sorry for the late reply. I think your fix goes in the right direction.

However I think that error returned should be `invalid_client` instead of `unauthorized_client` for all the mentioned cases. This is my understanding per the specification https://datatracker.ietf.org/doc/html/rfc6749#section-5.2 . The error `unauthorized_client` seems to be dedicated for the case when client is not authorized for the particular grant type (For example when you are sending `response_type=code`, but client is supposed to support only implicit flow. So a bit different case than failed client authentication).

Also I think it will be good to make sure that HTTP status 401 (UNAUTHORIZED) is returned in all those cases (it seems that you're still returning status 400 (BAD_REQUEST) in some places in this PR).

This is what I've proposed originally in the summary https://github.com/keycloak/keycloak/issues/12162 . Does it work to you?

**Comment by marcelomrwin** [comment]
I'll take a look on this

**Comment by pedro-hos** [comment]
Thanks @marcelomrwin 
I am sorry @mposolda I didn't have a chance to take a look at the suggested changes =/.

**Comment by mposolda** [comment]
@pedro-hos I am closing this PR as it was replaced by the PR https://github.com/keycloak/keycloak/pull/14656, which is merged in Keycloak main and will be available in Keycloak 20. That PR contains your changes and some more stuff according to the PR review. Thanks for starting this initial PR! It was good effort even if you did not manage to finish it.

**Pull request closed without merging**
