### PR TITLE
Throw meaningful error message for invalid session codes

### PR DESCRIPTION
**Pull request by patrickbadleyupstart**
Our keycloak instance regularly logs error messages like the following:
```
"message":{"message":"unexpectedErrorHandlingRequestMessage"},
"error":{"type":"javax.ws.rs.WebApplicationException","message":"HTTP 200 OK","stack_trace":"javax.ws.rs.WebApplicationException: HTTP 200 OK\n\tat org.keycloak.services.resources.IdentityBrokerService.parseSessionCode(IdentityBrokerService.java:1083)\n\tat org.keycloak.services.resources.IdentityBrokerService.performLogin(IdentityBrokerService.java:375)...
```

These messages are a bit confusing as the error details describe a 200: OK response which typically means success.  I believe this was a simple miss on a previous refactor of this code that used to redirect to an error screen, but now throws an exception to be handled later.  See this [PR](https://github.com/keycloak/keycloak/commit/41dc94fead4c20560e0dd96c3efbd7bd10a484b6#diff-e44efb607cb8cb833e99677c01e7fc10d67afc6ee54ce4faf06a01f5acaf50e7L1074) for when I believe this issue was introduced.

This PR simply changes the content of the exception that is thrown to contain a somewhat more meaningful error message.

### CODE REVIEW

**Comment by mposolda** [comment]
@patrickbadleyupstart Just a note that things like `code`, `clientId` and `tabId` are not added on purpose to the HTTP response. Those can contain values, which can be manually added into URL and hence can cause various issues like XSS attacks.

I think we can consider changing the status 200 to something different for this case. But it will be good if you first create GH issue with the description of the problem (including what is the HTTP response returning 200 and how it can happened etc). Also see this for the details: https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md

**Comment by patrickbadleyupstart** [comment]
Thank you, @mposolda .  There is already an open issue: https://github.com/keycloak/keycloak/issues/9187#.  My understanding is that we are creating the 200 OK response by rendering a generic Error page and putting that response in the exception:
```
            Response staleCodeError = redirectToErrorPage(Response.Status.BAD_REQUEST, Messages.INVALID_REQUEST);
            throw new WebApplicationException(staleCodeError);
```

**Comment by mposolda** [comment]
> Thank you, @mposolda . There is already an open issue: #9187. My understanding is that we are creating the 200 OK response by rendering a generic Error page and putting that response in the exception:
> 
> ```
>             Response staleCodeError = redirectToErrorPage(Response.Status.BAD_REQUEST, Messages.INVALID_REQUEST);
>             throw new WebApplicationException(staleCodeError);
> ```

I see. The exception is likely not created correctly. However I appreciate if you remove things like `code` , `tabId` etc values from the error message and possibly keep just `Invalid request. Authorization code, clientId or tabId was null.` . Also will be good to keep the logging message for this purpose (unless it is logged already somewhere else?) .

Also automated test will be nice if possible. And please see https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md (you can also take a look at other commit messages and other PRs for the inspiration how the PR should ideally look like).

**Comment by mposolda** [comment]
I am closing the PR due the no response to my last comment. Feel free to open new PR, but in that case please send the PR with the commit according to https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md and address my previous comments.

**Pull request closed without merging**
