### PR TITLE
Add Traditional Chinese support

### PR DESCRIPTION
**Pull request by allen0099**
Added Traditional Chinese language support.

### CODE REVIEW

**Comment by jonkoops** [comment]
Thanks you for the PR! Could you [sign-off](https://github.com/keycloak/keycloak/pull/28721/checks?check_run_id=23819947160) on your commit? @xianli123 could I ask you to review this for us?

**Comment by allen0099** [comment]
Hi @jonkoops

I rebase the commit and signed-off the commit, please check.

**Comment by xianli123** [comment]
I will take a look. Thanks @allen0099 @jonkoops .

**Comment by xianli123** [comment]
Hi @jonkoops I checked the translation, and it looks fine. From my point of view, it looks good.
One concern is that the translation is not the fully same as in Mandarin. If we have the opportunity, maybe we can invite people from other Chinese-speaking areas to help take a look. If we don't have the chance to do that, we can approve it.

**Review by xianli123 — APPROVED** [review]
Looks good to me.

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
Thanks @allen0099 !

**Pull request merged**
