### PR TITLE
Use the map storage's updated flag for Hibernate dirty checking

### LINKED ISSUE #11766: Leverage the updated flag in JPA Map storage for Hibernate checking checking
### Description

During performance testing, the results showed a lot of dirty checking for entities. 

While the checking can be improved (see #11765), this can also be avoided by using the leveraging the updated flag that is present in the store. 

### Discussion

_No response_

### Motivation

This has been showing in in performance tests for the new store.

### Details

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
This is overwriting the isUpdated() method on entities as the modification information is available from the metadata field. It doesn't call super.isUpdated() as that would load the lazy collections.
For nested entities (like the components in realms) are ignored.

Closes #11766

### CODE REVIEW

**Comment by ahus1** [comment]
As this changes the semantics of isUpdated() as for JpaRealmEntity it is now ignoring JpaComponentEntity and JpaRealmAttributeEntity, I'd like to discuss this and also if this should be moved to a different interface with isUpdatedJpa() and clearUpdatedFlagJpa()

**Comment by ahus1** [comment]
Alternative ideas I explored: I tried a fetch entities "read only", but then found no way to switch them to non-read-only later. Re-fetching an entity will retrieve it again read-only. Fetching entities lazily will always fetch them with the session's default, thereby non-read-only. 

I briefly though about two entity managers, one for read-only, and one for read-write, and the delegate would then switch between the two as necessary. Compared with the implementation here, it seems to be a lot more complex.

**Comment by ahus1** [comment]
Questions: 
* Is the Hibernate API stable? -> look into Hibernate 6, ask upstream.
* How is the performance impact

**Comment by ahus1** [comment]
@hmlnarik - the numbers are in for the performance comparison are in, see the previous comment for the details. In this scenario it will result in 2% less CPU usage. 

Please let me know if you think this is worth following up on. 

cc: @vramik

**Comment by vramik** [comment]
> @hmlnarik - the numbers are in for the performance comparison are in, see the previous comment for the details. In this scenario it will result in 2% less CPU usage.
> 
> Please let me know if you think this is worth following up on.
> 
> cc: @vramik

I assume the result would be even more significant with higher number of objects, right? If I understand it correctly when there are many objects in persistence context hibernate needs to check them all for dirtiness and it seems to me the proposed change should improve it. Just my 2 cents.

**Comment by ahus1** [comment]
Looking at the numbers above, this didn't show a big enough performance improvement compared to the complexity it adds. 

We'll revisit this once more performance metrics are in, for example for retrieving large collections via the admin interface.

**Pull request closed without merging**
