### PR TITLE
KEYCLOAK-15386 Some icons are not displayed properly

### PR DESCRIPTION
**Pull request by Pepo48**
* pficon.woff/woff2 - updated PatternFly font resource
* pficon.css - css that contains @font-face rule
Signed-off-by: Peter Zaoral <pzaoral@redhat.com>

@mabartos PTAL once you got a chance. You've requested updated Openshift and Microsoft icons so far. Both should be available:
* for OpenShift icon use `pf-icon-openshift` icon name,
* for Microsoft icon use `fa fa-windows` prefix and icon name respectively.

(cc: @ssilvert)

### CODE REVIEW

**Review by mabartos — DISMISSED** [review]
@Pepo48 LGTM. The `openshift-icon` is displayed. Thanks!

**Comment by Pepo48** [comment]
@mabartos Thanks for the review!

I have one more thing to discuss - I found out that a tile component needs to be added manually as well. As an important part of [KEYCLOAK-14138](https://issues.redhat.com/browse/KEYCLOAK-14138) I will definitely need it. Just to remind you It's still [a beta component ](https://www.patternfly.org/v4/components/tile/html).

My question is - should I add the necessary css directly into the `pficon.css` (and eventually rename it since it won't be just an icon related resource anymore) or should I place it into a separate file in a separate folder (e.g. `tile.css`). The second approach necessary means that there will be just another path  in `stylesCommon` (in `theme.properties`) and I will also send a separate PR for it in that case.

One way or another, right after the PF4 transition phase is finished, those additional resources will be deleted anyway. 
Let me know. Thanks!

Cc: @ssilvert @vmuzikar

**Comment by mabartos** [comment]
@Pepo48 Please, could you rebase that? It should be merged ASAP to provide Openshift icon.

**Comment by Pepo48** [comment]
> @Pepo48 Please, could you rebase that? It should be merged ASAP to provide Openshift icon.

Rebased.

**Review by mabartos — APPROVED** [review]
Thanks @Pepo48 !

**Review by mposolda — APPROVED** [review]

**Pull request merged**
