### PR TITLE
KEYCLOAK-10075 fix drop all tables for postgres and mssql

### PR DESCRIPTION
**Pull request by pskopek**
https://issues.jboss.org/browse/KEYCLOAK-10075
Due to bug in liquibase we need to have spacial case for postgres and mssql.

### CODE REVIEW

**Review by vramik — CHANGES_REQUESTED** [review]
@pskopek thank you for the PR, unfortunately the issue is not resolved yet: https://keycloak-jenkins.com/job/test-keycloak-jpa/DB=postgresql101,jdk=local_openjdk8,label_exp=rhel7_large/111/consoleFull

**Comment by pskopek** [comment]
https://keycloak-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/JPA/job/test-keycloak-jpa/119/

**Comment by pskopek** [comment]
https://keycloak-jenkins.com/view/JPA/job/test-keycloak-jpa/119/

**Review by vramik — APPROVED** [review]
Thanks @pskopek, lgtm now

**Review by mposolda — APPROVED** [review]
@pskopek Thanks for the fix!

**Pull request merged**
