### PR TITLE
Fix unexpected expiration when import offline client session

### LINKED ISSUE #23397: The "invalid_grant" error occurs again when loading the offline client session with an early creation time.
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

infinispan

#### Background
The origin issue was https://github.com/keycloak/keycloak/issues/9959 and wax fixed by https://github.com/keycloak/keycloak/pull/17490.

Regarding to the loading client session, I also proposed a fix https://github.com/keycloak/keycloak/pull/8671 long time ago.

From that time I made those customization in our production, and everything works well.

Recently, We update our Keycloak version to `22.0.3` and replace the customization with that fix.

And the `invaid_grant` error occurs again.

I compared the code between my customization  and  keycloak implementation, and find that,
there is `checkExpiration` added in the `importClientSession` method

https://github.com/keycloak/keycloak/blob/main/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java#L1072-L1080

#### Issue
When refreshing token, there was error `invalid_grant` and error description is `Session doesn't have required client`
The offline client session fails to load properly, while the offline user session loads successfully.

### Version

22.0.3

### Expected behavior

Offline client session loads successfully.

### Actual behavior

When refreshing token, there was error `invalid_grant` and error description is `Session doesn't have required client`

### How to Reproduce?

The steps are same as the https://github.com/keycloak/keycloak/issues/9959

And, the `timestamp` for the offline client session in the database should be a time **before the offline session idle time** or offline max session time (if set)

### Anything else?

I have identified the problem and will submit a PR later.

### PR DESCRIPTION
**Pull request by lexcao**
Closes #23397

### CODE REVIEW

**Comment by martin-kanis** [comment]
@lexcao Thanks for the PR. How did you end up in situation where you have offline client sessions created **before** the corresponding user session was created? Looking into the code, you can create a (offline) client session only if you before created a (offline) user session.

**Comment by lexcao** [comment]
Hi @martin-kanis 

> How did you end up in situation where you have offline client sessions created before the corresponding user session was created?

The background should set offline-session cache limitation, which there could be a cache state with user-session in cache but client-session not in cache.

You can refer to the original issue from #9959

For example, 
let's assume we have set up the cache limitation for `offlineSessions` with 2 and for `offlineClientSessions` with 1.

```
// Assuming the session idle time is 10 mins

Timeline: 0
Operation: create offline session A: 
Cache state:
  - offlineSession: A
  - offlineClientSession: A

Operation: create offline session B:
 Cache state:
  - offlineSession: A, B
  - offlineClientSession: B
---
Timeline: 1 (9 mins later)
Operation: refresh token for offline session A: success
Cache state:
  - offlineSession: A, B
  - offlineClientSession: A

Operation: refresh token for offline session B: success
 Cache state:
  - offlineSession: A, B
  - offlineClientSession: B

---
Timeline: 2 (11 mins later)
Operation: refresh token for offline session A: failure
Cache state:
  - offlineSession: A, B
  - offlineClientSession: A
But invalid_grant occurs
```

In the above example, both sessions A and B can be refreshed successfully for the `checkExpiration` is valid when the `timestamp` of the `offlientClientSession` is valid in 10 mins at `timeline 1`.
Then there could be a failure at `timeline 2` because the `timestamp` of the `offlientClientSession` is invalid when checking expiration.

--
I am going to add this code because there is the same assignment, which updates the timestamp to the same value as userSession, in `importUserSessions` while `importClientSession` does not.

https://github.com/keycloak/keycloak/blob/a65af2d25486e323c1e5ef415f65ceb8dbdc7e79/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java#L871-L872

I think there should be the same timestamp when loading the user session and loading the client session.

**Comment by martin-kanis** [comment]
It wasn't super clear to me, why we want to use `lastSessionRefresh` from offline user session for a timestamp of offline client session when importing from DB. Also we store timestamp of offline client session in DB. Then, I noticed, we update `lastSessionRefresh` only for offline user sessions via `AbstractLastSessionRefreshStore` . There is no such mechanism for offline client sessions, which means timestamp of an offline client sessions can be outdated in DB after some time and refreshes. @mposolda did I get it right?

If my understanding is correct, then I agree with the proposed changes. However, it would be nicer and more readable to have mechanism for updating `timestamp` of offline client sessions. Maybe that would have a performance impact, but in any case it can be evaluated in future.

**Review by martin-kanis — APPROVED** [review]
@lexcao Thanks for the PR!

**Review by ahus1 — APPROVED** [review]

**Pull request merged**
