### PR TITLE
Improved Usability for Admin Console

### PR DESCRIPTION
**Pull request by hypery2k**
see https://jira.jboss.org/browse/KEYCLOAK-10018

Now for users area, too

### CODE REVIEW

**Comment by ssilvert** [comment]
Hi @hypery2k. Thanks for the new contribution.  We need an open JIRA to go with the open PR. Can you create a new JIRA and link to the old one?

**Comment by hypery2k** [comment]
sure, created https://issues.jboss.org/browse/KEYCLOAK-10704

**Comment by ssilvert** [comment]
I tried your code and see a problem. 

If I go to Users --> admin --> Groups, the available groups is empty.

**Comment by hypery2k** [comment]
oh really, tried it and works for me. Maybe browser-caching on my side. Will re-check

**Comment by hypery2k** [comment]
found the error, is resolved now and working again

**Comment by hypery2k** [comment]
i would also suggest changing the label from name to path which makes it easier to use with nested groups.
Currently implementation would like this:
image

What do you think?
My changes would result in this:
image

**Comment by ssilvert** [comment]
> i would also suggest changing the label from name to path which makes it easier to use with nested groups.
> Currently implementation would like this:
> image
> 
> What do you think?
> My changes would result in this:
> image

I like that idea.  Does the code in this PR implement that?  If not, go ahead and add it.

**Comment by hypery2k** [comment]
added the needed change to this PR

**Comment by ssilvert** [comment]
I found a small bug.  In the Available Groups, close a parent group.  Then add that group.  The icon will change from a folder to a document.  That makes it look as if you can no longer expand it and open the folder.

**Comment by ssilvert** [comment]
> I found a small bug. In the Available Groups, close a parent group. Then add that group. The icon will change from a folder to a document. That makes it look as if you can no longer expand it and open the folder.

@hypery2k Did you see my previous comment?

**Comment by hypery2k** [comment]
sure, will try to fix that next week ;)

**Comment by hypery2k** [comment]
take a look at it and the error is already in the current code base, it's a bug in the angular-treeview 3rd party module

**Review by ssilvert — APPROVED** [review]
I'm going to go ahead and approve this and merge it.  We are at the end of the line with the angular-tree component.  So we can't fix that minor bug.

Thanks for the contribution and all your work on this.

**Pull request merged**
