### PR TITLE
Remove Tomcat and Jetty servers from the test suite

### LINKED ISSUE #29089: Remove redundant servers from the testsuiite
### Description

Remove the tomcat and jetty servers from the test suite once the adapters are removed.

### PR DESCRIPTION
**Pull request by douglaspalmer**
Closes https://github.com/keycloak/keycloak/issues/29089

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]
LGTM

**Review by mposolda — COMMENTED** [review]
@douglaspalmer @miquelsi Thanks, I am approving as from my point of view, it should be good. But before merging, I would rather ask also @miquelsi (or someone from the QA team) for the review.

@miquelsi This PR does not remove any EAP, Fuse or SpringBoot bits from the testsuite, but just tomcat and Jetty stuff. Is it ok to merge this one?

**Review by mposolda — APPROVED** [review]

**Comment by miquelsi** [comment]
For Jetty I'm totally fine with removing it, we don't test it for long now.

However, we're still using Tomcat for testing the Springboot adapters. Since the plan for testing those adapters is still being discussed, we might want to keep it still. Although we can still test those adapters with Undertow. If this option is acceptable, I'm fine removing Tomcat too.

WDYT, @mposolda?

**Comment by mposolda** [comment]
@miquelsi Yes, I think it is. Also we are going to test SpringBoot with the RH-SSO testsuite as discussed in the meetings, so we should be ok with removing tomcat and jetty.

**Review by mposolda — APPROVED** [review]

**Pull request merged**
