### PR TITLE
KEYCLOAK-14954 Enable replacement of ${client_id} placeholder in user client role prefix

### PR DESCRIPTION
**Pull request by Playmountain**
The user client role mapper, when presenting all client roles associated with a user and using the default token claim name (resource_access.${client_id}.roles), produces a structure as seen below

"resource_access": {
"test2": {
"roles": [
"muppet"
]
},
"test": {
"roles": [
"muppet"
]
},
"account": {
"roles": [
"manage-account",
"manage-account-links",
"view-profile"
]
}
}

Unfortunately, products exist which lack the capability to process structures more complex than a list. Structure-wise, the user client role mapper can be configured to provide the client roles as a list, so that is not a problem. The problem is that there does not seem to be a way of differentiating roles from different clients.

"roles": [
"muppet",
"muppet",
"manage-account",
"manage-account-links",
"view-profile"
]

Currently only the token claim name is able to replace ${client_id} placeholder with the actual client_id.

I suggest allowing the client role prefix to be able to replace the ${client_id} placeholder. So, providing a client role prefix of "${client_id}:::" would produce the following structure

"roles": [
"test2:::muppet",
"test:::muppet",
"account:::view-profile",
"account:::manage-account",
"account:::manage-account-links"
]

### CODE REVIEW

**Comment by hmlnarik** [comment]
Thank you for the PR. There has been no activity on this PR for considerable amount of time, and thus is being closed. Feel free to reopen the PR if you still feel it is valid.

**Comment by luisalves00** [comment]
Can this be reopened? Maybe make next keycloak release?

**Comment by ricshell** [comment]
It would be good to have this merged or, if not, some hints on how to do it differently.

**Comment by jonkoops** [comment]
Feel free to open up a new PR if you feel like this fix is still relevant. Please also make sure to log a new issue to go along with it.

**Comment by Playmountain** [comment]
Pr provided in #24823

**Pull request closed without merging**
