### PR TITLE
Update maintainers

### PR DESCRIPTION
**Pull request by hmlnarik**

### CODE REVIEW

**Review by abstractj — APPROVED** [review]

**Review by vmuzikar — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]

**Review by mhajas — APPROVED** [review]

**Review by tnorimat — APPROVED** [review]

**Review by jonkoops — APPROVED** [review]

**Review by mposolda — APPROVED** [review]

**Review by ssilvert — APPROVED** [review]
Thanks Hynek!

**Comment by thomasdarimont** [comment]
Thanks Hynek for your work!

**Review by thomasdarimont — APPROVED** [review]

**Comment by stianst** [comment]
Thanks Hynek for all the great work you have done for Keycloak, and I wish you all the best in your future endeavours.

**Comment by stianst** [comment]
PR to update CNCF maintainers list: https://github.com/cncf/foundation/pull/841

**Review by stianst — APPROVED** [review]

**Pull request merged**
