### PR TITLE
KEYCLOAK-12870 - Allow to pick arbitrary user for IdP linking

### PR DESCRIPTION
**Pull request by dteleguin**
To enable picking arbitrary user, turn off "Create User If Unique" (as well as any other execution that depends on it, like "Confirm Linking Existing Account").

Technical notes - added more fine-grained control over the visibility of different login form elements, via form attributes:
* `USERNAME_EDIT_DISABLED`: disable username editing, hide "Remember Me";
* `REGISTRATION_DISABLED`: hide registration link;
* `IDENTITY_PROVIDERS_FILTERED`: show only IdPs linked to the user;
* `IDENTITY_PROVIDERS_DISABLED`: hide the whole IdP/social block

### CODE REVIEW

**Comment by dteleguin** [comment]
Doc PR: https://github.com/keycloak/keycloak-documentation/pull/836

**Comment by stianst** [comment]
I think this PR is a bit more complicated than it needs to, and that we can simplify it and also at the same time resolve another relevant issue.

With this PR users can now select a different username if it the user it matches is read-only/disabled/etc. However, what if it matches the wrong user. For example I have the username "myuser" in the external IdP, but in Keycloak it's taken by a different user. In this case I can't link to the existing user as I'm not allowed to change the username.

I would say that a simpler and more flexible fix would just be to pre-fill the username field, but allow users to always change it.

**Review by stianst — COMMENTED** [review]
See previous comment

**Comment by dteleguin** [comment]
> I think this PR is a bit more complicated than it needs to, and that we can simplify it and also at the same time resolve another relevant issue.

The purpose (and complexity) of the PR is actually about handling situations where Keycloak user cannot be matched. E.g., there is an internal readonly LDAP user store with all users pre-created, and we want to allow users to easily link their social accounts by reauthentication. In this case, "Create User If Unique" should be disabled. This PR allows to handle it correctly and to adjust the login form accordingly.

> 
> With this PR users can now select a different username if it the user it matches is read-only/disabled/etc. However, what if it matches the wrong user. For example I have the username "myuser" in the external IdP, but in Keycloak it's taken by a different user. In this case I can't link to the existing user as I'm not allowed to change the username.
> 
> I would say that a simpler and more flexible fix would just be to pre-fill the username field, but allow users to always change it.

That'd be super easy to do, just a 1-line change

**Comment by mposolda** [comment]
@dteleguin @stianst It may be good to have username always enabled, and just pre-filled with the existing user.

However I am not sure if that would mean that this PR will be easier. I have some doubts it may currently break if different username will be used - for example the use-case like this:
- The Idp user has "myuser" as username
- The form will be displayed on KC side with pre-filled "myuser" as username
- user change it to different username and authenticates with it - here I have some doubts if it will work. Will be good to have the test-case for this at least.

**Comment by dteleguin** [comment]
Superseded by #6828

**Pull request closed without merging**
