### PR TITLE
Fix the website on https://www.keycloak.org/server/db showing some asiidoc related `ifeval` text

### LINKED ISSUE #30417: Keycloak 25 db guide shows unevaluated "ifeval
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

Fix the website on https://www.keycloak.org/server/db showing some asciidoc related ifeval text

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The evals should be evaluated

### Actual behavior

It is not evaluated due to missing line breaks.

### How to Reproduce?

Look at the docs.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Backport of #30394

Closes #30417

### CODE REVIEW

**Comment by foliengriller** [comment]
Imho mssql-driver is included. See https://github.com/keycloak/keycloak/blob/cc00566fae2ec49cdd9ce8307f1dadc0a3e988e5/pom.xml#L168

**Comment by ahus1** [comment]
@foliengriller - it is included in the community edition, but not in Red Hat Build of Keycloak

**Comment by ahus1** [comment]
@vmuzikar - as you've reviewed the parent PR, please approve this backport as well when you have the time. Thanks!

**Review by vmuzikar — APPROVED** [review]
@ahus1 Thank you for the backport!

**Pull request merged**
