### PR TITLE
Add logout other sessions checkbox to TOTP, webauthn and recovery authn codes setup pages

### LINKED ISSUE #10232: Kill sessions after a password reset or MFA modification
### Description

Hey !

I noticed that after a "password reset" process or after adding MFA, all current sessions remain active.

To reproduce, sign in from one browser and do a password reset from another one.
After set a new password, you are always logged within the first browser.

### Discussion

_No response_

### Motivation

It's a security good practice to kill all sessions (at least all, except the one used to make the change).

See OWASP site : https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#renew-the-session-id-after-any-privilege-level-change

Moreover, if I manually changed my password, currently all other sessions are well killed.

### Details

Use the same code as password change post actions.

Thanks.

### PR DESCRIPTION
**Pull request by rmartinc**
Closes https://github.com/keycloak/keycloak/issues/10232

Main points:

* There is a macro that to include the logout other sessions checkbox to the needed ftl pages.
* The `login-recovery-authn-code-config.ftl` has been modified a bit to make both check-boxes (the previous confirmation box and the new logout other sessions input) look the same.
* Now all the actions calls a static method `logoutOtherSessions` if the form parameter `logout-sessions` is passed to `on`.
* Tests added for each action: totp, webauthn and recovery codes.
* The previous test `BackwardsCompatibilityUserStorageTest` needs changes because it registers totp with a session created before. So the test failed as the previous sessions was removed now.

@mposolda I have not modified the update email action as it was mentioned this way in the issue. But we can do the same for that action. The new account console also uses an AIA to update the user email, so I think it would be exactly the same.

### CODE REVIEW

**Comment by mposolda** [comment]
@rmartinc Looks great, Thanks!

My vote would be to just add this to UpdateEmail action as well as it should be covered as well.

**Comment by rmartinc** [comment]
@mposolda Adding the checkbox to the update email was not so direct as I thought. It seems that if the email needs to be verified in the realm, it needs to be verified at change too (ensuring I'm the owner of the previous email). So there is a second case in which the logout sessions should be postponed to the time when the email is verified (I think it makes no sense doing the logout before when the email is sent). I have created a second commit instead of squashing the PR, I think it's easier to review this way. I can do it different if you think this is not the best option, or we can just remove the email part (second commit). CI worked yesterday in my branch.

**Review by mposolda — APPROVED** [review]
@rmartinc Thanks for the updates. Your changes look correct to me and I am approving this. Hopefully tests are ok. Will squash the commits during merge.

**Comment by moritzschmitz-oviva** [comment]
@mposolda May I ask here if the offline session token are invalidated as well?

**Comment by rmartinc** [comment]
@moritzschmitz-oviva I would say that no, the method that is called is getUserSessionsStream, not getOfflineUserSessionsStream to obtain the sessions to logout.

**Comment by moritzschmitz-oviva** [comment]
> @moritzschmitz-oviva I would say that no, the method that is called is getUserSessionsStream, not getOfflineUserSessionsStream to obtain the sessions to logout.

Was there a reason to not also invalidate them?

**Pull request merged**
