### PR TITLE
Remove JBoss-based auth servers from the testsuite

### LINKED ISSUE #14299: Remove JBoss-based auth servers from the testsuite
### Description

It's necessary to get rid of all JBoss-based auth servers from the testsuite in the upstream (auth-server-wildfly, auth-server-eap). It consists of removing Maven profiles, tests, util classes,...

### LINKED ISSUE #14306: Properly execute SAML adapter tests with JBoss based servers
### Description

As we still support WF/EAP SAML Adapter, we need to properly execute those tests. However, I've noticed some relations for `app-server-wildfly` and `app-server-eap` with `auth-server-wildfly` and the WF distribution in the testsuite. It should be possible to use only the generic WildFly server with our adapter and not rely on our WF distribution. 

Module `integration-arquillian/servers/app-server/jboss`.

### PR DESCRIPTION
**Pull request by mabartos**
Closes #14299
Closes #14306 

MR to the pipeline: https://keycloak-pipeline.com/keycloak/keycloak-pipeline/-/merge_requests/184

I'll execute pipeline tests for that.

@wojnarfilip @leonardobrancalhao @miquelsi Could you please check it? Thanks.

### CODE REVIEW

**Review by wojnarfilip — DISMISSED** [review]

**Comment by mabartos** [comment]
@wojnarfilip Thanks for the approval. However, I had to rebase in order to get all GH actions properly started(some of them were canceled and retention of the KC artifacts already expired). No additional changes

**Review by wojnarfilip — APPROVED** [review]
LGTM, Thanks !

**Comment by mabartos** [comment]
@wojnarfilip Thanks for the review!
@nehachopra27 Could you please check it? Thanks

After analyzing various failures in the internal pipeline, this PR will not affect any other test stage. Works as expected.

Server pipeline: https://keycloak-pipeline.com/job/universal-test-pipeline-server/2189/ - Failures for WebAuthn and Old Admin console are already resolved in the upstream; needs to be only rebased (we don't do it for now in order to speed up the process)
Adapter pipeline: https://keycloak-pipeline.com/job/universal-test-pipeline-adapters/1288/ - As expected
Win19(JDK17): https://keycloak-pipeline.com/job/universal-test-pipeline-server/2208/ - Failures present even in the nightly build
User Federation tests: https://keycloak-pipeline.com/job/universal-test-pipeline-server/2199/ - Same as in nightly builds

**Comment by nehachopra27** [comment]
Thanks Martin, Changes LGTM!

**Comment by abstractj** [comment]
Changes LGTM, but we need the approval from @leonardobrancalhao or @miquelsi

**Review by miquelsi — APPROVED** [review]
Great job @mabartos, thank you!

**Pull request merged**
