### PR TITLE
Remove log4j dependency from model/jpa which is EOL

### LINKED ISSUE #20421: Remove log4j dependency for model/jpa
### Description

**TL;DR:** The dependency for log4j in `model/jpa` is actually used only in tests. Therefore its scope should change. 

As Log4j 1.x is no longer maintained, and the use is minimal, this should migrate to jboss-logging which is also used inside of Quarkus (see https://quarkus.io/guides/logging): 

> Internally, Quarkus uses JBoss Log Manager and the JBoss Logging facade. You can use the JBoss Logging facade inside your code as it’s already provided, or any of the supported Logging API listed in the next chapter as Quarkus will send them to JBoss Log Manager. 

In the following paragraphs several logging frameworks are listed, but not log4j 1.x or 2.x

To avoid inquiries like in #20328, this should therefore migrate to JBoss Logging

### PR DESCRIPTION
**Pull request by ahus1**
Closes #20421

### CODE REVIEW

**Comment by ahus1** [comment]
I have performed the following local test: 

1. change to `model/jpa`
2. Run `mvn clean test` 

Expected = actual result: no warnings from the logging framework itself when running the tests. To see if the logging work as expected, I added a local `log.warn` to `JpaUtils.getCustomChangelogTableName` and then those log messages show

**Review by vramik — APPROVED** [review]
lgtm, thanks @ahus1

**Comment by martin-kanis** [comment]
I was curious whether we can remove log4j even from tests, so I gave it a try https://github.com/martin-kanis/keycloak/commit/6e5bd07069aadeb8cc39933c362302f86ddbc2ed and tests passed. WDYT?

**Comment by ahus1** [comment]
@martin-kanis - I see that your commit removes the log4j dependency. While the tests compile and pass, for the logging to work as expected all `log4j.properties` need to be migrated to the JBoss Logmanager `logging.properties` like in this PR. So this would require additional work. I think it is still worth doing, still it should be part of a future pull request.  

I'm asking a maintainer to merge this PR for now.

**Review by abstractj — APPROVED** [review]

**Pull request merged**
