### PR TITLE
Adds REGISTER event when new user login through first broker flow

### LINKED ISSUE #11646: REGISTER event not logged during First Broker Flow
### Describe the bug

Version : RH-SSO 7.5.0 

ISSUE : REGISTER event is not logged for new user during "First Broker Login" flow in RH-SSO 7.5

 

The issue is not observed in RH-SSO 7.4

 

### Steps to Replicate:

- Configure RH-SSO as a broker, by configuring Identity provider in RH-SSO.
- Disable "Update Profile" Default Action, if enabled
- Configure event listener logging level to INFO

```
               <spi name="eventsListener">
                    <default-provider>jboss-logging</default-provider>
                    <provider name="jboss-logging" enabled="true">
                        <properties>
                            <property name="success-level" value="info"/>
                            <property name="error-level" value="warn"/>
                        </properties>
                    </provider>
                </spi>
```

- Login into RH-SSO with identity provider. Use new user which is not already registered in RH-SSO.
- Checking server logs, there are 2 events for LOGIN and no event for REGISTER

```
2022-04-04 21:18:12,155 INFO  [org.keycloak.events] (default task-10) type=LOGIN, realmId=identity-broker-realm, clientId=account-console, userId=1e06fad1-0189-40f8-bf40-655b5fa1abe8, ipAddress=127.0.0.1, identity_provider=oidc, register_method=broker, response_type=code, consent=no_consent_required, identity_provider_identity=rishabh, code_id=42608047-dff5-4148-81de-db66993a4b09, email=rissingh@redhat.com, username=rishabh, response_mode=fragment, authSessionParentId=42608047-dff5-4148-81de-db66993a4b09, authSessionTabId=lqq3jxp7DdM

2022-04-04 21:18:12,155 INFO  [org.keycloak.events] (default task-10) type=LOGIN, realmId=identity-broker-realm, clientId=account-console, userId=1e06fad1-0189-40f8-bf40-655b5fa1abe8, ipAddress=127.0.0.1, identity_provider=oidc, register_method=broker, response_type=code, consent=no_consent_required, identity_provider_identity=rishabh, code_id=42608047-dff5-4148-81de-db66993a4b09, email=rissingh@redhat.com, username=rishabh, response_mode=fragment, authSessionParentId=42608047-dff5-4148-81de-db66993a4b09, authSessionTabId=lqq3jxp7DdM
 ```

### Observations:

EventListenerTransaction is added in RH-SSO 7.5. And it seems the same event object from `IdentityBrokerService#afterFirstBrokerLogin` with EventType REGISTER  is passed into `AuthenticationManager.finishedRequiredActions` . In `AuthenticationManager.finishedRequiredActions` the EventType is set to LOGIN
 
```
 644     private Response afterFirstBrokerLogin(AuthenticationSessionModel authSession) {
 645         try {
 646             this.event.detail(Details.CODE_ID, authSession.getParentSession().getId())
 647                     .removeDetail("auth_method");
.............
 709                 event.event(EventType.REGISTER)
 710                         .detail(Details.REGISTER_METHOD, "broker")
 711                         .detail(Details.EMAIL, federatedUser.getEmail())
 712                         .success();
 
...........

 816     private Response finishBrokerAuthentication(BrokeredIdentityContext context, UserModel federatedUser, AuthenticationSessionModel authSession, String providerId) { 
...........
 843             event.detail(Details.CODE_ID, authSession.getParentSession().getId());
 844             return AuthenticationManager.finishedRequiredActions(session, authSession, null, clientConnection, request, session.getContext().getUri(), event);
845         }
```

### Query:

This seems to be a bug. Need your input on the same.

### Version

17.0.0

### Note

Marek: I did not personally reproduced it, but I think that the observation is correct and this is valid bug.

### PR DESCRIPTION
**Pull request by rishabhsvats**
Updates KcOidcBrokerEventTest, AbstractFirstBrokerLoginTest to factor in REGISTER event in first broker flow

Closes #11646

### CODE REVIEW

**Comment by mposolda** [comment]
@rishabhsvats Thanks for this PR! It looks good to me, however I see that tests were not executed for some reason. Could you please try to rebase your PR on top of latest keycloak main? Hopefully that helps to have GH actions running.

**Comment by rishabhsvats** [comment]
@mposolda rebased the PR on top of latest Keycloak main. I am first-time contributor, and it seems I would require manual approval from a repository collaborator with write access before any Actions workflows run. 

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by trixpan** [comment]
@pedroigor @mposolda can we get an approval so the test units can be executed?

**Review by mposolda — APPROVED** [review]
@rishabhsvats Thanks!

**Pull request merged**
