### PR TITLE
KEYCLOAK-17874 Server cannot be started with oracle19cRAC

### PR DESCRIPTION
**Pull request by mposolda**

### CODE REVIEW

**Comment by mposolda** [comment]
@hmlnarik @vramik Do you please have a chance to review this? I am going to run pipeline for DB tests and DB migration tests with this and will attach links once it is finished.

**Review by vramik — COMMENTED** [review]
Thank you @mposolda for the PR. It looks really good to me. I like the way how the datatype is changed. 

I'd like to see results from DB tests and DB migration tests before merging. Unfortunately some database versions are not updated yet in pipeline. I'll sync with @pdrozd regarding the update. 

Another possibility is to check it manually with all DBs, but I'd like to avoid that if possible.

**Comment by mposolda** [comment]
@vramik Thanks Vlasta!

I've tried to run pipeline job, so hopefully results are later today.

As you pointed, I am not 100% sure if all the DB versions in the pipeline are the proper versions, which we need to officially support. I hope that as long as all "DB vendors" are OK, we are ok with this PR as well (For example I assume that it is quite low chance that functionality, which pass with Oracle 18 will fail with Oracle 19. Hence I guess it is ok if pipeline is still using Oracle 18 instead of Oracle 19 right now). But depends on @pdrozd to decide this though.

**Comment by vramik** [comment]
> I hope that as long as all "DB vendors" are OK, we are ok with this PR as well (For example I assume that it is quite low chance that functionality, which pass with Oracle 18 will fail with Oracle 19. Hence I guess it is ok if pipeline is still using Oracle 18 instead of Oracle 19 right now).

I'm afraid the pipeline will not run the tests with older versions of databases (which would be sufficient from my POV for the purpose of this PR). The pipeline will fail before the test is even started because it tries to download jdbc drivers from URLs which doesn't exist.

**Comment by hmlnarik** [comment]
Incorporated in #7996 (to prevent conflict resolution)

**Pull request closed without merging**
