### PR TITLE
DO NOT MERGE - Draft for quarkus 2.8.0.CR1

### PR DESCRIPTION
**Pull request by DGuhr**
Draft  PR to test new quarkus version as quarkus just released their 2.8.0.CR1

upgrade of hibernate to 5.6.7 included

### CODE REVIEW

**Comment by stianst** [comment]
Don't upgrade to Quarkus 2.8 until we've had a chat about it, as we may actually stick to 2.7

**Comment by DGuhr** [comment]
sure. this is just to check if we have some regressions in the testsuite for now, as long as it's not final and we didn't have a chat, nothing more will be done in that area. wanted to close the PR afterwards.

**Comment by stianst** [comment]
> sure. this is just to check if we have some regressions in the testsuite for now, as long as it's not final and we didn't have a chat, nothing more will be done in that area. wanted to close the PR afterwards.

I also mean don't upgrade to Quarkus 2.8 Final either

**Comment by DGuhr** [comment]
> > sure. this is just to check if we have some regressions in the testsuite for now, as long as it's not final and we didn't have a chat, nothing more will be done in that area. wanted to close the PR afterwards.
> 
> I also mean don't upgrade to Quarkus 2.8 Final either

as said, nothing more will be done until we had our chat. nevertheless it should be good to catch possible regressions early.

**Pull request closed without merging**
