### PR TITLE
[KEYCLOAK-17174] - New admin console using wrong base URI for redirection

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by ssilvert** [comment]
@pedroigor As long as the test suite runs with this change, it LGTM.  I need to find out if we still have an easy way to run the new account console tests without doing it locally.

**Comment by pedroigor** [comment]
@ssilvert Would you be able to approve the PR then?

**Comment by ssilvert** [comment]
> @ssilvert Would you be able to approve the PR then?

Yes.  As long as it doesn't break any tests I'll approve.

**Comment by pedroigor** [comment]
@ssilvert Tests are passing :) Or do you want to run some other test?

**Comment by ssilvert** [comment]
> @ssilvert Tests are passing :) Or do you want to run some other test?

I'm talking about the UI tests.  These are not run when you do a PR.  We used to be able to kick them off on Jenkins but that doesn't seem to be working right now.  I'm trying to find out what we can do.

**Review by ssilvert — APPROVED** [review]
I finally gave up and ran the tests locally.  Looks good.

**Pull request merged**
