### PR TITLE
/clients-registrations API doesn't return secret anymore and is not coherent #11116

### LINKED ISSUE #11116: /clients-registrations API doesn't return secret anymore and is not coherent
### Describe the bug

Hello,

When when a user create an OIDC Client using endpoint POST `/clients-registrations/default/` a client secret is not generated anymore with keycloak 15. It was with keycloak 11 very same call. No secret provided in the json, if I provide as secret it works but I want to let the API generate one.

If I do a PUT after on `/clients-registrations/default/{clientId}` with still no secret in the json, a secret is generated by the PUT api ! It's not coherent with the POST.

So only way for a user to know their client secret so far is to perform a useless PUT.

### Version

15.1.1

### Expected behavior

POST should generate a Secret

### Actual behavior
POST Doesnt generate a Secret
GET doesnt return the secret after a POST
PUT generate the secret
GET return the secret after a PUT

### How to Reproduce?

```
response = requests.post(
    'https://your_domain.com/auth/realms/your_realm/clients-registrations/default/',
    headers={'Authorization': 'Bearer %s' % your_valid_access_token},
    json={
        "clientId": "test_client",
        "name": "My Service Name",
        "description": "This describes what my app is for end users",
        "rootUrl": "https://root.url.of.my.app",
        "redirectUris": [
            "https://fullLoginPath",
            "/relative/redirect/path",
            "/these/can/use/wildcards/*"
        ],
        "defaultClientScopes":["openid"],
        "optionalClientScopes":["microprofile-jwt"],
        "webOrigins": ["+"],
        "bearerOnly": False,
        "consentRequired": True,
        "standardFlowEnabled": True,
        "implicitFlowEnabled": False,
        "directAccessGrantsEnabled": False,
    })
    ```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedro-hos**
Also fixing the https://github.com/keycloak/keycloak/issues/11897 and https://github.com/keycloak/keycloak/issues/11248
Closes: #11116 #11897 #11248

### CODE REVIEW

**Review by mposolda — CHANGES_REQUESTED** [review]
@pedro-hos Thanks for the PR!

Fix itself looks good, but can you please update this to not use tabs and instead switch to 4 spaces indentation? There is some setupf of codestyle which you can do in your IDE to automatically do this. I've updated 1 file of this PR in your branch, but see that you have this in all the others, so leaving the rest to you.

**Comment by pedro-hos** [comment]
@mposolda thank you for your feedback. I've updated the code with the right identation.

**Review by mposolda — APPROVED** [review]
@pedro-hos Thanks for fixing this!

**Comment by carlosli888** [comment]
Would this fix also address a similar issue when using the OIDC registration API?  See https://github.com/keycloak/keycloak/issues/12565 for details.

**Comment by mposolda** [comment]
@carlosli888 You can try latest keycloak nightly build. But I think it won't fix #12565 as I see the check in the `DescriptionConverter.toExternalResponse` is still there.

**Pull request merged**
