### PR TITLE
Add support for overriding offline session lifespan values

### PR DESCRIPTION
**Pull request by thomasdarimont**
See: #24274

Signed-off-by: Thomas Darimont <thomas.darimont@googlemail.com>

### CODE REVIEW

**Comment by ahus1** [comment]
Hi @thomasdarimont - we're considering your solution and are are currently making up our minds which automated tests we would add to it. 

As this PR is already some months old, do you have some ideas / thoughts / code you would like to add?

**Comment by thomasdarimont** [comment]
Hey @ahus1 thanks for the heads up! That's awesome news :)

Some ideas:

In my PR, I introduced dedicated settings for `offlineSessionCacheEntryLifespanOverride` and `offlineClientSessionCacheEntryLifespanOverride.` Perhaps instead of providing those settings, we could leverage the infinispan configuration directly, e.g., we could use the `max-idle` configuration of the corresponding infinispan cache. This allows users to customize and adjust the cache behavior according to their needs.

Most users who need to customize the cache behavior want to reduce memory usage over time, especially when many offline sessions are at play. Those users will probably adjust the max-idle time of the offline user/client sessions cache to be ~10 hours to cover a workday or 24 hours to cover a full-day travel experience in a travel companion app.

The current default [cache-ispn.xml](https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/resources/cache-ispn.xml#L48) file does not specify a max-idle, hence it uses either the internal default (-1) or a Keycloak controlled value. Perhaps we could make Keycloak inspect the provided cache configuration, and if we detect that the admins configured max-idle differently than the default, we could use that. :)

**Comment by ahus1** [comment]
Hi @thomasdarimont - thank you for the comment. We prefer documented options instead of a long XML file where people might get lost. Due to this, we prefer the SPI-parameters. Maybe we'll eventually have a CLI option for it. 

About the max-idle in the XML: As we're passing the lifetime and idle via the Java API, I was under the assumption that those would take precedence?

Having that configurable via the UI per realm would be a next step. Let's take it one step at a time.

**Comment by ahus1** [comment]
Closing in favor of #26811

**Pull request closed without merging**
