### PR TITLE
Enhance SupportedCredentialConfiguration to support optional claims object as defined in OpenID for Verifiable Credential Issuance specification

### LINKED ISSUE #30419: Credential Issuer Metadata: Support Optional ```claims``` Object in ```credential_configurations_supported``` in ```openid-credential-issuer``` endpoint
### Description

The Keycloak ```org.keycloak.protocol.oid4vc.model.SupportedCredentialConfiguration``` class lacks support for the optional ```claims``` object within the ```credential_configurations_supported``` entries in the Credential Issuer Metadata. This object is defined in the [OpenID for Verifiable Credential Issuance specification (Section 11.2.3)](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-13.html#name-credential-issuer-metadata-p).

### Discussion

_No response_

### Motivation

The ```claims``` object is essential for wallets to display accurate details about the Verifiable Credential that the issuer is about to provide. It allows the issuer to specify the expected claims and their properties, enhancing the wallet user experience.

e.g:
```json
{
  "credential_configurations_supported": {
    "test-credential": {
      "id": "test-credential",
      "format": "vc+sd-jwt",
      "scope": "VerifiableCredential",
      "claims": {
        "firstName": {},
        "lastName": {},
        "email": {}
      }
    }
  }
}

```

### Details

Extend the ```SupportedCredentialConfiguration``` class to include a new field ```claims``` from a class ```Claims extends HashMap<String, Claim>```  to represent the "claims" object.

Create a new ```Claim``` class to model the structure of individual claim entries within the "claims" object. This class should include properties specified in [OpenID for Verifiable Credential Issuance specification (Section 11.2.3)](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-13.html#name-credential-issuer-metadata-p) like:

- mandatory (boolean): Indicates if the claim is required.
- value_type (string): Specifies the data type of the claim value (e.g., "string", "number").
- display (array): Contains display properties for the claim (e.g., name, locale).

Ensure that the new claims field is correctly serialized and deserialized when converting the ```SupportedCredentialConfiguration``` to and from JSON.

Implement and test the dot notation for parsing and serializing nested claims e.g.:
```json
{
"attributes": {
    "vc.test-credential.expiry_in_s": 100,
    "vc.test-credential.format": "vc+sd-jwt",
    "vc.test-credential.scope": "VerifiableCredential",
    "vc.test-credential.claims": "{ \"firstName\": {}, \"lastName\": {}, \"email\": {} }"
  },
}
```
Modify ```org.keycloak.testsuite.oid4vc.issuance.signing.OID4VCIssuerWellKnownProviderTest``` to also test consuming nested json strings.

### PR DESCRIPTION
**Pull request by francis-pouatcha**
Closes: #30419

### CODE REVIEW

**Review by wistefan — APPROVED** [review]
LGTM

**Comment by francis-pouatcha** [comment]
@mposolda @wistefan : added fixes related to https://github.com/keycloak/keycloak/issues/30419#issuecomment-2169408107. Looks good to go now.

**Comment by wistefan** [comment]
> @mposolda @wistefan : added fixes related to [#30419 (comment)](https://github.com/keycloak/keycloak/issues/30419#issuecomment-2169408107). Looks good to go now.

Looks still good to me

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
@francis-pouatcha @wistefan Thanks for the work and review!

**Pull request merged**
