### PR TITLE
KEYCLOAK-8759: Wrong RH-SSO name on Welcome Page

### PR DESCRIPTION
**Pull request by ssilvert**

### CODE REVIEW

**Review by vmuzikar — APPROVED** [review]
I've managed to build the RH-SSO dist.
LGTM, although I wonder if we should add a test for it to the [WelcomePageTest](https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/other/welcome-page/src/test/java/org/keycloak/testsuite/welcomepage/WelcomePageTest.java). It could use the [test constants properties file](https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/resources/test-constants.properties) - see [AbstractKeycloakTest](https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java#L520).

If we're not adding the test right away, we should at least create a jira for it.

**Comment by ssilvert** [comment]
@keycloak-ci-bot test

**Comment by ssilvert** [comment]
@keycloak-ci-bot test

**Comment by ssilvert** [comment]
@keycloak-ci-bot test

**Comment by ssilvert** [comment]
@vmuzikar Go ahead and create a JIRA describing the needed test.  Since you are already familiar with the code, go ahead and write the test as well if you want.

**Comment by vmuzikar** [comment]
Ok, created https://issues.jboss.org/browse/KEYCLOAK-8836

**Review by stianst — APPROVED** [review]

**Pull request merged**
