### PR TITLE
[KEYCLOAK-1349] Add JS date-picker to admin and user events date filter in admin console UI

### PR DESCRIPTION
**Pull request by girirajsharma**
The library used for events datepicker is https://github.com/patternfly/patternfly/tree/master/components/bootstrap-datepicker

### CODE REVIEW

**Comment by stianst** [comment]
Please only include the required files from bootstrap-datepicker.

**Comment by girirajsharma** [comment]
Ok, I will do so and squash commits.

**Comment by stianst** [comment]
Does this require the updated PatternFly version? We're using a pretty old version atm

**Comment by girirajsharma** [comment]
I do think that we need to update the patternfly version. The latest patternfly release version is v2.2.0 (https://github.com/patternfly/patternfly/releases) and it does have the support of date-picker.

Reference : https://www.patternfly.org/patterns/datepicker/

**Comment by stianst** [comment]
I can upgrade PatternFly today, so let's hold off on this PR until then

**Comment by stianst** [comment]
Upgrading PatternFly is not going to be trivial as a lot of things break, so this will have to wait

**Comment by girirajsharma** [comment]
Closing this for now. I will re-push once keycloak has support for newer version patternfly.

**Pull request closed without merging**
