### PR TITLE
Removed hard-coded LTR dir attribute in inputs in configure OTP template

### LINKED ISSUE #32844: Login V2: Missing "dir" attributes
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

The new login theme doesn't add `dir` attributes to input fields and other tags

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

I know that "dir" is about the direction of the input, but I'm not 100% sure on how this would behave. 

I see that in the old templates all `input`s seem to have them to `ltr`, plus the `div`s which contain the input and the button for passwords. 

### Actual behavior

Some "dir" attributes are missing in the new templates.

### How to Reproduce?

Look at the code!

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by senyahnoj**
This should be done in the html opening tag only (see issue #33642)

Closes #32844

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
Thanks for the PR @senyahnoj. I'll also mark the issue as something to backport for v26 so that we can put this fix in a patch release.

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for the PR. The old theme had additional hard-coded `dir` attributes whenever there was a password with the show-password-toggle. 

https://github.com/keycloak/keycloak/blob/10fc2e9a316c2ed8e3e1b20adeb1101c6432e7b5/themes/src/main/resources/theme/base/login/login-password.ftl#L13-L24

Can you please comment if this should be restored? This was the original intent for this issue.

**Comment by senyahnoj** [comment]
Thanks @ahus1, I've had a look at the base theme as well and I see the hard-coded dir=ltr in a few places. Given that it's set in the HTML tag there is no need to override it.

I am new to contributing to this project but from the guidelines it looks like a single/rebased commit per issue is desirable. Therefore I'll close this PR and create a new one with the fix in both keycloak.v2 and base themes.

**Comment by ahus1** [comment]
> it looks like a single/rebased commit per issue is desirable

True, this is desired. If there is a good reason to keep two commits, that is possible when there is a justification. You can also agree with the reviewer to keep different commits for the review, and then the final approver will squash the changes when merging them to main.

**Comment by senyahnoj** [comment]
Re-opening PR as we have decided to only make the change in keycloak.v2 theme

**Review by jonkoops — APPROVED** [review]

**Review by ahus1 — APPROVED** [review]
Thank you for everyone involved in this, and the discussions we had to find the right fix.

**Pull request merged**
