### PR TITLE
Remove Infinispan workarounds after upgrading to 13.x

### LINKED ISSUE #13962: Remove Infinispan 12.1.7 workarounds from legacy store and model tests
### Description

We introduced the following workarounds to make model tests stable:
- https://github.com/keycloak/keycloak/commit/2b81e62b6b62f7ce6f6e3918bf0a237cc52d9b9a
- https://github.com/keycloak/keycloak/commit/64cbbde7cf255c853ba098f2cf3e899413ff4e0a
- https://github.com/keycloak/keycloak/commit/ebfc24d6c105971f00f86d1c96fc0dc2aed45bf9

We should revert this since now we are using ISPN 13 which should have these problems fixed.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #13962

### CODE REVIEW

**Comment by ahus1** [comment]
@mhajas - there is one workaround I was able to remove; the other one persists. See my code comment. Failing Quickstarts is unrelated, see #14080

**Comment by ahus1** [comment]
@mhajas - with the other Infinispan problems pending (see #14067), I wonder if this change should be hold back, or if we would merge it anyway and roll it back if we should revert to an earlier version of Infinispan.

**Comment by mhajas** [comment]
Honestly, I don't see the problems from #14067 to be so critical we should revert to the previous Infinispan version. This PR may make the issues we see in #14067 even more visible, so we should merge this first and then stabilize the test in the #14067 PR. WDYT?

**Review by mhajas — APPROVED** [review]
Thanks @ahus1, LGTM

**Comment by ahus1** [comment]
@mhajas - thanks for the comments, let's merge this first.

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
