### PR TITLE
KEYCLOAK-6106: Change order of fields in the encoded state to allow dots in client id

### PR DESCRIPTION
**Pull request by knutz3n**

### CODE REVIEW

**Comment by knutz3n** [comment]
It might be better to base64 encode the client id instead of rearranging the fields. Let me know if you would like me to change the pull request.

**Comment by hmlnarik** [comment]
Thank you for the pull request. Since we're in process of releasing right now and we need to adjust the approach, we'll implement it with more conservative approach. Your approach works too but given the situation affects more than we can afford right now.

**Comment by knutz3n** [comment]
Are you able to fix this issue with the release of version 3.4.3.Final? Let me know if you need/want my help with this issue. This is currently blocking our upgrade and there are bugs in v3.3.0.Final we would like to get rid of in production.

**Comment by hmlnarik** [comment]
We should. For the same reason, I'm closing this one and replacing it by #4899

**Pull request closed without merging**
