### PR TITLE
Docker entrypoint, read environment variables from files.

### LINKED ISSUE #10816: Read secrets from files
### Description

For passing sensitive information (database password) to a Keycloak container, it would be useful to support a file-based solution in addition to the plain environment variables.

[Postgres](https://hub.docker.com/_/postgres) image, for example supports it like this:

> As an alternative to passing sensitive information via environment variables, _FILE may be appended to some of the previously 
> listed environment variables, causing the initialization script to load the values for those variables from files present in the
> container. In particular, this can be used to load passwords from Docker secrets stored in /run/secrets/<secret_name> files. 

`docker run --name some-postgres -e POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd -d postgres`

I am creating my own image based on the official one and have a custom entrypoint to implement this.

```bash
#!/bin/bash

# Basic support for passing the db password as a mounted file. Or any other KC_ variable,
# really.
# Looks up environment variables like KC_*_FILE, reads the specified file and exports
# the content to KC_*
# e.g. KC_DB_PASSWORD_FILE -> KC_DB_PASSWORD

# Find suitable variables
lines=$(printenv | grep -o KC_.*_FILE)
# Split into array
vars=($lines)
# Enumerate variable names
for var in ${vars[@]}; do
    # Output variable, trim the _FILE suffix
    # e.g. KC_DB_PASSWORD_FILE -> KC_DB_PASSWORD
    outvar="${var%_FILE}"

    # Variable content = file path
    file="${!var}"

    # Empty value -> warn but don't fail
    if [[ -z $file ]]; then
        echo "WARN: $var specified but empty"
        continue
    fi

    # File exists
    if [[ -e $file ]]; then
        # Read contents
        content=$(cat $file)
        # Export contents if non-empty
        if [[ -n content ]]; then
            export $outvar=$content
            echo "INFO: exported $outvar from $var"
        # Empty contents, warn but don't fail
        else
            echo "WARN: $var -> $file is empty"
        fi
    # File is expected but not found. Very likely a misconfiguration, fail early
    else
        echo "ERR: $var -> file '$file' not found"
        exit 1
    fi    
done


# Pass all command parameters
/opt/keycloak/bin/kc.sh start "$@"
```
In my `Dockerfile`, I simply include the script and set it as the entrypoint.

```Dockerfile
COPY entrypoint.sh .
ENTRYPOINT ["/entrypoint.sh"]
```

This enables me to run it locally like:

`docker run --mount type=bind,source=$(pwd)/secret,target=/tmp/kcdbpw -e KC_DB_PASSWORD_FILE=/tmp/kcdbpw my-keycloak`

And enables using Docker Secrets for actual production use in pretty much equivalent manner.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by epuronta**
Adds a special entrypoint script for the Docker image.

The script supports using (mounted) files for configuring sensitive variables (like passwords). It is an alternative to passing the sensitive value directly as an environment variable (`KC_DB_PASSWORD=MyPassword`).

Basic process:
- The information is mounted as a file to the container (e.g. `/tmp/kc-db-password`)
- File path is passed as an environment variable (`KC_DB_PASSWORD_FILE=/tmp/kc-db-password`)
- The entrypoint detects `KC_DB_PASSWORD_FILE`, reads the file content and exports it as `KC_DB_PASSWORD`

Closes #10816.

### CODE REVIEW

**Comment by epuronta** [comment]
I had no idea if and how the included test script should be run automatically. Might be appropriate.

**Review by stianst — CHANGES_REQUESTED** [review]
We should consider how reading secrets for things like DB aligns with reading secrets for things like LDAP server within a realm.

I can see that we should support something along the line of DB_USERNAME_FILE, but in that case it's something we would add to the Quarkus distribution to support somehow, and not as a wrapper in the container image.

**Comment by epuronta** [comment]
Agreed @stianst, it would be better to have this directly where Quarkus loads the configuration instead of a wrapper script. I don't have the expertise to create a PR though, so someone else would need to step in for that.

Also, sorry for the late response - I totally missed the reply notification here.

**Comment by artpdr** [comment]
> Adds a special entrypoint script for the Docker image.
> 
> The script supports using (mounted) files for configuring sensitive variables (like passwords). It is an alternative to passing the sensitive value directly as an environment variable (`KC_DB_PASSWORD=MyPassword`).
> 
> Basic process:
> 
> * The information is mounted as a file to the container (e.g. `/tmp/kc-db-password`)
> * File path is passed as an environment variable (`KC_DB_PASSWORD_FILE=/tmp/kc-db-password`)
> * The entrypoint detects `KC_DB_PASSWORD_FILE`, reads the file content and exports it as `KC_DB_PASSWORD`
> 
> Closes #10816.

Sorry if I'm missing something, but if you do an `export foo=content_from_secret_file` you will end up with secrets in the environment variables, which has associated security risks.

**Comment by epuronta** [comment]
@artpdr as far as I understand, the primary security risk with having secrets in environment variables is related to how Docker displays the environment variables supplied to the container with `docker inspect` as this exposes the secrets to anyone with access to the docker socket.

The approach in this issue, however, exports the variables inside the container, so they are not exposed to docker (or at least not shown with `docker inspect`, I don't know how exactly it works internally).

For a simple example, fire up a container with one supplied secret and export another one from the inside
```
> docker run -it --rm  -e SECRET1=secret1 --name secret-test alpine
/ # export SECRET2=secret2
/ # printenv
HOSTNAME=941be17a9ac1
SECRET1=secret1
SECRET2=secret2
```

Inspecting the container only exposes the first secret
```
docker inspect secret-test -f "{{ .Config.Env }}"
[SECRET1=secret1]
```

**Pull request closed without merging**
