### PR TITLE
KEYCLOAK-11996 Authorization Endpoint does not return an error when a request includes a parameter more than once

### PR DESCRIPTION
**Pull request by tnorimat**
It seems that  keycloak does not follow some part of OAuth 2.0.
The details can be found in https://issues.jboss.org/browse/KEYCLOAK-11996.

### CODE REVIEW

**Comment by stianst** [comment]
Rather than looping over all params it might be better to update AuthzEndpointRequestParser.parseRequest to check only known OAuth/OIDC params for duplicates when retrieving them.

**Comment by tnorimat** [comment]
@stianst 
If any kind of the duplicated parameter error is returned to the user's browser (Error Page) not the client, it is easy to do this check in AuthzEndpointRequestParser.parseRequest.

However, if the client related parameters (client_id, redirect_uri) are valid and other parameter is duplicated, I think keycloak needs to return the error(invalid_request) to the client by HTTP redirection.

Therefore, the following check seems to be needed:
* check all parameters about whether they are duplicated or not.
* after validating client related parameters,
  - if those are valid, send the error to the client.
  - if not, send the error to the user's browser.

Looking into AuthzEndpointRequestParser.parseRequest, I can do those but might become complicated rather than my first commit.

Could you give me the comment on these of which are preferable?

**Comment by stianst** [comment]
> The authorization server MUST ignore unrecognized request parameters.  Request and response parameters MUST NOT be included more than once.

The two sentences above from the spec are a bit conflicting. However, I'd say that we should only check for duplicates in recognized parameters and ignore the rest.

I agree that an error response (error=invalid_request) is the correct behaviour if duplicated parameters are included.

**Comment by tnorimat** [comment]
I've checked duplicated parameters on AuthzEndpointRequestParser.parseRequest.

One point to note is that the error needs to be sent to the client after keycloak verifies the client's valid redirect URI.

To do so, I've add the member AuthorizationEndpointRequest.invaidRequestParamException to keep this error. This member can keep the error occured on AuthzEndpointRequestParser.parseRequest not only duplicated parameters in this time, but some other error check that might be added in the future (e.g. additional error check on request object).

There might be better way, but only this idea hit on me.

**Comment by stianst** [comment]
I don't like storing the exception and also having to pass AuthorizationEndpointRequest around. 

As AuthzEndpointRequestParser is instantiated for each request it would be better to just add "Map<String, String> invalidParameters" to AuthzEndpointRequestParser. Where the key would be the param name, and value would be a description of what the error is.

**Comment by tnorimat** [comment]
@stianst Thank you for your suggestion. I'm afraid I cannot catch what you pointed but I'm not sure how to get proposed `AuthzEndpointRequestParser.invalidParameters` after calling `AuthorizationEndpointRequestParserProcessor.parseRequest()` in `AuthorizationEndpoint.process()`.
```java
        request = AuthorizationEndpointRequestParserProcessor.parseRequest(event, session, client, params);

```
`AuthorizationEndpointRequestParserProcessor.parseRequest()` returns `AuthorizationEndpointRequest`.

I think the error response to the client might be generated after `AuthorizationEndpoint.checkRedirectUri()`.

**Comment by stianst** [comment]
I want to get this into Keycloak 9, but don't have time to review it right now. Will get back to it in January and perhaps see if I code up what I had in mind.

**Comment by tnorimat** [comment]
I see. I'll wait for you next year.

**Comment by stianst** [comment]
Did a little bit of cleanup/refactoring and opened a new PR here:
https://github.com/keycloak/keycloak/pull/6696

Closing this PR, as will continue with the above PR.

**Pull request closed without merging**
