### PR TITLE
KEYCLOAK-11779 Make feature controller which takes care of enabling/d…

### PR DESCRIPTION
**Pull request by mhajas**
…isabling features including restarting container if needed

### CODE REVIEW

**Comment by vmuzikar** [comment]
@mhajas I've tried to quickly check if this PR doesn't also resolve my [KEYCLOAK-11546](https://issues.jboss.org/browse/KEYCLOAK-11546) but it seems like Admin Console UI tests cannot be compiled. Could you please check it?

**Comment by mhajas** [comment]
@vmuzikar It was my fault, I forgot to look for things I removed in console package, which is not included by default, so the build passed. Now it should be ok.

**Review by vmuzikar — APPROVED** [review]
From Admin Console tests PoV, looks good now and even fixes [KEYCLOAK-11546](https://issues.jboss.org/browse/KEYCLOAK-11546). Thanks @mhajas!

**Review by hmlnarik — APPROVED** [review]
Thanks, @mhajas!

**Pull request merged**
