### PR TITLE
KEYCLOAK-16301 Steps to test Kerberos SSO on Windows

### PR DESCRIPTION
**Pull request by dxmann73**
After a lot of digging I've finally figured out how to make this work under Windows, decided to write up my results so you may add it to the docs if you wish.

### CODE REVIEW

**Comment by dxmann73** [comment]
Duplicate of #7577 

I've added a [JIRA](https://issues.redhat.com/browse/KEYCLOAK-16301) as requested.

Let me know if you need anything else! 👍

**Comment by hmlnarik** [comment]
@miquelsi Could you please review this PR?

**Comment by hmlnarik** [comment]
@dxmann73 Please ensure that the JIRA is in the commit message as well as the PR title. Please see https://github.com/keycloak/keycloak/blob/master/CONTRIBUTING.md#submitting-your-pr

**Comment by dxmann73** [comment]
Sorry for the delay, currently busy rolling out Keycloak at our site :-)

I've updated the PR and added a commit with reference to the [JIRA issue](https://issues.redhat.com/browse/KEYCLOAK-16301)

Let me know if you need anything else. Cheers!

**Comment by hmlnarik** [comment]
@miquelsi Could you please review this one?

**Comment by stianst** [comment]
I'm going to close this PR as it would be very time consuming for us to verify if these steps work, and it is not in the scope of Keycloak documentation to document how to use/test Kerberos in general.

**Pull request closed without merging**
