### PR TITLE
27770 Update README.md

### PR DESCRIPTION
**Pull request by amitkhurana92**
The sample url provided in readme is incorrect. The auth resource is not required

Signed-off-by: Amit Khurana amitkhurana92@gmail.com

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]
LGTM

**Comment by gim-** [comment]
There seem to be 2 more similar URLs:
https://github.com/keycloak/keycloak/blob/e872ac08d87e92ced756df291527ede0eaef4866/examples/saml/servlet-filter/README.md#L14
https://github.com/keycloak/keycloak/blob/d3bd0a67a7c76047a03e48a09d8275eb0e91dd7f/examples/saml/README.md#L20

**Comment by jonkoops** [comment]
Good catch @gim-, perhaps those could be resolved as well @amitkhurana92. Also, could you log an issue for this PR? We need this for our backporting proccess.

**Comment by stianst** [comment]
This example has now been deleted, so closing the PR

**Pull request closed without merging**
