### PR TITLE
Users in role Rest API returns empty when User federation used

### LINKED ISSUE #19516: Users in role Rest API returns empty when User federation used.
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

Hi Team,

I have successfully implemented User Federation using an external REST API. Users are pulled from external services, and their extra information is stored in Keycloak. Everything is working well, except for the **Users In Role** tab, which appears empty when clicked. 

image

Upon inspection, I noticed that none of my custom user federation methods were called when clicked on this tab. I even attempted to use the admin API GET `/{realm}/clients/{id}/roles/{role-name}/users`, but received the same result.

I already assigned roles to the user and can see the same when clicking on user's **Role Mapping** tab.

When I don't use user-federation and directly add users in Keycloak then it works.

### Version

20.0.5, 21.0.2

### Expected behavior

It should return filtered users by role.

### Actual behavior

Empty response.

### How to Reproduce?

Create a custom user-storage provider and implement `UserStorageProvider, UserLookupProvider, UserQueryProvider` interfaces. 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by martin-kanis**
Closes #19516 

This PR replaces https://github.com/keycloak/keycloak/pull/22449 where the test was missing. I kept [shankaryadavy9](https://github.com/shankaryadavy9) as co-author.

### CODE REVIEW

**Review by mhajas — COMMENTED** [review]
@martin-kanis I made some changes to the PR.

1. Changes in `UserMapStorage` were not necessary as it should not implement federation interfaces
2. I renamed the introduced method to not include `Federated` string. Maybe it makes sense to have it there, however, we are not using it anywhere else so it felt weird to have it only in that one method.

Please let me know whether the changes make sense to you, if yes I will approve and merge.

**Comment by martin-kanis** [comment]
> @martin-kanis I made some changes to the PR.
> 
> 1. Changes in `UserMapStorage` were not necessary as it should not implement federation interfaces
> 2. I renamed the introduced method to not include `Federated` string. Maybe it makes sense to have it there, however, we are not using it anywhere else so it felt weird to have it only in that one method.
> 
> Please let me know whether the changes make sense to you, if yes I will approve and merge.

@mhajas I agree that changes in `UserMapStorage` are not necessary. However, when you remove `Federated` string from the method name, and you attempt to implement both `UserRoleMappingsFederatedStorage, UserQueryProvider` interfaces, you will get a clash:
```
'getRoleMembersStream(RealmModel, RoleModel, Integer, Integer)' in 'org.keycloak.testsuite.federation.UserMapStorage' clashes with 'getRoleMembersStream(RealmModel, RoleModel, Integer, Integer)' in 'org.keycloak.storage.federated.UserRoleMappingsFederatedStorage'; attempting to use incompatible return type
```

WDYT?

**Comment by martin-kanis** [comment]
@mhajas  No it makes sense. Thank you for explaining the usages. The PR is then ready to go.

**Review by mhajas — APPROVED** [review]
Thanks @martin-kanis

**Pull request merged**
