### PR TITLE
Improving the generated REST API documentation

### PR DESCRIPTION
**Pull request by guusdk**
The changes in this PR add grouping to the generated REST API documentation, which makes it easier to find the a particular endpoint.

This is a [screenshot](https://ibin.co/38Q4S268KaSs.png) of the resulting documentation

### CODE REVIEW

**Comment by stianst** [comment]
Awesome, looks great

**Comment by stianst** [comment]
We'll review and merge once we get started on 3.x as it's to late to include it now

**Comment by stianst** [comment]
@mstruk can you review this PR please?

**Comment by mstruk** [comment]
I think it can be merged. 

There is one issue I noticed that's been in this code from before - usage of http: to connect to maven repo. I created [a JIRA](https://issues.jboss.org/browse/KEYCLOAK-4421). That can be fixed with another PR.

**Pull request merged**
