### PR TITLE
KEYCLOAK-2474 Possibility to add custom SPI and extend the data model

### PR DESCRIPTION
**Pull request by mposolda**

### CODE REVIEW

**Comment by ewjmulder** [comment]
Marek, thank you for wrapping up this PR and completing the Liquibase solution and example! Did you actually test the complete example in the end to see if the extra domain entites indeed were added to the database and you could request them through the added REST endpoint?

**Comment by mposolda** [comment]
Thanks to you as you did most of the work to have this functionality available!

And yes, I've tested and I've added some notes to the README of the example how to test it.

**Comment by mposolda** [comment]
Also automated test added to the testsuite-arquillian

**Comment by ewjmulder** [comment]
Ah yes, I see the added description in the README now, cool to finally see it all working on the master!
And funny to see your curl + sed access token extraction script, I have made something very similar for our inhouse testing. :)

Only downside to the super simple example is that it does not show an actual use case behind the extension functionality. But maybe an example is not the right place for that. Maybe its more suited for a blog post?

Do I understand correctly that you put the example in the testsuite-arquillian as well so it will system test the whole 'extension suite' with every build? Sweet!

**Comment by mposolda** [comment]
> Only downside to the super simple example is that it does not show an actual use case behind the extension functionality. But maybe an example is not the right place for that. Maybe its more suited for a blog post?

yes, feel free to write a blog and then we can maybe reference it from our blog. Yup, we try to have examples as easy as possible with focus on keycloak features. Having more complicated datamodel with more entities is more about JPA itself rather than about Keycloak, so it's likely not needed in the keycloak example IMO.

> Do I understand correctly that you put the example in the testsuite-arquillian as well so it will system test the whole 'extension suite' with every build? Sweet!

yes

**Pull request merged**
