### PR TITLE
OIDC logout: Support post_logout_redirect_uri param without requiring id_token_hint param

### LINKED ISSUE #12680: OIDC logout fails without id_token_hint
### Describe the bug

When trying to logout from Keycloak with a logout uri just containing the post_logout_redirect_uri param - without id_token_hint param - the following error is shown: "Missing parameters: id_token_hint".

I would expect to see a logout confirmation screen instead. Btw, that's the way it is done in "legacy" mode (property spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true), when just redirect_uri is specified.

**This is a critical bug, because the logout for several of our customer applications does no longer work with Keycloak 18.0.1 - the logout worked without id_token_hint in Keycloak 17.0.1.**

Showing a logout confirmation screen would conform to the OIDC spec, which states [1]:
"An id_token_hint is also RECOMMENDED when this parameter is included." (It's RECOMMENDED, *not* REQUIRED)
...
"At the Logout Endpoint, the OP SHOULD ask the End-User whether to log out of the OP as well. Furthermore, the OP MUST ask the End-User this question if an id_token_hint was not provided or if the supplied ID Token does not belong to the current OP session with the RP and/or currently logged in End-User. If the End-User says "yes", then the OP MUST log out the End-User."

[1] https://openid.net/specs/openid-connect-rpinitiated-1_0.html

### Version

18.0.1

### Expected behavior

In case a post_logout_redirect_uri is provided, but no id_token_hint is provided, a logout confirmation screen should be shown.

### Actual behavior

An error occurs: "Missing parameters: id_token_hint".

### How to Reproduce?

Use Keycloak 18.0.1 with default configuration.

Open the following URI:
http://localhost:8080/realms/master/protocol/openid-connect/logout?post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fadmin%2Fmaster%2Fconsole%2F%23%2Fserver-info

The following error page with the following content shown:

> We are sorry...
> Missing parameters: id_token_hint

### Anything else?

If you confirm that this is a bug, I would be happy to provide a PR fixing it.

### PR DESCRIPTION
**Pull request by danielFesenmeyer**
Closes #12680

### CODE REVIEW

**Review by mposolda — CHANGES_REQUESTED** [review]
MArking as "Request changes" for now.

**Comment by danielFesenmeyer** [comment]
Hi @mposolda,

I would be interested in a link to the corresponding draft of the RP-Initiated Logout from April 2022 - if it is a different one that this one here: https://openid.net/specs/openid-connect-rpinitiated-1_0.html. (I mentioned that link in the issue description here: https://github.com/keycloak/keycloak/issues/12680)

Of course our clients could change the logout endpoint calls to either include id_token_hint or client_id, but we have many customers with many applications. So we would have to wait with the Keycloak update (currently they are on 17.0.1) until all of our customers have adjusted all of their applications.
This is what we like to avoid.

**Comment by jbman** [comment]
Currently Keycloak users can't be logged out by the client applications, if the client application uses `post_logout_redirect_uri ` but wasn't changed to send the `id_token_hint`. The current 
draft from April 18, 2022 suggests to obtain explicit confirmation from the End-User before acting upon them (https://openid.net/specs/openid-connect-rpinitiated-1_0.html#Security). This is what the PR tries to achieve, right?
Is there a newer security recommendation, which suggests to ignore the request?

**Comment by danielFesenmeyer** [comment]
@jbman yes, that's exactly what the PR does.

**Comment by danielFesenmeyer** [comment]
Interesting: A previous version of the draft can be found here: https://web.archive.org/web/20220330141555/https://openid.net/specs/openid-connect-rpinitiated-1_0.html

That "old" version actually states that, in case post_logout_redirect_uri is specified, "id_token_hint is also REQUIRED" (in contrast to RECOMMENDED in the latest version)
Seems like the corresponding OIDC conformance test is based on that older version.

Btw, apart from a performance benefit, I see no (security) improvement by specifying the client_id parameter.

**Comment by mposolda** [comment]
@danielFesenmeyer Will it work for you that in case that backwards compatibility switch is enabled, then the `post_logout_redirect_uri` parameter will be accepted alone similarly like the `redirect_uri` parameter? In other words, it will be possible to use something like: `http(s)://example-host/auth/realms/my-realm-name/protocol/openid-connect/logout?redirect_uri=encodedRedirectUri` or something like `http(s)://example-host/auth/realms/my-realm-name/protocol/openid-connect/logout?post_logout_redirect_uri=encodedRedirectUri` . It seems this will address it for your client right?

**Comment by mposolda** [comment]
> Interesting: A previous version of the draft can be found here: https://web.archive.org/web/20220330141555/https://openid.net/specs/openid-connect-rpinitiated-1_0.html

Thanks for finding it.
 
> That "old" version actually states that, in case post_logout_redirect_uri is specified, "id_token_hint is also REQUIRED" (in contrast to RECOMMENDED in the latest version) Seems like the corresponding OIDC conformance test is based on that older version.

Yes, exactly. Allowing to use `post_logout_redirect_uri` alone means that Keycloak will fail to pass the OIDC RP-Initiated Logout conformance testsuite. Hence I would strongly prefer to accept it just if the backwards compatibility switch is enabled.

> Btw, apart from a performance benefit, I see no (security) improvement by specifying the client_id parameter.

The security benefit is that it is harder to use logout endpoint for Open Redirect. We had few reports that Keycloak Logout endpoint can be used as Open Redirector. It turned that the issue was that one (of the many) clients in the used deployment of the administrator, who reported the bug, used the `*` as Valid Redirect URI. Note that in case that one of many realm clients is mis-configured this way, the possibility is to use Logout endpoint as Open Redirector.

**Comment by sschu** [comment]
@mposolda Yes, for us it would be fine if `post_logout_redirect_uri' works like 'redirect_uri' only when the compatibility switch is enabled.

**Comment by mposolda** [comment]
@sschu @danielFesenmeyer Cool, Thanks for the confirm!

Could you please update the PR according to it?

I think that in that case, you can revert the changes in `RPInitiatedLogoutTest`, but possibly add new test instead in the `LegacyLogoutTest`, which contains some tests with the legacy switch enabled (but so far only with the `redirect_uri` parameter).

**Comment by danielFesenmeyer** [comment]
@mposolda Thanks for your explanations.
I will update the PR accordingly.

**Comment by sschu** [comment]
@mposolda Any chance this could make it into a 18.0.3? We just cannot rollout KC18 in the current state because we would break customer applications.

**Comment by danielFesenmeyer** [comment]
@mposolda, @sschu: Updated the PR accordingly: `post_logout_redirect_uri` is now handled the same way as `redirect_uri` when in "legacy mode"- when not in legacy mode, either `client_id` or `id_token_hint` is required.

**Review by mposolda — APPROVED** [review]
@danielFesenmeyer Thanks!

**Comment by mposolda** [comment]
@sschu @danielFesenmeyer I am not sure about 18.0.3 . TBH I don't know when/if this release is going to happen and what changes are going to be included in it. You can discuss this with @stianst . Just a note that he is on PTO and returning on Monday July 11 (AFAIK the 18.0.3 won't happen before that date).

**Comment by sschu** [comment]
@mposolda @stianst Is there any chance to get a faster decision? 11.7. is a bit late, we are planning to do our final rollout of KC18 on 13.7.

**Pull request merged**
