### PR TITLE
fix: "narrow" fix to persist build time spi options

### LINKED ISSUE #33902: Not persisted config settings prevent server start
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Starting a newly built Keycloak 26.0.0 with ``kc start --optimized`` shows the following error and starting fails.

> ERROR: The following build time options have values that differ from what is persisted - the new values will NOT be used until another build is run: kc.spi-user-cache-default-enabled

When running ``kc build`` with have the following config setting in *keycloak.conf*:
``spi-user-cache-default-enabled=false``

Obviously the config parameter ``spi-user-cache-default-enabled`` is not added to the */generated-bytecode.jar/META-INF/keycloak-persisted.properties*, but at startup the ``org.keycloak.quarkus.runtime.cli.Picocli.checkSpiOptions(IncludeOptions, List<String>, List<String>)`` method checks current settings (including those from *keycloak.conf*) against the entries of this file. The ``currentValueStr=false`` does not match ``currentValue=null`` from the persisted properties, hence the error.

In Keyckoak 25.0.6 this problem did not exist! There was no ``checkSpiOptions()`` in the **Picocli** class.

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

All properties set at build-time must be recognized correctly at startup-time.

### Actual behavior

Starting Keycloak with --optimized fails when ``spi-user-cache-default-enabled=false`` has been set at build-time.

### How to Reproduce?

1. Put ``spi-user-cache-default-enabled=false`` into /conf/keycloak.conf
2. Run kc build
3. Run kc start --optimized

### Anything else?

This is not just related to property ``spi-user-cache-default-enabled``. This error will also occur with properties matching one of these patterns:
- kc.spi*-provider
- kc.spi*-provider-default
- kc.spi*-enabled

### PR DESCRIPTION
**Pull request by shawkins**
closes: #33902

Radical simplification from the changes proposed in #33760

### CODE REVIEW

**Review by vmuzikar — COMMENTED** [review]
Changes LGTM but I think we're missing an integration test aiming for this particular fix.

**Comment by shawkins** [comment]
@vmuzikar @mabartos @Pepo48 the issue appears to be related to the "restart" handling in the KeycloakQuarkusServerDeployableContainer. Before the container successfully starts, it's deleting the data dir. On the next startup it's expecting to "restart" - meaning triggering a build. This no longer happens after the change in this pr. What I'm not understanding immeditately is the relationship between running build and the database being deleted - what build time side effects are there related to database setup?

**Review by pedroigor — DISMISSED** [review]

**Comment by pedroigor** [comment]
@vmuzikar Not sure. What you mean by working by accident?

**Comment by shawkins** [comment]
After talking things over with @pedroigor we determined that the arquillian tests are reliant upon the profile.properties for manipulating features, which is effectively broken once we persist the spi build time options. I will take a pass at removing the use of profile.properties and --optimized from the arquillian tests so that we can just rely on the real auto-build.

**Comment by shawkins** [comment]
@vmuzikar @pedroigor @Pepo48 @mabartos updated with initial changes to just use auto-builds. There will likely be a few additional clean ups, then some quarkus integration test to fully confirm we're persisting things.

What we could do differently:
- keep --optimized / log scraping - my assumption was there is only minimal value in skipping the auto-build checks, but if anyone feels differently we can instead react to the logs and signal dropping the --optimized
- I don't like the usage of the profile.properties the quarkus server - so it was removed from the runtime here. However how we specify features enabled / disabled in quarkus via a string list isn't ideal for testing - if we could do this directly from individual properties in the config, it would be easier. I had started down that path a while ago with versioned features: https://github.com/keycloak/keycloak/blob/47a7d9c12eac55980b083d7dc2da16643ef3dd32/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/Environment.java#L245 - but abandoned it after seeing how involved the test changes would be. So I'm removing the usage of the PropertiesProfileConfigResolver here also because it's not doing anyting - but we could revisit that. Alternatively we could make changes to both the KeycloakProcessor and Picocli (or just in one place with https://github.com/keycloak/keycloak/pull/33760) to persist / check the profile.properties. 

The test suite logic also seems to start the container before applying the necessary configuration, then restarts the container. A follow-up would be good to eliminate this first startup and instead rely on "client" side capturing of the configuration (which is very similar to KeycloakQuarkusConfiguration).

**Comment by pedroigor** [comment]
> * keep --optimized / log scraping - my assumption was there is only minimal value in skipping the auto-build checks, but if anyone feels differently we can instead react to the logs and signal dropping the --optimized

IMO, the key point is to avoid increasing test execution time significantly, ideally reduce it. If auto-build is faster, the same, or slightly worse, I think it is worth relying on auto-builds (and the auto-build check) to make this simpler.

**Pull request closed without merging**
