### PR TITLE
[KEYCLOAK-17872] Add missing HTTPClient properties

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: ruromero <rromerom@redhat.com>

Fix https://issues.redhat.com/browse/KEYCLOAK-17872

### CODE REVIEW

**Comment by ruromero** [comment]
Is there interest in this PR?

**Comment by mabartos** [comment]
@ruromero Thanks for you PR. I've recently make similar PR. Please take a look at it and we can merge our work somehow. See #8165

**Comment by ruromero** [comment]
@mabartos feel free to cherry-pick this PR into yours. I needed it for a customer and would be great to have it in the base code one way or another.

**Comment by ruromero** [comment]
Closed by https://github.com/keycloak/keycloak/pull/8165

**Pull request closed without merging**
