### PR TITLE
Deprecate old remote store (feedback)

### LINKED ISSUE #32577: Deprecate old remote store if persistent sessions performs good enough for A/P
* Introduce a new feature "remote Infinispan supported" which is then deprecated
* On Keycloak startup check the CacheManager if remote store in cache XML is configured in any cache. If the feature is not enabled, don't start Keycloak
* Write release notes and migration guide -> point people to persistent sessions for user sessions. No replacement for authentication session or other sessions in remote store. Also note that remote store was never supported, except in Keycloak 23+24 when used with multi-site setups.

### PR DESCRIPTION
**Pull request by pruivo**
Closes #32577

### CODE REVIEW

**Comment by pruivo** [comment]
@ahus1 I'm unsure how to make this less technical based on the feedback received. Let me know if what I wrote is useful or not.

**Comment by ahus1** [comment]
@pruivo - I like the non-technical approach of the updated release notes. 

I saw that this was now wrapped under one heading "Highly available multi-site deployments", which might be misleading. So I split part of it under a new heading "External {jdgserver_name} in a single-site setup" so people will not miss reading it if they use a single-site setup. 

Please let me know your thoughts.

**Comment by pruivo** [comment]
@ahus1 yes I did. I noticed that `Highly available multi-site deployments` is already present in the notes, and it wouldn't make sense to me to create another section for the "same" topic. 

It looks good to me. Let's grab feedback from others.

**Review by ahus1 — APPROVED** [review]

**Comment by pruivo** [comment]
@ahus1 looks good to me :+1:

**Pull request merged**
