### PR TITLE
KEYCLOAK-19482 Generate map entity cloners

### PR DESCRIPTION
**Pull request by hmlnarik**
Based on #8550

### CODE REVIEW

**Review by martin-kanis — CHANGES_REQUESTED** [review]
Great work @hmlnarik! I've just few cosmetic comments/questions.

**Review by mhajas — COMMENTED** [review]
Nice work @hmlnarik, the cloners look great. Seem to be exactly what we need to continue with our work. I added few questions into the code, mostly where I wasn't sure why it is there or what it does.

**Review by mhajas — APPROVED** [review]
@hmlnarik I cannot see any option to resolve the comments. I think only you can do it. From my point of view, all of them can be resolved. So I am approving.

**Review by martin-kanis — APPROVED** [review]
Thanks @hmlnarik! Looks good to me.

**Pull request merged**
