### PR TITLE
KEYCLOAK-18328 "access_denied" instead of "interaction_required" should

### PR DESCRIPTION
**Pull request by y-tabata**
JIRA ticket: https://issues.redhat.com/browse/KEYCLOAK-18328

### CODE REVIEW

**Comment by mposolda** [comment]
@y-tabata Thanks! Can you please add the test for this?

**Comment by y-tabata** [comment]
@mposolda Thank you for reviewing. Currently, there are cancel logics in `UsernamePasswordForm` and `LoginPage`, but there is no cancel button in the default login theme. So if we need to add a test, I think we need to add a custom theme and select it as the theme. This time, the code change is little, but do we need such a large-scale test? If yes, I prepare for the test. And if you have any idea, I would appreciate it.

**Comment by mposolda** [comment]
@y-tabata Ah, I see. When looking into this, it looks to me that exactly same issue can be seen for the CANCELLED_AIA as well? So when user press "Cancel" in some AIA screen (For example when user is requested to update password, but press Cancel), then I believe the "access_denied" should be returned as well instead of "interaction_required" . WDYT?

It looks that "interaction_required" is suitable mostly just for the cases when there is "prompt=none" sent, but interaction is needed and Keycloak needs to be display some form.

So regarding this, I suggest to change the status also for the AIA and then add the test for AIA (Or see if we already have some existing test and re-use it). It seems there are some test for this in the package "org.keycloak.testsuite.actions", so hopefully something can be used.

**Comment by y-tabata** [comment]
@mposolda Thanks.
> When looking into this, it looks to me that exactly same issue can be seen for the CANCELLED_AIA as well? So when user press "Cancel" in some AIA screen (For example when user is requested to update password, but press Cancel), then I believe the "access_denied" should be returned as well instead of "interaction_required" . WDYT?

You're right.
However, when we click "cancel" in some AIA screen, we catch "kc_action_status=cancelled" and "code", not "error". This is because context success [1].
So, it's difficult to test using some AIA screens, too. Is my understanding correct?

[1] https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/services/resources/LoginActionsService.java#L1030

**Review by mposolda — APPROVED** [review]
@y-tabata I see. I've looked at the sources and confirm that you are right. So this issue is applicable just for the case of custom theme with the "Cancel" button on the login screen and no easy way to test this. Thanks

**Comment by y-tabata** [comment]
@mposolda Thanks!

**Pull request merged**
