### PR TITLE
[KEYCLOAK-17254] [KEYCLOAK-18267] Fixes

### PR DESCRIPTION
**Pull request by iankko**
<hr/>

    [KEYCLOAK-17254] Adaptively add the default modular JVM options
    to the "javaVmArguments" to start the cache server container with,
    if the JVM used to run the cache server is modular (JDK 9+)
    
    Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

Fixes issues / errors like:
```
Listening for transport dt_socket at address: 6001
org.jboss.modules.ModuleNotFoundException: java.se
	at org.jboss.modules.Module.addPaths(Module.java:1266)
	at org.jboss.modules.Module.link(Module.java:1622)
	at org.jboss.modules.Module.relinkIfNecessary(Module.java:1650)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:296)
	at org.jboss.modules.Main.main(Main.java:437)
```
when running Cross-DC tests on hosts having both JDK 8 & JDK 11 installed (e.g. recent Fedora or RHEL-8.1 systems).

<hr/>

    [KEYCLOAK-18267] Fix 'java.lang.NoClassDefFoundError: Could not initialize class org.jboss.marshalling.river.RiverMarshaller'
    error for:
    
    * org.keycloak.testsuite.crossdc.LastSessionRefreshCrossDCTest and
    * org.keycloak.testsuite.crossdc.SessionExpirationCrossDCTest
    
    tests, when running cross-DC tests with JDK 11
    
    Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

Fixes issues / errors like:
```
java.lang.NoClassDefFoundError">java.lang.NoClassDefFoundError: Could not initialize class org.jboss.marshalling.river.RiverMarshaller
        at org.jboss.marshalling.river.RiverMarshallerFactory.createMarshaller(RiverMarshallerFactory.java:54)
...
```
when running Cross-DC tests on hosts having both JDK 8 & JDK 11 simultaneously installed with `-Pjava11-auth-server` profile enabled.

<hr/>

### CODE REVIEW

**Comment by iankko** [comment]
@vramik @vmuzikar @tkyjovsk @pdrozd PTAL (especially at the 2-nd commit once got a chance) **
@mposolda PTAL (especially at the 1-th commit once got a chance) **

Thanks,
Jan

** Of course you are welcome to review the PR as a whole, just your primary look at selected change is appreciated. Thanks, Jan

**Comment by iankko** [comment]
Corresponding testing pipeline runs for the change:
* Adapter: https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/410/
* Server: &nbsp; https://keycloak-jenkins.com/job/universal-test-pipeline-server/469/

**Comment by tkyjovsk** [comment]
@iankko I'm waiting for PR #7774 for KEYCLOAK-13757 to be reviewed.

I have also cretated branch `KEYCLOAK-18267_KEYCLOAK-17254_KEYCLOAK-13757` which includes all these changes including some necessary changes that are needed to merge all of these issues, and I successfully ran the tests:

https://keycloak-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/pipelines/job/universal-test-pipeline-server/2708/testReport/

I suggest merging this PR first before merging PR #7774.

**Comment by iankko** [comment]
> @iankko I'm waiting for PR #7774 for KEYCLOAK-13757 to be reviewed.

Briefly went through the code changes & LGTM AFAICT.

> 
> I have also cretated branch `KEYCLOAK-18267_KEYCLOAK-17254_KEYCLOAK-13757` which includes all these changes including some necessary changes that are needed to merge all of these issues, and I successfully ran the tests:
> 

Nice, thanks!
> 
> I suggest merging this PR first before merging PR #7774 because 1 additional commit is needed to adapt KEYCLOAK-13757 to changes in this PR.

Either way WFM. Let's do it following the way which is better for your preference / convenience.

**Comment by iankko** [comment]
@pdrozd @vramik @vmuzikar @mposolda Any feedback / reviews on the PR? (asking because according to the comment above, this would be great to be merged sooner than https://github.com/keycloak/keycloak/pull/7774 one)

PTAL once got a chance

Thanks,
Jan

**Review by vmuzikar — APPROVED** [review]
AFAICT (e.g. CrossDC tests are a bit outside of my expertise :)), looks good to me. My only concern is the renaming of `infinispan-jboss-marshalling,10.1.8.Final,Apache Software License 2.0` which seemed a bit suspicious to me, but I'm sure it is an intentional change hence approving. @iankko Thanks!

**Comment by iankko** [comment]
> AFAICT (e.g. CrossDC tests are a bit outside of my expertise :)), looks good to me. My only concern is the renaming of `infinispan-jboss-marshalling,10.1.8.Final,Apache Software License 2.0` which seemed a bit suspicious to me, but I'm sure it is an intentional change hence approving. @iankko Thanks!

Thanks for looking, Vashek! Asked you for review, since looked you touched some of the files, the PR is changing (IIRC that `jvm.extra.args` functionality was contributed by you. Since changing it again, is great to have your opinion if it's OK to be modified).

And for that file renaming part, yes, it's intentional. Since other (the remaining license files in that directory follow the `groupId,artifactId,versionId` form (IOW comma character is the delimiter). That renamed file was the only one having dot between `groupId` & `artifactId`. So renamed it to follow the naming scheme used by other files.

**Review by mposolda — APPROVED** [review]
@iankko @tkyjovsk @vmuzikar Thanks for this work and review. I am approving and merging this to unblock the further work on cross-dc tests.

**Comment by iankko** [comment]
> @iankko @tkyjovsk @vmuzikar Thanks for this work and review. I am approving and merging this to unblock the further work on cross-dc tests.

@mposolda Wonderful, TYVM! 

@tkyjovsk -^ https://github.com/keycloak/keycloak/pull/7774 should be G2G now too.

**Pull request merged**
