### PR TITLE
KEYCLOAK-14787: Update dependencies for new account console

### PR DESCRIPTION
**Pull request by ssilvert**
Ran npm audit fix.  Updated dependencies for lodash, acorn, and minimist.

### CODE REVIEW

**Comment by ssilvert** [comment]
Running UI tests.  Build number 969.

**Comment by ssilvert** [comment]
> Running UI tests. Build number 969.

UI Tests passed except for known failures.  No new failures found.

**Comment by ssilvert** [comment]
@abstractj Please review and merge if you think it looks good.

**Review by abstractj — APPROVED** [review]
@ssilvert LGTM

**Pull request merged**
