### PR TITLE
[KEYCLOAK-13924] Enable account linking when using token exchange mechanism

### PR DESCRIPTION
**Pull request by elepedus**
Allows a federated identity link for an existing user to be created when using external token exchange, provided:
1. There isn't already a linked account
2. Duplicate emails are disabled in the realm
3. A verified email is supplied by the provider
4. The "Trust Email" setting is enabled for the provider

### CODE REVIEW

**Review by stianst — CHANGES_REQUESTED** [review]
I'm strongly against adding this. Token exchange should not permit adding linking to existing users. That would be the equivalent of an application updating a users credentials through account linking.

**Comment by elepedus** [comment]
@stianst We are between a rock an a hard place. Without this feature, our 10k or so existing users would not be able to log in to the new game without first visiting our website on a different device and performing the account linking.

How could we implement this in a way that is acceptable to you?

**Comment by stianst** [comment]
I'd open a discussion on the dev mailing list around this if you do want to contribute something. Although, from my perspective any best practices around OAuth/OIDC recommends using an embedded user-agent. See https://tools.ietf.org/html/draft-ietf-oauth-native-apps-12 for example.

I have no clue about console/games development, but I would be very surprised if they don't support this flow.

Other alternatives could be CIBA or OAuth Device Grant. Both may come to Keycloak at some point, hopefully soon.

I can remember we discussed this somewhere, but not sure where. Perhaps also send a question on the user mailing list if anyone else has done something.

**Comment by stianst** [comment]
Adding some justification why I'm against this:

* It potentially allows applications to hijack a user account
* It allows applications to add links to a user account without the users awareness/consent

**Comment by elepedus** [comment]
Thanks for your thoughts and clarification, I think I'm starting to understand, but please bear with my if I'm barking up the wrong tree:

Your first objection is that a malicious application could perform the external token exchange using a token that does not belong to the user, thereby associating their KC account with an IdP account that is controlled by a malicious third party, thereby allowing hijacking of the user's KC account.

Your second objection is that, once an app has acquired a user's third-party token, it can perform the link without requesting the user's approval.

Is that correct?

**Comment by stianst** [comment]
#1 Not quite - the malicious application may have a valid token for the user, for example by making the user grant some access to for example view their profile in GitHub. That could then be used to escalate priviledges to gain full access to the user account

#2 Yes. A user should control if they want to enable social login to their Keycloak account, not an application

**Comment by elepedus** [comment]
Ok, now I think I understand. So if our deployment provides & trusts eg Sony as an IdP and user A has an old Sony account that they never use, but has the same email address, then a compromise of said Sony account would allow the attacker to get a Sony token which they could use to link accounts and gain control of the user's KC account.

**Comment by elepedus** [comment]
Only thing I'm not sure about is how that's any different to the browser-based flow? Surely if a malicious party compromised a Sony account with a weak password, they could just enter said password into the browser and link accounts that way.

What am I missing?

**Comment by stianst** [comment]
Only if automatic account linking is enabled, which is something we don't recommend. Further, there's a difference between a login flow to link, and just linking with some access token, which is the case here.

I'm going to close this for now - as I mentioned please open discussions on the mailing list around this. That way we can include a wider audience and perhaps there are others that have solutions for this already. Again, all specs recommend using standard redirect based flows - I would be very surprised if consoles are not able to integrate cleanly with OAuth/OIDC these days.

**Pull request closed without merging**
