### PR TITLE
Update realm-config.adoc

### PR DESCRIPTION
**Pull request by farnulfo**

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you for taking the time to provide this change. I had a look at the current Admin UI of Keycloak 25.0.0, and found a button "Add User" as stated in the docs:

image

Therefore I think the docs should stay as is and the text should not be changed. 

If you think the docs should still be changed, please provide a screen shot and the version number of Keycloak you are using.

**Comment by jonkoops** [comment]
The only time there is a label shown with the text 'Create new user' is when the list of users [is completely empty](https://github.com/keycloak/keycloak/blob/c90c06f70d8720588d89953a68c7460962329a4e/js/apps/admin-ui/src/components/users/UserDataTable.tsx#L359). Not sure under which conditions that would occur.

**Comment by ahus1** [comment]
@jonkoops - thank you for for pointing this out to me. This is correct, and actually the "Add User" button is not available when there is no user. 

In the context of this documentation, a new realm was created, so the list of users will always be empty. Therefore I'm approving. 

Thank you for this PR @farnulfo!

image

**Review by ahus1 — APPROVED** [review]

**Comment by ahus1** [comment]
Your change will be available in the docs once KC26 has been released which is expected to be at end of September.

**Pull request merged**
