### PR TITLE
KEYCLOAK-14687: Pbkdf2PasswordHashProviderFactory does not use DEFAULT_ITERATIONS

### PR DESCRIPTION
**Pull request by testn**

### CODE REVIEW

**Comment by stianst** [comment]
This doesn't actually matter as it will actually use the default from the PasswordPolicy - see https://github.com/keycloak/keycloak/blob/master/server-spi/src/main/java/org/keycloak/models/PasswordPolicy.java#L78

Honestly it would have been better if the default value was in the password hashing provider, and not in the password policy. As the default value should be dependent on what algorithm is selected.

**Comment by testn** [comment]
I just tried to make the code to be consistent with Pbkdf2Sha256PasswordHashProviderFactory and Pbkdf2Sha512PasswordHashProviderFactory. @stianst  Are you saying there is a better way to do this?

**Comment by stianst** [comment]
Was kinda just thinking out loud ;)

Changes you've done are an improvement, but doesn't make any changes to how KC works as it doesn't use the default iterations from the hashing provider, but rather the default from the password policy. That's an enhancement we can do later. So I'll accept this as it doesn't hurt and cleans things up a bit.

**Review by stianst — APPROVED** [review]

**Review by stianst — APPROVED** [review]

**Comment by testn** [comment]
If you can lay down how you want to change it, I might take a stab at it @stianst

**Pull request merged**
