### PR TITLE
KEYCLOAK-14747 LDAP pooling should include SSL protocol by default

### PR DESCRIPTION
**Pull request by reda-alaoui**
Relates to https://issues.redhat.com/browse/KEYCLOAK-14130

### CODE REVIEW

**Comment by VinodAnandan** [comment]
@reda-alaoui Thank you for your contribution.

As mentioned in the following contribution guidelines, the commit message needs a JIRA number. Sometimes you may find the issue in JIRA backlog (https://issues.redhat.com/projects/KEYCLOAK/ ). If you can't find it, could you please create a JIRA issue and prefix it?

https://github.com/keycloak/keycloak/blob/master/CONTRIBUTING.md

**Comment by reda-alaoui** [comment]
@VinodAnandan , I fixed the PR title and the commit message.

**Comment by VinodAnandan** [comment]
Thanks @reda-alaoui

**Review by pedroigor — COMMENTED** [review]
@mposolda This one LGTM. Can we just have it ?

**Review by mposolda — APPROVED** [review]
@reda-alaoui Thanks for the PR!

@pedroigor +1

**Pull request merged**
