### PR TITLE
KEYCLOAK-7166 Added the possibility of not logging out of remote idp …

### PR DESCRIPTION
**Pull request by torbjornsk**
…on browser logout, by passing a query param containing the id of the identity provider

### CODE REVIEW

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Comment by pdrozd** [comment]
@keycloak-ci-bot test

**Comment by mposolda** [comment]
@torbjornsk Lookds good, Thank! We just need to wait until jenkins build is successfully triggered and finished.

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Pull request merged**
