### PR TITLE
Use version specific tag for Keycloak images in the docs

### LINKED ISSUE #26819: Use version specific tag for Keycloak images in the docs
### Description

The documentation in upstream currently uses `:latest` to point to images. 

This is problematic in upstream, as people might upgrade their version of Keycloak unexpectedly to another major version by just re-running the script. 

It is also problematic in downstream to produce a documentation specific to a release. Also in downstream, the `latest` tag doesn't exist (possibly for the reasons stated above).

### Details

I'll prepare a PR

### PR DESCRIPTION
**Pull request by ahus1**
Closes #26819

### CODE REVIEW

**Comment by ahus1** [comment]
@vmuzikar - I see that downstream is using labels like `22` and `22-8`. To be able to use such a label downstream, I added the new attribute. 

I still need to test this fully when rendering the public site. By just looking at the AsciiDoc source, WDYT about this change?

**Review by vmuzikar — COMMENTED** [review]
In general, LGTM. I think you've covered all the affected places. Thanks for this change @ahus1!

One question. What will be the `{version}` (and therefore `{containerLabel}` set to? IMHO it'd make sense to set it to the "content stream" label, e.g. `22`, not respin specific label like `22-8`.

**Comment by ahus1** [comment]
@vmuzikar - I reached out to people to understand if `22-8` is `22.0.8` or just another arbitrary number, still waiting an answer. Can you give it to me :smile:?

I suppose I'll be +1 for `22`.

**Comment by ahus1** [comment]
Adding to the previous comment: In downstream, we'll set `containerLabel` with a custom logic and not to `version` directly.

**Comment by ahus1** [comment]
ok, works nicely in for the website, merging: 

image

**Comment by ahus1** [comment]
@vmuzikar - please review and approve when you have the time. Thanks!

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@ahus1 My apologies, I didn't realized we're setting `{version}` also in the upstream. I don't think it makes sense to use a specific version tag instead of `latest` here. The guides (unlike the regular docs) are "floating" and AFAIK not released and archived anywhere. So IMHO we should not tie it to a specific version. Question is how do we want our users to use it. I'd argue we should always push for the most recent version, i.e. `latest`.

Downstream is a different story.

CC @keycloak/cloud-native

**Comment by ahus1** [comment]
@vmuzikar - a screenshot is always helful :-)

I've updated the commit to now always set the `containerlabel` to `latest` for upstream. This way it should render as before. Ready for another round of review.

**Review by vmuzikar — APPROVED** [review]
@ahus1 Thank you, LGTM now.

**Pull request merged**
