### PR TITLE
Stabilizing Model tests for Infinispan 12.1.7

### LINKED ISSUE #9867: Unstable model tests when starting multiple Infinispan instances
### Describe the bug

When starting multiple instances of Infinispan during test like CacheExpirationTest, there is due to a race condition sometimes a NullPointerException that later leads to an InfinispanCache that doesn't start. Due to that, the tests fail. 

### Version

17.0.0-SNAPSHOT

### Expected behavior

The tests should not fail, even if multiple instances of Infinispan have been started.

### Actual behavior

New intermediate status: after some ugly workarounds for the time being, no timeouts in all the tests. 

Still, some tests are unstable and fail on GitHub actions. I suspect the reason for that being some nodes not being able to join properly in some circumstances.

After the following exception

```
17:12:48,372 WARN  [org.infinispan.CLUSTER] (jgroups-10,node-1) ISPN000071: Caught exception when handling command TopologyJoinCommand{cacheName='org.infinispan.CLIENT_SERVER_TX_TABLE', origin=node-4, joinInfo=CacheJoinInfo{consistentHashFactory=org.infinispan.distribution.ch.impl.SyncReplicatedConsistentHashFactory@238f0359, numSegments=256, numOwners=2, timeout=240000, cacheMode=REPL_SYNC, persistentUUID=04c47294-d241-4b72-99f3-2a9f8b399971, persistentStateChecksum=Optional.empty}, viewId=2}
java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at org.infinispan.topology.ClusterTopologyManagerImpl.handleJoin(ClusterTopologyManagerImpl.java:225)
	at org.infinispan.commands.topology.CacheJoinCommand.invokeAsync(CacheJoinCommand.java:42)
	at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler$ReplicableCommandRunner.run(GlobalInboundInvocationHandler.java:252)
	at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler.handleReplicableCommand(GlobalInboundInvocationHandler.java:174)
	at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler.handleFromCluster(GlobalInboundInvocationHandler.java:113)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1391)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1314)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:133)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1458)
	at org.jgroups.JChannel.up(JChannel.java:784)
	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:913)
	at org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:355)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:363)
	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
	at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
	at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
	at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
	at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
	at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
	at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
	at org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
	at org.jgroups.protocols.Discovery.up(Discovery.java:300)
	at org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
	at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

there is the following message that node-4 leaves the cluster

```
17:12:48,398 INFO  [org.infinispan.CLUSTER] (jgroups-9,node-4) ISPN000094: Received new cluster view for channel ISPN: [node-1|3] (5) [node-1, node-2, node-4, node-5, node-3]
17:12:48,398 INFO  [org.infinispan.CLUSTER] (jgroups-9,node-4) ISPN100000: Node node-3 joined the cluster
17:12:48,418 INFO  [org.infinispan.CLUSTER] (pool-5-thread-3) ISPN000079: Channel ISPN local address is node-3, physical addresses are [127.0.0.1:58074]
17:12:48,418 INFO  [org.infinispan.CLUSTER] (pool-5-thread-2) ISPN000080: Disconnecting JGroups channel ISPN
17:12:48,420 INFO  [org.infinispan.CLUSTER] (jgroups-6,node-1) ISPN000094: Received new cluster view for channel ISPN: [node-1|4] (4) [node-1, node-2, node-5, node-3]
17:12:48,421 INFO  [org.infinispan.CLUSTER] (pool-5-thread-4) ISPN000080: Disconnecting JGroups channel ISPN
17:12:48,421 INFO  [org.infinispan.CLUSTER] (jgroups-6,node-1) ISPN100001: Node node-4 left the cluster
```

### How to Reproduce?

As it is an unstable test, it is difficult to reproduce locally; it mostly happens on GitHub actions. 

### Anything else?

This has previously been discussed in #9648

The problem caches joining was reported here and is fixed for Infinispan 13: https://issues.redhat.com/browse/ISPN-13231

Started a discussion upstream if this could be backported to 12.1.x: https://infinispan.zulipchat.com/#narrow/stream/118645-infinispan/topic/NPE.20in.2012.2E1.2E7.2EFinal.20when.20handling.20TopologyJoinCommand

For now, will assume that we'll use the workaround for the test to not start too many caches at a time and re-activate the workaround so that the caches don't start all at once.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #9867

### CODE REVIEW

**Comment by ahus1** [comment]
This contains the one commit related to the referenced parent ticket. The model tests are expected to fail with timeouts as #9840 has not been merged.

**Comment by martin-kanis** [comment]
There's one timeout and `Interrupted while waiting for subscription to complete` message but not sure if that is cased by the changes in this PR.

**Comment by ahus1** [comment]
@martin-kanis - this issue is cased by PersistenceManager, and that one has been addressed in #9648 that was merged after this PR was created, so this was kind of expected. I expected a timeout, now I see an interrupted exception, but the cause remains the same.

I now rebased this PR, tests are running again, now I expect the model tests to be green in ~60 min

**Review by martin-kanis — APPROVED** [review]
Looking good, thanks Alexander!

**Comment by jonkoops** [comment]
Everything looks green, nice work 👍

**Review by hmlnarik — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
