### PR TITLE
KEYCLOAK-8359 Node.js tests removed from arquillian testsuite

### PR DESCRIPTION
**Pull request by mhajas**
Tests are present in https://github.com/keycloak/keycloak-nodejs-connect repository

### CODE REVIEW

**Review by vmuzikar — CHANGES_REQUESTED** [review]
I believe the tests were not yet migrated to the [native Node.js testsuite](https://github.com/keycloak/keycloak-nodejs-connect/tree/master/test) - mainly `timeoutsTest` and `sessionTest`. Correct, @abstractj? This was the only reason for keeping them in the Arquillian testsuite.

**Comment by abstractj** [comment]
@vmuzikar you're correct. At the moment we do not provide anything like that. So first, I believe we need to write these tests to the Node.js adapter and later remove it from Arquillian testsuite.

**Comment by mhajas** [comment]
@vmuzikar @abstractj Hi, maybe I misunderstood something, I was a little bit lost in syntax of node.js tests, but I went through all tests and this is what I matched with what part of arq tests:

* simpleLoginTest: https://github.com/keycloak/keycloak-nodejs-connect/blob/master/test/keycloak-connect-web-spec.js#L54
* timeoutsTest: 
  * First part: https://github.com/keycloak/keycloak-nodejs-connect/blob/master/test/grant-manager-spec.js#L91
  * Second part: https://github.com/keycloak/keycloak-nodejs-connect/blob/master/test/grant-manager-spec.js#L123
* sessionTest I was thinking a lot about this test and do we really need it? I would say it is basically testing Keycloak not node.js adapter am I wrong?

**Comment by vmuzikar** [comment]
@mhajas I've tried to do some quick coverage review and comparison and I believe the native Node.js testsuite really doesn't exactly cover the scenarios from the Arquillian tests.

Here's what I believe the Node.js testsuite doesn't currently cover:
* **simpleLoginTest:** Login "persistence" - when the Login button is clicked and user is logged in already, nothing happens (no login form is displayed) and the tokens are the same.
* **timeoutsTest:** I agree that the tests you linked are similar to the timeoutsTest. However, there's a bit different approach. Unlike the timeoutsTest, the native Node.js test is not passively waiting for the token to expire to see what happens, how the adapter as whole reacts. Instead, it directly asks the grant manager to refresh the token. Also, the native tests don't test the SSO timeout.
* **sessionTest:** This specifically cover [KEYCLOAK-3284](https://issues.jboss.org/browse/KEYCLOAK-3284).

I might have missed something but I believe the mentioned scenarios should be migrated to the Node.js testsuite before removing them from the Arquillian testsuite.

**Comment by abstractj** [comment]
@mhajas even though tests look similar to the Arquillian testsuite, they don't cover the scenarios @vmuzikar mentioned. I believe we should migrate, before remove anything.

**Comment by mhajas** [comment]
@vmuzikar @abstractj I am still not convinced that all of those scenarios are not covered/should be tested. But you are much more experienced with node.js so I will try to add all those scenarios to nodejs repository. I will probably approach one of you in case I will need some help.

**Review by abstractj — APPROVED** [review]

**Pull request merged**
