### PR TITLE
Avoid clients exchanging tokens using tokens issued to other clients

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by stianst — APPROVED** [review]

**Comment by Raidok** [comment]
Wasn't this one of the ideas behind Token Exchange that you can get a new token targeted to another client?

Mentioned [here](https://www.keycloak.org/docs/latest/securing_apps/index.html#how-token-exchange-works):

> A client can exchange an existing Keycloak token created for a specific client for a new token targeted to a different client

**Comment by Sobakaa** [comment]
I second @Raidok's question - was there some issue this merge covers? Since our token exchange cases are now broken we'd like to know what was the idea behind this change, so that we can align our implementation or workaround with keycloak's vision.

**Comment by pedroigor** [comment]
@Raidok Perhaps the title/description is not so good, but the main change was to avoid public clients from exchanging tokens if they are not the holder of the token (`azp` claim).

@Sobakaa Could you please describe how you are using token exchange and what is broken?

**Comment by 01epa** [comment]
@pedroigor Can you point to RFC which you use to cover this requirement?

**Comment by pedroigor** [comment]
@01epa You're right. But the spec is not very clear about the relationship between resource, audience, and scopes. In the end is up to AS to decide how token exchange requests should be accepted.

It should be possible to not set the `audience` but the server will only accept the request if the requesting client is among the audiences of the subject token.

**Comment by pedroigor** [comment]
@Sobakaa We are considering that tokens without an audience is an indication of a invalid bearer token usage. In fact, a RS should check the audience before accepting a bearer token.

I understand this brings additional complexity when configuring clients and how their tokens are built, but it is better aligned with the specs.

In the worst case, I think we could provide some flag to disable the audience check for confidential clients. But I'm not sure if that is the best way to go.

**Comment by gassan** [comment]
Why a client c1 can not request a token for c2 with own access token and secret of c2?
Here is clear that c2 is trusting to c1.

**Comment by s0ck4t7** [comment]
@pedroigor  Hello,
In our case,we have a "super_user" account login with "admin-cli" client(password grant) to get a "super_token".
We have a client "clientA" as audience.
We want to use "super_token" to exchange other users' token.
In old version(15),it works. But we get  "error_description": "Client is not within the token audience" in new version(20).
Should we use "super_user" login with "clientA" to get the "super_token"？It seems working in my test.

**Pull request merged**
