### PR TITLE
Make tests run on Oracle DB on the internal pipeline

### LINKED ISSUE #15643: Internal pipelines don't tests run for OracleDB or other database
### Area

storage

### Describe the bug

The internal pipelines have been switch to run Quarkus. Apparently the fix in #13642 hasn't been incomplete, and when the tests run on `db-allocator` the `keycloak.storage.connections.vendor` is not set, so the DB settings forwarded to the Quarkus CLI.

### Version

20.0.1

### Expected behavior

Tests should run on Oracle and all other databases.

### Actual behavior

Tests run on H2 all the time.

### How to Reproduce?

Have a look at the CLIs created in the internal pipelines.

### PR DESCRIPTION
**Pull request by ahus1**
This is a backport for KC20.

Closes #15643

### CODE REVIEW

**Comment by sguilhen** [comment]
rerun

**Comment by ahus1** [comment]
@sguilhen - as we found out today, those Wildfly checks don't run any more on the branch, so they will never report their status. Could you please approve this PR?

**Review by sguilhen — APPROVED** [review]

**Comment by ahus1** [comment]
@hmlnarik - this has been reviewed and approved, please merge. Thanks!

**Review by hmlnarik — APPROVED** [review]
Approving per @sguilhen 's approval

**Pull request merged**
