### PR TITLE
KEYCLOAK-11282 Fix KeycloakSpringBootConfigResolver could not be foun…

### PR DESCRIPTION
**Pull request by mhajas**
…d exception

### CODE REVIEW

**Review by pedroigor — CHANGES_REQUESTED** [review]
These changes partially solve the problem. We also need to cover multi-tenancy use cases, as we discussed. Although not exclusively to multi-tenancy.

Applications should be able to produce their own config resolver instances. By importing the configuration it could happen that two beans (config resolvers) are eligible for injection through the `org.keycloak.adapters.springboot.KeycloakBaseSpringBootConfiguration#setKeycloakSpringBootProperties` method. Thus, causing errors during startup.

I would propose the following changes https://github.com/pedroigor/keycloak/commits/KEYCLOAK-11282. It allows using a default config resolver if none is provided by the application while still allowing the application to provide its own config resolver instance.

**Comment by slaskawi** [comment]
I agree with Pedro. Also, may I ask for implementing at least one (even super simple) test, so that a similar issue won't happen in the future?

**Comment by pedroigor** [comment]
@slaskawi I'm afraid a good coverage is something we lack for Spring. We have been discussing increasing coverage for quite a long time, but we never managed to do it. But rely on quickstarts.

For this particular issue, I have a new quickstart that I would like to push.

In addition to that, there are plans to deprecate Spring adapter so I'm not sure if we want to invest in this right now. Write a single test where we have quite other functional areas to cover does not seem to be very useful so that we would probably need to write a few other tests to make sure we don't break the different combinations and usage of Spring Boot, Security, etc.

**Comment by mhajas** [comment]
@pedroigor Could we use `@Order` [annotation](https://www.baeldung.com/spring-order ) for this? Seems like if we set:

```java
@Order( Ordered.LOWEST_PRECEDENCE + 1 )
public class KeycloakAutoConfiguration extends KeycloakBaseSpringBootConfiguration
```

it could solve the problem you mentioned. WDYT?

**Comment by pedroigor** [comment]
@mhajas If it solves the problem I mentioned, sure.

However, I personally prefer having this more clear in the code than relying on annotations and the assumptions they provide. Also, not that applications should also be able to specify a simple `KeycloakConfigResolver` implementation without necessarily extend the `KeycloakSpringBootConfigResolver` type.

**Comment by mhajas** [comment]
Thank you for the explanation @pedroigor, I can see the issue with this PR now. Could you please send a new PR with your changes? I am closing this

**Comment by pedroigor** [comment]
See https://github.com/keycloak/keycloak/pull/6898

**Pull request closed without merging**
