### PR TITLE
Fix when importing empty uniqueMember attributes

### PR DESCRIPTION
**Pull request by ratcashdev**
see the comments in the code

### CODE REVIEW

**Comment by ratcashdev** [comment]
Submitting for master, but a backport for 1.9.x would be appreciated.

**Comment by mposolda** [comment]
Thanks for the PR. Two comments:
- Could you please create JIRA for this and use it in commit message? We try to have each bugfix associated with the JIRA for tracking purposes
- Could you use dnString.trim().isEmpty() ? Should be slightly safer.

**Comment by ratcashdev** [comment]
everything changed as requested.

**Comment by mposolda** [comment]
Thanks! Will backport to 1.9.x too

**Pull request merged**
