### PR TITLE
Clarifying the use of '--db-url-properties' option in its description and in the guide.

### LINKED ISSUE #12720: Clearify the use of `db-url-properties`
### Description

In the keycloak documentation (https://www.keycloak.org/server/all-config) it simply says about `db-url-properties`:

> Sets the properties of the default JDBC URL of the chosen vendor.

However, in what format does that need to be provided? What if I want to use multiple?

### PR DESCRIPTION
**Pull request by andre-nascimento6791**
Improvement on the description message for the option KC_DB_URL_PROPERTIES in the docs, in order to emphasize that the User/Developer need to provide also the first character according to the specific DBMS syntax. 

However, there was a suggestion of another approach: "There is the [DriverManager.getConnection(String url, Properties info)](https://docs.oracle.com/javase/8/docs/api/java/sql/DriverManager.html#getConnection-java.lang.String-java.util.Properties-) API where you can pass the connection properties separately as Properties object."

The suggestion is open to discuss and under analysis.

Closes #12720

### CODE REVIEW

**Review by vmuzikar — DISMISSED** [review]
@andre-nascimento-rh Thanks, LGTM. But before merging I'd like someone from @keycloak/store-maintainers to approve as well as it's basically a store area.

> However, there was a suggestion of another approach: "There is the [DriverManager.getConnection(String url, Properties info)](https://docs.oracle.com/javase/8/docs/api/java/sql/DriverManager.html#getConnection-java.lang.String-java.util.Properties-) API where you can pass the connection properties separately as Properties object."

I don't think we can use that since we're fully relying on Quarkus with creating DB connections. Notice that the `db-url-properties` option in the end [maps to `quarkus.datasource.jdbc.url`](https://github.com/keycloak/keycloak/blob/c17fcd49c84e835d0c7aea45704327a3e8fb4239/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java#L44-L49). But I'll leave the store team to chime in.

I also noticed this PR's description is prefixed with `[WIP]`. Does it mean you still plan to work on it, hence it shouldn't be merged in current state? If so, I'd suggest converting this PR to draft instead of using a prefix to make the semantics clear. Thanks.

**Comment by andre-nascimento-rh** [comment]
Hello, @vmuzikar ,

I remove the `[WIP]` prefix on PR's title because, at least from my side, I don't plan to change anything else in this regard. I just added the `[WIP]` due to the possibility of the acceptance of the given suggestion and If I could be allowed/asked to implement the change. But you clarified that the @keycloak/store-maintainers has a valuable opinion is this matter.

Thanks.

**Review by abstractj — DISMISSED** [review]

**Review by pedroigor — COMMENTED** [review]
@andre-nascimento-rh I agree with the [last comment](https://github.com/keycloak/keycloak/issues/12720#issuecomment-1561088066) on the issue about being a bit smart about it. It would definitely improve the user experience.

As we know in advance the vendor (e.g.: `db`) we could do that fairly easy. We could even use a common format like `a=a,b=b,c=c` and automatically transform the to the expected vendor format.

If not wanted, I don't mind solving this through docs as herein proposed. I would just avoid including the characters and especially `etc` from the description.

A text like `Make sure to set the properties accordingly to the format expected by the database vendor.`

**Comment by andre-nascimento-rh** [comment]
@pedroigor , Thanks for sharing your valuable thoughts on this question.

I thought the [initial suggestion provided by 'mwalser' here](https://github.com/keycloak/keycloak/issues/12720#issuecomment-1559944824) is a feasible alternative to implement after 22 release. And I confess I thought an even more nice suggestion what @ahus1 [said in his comment here](https://github.com/keycloak/keycloak/issues/12720#issuecomment-1562812980).

Although, I agree to @vmuzikar [wrote down here](https://github.com/keycloak/keycloak/issues/12720#issuecomment-1564434227). Then I believe we'll go for only updating the docs to let it clearer by now.

I accepted your text suggestion and I complemented it to mention the need to append the right character. Please review it again. 

Thanks in advance.

**Review by vmuzikar — APPROVED** [review]
@andre-nascimento-rh Thanks, LGTM.

Let’s wait for @pedroigor's approval.

**Review by hmlnarik — APPROVED** [review]
+1 for fixing the help text for now

**Review by abstractj — APPROVED** [review]

**Pull request merged**
