### PR TITLE
KEYCLOAK-9646: Fix Servlet API OSGi import ranges

### PR DESCRIPTION
**Pull request by grgrzybek**

### CODE REVIEW

**Comment by hmlnarik** [comment]
@grgrzybek Could you please extract https://github.com/keycloak/keycloak/pull/5935/commits/3c798038736cdb84bdc0cee709549a875ce71ff6 into a separate pull request and squash the https://github.com/keycloak/keycloak/pull/5935/commits/3e33a11b34dc035f8e971a31d8c6cdca007422ca and https://github.com/keycloak/keycloak/pull/5935/commits/53708831757789b7ae69a3dba7b493fe635dd5c3 into a single commit? The 3c798038736cdb84bdc0cee709549a875ce71ff6 will need adjustments since changes FuseAdminAdapterTest.java effectively disable check that the javascript loaded the console properly. There needs to be `assertThat(Matchers.anyOf(<alternative for 7.1-2>, <alternative for 7.3+>)` instead

**Comment by grgrzybek** [comment]
I just squashed this PR and created a new one (#5936) with itest fixes - I'd really like you (or someone else) to adjust this test to work with different XPaths for different hawtios...

**Review by hmlnarik — APPROVED** [review]

**Comment by hmlnarik** [comment]
Thanks! That works perfectly, we can take over the testsuite changes and the non-testsuite part is fixed in this PR.

**Comment by hmlnarik** [comment]
@keycloak-ci-bot test

**Comment by grgrzybek** [comment]
@hmlnarik thank you very much!

**Comment by hmlnarik** [comment]
@keycloak-ci-bot test

**Comment by hmlnarik** [comment]
@keycloak-ci-bot test

**Pull request merged**
