### PR TITLE
KEYCLOAK-14497 Compilation error in UsernameTemplateMapperTest

### PR DESCRIPTION
**Pull request by vmuzikar**

### CODE REVIEW

**Comment by abstractj** [comment]
@miquelsi would you like to help on the review?

**Review by ssilvert — APPROVED** [review]
LGTM

**Review by miquelsi — APPROVED** [review]
Looks fine. Thanks.

**Comment by thomasdarimont** [comment]
The builds for this PR and #7179 are both passing. Would someone be so kind to merge one of the PRs to get the master / main to compile again? :)

Cheers,
Thomas

**Comment by Cracky5457** [comment]
it works, thanks, can't test other development without it

**Review by amdev74 — APPROVED** [review]

**Pull request merged**
