### PR TITLE
Fixing how e-mail attribute permissions are set for both USER_API and ACCOUNT contexts

### LINKED ISSUE #21751: v 22.0.0 rest-api, cleans user email when updating attributes (with user-profile enabled)
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

When using `PUT` against `/admin/realms/<realm>/users/<user_id>`
To update user's attributes
It has the side-effect of deleting user email

`{'attributes': {'phoneNumber': 'XXXXX'}}`

I use the same endpoint to update user name and to set required actions

But this issue is only observed when adding an attribute

Not happening when using keycloak:21

Happening when using:

- quay.io/keycloak/keycloak:nightly
- quay.io/keycloak/keycloak:22.0

### Version

22.0

### Expected behavior

Using put to set/update user's attributes, only changes attributes

### Actual behavior

Using put to set/update user's attributes, is also deleting user email

### How to Reproduce?

`PUT`: `/admin/realms/<realm>/users/<user_id>`

payload:
`{'attributes': {'phoneNumber': '9999999'}}`

### Anything else?

_No response_

### LINKED ISSUE #21791: User unable to save user profile attributes
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

Realm config
- accountv3 enabled
- User Profiles enabled
- Email as username on
- Edit username off

When a user attempts to save their profile (https://example.com/auth/realms/my-realm/account/#/) they receive a validation error on their username.

POST to `https://example.com/auth/realms/my-realm/account/`

```json
{ "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "username": "user@example.com", "firstName": "Name", "lastName": "Example", "emailVerified": false, "userProfileMetadata": { "attributes": [ { "name": "locale", "displayName": "locale", "required": false, "readOnly": false, "validators": {} }, { "name": "username", "displayName": "${username}", "required": true, "readOnly": true, "annotations": {}, "validators": { "username-prohibited-characters": { "ignore.empty.value": true }, "length": { "max": 255, "ignore.empty.value": true, "min": 3 } } }, { "name": "nickname", "displayName": "Nickname", "required": false, "readOnly": false, "annotations": {}, "validators": {} }, { "name": "firstName", "displayName": "${firstName}", "required": true, "readOnly": false, "annotations": {}, "validators": { "person-name-prohibited-characters": { "ignore.empty.value": true }, "length": { "max": 255, "ignore.empty.value": true } } }, { "name": "lastName", "displayName": "${lastName}", "required": true, "readOnly": false, "annotations": {}, "validators": { "person-name-prohibited-characters": { "ignore.empty.value": true }, "length": { "max": 255, "ignore.empty.value": true } } } ] }, "attributes": { "nickname": "AlteredField" } }
```

Response:
```json
{
    "errors": [
        {
            "field": "username",
            "errorMessage": "missingUsernameMessage",
            "params": [
                "${username}"
            ]
        },
        {
            "field": "email",
            "errorMessage": "error-user-attribute-required",
            "params": [
                "${email}"
            ]
        }
    ]
}
```

### Version

v22.0.0

### Expected behavior

User should be able to save their profile when

### Actual behavior

User receive error that their username is invalid/required when saving the profile

### How to Reproduce?

Setting the realm config as listed above

In Realm settings -> User Profile, for both username and email, if I set them as non-user-editable then I can save the settings but then during registration those fields are not present.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #21751
Closes #21791

### CODE REVIEW

**Comment by Romain7495** [comment]
someone can approve this PR ?

**Review by rmartinc — APPROVED** [review]
@pedroigor LGTM!

**Review by ahus1 — APPROVED** [review]
Approving as of @rmartinc review. Thank you!

**Comment by ahus1** [comment]
@pedroigor - will you create a backport for this PR? I didn't see a patch milestone configuration on the parent issues, but looking at their titles it might be a good idea?

**Comment by pedroigor** [comment]
Yeah, I need to backport. Working on it. Thanks.

**Pull request merged**
