### PR TITLE
KEYCLOAK-19329 Fix message for access token response claim in admin ui

### LINKED ISSUE #9364: includeInAccessTokenResponse.label and includeInAccessTokenResponse.label.tooltip english messages are missing
### Describe the bug

includeInAccessTokenLabel

As you can see from attached screenshot includeInAccessTokenResponse.label and includeInAccessTokenResponse.label.tooltip english messages are missing.

This bug exists also in previous versions.

### Version

16.1

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by srose**
Closes #9364

### CODE REVIEW

**Review by ahus1 — DISMISSED** [review]
I see that the text changes included here match the suggested texts in #7371, therefore I approve them.

**Comment by ahus1** [comment]
Hi @srose - this PR looks good. 

To link this PR with the original issue, please add `Closes #9364` to the description of this issue. 

For future PRs, please note that the [contributing guidelines of the repository](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md) ask for some formalities in the commit message since January this year:

```
A brief descriptive summary

Optionally, more details around how it was implemented

Closes #1234
```

**Comment by srose** [comment]
Hi @ahus1,

thanks for your comments, the commit message should fit now.

**Comment by ahus1** [comment]
@ahus1 - thank you for the updated commit message. 

I also asked you to update the description of the issue. I see that this is still unchanged. Please add `Closes #9364` to the description so that GitHub links the PR to the issue. 

image

Thanks!

**Review by ahus1 — APPROVED** [review]
I see that the text changes included here match the suggested texts in #7371, therefore I approve them.

**Comment by ahus1** [comment]
Hi @abstractj - I see you've been involved in the related issue, therefore I wonder if you could merge this PR. 

I verified that the the changes in the PR match the texts provided in the original issue. 

Thanks!

**Review by abstractj — APPROVED** [review]

**Pull request merged**
