### PR TITLE
Ignore g-recaptcha-response in user profile validation

### LINKED ISSUE #29182: User profile Validation breaks with recaptcha
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

With the new user profile breaks profile validation, by default the max length of unmanaged attributes its 2048 and sometimes the g-recaptcha-response exceed that number breaking the registration. This make impossible to register.

Temporal solution, create the atributte in the user profile with lenght between 0 and 2400.

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

Ignore the g-recaptcha-response form data attributte in profile validation.

### Actual behavior

g-recaptcha-response form data attributte is take in consideration on profile validation.

### How to Reproduce?

Activate googles recaptcha wait for a google response over 2048 characters.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by alexagc**
Closes  #29182

### CODE REVIEW

**Review by jonkoops — DISMISSED** [review]
LGTM, but is there perhaps a way we could prevent this being sent in the first place?

**Comment by alexagc** [comment]
> LGTM, but is there perhaps a way we could prevent this being sent in the first place?

Its a mandatory param for later validation of recaptcha against google api, so its needed to send if recaptcha validation is activate

**Comment by jonkoops** [comment]
Gotcha, then let's see if we can merge this as-is.

**Comment by sguilhen** [comment]
@pedroigor can you quickly review this one? Changes make sense to me, but I think it is good to get your input.

**Review by pedroigor — APPROVED** [review]
@alexagc I changed the merge branch to `main` (the PR was targeted to `release/24.0`) and updated the code to use the constant you introduced.

**Pull request merged**
