### PR TITLE
Keycloak 4427

### PR DESCRIPTION
**Pull request by bejondshao**
Use current thread classloader to load resouce instead of KeyStoreUtil classloader

### CODE REVIEW

**Comment by stianst** [comment]
I don't think thread classloader is guaranteed to be the correct classloader. ServletContext#getResourceAsStream might be a better option. That's what's used to load keycloak.json.

**Comment by stianst** [comment]
KeyStoreUtil classloader is obviously not the correct class loader.

**Comment by bejondshao** [comment]
Hi stianst, the process is on deployment, is there a better way to get/inject servletContext on deployment?

**Comment by stianst** [comment]
Not sure

@patriot1burke @sebastienblanc any off you know if it's OK to use thread classloader from within JEE deployment or should this be changed to use ServletContext? As far as I remember the JEE spec states that you can't rely on the thread classloader.

**Comment by sebastienblanc** [comment]
@stianst Same as you, all I can say is the specs from JEE don't really like we use the thread classloader.

**Comment by patriot1burke** [comment]
Doesn't matter about JEE, its about the platform it runs on.  JBoss used to use thread classloader, don't know anymore.  For adapters, the correct classloader should be available, its just a matter of wiring it in.  I'm closing this PR as its not correct.

**Pull request closed without merging**
