### PR TITLE
Removed hard-coded LTR dir attributes from form elements

### LINKED ISSUE #32844: Login V2: Missing "dir" attributes
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

The new login theme doesn't add `dir` attributes to input fields and other tags

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

I know that "dir" is about the direction of the input, but I'm not 100% sure on how this would behave. 

I see that in the old templates all `input`s seem to have them to `ltr`, plus the `div`s which contain the input and the button for passwords. 

### Actual behavior

Some "dir" attributes are missing in the new templates.

### How to Reproduce?

Look at the code!

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by senyahnoj**
Directionality is set in the html opening tag only (in base/login/template.ftl)

See also related issue #33642 which is to fix directionality in keycloak.v2/login/template.ftl

Closes #32844

### CODE REVIEW

**Comment by jonkoops** [comment]
@Eng-Fouad @Mouhand-Kaddo @sharifrezvani as maintainers of the RTL languages, is this how you would expect the UI to work? Or is it normal to force a LTR direction in some of these cases?

**Comment by Eng-Fouad** [comment]
> @Eng-Fouad @Mouhand-Kaddo @sharifrezvani as maintainers of the RTL languages, is this how you would expect the UI to work? Or is it normal to force a LTR direction in some of these cases?

Switching all UI components to RTL is the normal behavior. However, it is just a personal preference to use LTR for text inputs in cases where the text is English and it starts or ends with special characters.

For instance, let's assume we have 2 usernames named `_abc` and `def$`, here is how it would look on RTL text inputs:

rtl

and here how it would look on LTR text inputs:

ltr

**Comment by jonkoops** [comment]
Thanks for that feedback. Then if it is just personal preference I would say let's opt for going full RTL when a RTL language is enabled, as that simplifies things technically and reduces the amount of variants.

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
@ahus1 since you have been involved in the other PRs and issues related to this, can I ask you for your take as well?

**Review by Eng-Fouad — APPROVED** [review]

**Comment by ahus1** [comment]
I was merely the person who spotted the HTML change. I have no experience with LTR languages at all. 

> Switching all UI components to RTL is the normal behavior. However, it is just a personal preference to use LTR for text inputs in cases where the text is English and it starts or ends with special characters.

With @Eng-Fouad's comment above, I'd like to hear @senyahnoj's if this changed his mind, if if he wants to continue with the PR as is.

Another aspect: 

This changes both the Login v1 and v2 themes. As this was originally what the v2 themes should do, I'd like to keep the v1 theme stable as this is the "old" theme we want people to migrate from. 

The reason I pointed towards the old theme was not to change the old theme, but to highlight that it was different in v1 for quite a while than it now in v2. I'm sorry if this caused confusion and extra work here.

**Comment by jonkoops** [comment]
> This changes both the Login v1 and v2 themes. As this was originally what the v2 themes should do, I'd like to keep the v1 theme stable as this is the "old" theme we want people to migrate from.

I was contemplating this as well, I feel like it should still be fine to land fixes in V1, but considering this is mostly a matter of opinion I agree the changes should only be applied for V2. This also simplifies any backporting to `26.0.1` we might want to do.

@senyahnoj could you make the proposed changes?

**Comment by senyahnoj** [comment]
OK. In that case I shall close this PR with the changes to both "base" and "keycloak.v2" and reinstate my previous PR which only made the change in the keycloak.v2 template https://github.com/keycloak/keycloak/pull/33652

**Pull request closed without merging**
