### PR TITLE
KEYCLOAK-2283 added truststore test for email

### PR DESCRIPTION
**Pull request by fkiss**

### CODE REVIEW

**Comment by stianst** [comment]
Looks like you're only testing valid certificate. The more important test is an invalid certificate.

**Comment by stianst** [comment]
I'm not quite convinced about the approach. If we have a profile for each test (this is one profile for a single test valid cert for email) would results in many profiles and additional tests runs, CI jobs, etc..

**Comment by fkiss** [comment]
I understand. However, afaik you have to set up keycloak-server.json before starting server to use keycloak.truststore which is not used by default, so it is configured along with this profile.

**Comment by stianst** [comment]
The truststore can be configured by default. I don't see any issue with that. In can then contain the required certs to check valid certs. Then you'd have separate tests for testing valid/invalid certs which would setup email, client, etc. with valid/invalid certs.

**Comment by stianst** [comment]
I'm rejecting this PR. Please re-open when truststore has been added to the default server so it doesn't require a separate profile and test execution.

**Pull request closed without merging**
