### PR TITLE
fix: using iteration to allow recursive structures

### LINKED ISSUE #21130: Use SchemaSwaps with depths to control crd representations
### Description

With fabric8 6.8 we'll be able to use https://github.com/fabric8io/kubernetes-client/issues/5233 to remove the use of override classes and instead control how many levels of recursion to allow in the crd.

This will render #12725 moot

### PR DESCRIPTION
**Pull request by shawkins**
closes: #21130

We have a couple of choices here - the depth of 10 was based upon some comments in the original issue. The only downside with additional depth is the size of the crd. 

This change will also terminate with nothing, but could terminate instead with a map to allow for even more nesting - but no validation.

### CODE REVIEW

**Comment by mabartos** [comment]
@shawkins Yep, the CRD might be quite ugly, but I think it does not matter much, right? Do you think the size will be a problem? Anyway, we don't have any other option, right?

I think it'll be better than keeping the 'override' classes.

**Comment by shawkins** [comment]
> Yep, the CRD might be quite ugly, but I think it does not matter much, right? 

> Do you think the size will be a problem? 

It doesn't appear to be. The realm import yaml after this change isn't much bigger and still under 200KB - the recursive structures aren't very large.

> Anyway, we don't have any other option, right?

Nothing good. Just need to agree on the depth and termination strategy.

**Review by vmuzikar — APPROVED** [review]
I compared previous CRD with the one after after these changes and 10 levels look reasonable, not that much new content.

Thanks @shawkins!

**Comment by shawkins** [comment]
@mabartos are you good with this as is?

**Review by mabartos — APPROVED** [review]
@shawkins Yep, works for me. Nice job (even with the PR to fabric8io) !

**Comment by shawkins** [comment]
> @shawkins Yep, works for me. Nice job (even with the PR to fabric8io) !

Thank you. I've been waiting to submit this for quite a while.

**Pull request merged**
