### PR TITLE
KEYCLOAK-5183 Support for AssertionConsumerServiceUrl in Saml Adapter…

### PR DESCRIPTION
**Pull request by frelibert**
… subsystem

### CODE REVIEW

**Review by hmlnarik — CHANGES_REQUESTED** [review]
@frelibert Thank you for the changes. Could you please ensure that the tests pass.

**Comment by frelibert** [comment]
@hmlnarik I somehow lost track of this pull request. Sorry about that. I fixed the the code to make the tests pass and squashed the commits into 1.

**Review by hmlnarik — CHANGES_REQUESTED** [review]
The changes should include testing in `org.keycloak.subsystem.adapter.saml.extension.SubsystemParsingTestCase`

Furthermore, to be correct, the changes should include version schema (copy keycloak/adapters/saml/*/subsystem/src/main/resources/schema/wildfly-keycloak-saml_1_1.xsd and increase version to 1.2, update `KeycloakSamlExtension` appropriately, ensure the configuration in old version still loads).

Maybe there are other points to address. @ssilvert, could you please comment?

**Comment by ssilvert** [comment]
I'm starting to get rusty on subsystem development, so take my answer for what it's worth.  You should indeed make changes to the XSD files so that anyone who wants to use validation will have a proper version.  If it causes too much pain we should talk about it some more.

Are there migration tasks that need to be done for this?

**Comment by hmlnarik** [comment]
@ssilvert I don't think so - there is no change in existing properties or their mappings, just adding new properties.

**Comment by hmlnarik** [comment]
Replaced by #4725

**Pull request closed without merging**
