### PR TITLE
verifySSL() - debug info

### PR DESCRIPTION
**Pull request by kinjelom**
DEBUG report like this:

```
SSL Verification: 
		passed: true, request is secure: true, 
		SSL is required for: EXTERNAL, 
		SSL is required for remote addr 192.168.100.123: false

SSL Verification: 
               passed: true, request is secure: true, 
               SSL is required for: EXTERNAL, 
               SSL is required for remote addr 98.147.156.162: true
```

### CODE REVIEW

**Comment by stianst** [comment]
@pdrozd assigned this to you by mistake

**Comment by stianst** [comment]
I don't really see the point in adding this. What is the actual point in outputting all of this per-request for something that is in fact static configuration.

**Comment by wildloop** [comment]
SSL verification depends on static configuration and remote address.
In our case `keycloak-dev.json` has `ssl-required` set to `external` (default).
So, result of `verifySSL()` was dependent on routing/proxy and sometimes remote address was recognized as a local but sometimes not:

```
private boolean isLocal(String remoteAddress) {
    try {
        InetAddress inetAddress = InetAddress.getByName(remoteAddress);
        return inetAddress.isAnyLocalAddress() || inetAddress.isLoopbackAddress() || inetAddress.isSiteLocalAddress();
    } catch (UnknownHostException e) {
        return false;
    }
}
```

This debug log helped us a lot... so I only try to share :)

**Comment by wildloop** [comment]
One more thing, why does `boolean verifySSL()` return `false` when verification is passed?

**Comment by stianst** [comment]
verifySSL returns true if SSL is required and it's not used. If everything is fine it returns false. I guess it is kinda backwards, but it made sense when I added it a few years ago ;)

I'd rather drop the general debug statement and instead add getSslRequired and getRemoteAddr to the existing warn statement. It should be a single liner as well and not use newlines.

**Comment by stianst** [comment]
Ping

**Comment by wildloop** [comment]
Sorry,  I miss the time recently...
I can collapse this log to one line, but I think that a warning level could produce too much logs that nobody's care... Debug level is for investigating.

**Comment by stianst** [comment]
There is no need to add additional statements, just add it to the existing warn statement so there is details available when it fails.

**Comment by wildloop** [comment]
Ok, you are right, now it is only a one line :)

**Comment by stianst** [comment]
Please clean the changes as well. You don't need all the changes. All you need is the single line change to add additional details to the warn statement.

**Comment by wildloop** [comment]
You want me to collapse code to the one line (i will be unreadable) or maybe to reduce unnecessary commits (I don't know how to do it without the new pull request)?

**Comment by stianst** [comment]
All you need is:

    log.warn("SSL is required to authenticate. SSL required for: %s, remote address: %s",   
        deployment.getSslRequired().name(), facade.getRequest().getRemoteAddr());

**Comment by wildloop** [comment]
Ok, let it be.
I named local variables to avoid confusion with the name of the method but we can skip it - I just only want to log what is wrong...
I hope this ends our discussion about one logging instruction ;)
Thanks.

**Pull request merged**
