### PR TITLE
Enable action token JPA provider in map-storage-jpa profile

### LINKED ISSUE #13139: Enable action token JPA provider in map-storage-jpa profile
### Description

The map-storage-jpa profile is currently missing the action token store provider, which results in tests being run with the concurrent hash map provider for action tokens.

### PR DESCRIPTION
**Pull request by sguilhen**
Closes #13139

### CODE REVIEW

**Review by ahus1 — DISMISSED** [review]
This is a valid change (assuming all tests will return green)

**Comment by sguilhen** [comment]
> Had some second thoughts, the map store tests will not run unless there is a change in git around the map store. Please add such a change to force these steps.

Will try to find something to change in the map store to force the tests.

**Comment by sguilhen** [comment]
@ahus1 Was able to find a file that needed a typo fix and the jpa store tests ran successfully. Please re-review when you find a chance.

**Review by ahus1 — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
