### PR TITLE
Fix issue with groups search not sending the search input in the request

### LINKED ISSUE #23341: Keycloak 22.0.3: Create user: select groups to join filter does nothing
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Filter 'search for groups' doesn't change the list of visible groups.

### Version

22.0.3

### Expected behavior

After entering something into the search field in the 'Create user -> Select groups to join', and pressing Enter or the button to the right of the filter, the list of groups should be shrinked. 
изображение

### Actual behavior

The list of groups remains unchanged.

### How to Reproduce?

Let's have some User groups.
Users -> Create user.
Press Join groups, input some text in the 'Search for groups' input. Press Enter.

### Anything else?

NOTE: the popup itself is blinking and becomes wider, it can be a separate design issue.

### PR DESCRIPTION
**Pull request by osorionicolas**
Closes #23341

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]
Good catch, thanks @osorionicolas!

**Comment by osorionicolas** [comment]
> Good catch, thanks @osorionicolas!

damn, I didn't know that rebasing the branch will restart the workflows, sorry @jonkoops

**Comment by jonkoops** [comment]
> damn, I didn't know that rebasing the branch will restart the workflows, sorry

No problem. Just be aware that being up-to-date with `main` is not a prerequisite to getting your PR merged, so unless you have conflicts there is no need to rebase your PR.

**Comment by osorionicolas** [comment]
Hey @jonkoops, the cypress CI seems to be failing because the realm was created enable when it shouldn't and the test didn't expect to have the disable realm modal. When I run the tests locally they run successfully and I couldn't find any condition that creates the realm enable. Do you have an idea why this would happend? should we re run the wf?

Screenshot 2023-09-22 at 15 22 32

**Pull request merged**
