### PR TITLE
added 'shouldBootstrap' property that will only show logo

### LINKED ISSUE #25541: Add an option for a custom welcome page to disable bootstrapping of admin account
### Description

https://github.com/keycloak/keycloak/pull/25420 refreshes the welcome page making it simpler and by default redirecting to the admin console. It also introduces the theme property `redirectToAdmin` which a custom theme can set to disable the redirect to for example show a basic page with the company logo.

As an addition to that it would be nice to have a theme property `supportAdminBootstrap` that would allow a custom theme to disable the ability to create the initial admin account through the welcome page.

When a custom theme sets `supportAdminBootstrap=false` and inherits from the Keycloak welcome page it should just display the Keycloak logo, and not allow any form posts. A custom theme can go further of course and replace the `index.html` as well, so in this case it would be just disabling the ability to post the form.

Should be easy to implement with just checking the theme property in the shouldBootstrap method.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by edewit**
fixes: #25541
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

### CODE REVIEW

**Review by ssilvert — DISMISSED** [review]

**Review by jonkoops — COMMENTED** [review]
Just a question, why is this being implemented? I don't really see much motivation in the original issue that seems to justify the need aside from 'would be nice for custom themes', but since custom themes would overwrite the template they can already accomplish this no?

**Comment by jonkoops** [comment]
> @jonkoops see the issue, it would mean that you only need to change a property instead of changing the template

I understand that, but I don't see anybody customizing this theme without also overwriting that template, it is the only template in the theme. And any small customization on top of the theme would not need to change the core functionality so dramatically.

**Comment by ssilvert** [comment]
> > @jonkoops see the issue, it would mean that you only need to change a property instead of changing the template
> 
> I understand that, but I don't see anybody customizing this theme without also overwriting that template, it is the only template in the theme. And any small customization on top of the theme would not need to change the core functionality so dramatically.

I don't think it's necessarily true that the welcome theme would always get customized.  And anyone who does do customization needs to clearly see that the `shouldBootstrap` option is possible.

**Comment by jonkoops** [comment]
> I don't think it's necessarily true that the welcome theme would always get customized. And anyone who does do customization needs to clearly see that the `shouldBootstrap` option is possible.

What I am simply saying is why would anyone want to do this? We're building a feature here that doesn't have any user motivation aside from 'would be nice to have'. But **why** would it be nice to have? What purpose does it serve? Perhaps I don't have all the context here, or it isn't on GitHub?

**Comment by edewit** [comment]
To much questions on how this is useful or how it can be used

**Pull request closed without merging**
