### PR TITLE
Entering a single space in a regex password policy makes admin interface unusable.

### LINKED ISSUE #20411: Entering a single space in a regex password policy makes admin interface unusable.
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Given a single space as input in a regex password policy the admin interface becomes no longer usable

### Version

21.1.1

### Expected behavior

The admin console is still usable after entering a space as regex password policy.

### Actual behavior

The admin console is not usable after entering a space as regex password policy.

### How to Reproduce?

In the admin console enter a single space as regex password policy and save.

### Anything else?

I had to fix the realms password policy via the database.
`update REALM set PASSWORD_POLICY=NULL where ID="<REALM_ID>";`

### PR DESCRIPTION
**Pull request by pedro-hos**
close #20411

Hi team, I have added a simple validation on RegexPatternsPasswordPolicyProvider to avoid white spaces on regex

### CODE REVIEW

**Comment by thomasdarimont** [comment]
@pedro-hos thanks for your contribution! Could you rebase the PR again?

**Review by jonkoops — DISMISSED** [review]
LGTM

**Comment by jonkoops** [comment]
@pedro-hos could you sign off on your commit?

**Comment by pedro-hos** [comment]
> sign off

Sure @jonkoops how can I do that?

**Comment by jonkoops** [comment]
See [the failing status check](https://github.com/keycloak/keycloak/pull/22807/checks?check_run_id=24940232600) on the PR.

**Comment by pedro-hos** [comment]
@jonkoops I think that's fine now

**Comment by jonkoops** [comment]
Yes, looking good! Thanks!

**Review by jonkoops — APPROVED** [review]

**Review by abstractj — APPROVED** [review]

**Pull request merged**
