### PR TITLE
Allow forwarding of the ui_locales parameter to identity providers

### PR DESCRIPTION
**Pull request by knutz3n**

### CODE REVIEW

**Comment by knutz3n** [comment]
Seems like the CI build got cancelled by a server shutdown. Can you try to trigger a rebuild, please?

**Comment by ssilvert** [comment]
Restarted

**Comment by knutz3n** [comment]
Tests seems to fail due to a network issues in the crossdc-server tests. However, the failure seems unrelated to my changes. Are other builds having problem? Restarting the build once again might help, but I would appreciate if someone had time to review [the build log](https://api.travis-ci.org/v3/job/409818217/log.txt).

**Comment by yuichi-nakamura** [comment]
Hi, It seems that this feature has already be able to  covered by the following PR that is more generic due to forwarding parameters other than ui_locales(Review is pending however..)
https://github.com/keycloak/keycloak/pull/5163

**Comment by knutz3n** [comment]
@yuichi-nakamura Thanks for pointing this out. Hopefully it gets reviewed and merged. Closing this PR since it is incorporated by #5163.

**Pull request closed without merging**
