### PR TITLE
SAML ECP does not work on the latest WF/EAP8

### LINKED ISSUE #24746: SAML ECP does not work on the latest WF/EAP8
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

adapter/jee-saml

### Describe the bug

I've just encountered an issue with the SAML ECP(Enhanced Client or Proxy) profile while testing the SAML Adapter on EAP8. There's an incompatibility between Java EE and Jakarta EE, more specifically, 'javax.xml.soap' and `jakarta.xml.soap`. 

This issue will also be seen on the latest WildFly distribution, where the SAML Adapter will be deployed. 

AFAIK, in order to comply with the SAML 2.0 standard, it needs to be fixed.

### Version

22.0.5

### Expected behavior

SAML ECP works

### Actual behavior

SAML ECP does not work - Cannot read the SOAP envelope

### How to Reproduce?

- Deploy the Jakarta SAML Adapter on top of the latest WildFly, or EAP8
- Execute test `SAMLServletAdapterTest#testInvalidCredentialsEcpFlow` with the mentioned app-server

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
Fixes #24746

Tested on EAP8, and it works now. Created a new Jakarta module for saml-core as we don't probably want to change the behavior for the 22.0.x micro releases.

### CODE REVIEW

**Comment by mabartos** [comment]
Works as expected on EAP8 (@miquelsi executed tests).

Could someone from the @keycloak/core review it? Thanks

**Review by sguilhen — APPROVED** [review]
It looks ok to me, @mabartos . 

Only thing I've realized now and which is not a problem of this particular PR, is the naming differences in the jakarta modules. We have `core-jakarta`, and `wildfly-elytron-jakarta`, where the `jakarta` identifier is appended at the end of the module name, and for `servlet-filter` we have `jakarta-servlet-filter`. I would rather follow a common naming pattern for these modules, but it might be too troublesome to adjust them now.

**Comment by ahus1** [comment]
@mabartos - please comment if this PR is now ready to be merged regardless of Stefan's comment "the naming differences in the jakarta modules"

**Comment by mabartos** [comment]
@sguilhen Thanks for the review. Yes, the naming convention is not unified in Keycloak. However, I don't see it as a big deal as it's only a matter of time when we have everything only JakartaEE compatible.

Could be merged to the `22.x`, but I need to propagate these changes even to the upstream main.

**Review by ahus1 — APPROVED** [review]
Approving as of @sguilhen's review

**Comment by ahus1** [comment]
@stianst - please merge for 22.0.7 once the branch is no longer protected. Thanks!

**Pull request merged**
