### PR TITLE
KEYCLOAK-3616 Add integration tests for Node.js adapter

### PR DESCRIPTION
**Pull request by vmuzikar**

### CODE REVIEW

**Comment by abstractj** [comment]
@vmuzikar actually we have the integration tests for Node.js here: https://github.com/keycloak/keycloak-nodejs-connect/tree/master/test. I'm not quite sure if here is the best place to include Node.js stuff.

Also, if I run:

```
mvn clean install -DskipTests -Pdistribution && mvn clean install -B -Pauth-server-wildfly -f testsuite/integration-arquillian/servers/pom.xml && mvn test -f testsuite/integration-arquillian/tests/other/nodejs_adapter/ -Pauth-server-wildfly -Pnodejs_adapter
```

It will gonna fail with:

```
Results :

Tests in error:
  NodejsAdapterTest.beforeNodejsAdapterTestClass:65 IllegalState testsuite.adapt...

```

My guess is the fact that I don't have a Node.js app started, right? If the answer is yes, I think integration tests should start up a Node.js server before they start to run. 

I see two alternatives:

1. Write JavaScript integration tests for Node.js like we [already do today](https://github.com/keycloak/keycloak-nodejs-connect/tree/master/test). Spinning up a Keycloak server.

2. Write Java integration tests with Arquillian. Spinning up a Node.js server.

I'd vote for option 1. Any thoughts @stianst?

**Comment by stianst** [comment]
I'll discuss this with Pavel tomorrow. It's a general question as it affects keycloak.js and admin console. It might be better to use testing frameworks specific for the framework/language or to rely on Arquillian/Selenium for all integration tests. If we use another testing framework we should still bootstrap it with Arquillian/Selenium as that provides a lot of value.

**Comment by vmuzikar** [comment]
We decided to add a few new tests different to [keycloak-nodejs-connect](https://github.com/keycloak/keycloak-nodejs-connect). Our tests use a real world scenarios with actual running Keycloak - it tries to login/logout, refresh tokens, sessions... This requires using a browser (PhantomJS) and other frameworks (not just Arquillian but also whole bunch of stuff we wrote ourselves).
From that reason we also decided to make the tests part of the original Keycloak project. It's not ideal but given the circumstances it's the most direct approach. If we were to have those tests e.g. as part of the [keycloak-nodejs-connect](https://github.com/keycloak/keycloak-nodejs-connect) it would mean to start again with a testsuite and write again or duplicate many things which are now part of the main Keycloak project.

The tests expect the [Node.js adapter Example](https://github.com/keycloak/keycloak-nodejs-connect/tree/master/example) to be running and a system property `testsuite.adapter.nodejs.example.realm` (which can be set from CLI using `-D` parameter) to be pointing to the [example real config file](https://github.com/keycloak/keycloak-nodejs-connect/blob/master/example/nodejs-example-realm.json). This includes checkout the current [keycloak-nodejs-connect](https://github.com/keycloak/keycloak-nodejs-connect) from a repository, installing it using `npm` and starting it. This would be a bit complicated to do from the testsuite using e.g. maven.
So this needs to be done "manually". But that shouldn't be a problem since it's intended to be run by Jenkins. We also used similar approach with other tests.

**Comment by stianst** [comment]
@pdrozd let's discuss this at todays meeting

**Comment by stianst** [comment]
Woops. Wrong button ;)

**Comment by stianst** [comment]
As we discussed the plan is to:
* Add UI functional tests for node.js adapter directly to Arquillian testsuite, I assume this is completed with this PR, but I can't see where the example app is coming from and how it's deployed
* Execute tests from node.js repositories. Do you want to create a separate JIRA/PR for that? IMO this is actually higher priority than the tests included in this PR

**Comment by vmuzikar** [comment]
- Yes, the Arquillian UI tests are incorporated in this PR. The deployment of the example app is done externally, in this case by Jenkins.
- I've created a JIRA on Jenkins job creation for both Arquillian and native Node.js tests.

**Pull request merged**
