### PR TITLE
[Keycloak-js] Expose processCallback, parseCallback and createPromise to custom adapters 

### PR DESCRIPTION
**Pull request by javialon26**
Possible solution to issue https://github.com/keycloak/keycloak-js/issues/27.

I'm adding a new way to create adapters, which is a factory function (receive as parameters all the required internal KC methods like processCallback, parseCallback, createPromise, and KC instance) and must return a KeycloakAdapter object.

This is a preliminary PR, we need to work on tests, documentation, etc. but the idea is pretty clear.

### CODE REVIEW

**Comment by jonkoops** [comment]
Thanks for the PR, but we do not want to expose `createPromise()` as a public API. Keycloak JS should be refactored internally first to move towards standard Promise-based code.

**Comment by mariomurrent-softwaresolutions** [comment]
Will this ever be done?

**Comment by jonkoops** [comment]
If someone is willing to take it on I am more than willing to review it. I would first like to refactor the internals of Keycloak JS to use regular Promises, rather than the custom internal implementation we have now.

Note that Keycloak JS now lives in its [own repository](https://github.com/keycloak/keycloak-js), and we are in the process of writing a new test suite for it. After this effort is complete it opens up the window for any possible refactoring.

**Comment by mariomurrent-softwaresolutions** [comment]
Sounds good. Let me know if you have finished writing the test suite. 

#Maybe I'll jump into the code then.

**Pull request closed without merging**
