### PR TITLE
Don't use the word 'please'

### PR DESCRIPTION
**Pull request by jonkoops**
Based on feedback by @andymunro (see https://github.com/keycloak/keycloak/pull/26161#discussion_r1450753438).

### CODE REVIEW

**Review by pedroigor — APPROVED** [review]

**Review by andymunro — APPROVED** [review]
Thanks, @jonkoops.  Please accept my approval.

**Review by vmuzikar — APPROVED** [review]
@jonkoops Thank you!

**Comment by vmuzikar** [comment]
The `HelpCommandDistTest` failed which seems to be caused by this change. @jonkoops Could you please check it?

**Comment by jonkoops** [comment]
Yeah, I'll fix it up when I have some time, looks like this also touched the Windows files in ways it should not have.

**Pull request closed without merging**
