### PR TITLE
Enable optimistic locking feature on auth sessions

### LINKED ISSUE #12242: Enable optimistic locking feature on auth sessions
After https://github.com/keycloak/keycloak/pull/12191 will be merged it should be possible to enable automatic optimistic locking mechanism on auth session entities.

### PR DESCRIPTION
**Pull request by vramik**
Closes #12242

### CODE REVIEW

**Review by ahus1 — APPROVED** [review]
I see the changes and they look good and valid. I also see that the tests for jpa-map have been executed in the CI-run. I thereby approve it.

What I don't understand yet: Why the other change enabled this to work ... nevermind :-)

**Comment by vramik** [comment]
> What I don't understand yet: Why the other change enabled this to work ... nevermind :-)

https://github.com/keycloak/keycloak/pull/12191 removed the inner transaction which prevented the optimistic locking. The inner transaction was replaced by enlisting new transaction which has only some code executed in case of rollback, otherwise it does nothing.

**Comment by ahus1** [comment]
>  The inner transaction was replaced by enlisting new transaction which has only some code executed in case of rollback, otherwise it does nothing.

Thanks @vramik - now I know!

**Review by hmlnarik — APPROVED** [review]
Approving per @ahus1 's approval

**Pull request merged**
