### PR TITLE
KEYCLOAK-4072 Add explicit check for key format

### PR DESCRIPTION
**Pull request by hmlnarik**

### CODE REVIEW

**Comment by stianst** [comment]
Seems like a sensible safety mechanism to add - it's not required for KEYCLOAK-4072, rather a separate enhancement.

**Comment by stianst** [comment]
I don't want to merge without Bills feedback though

**Comment by stianst** [comment]
@patriot1burke can you review this please?

**Comment by patriot1burke** [comment]
We need to reject this, or you need to change the pattern matcher.  User Storage userIds can be of the pattern:

"f:" + uuid + ":" + <opaque-string>

So, your check will break everything.

**Comment by patriot1burke** [comment]
bah sorry, i looked at code too quick!  The regex is there.I guess we can do this....but KEYCLOAK-4072 has nothing to do with your PR.

**Comment by hmlnarik** [comment]
Thanks, I'll introduce a new issue in JIRA (once it gets resurrected) and change the issue number then.

**Pull request merged**
