### PR TITLE
KEYCLOAK-8316 Add an option to ldap provider to trust email on import

### PR DESCRIPTION
**Pull request by micedre**
Option is false by default (for backward compatibility)

### CODE REVIEW

**Comment by abstractj** [comment]
@micedre could you please rebase your pull request to include the latest changes from master?

**Comment by micedre** [comment]
@abstractj done

**Comment by stianst** [comment]
Looks like a different approach to https://github.com/keycloak/keycloak/pull/6194

**Comment by stianst** [comment]
This looks like a better approach compared to 6194

**Review by mposolda — CHANGES_REQUESTED** [review]
@micedre Thanks for the PR and sorry for late review.

Instead of introducing another 1st level flag on LDAP provider for quite specific corner-case like you have, I would prefer to have another kind of "Hardcoded" LDAP mapper, which will allow to add hardcoded value to user model. Basically at the moment when user is created in Keycloak, there will be a way to hardcode specific configured attribute or property with specified hardcoded value. The mapper implementation can override method "proxy" and create UserModelDelegate, which will override various getter methods (isEmailVerified, getAttribute and maybe some others). Based on which attribute was specified, the particular method will return hardcoded value. In case that different name of attribute was specified, the implementation can just delegate to "super" (See other mappers for more details).

**Comment by micedre** [comment]
@mposolda I agree the configuration page for LDAP provider is quite big and complex as it is, but don't you want to be coherent with what already exists for External Identity Providers? (an maybe reorganise the LDAP page to hide some complexity)
I need that feature (mark as trusted email from ldap), so I will try to do another PR as you said, thanks for the review.

**Comment by mposolda** [comment]
@micedre Thanks, I would prefer the mapper as also I recall the case when someone wanted "hardcoded" value of some attribute for users coming from LDAP. So if you can do the mapper (EG. HardcodedModelAttributeMapper), it will be nice. Thanks

**Review by mposolda — APPROVED** [review]
@micedre I am actually thinking about this more and seeing that this use-case is requested by more users and in all cases, it is requested specifically just with the regards of "automatically trusting email" . Mapper will be possible, but switch is just easier than the mapper considering that use-case so far was always just about automatic trusting emails. So I am approving and merging this PR.

As you pointed, it will be nice if we better structure the page with LDAP provider and provide something like "Advanced settings" similarly like we have for configuration of clients. So if you can send another PR for this, it will be nice :)

I hope you didn't yet started on another PR and sorry for inconvenience around this.

**Comment by micedre** [comment]
@mposolda Thanks for the merge. I was a little busy at $work so did not have time to work on the mapper. But I also think it is a good idea (I may need it to force locale for example). I may try to work on it or arrangong the ldap page in the future. :)

**Pull request merged**
