### PR TITLE
KEYCLOAK-14380 Support Requesting Claims using the claims Request Par…

### PR DESCRIPTION
**Pull request by tnorimat**
This PR is for [KEYCLOAK-14380](https://issues.redhat.com/browse/KEYCLOAK-14380). This PR is required to pass Financial-grade API (FAPI) Security Profile's conformance tests provided by OpenID Foundation. The reason why in detail can be found in https://github.com/jsoss-sig/keycloak-fapi/issues/32 .

This PR does not cover all specification defined in [5.5.  Requesting Claims using the "claims" Request Parameter of OIDC core](https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter).

This PR only supports the following point.

* treats claims defined by "claims_supported" of Server Metadata.
* treats the claim specified as `{"essential" : true}` to include this claim onto ID Token and/or User Info.

### CODE REVIEW

**Review by pritish-nitb — COMMENTED** [review]
@tnorimat I checked the code and have tested against FAPI conformance suit and it resolved the defect that it is addressing. However when we check the FAPI specs it says that:
> shall request user authentication at LoA 3 or greater by requesting the acr claim as an essential claim as defined in section 5.5.1.1 of [OIDC]

Also when we check the corresponding OIDC spec, it says that:

> If the acr Claim is requested as an Essential Claim for the ID Token with a values parameter requesting specific Authentication Context Class Reference values and the implementation supports the claims parameter, the Authorization Server MUST return an acr Claim Value that matches one of the requested values. The Authorization Server MAY ask the End-User to re-authenticate with additional factors to meet this requirement. If this is an Essential Claim and the requirement cannot be met, then the Authorization Server MUST treat that outcome as a failed authentication attempt.

Which I am not sure if we have added in this fix so wanted to confirm if it is all that we need to change in Keycloak to comply with the particular FAPI spec.

**Comment by tnorimat** [comment]
@pritish-nitb Thank you for your confirmation about this PR's effectiveness against the issue I've reported.

As for acr Claim's values, I think we need not to do anything more than this PR's work to pass the FAPI conformance tests. The current FAPI conformance tests does not check this point.

How to treat ACR seems to be complicated issue. Please refer to the following [this JIRA ticket](https://issues.redhat.com/browse/KEYCLOAK-3314)

**Review by pedroigor — APPROVED** [review]
@stianst @mposolda LGTM. Anything else missing?

**Review by mposolda — APPROVED** [review]
@tnorimat Thanks for the PR! I am approving as well.

It seems that our own "claims" parameter support is not very generic, however if we pass FAPI, it is probably fine :-) I personally find the "claims" parameter a bit useless considering that "scope" (and other parameters like "acr") can be used to achieve the same thing. We will see if there are requests to support something more regarding "claims" parameter...

**Pull request merged**
