### PR TITLE
WebAuthn tests failures on WildFly

### PR DESCRIPTION
**Pull request by mabartos**
@miquelsi Could you please take a look at it? Thanks

I was able to reproduce the issue and this PR resolves it. I think it's not necessary to execute pipeline tests.

### CODE REVIEW

**Comment by stianst** [comment]
@mabartos please don't refer to internal CIAM issues

**Comment by mabartos** [comment]
@miquelsi This PR resolved the issue. See https://keycloak-jenkins.com/job/universal-test-pipeline-server/1100/

**Comment by stianst** [comment]
What does 'on JBoss' mean? Do you mean it's failing with the auth-server-wildfly profile?

**Comment by mabartos** [comment]
@stianst I changed the title.

**Review by miquelsi — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
