### PR TITLE
KEYCLOAK-8701 changes needed to include x5c property in jwks

### PR DESCRIPTION
**Pull request by toyaser**

### CODE REVIEW

**Comment by toyaser** [comment]
@stianst i noticed this pull request is "on hold", is there a timeline on when this change will be considered for review?

**Review by mposolda — COMMENTED** [review]
@toyaser Thanks for the PR and thanks for the patience with waiting for review. Looks good to me!

Just one thing, could you please squash the commits and rebase on top of latest master, so that PR contains just single commit insteead of 8 commits? The message of the commit can be exactly same as the header of this PR "KEYCLOAK-8701 changes needed to include x5c property in jwks" . Thanks!

**Comment by mposolda** [comment]
@toyaser any updates?

**Comment by toyaser** [comment]
@mposolda ill get this done asap. Thanks

**Comment by toyaser** [comment]
@mposolda done now, thanks!

**Comment by mposolda** [comment]
@toyaser Thanks!

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
@keycloak-ci-bot test

**Pull request merged**
