### PR TITLE
Ensure that parent's version ID is incremented when an attribute changes

### LINKED ISSUE #9874: JPA Map storage doesn't increment version column on attribute update
### Describe the bug

When updating an attribute for example with a client, the version in the client table should be updated as well. 

This way it ensures that no-one else updated any other attribute in the meantime. 

### Version

17.0.0-SNAPSHOT

### Expected behavior

Version number should be updated when an attribute changes

### Actual behavior

No change in the version number, as the relation is owned by the "Many" side. 

### How to Reproduce?

* Enable JPA Map storage for clients
* Edit a client attribute like "Backchannel Logout Session Required"
* look at the client table and see if the version changes

### Anything else?

This is been found when implementing #9645

### PR DESCRIPTION
**Pull request by ahus1**
This is necessary to allow the optimistic locking functionality to work as expected when changing only attributes on an entity.

Closes #9874

### CODE REVIEW

**Comment by ahus1** [comment]
Testing this, I found that the optimistic locking failed when updating only some attributes: the version in the parent wasn't incremented as the the ManyToOne relation is owned by the child.

I looked for a simple solution to change that ownership, but didn't succeed. I then added some hibernate listeners and iterfaces to trigger the essential `session.lock(root, LockModeType.OPTIMISTIC_FORCE_INCREMENT)`. 

The approach is inspired by https://vladmihalcea.com/jpa-entity-version-property-hibernate/ and https://vladmihalcea.com/hibernate-event-listeners/.

I tested it manually by changing role attribute or changing a client's "Backchannel Logout Session Required" and running it with and without `session.lock(root, LockModeType.OPTIMISTIC_FORCE_INCREMENT);`.

**Comment by ahus1** [comment]
Will be reworked to supported multiple levels. Reverting to draft.

**Comment by ahus1** [comment]
Has been reworked to supported multiple levels of parent-child-relationship. Ready for review.

**Review by sguilhen — APPROVED** [review]
LGTM, thanks @ahus1 !

**Review by hmlnarik — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
