### PR TITLE
Added save function in UserForm.tsx

### LINKED ISSUE #29336: Unlocking and saving the user's temporary lock will render the user disabled.
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

When a user is temporarily locked due to brute force security, unlocking the temporary lock from the user details screen and saving will result in the user becoming disabled.   

When the temporary lock is turned OFF, the temporary lock is lifted, and the user becomes enabled, and the changes are automatically saved. However, on the screen, the Enabled/Disabled status of the user does not change from the temporary locked state. Therefore, clicking the save button will result in the user being updated as disabled.

image

image

image

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

When unlocked and automatically saved, the user status changes to `Enabled`, consistent with the data stored in the records.

### Actual behavior

When the temporary lock is removed, the user remains in a disabled state, and if saved as is, it will be overwritten with `Disabled`.

### How to Reproduce?

Unlock the temporary lock for the user from the user details screen and click the save button.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by himanshi1099**
Closes #29336

### CODE REVIEW

**Comment by himanshi1099** [comment]
@ssilvert I have raised PR can you please check

**Comment by jonkoops** [comment]
For future reference if you want to link an issue to a PR you'll have to use one of the keywords [supported by GitHub](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). I have linked it manually for now.

**Review by ssilvert — APPROVED** [review]
Tried it out.  Looks good.

**Comment by himanshi1099** [comment]
@ssilvert  If changes are fine can you the merge the PR?

**Review by agagancarczyk — APPROVED** [review]

**Review by jonkoops — APPROVED** [review]

**Pull request merged**
