### PR TITLE
fix 10935 by respecting key use of EC keys in JWKS

### LINKED ISSUE #10935: Add key provider implementation to support ECDH-ES algorithm for encryption
### Description

ECDSA has been added as new algorithm for digital signing in keycloak. Is it possible to develop Elliptic Curve Diffie-Hellman Ephemeral Static (ECDH-ES) support for key encryption since EC is faster than RSA?

### Discussion

_No response_

### Motivation

elliptic curve cryptography now is widely accepted and perform faster than RSA.

### Details

Need to develop realm key provider implementation to support ECDH-ES algorithm for encryption

### PR DESCRIPTION
**Pull request by alwibrm**
When loading public keys for the OIDC /certs endpoint the key use for EC keys always defaults to "sig", even when the key use "enc" is stored through the provider. To change that behavior this PR hands over the key use of EC keys when building the JWKS.

This should fix #10935.

### CODE REVIEW

**Comment by pedroigor** [comment]
@alwibrm Did you write your own provider to support EC for encryption?

**Comment by alwibrm** [comment]
Hi @pedroigor, yes. I wrote a `KeyProvider` by extending the `AbstractEcdsaKeyProvider` that generates and stores an EC key pair as a `ComponentModel`.

**Review by pedroigor — COMMENTED** [review]
Changes LGTM. But I'm wondering if the best is to support EC for encryption rather than only fix the JWKS.

@mposolda Wdyt?

**Comment by alwibrm** [comment]
@pedroigor What do you think about fixing the JWKS first and support EC keys for encryption in a further iteration?

**Review by mposolda — APPROVED** [review]

**Comment by mposolda** [comment]
@pedroigor @alwibrm Works for me as well. I've added also @tnorimat for the review of this. There is related PR for adding EdDSA support from @tnorimat  https://github.com/keycloak/keycloak/pull/17215, so I was wondering if this change in this PR is aligned with this work.

**Review by tnorimat — APPROVED** [review]
LGTM.

**Comment by tnorimat** [comment]
@mposolda After this PR is merged, I will resolve conflicts of https://github.com/keycloak/keycloak/pull/17215 .

**Pull request merged**
