### PR TITLE
Password policy spi

### PR DESCRIPTION
**Pull request by naude-r**
this is a WIP for the password policy spi. currently outstanding are the UI changes. not sure how that should work yet.

in the meantime i would like to solicit feedback on the approach taken for the policy spi.

### CODE REVIEW

**Comment by patriot1burke** [comment]
conflicts

**Comment by stianst** [comment]
@naude-r are you able to work on the UI part as well?

**Comment by naude-r** [comment]
@stianst hi, have taken an initial look at the UI side of things. have not had much extra time to spend on it though. to be honest i will probably not be able to get around to it any time soon.

**Comment by stianst** [comment]
JIRA: https://issues.jboss.org/browse/KEYCLOAK-2824

**Comment by stianst** [comment]
This is put on hold a bit due to two reasons:
* Considering changing providers to support having config per-realm
* Need to complete the UI work

@naude-r thanks for your contribution so far, we'll take it from here and make sure it'll get merged once the above is resolved.

**Comment by stianst** [comment]
Closing this as I've sent another PR https://github.com/keycloak/keycloak/pull/3030

**Pull request closed without merging**
