### PR TITLE
fix: removing httpclient override

### LINKED ISSUE #21392: Align httpclient dependency with the Quarkus Platform BOM
### Description

httpclient removal caused [unit test failures](https://github.com/keycloak/keycloak/actions/runs/5411587832/jobs/9834779968)

[By reverting the changes](https://github.com/keycloak/keycloak/pull/21078/commits/ed5e9df7ec6af0137131fe6fe71ee362cd4e2667) and re-adding the dependency override back to the parent POM, all the workflows got stable again. I didn't have time to investigate the cause in more depth yet, therefore it's expected to address it in this follow-up as both the dependencies can be possibly aligned with the Quarkus Platform BOM.

This task serves as an follow-up of https://github.com/keycloak/keycloak/pull/21078.

### PR DESCRIPTION
**Pull request by shawkins**
closes: #21392

### CODE REVIEW

**Review by jonkoops — DISMISSED** [review]

**Comment by shawkins** [comment]
@jonkoops sorry, I should have opened this as a draft to start with. The issue mentioned ci failures related to this removal, but it wasn't clear what they actually were. It's not apparent that it's due to the quarkus dependency excluding commons logging. Let me see how that can be best addressed.

**Comment by shawkins** [comment]
Anywhere that had a dependency on httpclient and where jboss-logging was not provided, we need a runtime dependency on commons-logging-jboss-logging. This should mean that commons-logging is no longer transitively needed, but it is a subtle change for the adapters so that may need a second look.

**Review by mabartos — COMMENTED** [review]
@shawkins LGTM.

However, it'd be good to have it approved by someone from the @keycloak/core team and check the productization of the new dependency. 

(cc: @ASzc)

**Comment by shawkins** [comment]
> check the productization of the new dependency

The jboss logging dependency is what we're already relying upon at runtime with quarkus. We just have not be explicit about including it mostly so that tests will run. This change does mean that commons-logging will no longer be used by kcadm nor kcreg.

**Review by Pepo48 — DISMISSED** [review]
Approved based on the offline discussion.

Thanks @shawkins.

**Comment by ASzc** [comment]
`commons-logging-jboss-logging` appears to be productized by RHBQ, so LGTM in theory

**Review by vmuzikar — DISMISSED** [review]

**Comment by mabartos** [comment]
@shawkins @vmuzikar @Pepo48 AFAIK, the QE team has still faced some issues with the build pipeline, so it's not possible to execute adapter tests. 

Situation ATM: all of our adapters are deprecated, but we still need to ensure the functionality. And more importantly, ensure the functionality of the EAP 8 SAML adapter, as this touches the saml-core module.

I'll try to gather more info from the QE team.

Or what are your thoughts on this? Like, I'm pretty confident nothing will break, but you never know, so it'd be good to have it double-checked.

**Comment by mabartos** [comment]
@shawkins The build pipeline should be ready, but the test pipelines need to be clear due to the product testing. However, some adapter test executions might fit there today.

**Review by mabartos — APPROVED** [review]
@shawkins Sorry for the late response. Adapter tests passed (same failures as for other builds). LGTM.

[1] https://keycloak-jenkins.com/view/Keycloak/job/universal-test-pipeline-adapters/2195/

**Review by vmuzikar — APPROVED** [review]

**Pull request merged**
