### PR TITLE
return proper error message for admin /users endpoint

### LINKED ISSUE #28416: Keycloak is not returning proper error message for PUT /users admin API
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

Trigger  PUT /users admin API to change user's password
PUT /admin/realms/{realm}/users/{id}
Send password which is same as previous password. As per my password policy, this request will fail, because new password should not be same as past 3 passwords. 

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak should send exact error message as follows
 {"error":"invalidPasswordHistoryMessage",
"error_description":"Invalid password: must not be equal to any of last 3 passwords."}

### Actual behavior

Keycloak is responding 400 response code with very generic error message as follows
{"errorMessage":"Could not update user!"}

### How to Reproduce?

Trigger  PUT /users admin API to change user's password
PUT /admin/realms/{realm}/users/{id}
Send password which is same as previous password. As per my password policy, this request will fail, because new password should not be same as past 3 passwords

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by etiksouma**
closes #28416

### CODE REVIEW

**Review by sguilhen — COMMENTED** [review]
Thanks for the PR, @etiksouma ! I've been thinking a bit about it, and I found out that the creation of users handles this a little bit differently, by having a `catch (PasswordPolicyNotMetException e) ` [here](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java#L158-L160).

So I've been wondering if we should just replicate that when updating the user, instead of allowing every model exception message to be returned. I don't know if there's a reason to only return a generic "User could not be updated" message instead of the original exception message.

If there is no special reason, I would argue that the same treatment of the `ModelException` you're adding here should also be applied to the user creation.

@pedroigor @stianst What do you think? Would it be ok to always return the original exception message with the `BAD_REQUEST` (as it is done in the `resetPassword` method in the same endpoint), or is it preferred to keep the more generic error message and just add a special case for the `PasswordPolicyNotMetException`?

**Comment by pedroigor** [comment]
@sguilhen Makes sense to me and we can have a follow-up for this change in the User API.

**Comment by etiksouma** [comment]
@sguilhen 

Just for me to make sure I understood your analysis: 

Do we want to:

- show the generic message "Password policy not met" for the user update endpoint, as is currently the case for the user creation.

OR

- adapt the user creation endpoint so that a more specific message is shown as is done in this PR.

?

**Comment by sguilhen** [comment]
@etiksouma actually I was wondering if:

1- we should add a `catch(PasswordPolicyNotMetException e)` to the update user, and have it aligned with the user creation, or
2- use your fix, then follow up with a similar approach to the user creation.

Either way would bring consistency to the create and update user scenarios.

I am in favor of the second for now, but I wanted to hear other thoughts just to ensure there's no special reason why we are not returning the original `ModelException`  along with the `BAD_REQUEST` responses.

**Comment by etiksouma** [comment]
@sguilhen so I further analyzed the portion of code regarding PasswordPolicyNotMetException. 
Based on how/where this exception class is used I do not really see a business need for it, except adding more context (username) to logging in the "realms import" endpoint [here](https://github.com/keycloak/keycloak/blob/4f0298daaeaffea22f8356e4c75f237ed8d37097/services/src/main/java/org/keycloak/services/resources/admin/RealmsAdminResource.java#L168). 

The exception class was added as part of the ticket "KEYCLOAK-6146 realm import fails when password policy is specified". So I can understand that there was maybe a need to see exactly for which user the password policy did not match, since users are bulk-imported during realm import.

But even that change does not really help at the API level: Triggering a password policy error during a realm import does not produce a meaningful error. The current body value is ""errorMessage": "Password policy not met. See logs for details"".

That is different for the 2 other places where the exception is used: "user creation" and "user update". These 2 endpoints are "atomic" and the user is already known from the context. So there is really no need for this exception in these places.

That's why I updated the code and made sure the PasswordPolicyNotMetException is removed from user endpoints.
But I kept it for "realm import" for now. This endpoint needs a meaningful message for password policy errors so that API users can easily pinpoint the wrong data.

 So I would have rather completely removed the PasswordPolicyNotMetException class. But the last point regarding realm import needs to be clarified first.

**Comment by etiksouma** [comment]
There is one big issue with directly formatting ModelException messages and send them to the API user: Model Exception seems to be generic and returns many "API-unfriendly" messages, for example technical issues that an API user may not need to know. Here is one, detected thanks to the integration tests: "Kerberos unreachable".

@sguilhen I think the safest way under such conditions would be to go with the first option: add catch blocks for PasswordPolicyNotMetException where necessary and leave generic messages for ModelExceptions. What do you think?

**Comment by sguilhen** [comment]
> There is one big issue with directly formatting ModelException messages and send them to the API user: Model Exception seems to be generic and returns many "API-unfriendly" messages, for example technical issues that an API user may not need to know. Here is one, detected thanks to the integration tests: "Kerberos unreachable".
> 
> @sguilhen I think the safest way under such conditions would be to go with the first option: add catch blocks for PasswordPolicyNotMetException where necessary and leave generic messages for ModelExceptions. What do you think?

@etiksouma Yeah, that's exactly what I've been thinking too.. many of those exceptions are not API friendly, so I think we should handle the `PasswordPolicyNotMetException` where necessary (we can/should probably return the original message in the exception as that is more descriptive than generic "Password policy not met" that gives really no indication about what the policy expects).

**Comment by sguilhen** [comment]
So what I would do here: add a catch block for this exception in the  `UserEndpoint`, properly format the message, etc, and leave the remaining model exceptions unchanged. Then in `UsersResource` I would just make sure the policy exception is handled in the same way for consistency (i.e. format, get the original exception, etc).

**Review by sguilhen — APPROVED** [review]

**Comment by sguilhen** [comment]
@pedroigor we need the CI running again, the changes look good to me now!

**Review by ahus1 — APPROVED** [review]
Approving based on @sguilhen's review.

**Pull request merged**
