### PR TITLE
[KEYCLOAK-7659] - k_version not supporting cors

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by vramik — APPROVED** [review]
@pedroigor cool, thanks

**Comment by stianst** [comment]
Why should k_version support CORS? I would rather us remove that all together.

**Comment by pedroigor** [comment]
@stianst, I don't know. But we always had tests for this. I think question is if can we remove without break backward compatibility ? Not sure if there are people using this.

**Review by mposolda — APPROVED** [review]
@stianst @pedroigor @vramik How to continue with this? IMO we need at least to fix the DeploymentArchiveProcessorUtils. That is clearly a typo and will be good to fix ASAP (someone else may see and investigate test failures related to this even if it is already fixed in this PR).

For the PreAuthActionsHandler, my vote is to add cors support, but maybe deprecate/remove the endpoint in the future. WDYT? I am approving this PR as I am happy to do it this way.

**Comment by pedroigor** [comment]
@mposolda tks.

**Pull request merged**
