### PR TITLE
KEYCLOAK-9837 Not hide exception in email templating

### PR DESCRIPTION
**Pull request by dometec**

### CODE REVIEW

**Comment by abstractj** [comment]
@dometec JIRA is missing and commit message needs updating. Please see https://github.com/keycloak/keycloak/blob/master/CONTRIBUTING.md for details

**Comment by dometec** [comment]
@abstractj Hi Bruno, you right, I'm going to create a JIRA bug. I need to understand how to change the commit message...

**Comment by abstractj** [comment]
@dometec just look for `--amend` on git. See: https://help.github.com/en/articles/changing-a-commit-message. I hope it helps.

**Comment by dometec** [comment]
@abstractj I'm not so happy with this PR since now I see 5 commits... would you like to delete this PR? I'll send a new one...

**Comment by abstractj** [comment]
@dometec sure, whatever works best for you. Just leave the link to the new PR before you close for further reference.

**Comment by abstractj** [comment]
@dometec it has been a while since we requested changes to this PR. While the submission is appreciated, we are not able to merge it without these changes. Because it has been so long, we are going to close the issue. Feel free to reopen with the changes included, if your time permits.

**Pull request closed without merging**
