### PR TITLE
KEYCLOAK-14208 Default client profiles for FAPI

### PR DESCRIPTION
**Pull request by mposolda**

### CODE REVIEW

**Comment by mposolda** [comment]
@vmuzikar @tnorimat Do you please have a chance to review? The PR adds the "global" profiles for FAPI.

Default executors are approximately aligned with the discussion from the keycloak-dev mailing list: TODO. With some small changes based on our last discussion (for example ID Token as Detached signature, which was discussed later than this keycloak-dev discussion for global profiles).

I am marking this PR as draft as I have still few things to discuss:
- I would like to try FAPI Conformance testsuite to run with this PR and with global "FAPI Advanced" profile. It is possible that some changes will be needed in the global profile due the fact that latest conformace testsuite is not compliant with "FAPI 1 Final", but rather with "FAPI 1 ID2" . @tnorimat If you have a chance to try conformance testsuite as well, it will be nice, so that we verify on more fronts :-)

- I've added small change in app.js to display the global FAPI profiles in the JSON editor. I am not sure if this is good idea or not. It looks as possibly good idea to me due the fact that administrator can just easily copy/paste the JSON from global profile and use it as a "template" if he wants to create his own global profile, which differ just a little bit from the global profile. But if you guys think that this is not good idea, I can remove it from the PR. WDYT?

- I think there is some small bug that boolean properties are marked in the JSON as strings. For example:
```
   "auto-configure" : "true"
```
It seems that when some executor/condition with the boolean configuration property is saved, it saves the property as string "true" . Similarly when I update it by hand and change it to proper boolean:
```
  "auto-configure" : true
```
then admin console reads it as off. I will create JIRA tomorrow for this, and will likely not fix it in this PR, but just fyi...

**Review by vmuzikar — APPROVED** [review]
I'm not very familiar with FAPI specs so I did just a quick review (given our timeframe). LGTM.

**Review by vmuzikar — CHANGES_REQUESTED** [review]
Although there seem to be some test failures.

**Comment by mposolda** [comment]
@vmuzikar Thanks for the review. I am closing this PR. Details in the comment https://github.com/keycloak/keycloak/pull/8093#issuecomment-851282519

**Pull request closed without merging**
