### PR TITLE
ci: bump actions-setup-minikube to v2.7.2

### PR DESCRIPTION
**Pull request by manusa**
The current action version might have trouble with recent versions of Minikube. Especially since the latest release of crictl (this morning).

Relates to:
- https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.26.0
- https://github.com/manusa/actions-setup-minikube/releases/tag/v2.7.2

### CODE REVIEW

**Comment by abstractj** [comment]
Thank you @manusa 

@vmuzikar @andre-nascimento-rh could you please review?

**Review by vmuzikar — COMMENTED** [review]
@manusa Thank you, LGTM.

Let's wait for the CI now.

**Review by andre-nascimento6791 — COMMENTED** [review]
It seems OK, @manusa . Good Job!

Let's wait for the CI now.

**Review by stianst — CHANGES_REQUESTED** [review]
Please hold this PR until https://github.com/keycloak/keycloak/pull/15968 has been merged

**Review by stianst — DISMISSED** [review]

**Review by vmuzikar — APPROVED** [review]
@manusa LGTM, thanks!

**Review by abstractj — APPROVED** [review]

**Pull request merged**
