### PR TITLE
KEYCLOAK-15256 GroupMembershipMapper support nested json fields

### PR DESCRIPTION
**Pull request by fkowal**
Problem

TokenClaimName=https://hasura\.io/jwt/claims.x-hasura-allowed-ids
Results in generating "https://hasura\\.io/jwt/claims.x-hasura-allowed-ids": [....]

Rather then:
"https://hasura.io/jwt/claims": {"x-hasura-allowed-ids": [...]}

### CODE REVIEW

**Comment by swistaczek** [comment]
Hey, we encounter a similar bug in our runtime. Is there any chance to get this reviewed and merged? 

cc: @mposolda

**Review by slaskawi — CHANGES_REQUESTED** [review]
The code seems fine but we definitely need a test to prevent this from breaking again.

**Comment by slaskawi** [comment]
@fkowal Once you fix this, please let me and @mposolda know.

**Comment by fkowal** [comment]
ping @mposolda @slaskawi

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Thank you for the PR. The update in the code looks good.
However the test needs to be changed into a proper integration test. Mock frameworks like mockito are not permitted in Keycloak codebase. See e.g. `OIDCProtocolMappersTest` on the approach to the test.

**Comment by slaskawi** [comment]
I totally agree with @hmlnarik here. Please avoid Mockito.

You may also look into `GroupMappersTest` but I guess putting your tests in `OIDCProtocolMappersTest` might be a better idea.

**Comment by hmlnarik** [comment]
@fkowal Can you please rebase and update as requested above?

**Comment by hmlnarik** [comment]
Closing as this PR has had no activity for past few weeks. Feel free to resubmit with the review comments above addressed.

**Pull request closed without merging**
