### PR TITLE
KEYCLOAK-18903 More customizable OIDC WellKnown provider

### PR DESCRIPTION
**Pull request by mposolda**

### CODE REVIEW

**Comment by mposolda** [comment]
@pedroigor Do you have a chance for the review? PR allows possible to easily customize OIDC Well-Known endpoint by:
- Add the possibility with override some values with custom JSON file provided through the provider config
- Allow to make it easily to have custom provider available under URL "openid-configuration" if better customization is needed

Things should be backwards compatible and I've checked that custom provider from consultants for OpenBanking Brazil still works as expected with no changes needed.

**Review by pedroigor — DISMISSED** [review]

**Comment by pedroigor** [comment]
@mposolda Awesome!

**Review by pedroigor — APPROVED** [review]

**Comment by mposolda** [comment]
@pedroigor Thanks!

**Comment by Stefan774** [comment]
Hi we want to configure/customize our https://<keycloak-server-url>/auth/realms/A123/.well-known/openid-configuration

We need to override the attribute mtls_endpoint_aliases

I think this is what your commit does? But I can not figure out how to get it running. Could you provide an example like – configuration in domain.xml and where to put the *.json file? Probably an example of the *.json (override config) content would be really helpful.

**Pull request merged**
