### PR TITLE
Clarify note about containers

### LINKED ISSUE #26006: Clarification needed of use of containers
### Description

The note about what is supported needs to be clarified.  This only affects downstream however.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andymunro**
Closes #26006
@ahus1 Can you review this PR?

### CODE REVIEW

**Review by miquelsi — APPROVED** [review]

**Review by vmuzikar — DISMISSED** [review]
@andymunro LGTM, thanks!

**Comment by andymunro** [comment]
@ahus1 Can you merge this PR?

**Comment by andymunro** [comment]
@ahus1 I just updated the  branch and signed-off. Let me know it looks okay.

**Review by ahus1 — APPROVED** [review]
Approving as of @wfink's review

**Pull request merged**
