### PR TITLE
KEYCLOAK-14143 Turn OIDC requested scopes validation into an SPI

### LINKED ISSUE #8751: Config option for validation of requested scopes
### Description

In my company we created custom SPIs that use the value from the scope to limit our returned internal roles, but since version 10.0.0, it is not accepting any scope that is not previously creted in keycloak. I'm receiving the folowing error

"error_description": "Invalid scopes: openid application:salesforce"

The scope application:salesforce, is not registered in keycloak, looking at the source I didn't find a way to turn this validation off.

It would be useful to provide a configuration option to turn off strict validation of requested scopes. See https://groups.google.com/g/keycloak-dev/c/HnkPTMLCN3g/m/3uK8ZaC5AgAJ

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-14143

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by reda-alaoui**
Fix #8751

This change turns OIDC requested scopes validation into an SPI.

### CODE REVIEW

**Comment by reda-alaoui** [comment]
CI says ClientInvalidationClusterTest is failing.

However, this test is green on my computer when running:
```
 mvn -f testsuite/integration-arquillian/pom.xml clean install \
    -Pauth-server-cluster-quarkus \
    -Dsession.cache.owners=2 \
    -Dtest=ClientInvalidationClusterTest
```

**Comment by reda-alaoui** [comment]
Also green on my computer with:
```
mvn -f testsuite/integration-arquillian/pom.xml clean install     -Pauth-server-cluster-quarkus     -Dsession.cache.owners=2 -Dtest=**.cluster.**
```

**Review by PiryazevAlex — DISMISSED** [review]

**Review by borukho — APPROVED** [review]

**Review by borukho — DISMISSED** [review]

**Comment by stianst** [comment]
I appreciate the current behaviour is not great, but not sure we should require custom providers to be more flexible. Can we have a discussion on the dev mailing list around this topic?

**Comment by leandrobortoli** [comment]
A discussion has been started on the dev mailing [here](https://groups.google.com/g/keycloak-dev/c/yGCWth8reNw/m/bstLz0NoAwAJ). I would greatly appreciate it if this topic gained more attention as we also have a technical impediment regarding dynamic scopes.

**Comment by mposolda** [comment]
@reda-alaoui @PiryazevAlex @borukho Thanks for the contribution and feedback! I am closing this PR sincewe took a bit different approach after all and in recent Keycloak version (Keycloak 17), there is new feature of parameterized/dynamic scopes, which is supposed to handle use-cases like this. You will need to enable feature "dynamic_scopes" and when you do it, there is new field when creating client scope, which allows to setup this client scope as dynamic. So for example having dynamic scope like "foo" will allow that KEycloak would understand all the scopes like "foo:bar" or "foo:something-else" .

The feature is still being developed by @dgozalo , so feedback is welcome if the current Keycloak does not support your requested use-cases. In that case, feel free to create new issue in the GH and describe your use-case and possibly tag Daniel and/or me in the GH issue

**Pull request closed without merging**
