### PR TITLE
Add missing parameter to the JpaRootAuthenticationSessionEntity const…

### LINKED ISSUE #15093: JPA Map Storage: JpaRootAuthenticationSessionEntity constructor missing version parameter
### Describe the bug

While working on a possible fix for #13210 by adding a new field to this entity with a separate finder method, hibernate complained that the constructor was missing one parameter. Further investigating the issue, the missing parameter turns out to be the version used for optimistic locking.

Looking into `JpaRootAuthenticationSessionMapKeycloakTransaction`, the `selectCbConstruct` method includes the version, which makes hibernate look for a constructor that matches the signature provided in this method.

https://github.com/keycloak/keycloak/blob/dfb2bd144ba972e363d9f70e271678052e870880/model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/authSession/JpaRootAuthenticationSessionMapKeycloakTransaction.java#L43-L52

### Version

19.0.3

### Expected behavior

 The entity constructor must have arguments that match those specified in the respective transaction class.

### Actual behavior

As of now there's no exception or error displayed because we currently have no finder methods in the root auth session provider that would use the read with query parameters, so the error is not visible. But the mismatch between the root auth session tx and entity exists.

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sguilhen**
…ructor.

Closes #15093

### CODE REVIEW

**Review by vramik — APPROVED** [review]
Thank you @sguilhen for the fix.

**Review by ahus1 — APPROVED** [review]
An earlier run of the model tests failed with the known unstable test of #14917, so I approve this change and recommend to merge this PR anyway.

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
