### PR TITLE
[DO NOT MERGE] KEYCLOAK-7940 Keystore unification

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.jboss.org/browse/KEYCLOAK-7940

This is proposal of Keystore unification. More info on dev mailing list.

Please do not merge it. This PR is only for previewing reasons and for Travis.

### CODE REVIEW

**Comment by slaskawi** [comment]
I already noticed the failure. See the mailing list for more explanation.

**Review by hmlnarik — COMMENTED** [review]
We do not need that many keystores generated with every adapter run. Each generation takes several seconds, slowing down the adapter tests that are already overly slow. Lets number of keystores low and use two keystores for all adapter tests so that we can test that we don't accept invalid cert. The key size can also only stay very low since we're not in real environment. 512 bits should be more than enough and keep the generation time even faster.

**Comment by hmlnarik** [comment]
@slaskawi, Is this PR still relevant?

**Comment by slaskawi** [comment]
@hmlnarik +1, let me close it.

**Pull request closed without merging**
