### PR TITLE
Enhancement: Adding user and client information to the revoke grant event

### PR DESCRIPTION
**Pull request by intellitour**
I couldn't find an open issue on JIRA nor the mailing. This is an enhancement I've been using for a while, as a part of the efforts to achieve compliance with LGPD (sort of Brazilian GPDR). With this, an event listener could get user and client IDs involved in a revoke grant event.

### CODE REVIEW

**Review by mposolda — CHANGES_REQUESTED** [review]
@intellitour Thanks! I think this works, but few points:
- Could you please GH issue for this? And then comment here with the reference to this GH issue?
- Could you please rebase on top of latest Keycloak main? This is needed as currently there is conflict in this PR
- Could you please `AccountRestService.deleteConsentForClient()` and check that REVOKE_GRANT event, which is checked in this test, also contains correct client? Strictly speaking, I think it should already have correct user (at least that is what I am seeing), so in theory, there is no need to add `user` to the event like you did in your PR. But feel free to keep the user in this PR.

**Comment by intellitour** [comment]
@mposolda A little over one year have passed... I don't even have my test environment set anymore. 

Adding the user to the event is all this PR is about. I did this because when you catch the `REVOKE_GRANT` event, there was no user information whatsoever.

I will setup my test environment and first test if, in the current version, this PR is still needed and if so, I will go forward on this.

**Comment by mposolda** [comment]
@intellitour +1 for doublecheck current Keycloak first. As I see that there is actually user already available in the REVOKE_GRANT event in latest Keycloak main. Client is available in the "revoked_client" event detail. So yes, it is the question if this change is even needed in current Keycloak main. You can doublecheck and you will see...

**Comment by mposolda** [comment]
I am closing this as there is no further response and it seems this PR is out-of-date as "user" is now available on the REVOKE_GRANT event.

Client is also available in the `revoked_client` event detail. The "client" on the event is the client, which triggered the request to account REST API to revoke grant (Usually `account` client or some other client with the account roles like `manage-account` available)

**Pull request closed without merging**
