### PR TITLE
Update OpenShift REST client to fix a critical vulnerability on the transitive dependency com.squareup.okhttp3:okhttp

### LINKED ISSUE #14641: Update OpenShift REST client to fix a critical vulnerability on the transitive dependency com.squareup.okhttp3:okhttp
# Overview

[com.squareup.okhttp3:okhttp](https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp) is a HTTP & HTTP/2 client for Android and Java applications and a transitive dependency coming from OpenShift REST Client.

Affected versions of this package are vulnerable to Information Exposure. When there's an illegal character in a header value, an `IllegalArgumentException` is thrown whose message includes the full header value.

# Remediation

Upgrade OpenShift REST Client fixed it on 9.0.5.Final release which can be a breaking change for us.

# References

-   [GitHub Commit](https://github.com/square/okhttp/commit/1fd7c0afdc2cee9ba982b07d49662af7f60e1518)
-   [GitHub Issue](https://github.com/square/okhttp/issues/6738)
-   https://github.com/square/okhttp/issues/6738

### PR DESCRIPTION
**Pull request by abstractj**
transitive dependency com.squareup.okhttp3:okhttp

Resolves #14641

### CODE REVIEW

**Review by sguilhen — COMMENTED** [review]
@martin-kanis would this have to be productized too? Latest version on PNC seems to be 9.0.0.

**Comment by abstractj** [comment]
@vmuzikar if you have some time, would you be able to check if the failures for the Operator CI are related with those changes?

**Review by vmuzikar — DISMISSED** [review]
The Operator CI looks green to me. :) The Operator doesn't use this OpenShift client so it shouldn't be affected.

**Comment by martin-kanis** [comment]
> @martin-kanis would this have to be productized too? Latest version on PNC seems to be 9.0.0.

It should be eventually productized. Timeline depends on what product stream are we gonna include it to. The project is productized  by Thorntail team so the work should be coordinated with them. CC @pskopek

**Review by martin-kanis — DISMISSED** [review]

**Comment by abstractj** [comment]
@pskopek would you be able to review those changes when you get the time? I will rebase it.

**Review by drichtarik — DISMISSED** [review]
I can confirm the new version has been productized in our internal build system and the test build has passed by using the correct version.

**Review by sguilhen — DISMISSED** [review]

**Pull request merged**
