### PR TITLE
[issue-33536] js/apps/keycloak-server does not start anymore

### LINKED ISSUE #33536: js/apps/keycloak-server does not start anymore
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When starting the `js/apps/keycloak-server` an error occurs:

```
> node ./scripts/start-server.js "--admin-dev"

Downloading and extracting server…
Starting server…
login:v2 has an unrecognized feature, it should be one of [account-api, account3, admin-api, admin-fine-grained-authz, admin2, authorization, cache-embedded-remote-store, ciba, client-policies, client-secret-rotation, client-types, clusterless, declarative-ui, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, kerberos, login1, login2, multi-site, oid4vc-vci, opentelemetry, organization, par, passkeys, persistent-user-sessions, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn].
account:v3 has an unrecognized feature, it should be one of [account-api, account3, admin-api, admin-fine-grained-authz, admin2, authorization, cache-embedded-remote-store, ciba, client-policies, client-secret-rotation, client-types, clusterless, declarative-ui, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, kerberos, login1, login2, multi-site, oid4vc-vci, opentelemetry, organization, par, passkeys, persistent-user-sessions, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn]
```

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

Server to start.

### Actual behavior

```
> node ./scripts/start-server.js "--admin-dev"

Downloading and extracting server…
Starting server…
login:v2 has an unrecognized feature, it should be one of [account-api, account3, admin-api, admin-fine-grained-authz, admin2, authorization, cache-embedded-remote-store, ciba, client-policies, client-secret-rotation, client-types, clusterless, declarative-ui, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, kerberos, login1, login2, multi-site, oid4vc-vci, opentelemetry, organization, par, passkeys, persistent-user-sessions, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn].
account:v3 has an unrecognized feature, it should be one of [account-api, account3, admin-api, admin-fine-grained-authz, admin2, authorization, cache-embedded-remote-store, ciba, client-policies, client-secret-rotation, client-types, clusterless, declarative-ui, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, kerberos, login1, login2, multi-site, oid4vc-vci, opentelemetry, organization, par, passkeys, persistent-user-sessions, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn]
```

### How to Reproduce?

Start dev keycloak server

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by antikalk**
Fixes #33536

### CODE REVIEW

**Comment by jonkoops** [comment]
This is probably not the correct fix. Looking at the code in #33458 the original implementation is actually correct. The issue here is likely that e8d8de8936479f6fa1ca6fe1245e8a38614e33b6 only landed just today, and we have not yet had a nightly build (which is used by the script).

I believe this problem will fix itself once the next nightly is published, so I'll close this PR. We can re-open if this is not the case.

**Comment by antikalk** [comment]
@jonkoops I can confirm that this works as intended now with the new nightly being available.

**Comment by jonkoops** [comment]
Thanks for verifying that @antikalk, and apologies for the disruption.

**Comment by w0pp** [comment]
> @jonkoops I can confirm that this works as intended now with the new nightly being available.

Are you sure this works as intended now? Because when I follow https://www.keycloak.org/2024/09/keycloak-customizable-ui and run:
```
npm create keycloak-theme@latest my-theme
npm install
npm run start-keycloak
```
I still get these errors:
```
login2 is an unrecognized feature, it should be one of [account, account-api, admin, admin-api, admin-fine-grained-authz, authorization, cache-embedded-remote-store, ciba, client-policies, client-secret-rotation, client-types, clusterless, declarative-ui, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, kerberos, login, multi-site, oid4vc-vci, opentelemetry, organization, par, passkeys, persistent-user-sessions, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn].
account3 is an unrecognized feature, it should be one of [account, account-api, admin, admin-api, admin-fine-grained-authz, authorization, cache-embedded-remote-store, ciba, client-policies, client-secret-rotation, client-types, clusterless, declarative-ui, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, kerberos, login, multi-site, oid4vc-vci, opentelemetry, organization, par, passkeys, persistent-user-sessions, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn]
```

**Comment by jonkoops** [comment]
That is a different script, but it seems like a valid bug. Please log a new issue and it will be triaged.

**Pull request closed without merging**
