### PR TITLE
Update to Quarkus 3.2.8

### LINKED ISSUE #24160: HTTP/2 - Last parameter of POST form data contains 0x00 byte in some configurations.
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

This is a different manifestation of a previous issue with HTTP/2 handling and empty dataframes - https://github.com/keycloak/keycloak/issues/13315

When an HTTP/2 capable client sends POST data to a Keycloak instance running the current nightly codebase and also ends the HTTP/2 stream with an empty dataframe, the last parameter in the POST data will have a `0x00` byte appended to it. 

This current issue will show up in odd ways - such as Keycloak responding that `grant_type=client_credentials` is an invalid grant type when used at the OIDC Token endpoint, or that PKCE values are invalid.

This is ultimately a problem that should be handled by the resteasy-reactive implementation, but logging this bug for tracking purposes within Keycloak itself.

### Version

main / nightly

### Expected behavior

No `0x00` byte is appending to any form parameters.

### Actual behavior

`0x00` byte is appended to last form parameter, breaking various flows and making the deployment unusable.

### How to Reproduce?

Background:
Our deployment makes use of Openshift, and that uses HAProxy configured to reencrypt and send data to the backend (Keycloak) using http/2 - the HAProxy implementation uses an empty dataframe to close the stream.

Actually reproducing it:
Configure Keycloak with HTTPS and an appropriate TLS certificate.
Use the reproducer code from https://github.com/keycloak/keycloak/issues/13315#issuecomment-1238125070
Debug the code in Keycloak and notice that the last form parameter contains an additional `0x00`

Alternatively, without using Keycloak, it can be reproduced using a generic quarkus app + some of the constructs Keycloak uses

See - https://github.com/jsorah/reproducer/tree/null_bytes_appended_to_form_data

### Anything else?

Disabling HTTP/2 will prevent this issue from occurring.

### LINKED ISSUE #24638: Update to Quarkus 3.2.8
The Quarkus team release 3.2.8 with some relevant bug fixes, for more details please see: https://github.com/quarkusio/quarkus/releases/tag/3.2.8.Final

### PR DESCRIPTION
**Pull request by abstractj**
Closes #24638
Closes #24160

### CODE REVIEW

**Review by shawkins — DISMISSED** [review]

**Comment by jsorah** [comment]
Based on my testing, this should also fix https://github.com/keycloak/keycloak/issues/24160

Not sure of the etiquette if we should add another closes for that one to also link the PR or if the mention is enough.

**Comment by ahus1** [comment]
@abstractj / @vmuzikar - I've updated some version in Keycloak's POM that should match Quarkus' parent POM in a second commit. Please squash the commits before merging.

**Review by vmuzikar — DISMISSED** [review]

**Comment by vmuzikar** [comment]
@abstractj Thanks for the PR.

Seems there's some issue with the Operator OLM tests. I'll look into it.

**Comment by vmuzikar** [comment]
@abstractj @shawkins Created https://github.com/abstractj/keycloak/pull/2

**Comment by abstractj** [comment]
> Based on my testing, this should also fix #24160
> 
> Not sure of the etiquette if we should add another closes for that one to also link the PR or if the mention is enough.

Thanks for pointing that out @jsorah. Updated the commit message to reflect that.

**Review by vmuzikar — APPROVED** [review]

**Review by mabartos — APPROVED** [review]
LGTM

**Comment by ahus1** [comment]
@abstractj - there have been some expired certificates, which have just been updated in main. You might need another CI run before all your tests are green. See #24657.

**Comment by shawkins** [comment]
@abstractj @vmuzikar @vietj the issue with the javascript adapter tests appear to be due to changes in the vertx forwarding logic.  

The problematic request is explicitly setting an empty host:

```
sec-ch-ua="Not/A)Brand";v="99", "HeadlessChrome";v="115", "Chromium";v="115"
sec-ch-ua-mobile=?0
sec-ch-ua-platform="Linux"
upgrade-insecure-requests=1
user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/115.0.5790.110 Safari/537.36
accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
sec-fetch-site=none
sec-fetch-mode=navigate
sec-fetch-user=?1
sec-fetch-dest=document
accept-encoding=gzip, deflate, br
host=
```

The forwarding logic then creates an empty authority and will calculate absolute uris that lack a host https:/auth/admin...

I'm not sure if this this intended to be a protection mechanism when the host isn't populated, or if it should still infer the host - someone else will need to weigh in on a fix.

**Comment by vmuzikar** [comment]
@shawkins Thanks for investigating. I think we need someone from @keycloak/ui to chime in.

**Comment by vmuzikar** [comment]
@shawkins Actually, which request exactly do you mean is missing the header? A JS Adapter created request?

**Comment by shawkins** [comment]
> @shawkins Actually, which request exactly do you mean is missing the header? A JS Adapter created request?

I would presume it is coming from there yes.

**Comment by jonkoops** [comment]
I did some testing with @vmuzikar, and to me it doesn't look like this is an error caused by Keycloak JS or any other client-side code for that matter. I was able to run the test and get it to fail using the following command:

```sh
mvn test -Dtest=JavascriptAdapterTest#testLocationHeaderInResponse -Pauth-server-quarkus
```

The test only seems to fail when the Quarkus server is enabled using `-Pauth-server-quarkus`. The failure here is as follows:

```log
JavascriptAdapterTest.testLocationHeaderInResponse:654->lambda$testLocationHeaderInResponse$2a7ea37a$1:658 
Expected: a string containing "location: https://localhost:8543/auth/admin/realms/test/users/044f3ca4-af90-4ecb-b6b6-63d36a9cc2fd"
     but: was "access-control-allow-credentials: true
access-control-allow-origin: https://localhost:8543
access-control-expose-headers: location
content-length: 0
location: https:/auth/admin/realms/test/users/044f3ca4-af90-4ecb-b6b6-63d36a9cc2fd
referrer-policy: no-referrer
strict-transport-security: max-age=31536000; includesubdomains
x-content-type-options: nosniff
x-frame-options: sameorigin
x-xss-protection: 1; mode=block
"
```

Specifically, the value of the `location` header returned here is malformed, causing the test to fail:

```diff
-https://localhost:8543/auth/admin/realms/test/users/044f3ca4-af90-4ecb-b6b6-63d36a9cc2fd
+https:/auth/admin/realms/test/users/044f3ca4-af90-4ecb-b6b6-63d36a9cc2fd
```

For some reason the domain name is being stripped from the URL returned from the server. This seems to be a regression in Quarkus.

Looking at [the changelog](https://github.com/quarkusio/quarkus/releases/tag/3.2.8.Final) it looks like https://github.com/quarkusio/quarkus/issues/36234 might have something to do with this, which leads to https://github.com/eclipse-vertx/vert.x/issues/4879, which unfortunately does not have a commit or PR associated with it.

Either way, I think this is a Quarkus bug, or we're not passing something into it correctly on our side. It cannot be a client-side bug, as we're not allowed to set the `Host` header since it's a [forbidden header name](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name).

**Comment by shawkins** [comment]
@jonkoops that is correct, it is not coming directly from the client side.

> For some reason the domain name is being stripped from the URL returned from the server. This seems to be a regression in Quarkus.

Working backwards more from https://github.com/vert-x3/vertx-web/blob/a76e681af8313035ab7a772481d840a81051ecc9/vertx-web/src/main/java/io/vertx/ext/web/impl/ForwardedParser.java#L200 the header is being set by https://github.com/quarkusio/quarkus/blob/b9766f547d2c5c02715b5e35fda1c5f2f15904d8/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/ForwardedParser.java#L202

The headers at this level show the host is missing, not empty:

```
sec-ch-ua="Not/A)Brand";v="99", "HeadlessChrome";v="115", "Chromium";v="115"
sec-ch-ua-mobile=?0
sec-ch-ua-platform="Linux"
upgrade-insecure-requests=1
user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/115.0.5790.110 Safari/537.36
accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
sec-fetch-site=none
sec-fetch-mode=navigate
sec-fetch-user=?1
sec-fetch-dest=document
accept-encoding=gzip, deflate, br
```

Which then gets set as an explicit empty value on the delegate, which then gets turned into the uri with the missing host.

For reference the offending request is coming into the RealmsResource.getProtocol method - test/protocol/openid-connect/

**Comment by shawkins** [comment]
> Looks to me like a Vert.x bug. WDYT?

Yes, vert.x or the vert.x extension logic in quarkus. 

This change looks suspect: https://github.com/quarkusio/quarkus/commit/d41c78bf553406c6026d28ff2795f096b9da184d#diff-26b0d509bb91cfaf3c4160496ea25fc584e85d4e2cc1b708eb72ea3b25b74c4dR124 - the old logic just called host(), which would return localhost:8543 in this case.

**Comment by jonkoops** [comment]
So I guess this will have to be reported as a bug for Quarkus, perhaps we can even submit a fix? Anyone willing to jump on that? Either way, it looks like we will not be able to upgrade to 3.2.8 until this is fixed upstream.

**Comment by vmuzikar** [comment]
@jonkoops @shawkins Yeah, definitely seems like a blocker that prevents us from upgrading. Is there an issue for it on Quarkus side already?

**Comment by shawkins** [comment]
Captured as https://github.com/quarkusio/quarkus/issues/37045

**Comment by vmuzikar** [comment]
jFTR – it was confirmed to be a Vert.x bug: https://github.com/vert-x3/vertx-web/issues/2511

Found also another reproducer. Just access KC via `https://127.0.0.1.nip.io:8443/` (needs to be TLS to make browser to use HTTP/2 and a real hostname, not localhost).

**Comment by vmuzikar** [comment]
Possible workaround would be to temporarily disable HTTP/2 in KC. But there'd be perf implications at the very least.

**Comment by abstractj** [comment]
> Possible workaround would be to temporarily disable HTTP/2 in KC. But there'd be perf implications at the very least

@vmuzikar my 2 cents. I'd wait for the next release with the fix.

**Comment by vmuzikar** [comment]
It was [confirmed](https://github.com/quarkusio/quarkus/issues/37045#issuecomment-1814472834) the Quarkus issue will be resolved in 3.2.9. Since we'll skip 3.2.8, I think we can close this PR.

**Comment by vmuzikar** [comment]
Superseded by https://github.com/keycloak/keycloak/pull/24842.

@abstractj Let me know if you have any concerns with closing this.

**Pull request closed without merging**
