### PR TITLE
Update to the latest version of the official actions used by Keycloak

### LINKED ISSUE #10971: Update to the latest version of the official actions used by Keycloak
### Description

We should consider updating our GitHub actions to the latest releases. Today we have:

- actions/checkout@v2
- actions/setup-java@v1
- actions/cache@v2
- actions/download-artifact@v2
- actions/upload-artifact@v2

Another alternative is to introduce a GH action to update other actions https://github.com/marketplace/actions/github-actions-version-updater

### Discussion

_No response_

### Motivation

- Keep our GitHub actions up to date

### Details

_No response_

### PR DESCRIPTION
**Pull request by abstractj**
Resolves #10971

### CODE REVIEW

**Review by jonkoops — DISMISSED** [review]

**Comment by jonkoops** [comment]
Sidenote. The `setup-java` action now also supports [caching Maven dependencies](https://github.com/actions/setup-java#caching-maven-dependencies). This means that in some cases the `cache` action can be removed by adding this option.

**Review by andreaTP — DISMISSED** [review]
Thanks!

**Review by DGuhr — DISMISSED** [review]

**Comment by abstractj** [comment]
The new release of `actions/setup-java` introduced some breaking changes on `v2`. Please see more details [here](https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md). The pull-request was updated with a new commit to reflect those changes. Once all the tests pass, I will squash my commits.

**Review by DGuhr — DISMISSED** [review]
Thanks for the clarification, and good to know. re-approved :)

**Review by vmuzikar — DISMISSED** [review]

**Comment by vmuzikar** [comment]
> Sidenote. The `setup-java` action now also supports [caching Maven dependencies](https://github.com/actions/setup-java#caching-maven-dependencies). This means that in some cases the `cache` action can be removed by adding this option.

+1 to this. @abstractj Should we tackle this as a follow-up?

**Review by jonkoops — DISMISSED** [review]

**Comment by abstractj** [comment]
> +1 to this. @abstractj Should we tackle this as a follow-up?

That makes sense, created https://github.com/keycloak/keycloak/issues/10987

**Review by vmuzikar — APPROVED** [review]

**Review by hmlnarik — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
