### PR TITLE
Remove inaccurate statement about master realm imports

### LINKED ISSUE #34301: Remove inaccurate statement about master realm imports
### Description

The import/export documentation mentions that importing of the master realm is not supported, but since 26.0.0 it is.

### PR DESCRIPTION
**Pull request by maxhov**
Remove inaccurate statement about master realm imports. This is supported since 26.0.0. Closes #34301.

### CODE REVIEW

**Comment by vmuzikar** [comment]
Thank you for the contribution! Could you please open and link an issue as per our [contributing guidelines](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md#commit-messages-and-issue-linking)? That would help us a lot with tracking this.

**Comment by maxhov** [comment]
@vmuzikar ok, created #34301

**Comment by shawkins** [comment]
@maxhov can you also update the commit message so that it references https://github.com/keycloak/keycloak/issues/34301 - something like:

closes: #34301

**Review by ahus1 — APPROVED** [review]
Thank you for this fix to the docs!

**Pull request merged**
