### PR TITLE
Fix for TOTP's look ahead window

### PR DESCRIPTION
**Pull request by piotr-sarna**
After fix TOTP window will check past and future OTP codes, instead of only past ones

### CODE REVIEW

**Comment by stianst** [comment]
I'm not sure I agree with this change. Can you please bring it up on the dev mailing list?

**Comment by thomasdarimont** [comment]
FYI the Lombok guys do the same in their [TOTP Best practices example app](https://github.com/rzwitserloot/totp-example)

https://github.com/rzwitserloot/totp-example/blob/master/src/main/java/org/projectlombok/security/totpexample/Totp.java#L253

**Comment by piotr-sarna** [comment]
I'm sorry I haven't respond for such a long time. When I was using keycloak, I encounted following problem -> sometimes when I generated TOTP on my phone(with proper set clock) and I passed it to keycloak, authentication didn't work without clear reason. I had to check your source code and only then I realized that the reason was wrong setting of time on the server(clock was slightly late) and my OTP was recognized as OTP from the future(from server's perspective).

I think keycloak should accept above mentioned situation, because desynchronization of clocks sometimes happen. Maybe it should accept only one TOTP from the future, it can be discussed.

Another approach is to make it more configurable and let administrator to decide.

**Comment by stianst** [comment]
We currently have the option to set 'Look Ahead Window' and by default it is set to 1. Simply using this to check before as well is not great as it behaves differently to documented.

We should rather introduce an extra 'Look Before Window' property and by default set it to 1.

We'd also need tests adding before we can add a PR for it.

**Comment by stianst** [comment]
Closing this PR for a few reasons:
* There should be separate look ahead and look before properties
* No JIRA
* No tests
* No response from contributor

**Pull request closed without merging**
