### PR TITLE
Switch to send SAML attributes as single attributeStatement element

### PR DESCRIPTION
**Pull request by josh-cain**
See KEYCLOAK-3323.

Test cases (manual):
- Swtich OFF
  - Send SAML assertion - two attributeStatement elements present
- Switch ON
  - Send SAML assertion with regular + role attributes - one attributeStatement element present
  - Send SAML assertion with regular attributes only - one attributeStatement element present
  - Send SAML assertion with role attributes only - one attributeStatement element present

### CODE REVIEW

**Comment by patriot1burke** [comment]
Instead, maybe we should just have one Attribute statement?

**Comment by cainj13** [comment]
I'd be fine with that.  I was assuming that we'd want to leave the two as-is to preserve legacy functionality.  I've seen crazy-specific implementations that have hard dependencies on stuff like number/content of attribute statements (hence the PR in the first place).  Not saying it's right, but I just wanted to be careful about breaking anyone.

Would you rather me update/new PR to make everything fall under a single attributeStatement?

**Comment by patriot1burke** [comment]
I'd rather just put it under a single attribute statement.  Too many config options as it is.

**Comment by cainj13** [comment]
Closing this one,  #3064 has been submitted with suggested changes.

**Pull request closed without merging**
