### PR TITLE
Avoid warnings on bean validation as we don't use it in JPA

### LINKED ISSUE #16502: Hibernate 6 upgrade: Warning about missing Bean Validation provider
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

When starting the model tests with Hibernate 6, there is an exception in the log as the following: 

> 12:02:15,914 INFO  [org.hibernate.cfg.beanvalidation.TypeSafeActivator] (main) Error calling `jakarta.validation.Validation#buildDefaultValidatorFactory`
jakarta.validation.NoProviderFoundException: Unable to create a Configuration, because no Jakarta Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.

### Version

nightly, Quarkus 3 Branch

### Expected behavior

No warning should appear

### Actual behavior

Warning appears

### How to Reproduce?

Run a model test, for example ClientModelTest (happens in LegacyJpa and JpaMapStorage)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #16502

### CODE REVIEW

**Comment by ahus1** [comment]
@vramik - it would be great if you could review it as you're working on the H6 upgrade as well once you have the time. Please let me know if you don't have the time, and then I'll look for a different reviewer.

**Review by vramik — APPROVED** [review]
Thanks @ahus1!

**Comment by ahus1** [comment]
@hmlnarik - this is now ready to be merged. Thanks!

**Comment by hmlnarik** [comment]
@ahus1 Could you please rebase?

**Comment by ahus1** [comment]
@hmlnarik - rebased, now building.

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
