### PR TITLE
Downgrade Oracle driver

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes #24983

Signed-off-by: Václav Muzikář <vmuzikar@redhat.com>

### CODE REVIEW

**Comment by vmuzikar** [comment]
Created a follow-up: https://github.com/keycloak/keycloak/issues/25046

**Comment by vmuzikar** [comment]
@ahus1 @ASzc Not sure if this is something we need to backport to 23, only needs to be ported to #24850. It should affect only RHBK installations where the driver is not included and needs to be put into `/providers` directory.

**Review by ASzc — APPROVED** [review]
LGTM. Backport to 23 is unnecessary. 22 may need it backported, but could also be documented as a known issue and fixed in 24.

**Comment by ASzc** [comment]
Well, I suppose the actual fix is going to need to come from Quarkus. As far as what this PR does, I can do that also on my end at build time, so if it's not backported that's what I'll do

**Review by ahus1 — APPROVED** [review]

**Pull request merged**
