### PR TITLE
KEYCLOAK-2670 - client app is able to push additional HTTP GET

### PR DESCRIPTION
**Pull request by velias**
parameters in initial OpenID auth request for use in Auth flows.

This is PR for KC 1.9.x branche. Once accepted and merged I'll prepare another PR with the same content for master branche.

### CODE REVIEW

**Comment by velias** [comment]
@stianst Travis failed on `BruteForceTest` but it works OK on my local machine and it is unrelated to my changes. Any idea what to do? I want to rerun test on travis, but I'm not sure how to do it :-(

**Comment by mposolda** [comment]
@velias I rerun the travis build (There is a button for "refresh build" on the right side when you click on the build details in travis UI)

**Comment by stianst** [comment]
Looking at this I'm actually a bit worried about this change. For example someone could add several query params with large values. This could then be used as a DoS attack. It may also be vulnerable to injection attacks, unless values are properly escaped.

**Comment by velias** [comment]
@mposolda thanks, I know that it is possible to rerun build, but I didn't see the button on Travis, maybe some permission prevent me from build rerun.

**Comment by velias** [comment]
@stianst good point about size of data, I'll limit number of additional params stored into ClientSession notes (let's say max 5 additional params will  be stored) and also limit max size of the param data (let's say 200 characters, which should be enough for common use cases). 
Regarding injection attack, we work with String in this part of code, so I do not see any possibility for attack there nor any need/possibility of escaping value there as we do not know how it will be used. Correct escaping is responsibility of the code which uses/process this data (eg if value will be printed into HTML it has to be html escaped in the template etc).

**Comment by patriot1burke** [comment]
We need a PR for master as well before I can commit this.

**Comment by velias** [comment]
@patriot1burke I know, I wanted to let stian and others to review this one before I prepare second PR for master.

**Comment by velias** [comment]
@stianst what do you think now?

**Comment by stianst** [comment]
I'm happy with it. @patriot1burke does it look good to you?

**Comment by stianst** [comment]
Can we have PR for master as well please?

**Comment by velias** [comment]
Sure, sorry, I was in a fire last week, going to prepare it this week definitely

**Pull request merged**
