### PR TITLE
:bug: Fix unclosed span bracket in register.ftl

### LINKED ISSUE #28409: Unclosed span bracket in register.ftl
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

Unclosed span bracket in register.ftl

### Version

24.0.2-0

### Regression

- [ ] The issue is a regression

### Expected behavior

Closed span bracket

### Actual behavior

Unclosed span bracket

### How to Reproduce?

Open register.ftl

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Firelods**
Closes #28409

### CODE REVIEW

**Review by pedroigor — APPROVED** [review]
@edewit @jonkoops LGTM

**Comment by pedroigor** [comment]
@Firelods Thanks. You need to sign-off the commit otherwise we are not able to merge it.

**Comment by jonkoops** [comment]
@Firelods you have to put the issue in the PR description, fixed it for you :slightly_smiling_face:

**Comment by Firelods** [comment]
> @Firelods Thanks. You need to sign-off the commit otherwise we are not able to merge it.

Done

**Review by jonkoops — APPROVED** [review]
Looks good to me, thanks @Firelods!

**Review by pedroigor — APPROVED** [review]

**Pull request merged**
