### PR TITLE
KEYCLOAK-9601 KEYCLOAK-9602 Jetty 8.1 and 9.1 removal

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.jboss.org/browse/KEYCLOAK-9601
https://issues.jboss.org/browse/KEYCLOAK-9602

### CODE REVIEW

**Comment by hmlnarik** [comment]
@slaskawi Could you please review and remove docs references too?

**Comment by slaskawi** [comment]
@hmlnarik Yes, docs references to Jetty 8.1 and 9.1 should be removed (the rest should remain). I also created a PR against the docs: https://github.com/keycloak/keycloak-documentation/pull/634.

If you spot any place, where Jetty 8.1 (or 9.1) is still there, leave me a comment. I obviously must have missed it...

**Comment by slaskawi** [comment]
@keycloak-ci-bot test

**Review by mhajas — APPROVED** [review]

**Review by vramik — DISMISSED** [review]
@slaskawi LGTM thanks

**Review by mhajas — CHANGES_REQUESTED** [review]
I just realised, that springboot adapter is under the hook using jetty 8.1 here:  https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/test-apps/spring-boot-adapter/pom.xml#L145 I talked with @pdrozd and he said it will probably need some discussion whether we can stop testing spring boot with jetty 8.1

**Comment by slaskawi** [comment]
> I just realised, that springboot adapter is under the hook using jetty 8.1 here: https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/test-apps/spring-boot-adapter/pom.xml#L145 I talked with @pdrozd and he said it will probably need some discussion whether we can stop testing spring boot with jetty 8.1

@mhajas @pdrozd I removed this profile. If you use it anywhere, please switch to `jetty-version-92`.

**Comment by slaskawi** [comment]
@keycloak-ci-bot test

**Review by hmlnarik — COMMENTED** [review]
distribution/adapters/osgi/features/src/main/resources/features.xml need to be updated as well.

**Comment by mhajas** [comment]
@hmlnarik I created commit with few other references to jetty81/jetty91 not sure whether all are relevant, but probably yes https://github.com/mhajas/keycloak/commit/ae67a017b783b14da31d4dcf9268c429387c76f2

**Comment by pdrozd** [comment]
Finally Jetty 8 can be removed, not used in Fuse 6.3

**Review by hmlnarik — APPROVED** [review]

**Review by mhajas — APPROVED** [review]

**Review by vramik — APPROVED** [review]

**Pull request merged**
