### PR TITLE
Normalize JVM heap usage in tests and handle OOM situations

### LINKED ISSUE #15487: Flaky test: Model Tests DBLockTest
### Area

testsuite

### Describe the bug

DBLockTest is failing intermittently on GitHub Actions.

### Version

main

### Expected behavior

Test always pass

### Actual behavior

Test fails randomly

### How to Reproduce?

See test failures for more information:

* https://github.com/keycloak/keycloak/actions/runs/3457308991/jobs/5770727415
* https://github.com/keycloak/keycloak/actions/runs/3452341510/jobs/5762248007

### Anything else?

_No response_

### LINKED ISSUE #16089: Normalize memory usage in tests and OOM behavior
### Description

When analyzing #15487, I found that the tests were using a platform dependent amount of heap memory. Also looking into H2, it revealed some out-of-memory handlers which would close the database in such a case automatically. In our test setup with H2, this would also wipe the data as we're using an in-memory-database. 

This normalizes the heap usage in tests, and terminates the VM in OOM situations for tests to make test execution more predictable.

### Motivation

While this wasn't the cause of any suspicious behavior observed with DBLockTest, this is still something that would help to eliminate causes in future unstable tests tests.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #16089

### CODE REVIEW

**Comment by hmlnarik** [comment]
Thank you for the PR, @ahus1.
Should heap dump be taken automatically on OOM?

**Comment by ahus1** [comment]
@hmlnarik - good idea. Will add this, and then upload it to the GitHub workflow so we would be able to download it.

**Comment by ahus1** [comment]
Example run in a personal repo which uploaded some heap dumps: https://github.com/ahus1/keycloak/actions/runs/3739915474

Each file name contains a process ID, and uploading a heap dump is a rare thing AFAIK, so I didn't care about duplicate file names. Let me know if someone thinks different about that.

**Review by hmlnarik — APPROVED** [review]
Thank you!

**Pull request merged**
