### PR TITLE
Update create realm topics to replace Master

### LINKED ISSUE #29280: Update Create Realm in Keycloak 24 Getting Started
### Description

The word "Master" has been removed

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andymunro**
Closes #29280

@ahus1 Please verify

### CODE REVIEW

**Comment by andymunro** [comment]
@ahus1 I see I need to update the branch.  Is it save to update with merge commit or update with rebase?

**Comment by ahus1** [comment]
@andymunro - no need to update unless there are conflicts. As there are no conflicts, there's nothing that need to be done from your side.

**Comment by andymunro** [comment]
@ahus1 However, it says merging is blocked.

**Comment by ahus1** [comment]
@andymunro - the fine print below mentions: "Merging can be performed automatically with 1 approving review."

So it is waiting for a maintainer to approve it. The the block will disappear.

**Comment by andymunro** [comment]
Okay, thanks, that make sense.

**Comment by andymunro** [comment]
@ssilvert or @jonkoops Can you approve this change to remove the word Master where it now says Keycloak?

**Review by ahus1 — APPROVED** [review]

**Pull request merged**
