### PR TITLE
KEYCLOAK-11496 detect session timeout

### PR DESCRIPTION
**Pull request by edewit**
Now detects that the session is no longer valid and instead of showing the 401 goes to 'login'

### CODE REVIEW

**Comment by vmuzikar** [comment]
@edewit Thank you for your contribution. Could you please remove the `@Ignore` annotations here?
https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/SessionTest.java#L64-L83
[Here](https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/keycloak-preview/account/resources/README.md#running-tests) you can find the instructions on how to run them.

**Comment by edewit** [comment]
I ran the tests locally, but I guess they are not working?
```
[ERROR] Tests run: 43, Failures: 35, Errors: 6, Skipped: 0
```

**Comment by edewit** [comment]
okay now that I read it again I see that I should have put `"` around it, but I still get a ton of errors.

**Comment by edewit** [comment]
how do you run the tests?

**Comment by vmuzikar** [comment]
@edewit Well, even though I run them through my IDE, it's basically [this command](https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/keycloak-preview/account/resources/README.md#running-tests) I mentioned above.

What tests are failing on your machine?
Just a silly question but did you try to rebuild the whole project (root POM)?

**Comment by edewit** [comment]
@vmuzikar pushed a new commit that fixes both cases

**Review by ssilvert — CHANGES_REQUESTED** [review]
@edewit There is one thing missing here.  When you call kcSvc.login(), you need to pass the proper redirect uri.  This way, when the user logs back in, he is redirected back to the page he was viewing.

However, this PR does fix the major problem so we should merge.  Please create a new JIRA saying that we need to enhance this PR and also enhance the tests.  Reference this PR in the JIRA and reference the JIRA in this PR.  Then we can merge and fix this JIRA at a later date.

**Review by vmuzikar — DISMISSED** [review]
@ssilvert Very good point with the redirect URI. Completely forgot about this when writing tests (probably because it didn't work at all :)).

Other than that LGTM.

**Comment by ssilvert** [comment]
@edewit Using window.location.href will break whenever there is a referrer uri.  So things are a little more complicated than they appear.  That's why I said you could just create a JIRA and we could come back to it later.  

However, if you want to implement the whole fix then just go to account console from the admin console.  That will give you a referrer.  Then you will see your code break when it tries to redirect back to the admin console after timeout/login.

To make the correct fix, look at ApplicationInitiatedActionPage and AIACommand to see how we construct the redirectUri.

You'll notice that referrerUri.replace('#', '_hash_') is a bit of a hack.  After the redirect back to the account console, _hash_ is replaced with #.  I haven't come up with a better solution.

**Review by ssilvert — APPROVED** [review]

**Comment by vmuzikar** [comment]
@ssilvert It's weird but it seems for some reason explicit redirect URI is not necessary after all. After reauthentication user is redirected back to the original page in Account Console. No need to create a follow-up JIRA (just maybe for the tests).

**Pull request merged**
