### PR TITLE
KEYCLOAK-12281 Fix export/import for users that have custom credentia…

### PR DESCRIPTION
**Pull request by mposolda**
…l algorithms with no salt

### CODE REVIEW

**Review by pskopek — CHANGES_REQUESTED** [review]
IMO, the PasswordSecretData:decodeSalt method should not handle the exception and leave just message in the log.
The constructor should throw IOException in case something is wrong and `"__SALT__"` value should be treated as NULL before even trying to decode it to base64.
I have created PR in your branch https://github.com/mposolda/keycloak/pull/5

**Comment by mposolda** [comment]
@pskopek Thanks for the review and for the follow-up PR!

I agree it is slightly better to handle it in constructor rather than by catching the exception. However the "salt" String passed to the constructor can also be null in some cases, which will later throw the NPE exception during Base64 decode. I commented in your PR, which you sent to me.

**Comment by mposolda** [comment]
@pskopek Merged your PR, Thanks for it. What do you think now?

**Review by pskopek — APPROVED** [review]
Looks good! Thanks @mposolda !

**Review by stianst — APPROVED** [review]

**Pull request merged**
