### PR TITLE
Fix typos found by codespell in docs

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
This commit fixes most of the obvious issues. More passes will be needed to fix (or not) more complex typos, for example in the API.

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you for the work you put into this. At the moment we are not accepting PRs which focus on code comments which are not user facing. We expect them to be fixed only when another change is done to the file to fix a bug or change a feature.

We prefer PRs that fix bugs or add features. As described in the CONTRIBUTNG.md, a PR should reference an issue. 

I see that you are fixing typos for example in the docs which are user-facing. I therefore ask you to reduce the PR to only user-facing content excluding log messages. If the documentation changes are unrelated to for example UI changes, I ask you to create separate PRs for them, as they will be reviewed by different people.

**Comment by DimitriPapadopoulos** [comment]
Classifying typos as code comments / user facing messages / log messages is hardly feasible in the long term, because many spelling tools are language-agnostic.

**Comment by DimitriPapadopoulos** [comment]
I limited this PR to `docs`.

**Review by ahus1 — APPROVED** [review]
Thank you for these changes. I approve them and will merge them. I had to revert one change (see e5e26895e2860e52ab0a4fdf21bb7c2e8c1cc186) as this the typo is actually present in the API it is documenting. 

To change this as well, as as it is a public API, one would need to first add a new method and deprecate the old one, write release notes, and then remove the old one  in a future release. This would require a separate PR.

**Comment by DimitriPapadopoulos** [comment]
Thank you for reverting the code change. My intent was not to modify code, this fell through the cracks... I will change the API (and some function parameter names) in a different merge request.

**Comment by ahus1** [comment]
@DimitriPapadopoulos - no worries. A note for future PRs: It helps me as a reviewer if all changes are on the same level, like in this case it was all typos in the docs. Let's stick to that as long as you make changes to a lot of files.

**Pull request merged**
