### PR TITLE
KEYCLOAK-3507 - Custom Pagination Directive

### PR DESCRIPTION
**Pull request by mohitsuman**
- Add custom pagination directive for tables in keycloak.
- Pagination for clients and roles section in admin console.
- Custom css as aligned with datatables in PatternFly.

### CODE REVIEW

**Comment by thomasdarimont** [comment]
Very useful! Thank you :)

**Comment by stianst** [comment]
@ssilvert can you review this? I don't think it's the correct approach. It would probably be better to have a directive that can add pagination to tables as this approach is still leaving a lot of boilerplate in each individual table.

**Comment by ssilvert** [comment]
I agree.  We'll create a directive for it later.

**Comment by thomasdarimont** [comment]
@ssilvert  perhaps @mohitsuman can give it another spin if you'd provide some directions :)

**Comment by ssilvert** [comment]
Sure.  Mohit can work some more if he likes.  This is open source.  We always want good code.  This task just needs a little more love before we consider it done.

**Pull request closed without merging**
