### PR TITLE
[KEYCLOAK-19616] Update Keycloak themes dependencies for the account and admin console

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Comment by ssilvert** [comment]
> @abstractj Why are the `node_modules` checked into the source control?

@jonkoops @abstractj I believe it was done this way because we didn't have an official npm repo internally.  And we have to be able to reproduce the exact bits for every build.  Downloading from public npm repo was not allowed.

We will be fixing this along with the new admin UI, of course.

**Comment by ssilvert** [comment]
I spoke with @Aboullos today and he is going to run the tests.

**Comment by Aboullos** [comment]
I tried to run the tests, first building Keycloak in this Jenkins build:
[jenkins].apps.ocp4.prod.psi.redhat.com/job/keycloak-build-pipeline/342 
But had an error when trying to download the Theme dependencies on keycloak-admin-ui, there is a 400 error when trying to get the file:
https://maven.pkg.github.com/keycloak/keycloak-admin-ui/org/keycloak/keycloak-admin-ui/16.0.0-SNAPSHOT/keycloak-admin-ui-16.0.0-SNAPSHOT.pom
Also checking the two GitHub Actions tests that failed they have a similar error:
- CodeQL / Analyze fails with the same code on the same file (`400` on `keycloak-admin-ui-16.0.0-SNAPSHOT.pom`)
- Keycloak CI / Model tests fails with a `401` on the file `maven-metadata.xml`

**Comment by jonkoops** [comment]
@abstractj could you rebase your branch? I believe the build failures might be happening because there are some missing changes from upstream.

**Comment by abstractj** [comment]
@jonkoops @ssilvert @Aboullos rebased, and thanks for looking into this.

**Review by jonkoops — APPROVED** [review]
I am going to approve this PR as all the required checks are passing. I do however think that we should put in future efforts to remove `node_modules` from source control.

**Comment by stianst** [comment]
+1 To remove node_modules, although we need to check with productisation that it doesn't become an issue.

**Comment by stianst** [comment]
I'd like to get this merged before KC16 release, is it ready to go now?

**Comment by abstractj** [comment]
+1 about that @jonkoops, we can create a separate GH issue for that.

**Comment by ssilvert** [comment]
> I'd like to get this merged before KC16 release, is it ready to go now?

@Aboullos is working to get this verified.  Assuming no regressions we will be good to go.  But running the UI tests is always problematic, so it's hard to say when this will be complete.

**Comment by Aboullos** [comment]
It went all green for the admin console tests
https://master-jenkins-csb-keycloak-qe.apps.ocp-c1.prod.psi.redhat.com/job/universal-test-pipeline-server/932

**Comment by jonkoops** [comment]
@stianst I think we can go ahead and merge this PR

**Comment by ssilvert** [comment]
> It went all green for the admin console tests https://master-jenkins-csb-keycloak-qe.apps.ocp-c1.prod.psi.redhat.com/job/universal-test-pipeline-server/932

@Aboullos Are the account console tests green as well?  The dependencies for that are also updated in this PR.

**Comment by Aboullos** [comment]
I'll run another build for the account console tests

**Comment by Aboullos** [comment]
Account console tests went green also
https://master-jenkins-csb-keycloak-qe.apps.ocp-c1.prod.psi.redhat.com/job/universal-test-pipeline-server/937/

**Review by ssilvert — APPROVED** [review]
@abstractj @Aboullos @jonkoops Thanks for getting this done.  I approve.

**Comment by ssilvert** [comment]
On Thu, Nov 11, 2021 at 6:44 AM Stian Thorgersen ***@***.***>
wrote:

> I'd like to get this merged before KC16 release, is it ready to go now?
>
Merged now.

**Pull request merged**
