### PR TITLE
Identity provider plugin for Webex

### PR DESCRIPTION
**Pull request by strollo**
Added a further plugin for Identity providers / Social in order to directly support Webex OAuth2 integration.

Webex allows OAuth2 integrations as documented in the [Official Webex Integrations API](https://developer.webex.com/docs/integrations).

### CODE REVIEW

**Review by stianst — CHANGES_REQUESTED** [review]
Thanks for the PR.

Not sure brokering with Webex is common enough to warrant support it directly. It may be better to do this as an extension that is maintained outside Keycloak main repo.

We could consider adding it if we can add tests for it. See SocialLoginTest. At the moment that is running in an internal pipeline, but it would be worth to run this with GitHub Actions instead.

Is it possible to use generic OIDC provider with Webex?

**Comment by strollo** [comment]
Hi @stianst,
thanks for the answer.

About the Webex adapter, it is not possible to interact via OIDC provider since it only supports OAuth2 protocol and does not implement OIDC. 

Basically, the implementation of the plugin is obtained through a two phases protocol:

Phase1 - via clientID/clientSecret there is an authentication (to https://webexapis.com/v1/authorize) that receives back a token

Phase2 - a further request is done to endpoint `/people/me` (by passing in header the bearer token provided in previous phase) in order to retrieve info about logged in account; so basically email, id, displayName, userName. The retrieved data is so mapped on top of Keycloak internal User model.

I hope it is more clear now.

About SocialLoginTest I should give a look to it if necessary.

Thanks again.

**Comment by stianst** [comment]
> Hi @stianst, thanks for the answer.
> 
> About the Webex adapter, it is not possible to interact via OIDC provider since it only supports OAuth2 protocol and does not implement OIDC.
> 
> Basically, the implementation of the plugin is obtained through a two phases protocol:
> 
> Phase1 - via clientID/clientSecret there is an authentication (to https://webexapis.com/v1/authorize) that receives back a token
> 
> Phase2 - a further request is done to endpoint `/people/me` (by passing in header the bearer token provided in previous phase) in order to retrieve info about logged in account; so basically email, id, displayName, userName. The retrieved data is so mapped on top of Keycloak internal User model.
> 
> I hope it is more clear now.
> 
> About SocialLoginTest I should give a look to it if necessary.
> 
> Thanks again.

We should also probably check what interest there is out there for this one. If there's very little interest I'd suggest you just run it yourself as an extension, or perhaps you can also maintain it as an extension and have it listed on https://www.keycloak.org/extensions.html

**Comment by stianst** [comment]
I'm going to close this PR for now as there doesn't seem to be too much interest in Webex integration with Keycloak.

I would suggest rather than contributing directly to Keycloak that you maintain this as an extension to Keycloak instead, and advertise it to the community through https://www.keycloak.org/extensions.html.

You can take a look at https://github.com/BenjaminFavre/keycloak-apple-social-identity-provider as an example of how this can be bundled up as an extension.

**Comment by strollo** [comment]
Ok @stianst thanks for the support, I'll give a look at extension page.

**Pull request closed without merging**
